### ISSUE TITLE
Can't use the searchbox in explorer

### ISSUE THREAD

**Issue by oxygen-dioxide** [sandboxie-plus/Sandboxie#1002]
**Describe the bug**
Can't use the searchbox in explorer

**To Reproduce**
1. Run explorer .exe inside any sandbox.
2. Click the searchbox. The searchbox doesn't get focused, and I can't input to the searchbox.

**Expected behavior**
the searchbox is focused and I can input to the searchbox.

**Screenshots**

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 20H2
 - Sandboxie Plus 0.8.2
 
**Sandboxie configuration**
If applicable, consider to attach your sandboxie.ini configuration by copying the content at https://gist.github.com and sharing the resulting link here. If you decide to paste the configuration directly here, make sure to use the backticks around strings, like in this working example:

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 

[GlobalSettings]

FileRootPath=E:\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=RpcPortBindings
Template=OfficeLicensing
Template=OfficeClickToRun
Template=7zipShellEx

[UserSettings_050E0144]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[zhaopengme_gitnote]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
BorderColor=#00FFFF,ttl

[alibaba_yuque]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
BorderColor=#00FFFF,ttl

[Microsoft_WingetCreate]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
BorderColor=#00FFFF,ttl

[Microsoft_EdgeDev]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
BorderColor=#00FFFF,ttl

[alibaba_dingtalk]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
BorderColor=#00FFFF,ttl

</details>

**Comment by isaak654** [comment]
This is a very odd bug, I was able to stop it by putting this line on my sandbox:
`FakeAdminRights=y`
