### ISSUE TITLE
New IsCallerSigned verification makes programmatic manipulation of sandboxes harder, and doesn't seem to add security

### ISSUE THREAD

**Issue by benrg** [sandboxie-plus/Sandboxie#1003]
In 0.8.8 / 5.50.8, `SbieDll_UpdateConf` fails with `STATUS_INVALID_SIGNATURE` when I try to call it. As best as I can tell from the source code, calls are now rejected if the calling executable isn't signed by a particular key.

This API is documented at https://sandboxie-plus.com/sandboxie/sbie_dll_api/, suggesting it's meant to be used, and `SbieApi_ReloadConf` is still allowed without signature verification.

As it stands, the change adds no security, because `SbieIni.exe` in the installation folder is signed and calls this API with arbitrary arguments taken from the command line. Even if it restricted the arguments somehow, it would be easy (I imagine) to inject code into the process and make arbitrary protected calls, since only the exe is validated. Deleting `SbieIni.exe` from the installation folder or putting restrictive access permissions on it also wouldn't help, since the attacker could bundle a copy.

I've switched to calling `SbieIni.exe` as a workaround, but it's slow (one spawned process for every line added/changed in the ini file) and flaky (it ignores the return value from `SbieDll_UpdateConf`, so you can't tell if it failed).

It would be okay for my use case if `SbieDll_UpdateConf` could only be called by elevated administrators. They could modify `%WINDIR%\Sandboxie.ini` directly if they wanted to, so there's no reason not to provide a safer API. But in that case `SbieIni.exe` should also require elevation, and of course this has the potential to cause more breakage.

**Comment by DavidXanatos** [comment]
Right that is not ideal and there is already a setting to restrict access to the Config for administrators only, I'll probably remove this check again in an upcoming build.

**Comment by DavidXanatos** [comment]
the new build is out which removes this restriction again, have fun ;)
