### ISSUE TITLE
Windows 10 Pro Build 19043 Sees Trojan In Executable Regardless Of Download Method

### ISSUE THREAD

**Issue by akanderson001** [sandboxie-plus/Sandboxie#1004]
Regardless of which browser or which PC I use Windows 10 Pro is seeing "Sandboxie-Plus-x64-v0.8.8.exe" as a trojan.  I select "keep file" in Edge but it won't save it and in Brave it appears to complete the download but during the file scan procedure it finds the same virus which is listed as **Trojan:Win32/Spursint.F!cl** and then deletes it.

I've installed every revision of Sandboxie Plus prior to this and have never had this occur.

**Comment by isaak654** [comment]
I can't reproduce your issue, see also #999.

My suggestion is to report a false positive to Microsoft:
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Vzz1c** [comment]
![image](https://user-images.githubusercontent.com/49944812/125591484-49f5c86a-022a-43ab-b5d2-fb8744592970.png)

Antivirus software and browsers both detect viruses. If it is a certificate problem, please replace it. Thank you

**Comment by Vzz1c** [comment]
![image](https://user-images.githubusercontent.com/49944812/125592128-e08a3daa-0014-4d87-9cb9-1620b77e0479.png)

Antivirus software and browsers both detect viruses. If it is a certificate problem, please replace it. Thank you

**Comment by Vzz1c** [comment]
If you deliberately avoid this question, I think this is the truth

**Comment by isaak654** [comment]
> 
> 
> If you deliberately avoid this question, I think this is the truth

@Vzz1c
For your issue, see #847.

We already tried to report the URL as false positive to Google... do you know how to receive an official reply from them?
We're listening.

**Comment by Vzz1c** [comment]
I have visited so many github projects and never like this. At first, I even thought I had entered a fake github site.

**Comment by isaak654** [comment]
> 
> 
> I have visited so many github projects and never like this. At first, I even thought I had entered a fake github site.

Then please tell us how we can improve... we're already filling forms for these detection issues.

**Comment by silvestron** [comment]
The antiviruses are getting more and more aggressive though, I couldn't even whitelist the installer, I had to disable Defender.

What causes this? Is it just the name "Sandboxie"? If that's the case maybe we could change the name at this point.

**Comment by akanderson001** [comment]
I don't know what was done but I just reattempted the download through Brave and this time there was no flag by Windows Defender.  If you made a change in the packaging to correct this thank you, if it got whitelisted since I posted this also thank you.

**Comment by Katzenwerfer** [comment]
> The antiviruses are getting more and more aggressive though, I couldn't even whitelist the installer, I had to disable Defender.
> 
> What causes this? Is it just the name "Sandboxie"? If that's the case maybe we could change the name at this point.

I guess it could relate to some files that Sandboxie uses to work (similar case to RDPWrap) or just antivirus detection being shit.
I've been also getting warning in other repos that are pretty much safe, so I would say it's just some stupid thing on the AV's side

**Comment by isaak654** [comment]
Yesterday I discovered a form that sends an email to the _Google Search Central Support Team_. 
We'll keep you informed in the following post: https://github.com/sandboxie-plus/Sandboxie/issues/847#issuecomment-860057865.
