### ISSUE TITLE
Updater claims that there's no version available even though there is one

### ISSUE THREAD

**Issue by zingmars** [sandboxie-plus/Sandboxie#1006]
**Describe the bug**
When using the "Check for updates" function Sandboxie will say that there is no new version available, even when there is one.

**To Reproduce**
1. Go to GitHub and see that there's a new version
2. Open Sandboxie
3. Click on Help in the menu bar
4. Click on "Check for updates"
5. See that the update is not offered

**Expected behavior**
Sandboxie should offer the latest version to the user

**Screenshots**
![image](https://user-images.githubusercontent.com/917126/125740348-b96b1bae-bb36-473a-a2ca-d7b998d98b84.png)

**System details and installed software (please provide the following information):**
 - Windows version: Windows 10 Pro 21H1
 - Sandboxie version: Sandboxie Plus v0.8.2
 - When it was introduced: No idea, but it hasn't ever worked for me since I've started using Sandboxie (at least a year+ now) 
 - Security software: Windows Defender

**Comment by DavidXanatos** [comment]
This is normal and intended, as I only update the updater infos on the server once I see that a build runs reliably,
please check in a week or so than it should say there is 0.8.8 available
