### ISSUE TITLE
Couldn't install Servo in Sandboxie 5.50.8/Sandboxie-Plus v0.8.8

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#1007]
**Describe the bug**
Couldn't install Servo in Sandboxie 5.50.8/Sandboxie-Plus v0.8.8: 0x8007006e - system could not open specified device. 

**To Reproduce**
1. Launch Servo installer in Sandboxie
2. Click on 'Install'
3. Wait a moment

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (Windows 10 Enterprise LTSC 2019).
 - What is your current Sandboxie edition and version? Sandboxie 5.50.8/Sandboxie-Plus v0.8.8
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**Comment by 0x391F** [comment]
Get Servo
https://download.servo.org/nightly/windows-msvc/servo-latest.exe

**Comment by 0x391F** [comment]
Seems all msi installer couldn't work properly in Sandboxie.

**Comment by DavidXanatos** [comment]
in the 0.8.8 was a bug introduced, use MsiInstallerExemptions=y to fix it

**Comment by Pomax** [comment]
Can you explain what "use MsiInstallerExemptions=y" means?  (e.g. where do we do that, and what does it effect?)

**Comment by DavidXanatos** [comment]
It allows the MSI installer to run with a system token,

btw there is a 0.8.9 with the fix out as of today

**Comment by Pomax** [comment]
nice!

Although for completion, I meant that I didn't know what "use MsiInstallerExemptions=y" meant, but thankfully isaak explained that it meant going to the options menu, then editing the `ini` file and putting that line in, then reloading the settings.
