### ISSUE TITLE
Failed to Install Brave inside a sandbox with FakeAdminRights

### ISSUE THREAD

**Issue by NightmareWyrm** [sandboxie-plus/Sandboxie#1008]
**Describe the bug**
I have downloaded and tried to install Brave Browser.
I run it under a hardened sandbox with FakeAdminRights.
It Failed at installation when it had to decompress an archive.
Similar behavior happened with Vilvadi Installer and another application.
All of them failed, at installation when they have to decompress an archive. 

**To Reproduce**
1. Right Click BraveBrowserSetup.exe
2. Run Sandboxed
3. Select the Test_Installer Profile.
4. The installer will run successfully.
5. The downloading will also be successful.
6.  At Installation the error will occur.
7. Error Message: "The installer failed to uncompress archive. Please download Brave again."

**Screenshot**
![Error](https://user-images.githubusercontent.com/87491053/125828036-3c2a902e-882d-4e27-a0af-9d3c12a4fe64.PNG)

**Expected behavior**
Brave to install successfully.

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 21H1
 - Sandboxie Plus 0.8.8
 - Avast Antivirus Free.

**Sandboxie configuration**

<details>
 
<summary>configuration.ini</summary>
 
[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=Avast_Antivirus
Template=WindowsRasMan
Template=WindowsLive
Template=SynapticsTouchPad
Template=RpcPortBindings
Template=OfficeLicensing
Template=7zipShellEx
TemplateReject=Kaspersky

[UserSettings_0C940221]

SbieCtrl_EnableAutoStart=y
SbieCtrl_AutoStartAgent=SandMan.exe
BoxDisplayOrder=Edge,Vlc,Test(Test_Installers,Test_Files),SumatraPDF

[DefaultBox]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[UserSettings_0C02020A]

SbieCtrl_UserName=admin
SbieCtrl_NextUpdateCheck=1626266996
SbieCtrl_WindowCoords=200,150,1237,632
SbieCtrl_ActiveView=40021
SbieCtrl_AutoStartAgent=SandMan.exe

[Test_Installers]

Enabled=y
AutoRecover=n
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00ffff,ttl,6
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=9
DropAdminRights=y
ClosePrintSpooler=y
BoxNameTitle=n
FakeAdminRights=y
CopyLimitKb=81920
ClosedFilePath=C:\Users\Personal\Google Drive

</details>

**Comment by DavidXanatos** [comment]
could you please test the 0.9.3 build and report back? I know vivaldi is still not fine but it does nto longer complain about unability to uncomplress, also it a rework of the file close handling shoudl fix some issues of this sort.
