### ISSUE TITLE
gradle "java.io.IOException: Unable to establish loopback connection"

### ISSUE THREAD

**Issue by k7xzc1krh20nkrm6jfv** [sandboxie-plus/Sandboxie#1009]
**Describe the bug**

```
$ ./gradlew applyPatches
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Unable to establish loopback connection

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**To Reproduce**
1. Install oracle java 16 and git
2. Open Git Bash in a sandbox
3. `$ git clone https://github.com/PaperMC/Paper.git`
4. `$ cd Paper`
5. `$  ./gradlew applyPatches`

**Expected behavior**
Works fine

**Screenshots**

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2). 21H1
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2). 0.8.2 and 0.8.8
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**Additional context**

**Sandboxie configuration**
If applicable, consider to attach your sandboxie.ini configuration by copying the content at https://gist.github.com and sharing the resulting link here. If you decide to paste the configuration directly here, make sure to use the backticks around strings, like in this working example:

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]

.....

[UserSettings_175D0429]

.....

[DefaultBox]

.....

```

</details>

**Comment by tsao-chi** [comment]
Minecraft 1.17 also has similar problem

**Comment by worx7kbj** [comment]
> Minecraft 1.17 also has similar problem

https://github.com/sandboxie-plus/Sandboxie/issues/1521

**Comment by DavidXanatos** [comment]
please try adding 
```
OpenFilePath=*\Temp\socket_*
```
to the sandbox and let me know if it fixed the issue
