### ISSUE TITLE
Issue while playing a game

### ISSUE THREAD

**Issue by Beludia** [sandboxie-plus/Sandboxie#101]
Hello, sorry if I am not in the good place, new to github, I use sandboxie (and now plus) since a while for a mmorpg (Life Is Feudal) and there is a problem while opening a container in game, it take a long time to opening it (like 2-3 minutes) and if the containers is really full it can even crash the game.
Of course that dont happen without sandboxie.

I tried all kind of settings for sandboxie but never found a solution, if any of you have an idea.

dont know what else I can say to help, so if you have any question please ask, thanks.

**Comment by DavidXanatos** [comment]
what game, what do you mean with container?

**Comment by Beludia** [comment]
In my case its Life Is Feudal MMORPG, container as everything that store item, chest, warehouse, ect ...

**Comment by NewKidOnTheBlock** [comment]
@Beludia: Could you try again with a more recent version of Sandboxie?
Does it still happen?

**Comment by Beludia** [comment]
Hello, sadly that MMORPG shut down this month, but it worked fine/better after some updates.

**Comment by NewKidOnTheBlock** [comment]
Well, that game is officially dead since the 18th of January 2021:
https://store.steampowered.com/news/app/700030/view/2901972025485149196

It can't be downloaded any more on Steam.
-> I think this can be closed then.
