### ISSUE TITLE
Add the option to prevent specific programs from running for specific users

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#1010]
**Is your feature request related to a problem? Please describe.**
As it is now, you can only block programs and folders from running globally. I wish it could be applied on a user basis.

Yes, I know this is doable by setting up a sandbox with "block everything from running" and then adding forced folders. Still annoying though.

**Describe the solution you'd like**
Basically, I want a user option here:
![grafik](https://user-images.githubusercontent.com/12563436/125940224-39e819c2-eedf-41f3-a0ae-97de19fc6da8.png)

**Comment by diieg707** [comment]
that's a good request

**Comment by DavidXanatos** [comment]
I'm not exactly sure what you want, 
so you want to be able to specify for different windows users what is allowed to run and what is not?

**Comment by diieg707** [comment]
> I'm not exactly sure what you want,
> so you want to be able to specify for different windows users what is allowed to run and what is not?

I guess he meant to add option to prevent specific programs from running for specific sandboxes

**Comment by diieg707** [comment]
> > I'm not exactly sure what you want,
> > so you want to be able to specify for different windows users what is allowed to run and what is not?
> 
> I guess he meant to add option to prevent specific programs from running for specific sandboxes

If that's the case it's a request similar to #1070

**Comment by Dyras** [comment]
@DavidXanatos I want to block certain programs from running at all, for certain users on the computer.

**Comment by DavidXanatos** [comment]
Specific programs not running for specific users sounds a lot like a business use case.
I can add that but it would be only enabled on copies with a valid business supporter certificate + I would expect the requesting party to become a patreon on one of the top two tiers. deal?

**Comment by Dyras** [comment]
Sounds better than nothing to me. If nothing else, it will make you more money. So I say DEAL!

**Comment by DavidXanatos** [comment]
Cool, than we can continue with the design details on patreon.

**Comment by Dyras** [comment]
Ah, I see. Sorry I just woke up and I didn't see the "the requesting party to become a patreon on one of the top two tiers"
Can't really sign up right now. 50 bucks a month is a lot for me, as I'm still a student. 😅 If you don't want to add this until then, I understand.

When and if you feel like adding this, I was thinking something like this
![grafik](https://user-images.githubusercontent.com/12563436/152306008-4b070cbd-a844-4d40-9c37-e1d16e907766.png)

**Comment by DavidXanatos** [comment]
since you add so many drives, the goal is to block execution from usb sticks?

**Comment by Dyras** [comment]
That was the original goal, yes.

The above suggestion though, was mostly an idea that just came to me. Maybe you want to block firefox.exe on your grandpa's account to force him to use Edge or vice versa?

**Comment by Dyras** [comment]
This can be done with breakout programs now, I think.
