### ISSUE TITLE
[Ryzen 9 5900x] Sandboxie plus v0.8.8 Chrome error

### ISSUE THREAD

**Issue by CPYY** [sandboxie-plus/Sandboxie#1012]
**WerFault.exe (19120): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1**

Works fine with Edge latest version no errors.

**Comment by DavidXanatos** [comment]
are you using an 11th gen intel or AMD 5900X cpu on a windows 10 2004 or later
if yo than this sbiedll may fix the issue: https://xanasoft.com/Downloads/SbieDll_5.50.8b.zip
pelase try it and report back

**Comment by CPYY** [comment]
> are you using an 11th gen intel or AMD 5900X cpu on a windows 10 2004 or later
> if yo than this sbiedll may fix the issue: https://xanasoft.com/Downloads/SbieDll_5.50.8b.zip
> pelase try it and report back

Correct im using the latest windows 10 21H1 with a Ryzen 9 5900x i replaced the files and restarted Sandboxie and still got the same error.
[https://imgur.com/4WMkQDP](url)

**Comment by isaak654** [comment]
@CPYY Just in case and if David agrees, would you be available to provide remote access for fixing this issue?

**Comment by isaak654** [comment]
>  update on this issue, I had the opportunity to order some new hardware for my lab and ofcause picked a 5600X ryzen so with that I should be able to reproduce the issue when it comes and no otehr problems manifest. 

Original post: [here](https://www.wilderssecurity.com/threads/intel-11-gen-and-amd-5900x-compatybility-issue.438321/#post-3023598)

**Comment by isaak654** [comment]
#1067

**Comment by DavidXanatos** [comment]
workaround

chrome.reg
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\chrome.exe]
"MitigationOptions"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,20,00,00,\
  00,00,00,00,00,00
"MitigationAuditOptions"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00
"EAFModules"=""

```

for other apps replace chrome.exe with the name of the otehr app

**Comment by isaak654** [comment]
The workaround removes the stack protection also outside of the sandbox, so it would be advisable to revert the workaround before installing the next build.
