### ISSUE TITLE
Document if the portable version can overwrite itself

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#1013]
**Is your feature request related to a problem? Please describe.**
When a new release comes out, it's unclear if the option "Extract all files to a directory for portable use" means a fresh folder or also an existing folder that has an older release of the portable version.

**Describe the solution you'd like**
The menu option (plus README.md) should indicate what will happen if the folder already exists.
Hopefully "you can use an existing folder, older files will be replaced".
If not, then it should refuse to extract if the folder already has files.

**Additional context**
Even before adding that description, what shall actually happen if the folder already exists?

**Comment by isaak654** [comment]
I don't see the reason to do this, unless you can provide me a compelling example already present in another software.

**Comment by lwcorp** [comment]
> I don't see the reason to do this, unless you can provide me a compelling example already present in another software.

Portable versions are usually ZIP files, so you just know when they have less files than previous versions.
It's always a bit confusing when a portable version uses a self extractable EXE file, so it'll be good to know what it does.

**Comment by mpheath** [comment]
If you do not trust the installer with upgrading, put it into a empty directory. Run it, select portable install and let it extract the files to the default folder named `Sandboxie-Plus` in that directory. Once finished, `zip` up the folder and optionally remove the `Sandboxie-Plus` folder. Now you will have your ZIP file.

If you want to learn what the installer does, then read on.

From the install script:

```iss
[Files]
; Both portable and install.
Source: ".\Release\{#MyAppSrc}\*"; DestDir: "{app}"; MinVersion: 0.0,5.0; Flags: recursesubdirs ignoreversion; Excludes: "*.pdb";
; Only if portable.
Source: ".\Sandboxie.ini"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist; Check: IsPortable
Source: ".\Sandboxie-Plus.ini"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist; Check: IsPortable
```

Flag *ignoreversion* is set so it just overwrites all files. The exception is *Sandboxie.ini* and *Sandboxie-Plus.ini* for portable installs, as the flag onlyifdoesntexist is set for those files to prevent loss of settings.

If you want to know what the installer does, then try installing with arguments. If the installer is named `setup.exe`, then at a CMD prompt type `setup /?` to view a msgbox with arguments that you can use.

An excerpt:

>/LOG
>Causes Setup to create a log file in the user's TEMP directory.
>/LOG="filename"
>Same as /LOG, except it allows you to specify a fixed path/filename to use for the log file.

At a CMD prompt, type `setup /log` and perform the portable install. After the install, look in the TEMP folder for a txt file starting with Setup and the current date in the filename. Viewing the log will inform you of what the installer has done. Optionally, the `/log` argument supports setting a path to the log file, so you do not need to look in the TEMP directory.

In the log file, you may see this near the end:

>2021-08-09 23:03:41.484   -- File entry --
>2021-08-09 23:03:41.484   Dest filename: C:\Users\Michael\Desktop\test\Sandboxie-Plus\Sandboxie.ini
>2021-08-09 23:03:41.484   Time stamp of our file: 2021-07-26 01:17:12.000
>2021-08-09 23:03:41.484   Dest file exists.
>2021-08-09 23:03:41.484   Skipping due to "onlyifdoesntexist" flag.
>2021-08-09 23:03:41.484   -- File entry --
>2021-08-09 23:03:41.484   Dest filename: C:\Users\Michael\Desktop\test\Sandboxie-Plus\Sandboxie-Plus.ini
>2021-08-09 23:03:41.484   Time stamp of our file: 2021-07-26 01:17:12.000
>2021-08-09 23:03:41.484   Dest file exists.
>2021-08-09 23:03:41.484   Skipping due to "onlyifdoesntexist" flag.
>2021-08-09 23:03:41.484   Installation process succeeded.

This is from an upgrade install so the installer found the ini files and skipped overwriting them. All other files in the log show that they were all overwritten.

If you want to avoid the UAC prompt and clicking through the Wizard pages, then try this command:

```
setup /silent /portable=1 /currentuser /log=setup.txt
```

The relative path to the log should be OK as the setup will run with current user permissions in this case. You could keep that command in a batch file or a shortcut so it can be reused again with little effort.

**Comment by lwcorp** [comment]
So looks like no deleting of obsolete files, but I guess maybe there were no obsolete files.

**Comment by isaak654** [comment]
> > I don't see the reason to do this, unless you can provide me a compelling example already present in another software.
> 
> Portable versions are usually ZIP files, so you just know when they have less files than previous versions. It's always a bit confusing when a portable version uses a self extractable EXE file, so it'll be good to know what it does.

In order to consider your idea, I would need to see a visual example from another software or at least a mockup (design concept) produced by you with the modification you would like to be implemented.
