### ISSUE TITLE
Allow exceptions when hiding directories

### ISSUE THREAD

**Issue by dingwen07** [sandboxie-plus/Sandboxie#1019]
**Is your feature request related to a problem? Please describe.**
I hope to allow exceptions when setting up hidden directories. For example, I want applications in the sandbox to to directly access `C:\Users\some_folder`, but I don't want them to access any other files under `C:\Users`.

**Describe the solution you'd like**
At present, if I add `WriteFilePath=C:\Users` to the configuration (which is the same as hide `C:\Users`) and `OpenPipePath=C:\Users\some_folder` at the same time, the applications in the sandbox will not be able to access the files in `C:\Users\some_folder`. I hope that under this configuration, the application will be able to access these files.

**Comment by DavidXanatos** [comment]
This is currently not possible mit will be possible in 0.9.5 or to the latest 1.0.0 if everything goes tom plans,
a feature that will allow this is long time in planning: https://github.com/sandboxie-plus/Sandboxie/issues/890
