### ISSUE TITLE
Wording suggestion #2

### ISSUE THREAD

**Issue by Gravityzwell** [sandboxie-plus/Sandboxie#102]
You might recall I suggested a change to the donation wording. Looks much better now!

One last thing, for multiple reasons, I suggest changing:

_The SbieDrv.sys driver must be signed, and since the appropriate certificates are prohibitively expensive, I head to use a leaked code signing certificate I found laying around the Internets. This means some anti malware applications wrongfully flag it as potentially dangerous or a virus._

To:
Some anti malware applications might wrongfully flag Sandboxie Plus.

**Comment by DavidXanatos** [comment]
Do you mean to replace all  2 sentence long explanation with the the suggested short text? or only a part of it?

**Comment by Gravityzwell** [comment]
I suggest replacing all of it. The replacement is intentionally brief. The first version might be more informative, but I'd be concerned it could be trouble. It's basically admitting things, and giving potentially unfriendly types something to work with, and right up front. As the saying goes, in some cases, the less said the better ;)
