### ISSUE TITLE
add option to delete files on windows shutdown

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1026]
add option to delete files on windows shutdown

**Comment by diieg707** [comment]
@isaak654 what you think about this request?

**Comment by DavidXanatos** [comment]
That I never shutdown my windows LOL, always just hibernate.

And that it wil make the shutdown take longer, what is not good.

how about instead adding a autostart entry to clear selected boxes on boot?

**Comment by diieg707** [comment]
> That I never shutdown my windows LOL, always just hibernate.
> 
> And that it wil make the shutdown take longer, what is not good.
> 
> how about instead adding a autostart entry to clear selected boxes on boot?

I don't think your comment is accurate as it depends on the amount of files that will be deleted, and i think that won't affect shutdown time too much.

Your idea to delete on boot is not very secure as people might able to recover files using live OS

**Comment by DavidXanatos** [comment]
if oyu are woried about recoverign files this can be also done after files are deleted as thay are not secur erased

**Comment by diieg707** [comment]
> if oyu are woried about recoverign files this can be also done after files are deleted as thay are not secur erased

Its less worse to delete files on shutdown than letting they intact on disc. but sandboxie has option to further erase  to prevent recovering, but that goes back to your argument about shutdown taking longer.

I don't if doable but I suggest as well a progress dialog on shut down to track progress of files being deleted

**Comment by DavidXanatos** [comment]
One of the soon to come builds of sandboxie will have built in ramdisk support and box image encryption.
As we are not going to add a delete on shutdown due to the unwanted delay and lack of guarantees that windows wont kill the program in mid deletion I'll close this request.
please use a ram disk resident box for sensitive files as soon as its available
