### ISSUE TITLE
MouseOver highlight of sandbox list in the tray context menu

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#1030]
**Is your feature request related to a problem? Please describe.**
Thanks for implementing a comprehensive tray context menu. A slight imperfection at the moment is that the boxes in the sandbox list are not highlighted upon MouseOver while the rest of the menu entries are.

**Describe the solution you'd like**
It would be nice to have MouseOver highlight on the sandbox list.

**Comment by DavidXanatos** [comment]
I think this is by far more work than its worth

**Comment by superkryodev** [comment]
> I think this is by far more work than its worth

Ah, I naively thought it would no more complicated than the mouseover already implemented.

In term of justification, one might sometime click on an unintended box without realising and then go on do things on the sub-menus (which can obscure the list of boxes), such as "delete content"...

**Comment by DavidXanatos** [comment]
The normal highlighting is a function of Qt's menu implementation
while the box list is a QTreeWidget, thay behave differently

**Comment by superkryodev** [comment]
> The normal highlighting is a function of Qt's menu implementation
> while the box list is a QTreeWidget, thay behave differently

Understood, feel free to close

**Comment by isaak654** [comment]
If this could help: https://forum.qt.io/topic/57788/solved-qtreewidget-setstylesheet-problem/8

**Comment by isaak654** [comment]
If it helps: https://forum.qt.io/topic/57788/solved-qtreewidget-setstylesheet-problem/8

**Comment by superkryodev** [comment]
> If it helps: https://forum.qt.io/topic/57788/solved-qtreewidget-setstylesheet-problem/8

I think the problem is that the sandboxes in Sandman are not store as a simple tree used for QTreeView, instead they belong to a customised  QAbstractItemModel which is more sophisticated. See here: http://www.hardcoded.net/articles/using_qtreeview_with_qabstractitemmodel
