### ISSUE TITLE
[plus 0.8.8] window to recover files doesn't appear after click "delete content" 

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1033]
plus 0.8.8
to reproduce:
open chrome sandboxied and save something on download folder
then click delete contents, window to recover contents doesn't appear

(no problem in classic version)

my os: w10 1909 build 18363.1646

**Comment by DavidXanatos** [comment]
for me this works fine, ofcause you first need to enable this functionality:
![image](https://user-images.githubusercontent.com/3890945/129348637-61c19028-f138-4f4c-b348-ee6717a2ec93.png)

In plus this is not on by default unlike in classic where you can't even turn that annoying feature off

**Comment by diieg707** [comment]
good

**Comment by DavidXanatos** [comment]
So now this works for you as you wanted?

**Comment by diieg707** [comment]
> So now this works for you as you wanted?

I didn't know there was this setting

**Comment by diieg707** [comment]
But honestly I think recovery windows should open by default when emptying, there shouldn't even have this option, but that's ok

**Comment by diieg707** [comment]
For me I think you could remove this option and let recovery open by default, or leave it already checked on installation
