### ISSUE TITLE
Error 1067 or No error or response

### ISSUE THREAD

**Issue by 0m3rta13** [sandboxie-plus/Sandboxie#104]
Been trying to get this running for I'm not sure how long now. Both the 0.3/v5.42 & the recent 0.3.5/v5.42.1. Same result for both. 

Everything installs fine. Driver (or every folder with sandboxie in in) is whitelisted with AV (with exceptions too) the driver runs. The service starts but still it does not work. 

If using regular SbieCtrl, if I try and run anything at all there's just no response. Not even an error. 
If I'm running Sandman anytime I try and run something sandboxed I just get Error 1067

Tried in both installed & Portable mode. Same thing. 
Tried uninstalling/reinstalling the service and driver manually inside sandman with varying combinations of order etc. 
Even installed/ran it in Windows sandbox to see if it was my environment somehow as that is clean and still, same results.

Sometimes if I terminate or end within sandman, when I try to reinstall the driver or service it locks up and I have to end the process manually. This doesn't always happen. 

I am on:
Windows 10 Pro
Insider (Fast Ring)
Build: 20170.rs_prerelease.200710-1419

I have been trying to get it going on and off for over a money I'd say. Through a couple of windows updates (1-2 a week on fast ring) and always the same result. 

Any suggestions would be great as I really need and want to get this working. 

Thanks a lot! 
Do appreciate your work!

**Comment by DavidXanatos** [comment]
Is there a version of Sbie or SbiePlus that works for you?

**Comment by 0m3rta13** [comment]
> Is there a version of Sbie or SbiePlus that works for you?

Good point. I've only tried the last 2 (maybe 3) releases. 

Downloading all of them right now and will see if one works. 

Will edit this post once I've tried all of them in a clean env

**Comment by 0m3rta13** [comment]
After some more messing around I get a different error when trying SandboxiePlus in Portable mode.
When first launching i Get the usual prompt about the driver and it then mentions again that because of Portable mode it must install the service etc. After accepting that it frezes up with the following error for kmdutil
![kmdutil (2)](https://user-images.githubusercontent.com/39747256/88186364-fa687b00-cc2c-11ea-8ed8-e59d00380226.png)

it freezes up requiring me to end task and freezes up whenever i try to open it again so i have to remove every trace and start over again.

Thank the Pc Gods for the convenience of things like Revo Pro and its tracing function

**Comment by NewKidOnTheBlock** [comment]
I used to install the new version over the old one and that always worked.
What Sandboxie Plus doesn't tell you, is that you need to uninstall (and reboot) the old version - especially the driver - first, before you can install the new one.

Did you try that?

**Comment by 0m3rta13** [comment]
> I used to install the new version over the old one and it always worked. Up to 5.33, that is.
> What Sandboxie Plus doesn't tell you, is that you need to uninstall the old version first. Make sure to reboot, to really get rid of the old driver. Only after that you can install the new one.
> 
> Did you try that?

Many many many times yes. lol

All the above errors were from a completely clean build i have an image of that i loaded up clean after each attempt.
Also tried within windows sandbox env which is clean on every startup of it.
So each install was basically done on a machine that had never seen sandboxie before

**Comment by 0m3rta13** [comment]
Started working on latest insider

Insider Fast Ring
Version: 2004
OS Build: 20197.1000
