### ISSUE TITLE
Release v0.8.9 / 5.50.9 Entry Point not found Error

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#1040]
**Describe the bug**
.exe - Entry point not found
 The procedure entry point NtFilterTokenEx could not be located in the dynamic link library ntdll.dll
 
 Classic installer fails to install due to this error

**To Reproduce**
1. Try to start sandboxie
2. See error

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2). Windows 7 Ultimate 64-bit SP1 x64
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2). Release v0.8.9 / 5.50.9
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. Release v0.8.9 / 5.50.9
 
 0.8.8 / 5.50.8 works fine

**Comment by DavidXanatos** [comment]
mmh... I see NtFilterTokenEx is not available in windows 7 I'll add a fix for that loading that address on runtime instead of staticly linking

**Comment by DavidXanatos** [comment]
0.8.9b is out
