### ISSUE TITLE
Сreating a shortcut. *.chm hides exe file 

### ISSUE THREAD

**Issue by vitidev** [sandboxie-plus/Sandboxie#1041]
**Describe the bug**
If in the same folder with `appname.exe` there is a file with the name `appname.chm` then `appname.exe` does not appear in the list when `Create Shorcut` - `All Files And Folders` - `Drive C` ... Have to rename *.chm file

**To Reproduce**
1. In folder with `exe` file create empty `chm` file with same name. For example, `foo.exe` -> `foo.chm`. The content does not matter, it can be files with zero size
2. Menu  `Create Shorcut` - `All Files And Folders` - `Drive..` - `Folder with exe`
3. Only `foo.chm` will be visible in the menu 
4. If you delete or rename `foo.chm`, `foo.exe` will appear again 

**System details and installed software:**
 - Windows 10 x64 Pro 2004.
 - Sandboxie Plus 0.8.9
 - Kaspersky Internet Security 21

**Comment by Coverlin** [comment]
reproduced in 0.8.8

run from start menu will not show exe if chm with the same filename is present... also tested with .bat 
bat > chm > exe
