### ISSUE TITLE
[Question + Documentation Request] Hidden vs Closed (File/Folder Path in Resource Access)

### ISSUE THREAD

**Issue by supracoralline** [sandboxie-plus/Sandboxie#1043]
- What is the Hidden access setting for? 
- What are the benefits of using it instead of Closed access? 

Does it just **hides** the contents of the folder but allows read/write?

**Comment by isaak654** [comment]
See the following sandbox settings:
https://sandboxie-plus.github.io/sandboxie-docs/Content/WriteFilePath.html
https://sandboxie-plus.github.io/sandboxie-docs/Content/ClosedFilePath.html

The name WriteFilePath can be quite misleading as it's not really write only... I don't know why the previous devs didn't call it HiddenFilePath as parameter in the Sandboxie.ini configuration file.

**Comment by supracoralline** [comment]
I see, so it is basically somewhat of a better "ClosedFilePath" setting. Thanks for the info, they really should change that WriteFilePath to HiddenFilePath or something, or at least modify the documentation for it. Kinda confusing but I get it now, thanks.

**Comment by isaak654** [comment]
> or at least modify the documentation for it.

@supracoralline 
A good thing is that at least the GitHub repository with the documentation I linked before can be easily updated from any GitHub member with a pull request... if anyone wants, I could help there during my spare time.
