### ISSUE TITLE
Sandboxie-Classic-x86-v5.50.9 fails installation on Windows 7 (32-bit)

### ISSUE THREAD

**Issue by TeslaMagic** [sandboxie-plus/Sandboxie#1044]
Not sure if this is related to the Windows 7 crash issue #1040, but the installation starts and stops stating Installation Aborted - Setup was not completed successfully.

![SandboxieInstallError](https://user-images.githubusercontent.com/16181192/127224646-e9b2e0de-2630-4e84-b306-71369fb09394.png)

**Comment by isaak654** [comment]
Well, he said that Classic installer fails to install so it's the same issue. Please revert to the previous version.

**Comment by TeslaMagic** [comment]
> Well, he said that Classic installer fails to install so it's the same issue. Please revert to the previous version.

Ok, thank you. I did not get the error he did and his version was 64-bit.

**Comment by DavidXanatos** [comment]
0.8.9b is out
