### ISSUE TITLE
[Question] How do I enable a sandboxed browser to read the current desktop wallpaper?

### ISSUE THREAD

**Issue by Dark-Magician** [sandboxie-plus/Sandboxie#1048]
Vivaldi has a feature that enables it to use the current desktop wallpaper on the start page. This option disappears from settings when Vivaldi is running in a sandbox.

I added `%local appdata%\Microsoft\Windows\Themes` to file access and `Computer\HKEY_CURRENT_USER\Control Panel\Desktop` to registry access to no avail, although I am unsure whether I did the latter correctly. I cannot think of anything else.

![Outside sandbox](https://user-images.githubusercontent.com/19816749/127369648-aff01a9c-8850-4376-9eaa-d61084357ef5.png)

![Sandboxed](https://user-images.githubusercontent.com/19816749/127369679-b1ce4ac4-d597-4452-bfb8-8510968c0eb1.png)

**Comment by supracoralline** [comment]
Windows stores the current Desktop wallpaper at `%AppData%\Microsoft\Windows\Themes\CachedFiles` (roaming appdata).

You can also just use a custom image, as seen on the screenshots you provided, if it still doesn't show up.

**Comment by Dark-Magician** [comment]
Unfortunately, that did not work. The option to use the desktop wallpaper was still missing. Currently, I use a custom image, but I like the consistency between the browser start page and desktop background, which I occasionally change, so I want to find a solution.

**Comment by offhub** [comment]
The "Use Desktop Image" button can be enabled in Vivaldi (7.0.3495.27) with the following setting

```ini
OpenClsid=vivaldi.exe,{C2CF3110-460E-4FC1-B9D0-8A1C0C9CC4BD}
```
