### ISSUE TITLE
NSIS error

### ISSUE THREAD

**Issue by BrightYC** [sandboxie-plus/Sandboxie#105]
Hi. I am trying to compile sandbox and nsis is showing error: 

File: "..\\Bin\\\Win32\SbieRelease\SbieDrv.sys.rc4" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "C:\Users\BrightYC\Git\Sandboxie\Sandboxie\install\SandboxieVS.nsi" on line 973 -- aborting creation process
(in https://github.com/sandboxie/sandboxie SbieDrv.sys.rc4 does not exists)

I'm dumb, i have no idea what could be wrong. I trying compile this --> https://github.com/BrightYC/Sandboxie-1/tree/master/Sandboxie. This fork is just renamed SbieDll to AlabaiDll. 
Anyway, when i'm tryed to compile sandboxie from https://github.com/sandboxie/sandboxie - Sandboxie control got blinky and says me about SbieDrv =(

**Comment by DavidXanatos** [comment]
you get the rc4 files by calling

%~dp0\SandboxiePlus\x64\Debug\SandMan.exe -rc4 %~dp0\Sandboxie\Bin\x64\SbieRelease\SbieDrv.sys
%~dp0\SandboxiePlus\x64\Debug\SandMan.exe -rc4 %~dp0\Sandboxie\Bin\Win32\SbieRelease\SbieDrv.sys
