### ISSUE TITLE
[Question] If I installed a program and I no longer need it, do it need to uninstall it or do I just delete the content of the sandbox??

### ISSUE THREAD

**Issue by EfraMP** [sandboxie-plus/Sandboxie#1056]
Basically what the tittle says.

I installed a program thatI didn't trust, but it seems to be legit and it works well. Nevertheless, I don't longer need to use it so I don't know if I must first uninstall it or do I just need to delete the content of the sandbox.

My intuition tells me that I just need to delete the content. Is that right? 

Thanks for your help :)

**Comment by DavidXanatos** [comment]
yes just delete the sandbox

**Comment by isaak654** [comment]
The content of the sandbox or the sandbox itself.

See also #807.
