### ISSUE TITLE
Proposition to add Sandboxie to winget repo

### ISSUE THREAD

**Issue by rpr13** [sandboxie-plus/Sandboxie#106]
Hi.

Can you add Sandboxie to winget repo.

Here is proposed yaml, feel free to use it as base.
```
Id: SandboxiePlus.Sandboxie
Version: 5.42.1
Name: Sandboxie
Publisher: SandboxiePlus
License: GNU General Public License v3.0
LicenseUrl: https://github.com/sandboxie-plus/Sandboxie/blob/master/LICENSE
AppMoniker: sandboxie
Tags: sandbox
Description:
  Sandboxie is sandbox-based isolation software for 32- and 64-bit Windows NT-based operating systems.
  It was developed by Sophos (which acquired it from Invincea, which acquired it earlier from the
  original author Ronen Tzur). It creates a sandbox-like isolated operating environment in which
  applications can be run or installed without permanently modifying the local or mapped drive.
  An isolated virtual environment allows controlled testing of untrusted programs and web surfing.
Homepage: https://github.com/sandboxie-plus/Sandboxie
Installers:
  - Arch: x86
    Url: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.3.5/SandboxieInstall32-v5.42.1.exe
    Sha256: 9E603DAA59AD20E46F3B38B29B03548A4D8AD3A8BE8D400D1BAE2B0C11ECB311
    InstallerType: nullsoft
  - Arch: x64
    Url: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.3.5/SandboxieInstall64-v5.42.1.exe
    Sha256: 9D8004C963834162AAC0612240596B4D4EDB5961C81E1A6E062F0CBC1429738D
    InstallerType: nullsoft

```

**Comment by Gravityzwell** [comment]
I suggest waiting until the driver signing is worked out.

**Comment by quangkieu** [comment]
> I suggest waiting until the driver signing is worked out.

I agree with this as I remember to read that they run Microsoft Anti-virus check on the submit pull request before approve it. I am not sure how it would flag current build/driver

**Comment by DavidXanatos** [comment]
It may not flag it as the driver is obfuscated, so unless they run a dummy installation in a test VM and scan whats happening inside they wont find it.

**Comment by rpr13** [comment]
Ok then. :-)

Same as for choco.

**Comment by Gravityzwell** [comment]
..It _may not_ flag it...

It's not my call to make, but if it was, I wouldn't want to take chances bringing the clever trickery to the attention of MS. The same MS that sells the EV certificates and the same MS that owns github. They wouldn't even need any legal process for github.

And for what? Waiting some time the driver probably will be resolved. I'd rather keep it quiet until it becomes irrelevant.

**Comment by Gravityzwell** [comment]
And FYI it looks like Sandboxie Plus was delisted from Choco. I handn't known it was submitted there, but I would have suggested the same, wait till the driver is worked out.

**Comment by rpr13** [comment]
Yup. That's why creators should add their apps to choco, winget etc.

And btw, Windows 10 does have problem with driver and puts it on quarantine.  Easy to unmark.  
But still, better wait. 😄

**Comment by 0m3rta13** [comment]
Not sure about Choco (though i think the same would apply) but it seems sandboxie has a long history of being broken for insider builds. This still seems to be the case
Other than the driver, I think this would have it pulled/not approved for the Winget repo

**Comment by stephtr** [comment]
@rpr13 Thanks for the initial work, I have filed a modified [PR to winget's package repo](https://github.com/microsoft/winget-pkgs/pull/7828).

**Comment by stephtr** [comment]
`winget install sandboxie` is now live 🙂

**Comment by quangkieu** [comment]
I wonder if there could be a bot on Sandboxie repo to auto create pull request on winget on new release for both versions. I think could also add a static manifest for the origin Sandboxie version from Sophos if anyone want the old one.

**Comment by stephtr** [comment]
Microsoft is working on [some larger improvements](https://github.com/microsoft/winget-pkgs/issues/5418#issuecomment-755730967) to the winget tools. I wouldn't spend too much work on the manifest before those changes.
