### ISSUE TITLE
[Suggestion] Change the way Sandboxie Plus indicates a sandbox is actively emptying.

### ISSUE THREAD

**Issue by Dark-Magician** [sandboxie-plus/Sandboxie#1061]
Sandboxie Plus indicates a sandbox emptying by flashing a small window somewhere random on the screen. Classic Sandboxie does that unobtrusively by changing its tray icon to a stylized _x_ until completed.

![Sandboxie Plus - Delete](https://user-images.githubusercontent.com/19816749/127701131-20f7be50-95b0-403f-94b3-6e75bc4de5d9.gif)

![Classic Sandboxie - Delete](https://user-images.githubusercontent.com/19816749/127701191-92ae1816-be95-41a8-be5a-b705675fe501.gif)

**Comment by DavidXanatos** [comment]
the flashign window has the advantage that it has a cancel button which works and allows to cancel the operation,
but yea probably i should make the window appear only after 1 or 2 seconds if its not done till then?

**Comment by DavidXanatos** [comment]
the not worked canceling will be fixed in the next build

**Comment by DavidXanatos** [comment]
in the next build box deletion will no longer show a progress dialog, instead it will indicate the pending operation in the box list for the box its being performed for.

Hence deleting multiple sandboxes will be executed in parallel, in SSD's that's actually a spead up, on mechanical HDD's it's quite the opposite, hence if you have one of those best to only delete the content of one box at a time.
