### ISSUE TITLE
If "forceprocess=firefox.exe" or "Template=Firefox_Force" is set, "Run Outside Sandbox", "/disable_force" do not work.

### ISSUE THREAD

**Issue by xvim64** [sandboxie-plus/Sandboxie#1063]
**Describe the bug**
If "forceprocess=firefox.exe" or "Template=Firefox_Force" is set, "Run Outside Sandbox", "/disable_force" do not work.

**To Reproduce**
```
Sandboxie.ini ----------
[Firefox]
Template=Firefox_Force
------------------------

or

Sandboxie.ini ----------
[Firefox]
forceprocess=firefox.exe
------------------------

1.
in Command Prompt
"C:\Program Files\Sandboxie\Start.exe" /disable_force "C:\Program Files\Mozilla Firefox\firefox.exe"
or
on mouse
"Run Outside Sandbox"

2. 
Now firefox.exe runs in sandbox, not outside sandbox
```

**Expected behavior**
firefox.exe runs outside sandbox, not inside sandbox

**Screenshots**
![sandboxie-bug-run-outside-sandbox](https://user-images.githubusercontent.com/83569599/127718829-6fd9fd3c-37d9-4a2f-a100-107a9270d5ec.gif)

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (Windows 10 Pro 21H1).
 - What is your current Sandboxie edition and version? (Sandboxie-Classic-x64-v5.51.0.exe).
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. (Sandboxie-Classic-x64-v5.51.0.exe)
 - Please mention any security software running in the background, even if the real-time protection is disabled. (Microsoft Windows Defender Only)

**Sandboxie configuration**

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```
[GlobalSettings]

Template=RpcPortBindings
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing

[DefaultBox]

ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
Enabled=y

[UserSettings_0C360207]

SbieCtrl_UserName=abc
SbieCtrl_NextUpdateCheck=1628288017
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_TerminateWarn=n
SbieCtrl_WindowCoords=1104,145,700,577
SbieCtrl_ActiveView=40021

[Firefox]

ConfigLevel=9
BlockNetworkFiles=y
Template=Firefox_Force
Enabled=y
```

</details>

**Comment by isaak654** [comment]
Possible relation with #614... I think it was never fixed till now.

**Comment by xvim64** [comment]
> 
> 
> Possible relation with #614... I think it was never fixed till now.

This bug occured in Sandboxie-Classic-x64-v5.51.0.exe.

Since firefox cannot run outside Sandbox, it makes no update ...

Sandboxie-Classic-x64-v5.50.9.exe hotfix2 is OK.

**Comment by isaak654** [comment]
> 
> This bug occured in Sandboxie-Classic-x64-v5.51.0.exe.
> 
> Since firefox cannot run outside Sandbox, it makes no firefox update.
> 
> Sandboxie-Classic-x64-v5.50.9.exe hotfix2 is OK.

Confirmed! I was able to reproduce exactly what you did in the gif on Classic x64 v5.51.0 and v5.51.1. Last working version was 5.50.9.

Plus is immune to this problem, but it's not a good reason to not fix this issue... I had to reboot in order to uninstall those buggy versions.

**Comment by DavidXanatos** [comment]
When I test that with an app the process even though terminated remains in the sbiectrl process list, big bug not good...
well guud that the 0.9.x line is pre release beta still

**Comment by isaak654** [comment]
For another user it seems to affect Plus too:
https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-0.439305/page-3#post-3023604

**Comment by isaak654** [comment]
For another user it seems to affect Plus 0.9.1 too:
https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-0.439305/page-3#post-3023604

**Comment by DavidXanatos** [comment]
I'm looking into this issue right now and as far as i can assess the situation there are actually two bugs:
1. exemption from forced processes fails
2. the termination and cleanup when a process initialization fails is broken as than the process should be killed and not remain in the driver's process list

I should have a fix soon
