### ISSUE TITLE
Can't direct access resource

### ISSUE THREAD

**Issue by kckm** [sandboxie-plus/Sandboxie#1065]
**Describe the bug**
the programe  in sanbox can not write files in folder directly.

**To Reproduce**
1. Go to 'resource access'
2. Click on 'add file/folder'
3. program: all programs; access:direct; path: d:\downloads.
4. download file to d:\downloads . but no file in d:\downloads.
5. but the windows explorer(in sandbox) can create new folder in the path.
**Expected behavior**
the download file in d:\downloads.

**Screenshots**

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 11 22000.100).
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.9.0).
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**Additional context**

**Sandboxie configuration**
If applicable, consider to attach your sandboxie.ini configuration by copying the content at https://gist.github.com and sharing the resulting link here. If you decide to paste the configuration directly here, make sure to use the backticks around strings, like in this working example:

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]

.....

[UserSettings_175D0429]

.....

[DefaultBox]

.....

```

</details>

**Comment by DavidXanatos** [comment]
I can't reproduce this issue, on my w11 test system downloading to an open path works just fine

**Comment by kckm** [comment]
> I can't reproduce this issue, on my w11 test system downloading to an open path works just fine
I have reinstalled the sandboxie-plus. The problem is still exists.
And windows explorer is blank now.
<img width="844" alt="屏幕截图 2021-07-31 232111" src="https://user-images.githubusercontent.com/19590608/127745544-61699057-f38f-427f-9db8-67571598879e.png">

**Comment by kckm** [comment]
One more problem, when I select "Browse for Folder" and choose the folder, the added rules disappear when I click apply.

**Comment by isaak654** [comment]
> One more problem, when I select "Browse for Folder" and choose the folder, the added rules disappear when I click apply.
>

Confirmed in 0.8.9c

**Comment by DavidXanatos** [comment]
ok it seams that when a path is browsed the value is not properly saved ot the tree and when you click apply its removed as the save code seas an empty string double clicking on the Value and then applying solves the issue

**Comment by DavidXanatos** [comment]
no wrong the flag that something was changed is not set so editing any option will make apply wok

**Comment by kckm** [comment]
> ok it seams that when a path is browsed the value is not properly saved ot the tree and when you click apply its removed as the save code seas an empty string double clicking on the Value and then applying solves the issue

There are two difference issues. I have manually entered the path and successfully applied it.

I used qbittorrent to test. If qbittorrent is installed on a system that uses a sandbox to run it, it can write in the open path. But if qbittorrent is installed in sandbox, it cannot write in the open path.

**Comment by DavidXanatos** [comment]
If you want  qbittorrent is installed in sandboxie to write to open paths you need to select not "Direct" but  "Direct All"

**Comment by kckm** [comment]
Thanks, problem solved.

**Comment by kckm** [comment]
I have the same problem with 0.9.8d. Programs in the sandbox cannot access the specified directly accessible directory.
