### ISSUE TITLE
2nd time I've installed a new computer where Chrome starts in Sandboxie Classic and then automatically stops.

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#1067]
I've installed Chrome and Sandboxie 5.50.8 on a new HP Windows 10 home laptop.
I setup auto delete.
I checked all the Settings:Applications:Web Browser:Google Chrome [+] boxes.
I click on Chrome in the taskbar, and the following four programs start immediately.
   SandboxieDcomLaunch...
   SandboxieRpcSss.exe
   WerFault.exe
   chrome.exe
Then after a couple of seconds
   SandboxieCrypto.exe 
starts and then they all go away.
I never see the Chrome program.

Thanks for you help.

**Comment by jedimasterspaz** [comment]
Here are pictures of what happened.
![Screenshot 2021-07-30 16 37 31](https://user-images.githubusercontent.com/72579094/127755747-9d9ac678-c409-4492-ae8e-d1bd4c61ed73.png)
![Screenshot 2021-07-30 16 37 45](https://user-images.githubusercontent.com/72579094/127755748-b12044dd-8fcd-442c-a4c0-2cbfae660bd9.png)
![Screenshot 2021-07-30 16 37 49](https://user-images.githubusercontent.com/72579094/127755749-50228e48-a832-4e24-9c14-0226890220d1.png)

**Comment by isaak654** [comment]
Could you list the specs of this laptop (CPU, GPU, Windows 10 xxxx)?

**Comment by isaak654** [comment]
#225

**Comment by isaak654** [comment]
#225

**Comment by SengCheong** [comment]
Hi, I am running into a similar issue with chrome. I see the following sequence of events occuring:
1. SandboxieRpcSs.exe, SandboxieDcomLaunch.exe & Chrome.exe executing
2. Sandboxie produces a single error message: SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
3. WerFault.exe appears
4. SandboxieCrypto.exe appears
5. All programs disappear

Chrome Version: 92.0.4515.131
CPU: AMD Ryzen 5 5600X
GPU:  Nvidia RTX 3070

**Comment by DavidXanatos** [comment]
> 5 5600X
this is teh problem

same issue with 11th gen intel CPU's
probably the shadow stack feature is the issue

I'm looking into obtaining affected hardware and debug the issue soon.

Unfortunately I need a CPU with that feature set to work on the problem, hence the delays.

**Comment by isaak654** [comment]
#1012

**Comment by DavidXanatos** [comment]
workaround

chrome.reg
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\chrome.exe]
"MitigationOptions"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,20,00,00,\
  00,00,00,00,00,00
"MitigationAuditOptions"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00
"EAFModules"=""

```

for other apps replace chrome.exe with the name of the otehr app

**Comment by isaak654** [comment]
I hope this can be fixed reliably without disabling the CET stack protection.

**Comment by isaak654** [comment]
I hope this can be fixed reliably without disabling the CET stack protection per process.

**Comment by DavidXanatos** [comment]
> 
> 
> I hope this can be fixed reliably without disabling the CET stack protection per process.

I don't know yet, but the issue affects the sys call hooks of sandboxie, the other hooks as well as the low level injection code seam to work fine, if you disable the sys call hooks with NoSysCallHooks=y and make the box super insecure in order for the process to be able to start like this with OriginalToken=y chrome starts and runs, you may also need NoSandboxieDesktop=y 

So there is a chance that the problem might be fixable without disabling CET but I'm not sure yet if that is really the case.

When I think about it its strange that a function hook would upset the stack protection as normally it works like this
something: call hooked_fx -> jump to function hook -> do some hooky stuff may be call original function than return from it -> return from  function hook directly to something calling the hooked function. 
So only normal call and returns with a jump in the middle but no need to manipulate the return address on the stack, what would be what upsets the CET feature.

**Comment by DavidXanatos** [comment]
Update: as it looks it should be possible to fix the sys-call hooking mechanism to be CET compatible :D

**Comment by isaak654** [comment]
The workaround posted above removes the stack protection also outside of the sandbox, so it would be advisable to revert it before installing the next build.
