### ISSUE TITLE
Allow some outer program to be executed un-sandboxed from sandbox

### ISSUE THREAD

**Issue by NyaMisty** [sandboxie-plus/Sandboxie#1070]
**Is your feature request related to a problem? Please describe.**
I'm always using app with file processing functionality, such as downloaders and mobile device managers.
After these app copying/downloading files, I usually wants to process them with explorer. But because the sandbox, these apps can't bring me to the target folder. Instead, they bring up a sandboxed explorer.
Also, sometimes apps want to open a webpage, and instead of open it externally, they simply opens up a Chrome inside.

**Describe the solution you'd like**
I want a sandbox option, which can allow process in it to spawn some outer process unsandboxed.

**Describe alternatives you've considered**
Users can manually inject a DLL and hook up onto the CreateProcess and ShellExecute, but that would be quite some work.

**Comment by DavidXanatos** [comment]
> I want a sandbox option, which can allow process in it to spawn some outer process unsandboxed.
>

Lol that kind of defeats the purpose and opens a major security whole if not done exact right.

But for the planed not security oriented App Container mode its worth a try.
As well as the ability to open an application in/from an other sandbox / app container

**Comment by NyaMisty** [comment]
Well that's not true ;)
actually we've already have bunches of options to partially bypass security
And prompting a dialog box before attempting to ShellExecute anything should be pretty good?

**Comment by DavidXanatos** [comment]
I was looking into this feature request and I see a major issue: 
When you want to open a file in the sandbox lets say with an unsandboxed winrar, tha unsandboxed instance will not be able to access the file at the sandboxed path.
For webpages sure that would work opening them on the desktop, but for files, that woudl work only if the file is located in a open path to begin with, that is unless one would always parse and modify the arguments passed to the program.
Is that what you want?

**Comment by exander77** [comment]
@DavidXanatos I think the of the uses is to run Steam sandboxed and run the applications from that Steam unsandboxed.
