### ISSUE TITLE
Sandman leaks CWD on spawning sandboxed processes

### ISSUE THREAD

**Issue by nedsociety** [sandboxie-plus/Sandboxie#1071]
**Describe the bug**
SandMan-spawned processes are inheriting SandMan's current working directory.

I'm not sure if it was an existing behavior or a regression, but at least the use case below have been affected and this is not intuitive.

**To Reproduce**
1. (Close SandMan process)
2. mkdir testdir
3. cd testdir
3. echo > test.txt
4. In Explorer, open testdir, and use context menu to open test.txt on sandbox (Run Sandboxed).
5. (The dialog for choosing Sandbox to run can be ignored so just Cancel it. The important thing is the behavior after it.)
6. In newly spawned SandMan, right-click DefaultBox to run Terminal -> **It opens on testdir.**
7. In Explorer, navigate to %windir%\system32
8. Use context menu to open cmd.exe on sandbox (Run Sandboxed) -> **It opens on testdir.**

**Expected behavior**
The first highlighted terminal should have been opened on `%userprofile%`. This was true up to v0.8.2 but after I updated to v0.8.9 it somehow started to leak where Sandman had been started on newly spawned processes.

I don't quite remember if the second one was opened on `%userprofile%` (the default cmd location) or `%windir%\system32` (where context menu had been called) in v0.8.2, but at least I believe it wasn't testdir.

**System details and installed software (please provide the following information):**
10 20H2, Sandboxie-Plus 0.8.9

**Additional context**
v0.8.2 used an old Sandbox choice dialog. If it's turned out to be a regression then this might be related.

**Comment by DavidXanatos** [comment]
fyi: the start dir wil always be c:\windows\system32 from now on out
