### ISSUE TITLE
High CPU usage with sandboxed game in private game server (Win 10 1803)

### ISSUE THREAD

**Issue by 759852125** [sandboxie-plus/Sandboxie#1072]
沙盒游戏卡顿

**Comment by isaak654** [comment]
> 
> 
> 沙盒游戏卡顿

Please write in english or use a translator.
You also need to mention your sandboxie version and a detailed description of the issue is missing.

**Comment by 759852125** [comment]
> > 沙盒游戏卡顿
> 
> 请用英文书写或使用翻译。
> 您还需要提及您的沙盒版本，并且缺少对问题的详细描述。

Play 2D games in sandbox very card

![image](https://user-images.githubusercontent.com/54934866/128355553-0f3060d1-35c2-4830-bf21-749a6f21d960.png)
![1628169130(1)](https://user-images.githubusercontent.com/54934866/128355647-8416e37d-203e-4a4f-b870-e6be3831214c.jpg)

**Comment by 759852125** [comment]
> > 沙盒游戏卡顿
> 
> 请用英文书写或使用翻译。
> 您还需要提及您的沙盒版本，并且缺少对问题的详细描述。

I can provide remote control or remote assistance for you to debug

**Comment by 759852125** [comment]
@isaak654

**Comment by isaak654** [comment]
Please provide a download link for this game and see if downgrading your Plus version to [0.8.9c](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.8.9c) solves your issue... 0.9.1 is full of bugs and I can only recommend it for testers.
For remote assistance you'll have to wait @DavidXanatos , currently he's the only active developer for Sandboxie.

**Comment by 759852125** [comment]
> 请提供此游戏的下载链接，看看将您的 Plus 版本降级到[0.8.9c 是否能](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.8.9c)解决您的问题... 0.9.1 充满了错误，我只能向测试人员推荐它。
> 如需远程协助，您必须等待@DavidXanatos，目前他是 Sandboxie 的唯一活跃开发人员。

This game is not an official game, but a private game server,I already no download address,I am willing to wait for the contact person you provide,Excuse me Is he contacted me, or I contact him?   @isaak654

**Comment by isaak654** [comment]
You just need to wait here, it's like a waiting list... you're not the only one, I'm still waiting confirmation for other issues as well.

**Comment by 759852125** [comment]
> 你只需要在这里等待，就像一个等待名单......你不是唯一的人，我还在等待其他问题的确认。

Ok, understand, thank you

**Comment by isaak654** [comment]
Please check if 0.9.2 works:
https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2

**Comment by isaak654** [comment]
1) Please check if 0.9.2 works:
https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2
2) What is your Windows edition and version?
3) This game has a corresponding name in english language?

**Comment by 759852125** [comment]
> 1. 请检查 0.9.2 是否有效：[https](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2) : 
>    [//github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2)
> 2. 您的 Windows 版本和版本是什么？
> 3. 这个游戏有英文对应的名字吗？
1.Try now
2.Windows10 var 1803 
3.Sorry, this is China's game, and there seems to be no English name.

**Comment by 759852125** [comment]
> 1. 请检查 0.9.2 是否有效：[https](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2) : 
>    [//github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.2)
> 2. 您的 Windows 版本和版本是什么？
> 3. 这个游戏有英文对应的名字吗？

@isaak654 

Use 0.9.2, the problem still exists,But I found that using the sandbox to play this game, the CPU is full, it 
 is more than 90% or 95% higher  than the not use sandbox!

**Comment by isaak654** [comment]
Please update to 0.9.6 and verify it this issue was fixed.

**Comment by isaak654** [comment]
Please update to 0.9.6 and verify if this issue was fixed.
