### ISSUE TITLE
Sandboxie Plus Global Settings zh-CN no translate in sidebar

### ISSUE THREAD

**Issue by kouhe3** [sandboxie-plus/Sandboxie#1074]
**Describe the bug**
Sandboxie Plus Global Settings 
There is no translation in the sidebar

**To Reproduce**
0. Change language to zh-CN (中文简体)
1. Go to 'Options'（选项）
2. Click on 'Global Settings'（全局设置）
3. See error

**Expected behavior**
Chinese 

**Screenshots**

![image](https://user-images.githubusercontent.com/25522053/128594884-afa3a66a-78a1-4624-bfcc-0fc288d44397.png)

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 20H2
 -  Sandboxie Plus 0.9.1 x64
- huorong

**Comment by isaak654** [comment]
See #1064
