### ISSUE TITLE
Windows 8 capture not available

### ISSUE THREAD

**Issue by FluffyDiscord** [sandboxie-plus/Sandboxie#1077]
**Describe the bug**
Using [Ambibox ](http://www.ambibox.ru/en/index.php/Main_Page) software and setting the capture mode to Windows 8 does not work. Everything except that works fine, the application is able to connect to a separate COM port and correctly saves it's settings.

**To Reproduce**
1. Fresh Sandboxie install
2. Run Ambibox in Sandboxie

**Expected behavior**
The Windows 8 capture should work just fine.

**Screenshots**
Won't help.

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 20H2 (19042.1052)
 - Sandboxie Plus v0.8.9
 - First time using sandboxie - no idea, if this bug was present in earlier versions

**Additional context**
--

**Sandboxie configuration**
Fresh out of box

**Comment by isaak654** [comment]
Please could you take a log to post here?

With Plus 0.8.9, you need to enable 'Trace Log' tab by opening 'Options' menu -> 'Trace Logging'.
Once enabled, you can reproduce your issue.
After reproducing it, just right click -> 'Copy Panel' to copy the full log and post it here:
![trace_log](https://user-images.githubusercontent.com/12372772/113529350-793af380-95c3-11eb-8d48-f9aab655b37a.png)
