### ISSUE TITLE
Reports error when run programs in my win10_pro_x64

### ISSUE THREAD

**Issue by xyxtgm** [sandboxie-plus/Sandboxie#1090]
**Describe the bug**
using Sandboxie-Plus-x64-v0.9.3 to run programs in win10_x64, it reports an error and exit: 
**"cannot locate program input point _o__cexit in dll C:\WINDOWS\System32\msvcp_win.dll"**

EXAMPLE: Run TIM which is download from  https://office.qq.com/ (https://dldir1.qq.com/qqfile/qq/PCTIM/TIM3.3.8/TIM3.3.8.22043.exe)
It reported:
![image](https://user-images.githubusercontent.com/14138488/128687265-27575b4f-71f7-47de-8241-bce7f27f7e34.png)

Even just run TIM installer TIM3.3.8.22043.exe, it also report this error.

**System details and installed software (please provide the following information):**
 - Windows 10 Pro x64  (version 2004 installed 2021/8/4)
 - Sandboxie-Plus-x64-v0.9.3 and old versions as same
 - When win10 auto updated at 2021/8/4 (version updated to 2004),  then sandboxie begun to report this error when i run programs.
 - NO security software running in the background

**Additional context**

**Sandboxie configuration**

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]

Template=RpcPortBindings
Template=WindowsRasMan
Template=AdobeLicensing
Template=SynapticsTouchPad
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Logitech_G15_Keyboard

[DefaultBox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Enabled=y

[UserSettings_37A604A1]

SbieCtrl_UserName=tangguoming
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1628559628
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_ExplorerNotify=n
SbieCtrl_WindowCoords=200,150,1237,632
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_AutoStartAgent=SandMan.exe

```

</details>

**Comment by DavidXanatos** [comment]
On my test system that installer runs fine
