### ISSUE TITLE
Mount an ISO image with ImDisk under Sandboxie supervision causes SBIE2337 and sometimes BSoD

### ISSUE THREAD

**Issue by matheuswillder** [sandboxie-plus/Sandboxie#1092]
**Describe the bug**
As the title says. Accidentally I tried to mount an ISO image that was located in a forced folder, and the ImDisk process started under the supervision of Sandboxie. After process started Sandboxie can't kill it or delete the contents of the box. After a few attempts of trying to kill the process the Windows ended up in a BSoD and... ok, it would have been better save my work and restart the computer before this :(

**To Reproduce**
1. Simply install [ImDisk Toolkit](https://sourceforge.net/projects/imdisk-toolkit/) (open source, available on SourceForge) outside of Sandboxie and try to mount an ISO image that is inside a forced folder, or even start the image mounter already under Sandboxie and try to mount the ISO image there. After that Sandboxie can no longer kill the process.

**Expected behavior**
I didn't expect it to be possible to mount the image inside Sandboxie, but not being able to kill the process or delete the contents of the box doesn't seem normal. **Edit**: I found now that [WinCDEmu](https://github.com/sysprogs/WinCDEmu) (another virtual image mounter) can mount an image when it is under the supervision of Sandboxie, and the virtual drive appears outside of the boxes, is this correct or a security issue?

**System details and installed software (please provide the following information):**
 - Windows 10 Home 21H1 x64.
 - Sandboxie Plus 0.9.3.
 - I have tested some older builds before reporting this issue, it occurs in all.
 - None, I installed a virtual machine to test after discovering this on my real machine.

Sorry my English :)

**Comment by DavidXanatos** [comment]
I have added ```ClosedFilePath=\Device\ImDiskCtl``` to Templates.ini as a workaround, we generally don't want sandboxes programs to mount disk images. I have observed issues arising with ImDisk when termianting disk proxy processes resulting in deadlocks and not unmountable volumes, so I don't think without changes to the ImDisk driver we could safely use it from withing a sandbox.
To workaround force folder the image mounter can be configured as a break out process and not get sandboxed.
