### ISSUE TITLE
[bug/feature request] [classic 5.50.8] shortcuts created don't "run outside sandbox"

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1093]
it's a combination of bug/feature request:

If we try to RUN OUTSIDE SANDBOX a shortcut created through (configure - window shell integration - add shortcut icons) - it won't work, they will open sandboxed anyway

my request
if we click "run outside sandbox" a shortcut created through (configure - window shell integration - add shortcut icons) - make it open the original unsandboxed file.

**Comment by isaak654** [comment]
There is already a fix about it on 5.51.3.

**Comment by diieg707** [comment]
> 
> 
> There is already a fix about it on 5.51.3.

well what fix is it?, i can't tell on the changelog

**Comment by isaak654** [comment]
> 
> 
> > There is already a fix about it on 5.51.3.
> 
> well what fix is it?, i can't tell on the changelog

See https://github.com/sandboxie-plus/Sandboxie/issues/614

**Comment by diieg707** [comment]
> 
> 
> > > There is already a fix about it on 5.51.3.
> > 
> > 
> > well what fix is it?, i can't tell on the changelog
> 
> See #614

ok then, i'm gonna test it later

**Comment by isaak654** [comment]
> ok then, i'm gonna test it later

I would suggest to reboot afterwards, it's a huge jump from 5.50.8.

**Comment by diieg707** [comment]
Im still using classic to this day, plus version has lots of bugs and improvements need to be done

**Comment by diieg707** [comment]
you can close it
