### ISSUE TITLE
"Administrator Mode Detected" dialog box that pops up every time Edge is run with v5.51.3

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1097]
Besides not running as Administrator on Windows 8.1 (I don't have another account), how do I get rid of the "Administrator Mode Detected" dialog box that pops up every time Edge is run starting with v0.9.3 / 5.51.3?  Checking "Don't show me this message again" doesn't help -- it still comes up every time Edge is started.  This does not occur with Sandboxie-Classic-x64-v5.50.9.exe and prior versions. 

![Capture](https://user-images.githubusercontent.com/36712448/129125495-7cd555d0-dcd4-4e75-8c49-ebcb424505b9.JPG)

@DavidXanatos
> did you enabled fake admin mode in the settings?

The only thing I did was run Sandboxie-Classic-x64-v5.51.3.exe to upgrade from Sandboxie-Classic-x64-v5.50.9.exe.

I've been a Sandboxie user for many many years, but I don't set up additional sandboxes or use special settings. It's a very simple installation.

I've gone back to v5.50.9 and the problem goes away.

Thanks!

_Originally posted by @reraikes in https://github.com/sandboxie-plus/Sandboxie/discussions/1085#discussioncomment-1161408_

**Comment by isaak654** [comment]
Bug confirmed, it affects only Windows 8.1 x64 for some odd reason.

**Comment by DavidXanatos** [comment]
hmm... pfff.... okay... wil have to debug that, strange that it only affects this windows version, I remember there wer some workarounds by the old sbie devs for IE regarding running it as admin so possibly its one of the workarounds, and probalby there was a good reason for it to be there in the first place :/

**Comment by reraikes** [comment]
> Strangely I can reproduce it on W10 x64 too... I think something changed with Edge recently, because downgrading to v5.50.9 didn't fix it.

FWIW...

v5.50.9 on Windows 8.1 x64 (w/latest Windows updates) does not experience the problem.

Upgrading to x64 v5.51.3 brings the problem back.

**Comment by isaak654** [comment]
> 
> 
> > Strangely I can reproduce it on W10 x64 too... I think something changed with Edge recently, because downgrading to v5.50.9 didn't fix it.
> 
> FWIW...
> 
> v5.50.9 on Windows 8.1 x64 (w/latest Windows updates) does not experience the problem.
> 
> Upgrading to x64 v5.51.3 brings the problem back.

I know, but my experience about it was different.

**Comment by bjm234** [comment]
FWIW ~ https://thegeekpage.com/administrator-mode-detected/

**Comment by isaak654** [comment]
1) In Windows 8.1 this happens always, even without FakeAdminRights
2) In Windows 10 it's enough to remove `FakeAdminRights=y` in order to not see the dialog box.

**Comment by reraikes** [comment]
> 1. In Windows 8.1 this happens always, even without FakeAdminRights
> 2. In Windows 10 it's enough to remove `FakeAdminRights=y` in order to not see the dialog box.

Thanks for that clarification.

**Comment by DavidXanatos** [comment]
> 
> 
> > Strangely I can reproduce it on W10 x64 too... I think something changed with Edge recently, because downgrading to v5.50.9 didn't fix it.
> 
> FWIW...
> 
> v5.50.9 on Windows 8.1 x64 (w/latest Windows updates) does not experience the problem.
> 
> Upgrading to x64 v5.51.3 brings the problem back.

ok in that case that should be fixable

**Comment by DavidXanatos** [comment]
strangely for me in win 8.1 the most recent chrmium based edge does not show this error line

**Comment by reraikes** [comment]
> strangely for me in win 8.1 the most recent chrmium based edge does not show this error line

Microsoft Edge
Version 92.0.902.73 (Official build) (64-bit)

**Comment by DavidXanatos** [comment]
Yep i tested with this version and no problem, may be its some fring issue, with some window supdate as my w8 vm is not up to date at all lol

**Comment by DavidXanatos** [comment]
i have fully updated by win 8.1 Vm but it still does not reproduce this issue.

**Comment by reraikes** [comment]
> > 1. In Windows 8.1 this happens always, even without FakeAdminRights
> > 2. In Windows 10 it's enough to remove `FakeAdminRights=y` in order to not see the dialog box.

Since @isaak654 is able to reproduce it, it's not just me.  :)

**Comment by isaak654** [comment]
On Windows 10 it's enough to add `FakeAdminRights=y` on a clean box to reproduce the issue on Edge.

**Comment by isaak654** [comment]
On Windows 10 it's enough to add `FakeAdminRights=y` on a clean box to reproduce the issue on Edge... for this test, I used the same VM sent to David weeks ago for another non-related issue (recently fixed).

**Comment by isaak654** [comment]
In the end, the problem was related to the "Run this program as admin" compatibility setting that should be turned off in the shorcut properties:
![image](https://user-images.githubusercontent.com/12372772/129605091-ba0cc931-fad7-472b-b87d-1fedd3a17c9e.png)

**Comment by isaak654** [comment]
In the end, on my Windows 8.1 setup the problem was related to the "Run this program as an administrator" compatibility setting that should be turned off in the shortcut properties.

Unfortunately I still have this problem on Windows 10 machine (described in the previous post), I checked the properties and no compatibility setting was there.

**Comment by reraikes** [comment]
> In the end, on my Windows 8.1 setup the problem was related to the "Run this program as an administrator" compatibility setting that should be turned off in the shortcut properties.

That's not the problem here:

![Capture](https://user-images.githubusercontent.com/36712448/129607133-88b3cecb-8f3b-4ba9-959d-16a9b38113a2.JPG)

**Comment by reraikes** [comment]
Just an FYI...

This problem is still present in Sandboxie-Classic-x64-v5.51.4.exe.

Dropping back to Sandboxie-Classic-x64-v5.50.9.exe eliminates the problem.

**Comment by bjm234** [comment]
as test ~ reproduced Administrator Mode Detected with FakeAdminRights=y
![image](https://user-images.githubusercontent.com/25015553/130510220-3551225e-5583-4675-a084-265b8089c320.png)
0.9.4

**Comment by reraikes** [comment]
Just an FYI...

This problem is still present in Sandboxie-Classic-x64-v5.51.5.exe.

Dropping back to Sandboxie-Classic-x64-v5.50.9.exe eliminates the problem.
