### ISSUE TITLE
Right click "Run Sandboxed" a already inside a sandboxed program 

### ISSUE THREAD

**Issue by sebadamus** [sandboxie-plus/Sandboxie#1099]
**Describe the bug**
I used to run any program I installed inside my sandbox by right clicking the shortcut I create on my desktop and "Run Sandboxed", and it used to open normally in the correct sandbox or then selecting the sandbox I want from the popup sandbox selection.  

Now in 0.9.3 version seems this behaviour has changed.

Now, it seems Sandboxie tries to re-open sandman in systray (you see the sandman systray icon with its yellow rectangle showing it is sandboxed) and the gives this popup "Error Status: -1073741822" (I have never seen before), then I click OK and popups the Sandboxie selection box (I have 3) but as this Sandman is "sandboxied" you just see one sandbox avaiable.  Better explained in pictures.

**To Reproduce**
1. Right click on a shortcut in my real desktop that points to a program inside any sandbox, then after the right click select from the popup Run Sandboxed.
2. Now a new sanman appear in the systray but its "sandboxed icon" and after that errors apears.

**Expected behavior**
As from previous version, I right click the shortcut and then it let me select which sandbox to run it in (even if the shortcut is also a program inside a sandbox folder) and opened just right with no error.
If I open the shortcut just with double click (without "Run Sandboxed" right clicking... it works normall as always.

**Screenshots**
This first screenshot you see on top a sandman (the real one) that when I do the steps mentioned before, opens the 2nd "# sandman sandboxed #" 
![imagen](https://user-images.githubusercontent.com/1787753/129296557-2fdc2a70-a996-4418-9224-500d97cf6d88.png)

![imagen](https://user-images.githubusercontent.com/1787753/129296567-c07eade0-9c7a-4029-9ffb-43109b3664a2.png)

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 21H1).
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.9.3).
 - Started in this last 0.9.3 version, before this I had 5.51.3 and 5.50.9 classic x64 versions.  DIdnt had this behaviour.  Will try to reinstall those versions and trying again.
 - Please mention any security software running in the background, even if the real-time protection is disabled.
Windows Defender, but tried disabling it

**Sandboxie configuration**
<details>
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]

FileRootPath=E:\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=RpcPortBindings
Template=OfficeLicensing
Template=BitVise
Template=7zipShellEx

[UserSettings_2648039E]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
BoxDisplayOrder=BoxDev,Testings

[DefaultBox]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[BoxDev]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[Testings]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

```

</details>

**Comment by sebadamus** [comment]
Sorry, I cut the systray part...  here it is.
![imagen](https://user-images.githubusercontent.com/1787753/129297977-3e025fcf-3edb-4068-9b23-ed427d3e831d.png)

**Comment by DavidXanatos** [comment]
hmm...
I have tested that scenario and
1. indeed when sandman is used for the run sandboxed handling it fails in that scenario, but
2. as far as i can tell from my testing using the old start.exe the calssical build always opens the program in the sandbox its located in and there is no box selection dialog, also on a technical level it would be very strange to be able to run a program located in box A inside box B as then a lot of things would be broken or inaccessible

So how do you get a box selection dialog for a exe that is located in a sandbox?

**Comment by DavidXanatos** [comment]
1 will be fixed in next build i.e. when you run sandboyed on y link to somethign thats in a sandbox it wil be successfully started in that sandbox.

there will be no selection dialog and I could nto reproduce getting one with the classic ui in such a scenario.


@sebadamus 
if you can provide a guide how to reproduce a box selection dialog for this usecase I'll look into it

**Comment by sebadamus** [comment]
> So how do you get a box selection dialog for a exe that is located in a sandbox?

Yep, you are completely right (as always... there have some flowers :-p)

I have just went back to classic version 5.51.3 and the problem wont appear here so might be the Plus version.
