### ISSUE TITLE
Sandboxie Portable

### ISSUE THREAD

**Issue by GunGunGun** [sandboxie-plus/Sandboxie#11]
Now Sandboxie has became open source, can you consider adding portable launcher ? Thank you.

Portable Launcher - Contributed by wraithdu https://www.sandboxie.com/old-forums/viewtopic48d6.html?f=22&t=2299

**Comment by DavidXanatos** [comment]
Technically by its nature sandboxie isn't very portable as it needs a driver and a service. But given that many other "portable" tools like the sysinternals suite, etc... don't confider that an issue and just install drivers I think there is no reason why we shouldn't do the same with sandboxie.

IMHO the easiest approach would be to add the ability to install the driver to the UI component such that if you copy your Program Files\Sandboxie folder on a USB stick and create some config file in it. The tool hen started from it will first check if there is a drier already installed and and if not install one temporary.

**Comment by diversenok** [comment]
> But given that many other "portable" tools like the sysinternals suite, etc... don't consider that an issue and just install drivers I think there is no reason why we shouldn't do the same with sandboxie.

All Sysinternals tools that come with a driver, automatically unload it when you close the application. It's not required because loading a driver does not lock the file, but it's still a good practice.

I see that we can't unload SbieDrv by ordinary means since it doesn't register the `DriverUnload` callback. However, there seems to be a designated API call `API_UNLOAD_DRIVER`, used by the installer when upgrading Sandboxie.

**Comment by DavidXanatos** [comment]
Yes exactly, actually something working could even be fashioned form an unmodified release, you only need the kmdutil.exe file which the setup utilizes and temporally stores in the temp files.

But IMHO it would be a better practice to add this functionality to the SbieCtrl.exe
together with some extensions to the driver that will make it pull the Sandboxie.ini location from registry and use it instead of relaying on a hard coded path under c:\windows\

**Comment by brushington** [comment]
I have start a script of doing this. The scripts works fine but need some improvements. But I have a problem that the programs cannot start in the sandbox. I open a new issue for describing that. I will further test my script after the issue is solved. :D

**Comment by brushington** [comment]
Consider you put the compiled binary of sandboxie_portable into a runtime library D:\Sandboxie_RT. When the driver is signed. The installation bat script (SbieInstall.bat) is like this:

```
set SANDBIN=D:\Sandboxie_RT

%SANDBIN%\KmdUtil.exe /lang=1033 install SbieDrv "%SANDBIN%\SbieDrv.sys" type=kernel start=demand "msgfile=%SANDBIN%\SbieMsg.dll" altitude=86900
%SANDBIN%\KmdUtil.exe /lang=1033 install SbieSvc "\"%SANDBIN%\SbieSvc.exe"\" type=own start=auto "display=Sandboxie Service" group=UIGroup "msgfile=%SANDBIN%\SbieMsg.dll
```

Then import the Windows registry File (SbieSvc.reg) as follows:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieSvc]
"Language"=dword:00000409
"PreferExternalManifest"=dword:00000001
```

After reboot, you can start the system services (StartSvc.bat) as follows:
```
%SANDBIN%\KmdUtil.exe /lang=1033 start SbieDrv
%SANDBIN%\KmdUtil.exe /lang=1033 start SbieSvc
```

Then the sandboxie should work well. You can double click D:\Sandboxie_RT\SbieCtrl.exe to control the sandboxie. 

Note that you only need to reboot once after you install the driver SbieDrv.sys with KmdUtil.exe. You do not need to reboot when you try to replace the driver. You can just stop the system services, replace the driver, and start the services.

The following script stops the system services (StopSvc.bat):
```
%SANDBIN%\KmdUtil.exe /lang=1033 stop SbieSvc
%SANDBIN%\KmdUtil.exe /lang=1033 stop SbieDrv
```

If you want to uninstall the sandboxie_portable, just stop the system services with StopSvc.bat. And remove them with SbieUninstall.bat as follows:
```
%SANDBIN%\KmdUtil.exe /lang=1033 delete SbieSvc
%SANDBIN%\KmdUtil.exe /lang=1033 delete SbieDrv
```

These are the scripts I wrote in my laptop. With these scripts, you do not need the SandboxieInstall package in the VS projects, and make the sandboxie easy to portable.

**Comment by jack1142** [comment]
@DavidXanatos I saw that the v0.2 / 5.41 release has zip files included, does it mean this issue can be closed or is it not fully functional just yet?

**Comment by DavidXanatos** [comment]
Yes it can be closed
