### ISSUE TITLE
Rename a sandbox without emptying the content

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#1100]
**Is your feature request related to a problem? Please describe.**
The legacy sandboxie does not allow rename a sandbox without emptying its content first, sandboxie-plus has kept this restriction.

On the other hand, it seems possible to to rename while keeping the content by changing the name in sandboxie.ini and rename the folder of the corresponding sandbox manually. Doing so has not appeared to affect the running of the sandbox concerned under either sandboxie or sanboxie-plus.

Are there some subtle detriments that make renaming without emptying undesirable/defective?

**Describe the solution you'd like**
Allow rename with emptying through sandman menu instead of manual operation as described above.

**Describe alternatives you've considered**
See the above description

**Additional context**

**Comment by DavidXanatos** [comment]
I think that's doable without issues, the sandboxed programs dont see the real location anywys

**Comment by Dyras** [comment]
@DavidXanatos Any chance you could also add a delete contents prompt when trying to remove a Sandbox? I mean, why would you have to manually empty it, right?

**Comment by DavidXanatos** [comment]
deleting is problematic in as far as it can take a long time, but I could first delete the sandbox entry and then start the folder deletion if it fails the user will have to clean it up himself

**Comment by superkryodev** [comment]
@DavidXanatos Thanks for implementing both features
