### ISSUE TITLE
A tray box-list highlight/selection issue and possible improvements

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#1106]
**Describe the bug**
When right-click on a non-selected item in the box list in the tray menu, the item is highlighted and selected with the context menu displayed. This is the expected behaviour, however subsequent right-clicks on a different item do change the selection but **not** the highlight. This can cause confusion on using context menu actions, especially "delete contents".

**To Reproduce**
1. Display the tray menu by right-click the tray icon (the box selected in the sandman window is highlighted in the box list)
2. Right click on a different box in the list: the highlight is changed to the that box under the pointer and context menu displayed, as expected
3. Right click on another different box in the list: the context menu is displayed next to the box under the pointer however the highlight and selection are **NOT** changed

**Expected behavior**
Step 3 should result in the same behaviour of step 2, i.e., both highlight and selection are changed following the pointer

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 21H1, Sandbox Plus 0.9.3
 
**Additional context**
The highlight colour for the tray box list is grey by default, presumably to differentiate from the selections of tray menu option in blue. However the contrast of the colour is quite weak in the dark theme and almost disappears in the light theme. Maybe a different highlight colour, such as orange/magenta/yellow, could be used?

Another suggestion is to display the box name in the pop-up windows for the confirmation of actions such as "delete content" or "remove sandbox" to avoid confusion, especially for the non-highlight bug reported above

**Comment by Coverlin** [comment]
For me the selection stays with the highlight, the box context menu reopens under the cursor but the actions are for the first right clicked box/highlight
Can use left click to reset the bug without closing the tray context menu allowing to highlight/select another box

For the highlight color i'd say to use the same as the main window instead

0.9.3
w7 x64

**Comment by superkryodev** [comment]
> For me the selection stays with the highlight, the box context menu reopens under the cursor but the actions are for the first right clicked box/highlight

You are right, corrected in the OP
> Can use left click to reset the bug without closing the tray context menu allowing to highlight/select another box

Yes, but an extra click is required

> For the highlight color i'd say to use the same as the main window instead

For me only the highlight on the box list in the tray menu is grey

**Comment by DavidXanatos** [comment]
idk how I can fix that easily with how Qt works, the menu handling is done by Qt so to fix that some event interception etc woudl be needes
