### ISSUE TITLE
How to set different sandboxes to different save directories？

### ISSUE THREAD

**Issue by zt5** [sandboxie-plus/Sandboxie#1108]
For example, if there are two sandboxes "A" and "B", I want the "A" sandbox to be stored in disk C and the "B" sandbox to be stored in disk D

**Comment by sebadamus** [comment]
I think you cant do that from Sandboxie Classic (dont really know if on Plus but I suppose you cant), the directory is configured as only one path in sandboxie.ini like here:

[GlobalSettings]
FileRootPath=E:\%SANDBOX%

Maybe you can create a hardlink (mklink) in Windows but from my experience it works strangely in sometimes, and I wouldnt dare to test it in sandboxie.  But if you are brave, try it and post back :-)

**Comment by Dyras** [comment]
Here's an example of how to do it. Basically add "FileRootPath=" to your sandboxie.ini under the Sandbox you want to change the location for.

[Defaultbox]
FileRootPath=E:\Location

[Firefox]
FileRootPath=E:\Another Location

**Comment by zt5** [comment]
> Here's an example of how to do it. Basically add "FileRootPath=" to your sandboxie.ini under the Sandbox you want to change the location for.
> 
> [Defaultbox]
> FileRootPath=E:\Location
> 
> [Firefox]
> FileRootPath=E:\Another Location

Thank you very much. This is working fine
