### ISSUE TITLE
baidu netdisk  cann't launch.

### ISSUE THREAD

**Issue by carlsue** [sandboxie-plus/Sandboxie#111]
windows 10 2004
sandboxie 5.42.1
BaiduYunGuanjia_7.0.2.9(pan.baidu.com)

can install ,cann't lauch.

**Comment by skygunner** [comment]
20H2
5.43.7

Installation and run works. But try to launch again will fail

**Comment by WhianGaulin** [comment]
> windows 10 2004
> sandboxie 5.42.1
> BaiduYunGuanjia_7.0.2.9(pan.baidu.com)
> 
> can install ,cann't lauch.

hello Do you know how to compile the program? I only compile SandMan.sln and there is no KmdUtil in the folder, what others should I compile? thank you very much

**Comment by DavidXanatos** [comment]
Compile sandbox.sln
is the issue still present in tne latest builds? thay improved windows 2004 and later compatybility a low
