### ISSUE TITLE
Tor browser is not working in sandboxie-plus

### ISSUE THREAD

**Issue by prorounak2005** [sandboxie-plus/Sandboxie#1116]
**Describe the bug**

**To Reproduce**
1. Install tor browser from https://www.torproject.org/
2. Right click tor browser and run it as admin is default sandbox
3. Tor browser didnt work 
4. Dll initialisation error.

**Expected behavior**
I thought tor browser should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/69617708/129665614-8b39b76c-9654-4824-8f01-22e5585865da.png)

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2). Windows 10 Enterprise 21H1 x64
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2). Sandboxie-plus x64 version 0.9.3
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. not working with latest version 0.9.3
 - Please mention any security software running in the background, even if the real-time protection is disabled. I have windows defender

<details>
 
<summary>My initial sandboxie.ini settings</summary>

[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=RpcPortBindings
Template=RBTray
Template=OfficeLicensing
Template=OfficeClickToRun
Template=7zipShellEx

[UserSettings_3F7604D3]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
BoxDisplayOrder=New_Box,dwadwa,sdsadad,Prorounak,fds,grdgrdgd,For_Browsing_Internet_,For_Launching_Application_,For_Launching_Applications,All_in_One,dw,de,dsd,xxs,For_Browsing_Internet,For_Browsing_,All_in_One_,For_Browsing_,For_running_application_,For_Browsing_,For_Running_applications_,For_watching_gogoanime,For_watching_gogoanime,For_running_applications_,For_watching_gogoanime_,For_watching_gogoanime,For_watching_gogoanime_,For_Watching_gogoanime,For_watching_gogoanime,For_running_gogoanime_,For_running_Applications_,For_daily_work,For_Daily_work_,For_Daily_Uses

[For_running_gogoanime_]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
ClosePrintSpooler=y

[For_running_Applications_]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[For_Daily_Uses]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

</details>

**Comment by Coverlin** [comment]
https://www.torproject.org/download/languages/ 
Download the 32 bit version , known issue with x64

**Comment by isaak654** [comment]
See https://github.com/sandboxie-plus/Sandboxie/issues/538#issuecomment-787092834 and https://github.com/sandboxie-plus/Sandboxie/issues/538#issuecomment-808277752.

**Comment by isaak654** [comment]
For your knowledge, this issue has just been fixed with Sandboxie [v1.0.21 / 5.55.21](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.21)
