### ISSUE TITLE
Program Compatibility Assistant : This app can't ran because of security issues

### ISSUE THREAD

**Issue by SanderBouwhuis** [sandboxie-plus/Sandboxie#112]
I started up my computer this morning and I got this messagebox:

![pcaui_CviFZgH8bW](https://user-images.githubusercontent.com/10495173/90217236-1bbe2080-de01-11ea-9a2d-df35a2c6676a.png)

I followed the link here, but don't know where to download a new(er) version. I'm probably an idiot, but is there a website where I can find the latest installer (for Windows 10)?

Thanks in advance.

**Comment by DavidXanatos** [comment]
what version are you using right now?

**Comment by SanderBouwhuis** [comment]
![SandboxIE](https://user-images.githubusercontent.com/10495173/90260066-492fbc00-de4b-11ea-92bd-ecd42d61e197.png)

**Comment by ahahahaah** [comment]
the latest version is here https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.3.5 v5.42.1

(but i cant tell you which one you should download between "sandboxieplus" "sandboxieinstall" and "sbieplus")

**Comment by DavidXanatos** [comment]
sandboxieinstall <- calssical sandboxie build
sandboxieplus <- modern sandboxie build
sbieplus <- same as sandboxieplus just as zip no installer, fully portable.

**Comment by SanderBouwhuis** [comment]
So, I should get sandboxieplus from now on if I want to keep getting (security) updates?

PS
Only now do I notice the tiny '+7 releases' on the https://github.com/sandboxie-plus/Sandboxie page.

**Comment by DavidXanatos** [comment]
Booth releases the classical and the plus once will get security updates, but only the plus one will get new features

**Comment by SanderBouwhuis** [comment]
When trying to install the SandboxIE Plus I get this:
![explorer_odDqdD3uW6](https://user-images.githubusercontent.com/10495173/90328583-b7849380-df9d-11ea-970b-6db23c7bde7d.png)

**Comment by DavidXanatos** [comment]
Well you need to add an exception for the driver as due to the used signing certificate its prone o false positives.
the message box tells you that much.

**Comment by SanderBouwhuis** [comment]
Circumventing anti-virus seems a bit scary/dodgy.
Anyway, thanks for the info.
