### ISSUE TITLE
How to create .sig file for a modified SandMan.exe, getting permissions error with it

### ISSUE THREAD

**Issue by engr-m-ayoub** [sandboxie-plus/Sandboxie#1124]
Hi,
I rebuilt Sanboxie plus 0.9.3 with some changes in SandMan. On running it gives Permission error because SandMan.exe.sig file isn't valid anymore(I assumed because it works if I place sandman.exe from given installer with .sig file).

It works fine if If boot windows with ''bcdedit /set testsigning on''.

what is recommended way to fix this issue? Do I need to get a certificate and sign this exe before creating installer? Will appreciate the help.

**Comment by DavidXanatos** [comment]
You need to build your own driver with your own pub key or the sign check disabled and sign it through MSFT using an EV cert.
