### ISSUE TITLE
Firefox XULRunner error

### ISSUE THREAD

**Issue by SirMoefe** [sandboxie-plus/Sandboxie#1125]
When I start Firefox in sandboxie plus sometimes the following error appears:

![2021-08-20 08_51_15-Window](https://user-images.githubusercontent.com/56847596/130196541-8db2b67b-c51a-46af-8e98-a8d349e6996a.png)

This error happend already sometimes in older versions of sandboxie plus but not that frequent. Since I updated to version 0.8.8 it happens almost every day.

Anyone else has this problem?

The workaround is to delete the content of the Sandbox.

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 20H2
 - Sandboxie Plus 0.9.3
 - Firefox 91.0.1
 - Windows Defender

**Sandboxie configuration**

My configuration is almost default. I force firefox to start sandboxed and I recover downloaded files immediately.

 
<summary>My initial sandboxie.ini settings</summary>

<details> 
Enabled=y
ConfigLevel=9
AutoRecover=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,4
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
BoxNameTitle=-
CopyLimitKb=81920
ProcessGroup=<Browser>,firefox.exe
ForceProcess=firefox.exe
DropAdminRights=y

</details>

**Comment by isaak654** [comment]
Known issue (never fixed since 2016 or earlier):
https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/searchd528d528.html?keywords=XULRunner

**Comment by Dyras** [comment]
Hello. The issue appears to be that Firefox is updating inside the sandbox. I had this happening for quite some time and I never really did figure out a good way of solving it.

You can disable Firefox updates, and then update Firefox with Ninite, for example.

**Comment by SirMoefe** [comment]
Thanks for the answers! Update outside the Sandbox helped!

**Comment by Dyras** [comment]
@SirMoefe if you want to try a possible fix, add this to your sandbox file:
ReadFilePath=C:\Program Files\Mozilla Firefox
It would be useful to know if it causes Firefox to crash, or if it just stops the updates.

**Comment by SirMoefe** [comment]
@Dyras 
I added the **ReadFilePath** part to the .ini file.

Now Firefox downloads the update and if I click the restart button, the browser closes completely. When I start the browser again I see **Update failed**

What exactly does this ini entry?

**Comment by isaak654** [comment]
> What exactly does this ini entry?

https://sandboxie-plus.github.io/sandboxie-docs/Content/ReadFilePath.html

Another approach is adding a [ClosedFilePath](https://sandboxie-plus.github.io/sandboxie-docs/Content/ClosedFilePath.html) to deny the access for the content of the updates folder:

```
ClosedFilePath=*\Mozilla\updates\*
```

**Comment by isaak654** [comment]
> What exactly does this ini entry?

https://sandboxie-plus.github.io/sandboxie-docs/Content/ReadFilePath.html

Another approach is adding a [ClosedFilePath](https://sandboxie-plus.github.io/sandboxie-docs/Content/ClosedFilePath.html) to deny the access for the content of the updates folder:

```
ClosedFilePath=*\Mozilla\updates\*
ClosedFilePath=*\UpdateLock*
```

Update: I've found out that these lines work too without the previous ClosedFilePath:
```
ReadFilePath=*\Mozilla\updates\*
ReadFilePath=*\UpdateLock*
```

**Comment by mpheath** [comment]
[Policies](https://github.com/mozilla/policy-templates) are a method to stop Firefox from updating. If a policy is setup to prevent updates, then the About Firefox window will state something like *Updates disabled due to policies*. I used it with Firefox 67 to prevent updating to keep XULRunner and all other stuff that were deprecated with later versions. Policies can be set by registry or by json file.

I could think of a script solution to add policies to a sandbox, though perhaps policies can be set by Sandboxie itself, then that might be a cleaner method. Thunderbird, Chrome and perhaps some others I would expect to adhere to policies. This works with the programs rather then blocking them. Just mentioning the idea for consideration if someone wants to try it.
