### ISSUE TITLE
SandMan: sandbox options: window border (unexpected effect)

### ISSUE THREAD

**Issue by antix-skidoo** [sandboxie-plus/Sandboxie#113]
Sandboxie-Plus v0.3.5
Driver: 5.42
Windows 7

bug: Upon choosing "Border Disabled" (and click "Apply"), a confirmation message stating "Sandboxie config has been reloaded" is displayed in the lower SandMan pane. Upon revisiting the sandbox options UI, GeneralOptions tab, the selectbox for "Sandboxed window border" is now blank. However, contrary to the expected result, the behavior is now that of "show border only when window is in focus".

Additionally (and perhaps this is unavoidable), when hovering to raise the autohidden Windows taskbar, the sandboxed window border is painted atop the taskbar.

Separately (as a wishlist consideration) an additional control to choose border _width_ would be a welcome feature. If I could set the width to 1 or 2px, that would be ideal. As is, the seemingly too-wide border obscures part of the the scrollbar of a windowed application and I wind up causing a drag-resized operation instead of achieving a scroll operation. Another regrettable effect of a too-wide border is that it obscures an application's window titlebar text.

**Comment by DavidXanatos** [comment]
Will add that to the next build

**Comment by DavidXanatos** [comment]
as the lastest release includes the width setting I will close this now
