### ISSUE TITLE
"Run Sandboxed" in portable mode

### ISSUE THREAD

**Issue by ltGuillaume** [sandboxie-plus/Sandboxie#1133]
**Describe the bug**
I wish to not have Sandboxie installed all the time (thus run it portable), but still have the ability to run a program sandboxed directly from the context menu. If I add the shell extension via Sandman, at first start via "Run Sandboxed", Sandman opens and installs Sandboxie, but then forgets to run the program. I need to right-click the program and choose "Run Sandboxed" again to actually run it.

**To Reproduce**
1. Set Sandboxie to run as a portable program
2. Add 'Run Sandboxed' to the Explorer context menu (and choose to always use DefaultBox) from within Sandman
3. Close Sandman (thus uninstalling Sandboxie)
4. Right-click on a program and choose "Run Sandboxed"

**Expected behavior**
Sandman opens, installs Sandboxie, _and runs the program sandboxed_.

**System details and installed software (please provide the following information):**
 - W10 Pro x64
 - Sandboxie Plus 0.9.4
 - No antivirus

**Comment by DavidXanatos** [comment]
why dont you want to install permanently when you want to have it permanently installe in the context menu?

**Comment by ltGuillaume** [comment]
> 
> 
> why dont you want to install permanently when you want to have it permanently installe in the context menu?

1. I'm using Sandboxie very irregularly, so I'd like the service and drivers not to be running/installed all the time
2. I'm not actually using the permanent context menu item, but copied over the command line to Total Commander as an "internal association" in the context menu (and assigned a hotkey to it).

**Comment by ltGuillaume** [comment]
This is great, thank you so much!
