### ISSUE TITLE
Error creating shortcut

### ISSUE THREAD

**Issue by JNylson** [sandboxie-plus/Sandboxie#1134]
Error creating shortcut,  does not add correct extension
Windows 10 1909 x64
![Animação](https://user-images.githubusercontent.com/20192563/130671041-c91db5f5-0ea2-478e-8a6d-63e272cdb9ec.gif)

**Comment by bastik-1001** [comment]
I am able to reproduce this with Sandboxie-Plus 0.9.4 64bit on Windows 7 64bit.

It creates a file with the extension shown, but it isn't a shortcut, as windows thinks it would be an executable.

**Comment by DavidXanatos** [comment]
ups indeed, will be fixed in tne next build

**Comment by DavidXanatos** [comment]
https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.5
