### ISSUE TITLE
"System cannot find the path specified" when launching executables

### ISSUE THREAD

**Issue by Enginecrafter77** [sandboxie-plus/Sandboxie#1142]
**Describe the bug**
When you attempt to launch an executable file from overlayed path, it produces "System cannot find the path specified" error message. For example, imagine you downloaded an exe to "C:/Users/%USER%/Downloads/foo-install.exe" using sandboxed browser. You can't obviously see the file outside the sandbox. Inside the sandboxed explorer.exe, you can see the file just fine. But when you try to launch it, it always produces "System cannot find the path specified" error message. A temporarily solution is to navigate to your sandbox folder and run it from under "%SANDBOX%/drives/C/Users/%USER%/Downloads/foo-install.exe". But even this way, some programs continue to give this message since they probably want to access something outside of that path. I believe that this is not the expected behavior.

**To Reproduce**
1. Download a program using sandboxed browser to overlayed path outside the sandbox folder (e.g. user downloads directory)
2. Attempt to launch the exe
3. See the error message

**Expected behavior**
The program should be able to launch from within the overlayed filesystem.

**Screenshots**
[not necessary]

**System details and installed software (please provide the following information):**
 - Windows version: Win10 21H1 (19043.1165)
 - Sandboxie version: Sandboxie-Plus v0.9.4
 - Bug occurs in: Sandboxie-Plus v0.9.4
 - Security software: None (except Windows Defender)
 - Potentially concerning software:
   - Cheat Engine v7.2
   - MSI Afterburner & RTSS
   - Nvidia drivers (no GeForce Exp)
   - OpenRGB

**Additional context**
[not needed]

**Sandboxie configuration**
[see below]

<details>
<summary>Sandboxie sandbox configuration</summary>

```
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=y
DropAdminRights=y
FakeAdminRights=y
CopyLimitKb=81920
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
```

</details>

**Comment by DavidXanatos** [comment]
Unfortunately I can not reproduce this issue right now, strange

**Comment by Enginecrafter77** [comment]
Hmm this is strange, I even tried reinstalling Sandboxie+ but it's still the same. Would it help if I provided some more info? (If so, what exactly)

**Comment by DavidXanatos** [comment]
the issue is that you can not have your sandbox root be a sub fodler of the instalation directory.
so  "C:/ExtPrograms/Sandboxie", and my sandboxes are stored in "C:/ExtPrograms/Sandboxie/Sandboxes will nto work but
C:/ExtPrograms/Sandboxie and C:/ExtPrograms/Sandboxes will work
Cheers
