### ISSUE TITLE
SBIE1222 Error with security token. Couldn't work in windows server 2022

### ISSUE THREAD

**Issue by breaking111** [sandboxie-plus/Sandboxie#1143]
**Describe the bug**
sandboxie(include plus ,older version) can't work in windows server 2022,but windows server 2019 is fine.
SBIE1222 Error with security token:  [C0000058 / 62]
SBIE1222 Error with security token:  [C0000022 / 61]
PID 2228: SBIE2314 Cancelling process Start.exe [2060 / 12]

**To Reproduce**
1. select any exe
2. Click on 'run sandboxed',  ok
3. See error

**Screenshots**
![Screenshot2021-08-28_124612](https://user-images.githubusercontent.com/32029087/131206652-d119a1c1-6fd5-411a-aa34-e3ebd322422e.png)

**System details and installed software (please provide the following information):**
 - Windows Server 2022 Datacenter  21H2  20348.202
 - Sandboxie Plus 0.9.4  .older version too.

**Sandboxie configuration**
<script src="https://gist.github.com/breaking111/af19e9f124392e2d9c96446e93ac5364.js"></script>

**Comment by DavidXanatos** [comment]
Yes I know i ran into the same issue last week, I already have a fix and ti will be deployed next week with the 0.9.5 release

**Comment by DavidXanatos** [comment]
https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.5

**Comment by acidhorse1972** [comment]
Windows 10 Pro is the same way with the newest 1.9.5 - 1.9.7 versions.

**Comment by DavidXanatos** [comment]
the issue was fixed, if there are problems then its a new issue, which exact build of windows 10 is affected?

**Comment by bastik-1001** [comment]
Since, I don't have any relevant information, I can't report if that is a new issue, so I will not open a new issue, unless I am told to.

In the forum, the user "Inside" has reported having a [problem with SBIE1222 on ARM with Windows 10 Pro](https://forum.xanasoft.com/viewtopic.php?f=14&t=652).
