### ISSUE TITLE
Evade Sandboxie Detection

### ISSUE THREAD

**Issue by DavidBerdik** [sandboxie-plus/Sandboxie#115]
I would like to sandbox a program that is designed to not work if executed from within Sandboxie. Is it possible to harden a sandbox to prevent such detection? I suspect that to make this work, the best approach would be to modify all references to Sandboxie by name and then compile it myself, but I do not know enough to say for sure.

**Comment by DavidXanatos** [comment]
what program is that?
I think the best approach would be to try to debug the program and find out how it detects being sandboxed, there are sooo many ways to do that, renaming wont prevent all.

Cheers
David

**Comment by DavidBerdik** [comment]
The program in question is Respondus LockDown Browser. Here's the download link for it: https://downloads.respondus.com/installs/2.0.6.08/961615468/LockDownBrowser-2-0-6-08.exe

Debugging it seems like a logical step to take, but is also kind of a blocker for me, as I have no knowledge of how to debug, and although I would like to learn, I have never found any good resources on how to do so.

**Comment by DavidBerdik** [comment]
For now, I am using a virtual machine to isolate this program, but I am still very interested in migrating it to Sandboxie.

**Comment by deajan** [comment]
Before using debugging techniques, you could start with Microsoft Procmon, which will show you exactly which ressources your program will access while starting.

**Comment by DavidBerdik** [comment]
@deajan That's a very good point! I decided to give it a try, and I am seeing a bunch of registry activity. Unfortunately, nothing which points to Sandboxie detection as far as I can tell. I have attached a copy of the log in case anyone cares to take a look. The dump was made by opening the program, letting it sit for a bit, and closing it.

[LockDown Browser Log.zip](https://github.com/sandboxie-plus/Sandboxie/files/5120410/LockDown.Browser.Log.zip)

**Comment by DavidXanatos** [comment]
are you sure its sbie detection and not just some sort fo incompatibility?
in any case I will take a look....

**Comment by DavidXanatos** [comment]
I only see a crash like sometimes observed with chrome based browsers nothing particularly related to sbie

**Comment by DavidBerdik** [comment]
> are you sure its sbie detection and not just some sort fo incompatibility?
> in any case I will take a look....

I do not know for sure that this program is detecting Sandboxie and not just crashing, but given the nature of what the software does, I suspect that it is detecting it. I know older versions of the software used to work fine using Sandboxie in the past, but that is no longer the case.

https://youtu.be/k95AChgUCXU

**Comment by DavidBerdik** [comment]
Looking at this, I'm curious if I could build a custom Sandboxie version that hides from these tactics: https://security.stackexchange.com/questions/215502/program-detecting-sandboxie-present-how-to-prevent

At the very least, I can probably figure out how to change `SbieDll.dll` and `SbieDll.sys` to be something else, but I am not sure about `IsDebuggerPresent()` or `NtQueryInformationProcess`. I would think it should be possible to intercept them but I do not know.

**Comment by DavidBerdik** [comment]
So I'm making an attempt to rename SbieDll.dll using the Sandboxie code from: https://github.com/sandboxie/sandboxie/

I would prefer to use your version but I am not sure in what way the build process differs. The main issue that I'm running in to is struggling to sign my driver instead. I signed it, but it still only loads if test signing is on.

![image](https://user-images.githubusercontent.com/7663225/93033997-951a8000-f606-11ea-8c83-e138300984f2.png)

When trying to run LockDown Browser in a sandbox using my build, I get an error message this time. Unfortunately I failed to document it. I am not sure if the change in behavior comes from my code alterations or because I'm using less buggy code.

**Comment by DavidXanatos** [comment]
you probably forgot the crossignign certificate, try a command like this:
%TOOL_PATH%\signtool.exe sign /v /ac "%~dp0..\GeoTrust-master\MSCV-VeriSign Class3 Cross Certificate.cer" /s my /n "HT srl" %~dp0\Sandboxie\Bin\x64\SbieRelease\SbieDrv.sys

**Comment by DavidBerdik** [comment]
> %TOOL_PATH%\signtool.exe sign /v /ac "%~dp0..\GeoTrust-master\MSCV-VeriSign Class3 Cross Certificate.cer" /s my /n "HT srl" %~dp0\Sandboxie\Bin\x64\SbieRelease\SbieDrv.sys

This doesn't seem to work. I get this error: SignTool Error: No certificates were found that met all the given criteria.

**Comment by DavidXanatos** [comment]
I also get an error like the later,
can you run e.g. firefox in your build usccessfully?

**Comment by DavidBerdik** [comment]
The Firefox installer did not work inside my build, but I was able to install it normally and then launch it in a sandbox. I am able to launch Chrome in a sandbox as well.

**Comment by DavidBerdik** [comment]
So I am attempting to migrate my changes to your version of Sandboxie, and I'm running in to issues with building the installer. Specifically, the `sys.rc4` file is not being found. When I compile Sandboxie, this file was not generated. I edited the installer script to look for the `sys` file directly instead, but what ends up happening is that the resulting installer has a signed `sys.rc4` file and an unsigned `sys` file even though I did sign the `sys`. Could you tell me what is going on here? I did not see this behavior when working off of the other Sandboxie GitHub repository and cannot figure out what has changed.

**Comment by DavidXanatos** [comment]
the rc4 file is an obfuscated version of the sys file to evade triggering antimalware fools dring dowload already as thay often can unpack installers and look inside.
the rc4 file can be crated using sandman.exe

you can howeever just use the original installer script and an unobfuscated sys file that should also work fine

**Comment by DavidBerdik** [comment]
`sandman.exe`? I'm not sure where that is or what it is. I don't see it in my working directory even though I've done a complete build.

I'm also confused about your explanation about the rc4 file. I only understand that it's obfuscated as a way to reduce the chance that poorly-designed malware will falsely flag the driver because of the signing certificate that was used.

As for the installer script, there is one thing I don't understand: where are some of the variables that are being used getting defined at? For example:

```
    File "/oname=$PLUGINSDIR\KmdUtil.exe" "${BIN_ROOT}\KmdUtil.Exe"
    File "/oname=$PLUGINSDIR\${SBIEMSG_DLL}" "${BIN_ROOT}\SbieMsg.dll"
    File "/oname=$PLUGINSDIR\${SBIEDLL_DLL}" "${BIN_ROOT}\${SBIEDLL_DLL}"
```

I've done a search on the repo for these variables so I can change them, but I cannot find where some of them are getting defined. For example, I don't see where `SBIEDLL_DLL` is getting set to `SbieDll.dll`. I'd like to know though because I want to rename the DLL as well. I have already renamed it in the code, but the installer fails at this step unless I hard code the new name I set for it.

**Comment by DavidBerdik** [comment]
Alright well I've made some progress, but I still clearly have a problem. It seems that despite what I thought was a successful rename of the DLL, it's still hidden away somewhere.

![image](https://user-images.githubusercontent.com/7663225/93655736-55330e80-f9f3-11ea-9261-a0ee69d34e89.png)

**Comment by uk-classy** [comment]
> 
> 
> ~Alright well I've made some progress, but I still clearly have a problem. It seems that despite what I thought was a successful rename of the DLL, it's still hidden away somewhere.~
> 
> ~https://user-images.githubusercontent.com/7663225/93655736-55330e80-f9f3-11ea-9261-a0ee69d34e89.png~
> 
> ~Figured out the DLL problem! New problem though:~
> 
> ~https://user-images.githubusercontent.com/7663225/93656526-1f912400-f9f9-11ea-8d1c-6793798c5d37.png~
> 
> ~The program I'm trying to run has a `LockDownBrowser.dll` file. I renamed `SbieDll.dll` to this name. I'm wondering if that's the source of the problem here. The good news is that this change seems to be enough to get around PaFish detection!~
> 
> Another update: Renaming the DLL worked, but now I'm seeing the memory error again. Do you have any advice on how to proceed with attempting to fix it? I'm not well-versed enough in this kind of development to know. What I find confusing is that the memory error does not always happen. I'm not wondering if this is a legitimate Sandboxie bug now and not an attempt by the program to evade detection.

Would it be possible for you to give some explanation and elaborate more on to how to rename the SbieDLL.dll when compiling the new version?

I'm also having a similar issue with an application refusing to run if sbie.dll is present in the process list of said application.

**Comment by DavidBerdik** [comment]
@uk-classy Unfortunately for the program I am trying to work around, renaming was not enough to fix the problem, but I can name the files you need to look at. Here is a list.

![image](https://user-images.githubusercontent.com/7663225/93717297-eb297f00-fb42-11ea-807a-69713a4e3a01.png)

Go through these files and replace any occurrence of `SbieDll.dll` and `SbieDll.lib` with the new name you wish to use.

**Comment by DavidBerdik** [comment]
Are there any logs generated when a program running in Sandboxie crashes? I'm still trying to work out what's causing this program to crash but haven't had any luck.

**Comment by DavidBerdik** [comment]
@DavidXanatos It's my understanding that in the latest release, debugging features have been added that might make tracking down the source of the problem with using this software a bit easier. How would I go about using it? I haven't had any luck with trying to locate documentation.

**Comment by DavidXanatos** [comment]
@DavidBerdik The debuging features added recently help rather with tracking down compatibility issues.

Did you get sbie to compile? with the recent versions that should be more easy as it now only needs vs 2019 with a up to date WDK/SDK

then get this VS extension: https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool

Start a cmd,exe in sandbox and attach the debugger to it, enabel child process debuging and go to SbieDll!Ordinal1 put a breakpoint there and start somethign from that cmd window does nto mater what you should break in Ordinal1 if that works.

Proceed to your target program you really want to debug.

**Comment by DavidBerdik** [comment]
> Did you get sbie to compile? with the recent versions that should be more easy as it now only needs vs 2019 with a up to date WDK/SDK

I have a version based on one of your older releases, and I actually do use VS 2019 with it. At some point, I will merge your changes in to mine and see if I can make it work. It's highly likely that I will need assistance with this along the way.

**Comment by DavidBerdik** [comment]
Alright, so, step one succeeded. After resolving the merge conflicts, I was successfully able to compile the new build. I haven't put any effort forward towards attempting to debug though. I suppose I should have asked this before, but it kind of slipped my mind: do I have to use Sandboxie Plus for this or can I use the classic one? I've been working with the classic one but I'm not sure if that is appropriate.

**Comment by DavidBerdik** [comment]
Hello everyone, and Happy New Year!

I realize that New Year's Eve (or New Year's Day already, depending on where you are in the world) is an odd time to be hanging out on GitHub, but I finally got a chance to test the use of LockDown Browser with Sandboxie-Plus and the LogApiDll today. I have made a copy of the output in the "Api Call Log" tab and attached it here.

@DavidXanatos, would you be willing to provide some assistance with interpreting the log and potentially identifying where things are going wrong? I haven't had much luck. Thank you

Download link for the log: [ldb_log.txt](https://github.com/sandboxie-plus/Sandboxie/files/5758384/ldb_log.txt)

**Comment by DavidBerdik** [comment]
Since the v5.46.0 release had this entry in the changelog, I decided to try again:

> fixed hooking issues SBIE2303 with chrome, edge and possibly others

Since this software uses Chromium as one of its components, I thought perhaps the problem would be solved. Sadly, it remains. If anyone has the time and knowledge to investigate the log I attached to my previous post, I would greatly appreciate it.

**Comment by DavidBerdik** [comment]
It seems that in more recent releases of Sandboxie+, it is possible to run this software, up to a point. Instead of crashing, it does at least make an attempt to start, but ultimately, you get the following error.

![image](https://user-images.githubusercontent.com/7663225/125122807-e6c75600-e0c3-11eb-8d1e-f9ee5b5eef6e.png)

This screenshot was taken using Sandboxie+, but if you use Sandboxie, you get the same error. The only difference is that instead of instructing you to close `SandMan.exe`, you are instructed to close `SbieCtrl.exe`

There are two interesting things to note about the program: it still blocks you from using `ALT+TAB`, and you cannot take screenshots (the screenshot I shared above was a screenshot taken from a screen recording made with OBS). These capabilities both seem like functions that should be restricted by the sandbox.

Here is the video that I recorded of attempting to use the software. Sandboxie does stop the forced program terminations from happening which is wonderful!


https://user-images.githubusercontent.com/7663225/125129473-84735300-e0cd-11eb-8f51-d9031d51698d.mp4

**Comment by Xlaits** [comment]
Confirming this behavior. Using Sbie+'s ability to hide processes only works for a few programs, and then it tells me to close out SandboxieRpcSs.exe, and hiding this process does not work.

**Comment by DavidBerdik** [comment]
@Xlaits Have you tried doing a custom build that renames the Sandboxie binaries that it detects? I want to try it myself, but I haven't yet.

Also, it seems that the application is able to clear the clipboard even when running in the sandbox. If you take a screenshot, launch the application within the sandbox, and close it, the screenshot gets cleared from the clipboard.

**Comment by Xlaits** [comment]
> @Xlaits Have you tried doing a custom build that renames the Sandboxie binaries that it detects? I want to try it myself, but I haven't yet.
> 
> Also, it seems that the application is able to clear the clipboard even when running in the sandbox. If you take a screenshot, launch the application within the sandbox, and close it, the screenshot gets cleared from the clipboard.

I have not tried this yet.

**Comment by DavidBerdik** [comment]
> I have not tried this yet.

I'm trying to attempt it, but it seems that the method that I used to use for signing the driver no longer works on newer versions of Windows 10, so I'm trying to figure out how to do self-signing.

**Comment by DavidBerdik** [comment]
> I have not tried this yet.

It took me a bit of effort, but I finally was able to bypass it!

**Comment by DavidXanatos** [comment]
So now its no longer detected? was it really only the dll names?

**Comment by DavidBerdik** [comment]
> So now its no longer detected? was it really only the dll names?

Considering that the program actively detects `SandMan.exe`, which I know you introduced to Sandboxie yourself, I believe that the company behind this awful piece of software is actively monitoring this repo and will update their software if they know how I did it. I therefore do not want to share what I did here and will use a more private channel for communicating my methods to you.

**Comment by DavidXanatos** [comment]
i think we can close this issue

**Comment by DavidBerdik** [comment]
In light of the upcoming changes in the next build, I agree.

**Comment by dumpsters** [comment]
Resurecting this because I found another program that detects sandboxie and closes automatically, [Thaiphoon Burner](http://www.softnology.biz/), I've already hidden every sandboxie related .exe for that box but still it detects it, maybe it's recognizing the driver? (is it possible to hide drivers?)

**Comment by DavidBerdik** [comment]
@dumpsters Can you share the `HideHostProcess` configuration for your sandbox?

**Comment by dumpsters** [comment]
> @dumpsters Can you share the `HideHostProcess` configuration for your sandbox?

![hide](https://user-images.githubusercontent.com/12140220/160483358-91bef99a-d0a2-445c-86db-ad9691be3160.png)

**Comment by DavidBerdik** [comment]
@dumpsters I am not sure if this will actually work, but could you try adding `SbieDrv.sys`?

**Comment by dumpsters** [comment]
> @dumpsters I am not sure if this will actually work, but could you try adding `SbieDrv.sys`?

Doesn't seem to work

![hide2](https://user-images.githubusercontent.com/12140220/160495919-297f2f17-f36d-493b-9586-f88e0c21f5b9.png)

**Comment by DavidBerdik** [comment]
@dumpsters Hmmm. I don't have any other ideas unfortunately. Maybe try compiling a custom build of Sandboxie that has the binaries renamed?
