### ISSUE TITLE
Thunderbird 91.0.3 is rendered with Hex Characters when sandboxed

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1156]
**Describe the bug**
Thunderbird 91.0.3 is rendered with Hex Characters when it runs sandboxed. Outside of the sandbox, it works fine.

**To Reproduce**
See https://www.wilderssecurity.com/threads/thunderbird-with-hex-characters.440046

**Additional context**
I'm still on 78.13.0, so I'm unable to reproduce it. However, a number of people is reporting this issue on that thread only for version 91.0.3. Multiple Sandboxie versions are involved like Sandboxie 5.47.1, 5.50.2, 5.51.3, 5.51.4.

**Comment by DavidXanatos** [comment]
There is an easy workaround, add
```SpecialImage=firefox,thunderbird.exe```
to your sandboxie ini

the proper fix will be included in the next build
