### ISSUE TITLE
Sandboxie can't work in Windows 11 22449.1000.

### ISSUE THREAD

**Issue by Aspector1** [sandboxie-plus/Sandboxie#1164]
**Describe the bug**

1. Sandboxie can't work in Windows 11 22449.1000.
2. Start.exe (15988): SBIE2101 Object name not found: \Sessions\1\BaseNamedObjects\SM0:15988:304:WilStaging_02, error CreateMutant (C0000022) access=001F0001 initialized=1
3. PID 3272: SBIE2314 Cancelling process Start.exe [15988 / 7]

**To Reproduce**

1. Select any exe.
2. Click on 'run sandboxed'
3. See the error

**Screenshots**
![Снимок экрана 2021-09-04 025537](https://user-images.githubusercontent.com/84536195/132075378-6e2b8211-0c25-44bd-a368-3d606430d21a.png)

**System details and installed software (please provide the following information):**

- Windows 11 22449.1000
- Sandboxie Plus 0.9.5

**Sandboxie configuration**
Default configuration.

**Comment by DavidXanatos** [comment]
will be fixed in next build,
until then you can add 
```OpenIpcPath=\Sessions\*\BaseNamedObjects\SM*:WilStaging_*```
to your sandboxie ini

**Comment by Aspector1** [comment]
> will be fixed in next build,
> until then you can add
> `OpenIpcPath=\Sessions\*\BaseNamedObjects\SM*:WilStaging_*`
> to your sandboxie ini

Thanks!
