### ISSUE TITLE
Possible loop causing PC to freeze and high CPU usage

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#117]
### Environment
- **OS:** Server 2019 `17763.1397` with latest updates (`KB4565349`, `KB4571462` et al.)
- **Sandboxed programs:** latest versions firefox, telegram, thunderbird,
- Sometimes WSL in background (just opened console).
- Defender removed as a package via DISM.

### Problem description
So far, it has been possible to identify that the problem appears when launching programs in the sandbox and when interacting with firefox.
When starting thunderbird, telegram.
In firefox, when opening a new tab, sometimes when scrolling the page.

The problem is not always frequent, but sometimes it repeats 2-3 times after a reboot.

I will assume that either the last Windows update affects, sometimes there is WSL 1 in the background (just an open console), but the repeated freeze manifested itself after a reboot, moreover, its probability is even higher.

The problem is very similar to winrar.exe, which was given the realtime priority and starting a test in it.

**Comment by Zymlex** [comment]
I suspect there was a conflict with SpyShelter. Even when it was disabled :(

**Comment by DavidXanatos** [comment]
So after SpyShelter got removed its not working fine?

**Comment by Zymlex** [comment]
There were no more freezes after uninstalling SpyShelter. I suspect so far that arose after updating Sandboxie and/or Windows.

**Comment by Zymlex** [comment]
The hang repeated. Was able to reproduce the issue without running the Sandboxie driver.
Probably the problem is due to hardware acceleration and hardware.
