### ISSUE TITLE
[UI] Re-add double clicking on "Run Sandboxed" dialog

### ISSUE THREAD

**Issue by nedsociety** [sandboxie-plus/Sandboxie#1171]
**Is your feature request related to a problem? Please describe.**
The dialog (changed somewhere between 0.8.2 and 0.8.9) has lost the ability to double click an entry on the listbox to run app. It's just annoying to click OK button every time.

**Describe the solution you'd like**
Re-add the double-clicking behavior that redirects as OK button.

**Comment by DavidXanatos** [comment]
will be in the next build
