### ISSUE TITLE
create shortcut unsandboxed [feature request]

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1173]
there are programs that we always use sandboxed, but sometimes we wanna run then outside sandbox:

request:
add an option to create shortcut unsandboxed, these shortcuts will force program to run unsandboxed:

this is necessary for people that always use programs in sandbox and sometimes wanna open them unsandboxed, a shortcut for this would be handy.

thank you in advance

**Comment by isaak654** [comment]
You mean [this](https://sandboxie-plus.github.io/sandboxie-docs/Content/StartCommandLine.html#disable-forced-programs)?

**Comment by diieg707** [comment]
> 
> 
> You mean [this](https://sandboxie-plus.github.io/sandboxie-docs/Content/StartCommandLine.html#disable-forced-programs)?

yes.
both commands do the same thing? **/disable_force** and **/dfp**

**Comment by diieg707** [comment]
another request:
add keyboard shortcut to force open unsandboxed, if we hold it (like shift or ctrl for example), and click a program which is forced IT WILL OPEN UNSANDBOXED.
