### ISSUE TITLE
add highlight to programs forced in sbie [in sandboxie panel]

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1174]
add some kind of highlight to programs that are being forced in sandbox,

for example:
Make it look like they're selected, make text bold and/or with different color etc...

**Comment by DavidXanatos** [comment]
we already have the yellow border, and the window title isn't that enough?
I would be very reluctant to add more intrusive modifications.

**Comment by diieg707** [comment]
> we already have the yellow border, and the window title isn't that enough?
> I would be very reluctant to add more intrusive modifications.

I mean in the sandboxie panel

**Comment by diieg707** [comment]
I mean in the sandboxie panel
![Image 1](https://user-images.githubusercontent.com/54504707/132519942-9ab58013-1775-4e34-bafc-bf4c45297000.jpg)

**Comment by diieg707** [comment]
explaining better:
whenever the option "force into this sandbox" is selected the program is highlighted, similar to this:
![What is new - 1](https://user-images.githubusercontent.com/54504707/132951354-78d971e7-2a69-40b1-a53b-320c926ca3c8.png)

**Comment by diieg707** [comment]
explaining better:
whenever the option "force into this sandbox" is selected the program is highlighted, similar to this:
![procexp](https://user-images.githubusercontent.com/54504707/132951421-785bbe09-7537-4428-824d-aa7e0d980922.png)

**Comment by diieg707** [comment]
for example:
![Image 2](https://user-images.githubusercontent.com/54504707/132951775-6a9d9032-054a-4106-b5de-49810648f32e.jpg)

**Comment by DavidXanatos** [comment]
I see so you want the plus UI to diferentiate between manually started and forces processes

**Comment by diieg707** [comment]
> I see so you want the plus UI to diferentiate between manually started and forces processes

When we select the option "force into this sandbox", the program is highlighted like in the picture

**Comment by diieg707** [comment]
For example: 
I open Firefox.exe in sbie, right click on it and select the "force into this sandbox" option, after that the process is highlighted like in the picture to indicate it always opens in sandboxie.

**Comment by diieg707** [comment]
> I see so you want the plus UI to diferentiate between manually started and forces processes

Basically I want the plus UI to differentiate the forced processed

**Comment by bastik-1001** [comment]
While I don't know how Sandboxie(-Plus) tracks if a process has been forced into the sandbox, if it is possible to use a different color for highlighting those processes, you may want to add the word 'forced' into the status column as well. So that it shows "Running, forced (Processname)"

**Comment by DavidXanatos** [comment]
Yea I could add that info to the column, there should be a flag in the driver I could query to get this info

**Comment by diieg707** [comment]
> While I don't know how Sandboxie(-Plus) tracks if a process has been forced into the sandbox, if it is possible to use a different color for highlighting those processes, you may want to add the word 'forced' into the status column as well. So that it shows "Running, forced (Processname)"

If you take a look at the program process explorer they have this highlight feature in their UI

**Comment by DavidXanatos** [comment]
column info will be in included in the next build 0.9.7

**Comment by diieg707** [comment]
Thanks
