### ISSUE TITLE
Hardware acceleration support for Steam client

### ISSUE THREAD

**Issue by LexLonbray** [sandboxie-plus/Sandboxie#118]
Hello, is it possible to allow sandboxed Steam client to take advantage of "GPU accelerated rendering in web views" setting? There is a significant performance loss due to this option not working under Sandboxie, scrolling profiles for example produce a lot of stuttering. Interestingly enough, Chrome browser, which Steam web view is based on afaik, doesn't have the same issue.

**Comment by DavidXanatos** [comment]
its probably possible you just need to allow the right exceptions the chalange is to find what exactly needs to be unblocked.

**Comment by LexLonbray** [comment]
I'm getting this an error when starting Steam with acceleration enabled:
`SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1 by process: 83528 (steamwebhelper process id)`
The error isn't there with acceleration disabled.
Could this be any useful?

**Comment by NewKidOnTheBlock** [comment]
@LexLonbray
Is this still the case?
I just tried running Steam in a SB and successfully turned GPU on acceleration:
![steam gpu acceleration](https://user-images.githubusercontent.com/12411527/106042575-84623680-60dd-11eb-8820-5fca9e982435.png)

**Comment by DavidXanatos** [comment]
simmilar issues were fixed recently for chrom so this os probably fixed as well
