### ISSUE TITLE
It's a simple question. Where is the menu? Delete Settings

### ISSUE THREAD

**Issue by oklokl** [sandboxie-plus/Sandboxie#1183]
https://sandboxie-plus.com/sandboxie/deletesettings/

![11](https://user-images.githubusercontent.com/1571600/132974042-6e781458-ac83-49d1-b1a2-268b5fb4176b.png)
I can't see it in the new version.

Sandboxie Control > Sandbox Settings > Delete:
Sandboxie Control > Sandbox Settings > Delete > Command: RMDIR (The old version.)
(I want to remove process debris automatically. I'd like to set "Don't save my records" as a setting.)
I want to use it. Automatically.
If I don't have this function, I'd like to suggest it.

Thank you.
I'm deleting it manually right now. :(
(inconvenient)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2).
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2).
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**Additional context**

**Sandboxie configuration**
If applicable, consider to attach your sandboxie.ini configuration by copying the content at https://gist.github.com and sharing the resulting link here. If you decide to paste the configuration directly here, make sure to use the backticks around strings, like in this working example:

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]

.....

[UserSettings_175D0429]

.....

[DefaultBox]

.....

```

</details>

**Comment by bastik-1001** [comment]
You can find this option in the general options of the sandbox under 'File Options'. You can see the file options in your screenshot at the top.

There you can find 'Box delete options' and the setting 'Auto delete content when last sandboxed process terminates'.

**Comment by oklokl** [comment]
Thanks a lot.
Cheers. :)
