### ISSUE TITLE
Sandboxie-Plus, Filter to show only active boxes in the main window

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#1185]
**Is your feature request related to a problem? Please describe.**
I have defined some boxes, of which not all get used at the same time, but right now the main window of Sandboxie-Plus shows all of them, which by default is how it should be.

**Describe the solution you'd like**
Some sort of filter, like a button or menu entry to only show boxes with some processes in it.  This filter may reset each time Sandboxie-Plus gets restarted to avoid confusion.

I expect this to be straightforward, if the filter is active, only boxes with a process running will be shown. While the filter is disabled every box is shown.

**Describe alternatives you've considered**
Some general way to filter for arbitrary properties, like running, empty, isolation-type. This is of course far more complicated and therefore seems to be error-prone.

**Comment by DavidXanatos** [comment]
you can achive this already now by Pressing Ctrl+F and typing Running, uncheck highlight
than onyl runing processes will be shown and the boxes they are in.

**Comment by bastik-1001** [comment]
This is a good way to filter it. I had not known that this is possible. Consider this to be implemented. :)
