### ISSUE TITLE
Custom Application Sandboxing Order

### ISSUE THREAD

**Issue by SiNONiMiTY** [sandboxie-plus/Sandboxie#1189]
Is there a way to prioritize on what sandbox an application would run if the said application is defined in multiple sandboxes?

A scenario for this is as follows:
- I have a standalone Sandbox named "Browser" for my browsers.
- By default, I set Sandboxie to run the contents of the "Downloads" folder in the "DefaultBox"
- When I download and open .HTML files located in "Downloads" it will execute my browser in the "DefaultBox"
- With that, even if I set the "Downloads" location to execute in "DefaultBox", I would like the browser to still run on the "Browsers" sandbox.

I would like to propose that we should be able to define a custom order to execute applications in a given sandbox if it is defined on multiple sandboxes. Is this feasible? Would this affect security?

**Comment by SiNONiMiTY** [comment]
My suggestion for this is, create a separate section on the Global Options that contains a list of programs/locations and on what sandbox they should be run. This list should also contain the order/priority. If there are no matches found, they will be executed on a "per-sandbox" configuration basis.

**Comment by DavidXanatos** [comment]
So what you basically want to do is to have forced folders priority over forced programs, is that right?
I mean you won't set two sandboxes to run program.exe but only one, you may howeever asign different folders to different boxes.

With an full priority model you could in special cases have the force program again overrule forced fodlers but do you need that?

**Comment by SiNONiMiTY** [comment]
Hi @DavidXanatos,

Thanks for noticing this thread. Apologies if I was not clear on this feature request.

What I was trying to suggest is that, in the event that there are conflicting sandbox rules, we should be able to prioritize on what sandbox a forced process or forced program should go.

Assume the following settings for my scenario:
- "Downloads" folder is forced to "DefaultBox" so that programs accidentally executed on the downloads folder will have some sort of protection in the event that these files are malicious.
- "firefox.exe" process is forced to "Browser" sandbox.

In my case, I use my browser (Firefox) as a PDF Viewer. Take for example, I browse the PDF file and open it on the "Downloads" folder. Since the "Downloads" folder is forced to the "DefaultBox" sandbox, Firefox would then be launched under "DefaultBox" instead of the "Browser" sandbox.

**Comment by DavidXanatos** [comment]
Starting with build 1.0.8 you have the options BreakoutProcess=program.exe and BreakoutFolder=C:\SomePath, see
https://github.com/sandboxie-plus/Sandboxie/issues/1500

You can configure firefox.exe to be a BreakoutProcess=firefox.exe and have it set as ForceProcess=firefox.exe for a specific sandbox, configured this way, firefox will be able to break out of any box with the break out entry and will be forced into the box with teh force entry.
This is not a full priority system but should cover most use-cases already.

**Comment by SiNONiMiTY** [comment]
@DavidXanatos now that I am able to test this:

```BreakoutProcess=firefox.exe```

Works perfectly when declared on the Global level.
