### ISSUE TITLE
immediate recovery/file recovery icon not showing on taskbar, plus 0.9.6

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1195]
immediate recovery/file recovery icon not showing on taskbar

**Comment by DavidXanatos** [comment]
??? explain what icon should show? what does it do and indicate?
Esplain the exact desred behavioure,
kep in mind that i don't use the recovery stuff at all for myself.

**Comment by DavidXanatos** [comment]
it it supposed to always be always on top?

**Comment by diieg707** [comment]
> it it supposed to always be always on top?

Yes sir, if you check classic version you'll notice immediate recovery window always stays on top if click out of its window.

**Comment by diieg707** [comment]
@DavidXanatos did you implement the always on top behavior and the "don't prompt again check box in immediate recovery?
