### ISSUE TITLE
Cant terminate a crashed program, "A device attached to the system is not functioning"

### ISSUE THREAD

**Issue by stubmirror** [sandboxie-plus/Sandboxie#1198]
v0.9.6 also experienced it in earelier versions.
Sometimes when a program crashed inside of the sandboxie there is no way to close or terminate it other than rebooting the pc, ive tried taskmgr/terminate every combo i can think off. but sandboxie just returns a error and leaves the program and window open. I also tried Maintanance-disconnect and stop all, neither is able to terminate the programs
Error Status 0x c0000001 (A device attached to the system is not functioning)
anyone have an idea on how to terminate this without rebooting?

**Comment by isaak654** [comment]
- What is your Windows edition and version? (i.e. Windows 10 Pro 20H2).
 - Please mention the software which crashed and provide a download link
 - Please mention any security software running in the background, even if the real-time protection is disabled.
