### ISSUE TITLE
win10 2004 can't input Chinese 

### ISSUE THREAD

**Issue by carlsue** [sandboxie-plus/Sandboxie#120]
version:5.42.1 64bit
os:window 10 10.0.19041 暂缺 Build 19041
issue: can't input Chinese with integration inputmethod。

**Comment by zongren** [comment]
打开兼容模式可解决

> version:5.42.1 64bit
> os:window 10 10.0.19041 暂缺 Build 19041
> issue: can't input Chinese with integration inputmethod。

![批注 2020-09-11 112629](https://user-images.githubusercontent.com/4525819/92852886-cb4ada80-f421-11ea-87cb-ed0f3c80f227.png)

**Comment by Xegony** [comment]
> 打开兼容模式可解决
> 
> > version:5.42.1 64bit
> > os:window 10 10.0.19041 暂缺 Build 19041
> > issue: can't input Chinese with integration inputmethod。
> 
> ![批注 2020-09-11 112629](https://user-images.githubusercontent.com/4525819/92852886-cb4ada80-f421-11ea-87cb-ed0f3c80f227.png)

you can also add \BaseNamedObjects\[CoreUI]-* to IPC direct access list.

**Comment by DavidXanatos** [comment]
try adding 

OpenIpcPath=\BaseNamedObjects\[CoreUI]-*

to your sandboxie ini

**Comment by skygunner** [comment]
It should be **\BaseNamedObjects\[CoreUI]-PID***

Right-click on Sandboxie icon, then : 
Sandbox > Defaultbox > Sandbox Settings > Resource Access > IPC Access > Direct Access
Click Add

Or if you are using Rime input method, you can also do this instead:
add this to file , full access:
**\Device\NamedPipe\your-username\WeaselNamedPipe**

**Comment by DavidXanatos** [comment]
the compatybility templates will include this setting for win10

**Comment by skygunner** [comment]
Thanks bro, issue 39 and 88 should be same issue, they can be closed I think.

**Comment by Lyoko-Jeremie** [comment]
this not work for me:

```
OpenIpcPath=\BaseNamedObjects[CoreUI]-*
```


but this work for me:

```
OpenIpcPath=\BaseNamedObjects\[CoreUI]-PID*
```

i add it to my config ini ```[GlobalSettings]``` segment. then all work well.

thank you every one~

**Comment by BowmanChow** [comment]
@skygunner could please tell me what is the `NamedPipe` and `WeaselNamedPipe` and how to find them?

I tried to add
```
OpenIpcPath=\Device\NamedPipe\BBBBB\WeaselNamedPipe
```
or
```
OpenIpcPath=\DESKTOP-XXXXX\NamedPipe\BBBBB\WeaselNamedPipe
```
 to my config ini `[GlobalSettings]` but neither of them work. While `DESKTOP-XXXXX` is my computer's name and `BBBBB` is my user name.

I am just wondering whether I should replace the `NamedPipe` and the `WeaselNamedPipe`  with something
