### ISSUE TITLE
Issues with Sandboxie running with Cylance installed - MemDef error

### ISSUE THREAD

**Issue by souldjer777** [sandboxie-plus/Sandboxie#1201]
**Describe the bug**
Issues with Sandboxie running with Cylance installed - MemDef error

**To Reproduce**
1. Open Sandboxie
2. Go to 'Run > Run Program' (Any program)
3. Error - See Error

Error:
10:50:01.242   Sbie Directory: C:\Program Files\Sandboxie-Plus                                                                                          
10:50:01.242   Loaded Config: C:\WINDOWS\Sandboxie.ini                                                                                                  
10:50:08.937   Start.exe (10564): SBIE2101 Object name not found: \Device\NamedPipe\**MemDef,** error CreateFile (C0000022) access=0012019F initialized=1  
10:50:08.941   PID 8828: SBIE2314 Cancelling process Start.exe [10564 / 7]      

**Expected behavior**
Expecting Sandboxie to be able to start any application selected to be run successfully.

**System details and installed software (please provide the following information):**

 - What is your Windows edition and version?
    Windows 10 Pro 2004 OS Build 19041.1165

 - What is your current Sandboxie edition and version?
    Sandboxie 9.5

- Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
   Security team wanted us to reach out to the developer to resolve issue with Cylance.
   "Ultimately it'll probably come down to your app vendor figuring out why their app is crashing. Cylance isn't going to be able to determine what part of their code is failing since they didn't write it, and they won't try to reverse engineer it for us." - Security Dept.

 - Please mention any security software running in the background, even if the real-time protection is disabled. 
    Cylance Protect Version 2.1.1564.40

**Additional context**
Fresh install - trying to run first sandboxed application

**Sandboxie configuration**
No changes made - clean install

FIX FOR THIS ISSUE - 2021/09/15

	1. Using the Registry Editor, go to HKEY_LOCAL_MACHINE\SOFTWARE\Cylance\Desktop.
	2. Right-click Desktop, click Permissions, then take ownership and grant yourself Full Control. 
	(EXAMPLE: Changed owner from SYSTEM to user001  )
	3. Right-click Desktop, then select New > Binary Value.
	4. For the name, type CompatibilityMode.
	5. Open the registry setting and change the value to 01.
	6. Click OK, then close Registry Editor.
	7. Reboot

**Comment by DavidXanatos** [comment]
since tehre is no reply and i dont have the problematic app i have to close this
