### ISSUE TITLE
Sayatoo Subtitle Maker: "This application cannot run under a virtual machine"

### ISSUE THREAD

**Issue by InfernalArmageddon** [sandboxie-plus/Sandboxie#1204]
Hi there, 
I am getting "This application cannot run under a virtual machine" running 64 Bit versions of (sandboxie classic 5.45.2-5.51.6, sandboxie plus 0.9.6) for "Sayatoo Subtitle Maker v2.3.7.5529" upon starting after installation.
I am using Windows 7 Ultimate SP1 x64.
Are there any ways to make an option to make programs think that they are not inside a virtual machine?
Installer is here:
https://drive.google.com/file/d/1lZquRbC-QhwraUn47G6TL4YkrqEr6pol/view?usp=sharing

Thank you
![Sayatoo](https://user-images.githubusercontent.com/90867032/133673270-5ecee8e2-4da4-483e-bdf6-9e3cbd41ac1f.jpg)

**Comment by DavidXanatos** [comment]
such functionality is rather out of teh scope of this project
