### ISSUE TITLE
Sayatoo Subtitle Maker: "This Windows Installer Package has Problems, parts of the default installation process didn't complete as expected. Please contact your support staff or program publisher" at close to end of program installation

### ISSUE THREAD

**Issue by InfernalArmageddon** [sandboxie-plus/Sandboxie#1205]
Hi there,
I am getting "This Windows Installer Package has Problems, parts of the default installation process didn't complete as expected. Please contact your support staff or program publisher." 
Running 64 Bit versions of (sandboxie classic 5.51.3-5.51.6, sandboxie plus 0.9.6) for "Sayatoo Subtitle Maker v2.3.8.5568", error comes up at close to the end of installation.
I was able to install it successfully in sandboxie classic v5.49.8 64 Bit
I am using Windows 7 Ultimate SP1 x64.
Installer is here:
https://drive.google.com/file/d/1X5v06IDuYcvLOatawegEIok5lUBTkA6f/view?usp=sharing

Thank you
![WIC](https://user-images.githubusercontent.com/90867032/133676317-16baee91-f34d-4df4-a0cf-0aadb03cb2e4.jpg)

**Comment by isaak654** [comment]
Could you attach your sandboxie.ini configuration?

**Comment by InfernalArmageddon** [comment]
Here is my sandboxie.ini configuration:

[GlobalSettings]

Template=Kaspersky
Template=nVidia_Stereoscopic3D
Template=7zipShellEx
Template=AdobeAcrobatReader
Template=OfficeLicensing
TemplateReject=ComodoInternetSecurity
FileRootPath=C:\Sandbox\%SANDBOX%
SeparateUserFolders=n
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n

[UserSettings_086001AA]

SbieCtrl_UserName=home
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_ShowWelcome=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=590,170,709,494
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_TerminateWarn=n
SbieCtrl_TerminateNotify=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_BoxExpandedView=,
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[UserSettings_4BC00582]

SbieCtrl_UserName=administrator
SbieCtrl_ShowWelcome=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=200,150,1237,632
SbieCtrl_ActiveView=40021

[DefaultBox]

Enabled=n
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[Chromium]

Enabled=y
BorderColor=#00ffff,ttl,6
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=81920
ClosePrintSpooler=y
ShowForRunIn=n

[Hardened]

Enabled=y
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
ClosePrintSpooler=y
BoxNameTitle=n
CopyLimitKb=81920
DropAdminRights=y

I've tried to use a legacy sandbox mode, and turning things on and off in settings related to msi installer, but no help so far.
Thank you.

**Comment by isaak654** [comment]
It runs fine for me if I add `MsiInstallerExemptions=y` to my box, and the installer will continue to install without stopping.

In Plus, you can enable it on the Sandbox options -> General Options -> Box Options -> Allow MSIServer to run with a sandboxed system token and apply other exceptions if required

**Comment by isaak654** [comment]
If I add `MsiInstallerExemptions=y` to my box, the installer will continue to install without stopping:

```
[DefaultBox]

Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=81920
MsiInstallerExemptions=y
```
Win7 SP1 x64 clean install with no third-party apps, Sandboxie Plus 0.9.6, Win Defender

In Plus, you can enable it on the Sandbox options -> General Options -> Box Options -> Allow MSIServer to run with a sandboxed system token and apply other exceptions if required

**Comment by InfernalArmageddon** [comment]
When i uncheck Allow MSIServer to run with a sandboxed system token and apply other exceptions if required, I get unable to start windows installer error at the beginning of installation. 
With Allow MSIServer to run with a sandboxed system token and apply other exceptions if required enabled, i get the error mentioned in first post at the very end of installation, unable to complete installation.
However, using sandboxie classic 5.48.9 x64 can complete the entire installation with nothing to add or change in settings, i am not sure if versions between 5.48.9 and 5.51.2 can complete as well.

Thank you.

**Comment by isaak654** [comment]
It looks like there is something on your system that interferes with `MsiInstallerExemptions=y` option.

1) Do you have the same program installed also outside of the sandbox?
2) Could you try all the releases in the middle to know exactly which release broke the compatibility for you?
3) Please report also any security software running in the background, even if the real-time protection is disabled.

**Comment by InfernalArmageddon** [comment]
I remember in 5.49.8 x64 it does a lot of registry modifications in a cmd window, but too fast too see what it did. So the error might be related to newer version of sandboxie blocking those registry additions/changes.

1. I don't trust this program at all, so I wont install it unsandoxed because it has a lot of behidn the scene installations when I observed it in sandboxie.
2. I will try to do that
3. Currently running Kaspersky Security Cloud v21.2.16.590c with real time protection enabled. But since it installed successfully in version 5.49.8 x64, I doubt antivirus is causing the error. Must be some changes in between 5.50.0-5.51.3 that caused it.

**Comment by isaak654** [comment]
> 2. I will try to do that

That would increase the chance for the maintainer to take a look at this issue.

> 4. Quick question, are you able to start up the program in the sandbox after completing the installation? Mine crashes upon starting with nothing happening after starting it in 5.49.8. Might be related to a virtual machine check error that I mentioned in my other post here:
>        [Sayatoo Subtitle Maker: "This application cannot run under a virtual machine" #1204](https://github.com/sandboxie-plus/Sandboxie/issues/1204)
> 

On my 0.9.6 install, the process SayaSub2.exe is automatically terminated soon after the sayatoo logo without receiving any error dialog.

**Comment by InfernalArmageddon** [comment]
I followed your advice and tested all the builds in between and found the following problems:
As soon as I upgrade to sandboxie v5.50.0 x64 the error mentioned in post #1 appears.
I then revert back to 5.49.8 x64 and surprisingly it started happened as well, and I tried every single one before 5.49.8 up to 5.45.0 x64, same thing. I tried doing fresh installs and removing sandboxie.ini, or pasting my original working 5.49.7 sandboxie.ini and for some reason that error doesn't go away. So I am guessing v5.50.0 left something in the registry or system that wasn't completely removed, so no matter what newer or older version i tried, it gives the same error. I also tested this on my Windows 10 LTSC 2019 x64 machine and same results. 
I also noticed that it was able to install everything with the error, just not launching.
The last line in the cmd window mentioned something about "deleting backup files" before the error occurs, if that helps.

Thank You.

**Comment by hansnolte** [comment]
I think I have the same problem.
![installer-service](https://user-images.githubusercontent.com/7922627/144392962-cb5fa954-b90f-4625-a2e1-be80312f47d7.jpg)

"_The Windows Installer service could not be accessed. 
This can occur when Windows is running in Safe Mode or when the Windows Installer is not installed correctly. 
Contact support personnel for further assistance._"

Win 10 - 21H2
Sandboxie-Classic-x64-v5.55.0

`
[GlobalSettings]

Template=VirtualDesktopManager
Template=RpcPortBindings
Template=Windows10CoreUI
Template=FireFix_for_Win7
Template=Kaspersky
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=E:\Sandbox\%USER%\%SANDBOX%
CopyLimitKb=-1
MsiInstallerExemptions=y

[DefaultBox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Enabled=y
NotifyInternetAccessDenied=y
ProcessGroup=<InternetAccess>,firefox.exe,firefoxportable.exe,googlechromeportable.exe,chrome.exe
ClosedFilePath=!<InternetAccess>,InternetAccessDevices

[UserSettings_1F3A0369]

SbieCtrl_UserName=sysadmin
SbieCtrl_NextUpdateCheck=1638461230
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_ShowWelcome=y
SbieCtrl_WindowCoords=404,286,1237,609
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_AutoApplySettings=n
SbieCtrl_HideMessage=2203,*GUIPROXY_00000001; MsgId: 12 - TOTALCMD64.EXE [C0000024]
SbieCtrl_HideMessage=2203,*GUIPROXY_00000001; MsgId: 13 - TOTALCMD64.EXE [C0000024]
SbieCtrl_HideMessage=2103,ysdrv [Internet]
SbieCtrl_HideMessage=2221,msiexec.exe [DefaultBox]
SbieCtrl_HideMessage=2203,*GUIPROXY_00000001; MsgId: 13 - ScreenToGif.exe [C0000024]
SbieCtrl_HideMessage=2103,ysdrva [Internet]
SbieCtrl_HideMessage=2221,moi_commandprocessor.exe [DefaultBox]
SbieCtrl_HideMessage=2205,ConsoleInit (C00000D4)
SbieCtrl_HideMessage=2203,*GUIPROXY_00000001 - TOTALCMD64.EXE [C0000024]
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_TerminateNotify=y
SbieCtrl_TerminateWarn=y
SbieCtrl_ExplorerNotify=y
SbieCtrl_ExplorerWarn=y
SbieCtrl_EditConfNotify=y
SbieCtrl_ReloadConfNotify=y
SbieCtrl_HideWindowNotify=y
SbieCtrl_ProcSettingsNotify=y
SbieCtrl_SettingChangeNotify=y
SbieCtrl_ShortcutNotify=y
SbieCtrl_ShouldDeleteNotify=y
SbieCtrl_BoxExpandedView=,

[Internet]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
`

**Comment by DavidXanatos** [comment]
with the option checked to allow extra permissions for msi installer it installs just fine
