### ISSUE TITLE
Neat Download Manager: "SSL HandShake Error" When Downloading From Github/Other Sites

### ISSUE THREAD

**Issue by InfernalArmageddon** [sandboxie-plus/Sandboxie#1206]
Hi there, 
I am getting "SSL HandShake Error" running 64 Bit version of (sandboxie plus v0.9.6) for "Neat Download Manager v1,3.24" upon downloading any files from github/random sites.
On certain sites it downloads fine, but 100% error on github and sometimes other sites.
It was working fine with Sandboxie Classic v5.51.3 64Bit.
I am using Windows 7 Ultimate SP1 x64
Program is here:
https://drive.google.com/file/d/1kJ5hna8lowUSKjbuIMwiNxSApPktZVJV/view?usp=sharing
Test error link from sandboxie plus github:
https://github.com/sandboxie-plus/Sandboxie/archive/refs/tags/0.9.6.zip

Thank you

Screenshot of error:
![SSL](https://user-images.githubusercontent.com/90867032/133678727-d636e40a-0e91-44dd-ad14-3ec0f1c3fa94.jpg)
Neat Download Manager Error Log:
![SSL Log](https://user-images.githubusercontent.com/90867032/133678777-924077f1-a156-4ef3-825a-0f1f32e3b034.jpg)

**Comment by DavidXanatos** [comment]
Hmm if that worked and now does not thats not cool, I'll look into it to fix it asap

**Comment by DavidXanatos** [comment]
I tested with the latest sbie build on windows 10 and it works fine now
