### ISSUE TITLE
Unable to run software that needs driver installed/loaded (eg. virtualbox/android emulators): "SBIE2103 Denied attempt to load system driver"

### ISSUE THREAD

**Issue by InfernalArmageddon** [sandboxie-plus/Sandboxie#1207]
Hi there,
I was wondering if there is anyway to run virtual box or android emulators in sandboxie? I've tried many different combinations of installing manually and everytime the programs will terminate at the end when installing/loading drivers with "SBIE2103 Denied attempt to load system driver". In older versions of sandboxie there is this command for sandboxie.ini: BlockDrivers=n 
Is there any work around since it would be great to run software with driver support with an option to allow in settings (box/program individual setting/temporary permissions).

Memu Android Emulator offline installler to test:
https://www.memuplay.com/download-en.php?file_name=Memu-Setup&from=offline_installer

Thank You

Error at End Of Installation:
![SS A](https://user-images.githubusercontent.com/90867032/133682275-6f686229-f8f4-4520-9e08-47242fccd02a.jpg)
Error upon starting program:
![SS B](https://user-images.githubusercontent.com/90867032/133682299-39d0dfe1-8bb9-4910-aa6b-f6313268ee09.jpg)
Deprecated command: BlockDrivers=n
![Drivers B](https://user-images.githubusercontent.com/90867032/133681441-c21add1f-3bce-49fd-9ed3-ca11073b8f43.jpg)

**Comment by DavidXanatos** [comment]
Why would you want that?
I mean if you allow a software to load a driver than you are at its mercy sandboxie wont protect you if the proces wants to do something bad?

Are android emulators generally so messy that you need tom compartmentalize it with sandboxie to keep your system clean?

What you could try is to install only the driver by hand outside of sandboxie and start it, find out what IPC or device paths it uses and open those paths in the resources options.

**Comment by DavidXanatos** [comment]
Using a box in App COmpartment mode available since the 1.0x line of builds you shouldbe able to break alls ecurity and load a driver if you must

**Comment by isaak654** [comment]
#3680
