### ISSUE TITLE
Network access restriction crashes sandboxed app, but disable network device works fine

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#121]
Some sandboxed applications crash when the sandox restricts network access. However, when instead disabling the actual network device outside the sandbox, the sandboxied application runs just fine.

This is a recurring issue with a number of applications and prevents running untrusted applications inside sandboxie without actually disabling the real network device. Personally, this is one of the key features I'd like to see changed with Sandboxie.

The issue can be reproduced with "LR Timelapse Pro" trial, but is an issue affecting a range of applications.

Reproduce:
* Download "LR Timelapse Pro" version 5.4.0 from https://lrtimelapse.com/download/  (SHA256: 1A58CAC02B5DF044D4599602D57973BBDA87649CBB9D77E2F82FF948FD77CDE3.
* Download SandboxieInstall64-v5.42.1.exe
* Start Windows Sandbox as a clean test env (running Windows 10 x64 v. 10.0.19041
* In Windows Sandbox install Sandboxie
* In Sandboxie in default sandbox, install LRTimelapse Pro
* Start the application. The application starts as expected. Exit the application.
* In Sandboxie, disable Network Access (Restrictions > Internet Access)
* Start the application. Issue: The splash screen briefly shows then the application exits silently.
* In Sandboxie, re-enable Network Access
* In Windows Control Panel, disable the network device (Control Panel > Network and Internet > Network Connections > Disable Network Device
* Start the application. The application starts as expected.

**Comment by typpos** [comment]
I just found related #116 Ability to block network access. Doh!

**Comment by AqlaSolutions** [comment]
Yep, please consider other options to block internet access as many apps just crash when they can't create a socket instance at all.

**Comment by DavidXanatos** [comment]
further discussion on sandboxie's networking aspects please in issue #894
