### ISSUE TITLE
Problem with NSIS based installers

### ISSUE THREAD

**Issue by ikassaki** [sandboxie-plus/Sandboxie#1218]
When trying to run the installer of [Udeler](https://github.com/FaisalUmair/udemy-downloader-gui) software available on GitHub, I get this error.

![image](https://user-images.githubusercontent.com/17125244/134152443-34f1ff3a-1764-4496-93ad-137ceeafe559.png)

According to this [page](https://www.bleepingcomputer.com/forums/t/635376/cant-initialize-plug-ins-directory/), it looks like this error is prompted for

> The error message is shown when an installer based on NSIS tries to access the TMP directory, and fails to do so. 

So I tried providing access to the temp folder by using the sandbox options:

![image](https://user-images.githubusercontent.com/17125244/134152305-0222e668-eb18-42fb-9bf5-0d3157cd06e6.png)

But then I get this error.

![image](https://user-images.githubusercontent.com/17125244/134152142-dfff79c3-f01d-49a7-8235-3c1d2f718c64.png)

I am wondering why such errors show up. Isn't sandboxie supposed to sandbox all the disk access? What can I do to solve this problem?

**Comment by DavidXanatos** [comment]
on my test VM it installs just fine, are you using the latest sbie release 0.9.6?

**Comment by NMHy8C** [comment]
0.9.6 works fine, at least for me. But all the 0.9.7 builds seem to have similar issues. If you want to run sandboxed installers, the installation failed.

**Comment by NMHy8C** [comment]
Hi David,

Problem solved:
1. Reinstall 0.9.7e
2. Delete the old ini file and let Sandboxie create a new one.
3. Enable Compatibility - Default RPC Port Bindings

Thanks a lot.
