### ISSUE TITLE
some installers problems

### ISSUE THREAD

**Issue by dxq3** [sandboxie-plus/Sandboxie#1219]
1. (https://www.softpedia.com/get/Multimedia/Graphic/Graphic-Editors/Affinity-Designer.shtml)
Error message "Windows Installer could not be accesed"
2 (https://files.kompas.ru/download/sduser371/KOMPAS/v20/x64/KOMPAS-3D_Viewer_v20_x64.zip)
Error message "КОМПАС-3D Viewer v20 x64 не предназначен для использования в данной операционной системе"

win 10 v21382.1, sandbox v0.9.6

P.S I don't need this programs in my sandbox and posted this info just for future sandboxie improvment

**Comment by DavidXanatos** [comment]
try this option:

![grafik](https://user-images.githubusercontent.com/3890945/134312760-35236c3a-05f9-4e57-91a9-09cd233d0a0b.png)

with that it works for me
![grafik](https://user-images.githubusercontent.com/3890945/134312924-e306a501-6879-4af5-8091-60075c892741.png)
