### ISSUE TITLE
Sandboxie Plus - missing explorer right click - Run Sandboxed?

### ISSUE THREAD

**Issue by tutak-kat** [sandboxie-plus/Sandboxie#122]
Hi,
I installed SandboxieInstall64-v5.42.1 and right click menu in explorer is there.
Then I removed that version and installed Sandboxie-Plus-x64-v0.3.5.exe and there is no menu anymore?
Also in that version I was unable to change default? black box around sandboxed program. I choose for ex. yellow but when I pressed Apply or OK colour returned to black.
Also some browsers give me error - "Initialization of the dynamic link library c:\.........\Sbiedll.dll failed. The process is terminating abnormally". 
Win 7 x64.
Is there any instructions how to correct this behaviour?
Thanks

**Comment by FrogsInSpace** [comment]
Had the same problem after Sandboxie plus installation

Solution is easy:

- Launch the classic SbieCtrl.exe from your Sandboxie installation folder 
- from the Menu pick Configure->Windows Shell integration
- Disable "Add right-click action .... " checkbox
- Press OK button
- open menu Configure->Windows Shell integration once again
- Enable  "Add right-click action .... " checkbox
- Press OK button

this steps solved it for me ...

**Comment by tutak-kat** [comment]
Thanx for instruction, will try it - regarding black (default) color of sandboxie window can you change it?

Regarding sandboxie errors with this latest version I still have the same problems..... it looks like that all firefox based Quantum? engine browsers are not working for me for ex. icecat 78.2; iceveasel 80.0.1; torbrowser 10.0a6, however waterfox classic, palemoon, basilisk, vivaldi just works fine - win7 x64.

Is it just me or someone else have the same problems?

**Comment by tutak-kat** [comment]
Solution for right click as provided - worked, also colour can be adjusted that way,.

With plus version  I just can't run anything sanboxed so I deinstalled plus version, rebooted and instaleled again SandboxieInstall64-v5.43 and now I can't run anything in sandbox and constantly getting errors like this:


The instruction at 0x7739c476 referenced memory at 0x00000008. The memory could not be written.
Click on OK to terminate the program

SBIE2224 Sandboxed program has crashed: basilisk.exe [DefaultBox] by process: 2892
SBIE2224 Sandboxed program has crashed: SandboxieRpcSs.exe [DefaultBox] by process: 8152
SBIE2224 Sandboxed program has crashed: WerFault.exe [DefaultBox] by process: 7976

SBIE2224 Sandboxed program has crashed: Start.exe [DefaultBox] by process: 6124
SBIE2224 Sandboxed program has crashed: SandboxieRpcSs.exe [DefaultBox] by process: 7200
SBIE2224 Sandboxed program has crashed: WerFault.exe [DefaultBox] by process: 7912

|Name|            |Process ID|   |Status|                       |Start Time|   |Path|                                      

DefaultBox                          Enhanced Isolation, No Admin              C:\Sandbox\......\DefaultBox                   
_ Start.exe       2920           Running                        13:16:56          C:\Program Files\Sandboxie-Plus\Start.exe   
__ WerFault.exe   7404       Running                        13:16:56          C:\Windows\System32\WerFault.exe     

       
SBIE2224 Sandboxed program has crashed: SandboxieRpcSs.exe [DefaultBox]
SBIE2224 Sandboxed program has crashed: Start.exe [DefaultBox]
SBIE2224 Sandboxed program has crashed: WerFault.exe [DefaultBox]


SBIE2224 Sandboxed program has crashed: SandboxieRpcSs.exe [DefaultBox]
SBIE2224 Sandboxed program has crashed: basilisk.exe [DefaultBox]

Looks like I will have an interesting afternoon.

**Comment by FrogsInSpace** [comment]
Crash seems to be a bug with the latest 0.4 / 5.3 version
had the same crash as mentioned directly above
so i installed Sandboxie plus v0.3.5 and the crash was gone

**Comment by DavidXanatos** [comment]
Could you please test this build: https://drive.google.com/file/d/1L3GjBGc-jnpo7VB4FSHBWC_Q-DgwjtXr/view?usp=sharing

it rolls back the changes to the hooking mechanism but keeps the snapshot feature

**Comment by tutak-kat** [comment]
This latest build fixed my errors. Just to explain ver. SandboxieInstall64-v5.43.exe worked fine for me, except for errors with quantum based browsers, then I got suggestion how to fix some problems with Sandboxie-Plus-x64-v0.4.0.exe and I installed that version and missing right click I fixed as suggested, BUT then nothing worked so I deinstalled that version cleared disk and registry of any sandboxie entry and installed again SandboxieInstall64-v5.43.exe - but still got the same errors. Before installation of Plus version that version worked for me. Strange.

However this latest bild is working fine except errors like this in quantum based browsers:
- SBIE2205 Service not implemented:  CreateDesktop
- Initialization of the dynamic link library C:\Program Files\Sandboxie\SbieDll.dll failed. The process is terminating abnormally. 

Is this happening only to me or is it known problem?
 - I tried Icecat - installed, portable Iceweasel, torbrowser, portable Icecat. Didn't try firefox - pis...ed off by Mozilla so I don't want to touch it anymore.

Thanks for quick fix.

**Comment by NMHy8C** [comment]
> Is this happening only to me or is it known problem?

Same problem confirmed.
It seems that all the portable Quantum-based browsers will cause the following error and fail to start:
SBIE2205 Service not implemented:  CreateDesktop

> Before installation of Plus version that version worked for me. Strange.

I think the Plus version might somehow interfere with the classic version. After I found the Forced Folders function of the Plus version is not working, I uninstalled it and installed the classic version instead. However, I found its Forced Folders function suddenly has the same problem. Before I tried the Plus version, it worked fine.

**Comment by DavidXanatos** [comment]
So the version from my g-drive works as fine as the 5.42?
I have reuploaded 0.4.0 with a minor change that may fix the issue (one of the changes in the gdrive build) can you test if a re downloaded 0.4.0 works for you?

Also about Plus and non plus builds, don't interpret to much into not repeated one time observations.
Booth the legacy and plus build have the exact same core components, the plus build only adds the Qt based UI.
When you do something in the sandbox settings booth builds do the same thing in the end, talk to the driver to save some,
values into C:\Windows\Sandboxie.ini every other interaction with the driver/service is transient and gone after the driver was unloaded an re loaded (reboot or manual using kmdutill or sandman maintenance menu).

So if you have a persistent problem after going back to a known good build check your C:\Windows\Sandboxie.ini for improper entries.

**Comment by DavidXanatos** [comment]
PS: about forced folders there is indeed an issue, Qt uses / while windows uses \ to separate path components i forgot to fix that when adding forced folders entries to the ini, so check you rini file if you have 

ForceFolder=

entries that have /paths/like/that instead of paths\like\this and fix them manually.

the issue shoudl howeever only have affected newly added entries

**Comment by NMHy8C** [comment]
Hi David,

Do you have any plan to make portable browsers (Firefox, Chrome etc.) work with Sandboxie? Thanks.

**Comment by tutak-kat** [comment]
`So the version from my g-drive works as fine as the 5.42?
I have reuploaded 0.4.0 with a minor change that may fix the issue (one of the changes in the gdrive build) can you test if a re downloaded 0.4.0 works for you?`


Yes g-drive version worked for me, but new 5.43 (corrected one) unfortunally is not working - I have the same errors as above.
I didn't tested Plus version but SandboxieInstall64-v5.43.exe (SHA1 - 88BFB5ABC03B93E43076D4BCA13C25CDD8498B52).

`Do you have any plan to make portable browsers (Firefox, Chrome etc.) work with Sandboxie? Thanks.`

For me all non quantum based firefox browsers (waterfox classic, palemoon, firefox 28, basilisk) installed or portable works fine with g-drive version.
Quantum based firefox forks (iceweasel, icecat or tor browser is not working)
Chrome browsers - iridium, ungoogled chromium, vivaldi works fine, didn't try chrome.

I have 1 question - how to make keeppassxc working with sandboxie?

Thanks

PS - I noticed that hitmanalert pro block SandboxieCrypto.exe from running marked it as dangerous?
I noticed that with earlier versions as well but I don't use that program often. 
Maybe that is related with warning regarding signed driver?

**Comment by NMHy8C** [comment]
> For me all non quantum based firefox browsers (waterfox classic, palemoon, firefox 28, basilisk) installed or portable works fine with g-drive version.
> Quantum based firefox forks (iceweasel, icecat or tor browser is not working)
> Chrome browsers - iridium, ungoogled chromium, vivaldi works fine, didn't try chrome.

Thank you for your feedback. I just tried ungoogled chromium with the Plus version, it surprisingly works. David has definitely improved Sandboxie. Before that, the official build fails to support any latest Quantum-based or Chromium-based portable browsers. I just hope the author would add the support of Quantum-based portable browsers as well.

**Comment by DavidXanatos** [comment]
I'll close that for now feel free to create a new issue for the "portable browsers " problem separately
