### ISSUE TITLE
snapshot improvement ideas

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1220]
i have some snapshot improvement ideas you may consider.

1 - add snapshot manager to plus panel UI

2 - redesign snapshot manager with the list of boxes on left (like virtualbox), and add an option to show all boxes whenever we want to use a snapshot from another box.
2.1 add option to delete all snapshots in snapshot manager (from specific box and globally)
2.2 if delete the box icon on the left panel all snapshots of that box should be deleted
![t1-1](https://user-images.githubusercontent.com/54504707/134211731-5fc798be-6a99-4adf-8a6e-0627f25d2576.png)

3 - add option to restore box to specific snapshot after content is deleted

4 - dont delete snapshot when delete contents, instead app an option in delete files UI to delete snapshots, and leave this option unchecked by default

**Comment by DavidXanatos** [comment]
1 - no I prefer the VMWare approach where snapshot manager is an own window
2 - using snapshots from other boxes is not supported, and would be similar to this request https://github.com/sandboxie-plus/Sandboxie/issues/339
3 - will be included in 1.0.9
4 - will be included in 1.0.9
