### ISSUE TITLE
Sandboxie-Plus "Browse Content" shows folder contents of installation folder when empty

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#1226]
**Describe the bug**
When clicking on a non-empty sandbox and click "Explore content", Sandboxie Plus' Sandman shows me the list of files and folders of that Sandbox. However when I do that to an empty sandbox it shows me a list of Sandboxies installation folder. I can't be sure it is always the installation folder.

**To Reproduce**
1. Go to and empty box
2. Right-click on it and select "Browse Content"
3. See it displaying files and folders of the installation folder

**Expected behavior**
Show me and empty list or a message telling me there wouldn't be anything to display similar to when I try to explore the content, which gives me such a message.

**Additional context**
This issue is being present in Sandboxie-Plus 0.9.6, but I am not sure if that did not occur in any other release once that browsing feature had been added.

I am using the 64bit version and this bug is present on Windows 7 and Windows 10, both 64bit versions.

Edit: Added Screenshot
![Boxcontent when empty](https://user-images.githubusercontent.com/1449429/134767662-1b886ea8-eaef-4458-bb48-4ccca80b2a84.png)
.

**Comment by Coverlin** [comment]
It's showing the current directory/working directory the sandman process started with

Something else to add : When having the browse content window open and deleting the sandbox content using the context menu on the box , this window should be closed as it's preventing some "leftover" empty folders from geting deleted
