### ISSUE TITLE
How am I supposed to update Sandboxie??

### ISSUE THREAD

**Issue by EfraMP** [sandboxie-plus/Sandboxie#1228]
Do I just uninstall the current version and install the newest? 
Or is there another option to avoid this?
Will my data be lost?

**Comment by bastik-1001** [comment]
You may backup the Sandboxie.ini which is located at **C:\windows\sandboxie.ini**, although it should remain untouched when you install a new version. Simply install the latest version, without uninstalling the previous installation. The installer is supposed to update the current installation while preserving your settings and files.

When you want to install the plus build, but are currently using the classic build, you have to remove the classic installation before installing the plus build. Please have a look at #259 for that.

**Comment by EfraMP** [comment]
Thanx bro
