### ISSUE TITLE
Option to clear a sandbox when Sandman is terminated

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#1229]
**Is your feature request related to a problem? Please describe.**
One option per sandbox that allows to clear it once Sandman.exe is being terminated by the user.

#1026 asks to add that on shutdown or reboot of Windows, which can still be done, but my request might be easier to implement.

Currently I can either clear it manually or have it cleaned when the last process is terminated. Having it set to clear when the last process ended can lead to frequent clearing processes per day when a forced program is launched in a sandbox several times a day.

**Describe the solution you'd like**
A setting that allows to clear selected sandboxes when Sandman is being terminated by the user.

**Describe alternatives you've considered**
As this is a convenience feature, this is something for the plus version, if that is UI related. When it is possible the classic version should get the same feature.

**Comment by DavidXanatos** [comment]
I'm not sure about that, as it would delay windows shutdown/reboot if there are many files in the box, also it may fail if windows decides to force terminate it

**Comment by bastik-1001** [comment]
Yes, I understand that this might be an issue. If that is something you would not want to implement that, I can understand that as well, as that could lead to support questions about sandboxes not being emptied, while they should have been, but were not as the process got killed or that it would take much longer to reboot/shutdown. The latter one might be something the user expects as cleaning lots of files is expected to take longer. Still it is a concern to be raised.

**Comment by bastik-1001** [comment]
This request does not seem to be of any use. I don't find this as useful anymore, compared to when I asked for that feature.
