### ISSUE TITLE
An explanation for the Plus version

### ISSUE THREAD

**Issue by birdie-github** [sandboxie-plus/Sandboxie#123]
I don't see it in release notes, I don't see in the project's readme. Please add info somewhere 'cause I'm sure I'm not the only person who's confused.

**Comment by NEK-RA** [comment]
Probably Plus is another GUI built on Qt and using original Sandboxie binaries as backend, but I'm not sure. Hope the answer will appear here

**Comment by DavidXanatos** [comment]
Hi,

Yes the plus build has a new UI which supports the new functions of the core components like box snapshots.

Cheers
David X.

**Comment by NEK-RA** [comment]
Thank for answer.
Add please this info into repo's readme, cause you've mentioned about "SandMan" in release notes,  but not the "Sandboxie Plus". That's why this question appeared :D Also when you'll update readme, write your new functions please :)

**Comment by DavidXanatos** [comment]
I have added it to the read me

**Comment by jack1142** [comment]
So, Sandboxie Plus (i.e. `Sandboxie-Plus-x64-v0.4.1.exe`) build in comparison to Sandboxie build (i.e. `SandboxieInstall64-v5.43.5.exe`) has the new UI and it gets the new features? If that's true, how exactly does Sandboxie build differ from the last version released by Sophos? Does it contain *just* bug fixes?

**Comment by DavidXanatos** [comment]
Yes that is correct.

It differs a huge lot, see the change-log: https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md

**Comment by jack1142** [comment]
Hmm, I have a suggestion then. Could you maybe split the version changelogs in 2 sections so that it's more obvious what from the changelog is related to Sandboxie Plus and what is related to Sandboxie?

**Comment by DavidXanatos** [comment]
> 
> 
> Hmm, I have a suggestion then. Could you maybe split the version changelogs in 2 sections so that it's more obvious what from the changelog is related to Sandboxie Plus and what is related to Sandboxie?

That is not really possible for example the Box Snapshot feature required many changes to the core parts of Sandboxie yet this functionality is only available through the Sandboxie Plus UI so into what changelog to put it?

I could tag every line in the changelog with 
- SbieCore: added bla blaa
- SbiePlus: added bla bla
- SbieCtrl: changed blup
but that would make the change log less readable imho and its not really required just remember the following guidelines
1. All new features are added to the Sandboxie Plus, if they are controlled through Sandboxie.ini they will also work with the legacy release but wil have to be configured with an text editor in the ini directly.
2. All security, performance and compatybility improvements apply equally to the Legacy and Plus release
And that's all
