### ISSUE TITLE
When its dark theme is enabled, Sandboxie Plus flashes a bright white page when the main GUI is launched and shown

### ISSUE THREAD

**Issue by Dark-Magician** [sandboxie-plus/Sandboxie#1231]
![Sandboxie Plus - Launched](https://user-images.githubusercontent.com/19816749/135010367-5faa9aae-0fc1-470e-89e3-568ebddecc07.gif)

![Sandboxie Plus - ShowHide](https://user-images.githubusercontent.com/19816749/135010396-ba845031-19ea-4675-95e3-60fdf3bd0bb3.gif)

Windows edition and version: Windows 10 Pro 20H2 (up to date)
Sandboxie Plus version: 0.9.6

**Comment by DavidXanatos** [comment]
you mean when the process starts not when its unminimized form tray or alike?
I think this is an issue with how Qt operates internaly so no easy way to fix this.

**Comment by Dark-Magician** [comment]
Sandboxie-Plus flashes a bright white page when I launch it, restore it from the system tray and taskbar, and sometimes open dialog boxes like the global settings and sandbox options.

It is as you said. It turns out that this problem is related to Qt behavior, but the lead developer of Shotcut has demonstrated developers can address it by controlling window opacity.

Since version 21.12, Shotcut no longer displays a white page when I launch it and restore it from the taskbar, and it helps so much with eyestrain. Can you read [this](https://github.com/mltframework/shotcut/issues/1168#issuecomment-950412076) and reconsider your stance? What do you think about his workaround? Can you apply something similar to Sandboxie-Plus?

**Comment by isaak654** [comment]
This is the commit that fixed the same Qt issue: https://github.com/mltframework/shotcut/commit/a72b757c72ef085bfecebb7e379d1dd05a0667f9
Please reconsider this issue, David.

**Comment by DavidXanatos** [comment]
I'll take a look in that seams easy enough, the fix will be in included in the next build.

**Comment by DavidXanatos** [comment]
I have noticed that this issue appears to a lesser extent to virtually any Qt dialog that opens, also message boxes, and alike.
The current fix is only for the main window and the tool windows.
Should I look into fixing that also for all the small dialogs? Or is that a non issue because thay are small and load faster?

**Comment by isaak654** [comment]
The white animation is also on the About window, so I would suggest to extend the fix for all windows.

**Comment by Dark-Magician** [comment]
I finally had the chance to test the new version on Windows 10 and 11. I still see the white flash in the main GUI when I launch SandMan.exe. The problem appears fixed in all other cases.

**Comment by DavidXanatos** [comment]
will be fixed in the next build
