### ISSUE TITLE
Paypal donation fail

### ISSUE THREAD

**Issue by zhenjie1999** [sandboxie-plus/Sandboxie#1233]
![image](https://user-images.githubusercontent.com/75268245/135143593-23d329cf-cfdb-49da-8d1d-88d6839b96e9.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dyras** [comment]
I think this is due to the country you're living in. I just donated and it worked.
![grafik](https://user-images.githubusercontent.com/12563436/135223735-4d6c9b54-c947-4bfa-8004-8207d215aac2.png)

**Comment by DavidXanatos** [comment]
Yea unfortunately some countries are blocked by paypal

**Comment by isaak654** [comment]
It's a common Paypal issue, see:
https://www.paypal-community.com/t5/Payments-Archives/Unable-to-make-a-payment/m-p/2333373

> It looks like it's working again.  If you were trying to make a payment from Fiji, Egypt, China, India, Japan, Taiwan, or Hong Kong, you got the error: "Donations to this recipient aren't supported in this country."

> Nope. Still getting that error message and I cannot find a way to contact customer support.  However, if I go into my Paypal account and send the payment that way, rather than via the link in the merchant's website, it goes through right away.

**Comment by isaak654** [comment]
It's a common Paypal issue, see:
https://www.paypal-community.com/t5/Payments-Archives/Unable-to-make-a-payment/m-p/2333373

> It looks like it's working again.  If you were trying to make a payment from Fiji, Egypt, China, India, Japan, Taiwan, or Hong Kong, you got the error: "Donations to this recipient aren't supported in this country."

> Nope. Still getting that error message and I cannot find a way to contact customer support.  However, if I go into my Paypal account and send the payment that way, rather than via the link in the merchant's website, it goes through right away. 

> It looks like the problem comes and goes.  Customer service doesn't know anything and will run you in circles.  Maybe you'll get lucky and get someone who actually knows something.
