### ISSUE TITLE
conhost.exe (14352): SBIE2205 Service not implemented:  ConsoleControl

### ISSUE THREAD

**Issue by koliu** [sandboxie-plus/Sandboxie#1238]
**Describe the bug**
When I try to run the git command (e.g. git --version) in the sandbox terminal (cmd.exe or VS Code terminal --powershell/command prompt/gitbash), it hangs...

And if remove the terminal from VS Code, it will get the sbie message: **conhost.exe (14352): SBIE2205 Service not implemented:  ConsoleControl**.

The last 3 trace logs of git:
git.exe (11824, 15336) - 23:21:02.416   Ipc      Open       \KnownDlls\SHELL32.dll           
git.exe (11824, 2296) - 23:21:02.416    Pipe     (8)        \Device\NamedPipe\winansi11824   
git.exe (11824, 2296) - 23:21:02.416    Pipe                \Device\Null       

**To Reproduce**

1. Download [VSCode](https://code.visualstudio.com/docs/?dv=winzip)
2. Unzip it to a sandbox folder
3. Run [Unzip Folder]/code.exe
4. [**Ctrl**+**`**] to display VS Code terminal
5. Enter the command: **git --version**, then the terminal will hang up...
6. Click "**Kill Terminal**" in the upper right corner of the terminal, and then the sbie message will be displayed.

**Expected behavior**
- No the sbie message.
- Running git commands in the sandbox will not hang up...

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 21H1.
 - Sandboxie Plus 0.9.6.
 - Latest VS Code.
 - Comodo Personal Firewall 12.2.2.8012

**Sandboxie configuration**
- The sandbox has been set to **Drop rights from Administrators and Power Users groups**.

**Comment by DavidXanatos** [comment]
is this teh git version you used: https://git-scm.com/download/win

**Comment by ko25july** [comment]
I'm in the same situation.

**Comment by DavidXanatos** [comment]
@ko25july so for you the issue is nto fixed yet? are you using the latest sbie version?

**Comment by ko25july** [comment]
> @ko25july so for you the issue is nto fixed yet? are you using the latest sbie version?

@DavidXanatos Thank you very much for your reply.
