### ISSUE TITLE
Sandboxie-plus "run-sandboxed" dialog fails to close handle to unsandboxed file or folder

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#1247]
**Summary**

I am unable to rename (etc) a folder that is located outside the sandbox after I select "Run Sandboxed" from the File Explorer context menu. Simply displaying the "Run Sandboxed" dialog is sufficient. The selected executable need not be run.

**Reproduce**

0. Install Sandboxie-Plus 0.9.6 on Win 10 x64 10.0.19043
1. Create a folder, eg, "A",  outside of sandboxie and place an executable into this folder
2. Right-click on executable and select "Run Sandboxed" from context menu
3. Sandboxie-Plus shows dialog and main window
4. Cancel the dialog (no need to run and exit app)
5. Verify that you do not have File Explorer open inside folder "A"
5. In File Explorer try to rename folder "A"
6. Windows shows error dlg "Folder in Use:": "The action can't be completed because the folder or a file in it is open in another program"
7. Exit Sandboxie plus (closing main window is not sufficient)
8. On "Folder in Use" dlg click retry. Renaming the folder succeeds.

**Comment by DavidXanatos** [comment]
I cant reproduce this bug
