### ISSUE TITLE
A Few Minor Pointers / Issues SBP v0.4.0

### ISSUE THREAD

**Issue by J-Wildfire-T** [sandboxie-plus/Sandboxie#125]
Just a few minor issues / pointers for SBP v0.4.0

-  Under Options / General Options / Language Selection - Spelling mistake for the word English.  Currently reads, International Englisch.
-  Dark theme issue when selecting a sandbox's options, the left tabs are barely visible / bright background and text.

**Comment by DavidXanatos** [comment]
booth fixed, fixes will be included in the next build
