### ISSUE TITLE
I can't run Sandboxie plus on Windows 11

### ISSUE THREAD

**Issue by yydcwl** [sandboxie-plus/Sandboxie#1255]
I can't run Sandboxie plus on Windows 11

**Comment by DavidXanatos** [comment]
Others report you can,
what version are you trying to use the 0.9.6 release is know to work fine,
if you have issues with it please be more specific, whats the error message, what is happening, what isn't working etc....

**Comment by yydcwl** [comment]
Because I can't use it, I have rolled back the operating system to windows 10. I remember that I used Sandboxie plus version 0.9.3 on Windows 11. It's really bad. I didn't use the latest version.

**Comment by Kemny** [comment]
Hi, I also can't get this to work on windows 11. Here is a screenshot from trying to open file browser from the "AI" sandbox. I get the same issue no matter what I box I use or what I try to open
![image](https://user-images.githubusercontent.com/48955461/143426440-818258a1-a55b-4a63-a488-d9d98be78a1f.png)

**Comment by DavidXanatos** [comment]
strange onmy win11 test vm the last build works just fine
