### ISSUE TITLE
Running whatsapp desktop the second time (after install) no response

### ISSUE THREAD

**Issue by arkhub** [sandboxie-plus/Sandboxie#1258]
Step to recreate :
-Create "hardened" box
- Download whatsappsetup (64 bit) from the website
- Run the setup from sandbox
- Setup continues and login with QR Codes
- Install and apps successfully running
- close the app
- Open whatsapp second time from "run from start menu"
- nothing happened (shows process of whatsapp exe running on the sandboxie-plus but then empty after that.

Environment : windows 10 pro

**Comment by isaak654** [comment]
Sandboxie version?

**Comment by isaak654** [comment]
I can reproduce the issue described in the first post on 0.9.7d, but with the difference that I used a new sandbox with the default preset (not the hardened one).

> sorry, 0.9.6
> 
> now after removing the box and creating with same sandbox name, during setup whatsapp does not create qr code to link to phone, only when changing the sandbox name then it's working.

I wasn't able to reproduce this one on 0.9.7d.

**Comment by arkhub** [comment]
Trying the latest 0.98 x64 (portable), so I add  `SpecialImage=chrome,WhatsApp.exe` below my [Whatsapp_Box_Name] Settings (as mentioned in other report sandboxie portable 0.9.8 don't work first time / crashed in portable so I add that before running). and while at first it's running, the box just shows black window screen.
