### ISSUE TITLE
windows 11 22000.194  Explorer.exe Cannot display

### ISSUE THREAD

**Issue by gdzjy** [sandboxie-plus/Sandboxie#1259]
Explorer.exe Cannot display.

![Snipaste_2021-10-08_00-45-34](https://user-images.githubusercontent.com/22785084/136429158-322ec562-441b-426d-87e8-ffc0036518a3.png)

![Snipaste_2021-10-08_00-46-14](https://user-images.githubusercontent.com/22785084/136429753-b9f6cfac-8437-4369-8f4c-84dbf5626932.png)

**Comment by isaak654** [comment]
Related to #1127 and #69.
