### ISSUE TITLE
Forced Folders not working in Plus version

### ISSUE THREAD

**Issue by NMHy8C** [sandboxie-plus/Sandboxie#126]
1. Add Firefox folder to Forced Folders of a sandbox
e.g.  "C:\Program Files\Mozilla Firefox\"
2. Launch firefox.exe in that folder
3. Firefox is not forced to run in the sandbox at all.

Environment:
Windows 10 Pro 2004 x64, Windows Defender, Sandboxie-Plus-x64-v0.4.0

Thank you.

**Comment by DavidXanatos** [comment]
there is a bug in the current build where when adding a path using the SandMan ui the paths separators are wrong i.e. / instead of \ hence the new entries don't work.
please edit the Sandboxie.ini to fix the ForceFolder=.... entries that are affected by replacing all / with \

**Comment by NMHy8C** [comment]
Thank you David. Looking forward to more new features in the Plus version.
