### ISSUE TITLE
OST file imported into Sandbox in V0.9.7d

### ISSUE THREAD

**Issue by mauriceatkinson** [sandboxie-plus/Sandboxie#1260]
I downloaded v0.9.7d as I had an issue with click to run after i downloaded a csv within the sandbox.

This version now displayed the downloaded csv but before it did that sandboxie imported my entire OST email file into the sandbox. 

Strange behaviour I thought and could not see why my ost file is needed??

**Comment by isaak654** [comment]
Did you apply the Office Outlook template on your sandbox?
