### ISSUE TITLE
Blank white screen when launching Chrome 94 (hardware acceleration)

### ISSUE THREAD

**Issue by Orcman2019** [sandboxie-plus/Sandboxie#1261]
Worked on earlier versions of Chrome, noticed after Chrome 94 update that it won't work sandboxed with force to run sandboxed and any or all additional options allowed.

**Comment by bjm234** [comment]
> Worked on earlier versions of Chrome, noticed after Chrome 94 update that it won't work sandboxed with force to run sandboxed and any or all additional options allowed.

Please check "hardware acceleration" is off.

**Comment by isaak654** [comment]
@Orcman2019 Could you post your hardware specs and Windows version? 
Hardware acceleration set to off is a workaround, not a fix, so I would appreciate if you could share more details about this.

**Comment by DavidXanatos** [comment]
hmm... I cant reproduce this issue not even on my real host machine, it uses a 1060 nvidia card.
I presume the issue may be related to the used GPU and drivers.

**Comment by isaak654** [comment]
Further update about this issue from @superkryodev:

> Good to hear Chrome HW-acceleration issue has disappeared for @algol1, however it still remains on my 11th gen
> 
> Many thanks for your continued effort

Source: https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-1.442616/#post-3055648

**Comment by DavidXanatos** [comment]
this issue will be resolved using an experimental new feature, to enable it add ```EnableWin32kHooks=y``` to your sandboxie ini and reload the driver or reboot.

**Comment by isaak654** [comment]
> this issue will be resolved using an experimental new feature, to enable it add `EnableWin32kHooks=y` to your sandboxie ini and reload the driver or reboot.

I think `EnableWin32kHooks=y` should be enabled by default in a later version, people keep complaining about the hardware acceleration issue without reading a damned thing: 
https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-1.442616/page-3#post-3057464
