### ISSUE TITLE
Question: Force Folder excludes?

### ISSUE THREAD

**Issue by DocMAX** [sandboxie-plus/Sandboxie#1268]
Can i set excluded *.exe within a forced folder and how?

**Comment by SiNONiMiTY** [comment]
AFAIK, you can't do that. I am having the same problem, referenced here:

#1189 

Wanted certain applications to be ran on other sandboxes even if executed on a forced folder.

**Comment by DavidXanatos** [comment]
Does the breakout process feature help your usecase: https://github.com/sandboxie-plus/Sandboxie/issues/1500 ?

**Comment by SiNONiMiTY** [comment]
@DavidXanatos now that I am able to test this:

```BreakoutProcess=firefox.exe```

Works perfectly when declared on the Global level.

This issue should be closed now.
