### ISSUE TITLE
Why is sanboxie marked as a trojan in Windows Defender

### ISSUE THREAD

**Issue by Absence209** [sandboxie-plus/Sandboxie#127]

**Comment by DavidXanatos** [comment]
its a false positive see: https://github.com/sandboxie-plus/Sandboxie/issues/95

**Comment by milxxon** [comment]
Why is sanboxie marked as a trojan in Windows Defender.
![ameaça](https://user-images.githubusercontent.com/75681974/101497932-e0aca380-3941-11eb-8589-fb24b044bc3f.png)
![ameaça2](https://user-images.githubusercontent.com/75681974/101498039-046fe980-3942-11eb-8544-993a43763245.png)
