### ISSUE TITLE
Why the message about Edge running in Administrator Mode?

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#1271]
When I open Edge outside Sandboxie, everything goes correctly.

When I open Edge in any of my five sandboxes, I get a message:
'Administrator Mode Detected
Close Microsoft Edge and relaunch in non-administrator mode for best performance.'
and there is a button saying, 'Close Microsoft Edge'.

With that message still showing, I go to Task Manager --> Details --> Elevated (I added the elevated column to the display some time ago).  All the instances of msedge.exe are reported as running non-elevated.

I close Edge as advised by pressing the button and relaunch in the same sandbox, and the message reappears.

I wipe all the sandboxes every few days, so nothing is hanging around there.

* What is going on?  I have never consciously run Edge elevated.  
* Why is the message reporting that Edge is running elevated when the Task Manager reports it as non-elevated?
* How do I prevent the message appearing?

I have just installed Sandboxie-Plus-x64-v0.9.7.exe, Version (e), but the problem is still there.
Desktop running Windows 10 Pro 21H1 V10.0.19043.1266

**Comment by isaak654** [comment]
Already reported on issue #1097.

**Comment by DavidXanatos** [comment]
Since edge normaly doesnot need to be run as admin I'll add an excemption to the FakeAdmin function to never apply to edge
