### ISSUE TITLE
Games that run with Sandboxie Classic either crash or have issues with Sandboxie Plus

### ISSUE THREAD

**Issue by F0nt** [sandboxie-plus/Sandboxie#1275]
**Describe the bug**
Certain games that run fine with Sandboxie-Classic-x64-v5.51.6, either fail or have issues with Sandboxie-Plus-x64-v0.9.6.

With SB Plus, one game fails to start entirely, simply throwing a box of gibberish. (The gibberish might be because the game is localized from Japanese.)
The other starts to menu, but with no sound - and a missing background graphic. Then fails to load the main game.

With Classic, both games run without errors.

**To Reproduce**
1. I create a new box with default settings.
2. I right click the game on the unsandboxed harddrive and run sandboxed in the new box.

**Expected behavior**
The games are supposed to run without issue.

**System details and installed software**
Windows 10 Pro 20H2 64-bit
Sandboxie-Classic-x64-v5.51.6 (and Sandboxie-Plus-x64-v0.9.6 - which has the issue)
- What was your previous Sandboxie version before the update, if any? v5.42.1
I don't know which version the bug was introduced, but I started having issues when I tried to use SB Plus instead of Classic. I installed SB Plus 0.9.6 after having Classic 5.42.1. Errors started happening, and I installed Classic 5.51.6 - and the errors went away.
 - Please mention any security software running in the background, even if the real-time protection is disabled. I have windows defender and malwarebytes firewall.

**If you have a compatibility issue**
 - Please add a reference link to the program not working properly in Sandboxie.
https://store.steampowered.com/app/1293820/YOU_and_ME_and_HER_A_Love_Story/
(NSFW) https://www.mangagamer.com/r18/detail.php?goods_type=1&product_code=1250 

**Sandboxie configuration**
It happens with a fresh install of Sandboxie and no existing .ini file..

**Comment by DavidXanatos** [comment]
I think this issue should be solved by that fix: https://github.com/sandboxie-plus/Sandboxie/issues/1436
