### ISSUE TITLE
new slack 4.20.0 does not run in Sandboxie

### ISSUE THREAD

**Issue by boldcompany** [sandboxie-plus/Sandboxie#1278]
**Describe the bug**
Slack versions prior to the current version ran in sandboxie with no issues.
Current version (https://slack.com/download) crashes.
Quite a bit of troubleshooting using Xanatos TaskExplorer and various Sandboxie settings, but no obvious solution so far.

**To Reproduce**
1. Go to https://slack.com/download and download the current installer.
2. Run the installer in a Sandboxie sandbox.
3. Try to run the new version of slack. It will crash.

**Expected behavior**
Slack will run in Sandboxie as it did before.

**System details and installed software**
 - Windows 10 Pro 20H2 64-bit
 - Sandboxie Plus 0.9.6 64-bit)
 - Previous Sandboxie version: Sandboxie Plus 0.9.3

**Comment by boldcompany** [comment]
@isaak654 , thank you - these details are much appreciated.
Should we leave this ticket open for your case, or close this one and open a new one?

**Comment by isaak654** [comment]
My problem reported in [post 3](https://github.com/sandboxie-plus/Sandboxie/issues/1278#issuecomment-942226292) persists also in stable 0.9.8.
I prefer to reuse this thread to not open another issue about the same program.
