### ISSUE TITLE
Sandboxie x64-v5.43 Crash Message SBIE2224

### ISSUE THREAD

**Issue by Coverlin** [sandboxie-plus/Sandboxie#128]
Installed : SandboxieInstall64-v5.43
OS:Windows 7 Ultimate 64-bit SP1
Happens on empty and already used boxes
SBIE2224 Sandboxed program has crashed: SandboxieRpcSs.exe [Box]

Previous version no issues

**Comment by DavidXanatos** [comment]
mmh... try this two test builds

https://drive.google.com/file/d/1L3GjBGc-jnpo7VB4FSHBWC_Q-DgwjtXr/view?usp=sharing
https://drive.google.com/file/d/1oDoE0oY-2MPUPW3-RUKPCx6tByj661z4/view?usp=sharing

and tell me if boot of one of them or no is working for you.

**Comment by Coverlin** [comment]
> mmh... try this two test builds
> 
> https://drive.google.com/file/d/1L3GjBGc-jnpo7VB4FSHBWC_Q-DgwjtXr/view?usp=sharing
> https://drive.google.com/file/d/1oDoE0oY-2MPUPW3-RUKPCx6tByj661z4/view?usp=sharing
> 
> and tell me if boot of one of them or no is working for you.

Both 5.43.x test builds solved the start and crash error related to SandboxieRpcSs.exe
Runing a game , opening media player or a image viewer that's installed outside the sandbox will work
but previously installed software inside a sandbox will fail to work (except firefox x64 v7x)

Something that is occuring with the test builds and not with v5.42.1
Sandboxed Win Explorer , navigate to the sandbox container , trying to open self box will trow the error msgbox : 
Title : Location is not available
<Path> is not accessible.
Invalid access to memory location
 Then sandboxed explorer.exe freezes

**Comment by DavidXanatos** [comment]
So you mean if you have a explorer runnign in sandbox and than go to C:\Sandbox\... ?

**Comment by Coverlin** [comment]
> So you mean if you have a explorer runnign in sandbox and than go to C:\Sandbox... ?

Yes , Sbie control context menu Run Sandboxed -> Run Windows Explorer on DefaultBox and from the explorer started navigate to the defaultbox(self) location

**Comment by DavidXanatos** [comment]
should be fixed with the latest release

**Comment by phrab** [comment]
I have Sandboxie x64 v5.48.5 & it crashed (SBIE2224) when:
1.  Right click Sandboxie icon
2.  Default box/Run any program/C:\Windows\Explorer.exe

The reason I was trying it that way, rather than using "Run Windows Explorer" is that the latter opens a Sandboxed Explorer to the C:\ drive & I wanted to open it directly to Quick Access, which is what I get if I click directly on Explorer.exe.
