### ISSUE TITLE
[0.9.8] Edit ini Section is always empty when you double click any template

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1287]
**Describe the bug**
The graphical editor "Edit ini Section" won't show any code if you double click any template on the "App Templates" list.

**To Reproduce**
1. Go to "Sandbox options" -> "App Templates"
2. Double click any template to display its code
3. "Edit ini Section" will appear always empty

**System details and installed software**
 - What is your Windows edition and version? W10 20H2
 - What is your current Sandboxie edition and version? 0.9.8
-  Please mention in which version this bug got introduced. 0.9.8

**Comment by Coverlin** [comment]
reproduced the issue, only affects templates in templates.ini , local/sandboxie ini templates are displayed
