### ISSUE TITLE
[Classic 5.53.0] Extra separator to remove in Miscellanous category

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1288]
**Describe the bug**
There is an extra separator to remove in Sandboxie 5.53.0 (Miscellanous).

**Screenshot**
![Classic 5.53.0](https://user-images.githubusercontent.com/12372772/137564664-0d841891-1c15-4d47-8e55-9779e672be62.png)

**Comment by Coverlin** [comment]
Do you mean the empty line ? press view code it's the special images template

To fix it comment the class in templates ini

```
[Template_SpecialImages]
#Tmpl.Title=#xxxx
#Tmpl.Class=Misc
```
