### ISSUE TITLE
[0.9.8] "Template_SpecialImages" is visible as option to check on Miscellaneous (unlike Classic UI)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1289]
**Describe the bug**
Template_SpecialImages is always visible on Plus UI Miscellanous (unlike Classic UI Miscellanous).

**Expected behavior**
Template_SpecialImages shouldn't appear on Plus UI Miscellanous at all, since it's expected to be always applied.

**Screenshots**
Plus UI 0.9.8 Miscellanous:
![Plus UI 0.9.8](https://user-images.githubusercontent.com/12372772/137564981-a4ef1a4a-5b75-474d-9b01-e3c35b9277be.png)

Classic UI 5.53.0 Miscellanous:
![Classic UI 5.53.0](https://user-images.githubusercontent.com/12372772/137565027-a777756d-9613-4bce-8170-f37d048edd4a.png)

**Comment by Coverlin** [comment]
Same fix as #1288
