### ISSUE TITLE
[0.9.8] installing/configure Sandboxie in portable will crash

### ISSUE THREAD

**Issue by Morku** [sandboxie-plus/Sandboxie#1292]
**Describe the bug**
When starting Sandboxie Plus 0.9.8 for the first time after installing in Portable Mode, the Setting screen will crash. After force closing the program and rerun it, the mainscreen directly crash as well.

**To Reproduce**
1. Start Sandboxie-Plus-x64-v0.9.8.exe
2. Select Portable installation
3. Start SandMan.exe
4. Click OK to confirm to have SandBoxie installed in Portable mode to get UAC screen
5. Now I press Yes that Sandbox folder shall be created nearby Sandboxie Plus installation
6. Crash, close program, start again -> directly Crash again
7. When I do the exact same steps with Sandboxie-Plus-x64-v0.9.6.exe,  everything is working fine as expected on same OS environment. The issue started for me with 0.9.8. I didn't test the previous Beta versions.

**Screenshots**
![Screenshot 2021-10-16 122517](https://user-images.githubusercontent.com/6276915/137583848-68e973ff-c52e-469a-abae-46a33fedfd2a.png)

**Video**

https://user-images.githubusercontent.com/6276915/137583856-e973657a-1f49-4f6b-9f9b-a5490b0326c2.mp4

**System details and installed software**
 - What is your Windows edition and version? Windows 11 Enterprise 21H2 64-bit Build 22000.258 German
 - What is your current Sandboxie edition and version? Sandboxie Plus 0.9.8 64-bit
 - What was your previous Sandboxie version before the update, if any? 0.9.6 64-bit -> working fine
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. Sandboxie Plus 0.9.8 64-bit
 - Please mention any security software running in the background, even if the real-time protection is disabled. Windows Defender

**Sandboxie configuration**
It's empty since it's unable to run for the first time

**Comment by DavidXanatos** [comment]
will be fixed in the next build,
the issue appears only in the special case when sandboxie.ini is empty, add somethign to it manually as a workaround
