### ISSUE TITLE
ProcessGroup lines that contain more than 1010 characters do not show up in SandMan

### ISSUE THREAD

**Issue by EliEron** [sandboxie-plus/Sandboxie#1293]
**Describe the bug**
If a ProcessGroup line contains more than 1010 characters it does not show up in the program groups tab. Both the SandMan and Sandbox Control interfaces allows you to create lines that exceed this character amount, but only the Sandbox Control interface is able to read it correctly.

**To Reproduce**
1. Add one or multiple items causing the line to exceed 1010 characters to a group
2. Hit apply
3. The group will disappear from SandMan

**Screenshots**
Here is a video showing off the steps above:

https://user-images.githubusercontent.com/22575945/137587293-198a8640-7ab9-4490-94e4-7a1fee3f8b67.mp4

I add a single item exceeding 1010 characters in the video since it made the demonstration simple. But the bug does not require a single item to exceed the length, any item combination that makes the config line exceed 1010 characters triggers the bug.

**Expected behavior**
SandMan should be able to read the ProcessGroup line in the same way as Sandbox Control.

**System details and installed software**
 - Windows 10 64-bit
 - Sandboxie Plus 0.9.8 64-bit

**Additional context**
I recently decided to upgrade Sandboxie since it had been quite a while since I installed it (I installed it prior to the Classic and Plus split) and decided to give the Plus version a spin. And while I like it for the most part I immediately ran into an issue as my *StartRunAccess* group was not showing up in either the "Start Restrictions"  or "Program Groups" tabs.

After experimenting a bit I realized that the issue was the number of items present in the group, or to be more precise how many characters all of those items ended up taking.  I then verified that the same behavior applies to all other program groups, not just the *StartRunAccess* group specifically.

I want to emphasis that this bug only applies to the SandMan interface, and not to the classic Sandbox Control interface, even when it is used with Sandboxie Plus.

**Sandboxie configuration**
<details>

<summary>sandboxie.ini generated in the above demonstration</summary>

```
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
ProcessGroup=<Example>,1011characteritemAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

</details>

**Comment by DavidXanatos** [comment]
Good find, very exotic, wil be fixed in the next build
fvi: there is a built in hard limit at 2000 charakters per ini line so you may run into that issue at some point.
But 1010 was a bug and i fixed it now.

**Comment by EliEron** [comment]
Thanks for the speedy response, and yeah it did take a while to identity the exact trigger of the issue, but I like to be precise when I'm reporting bugs.

Is there a possibility of that hard limit being lifted in the future, at least for entries containing lists? While my *StartRunAccess* group is still quite a ways away from that I could legitimately see it bumping into it in the future, and while I suppose I could get around it by creating subgroups it would be a bit cumbersome.
