### ISSUE TITLE
[5.52.5] SandboxieBITS.exe is not treated as a Lingering program

### ISSUE THREAD

**Issue by asbai** [sandboxie-plus/Sandboxie#1297]
**Describe the bug**
SandboxieBITS.exe is not treated as a Lingering program, even if `sandboxiebits.exe` has been forcibly added to the lingering program list

**To Reproduce**
1. Create a sandbox.
2. Add `sandboxiebits.exe` to its lingering program list.
3. Start chrome within this sandbox and wait until the `SandboxieBITS.exe` process started in this sandbox.
4. Stop chrome.
5. `SandboxieBITS.exe` and few other `Sandboxie*.exe` still running until we killed `SandboxieBITS.exe`.

**Screenshots**
[Screenshot](https://drive.google.com/file/d/1ur6rVt8bbjdpEzCaN2MOyUSpyIAPb2qX/view?usp=sharing)

**Expected behavior**
After the chrome process is stopped, the sandbox should be emptied

**System details and installed software**
 - What is your Windows edition and version? Win7 x64
 - What is your current Sandboxie edition and version? 5.52.5
 - What was your previous Sandboxie version before the update, if any? 5.51.6 (also has the same problem)

**Comment by isaak654** [comment]
I can't reproduce it on Plus 1.0.3, possibly because of this fix: https://github.com/sandboxie-plus/Sandboxie/discussions/1347#discussioncomment-1778813

**Comment by asbai** [comment]
Sure, I have been using version 5.55.5 these days and it seems that it has indeed been fixed.
