### ISSUE TITLE
Cannot Start any Program in the Sandbox

### ISSUE THREAD

**Issue by brushington** [sandboxie-plus/Sandboxie#13]
I am a user of Sandboxie for a long time. The version 5.33.2 works normally on my computer. Today I compiled the 5.40 from source code. The building process is fine without any issue and I make the driver (SbieDrv.sys) signed.

The new version runs well and the SbieCtrl loads Sandboxie.ini  in a normal way. But I cannot start any program in the sandbox! It seems that Start.exe will crash before it loads anything. I can see some WERFAULT.exe processes emerged when I try to start some program. 

I am quite sure it is the problem in the code. Because when I substituted the compiled binary to the binary of version 5.33.2 without uninstalling/rebooting, everything is good again. 

The problem exists in both the initial release of Sophos code and the version v5.40.1 in the github. I tried it on two different laptops with Windows 10 x64. The problem is the same. Is there anyone else have this strange problem?

**Comment by DavidXanatos** [comment]
That is strange, for me the build process worked on my host machine and in a mostly empty VM, what Visual studio are you using?

**Comment by brushington** [comment]
I am using Visual Studio 2017. The build process is well even with little warnings. The Sandboxie starts well. I just cannot start any program in a sandbox after the Sandboxie starts.

**Comment by DavidXanatos** [comment]
could you please post the warnings.
FYI I'm also using VS2017...

btw, just to be sure, when opening the solution you did not let VS update/upgrade the build tools?
because if you did than it set them to the VS2017 once and that may be an issue.

When installing VS2017 you have the option to install VS2015 build tools which are required for Sandboxie.

And when opening a solution for the first time you must make sure the build tools will not be changed.

Cheers
David X.

**Comment by brushington** [comment]
Thank you David. I think the problem is that I upgrade the build tools. All the projects are set to VS2017, and the problem occurs. I am trying to install  VS2015 build tools now.

**Comment by jotac0** [comment]
the root cause is that sandboxie uses internal windows kernel features, and in visual studio 2019, (i tested), some functions and even a file or two don't exist

**Comment by DavidXanatos** [comment]
I don't see a really good reason to add problems and potential issues right now by updating the project to a never VS version. Installing 2015 build tools should have no down sides as far as i can tell so there really is no up side to updating right now.
