### ISSUE TITLE
Zoom Hangs on Login on Sandboxie 5.43

### ISSUE THREAD

**Issue by DavidBerdik** [sandboxie-plus/Sandboxie#130]
When attempting to sign in to my Zoom account when running Zoom with Sandboxie x64 5.43, Zoom freezes and does not allow me to complete the sign-in. This issue does not occur when using a previous release.

Steps to reproduce:

1. Install Sandboxie 5.43
2. Install Zoom inside a Sandboxie sandbox
3. Launch Zoom and attempt to sign in
4. Zoom will freeze when the sign in button is pressed

My Windows 10 version is 2004.

**Comment by DavidXanatos** [comment]
mmh... try this two test builds

https://drive.google.com/file/d/1L3GjBGc-jnpo7VB4FSHBWC_Q-DgwjtXr/view?usp=sharing
https://drive.google.com/file/d/1oDoE0oY-2MPUPW3-RUKPCx6tByj661z4/view?usp=sharing

and tell me if boot of one of them or no is working for you.

**Comment by DavidBerdik** [comment]
Unfortunately it seems that neither of these builds work as intended.

**Comment by DavidXanatos** [comment]
that is strange,  can you than please verify that the previous build works: https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.3.5

**Comment by DavidBerdik** [comment]
To allow myself to continue using Zoom, I have reverted to using v0.3.5 on my computer. It works perfectly!

**Comment by DavidXanatos** [comment]
And the build SandboxieInstall64-v5.43.1.exe did not work?
that is strange it should revert all changes that may potentially cause issues

**Comment by DavidBerdik** [comment]
Yeah I have no idea. My guess is as good as yours. I might be losing track of version numbers. Is v5.43.1 the version that you linked to here?

> https://drive.google.com/file/d/1L3GjBGc-jnpo7VB4FSHBWC_Q-DgwjtXr/view?usp=sharing
> https://drive.google.com/file/d/1oDoE0oY-2MPUPW3-RUKPCx6tByj661z4/view?usp=sharing

**Comment by DavidXanatos** [comment]
the two links are 5.43.1 and 5.43.2
5.43.1 must imho work as it rolls back all hooking mechanism changes and the snapshot mechanism is dormant when no snapshots are found
so imho whatever works with 5.42.1 should also work with that at least as long as no snapshots have been made.

**Comment by DavidXanatos** [comment]
It seams the issue indeed has somethign to do with one of the changes for teh snapshot mechanism, what is strange as it should behave normally as long as no snapshots are used, i'm looking into it

**Comment by DavidBerdik** [comment]
Have you tested 5.43.1 yourself? If yes, does it work for you?

**Comment by DavidXanatos** [comment]
> 
> 
> Have you tested 5.43.1 yourself? If yes, does it work for you?

yea it works with firefox and windows explorer, but you are right zoom freezes, as i wrote earlier the issue with zoom wasnt the hooking but indeed a smal change around the snapshot system that will be fixed in the next build

**Comment by DavidBerdik** [comment]
Thank you! By the way, I realize this is unrelated, but do you have any further advice for #115? I've done some research on it, but overall I am really struggling.

**Comment by DavidBerdik** [comment]
Sandboxie 5.43.5 fixes the problem, so I am going to close this now. Thank you!
