### ISSUE TITLE
The file tree view in FileBrowserWindow is not fully localized

### ISSUE THREAD

**Issue by gexgd0419** [sandboxie-plus/Sandboxie#1305]
**Describe the bug**
FileBrowserWindow is the window that shows the specified sandbox's content after you right click a sandbox then select Browse Content.

It contains a tree view that shows all files and subdirectories in the sandbox's directory. However, the column names and each item's "type" is always shown in English, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/55008943/137720026-e5b5478e-21e7-4b20-8054-18b3b053ffa3.png)

My system language and the language set in Sandboxie are all Chinese Simplified.
- The title ("DefaultBox - Files") is translated.
- The column titles ("Name", "Size", "Type" and "Date Modified") are still in English.
- The size of desktop.ini (218 bytes) is translated, but it follows the system language setting instead of Sandboxie's setting.
- The item types are not translated. They are just "File Folder" or "&lt;extension&gt; File" in English.

From the code I can know that the tree view's content is provided by `QFileSystemModel`, but it's part of Qt library, so its strings won't appear in sandman's .ts files.

Sandboxie-Plus v0.9.8b

**Comment by gexgd0419** [comment]
Also I found that the Select Color dialog that shows up when you want to change the window border color is also always in English, except the OK and Cancel button.

![image](https://user-images.githubusercontent.com/55008943/137853606-451a6e13-3470-41f9-9dc7-b84e404a7184.png)

It's `QColorDialog`, so the question is how to localize Qt's own components, I guess.

**Comment by gexgd0419** [comment]
In changelog you said that this was fixed in v0.9.8b.

I've installed that version, but these dialogs still seems to be only partially localized in Simplified Chinese.

![image](https://user-images.githubusercontent.com/55008943/138028568-f248bc26-3b0b-415b-a542-35a14803b661.png)

**Comment by DavidXanatos** [comment]
see the \translations folder i added all the original qt translations, i see that thay only provide zh_TW and not _zh_CN so that might be the issue here
