### ISSUE TITLE
Auto Delete bug in Plus version

### ISSUE THREAD

**Issue by NMHy8C** [sandboxie-plus/Sandboxie#131]
When "Advanced Options - Auto delete content when last sandboxed process terminates" is checked, all the content in the sandbox won't be deleted after all the processes terminate.

**Comment by DavidXanatos** [comment]
Oh... indeed it does not, and do you know why; because its only implemented in the SbieCtrl, I somehow missed that, I assumed this functionality would be done by the service.
I will add it to the next SandMan build, such that a running instance of sbie ctrl is no longer needed.

**Comment by NMHy8C** [comment]
Thank you, David.
