### ISSUE TITLE
[0.9.8b] Minor issue with displayed sandboxed processes icons

### ISSUE THREAD

**Issue by Coverlin** [sandboxie-plus/Sandboxie#1310]
**Describe the bug**
Starting a sandboxed process in my example case (discord) will not have any process icon untill sandman reconnects or restarted
Sometimes a process/subprocess displays correct icon without the user taking any of the above action

**Screenshots**
Before
![untitled1](https://user-images.githubusercontent.com/34079190/137982110-54b22f4d-17fe-4e95-9d80-9c8433c4a288.png)

After
![untitled2](https://user-images.githubusercontent.com/34079190/137982135-bf902bcc-3954-40f5-b3c1-bdd1b7c3345a.png)

**System details and installed software**
 - What is your Windows edition and version? (e.g. Windows 10 Pro 20H2 64-bit) w7 64
 - What is your current Sandboxie edition and version? (e.g. Sandboxie Plus 0.9.6 64-bit) 0.9.8b
 - What was your previous Sandboxie version before the update, if any? 0.9.8

**Comment by DavidXanatos** [comment]
[SandMan.zip](https://github.com/sandboxie-plus/Sandboxie/files/7376925/SandMan.zip)
Does the attached version of sandmanexe fixes your issue?

**Comment by Coverlin** [comment]
> [SandMan.zip](https://github.com/sandboxie-plus/Sandboxie/files/7376925/SandMan.zip) Does the attached version of sandmanexe fixes your issue?

Yes it does but another issue : "Error Status: 0xc0000022 (Access is denied.)"
