### ISSUE TITLE
[0.9.8b] Plus is crashing windows 11 while trying to access Chrome

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1311]
### Originally posted by @BilleBarrett in https://github.com/sandboxie-plus/Sandboxie/discussions/1308#discussioncomment-1504721
This update Plus is crashing windows 11 whI tried to access Chrome and Ms Chrome
The Classic version will not allow Chrome to open up. i.e. 94 & 95
How to revert back to previous version

**Comment by BilleBarrett** [comment]
BTW on the new system I just build the newer version run with not change from the install.

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
"Your operating system and Data are only as good as your last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by DavidXanatos** [comment]
Ok, i have revieved the driver changes and I dont see how thay cause a BSOD, so the next thing to test is on the affected system if you change back to the new driver is the crash reproducable?

**Comment by DavidXanatos** [comment]
and if you install the previouse build it works fine,
did you kept the sandboxie.ini?
tra saving it to a backup location and running the new builf with an empty file.
if that works that its some option set there, in which case please send me the affected ini for inspection, if i can reproduce the issue here i can fix it.

**Comment by BilleBarrett** [comment]
Right now I’m running Sandboxie 5.53.0, I’ll install Plus later to night 

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
"Your operating system and Data are only as good as your last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by BilleBarrett** [comment]
Good morning David

I uninstalled everything and save the ini files 

1st I have installed 9.8.0 and made some setting  Sandboxie.9.8

I have just installed 9.8b and so far it is running

I may have been over reacting 

Bill

 

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
"Your operating system and Data are only as good as your last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/
