### ISSUE TITLE
Losing assigned templates in `GlobalSettings` section after global settings change in SandMan

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#1319]
`Sandboxie.ini` must contains `GlobalSettings` with `Template`:
```
[GlobalSettings]

...
Template=Main
Template=Block
Template=Visual
```
It is enough to change any global setting in SandMan, for example, enable checking for updates.
SandMan immediately applies the new settings, but without lines of assigned templates (as in sample).

**Comment by DavidXanatos** [comment]
since there is no more feadback and i cant reproduce it i'll close this

**Comment by Zymlex** [comment]
In subsequent versions, I also couldn't reproduce this problem, probably something was changed in the code.

**Comment by Zymlex** [comment]
@DavidXanatos This problem reproduced again when turned on:

![image](https://user-images.githubusercontent.com/25817412/154806459-4cca7f9c-a506-4a67-aaf0-4a88b6bd46dc.png)
