### ISSUE TITLE
Google Chrome blocks download of SandboxieInstall64-v5.43.exe

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#132]
Reproduce:
* Run Chrome (Version 85.0.4183.102 (Official Build) (64-bit))
* Download https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.4.0/SandboxieInstall64-v5.43.exe
* Chrome displays message "SandboxieInstall64...exe is dangerous, so Chrome has blocked it." [Discard]
  * No option is provided to "keep the file".

Workaround: 
* Powershell > invoke-webrequest

Windows 10 "Windows Defender" does not complain.

VirusTotal website largely clears the file (2/68 engines identify the file):
https://www.virustotal.com/gui/file/2d849d1e6cda005bc5ddc6e95247ed6e0e1184db2d1380fe99999e3765fd8a67/detection

SHA256 of SandboxieInstall is 2D849D1E6CDA005BC5DDC6E95247ED6E0E1184DB2D1380FE99999E3765FD8A67.

**Comment by typpos** [comment]
![Screen shot](https://user-images.githubusercontent.com/28550406/92700276-fede2400-f391-11ea-928c-12d236e5daaf.png)

**Comment by mysteriously** [comment]
Open downloads tab and you will have the ability to keep the file
