### ISSUE TITLE
Firefox and certificate problem

### ISSUE THREAD

**Issue by vpeter4** [sandboxie-plus/Sandboxie#1322]
**Describe the bug**
When connecting to web site with Firefox browser using personal certificate connection fails with this message:

> Secure Connection Failed
> 
> An error occurred during a connection to edavki.durs.si. A PKCS `#11` module returned CKR_GENERAL_ERROR, indicating that an unrecoverable error has occurred.
> 
> Error code: SEC_ERROR_PKCS11_GENERAL_ERROR
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.
> 
> Learn more…      Try Again

**To Reproduce**
1. Open desired web page
2. Select one of the offered certificates
3. See error

**Expected behavior**
Successful connection to web site and continue browsing.

**System details and installed software**
 Microsoft Windows 10 Pro, 10.0.19043 N/A Build 19043
 Sandboxie Classic 5.53.1 64-bit
 Firefox 93.0 64-bit
 NOD32 Antivirus 14.2.24.0

**Additional context**
I'm not really sure if this is even Sandboxie issue because I tested same configuration in Virtual machine when everything works. Also running Edge browser in Sandboxie works.
But I would really appreciate if anyone could give me some pointers why current setup doesn't work.

**Sandboxie configuration**
Using default profile.

**Comment by isaak654** [comment]
A possible workaround was mentioned here: https://github.com/sandboxie-plus/Sandboxie/issues/1679#issuecomment-1065760921

**Comment by mitchcapper** [comment]
Confirmed, personal certificate is client certificate and that is the exact error.  Setting in #1679 does resolve.

**Comment by vpeter4** [comment]
Works for me too. Thank you.
