### ISSUE TITLE
WINE: Failed to connect to the driver

### ISSUE THREAD

**Issue by ylluminate** [sandboxie-plus/Sandboxie#1323]
I'd like to use Sandboxie-Plus in WINE for running certain applications with different settings. When I attempt to do this I get "Failed to connect to the driver":
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/L1uekbXw/c3ad1e66-1624-467b-ba9f-c27547896f69.jpg?v=f79d6184c15a90b430112dcc2292833f)

Can we please figure out a way to run Sandboxie with WINE to use it as a launcher and such for various apps or games where multiple configurations would be useful?

**Comment by Coverlin** [comment]
You should probably try this first https://wiki.winehq.org/FAQ#Where_can_I_get_further_help.3F
