### ISSUE TITLE
[Suggestion] Add UI for each sandbox's file system/registry/IPC root path settings

### ISSUE THREAD

**Issue by gexgd0419** [sandboxie-plus/Sandboxie#1327]
Sandboxie allows users to adjust the *default* file system/registry/IPC root path in the Global Settings.

There's no UI that allows you to change the file system/registry/IPC root path of each sandbox. So I thought that was impossible, and there's only global settings for them. Until I saw [this documentation](https://sandboxie-plus.com/sandboxie/filerootpath/) did I know that I can actually add `FileRootPath=<path>` in the sandbox's INI section.

Adding UI for this will make users more aware of the setting's existence.

Sandboxie-Plus v0.9.8

**Comment by DavidXanatos** [comment]
Because of this considerations: https://github.com/sandboxie-plus/Sandboxie/issues/1531 this will not be added in the UI
