### ISSUE TITLE
"HideHostProcess=SandboxieRpcSs.exe" Does Not Hide SandboxieRpcSs.exe from the Process List

### ISSUE THREAD

**Issue by DavidBerdik** [sandboxie-plus/Sandboxie#1336]
**Describe the bug**
Using the `HideHostProcess` configuration option is supposed to prevent the application listed from being visible in the process list to application running in the sandbox, however, this does not work for `SandboxieRpcSs.exe`, and it is still visible.

**To Reproduce**
1. Add `HideHostProcess=SandboxieRpcSs.exe` to your Sandboxie configuration.
2. Attempt to run an application that will detect the presence of `SandboxieRpcSs.exe`. (I used Respondus LockDown Browser)
3. `SandboxieRpcSs.exe` will be detected even though it is supposed to be hidden according to the rule defined in the configuration file.

**Expected behavior**
`SandboxieRpcSs.exe` is not visible to the process running in the sandbox.

**System details and installed software**
 - Windows 11 Pro for Workstation, x64, build number 22000.282
 - Currently using Sandboxie+ v0.9.8c

This issue was filed at the request of @DavidXanatos after having a discussion about it with him.

**Comment by DavidXanatos** [comment]
with built 1.0.10 every process that's name starts with Sandboxie will be able to be hidden from the sandbox its running in

**Comment by DavidBerdik** [comment]
> with built 1.0.10 every process that's name starts with Sandboxie will be able to be hidden from the sandbox its running in

Cool! I am looking forward to trying it out! And also digging through the code to figure out how you did it since I wasn't able to pull it off myself.

**Comment by LucioAmely** [comment]
> with built 1.0.10 every process that's name starts with Sandboxie will be able to be hidden from the sandbox its running in

David, what about implementing hiding all of the Sandboxie processes and maybe some other things all together under an "Try to hide Sandboxie" checkbox option under the sandbox settings?

**Comment by gettysburg** [comment]
@LucioAmely Exactly what I was thinking.
