### ISSUE TITLE
Sandboxie 5.53.2 - SBIE2310 SBIE2335 SBIE2336

### ISSUE THREAD

**Issue by bytos** [sandboxie-plus/Sandboxie#1342]
The first error I got when running an old game (Legendary on Win10) was SBIE2310 Name buffer is approaching overflow, but when testing the game using Windows compatibility settings got SBIE2336 & SBIE2335, then SBIE2310 again.

![a](https://user-images.githubusercontent.com/16452541/139081523-3bf9a265-a983-4c11-80a2-54b6f0c26d28.png)

**Comment by DavidXanatos** [comment]
i have doubled the buffer size that should take care of the SBIE2310 issue, and possibly fix teh others if the buffer really ran out

**Comment by linax3-genuine** [comment]
im trying to use mods for NFS ProStreet and im still(sbie+1.0.7) unable to do so. the game immediately closes/crashes and sbie shows:
SBIE2310 Name buffer is approaching overflow (21)
SBIE2310 Name buffer is approaching overflow (22)
SBIE2310 Name buffer is approaching overflow (23)
SBIE2310 Name buffer is approaching overflow (24)
SBIE2310 Name buffer is approaching overflow (25)

https://www.pcgamingwiki.com/wiki/Need_for_Speed:_ProStreet#Mods

**Comment by daladalada** [comment]
I have the same issue in sandboxie 5.55.15,  
win10 20h2 19042.1645

**Comment by linax3-genuine** [comment]
i dont remember much, but i think my problem with nfsps got fixed. there is a 5.55.20 version, 5 releases after yours. 
maybe you can try the latest one and see, if its fixed.

**Comment by daladalada** [comment]
Thanks for replying!
I tried the latest version 5.55.20, but when I ran IE in sandboxie here's what happened, 
There is no problem running IE outside the sandbox and I tried reinstalling IE11 and it didn't work.
![image](https://user-images.githubusercontent.com/40569128/166871106-04921566-920d-421a-9fea-c629019f310e.png)

**Comment by DavidXanatos** [comment]
What windows version are you using, and why are you using this issue this was about name buffer you screenshot show soemthign else, 
pelase create a new issue for your problem and provide detailed informations

**Comment by linax3-genuine** [comment]
probably it was more a reply to what i said, than a new issue report.

@daladalada, to clear things out,  2 people reported SBIE2310 with old games, 
**what software is giving you this issue and was it fixed in the latter releases, ignoring your new issues**(SBIE2335, SBIE2336)?

SBIE2335, SBIE2336 were mentioned here as a result of an attempted workaround to fix SBIE2310, i think.
and as a result of some incompatibility with windows' compatibility options. :)

**Comment by rcsantos695** [comment]
i'm same error. can u to fix this?

**Comment by Vstory** [comment]
I also encountered SBIE2335, how to solve it?

![Image](https://github.com/user-attachments/assets/1e28347b-3d44-482a-8deb-c02243c7c082)
