### ISSUE TITLE
Browsers don't recognize Yubikey 5 NFC

### ISSUE THREAD

**Issue by HikariWS** [sandboxie-plus/Sandboxie#1343]
**Describe the bug**
When a browser is on a sandbox it doesn't recognize Yubikey and is unable to use it to authenticate with WebAuthn/U2F/FIDO.

**To Reproduce**
1. Run browser outside sandbox
2. Go to https://demo.yubico.com/webauthn-technical/registration
3. Authentication works
4. Close browser
5. Run browser inside a sandbox
6. Go to https://demo.yubico.com/webauthn-technical/registration
7. It fails with the following msg

The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client

**Expected behavior**
Browser recognized the FIDO device and authentication works.

**System details and installed software**
 - What is your Windows edition and version? Windows 10 Pro Win64 1909
 - What is your current Sandboxie edition and version? Sandboxie 5.49.8 Win64
 - What was your previous Sandboxie version before the update, if any? I haven't updated for some time now

**If you have a compatibility issue**
Tested on Vivaldi 4.3.

**Additional context**
It was working on Brave which ATM isn't being sandboxed. At first I thought it was Vivaldi issue and tried on FireFox where it also didn't work. Then I guessed it was due to Sandboxie and executed Vivaldi outside of it, and it worked.

**Comment by DavidXanatos** [comment]
did you enabled the Yubikey compatibility template?

**Comment by HikariWS** [comment]
tnx, I didn't know there's a template.

I searched for it and found the mention on the changelog. As a reference, it's added to Sandboxie.ini simply as:

`Template=Yubikey`

I'm gonna make some tests and report back how it goes.

**Comment by isaak654** [comment]
See also https://github.com/sandboxie-plus/Sandboxie/issues/596#issuecomment-787019231
