### ISSUE TITLE
does sandboxie leaves trace of deleted files in pc when you Delete content in sandbox?

### ISSUE THREAD

**Issue by abu-101** [sandboxie-plus/Sandboxie#1344]

**Comment by Coverlin** [comment]
short answer : yes

**Comment by abu-101** [comment]
Can you tell me the  location?

**Comment by abu-101** [comment]
I forget to write, I use Portable version of Sandboxie Plus

**Comment by bastik-1001** [comment]
You may want to read about [privacy expectations](https://sandboxie-plus.com/sandboxie/privacyconcerns/) that are not met.

Sandboxie was not designed to mess with how the operating system keeps track of events that happen while the system is running. Sandboxie is not a virtual machine.

You might be able to improve some privacy issues by creating an encrypted storage container, like with VeraCrypt or something similar, to place the sandbox locations inside the mounted container (or some of those to separate the sandboxes). So at least the files created there could only be read while the drive is mounted and if you delete the container its contents can't be read from the disk as they had been encrypted. Of course something might still copy or cache them.
