### ISSUE TITLE
[Plus UI] Two english languages on the language selector

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1348]
**Is your feature request related to a problem? Please describe.**
If you set American English on the Plus UI language selector, it will become International English when you reopen the Global Settings window. I think having both can confuse users (see [here](https://github.com/sandboxie-plus/Sandboxie/discussions/1332#discussioncomment-1559764)).

![Plus_language_selector](https://user-images.githubusercontent.com/12372772/139728578-15810d43-2f3b-4a0e-9776-15e746b70868.png)

**Describe the solution you'd like**
Hide American English from the language selector.

**Comment by isaak654** [comment]
I still have both International English and American English on 1.0.5 build.

**Comment by DavidXanatos** [comment]
That's on purpose!
International English: don't apply any translation use the strings as they are in the binary
American English: use the en-us translation file if present.

**Comment by isaak654** [comment]
> That's on purpose!
International English: don't apply any translation use the strings as they are in the binary 
American English: use the en-us translation file if present.

Interesting, so the first one could be useful to exclude a translation issue. Good to know.
