### ISSUE TITLE
SbieSvc doesn't run SbieCtrl configured to launch with app

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#135]
![изображение](https://user-images.githubusercontent.com/25817412/93002471-ac139080-f57a-11ea-9148-22a6188c45b0.png)
![изображение](https://user-images.githubusercontent.com/25817412/93002444-7e2e4c00-f57a-11ea-8a28-4819e6b1280b.png)

**Comment by DavidXanatos** [comment]
This issue is fixed for the the next build 0.4.3 / 5.43.7 (to be released soon)

**Comment by Zymlex** [comment]
Not fixed in Sandboxie-Plus-x64-v0.4.3.exe

![изображение](https://user-images.githubusercontent.com/25817412/98068386-a3b74200-1ea7-11eb-9dbf-f6357ff7f368.png)

**Comment by Zymlex** [comment]
I wouldn't mind if SandMan.exe was started from a service by Sandboxie-Plus.
