### ISSUE TITLE
delete sbiedrv.sys

### ISSUE THREAD

**Issue by tilenzz** [sandboxie-plus/Sandboxie#1353]
good night, I used windows 7, now I use windows 10, on windows 7 I used to run and delete SbieDrv.sys normally, without problems (I need to delete to play the game I play), and now on windows 10, the file is not deleted , and I can't stop him, how do I?

**Comment by DavidXanatos** [comment]
You can stop the driver using the maintenance menu of the plus ui sandman.exe or manually using the ```kmdutill stop SbieDrv```
than you can delete it.
Windows 10 does not allow to delete the sys file of a loaded driver while on 7 that worked IIRC

**Comment by Kisara-Azure** [comment]
this needs a proper way to be disabled or outright removed without the other parts of the software it's self. kernal level access on a paywall program might as well be flagged as malware

**Comment by DavidXanatos** [comment]
The proper way is to use the maintenance menu or the uninstaller.

> kernal level access on a paywall program

LOL tell that to virtually every antimalware vendor ever.

All antivirus have kernel access and most antivirus have a paywal
