### ISSUE TITLE
[Classic 5.53.3] SbieSvc.exe errors (0xc0000005) in Event Viewer

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1354]
> Sometimes an event viewer error occurs related to Sandboxie 5.53.3 (see attachment):
> https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-8d.441737/#post-3047629
> I have no other security solution installed, only Microsoft Defender!
> 
> I found the cause. It happens when I open microsoft edge pdf sandboxed document. I returned to v 5.53.2 and I removed VirtualDesktop Manager template in Sandboxie.ini settings. I think the VirtualDesktop Manager template it's the problem because for me it's the only setting in addition to 5.53.2.
>
> I also faced other issues with Sandboxie Classic 5.53.3 - gmail connection issues (page freeze) and high disk activity. Now I use Sandboxie Classic 5.33.2 and these problems are gone!
I have windows 10 Pro 21H1, Microsoft Defender only and Windows firewall. My main browser is Mozilla Firefox.

It's weird because I cannot reproduce this myself with Edge 95.0.1020.40 x64, Plus 0.9.8d and Windows 10 x64 21H1.
If you have this issue, please share your findings here.

**Comment by bjm234** [comment]
I found this.  Don't know if related.  
![image](https://user-images.githubusercontent.com/25015553/140603385-02012ddb-57fb-4892-b5f9-3cf3d33234a5.png)

Faulting application name: SbieSvc.exe, version: 5.53.3.0, time stamp: 0x617d91af
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000002340c242850
Faulting process id: 0x1544
Faulting application start time: 0x01d7d1ec8eb6a034
Faulting application path: C:\Program Files\Sandboxie-Plus\SbieSvc.exe
Faulting module path: unknown
Report Id: a2ffe8c2-758f-400d-82ce-02f861c39bfe
Faulting package full name: 
Faulting package-relative application ID: 
--------------------------------------
Faulting application name: SbieSvc.exe, version: 5.53.3.0, time stamp: 0x617d91af
Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x564f9f39
Exception code: 0x40000015
Fault offset: 0x000000000000ae22
Faulting process id: 0xc34
Faulting application start time: 0x01d7d1ced391d654
Faulting application path: C:\Program Files\Sandboxie-Plus\SbieSvc.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: 90dca17b-e897-4548-93c7-c843671fef06
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bjm234** [comment]
Error	11/7/2021 4:56:32 AM	Application Error	1000	(100)
Faulting application name: SbieSvc.exe, version: 5.53.3.0, time stamp: 0x617d91af
Faulting module name: combase.dll, version: 10.0.19041.1288, time stamp: 0x7e843d58
Exception code: 0xc0000005
Fault offset: 0x00000000000c7247
Faulting process id: 0xca4
Faulting application start time: 0x01d7d3bc6a7971f3
Faulting application path: C:\Program Files\Sandboxie-Plus\SbieSvc.exe
Faulting module path: C:\WINDOWS\System32\combase.dll
Report Id: 9537b5b4-7f4a-4869-84f9-29017b2cb108
Faulting package full name: 
Faulting package-relative application ID: 
-----------------------------------------
Error	11/7/2021 4:39:57 AM	Application Error	1000	(100)
Faulting application name: SbieSvc.exe, version: 5.53.3.0, time stamp: 0x617d91af
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000019712287b40
Faulting process id: 0x1aec
Faulting application start time: 0x01d7d3bafb7876d9
Faulting application path: C:\Program Files\Sandboxie-Plus\SbieSvc.exe
Faulting module path: unknown
Report Id: 8eb0640e-aceb-4426-9012-260851340a14
Faulting package full name: 
Faulting package-relative application ID:

**Comment by isaak654** [comment]
David's reply:
> To my understanding the error is with 5.53.3 and the 5.53.2 works fine, i presume this error is related to the com change i need to do in the last build in order to get the virtual desktop stuff to work.
The sbiesvc seams now to be invoked for an other open com path that causes an error log.
I may need to have 2 open com options one for process hoster and one for self hosted com objects but than having 2 different com open setting might be confusing for the user. 

Source: https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-8d.441737/page-2#post-3048234

**Comment by bjm234** [comment]
Log Name:      Application
Source:        Application Error
Date:          11/24/2021 9:25:45 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-DELL
Description:
Faulting application name: SbieSvc.exe, version: 5.53.3.0, time stamp: 0x617d91af
Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x564f9f39
Exception code: 0x40000015
Fault offset: 0x000000000000ae22
Faulting process id: 0x1cc0
Faulting application start time: 0x01d7e1a0bc7afc5d
Faulting application path: C:\Program Files\Sandboxie-Plus\SbieSvc.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: 0e838a3a-7f61-4e2f-8b88-efb98548e5db
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-11-25T02:25:45.2158394Z" />
    <EventRecordID>51021</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-DELL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>SbieSvc.exe</Data>
    <Data>5.53.3.0</Data>
    <Data>617d91af</Data>
    <Data>msvcrt.dll</Data>
    <Data>7.0.19041.546</Data>
    <Data>564f9f39</Data>
    <Data>40000015</Data>
    <Data>000000000000ae22</Data>
    <Data>1cc0</Data>
    <Data>01d7e1a0bc7afc5d</Data>
    <Data>C:\Program Files\Sandboxie-Plus\SbieSvc.exe</Data>
    <Data>C:\WINDOWS\System32\msvcrt.dll</Data>
    <Data>0e838a3a-7f61-4e2f-8b88-efb98548e5db</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by isaak654** [comment]
In theory it should be fixed with this commit: https://github.com/sandboxie-plus/Sandboxie/commit/d7758071f6930539c4e1f236297b4cfa332346ad
Please check the next release when it comes out.

**Comment by isaak654** [comment]
It should be fixed with this commit: https://github.com/sandboxie-plus/Sandboxie/commit/d7758071f6930539c4e1f236297b4cfa332346ad
Please check the next release when it comes out.
