### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by LiteEagle** [sandboxie-plus/Sandboxie#1355]
So basicly i just installed sandboxie and wanted to test if it worked i was quite skeptical so i made a python app that just simply made a log file and ran it in sandboxie to see if it worked and to see if the log file was on my computer, the log file did not get to my computer so that was good. But i was still skepticle so i decided to run Mercail logger wich is a malware builder that is open source and basicly takes your browser info etc to see if it would keep it from reading my info, and it didnt the file was still able to get all my browser info cookies etc so basicly this does work with harmfull programs but not with spyware i recomend putting a security patch somehow on that.

**Comment by isaak654** [comment]
See https://github.com/sandboxie-plus/Sandboxie/issues/890

**Comment by isaak654** [comment]
It's a work in progress, see https://github.com/sandboxie-plus/Sandboxie/issues/890.
