### ISSUE TITLE
Couldn't install or run Epic Games Launcher in sandboxie

### ISSUE THREAD

**Issue by ameaninglessname** [sandboxie-plus/Sandboxie#1356]
**Describe the bug**
Couldn't install or run Epic Games Launcher in sandboxie

**To Reproduce "Couldn't install"**
1. put  "EpicInstaller-12.2.17.msi" into " my sandbox "
2. Click on  "EpicInstaller-12.2.17.msi"
3. "click next" x n

**To Reproduce "Couldn't run sandboxed"**
1. Find "EpicGamesLauncher.exe" on computer disk
2. right click and "run sandboxed"
3. See error

**Trace Logging**

|Time|         |Message|                                                                                    

14:24:40.692   DXSETUP.exe (14424): SBIE1231 Initialization failed for process  [C0000001 / A4]             
14:24:40.694   PID 8368: SBIE2314 Cancelling process DXSETUP.exe                                            
14:25:19.949   EpicGamesLauncher.exe (12424): SBIE1231 Initialization failed for process  [C0000001 / A4]   
14:25:19.950   PID 8368: SBIE2314 Cancelling process EpicGamesLauncher.exe                                  
14:25:27.702   EpicGamesLauncher.exe (3124): SBIE1231 Initialization failed for process  [C0000001 / A4]    
14:25:27.704   PID 8368: SBIE2314 Cancelling process EpicGamesLauncher.exe                                  
14:25:34.952   EpicGamesLauncher.exe (14560): SBIE1231 Initialization failed for process  [C0000001 / A4]   
14:25:34.954   PID 8368: SBIE2314 Cancelling process EpicGamesLauncher.exe                                  
14:26:24.020   EpicGamesLauncher.exe (13288): SBIE1231 Initialization failed for process  [C0000001 / A4]   
14:26:24.022   PID 8368: SBIE2314 Cancelling process EpicGamesLauncher.exe                                  
14:29:05.510   EpicGamesLauncher.exe (12088): SBIE1231 Initialization failed for process  [C0000001 / A4]   
14:29:05.512   PID 8368: SBIE2314 Cancelling process EpicGamesLauncher.exe                                  
14:29:08.832   EpicGamesLauncher.exe (3848): SBIE1231 Initialization failed for process  [C0000001 / A4]    
14:29:08.833   PID 8368: SBIE2314 Cancelling process EpicGamesLauncher.exe                                  
14:29:23.647   Sandboxie config has been reloaded                                                           
14:33:45.200   Sandboxie config has been reloaded                                                           
14:33:45.710   Sandboxie config has been reloaded                                                           

**Expected behavior**
Install or run Epic Games Launcher in sandboxie and play games from it.

**System details and installed software**
 - Windows 10 Pro N 21H1 64-bit 19043.1320
 - Sandboxie Plus 0.9.8d 64-bit
 - previous version :Sandboxie Plus 0.9.8c 64-bit

**Additional context**
I tried to install with different version
[Lastest](https://epicgames-download1.akamaized.net/Builds/UnrealEngineLauncher/Installers/Win32/EpicInstaller-13.0.0.msi?launcherfilename=EpicInstaller-13.0.0.msi)
[Older](https://epicgames-download1.akamaized.net/Builds/UnrealEngineLauncher/Installers/Win32/EpicInstaller-12.2.17.msi?launcherfilename=EpicInstaller-12.2.17.msi)

**Sandboxie configuration**
If applicable, consider to attach your Sandboxie.ini configuration by copying the content on https://gist.github.com and sharing the resulting link. If you decide to paste the configuration here, make sure to use the backticks around strings, like in this working example:

<details>

<summary>My initial sandboxie.ini settings</summary>

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
ClosePrintSpooler=y
WriteFilePath=%Cookies%
WriteFilePath=C:\Users
WriteFilePath=D:\Users
WriteFilePath=C:\Program Files\
WriteFilePath=C:\Program Files (x86)\
WriteFilePath=C:\ProgramData\
WriteFilePath=%Personal%
FakeAdminRights=y
</details>

**Comment by ameaninglessname** [comment]
After some attempts and finding, I successfully installed Epic Games Launcher in sandboxie :
1. Uninstalled the launcher outside the sandboxie
2. add "MsiInstallerExemptions=y" to my sandbox.ini

# See
https://github.com/sandboxie-plus/Sandboxie/issues/1205#issuecomment-922447595

**Comment by ameaninglessname** [comment]
Not sure whether the first step is needed, anyway I could accept that.

**Comment by firgk** [comment]
Before I remove EpicInstaller-17.2.0-b7c42baf14ae4ae5b21afeb353b14450.msi to sandboxie file system, but file to install, ( I've already have   modified my sandbox.ini)
After I rightClick EpicInstaller-17.2.0-b7c42baf14ae4ae5b21afeb353b14450.msi  in physical machine, and open in sand box (which in the meau list) and it works ok
