### ISSUE TITLE
[Plus UI] Chinese Simplified translation is incomplete

### ISSUE THREAD

**Issue by rihalvnium76** [sandboxie-plus/Sandboxie#1357]
**Describe the bug**
Log text translation is not complete.  

P.S. In my memory, it seems that the translation of the log in version 0.9.8 and before is complete

**To Reproduce**
1. Set the SandMan UI language to "简体中文"
2. Restart SandMan

**Screenshots**
![image](https://user-images.githubusercontent.com/57667144/140609436-aad04a41-4d33-4292-996b-54ccb39d33cc.png)

**System details and installed software**
 - Win10 LTSC 2019 x64
 - Sandboxie Plus 0.9.8d x64

**Comment by Bush2021** [comment]
Version 1.0.9 still has this problem (February 2,2022)
![2022-02-02](https://user-images.githubusercontent.com/79072750/152172984-bf8a30e6-2f43-4ecc-bcc7-cf19051e93f9.jpg)

**Comment by isaak654** [comment]
Please help to spread the word about this, thanks:
[ [Plus UI] Create a new workflow to improve delivery of language updates #1595 ](https://github.com/sandboxie-plus/Sandboxie/issues/1595)

**Comment by isaak654** [comment]
Please help to spread the word about this, thanks:
[ [Plus UI] Create a new workflow to improve delivery of language updates](https://github.com/sandboxie-plus/Sandboxie/issues/1595)
