### ISSUE TITLE
[Plus UI] Multiple issues with custom box order

### ISSUE THREAD

**Issue by olliebean** [sandboxie-plus/Sandboxie#1358]
In Sandboxie Control, the option "Set Layout and Groups" allows a custom ordering of the boxes, so I can have my most used ones at the top of the list. Is there a similar option in Sandboxie Plus?

**Comment by isaak654** [comment]
Infact there is a "Move Box / Group" option, but for some reason I can't get it working anymore on 0.9.8, 0.9.8b, 0.9.8c and 0.9.8d:
![Move Box / Group](https://user-images.githubusercontent.com/12372772/140618885-57f4fc55-1b7b-4df6-bff0-095ef8092271.png)

I tried those versions, but the "Move Up" and "Move Down" entries remain always greyed out.

**Comment by Coverlin** [comment]
@isaak654 @olliebean 
To make that feature work click on the Name column until the Ascending`▲`/Descending`▼` order is not used

Also column Name seems to not have Descending order.. possibly intended / replaced by custom order

**Comment by olliebean** [comment]
Thanks - I hadn't noticed the "Move Box/Group" option. Seems easier to use the Alt+Up/Down keys than the menu entries. Things were moving a bit erratically at first, a hangover I think from the order I had them in in Sandboxie Control, but after fiddling with it for a while it seems to be working properly now.

**Comment by isaak654** [comment]
> Spoke too soon - just after posting that, I created a new box and suddenly all my previous changes to the box order were undone - including some groups I'd created, they were gone and all the boxes I'd put in them were back in the main list. So I guess this is a bug, after all.

I think this is another sorting issue. If you came from Sandboxie Classic, you will need to replace `SbieCtrl_BoxExpandedView` with `BoxDisplayOrder` in the Sandboxie.ini configuration file, making sure that it contains all the sandboxes separated by commas.

So there are two sorting issues in total.

**Comment by Coverlin** [comment]
> Spoke too soon - just after posting that, I created a new box and suddenly all my previous changes to the box order were undone - including some groups I'd created, they were gone and all the boxes I'd put in them were back in the main list. So I guess this is a bug, after all.

Workaround # 2 : `BoxDisplayOrder` is saved without issues when you exit sandman ( file menu `Sandbox` ->` Exit` ) after customizing the order and groups  **don't disconnect or/and as you already found out don't create new boxes before saving the new layout** (also do not manually reload ini just to be safe)
Worked fine with and without the BoxDisplayOrder present in ini and with watch ini for changes setting on

`SbieCtrl_BoxExpandedView` is only used by classic to keep track of "expanded' boxes that shows you the list of running processes otherwise the active sandbox will have the running processes collapsed (hidden from view)


Issue # 3 : The Move box/group context menu will create more than 1 [None] on related actions

**Comment by olliebean** [comment]
> Workaround # 2 : `BoxDisplayOrder` is saved without issues when you exit sandman ( file menu `Sandbox` ->` Exit` ) after customizing the order and groups **don't disconnect or/and as you already found out don't create new boxes before saving the new layout** (also do not manually reload ini just to be safe) Worked fine with and without the BoxDisplayOrder present in ini and with watch ini for changes setting on

Thanks, the trick seems to be to quit and restart Sandboxie Plus after making any changes to the layout. It doesn't seem to be saved under `BoxDisplayOrder` in the ini file though - that was unchanged after editing the layout and quitting, and still contains the names of boxes I deleted ages ago in Classic.

**Comment by olliebean** [comment]
> It doesn't seem to be saved under `BoxDisplayOrder` in the ini file though - that was unchanged after editing the layout and quitting, and still contains the names of boxes I deleted ages ago in Classic.

Just discovered there's a second `UserSettings` section in my ini file, 3/4 of the way down and stuck in between two of my boxes, and the `BoxDisplayOrder` is being saved there. The `UserSettings` section at the top of the file must be left over from an old installation.

**Comment by DavidXanatos** [comment]
1 is intended you can only move up and down in the non alphabetic view, rest will be fixed in the next build
