### ISSUE TITLE
Portable version for v0.4.1

### ISSUE THREAD

**Issue by setyb** [sandboxie-plus/Sandboxie#136]
For v0.3.5, you kindly provided a portable version in the GitHub releases.

I don't see any portable version for v0.4.1 on GitHub.

Do you have one?  Thanks you for your help.

**Comment by Coverlin** [comment]
> For v0.3.5, you kindly provided a portable version in the GitHub releases.
> 
> I don't see any portable version for v0.4.1 on GitHub.
> 
> Do you have one? Thanks you for your help.

The plus installer has a portable option (extract files)

**Comment by DavidXanatos** [comment]
> 
> 
> > For v0.3.5, you kindly provided a portable version in the GitHub releases.
> > I don't see any portable version for v0.4.1 on GitHub.
> > Do you have one? Thanks you for your help.
> 
> The plus installer has a portable option (extract files)

yes, just extract the files and voila, portable version

**Comment by setyb** [comment]
Thank you @Coverlin and @DavidXanatos.

So is the solution to run the installer and select an option to extract the files, or to just use a third-party zip tool to extract them?

**Comment by DavidXanatos** [comment]
> 
> 
> Thank you @Coverlin and @DavidXanatos.
> 
> So is the solution to run the installer and select an option to extract the files, or to just use a third-party zip tool to extract them?

run the installer and select an option to extract the files

a third-party zip will not work as the format of the installer is very custom.
