### ISSUE TITLE
Hidden host process function does not work

### ISSUE THREAD

**Issue by rihalvnium76** [sandboxie-plus/Sandboxie#1360]
**Describe the bug**
Using the `HideHostProcess` configuration option is supposed to prevent the application listed from being visible in the process list to application running in the sandbox, however, hidden applications can still be detected.

**To Reproduce**
1. Add `HideHostProcess=XXX.exe` (Any executable file can be replaced here) to any sandbox configuration
2. Run `XXX.exe` in the host environment
3. Run  `cmd` in this sandbox
4. Run `tasklist` in the cmd
5. Hidden application can still be detected

**Screenshots**
![image](https://user-images.githubusercontent.com/57667144/140653463-ebf0319c-9bf9-4ef0-8a3a-4eeee331ff2a.png)
![image](https://user-images.githubusercontent.com/57667144/140653807-13215f53-e9b8-48e1-87c6-80a8b05712ca.png)
![image](https://user-images.githubusercontent.com/57667144/140653498-882681d5-c8f8-4b40-b8d8-8944884f9609.png)

**Expected behavior**
Hidden applications can not be detected by applications in the sandbox.

**System details and installed software**
 - Win10 LTSC 2019 x64
 - Sandboxie Plus 0.9.8d x64

**Comment by DavidXanatos** [comment]
this is know task list is using WIM which connects to a unsandboxed server process, there is no reasonable way to fix this
