### ISSUE TITLE
[Classic 5.53.3] Error after installing Sandboxie

### ISSUE THREAD

**Issue by TheLevelCode** [sandboxie-plus/Sandboxie#1363]
**Describe the bug**
Trying to install and reinstall Sandboxie causes an unsigned driver error on my PC
**To Reproduce**
1. Install Sandboxie x64-Bit 5.53.3
2. After driver installation, this error appears

**Screenshots**
Screenshot I took:
![issue4](https://user-images.githubusercontent.com/63305091/140846375-180b563b-13dd-4722-8dc5-368b356970e1.JPG)
This also happens when reinstalling Sandboxie, the same driver gets unavailable by Windows (Sorry for the spanish btw, might translate it later)

**Expected behavior**
A normal installation without any issues I guess

**System details and installed software**
 - Windows edition and version: Windows 7 Ultimate x64-Bit Service Pack 1
 - Current Sandboxie edition and version: Sandboxie Classic 5.53.3 64-bit
 - Previous Sandboxie version before the update, if any: I'm new to Sandboxie, so no prevoius versions were installed
 - Mention in which version this bug got introduced: No idea
 - Mention any security software running in the background, even if the real-time protection is disabled. Something with Windows probably

**If you have a compatibility issue**
I don't think this issue is compatibility related, tho you never know

**Additional context**
While getting my first installation ready, I have noticed an error about one of the drivers not being digitally signed, so Windows itself made the driver unavailable, this also causes other issues while running Sandboxie, there may be a fix to this already and I'm not noticing about it, or simply this is a random error no one got before, _**or**_ this is a normal error which I highly doubt

**Sandboxie configuration**
There is no Sandboxie.ini generated in my case

**Comment by mpheath** [comment]
Perhaps you do not have KB4474419 hotfix installed. This is for SHA-2. Without, the driver certificate may not be able to be validated.

Minimal updates for Windows 7 that I recommend:

 1. KB4490628 [Servicing Stack Update](https://www.catalog.update.microsoft.com/search.aspx?q=kb4490628)
 2. KB4474419 [SHA-2 Update](https://www.catalog.update.microsoft.com/search.aspx?q=kb4474419)
 3. Restart OS
 4. KB4536952 [Servicing Stack Update](https://www.catalog.update.microsoft.com/search.aspx?q=kb4536952)
 5. KB3125574 [Rollup Update](https://www.catalog.update.microsoft.com/search.aspx?q=kb3125574)

Might be able to do 1 to 3 and try installing Sandboxie again. Though 1 to 5 is what I recommend as the Rollup will have many other fixes.

Get list of installed Hotfix IDs in a command prompt: `wmic qfe get hotfixid`

Sandboxie x64-Bit 5.53.3 installs OK in Windows 7 for me with those updates installed.

**Comment by TheLevelCode** [comment]
Well after installing the updates I can confirm that everything works fine, the SHA-2 Update really made my day since a lot of websites that were unable to load in Chrome they do now, after intalling everything Sandboxie opens without issues, so this issue can now be closed
