### ISSUE TITLE
Do i need to walk through hell ....

### ISSUE THREAD

**Issue by aznboy84** [sandboxie-plus/Sandboxie#1364]
Out of my expectations, the .sln projects doesn't work :
 - The "plus" things is missing qt stuffs
![image](https://user-images.githubusercontent.com/6320782/140958853-d781bc3b-aa5b-42b4-a7b2-52afa4daaef7.png)

 - The "classic" things don't have the msgs.h
![image](https://user-images.githubusercontent.com/6320782/140958296-616e18f3-bf1b-4348-b2df-67d2abd4dcc1.png)
which i assume to be some kind of "language" header that could be generate through the "parse.exe", which threw CR/LF error because they required all text files to end a line with both CR/LF, which, by the way, all the text files in that folder having their lines ended with a single LF.
![image](https://user-images.githubusercontent.com/6320782/140959939-d7e398d7-6dab-439d-8aad-94f704d3a106.png)
so, i replaced all the LF inside txt files with CRLF, this time the parse.exe don't throw an error but they also write nothing to the disk, also trying to recompile the "parse" project throws an error on the custom build scripts ....

At this point i gave up, since i don't have the willing to walk through hell to have a working sandboxie project ...
(and by the way where the hell is the "mc.exe" in the custom build script ...)

**Comment by DavidXanatos** [comment]
Did you installed Qt and the requires Qt extension for visual studio?

As you can see with the automated CI auto build (https://github.com/sandboxie-plus/Sandboxie/blob/master/.github/workflows/main.yml) its quite strait forward to compile Sandboxie-Plus

**Comment by typpos** [comment]
A screen recording video to show how to go from a clean virtual machine all the way to successfully build Sandboxie would be great. A script to execute all these steps would make it easy for people to get started (and contribute) and could be used for occasional QA.

**Comment by xujin1982** [comment]
I fixed the "plus" things by installing QT extension. 
However, I have the same issue with "The "classic" things don't have the msgs.h".

**Comment by DavidXanatos** [comment]
msgs.h is generated by the parser peoject when its executed

**Comment by xujin1982** [comment]
> 
> 
> msgs.h is generated by the parser peoject when its executed

The parser peoject is not build correctly. I have the same error information with @aznboy84 as listed below.

Severity	
Error	
========================
Code	
MSB3073	
========================
Description
The command "@echo off
setlocal enabledelayedexpansion enableextensions
Set PARSE_ARGS=
copy Sbie-English-1033.txt Text-English-1033.txt
for %%f in (Text-*.txt) do (Set PARSE_ARGS=%%f !PARSE_ARGS!)
SbieRelease\parse %PARSE_ARGS% 2> ParseOutput.log
if not errorlevel 1 goto end
echo *** PARSE FAILURE! ***
exit 1
:end
mc /h D:\sandboxie\Sandboxie\msgs\SbieRelease /r D:\sandboxie\Sandboxie\msgs\SbieRelease -u D:\sandboxie\Sandboxie\msgs\msgs.mc

:VCEnd" exited with code 1.	
========================
Project	
Parse	
========================
File	
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	
========================
Line
286	
========================
Suppression State
N/A

**Comment by aznboy84** [comment]
Update : I managed to build the "classic" by modify the parser code to remove the "CR" part, after that the entire project is built.
I haven't test the plus yet, but i think it should be buildable too with qt installed (which i don't, since they keep asking for money - please pay us if you're using qt for commercial blah blah .
The entire problem is just the text files format ...

**Comment by DavidXanatos** [comment]
Just download the open source Qt version it is LGPL meaning you can use it for free for what ever and however as long as you don't compile and distribute an own build of Qt you have 0 obligations, troubles or issues.
Qt is misrepresenting the implications of using LGPL code to extract payments from their users.

**Comment by isaak654** [comment]
> Update : I managed to build the "classic" by modify the parser code to remove the "CR" part, after that the entire project is built. 

@aznboy84 
Could you be more specific and share more details about this code change?

**Comment by aznboy84** [comment]
> 
> 
> > Update : I managed to build the "classic" by modify the parser code to remove the "CR" part, after that the entire project is built.
> 
> @aznboy84 Could you be more specific and share more details about this code change?

void ReadTextFile(const UCHAR *path, LIST *msgs)
{
    HANDLE hFile;
    ULONG ByteSize, ReadSize;
    UCHAR* Buffer;
    WCHAR *BufPtr;
    ULONG LineNum;
    ULONG i;
    BOOLEAN isUTF8 = TRUE;

    //
    // read entire contents of text file
    //

    hFile = CreateFileA(path, FILE_READ_DATA, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    if (hFile == INVALID_HANDLE_VALUE) {
        fprintf(stderr, "can\'t open input file - %s\n", path);
        exit(EXIT_FAILURE);
    }

    ByteSize = GetFileSize(hFile, NULL);
    if (ByteSize)
        Buffer = Alloc(ByteSize + 16);
    else
        Buffer = NULL;

    if (! ReadFile(hFile, Buffer, ByteSize, &ReadSize, NULL))
        ReadSize = 0;
    if (ReadSize == 0 || ReadSize != ByteSize) {
        fprintf(stderr, "can\'t read input file - %s\n", path);
        exit(EXIT_FAILURE);
    }

    CloseHandle(hFile);

    memset(&Buffer[ReadSize], 0, 16);

    //
    // build list of messages
    //

    List_Init(msgs);

    LineNum = 1;


    if (Buffer[0] == 0xFF && Buffer[1] == 0xFE) // Unicode BOM
    {
        BufPtr = &Buffer[2];
        ReadSize -= 2;
        isUTF8 = FALSE;
    }
    else if (Buffer[0] == 0xEF && Buffer[1] == 0xBB && Buffer[2] == 0xBF)  // UTF8 BOM
    {
        BufPtr = &Buffer[3];
        ReadSize -= 3;
        isUTF8 = TRUE;
    }
    else
        BufPtr = Buffer;

    if (isUTF8)
    {
        char* utf8 = BufPtr;

        ByteSize = MultiByteToWideChar(CP_UTF8, 0, utf8, ReadSize, NULL, 0) + 1;
        Buffer = Alloc(ByteSize * sizeof(wchar_t));
        BufPtr = Buffer;

        MultiByteToWideChar(CP_UTF8, 0, utf8, ReadSize, BufPtr, ByteSize);
    }

    while (1) {

        //WCHAR *Cr = wcschr(BufPtr, L'\r');
        WCHAR *Lf = wcschr(BufPtr, L'\n');
        ULONG Len;

        if (/*BufPtr[0] == L'\r' && */BufPtr[1] == L'\n')
            ++LineNum;

        if (/*Cr == BufPtr || */Lf == BufPtr) {
            ++BufPtr;
            continue;
        }

        /*if (Cr && Cr < Lf)
            Len = Cr - BufPtr;
        else */if (Lf)
            Len = Lf - BufPtr;
        else
            break;

        /*if (Lf != Cr + 1) {
            fprintf(stderr, "\ncrlf error - %s - line %d - %*.*S\n", path, LineNum, Len, Len, BufPtr);
            exit(EXIT_FAILURE);
        }*/

        if (*BufPtr != L'#') {

            Len = AddTextEntry(path, BufPtr, msgs, LineNum);
            for (i = 0; i < Len; ++i)
                if (/*BufPtr[i] == L'\r' && */ BufPtr[i + 1] == L'\n') {
                    ++LineNum;
                    ++i;
                }

            ++LineNum;
        }

        BufPtr += Len;
    }
}

**Comment by isaak654** [comment]
So changing all the line endings to CRLF in all files on `Sandboxie/msgs` folder didn't make any difference before that change?

**Comment by isaak654** [comment]
So setting the line endings to CRLF in all files on `Sandboxie/msgs` folder didn't make any difference before your code changes?
