### ISSUE TITLE
Better (additional) systray icon

### ISSUE THREAD

**Issue by Pomax** [sandboxie-plus/Sandboxie#1365]
**Describe the bug**

The systray icon is currently lots of different colors, and doesn't vertically fill the same space that windows' own icons, and most application icons, do, without an option to pick from a set of icons to make sure it fits the rest of the systray

**Screenshots**

![image](https://user-images.githubusercontent.com/177243/141168788-a2c0ef40-7535-462d-a201-21cdeb2e454f.png)

_a screenshot showing off the height discrepancy, and coloring confusion_

**Expected behavior**

I expected there to be an advanced UI option to pick the systray icon, including a more "boring" but visually fitting one similar to the original sandboxie, with one dominant colour so that it can be placed in an ordered systray and be easier to find because its location makes psychological sense.

**Additional context**

By all means, keep the current icon the default, but it would be _super_ helpful to also have a more "boring, but stylistically fitting" icon (and possibly a third, "white, mostly-outline-only" icon that fits with windows' own icon style)

**Comment by Coverlin** [comment]
>... but visually fitting one similar to the original sandboxie, ...

![untitled](https://user-images.githubusercontent.com/34079190/141175126-8368d7ad-9a34-4bdd-9986-f57073992300.png)

Click gears icon and you can use the classic icon

**Comment by Pomax** [comment]
Interesting, I was seeing this:

![image](https://user-images.githubusercontent.com/177243/141246014-ef82d32c-f442-4446-92da-033c6783f92f.png)

Forced sandboxie plus to update, and I now see that setting. However, the icon doesn't look quite the right size:

![image](https://user-images.githubusercontent.com/177243/141246230-2ced9570-97a6-4e29-b002-a3f8a29e6c13.png)

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/141300023-d143b52f-b4f4-40ed-8bf1-0e0ac347fe51.png)
the icon is absolutely where it should be and as large as it should be, you can open SbieCtrl.exe on the side and compare

**Comment by Pomax** [comment]
Yes, that's what I said. but _optically_ it isn't, because of those thick borders.

**Comment by linax3-genuine** [comment]
apparently this is about the bad new icons. 
yes they are bad. an icon should be an easy to recognize symbol. not some 5yo picasso's artistic attempts.

**Comment by DavidXanatos** [comment]
in that case make a better icon ;)

**Comment by linax3-genuine** [comment]
ok. but wasnt there a good old one? why do we need to change it?

**Comment by isaak654** [comment]
> ok. but wasnt there a good old one? why do we need to change it?

You mean "why not apply the Classic icon by default instead to apply it manually" ?

**Comment by linax3-genuine** [comment]
i have that option enabled, but the main windows have the new icons and they are quite disturbing, for a software that im supposed to use, to protect myself from harm.

**Comment by isaak654** [comment]
Just in case, my suggestion provided [here](https://github.com/sandboxie-plus/Sandboxie/issues/963#issuecomment-904038046) is still valid (no need to rush).

**Comment by isaak654** [comment]
Any news?
