### ISSUE TITLE
SetCursorPos sets wrong coordinates with high-DPI scaling screens

### ISSUE THREAD

**Issue by alvinhochun** [sandboxie-plus/Sandboxie#1369]
**Describe the bug**
I haven't checked thoroughly, but from what I've experienced with running Blender under Sandboxie, it wraps the mouse cursor around the viewport when performing transformations and viewport controls, and here it always wrap the cursor to the wrong position.

**To Reproduce**
1. Set monitor to 200% scaling
2. Run Blender under Sandboxie
3. Use the default file with the default cube
4. With the cursor inside the viewport area, press `g` to enter "Move" mode
5. Move the cursor past the edge of the viewport
6. Observe how the cursor moves. The cursor will be warped to the expected coordinates multiplied by two.

**Screenshots**

**Expected behavior**
The cursor should be wrapped to the exact opposite end of the viewport.

**System details and installed software**
 - Windows 10 Pro 20H1 64-bit
 - Sandboxie Plus 0.9.6 64-bit
 - I don't think this is a recent regression
 - Windows Defender is enabled (not that it would matter)

**If you have a compatibility issue**
 - Blender: https://www.blender.org/
 - Anything that calls `SetCursorPos` and is high-DPI aware

**Additional context**
Seeing that Sandboxie [hooks](https://github.com/sandboxie-plus/Sandboxie/blob/294966c7d6e99cd153ede87ad09aa39ef29e34c3/Sandboxie/core/dll/guimisc.c#L457) and [proxies](https://github.com/sandboxie-plus/Sandboxie/blob/294966c7d6e99cd153ede87ad09aa39ef29e34c3/Sandboxie/core/svc/GuiServer.cpp#L3334) the API call, I have a suspicion that it is due to the different DPI awareness of the Blender process and the Sandboxie GUI server (or whatever it is that actually performs the API call). Blender is per-monitor DPI aware (can be checked with Task Manager).

The `SendInput` API might also be affected by the same issue. There are also other WinAPIs which changes behaviour depending on the DPI awareness of the calling thread/process which might need attention.

**Comment by DavidXanatos** [comment]
> Seeing that Sandboxie hooks and proxies the API call, I have a suspicion that it is due to the different DPI awareness of the Blender process and the Sandboxie GUI server (or whatever it is that actually performs the API call). Blender is per-monitor DPI aware (can be checked with Task Manager).
>

yes that is very likely the issue

**Comment by alvinhochun** [comment]
I made some changes to possibly fix only `SetCursorPos` and `ClipCursor`, but I couldn't get it to run locally over the installed version just yet. Any tips?

https://github.com/sandboxie-plus/Sandboxie/compare/master...alvinhochun:cursor-dpi-aware

**Comment by alvinhochun** [comment]
Okay, it took some effort but I was able to verify that my fix does fix the issue, at least for `SetCursorPos` with Blender.

**Comment by DavidXanatos** [comment]
The next build will be ready soon, with this fix, thanks for finding a solution, if you contact me on gmail, I'll send you a supporter certificate with the type contributor.
