### ISSUE TITLE
[Minor issue/annoyance] Plus-x64-v0.4.1 Message SBIE2205

### ISSUE THREAD

**Issue by Coverlin** [sandboxie-plus/Sandboxie#137]
SBIE2205 Service not implemented:  PreferExternalManifest

Stepts to reproduce : 
1. Install Sandboxie-Plus-x64-v0.4.1
2. Start SbieCtrl.exe 
3. Run any exe sandboxed

No message when using v5.43.5 install SbieCtrl.exe or skipping step 2
Error code can be hidden but will still appear in sandman

OS:Windows 7 Ultimate 64-bit SP1

**Comment by DavidXanatos** [comment]
that is strange,
please got to HKLM\SYSTEM\ControlSet001\Services\SbieSvc
and check if the entry PreferExternalManifest = 1 exists
it should if it does not that causes this issue.

**Comment by Coverlin** [comment]
> that is strange,
> please got to HKLM\SYSTEM\ControlSet001\Services\SbieSvc
> and check if the entry PreferExternalManifest = 1 exists
> it should if it does not that causes this issue.

Thank you that was it , but my system seems to ignore the controlset# , the entry was missing from CurrentControlSet , v5.43.5 did create it
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\SbieSvc]
> "PreferExternalManifest"=dword:00000001
