### ISSUE TITLE
Systray icon is loaded even though the settings are set to "do not show an icon"

### ISSUE THREAD

**Issue by Pomax** [sandboxie-plus/Sandboxie#1370]
**Describe the bug**

I've set sandboxie (v0.9.8d) to not show a systray icon, but if I reboot, sandboxie still puts the icon in the systray until I change the option, apply, and the set it back to none, and apply a again.

![image](https://user-images.githubusercontent.com/177243/141659652-189e81a8-d85c-4e8d-8531-045d8a37a9d4.png)

**Comment by DavidXanatos** [comment]
yes that is expected, to disable this behavioure fully ou need to also disable auto start.
or what would you want the tool to do on boot open a unsolicited window each time?

**Comment by Pomax** [comment]
I assumed that "auto start" meant all of sandboxie, as in if that isn't turned on, you can't run anything in a sandbox because its drivers don't get loaded. Is that not the case?

**Comment by DavidXanatos** [comment]
no autostart is only for the ui the sandboxie service starts always automatically

**Comment by Pomax** [comment]
I see, in that case this is indeed a non-issue and I'll just turn that off. thank you.
