### ISSUE TITLE
Microsoft Teams dies unexpectly (x64.json)

### ISSUE THREAD

**Issue by szusik** [sandboxie-plus/Sandboxie#1373]
I'm trying to run MS Teams in sandbox with basically default setup.
Application dies every couple dozen of minutes, less then hour most of the time.
I have latest Sandboxie-plus (0.9.6) on Windows 10 x64 - but the issue is there for few versions already.
I think almost all the time, just one second before crash teams show "Save file" dialog with proposed name "x64.json".
Does not matter what you do - app is gone.
If you are fast enough then file saves on the disk with empty content.

I would love to provide more feedback - just let me know what it could be

**Comment by DonForigua** [comment]
I have the similar issue

**Comment by isaak654** [comment]
If you wish, you can still open a [new report](https://github.com/sandboxie-plus/Sandboxie/issues/new/choose) for your calls issues.
Further instructions about the creation of crash dumps on the sandbox itself were provided in the v1.0.5 / 5.55.5 changelog:

> added sandbox top level exception handler to create crash dumps -- it can be enabled per process or globally using "EnableMiniDump=process.exe,y" or "EnableMiniDump=y" respectively -- the dump flags can be set as hex with "MiniDumpFlags=0xAABBCCDD" -- a preselected flag set for a verbose dump can be set with "MiniDumpFlags=Extended" -- Note: created dump files are located at: `C:\Sandbox\%USER%\%SANDBOX%`
