### ISSUE TITLE
File Recovery dialog keeps grabbing focus

### ISSUE THREAD

**Issue by olliebean** [sandboxie-plus/Sandboxie#1374]
**Describe the bug**
Every time a file is created or updated in the file recovery folders of a box, the File Recovery dialog grabs focus.

**To Reproduce**
Run any program in a box, which regularly creates or updates files within one or more of the file recovery folders set up for that box.

**Expected behavior**
As in Sandboxie Control, the File Recovery dialog should grab focus only when it first appears; as long as the dialog is left open, subsequent changes in the file recovery folders should not make it grab focus.

**System details and installed software**
 - What is your Windows edition and version? Windows 10 Pro 20H2 64-bit
 - What is your current Sandboxie edition and version? Sandboxie Plus 0.9.8d 64-bit
 - What was your previous Sandboxie version before the update, if any? Sandboxie Classic (not sure of version number)

**Comment by olliebean** [comment]
Is there any comment on this? It's a real problem; it makes it damn near impossible to use any other program whilst a sandboxed program is regularly saving to a recoverable file. "Close until all programs stop in this box" isn't a great solution because it relies on me remembering to manually open the File Recovery dialog later. Also I've had problems on occasion having to take several tries to select that option because of the dialog grabbing focus from itself.

**Comment by olliebean** [comment]
I have just downloaded the latest build (v1.0.19), and this is only partially fixed - the File Recovery dialog no longer grabs focus when an existing file is updated, but it still does every time a new file is added. So it's still a problem with programs that regularly save new files.

**Comment by cheaphandymandubai** [comment]
This issue needs to be fixed to improve user experience by allowing background operation. For more information, visit here: https://uaedatarecovery.com/
