### ISSUE TITLE
CreateSymbolicLink returns failed

### ISSUE THREAD

**Issue by 344389541** [sandboxie-plus/Sandboxie#1375]
```
int main()
{
	BOOL ret = CreateSymbolicLinkA(R"(C:\list_link)", R"(C:\list)", SYMBOLIC_LINK_FLAG_DIRECTORY);
	std::cout << ret << " " << GetLastError() << "\n";
	system("pause");
	return 0;
}
```

sandbox 5.50.9
C:\list is my local directory
CreateSymbolicLink returns failed, but in fact the file in the sandbox was created successfully

**Comment by onhitsu** [comment]
I use `mklink /D` command created symlink file successfully in Sandboxie-Plus-x64-v1.1.3, but I found something strange when I try to rename symlink file.
The file that is actually renamed is the source file, not the symlink file I specified.
