### ISSUE TITLE
Problem caused by the CWD always being %SystemRoot%\system32 at startup

### ISSUE THREAD

**Issue by ZalerC** [sandboxie-plus/Sandboxie#1377]
When I started the program by using `Run Program`, I found that some of the programs did not work properly. Then a search for issues revealed this decision:
> fyi: the start dir wil always be c:\windows\system32 from now on out
> _Originally posted by @DavidXanatos in https://github.com/sandboxie-plus/Sandboxie/issues/1071#issuecomment-894753243_

This makes the CWD default to `%SystemRoot%\system32` for all programs launched via SandMan (e.g. `Run Program`, `Run Menu`, `Auto Start`). Since Windows default policy for `Run Program` is that the CWD is the program's directory, any search for resources in a program using the CWD instead of the program's directory will cause the following problems:
1. Search for resources in `%SystemRoot%\system32`, nothing was found.
2. Write anything in `%SystemRoot%\system32` instead of the program's directory.

**System details and installed software (please provide the following information):**
Winows7 SP1, Sandboxie-Plus 0.9.8d

**Comment by nedsociety** [comment]
Yes, at the time I reported #1071 I was a bit unsure if it were running on Explorer's current directory or system32 before the change, but recently I also feel disparity to have it on system32. The Explorer's current directory should be the right location to start.

**Comment by DavidXanatos** [comment]
should be fixed since quie a few builds acually
