### ISSUE TITLE
[Plus UI] Text cut-off on Box Types drop-down list

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1381]
### - Describe the bug
It affects Italian and both Portuguese languages, see the screenshots below.
Screen Resolution is 1600x1200, dpi scaling is at 100% (recommended).
Windows 10 22H2 on a Virtualbox VM.

### - Screenshots
![Box Types Italian](https://user-images.githubusercontent.com/12372772/142327859-ffd1ba5b-136f-498b-9ac8-b688f641f061.png)
![Text being cut in Sandman 1.0.14 for Portuguese languages](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/47754550-0bef-4942-ad75-249a74a2241b)

**Comment by DavidXanatos** [comment]
is this issue still present?

**Comment by isaak654** [comment]
I can confirm it on 1.0.17. 
Somehow Plus UI can't resize that dropdown list correctly with the screen resolution described in the first post.

**Comment by DavidXanatos** [comment]
its stange that on my system the texts are not cut will investigat that further

**Comment by isaak654** [comment]
This is still an issue on Plus 1.2.6 when using High DPI scaling set to "None" in the Interface Config.

The workaround in this case is to switch the "None" option to "Native":
![Interface_config_Plus](https://user-images.githubusercontent.com/12372772/181903428-2627d60b-7a9a-4262-a18b-d5e19872bfdf.png)

### Notes

- It happens only when the "None" option is combined with the Font Scaling option set to 100%.
- The internal Qt 6 build you passed me privately doesn't have this issue at all.

**Comment by isaak654** [comment]
I've just checked again this issue in version 1.10.4 and now it can be reproduced for Italian, Portuguese and Brazilian Portuguese languages in Plus UI when the following settings are set:

> **Important**
> ![Windows 10 version](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/f36e65e3-9896-4f65-8779-1c8763955e5c)
> ![DPI value and screen resolution in Windows 10](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/cec4a083-4e6a-4f49-93d9-324e1c84dacf)
> ![DPI value in Sandman](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/52d1e233-a4bb-4d51-bcc5-2bf1f5ad57a8)

> **Note**
> The new workaround to bypass the issue is to set a high DPI value in Sandman:
> ![sandman_workaround](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/172e7204-14c2-45dd-ae41-a1c85162ec9d)
