### ISSUE TITLE
[SbiePlus] "Create New Box" and "Create Box Group" entries are greyed out

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1382]
**Describe the bug**
"Create New Box" and "Create Box Group" menu entries are greyed out soon after running SandMan.exe

**To Reproduce**
I can reproduce this issue on Plus 0.9.8d, 1.0.0, 1.0.4 in two Windows 10 installations:
1. Make sure to not have running SandMan.exe instances
2. Open SandMan.exe from the desktop icon
3. Right-click on an empty spot below the last sandbox
4. See the screenshot below:
![Create options greyed out](https://user-images.githubusercontent.com/12372772/142332547-a61a0327-830e-4da4-bb71-82453947e318.png)

**Workaround**
- Right-click on the last sandbox, then right-click on an empty spot below... the "Create New Box" and "Create Box Group" menu entries won't be greyed out anymore. Or you can just go to the Sandbox menu at the top.
- Reduce the height below the last sandbox in order to prevent right clicks.

**Expected behavior**
"Create New Box" and "Create Box Group" menu entries should be always available.

**Comment by isaak654** [comment]
I hope this bug can be fixed, it's annoying to see.

**Comment by Shadowized** [comment]
I noticed this too. a funny workaround is to first rightclick any existing box and then rightclick on the blank area.
