### ISSUE TITLE
SBIE1314 Blocked request to alter network/firewall settings by process

### ISSUE THREAD

**Issue by wpresources** [sandboxie-plus/Sandboxie#1385]
I read the error information and information in related links at
https://sandboxie-plus.com/sandboxie/sbie1314/

But I can't find any instructions on how to fix it.I am using the latest sandboxie-plus version.What should I edit in sandboxie or window.I don't care about security.Please help me

**Comment by isaak654** [comment]
You can disable the option "Prevent change to network and firewall parameters" from the Sandbox Options -> General Options -> Access Restrictions
