### ISSUE TITLE
"Find on Page" in Chromium Edge is not working sandboxed on Windows 11

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1395]
> Hi @DavidXanatos
> 
> I updated to Windows 11 on one of my machines last night, and there's a problem with the function "Find on Page" in Chromium Edge when running Edge under Sandboxie 0.9.8.d. I then updated the machine to Sandboxie version 1.0.0, but the problem persists in this version too. As I only just updated to Windows 11, I'm afraid I can't tell you which version of Sandboxie or Edge this became a problem. I'm running Edge 96.0.1054.29.
> 
> The problem does not occur in my Windows 10 machines running Edge under Sandboxie.
> 
> To reproduce in Windows 11, go to the 3 dots (settings and more) in Edge and click on Find on Page. Unsandboxed - the wee find bar with the arrows appears as it should, but sandboxed - it's invisible. If you mouse over the general area you'll see a sandboxed yellow border appear, but the contents are invisible rendering it unusable. It's not a problem on FF, Chrome or Brave though - just Edge. I tried changing colour schemes of the browser and using with/without an external monitor, but no change.
> 
> Here are some screenshots of with Sandboxie and without:
<img src="https://www.wilderssecurity.com/data/attachments/105/105047-2b0a2944a933e491fd87a33cb2e782da.jpg">
<img src="https://www.wilderssecurity.com/data/attachments/105/105048-edc6504f49c9e8edabf94d097b5ebb74.jpg">

Source: 
https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-0.442171/page-5#post-3052481
https://www.wilderssecurity.com/threads/windows-11-bugs.441463/#post-3052499

**Comment by isaak654** [comment]
I would appreciate if someone could make available a trace log about this issue for analysis, see: https://git.io/JDIhI

**Comment by DavidXanatos** [comment]
this issue will be resolved using an experimental new feature, to enable it add ```EnableWin32kHooks=y``` to your sandboxie ini and reload the driver or reboot.
