### ISSUE TITLE
Malware and fake dev

### ISSUE THREAD

**Issue by burnsjackie** [sandboxie-plus/Sandboxie#14]
official Sandboxie found here: https://github.com/sandboxie/sandboxie

this one is not official, exe signed with malware signer this one. avoid

**Comment by VitRom** [comment]
hey, shiteater, what about proof?
don't you know such a loud words need some confirmation, arshead?

> 
> 
> official Sandboxie found here: https://github.com/sandboxie/sandboxie
> 
> this one is not official, exe signed with malware signer this one. avoid

**Comment by Justsnoopy30** [comment]
The official sandboxie is no longer being maintained, so now the community is trying to maintain it.

**Comment by VitRom** [comment]
Wow! Such a fresh news! I'm so glad to get know this, thank you very much.

And now let's come back to the second part of your first poop:
What. About. Proof. Qestionmark.

**Comment by VitRom** [comment]
> 
> 
> The official sandboxie is no longer being maintained, so now the community is trying to maintain it.

Good morning, dear "community that is trying to maintain". So nice you're awoken. Finally.
But https://github.com/sandboxie-plus/Sandboxie/network vs https://github.com/sandboxie/sandboxie/network shows clear who are trying and who are talking.

**Comment by Justsnoopy30** [comment]
I was not agreeing with the person who opened the issue if you couldn't tell.
