### ISSUE TITLE
kmdutil ControlService Start Error during Installation

### ISSUE THREAD

**Issue by RiskyRomero** [sandboxie-plus/Sandboxie#140]
Basically an error pops up every time it tries to install "SbieDrv", I've tried reinstalling Sandboxie-Plus multiple times, restarted pc and turned off Anti-Virus. 

The error message is as below:
![image](https://user-images.githubusercontent.com/44841166/93565711-c4463e00-f9c6-11ea-8807-bdd85037e180.png)

Let's say I do click "no" on the error message, and want to uninstall and reinstall the drivers through Sandboxie-Plus itself, a new error arises:
![image](https://user-images.githubusercontent.com/44841166/93565943-2606a800-f9c7-11ea-8b09-e5f3a47e0c6e.png)

Is there a way to fix this?

**Comment by DavidXanatos** [comment]
You need to add an exception in your antivirus for the driver as its not properly signed due to a lack of a proper certificate

**Comment by RiskyRomero** [comment]
> You need to add an exception in your antivirus for the driver as its not properly signed due to a lack of a proper certificate

How do I do it? Do I add the entire installation folder as an exception?

**Comment by DavidXanatos** [comment]
> 
> 
> > You need to add an exception in your antivirus for the driver as its not properly signed due to a lack of a proper certificate
> 
> How do I do it? Do I add the entire installation folder as an exception?

how to do it depands on what antivirus you are using, and yes best it so add an exception for the entire folder

**Comment by RiskyRomero** [comment]
> how to do it depands on what antivirus you are using, and yes best it so add an exception for the entire folder

Pretty weird since I added it as an exception for the entire installation folder, using Windows Security

**Comment by DerEchteKroate** [comment]
Same problem, the antivirus isnt a problem!

**Comment by DavidXanatos** [comment]
we have now a properly signed driver and the plus build got a new installer that issue shouldn't appear anymore
