### ISSUE TITLE
File Recovery window bug/improvements

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#1402]
![image](https://user-images.githubusercontent.com/133706/143295907-3a597a7b-b097-47b7-a8ac-202b5d93fcec.png)

- Is there a particular reason that resizing is allowed but e.g. no maximizing? 😕
- Sandbox size estimations are not tracked real time (In Unix terms/code, it would've been easy enough to do).
- Sandbox size estimations are not updated, even after the "Refresh" button is pressed. Instead, window needs to be re-launched

**Comment by DavidXanatos** [comment]
> Is there a particular reason that resizing is allowed but e.g. no maximizing? 😕
> 
no not really, shell i change it?

> Sandbox size estimations are not tracked real time (In Unix terms/code, it would've been easy enough to do).
> 

i think this is not so easy on windows, imho i would need to set up a ile system watcher on every sub directory in the path and thats a lot of handles

> Sandbox size estimations are not updated, even after the "Refresh" button is pressed. Instead, window needs to be re-launched
>

that sounds like bug teh refresh button should update the size as well, will check that out asak

**Comment by stdedos** [comment]
> > Is there a particular reason that resizing is allowed but e.g. no maximizing? 😕
> 
> no not really, shell i change it?

I guess? 😕
I mean, your software - your rules.
But I don't see the reason why I cannot "make the window bigger quickly", and instead I have to always drag it to make it bigger (and it doesn't remember the size I've set it).

> > Sandbox size estimations are not tracked real time (In Unix terms/code, it would've been easy enough to do).
> 
> i think this is not so easy on windows, imho i would need to set up a ile system watcher on every sub directory in the path and thats a lot of handles

Then forgo it :-D just checking.

**Comment by diieg707** [comment]
> ![image](https://user-images.githubusercontent.com/133706/143295907-3a597a7b-b097-47b7-a8ac-202b5d93fcec.png)
> 
> * Is there a particular reason that resizing is allowed but e.g. no maximizing? 😕
> * Sandbox size estimations are not tracked real time (In Unix terms/code, it would've been easy enough to do).
> * Sandbox size estimations are not updated, even after the "Refresh" button is pressed. Instead, window needs to be re-launched

may i know what file explorer program is that?

**Comment by stdedos** [comment]
TreeSize Professional v7
