### ISSUE TITLE
 Compartmental box, but not standard box, gives "SBIE2205 Service not implemented: Win32Init.x" for some applications

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#1405]
**Describe the bug**
Some applications running in an "Application Compartment" are halted by SBIE2205 Service not implemented: Win32Init, but work fine in standard sandboxie (eg default box)

**To Reproduce**
One of the example is [WinPython](https://winpython.github.io/)
1. Download the minimum package, e.g. https://github.com/winpython/winpython/releases/download/4.6.20211106/Winpython64-3.9.8.0dot.exe, and install or simply unzip the sfx
2. Create a clean Application Compartment and run "WinPython Command Prompt.exe" from the installation/extract directory using Soandboxie's "Run" context menu.
3. "SBIE2205 Service not implemented: Win32Init.x" is thrown and the program exits
4. Repeat "2" in a default box, a cmd window (with the WinPython PATH settings) opens as expected 

**Expected behavior**
This is quite unexpected as a better compatibility is expected for the compartmental mode

**System details and installed software**
 - Windows 10 Pro 21H2 64-bit
 - Sandboxie Plus 1.0.0 64-bit

**Comment by DavidXanatos** [comment]
indeed,  a better compatibility is expected but as the feature is new some issues are to be expected to, I'll check out this asap

**Comment by DavidXanatos** [comment]
strangely enough for me it starts fine

**Comment by superkryodev** [comment]
Strange indeed, it also works for me under 1.0.1. Many thanks
