### ISSUE TITLE
Quick file recovery not working

### ISSUE THREAD

**Issue by Logic530** [sandboxie-plus/Sandboxie#1406]
**Describe the bug**
Save a file to desktop while sandboxed, the recovery window pop up but showing no file in list and recover button has no effect.
Show all files and manually select the file works.

**To Reproduce**
1. Save a file to desktop while sandboxed. (Using chrome or other program)
2. The recovery window pop up.
3. The file list is blank and recover button has no effect.

**Screenshots**
![image](https://user-images.githubusercontent.com/22793670/143516673-8cb3d6a3-3eba-464e-9ba5-7cd27f8317b7.png)

**Expected behavior**
The file saved to desktop show in the list, and is able to be recovered.

**System details and installed software**
 - What is your Windows edition and version?
 - Windows 11 Home 21H2
 - What is your current Sandboxie edition and version?
 - Sandboxie Plus v1.0 64-bit
 - What was your previous Sandboxie version before the update, if any?
 - v0.9.8d
 - Please mention any security software running in the background, even if the real-time protection is disabled.
 - Windows Defender

**Additional context**

**Sandboxie configuration**
If applicable, consider to attach your Sandboxie.ini configuration by copying the content on https://gist.github.com and sharing the resulting link. If you decide to paste the configuration here, make sure to use the backticks around strings, like in this working example:

<details>

<summary>My initial sandboxie.ini settings</summary>

[GlobalSettings]

FileRootPath=D:\Programs\Sandboxie-Plus\%SANDBOX%
SeparateUserFolders=n
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
TemplateReject=AdobeLicensing
TemplateReject=WindowsRasMan
TemplateReject=WindowsLive
TemplateReject=RpcPortBindings
TemplateReject=OfficeLicensing
TemplateReject=OfficeClickToRun
TemplateReject=7zipShellEx
Template=VirtualDesktopManager
EnableObjectFiltering=n

[UserSettings_06280108]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=n
SbieCtrl_HideMessage=2203, *GUIPROXY_00000018; MsgId: 12 - TIM.exe [C0000024]
SbieCtrl_HideMessage=2321, [C0000002 / 11]
SbieCtrl_HideMessage=2203, *GUIPROXY_00000009; MsgId: 12 - TIM.exe [C0000024]
SbieCtrl_RecoverTarget=C:\Users\60485\Desktop
BoxCollapsedView=QQ,WeChat

[DefaultBox]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[WeChat]

Enabled=y
AutoRecover=y
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=-
CopyLimitKb=81920
LeaderProcess=WeChat.exe

[QQ]

Enabled=y
AutoRecover=y
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
LeaderProcess=QQ.exe
BoxNameTitle=-
CopyLimitKb=81920

</details>

**Comment by isaak654** [comment]
Version [1.0.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.2) contains a fix to the recovery window not refreshing count on reload.

**Comment by DavidXanatos** [comment]
please confirm that in build 1.0.2 or later its fine or that you still have an issue, else this issue will be closed
