### ISSUE TITLE
"There is insufficient memory to run setup" while launching installer (CreateProcess returns Err=3)

### ISSUE THREAD

**Issue by memorynoise** [sandboxie-plus/Sandboxie#1408]
**Describe the bug**
I'm using Sandboxie to test a few legacy games in Windows 10  Ver 21H1 64 bit. While trying to install Microsoft 3D Movie Maker, the installer returns the following MessageBox error: "There is insufficient memory to run setup. Try closing any open applications or restarting windows." Upon inspecting the log, it seems that the CreateProcess function returns  Err=3 , which [according to the MSDN](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-), it could be an ERROR_PATH_NOT_FOUND System error. No idea what path it is actually referring to, though.

The installer runs fine when started outside the sandbox even with no compatibility fixes enabled. Both the original exe (16setup.exe) and the spawn process (acmsetup.exe) are 32-bit, despite the name of the former.

A trace log is available:
https://gist.github.com/memorynoise/db0e8e6fd6605cf269b5b785a1de50ee

**Screenshots**
![screen](https://user-images.githubusercontent.com/1699807/143688254-f497e593-5e52-48f3-8a0d-f3cd1594f3c5.png)

**System details and installed software**
Windows 10 ver 21H1 64bit
Sandboxie v0.9.8d

**Sandboxie configuration**

My configuration is available here:
https://gist.github.com/memorynoise/01a7917adccef4a67e7d09dac5541c84

**Comment by DavidXanatos** [comment]
where can I download that instaler to try it out?

**Comment by memorynoise** [comment]
The installer is used in the retail version of Microsoft 3D Movie Maker and most of the "Microsoft Home" Series. Not advocating for piracy or anything, but the disk image can be easily found on archive.org - specifically the executable in [this image](https://archive.org/details/3dmoviemaker) is the same as the OEM Bundle Version I own.

**Comment by DavidXanatos** [comment]
Well whats wrong with piracy? Also IMHO there is no piracy on archive.org, if its there and not taken down its by inaction permitted by the rights holder.

**Comment by memorynoise** [comment]
I should probably submit a new issue, but after spawning the acmsetup.exe process the installer now shows a different error:
![Screenshot (3)](https://user-images.githubusercontent.com/1699807/145878238-d5d9ad1e-fd75-4072-bf3b-46d29ee490dc.png). 

Tested on both v1.0.3 / 5.55.3 and v1.0.2 / 5.55.2.

No idea about what's going on, It looks like some kind of environment start folder error?

Here's the trace log: https://gist.github.com/memorynoise/eda35bb72d0c1afc828f4f8a6352dc85

As I said earlier, it works fine when I run outside of sandboxie.

**Comment by isaak654** [comment]
> I should probably submit a new issue, but after spawning the acmsetup.exe process the installer now shows a different error:

New error, new issue. I'm going to close this one.
