### ISSUE TITLE
sadly the problem with mounted directories is not fixed

### ISSUE THREAD

**Issue by ruixingchen** [sandboxie-plus/Sandboxie#1409]
##**version 1.0.0**
the problem in #1302 is not fixed
here is how to show the bug
1, mount a disk to C:\Disk1
2, create a blank txt file in C:\Disk1
3, set C:\Disk1 to "open to All"
4, open that txt file in default box
5, write something and save
**6, now notepad will ask you to safe to other place**

**Comment by DavidXanatos** [comment]
I tested that procedure , with the only difference i used c:\test\Disk1 and this worked for me fine, do i need to test on C directly? Or does it fail for you on the sub path as well?

**Comment by ruixingchen** [comment]
will check it intensively tonight

**Comment by DavidXanatos** [comment]
and how does it look?

**Comment by DavidXanatos** [comment]
since it works for me and thre is no more fead back on this sisue I'll close it
