### ISSUE TITLE
Occasional BlueScreen when running Kodi Sandboxed

### ISSUE THREAD

**Issue by tfjield** [sandboxie-plus/Sandboxie#141]
I occasionally get bluescreens on Windows 10 and I finally looked at the debug logs.  Looks like SbieDrv.sys is involved.

I was running 5.33-3 and upgraded afterwards to 5.43.5.  I'm not sure if the bluescreens will continue, but wanted to share some info now just in case.

Here is the summary from dumpchk:

UNEXPECTED_KERNEL_MODE_TRAP (7f)
This means a trap occurred in kernel mode, and it's a trap of a kind
that the kernel isn't allowed to have/catch (bound trap) or that
is always instant death (double fault).  The first number in the
bugcheck params is the number of the trap (8 = double fault, etc)
Consult an Intel x86 family manual to learn more about what these
traps are. Here is a *portion* of those codes:
If kv shows a taskGate
        use .tss on the part before the colon, then kv.
Else if kv shows a trapframe
        use .trap on that value
Else
        .trap on the appropriate frame will show where the trap was taken
        (on x86, this will be the ebp that goes with the procedure KiTrap)
Endif
kb will then show the corrected stack.
Arguments:
Arg1: 0000000000000008, EXCEPTION_DOUBLE_FAULT
Arg2: ffffa081d64efe70
Arg3: ffff898671354f60
Arg4: fffff80279eeba95

Debugging Details:
------------------
BUGCHECK_CODE:  7f
BUGCHECK_P1: 8
BUGCHECK_P2: ffffa081d64efe70
BUGCHECK_P3: ffff898671354f60
BUGCHECK_P4: fffff80279eeba95
PROCESS_NAME:  WUDFHost.exe
SYMBOL_NAME:  SbieDrv+1ef99
MODULE_NAME: SbieDrv
IMAGE_NAME:  SbieDrv.sys
FAILURE_BUCKET_ID:  0x7f_8_SbieDrv!unknown_function
FAILURE_ID_HASH:  {ff38f1c7-a3c1-60bf-ef16-e8534b53253a}
Followup:     MachineOwner

Let me know if I can provide any other info that would help!

**Comment by DavidXanatos** [comment]
Is the issue still present? If it is what would help would be a kernel crash dump from the current build

**Comment by tfjield** [comment]
Hey David. No, I haven't had a blue screen since updating.  I'm running 5.43.7 now, and it appears to be quite stable.  I have 4 monitors, and one is running Kodi sandboxed pretty much all the time.

Thanks for checking in, but I think this problem has been solved.

**Comment by DavidXanatos** [comment]
great than I'll close it :)
