### ISSUE TITLE
windows 10 edge 96.0.1054.34 can not lauch

### ISSUE THREAD

**Issue by carlsue** [sandboxie-plus/Sandboxie#1411]
**Describe the bug**
windows 10 19044.1387 edge 96.0.1054.34 can not lauch
**To Reproduce**
1. Go to 'default sandboxie'
2. right Click on 'default sandboxie'
3. Scroll down to 'open default browser'

**Screenshots**
![image](https://user-images.githubusercontent.com/17507066/144159792-3dc24724-4333-471a-a974-409b27284067.png)

**Expected behavior**

**System details and installed software**
 - What is your Windows edition and version? (e.g. Windows 10 Pro 20H2 64-bit)
 -  windows 10 pro 21h2 
 - What is your current Sandboxie edition and version? (e.g. Sandboxie Plus 0.9.6 64-bit)
 -    Sandboxie Plus 0.9.8d 64-bit

**Sandboxie configuration**
If applicable, consider to attach your Sandboxie.ini configuration by copying the content on https://gist.github.com and sharing the resulting link. If you decide to paste the configuration here, make sure to use the backticks around strings, like in this working example:

[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=n
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=VirtualDesktopManager
Template=WindowsRasMan
Template=WindowsLive
Template=RpcPortBindings
Template=OfficeLicensing
Template=OfficeClickToRun
Template=7zipShellEx

[UserSettings_0CC60222]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
SbieCtrl_RecoverTarget=
SbieCtrl_HideMessage=2203, *GUIPROXY_00000001; MsgId: 12 - DingTalk.exe [C0000024]

[default]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
CopyLimitKb=4096000

**Comment by carlsue** [comment]
chrome v96 is the same

**Comment by mysteriously** [comment]
Ye, sometimes chrome does not start. However it is enough to terminate programs and run it again. 5.53.3 and chrome  96.0.4664.45

**Comment by DavidXanatos** [comment]
please try the newest pre release build 1.0.3 and let me know if there edge works for you

**Comment by mysteriously** [comment]
SBIE: 5.53.3, Chrome  96.0.4664.110
Actually chrome process starts, but in like 50% of cases there is no GUI.
Also sometimes GUI closes on chrome exit, but processes stays running in sandbox until manually terminated.

**Comment by DavidXanatos** [comment]
please try build 1.0.3 or later

**Comment by mysteriously** [comment]
Ok I switched from SBIE classic to + as it is more matrure now . Using v1.0.3 I think Chrome alwats starts properly. However it still does not terminate properly leaving one chrome.exe process opened forever. Having Chrome as leader process does not help. Also chrome.exe is the only process allowed in my main sandobox and the only process which has access to the Internet.
