### ISSUE TITLE
Command to Run Program Launched From Within Sandbox Outside of Sandbox?

### ISSUE THREAD

**Issue by SolidSouless** [sandboxie-plus/Sandboxie#1412]
I want to launch a game from the sandboxed Steam client, but want that launched Steam game to run outside the sandbox. I found this site with a list of commands that are supposed to exempt a program from running in the sandbox, but I could not get it to do so.

Steam needs to be running in the sandbox, but I want the game to run outside. Is this even possible?

https://sandboxie-website-archive.github.io/www.sandboxie.com/StartCommandLine.html
_**Disable Forced Programs**

The following command runs a program outside the sandox, even if the program is forced. It is similar to using the Run Outside Sandbox option from the sandbox selection window of the Run Sandboxed command.

  "C:\Program Files\Sandboxie\Start.exe"  /dfp            c:\path\to\program.exe
  "C:\Program Files\Sandboxie\Start.exe"  /disable_force  c:\path\to\program.exe_

**Comment by exander77** [comment]
> no its not possible, these commands dont work from within a sandbox only from outside, for security reasons

Can this be implemented? I made a feature request: https://github.com/sandboxie-plus/Sandboxie/issues/1500
