### ISSUE TITLE
I'd like to take over Turkish Translations

### ISSUE THREAD

**Issue by nulledone** [sandboxie-plus/Sandboxie#1419]
I've recently seen that it is inactive therefore I'd like to help. I will be re-doing it completely.

**Comment by isaak654** [comment]
In this case, I would suggest the following translation hints: https://github.com/sandboxie-plus/Sandboxie/discussions/1123#discussioncomment-1203489

**Comment by DavidXanatos** [comment]
Sure, go ahead and make a pull request, as simple as that.
Any help will be greatly appreciated :)
