### ISSUE TITLE
SB+ 0.96, 0.98d is disguising host Windows version as detected by some installers

### ISSUE THREAD

**Issue by alasalto** [sandboxie-plus/Sandboxie#1426]
> Freefilesync software (https://freefilesync.org/) installer shows up the same issue with SB+. It´s unable to install as of version 11.14 when using SB+ v0.96 on a Win10Pro 21H1 system. The FreeFileSync Installer refuses to install in a fresh sandbox. The error message points out to a min Windows version needed: Windows 7 or later. Adding 'OverrideOsBuild=7601' parameter didn't work neither.

Testing FFF ver 11.15 still happening. The program refuses to install showing up an error dialog: "FreefileSync 11.15 requires Windows 7  or later to run"

_Originally posted by @alasalto in https://github.com/sandboxie-plus/Sandboxie/issues/605#issuecomment-991434135_

**Comment by isaak654** [comment]
> Adding 'OverrideOsBuild=7601' parameter didn't work neither.

That parameter never worked since the beginning. Just for the record, it was added in `Sandboxie/core/dll/userenv.c`:
https://github.com/sandboxie-plus/Sandboxie/commit/48488dfec15c460b140a0c8dfefb82e0a9436e6d?diff=unified#diff-3434716960b35ef0cac23943b4c76a5a8f1fc5f60e76e5e9b3e860120ad82d4d

I think it's just a matter to decide if fixing it or reverting it.

**Comment by isaak654** [comment]
> Adding 'OverrideOsBuild=7601' parameter didn't work neither.

That parameter never worked since the beginning. Just for the record, it was added in `Sandboxie/core/dll/userenv.c`:
https://github.com/sandboxie-plus/Sandboxie/commit/48488dfec15c460b140a0c8dfefb82e0a9436e6d?diff=unified#diff-3434716960b35ef0cac23943b4c76a5a8f1fc5f60e76e5e9b3e860120ad82d4d

I think it's just a matter to decide if fixing the not working code or undo it for good.

About the rest of the issue, please test Plus 1.0.2. I can't reproduce it with this version.

**Comment by alasalto** [comment]
Testing again SB+ 1.03 w/ OverrideOsBuild=7601 parameter.  The problem still persists. 
SB+ notificaion dialog shows the following error:
FreeFileSync_11.15_Windows_Setup.exe (7936): SBIE2224 Sandboxed program has crashed: FreeFileSync_11.15_Windows_Setup.exe [FreeFileSyncToInstallH]
On installer side, it shows: Runtime error and installation ends abruptly.

**Comment by isaak654** [comment]
> On installer side, it shows: Runtime error and installation ends abruptly.

Please report the exact runtime error, thank you.

**Comment by alasalto** [comment]
> > On installer side, it shows: Runtime error and installation ends abruptly.
> 
> Please report the exact runtime error, thank you. Do you use a third-party security software besides Sandboxie?

Sorry Sir, I have just forgotten it to state properly:

Tested on a Standard isolation sandbox
---------------------------
FreeFileSync_11.15_Windows_Setup.exe - Application Error
---------------------------
The instruction at 0x0000000000000001 referenced memory at 0x0000000000000001. The memory could not be read.
Click OK to terminate the program
---------------------------
OK   
---------------------------

And installer reported this one:
---------------------------
Error
---------------------------
Runtime error 216 at 00000001
---------------------------
OK   
---------------------------

**Comment by isaak654** [comment]
It looks like "Runtime error 216" could indicate the presence of one or more viruses, see [Error Message: Runtime Error 216](https://support.microsoft.com/en-us/topic/error-message-runtime-error-216-1d0db575-c9bf-94e9-c432-2315c5bab9d5)

**Comment by alasalto** [comment]
Thank you for pointing it out. AV does not detect unusual activities as regards of a virus nor was detected. Therefore, this error does not occur when running installer from outside the sandbox. ¿?

**Comment by diversenok** [comment]
> It looks like "Runtime error 216" could indicate the presence of one or more viruses

Runtime error 216 has nothing to do with viruses. It means that a program that is written in Delphi got an access violation before exception handling was fully initialized. Nothing more, nothing less.

**Comment by isaak654** [comment]
> > It looks like "Runtime error 216" could indicate the presence of one or more viruses
> 
> Runtime error 216 has nothing to do with viruses. It means that a program that is written in Delphi got an access violation before exception handling was fully initialized. Nothing more, nothing less.

So even MSFT provided an oversimplified explanation on that error code, good to know...
I think it's time to reopen this issue, I've just tested this behavior and I can confirm it.

**Comment by DavidXanatos** [comment]
without OverrideOsBuild=7601 free fiel sync seams to me to install just fine, the issue is that if we tell the program we are win 7 it will screw somethign up so imho everythign works on our side as intended

**Comment by alasalto** [comment]
> without OverrideOsBuild=7601 free fiel sync seams to me to install just fine, the issue is that if we tell the program we are win 7 it will screw somethign up so imho everythign works on our side as intended

Thank you for your response. I really appreciate your work. Just in case this long standing issue deserves your attention again. The behavior or both programs is what it seems to me that SB+ is disguising host Windows ver. The program to be installed is not functioning as expected since as soon as I try to install the software it shows an error dialog stating that at least Windwos 7 ver is required. Tested again thoroughly on Windows 10 Pro 21H1 and SB+ 096, 0.98d, 1.03 &1.04 unfortunately the error persists in all cases. 

---------------------------
Setup
---------------------------
﻿F﻿r﻿e﻿e﻿F﻿i﻿l﻿e﻿S﻿y﻿n﻿c 11.15 requires Windows 7 or later to run!
--------------
OK   
-------------
