### ISSUE TITLE
Is it possible to let program that run inside sandboxie has capacity to monitor keyboard/mouse input

### ISSUE THREAD

**Issue by JiaPai12138** [sandboxie-plus/Sandboxie#1428]
**Is your feature request related to a problem? Please describe.**
No i dont think it is a problem

**Describe the solution you'd like**
With some settings modified, I will be able to use GetAsyncKeyState or GetKeyState for my programs run inside sandboxie to successfully monitor such input.

**Describe alternatives you've considered**
Nope

**Additional context**
Nope

**Comment by JiaPai12138** [comment]
For example, it can be enabled in settings or in ini file, with an obvious warning popup, and when sandboxie restarts, it will be automatically disabled

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/146275988-95c479fb-2cdc-476a-94d7-5a5668cc384c.png)

disable this option to get what you want

**Comment by JiaPai12138** [comment]
> ![grafik](https://user-images.githubusercontent.com/3890945/146275988-95c479fb-2cdc-476a-94d7-5a5668cc384c.png)
> 
> disable this option to get what you want

![image](https://user-images.githubusercontent.com/72233260/146954167-fe8587db-9641-4070-963e-0d86d930cdad.png)
Sorry i dont see those options. Are these from release 1.x ?

**Comment by DavidXanatos** [comment]
to be honest i don't remember when i introduced them, try looking on the isolation tab instead, i may have moved them.
if you dont find them eider use a newer version or set the option manually in the ini
"NoAddProcessToJob=y"
the option is availabel since a logn time but only recently exposed in the UI

**Comment by NJT145** [comment]
Is it possible to give access for only one program? I want to let access for my selected programs and block access for others.
