### ISSUE TITLE
Block internet in internet acces not save

### ISSUE THREAD

**Issue by jtssi** [sandboxie-plus/Sandboxie#143]
Hello, the checked box is not saved, so the internet is never blocked.

**Comment by neil-benn253** [comment]
Same issue. In Plus settings, blocking web does not stick, not even temporarily. Creating a new box in Plus is open by default, cannot block it. Old boxes can still be blocked-unblocked via legacy Sbie, however any NEW box created in Plus GUI does not show up in legacy list, not in tray list or GUI, so no way to block via legacy Sbie. Issue is occuring in v040 & 041, on Windows 10-1909, 2004 & Win-8.1 - cheers 👍

**Comment by neil-benn253** [comment]
And just to clarify, I am running only one version of Sandboxie on any system, ie: Plus with it's included SbieCtrl.exe. Older versions were always uninstalled first, just leaving the old Sandboxie.ini in place.

**Comment by DavidXanatos** [comment]
the issue will be fixed in the next build
