### ISSUE TITLE
Cannot run browsers sandboxed

### ISSUE THREAD

**Issue by crlsgms** [sandboxie-plus/Sandboxie#1432]
**Describe the problem**
Cannot launch any web browser sandboxied

**To Reproduce**
"C:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "C:\Program Files\Mozilla Firefox\firefox.exe" as a shortcut gives an error "could not be located in the dynamic link library ...\firefox.exe"

changing this shortcut to only \start.exe" "firefox.exe" without the specific box gives the same result

Changing the shortcut to ask for the default browser (on my env is chrome) it opens an instance with white background but closes in some seconds

"C:\Program Files\Sandboxie\Start.exe" /box:DefaultBox default_browser

(as suggested on issue - https://github.com/sandboxie-plus/Sandboxie/issues/525)

**Screenshots**
![image](https://user-images.githubusercontent.com/4990453/145866071-512b3f19-3373-4e9d-bfe4-3eb5eb5c0b33.png)

**Expected behavior**
Open any browser sandboxed

**System details and installed software**
 - Windows 10 Pro 20H2 64-bit)
 - Sandboxie 5.33.1

**Sandboxie configuration**
not much configures, fresh install just to use a save browser

**Comment by isaak654** [comment]
> Sandboxie 5.33.1

Are you sure you haven't mistyped the version? That was released around 2 years ago:
https://community.sophos.com/sandboxie/f/forum/117307/sandboxie-5-33-1-is-available-for-download

**Comment by isaak654** [comment]
I was able to receive the same error on Plus 1.0.3, but only in one specific sandbox and triggered with a simple `ForceProcess=firefox.exe` on a default config:

> "The procedure entry point ?BeginProcessRuntimeInit@detail@mscom@mozilla@@YAAEA_NXZ could not be located in the dynamic link library C:\Program Files\Mozilla Firefox\firefox.exe.

The error is gone quickly for me by deleting the content of the sandbox.
