### ISSUE TITLE
Saving to Network Share Based Folders Results in Missing File in UI

### ISSUE THREAD

**Issue by TGKx** [sandboxie-plus/Sandboxie#1435]
**Describe the problem**
When utilizing a sandboxed Iridium (a chromium based web browser), I save a file to a network share, sandboxie-plus v0.9.8d triggers quick recovery but the file does not appear in the dialog box that pops up.  Instead it is an empty screen with no files or folders listed.  When attempting to manually recover via the UI, the path and file do not show up in the dialog box. When I manually browse to the Sandbox folder (outside of the sandboxie) and browse through E:\Sandbox\share\192.168.1.1\folder the file is present and can be opened or copied.  The file might actually be going into some sort of limbo with the UI.  This is likely a regression as the early versions of sandboxie-plus worked properly.

**To Reproduce**
1. Configure Sandboxie-plus for quick recovery and specify a network share location via UNC \\IP\folder.
2. Open a browser and save a file to the location
3. Observe that Sandboxie-plus pops up the quick recovery interface but no files or folders are listed.
4. Observe that clicking on the sandbox via the sandboxie  UI and selecting recover, the files and folders are also not listed.

**Expected behavior**
When I save a file to a network location via a sandboxed process, Sandboxie-Plus should behave the same way as a folder on a local drive.

**System details and installed software**
- Windows 10 Enterprise 64 bit, version 10.0.19042 Build 19042
- Sandboxie Plus v0.9.8d 64 bit
- This behavior has been present for at least the past three releases, perhaps more.
- The original few releases of sandboxie-plus did not have this problem.
- No additional security software is running on the system, besides Windows Defender with default configuration.

**Sandboxie configuration**
If applicable, consider to attach your Sandboxie.ini configuration by copying the content on https://gist.github.com and sharing the resulting link. If you decide to paste the configuration here, make sure to use the backticks around strings, like in this working example:

<details>

<summary>My initial sandboxie.ini settings</summary>

[GlobalSettings]

Template=VirtualDesktopManager
Template=RpcPortBindings
Template=OfficeClickToRun
Template=nVidia_Stereoscopic3D
Template=OfficeLicensing
Template=WindowsRasMan
Template=SystemAudioStream
Template=7zipShellEx
FileRootPath=E:\Sandbox\%USER%\%SANDBOX%
ExperimentalProtection64Bit=y
ActivationPrompt=n
KnownConflicts=StrokeIt
ForceDisableSeconds=60
TemplateReject=WindowsLive
TemplateReject=StrokeIt
TemplateReject=RTSS
TemplateReject=Logitech_G15_Keyboard
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
StartRunAlertDenied=y
NotifyStartRunAccessDenied=y
NetworkEnableWFP=n

[Iridium]

Enabled=y
AutoRecover=y
AutoRecover=n
BlockNetworkFiles=n
BlockNetworkFiles=y
RecoverFolder=\\192.168.1.1\downloads\username\
RecoverFolder=%{374DE290-123F-4565-9164-REDACTED}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
ClosePrintSpooler=y
OpenSmartCard=n
BoxNameTitle=n
BlockNetParam=y
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
CopyLimitKb=-1
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,msedge.exe,Maxthon.exe,iron.exe,iridium.exe,dragon.exe,chrome.exe,browser.exe,brave.exe
ForceFolder=C:\Program Files\Iridium
OpenFilePath=C:\Users\username\AppData\Local\Iridium\User Data\Default
OpenFilePath=C:\Program Files\Iridium\Dictionaries

</details>

**Comment by isaak654** [comment]
I noticed you have some duplicated settings on the same sandbox, you need to decide between one of these:

```
BlockNetworkFiles=n
BlockNetworkFiles=y
```

```
AutoRecover=y
AutoRecover=n
```

While these are obsolete and can be removed:
```
ExperimentalProtection64Bit=y
ActivationPrompt=n
BorderColor=#00FFFF,ttl
```
