### ISSUE TITLE
Working directory not being set correctly for some portable applications

### ISSUE THREAD

**Issue by mitomenai** [sandboxie-plus/Sandboxie#1436]
**Describe the problem**
In some instances, the working directory is not being set correctly in Sandboxie Plus.

**To Reproduce**
1. Download Electrum Portable from https://electrum.org/#download
2. Initialize a wallet
3. Review Sandbox directory
4. Note that electrum_data is being created inside SysWOW64: DefaultBox\drive\C\Windows\SysWOW64\electrum_data

**Expected behavior**
As with previous versions of Sandboxie, the directory is correctly created inside the working directory, next to the executable. In my case, it should be on the Desktop: DefaultBox\user\current\Desktop\electrum_data

**System details and installed software**
 - Windows 10 Enterprise 20H2 64-bit
 - Sandboxie-Plus-x64-v1.0.3

**Additional context**
Some applications like Telegram seem to work correctly. In this case, it's just Electrum that seems to be misbehaving.

**Comment by DavidXanatos** [comment]
could you pelase tell me with which exact version of sandboxie this error got introduced#?

**Comment by mitomenai** [comment]
I believe it was introduced in Sandboxie Plus. I tried both Sandboxie Plus v0.9.8.4 and Sandboxie Classic v5.53.3. It seems to work correctly in the Classic build, but not in the Plus build.

**Comment by dhjw** [comment]
This has caused a number of programs I try to run in Sandboxie-Plus to crash and fail to load. A fix for me has been to create a run.bat file that changes to the folder and runs the .exe, e.g.:

```
cd "C:\Path to\Program"
.\program.exe
```
