### ISSUE TITLE
Can not control the camera in Minecraft

### ISSUE THREAD

**Issue by sduoduo233** [sandboxie-plus/Sandboxie#1439]
**Describe the problem**
camera keeps spinning & unable to rotate vertically

**To Reproduce**
1. launch Minecraft 1.8.9 in sandboxie
2. join a world

**Screenshots**

[recording](https://streamable.com/ifpf1s)

**Expected behavior**
able to control the camera

**System details and installed software**
 - What is your Windows edition and version? Windows 10 21H1
 - What is your current Sandboxie edition and version? sandboxie-plus 0.9.8 (64 bits)
 - What was your previous Sandboxie version before the update, if any? none
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled. windows defender

**If you had a compatibility issue or a crash**
 - Please add a download link to the program not working properly in Sandboxie.
 - Please consider to take a log and make it available for analysis: https://git.io/Jwj2y
 - Please attach the actual memory dump and NOT the simple output, which often turns out to be insufficient for a proper analysis.

**Additional context**
it spins slower when the game window is at the edge of my screen

**Sandboxie configuration**
If applicable, consider to attach your Sandboxie.ini configuration by copying the content on https://gist.github.com and sharing the resulting link. If you decide to paste the configuration here, make sure to use the backticks around strings, like in this working example:

<details>

<summary>My initial sandboxie.ini settings</summary>

```

#
# Sandboxie-Plus configuration file
#

[GlobalSettings]

[UserSettings_11D00291]
SbieCtrl_AutoStartAgent=SandMan.exe

[DefaultBox]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9



```

</details>

**Comment by sduoduo233** [comment]
It may be because the game cannot set the mouse position correctly

**Comment by worx7kbj** [comment]
Possibly related to https://github.com/sandboxie-plus/Sandboxie/issues/895

**Comment by worx7kbj** [comment]
I observed that the yellow square of sandboxie sometimes doesn't match the real size of the game window when this issue occurs

**Comment by worx7kbj** [comment]
Maybe the mouse wasn't captured correctly?

**Comment by worx7kbj** [comment]
> I observed that the yellow square of sandboxie sometimes doesn't match the real size of the game window when this issue occurs

Sometimes the mouse pointer appears in weird positions.

**Comment by worx7kbj** [comment]
> I observed that the yellow square of sandboxie sometimes doesn't match the real size of the game window when this issue occurs

It is pretty random on my machine. Resizing the window or full-screen might cause it

**Comment by sduoduo233** [comment]
> > I observed that the yellow square of sandboxie sometimes doesn't match the real size of the game window when this issue occurs
> 
> It is pretty random on my machine. Resizing the window or full-screen might cause it

I think Minecraft will set the mouse pointer position at the center of the window when playing, but Minecraft running in sandbox can't set the mouse pointer correctly (the pointer will be out of game window when the window in small)

**Comment by worx7kbj** [comment]
> > > I observed that the yellow square of sandboxie sometimes doesn't match the real size of the game window when this issue occurs
> > 
> > 
> > It is pretty random on my machine. Resizing the window or full-screen might cause it
> 
> I think Minecraft will set the mouse pointer position at the center of the window when playing, but Minecraft running in sandbox can't set the mouse pointer correctly (the pointer will be out of game window when the window in small)

I also think so

**Comment by isaak654** [comment]
Do you have a custom DPI scaling set on W10?

**Comment by sduoduo233** [comment]
> Do you have a custom DPI scaling set on W10?

it now works with the latest version of sandboxie
