### ISSUE TITLE
Thread leak causing computer to slow to a crawl

### ISSUE THREAD

**Issue by Thordin** [sandboxie-plus/Sandboxie#144]
Not sure how to debug this but there is a thread leak in SbieSvc.exe that causes your computer to slow down to a crawl until the process is ended a long time later. This is with no sandboxed process running.

After running some applications sandboxed, I noticed this process using 3gb commit, only thing I can see is that it has a bunch of thread handles.

I run taskkill on the pid and it only closes >20 minutes later. Trying to run taskkill on the process repeatedly, it will just say "There is no running instance of the task.". Closing the sandboxie GUI does nothing.

**Comment by DavidXanatos** [comment]
Can you try to find out in which version this issue got introduced?
Or was it present already in the original sophos release?

**Comment by diversenok** [comment]
It is a very old bug. Every time Sandboxie shows an error message, SbieSvc leaks a thread handle.

**Comment by DavidXanatos** [comment]
> 
> 
> It is a very old bug. Every time Sandboxie shows an error message, SbieSvc leaks a thread handle.

Ok that's sounds easy enough to replicate, thanks, I'll debug that on the weekend.

**Comment by mysteriously** [comment]
SbieCtrl_HideMessage=*
may be potential temporary workaround

**Comment by diversenok** [comment]
Here is a small demo that triggers a handle leak: https://gist.github.com/diversenok/bfb629798dc1cdbdd51db6dc945c0c16

**Comment by DavidXanatos** [comment]
aaaa... great thanks that will help :D

**Comment by DavidXanatos** [comment]
The bug is bigger than expected, most communication operations between the service and the driver have leaked a thread handle, really not good!
The issue will be fixed in the next build.

**Comment by SanderBouwhuis** [comment]
Not specifically only about Sandboxie, but more in general:
Why do they need to close the handle? Doesn't that automatically happen when the thread ends of its own accord? If a messagebox is shown in a new thread, then I assume the thread only lives that long and will exit when the messagebox closes.

**Comment by diversenok** [comment]
@SanderBouwhuis

It is a design choice.

By contrast with `MessageBox`, `CreateThread` does not just create a thread; it also opens a handle to it. You can use this handle to interact with the thread, and it acts as a reference, preventing the system from deallocating associated resources. Windows does not invalidate the handle when the thread exits because this handle can still be useful. You can wait on it to synchronize execution; you can use it to query the thread's exit code, etc. Therefore, it is up to the caller to close the handle since Windows cannot determine whether the developer forgot to do so or wants to use it later.

**Comment by Shadowized** [comment]
wow, I remember reporting this bug on the old sandboxie forums _years_ ago. great to see it being looked into, only thing I can do to mitigate it is closing sandboxie gui and restarting the background service to free all handles else it continues to grow with each message whether suppressed or not.

**Comment by DavidXanatos** [comment]
fixed in the just released 0.4.2
