### ISSUE TITLE
SBIE2205 Stremio doesn't work properly: Service not implemented (CreateDesktop)

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#1442]
**Describe the problem**
Installing Stremio in a sandbox works as intended.
Running it does not.

**To Reproduce**
1. Download Stremio 4.4 from their website
2. Install it into a brand new sandbox. I named mine "Stremio"
3. See the picture below.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12563436/146643130-13d41369-ce23-4bb2-a825-2699434064db.png)
![grafik](https://user-images.githubusercontent.com/12563436/146643173-72db6540-cdd9-48fb-866e-9754b838a28e.png)

**Expected behavior**
It should start and run, just as it does after a "real" install.

**System details and installed software**
Windows 10 21h2
Latest Sandboxie-Plus

**If you had a compatibility issue or a crash**
[ - Please add a download link to the program not working properly in Sandboxie.](https://www.stremio.com/downloads)

**Additional context**
Should be easy to reproduce

**Sandboxie configuration**
A brand new created (hardened) sandbox.

**Comment by DavidXanatos** [comment]
try enabling this option:
![grafik](https://user-images.githubusercontent.com/3890945/146644059-a9f26358-62e2-4c3a-8d65-d14d427f79bf.png)

**Comment by Dyras** [comment]
@DavidXanatos Seems to work just fine with that enabled :)
Could that be made the default for stremio.exe and stremio-runtime.exe?

**Comment by DavidXanatos** [comment]
well what is stremio how pupular is it?

**Comment by isaak654** [comment]
> @DavidXanatos Seems to work just fine with that enabled :) Could that be made the default for stremio.exe and stremio-runtime.exe?

It could be easily done with a new template that scans a specific program key in order to apply these rules automatically: 
```
UseSbieWndStation=stremio.exe,y
UseSbieWndStation=stremio-runtime.exe,y
```

I think it would be recommended to provide a detailed installation log taken with third-party uninstallation software like Revo Uninstaller.

**Comment by Dyras** [comment]
@DavidXanatos 
It's a program/app for streaming various content. I mostly use it on my computer connected to the TV to watch TV shows. It has Netflix support, Torrent support, etc.

I'd say it's pretty popular. It's basically a newer KODI.

**Comment by DavidXanatos** [comment]
I'm thinking should we just enable this for all apps its not the first one that this change helps and i dont think it woudl break any others

**Comment by isaak654** [comment]
It looks like you canceled the decision to enable `UseSbieWndStation` by default: https://github.com/sandboxie-plus/Sandboxie/commit/d69fb39415a9afb38b7f988ee0c2bfec438d2f21
May I ask the reason?

**Comment by DavidXanatos** [comment]
I want to make 1.0.5 a final i.e. not pre release finally, so i thought i will not change anything untested

**Comment by Dyras** [comment]
1.0.6 has been released, so I'm gonna close this. Will re-open if there are any issues.

Thanks for the quick solution like always David!

**Comment by Dyras** [comment]
This issue appears to be back in v1.1.3
![grafik](https://user-images.githubusercontent.com/12563436/176428526-5bdb3fdb-9a0d-4e36-8172-db079a62f543.png)

**Comment by Dyras** [comment]
Yup that indeed helped, I thought that was added automagically, oopsie!
