### ISSUE TITLE
SandMan.exe will no response after delete Uninstall registry key

### ISSUE THREAD

**Issue by mystique** [sandboxie-plus/Sandboxie#1444]
**Describe the problem**
After deleting the Uninstall key in the registry, running SandMan.exe will cause no response and can only be forced to end task.

**To Reproduce**

1. Exit SandMan.exe
2. Delete following registry key

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall

3. Start SandMan.exe

**Screenshots**
<img width="671" alt="Screenshot 2021-12-19 204033" src="https://user-images.githubusercontent.com/561788/146675370-a09701d3-94d5-4279-b0b7-93a051f098b7.png">

**System details and installed software**
 - Windows 11 Enterprise 21H2 64-bit
 - Sandboxie Plus 0.9.8d

**Comment by isaak654** [comment]
I wasn't able to reproduce it with the following combination:

Windows 10 Pro 21H1 64-bit
Sandboxie Plus 1.0.3 (clean install)
McAfee Total Protection trial

**Comment by mystique** [comment]
I still have this problem when I update to the pre-release version. If I create these two empty registry keys, sandman.exe will start without any problems.

**Comment by DavidXanatos** [comment]
Well sandman is not suposed to read those keys, I think this must be some intrusive 3rd parts software that is causing troubles here
