### ISSUE TITLE
Forced Programs Section List Glitch

### ISSUE THREAD

**Issue by SiNONiMiTY** [sandboxie-plus/Sandboxie#1447]
Repeatedly checking and unchecking the "Show Templates" box will populate the list with repeated entries

From
![image](https://user-images.githubusercontent.com/9588282/146919135-b9787f59-6cff-48d0-aee2-861539dc0f27.png)

To
![image](https://user-images.githubusercontent.com/9588282/146919167-648b0961-e7b5-47b1-a214-b8be9ac8e717.png)

**Comment by SiNONiMiTY** [comment]
Tested on the latest version, v1.0.4, W10 21H2 x64

**Comment by isaak654** [comment]
I can't reproduce it, could you post your 'MozillaFirefox' configuration lines?

**Comment by SiNONiMiTY** [comment]
````

Enabled=y
ConfigLevel=9
AutoRecover=n
BorderColor=#00ffff,off,6
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=Firefox_Profile_DirectAccess
Template=Firefox_Force
DropAdminRights=y
BoxNameTitle=-
CopyLimitKb=-1
OpenSmartCard=n
NotifyInternetAccessDenied=n
ProcessGroup=<InternetAccess>,firefox.exe,
AllowNetworkAccess=!<InternetAccess>,n
AllowNetworkAccess=<BlockNetAccess>,n
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
LeaderProcess=firefox.exe
OpenPipePath=firefox.exe,D:\Downloads
ShowForRunIn=n
NeverDelete=y

**Comment by isaak654** [comment]
Issue confirmed on both 1.0.3 and 1.0.4.

Steps to reproduce it:
1) Add `Template=Firefox_Force` on a default box
2) Go to the Sandbox Options -> Forced Programs -> click the "Show Templates" checkbox multiple times -> the result is equal to the second pic in the first post.
