### ISSUE TITLE
Line PC version can't working

### ISSUE THREAD

**Issue by games1tw** [sandboxie-plus/Sandboxie#145]
OS:Windows 10 2004
Version:Sandboxie 5.43.5 64bit
Issue:Line PC ver 6.3.2.2338 can't working

![image](https://user-images.githubusercontent.com/20733901/94770951-9a3e4400-03e8-11eb-9253-fad1b6cf43b4.png)

**Comment by DavidXanatos** [comment]
please provide more explenation

**Comment by games1tw** [comment]
> please provide more explenation

https://drive.google.com/file/d/1QfUkVbLN1HRRBh0XxU1YCLlp8z4EnWNR/view?usp=sharing

**Comment by games1tw** [comment]
Same as
OS:Windows 10 20H2
Version:Sandboxie 5.44.0 64bit
Issue:Line PC ver 6.3.2.2338 can't working

**Comment by DavidXanatos** [comment]
please see https://github.com/sandboxie-plus/Sandboxie/issues/228 the issue will be solved in the next build
