### ISSUE TITLE
[0.9.8d] SBIE2205 Service not implemented: Win32Init.5, Win32Init.4

### ISSUE THREAD

**Issue by Ceyarrecks** [sandboxie-plus/Sandboxie#1450]
(first, I am unsure if this is the correct area in which to post this problem i am experiencing, if incorrect, please move)

I was experiencing the following error from Sandboxie v5.33**.6**(64) when launching any browser (WaterFox, FireFox, Chrome) on a win7pro64 system, but ONLY when logged in under a User-privileged account, no issue when launched under the Administrator account.

SBIE2205 Service not implemented: Win32Init.5 (0000000000000005)
SBIE2205 Service not implemented: Win32Init.5 (0000000000000005)
SBIE2205 Service not implemented: Win32Init.5 (0000000000000005)
SBIE2205 Service not implemented: Win32Init.4 (FFFFFFFFC0000021)
SBIE2203 Failed to communicate with Sandboxie Service: *GUIPROXY_00000008 - SandboxieRpcSs.exe [FF000005]

this system was a recent re-image, so if this is a common error i might have solved in the past, i have long since forgotten the steps taken that had this same system with same version Sandboxie to work as expected.

Services, Firewall, installed Programs exactly match other systems where this same version of Sandboxie works fine.
No resident AV present.

installed Sandboxie-Plus v0.9.8d[nov2021]

received (basically) same error when launching FF, WF, Chrome under User-privileged account.

SBIE2205 Service not implemented: Win32Init.5 (0000000000000005)
SBIE2205 Service not implemented: Win32Init.4 (FFFFFFFFC0000021)
SBIE2203 Failed to communicate with Sandboxie Service: *GUIPROXY_00000002; MsgId: 13 - SandboxieRpcSs.exe [FF000005]

Note: when launching browser, SB+ displays that sbieCtrl.exe[v5.53.3] runs/reloads after Exiting (and shows icon in system tray)
[placed sbieCtrl.exe into Never Launch box, which seemed to bring SB+ UI up when launching browser]
...
promoted user account to admin, logged in, verified SB+'s settings, launched FF, WF, Chrome w/o problem.
removed admin priv from user account, launched FF, SB+ ui displayed, FF ui d/n display, relaunched FF, received same set of errors.

firefox.exe (2952) SBIE2205 Service not implemented: Win32Init.5 (0000000000000005)
firefox.exe (2952) SBIE2205 Service not implemented: Win32Init.4 (FFFFFFFFC0000021)
SandboxieRpcSs.exe (1720) SBIE2203 Failed to communicate with Sandboxie Service: *GUIPROXY_00000002; MsgId: 13 - SandboxieRpcSs.exe [FF000005]

again, to stress fact, this re-imaged system WAS working with former 5.53**.6** version of "classic" SB prior to re-image; which this error seems familiar, i do NOT recall steps taken in the past to resolve it,... (i will certainly, this time around, retain all troubleshooting steps and resolution(s))

Thank you for the guidance/assistance.

**Comment by isaak654** [comment]
1) Could you attach your configuration file (sandboxie.ini) used on 0.9.8d ?
2) Do you use third-party security software or specific security extensions on all Chromium browsers?

**Comment by isaak654** [comment]
1) Could you attach your configuration file (sandboxie.ini) used on 0.9.8d ?
2) Do you use specific security extensions on all browsers?

**Comment by isaak654** [comment]
1) Could you attach your configuration file (sandboxie.ini) used on 0.9.8d ?
2) Do you use specific extensions on all browsers?

**Comment by Ceyarrecks** [comment]
ALCON:

I want to Thank You for taking the time to assist me.
Please see attached, both for file requested and Messages display by SB+.
There is NO security software installed on the system (unless you
consider the GUI called Windows Firewall Control or YogaDNS as
"security")

Additionally,
I. these are re-emergent errors, as I /seem/ to recall* these in the
past; however I neglected to save the troubleshooting/resolution steps
accomplished on this same image.
II. these errors ONLY occur on a USER-privileged account, NOT on an
Administrator-privileged account.

*i have such a horrible memory, hence my dire need to take and keep notes.

So, as Sandboxie Classic(SBc) v.5.33.6(64bit) [i think this was the
Sophos-released version in mar/apr2020] works fine on other systems
nearly identically-configured[win7pro, FF, WF, IE, Crm all in separate
sandboxes on a User account, with WFC & YogaDNS; no issues],

I think it is a problem with *ME* my configuration, or lack there-of.

I just do not recall what I did last time to resolve this. :(

So it is my hope, through the error messages provided and any pother
further troubleshooting, that I receive help in understanding what is
lacking or mis-configured. And certainly, this would provide better
insight into a rare, fringe case (i know, right? how many run their
systems locked down?) for the improved performance of SB+

Any more in-depth questions on the configuration of my system(s), please ask :)

I Thank You again for your time in assisting me.

Hunt Christopher Adam.

On 12/23/21, isaak654 ***@***.***> wrote:
> 1) Could you attach your configuration file (sandboxie.ini) used on 0.9.8d
> ?
> 2) Do you use third-party security software or specific security extensions
> on all Chromium browsers?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/sandboxie-plus/Sandboxie/issues/1450#issuecomment-1000300800
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Hunt Christopher Adam

*_The expectancy of the Strong_*
is to Protect & Support the weak, the wounded, the infirm.
Not miles ahead that the dangers they are being protected from are forgotten,
Not from behind that they are injured by said danger and friendly-fire,
but
Side. by. Side.
that they see What. they are being protected from,
How. they are being protected,
and to learn to protect others who are,...
weak,... wounded,... infirm,...
once they are become strong.


|Time|         |Message|                                                                                                                                          

13:13:25.302   Sbie Directory: C:\Program Files\Sandboxie-Plus                                                                                                    
13:13:25.302   Sbie+ Version: 0.9.8d (5.53.0)                                                                                                                     
13:13:25.302   Loaded Config: C:\Windows\Sandboxie.ini                                                                                                            
13:16:05.960   iexplore.exe (292): SBIE2205 Service not implemented:  Win32Init.5 (00000005)                                                                      
13:16:17.773   SandboxieRpcSs.exe (1388): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 - SandboxieRpcSs.exe [FF000005]   
13:16:22.713   SandboxieRpcSs.exe (1908): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                       
13:16:22.727   chrome.exe (900): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                                
13:16:22.846   SandboxieDcomLaunch.exe (1264): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                  
13:16:22.862   chrome.exe (112): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                                
13:16:26.792   chrome.exe (112): SBIE2205 Service not implemented:  Win32Init.4 (FFFFFFFFC0000021)                                                                
13:16:26.794   SandboxieRpcSs.exe (1908): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 - SandboxieRpcSs.exe [FF000005]   
13:16:33.524   SandboxieRpcSs.exe (1788): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                       
13:16:33.583   waterfox.exe (1112): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                             
13:16:33.650   SandboxieDcomLaunch.exe (1636): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                  
13:16:34.401   waterfox.exe (1112): SBIE2205 Service not implemented:  Win32Init.4 (FFFFFFFFC0000021)                                                             
13:16:34.404   SandboxieRpcSs.exe (1788): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 - SandboxieRpcSs.exe [FF000005]   
13:16:42.182   firefox.exe (2032): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                              
13:16:42.188   SandboxieRpcSs.exe (2044): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                       
13:16:42.295   SandboxieDcomLaunch.exe (984): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                   
13:16:42.993   firefox.exe (2032): SBIE2205 Service not implemented:  Win32Init.4 (FFFFFFFFC0000021)                                                              
13:16:42.997   SandboxieRpcSs.exe (2044): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 - SandboxieRpcSs.exe [FF000005]

**Comment by isaak654** [comment]
> Please see attached, both for file requested and Messages display by SB+.

I'm sorry, but there is no sandboxie.ini file attached on your reply... unfortunately GitHub doesn't seem to provide a reliable way to attach files via email, so I would recommend to use the GitHub web interface to send the file or even a simple copy and paste of the file content.

**Comment by Ceyarrecks** [comment]
Alright, the frighteningly horrific text file attachments omitted;
please see below, with ==== as delineations between the aforementioned
files :)
Sorry for the inconvenience.
and again, I Thank You for the time taken to assist me.

==========sandboxie.ini
[GlobalSettings]

Template=OfficeLicensing
FileRootPath=E:\\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
EditAdminOnly=y
ForceDisableAdminOnly=y
ForgetPassword=n
StartRunAlertDenied=y
NotifyStartRunAccessDenied=y
AlertProcess=C:\Program Files\Sandboxie-Plus\SbieCtrl.exe

[UserSettings_583405F4]

SbieCtrl_UserName=oddministrator
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_ShowWelcome=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=16,258,880,450
SbieCtrl_ActiveView=40022
SbieCtrl_BoxExpandedView=Offices
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_NextUpdateCheck=1640700902
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[UserSettings_95D8073A]

SbieCtrl_UserName=christopher_a._hunt
SbieCtrl_ShowWelcome=n
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_BoxExpandedView=Chrome,IE,PDFs,WaterFox
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=380,295,880,450
SbieCtrl_ActiveView=40022
SbieCtrl_NextUpdateCheck=1640702378
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EnableAutoStart=y

[FireFox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=Firefox_Force
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#8080FF,ttl
Enabled=y
BoxNameTitle=n
ForceFolder=C:\Program Files\FireFox
CopyLimitKb=491520
NotifyInternetAccessDenied=n
DropAdminRights=y
ClosedFilePath=E:\Documents\

[WaterFox]

Enabled=y
ConfigLevel=9
AutoRecover=y
Template=SkipHook
Template=FileCopy
Template=Waterfox_Force
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#ffff00,ttl,6
BoxNameTitle=n
ForceFolder=C:\Program Files\WaterFox Classic
CopyLimitKb=491520
DropAdminRights=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
ClosedFilePath=E:\Documents\
NotifyDirectDiskAccess=y
AllowNetworkAccess=<BlockNetAccess>,n

[Chrome]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#0000FF
BoxNameTitle=n
ForceFolder=C:\Program Files\Google
CopyLimitKb=491520
DropAdminRights=y
ClosedFilePath=E:\Documents\

[IE]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=IExplore_Favorites_RecoverFolder
Template=IExplore_Force
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#0080FF,ttl
BoxNameTitle=n
ForceFolder=C:\Program Files (x86)\Internet Explorer
ForceFolder=C:\Program Files\Internet Explorer
NotifyInternetAccessDenied=n
ClosedFilePath=InternetAccessDevices
DropAdminRights=y
ReadFilePath=E:\Documents\

[PDFs]

Enabled=y
ConfigLevel=9
AutoRecover=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
BoxNameTitle=n
ForceFolder=C:\Program Files (x86)\Foxit
NotifyInternetAccessDenied=n
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
ClosedFilePath=InternetAccessDevices
DropAdminRights=y
ReadFilePath=E:\Documents\
AllowNetworkAccess=<BlockNetAccess>,n
CopyLimitKb=81920
AutoDelete=y
ProcessGroup=<InternetAccess>,

[Offices]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#8000FF,ttl
BoxNameTitle=n
ForceFolder=C:\Program Files (x86)\Office
ForceFolder=C:\Program Files (x86)\Microsoft Works
ForceFolder=C:\Program Files (x86)\Microsoft Office
ForceFolder=C:\Program Files (x86)\LibreOffice 4
NotifyInternetAccessDenied=n
ClosedFilePath=InternetAccessDevices
DropAdminRights=y

[DefaultBox]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
==========


==========sandboxie messages
|Time|         |Message|

13:13:25.302   Sbie Directory: C:\Program Files\Sandboxie-Plus
13:13:25.302   Sbie+ Version: 0.9.8d (5.53.0)
13:13:25.302   Loaded Config: C:\Windows\Sandboxie.ini
13:16:05.960   iexplore.exe (292): SBIE2205 Service not implemented:
Win32Init.5 (00000005)
13:16:17.773   SandboxieRpcSs.exe (1388): SBIE2203 Failed to
communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 -
SandboxieRpcSs.exe [FF000005]
13:16:22.713   SandboxieRpcSs.exe (1908): SBIE2205 Service not
implemented:  Win32Init.5 (0000000000000005)
13:16:22.727   chrome.exe (900): SBIE2205 Service not implemented:
Win32Init.5 (0000000000000005)
13:16:22.846   SandboxieDcomLaunch.exe (1264): SBIE2205 Service not
implemented:  Win32Init.5 (0000000000000005)
13:16:22.862   chrome.exe (112): SBIE2205 Service not implemented:
Win32Init.5 (0000000000000005)
13:16:26.792   chrome.exe (112): SBIE2205 Service not implemented:
Win32Init.4 (FFFFFFFFC0000021)
13:16:26.794   SandboxieRpcSs.exe (1908): SBIE2203 Failed to
communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 -
SandboxieRpcSs.exe [FF000005]
13:16:33.524   SandboxieRpcSs.exe (1788): SBIE2205 Service not
implemented:  Win32Init.5 (0000000000000005)
13:16:33.583   waterfox.exe (1112): SBIE2205 Service not implemented:
Win32Init.5 (0000000000000005)
13:16:33.650   SandboxieDcomLaunch.exe (1636): SBIE2205 Service not
implemented:  Win32Init.5 (0000000000000005)
13:16:34.401   waterfox.exe (1112): SBIE2205 Service not implemented:
Win32Init.4 (FFFFFFFFC0000021)
13:16:34.404   SandboxieRpcSs.exe (1788): SBIE2203 Failed to
communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 -
SandboxieRpcSs.exe [FF000005]
13:16:42.182   firefox.exe (2032): SBIE2205 Service not implemented:
Win32Init.5 (0000000000000005)
13:16:42.188   SandboxieRpcSs.exe (2044): SBIE2205 Service not
implemented:  Win32Init.5 (0000000000000005)
13:16:42.295   SandboxieDcomLaunch.exe (984): SBIE2205 Service not
implemented:  Win32Init.5 (0000000000000005)
13:16:42.993   firefox.exe (2032): SBIE2205 Service not implemented:
Win32Init.4 (FFFFFFFFC0000021)
13:16:42.997   SandboxieRpcSs.exe (2044): SBIE2203 Failed to
communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 -
SandboxieRpcSs.exe [FF000005]
==========

On 12/23/21, isaak654 ***@***.***> wrote:
>> Please see attached, both for file requested and Messages display by SB+.
>
> I'm sorry, but there is no sandboxie.ini file attached on your reply...
> unfortunately GitHub doesn't seem to provide a reliable way to attach files
> via email, so I would recommend to use the GitHub web interface to send the
> file or even a simple copy and paste of the file content.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/sandboxie-plus/Sandboxie/issues/1450#issuecomment-1000513826
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Hunt Christopher Adam

*_The expectancy of the Strong_*
is to Protect & Support the weak, the wounded, the infirm.
Not miles ahead that the dangers they are being protected from are forgotten,
Not from behind that they are injured by said danger and friendly-fire,
but
Side. by. Side.
that they see What. they are being protected from,
How. they are being protected,
and to learn to protect others who are,...
weak,... wounded,... infirm,...
once they are become strong.

**Comment by isaak654** [comment]
The ini file looks good to me.

I just found these old discussions with a similar issue like yours:
https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopicc1dec1de.html?f=40&t=16281
https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopica3ce-2a3ce.html?f=11&t=19835

The first link suggests something related to any third-party software that is blocking the Sandboxie process "SandboxieRpcSs.exe":

> If you're still getting those error codes 00000005 and FF000005 in the messages,
> then you might have some third party software that is blocking the process in the
> sandbox from connecting to the Sandboxie service.

or something related to custom "group policy" settings:
> ust an FYI the problem occurs after restoring my group policy settings from a backup, evidently they were the cause. Simply resetting to defaults is enough to fix the problem and it is easily reproduced. 

----

The second link is about "User Rights Assignment" policy settings:

> I finally had some spare time so I went through and tested changes one at a time and finally figured out the cause. When I removed Users from "Bypass traverse checking" in User Rights Assignment and attempted to launch a forced program via runas I got this error once again. Adding Users back allows me to use runas to launch the program and Sandboxie 4.x does not throw the SBIE2205 Win32Init.5 error any longer.

**Comment by Ceyarrecks** [comment]
SOLUTION:
 it seems the PC in question was LACKING groups under secpol.msc
Computer Configuration\Windows Settings\Security Settings\Local Policies\User Rights Assignment\
**Bypass traverse checking**

That being either^
**USERS Group**
or
_%SpecificNamedUser-PrivilegedAccount%_

also note, one does NOT, EVER, need Everyone Group in Bypass listing. 

^ tested on two different systems, one with initial issue, other known good.

more info at:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn221950(v=ws.11)

**Comment by Ceyarrecks** [comment]
ALCON:

Thank YOU! for the point in right direction, as I verified on the
issue system and a known good their Bypass traverse checking.

here is the
SOLUTION:

it seems the PC in question was LACKING groups under secpol.msc

Computer Configuration\Windows Settings\Security Settings\Local
Policies\User Rights Assignment\

Bypass traverse checking

That being either^

USERS Group
or
%SpecificNamedUser-PrivilegedAccount%

also note, one does NOT, EVER, need Everyone Group in Bypass listing.

^ tested on two different systems, one with initial issue, other known good.

more info at:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn221950(v=ws.11)

I Thank You again for your assistance in this issue.
I also Thank You for /your/ patience with an issue that was obviously
*my* mis-configuration.

Hunt Christopher Adam.




On 12/23/21, isaak654 ***@***.***> wrote:
> The ini file looks good to me.
>
> I just found these old discussions with a similar issue like yours:
> https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopicc1dec1de.html?f=40&t=16281
> https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopica3ce-2a3ce.html?f=11&t=19835
>
> The first link suggests something related to any third-party software that
> is blocking the Sandboxie process "SandboxieRpcSs.exe":
>
>> If you're still getting those error codes 00000005 and FF000005 in the
>> messages,
>> then you might have some third party software that is blocking the process
>> in the
>> sandbox from connecting to the Sandboxie service.
>
> or something related to custom "group policy" settings:
>> ust an FYI the problem occurs after restoring my group policy settings
>> from a backup, evidently they were the cause. Simply resetting to defaults
>> is enough to fix the problem and it is easily reproduced.
>
> ----
>
> The second link is about "User Rights Assignment" policy settings:
>
>> I finally had some spare time so I went through and tested changes one at
>> a time and finally figured out the cause. When I removed Users from
>> "Bypass traverse checking" in User Rights Assignment and attempted to
>> launch a forced program via runas I got this error once again. Adding
>> Users back allows me to use runas to launch the program and Sandboxie 4.x
>> does not throw the SBIE2205 Win32Init.5 error any longer.
>
>
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/sandboxie-plus/Sandboxie/issues/1450#issuecomment-1000540792
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Hunt Christopher Adam

*_The expectancy of the Strong_*
is to Protect & Support the weak, the wounded, the infirm.
Not miles ahead that the dangers they are being protected from are forgotten,
Not from behind that they are injured by said danger and friendly-fire,
but
Side. by. Side.
that they see What. they are being protected from,
How. they are being protected,
and to learn to protect others who are,...
weak,... wounded,... infirm,...
once they are become strong.
