### ISSUE TITLE
[Sandboxie-Classic-x64-v5.55.4.exe] Requires UAC at Windows Startup

### ISSUE THREAD

**Issue by xvim64** [sandboxie-plus/Sandboxie#1451]
**Describe the problem**
Requires UAC at Windows Startup

**To Reproduce**
1. Install Sandboxie-Classic-x64-v5.55.4.exe
2. Reboot Windows

**Screenshots**
![01](https://user-images.githubusercontent.com/83569599/147011072-db0e4fb0-5627-461d-8c55-07376efe3bc4.png)

**Expected behavior**
No UAC Dialog

**System details and installed software**

 - What is your Windows edition and version?
Windows 10 21H2 64-bit

 - What is your current Sandboxie edition and version?
Sandboxie-Classic-x64-v5.55.4.exe

 - What was your previous Sandboxie version before the update, if any?
Sandboxie-Classic-x64-v5.55.3.exe

 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
Sandboxie-Classic-x64-v5.55.4.exe

**Comment by ImSpecial** [comment]
I cannot reproduce this, mine works expected, no UAC prompts on boot.

**Comment by DavidXanatos** [comment]
Try reinstalling the software seams to me sbiesvc is not set to autostart

**Comment by xvim64** [comment]
It seems that Microsof Security Essentials blocked some part of the sandbxoie installation process.

It's normal now.

**Comment by xvim64** [comment]
> Try reinstalling the software seams to me sbiesvc is not set to autostart

It seems that Microsof Security Essentials blocked some part of the sandbxoie installation process.
It's normal now.

**Comment by isaak654** [comment]
According to the OP, this bug got introduced since `Sandboxie-Classic-x64-v5.55.4.exe`.

It's time to reopen this issue because of new reports affecting both Sandboxie Plus and Classic editions:

Report n. 1 ([Source](https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-7.443250/#post-3060995))
> There is one minor issue though I'm observing with increased frequency - at least since v1.06, probably since v1.05 or even before that. Not exactly sure when it actually started but somewhere in the v1.0x-range.
>
>The issue being that now in approx. 1/3 of cases of boot-up or re-boot the UAC will be triggered. When entering OK the boot-sequence will continue as normal. If I decline an error-message will pop up that the connection to the driver has somehow failed and there is no Sandboxie-service available.
>
> Not a big thing as compared to the general progress that seemingly makes things run even more smoothly, especially after "blitz"-fixing the Chromium-browsers closing-issue with v1.07. Just wanted to mention it though and nominate the UAC-phenomenon for further analysis and a possible fix in a future release.
>
> Again I have no clue so far what (timing issue?) difference in the boot-up-sequence might trigger the UAC - but in about 2/3 of cases Sandboxie-plus will start up completely normal wit no UAC-triggering at all. 

Report n. 2 ([Source](https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-7.443250/#post-3061033))
> I can confirm this. This happened to me when doing a clean install in the last few versions. After completing the install, when you reboot the computer, UAC is triggered and a message about the Sandboxie service pops up. Once you click ok, you don't see the message again. I forgot to mention it until all saw this post. It happens in both Sandboxie Plus and Classic.

**Comment by isaak654** [comment]
> i think i have found the issue with the csrss.exe the function to find its PID was failing when very quickly while it was operating new processes were created, as it can happen on boot.
> Will be fixed in the next build 


Source: https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-7.443250/page-3#post-3061975
