### ISSUE TITLE
[Plus] Search box in Compatibility Templates can only find template sections, not full titles

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1456]
**Is your feature request related to a problem? Please describe.**
Search box in Compatibility Templates can only find a single template section, not full templates titles.
For example: if you type "Google Chrome" you won't find anything, but if you type just "Chrome" without spaces you will find the corresponding results.

**Describe the solution you'd like**
The search box in App Templates -> Compatibility Templates should extend the search to the full length of templates titles (indicated as `Tmpl.Title` in the _Templates.ini_ file):
https://github.com/sandboxie-plus/Sandboxie/blob/6c77cc63192032008a02e8df52a477e6a412f482/Sandboxie/install/Templates.ini#L486

**Comment by Coverlin** [comment]
The filter uses the template section not the tmpl.title

**Comment by DavidXanatos** [comment]
In the next build the display name of the template will be used
