### ISSUE TITLE
Could not install and launch Microsoft Teams

### ISSUE THREAD

**Issue by Deilan** [sandboxie-plus/Sandboxie#1459]
**Describe the problem**
Could not install and launch Microsoft Teams
                                             
**To Reproduce**
1. Download Microsoft Teams for Windows desktop from https://www.microsoft.com/en-us/microsoft-teams/download-app
2. Run downloaded `Teams_windows_x64.exe`

**Screenshots**
![image](https://user-images.githubusercontent.com/4777512/147268867-b088d624-4b69-4755-8664-e58aeb2d727b.png)

**Expected behavior**
Microsoft Teams for Windows desktop is installed and launched successfully.

**System details and installed software**
 - Windows 10 Pro 20H2 64-bit
 - Sandboxie Plus 0.9.8d 64-bit
 - Kaspersky Endpoint Security 11.7.0.669 AES56

**Additional context**
Log:
```
Teams_windows_x64.exe (7892): SBIE1231 Initialization failed for process Teams_windows_x64.exe [C0000038 / 66]
Teams_windows_x64.exe (7892): SBIE1231 Initialization failed for process [C0000001 / A8]
PID 16828: SBIE2314 Cancelling process Teams_windows_x64.exe
Teams_windows_x64.exe (4544): SBIE1231 Initialization failed for process Teams_windows_x64.exe [C0000038 / 66]
Teams_windows_x64.exe (4544): SBIE1231 Initialization failed for process  [C0000001 / A8]
PID 16828: SBIE2314 Cancelling process Teams_windows_x64.exe
```

**Sandboxie configuration**
<details>

<summary>My initial sandboxie.ini settings</summary>

```
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]

[UserSettings_37F204AF]
SbieCtrl_AutoStartAgent=SandMan.exe

[DefaultBox]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

```

</details>

**Comment by isaak654** [comment]
Did you try to add the Sandboxie installation folder to the Kaspersky exclusion list?

**Comment by Deilan** [comment]
> Did you try to add the Sandboxie installation folder to the Kaspersky exclusion list?

Unfortunately I am not allowed to.

But I restarted the OS after the installation of Sandboxie and everything works fine for some reason since then.

**Comment by kocane** [comment]
@Deilan did you actually have succes using Teams? I can sign in and the program seems to load correctly for a moment but then it just freezes. It does this consistently.

**Comment by Aeroverra** [comment]
> @Deilan did you actually have succes using Teams? I can sign in and the program seems to load correctly for a moment but then it just freezes. It does this consistently.

same here
