### ISSUE TITLE
Broken after 5.26

### ISSUE THREAD

**Issue by robdplatt** [sandboxie-plus/Sandboxie#146]
I have a unique situation. We run a proprietary app that is written in Visual Fox Pro. I do not have access to the source. I've been able to run it for years in Sandboxie.

Recently we ran into the problem that our license failed to activate, so we were forced to update. Upon updating this app no longer works. I went through each version and found that the break occurs when we install 5.28. (Each version prior works, each version after fails).

I can't simply use an older version in free mode due to needing to run multiple copies of this app side by side. (It requires it's own environment).

OS Windows Server 2020 R2 (No recent changes).

Upon launching the app we are met with

> ---------------------------
> COM Failure 1426
> ---------------------------
> OLE error code 0x800401ea: Moniker cannot open file.

![image](https://user-images.githubusercontent.com/13525487/94837283-eb3e4000-03c8-11eb-8ecb-b61c8c077798.png)

> ---------------------------
> Error 1924
> ---------------------------
> LOWBEMSERVICES is not an object.

![image](https://user-images.githubusercontent.com/13525487/94837320-f5603e80-03c8-11eb-8bc8-7362344890f5.png)

![image](https://user-images.githubusercontent.com/13525487/94837337-fabd8900-03c8-11eb-8940-a8528777f4f5.png)

Undoubtedly, these errors are within Visual Fox Pro. 

I've tried using Procmon, Resource viewer, and the API Log viewer to see if I could determine errors. I wasn't able to. The API Log viewer, when running, prevents this application from even starting. It fails immediately with DWWIN error:

> Fatal error: Exception code=C0000005 @ 10/01/20 09:38:08 AM. Error log file: C:\Program Files (x86)\Common Files\Microsoft Shared\VFP\vfp9rerr.log

This happens in all sandboxes, even a new one. Here's the config for this sandbox. Note that none of these settings are necessary. This app used to run in the DefaultBox

> Enabled=y
> ConfigLevel=7
> AutoRecover=y
> Template=WindowsFontCache
> Template=BlockPorts
> Template=LingerPrograms
> Template=Chrome_Phishing_DirectAccess
> Template=Firefox_Phishing_DirectAccess
> Template=AutoRecoverIgnore
> RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
> RecoverFolder=%Personal%
> RecoverFolder=%Favorites%
> RecoverFolder=%Desktop%
> BorderColor=#00ffff,ttl,6
> OpenPipePath=\Device\NamedPipe\LogAPI
> OpenPipePath=E:\
> CopyLimitKb=819200
> CopyLimitSilent=y
> InjectDll=C:\Users\me\Desktop\Sandboxie Installers\Sandboxie-Plus\LogAPI\logapi32.dll
> InjectDll64=C:\Users\me\Desktop\Sandboxie Installers\Sandboxie-Plus\LogAPI\logapi64.dll

I've done everything I can to try and figure out what exactly changed between 5.26 and 5.28. The changelog points to a forum link that isn't part of the old forum.

Any ideas? I've all but given up at this point. My only work-around is to start firing up VM's, which I was hoping to avoid.

It's worth noting that another Visual Fox Pro app does launch successfully.

**Comment by robdplatt** [comment]
Just adding that this seems to fail when attempting to read something from winmgmts. More than likely using the GetObject function in VFP. Something changed in 5.28 that is interfering with this.

**Comment by DavidXanatos** [comment]
hmm... now that would be easy if older sources would be available but they are not.
I don't really know how to tackle that issue, without having access to the particular applications making problems.
I would have to somehow get my hands on that software.

**Comment by robdplatt** [comment]
I'll email you a dropbox link to the setup.exe. Feel free to poke at it in your own test environment. Note that so far my testing was limited to the already installed application. Running the installer within a new sandbox, on a computer that has never seen it before, produced a new set of errors. I haven't had a chance to start down that road of troubleshooting yet.

**Comment by DavidXanatos** [comment]
I seam not to have recived the affected binary so I'll close that for now

**Comment by DavidXanatos** [comment]
ok thanks will test it on we

**Comment by DavidXanatos** [comment]
i still havn't got it, Strage, can you upload it in a pasword protected archive to some file hoster and send me may be only the link and the password that may work better

**Comment by robdplatt** [comment]
I'm not sure why you're not getting my email. I'm sending you the dropbox link from my gmail to yours. It was sent Oct 29th. Is there another method in which I can privately provide the URL? I don't want it posted publically.

**Comment by DavidXanatos** [comment]
whats the status of this issue in the latest build of sbie plus is it fixed now?

**Comment by robdplatt** [comment]
@DavidXanatos, give me a couple of days and I'll see about testing it. Thanks for pinging me.

**Comment by DavidXanatos** [comment]
i tryed the software and it opens on my test system in the latest build so I'll close this now
