### ISSUE TITLE
plus 0.9.8d recovery window doesn't show after delete content is clicked

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1462]
if delete content is clicked the content is deleted without previously showing recovery window, this is bad if we forget to recover something

**Comment by DavidXanatos** [comment]
this isue is fixed in the 1.0.x pre release line please update to 1.0.4 or wait for 1.0.5 that is to come out very soon

**Comment by diieg707** [comment]
Thx
