### ISSUE TITLE
[1.0.5 / 5.55.5] Error 0x426-0x0 with Office 2021 when launching programs

### ISSUE THREAD

**Issue by srccrow** [sandboxie-plus/Sandboxie#1468]
**Issue with:** Release v1.0.5 / 5.55.5

**What happens:** Any program, like Excel, or Word, will refuse to start once the driver is loaded after a reboot, the problem is experienced both with a clean installation and with an upgrade over a previous version.

**What tested:**  Regression to pre-release, doesn't cause problem.

**Comment by isaak654** [comment]
I can confirm the regression with Excel and Word 2016 C2R (using a new clean sandbox with the default preset):
![endpoint_error_1752](https://user-images.githubusercontent.com/12372772/147389957-18599baf-17d4-4a48-b3ba-ae026a336cf3.png)

**Comment by DavidXanatos** [comment]
I'll upload a fixed build soon, just need to wait for a new signature

**Comment by DavidXanatos** [comment]
fixed: https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.5.1

**Comment by KANGKKKKKKK** [comment]
OK, update the old sandbox to solve the " OfficeClickToRun.exe does not run, Problem with error code 0xc 000005 "
