### ISSUE TITLE
Can not create shortcut from Box Content since 1.0.4

### ISSUE THREAD

**Issue by wenyifancc** [sandboxie-plus/Sandboxie#1471]
**Describe the problem**
Can not create shortcut from Box Content since 1.0.4

**To Reproduce**
1.Right click the sandbox
2.Select [Box Content]->[Create Shortcut]
3.Select the Program from menu
4.Nothing happen

**Expected behavior**
Show the dialog box to save shortcut.

**System details and installed software**
OS:Windows 10
Problem with Sandboxie-plus 1.0.4 and 1.0.5
Normal with  Sandboxie-plus 1.0.3 and earlier version

**Comment by isaak654** [comment]
Workarounds:
* Create shortcuts manually on Windows using the following [tips](https://sandboxie-plus.github.io/sandboxie-docs/Content/StartCommandLine.html).
* Open SbieCtrl.exe that's included on main Plus folder and use the [Add Shorcut Icons](https://sandboxie-plus.github.io/sandboxie-docs/Content/ConfigureMenu.html#windows-shell-integration) button.
