### ISSUE TITLE
Microsoft Office Visio 2016 - Error 1719 The Windows Installer Service Access

### ISSUE THREAD

**Issue by bytos** [sandboxie-plus/Sandboxie#1474]
Installed latest classic version (today) and continue to get the same error.

In the past, installing a more recent version of Sandboxie solved a similar issue, but not this time.

Since it is an old version (2016) and no updates will be installed, is there a way to install it in Sandboxie?

`Error 1719. The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed.`

**Comment by isaak654** [comment]
Did you add `MsiInstallerExemptions=y`  into the ini file on your sandbox ?

**Comment by bytos** [comment]
Have used the sandbox settings before, but have not seen an .ini file.

**Comment by isaak654** [comment]
Assuming you're on the main Sandboxie Plus window and you've closed any running program in the sandbox:

* Go to Options menu -> Edit ini file -> confirm yes
* Add `MsiInstallerExemptions=y` below [DefaultBox]
* Save the ini file and close it

In Sandboxie Classic, the steps are a bit different:
* Go to Configure menu -> Edit configuration -> confirm yes
* Add `MsiInstallerExemptions=y` below [DefaultBox]
* Save the ini file and close it

**Comment by bytos** [comment]
That worked, thanks.

But got an unspecified error, maybe others have tried installing Office 2016 and solved this problem.

`Microsoft Visio Professional 2016 encountered an error during setup.`

**Comment by isaak654** [comment]
Paint 3D is an UWP app or store app, and it's a current Sandboxie limitation: https://github.com/sandboxie-plus/Sandboxie/issues/19

However, in the scheduled changes of the next 1.0.6 version, the developer added the following note:
`* added ability to run store apps in app container mode, requirers COM to be open`

You can read the full changelog [here](https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md).

**Comment by bytos** [comment]
Installed it inside the sandbox only because don't have much use for it afterwards and could just delete the sandbox's contents.

Paint 3D wasn't working outside the sandbox, but good to know about the limitation.

Thanks

**Comment by pantau000** [comment]
doesn't work for me, still get the same error trying to install bonjour
