### ISSUE TITLE
sbie plus - add "don't prompt again for immediate recovery until all programs in this sandbox have ended" checkbox on recovery window

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1478]
add **"don't prompt again for immediate recovery until all programs in this sandbox have ended"** checkbox on recovery window

**Comment by diieg707** [comment]
would you mind taking this request?

**Comment by DavidXanatos** [comment]
its added a few versions ago dont rememner in ehich one

**Comment by diieg707** [comment]
i just looked all over plus 0.22 and didn't find this option, i'm afraid you didn't add it.

**Comment by DavidXanatos** [comment]
its here:
![grafik](https://user-images.githubusercontent.com/3890945/170928202-acad6af6-649f-4385-913a-af0fcb14b6f8.png)

**Comment by diieg707** [comment]
> ed all over plus 0.22 an

you put it in a weird way, thank you though

**Comment by diieg707** [comment]
@DavidXanatos i just sent you an email asking for something, would you answer it?

**Comment by Germs2004** [comment]
Could we get another button that says "Disable Immediate Recovery for this Box" that permanently disables it?

**Comment by DavidXanatos** [comment]
> Could we get another button that says "Disable Immediate Recovery for this Box" that permanently disables it?

yes will be added to the next build
