### ISSUE TITLE
Windows Explorer in Sandbox is not working on Windows 11 21H2

### ISSUE THREAD

**Issue by wenyifancc** [sandboxie-plus/Sandboxie#1480]
**Describe the problem**
Windows Explorer in Sandbox is not working on Windows 11 21H2,just show a broken window and it can't be close.
If you wait about 50 seconds,the broken window will work fine(But right-click menu is invalid).

Temporary workaround:
1. Select [Run] -> [Boxed Tools] -> [Programs and Features]
2. Switch to [This PC] from address bar.

**To Reproduce**
1. Right click the sandbox.
2. Select [Run] -> [Boxed Tools] -> [Windows Explorer]
3. See error

**Screenshots**
![Broken Window](https://file.evan.run/20211227100322.png)
[Problem Video](https://file.evan.run/problem.mp4)

**System details and installed software**
OS: Windows 11 21H2 x64
Sandboxie-plus v1.0.5

**Comment by isaak654** [comment]
See https://github.com/sandboxie-plus/Sandboxie/issues/1127#issuecomment-950351353
