### ISSUE TITLE
Microsoft Office 365 error 0x426-0x0

### ISSUE THREAD

**Issue by Nanonona** [sandboxie-plus/Sandboxie#1482]
**Describe the problem**
Microsoft Office 365 error

1.Creat New Box
2.Open Microsoft Office 365 error

**Screenshots**
![2021-12-27 225349.png](https://s2.loli.net/2021/12/27/gCGXDheUwWlLYtp.png)

**System details and installed software**
Windows 10 Pro 20H2 64-bit
Sandboxie Plus 1.0.5 64-bit

![2021-12-27 225525.png](https://s2.loli.net/2021/12/27/hHocQMsz4vXtbBG.png)
日志名称:          Application
来源:            Application Error
日期:            2021/12/27 22:38:02
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           Y7000
描述:
错误应用程序名称: OfficeClickToRun.exe，版本: 16.0.14701.20240，时间戳: 0x61b0fbaf
错误模块名称: SbieDll.dll，版本: 5.55.5.0，时间戳: 0x61c5c3ce
异常代码: 0xc0000005
错误偏移量: 0x000000000005a139
错误进程 ID: 0x1a3c
错误应用程序启动时间: 0x01d7fb2f5a0f6fd6
错误应用程序路径: C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
错误模块路径: C:\Program Files\Sandboxie-Plus\SbieDll.dll
报告 ID: 2c063c6d-7294-409d-8d65-082b02b4a0d8
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
![2021-12-27 230347.png](https://s2.loli.net/2021/12/27/nFXJu1xDWG6gUyP.png)

<summary> My initial sandboxie.ini settings </ summary>
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=InternetDownloadManager
Template=7zipShellEx

[UserSettings_08BC0141]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[Nano]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
UsePrivacyMode=n

**Comment by isaak654** [comment]
Error 0x426: https://github.com/sandboxie-plus/Sandboxie/issues/1468
