### ISSUE TITLE
BSOD happened when 微信 launched in a sandbox

### ISSUE THREAD

**Issue by StrollStars** [sandboxie-plus/Sandboxie#1483]
**Describe the problem**
When [微信](https://pc.weixin.qq.com/) launched in a sandbox, BSOD happened.

**To Reproduce**
1. Double click to lauche WeChat.exe.  
2. BSOD happened.  

**Screenshots**
No

**Expected behavior**
The [微信](https://pc.weixin.qq.com/) launched in a sandbox successfully.

**System details and installed software**
 - System: Windows 10 Home 21H1 64-bit
 - Sandboxie-Plus-x64: 1.02 and 1.03 have no problem, but 1.04 and 1.05 have the problem.

**If you had a compatibility issue or a crash**
 - 微信: https://pc.weixin.qq.com/
 - Memory dump: https://app.box.com/s/fn9gup4alae2f4jw84jmrxaeq6qbpz8f

**Additional context**
No.

**Comment by DavidXanatos** [comment]
Do you have HVCI enabled and does EnableWin32kHooks=n solve the issue?

**Comment by isaak654** [comment]
For you information, HVCI is labeled as "Memory integrity" in the Windows Security app and it can be accessed in this way:
`Settings > Update & Security > Windows Security > Device security > Core isolation details > Memory integrity`

**Comment by StrollStars** [comment]
@isaak654 "Memory integrity" disabled can solve the problem, but I prefer what @DavidXanatos said.
Thank you very much.

**Comment by isaak654** [comment]
The HVCI fix is already on 1.0.6, thanks for the confirmation.

**Comment by StrollStars** [comment]
@isaak654 Thank you, it works even without EnableWin32kHooks=n.
