### ISSUE TITLE
Windows 11 notepad can not run

### ISSUE THREAD

**Issue by ImJordanKing** [sandboxie-plus/Sandboxie#1489]
**Describe the problem**
the new notepad in windows 11 can not run

**To Reproduce**
1. Go to 'DefaultBox'
2. run xxx.txt
3. See error

**Screenshots**

![图片](https://user-images.githubusercontent.com/96854166/147718997-f2b18882-bce3-4b36-acb2-69ac5682e69a.png)

**Comment by isaak654** [comment]
That's because Notepad on Windows 11 is an UWP app, see #19.
