### ISSUE TITLE
Google Chrome Version 86.0.4240.75 doesn't work in Sandboxie 5.43.5

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#149]
The extensions crash and the tab shows a sad face and the web page isn't displayed.
I turned off Eset NOD32.
Uninstalled the last version from Sophos, keeping the ini file, and rebooted.
I installed the latest version 5.43.5 and Chrome has the same problem in Sandboxie.

**Comment by DavidXanatos** [comment]
Its a known issue with the latest chrome build... I'm looking into it.
as a workaround you can disable chromes own sandbox with the command line parameter "--no-sandbox"
That is works fine.

**Comment by jedimasterspaz** [comment]
By chance, would you know how to get Outlook or Thunderbird to pass "--no-sandbox" with the link that is clicked?
FYI, I'm not afraid of RegEdit.
Thanks for picking up Sandboxie and running with it.

**Comment by diversenok** [comment]
Disabling Chrome's sandbox is a really bad idea since it is significantly more restrictive than Sandboxie. You should always use special-purpose sandboxes when possible.

**Comment by DavidXanatos** [comment]
The chrome 68+ compatibility bug is properly fixed in the new build 0.4.2 released today

**Comment by bjm234** [comment]
> The chrome 68+ compatibility bug is properly fixed in the new build 0.4.2 released today

86.x
Thanks!
