### ISSUE TITLE
SBIE+1.0.6: User access to the Signal Desktop App window is blocked.

### ISSUE THREAD

**Issue by d3bil0x** [sandboxie-plus/Sandboxie#1492]
**To Reproduce**
1. Signal Desktop installed outside SBIE.
2. Run the Signal inside SBIE.
3. Minimize the Signal window.
4. Have a friend send you a message.
5. Try to restore the Signal window and write something (your access to all application functions is almost completely limited, although you can see incoming messages))

**System details and installed software**
 - Windows 10 LTSC 21H2 64-bit bld 19044.1415
 - Sandboxie Plus 1.0.6 64-bit (with 1.0.5 the problem does not occur)
 - What was your previous Sandboxie version before the update, if any?: 1.0.5
 - Please mention any security software running in the background, even if the real-time protection is disabled: Comodo Internet Security 12.2.2.8012

**If you had a compatibility issue or a crash**
 - [Signal Desktop 5.26.1](https://updates.signal.org/desktop/signal-desktop-win-5.26.1.exe) 

[Trace Log](https://gist.github.com/d3bil0x/9b2c1a3cf61430dd5e5f8d4a99646a86)

<details>

<summary>My initial sandboxie.ini settings</summary>

```

#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=D:\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=y
ForceDisableAdminOnly=y
ForgetPassword=n
Template=7zipShellEx
Template=ComodoInternetSecurity
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
ForceDisableSeconds=1000
ClosedFilePath=*\cssguard64.dll
ClosedFilePath=*\cssguard32.dll
EnableObjectFiltering=n
EnableWin32kHooks=n

[UserSettings_028E00D9]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9


[Signal]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
ForceFolder=D:\Users\MK\AppData\Local\Programs\signal-desktop
ForceFolder=D:\Users\MK\AppData\Roaming\Signal
ForceFolder=D:\Users\MK\AppData\Local\signal-desktop-updater
OpenFilePath=D:\Users\MK\AppData\Local\Programs\signal-desktop
OpenFilePath=D:\Users\MK\AppData\Local\signal-desktop-updater
OpenFilePath=D:\Users\MK\AppData\Roaming\Signal
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices


```

</details>

**Comment by isaak654** [comment]
Is there an alternative way to reproduce it without being logged in with a phone?

**Comment by d3bil0x** [comment]
> Is there an alternative way to reproduce it without being logged in with a phone?

I checked, but found no alternative without logging in.

**Comment by isaak654** [comment]
Then I would suggest to provide a trace log related to the latest working version (1.0.5).

**Comment by d3bil0x** [comment]
[Trace Log for SBIE+ 1.0.5](https://gist.github.com/d3bil0x/c73c7dbb3e632d2a31899722c19a0e48)

**Comment by d3bil0x** [comment]
Signal seems to be working fine in v1.0.7.
