### ISSUE TITLE
SandboxIE driver bug

### ISSUE THREAD

**Issue by aquila-XP** [sandboxie-plus/Sandboxie#1493]
I updated the program (Sandboxie Classic), version after version, since the new development.
Starting with 5.55.4, the program no longer works on my machine. I have Windows 10 Enterprise 2015 LTSB 64-bit.
I have no security software running in the background, except Windows Defender Engine Version: 1.1.18800.4.
I did not changed the Sandboxie.ini configuration file.
The last working version of Sandboxie Classic is 5.55.3.
I tested the new versions (5.55.4-5.55.6) on another machine (Windows 10 Enterprise LTSC version 1809 64-bit) and they are working as usual. No issue encountered.

When I try to install the program (overwrite the existing installation), the setup is stuck to this step `Extract: LICENSE.TXT`.
And a dialog box displays this message:
`Cannot create or update Sandboxie program files.`
`Please make sure that Sandboxie Control is not running, and that no programs are running sandboxed.`
`Then click OK to retry the installation.`
`Otherwise click Cancel to abort the installation.`

After I managed to finish the installation, I noticed the icon of the program with an exclamation mark in System Tray.
When I right-clicked on it I get the following message:
`SBIE2331 Service start failed: [22 / 5] Access is denied.`

Another error that I received is this:
`Failed to record configuration setting SbieCtrl_UserName in section Unknown: C0000080`

**Comment by isaak654** [comment]
Known issue: https://github.com/sandboxie-plus/Sandboxie/issues/686
* First make a backup of your C:\windows\sandboxie.ini just in case
* uninstall your faulty Sandboxie Classic installation and when prompted opt for keeping the sandboxie.ini file
* reboot
* install the latest Classic version
* reboot

**Comment by aquila-XP** [comment]
I managed to install the latest Classic version 5.55.6, after I uninstalled the old version.
But only after I rebooted the OS.
The problem is with `SbieDrv.sys`. The driver file is not unloaded from memory. Even if I kill the service, I can't delete this file. Only after I reboot I can remove it. This did not happened before.
Usually when I update the program and overwrite the existing installation, I can use it immediately after, no reboot required.

**Comment by isaak654** [comment]
Since the Classic edition of Sandboxie doesn't provide a maintenance menu to handle the driver/service removal (unlike Plus), you may want to try the following commands on a cmd prompt in administrator mode and tell if you notice some difference:

```
KmdUtil.exe stop SbieSvc
KmdUtil.exe stop SbieDrv
KmdUtil.exe delete SbieSvc
KmdUtil.exe delete SbieDrv
```

KmdUtil is located on the main Sandboxie folder.

**Comment by isaak654** [comment]
@aquila-XP Any news about this issue?

**Comment by isaak654** [comment]
@aquila-XP Any news about this issue? If yes, how did you fix it precisely?

**Comment by isaak654** [comment]
A fix will be deployed for the next build 1.0.7 / 5.55.7:
`- fixed KmdUtil sometimes not properly terminating the driver #1493`

**Comment by isaak654** [comment]
A more specific fix will be deployed to the next build 1.0.8 / 5.55.8: https://github.com/sandboxie-plus/Sandboxie/commit/130c43a62c9778b734fa625bf4f46b12d0701719

**Comment by aquila-XP** [comment]
I tested again in Windows 10 Enterprise 2015 LTSB 64-bit, the Sandboxie Classic versions 5.55.7 and 5.55.8.
It's the same issue.
The setup is stuck on the step `Extract: LICENSE.TXT`. Backup Sandboxie.ini file.
Restart. Try again. The same issue. Uninstall. Restart. The process of installation works without issues.
Pulsating icon of the program with an red exclamation mark in System Tray.
error message `SBIE2331 Service start failed: [22 / 5] Access is denied.`
Restart. Uninstall.
Back to Sandboxie Classic x64 v5.55.3 - the last working version on Windows 10 Enterprise 2015 LTSB.

**Comment by isaak654** [comment]
Did you try the KmdUtil commands mentioned above? 
You need to be located on the Sbie folder in order to be run correctly on a cmd prompt in administrator mode.

**Comment by isaak654** [comment]
Did you try the KmdUtil commands mentioned above? 
You need to be located on the Sbie folder in order to run them correctly on a cmd prompt in administrator mode.

**Comment by isaak654** [comment]
I would also be curious about what is holding you back from updating to Sandboxie Plus, if that's ok for you.

**Comment by isaak654** [comment]
> All gone right but after updating Windows (from build 22557 to 22563) it says the error as written above.
> This can be a result from Windows development build, but I'm posting my case here because the symptom is similar.

@wldh-g A related fix is planned for the next build: https://github.com/sandboxie-plus/Sandboxie/commit/24c6ec751b503ae95714ba431e196f22ecd4f553

**Comment by DavidXanatos** [comment]
So whats the state on this did the fix resolved your win 11 issue?

**Comment by wldh-g** [comment]
> So whats the state on this did the fix resolved your win 11 issue?

Yes, it works! Thank you.
