### ISSUE TITLE
[1.0.6] Issue with AutoDelete option when closing Chromium browsers

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1496]
**Describe the problem**
AutoDelete issue related to Chromium browsers starts from this post:
https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-6.442993/page-2#post-3059701

report n. 1
> anyone notice change in "Auto delete content" with 1.0.6?
> my browser box's "Auto delete content" is not deleting content.
> as test:
> 1.0.5 -> "Auto delete content" = okay.
> 1.0.6 -> "Auto delete content" = not okay.
> I'm back with 1.0.5 

report n. 2
> No David something has changed.
I can reproduce this each time.
I have my Default box (Vivaldi ) running.
I then right-click on Edge and select Run Sandboxed and choose Tester box.
I look at something online in Tester box and the close it.
Before a red x would appear and only Default Box items would appear in GUI and Tester would say empty..
But now Tester box items do not empty, I have to do it manually.
I then close Default Box and that doesn't empty either.
>
> Something stops it. Sometimes Default box will empty and sometimes it won't. 

report n. 3
> Did some testing with 1.0.6: with a sandboxed Firefox all content closes and Sandboxie autodeletes the sandbox. With a sandboxed Edge Chromium some content won’t close and of course no autodelete of the sandbox. Manually closing the Edge-sandbox and deletion no problems.

**Comment by DavidXanatos** [comment]
I have pinpointed the issue, a recent bigfix instantiation of Windows.UI.Notifications.ToastNotificationManager succeeds, however when com is closed this does nto work properly and causes a dead lock further down the line.

There is a workaround:
ClosedRT=Windows.UI.Notifications.ToastNotificationManager
this will be hard coded in the next build
