### ISSUE TITLE
Missing "Explore Sandbox/Contents" function

### ISSUE THREAD

**Issue by Coldblackice** [sandboxie-plus/Sandboxie#150]
Not sure if I'm being blind by overlooking this, but did the ability to "Explore Sandbox/Contents" get removed?

There used to be the ability to right-click a sandbox and explore it, which would open a windows explorer window to where the particular sandbox running program's contents were located on disk.

I can search/navigate to the folder manually, but it was nice having that quick function accessible from directly in/from Sandboxie. Wondering if I'm just overlooking it in Sandboxie Plus (latest, v0.4.1/v5.43.5) or if it was removed from Sandboxie Plus.

**Comment by DavidXanatos** [comment]
its not yet added, I will add it in a future build, it did not seam important so I overlooked it.

**Comment by DavidXanatos** [comment]
its included in the todays build 0.4.2

**Comment by Coldblackice** [comment]
@DavidXanatos Wow, was not expecting such a quick turnaround, awesome! Thanks!
