### ISSUE TITLE
Firefox border on 1.x

### ISSUE THREAD

**Issue by Mmoi-Fr** [sandboxie-plus/Sandboxie#1503]
When I upgraded to 1.0.5 (from the last before 1.x), Firefox ad a small border on the left of the window.

The sandbox is configured to have no border and the original title.

Note: I'm always on full window

**Comment by DavidXanatos** [comment]
re check your ini settings and post a screanshot, also try a new sandbox

**Comment by Mmoi-Fr** [comment]
Strangelly enough, while performing the tests, it seems the issue has disapeared...

**Comment by Mmoi-Fr** [comment]
Sorry I closed by error...

The Sandbox ini:
`[Firefox]
Enabled=y
AutoRecover=n
BorderColor=#00ffff,off,1
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
Template=Local_BlockTelemetry
Template=Local_RestrictedFolders
Template=Local_RestrictedOperaFolders
Template=Local_RestrictedGamingFolders
ConfigLevel=9

OpenPipePath=...

BoxNameTitle=-
CopyLimitKb=-1
ClosePrintSpooler=y
ForceFolder=C:\Program Files\Mozilla Firefox
ForceFolder=C:\Program Files (x86)\Firefox Developer Edition
AlwaysCloseForBoxed=n
DontOpenForBoxed=n
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
HideOtherBoxes=y
ShowForRunIn=n
ProcessGroup=<StartRunAccess>,`
The local templates are only ClosedFilePath directives.

The screenshot is kind of bad, but there is 1px on the edge of the screen (left only).

**Comment by Mmoi-Fr** [comment]
Just upgraded to 1.0.22, seems to be fixed
