### ISSUE TITLE
How to sign driver when it has been modified?

### ISSUE THREAD

**Issue by Aholicknight** [sandboxie-plus/Sandboxie#1505]
I am trying to compile Sandboxie-plus on my computer for testing purposes, but the driver refuses to run since the signature is invalid. I know that leaked certificates were used in the past, but since they are all outdated, this does not work (I even tried changing my computer time to match the start of the certificate time). Is there any way this can work, or do I need to disable driver signing verification altogether on my computer? Thanks.

**Comment by DavidXanatos** [comment]
You need to disable driver signing all together.
