### ISSUE TITLE
Window border highlight is missing on second monitor

### ISSUE THREAD

**Issue by ameaninglessname** [sandboxie-plus/Sandboxie#1506]
**Describe the problem**
Window border highlight is missing on second monitor

**To Reproduce**
1. Run - Boxed tool - Windows explorer
2. Move the explorer to second monitor
3. See error

**Screenshots**
Main display:
![image](https://user-images.githubusercontent.com/20263103/147906531-a163f8c2-0213-4ca9-bfc4-515f3d8c7865.png)

Second display:
![image](https://user-images.githubusercontent.com/20263103/147906538-7cdc554d-dcec-4962-9afb-13f8888982b2.png)

**Comment by DavidXanatos** [comment]
O have 5 monitors and cant reproduce this issue, any one else with that problem?

**Comment by mysteriously** [comment]
Not the same, however if you move explorer window to be 50% on one display and 50% on other display, the border shows up only around one part of the display

**Comment by DrPleaseRespect** [comment]
Could your issue be the same as mine?
#1512

**Comment by ameaninglessname** [comment]
> Could your issue be the same as mine? #1512

I think it does.
My two monitors are 2K and 1080P resolution.
