### ISSUE TITLE
FileRootPath setting is ignored when in Portable mode

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1509]
**Describe the problem**
No matter what you set as FileRootPath in the INI file (while being on Portable mode), the value is replaced with its default on startup.

**To Reproduce**
See https://forum.xanasoft.com/viewtopic.php?f=16&p=465 and https://github.com/sandboxie-plus/Sandboxie/issues/1318#issuecomment-949009840

**System details and installed software**
Sandboxie Plus 0.9.8b and 0.9.8d 64-bit
This probably affects the current build too, since it wasn't fixed.

**Comment by isaak654** [comment]
It is 0, but I already reported/fixed that manually months ago with a few attempts.
However the issue is still there and something should be done to prevent it, as shown by the other user request on your forum.

**Comment by DavidXanatos** [comment]
What would be the fix though? Its in a way intentional behavior that if the user is asked and chooses yes and selects don't ask in future.
may be an additional checkbox in the settings that allows to controll this?

**Comment by DavidXanatos** [comment]
i just realized i already added that checkbox some versions ago and forgot, LOL
![grafik](https://user-images.githubusercontent.com/3890945/149512758-fa8725ab-feab-4f71-9486-6d76d54db7f4.png)

so the issue can be closed?

**Comment by isaak654** [comment]
The portable mode can also be applied with specific portable dialogs at sandman startup (if I recall correctly), so imho there should be a choice there too.

**Comment by isaak654** [comment]
> i just realized i already added that checkbox some versions ago and forgot, LOL

I just verified that there is no "Portable root folder" in current 1.0.7 build, so it's missing or you moved it elsewhere.

**Comment by DavidXanatos** [comment]
The check box is only showed when sandman is started in portable mode

**Comment by isaak654** [comment]
> The check box is only showed when sandman is started in portable mode

The title bar of sandman says `Sandboxie-Plus v1.0.7 - Portable`, but I still can't see the checkbox.

**Comment by DavidXanatos** [comment]
I have check it its only there when PortableRootDir is not -1

**Comment by DavidXanatos** [comment]
whenn i change it to be always tehre just with the indetermined value?

**Comment by isaak654** [comment]
> I have check it its only there when PortableRootDir is not -1

I have `PortableRootDir=0`, so it's not -1..  this is so confusing.

**Comment by DavidXanatos** [comment]
I'l make it always there in portable mode and check if tehre are any issues to fix with the dispaly
