### ISSUE TITLE
Sandboxie failed to install Foxit Reader

### ISSUE THREAD

**Issue by hitechlover** [sandboxie-plus/Sandboxie#1510]
Dear Developers,

I wanted to try Foxit Reader by installing it inside Sandboxie. However, it crashes towards the end of the installation process. I even checked the Admin rights box but still crashes. 

Please provide a resolution on how to install Foxit Reader without issues. You can download the install file directly from Foxit website and try it yourself.

I am using Sandboxie version 1.0.6 x64.

Thank You,

hitechlover

**Comment by isaak654** [comment]
* Please provide extra details about the installer crash, does it contain a specific error?
* What is your Windows edition and version? Windows 11, 10, etc ? 32 bit or 64 bit ?

**Comment by hitechlover** [comment]
There is no specific Sandboxie error, just installer error. I am using
Windows 10 Pro X64 version 21H1 with latest updates.

You can download the little installer directly from Foxit and test run it
inside Sandboxie and you will see the error message. The installation
process will stalls for about 2 minutes before it proceed, so be patient
with it.

**Comment by isaak654** [comment]
After creating a new sandbox with the default preset, I installed `FoxitPDFReader111_Setup.exe` successfully without receiving any error.

**Comment by Dyras** [comment]
For me it installs, but this window pops up repeatedly every time I close it. Not sure why.
![grafik](https://user-images.githubusercontent.com/12563436/148407272-c033ce1f-e67f-460c-ad93-accfd351db52.png)

**Comment by hitechlover** [comment]
I figured it out what the issue was. I had an older version on my PC. So
when I install the new version within Sandboxie to the default installation
directory of the software, then it failed to install. So I installed it to
a different directory, then the installation was successful without any
issues.

Thanks for looking into the issue guy.

Continue to improve Sandboxie guys. It is a very useful tool to test
unknown or suspicious software. I will support its development whenever I
can.

Please disregard this reported issue and delete this thread since it is no
longer useful.


Thank You
