### ISSUE TITLE
Privacy Enhanced sandbox does not work using installers

### ISSUE THREAD

**Issue by Aholicknight** [sandboxie-plus/Sandboxie#1511]
https://user-images.githubusercontent.com/7843719/148005630-ddd15bd1-ae0a-47df-bf70-62d55e6af8e3.mp4

I am using the Privacy-Enhanced sandbox, and it fails to install steam, while on the yellow one, it works fine. I am using the default configuration, and nothing has been changed or modified.

**Comment by DavidXanatos** [comment]
Please try the pre release 1.0.6 it fixed many issues with privacy mode, but added an other issue with open filders so be carefull

**Comment by Aholicknight** [comment]
Thank you, will be trying this soon
