### ISSUE TITLE
Border Breaks when using DPI Scaling

### ISSUE THREAD

**Issue by DrPleaseRespect** [sandboxie-plus/Sandboxie#1512]
**Describe the problem**
The border doesn't match the window if the window is moved from one screen to another

**To Reproduce**
1. Have 2 Monitors
2. Set the Main Display to have 125% scaling
3. Set the Second Display to 100% scaling
4. Set Sandboxed window border to Always show
5. Start an explorer.exe window and drag the window from the Main Display to the Second Display

**Screenshots**
Main Monitor: [https://i.imgur.com/vMudUMh.png](https://i.imgur.com/vMudUMh.png)
Second Monitor: [https://i.imgur.com/xt2oMIu.png](https://i.imgur.com/xt2oMIu.png)

**Expected behavior**
The Border should match the frame of the window in the second screen

**System details and installed software**
 - Windows 10 Education 21H1 (OS Build 19043.1415)
 - Sandboxie-Plus Version 1.0.6 x64
 - Microsoft Windows Defender
 - Main Screen (1920x1080, Scale=125%)
 - Second Screen (1366x768, Scale=100%)

**Additional context**
I have a custom theme installed using SecureUxTheme

**Sandboxie configuration**
<details>

<summary>My initial sandboxie.ini settings</summary>

```
[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=InternetDownloadManager
Template=7zipShellEx
EnableObjectFiltering=n
EnableWin32kHooks=y

[UserSettings_643E0647]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,2
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=y
ClosePrintSpooler=y
OpenClipboard=n
CopyLimitKb=81920
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices

[Security_Hardened_Sandbox]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#0000ff,on,2
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
BoxNameTitle=y
CopyLimitKb=81920
ClosePrintSpooler=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
```

</details>

**Comment by mysteriously** [comment]
I have DPI set up to 125% on all currently used displays and 100% on laptop screen which is disabled.
Both displays 125% DPI. One display ends exactly when right line ends
https://i.imgur.com/IilIqL2.png
