### ISSUE TITLE
Plex Media Server fails installation

### ISSUE THREAD

**Issue by Nypheena** [sandboxie-plus/Sandboxie#1513]
**Describe the problem**
Plex media server installation fails due to windows installer service not being accessible

**To Reproduce**
https://www.plex.tv/media-server-downloads/#plex-media-server
download the latest version and try to install in a sandbox

**Screenshots**
![image](https://user-images.githubusercontent.com/16083155/148042414-f067ec16-ba7b-4884-a694-827edd7d8056.png)

**Expected behavior**
No error pop up and installing fine

**System details and installed software**
windows 10 pro 2004
sandboxie plus 1.0.5
f-secure

**Sandboxie configuration**
https://gist.githubusercontent.com/Nypheena/66cf82a9735690aafac5c48040d4ec65/raw/4ee06fba4975725c7fe08d5f0c8f86215d208501/gistfile1.txt

**Comment by isaak654** [comment]
Try again by adding `MsiInstallerExemptions=y` to your configuration.

**Comment by Nypheena** [comment]
worked, thank you
