### ISSUE TITLE
Brave now lurks in the sandbox on shutdown, preventing it from being opened again

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#1518]
**Describe the problem**
It might just be my computer preparing itself for a fresh reinstall, but...

For whatever the reason, brave.exe keeps running in a sandbox even if I've closed all open tabs.

**To Reproduce**
1. Force Brave to run inside your sandbox. I'm using the template.
2. Open it
3. Close it
4. See the screenshot

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12563436/148301360-223399c2-39b9-45d5-b06b-e0e41dae106f.png)
^ This is what happens after I've closed all open Brave windows, and disabled "Run Brave in the background" or whatever it says in English in the settings

**Expected behavior**
The last brave.exe should close properly, allowing Brave to be started again. As it is now, the last brave.exe is blocking Brave from opening again

**System details and installed software**
Latest Windows 10
Latest Sandboxie-Plus at the time of writing.

**Additional context**
Seems to happen regardless of what I've tried to get it working. Tried different types of boxes, etc. Even disabled automatic updates.

Tried Brave with v1.0 and it works in that version

**Sandboxie configuration**
Doesn't seem to matter. If you're unable to reproduce, please comment and I will post it.

**Comment by DavidXanatos** [comment]
known issue, will be fixed in next build
use as workaround:


ClosedRT=Windows.UI.Notifications.ToastNotificationManager

**Comment by Dyras** [comment]
Man, do you ever rest or what? :)
