### ISSUE TITLE
Unable to run gradle with OpenJDK17

### ISSUE THREAD

**Issue by worx7kbj** [sandboxie-plus/Sandboxie#1520]
**Describe the problem**
Unable to run gradle with OpenJDK17

**To Reproduce**
1. Install OenJDK17 and git
2. Open Git Bash in a sandbox and `git clone https://github.com/PaperMC/Paper.git&&cd Paper`
3. `./gradlew runDev`

```

* What went wrong:
java.io.IOException: Unable to establish loopback connection
```

**Screenshots**

**Expected behavior**

**System details and installed software**
 - What is your Windows edition and version? Win10 21H1 and Win11
 - What is your current Sandboxie edition and version? Sandboxie Plus 0.7.x to 1.0.x
 - What was your previous Sandboxie version before the update, if any?
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**If you had a compatibility issue or a crash**

**Additional context**

**Sandboxie configuration**

**Comment by worx7kbj** [comment]
Same as https://github.com/sandboxie-plus/Sandboxie/issues/1009

**Comment by worx7kbj** [comment]
Older versions of OpenJDK such as OpenJDK11 do not have this issue

**Comment by worx7kbj** [comment]
I also tried OpenJ9 and Graal versions of jdk17, same result.

**Comment by worx7kbj** [comment]
Sandboxie Plus versions from 0.7.5 to 1.0.5 all have this issue

**Comment by worx7kbj** [comment]
I tried some possible solutions such as enabling NetShare and removing network restrictions, none of which works

**Comment by worx7kbj** [comment]
> I also tried OpenJ9 and Graal versions of jdk17, same result.

Also Microsoft's builds of OpenJDK

**Comment by DavidXanatos** [comment]
please try adding 
```
OpenFilePath=*\Temp\socket_*
```
to the sandbox and let me know if it fixed the issue
