### ISSUE TITLE
Unable to play Minecraft 1.18.1 locally in a sandbox

### ISSUE THREAD

**Issue by worx7kbj** [sandboxie-plus/Sandboxie#1521]
**Describe the problem**
You can't start Minecraft 1.17.x to 1.18.x single player or server in a sandbox

**To Reproduce**

1. Install vanilla Minecraft
2. Play
3. See the error

**Screenshots**

**Expected behavior**

**System details and installed software**
 - What is your Windows edition and version? (e.g. Windows 10 Pro 20H2 64-bit) Win10 21H1 and Win11
 - What is your current Sandboxie edition and version? (e.g. Sandboxie Plus 0.9.6 64-bit) Sandboxie Plus 0.7.x to 1.0.x
 - What was your previous Sandboxie version before the update, if any?
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**If you had a compatibility issue or a crash**

**Additional context**

Maybe related to https://github.com/sandboxie-plus/Sandboxie/issues/1520

**Sandboxie configuration**

**Comment by worx7kbj** [comment]
> Maybe related to #1520

These two issues are both about loopback connection.

**Comment by worx7kbj** [comment]
Newer versions of minecraft require java16+
Those minecraft versions that support java 11 do not have this issue if you use java 11 to run them

**Comment by worx7kbj** [comment]
> Those minecraft versions that support java 11 do not have this issue if you use java 11 to run them
But older minecraft versions such as 1.16.5 also have this issue if you run them on java 16+

**Comment by DRB02** [comment]
Adding to this. Gave the program access to %appdata%. Get the error message "failed to open a new selector" when trying to play minecraft online or world. According to the internet the issue means it can't reach some files. Also it takes 4 minutes just to launch the launcher.

**Comment by worx7kbj** [comment]
> Adding to this. Gave the program access to %appdata%. Get the error message "failed to open a new selector" when trying to play minecraft online or world. According to the internet the issue means it can't reach some files. Also it takes 4 minutes just to launch the launcher.

I get the same error message "failed to open a new selector"

**Comment by DavidXanatos** [comment]
please try adding 
```
OpenFilePath=*\Temp\socket_*
```
to the sandbox and let me know if it fixed the issue

**Comment by DRB02** [comment]
it worked for me. Thank you so much!

**Comment by DavidXanatos** [comment]
And its getting better with the next build you will no longer need that workaround,
I'm adding propper support for this: https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
that is what caused the issue.

**Comment by DRB02** [comment]
Hello David,
I wanted to start using sandboxie plus again.

But I launch minecraft, it shows running in the sandboxie list.
But then the screen doesn't pop-up. 

I revisited this issue, but that temporary fix doesn't work.

**Comment by DRB02** [comment]
for some reason the issue is that it just takes incredibly long to startup.

I ran it to give it another try. Forgot about it and ~30 minutes later the screen popped up.

**Comment by isaak654** [comment]
> for some reason the issue is that it just takes incredibly long to startup.
> 
> I ran it to give it another try. Forgot about it and ~30 minutes later the screen popped up.

Another issue is required for it.
