### ISSUE TITLE
FakeAdminRights=y not working with Sandboxie-Classic 5.55.5

### ISSUE THREAD

**Issue by RadarNyan** [sandboxie-plus/Sandboxie#1522]
**Describe the problem**
With FakeAdminRights=y added to ini file (under [Test] section, just below DropAdminRights=y) installers still fail to run. Confirmed config file has been reloaded.

**Screenshots**
![SnapCrab_NoName_2022-1-6_18-29-0_No-00](https://user-images.githubusercontent.com/2091529/148361981-43d43625-31d3-4a78-88b2-e58b3bcd7aec.png)

**Additional context**
I've tried 3 different installers, none of them worked. It's not like I need this feature, I'm used to just install the application with admin rights, then enable "Drop rights" afterwards. Just saw this option is mentioned in the settings page and I decided to give it a try and found it doesn't do anything.

**Comment by DavidXanatos** [comment]
For me that works, perhaps try yet an other installer, for example 7zip is known to work.
If that fails for you its something with your config,if that works, let me know which installers you tried and failed, possibly some more hacks for the fake admin option are in order.

**Comment by RadarNyan** [comment]
Just tried 7-zip and it doesn't work either

```html
---------------------------
Sandboxie Start
---------------------------
Could not invoke program:



"C:\Test\7z2107-x64.exe"

System Error Code:

The operation was canceled by the user.

 (1223)
---------------------------
OK   
---------------------------
```
```html
SBIE2217 Request to run as Administrator was denied due to dropped rights
SBIE2219 Request was issued by program Start.exe [Test]
SBIE2220 To permit use of Administrator privileges, please double-click on this message line
```

My config files is basically the default:
```ini
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
Template=7zipShellEx
Template=WacomTablet

[Test]
Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
DropAdminRights=y
FakeAdminRights=y
```

**Comment by DavidXanatos** [comment]
hmm... interesting.... in my test system it works fine even with your config... 
what exact version of sandboxie are you using
It may be related to you using windows 7 as far as i see on from the screenshot,
I'm testing on 10 I'll test the functionality on win 7 perhaps this old platform requires some other workaround.

**Comment by DavidXanatos** [comment]
Yea its a windows 7 issue, I will check it out what workaround is there required...
