### ISSUE TITLE
Ukrainian language is missing from Plus UI

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1527]
**Describe the problem**
The new merged Ukrainian language is missing from Plus UI.

**Screenshot**
![Ukrainian_language](https://user-images.githubusercontent.com/12372772/148570366-f4faa79a-7217-4af7-881b-e80eb4857994.png)

**Expected behavior**
It's supposed to be selectable from the Plus UI.
Sandboxie Plus 1.0.6 / 1.0.7 x64

**Comment by DavidXanatos** [comment]
lang code for Ukrainian is uk not ua fix commited
