### ISSUE TITLE
[v5.55.7] ReadFilePath no longer works

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#1529]
I have updated from version 5.53.3 to 5.55.7. Unfortunately, however, allowing a network directory with ReadFilePath no longer works.

Network access is prevented by BlockNetworkFiles=y. Using ReadFilePath, I have always been able to allow read-only access to a network directory. This no longer works now. If OpenFilePath is used instead, access works again, but then there are also write permissions.

**Edit:** What I noticed:
With OpenFilePath: Access works.
With ReadFilePath: No access, file dialog reports missing permissions.
Without OpenFilePath/ReadFilePath: No access, file dialog reports drive not available.
Maybe this helps to analyze the problem?

**Comment by DavidXanatos** [comment]
So to clarify:
1. were you able to bypass BlockNetworkFiles=y with ReadFilePath, i.e. have BlockNetworkFiles=y and yet still access to network files?
2. are we talking about unc paths \\server\share\some_folder or mounted network drivers?

**Comment by isaak654** [comment]
According to [this reply](https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic01d901d9.html?f=58&t=23084&p=122440#p122418), BlockNetworkFiles blocks all network files except those you specifically open (for reading or writing).

**Comment by DavidXanatos** [comment]
hmm... indeed... it would seam so, yea I'll have to fix this the new rule specificity system did not take this into account I just took it at face value block -> block everything

**Comment by isaak654** [comment]
So this is the only question left that would need a confirmation:
> 2\. are we talking about unc paths \server\share\some_folder or mounted network drives?

**Comment by DavidXanatos** [comment]
The issue will be fixed in the next build,
and improved,
you will now also be able to allow specific network paths with the NormalFilePath= directive which means writes to these locations will be captured in the sandboxed.

**Comment by isaak654** [comment]
I'm not sure this is completely fixed, I just extracted the latest CI build and used `ReadFilePath=\\VBoxSvr\folder` in a clean new sandbox (with the default preset) and I got the missing permissions error reported in OP:

> With ReadFilePath: No access, file dialog reports missing permissions.

**Comment by isaak654** [comment]
I'm not sure this is completely fixed, I just extracted the latest CI build, used `ReadFilePath=\\VBoxSvr\folder` in a clean new sandbox (with the default preset) and I got the missing permissions error reported in OP:

> With ReadFilePath: No access, file dialog reports missing permissions.

**Comment by DavidXanatos** [comment]
Strange for me this test passes, please test again with a real share, its possible that the virtual box stuff is internally a different device or something

**Comment by isaak654** [comment]
@DavidXanatos 
The weirdest thing here is that I can actually see my real network shares in Windows Explorer on the same VM, but I'm not able to see them inside a sandboxed Windows Explorer... I really don't know why this happens.

**Comment by APMichael** [comment]
> The issue will be fixed in the next build and improved, ...

Thank you for the quick reply. Great news that it will be fixed in the next build.

> 2. are we talking about unc paths \server\share\some_folder or mounted network drives?

The required network drive is mapped/mounted to a drive letter using "net use" (e.g. drive letter "Z:", ReadFilePath would then be "ReadFilePath=Z:\\").

@isaak654 Thank you also for the help.

**Comment by APMichael** [comment]
I can confirm that the issue has been fixed with the new version 5.55.8. Thanks again! 👍
