### ISSUE TITLE
Vivaldi (browser) can't save bookmarks anymore.

### ISSUE THREAD

**Issue by Julikus** [sandboxie-plus/Sandboxie#153]
Vivaldi can't save bookmarks anymore. Settings are set: "applications -> browsers -> Vivaldi [did same for Chrome] -> allow direkt access to Bookmarks".
If I add the path "%Local AppData%\Vivaldi\User Data\Default\" in "Resource Access -> File Access -> Direct Access" I am able to save bookmarks. 
But this is a big hole and allows everything to be saved (history, cookies, etc.).

I need some guidance to solve the issue.

**Comment by Deadite333** [comment]
Same here. 

Both methods, using the template or manually adding bookmarks don't work. 

Only the entire profile folder or - slightly more secure - "Default" folder will do the trick, not recommended for obvious reasons. 

Hopefully the next update will fix the issue, nothing a user can do.

**Comment by DavidXanatos** [comment]
Is that issue Vivaldi specific or happens to  other chrome derivates to?

**Comment by Deadite333** [comment]
Hi and thx for answering.

I've just tried Edge (Chromium version), added bookmarks via Direct Access, and yep, bookmarks/favorites don't get saved there either.

**Comment by bjm234** [comment]
> Hi and thx for answering.
> 
> I've just tried Edge (Chromium version), added bookmarks via Direct Access, and yep, bookmarks/favorites don't get saved there either.

Yes, 
used to work

**Comment by Julikus** [comment]
Good to hear that I am not the only one with this issue. I hope you can fix it soon.
Unfortunately sandboxie is without this function worthless to me. :-(

**Comment by Julikus** [comment]
> It's a possibility to still add Default to Direct Access and then relevant files and folders from Default to Read-Only Access.
> 
> Greatly reduces what would hit the drive, instead of several MB it's only some kB. Bookmarks can now be handled, and the exposure left is tolarable (to me at least, under the circumstances) compared to the inconvenience of not being able to save or delete bookmarks from within Sandboxie .

That doesn't work for me. My Vivaldi won't start if I set "Default" to "Direct Access" and partial to "Read-Only Access".
Precisely if I add the file(s) "History", "Login Data", "Cookies", etc. to "Read-Only Access" the Vivaldi-Window won't show up just for a second. 

My only choices are: 
add "Default" to "Direct Access" (so using sandboxie makes no sense)
or:
to use sandboxie with standard config (nothing will be saved: no bookmarks, no cookies, no login, etc.).
Browsing without bookmarks is like browsing with Alzheimer's disease: you can't remember anything after <5 hours.

**Comment by DavidXanatos** [comment]
I found the issue it was a bug introduced with one of the driver verifier fixes and affects file renaming.

Chrome and derivatives create a temporary bookmark file and than rename it to its target name which is white listed in the ini, this renaming operation failed.

The issue is resolved in builds 0.4.4 / 5.43.7 and later (which are to be released soon), until than a workaround could be to allow chrome access to the entire chrome profile folder i.e. using
OpenFilePath=chrome.exe,%Local AppData%\Google\Chrome\User Data\Default\*

**Comment by Julikus** [comment]
Thank you very much!
