### ISSUE TITLE
I can translate to Czech language if needed

### ISSUE THREAD

**Issue by exander77** [sandboxie-plus/Sandboxie#1530]
Could be useful for other Czech users.

**Comment by isaak654** [comment]
See [Localization notes and tips](https://github.com/sandboxie-plus/Sandboxie/discussions/1123#discussioncomment-1203489) if you need further details.

**Comment by exander77** [comment]
@isaak654 Will look into that.

**Comment by DavidXanatos** [comment]
here is the new cz translation file start with: https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_cs.ts

**Comment by DavidXanatos** [comment]
Will we have a Cz translation ready lets say for a release on monday?

**Comment by exander77** [comment]
@DavidXanatos I started working on it, but it's pretty long. :D I actually Kickstarter it by writing a script that passed to Google translate to speed it up. But there is a lot of corrections to be done. Will inform you tomorrow evening how is it going.

**Comment by exander77** [comment]
@DavidXanatos Will most likely make it for Monday. But there will be updates in the future, I am translating it kind of blind and I don't know where all the text are in the app.

Also, why is there sometimes just a box instead of sandbox?

**Comment by isaak654** [comment]
> But there will be updates in the future

There is little more than 10 new entries in the new release, but you'll see them only when `sandman_cs.ts` will be properly enabled for the release. The most important thing is to translate all Plus installer entries in `Languages.iss`.

**Comment by exander77** [comment]
@exander77 I meant it in a way, that when I see it in the actual app, I may decide to change translations of several items. So there will be an update from me. I don't think I can make it "perfect" on a blind attempt.

**Comment by isaak654** [comment]
You can create a new pull request anytime with the updated file(s), otherwise you could attach the updated file(s) here and someone will create a pull request for you.

**Comment by exander77** [comment]
I will make a pull for initial and all updates, no issue.

**Comment by exander77** [comment]
Work in progress. The second half has much larger texts and more corrections, but I would assume to have it done before the next release.

**Comment by DavidXanatos** [comment]
next release may be monday will it be ready in time

**Comment by isaak654** [comment]
@exander77 Any news?

**Comment by bastik-1001** [comment]
While I have not used it myself, there is a [weblate instance](https://weblate.xanasoft.com/projects/sandboxie-plus/) that might be useful to crowdsource the effort of translating Sandboxie into other languages.
