### ISSUE TITLE
add option to choose different file system root directory for each sandbox

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1531]
add option so we can specify different root location for each sandbox

**Comment by Dyras** [comment]
You can actually. Just not in the GUI.
Example:
[DefaultBox]
Enabled=y
ConfigLevel=9
**FileRootPath=D:\Sandboxes\DefaultBox**

**Comment by diieg707** [comment]
> You can actually. Just not in the GUI. Example: [DefaultBox] Enabled=y ConfigLevel=9 **FileRootPath=D:\Sandboxes\DefaultBox**

Thank you, an option in the GUI would be more handy though

**Comment by isaak654** [comment]
> > You can actually. Just not in the GUI. Example: [DefaultBox] Enabled=y ConfigLevel=9 **FileRootPath=D:\Sandboxes\DefaultBox**
> 
> Thank you, an option in the GUI would be more handy though

I would prefer not if it could potentially introduce new bugs. For example, a similar GUI setting should also prevent to set that option if there is already an existing one on the [GlobalSettings] section.

**Comment by diieg707** [comment]
> > > You can actually. Just not in the GUI. Example: [DefaultBox] Enabled=y ConfigLevel=9 **FileRootPath=D:\Sandboxes\DefaultBox**
> > 
> > 
> > Thank you, an option in the GUI would be more handy though
> 
> I would prefer to avoid it if it could potentially introduce new bugs. For example, a similar GUI setting should also prevent to set that option if there is already an existing one on the [GlobalSettings] section.

i have a suggestion for that:
add a grayed out field containing global location
below add a checkbox and leave it marked by default on "use global root directory location"

whenever se unmark the checkbox the text field would become active for us to put the new location.

![2022-01-09 15_21_32-Free Online PDF Creator _ Create PDF Online with Soda PDF Online - Chromium](https://user-images.githubusercontent.com/54504707/148695331-82c64963-48e7-43ec-8e10-c6ddfccec235.png)

that would be an easy design to everybody understand.

**Comment by DavidXanatos** [comment]
I see a much bigger issue: Users that change the dir and forget to move the files inside to that location.
I mean we could 
a. disable the ability to change this option when the box is not empty
or
b. add the mechanism to move the files, but that's potentially a lot fo work as we need to handle the case of what when the move breaks or the user aborts it or the pc reboots, or something...

Deleting sandbox no problem, just delete again
taking/restoring snapshots, moving folders on the same drive only takes seconds

but moving a box to an arbitrary location can be from hdd1 to hdd2 and that takes time.

How do we handle the case when the operation does not complete?

**Comment by diieg707** [comment]
> disable the ability to chang

i think for now option a would be enough, as option b would take a lot of work.

**Comment by typpos** [comment]
Remember: when you copy a sandbox that you configured with a FIXED path, then both sandboxes point at the SAME path. Probably not what you wanted.

Ideally, sandboxie should warn the user if %SANDBOX% is not part of the file root path. Same for registry & IPC paths.

**Comment by DavidXanatos** [comment]
oh thats a good point so when copying we would need to have a setting filter that removed the entry and resets for the duplicate back to the default

**Comment by DavidXanatos** [comment]
the next build will remove the FileRootPath config it it do not contain %SANDBOX%

**Comment by DavidXanatos** [comment]
@xsmolasses why the down vote? having t boxes pointing to the same fodler is asking for trouble, removing this value is a safety measure.

I could add an option to choose a non standard root directory when creating a box from scratch.
That in combination with the auto removal of FileRootPath  on duplication should be safe enough

**Comment by xsmolasses** [comment]
> @xsmolasses why the down vote? having t boxes pointing to the same fodler is asking for trouble, removing this value is a safety measure.
> 
> I could add an option to choose a non standard root directory when creating a box from scratch. That in combination with the auto removal of FileRootPath on duplication should be safe enough

Only on duplication encountered? Oh, then my misunderstanding, but still there might conceivably exist a scenario where I would like two or more different configs for one root Sandbox "installation" of files.

Enforcement is not ideal for [my] organising of a directory (plus grouping in gui) tree.
```
[Game_Command_n_Conquer]
FileRootPath=C:\Games\%SANDBOX%
# means C:\Games\Game_Command_n_Conquer
# it's yuck!
# preference
FileRootPath=C:\Games\Command_n_Conquer
```
If not settled on leaving it at a stopgap, then perhaps, and I don't think I'm suggesting something too convoluted (i.e., keep an extra member variable and add supporting code), that is to propose, that when parsing the ini, allow directory separators (and almost any character for that matter) for Sandbox names and use in ini [section], expanded %SANDBOX%, and the gui. For internal use, "flatten" [Game\Command & Conquer] with underscores.

**Comment by DavidXanatos** [comment]
> ... , but still there might conceivably exist a scenario where I would like two or more different configs for one root Sandbox "installation" of files.
>

You can have this, the FileRootPath preset is only removed when duplicating a sandbox and it does not contain %SANDBOX%, from the duplicate, the original isn't altered and if you by hand manufacture a conflict it will stay
