### ISSUE TITLE
Application failure - "Service Not Implemented: CreateDesktop"

### ISSUE THREAD

**Issue by wwilsonn91** [sandboxie-plus/Sandboxie#1536]
Application's failing to start, or showing the splash then promptly crashing - both events give the same error.
![Sandboxie - EVE](https://user-images.githubusercontent.com/78976418/148877649-7303a46b-c98c-43dd-85ad-1c6a6cc7fa84.png)

**Comment by hg421** [comment]
See #1442 and check if the option "Emulate sandboxed window station for all processes" resolves it. That option is also enabled by default on the latest version (1.0.7).

**Comment by wwilsonn91** [comment]
> See #1442 and check if the option "Emulate sandboxed window station for all processes" resolves it. That option is also enabled by default on the latest version (1.0.7).

That fixed it. Thank you.
