### ISSUE TITLE
Discord hardware acceleration

### ISSUE THREAD

**Issue by Foosec** [sandboxie-plus/Sandboxie#1538]
**Describe the problem**
Discord seems to run without hardware acceleration, it is very laggy with animations.
I can also see in nvidia activity, that discord is not running on the dedi gpu.

**To Reproduce**
Install and run discord in sandbox

**Expected behavior**
Discord to run with hardware acceleration, like firefox does. 

**System details and installed software**
 - Windows 10 pro Version 10.0.19043 Build 19043
 - Current: Sandboxie-plus 1.0.7 64 bit
 - Previous: Sandboxie-plus 10.5 64 bit
 - Eset antivirus

**Sandboxie configuration**
If applicable, consider to attach your Sandboxie.ini configuration by copying the content on https://gist.github.com and sharing the resulting link. If you decide to paste the configuration here, make sure to use the backticks around strings, like in this working example:

<details>

<summary>ini for this sandbox</summary>

```
Enabled=y
AutoRecover=n
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=Firefox_Addon_Zotero
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
CopyLimitKb=81920
UseRuleSpecificity=y
UsePrivacyMode=y
ClosePrintSpooler=y
OpenWinClass=#
BoxNameTitle=-



```

</details>

**Comment by DavidXanatos** [comment]
please try if adding AlwaysUseWin32kHooks=y to your sandboxie in i resolves the issue

**Comment by Foosec** [comment]
> please try if adding AlwaysUseWin32kHooks=y to your sandboxie in i resolves the issue

Was not able to test this, i've since done a complete windows reinstall and it seems to work without issue now.
