### ISSUE TITLE
Unable to test supporter only features.

### ISSUE THREAD

**Issue by ThelsK** [sandboxie-plus/Sandboxie#1539]
I'm running a PC with 2 monitors, 2 keyboards, 2 mice and 2 sound devices. The idea is to use the PC as 2 workstations to be used by 2 different users.

I'm using Aster to split the devices into 2 workstations, which mostly works fine. However, since it's effectively still the same OS with shared processes, I cannot open Steam on both workstations at the same time. Sandboxie is generally recommended as the workaround.

Running Steam natively on one workstation, and opening Sandboxie Plus to run Steam inside a Sandbox on the other workstation does work and allows both workstations to run Steam (though the one running Steam in the Sandbox has to log in every time).

However, some games provide an error when run through the Sandboxed Steam: WerFault.exe: SBIE2101 Objectname not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1

I wanted to see if the less secure policy does allow me to run such games, so I created a new box and chose Applicationcompartment (NO isolation) as the box type. It gives me a warning that the sandbox gets terminated after 5 minutes. That is fine. I can just run it and test if it works in those 5 minutes.

However, when I try to do so, I get a lot of "The selected boxconfiguration is not allowed.", effectively preventing me from testing and seeing if the less secure box solves the issue for me or not.

**Comment by ThelsK** [comment]
It's not the problem that the messages show up there. The problem is that I can't properly test if that functionality solves my problem with some of the games...

If it would simply work unrestricted for five minutes, and then terminate the process after those five minutes, I would know "Okay, this way, Sandboxie Plus solves my issue, and I can get a license to remove the 5 minute limit" or "Nope, this way it still doesn't work, time to look for a different program."

Also, sidenote, is there a guide for settings for Steam, and/or a Discord community server to discuss with fellow users?

**Comment by DavidXanatos** [comment]
> If it would simply work unrestricted for five minutes, and then terminate the process after those five minutes
> 

this is exactly what it does + posting that message on every process start, 
the "The selected boxconfiguration is not allowed." the message is only a message it does not terminate anything.

Your stream issue is probably related to IPC isolation, which you need ti disable separately

**Comment by ThelsK** [comment]
Ah, if that's the case, then it would help to word that a little more clearly. Unfortunately that means it's not solving my issue here.

How would I disable the IPC isolation separately?

**Comment by ThelsK** [comment]
> > it would help to word that a little more clearly.
> 
> Do you have a specific suggestion?

Either not mention the message at all, because the user already opted into a Trial only option, or something like "The selected boxconfiguration includes Trial features. For prolonged use, please consider supporting this project."

**Comment by isaak654** [comment]
> > > it would help to word that a little more clearly.
> > 
> > 
> > Do you have a specific suggestion?
> 
> Either not mention the message at all, because the user already opted into a Trial only option, or something like "The selected boxconfiguration includes Trial features. For prolonged use, please consider supporting this project."

A similar change will be included in the next release:
https://github.com/sandboxie-plus/Sandboxie/commit/d5a68170694382029fa1856cd070b5262e2fd6c8#diff-d7d583c391d8b7aa28609e54893ae147b9720faa68f79bc13e9ff41f510cddec

**Comment by ThelsK** [comment]
> > > > it would help to word that a little more clearly.
> > > 
> > > 
> > > Do you have a specific suggestion?
> > 
> > 
> > Either not mention the message at all, because the user already opted into a Trial only option, or something like "The selected boxconfiguration includes Trial features. For prolonged use, please consider supporting this project."
> 
> A similar change will be included in the next release: [d5a6817#diff-d7d583c391d8b7aa28609e54893ae147b9720faa68f79bc13e9ff41f510cddec](https://github.com/sandboxie-plus/Sandboxie/commit/d5a68170694382029fa1856cd070b5262e2fd6c8#diff-d7d583c391d8b7aa28609e54893ae147b9720faa68f79bc13e9ff41f510cddec)

I like the way that's worded. It makes it a lot more obvious what's going on! :)

**Comment by DavidXanatos** [comment]
the wording will be changed to "The configuration %3 of box %2 requires a supporter certificate. Processes in this box will be terminated after 5 minutes. For prolonged use, please consider supporting this project." in the next build
