### ISSUE TITLE
SbieCtrl does not start with the sandboxed app

### ISSUE THREAD

**Issue by GH01** [sandboxie-plus/Sandboxie#154]
Usually I use Sandboxie this way:
Enable the option: Start Sandboxie Control When a program starts in the sandbox.
Stop SbieSvc, but set it to "Demand start".
Run an app in a sandbox via shell/SendTo menu (with Sandboxie command line options).
Starting Sandboxie this way will start both SbieSvc and SbieCtrl.

Everything worked fine with v5.40 or earlier.

Now I updated from 5.40 to 5.43.6.
I think there's something broken:
When running an app in a sandbox via shell/SendTo menu, SbieSvc does start, but SbieCtrl does NOT.
So I don't have Sandboxie's tray icon, can't open Sandboxie's main window. And the window of the sandboxed app has no color border...

Win 7 x86.

**Comment by NewKidOnTheBlock** [comment]
Looks like a duplicate of issue #135

**Comment by GH01** [comment]
> Looks like a duplicate of issue #135

Thank you.
Let's await the fix.

**Comment by NewKidOnTheBlock** [comment]
I've pulled one myself -> issue #152 
Is there any way to merge or attach a duplicate issue with #135 ?

**Comment by GH01** [comment]
Two threads will be automatically linked to each other if one is mentioned in the other.

If you think there's still something that needs to be stressed/attached, you can mention/link it in #-135.

For me, #-135 ( + the dev's comment in your thread #-152 ) is enough for this minor issue. So I closed mine.
(And here I'm preventing from re-mentioning them again.)
