### ISSUE TITLE
Remove Sandbox should warn it deletes the contents

### ISSUE THREAD

**Issue by 01yakiek** [sandboxie-plus/Sandboxie#1546]
As of writing this, using Sandboxie-Plus v1.0.7 Portable, not classic.

Jesus Christ I've nearly ripped my hair off twice because right clicking the sandbox to remove sandbox actually deletes the entire sandbox contents from the disc -- without the ability to recover it! It doesn't get moved to recycle bin.

I'm only thankful I didn't pull my entire scalp off because I had a backup for second event, the first event was the most desperate moment as I had to use file recovery software to recover some bits, I had no backup.

Please for the love of god, add a warning or split the Remove Sandbox into two, like maybe one is just remove sandbox without deleting contents, another remove sandbox and delete contents -- and also add warning to them for double take.

Thank you.

**Comment by isaak654** [comment]
There is already a warning, I don't think it's convenient to add another warning.
In my opinion, it would be better to add a new entry at the bottom like:
"Note: in this way, the content will also be deleted!"

**Comment by 01yakiek** [comment]
@isaak654
You mean, this?

![2022-01-16_03 33 34_Sunday](https://user-images.githubusercontent.com/7377351/149635496-d257bfb7-f06f-4136-b94d-8aceac67387b.png)

Because I just tested again and this is all it says.
Remove sandbox does not mean delete contents. We're having an ambiguous situation here.

Remove sandbox could mean remove sandbox from the list, but not delete contents. Some users, well, in this case me, thinks it this way for some reason. I find it frustrating that there are applications that get this mixed up and ends up causing users to lose their files because of this mistake.

For example in Clip Studio, where there is a Work tab that keep tracks of files opened. The stupid thing is that it's just like Sandboxie-Plus, removing the item on the list means deleting the files. There is no way to clear the list without ending up deleting the file.

To only way to avoid deleting the contents while deleting the list is to rename the folders on the file system, then delete the list, then rename it back to original. This is utterly ridiculous.

Thank you.

**Comment by DavidXanatos** [comment]
hmm... okay.... 
well leaving files behind if box is removed is bad as people may not explore their box folder and accumulate a lot of junk
the old sandboxie just said that you cant remove the box as long as its not emptied.

So warning message ? or a second message box saing that to remove box some:name its content must be deleted, ok, cancel
???

**Comment by isaak654** [comment]
> This is why I proposed splitting the Remove Sandbox into two; one for remove sandbox and its contents. Another is just remove it from the list within Sandman.exe.

Personally I wouldn't like to see a second warning after an existing one, possibly other users too.

**Comment by 01yakiek** [comment]
@DavidXanatos 
Yes, that's the idea, I think that works too.

The second confirmation should be "Yes / No" instead of "Ok / Cancel".

Because "Ok / Cancel" causes the ambiguity of whether if the cancel actually cancelling the entire process of Remove Sandbox, or it just cancels the delete contents part.

Also, I noticed Renaming files also renames the folders on the file system. But I suppose we can let that go as it's less severe than Remove Sandbox.

Thank you.

**Comment by DavidXanatos** [comment]
I don't really see why some one would want to remove the box but keep the files in their original location.
There is always the option to move the box dir to some ware else and then remove the box.

I think a warning like @isaak654 suggested is enough to avoid accidental deletion.

![grafik](https://user-images.githubusercontent.com/3890945/149635944-7a2da10c-2e29-4262-aa43-f6fab6146106.png)

About the recycle bin I'm not sure how well this would work, ...

**Comment by 01yakiek** [comment]
@DavidXanatos 
Yeah for the move to recycle bin solution causes a new problem; What if the Sandbox folders are in portable drives or some places that doesn't does not have Recycle Bin functionality? And what if the contents of the folder is too big to move to Recycle Bin?

I think the Recycle Bin solution won't work.

**Comment by 01yakiek** [comment]
Hang on... There is a bit of miscommunication here.

What I meant by "Yes / No / Cancel" is that these has different operations to them.

- Yes: Deletes the contents.
- No: Do not delete the content, but proceed to delete the selected sandbox from the list.
- Cancel: Cancel entire operation. In other words, do not delete the selected sandboxes from the list, and do not delete the contents either.

So the message should be more clear to avoid ambiguity as well;

"You've confirmed to delete the selected Sandbox(es). Do you want to delete the contents as well? (Choose Cancel to cancel everything)"

Or something similar.

Thank you.

**Comment by mysteriously** [comment]
Maybe just checkbox: [x] Delete Sandbox files
