### ISSUE TITLE
Yellow border in applications running outside the Sandboxie

### ISSUE THREAD

**Issue by Ponywka** [sandboxie-plus/Sandboxie#1547]
**Describe the problem**
Yellow border in applications that have a PID that was previously launched by the application via the Sandboxie

**To Reproduce**
1. Open any application via Sandboxie
2. Close it
3. Try open any other application until the PID matches 

**Screenshots**
![SandMan_H92B9t51NY](https://user-images.githubusercontent.com/26777464/149638512-b948d67e-1b98-44b3-8bb4-fe356fa3c746.png)

**Expected behavior**
The yellow border should not appear on PID applications that have been terminated. 

**System details and installed software**
Windows 10 Pro 21H1 (19043.1466)
Sandboxie-Plus v0.9.8d

**Sandboxie configuration**
https://gist.github.com/Ponywka/774ab1f6687c7a9a3be98b46f44b86b9

**Comment by Ponywka** [comment]
Also you can see the bug here:
https://user-images.githubusercontent.com/26777464/149638775-4e62141c-bf47-491a-9815-a29986655aad.mp4

**Comment by isaak654** [comment]
A fix about reused process IDs is listed on Plus 1.0.7 changelog:
`- fixed SandMan issue with reused process IDs`

Could you verify if your issue happens there too?

**Comment by DavidXanatos** [comment]
no that was an otehr issue, this one I just fixed for the 1.0.8 release
