### ISSUE TITLE
Firefox 97.0b4 x64 crashed with 5.55.6-5.55.7-1.0.8 x64 test build (but it works with 5.55.5)

### ISSUE THREAD

**Issue by p0sapiano** [sandboxie-plus/Sandboxie#1548]
Hi.
Windows 10 64-bit 21h2
Firefox 97b3
Sandboxie Classic 5.55.7
Firefox 97 carshed in sandbox, and 5.53.3 no problem.

**Comment by isaak654** [comment]
It would be useful if you could downgrade to each previous version (5.55.6, 5.55.5 until reaching 5.55.0) in order to know which version introduced the issue for you.

**Comment by p0sapiano** [comment]
> It would be useful if you could downgrade to each previous version (5.55.6, 5.55.5 until reaching 5.55.0) in order to know which version introduced the issue for you.

5.55.6

**Comment by isaak654** [comment]
Just tried [Firefox 97b4](https://www.mozilla.org/en-US/firefox/all/#product-desktop-beta), it looks incompatible with Sandboxie 5.55.7 x64 and also with Plus 1.0.8 x64 test build. 
Windows 10 20H2 x64 clean install.

**Comment by isaak654** [comment]
This is fixed for me in the 1.0.8 final build.
