### ISSUE TITLE
How to use Supporter certificate?

### ISSUE THREAD

**Issue by wgetnz** [sandboxie-plus/Sandboxie#1549]
I bought a Supporter certificate but I can't find any place to enter activation in the program, how can I use the Supporter certificate?

**Comment by isaak654** [comment]
Options menu -> Global Settings -> Support (left side)

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/149669859-d20d9c6e-f82c-43dc-a5e6-9ef8f8fb66de.png)
