### ISSUE TITLE
Failed to install WPS Office!

### ISSUE THREAD

**Issue by hitechlover** [sandboxie-plus/Sandboxie#1550]
Dear Developer,

Sandboxie Plus failed to install the latest WPS Office. It just crashes without any error message. Please fix this crash issue.

Steps to reproduce:
1. Go to wps.com
2. Click on "Offline Installer" and download it
3. Install it inside Sandboxie using default settings
4. The install then crashes without any error message

My system:
-Windows 10 Pro 21H1
-Sandboxie-plus version 1.0.6.0 X64

Best Regards

**Comment by isaak654** [comment]
I received the following message with Sandboxie Classic 5.55.7 x64 at the end of WPS Office installation: 

> SBIE2205 - Service not Implemented: NtRenameKey

I think it's related to the missing renaming support of registry keys: #205
However I was still able to run WPS Office after install (without crash).

**Comment by hitechlover** [comment]
Can you fix the issue for Sandboxie Plus? I don't like the classic user
interface and I don't want to use it. Modern UI is the way to go.

**Comment by isaak654** [comment]
> Can you fix the issue for Sandboxie Plus? I don't like the classic user interface and I don't want to use it. Modern UI is the way to go.

I tested Plus 1.0.7 too, but I didn't find any difference with the Classic behavior I mentioned before.
No crash with both editions in the same machine, just a small NtRenameKey warning that can be skipped.

**Comment by hitechlover** [comment]
Hmm. I have the older WPS Office version installed on my PC. I test
installed the newer version inside Sandboxie Plus. Maybe the pre-existing
WPS Office causes the installation inside Sandboxie to crash. Maybe I need
to uninstall the older version first which might fix the installation crash.

Since this works on your end, then it is not a bug.

Please delete this thread since it is not a bug.

Thanks for your help.
