### ISSUE TITLE
Windows "Compatibility Settings" are loaded from outside the sandbox

### ISSUE THREAD

**Issue by divinity76** [sandboxie-plus/Sandboxie#1552]
**Describe the problem**
the "Compatibility settings" set inside the sandbox are ignored, when a program is started, the compatibility settings from outside the sandbox are applied.

**To Reproduce**
try starting "Yu-Gi-Oh! Power of Chaos: Joey the Passion" inside a sandbox, notice it refuse to go fullscreen, even when enabling the fullscreen option in settings. then set the "Run this program in compatibility mode for: Windows XP (Service Pack 2)" setting inside the sandbox (inside explorer.exe running in a sandbox) and restart the game. there's no difference, nothing happens. 

Then try setting the same setting *outside* the sandbox, and restart the game again inside the sandbox. this time the "fullscreen" option works, because now it's actually running in XP-SP2 compat mode. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1874996/149756343-337b563e-c453-4e37-a66d-709450700fa5.png)

**Expected behavior**
in-sandbox settings should be applied

**System details and installed software**
 - Windows 10 "version 2004", cmd version string 10.0.19041.1415
 - Sandboxie Plus 1.0.7 64-bit
 - i think this bug bas been around for a long time, i remember having this issue in Windows 7 playing Metal Fatigue, several years ago.. i think this issue was still present back in the 2013 - 2017 Invincea times
 - running standard-issue Microsoft Defender antivirus..

**Comment by DavidXanatos** [comment]
well the sandbox does what it should do:
it blocks the explorer.exe inside the sandbox from chaging system settings outside the sandbox.
Windows's compatibility engine is an unsandboxed component, so its oblivious to what settings amy or may not have been writen to a sandboxed registry copy.

**Comment by divinity76** [comment]
@DavidXanatos oh i see, interesting.

Guess there's nothing to do here and this issue should be closed then?

**Comment by mysteriously** [comment]
You can try using Application Compatibility Toolkit in the sandbox or apply compatibility setting via sandboxed registry
