### ISSUE TITLE
Build scripts are not including the latest changes to the Plus installer

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1556]
**Describe the problem**
sandman_pt.qm and sandman_ua.qm were not deleted as expected with the upgrade from Plus 1.0.7 to 1.0.8:
https://github.com/sandboxie-plus/Sandboxie/blob/18f900f7a293d4a8909ccc2abba970567d54eb63/Installer/Sandboxie-Plus.iss#L78-L83

**Expected behavior**
sandman_pt.qm and sandman_ua.qm should be deleted automatically at install time.

**Workaround**
Manual removal of sandman_pt.qm and sandman_ua.qm

**Comment by isaak654** [comment]
It's not the first time that GitHub commits are randomly skipped and I would like to not see this type of drawbacks again.
Sometimes I wonder what's the point to merge commits if I also need to be worried about some of them being discarded without notice.

**Comment by DavidXanatos** [comment]
the reason fir this particular issue is that I forgot to tell the person whom is signing and installers to update the installer scripts. ups...

**Comment by isaak654** [comment]
> the reason fir this particular issue is that I forgot to tell the person whom is signing and installers to update the installer scripts. ups...

In this case, you might want to suggest to the person this service: https://app.github-file-watcher.com/
Note: this only supports files on master branch.

**Comment by isaak654** [comment]
Did you consider my suggestions to prevent these drawbacks?

**Comment by DavidXanatos** [comment]
I will just remember to remind the guy of updating the installer repo. whenever its needed that should be good enough.
Or better... I'll update the build scripts to use the iss file from the regular source repository that's pretty much full proof and probably wont break anything

**Comment by isaak654** [comment]
Sandboxie Plus v.1.8.3 does not include the newly added Hungarian language in the installer (out of sheer forgetfulness): https://github.com/sandboxie-plus/Sandboxie/commit/b3ee1723e8a1aeecd8c474337fd319fe2b9dbd92

I would like to renew [my previous request](https://github.com/sandboxie-plus/Sandboxie/issues/1556#issuecomment-1015799069) or at least provide another way to avoid these shortcomings.

**Comment by isaak654** [comment]
Sandboxie Plus v.1.8.3 does not include the newly added Hungarian language in the installer (out of sheer forgetfulness): https://github.com/sandboxie-plus/Sandboxie/commit/b3ee1723e8a1aeecd8c474337fd319fe2b9dbd92

I would like to renew [my previous request](https://github.com/sandboxie-plus/Sandboxie/issues/1556#issuecomment-1015799069). Otherwise, could you at least consider another way to avoid these shortcomings?
