### ISSUE TITLE
SBIE2203 with Brave browser

### ISSUE THREAD

**Issue by randyabr** [sandboxie-plus/Sandboxie#1558]
**Describe the problem**
I got message saying "brave.exe" (28536): SBIE2203 Failed to communicate with Sandboxie Sevice: *GUIPROXY_00000001; Msgld 22 - brave.exe [00000102]

Some of the Msglds are 15, 20, 6, and 13 too.

I really don't notice any effects on my browsing experience though.

**To Reproduce**
1. As far as I know the repro is to use the browser, but I can play around and see if there's a specific repro sequence

**Screenshots**

**Expected behavior**

**System details and installed software**
 - Windows 10 version 10.0.19042. Dual Boot with Ubuntu Studio 21.04
 - Sandboxie Plus 1.07
 - What was your previous Sandboxie version before the update, if any?
 - I only recently installed brave. I'm not sure how long the issue has been there. I only recently started using Brave
Running ESET Internet Security 15.0.21.0

**If you had a compatibility issue or a crash**
 - Please add a download link to the program not working properly in Sandboxie.
 - Please consider to take a log and make it available for analysis: https://git.io/Jwj2y
 - Please attach the actual memory dump and NOT the simple output, which often turns out to be insufficient for a proper analysis.

**Additional context**
Add any other context about the problem here. I can play around, with it, but I got so used to messages that seemed to have no effect with the original version of Sandboxie that I just ignored them. I'll pay more attention now to try to help you folks.
**Sandboxie configuration**

I've got 4 sandboxes. 

#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n

[UserSettings_0C9C021F]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
BoxCollapsedView=DefaultBox

[DefaultBox]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=y
CopyLimitKb=81920
ForceProcess=acrobat.exe
ForceProcess=edge.exe
ForceProcess=chrome.exe
ForceProcess=brave.exe
ForceProcess=firefox.exe

[Trusted_Hardened]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ff9d,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
UsePrivacyMode=n
BoxNameTitle=y
CopyLimitKb=81920
FakeAdminRights=y

[Trusted]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#4bc800,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
UsePrivacyMode=n
BoxNameTitle=y
CopyLimitKb=81920

[Temp]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00aaff,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
UsePrivacyMode=n
BoxNameTitle=y
CopyLimitKb=81920

**Comment by isaak654** [comment]
That may indicate that there is an incompatible browser extension to disable from the sandboxed browser.
