### ISSUE TITLE
IpcRootPath (and KeyRootPath) not automatically set to match FileRootPath

### ISSUE THREAD

**Issue by Gitoffthelawn** [sandboxie-plus/Sandboxie#1559]
**Describe the problem**
`IpcRootPath` (and `KeyRootPath`) not automatically set to match `FileRootPath`.

**To Reproduce**
1. Install Sandboxie-Plus portable.
2. Run `Sandman.exe`.
3. Open the settings UI.
4. Via the settings UI, remove `%USER%` from the sandbox's root folder.
5. In the settings UI, uncheck the box indicating to use separate folders for each user.
6. Open `Sandboxie.ini`.
7. Notice `IpcRootPath` points to a non-existent path.

**Relevant details from `Sandboxie.ini` after following the above steps**  
```
FileRootPath=\??\%SystemDrive%\Sandbox\%SANDBOX%
SeparateUserFolders=n
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
```

**Expected behavior**
I'm not 100% sure this is a bug, but I think `%USER%` should get removed by `sandman.exe` from at least `IpcRootPath` and possibly also `KeyRootPath` when the user removes it from the sandbox root location and indicates not to use separate folders for each user.

**System details and installed software**
 - What is your Windows edition and version? Win7 64-bit
 - What is your current Sandboxie edition and version? Tested with v1.0.7 64-bit portable (now running v1.0.8 64-bit portable)
 - What was your previous Sandboxie version before the update, if any? None

**Comment by DavidXanatos** [comment]
They don't need to match, why would you want them to match?
I think its fine as it is.

**Comment by Gitoffthelawn** [comment]
No problem.  I just wanted to make sure it's not a bug.

It seems like if the user has `FileRootPath` set to `\??\%SystemDrive%\Sandbox\%SANDBOX%`, then having `IpcRootPath` set to `\Sandbox\%SANDBOX%\Session_%SESSION%` instead of `\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%` makes more sense, no?

**Comment by DavidXanatos** [comment]
well that depands on that the user wants
also as long as %session% is in the path 2 users on the same system will not share the namespaces as each user gets an own session id

**Comment by Gitoffthelawn** [comment]
Sounds good. Thanks.

There's no problem in the user manually editing `Sandboxie.ini` and changing `IpcRootPath` to `\Sandbox\%SANDBOX%\Session_%SESSION%`, right?

**Comment by DavidXanatos** [comment]
sure you can change that this way

**Comment by Gitoffthelawn** [comment]
Thank you for your help.  I'll close this now.
