### ISSUE TITLE
Deleting folder dialog get stuck when remove sandbox

### ISSUE THREAD

**Issue by wenyifancc** [sandboxie-plus/Sandboxie#1562]
**Describe the problem**
Deleting folder dialog get stuck when remove sandbox.
It works fine in Sandboxie-plus 1.0.7

**To Reproduce**
1. Right click the sandbox in SandMan
2. Click [Remove Sandbox] in right-click menu
3. See error: Deleting folder dialog won't close

**Expected behavior**
Just remove the sandbox and close the dialog.

**System details and installed software**
Windows 10 21H2 and Windows 11
Sandboxie-plus 1.0.8

**Comment by isaak654** [comment]
For me the deletion process gets stuck here without errors:
![stuck_deletion](https://user-images.githubusercontent.com/12372772/150287274-0fcc5a19-64b2-431e-a310-b51087d19f7b.png)

Workaround: close the window and the sandbox will be removed as expected
