### ISSUE TITLE
GitHubDesktop window does not appear when sandbox name is 'GitHub'

### ISSUE THREAD

**Issue by vitidev** [sandboxie-plus/Sandboxie#1564]
**Describe the problem**
GitHubDesktop window does not appear when sandbox name is 'GitHub'

**To Reproduce**
1. create new sandbox with any name and type (for example, application container)
2. install `GitHubDesktopSetup-x64.exe` from https://desktop.github.com/ in sandbox 
2. start from menu. App window will appear 
3. rename sandbox to 'GitHub'
4. start from menu. App window will not appear 

**System details and installed software**
 - Windows 10 Pro 21H2 64-bit (19044.1466)
 - Sandboxie Plus 1.0.8 64-bit

It is not clear why this is happening. Does the running process somehow know about the name of the sandbox?

**Comment by DavidXanatos** [comment]
I guess if you disable show sandbox indicator in title
![grafik](https://user-images.githubusercontent.com/3890945/151675964-adfae880-8f80-4218-82dc-0dea4ea95b87.png)

it will work in that box, this is why sandboxie+ has so many options
