### ISSUE TITLE
A problem happened when tried to run the programs in Sandboxie: ”A JavaScript error occurred in the main process“ 

### ISSUE THREAD

**Issue by Decem6er** [sandboxie-plus/Sandboxie#1566]
**To Reproduce**
1. Install the application in Sandboxie and it succeeded.
2. Run the application installed just now.
3. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/16839570/150491655-55b4f44b-8c98-4582-bc3b-479eb6246d21.png)

**System details and installed software**
 - Windows 11 Pro 21H2 64-bit (Build 22000.466)  (Experience Windows Feature Experience package1000.22000.466.0)
 - Current Sandboxie edition and version: Sandboxie Plus 1.0.8 64-bit
 - Avira and Windows Defender are running in the background, but real-time protection is disabled.
 - The program not working properly in Sandboxie: AliyunDrive
  - Download link: https://yunpan.aliyun.com/downloads/apps/desktop/aDrive.exe?spm=aliyundrive.index.0.0.2d836020Dtg4Y7&file=aDrive.exe

**Sandboxie configuration**

<details>

<summary>My initial sandboxie.ini settings</summary>

```

#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=P:\Sandboxies\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Listary
Template=InternetDownloadManager
Template=Avira_Antivirus
Template=7zipShellEx

.....

[UserSettings_0D7E0211]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

.....

[AliCloudDrive]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
FakeAdminRights=n
CopyLimitKb=81920
ClosedFilePath=G:\
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
RpcMgmtSetComTimeout=n
DropAdminRights=n
RunCommand=aDrive.exe|"P:\Sandboxies\AliCloudDrive\user\current\AppData\Local\Programs\aDrive\aDrive.exe"

.....

```

</details>

**Comment by isaak654** [comment]
#1403
