### ISSUE TITLE
Sandboxie64 fails to launch with error "Unknown user, configuration settings may not be saved"

### ISSUE THREAD

**Issue by ojo11** [sandboxie-plus/Sandboxie#1574]
Application fails to launch with error "Unknown user, configuration settings may not be saved"

Environment: Desktop
OS: Windows 10 Insider Preview
OS build: 22520
App Version: 5.53.2 &5.51.6

Repro Steps:
1. Run the application setup file.
2. Install the Application.
3. Launch the Application.
4. Observe.

Actual Results:
Application fails to launch with error “Unknown user, Configuration settings will not be saved”

Expected Results:
Application should launch without any issue
Environment: Desktop

Ask: Please update the app to not depend on version check.

**Comment by DavidXanatos** [comment]
what is the latest build doing?

**Comment by ojo11** [comment]
Hello David - I'm with Microsoft App Assure ISV Outreach and we would like work with you to make sure Sandboxie does not depend on version check.

Are you a dev for Sandboxie?

Thank you,
Oscar

**Comment by DavidXanatos** [comment]
Yes I am, I'll take a look at this issue shortly, just need to set up a VM with that windows 10 version, my regular insider VM is already at win 11.

**Comment by DavidXanatos** [comment]
hmm... in said win 11 snapshot i can not reproduce the issue.

**Comment by ojo11** [comment]
Hello David - I'm working with our engineering team to make sure the you're able to repro with 22523 build. I'll follow up in a week or so.

Thank you,
Oscar

**Comment by ojo11** [comment]
Hello David - Can you please attempt a new repro on 22564?

Thank you,
Oscar

**Comment by ojo11** [comment]
Hello - Have you attempted a new repro?

Thank you,
Oscar

**Comment by isaak654** [comment]
If it's urgent, I would suggest to reach him on the email reported on his GitHub profile.

**Comment by isaak654** [comment]
If it's urgent, I would suggest to reach him through the email reported on his GitHub profile.

**Comment by ojo11** [comment]
Hello, I reported this via Davids email

**Comment by DavidXanatos** [comment]
I don't think i got an email, was very busy with other bugs lately, and the ARM64 port...

I regularly test sandboxie with the insider build most recent 22598.1 and on my vm it starts up just fine.

Could you may be provide a VM image for download in which this issue apprears?

**Comment by isaak654** [comment]
@ojo11 Does this issue still apply to you?
