### ISSUE TITLE
Cant run VS2022

### ISSUE THREAD

**Issue by Barshan-Mandal** [sandboxie-plus/Sandboxie#1576]
**Describe the problem**
Cant run VS2022 emulating admin rights

**To Reproduce**

try installing Visual Studio 2022 by VS installer

**Expected behavior**
Running

**System details and installed software**
 - What is your Windows edition and version? (e.g. Windows 11)
 - What is your current Sandboxie edition and version? ( latest)
 - What was your previous Sandboxie version before the update, if any?

**Comment by isaak654** [comment]
#1452

**Comment by DavidXanatos** [comment]
I'm working on getting host installed VS2019 to run inside a compartment type sandbox,
once that works I'll look into VS2022 presumably once one work the other should only need minor fixes.

**Comment by DavidXanatos** [comment]
In the next preview build 1.1.1 VS2019 and VS2022 will start successfully,
but to have your licence recognized you need to open the protected storage, ```OpenProtectedStorage=y```
Seams to even work in a regular box, although to use the debugger use of a compartment type box seams required.
