### ISSUE TITLE
EAappInstaller.exe

### ISSUE THREAD

**Issue by Chaython** [sandboxie-plus/Sandboxie#1577]
**Describe the problem**
When you run EAappInstaller.exe it says it's already installed.
Clicking repair, does do an install process but doesn't install anything.

**To Reproduce**
https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
When ran in a box says it's already installed...

**Screenshots**
When ran ![image](https://user-images.githubusercontent.com/6486343/151649433-537be512-e482-4797-8639-9dfc7a5d5e05.png)
When clicking repair 
![image](https://user-images.githubusercontent.com/6486343/151649580-d543dbce-a4c3-41dd-beb5-6922869b5ad0.png)

**Expected behavior**
It should install, not just exit thinking it is installed. 

**System details and installed software**
 - What is your Windows edition and version? Windows 11 Enterprise 64-bit
 - What is your current Sandboxie edition and version?  Sandboxie Plus 1.08

**If you had a compatibility issue or a crash**

**Additional context**

**Sandboxie configuration**

<details>

<summary>My initial sandboxie.ini settings</summary>
[Options]
UiLanguage=en
NextCheckForUpdates=1642624499
UseDarkTheme=2
RunInDefaultBox=false
ShowNotifications=true
OpenUrlsSandboxed=0
ShowRecovery=false
InstantRecovery=true
EnablePanicKey=false
PanicKeySequence=Shift+Pause
WatchIni=true
SysTrayIcon=1
OnClose=ToTray
AutoRunSoftCompat=true
CheckForUpdates=0
WarnTerminate=1
NoSupportCheck=false

[SettingsWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAYMAAADJQAACPMAAAT8AAAGDQAAA0QAAAjyAAAE-wAAAAAAAAAADwAAAAYNAAADRAAACPIAAAT7

[OptionsWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAi4AAAFZwAAC98AAAd_AAAIuQAABYYAAAveAAAHfgAAAAAAAAAADwAAAAi5AAAFhgAAC94AAAd-
Run_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAecAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABgwAAAAEAAAAAAAAD6AAAAABk
AutoRun_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAecAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABgwAAAAEAAAAAAAAD6AAAAABk
Groups_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAABAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAABAAAAZAAAAAEAAAAAAAAD6AAAAABk
Forced_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAe4AAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABigAAAAEAAAAAAAAD6AAAAABk
Stop_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAd8AAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABewAAAAEAAAAAAAAD6AAAAABk
Start_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAABAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAABAAAAZAAAAAEAAAAAAAAD6AAAAABk
INet_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAfEAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABjQAAAAEAAAAAAAAD6AAAAABk
NetFw_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfQAAAAFAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAFAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAD6AAAAABk
Access_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAeQAAAAEAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAAhQAAAAEAAAAAAAAAkQAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAagAAAAEAAAAAAAAD6AAAAABk
Recovery_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe4AAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABigAAAAEAAAAAAAAD6AAAAABk
Templates_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAeEAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABfQAAAAEAAAAAAAAD6AAAAABk

[PopUpWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAyUAAAHRgAADu0AAAgtAAAMlQAAB2UAAA7sAAAILAAAAAAAAAAADwAAAAyVAAAHZQAADuwAAAgs

[MainWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAZEAAADEQAACSsAAAVNAAAGRQAAAzAAAAkqAAAFTAAAAAAAAAAADwAAAAZFAAADMAAACSoAAAVM
LogList_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtwAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAACeAAAAAEAAAAAAAAD6AAAAABk
Log_Splitter=:ByteArray:AAAA_wAAAAEAAAACAAAAwAAAAQQB_____wEAAAACAA
Panel_Splitter=:ByteArray:AAAA_wAAAAEAAAABAAABAAH_____AQAAAAEA
LogTab=0
TraceLog_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnwAAAAEAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAALwAAAAEAAAAAAAAAHwAAAAEAAAAAAAAAJwAAAAEAAAAAAAACBwAAAAEAAAAAAAAD6AAAAAAj
BoxTree_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAuEAAAAGAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAGAAABLAAAAAEAAAAAAAAARgAAAAEAAAAAAAAARgAAAAEAAAAAAAAARgAAAAEAAAAAAAAAVAAAAAEAAAAAAAAAjwAAAAEAAAAAAAAD6AAAAACP

[FileBrowserWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAZiAAADPwAACJ4AAAUBAAAGYgAAAz8AAAieAAAFAQAAAAAAAAAADwAAAAZiAAADPwAACJ4AAAUB
FileTree_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiMAAAAEAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAA9wAAAAEAAAAAAAAD6AAAAABk

</details>

**Comment by isaak654** [comment]
1) I think you confused Sandboxie.ini configuration file (mainly located on C:\Windows) with Sandboxie-Plus.ini.
The latest one should be attached mostly if you have user interface issues with Sandboxie Plus.
2) Do you have EA Desktop Client also installed outside the sandbox?

**Comment by Chaython** [comment]
> 1. I think you confused Sandboxie.ini configuration file (mainly located on C:\Windows) with Sandboxie-Plus.ini.
>    The latest one should be attached mostly if you have user interface issues with Sandboxie Plus.
> 2. Do you have EA Desktop Client also installed outside the sandbox?

It was not installed outside the box, but there was still some interfering registry keys. Mainly because of Origin? Or because of the Xbox_eaconnect integration?

**Comment by Doc-4** [comment]
I'd like to update this issue, the recent updates (likely the electron app fixes) fixed the installation, the launcher mostly works minus some quirkyness likely inherent to it being sandboxed. It works well enough to install and play games, it's harder to trick it into thinking dependency installs than origin but not impossible. Could someone close this issue please?
