### ISSUE TITLE
Aliyun Cloud Drive Launch Failed

### ISSUE THREAD

**Issue by People-11** [sandboxie-plus/Sandboxie#1578]
**Describe the problem**
Install Aliyun Cloud Drive (www.aliyundrive.com) in the Sandbox, and it succefully installed, but failed to launch and pop an Error Window

**To Reproduce**
1. Run aDrive.exe in Sandboxie Plus
2. Click Install
3. The installation finished, then click launch

**Screenshots**
![Snipaste_2022-01-29_21-42-08](https://user-images.githubusercontent.com/41558215/151663422-65d84d93-29da-44d6-b992-ae0c70a0c11e.PNG)

**Expected behavior**
Aliyun Drive succefully launch and pop up login window.

**System details and installed software**
 - Windows 10 LTSC 2021 
 - Sandboxie Plus 1.0.8 64-bit
 - 1.0.7
 - 1.0.8, 1.0.7 and maybe all versions 
 - 火绒安全软件 https://www.huorong.cn/

**Comment by isaak654** [comment]
#1403

**Comment by People-11** [comment]
Now Fixed
