### ISSUE TITLE
"Run Sandboxed" entry in Sandman behaves differently than SbieCtrl

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1579]
| _Reported by @walmar in https://github.com/sandboxie-plus/Sandboxie/discussions/1554#discussioncomment-2073882_ |
|--------------|

I am not satisfied with the following last change.
> „SandMan will now run in background like SbieCtrl when starting a boxed process“

As I already [commented to Release v0.8.8 / 5.50.8](https://github.com/sandboxie-plus/Sandboxie/discussions/998#discussioncomment-1133634):
> Version 0.8.2 of Sandboxie-Plus was running minimized to tray via Run Sandboxed context menu option with Sandboxie.ini UserSettings section option SbieCtrl_AutoStartAgent=SandMan.exe -autorun.
> Sandboxie-Plus v0.8.8 Run Sandboxed context menu option seems to ignore the UserSettings section option SbieCtrl_AutoStartAgent.

After the change, "Run Sandboxed" behaves differently as SbieCtrl.exe when used several times.
- System start
  1. RS option > close SandMan or SbieCtrl
  2. RS option (again)
     - with <1.0.8/5.55.8:  SandMan/SbieCtrl is running again
     - with 1.0.8: SandMan.exe is missing

**Comment by DavidXanatos** [comment]
I see the problem :/ will look into a fix
