### ISSUE TITLE
how to disable Sandboxie-plus service SbieSvc.exe after exiting Sandboxie? I use portable version.

### ISSUE THREAD

**Issue by abu-101** [sandboxie-plus/Sandboxie#1581]
SbieSvc.exe is running after exiting Sandboxie? is there a way to disable it automatically after exiting Sandboxie...

**Comment by DavidXanatos** [comment]
When you run it in portable mode it will prompt you if you want to terminate it.
It is not intended to terminate the service when running installed, as its required for the forced processes function

**Comment by abu-101** [comment]
> When you run it in portable mode it will prompt you if you want to terminate it. It is not intended to terminate the service when running installed, as its required for the forced processes function...

after terminate all processes and exiting Sandboxie this service still running it's not stopped

**Comment by DavidXanatos** [comment]
yes that is normal

**Comment by abu-101** [comment]
ok
