### ISSUE TITLE
"Browse content" should bring content window to front

### ISSUE THREAD

**Issue by Symbai** [sandboxie-plus/Sandboxie#1584]
### Is your feature request related to a problem or use case?

If I click on "Browse content" I would expect the content window gets brought back to front if its already opened. But it does not. So if this window is somewhere behind many other windows and you click on "Browse content" it looks like nothing would happen. So you would have to remember you got the window opened and then try to find it.

### Describe the solution you'd like

Clicking "Browse content" brings window back to front if its already opened.

**Comment by DavidXanatos** [comment]
fixed in next build
