### ISSUE TITLE
dll cant register under sandboxie

### ISSUE THREAD

**Issue by mrvanity** [sandboxie-plus/Sandboxie#1588]
### What happened?

Hello,
I have a software that i want to run under sandboxie that for a part of it to work it needs a registration of a dll (x86).
The software runs properly out of the sandboxie. Trying to troubleshoot i tried to install the software under sandboxie.
The installation didn't succeed by failing on the dll registration.
So i launched a command prompt within the sandbox.
The registration failed with the message in the screenshot below.
https://drive.google.com/file/d/14Jbq01i7-AVWmh7daJZ2rRT_GBde52gd/view?usp=sharing
The same command outside the sandbox works correctly.
(The command is "C:\Windows\SysWOW64>regsvr32 d:\XX\bin\XXgm.dll"

### Expected behavior

The dll to be registered

### What is your Windows edition and version?

Windows 10 Pro 20H2

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.8 x64

### Please mention any installed security software

Windows Defender (disabled or not)

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=AdobeLicensing

[UserSettings_08780188]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,1
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=y
CopyLimitKb=-1
BlockNetParam=n
OpenPrintSpooler=y
AllowSpoolerPrintToFile=y
OpenProtectedStorage=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
OpenDevCMApi=y
OpenSamEndpoint=y
OpenLsaEndpoint=y
```

**Comment by DavidXanatos** [comment]
well without the dll to test i'm affraid i cant help much

**Comment by mrvanity** [comment]
Of course.
My bad.
the dll is the one in the link
https://drive.google.com/file/d/14NhflYPirhEXk8b066o3DmwjM9tVv6x_/view?usp=sharing

Thank you. :)

**Comment by DavidXanatos** [comment]
You can use this
```OpenWinClass=*```
as a workaround for now
than i get a message box later it fails but it fails the same without a sandbox, probably missing activation or something.

**Comment by DavidXanatos** [comment]
fixed in next build, ther you will only require
```
OpenWinClass=#32769
```

which is opening access to the desktop window only

**Comment by mrvanity** [comment]
Thank you!
Adding OpenWinClass=* registered the dll!

The problem after this is that it doesn't load when needed.
When the dll is loaded there is a window with data in the software.
Apart from this there is a button to "maximize" the data window.

in the link below are two traces.
https://drive.google.com/file/d/18CspvslGTcTOhhgsAa-F2qzcXFZSVntT/view?usp=sharing
The first one is when the dll is called in the embedded window, and the extended after the "maximize button is pushed"

`                                           
reader.exe (33520, 17492) - 13:57:19.509   ComClass (U)   Open       {F5D98C43-DB16-11CF-8ECA-0000C0FD59C7} ActiveCGM Control  ` 
There is a call to  ActiveCGM Control (the dll is aActiveCGM plugin)

The maximize window clearly uses iexplore engine.                                                                                                                                                                                     
`  
SandboxieDcomLaunch.exe (3576, 30404) - 13:58:56.067   Debug (U)   Trace      CreateProcess: C:\Program Files (x86)\Internet Explorer\ielowutil.exe ("C:\Program Files (x86)\Internet Explorer\ielowutil.exe" -CLSID:{0002DF01-0000-0000-C000-000000000046} -Embedding); err=0   `

The box is almost air gapped, so i don't mind sacrificing any security,
My regards.

**Comment by mrvanity** [comment]
Installing the app through sandboxie and executing via sandboxie, works just fine.
Thank you!

P.S. Is this the right place to ask a question about duplicates sandboxes or at the discussions?
(copying the sandbox does not copy all the data and if  I xcopy the folder and add a new section to  sandboxie.ini i cant launch the app at the same time from both sandboxes)

**Comment by emmadavis23** [comment]
I think [downloading acgm.dll](https://pcpatchedup.com/acgm-dll) will solve the issue, Ensure to restart the system after installing dll file.
