### ISSUE TITLE
Sandman notification area icon is hidden after every restart via Run Sandboxed

### ISSUE THREAD

**Issue by walmar** [sandboxie-plus/Sandboxie#1590]
### What happened?

x

### Expected behavior

The icon is always displayed.

### What is your Windows edition and version?

Windows 7 Pro 6.1.7601 64-bit

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.9 64-bit

### Please mention any installed security software

x

### Is it a regression?

Starting from 1.0.8 64-bit

**Comment by isaak654** [comment]
Still related to #1579 ?

**Comment by walmar** [comment]
For me it seems in the sense of the different behavior of Sandman.
I already noticed it with 1.0.8, but did not found it as important as the missing process to mention it.

**Comment by DavidXanatos** [comment]
Could you please make a video demonstrating the issue,
What do you mean exactly? Is sand man not being started? Is it crashing? is it there but the icon dissapears?
From the breef description its not clear to me which failure mode you are experiencing.

**Comment by walmar** [comment]
> What do you mean exactly?

I mean the Sandman notification area icon is added hidden as explained for the taskbar notification area [on Wikipedia web page](https://en.wikipedia.org/wiki/Taskbar#Taskbar_elements):
> Starting with Windows XP, the user can choose to always show or hide some icons, or hide them if inactive for some time. A button allows the user to reveal all the icons.

The placement state is not restored.

**Comment by DavidXanatos** [comment]
Hmm... I'v seen that happening, not sure why and ow to fix it, seams somehow windows does not thread it as the same program sometimes.
For me moving the icon when in started by service mode fixed the issue.

**Comment by isaak654** [comment]
Just for the record, I found similar reports related to other QT5 projects:
https://forum.kde.org/viewtopic.php?f=289&t=156799 (fixed by https://github.com/KDE/plasma-integration/commit/d2a1d1ca9e9e5512749cb59f2c7d56849ab04380)
https://github.com/hluk/CopyQ/issues/1258 (fixed by https://github.com/hluk/CopyQ/commit/5a0be76552441f6007997c18fe621619f9c12421)

About the second fix, Sandboxie Plus already provides `styles/qwindowsvistastyle.dll`, just not on the .iss installer: https://github.com/sandboxie-plus/Sandboxie/blob/41f06e4bf342fb87a3078408d0df8af46bd6530d/Installer/copy_build.cmd#L46-L47

Another example of qwindowsvistastyle.dll provided on the .iss installer: https://github.com/jackaudio/jack2/commit/3d681a3a9941233295f31a227b5d54a40f0373ca

**Comment by walmar** [comment]
I have performed a few more tests with v1.0.11.
- Not sure what you mean by service mode. I
  - checked Options > Global Settings > Shell Integration > Start Sandbox Manager
    - [x] Start UI with Windows
  - restarted system
  - placed icon as shown
  - closed SandMan and
  - selected Run Sandboxed > [Sandbox]

  with the result that the icon is hidden
- I called Run Sandboxed and Start.exe again
  - with the result that Start.exe does not reset the icon placement, unlike Run Sandboxed
- I changed Sandboxie.ini UserSettings section option to SbieCtrl_AutoStartAgent=start.cmd with _cmd.exe_ as file content
  - it starts the cmd.exe via Run Sandboxed/Start.exe
  - I typed in both cases with same result
    - whoami
    - cd
    - fsutil dirty query %systemdrive%
  - I entered the following line with reseted icon as result only when running a Sandbox via the Run SandBoxed dialog before SandMan
    - "C:\Program Files\Sandboxie-Plus\SandMan.exe" -autorun

So it seems to me, when running a sandbox via Run Sandboxed option, then icon placement is reset. At the moment, when the SandMan.exe Run Sandboxed dialog sets its icon.

During my tests, I also discovered another issue
- when
  1. starting SandMan and just closeing its window
  2. selecting Run Sandboxed and keeping the dialog open
  3. starting SandMan
- then an additional icon with a hanging process is added 

<details><summary>As a workaround, I am temporarily use a AutoHotkey script</summary>

```
#NoEnv
SendMode Input
SetWorkingDir %A_ScriptDir%
DetectHiddenWindows, On

#include TrayIcon.ahk ; [https://www.autohotkey.com/boards/viewtopic.php?t=1229 [LIB] TrayIcon - Sean's TrayIcon for Unicode and 64 bit - AutoHotkey Community]

#IfWinActive Sandboxie-Plus - ahk_class Qt5152QWindowIcon ahk_exe SandMan.exe
LButton::
	KeyWait, %A_ThisHotkey%, T0.2
	if (!Errorlevel)
	{
		KeyWait, LButton, D T0.2
		if (!ErrorLevel && A_TimeSinceThisHotkey < 400)
		{
			TrayIcon_Button("SandMan.exe",,True) ; double clicks tray icon
			WinWaitActive, Sandboxie-Plus v ahk_class Qt5152QWindowIcon ahk_exe SandMan.exe,, 0.2
			if ErrorLevel
			{
				Run, "C:\Program Files\Sandboxie-Plus\SandMan.exe" -autorun
				sleep, 500
			}
			else
				WinClose
			
			WinActivate, Sandboxie-Plus - ahk_class Qt5152QWindowIcon ahk_exe SandMan.exe
			WinWaitActive, Sandboxie-Plus - ahk_class Qt5152QWindowIcon ahk_exe SandMan.exe,, 1
			if (!ErrorLevel)
			{
				Loop, 2
					Send {%A_ThisHotkey%}
			}
		}
		else
			Send {%A_ThisHotkey%}
	}
Return
```

</details>

- that runs SandMan.exe -autorun before a sandbox runs via double-clicking into the Run Sandboxed dialog, when SandMan UI is not displayed via double-click on the icon
