### ISSUE TITLE
Question, what is the memory limit of this sandboxie version?

### ISSUE THREAD

**Issue by iamaneophyte** [sandboxie-plus/Sandboxie#16]
is there or will there be a way to increase the memory limit of the programs that sandboxie can run? I need to run a bitcoin miner but it crashes due to sandboxie's limited memory.

**Comment by DavidXanatos** [comment]
Do you get some error message? I'm not aware of a ram limitation with sandboxie, what is limited though is the size of files when they are copied form their original location to the sandbox.

**Comment by iamaneophyte** [comment]
with the miners ive tried i get some error message regarding the memory (maybe its my gpu memory not being processed through sandboxie) but when i try running it outside the sandbox it works fine

**Comment by iamaneophyte** [comment]
ive come to the conclusion that sandboxie cannot process OpenGL code using an AMD GPU

**Comment by breadnone** [comment]
Miner inside a sandbox... holy mother of god!

**Comment by iamaneophyte** [comment]
a man has his reasons! :S

**Comment by DavidXanatos** [comment]
i think this issue can be closed
