### ISSUE TITLE
Trying to reinstall sandboxie plus

### ISSUE THREAD

**Issue by MonthOLDpickle** [sandboxie-plus/Sandboxie#160]
It still shows up in my apps program but install is gone. I can't reinstall or upgrade I get this:

startSetup failed

I tried the portable mode (extract option)

Error Code 2

Then a windows can't verify the app

Then a Failed to connect to driver

How do I fix this? Or am I screwed?

**Comment by MonthOLDpickle** [comment]
I was reinstalling because the app would freeze on making a new sandbox.

**Comment by ProjectBacker** [comment]
Using 64bit version
1. Reboot PC
2. Make sure no process of sandboxie is running
3. Go to the following and remove both these folders
C:\Program Files\Sandboxie
C:\Program Files\Sandboxie-Plus\
4. Reboot
5. Run Sandboxie-Plus-x64-v0.4.2.exe in Administrator mode (right click use admin option)
6. If you get a blue box click on more info and choose allow.
7. Accept the contract and Install
8. Done (Reboot just in case to lock it in place)

That should be it if you get any errors in the steps I'll be monitoring the post for a few hours.

**Comment by MonthOLDpickle** [comment]
> ......

I get startSetup failed and there is nothing on my system for sandboxie.  
  
I think I have to uninstall a driver or two, yet I have no clue. When I uninstalled it failed even though it removed 90% of the program.

**Comment by DavidXanatos** [comment]
Go for extract put it in a folder,
start sandman.exe
than use the sandbox->maintanance->... menu options to check what components are still installed and uninstall that was left behind,
first the service than the driver.
Verify that the components are gone, reboot and reinstall.
that should be a reliable procedure

**Comment by MonthOLDpickle** [comment]
Beore rebooting that menu in snadboxie says I can install them - that means they are gone right? But rebooting just shows them back. How do I see them on my PC? 

I get this on starting extract version even as admin:

ControlServe Start: The filename, directory name, or volume label syntax is incorrect. (123)

**Comment by DavidXanatos** [comment]
Wait so they are returning after a reboot? that shouldn't happen, that's very strange.
please check in 
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieSvc
and
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieDrv

in booth registry keys, where is the value "ImagePath" pointing to?

**Comment by MonthOLDpickle** [comment]
I think Drv one is broke as other one is a valid path. Drv has this at the start \??\ whereas service starts at F:\

Both end at same location.

**Comment by DavidXanatos** [comment]
\\??\ is normal for drivers
uninstall the softwar check if the two keys are gone if not delete them and reboot
than confirm after the reboot they are gone
than try re installing

**Comment by MonthOLDpickle** [comment]
That didn't help =(

I don't know what to do besides wiping my entire PC with a reformat.

**Comment by DavidXanatos** [comment]
Normally deleting the reg key and rebooting is all it takes, if the entry returns that there must be something deeply messed up, i.e. after rebot a old version of the system reg hive gets mounted instead of teh actual oen or soemthing.

**Comment by MonthOLDpickle** [comment]
I understand that but how do I find the driver itself? The service seems to be fine, but the driver has an issue.

**Comment by DavidXanatos** [comment]
service: Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieSvc

driver: Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieDrv

on windows they are managed using the same mechanisms

**Comment by MonthOLDpickle** [comment]
So I fixed it. I had to do that plus find the registry for the uninstall location and delete that. Instead of getting upgrade from the exe now I got install.
