### ISSUE TITLE
Sbie Plus applies "Explore Sandboxed" for folders, but the installer applies always "Run Sandboxed" (inconsistency)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1601]
### What happened?

Plus installer 1.0.10 applies at install time "Run Sandboxed" for both folders and files, while if you unset / set the other option `Add 'Run Sandboxed' to the explorer context menu` available on the `Shell integration` tab you will get "Explore Sandboxed" for folders and "Run Sandboxed" for files. 

I think it represents an inconsistency between the main program and the installer.

For my tests, I did run the english installer and the english Plus interface.

Relevant entries on the installer side:

https://github.com/sandboxie-plus/Sandboxie/blob/085b7061316bb93b107dcae959d3d2713ed7fa54/Installer/Sandboxie-Plus.iss#L90-L100

https://github.com/sandboxie-plus/Sandboxie/blob/2be7d6cb033041ec3ef2c4eebb3c7e6e46c90461/Installer/Languages.iss#L57

Personally I'm against the implementation of "Explore Sandboxed" for folders and "Run Sandboxed" for files, because that would mean to introduce extra lines for all languages on the installer side.

### Expected behavior

Restore the previous behavior: Run Sandboxed for both folders and files on the `Shell integration` tab

### What version of Sandboxie are you running?

Plus 1.0.10 x64

### Is it a regression?

It happened even earlier than v1.0.8.

**Comment by DavidXanatos** [comment]
classical sandboxie had the 2 different strtings so I'll update the installer to create 2 different entries as well

**Comment by DavidXanatos** [comment]
no it seams i miss rememebr the calssical one has only run sandboxed for everything, than I'll revert to that in the plus ui

**Comment by isaak654** [comment]
I can confirm the fix on Plus 1.0.11.
