### ISSUE TITLE
The new BlockSoftwareUpdaters template needs more browser support

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1602]
### Is your feature request related to a problem or use case?

Only a couple of browsers are supported for the new introduced BlockSoftwareUpdaters template:

https://github.com/sandboxie-plus/Sandboxie/blob/2be7d6cb033041ec3ef2c4eebb3c7e6e46c90461/Sandboxie/install/Templates.ini#L162-L178

### Describe the solution you'd like

Add the rest of supported browsers that have already a template:

- [x] Waterfox
- [x] PaleMoon
- [x] SeaMonkey

~~LibreWolf~~ (no built-in updater)

- [x] MS Edge
- [x] Vivaldi
- [x] Brave
- [x] Opera
- [x] Yandex

~~Ungoogled~~ (no built-in updater)
~~Iron~~ (no built-in updater)

- [ ] Maxthon_6
- [ ] Comodo Dragon
- [ ] Osiris
- [ ] Slimjet

**Comment by Dyras** [comment]
Hello!

I know from experience that at least Edge and Chrome don't try to update themselves in the sandbox. Maybe Brave too. But this is definitely needed for Waterfox, PaleMoon and SeaMonkey.

I can take a look at this later this week if you want.

**Comment by isaak654** [comment]
Thank you for taking care about it!

Unfortunately it seems that other users had different experiences about the updates within the sandboxes, so I think all supported browsers would still need to be reconsidered:

> Well, Chrome gets updated automatically, even running within the Sandbox, but instead of a successful update gets crippled that way. You can only disable forced programs intentionally and beforehand if you know exactly when that update is going to be triggered.
Opera gets updated once a week, although not necessarily automatically. And Chrome more often than once a month, too, albeit constituting the bigger problem because of the unpredictable point in time such an upgrade is triggered. 

I'm also wondering... what about the Firefox/Chrome antiphishing templates enabled by default?

They are more needed or less needed, now that BlockSoftwareUpdaters is forcefully enabled for anybody?
And if they are needed, why MS Edge is out of the equation?

Since @APMichael took care of browser templates in the past, I'm going to attach it to the discussion.

**Comment by isaak654** [comment]
Thank you for taking care about it!

Unfortunately it seems that other users had different experiences about the updates within the sandboxes, so I think all supported browsers would still need to be reconsidered:

> Well, Chrome gets updated automatically, even running within the Sandbox, but instead of a successful update gets crippled that way. You can only disable forced programs intentionally and beforehand if you know exactly when that update is going to be triggered.
Opera gets updated once a week, although not necessarily automatically. And Chrome more often than once a month, too, albeit constituting the bigger problem because of the unpredictable point in time such an upgrade is triggered. 

I'm also wondering... what about the Firefox/Chrome antiphishing templates enabled by default?

They are more needed or less needed, now that BlockSoftwareUpdaters is forcefully enabled for anybody?
And if they are needed, why MS Edge is out of the equation?

Since @APMichael took care of browser templates in the past, I'm going to mention him to the discussion.

**Comment by APMichael** [comment]
> Since @APMichael took care of browser templates in the past, I'm going to mention him to the discussion.

Too much of the honor! I had posted at the time in the forum of Tzur and Invincea only now and then the necessary changes for the "Safe Browsing" and the "Bookmarks". The blocking of updates has always been hard coded and I have not yet dealt with it, because I always disable the automatic update immediately after installing a browser.

However, I just noticed that Firefox 97.0 suddenly appends an ID to the "Mozilla" directory under "ProgramData", so an asterisk would probably need to be added:

`SoftwareUpdater=firefox.exe,*\mozilla*\updates\*updater.exe `

**Comment by isaak654** [comment]
I have a "Mozilla" folder for TB 91.6.0 and the new one with the appended ID just for Firefox 97.0... do you know if it's going to affect Thunderbird in a future release?

**Comment by APMichael** [comment]
I don't know, but I guess it will be changed in Thunderbird sooner or later.

Since the file "ipcclientcerts.dll" is in the program directory, I guess we don't need to pay attention to it for the templates.

**Comment by Dyras** [comment]
Templates for Brave and Waterfox done! Planning on installing Opera and Vivaldi later. I tried to figure out Edge, but I'm not sure which file it uses to update.

```
SoftwareUpdater=brave.exe,*\BraveSoftware\Update\BraveUpdate.exe
SoftwareUpdater=waterfox.exe,*\Waterfox\updater.exe
```

**Comment by isaak654** [comment]
> I tried to figure out Edge, but I'm not sure which file it uses to update.

The path is `C:\Program Files (x86)\Microsoft\EdgeUpdate`, so I suggest the following rule:

`SoftwareUpdater=msedge.exe,*\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe`

**Comment by isaak654** [comment]
Any suggestion about SBIE2193 that appears when a program update is blocked?
I think the delete sandbox part could be confusing, besides deleting a content sandbox or the sandbox itself is not always required after a program update, so I'm more oriented to disable the following warning than rewriting it:
https://github.com/sandboxie-plus/Sandboxie/blob/432fef2b5cad9c3d04f563fc788ae3eb055a621e/Sandboxie/msgs/Sbie-English-1033.txt#L366-L367

Opinions?

**Comment by APMichael** [comment]
In a next update the following line can be removed:
`SoftwareUpdater=firefox.exe,*\mozilla firefox\updates\*updater.exe`

The path is already covered by this line:
`SoftwareUpdater=firefox.exe,*\mozilla*\updates\*updater.exe`

**Comment by APMichael** [comment]
These should be the lines for the remaining 4 browsers:
```
SoftwareUpdater=maxthon.exe,*\Maxthon\Application\*mxupdater.exe
SoftwareUpdater=dragon.exe,*\Comodo\Dragon\dragon_updater.exe
SoftwareUpdater=osiris.exe,*\Osiris\update.exe
SoftwareUpdater=slimjet.exe,*\Slimjet\updater.exe
```

**Comment by isaak654** [comment]
It looks fine, but for Osiris you need to add app_launcher.exe that is also set as desktop shortcut.

It needs to be checked throughly with a process manager, because that file (among other things) creates the file Update.exe in `%Temp%` directory.
