### ISSUE TITLE
Sandboxie-Plus' sandbox context menu -> Box contents -> Open Rigistry maybe ambiguous, because it's not sandboxed

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#1606]
### What happened?

Sandboxie-Plus' sandbox context menu -> Box contents -> Open Rigistry maybe ambiguous, because it's not sandboxed, user maybe delete or change registry by accident.
context menu -> Run -> Boxed Tools -> Registry Editor is Sandboxed, any change in it will not effect on real system. 

### Expected behavior

Consider remove context menu -> Box contents -> Open Rigistry or always show a warning before open it

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2021 x64 (21H2)

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

ESET Internet Security 15.0.23.0

### What version of Sandboxie are you running?

Sandboxie-Plus v1.0.9 x64

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
I like the function, so I'll add a warming message box
