### ISSUE TITLE
Sandboxie not responded when a number of process are created and stopped

### ISSUE THREAD

**Issue by worx7kbj** [sandboxie-plus/Sandboxie#1607]
### What happened?

Sandboxie not responded

### To Reproduce

0. Install JDK and Git
1. Clone https://github.com/PaperMC/Paper
2. run `./gradlew applyPatches` in a sandbox

### Expected behavior

Running smooth

### What is your Windows edition and version?

Windows 11

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Plus 1.0.9 64bit

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by worx7kbj** [comment]
Running other development related software in a sandbox often cause the same issue.

**Comment by worx7kbj** [comment]
> Running other development related software in a sandbox often cause the same issue.

Especially git

**Comment by worx7kbj** [comment]
Is there a option to stop tracing processes of a sandbox as a workaround of this issue?

**Comment by worx7kbj** [comment]
I need to force close the sandboxie manager from time to time. Sometimes I found two manager running in parallel and sometimes the manager didn't open - I can see the window open and close without loading any content

**Comment by DavidXanatos** [comment]
this should have been fixed in build 1.0.12
