### ISSUE TITLE
Chrome extensions still crashing and tabs have sad face folder icons after upgrading to Sandboxie 5.43.5 (64-bit)

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#161]
Google Chrome is up to date
Version 86.0.4240.111 (Official Build) (64-bit)
Note: I just updated Chrome from the previous 86 version.
Microsoft Windows [Version 10.0.18363.1139]
Sandboxie Version 5.43.5 (64-bit)

I also installed it on another computer with Windows 10 ver 2004 with the same problem.

**Comment by NewKidOnTheBlock** [comment]
Why are you using an old version of Sandboxie, when 5.43.6 adresses exactly this issue?
https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md

**Comment by jedimasterspaz** [comment]
Sorry, Must have been a rectal cranial inversion.
Thank you so much for catching that.

After I upgraded both computers, one is fine and the other has the following errors:
SBIE2303 Could not hook CoGetObject (33, 1655)
SBIE2303 Could no hook RegisterDragDrop (33, 1655)
SBIE2318 DLL initialization failed for 'ole32.dll'
SBIE2303 Could no hook CM_Add_Driver_packageW (33, 1655)
SBIE2318 DLL initialization failed for 'cfgmgr32.dll'
SBIE2303 Could not hook SetCurrentProcessExplicitAppUserModeID (33, 1655)

Chrome has 3 start tabs:
https://www.huffpost.com/
https://www.cnn.com/
https://mail.google.com/mail/u/0/#inbox

Any ideas???

**Comment by DavidXanatos** [comment]
the could not hook messages are strange, do you have some other security software that ma interferer? or try emptying the sandbox or re installing sandboxie again

**Comment by jedimasterspaz** [comment]
No additional security software is installed and I even turned off Defender.

**Comment by jedimasterspaz** [comment]
I'm uninstalled Sandboxie including the ini file.
I restarted and then reinstalled with administrator privileges and re-setup everything and the 6 errors still come up.
Any ideas?

**Comment by isaak654** [comment]
Just for the record, it looks similar to these issues:
https://community.sophos.com/sandboxie/f/forum/115348/anyone-seeing-occasional-ole-init-hook-failed-errors-from-sandboxie/424191
https://www.wilderssecurity.com/threads/sandboxie-plus-sbie-fork.427755/page-27#post-2958371
https://www.wilderssecurity.com/threads/sandboxie-technologies-sbie-open-source.428156/page-3#post-2919819

**Comment by NewKidOnTheBlock** [comment]
You still haven't answered whether you are still using 5.43.5 instead of the latest version -> 5.43.6

**Comment by HikariWS** [comment]
He did say he updated and 1 of his PCs is working.

**Comment by DavidXanatos** [comment]
this should be already fixed with the recent releases, the could not hook messages though only with the next build
