### ISSUE TITLE
Inaccessible network-mapped drive after enabling privacy mode + folder access given

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [sandboxie-plus/Sandboxie#1617]
### What happened?

Network-mapped drive couldn't be accessed inside sandboxie.

### To Reproduce

1. Map a samba share as network drive outside sandboxie.
2. Enable privacy mode in sandbox options -> resource access -> resource access policies
3. Allow access to network mapped drive （This doesn't count）
4. "Nothing" happens after double-click the network-mapped drive inside sandboxie.

### Expected behavior

The network-mapped drive opens in sandboxie with privacy mode, and follows access control.

### What is your Windows edition and version?

Windows Server 2022

### In which Windows account you have this problem?

I use the built-in Administrator with Admin Approval Mode turned on.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.8

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by Foosec** [comment]
> 

Does this allow access to all mapped drives? That seems to be the case with me.
Is it possible to only allow a specific network mapped drive?

**Comment by DavidXanatos** [comment]
remove 
NormalFilePath=\Device\Mup

and use a new build with the fix to ipen only selected drives

**Comment by Foosec** [comment]
> remove NormalFilePath=\Device\Mup
> 
> and use a new build with the fix to ipen only selected drives

Im using the current release but it doesn't work without that line
