### ISSUE TITLE
Adding shortcut to sandboxied application?

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [sandboxie-plus/Sandboxie#162]
In the SandMan.exe interface, is there a way to create shortcuts on your desktop to launch application in sandboxie, or do you have to go into the original SbieCtrl.exe interface to do it?

**Comment by DavidXanatos** [comment]
that feature is still missing I will add it soon, looks usefull :)

**Comment by skygunner** [comment]
I guess you can do it in bat like this:

"D:\Program Files\Sandboxie\Start.exe" /box:TIM "C:\Sandbox\yfh\TIM\drive\C\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe"
ping -n 3 127.0.0.1>nul
"D:\Program Files\Sandboxie\Start.exe" /box:TIM "C:\Sandbox\yfh\TIM\drive\C\Program Files (x86)\Tencent\QQLite\Bin\QQ.exe"

**Comment by DavidXanatos** [comment]
the feature was added in the last major build so i'll clsoe that now

**Comment by ShaunTheQuietGamer** [comment]
> 
> 
> the feature was added in the last major build so i'll clsoe that now

I've only just come back to windows after a while, how do i go about doing this?

**Comment by isaak654** [comment]
Box context menu -> Create shortcut
