### ISSUE TITLE
Sandboxed Windows Explorer takes 20+ seconds to open.

### ISSUE THREAD

**Issue by PirateModz** [sandboxie-plus/Sandboxie#1628]
### What happened?

Sandboxed Windows Explorer takes 20+ seconds to open. The yellow border around sandboxed programs with maximized windows is cut off at the top (Chrome for example has this problem). The taskbar on Windows 11 may have a different height thus cutting off the top of the yellow border.
![image](https://user-images.githubusercontent.com/60668602/153824571-98e2a351-dbf2-4522-b26f-504efcf3eb8e.png)
![image](https://user-images.githubusercontent.com/60668602/153824663-1794989e-7d25-4c82-bbf7-85ee3c48525a.png)

### To Reproduce

1. Run/open Sandboxie-Plus
2. Run
3. Boxed Programs
4. Windows Explorer

### Expected behavior

Sandboxed Windows Explorer should open in less than 5 seconds.

### What is your Windows edition and version?

Windows 11 Pro 21H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Windows Defender set to maximum security with ConfigureDefender (https://github.com/AndyFul/ConfigureDefender). I have no other anti-virus installed. Problems persists with real-time protection disabled.

### What version of Sandboxie are you running?

Sandboxie-Plus v1.0.11

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No. Aside from setting a hotkey to terminate sandboxed programs, no other settings were changed.

**Comment by isaak654** [comment]
#1127
