### ISSUE TITLE
Add a switch in sandboxie.ini to disable the CallerSigned check ?

### ISSUE THREAD

**Issue by vmtest888** [sandboxie-plus/Sandboxie#1631]
### Is your feature request related to a problem or use case?

```
_FX BOOLEAN MyIsCallerSigned(void)
{
    NTSTATUS status;

    // in test signing mode don't verify the signature
    if (MyIsTestSigning())
        return TRUE;

    status = KphVerifyCurrentProcess();

    //DbgPrint("Image Signature Verification result: 0x%08x\r\n", status);

    if (!NT_SUCCESS(status)) {

        //Log_Status(MSG_1330, 0, status);

        return FALSE;
    }

    return TRUE;
}
```

I don't have a driver signing certificate  ,   So can disable CallerSigned check?

### Describe the solution you'd like

none

### Describe alternatives you've considered

none

**Comment by DavidXanatos** [comment]
no but you can disable driver signature enforcement a.k.a. put your system into tets mode than the driver does not do any caller verfiication

**Comment by isaak654** [comment]
Imho this issue still exists.. even after enabling test mode, SbieSvc service will refuse to start unless you manually change MyIsCallerSigned to always return TRUE: https://github.com/sandboxie-plus/Sandboxie/issues/2880#issuecomment-1533940665

**Comment by DavidXanatos** [comment]
It definitely returns true when it detects that the windows is runnign in test signign mode, see https://github.com/sandboxie-plus/Sandboxie/blob/0dedccfc37a4f2e23605000a0f0cdfc516e6df57/Sandboxie/core/drv/util.c#L353 its on of the most tested feature in sandboxie as I always run all my test builds unsigned.
I have replied  in the other thread and will close this one.
