### ISSUE TITLE
Hi, I use WindowFX from Stardock and I wondering if anyone had a Template that would make it work on Sandboxed windows?

### ISSUE THREAD

**Issue by firepacket** [sandboxie-plus/Sandboxie#1633]
### What happened?

[WindowFX](https://www.stardock.com/products/windowfx/) is a program made by Stardock which also makes ObjectDock and Windows Blinds (which DO have templates), but there is no template for [WindowFX](https://www.stardock.com/products/windowfx/).

[WindowFX](https://www.stardock.com/products/windowfx/) animates your windows to add special effects to movement, focus, opening, closing, and context menus. Obviously Sandboxie is protecting the process rendering from being manipulated.

I've tried everything, OpenIpcPath, OpenPipePath, OpenFilePath, etc.

I've tried every process and pipe I see [WindowFX](https://www.stardock.com/products/windowfx/) using, tried to find similar programs I could copy, but nothing allows [WindowsFX](https://www.stardock.com/products/windowfx/) to work on Sandboxed windows. I have checked the trace log and see a WinClass WFX_DARKEN being blocked but that's it. I've seen a few pipes made by WFX but they did nothing.

I am not sure how the software works so I don't know what to look for.

If someone has a [WindowFX](https://www.stardock.com/products/windowfx/) template they could share with me, or give me better instructions on how to find the right mechanism to allow it, I would be most grateful.

Thanks.

### To Reproduce

Install [WindowFX](https://www.stardock.com/products/windowfx/) they offer a free trial.

Notice that none of the effects work on sandboxed windows, although the slide effect and transparency effect seem to work.

### Expected behavior

I would like my sandbox windows to move around and behave like my un-sandbox windows as configured in Windows FX

### What is your Windows edition and version?

Windows 10 x64 1809 LTSC

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.8 x64

### Is it a regression?

No

### List of affected browsers

Firefox, Chrome, and all sandboxed windows.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No I have most default security settings turned off.

### Crash dump

No crashes

### Sandboxie.ini configuration

```shell
[GlobalSettings]
AlertProcess=firefox.exe
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=y
EnableWin32kHooks=y
EditAdminOnly=y
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsLive
Template=OfficeLicensing

[UserSettings_08DA01C0]
SbieCtrl_UserName=user
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_TerminateWarn=y
SbieCtrl_HideWindowNotify=n
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=n
SbieCtrl_AddSendToMenu=y
SbieCtrl_WindowCoords=126,104,1237,616
SbieCtrl_ActiveView=40022
SbieCtrl_AlwaysOnTop=y
SbieCtrl_TerminateNotify=y
SbieCtrl_ExplorerNotify=y
SbieCtrl_ExplorerWarn=n
SbieCtrl_EditConfNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_ProcSettingsNotify=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_ShortcutNotify=y
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_ShouldDeleteNotify=y
SbieCtrl_ShowWelcome=y
SbieCtrl_AutoApplySettings=y
SbieCtrl_BoxExpandedView=Firefox,Isolation,Malware
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_ProcessViewColumnWidths=250,70,300
BoxDisplayOrder=Malware
SbieCtrl_HideMessage=1307, rundll32.exe [Firefox]
SbieCtrl_HideMessage=1307, iexplore.exe [Firefox]
SbieCtrl_HideMessage=1308, RuntimeBroker.exe [Firefox]

[Chrome]
Enabled=y
AutoRecover=y
RecoverFolder=C:\Users\User\Dropbox\CSharp Projects\packages
RecoverFolder=C:\Users\User\Downloads\*
RecoverFolder=C:\Users\User\Desktop\
RecoverFolder=C:\Users\User\ungoogled-chromium-portable\*
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,1
Template=TaskbarJumpList
Template=Ungoogled_Force
Template=Ungoogled_Bookmarks_DirectAccess
Template=Ungoogled_History_DirectAccess
Template=Ungoogled_Cookies_DirectAccess
Template=Ungoogled_Passwords_DirectAccess
Template=Ungoogled_Preferences_DirectAccess
Template=Ungoogled_Sync_DirectAccess
Template=Ungoogled_Profile_DirectAccess
Template=BlockTelemetry
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=-1
OpenFilePath=C:\Program Files\WinRAR\WinRAR.exe
OpenFilePath=C:\Program Files (x86)\uTorrent\uTorrent.exe
OpenFilePath=C:\Users\User\Downloads\*
OpenFilePath=C:\Users\User\ungoogled-chromium-portable\*
OpenFilePath=C:\Users\User\Desktop
ForceProcess=chrome.exe
ForceProcess=ungoogled-chromium-portable.exe
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
HideOtherBoxes=y
OpenDevCMApi=y
OpenSamEndpoint=y
OpenLsaEndpoint=y
ShowForRunIn=n
FakeAdminRights=y
ProcessGroup=<StartRunAccess>,WinRAR.exe,ungoogled-chromium-portable.exe,chrome.exe
NeverDelete=y
ClosedIpcPathDisabled=!<StartRunAccess>,*
```

**Comment by firepacket** [comment]
I just upgraded to 1.0.11 and now everything has broken. I am getting spammed with SBIE2101 from both my Chrome and Firefox boxes and I believe it has something to do with WindowsFX because it happens when I move the windows, the yellow border lags, and sandboxie freezes.

It is completely unusable now.

Someone please help, I really hope I can downgrade. :-(

**Comment by DavidXanatos** [comment]
can you test which exact version of sandboxie introduced the issue?
ALso yea you can up and down grade mostly as you like

**Comment by firepacket** [comment]
Unfortunately I am very scared to try. Upgrading destroyed my portable browser boxes for both chrome and firefox that I had properly pinned on my taskbar and messed with my complicated array of plugins, it took  me forever to fix. What does SBIE2101 mean? I can't find it anywhere it only goes up to SBIE2102.

I actually noticed that when I ran explorer inside a box, then right clicked to open a CMD that window was fully accessible to WindowFX and would move around properly.

I will try to upgrade to 1.0.9 and see how that goes.

**Comment by DavidXanatos** [comment]
I think there must be something more screwed up with your configuration, I have installed the tool in my test VM and it works fine, even most of teh functionality works on sandboxed programs for me, transparency and alike, indeed animation does not, but thats the only thing that seams not to work on sandboxed programs.

**Comment by firepacket** [comment]
Oh, yeah that's right its the animations. The sliding effect and the transparency works, but I couldn't figure out how to get the windows to animate.

There's no way to fix that it just doesn't support animations?

**Comment by isaak654** [comment]
> There's no way to fix that it just doesn't support animations?

Did you try also the special forms of OpenWinClass?
https://sandboxie-plus.github.io/sandboxie-docs/Content/OpenWinClass.html

**Comment by firepacket** [comment]
I did. The ones I saw in trace were WFX_DARKEN and WFX_EXPANDER2 I also opened the pipe WFXServer1* and access to the WindowFX appdir and reg keys which it appeared to need in trace and aaaa aaaa

**Comment by firepacket** [comment]
Success!

I finally got animations working in the Standard Isolation Sandbox by doing everything I mentioned and then adding OpenWinClass * for all programs finally did it and $ for explorer.exe. It removes the [#] indicator in the title but now at least animations are working.

It doesn't need any pipe access it just needs full access to that registry key and the program files folder and OpenWinClass * and I think $ for explorer.exe too.


But all WindowFX effects vanish if I try to use it with Privacy mode or Drop Admin Rights, so that's my next challenge.
