### ISSUE TITLE
can't install Zebra designer 3 using sandboxie

### ISSUE THREAD

**Issue by RobbiNespu** [sandboxie-plus/Sandboxie#1634]
### What happened?

I getting installation problem. Image attached
![image](https://user-images.githubusercontent.com/3077875/154219462-927cd233-8397-4658-9d24-35d736907fb8.png)

### To Reproduce

1. download Zebra design https://www.zebra.com/us/en/support-downloads/printer-software/zebra-designer-3-downloads.html (
zebradesigner3-322611.exe)
2. install via sandboxie
3. Getting error when installing

### Expected behavior

flawless installation

### What is your Windows edition and version?

Windows 10.0.19044 N/A Build 19044

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

n/a

### What version of Sandboxie are you running?

5.55.11

### Is it a regression?

m/a

### List of affected browsers

n/a

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
enable this and try again:
![grafik](https://user-images.githubusercontent.com/3890945/154350345-b5551184-82fe-40a4-a901-ad012d627c0e.png)
