### ISSUE TITLE
SBIE2205 Service not implemented: DDE 000003E6

### ISSUE THREAD

**Issue by mrvanity** [sandboxie-plus/Sandboxie#1635]
### What happened?

There is an sandboxed application running normally. In a menu an additional exe is called (sisnprex.exe)

When it is called there is an error windows popping with the following error message.
`sisnprex.exe (31672): SBIE2205 Service not implemented: DDE 000003E6`

Sandboxie.ini is as follows
`#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=AdobeLicensing

[UserSettings_08780188]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=n

[New_Box]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
OpenWinClass=#32769
OpenProtectedStorage=y
CopyLimitKb=-1
`

The tracelog is the one below:
`
|Process|                                    |Type|         |Status|    |Value|                                                                                                 

umbrella.exe (25100, 16156) - 13:48:12.862   Ipc (U)                    \Sessions\108\BaseNamedObjects\-SEM32-SISNPREV                                                          
umbrella.exe (25100, 16156) - 13:48:12.873   Debug (U)      Trace       CreateProcess: D:\SIS\bin\sisnprex.exe (D:\SIS\BIN\SISNPREX.EXE -SEM32-SISNPREV NPRSECURITY ο); err=0   
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls\wow64.dll                                                                                    
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls\wow64win.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls\kernel32.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls32\kernel32.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls\user32.dll                                                                                   
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls\wow64cpu.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls32\kernel32.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls32\kernelbase.dll                                                                             
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \Sessions\108\Windows\SharedSection                                                                     
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \Sessions\108\Windows\ApiPort                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (D)        Open        \KnownDlls32\PSAPI.DLL                                                                                  
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom13                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\HarddiskVolume5                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\HarddiskVolume2                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom0                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom1                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom2                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom3                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom4                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom5                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom6                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom12                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom7                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom8                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom9                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom10                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom14                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom15                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom11                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.873   Drive (U)                  \Device\CdRom16                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.873   Ipc (U)                    \Sessions\108\BaseNamedObjects\SBIE_BOXED_DummyEvent_26984                                              
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (U)                    \Sessions\108\BaseNamedObjects\SboxSession                                                              
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\MSVCRT.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\user32.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\win32u.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\gdi32.dll                                                                                  
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\gdi32full.dll                                                                              
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\msvcp_win.dll                                                                              
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\ucrtbase.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\SHELL32.dll                                                                                
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\SHLWAPI.dll                                                                                
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\OLEAUT32.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\combase.dll                                                                                
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\rpcrt4.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\Setupapi.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\cfgmgr32.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.884   Ipc (D)        Open        \KnownDlls32\bcrypt.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.895   Ipc (U)                    \RPC Control\epmapper                                                                                   
sisnprex.exe (26984, 24536) - 13:48:12.895   Ipc (D)        Open        \KnownDlls32\sechost.dll                                                                                
sisnprex.exe (26984, 24536) - 13:48:12.895   Ipc (D)        Open        \KnownDlls32\ole32.dll                                                                                  
sisnprex.exe (26984, 24536) - 13:48:12.895   Ipc (D)        Open        \KnownDlls32\advapi32.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.906   Ipc (D)        Open        \KnownDlls32\SHCORE.dll                                                                                 
sisnprex.exe (26984, 24536) - 13:48:12.916   Ipc (D)        Open        \KnownDlls32\IMM32.dll                                                                                  
sisnprex.exe (26984, 24536) - 13:48:12.916   Ipc (U)        Open        \RPC Control\SbieSvcPort                                                                                
sisnprex.exe (26984, 24536) - 13:48:12.916   Pipe (U)                   \Device\DeviceApi                                                                                       
sisnprex.exe (26984, 24536) - 13:48:12.916   Pipe (U)                   \Device\KsecDD                                                                                          
sisnprex.exe (26984, 24536) - 13:48:12.927   Ipc (D)        Open        \KnownDlls32\COMDLG32.dll                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.937   WinClass (U)   (2)         PM_Frame                                                                                                
sisnprex.exe (26984, 24536) - 13:48:12.937   WinClass (U)               PM_Dialog                                                                                               
sisnprex.exe (26984, 24536) - 13:48:12.937   WinClass (U)               PM_BitmapButton                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.937   WinClass (U)               CdlgModelessPopup                                                                                       
sisnprex.exe (26984, 24536) - 13:48:12.937   WinClass (U)               NotebookWrapper                                                                                         
sisnprex.exe (26984, 24536) - 13:48:12.937   WinClass (U)               WC_WORMHOLE                                                                                             
sisnprex.exe (26984, 24536) - 13:48:12.937   Ipc (U)                    \Sessions\108\BaseNamedObjects\Win32_MuxWaitSemList                                                     
sisnprex.exe (26984, 24536) - 13:48:12.937   Ipc (U)                    \Sessions\108\BaseNamedObjects\MuxWaitSemListReadEvent                                                  
sisnprex.exe (26984, 24536) - 13:48:12.937   Ipc (U)                    \Sessions\108\BaseNamedObjects\MuxWaitSemListWriteEvent                                                 
sisnprex.exe (26984, 24536) - 13:48:12.937   Ipc (U)                    \Sessions\108\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs                                     
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (U)                    \Sessions\108\BaseNamedObjects\-SEM32-SISNPR                                                            
sisnprex.exe (26984, 2848) - 13:48:12.948    Ipc (D)                    \Sessions\108\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch                                
sisnprex.exe (26984, 38268) - 13:48:12.948   Ipc (U)        Open        \RPC Control\SbieSvcPort                                                                                
sisnprex.exe (26984, 38268) - 13:48:12.948   WinClass (U)   (2)         ICL Frame0                                                                                              
sisnprex.exe (26984, 38268) - 13:48:12.948   Ipc (U)        Open        \ThemeApiPort                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.948   WinClass (U)   (2)         ICL Frame1                                                                                              
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (U)                    \Sessions\108\BaseNamedObjects\windows_shell_global_counters                                            
sisnprex.exe (26984, 38268) - 13:48:12.948   Ipc (D)        Open        \KnownDlls32\MSCTF.dll                                                                                  
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (U)        Open        \Sessions\108\Windows\ThemeSection                                                                      
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (U)        Open        \Windows\Theme3924390650                                                                                
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (U)        Open        \Sessions\108\Windows\Theme2646130874                                                                   
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:168:WilStaging_02                                        
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02                                              
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:168:WilStaging_02_p0                                     
sisnprex.exe (26984, 24536) - 13:48:12.948   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02_p0                                           
sisnprex.exe (26984, 38268) - 13:48:12.948   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.948   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 38268) - 13:48:12.948   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.948   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 38268) - 13:48:12.948   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.948   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.959   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:168:WilStaging_02                                        
sisnprex.exe (26984, 24536) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02                                              
sisnprex.exe (26984, 24536) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02_p0                                           
sisnprex.exe (26984, 38268) - 13:48:12.959   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:168:WilStaging_02                                        
sisnprex.exe (26984, 24536) - 13:48:12.959   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:64:WilError_03                                           
sisnprex.exe (26984, 38268) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02                                              
sisnprex.exe (26984, 24536) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:64:WilError_03                                                 
sisnprex.exe (26984, 38268) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02_p0                                           
sisnprex.exe (26984, 24536) - 13:48:12.959   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:64:WilError_03_p0                                        
sisnprex.exe (26984, 24536) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:64:WilError_03_p0                                              
sisnprex.exe (26984, 38268) - 13:48:12.959   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:64:WilError_03                                           
sisnprex.exe (26984, 38268) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:64:WilError_03                                                 
sisnprex.exe (26984, 38268) - 13:48:12.959   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:64:WilError_03_p0                                              
sisnprex.exe (26984, 38268) - 13:48:12.970   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.970   WinClass (U)   Open (2)    Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 38268) - 13:48:12.970   WinClass (U)   Open (2)    Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.970   WinClass (U)   Open        Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 38268) - 13:48:12.970   Ipc (U)                    \Sessions\108\BaseNamedObjects\/BTRV/SEM32/ELINK.SEM                                                    
sisnprex.exe (26984, 24536) - 13:48:12.970   WinClass (U)   (3)         ICLWC_OBJECT                                                                                            
sisnprex.exe (26984, 24536) - 13:48:12.970   WinClass (U)   Open (3)    Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:12.970   Ipc (D)        Open        \KnownDlls32\bcryptPrimitives.dll                                                                       
sisnprex.exe (26984, 24536) - 13:48:12.981   Pipe (U)                   \Device\CNG                                                                                             
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\MSCTF.Asm.MutexDefault108                                                
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\CTF.AsmListCache.FMPDefault108                                           
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\CicLoadWinStaWinSta0                                                     
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\MSCTF.CtfMonitorInstMutexDefault108                                      
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \RPC Control\lsapolicylookup                                                                            
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \BaseNamedObjects\msctf.serverDefault108                                                                
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:168:WilStaging_02                                        
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02                                              
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02_p0                                           
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\BMKDE/CLNT/SESSION/BUFFER                                                
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\BMKDE/CLNT/SESSION/SUBMIT                                                
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\BMKDE/CLNT/SESSION/RETURN                                                
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\BMKDE/CLNT/SESSION                                                       
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/INIT_INFO/0                                                  
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/SEM32/SUBMIT39564                                            
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/SEM32/RETURN39564                                            
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/BUFFER39564                                                  
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)                    \Sessions\108\BaseNamedObjects\BMKDE/GlobalCsSem                                                        
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/SEM32/BUFFER39564                                            
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/SEM32/SUBMIT36076                                            
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/SEM32/RETURN36076                                            
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/BUFFER36076                                                  
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)                    \Sessions\108\BaseNamedObjects\BMKDE/GlobalCsSem                                                        
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)                    \Sessions\108\BaseNamedObjects\/BMKDE/CLNT/SEM32/BUFFER36076                                            
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)        Open        \Security\LSA_AUTHENTICATION_INITIALIZED                                                                
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)        Open        \RPC Control\lsasspirpc                                                                                 
sisnprex.exe (26984, 38268) - 13:48:12.981   WinClass (U)   (2)         ICL Frame2                                                                                              
sisnprex.exe (26984, 38268) - 13:48:12.981   WinClass (U)               ICLWC_OBJECT                                                                                            
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (D)        Open        \KnownDlls32\WS2_32.dll                                                                                 
sisnprex.exe (26984, 38268) - 13:48:12.981   WinClass (U)   Open (3)    Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\MSCTF.Asm.MutexDefault108                                                
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\CTF.AsmListCache.FMPDefault108                                           
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\CicLoadWinStaWinSta0                                                     
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)        Open        \Sessions\108\BaseNamedObjects\MSCTF.CtfMonitorInstMutexDefault108                                      
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (U)        Open        \BaseNamedObjects\msctf.serverDefault108                                                                
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \BaseNamedObjects\CoreMessagingRegistrar                                                                
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:168:WilStaging_02                                        
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02                                              
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02_p0                                           
sisnprex.exe (26984, 24536) - 13:48:12.981   WinClass (U)               UserAdapterWindowClass                                                                                  
sisnprex.exe (26984, 38268) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\-SEM32-SISNPR                                                            
sisnprex.exe (26984, 24536) - 13:48:12.981   WinClass (U)               UserAdapterWindowClass                                                                                  
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \BaseNamedObjects\[CoreUI]-PID(26984)-TID(24536) 2d71d9fa-1018-46d1-a0af-08065cf75da3                   
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)        Open        \BaseNamedObjects\[CoreUI]-PID(12664)-TID(19476) d4bd64f6-7acb-4ca9-8b5f-17ad3e932f1a                   
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (U)                    \Sessions\108\BaseNamedObjects\Local\SM0:26984:168:WilStaging_02                                        
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02                                              
sisnprex.exe (26984, 24536) - 13:48:12.981   Ipc (D)                    \Sessions\108\BaseNamedObjects\SM0:26984:168:WilStaging_02_p0                                           
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (2)         ICL Container                                                                                           
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (2)         ICL Container Edge                                                                                      
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (2)         ICL Container Title                                                                                     
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (2)         ICL Container LDetail                                                                                   
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (2)         ICL Container RDetail                                                                                   
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (2)         ICL Container LColumn Title                                                                             
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (2)         ICL Container RColumn Title                                                                             
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Notebook                                                                                            
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Notebook Page                                                                                       
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Notebook Page Button                                                                                
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Notebook Scroll Tab                                                                                 
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Slider                                                                                              
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Circular Slider                                                                                     
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Spin Button                                                                                         
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Spin Button Arrows                                                                                  
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Notebook                                                                                            
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Notebook Page Button                                                                                
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)               ICL Notebook Page                                                                                       
sisnprex.exe (26984, 24536) - 13:48:13.013   WinClass (U)   (3)         ICL Notebook Scroll Tab                                                                                 
sisnprex.exe (26984, 24536) - 13:48:13.024   WinClass (U)               ICLWC_OBJECT                                                                                            
sisnprex.exe (26984, 24536) - 13:48:13.024   WinClass (U)   Open (3)    Shell_TrayWnd                                                                                           
sisnprex.exe (26984, 24536) - 13:48:13.024   WinClass (U)               MainScreen                                                                                              
sisnprex.exe (26984, 24536) - 13:48:13.035   Ipc (D)                    \Sessions\108\BaseNamedObjects\-SEM32-SISNPREV                                                          
sisnprex.exe (26984, 24536) - 13:48:15.456   WinClass (U)               TreeviewToolTipClass                                                                                    
sisnprex.exe (26984, 24536) - 13:48:15.456   Ipc (U)        (3)         \Sessions\108\BaseNamedObjects\BMKDE/GlobalCsSem                                                        `

My regards.

### Expected behavior

No error message, and the exe to load properly

### What is your Windows edition and version?

Windows 10 Pro 20H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender (disabled)

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.11 x64

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=AdobeLicensing

[UserSettings_08780188]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=n

[New_Box]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
OpenWinClass=#32769
OpenProtectedStorage=y
CopyLimitKb=-1
```

**Comment by isaak654** [comment]
Could you provide an installer link to the program?

**Comment by mrvanity** [comment]
I will try to upload.
A couple of iso's are needed to be able to install the software.

Thank you.
