### ISSUE TITLE
Add a donation link towards an EV-Code Signing Certificate

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#164]
In order to fix #95 how about a way to directly donate to get that certificate? While greatly appreciated, the patreon.com link is a general donation to all your programs in general, not even necessarily to Sandboxie.

How much does such a signature cost?

**Comment by DavidXanatos** [comment]
It costs between ~400 and 1000€/year and it can only be issued to companies, meaning to this costs additional costs of creating a shell company must be added.

I'm currently trying to get such a certificate with the help of an existing company, I hope it will work as creating and maintaining a shell company capable of getting an EV certificate is expensive.

You can donate using the paypal link on my homepage and write in the message field that its for the cert explicitly.

**Comment by lwcorp** [comment]
May you share how you ended up solving it in https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.5.0?

**Comment by DavidXanatos** [comment]
I got a company of a friend to get the EV cert for me, as simple as that, just that nothing about that was simple. LOL

**Comment by lwcorp** [comment]
> I got a company of a friend to get the EV cert for me, as simple as that, just that nothing about that was simple. LOL

Then you may want to close this ticket, unless next year you'll need it again.
But does it mean Sandboxie's EXE files and drivers have it written that they belong to your friend's company?

Also, is it worth it to upgrade just to have it signed?

**Comment by DavidXanatos** [comment]
> But does it mean Sandboxie's EXE files and drivers have it written that they belong to your friend's company?
No only that they take the responsibility for them not being purposefully malicious.

> Also, is it worth it to upgrade just to have it signed?
This question does not pose itself as the release also includes many other improvements, so its worth it in any case.
