### ISSUE TITLE
SBIE2101 - can't launch programs

### ISSUE THREAD

**Issue by Aspector1** [sandboxie-plus/Sandboxie#1644]
### What happened?

18:10:02.466   WerFault.exe (14752): SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1   
18:10:03.472   WerFault.exe (14752): SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1   

### Expected behavior

running programm

### What is your Windows edition and version?

Windows 11 Build 22557.1

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

nothing

### What version of Sandboxie are you running?

Sandboxie Plus v1.0.11

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
Which program, for example?

**Comment by SimpleJack** [comment]
For me it is anything. Browsers like Chromium Edge, Chrome, Firefox, Windows Explorer.

**Comment by DavidXanatos** [comment]
did you try a clean install without any old config?
