### ISSUE TITLE
Chrome Crashing

### ISSUE THREAD

**Issue by qazero** [sandboxie-plus/Sandboxie#1645]
### What happened?

I would like to resurrect issue [#198](https://github.com/sandboxie-plus/Sandboxie/issues/198#issuecomment-1010155008)
This is still a problem and wondering if you could please fix it?

### To Reproduce

The workaround `ClosedFilePath=*\Windows.System.Launcher.dll` isn't working anymore. 
I noticed that Brave web browser (chromium based) automatically closes randomly when going to app.plex.tv. 
Sometimes it works and sometimes it doesn't. Any ideas what may be causing it?

### Expected behavior

Not crash

### What is your Windows edition and version?

Windows 10 Pro

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie 5.55.8

### List of affected browsers

Brave: 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=RpcPortBindings
Template=Windows10CoreUI
Template=FireFix_for_Win7
Template=Kaspersky
Template=InternetDownloadManager
Template=AdobeDistiller
Template=Avira_Antivirus
Template=KeyScrambler
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
ActivationPrompt=n
ClosedFilePath=*\Windows.System.Launcher.dll
SpecialImage=firefox,brave.exe

[DefaultBox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=Firefox_Force
Template=Chrome_Force
Template=IExplore_Favorites_RecoverFolder
Template=IExplore_Force
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%Desktop%
BorderColor=#00FFFF,off
Enabled=y
BoxNameTitle=-
AutoDelete=y
NeverDelete=n
ForceProcess=brave.exe
ForceProcess=microsoftedge.exe

[UserSettings_08DA01C0]

SbieCtrl_UserName=user
SbieCtrl_NextUpdateCheck=1645393137
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_WindowCoords=-2660,829,1553,884
SbieCtrl_ActiveView=40021
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_HideMessage=1320,[19748]
SbieCtrl_HideMessage=1319,[19748]
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_BoxExpandedView=DefaultBox,Test

[Test]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
```
```


### Sandboxie-Plus.ini configuration (for Plus interface issues)

_No response_

**Comment by qazero** [comment]
Pls help!!

**Comment by DavidXanatos** [comment]
I still cant reproduce the issue the page loads fine on my system, please test a clean install
