### ISSUE TITLE
Graphic device is not available

### ISSUE THREAD

**Issue by 53jk1** [sandboxie-plus/Sandboxie#1647]
### What happened?

I wanted to run an application that requires a graphics device.

### To Reproduce

1. Started App
2. Got error from application "graphic device is not available".

### Expected behavior

Just run application

### What is your Windows edition and version?

Windows 11 Pro 10.0.22557

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus v1.0.11

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
Please mention the program in question and the download link if it's publicly available

**Comment by 53jk1** [comment]
Figured it by myself, can't give you the program. :(

Reset settings of AMD Drivers.
Turned on in Programs and Features
Windows Sandbox.
Checked is vGPU is turned on.

in cmd prompt in Sandboxie check if you "dxdiag" recognizing your GPU, it should
