### ISSUE TITLE
What are the exact relations between Sandboxie Plus and Sandboxie?

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#165]
This is somewhat related to #62 but more focused about the differences from Sandboxie:

When I install SandboxieInstall-Y.exe it takes over the official installation of Sandboxie, as if it was an official upgrade.

But what shall happen if I install Sandboxie-Plus-X.exe (or run it in portable mode) instead? Will it be installed as a separate program with another name, paths (including %SystemDrive%\Sandbox), icon, etc.?

If so, can both be installed at the same time?

**Comment by DavidXanatos** [comment]
SandboxieInstall-Y.exe is not aware of sandboxie plus

If you install Sandboxie-Plus-X.exe it will uninstall the classical SandboxieInstall-Y.exe first.

If you run Sandboxie-Plus in portable mode it will try to use the driver and service of the pre existing classical installation, if present, of not it will load an own driver.

**Comment by DavidXanatos** [comment]
since there are no more questions I'll close this
