### ISSUE TITLE
Windows Explorer.exe unresponsive 

### ISSUE THREAD

**Issue by kouhe3** [sandboxie-plus/Sandboxie#1652]
### What happened?

Can't run explorer.exe.
<img width="826" alt="搜狗截图20220223214524" src="https://user-images.githubusercontent.com/25522053/155341403-b61305ab-860e-4fa5-98df-a93b45a125c5.png">

### To Reproduce

Just run explorer.exe in DefultBox.

### Expected behavior

i can see my files.

### What is your Windows edition and version?

Windows 11 Pro workstation 21H2 22000.527

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.10 64-bit

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Trace log

https://pastebin.com/8gBP2Q5y

**Comment by isaak654** [comment]
#1127
