### ISSUE TITLE
plus and classic: add option to enable/disable immediate recovery to each box in tray icon

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1653]
### Is your feature request related to a problem or use case?

yes

### Describe the solution you'd like

add option to enable/disable immediate recovery to each box in tray icon

**Comment by DavidXanatos** [comment]
you mean fro the menu directly?

**Comment by diieg707** [comment]
> you mean fro the menu directly?

 add enable/disable immediate recovery in the tray icon to each box
![Untitled](https://user-images.githubusercontent.com/54504707/158021299-af2876af-6968-4973-9b7b-90ae6a67855c.png)

**Comment by diieg707** [comment]
> you mean fro the menu directly?

 add option enable/disable immediate recovery in the tray icon to each box
![Untitled](https://user-images.githubusercontent.com/54504707/158021902-e24acb67-4e0e-42f6-aae7-29fc5c68e985.png)

**Comment by diieg707** [comment]
@DavidXanatos any hope this request?, it's a fast way to enable/disable immediate recovery option

**Comment by diieg707** [comment]
my suggestion is that you add an option in the front layer in order to disable immediate recovery globaly, and also add the option to each box in the tray, like the first picture i've sent
![Untitled](https://user-images.githubusercontent.com/54504707/172860132-f1584bd5-fe81-4a90-9d89-a01275ce9c35.jpg)

**Comment by DavidXanatos** [comment]
I put it here: 
![grafik](https://user-images.githubusercontent.com/3890945/172890947-911578f1-6fea-4ade-af2b-0a48f989b6a9.png)

and i think this is a good place where it will stay.

**Comment by diieg707** [comment]
> I put it here: ![grafik](https://user-images.githubusercontent.com/3890945/172890947-911578f1-6fea-4ade-af2b-0a48f989b6a9.png)
> 
> and i think this is a good place where it will stay.

That should do it,

What about an option where the ( terminate all processes) is to disable immediate recovery globally?

**Comment by diieg707** [comment]
let me clarify a bit.
my suggestion you add 2 options:
one in the main system tray menu called "disable immediabe recovery globaly" in order to disable all window from all boxes to show up like in the pic below.
and the second one is the one you just did, add an option to disable immediate recovery to each box.

![Untitled](https://user-images.githubusercontent.com/54504707/173177706-659df6bb-cd30-4aef-bf34-3513d8577457.jpg)

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/173190951-39cee3fd-b0c1-4a1f-aadb-d4fbaa20c9d5.png)

**Comment by diieg707** [comment]
> ![grafik](https://user-images.githubusercontent.com/3890945/173190951-39cee3fd-b0c1-4a1f-aadb-d4fbaa20c9d5.png)

Yes, just like that

**Comment by DavidXanatos** [comment]
yes
