### ISSUE TITLE
When starting Sandboxie-Plus, the nssm.exe program is automatically executed and a pop-up window appears.

### ISSUE THREAD

**Issue by Vzz1c** [sandboxie-plus/Sandboxie#1659]
### What happened?

At first I thought it was part of the program, when I removed the nssm.exe program this does not happen, I think this is a strange error

### To Reproduce

1. First of all, the computer has installed the nssm program, and it exists in the path environment variable
2. Click on SandMan.exe and the nssm help window will pop up

### Expected behavior

None

### What is your Windows edition and version?

win10 21H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

windows defender

### What version of Sandboxie are you running?

sandboxie plus 1.0.11

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
what is  nssm.exe where can it be downloaded?

**Comment by isaak654** [comment]
Most likely related to this: https://nssm.cc/download

**Comment by Vzz1c** [comment]
> https://nssm.cc/download

I installed it using the "scoop" package manager
scoop install nssm
This will be automatically added to the environment variables.
Then when I click on sandboxie, it automatically starts the nssm program and brings up the help window, which is the same as if I had clicked on nssm manually.
This is really some kind of strange error

**Comment by Vzz1c** [comment]
I am running sandboxie in portable mode

**Comment by Vzz1c** [comment]
For some reason, I reinstalled the windows 10 system, but the problem still exists until v1.0.15
