### ISSUE TITLE
Spotify (Electron) flickers on start, then crashes

### ISSUE THREAD

**Issue by Vinyzu** [sandboxie-plus/Sandboxie#1663]
### What happened?

Hello, today i wanted to create a new sandbox and run spotify in it. after reloading the config however when i run spotify it crashes

### To Reproduce

Im using this python code:
```
import subprocess, configparser, threading,  time

config = configparser.ConfigParser()
config.optionxform = str
config["SpotifyTest"] = {'Enabled':'y','ConfigLevel':'9','PreferExternalManifest':"y",'AutoRecover':'n',"BlockNetworkFiles": "y",'BorderColor':'#00FFFF:ttl:6','BoxNameTitle':'y','DropAdminRights':'y'}
with open(r'C:\Windows\Sandboxie.ini', 'a') as configfile:
  config.write(configfile)

subprocess.call('"C:\Program Files\Sandboxie\Start.exe"  /reload', False)
time.sleep(5)
threading.Thread(target=subprocess.call, args=(r'"C:\Program Files\Sandboxie\Start.exe" /box:StokifyTest "yourSpotifyPath"', False)).start()
```

### Expected behavior

I want it to run VÖV haha

### What is your Windows edition and version?

Windows 10 Pro 10.0.22

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Windows Defender, Norton

### What version of Sandboxie are you running?

Sandboxie v5.55.11

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
[SpotifyTest]
Enabled=y
ConfigLevel=9
AutoRecover=n
BlockNetworkFiles=y
BorderColor=#00FFFF:ttl:6
BoxNameTitle=y
DropAdminRights=y
```

**Comment by Vinyzu** [comment]
Solved, ill send the solution later

**Comment by DavidXanatos** [comment]
> 

so what was the solution?

**Comment by Vinyzu** [comment]
sry for the late response:
```py
_1, _2 = r"C:\Program Files\Sandboxie\SbieIni.exe", "C:\Program Files\Sandboxie\Start.exe"
subprocess.call(f"{_1} set %BOX_NAME% Enabled y", False)
```
