### ISSUE TITLE
LINE does not work on Windows 10 2004

### ISSUE THREAD

**Issue by Wintiger0222** [sandboxie-plus/Sandboxie#167]
![Cap 2020-10-26 21-54-56-521](https://user-images.githubusercontent.com/24960466/97174854-fde44300-17d5-11eb-98a7-2933a38b0391.png)
Left one is not on Sandboxie one
Right is on Sandboxie.

It worked properly on Windows 10 1909 but get freeze on Windows 10 2004
I now using Sandboxie-Plus v0.4.2 Driver v5.43.5 64bit
Also same thing happened at v5.31.1 64bit

**Comment by DavidXanatos** [comment]
And how is the version: 5.43.6
it fixes a critical chrome issue and this app looks like a PWA, so good chances this fixes it as well.

**Comment by Wintiger0222** [comment]
![image](https://user-images.githubusercontent.com/24960466/97242507-67486e00-1837-11eb-9a0f-cdec46280868.png)
I downgrade my windows to 1909 so I'll test later.

By the way, I installed sandboxie-plus v0.4.2 but why driver stuck at v5.43.5, not v5.43.6

**Comment by DavidXanatos** [comment]
The SbieDrv.sys File should have the right version of 5.43.6 the displayed version is always the last compatible version, i.e. I don't increment that internal version number when no changes were introduced that would break compatibility.

**Comment by Wintiger0222** [comment]
Then, it must be 5.43.6 version.

**Comment by games1tw** [comment]
Same as
OS:Windows 10 20H2
Version:Sandboxie 5.44.0 64bit
Issue:Line PC ver 6.3.2.2338 can't working

**Comment by DavidXanatos** [comment]
please see https://github.com/sandboxie-plus/Sandboxie/issues/228 the issue will be solved in the next build
