### ISSUE TITLE
[FR] Modify UUID of a DefaultBox

### ISSUE THREAD

**Issue by boromyr** [sandboxie-plus/Sandboxie#1672]
### Is your feature request related to a problem or use case?

No.

### Describe the solution you'd like

The proposed functionality consists in being able to modify or assign a customized UUID to each single Box, so as to deceive a program that is started in the virtual area to be in a "new PC".
It could be added in, for example: context menu DefaultBox -> virtual area options -> edit configuration -> new entry in .ini file "UUID = {number}

### Describe alternatives you've considered

In VMware there is an identical configuration, in the .vmx configuration file just edit the entry:
`uuid.bios = "56 4d 9b bc 6b 3d a5 12-7d 5d fc 18 59 43 a6 db"`

**Comment by DavidXanatos** [comment]
Sandboxie is not a virtual machine, and there is a myriad ways you can get unique identifiers querying windows API's
Please specify in which API calls you would like a fake value to be returned.

**Comment by boromyr** [comment]
I've done some research, but it's a very technical topic, and I'm not an experienced programmer. However, the cmd command I'm referring to is `wmic csproduct get uuid`, that would be the same commando `uuid.bios ` in VMware.

**Comment by DavidXanatos** [comment]
that sounds liek wim stuff, and this works by querying a host process so i dont think its doable with reasomable affort,
also we have a more broad feature request that may cover this usecase https://github.com/sandboxie-plus/Sandboxie/issues/1712
si I'll close this issue

**Comment by boromyr** [comment]
I've read post # 1712, and it fits my feature request perfectly. It seemed easier to change a single value than all the individual hardware values, but I think the final result is the same, or better.
