### ISSUE TITLE
How can i build this version while changing name of sandboxie dlls?

### ISSUE THREAD

**Issue by snareplug** [sandboxie-plus/Sandboxie#1674]
### What happened?

Can someone explain me how i could do this? i would help financial if you can give me live help to it or try to teach it pls

### Expected behavior

name change ofSbieSvc.exe SbieCtrl.exe SandboxieCrypto.exe driver and dlls

### What is your Windows edition and version?

win 10 64bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

none

### What version of Sandboxie are you running?

new

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
@DavidBerdik mentioned it in issue #115, but he didn't want to share the details publicly.

**Comment by DavidBerdik** [comment]
> @DavidBerdik mentioned it in issue #115, but he didn't want to share the details publicly.

At this point, I don't mind sharing the details, but I also don't know if it's worth the effort. Presumably, @snareplug's goal is to evade detection of Sandboxie for an application that they want to use it with, but that is what `HideHostProcess` is for.

**Comment by DavidXanatos** [comment]
you can change the names of most of the components in my_version.h

**Comment by DavidBerdik** [comment]
> you can change the names of most of the components in my_version.h

If he decides that he still wants to go through the renaming process, I will certainly help. I just don't know if it's worth the effort.
