### ISSUE TITLE
Patreon Update Certificate Emailer does not exclude Public Team Member Emails

### ISSUE THREAD

**Issue by irlcatgirl** [sandboxie-plus/Sandboxie#1676]
### What happened?

The Patreon Update Certificate Emailer at `https://xanasoft.com/get_cert.php?eMail=xa[redacted]d@gmail.com does not block me from entering a team member's public email address and getting an unpaid update certificate. Anyone who wants Patreon-exclusive updates and doesn't want to pay can access them this way. This is overall harmful to Sandboxie's mission so I am reporting it here.

### To Reproduce

1. Open `https://xanasoft.com/get_cert.php?eMail=[a certain team member]@gmail.com`  check
2. Copy the Certificate
```
NAME: [redacted]
DATE: 11.02.2022 
TYPE: PATREON-HUGE
UPDATEKEY: 6[redacted]7
SIGNATURE: 0[redacted]==
```
4. Add to program settings and enjoy the updates (pls don't actually do this if you don't pay for Sandboxie)

### Expected behavior

The certificate email should either refuse to provide a certificate OR email a one-time code or other single-use link to access the update certificate.

### What is your Windows edition and version?

Windows 10 Enterprise 21H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Idk whatever is newest

### Is it a regression?

No

### List of affected browsers

N/A

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

Not relavent to my request

### Crash dump

N/A

### Trace log

N/A

### Sandboxie.ini configuration

```shell
N/A
```

### Sandboxie-Plus.ini configuration (for Plus interface issues)

N/A

**Comment by eneerge** [comment]
I am a Patreon supporter, but when I download a certificate from that link and apply on version v1.0.12, it does not work.

**Comment by DavidXanatos** [comment]
fixed for thet case, but i guess i should overall swap this mechanism to send the cert to that email instead of offering a download
