### ISSUE TITLE
[Plus UI] AutoRunSoftCompat checkbox not working correctly

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1678]
This is the checkbox in question:
![compat_checkbox](https://user-images.githubusercontent.com/12372772/157967133-0392063e-d2c6-4131-b0f5-1be495edd31f.png)

There is no way to turn it on from the UI, it remains always off even after pressing OK button.

In order to reproduce it, you need to have `AutoRunSoftCompat=false` previously set on Sandboxie-Plus.ini.

If you replace it with `AutoRunSoftCompat=true`, the issue will be the opposite, that is, you can't turn off the checkbox from the UI at all.

**Comment by Coverlin** [comment]
> This is the checkbox in question: ![compat_checkbox](https://user-images.githubusercontent.com/12372772/157967133-0392063e-d2c6-4131-b0f5-1be495edd31f.png)
> 
> There is no way to turn it on from the UI, it remains always off even after pressing OK button.
> 
> In order to reproduce it, you need to have `AutoRunSoftCompat=false` previously set on Sandboxie-Plus.ini.
> 
> If you replace it with `AutoRunSoftCompat=true`, the issue will be the opposite, that is, you can't turn off the checkbox from the UI at all.

^small correction  `(n) = false = off = check`      `(y) = true = on = uncheck`    (classic)
The value can be set to true if you press ok or apply (while box uncheck) after switching to the Compatibility tab

If you press ok or apply without going to the tab in the ui it will set it to false (switching to the tab you can see the checkbox is checked) ... well that works

**Comment by mitchcapper** [comment]
Good bug although the suspected behavior isn't quite as thought.    Really the only issue (I believe) is the UI forgets to invert the value when it reads it.  This can be validated as the issue by opening the ui and hitting apply without changing anything. You will see it toggles back and forth.  Further if you open the ui and hit the checkbox twice (so it should be the same value) it will actually change the value, 3 times however does not change it.

PR should close.
