### ISSUE TITLE
Running SandMan without write ability on "Sandboxie-Plus.ini" cannot save Sanboxie Plus only settings to config (and fails silently)

### ISSUE THREAD

**Issue by mitchcapper** [sandboxie-plus/Sandboxie#1681]
### What happened?

The settings dialog has many settings and some of them do not save if you cannot write the .ini files.   Others however save without issue.  Checking the box under program control "Prevent the listed programs from starting..."  saves but "Open urls from this ui sandboxed" on general config does not.

These things all don't save for example: `AlwaysOnTop UiLanguage AutoRunSoftCompat RunInDefaultBox UseDarkTheme OpenUrlsSandboxed ShowNotifications EnablePanicKey WatchIni`

Looking at the code it is clear as to why,  the ones that do save call `theAPI->GetGlobalSettings()->SetBool` and the ones that don't call `theConf->SetValue`.   For those this is not immediately apparent for (me sandboxie noob), theConf settings are stored in the Plus ini vs the others stored in  the primary ini.  The primary ini is being written by the administrator running sandbox service, the plus it attempts to write directly.

Many (all?) the dismiss forever popups are also stored in the Plus UI and thus fail to save.

Now this may be as expected, run an app without write access to the config file of course it won't write it.  I would potentially argue that as a normal user is highly unlikely to tell which settings (that can sit side by side each other) will fail though, it is not a great experience.

Either way, the more pressing problem is that SandMan doesn't throw an error if it can't write the settings file.  The user in this case won't know something went wrong only some settings don't save.

The application uses the QT QSettings class for managing the ini and calls its sync() function to read and write these settings. The function does not return a success code and will silently fail.

To fix this we need to call ->status() which will return the first error encountered.  The other option is to call isWritable which should return false (from their documentation it sounds like this does _not_ update if the settings file changes its writable status after the class is created (but maybe on sync it updates).

The easiest path to a resolution is to just tell the user when an error happens.  The long term solution is probably to move the Plus settings to also be written by the service instead, so that all settings behave the same.

It may sound like an obtuse case of running into this problem but the easy way I ran into it was:
- Only use portable version for testing
- Copy portable to a admin write only path (say c:\program files)
- Start it up

As it actually handles most (all?) other non elevated calls properly one can assume everything is working.

### Expected behavior

Changing a setting saves to disk or throws an error

### What is your Windows edition and version?

10.0.19042.1526

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

n/a

### What version of Sandboxie are you running?

fd83db5202137741cfa20237725e98ac9d2692ae

### Is it a regression?

Yes?? Unclear as technically settings written by classic work as the service writes them, so depending if you consider plus new or just more settings:)

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
thanks for the verbose analysis, indeed the plus settings when fail should present an error.
it is not intended for the Sandboxie-Plus.ini to be in a location not writable by the user.
So I will add a warning pop up at start when this condition is encountered, or better in that case ignore the ini in the application folder and create one in the users profile under appdata/local... that is writable.

**Comment by mitchcapper** [comment]
Just keep in mind a user may not expect the portable version to write to AppData, and there may be further confusion with the main config file having changes but the plus one not (so may be good to not do that if in portable mode).    I think a warning though would be great.

**Comment by DavidXanatos** [comment]
well portable mode is defined by having the ini in the apps install location so I'll add a warnign and leave the resolution to the user

**Comment by sl2365** [comment]
I am having something similar to this. However, my issue is that I am running Sandboxie-Plus from a NON-write-protected environment. I am a new user and have little knowledge on how this app works. But only require it for basic usage anyway. But this having to set up on every launch is a bit of a put off.

Here's what I do:
> 1. Installed portable Sandboxie v1.14.10 on D drive. Win 11 23H2 x64. i7 11700, 24GB RAM.
> 2. Run Sandman.exe
> 3. Popup asks permission to create services. I check "do not show again" and click "Yes".
> 4. Popup asking where to store sandbox. I check "do not show again" and click "No". I've set sandbox to root of D drive.
> 5. Setup wizard shows. If I click "Next" and go through whole set up process, I still get the wizard every time. If I click "Cancel" and affirm not to show the wizard again, it still shows.
> 6. Move column "Path/Command Line" left next to "Name" column.
> 7. Click settings and select "Shell Integration/System Tray" then "On main window close" I select "Close" and tick the two boxes for "Minimise to tray" and "Single click open", then click "Apply" and "OK" to close window.
> 8. Click the Sandboxie main window close button, after setting the above, popup appears. Tick the box to not show again and then click "Yes" to confirm cleanup. This closes Sandboxie completely, ending the task in Windows Task Manager.

After saving the settings following the above procedure, nothing is saved and I literally have to go through the exact same steps on every start up.

Sandboxie.ini after performing all the above steps:
`#
# Sandboxie configuration file
#

[GlobalSettings]
FileRootPath=D:\Sandbox\%SANDBOX%
Template=Edge_Fix
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_0CF2022E]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
RecoverFolder=D:\Documents\- TEST -
BorderColor=#00ffff,on,5
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
`

Sandboxie-Plus.ini after performing all the above steps:
`[Options]
UiLanguage=en`
