### ISSUE TITLE
"check for updates" stuck at 1.0.10

### ISSUE THREAD

**Issue by divinity76** [sandboxie-plus/Sandboxie#1682]
### What happened?

when running 1.0.9 and checking for updates, it will inform us that 1.0.10 is available, and when running 1.0.10 and checking for updates, it will say "No new updates found, your Sandboxie-Plus is up-to-date."

meanwhile the newest version is 1.0.13

### Expected behavior

tell us that 1.0.13 is available

### What is your Windows edition and version?

Windows 10 x64

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.0.10

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
Ok I need to add a notification windows about that:
the server is always a few weeks behind to ensure no build with a bug will be advertized to the  broad public.

Now it seams build 1.0.13 is stabile so I'll update it, bit for build 1.0.14 I'll also add a messagebox to the update checker notifying that the results may differ from github and why.

**Comment by DavidXanatos** [comment]
should I add a setting to choose if you want delayed updates or always the newest even if it may have a major issue?

**Comment by divinity76** [comment]
an explanation is definitely warranted.

as for a setting, i certainly wouldn't mind, it works for LibreOffice: https://www.libreoffice.org/download/download/

maybe call it "bleeding-edge updates"?
