### ISSUE TITLE
Pathos Nethack (free roguelike game) crashes.

### ISSUE THREAD

**Issue by ImSpecial** [sandboxie-plus/Sandboxie#1687]
### What happened?

So this might be better suited for a forum post, but since David doesn't use his own site/forum, I guess the only place to ask general questions or Sandboxie related things is here. (USE YOUR DAMN FORUMS DAVID!)

So, this game [Pathos Nethack](https://pathos.azurewebsites.net/), is an old favorite of mine, I play it ever once in a awhile but now all of a sudden it just crashes when I go to launch it... I'm really at a loss as to why, the only software on my system that has changed that could be even remotely related to this is Sandboxie, and bullshit Windows 10 "Patch Tuesday" update stuff.

Could anyone be so kind as to test if the "Windows Desktop" version of Pathos starts up as expected, instead of just crashing. That way if I know it works for you in a Sandbox then I'll know it's not a Sandboxie related issue and something else "Windows".

It's a small game, and free, no adware or anything. Just run the installer in Sandboxie, and then find the PathosGame.exe and click it.

Thanks in advance.

### Expected behavior

game to work

### What is your Windows edition and version?

Windows 10 Pro Version - 21H2 OS build - 19044.1586

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Classic 5.55.12

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by ImSpecial** [comment]
Thanks for taking the time, it indeed runs, which means... Damn! It must be something else with my system preventing the thing to running...

**Comment by Dyras** [comment]
Try checking with Plus and see if it works in the green box

**Comment by ImSpecial** [comment]
Hey sorry to keep you hanging on this, I kind of gave up after well, when I couldn't figure out for the life of me as to why it and only it was crashing outta the blue. I did try a fresh Sandboxie with the same results, so yeah.

Only a few days ago did I finally solve this, it was in part of the Windows March update actually and had nothing to do with Sanboxie, but also in part with RRTS Rivatuner Statistics Server, which is part of the MSI Afterburner package.

So in short the Windows update changed some behind the scenes stuff with DirectX, which caused RRTS that hooks Pathos to crash it, refreshing the RRTS cache file fixes everything, this isn't a super uncommon thing with Windows updates and RRTS, I should have known, but this kind of problem only crops up maybe once every year or two, so when it does happen you never really think of it.

Anyway I just wanted to let you know, close this issue which has nothing to do with Sandboxie, and well maybe, some day someone else (or me again) will come here asking about a game/certain program crashing, and a lead to said crashing might be this. - "do you use MSI Afterburner/RRTS?"...
