### ISSUE TITLE
Forced programs ignore sandboxie whatsoever

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [sandboxie-plus/Sandboxie#1688]
### What happened?

Tried several programs added in "auto start" or "forced program" in a default setting sandbox. While sandboxie is running in the background. I try running any program that's in that list. They never start in the sandbox.
If I explictly run these programs in the sandbox there is no problem. 

### To Reproduce

Have sandboxie plus started.
Add the progarm path to a sanbox options-Forced programs
OK out
Run the added program.
The program runs outside sandbox.

### Expected behavior

It runs inside the sanbox automatically when I run it.

### What is your Windows edition and version?

Windows 10 Home 64 bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Hitman Pro, Avira, Malwarebyte and othe on demand scanners

### What version of Sandboxie are you running?

sandboxie plus 0.9.8.d

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
Programs must be in the forced processes list for otehre users thsi seams to be working, please try again.
