### ISSUE TITLE
Constrains for box names are unclear

### ISSUE THREAD

**Issue by hippalectryon-0** [sandboxie-plus/Sandboxie#1693]
### What happened?

When creating a sandbox with a name containing special characters, one gets the message _The sandbox name can contain only letters, digits and underscores which are displayed as spaces._

This has two issues:
* it suggests that spaces can't be used in the names
* it isn't clear whether underscores are just _rendered_ as spaces or _equivalent_ to spaces.

Upon quick investigation, it seems that underscores and spaces are functionally equivalent (I can't both create the sandbox "a&nbsp;&nbsp;a" and "a__a")

__Note__: Very much related, the limit of 32 characters and the charset constrains are not explicitly stated in the creation menu. It would be helpful to add one line under "Sandbox Name" to make them clear.

### To Reproduce

Not relevant

### Expected behavior

Make it clear that spaces _can_ be used in the names, and make it clear that spaces and underscores are functionally identical.

### What is your Windows edition and version?

Not relevant

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

SB-Plus 1.0.13

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
message changed to "The sandbox name can contain only letters, digits, spaces and underscores which are displayed as spaces."
you cant enter more than 32 charakters in the ui, and if you did by some hacky method there would be a separate message stating the limit
