### ISSUE TITLE
Crash when you run EasyJoin Pro in a sandbox

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1699]
I have a crash issue when I run EasyJoin Pro inside any sandbox (standard or compartment type).

The program is only installed in the real system.

1. Download EasyJoin Pro from here: https://easyjoin.net/windows.html
2. Install it only in the real system.
3. Run the executable `C:\Program Files (x86)\EasyJoin\EasyJoin.exe` in an empty sandbox with compartment box type or standard box type.
4. EasyJoin Pro will crash in both cases, producing the crash dumps in `C:\Sandbox\%User%\DefaultBox\user\current\AppData\Local\CrashDumps`

Tested on Windows 10 21H1 x64.
Sandboxie Plus 1.0.13 x64

Crash dump: [EasyJoin.exe.16260.zip](https://github.com/sandboxie-plus/Sandboxie/files/8258675/EasyJoin.exe.16260.zip)

**Comment by anemomylos** [comment]
Hi, I am the developer of EasyJoin.

The application fails because it can't find the Windows.UI.Notifications.ToastNotificationManager class; most likely also the other classes that are part of those provided by Microsoft for classic desktop applications (not UWP). 

I don't know how Sandboxie works, so I could be wrong, but have you checked if you have installed .net 4.6.1 or newer and if you have enabled from Windows update the installation of updates for all Microsoft products?

**Comment by isaak654** [comment]
My Windows 10 installation is fully updated with .net 4.8 and EasyJoin Pro works great outside Sandboxie. 
The main developer stated once that the toast notifications should be run in a compartment box type with open COM, but I already tried this way and unfortunately it didn't work. That's why the crash surprised me...

**Comment by DavidXanatos** [comment]
this toast notification is devolving into a real issue, i may need to provide a fake interface for this functionality and proxy the requests somehow...

**Comment by DavidXanatos** [comment]
@anemomylos 
the best would be if you coudl check if the required object was created and if not handle the situation without a crash, 
I haven't found a strait forward way to solve this issue the thing is that some rpc endpoints don't like seing an anonymous logon token on the requesting process, no mater what user the callign thread impersonates.

**Comment by DavidXanatos** [comment]
i have tested the latest version thoroughly and it does not seam to crash anymore

**Comment by isaak654** [comment]
It keeps crashing for me in Sandboxie Plus x64 1.10.2f.

- I've used standard and application compartment sandboxes (both empty, with or without `Template=OpenCOM`)
- System: Windows 10 22H2 x64 build 19045.3208

**Comment by DavidXanatos** [comment]
can you please play around with the notification/toast settings seams i need to set some non default config to run into that issue

**Comment by isaak654** [comment]
The crash issue has been fixed after updating EasyJoin Pro 3.15 to version 4.3.1.

**Comment by e-t-l** [comment]
> i may need to provide a fake interface for this functionality and proxy the requests somehow...

Sounds complicated. Have you identified which COMs actually need to be open in order for toasts to go through? As mentioned in https://github.com/sandboxie-plus/Sandboxie/issues/2770#issuecomment-1912520413, I tried opening a ton of specific COMs and it still didn't work.
