### ISSUE TITLE
Recovering files to non-existant paths

### ISSUE THREAD

**Issue by 0657code** [sandboxie-plus/Sandboxie#17]
When attempting to recover a file to a path which does not exist, the deepest folder of the path will not be created and the file will be renamed to this folder name instead.

Example:
Recover file.png to C:\a\b\
1. If the folder C:\a\b\ exists, the file will be recovered as C:\a\b\file.png
2. If the folder does not exist, the file will be recovered as C:\a\b (where b is a file with the file.png content)

Version 5.31.4 (64-bit) on Windows 10 Build 17763

**Comment by DavidXanatos** [comment]
will look into it. thanks for the report

**Comment by DavidXanatos** [comment]
please use the plus UI ther this problem should not occur.
