### ISSUE TITLE
Opening Links In Desktop Apps

### ISSUE THREAD

**Issue by Vinyzu** [sandboxie-plus/Sandboxie#1706]
### What happened?

In Windows, u can open links on ur desktop app like with `spotify:track:trackname`.
I wanted to use this to opn a track on a sandboxed spotify app, but instead it just opens the normal spotify app

### To Reproduce

0. Have Windows
1. Download Spotify
2. Open Spotify in a Sandbox
3.  Open `spotify:track:trackname` in ur desktop
4. See that it opens the normal Spotify

### Expected behavior

It should open the track on all Spotify instances

### What is your Windows edition and version?

Windows 11

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender, Norton

### What version of Sandboxie are you running?

Sandboxie v5.55.11

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
> Open `spotify:track:trackname` in ur desktop

Where, exactly? 
After replacing trackname, I pasted the command on the Explorer.exe address bar, but I can't make it work even outside Sbie.
