### ISSUE TITLE
integrate some contributions from the old forum, please.

### ISSUE THREAD

**Issue by JulyMorning** [sandboxie-plus/Sandboxie#171]
Just found these two features. The first is the major one. Really freaks me out all that apps that requests admin right just for the sake of installation. That guys shared the code he said:

– https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic8c4c8c4c.html?f=22&t=24038

And the second one is a minor:

– https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic96ca96ca.html?f=22&t=22399

thanks!

**Comment by DavidXanatos** [comment]
huh that looks useful will check it out soon

**Comment by DavidXanatos** [comment]
If you find any other user full 3rd party tools for sbie please bring them to my attention.

**Comment by isaak654** [comment]
I suggest the integration of a registry viewer/editor called SandboxToys2, its source code is still available in the zip file:
https://github.com/sandboxie-plus/Sandboxie/issues/60#issuecomment-813610512

The most annoying bug I've found: it doesn't recognize sandboxes names with spaces like `My sandbox 1`.

**Comment by DavidXanatos** [comment]
no uac install is in run unsandboxed as well and for two way cansbox isoaltion we have a request on the todo asap track: https://github.com/sandboxie-plus/Sandboxie/issues/1367
so I'll close this now
