### ISSUE TITLE
Sandbox breakout bug (details omitted)

### ISSUE THREAD

**Issue by hx1997** [sandboxie-plus/Sandboxie#1714]
### What happened?

The details of this bug have been sent to @DavidXanatos by email on March 21. This issue only serves to track the fixing (that is, if this is confirmed to be a real bug) progress publicly.

In short, I've found a bug in Sandboxie that presumably lets an attacker break out of the sandbox. This has yet to be confirmed by the developers, though.

### To Reproduce

Described in the email.

### Expected behavior

Sandboxed programs should not be allowed to escape.

### What is your Windows edition and version?

Windows 10 Home 20H2 (19042.1466) 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Built-in realtime protection in Windows 10

### What version of Sandboxie are you running?

Sandboxie Classic v5.55.13 64-bit

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Is the sandboxed program also installed outside the sandbox?

No, it is not installed in the real system.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
I can confirm the issue and luckily there is already a workaround in place which can be enabled, by adding
```EnableObjectFiltering=y``` to the [GlobalSettings] section in the sandboxie.ini 
or through the UI:
![grafik](https://user-images.githubusercontent.com/3890945/159678273-99ac4384-a34f-4f87-9e04-57d4c1d07251.png)

never the less the issue when not using this enhanced filtering is present and will be fixed ...
