### ISSUE TITLE
Cannot start explorer

### ISSUE THREAD

**Issue by inkuxuan** [sandboxie-plus/Sandboxie#1716]
### What happened?

Starting explorer using "Run" -  "Boxed Tools" - "Windows Explorer" in the right-click menu at a sandbox will end up with Start.exe and explorer.exe being started and instantly terminated (No window pops up).
![image](https://user-images.githubusercontent.com/19793388/159733131-f5138dfc-947a-4b80-8e44-2b26ba15f7c8.png)

Starting explorer using "Run" - "Run Program" and entering "explorer.exe" will end up with multiple errors.
![image](https://user-images.githubusercontent.com/19793388/159733329-002744ef-0b79-41b5-aa37-dff3452fec9c.png)
![image](https://user-images.githubusercontent.com/19793388/159733413-3b42cf00-10e3-40f3-b209-0d00079a2607.png)

This problem is not present in Sandboxie-Plus v0.9.x (It occurs after I updated it)

### Download link

Not relevant

### To Reproduce

1. Create a standard sandbox
2. In "Sandbox Options" - "Resource Access", add an IPC Path for "All Program" with "Open" access for "*" (You have to enter this for reproducing this bug)
3. Save options and start explorer in the created sandbox

### Expected behavior

File Explorer starts

### What is your Windows edition and version?

Windows 10 Pro 20H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Huorong Security 5.0.66.3

### What version of Sandboxie are you running?

Sandboxie-Plus v1.0.10

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
> Starting explorer using "Run" - "Boxed Tools" - "Windows Explorer" in the right-click menu at a sandbox will end up with Start.exe and explorer.exe being started and instantly terminated (No window pops up).

> This problem is not present in Sandboxie-Plus v0.9.x (It occurs after I updated it)

My downgrades confirmed that `OpenIpcPath=*` crashes explorer.exe at least since [0.9.8 x64](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.8)
Could you be more specific about which version introduced the issue, doing the rest of the downgrades version by version?

> Starting explorer using "Run" - "Run Program" and entering "explorer.exe" will end up with multiple errors.

This is a common mistake, in Sandboxie you need to run explorer by using the following command:
`explorer.exe /e,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}`
The official explanation was provided here: https://github.com/sandboxie-plus/Sandboxie/issues/362#issuecomment-758602253

If you want to contribute to the documentation with the current volunteers, you can write your own ideas in https://github.com/sandboxie-plus/sandboxie-docs/issues/54

**Comment by isaak654** [comment]
I updated my previous post, so the regression started since Plus 0.9.6 x64.

**Comment by isaak654** [comment]
I made a few more tests, so if we exclude that single char preset issue mentioned in [#971](https://github.com/sandboxie-plus/Sandboxie/issues/971#issuecomment-918517541):

0.7.5 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.7.4 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.7.3 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.7.2 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.7.1 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.7.0 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.6.7 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.6.5 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.6.0 has the crash issue with OpenIpcPath=* in sandboxed explorer
0.5.0 has the crash issue with OpenIpcPath=* in sandboxed explorer

**Comment by isaak654** [comment]
I made a few more tests, so if we exclude that single char preset issue mentioned in [#971](https://github.com/sandboxie-plus/Sandboxie/issues/971#issuecomment-918517541):

0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.7, 0.6.5, 0.6.0, 0.5.0 have the crash issue with OpenIpcPath=* in sandboxed explorer

Maybe a warning to prevent the crash would be more useful.

**Comment by DavidXanatos** [comment]
warning added in next build SBIE2195
