### ISSUE TITLE
Sandboxie says it is reloading the config when it isn't

### ISSUE THREAD

**Issue by coavins** [sandboxie-plus/Sandboxie#1717]
### What happened?

I was trying to restore my Sandboxie settings from a backup.

1. I renamed my `C:\WINDOWS\Sandboxie.ini` file to `Sandboxie.ini.new` (A)
2. I renamed my old backup from `Sandboxie.ini.bak` to `Sandboxie.ini` (B)
3. When I start the Sandboxie GUI again, I get a message that it has loaded the config from config B, but all of the boxes from config A appear.
 
I then tried renaming `Sandboxie.ini` (B) back to `Sandboxie.ini.bak` to regenerate default settings, and still the boxes from config A appear.

Upon starting Sandboxie-Plus GUI, I am consistently seeing the following message printed in the log:

    Loaded Config: C:\WINDOWS\Sandboxie.ini

even when this file doesn't exist on disk. I'm guessing Sandboxie is not actually reloading the configuration when it says it is. The `Options > Reload ini file` command **does** perform as expected.

### Download link

Not relevant

### To Reproduce

1. Close sandboxed applications and shut down Sandboxie-Plus GUI
2. Rename `C:\WINDOWS\Sandboxie.ini` to `C:\WINDOWS\Sandboxie.ini.bak`
3. Open Sandboxie-Plus GUI
4. See this message printed in the log: `Loaded Config: C:\WINDOWS\Sandboxie.ini`

### Expected behavior

I expect Sandboxie to only print a message that it loaded the config from a file when it actually does so

### What is your Windows edition and version?

Windows 10 Pro 21H1 64-bit 19043.1586

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.13

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
This is not a bug but a missunderstanding.
Loaded config tells you which confing waas loaded not when.

the message "Sandboxie config has been reloaded" tells you that a config was reloaded

**Comment by DavidXanatos** [comment]
makes sense will change that in the over next build

**Comment by isaak654** [comment]
> how about "Current Config:"

Thumbs up, so let's go for it.
