### ISSUE TITLE
Sandboxie requires a supporter certificate for boxes where supporter-only features were turned off

### ISSUE THREAD

**Issue by coavins** [sandboxie-plus/Sandboxie#1718]
### What happened?

I activated a setting, learned from a pop-up that it requires a certificate, and deactivated the setting. My box now requires a certificate even though the offending feature was disabled. I had to restore my config file from a backup in order to revert my box from a supporter-only state.

### Download link

Not relevant

### To Reproduce

1. Go to `Sandbox Options`
2. Go to `Resource Access`
3. Go to `Resource Access Policies`
4. **Enable** the `Privacy Mode, block file and registry access to all locations except the generic system ones` checkbox under `Access Mode`
5. Dismiss the pop-up that says you that you just activated a supporter-only feature
6. **Disable** the `Privacy Mode, block file and registry access to all locations except the generic system ones` checkbox under `Access Mode`
7. Dismiss the pop-up that says you that you just activated a supporter-only feature
8. Start an application in the sandbox
9. See the pop-up warning that your application will be terminated for using a supporter-only feature

### Expected behavior

I expect Sandboxie to stop treating my box like a supporter-only box when I deactivate supporter-only features

### What is your Windows edition and version?

Windows 10 Pro 21H1 64-bit 19043.1586

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.13

### In which sandbox type you have this problem?

In a Hardened sandbox (red sandbox icon).

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
yea the way privacy mode is implemented, its the Rule Specificity feature + a list of locations which must be open
