### ISSUE TITLE
Sandboxie does not inform the user why their box requires a supporter certificate

### ISSUE THREAD

**Issue by coavins** [sandboxie-plus/Sandboxie#1719]
### Is your feature request related to a problem or use case?

I configured a sandbox to my liking, but when I start an application into it I am warned that the sandbox requires a supporter certificate:

    PID xxxxx: The configuration of box Discord requires a supporter certificate.

I don't remember which settings I'm not allowed to use, therefore I'm unable to reconfigure the sandbox to remove the offending settings.

### Describe the solution you'd like

Sandboxie should explicitly tell me which settings are causing this warning to appear in the log so that I can disable them or decide whether I want to pay for them.

**Comment by DavidXanatos** [comment]
thats a great idea :D
