### ISSUE TITLE
Why not merging Sandboxie Plus and Sandboxie?

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#172]
Following #165, if they use the same drivers and Sandboxie Plus is a nicer looking (though there are no screenshots to support that claim) and has more features why not making them into two separate programs?

I mean, surely it takes precious time from you to support two different programs that basically do the same thing.

**Comment by DavidXanatos** [comment]
Because many people who used the old UI would like to stick to it.
Because the old UI is very lightweight, while the new one brings 10's of MB of Qt Dependencies, most people wouldn't care but some do. 

I don't add anything new to the old UI so its more or less 0 afford to provide booth versions.

**Comment by lwcorp** [comment]
So you'll never add new features to Sandboxie, only to Plus?

**Comment by DavidXanatos** [comment]
> 
> 
> So you'll never add new features to Sandboxie, only to Plus?

Well, most components are shared among the two builds

The only main difference is that the classical build uses SbieCtrl.exe as main UI and the Plus Build uses the Qt based SandMan.exe
Features added to the core components and configurable using the INI are therefor available in all builds, only that in the classical build there is no UI support for them. Meaning you need to edit the ini by hand to configure new features. 

I will not add any non trivial features to the old UI as its using the very old MFC framework which it a pain to work with, 
Q't it's much more fun to use, and the resulting UI's look much better to.

**Comment by bjm234** [comment]
FWIW ~ I'll have an easier transition to SandMan when SandMan offers SbieCtrl functions and features.
for example:
![image](https://user-images.githubusercontent.com/25015553/97418146-d9c05900-18de-11eb-83b5-3660fd88a130.png)

**Comment by bjm234** [comment]
I imagine.... I can get used to calling Plus UI from the Taskbar - 
![image](https://user-images.githubusercontent.com/25015553/97717753-85160d00-1a9b-11eb-98d9-f151e97dfbe2.png)
old dog takes time to learn new tricks
Regards w Respect

**Comment by lwcorp** [comment]
@DavidXanatos, is the last 2 comments the reason you don't merge?
That is, do you confirm Plus misses features that Sandboxie has?

**Comment by DavidXanatos** [comment]
The current build has more tray options: 
![grafik](https://user-images.githubusercontent.com/3890945/101941313-170b4c80-3be8-11eb-93bf-d29f4bac01e0.png)

And users in the forum said they don care about the additional tray options.

Also the submenu has now more options:
![grafik](https://user-images.githubusercontent.com/3890945/101941430-4457fa80-3be8-11eb-9ee3-d3e5afd72895.png)

All the chrome and notepad2 entries all below the separator are user defined, so you can add your entries to the run menu.

**Comment by bjm234** [comment]
> The current build has more tray options:
> 
> And users in the forum said they don care about the additional tray options.
> 
Users do not care about additional tray options?

**Comment by lwcorp** [comment]
> Hmm, users do not care about additional tray options??
I know I sometimes use them...

> I'll install Plus....but, continue to run SbieCtrl.
How will you do that? Will you install both programs and have them both run in the background all the time?

**Comment by bjm234** [comment]
> How will you do that? Will you install both programs and have them both run in the background all the time?
Sandboxie-Plus and Sandboxie builds from @DavidXanatos share components.  
Look if your Sandboxie-Plus folder.  You'll find SbieCtrl.exe. 
I pin SandMan.exe and SbieCtrl.exe to my taskbar.  
![image](https://user-images.githubusercontent.com/25015553/101989497-b541f580-3c6e-11eb-8433-6491f3a7acdc.png)

**Comment by lwcorp** [comment]
> `> How will you do that? Will you install both programs and have them both run in the background all the time?`
> 
> No, I just install Sandboxie-Plus.
> Sandboxie-Plus and Sandboxie builds from @DavidXanatos share components.

If I want to switch to Sandboxie Plus, how do I do that without losing all my Sandboxie settings, folders, etc.?

**Comment by bjm234** [comment]
> > `> How will you do that? Will you install both programs and have them both run in the background all the time?`
> > No, I just install Sandboxie-Plus.
> > Sandboxie-Plus and Sandboxie builds from @DavidXanatos share components.
> 
> If I want to switch to Sandboxie Plus, how do I do that without losing all my Sandboxie settings, folders, etc.?
Uninstall Sandboxie and retain ini file.

**Comment by DavidXanatos** [comment]
0.5.1 fixes many bugs of the 0.5.0 build and it comes with a normal inno setup installer so it should be less offending to other security software,

**Comment by lwcorp** [comment]
> Uninstall Sandboxie and retain your Sandboxie.ini file. Then install Sandboxie-Plus.

Do you mean it uses the very same INI file in %windir%?
What about  %HOMEDRIVE%\Sandbox?

**Comment by bjm234** [comment]
> 0.5.1 fixes many bugs of the 0.5.0 build and it comes with a normal inno setup installer so it should be less offending to other security software,

Okay....I've now installed 0.5.0.

**Comment by bjm234** [comment]
> > Uninstall Sandboxie and retain your Sandboxie.ini file. Then install Sandboxie-Plus.
> 
> Do you mean it uses the very same _%windir%\Sandboxie.ini_ for its settings?
> What about _%HOMEDRIVE%\Sandbox_?

Yes, C:\Windows\Sandboxie.ini is the same ini file for me, on my machines.

**Comment by lwcorp** [comment]
> Yes, C:\Windows\Sandboxie.ini is the same ini file for me.
> I've installed all @DavidXanatos builds. I've retained Sandboxie.ini.

So does Sandboxie Plus also save its settings there? This means once you install Plus it might be hard to go back.

> What about %HOMEDRIVE%\Sandbox?

?

**Comment by bjm234** [comment]
> > Yes, C:\Windows\Sandboxie.ini is the same ini file for me.
> > I've installed all @DavidXanatos builds. I've retained Sandboxie.ini.
> 
> So does Sandboxie Plus also save its settings there? This means once you install Plus it might be hard to go back.
> 
> > What about %HOMEDRIVE%\Sandbox?
> 
> ?

Sorry, I'm not understanding <  What about %HOMEDRIVE%\Sandbox? >.  
I've installed, uninstalled & reinstalled Davids builds.  My Settings are reflected with in SandMan & SbieCtrl.

**Comment by lwcorp** [comment]
Does Plus **save** its settings inside _%windir%\Sandboxie.ini_?

Meanwhile, _%HOMEDRIVE%\Sandbox_ contains the sandboxes themselves what with their folder structure and registry.
Does Plus reads and writes its sandboxes there to?

**Comment by bjm234** [comment]
> Does Plus **save** its settings inside _%windir%\Sandboxie.ini_?
> 
> Meanwhile, _%HOMEDRIVE%\Sandbox_ contains the sandboxes themselves what with their folder structure and registry.
> Does Plus reads and writes its sandboxes there to?

If I understand.  Yes > https://www.wilderssecurity.com/threads/released-sandboxie-plus-sbie-fork-versions-with-signed-driver.434924/page-4#post-2973465
