### ISSUE TITLE
libssl-1_1-x64.dll is corrupt

### ISSUE THREAD

**Issue by Qhgu** [sandboxie-plus/Sandboxie#1721]
### What happened?

When I try to install the Sandboxie Plus 1.0.14 over 1.0.13, an error window notices that the source file libssl-1_1-x64.dll is corrupt. Please check the screenshot.

Windows 10 LSTC 2021 21H2 x64 (19044.1586)
Sandboxie Plus 1.0.14

![corrupt](https://user-images.githubusercontent.com/83149974/159814375-7e51783b-4ed4-470e-a08f-4c856c47a252.png)

### Download link

Not available

### To Reproduce

1. Install the Sandboxie Plus 1.0.14 over 1.0.13 (both versions are x64).
2. The error should occure.

### Expected behavior

No error 

### What is your Windows edition and version?

Windows 10 LSTC 2021 21H2 x64 (19044.1586)

### In which Windows account you have this problem?

I use the built-in Administrator with Admin Approval Mode turned on.

### Please mention any installed security software

ESET Endpoint Security 9.0.2032.6

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.13 x64

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
Do you notice any difference with [1.0.15](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.15)?

**Comment by Qhgu** [comment]
> Do you notice any difference with [1.0.15](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.15)?

This issue is not reproduced in the 1.0.15 over 1.0.14.
