### ISSUE TITLE
getmac error

### ISSUE THREAD

**Issue by vmtest888** [sandboxie-plus/Sandboxie#1722]
### What happened?

![image](https://user-images.githubusercontent.com/26427035/159825518-f492eddf-1aee-4d21-80fd-408082af609e.png)

The system is windows 10 , C:\Windows\System32\getmac.exe is normal outside the sandbox, and not normal inside the sandbox

### Download link

Not relevant

### Expected behavior

no

### What is your Windows edition and version?

windows 10

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

no

### What version of Sandboxie are you running?

1.0.14

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by 0x391F** [comment]
![1](https://user-images.githubusercontent.com/56181919/159830049-e53f8d17-40cc-4ccb-bee4-921b4c98c964.PNG)

Couldn't reproduced on Sandboxie 5.5.14/Sandboxie-Plus 1.0.14
