### ISSUE TITLE
Windows explorer can't be sandboxed in Windows 11

### ISSUE THREAD

**Issue by drifter561** [sandboxie-plus/Sandboxie#1729]
### What happened?

You can't sandbox windows explorer with windows 11. This problem exist months and months with windows 11 !!!!!!
You get a blank screen, you can't close that screen (only after 20 seconds)
After a 20 seconds, you get always this message:
- explorer.exe (15060): SBIE2224 Sandboxed program has crashed
- Werfault.exe (21772): SBIE2101 Object not found : unnamed object, ...

This problem exists months and still it isn't resolved!!!!!!!!!!!!!!!

Please resolve it (windows 11).

### Download link

not relevant

### To Reproduce

1. Start Sandboxie-Plus 1.0.15 (latest)
2. Rightclick on "DefaultBox".
3. Choose: Run/Boxed Tools/Windows explorer.

You get a white screen, it blocked, after 20 seconds you get message:
- explorer.exe (15060): SBIE2224 Sandboxed program has crashed
- Werfault.exe (21772): SBIE2101 Object not found : unnamed object, ...

This problem exists months and still it isn't resolved!!!!!!!!!!!!!!!

### Expected behavior

Run explorer.exe in sandbox mode WITHOUT errors or white screen 

### What is your Windows edition and version?

Windows 11 21H2 (build 22000.556) (but problem exists months and months)

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Avast

### What version of Sandboxie are you running?

Sandboxie-Plus 1.0.15

### Is it a regression?

since windows 11 introduced

### List of affected browsers

Firefox 64 bit

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no

**Comment by isaak654** [comment]
As you can notice in the original issue #1127, it is reported as working from the Insider 22478.1012 build, so the lead developer is waiting Microsoft to update the RTM branch. My guess is that it will most likely be released as 22H2.

**Comment by drifter561** [comment]
Thank you so much.
It's when windows 11 came out, this problem occured with sandboxie. 
So we'll wait for the microsoft update RTM branch. I hope Microsoft will update it soon.
Sandboxie is very good developed , thanks for developing it after the previous developer has stoped.
