### ISSUE TITLE
reg.exe add error

### ISSUE THREAD

**Issue by vmtest888** [sandboxie-plus/Sandboxie#1741]
### What happened?

OpenKeyPath was added in ini

```
[GlobalSettings]
OpenKeyPath=reg.exe,HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\*
```

Start a cmd inside sandboxie, then run the command, and get an error

```
reg add   HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\.test
```

![1648622605340_B88A4BAF-BCE2-494c-BF39-2210A39E54FD](https://user-images.githubusercontent.com/26427035/160768445-057de869-dc0f-40ee-89b9-745a62bacb04.png)

### Download link

Not relevant

### Expected behavior

no

### What is your Windows edition and version?

windows 10

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

no

### What version of Sandboxie are you running?

v1.0.11 / 5.55.11

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
This kind of is a bug and it isn't... you see there is no CurrentControlSet that's a sort of link to ControlSet001 hence opening CurrentControlSet without also opening ControlSet001 will be pointless.
Sure it would be nice if in such cases the driver would be smart enough to figure that out and open booth internally, but that's in the most cases a fringe use case so I wont change this for now.

To get what you want to work just add
OpenKeyPath=reg.exe,HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\*
OpenKeyPath=reg.exe,HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\*
or
OpenKeyPath=reg.exe,HKEY_LOCAL_MACHINE\SYSTEM\*ControlSet*\Services\*
and it will work as expected you will be able to write to the real registry under the services key.

Cheers
David
