### ISSUE TITLE
Some programs couldn't run in Sandboxie 5.5.16/Sandboxie-Plus 1.0.16

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#1749]
### What happened?

Some programs couldn't run in Sandboxie 5.5.16/Sandboxie-Plus 1.0.16, such as VMWare Workstation 16.2.3, Firefox 98.0.2

### Download link

Not relevant

### To Reproduce

Run Firefox in Sandboxie: 
WerFault.exe (4052): SBIE2101 Object name not found: \Device\NamedPipe\nod_scriptmon_pipe, error OpenFile (C0000034) access=0012018B initialized=1

![1](https://user-images.githubusercontent.com/56181919/161378963-87a11844-6630-4a06-a61a-fbff16720499.png)

I guess this bug related to ESET advanced scanning of browser scripts (scriptmon)

https://help.eset.com/eis/15/en-US/idh_config_web.html?idh_config_web_basic.html=

Run VMWare Workstation 16 Pro (16.2.3 build-19376536)

![2](https://user-images.githubusercontent.com/56181919/161379003-9f6a970a-c909-41bf-99d3-e7cf1b829d45.png)

### Expected behavior

This bug shouldn't appear

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2022 x64 (21H2)

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

ESET Internet Security 15.1.12.0 x64

### What version of Sandboxie are you running?

Sandboxie 5.5.16/Sandboxie-Plus 1.0.16

### Is it a regression?

Sandboxie 5.5.16/Sandboxie-Plus 1.0.16

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by 0x391F** [comment]
I rollback to Sandboxie 5.5.15/Sandboxie-Plus 1.0.15, everything well.

**Comment by DavidXanatos** [comment]
Well on my system firefox runs just fine, but then I don't have ESET
I haven't tried VMWare,
please try adding
ReadIpcPath=$:*
if that works don't keep it on instead look in the log for open IPC $: entries ans try opening them selecively to find out which once oyu need

**Comment by plofhaan** [comment]
> Well on my system firefox runs just fine,
When I run Firefox Portable sandboxed I get this error:
`SBIE2111 Process is not accessible: $:explorer.exe, call OpenProcess (C0000022) access=00000040 initialized=1`
Running on latest Windows 11 stable/official (with latest ExplorerPatcher pre-release).

**Comment by DavidXanatos** [comment]
but aside of the error message it works fine?

**Comment by plofhaan** [comment]
> but aside of the error message it works fine?

Yeah

**Comment by 0x391F** [comment]
> > Well on my system firefox runs just fine,
> 
> When I run Firefox Portable sandboxed I get this error: `SBIE2111 Process is not accessible: $:explorer.exe, call OpenProcess (C0000022) access=00000040 initialized=1` Running on latest Windows 11 stable/official (with latest ExplorerPatcher pre-release).

+1, the same problem when I run Firefox in Sandboxie, but aside of the error message it works fine.

**Comment by 0x391F** [comment]
By the way, VMWare Workstation works well on Sandboxie 5.5.17

**Comment by 0x391F** [comment]
Unfortunately, If ClosedFilePath=\Device\DeviceApi is set. VMWare Workstation couldn't work. 
#1715

**Comment by 0x391F** [comment]
> Unfortunately, If ClosedFilePath=\Device\DeviceApi is set. VMWare Workstation couldn't work due to this bug. #1715

The same with Firefox.

**Comment by DavidXanatos** [comment]
so can we close this?

**Comment by 0x391F** [comment]
> so can we close this?

Yes.
