### ISSUE TITLE
Microsoft Edge browser, cannot sync data 

### ISSUE THREAD

**Issue by eyaladmin** [sandboxie-plus/Sandboxie#175]
Hi 

Other browsers can sync profile online like favorites and history
But Microsoft Edge not, I know there is two versions
I am using the chrome based with Sandboxie

Please try to resolve that in the next release

Thank you

**Comment by bjm234** [comment]
`The new Microsoft Edge, which is now based on Chromium, is still missing one key feature – history and tab sync support.`
https://www.windowslatest.com/2020/10/29/microsoft-edge-is-finally-getting-tab-and-history-sync-support/

**Comment by eyaladmin** [comment]
Hi there

By the way, I gladly donated yesterday 20 euros

When I am using edge outside of the sandbox it is syncing fine

But I really wanted to use it under Sandboxie, with syncing enabled

I did try to give it direct access to
%Local AppData%\Microsoft\Edge\User Data\Default\Sync Data\

But without results

Please advise

________________________________

**Comment by eyaladmin** [comment]
That is the status outside the sandbox, this is the sync I meant
My concern is just about the Favorites
I have So many
🙂

[cid:d23903d1-1dc8-48ae-88b1-8fd4dc40b432]
________________________________

**Comment by DavidXanatos** [comment]
I'll take a look on these edge features...

**Comment by eyaladmin** [comment]
Thank you
I appreciate your efforts
:-)

השג את Outlook עבור iOS<https://aka.ms/o0ukef>
________________________________
מאת: DavidXanatos <notifications@github.com>
‏‏נשלח: Saturday, October 31, 2020 3:11:40 PM
‏‏אל: sandboxie-plus/Sandboxie <Sandboxie@noreply.github.com>
עותק: Eyal Feder <eyal@actualtech.co.il>; Author <author@noreply.github.com>
‏‏נושא: Re: [sandboxie-plus/Sandboxie] Microsoft Edge browser, cannot sync data (#175)


I'll take a look on these edge features...

**Comment by isaak654** [comment]
Even Smartscreen protection in Edge browser results broken:
https://github.com/sandboxie-plus/Sandboxie/issues/301#issuecomment-753686631

Maybe there is a common origin with this data sync issue?

**Comment by isaak654** [comment]
Is this issue fixed now?

**Comment by isaak654** [comment]
stale

**Comment by isaak654** [comment]
stale

**Comment by isaak654** [comment]
The new reference for this issue is #2015, as it contains more accurate details.
