### ISSUE TITLE
Right-click sometimes not working on Chrome or Chromium

### ISSUE THREAD

**Issue by tsao-chi** [sandboxie-plus/Sandboxie#1750]
### What happened?

Right-click sometimes not working on Chrome or Chromium

### Download link

https://www.google.com/intl/en/chrome/

### To Reproduce

1. Download and install Chrome inside a sandbox
2. Right-click

### Expected behavior

Working

### What is your Windows edition and version?

Windows 11 Enterprise 21H2 22000.556

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.0.13 64bit

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by tsao-chi** [comment]
Edge also applies

**Comment by isaak654** [comment]
Do you notice any difference with 1.0.15 or 1.0.16?

**Comment by tsao-chi** [comment]
I also can't reproduce it every time. Sometimes this problem disappears after rebooting the computer.

**Comment by tsao-chi** [comment]
I haven't tried 1.0.17

**Comment by mysteriously** [comment]
When you highlight text in sandboxed Firefox, it is not possible to drag and drop it on url bar or tabs bar if explorer.exe is not runnning
