### ISSUE TITLE
Sanboxed Chrome is accessing global Chrome profile and does not re-create profile in sandbox.

### ISSUE THREAD

**Issue by smithy49** [sandboxie-plus/Sandboxie#1763]
### What happened?

Sandboxie-plus not saving profiles in sandbox. 
See below To Reproduce.

In the original classic  Sandboxie:
Resource Access -> Write-only Access
C:\Users\username\AppData\Local\Google\Chrome\User Data\Default

Sandoxed Chrome did not have any access to the global Chrome data and profile.
Chrome then re-created the profile in the sandbox.

I've attached of the original classic Sandboxie settings dialog.

![sandboxie-1](https://user-images.githubusercontent.com/6471037/161440800-d390fed8-dc41-4f29-a110-ece898245617.jpg)

### Download link

Not relevant

### To Reproduce

Resource Access -> Access Rules > Programs {All programs} - Access {closed} - path {Drive:\Users\username\AppData\Local\Google\Chrome\User Data\Default}

Start sandboxed Chrome.

Visit a couple of sites.

Close Sandboxed Chrome and re-start in Sandbox.

All open tabs lost plus all profile data because Chrome is not re-creating profile in Sandbox.

Below is Sandboxie-plus Options.

![sandboxie-plus-4](https://user-images.githubusercontent.com/6471037/161442223-38e2a55d-d445-4acc-a6f9-5243d6b8129b.PNG)

### Expected behavior

I expect that sandboxed Chrome to create a profile in the sandbox.

### What is your Windows edition and version?

Windows 10 Pro 21H1 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie-plus V1.0.17

### List of affected browsers

Chrome

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by isaak654** [comment]
The equivalent of the Sandboxie Classic reference `Write-only File Access (WriteFilePath)` is called `Box Only (Write Only)` that needs to be properly selected under the Access column of the Plus UI Resource Access.

**Comment by offhub** [comment]
WriteFilePath gives an access restriction error -like ClosedFilePath- when the folder exist outside of the sandbox. If it doesn't exist it creates one in the sandbox. Shouldn't it give the same result?

Version 1.0.17

**Comment by offhub** [comment]
WriteFilePath gives an error when the folder exist outside of the sandbox. If it doesn't exist it creates one in the sandbox. Shouldn't it create new files or folders in both cases?

Version 1.0.17


> WriteFilePath is a sandbox setting in [Sandboxie Ini](https://sandboxie-plus.com/sandboxie/writefilepath/SandboxieIni). It specifies path patterns for which Sandboxie will hide any files or folders outside the sandbox, while allowing new files and folders to be created in the sandbox.

**Comment by smithy49** [comment]
@isaak654, Thank you, that did the trick.
