### ISSUE TITLE
Is Sandboxie trying to connect to the driver ahead of time?

### ISSUE THREAD

**Issue by lzrdblzzrd** [sandboxie-plus/Sandboxie#1764]
### What happened?

It feels like Sandboxie is trying to connect to the driver ahead of time, and because of this it gives an error message. Immediately after the error, you can see that the driver and the service have been successfully started.
[A video with the problem showing that the driver is *actually* running after an error](https://www.youtube.com/watch?v=DQZPNfc9Pq8)

### Download link

Not relevant to my request.

### To Reproduce

1. Open Sandboxie in portable mode.
2. Get a message that an error occurred when connecting to the driver.
3. Notice that the driver is actually running.

### Expected behavior

*First* start the driver, and then try Sandboxie to connect to it.

### What is your Windows edition and version?

Window 10 Pro 21H1 x64

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

Nothing.

### What version of Sandboxie are you running?

Sandboxie Plus v1.0.15 Portable

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
Co i disabled UAC and tried starting sandboxie from a nothign is startes state it started up just fine, any other changes you may have in your config that may affect this issue?

**Comment by lzrdblzzrd** [comment]
No, everything is fine with my config, it happens even on a clean, just downloaded program. Most likely this is a problem of my system. Soon I will try to run the program in Virtualbox with absolutely clean Windows and let you know if everything is working well.
