### ISSUE TITLE
Item appears with Classic UI - not with Plus UI

### ISSUE THREAD

**Issue by bjm234** [sandboxie-plus/Sandboxie#177]
Curious, why item appears with SbieCtrl and not with Plus.
For example: chrome.exe appears with Classic Internet Access ...not with Plus Internet Access 
![image](https://user-images.githubusercontent.com/25015553/97714420-847b7780-1a97-11eb-8cfd-80865f617fb4.png)
Edge does not appear with Plus Internet Access.
![image](https://user-images.githubusercontent.com/25015553/97714585-b8569d00-1a97-11eb-90dc-41607d3e3343.png)
Edge does not appear with Plus Start Restrictions. 
![image](https://user-images.githubusercontent.com/25015553/97714673-d45a3e80-1a97-11eb-8827-071735a04840.png)

**Comment by DavidXanatos** [comment]
fixed in next build 0.4.3
