### ISSUE TITLE
Failure to rename a Box

### ISSUE THREAD

**Issue by Germs2004** [sandboxie-plus/Sandboxie#1778]
### What happened?

Sometimes, when I rename a Box to replace a space with an underscore, it does nothing.  No error, no change to the name.

Sometimes, if the Box contains files, and I rename a Box to replace a space with an underscore, it gives an error that Sandboxie cannot move the files.  The error message shows the source path and destination path as identical.  This is because Sandboxie replaces spaces with underscores when it creates its underlying files for each Box, and it does not check whether the source path and destination path are identical before attempting to rename or move those NTFS files.

Other times, when I rename a Box to replace a space with an underscore, Sandboxie creates a new unwanted Box Group with a similar name as the Box (the Box Group's name is identical to the Box's name except it replaces ALL the spaces with underscores).  Yes, it creates a Box Group for some reason.

### Download link

not relevant

### To Reproduce

1) Create a Box Group named "testgroup"
2) Create a new Box named "alpha bravo charlie" and move it into testgroup.
3) Rename "alpha bravo charlie" to "alpha_bravo charlie" (replace the first space with an underscore)
4) Sometimes, the box will not be renamed, and nothing will happen.  Sometimes, if that Sandbox has files in it, you get an error that Sandboxie failed to move the files from the old path to the new one because both paths are identical (since Sandboxie secretly replaces spaces with underscores in the actual NTFS folder names).  Other times, it will create a new Box Group named "alpha_bravo_charlie" inside testgroup while leaving the "alpha bravo charlie" Box unchanged.

### Expected behavior

Renaming a Box should rename the box in the GUI, even if it's just replacing a space with an underscore, and if that causes the sanitized NTFS folder name to change, then it should change the folder name too.  It should detect whether the name change actually will have any effect on the folder name, and not try to move its files if the names are the same.  It should not create a new Box Group.

### What is your Windows edition and version?

Windows 11 21H2 64

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.15

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
This is strange, true sbie issues a move operation from the same name to the same name but for some reason on my test system this operation us successfully, not sure why this is. anyhow in the next build if the names are same it will no try a rename.
Also please note that the UI will never show a underscore in the name they are always replaced with spaced.
The group issue will be fixed in the next build
