### ISSUE TITLE
Not opening a box for option what to do with downloaded files

### ISSUE THREAD

**Issue by MonthOLDpickle** [sandboxie-plus/Sandboxie#178]
Downloading something, anything, from within a boxed browser requires me to manually move/copy to outside. How do I get a pop up like the old sandboxie?  
 
I rather ask this in discord, but I can't find a server.

**Comment by MonthOLDpickle** [comment]
I can't find the option to have it ask every time.

**Comment by MonthOLDpickle** [comment]
Also I have to reset the entire instance if I download one thing and need to download another. How do I fix this? That box like the old one could.

**Comment by bjm234** [comment]
> Also I have to reset the entire instance if I download one thing and need to download another. How do I fix this? That box like the old one could.
Are you running v0.4.3.  Try calling SbieCtrl from Sandboxie-Plus folder.   
And you'll see Sandboxie Control then offers familiar Quick Recovery. 
Maybe, run 5.43.7
https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.4.3

**Comment by MonthOLDpickle** [comment]
Both are installed. No quick recovery has ever shown with plus even when I was using 0.4.1. I have always had to explore content, move it, terminate the instance, and restart the instance. It has also been reinstalled a few times.  
  
I do notice if running sandboxie, I can right click there and do manual quick recovery - but then I wonder - why am I running both plus and the sandboxie when I have to use the old one to get files out and continue in a instance when using plus?

**Comment by bjm234** [comment]
> I do notice if running sandboxie, I can right click there and do manual quick recovery - but then I wonder - why am I running both plus and the sandboxie when I have to use the old one to get files out and continue in a instance when using plus?

Maybe, start over and run Sandboxie v5.43.7
https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.4.3

**Comment by Ouro17** [comment]
I installed fresh version of v0.4.3 and still doesn't have this option. Maybe I didn't understand the problem, because it seems that I need to have both old sandboxie and plus version installed to get my files?
For now I navigated through the "explore content" option to get the files but it's annoying.
Is this something that can be fixed or is planned to be fix?

**Comment by bjm234** [comment]
> 2. Why on earth doesn't the new Plus-tray-icon offer the same basic functionality (apart from any optical "look-and-feel"-preference) as the traditional one - like terminating all processes right from the icon via a right-mouse-click-menu for emergency purposes?

> 2. Because it does not yet has feature parity i.e. some minor things are missing, If the tray functionality is so important for you I'll add some of it to the next plus build.
https://www.wilderssecurity.com/threads/sandboxie-plus-sbie-fork.427755/page-30#post-2963705

**Comment by DavidXanatos** [comment]
The next build 0.5.0 will include all the missing recovery features in the new UI as well.
