### ISSUE TITLE
Show size of each Sandbox in GUI

### ISSUE THREAD

**Issue by Germs2004** [sandboxie-plus/Sandboxie#1780]
### Is your feature request related to a problem or use case?

It would be helpful to easily see how much disk space is used by each Sandbox.

### Describe the solution you'd like

Add a column to the Sandboxie GUI called Size, where it shows the amount of disk space used by each Box.

If querying file sizes might be resource-intensive or add wear and tear to the disk, you could make it refresh one of these ways:
1) manually - user has to click a button each time
2) at a 30-minute interval - easy to program but 99% of the time, the size won't change
3) intelligently - when Sandboxie notices that a disk-write has occurred inside a sandbox, it will refresh the Size column for just that Box.  Don't refresh more than once per 5 seconds.  Don't refresh if the Sandboxie GUI is not open & visible.

**Comment by DavidXanatos** [comment]
That's a nice addition, there are issues with that for example you cant delete a box's content while its scanning the size, so some additional logic must be added to abort the scan before deleting, etc...
I would make the box do a scan only when its closed, closing a box means last process in the box gets terminated, and may be a manual option to refresh open boxes

**Comment by typpos** [comment]
Please provide an opt-out setting for the auto-scan.

If possible, don't lock while scanning.

**Comment by DavidXanatos** [comment]
This will be available in the 1.1.x line of builds,
just a few questions fro you users:
1. I guess we want a dedicated size column, should we show ram usage for programs in that column or leav it empty Or rename ste start time column to aux and use it for box size and process start time lol
2. How often to refresh the size only on box close, avery 5 minues as logn as there are active processes, once whenever the ui is brought up if there were running programs
3. How about ui start enum all boxes or try caching the value between sessions, probably yes...
4. default on or default off for new installs?

**Comment by Germs2004** [comment]
1. A dedicated size column is good.  RAM usage is not very important to me.  Seeing RAM/CPU usage might rarely be useful when troubleshooting a program inside a sandbox, but there are probably more valuable things to work on.
2. When Sandboxie detects ReadDirectoryChangesW, it could save the current datetime to a flag on the affected box called NeedsSizeRefresh.  Each time ReadDirectoryChangesW is detected, it should update that flag with the current datetime. 
 Once 60 seconds has passed since the time on that flag (which means no files have changed for 60 seconds), it should scan the box's size and set the flag to null.  That way, the size won't get scanned constantly if a program is running in the box and changing many files or if a user is copying many files into a box via Explorer.
3. I suggest only querying the size when you know that it has changed via ReadDirectoryChangesW , not every startup.  You could add a right-click menu item called "Refresh Size" on each box so the user can manually force a size scan.  Some boxes may have many files, so excessive scanning is important to avoid.
4. Default on for existing and new boxes because it seems pretty unintrusive, and if were off by default for old boxes, users may wonder why their Size column isn't refreshing on their older boxes and is working on their new boxes.  It would be good to have options to disable automatic size scanning globally and per-box.  If auto scanning is disabled, the user has to manually click the Refresh Size right-click menu item each time.  For boxes with auto scanning disabled, you may want a tooltip when the user hovers over its size cell that says "Size: 123 MB, auto refresh disabled by settings".

**Comment by typpos** [comment]
> just a few questions fro you users

If auto-refresh is off, I rather not see anything about this feature in the main UI, ie, no fixed "empty/aux" columns.

Please consider the following scenarios:
* Large sandboxes with many files
* Applications that change/add/remove lots of files while running
* Ability to manipulate sandbox content (including moving, deleting, renaming, and device ejection) by sandboxed and unsandboxed apps without experiencing "directory locked" because the size scanner is running
* Sandboxes with root path on a removable storage device, eg, USB stick, or a virtual device, eg, Veracrypt drive
* Mapped drives.

For what it's worth, running File Explorer "Properties" on the sandbox root folder takes me 50 seconds with SSD at ~60% load. I wouldn't want this to get in the way of normal file operations, PC idle time, etc. As an alternative, WinDirStat would be free, purpose-built, and does much more.
