### ISSUE TITLE
A flaw in the snapshot feature

### ISSUE THREAD

**Issue by dnt1996** [sandboxie-plus/Sandboxie#1782]
### What happened?

Initialize system environment variables When creating or switching snapshots

### Download link

https://github.com/git-for-windows/git/releases/download/v2.35.1.windows.2/Git-2.35.1.2-64-bit.exe

### To Reproduce

1. Create a new sandbox
2. Install git in this sandbox, at this point you can run git from the command line
3. Create a snapshot after successful installation
4. Can't run git via command line at this point

### Expected behavior

I can always run git from the command line

### What is your Windows edition and version?

windows11 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus v1.0.15

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=D:\Sandbox\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=y
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing

**Comment by isaak654** [comment]
Also confirmed with Plus 1.0.17, it's crazy how the snapshot feature can break system environment variables.

**Comment by DavidXanatos** [comment]
the problem was with the taking of teh snapshot moving RegHive to the snapshot instead of only copying it.
You can fix the issue for now by copying reghive manualyl out of the snapshot back to the root, and the next build will no longer do that mistake
