### ISSUE TITLE
Vivaldi not opening PDFs when sandboxed (since 5.2)

### ISSUE THREAD

**Issue by OrangeDancer** [sandboxie-plus/Sandboxie#1783]
### What happened?

Vivaldi : version 5.2.2623.26 (Stable channel) (64-bit) 
Windows 10 : Windows 10 Version 21H1 (Build 19043.1586)

Sandboxie Classic : 5.55.15

Recent versions of Vivaldi will not open online PDFs ... for example https://www.ebu.co.uk/documents/results-data/2022/national-pairs/NatPairs2022.pdf

What results is an empty dark screen where the text should be. Outside Sandboxie PDF's are opened correctly. I can't rewind to an earlier version of Vivaldi as I keep getting force fed the latest version via automatic updates that I can't seem to turn off ... that is another problem but one I can live with.

I notice some months ago another poster reported a similar problem that was resolved with an update to SB. Hope someone can help. All the best.

### Download link

Not relevant

### Expected behavior

.

### What is your Windows edition and version?

.

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

.

### What version of Sandboxie are you running?

.

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
I can confirm the Vivaldi issue also with Plus 1.0.17 (reproduced with any online PDF file):
![immagine](https://user-images.githubusercontent.com/12372772/162656896-318febef-109b-43c7-adc6-7a15fa1ab634.png)

Note: It looks the same as the old #930 issue.

**Comment by DavidXanatos** [comment]
to my understanding this is an issue with new vivaldi not somethign that got broken in sandboxie so its not a regression

**Comment by isaak654** [comment]
A third-party regression is still a regression imho.

**Comment by DavidXanatos** [comment]
This seams as far as I see some wired screw up in vivaldi's hooking mechanism. they hook NtCreateSection, but somehow their trampoline pointer ends up pointing to out CreateClassNameW detour and than everything is thoroughly screwed.

Is this bug only present in Vivaldi and other chromium based browsers using the same or later chromium version work fine?
If yet, I would actually raise the issue with them.

**Comment by DavidXanatos** [comment]
PS: to me a regression is something that I broke, if someone else broke it its not a regression of sandboxie.

**Comment by isaak654** [comment]
> Is this bug only present in Vivaldi and other chromium based browsers using the same or later chromium version work fine?

The latest Brave 1.37.116 based on Chromium 100.0.4896.127 works fine, so this is a specific Vivaldi regression.
I would suggest to all Vivaldi users that use Sandboxie to open a new bug report there:
https://help.vivaldi.com/desktop/troubleshoot/reporting-a-bug-in-vivaldi/

> PS: to me a regression is something that I broke, if someone else broke it its not a regression of sandboxie.

Therefore, I guess you might be interested to create another "Third-party regression" label to highlight that distinction. That would also help in tracking other specific app issues instead of searching them manually.

**Comment by isaak654** [comment]
> Is this bug only present in Vivaldi and other chromium based browsers using the same or later chromium version work fine?

The latest Brave 1.37.116 based on Chromium 100.0.4896.127 works fine, so this is a specific Vivaldi regression.
I would suggest to all Vivaldi users that use Sandboxie to open a new bug report there:
https://help.vivaldi.com/desktop/troubleshoot/reporting-a-bug-in-vivaldi/

> PS: to me a regression is something that I broke, if someone else broke it its not a regression of sandboxie.

Therefore, I guess you might be interested to create another "Third-party regression" label to highlight that distinction. That would also help in tracking all third-party regressions or conflicts at once, otherwise it could be used the "Known issue" label.

**Comment by DavidXanatos** [comment]
As a workaround for now you can use the advanced option to disable window renaming, this makes the problematic hook not being applied.
Also the next build will contain a hardcoded workaround for vivaldi.exe it is not a proper fix but should make it work for now.

**Comment by DavidXanatos** [comment]
i created the new label incompatibility for such cases, Known issue i would reserve for more generic things, i.e. a fundamental issue that may affect more than one program

**Comment by isaak654** [comment]
@OrangeDancer 
Did you open a new bug report at the Vivaldi support [here](https://help.vivaldi.com/desktop/troubleshoot/reporting-a-bug-in-vivaldi/)?
This issue may not solve itself, so it would be important to reach the involved third-party app and keep this issue report updated accordingly.

**Comment by NotepadPlusUser** [comment]
A short comment to say that my issue 1835 ([Can't open second instance of Vivaldi in the same sandbox](https://github.com/sandboxie-plus/Sandboxie/issues/1835)) disappeared a week or so ago.  Presumably the various updates solved it, but I have no idea which one.  I am now using:
Windows Pro 64-bit 21H2 V10.0.19044.2132
Sandboxie 1.5.0
Vivaldi.5.5.2805.38
Thanks, DavidXanatos and isaak654.
