### ISSUE TITLE
Latest security feature introduced in 5.55.16 breaks some installers

### ISSUE THREAD

**Issue by Smurf451** [sandboxie-plus/Sandboxie#1795]
### What happened?

While dandy for security purposes the latest Sandboxie feature (memory of unsandboxed processes can no longer be read, exceptions are possible) breaks some installers.

### Download link

https://send.vis.ee/download/2c8c90d6e44d6617/#Yb77zkw1GJ5xKYIAQ-F0bA

### To Reproduce

1. Install Sandboxie 5.55.16, 17 or 18
2. Try to run the attached installer.exe
3. Receive "Runtime error 229 at 0D7B4BCF"
![plaza](https://user-images.githubusercontent.com/79382489/163242604-a39d0dad-41ed-4000-b319-ce82f1637678.png)
4. Revert to Sandboxie 5.55.15
5. Installer.exe runs as expected.

### Expected behavior

Installer should run without runtime errors

### What is your Windows edition and version?

Windows10 21H1 64bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie 5.55.18 64bit

### Is it a regression?

5.55.16

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
You can find out which program needs to be accessed using the trace monitor,
or use ReadIpcPath=$:* to switch back to the old behavioure for a selected box for the time of instalaltion

**Comment by DavidXanatos** [comment]
Ok i had time to look into the issue and its not related to the blockage of reading, but to the with that build enabled by default EnableObjectFiltering
it blocks an attempt of the installer to open explorer.exe with duplicate handle permission
So the suggested workaround would not work.
Instead you need to add EnableObjectFiltering=n globally
