### ISSUE TITLE
`EnableObjectFiltering` cannot be found on the UI with the instructions provided

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#1797]
### What happened?

Using the instructions provided:
> To facilitate optimal process isoaltion the EnableObjectFiltering option is now on by default, although this only applies for new installations, hence its recommend for existing installation to go to settings->advanced and enable it explicitly.

I am unable to find the recommended setting:
![image](https://user-images.githubusercontent.com/133706/163254168-0a81839f-e4c0-42de-a9af-84640610c8d5.png)

I have to:

1. _Go to the Sandboxie UI_
2. _Go to Options >_ Settings
3. Switch to Advanced _Config_
4. ????

### Download link

N/A

### Expected behavior

The instructions provided are enough to activate the feature, without esoteric knowledge or additional guidance

### What is your Windows edition and version?

18363.836

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Version 1.0.18

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
"Activate Kernel Mode Object Filtering" its right there in your screenshot, and its already on. Its not a new feature just now on by default, you must have had enabled it at som point in the past.

**Comment by stdedos** [comment]
Then why my Sandboxie.ini has no `EnableObjectFiltering` (or `EnableObjectFiltering=y`)? 😕

**Comment by DavidXanatos** [comment]
because the default value is =y that is when there is no value its equivalent to EnableObjectFiltering=y

**Comment by stdedos** [comment]
Okay - I hope it's just me that all of that don't exactly make sense the way they are laid out.
(Or I guess it _is_ just me that won't default to "don't bother")
