### ISSUE TITLE
Recovery window is not opening on the main display

### ISSUE THREAD

**Issue by 0657code** [sandboxie-plus/Sandboxie#18]
The recovery windows does not respect the system's "main display" setting. Instead it always opens on the leftmost screen.

Version 5.31.4 (64-bit) on Windows 10 Build 17763

**Comment by DavidXanatos** [comment]
minor issues of the classical ui SbieCtrl.exe wont be fixed anymore, please use the new SandMan.exe ui instead, its far superior anyways.
