### ISSUE TITLE
Couldn't create box if there're non-ASCII characters existing

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [sandboxie-plus/Sandboxie#180]
For instance I wish to create a box named "百度云", but it won't be created.
Sbie Message shows:

```Failed to communicate with Sandboxie Service: Failed to set configuration setting Enabled in section 百度云: c000000d```

**Comment by NewKidOnTheBlock** [comment]
Confirmed, although the error message is saying exactly that:
![chinese](https://user-images.githubusercontent.com/12411527/106301764-6705a780-6258-11eb-9a19-e928e9c1bc1c.png)

**Comment by HinataKato** [comment]
> @Aster-the-Med-Stu Confirmed. Although the error message is saying exactly that:
> ![chinese](https://user-images.githubusercontent.com/12411527/106301764-6705a780-6258-11eb-9a19-e928e9c1bc1c.png)
> So this behaviour is kinda expected.
> Is the error message at the bottom missing in your language?

Only this will be displayed in Sandboxie-Plus
![image](https://user-images.githubusercontent.com/57648531/106371480-c9b58b00-639f-11eb-9180-1a374859c406.png)

**Comment by isaak654** [comment]
There is currently an ongoing discussion about it: https://github.com/sandboxie-plus/Sandboxie/discussions/2157
