### ISSUE TITLE
sandboxie-plus

### ISSUE THREAD

**Issue by 2chy2** [sandboxie-plus/Sandboxie#1808]
### What happened?

无法分身64位的软件，只能分身32位的软件

### Download link

na

### To Reproduce

na

### Expected behavior

希望能分身64位的软件

### What is your Windows edition and version?

windows10 home 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

na

### What version of Sandboxie are you running?

sandboxie-plus v1.0.15

### Is it a regression?

na

### List of affected browsers

na

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

na

### Crash dump

na

### Trace log

na

### Sandboxie.ini configuration

```shell
..
```

**Comment by DavidXanatos** [comment]
please write in english
