### ISSUE TITLE
start.exe parameters: disable_force_off and disable_force

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#181]
The old start.exe program in V5.33.6 had two parameters disable_force_off and disable_force, but they don't seem to work in V5.43.6.  I typed start.exe /? into CMD and got a long list of parameters, but nothing resembling these two.

I may well be missing something obvious, but if they have not yet been implemented, they have my vote for a future version.  It's often useful to toggle forced browsers.

**Comment by mysteriously** [comment]
"C:\Program Files\Sandboxie\Start.exe" /box:Chrome  /disable_force "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"

**Comment by NotepadPlusUser** [comment]
Thanks, @mysteriously.  I've done some more experiments using CMD, and now the situation is not at all clear to me.  I am no techie, so all I can do is report the behaviour. I am using V5.43.6 on Windows 10 2004 19041.610.

* After I have I run **"C:\Program Files\Sandboxie\Start.exe" disable_force_off** (note no slash before **disable**) the two forced browsers Vivaldi and Firefox always open within the default sandbox.  And there is no error message, whereas adding the slash gives an error message.

* After I have run **"C:\Program Files\Sandboxie\Start.exe" disable_force** the two forced browsers sometimes open outside Sandboxie (particularly first time), but mostly still open within the default sandbox.  And there is no error message.

I ran these two commands (assisted by shortcuts) successfully for years with the old Sandboxie.

There's no documentation using /? of these two commands.  Using **help** instead (no slash) makes a new CMD window appear very briefly and run though a list that I can't make out (with no error message).  Perhaps fragments of the old code are still hanging about.

**Comment by Coverlin** [comment]
https://sandboxie-website-archive.github.io/www.sandboxie.com/StartCommandLine.html#disableforce

**Comment by bjm234** [comment]
https://xanasoft.com/sandboxie/startcommandline/

**Comment by DavidXanatos** [comment]
https://sandboxie-plus.com/sandboxie/startcommandline/

hmm this is indeed broken... wil have to look into fixing it

**Comment by DavidXanatos** [comment]
no i was wrong the only thign broken was in my local tets build the last release seams to handle the command just fine

**Comment by NotepadPlusUser** [comment]
I have now upgraded to Plus, and the commands work perfectly for me.  I then used them to create a Directory Opus button that does the job --- no worries.  Thanks very much for your concern about these small details.
