### ISSUE TITLE
Sandboxie-Plus does not register with CCleaner

### ISSUE THREAD

**Issue by bjm234** [sandboxie-plus/Sandboxie#182]
Sandboxie registers with CCleaner.  I run a few boxes sans Automatically delete.  My habit has been to check CCleaner Utilities to delete boxes contents that I prefer to run sans Automatically delete.   Not a deal breaker.  Just sharing.  Thanks
Sandboxie
![image](https://user-images.githubusercontent.com/25015553/98053963-cbef6400-1e07-11eb-892a-0e785bf17b20.png)
Sandboxie-Plus
![image](https://user-images.githubusercontent.com/25015553/98054003-e0336100-1e07-11eb-938c-831ac397c2a9.png)

**Comment by DavidXanatos** [comment]
I'm pretty sure sandboxie does not do anything, its CC Cleaner that actively looks for it,
Plus is installed to a different location and so on, hence they don't notice it,
talk to CC cleaner for adding SbiePlus support.
