### ISSUE TITLE
Error when upgrading from old ver to current classic (because of missing version check)

### ISSUE THREAD

**Issue by dfgyuri** [sandboxie-plus/Sandboxie#1821]
### What happened?

tried to upgrade an old sandboxie install (I believe it was 5.33.2 but not 100% sure) to the current classic version and during the process it gave a KmdUtil: ControlService Interrogate: The service cannot accept control messages at this time messagebox. And later would fail in the install with "cannot create or update sandboxie program files"

### Download link

Not relevant

### Expected behavior

installer upgrades sandboxie without issue

### What is your Windows edition and version?

Windows 10 Education 21H2

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Windows defender

### What version of Sandboxie are you running?

5.33.2 trying to upgrade to 5.55.15 classic

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by APMichael** [comment]
Version 5.33.x was still from Sophos. To use David's version, it always had to be uninstalled before. Therefore, the changelog since then also states: "If you have issues with an update installation, just uninstall the previous version keeping the sandboxie.ini and reinstall the new build."

**Comment by isaak654** [comment]
The lead developer did not prevent Sandboxie Classic upgrades before a certain release (as asked in https://github.com/sandboxie-plus/Sandboxie/issues/738), but only the installation of Sandboxie Classic after an existing Plus installation: [Sandboxie/install/SandboxieVS.nsi](https://github.com/sandboxie-plus/Sandboxie/commit/e08e9b0fd5391951f9c5d5c2f6261775a7410aa0#diff-68203c40e515e70ee240d5291ca5fa6589416c99d223c9f317c456df60e5df98)

I think it's part of the plan to encourage anyone to use Sandboxie Plus.

**Comment by DavidXanatos** [comment]
The current classic installer can proeprly handle uninstalation of odler sophos builds.
the issue discribed in the opening post is most likely due to an suttle incompatybility between windows 10 2004 and later with the old driver, which nessesitates a reboto to be able to uninstall it.
