### ISSUE TITLE
[Plus UI] Selecting "Internet Restrictions" tab always marks options dialog dirty

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#1825]
### What happened?

In the Box Options dialog, just switching to the "Internet Restrictions" tab marks the dialog as dirty. Pressing Esc then pops up the following dialog even if nothing was changed:
![grafik](https://user-images.githubusercontent.com/78082344/165515237-2a3ca6a2-e3a3-4920-a798-7db16440f206.png)

Maybe `OnBlockINet` should not be called until a change was made?
https://github.com/sandboxie-plus/Sandboxie/blob/952bee0c688af12e56ad4a1d1713361fdf65ea1d/SandboxiePlus/SandMan/Windows/OptionsWindow.cpp#L686

### Download link

N/A

### To Reproduce

1. Open Sandbox Options dialog for any box
2. Switch to "Internet Restrictions" tab
3. without changing anything, try to close dialog by pressing Esc

### Expected behavior

No warning dialog on Esc if nothing was changed

### What is your Windows edition and version?

Windows 10 20H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

N/A

### What version of Sandboxie are you running?

Sandboxie-Plus 1.0.19 64-bit

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by bastik-1001** [comment]
For me Sandboxie-Plus does the same. Simply opening the tab triggers it.
