### ISSUE TITLE
MSI Installers fail to run inside any sandbox

### ISSUE THREAD

**Issue by soleera** [sandboxie-plus/Sandboxie#1826]
### What happened?

MSI installers fail with error 1625 ("The system administrator has set policies to prevent this installation.") when run inside any sandbox. This occurs even when isolation is not enforced (e.g. application compartments). This issue is present in fresh installs of Windows 11 from the current dev channel, but does not seem to affect the current public release or beta builds. 

### Download link

https://store.epicgames.com/en-US/download

### To Reproduce

1. Install a fresh copy of Windows 11 Home build 22598 and update to the latest subversion.
2. Install Sandboxie-plus.
3. Create a new sandbox (any configuration).
4. Download an MSI Installer (e.g. https://store.epicgames.com/en-US/download).
5. Attempt to run the MSI Installer inside the sandbox (via right click context menu, explorer, or command prompt).
6. Error message appears.

### Expected behavior

MSI Installers are able to run.

### What is your Windows edition and version?

Windows 11 Home build 22598.200

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

Windows Defender only

### What version of Sandboxie are you running?

1.0.15 64-bit

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Trace log

https://gist.github.com/soleera/25ec0ab7d21467cf4596f9dd416067d7

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]

[UserSettings_08C401B6]
SbieCtrl_AutoStartAgent=SandMan.exe

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[Test]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
NoSecurityIsolation=y
UsePrivacyMode=n
BoxNameTitle=n
MsiInstallerExemptions=y
CopyLimitKb=81920
```

**Comment by DavidXanatos** [comment]
On the 22610 insider build the installer does not show this error, it must be something specific to your system.

**Comment by soleera** [comment]
Tested again with Hyper-V running insider build 22616 and couldn't replicate the problem. You're probably right that it was just and issue with my particular setup, so I'll close this issue.
