### ISSUE TITLE
Sandboxie-Plus 1.0.19 does not allow encrypted videos to be played in Firefox

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#1831]
### What happened?

TL,DR: Sandboxie-Plus 1.0.19  does not play Netflix videos in Firefox, while Sandboxie-Plus 1.0.18 does.

I occasionally watch Netflix videos in Firefox, which is forced to run in a sandbox. It used to work with some versions ago and at first I guessed a network issue, before blaming Firefox extensions, since the version of Firefox did not change nor its configuration, but then I ran Firefox, while disabling it being forced to run sandboxed, so it ran normally. And without Sandboxie Netflix started to play videos again.

Netflix normally uses the encryption module spawned via plugin-container.exe, but when run in Sandboxie, it would not load any Netflix video and Firefox did not show any sign of the plugin being loaded. This was true for a clean sandbox with standard settings.

Since new versions of Sandboxie added or changed something and I was not sure if it was due to the configuration, I disabled the memory access prevention, the kernelmode object filter, the win32 hooks, but neither of them worked, so I enabled them again.

Now I went back from Sandboxie-Plus 1.0.19 to Sandboxie 1.0.18 and it works. (I planned to go through all the latest version as I could not recall if 0.15 was the latest working version, but just going back one version was enough.)

The drop-down below, lets me select for which sandboxes it applies, and I can only select one, which for me is not working, since  it does happen with all the boxes I can configure, that being the standard and the hardened one. For me those are all I try, so from my point of view I had to select all of them, but I can't be sure that this issue applies to app compartment,

### Download link

Not relevant

### To Reproduce

1. Install Sandboxie-Plus 1.0.19 x64
2. Install Firefox 99 x64 in the system (not sure if it has to be installed there, but that is my case.)
3. Start Firefox in a sandbox
4. Log into Netflix, which works
5. Try to play a video, which will try to start, but fail
6. Close Firefox
7. Start Firefox outside a sandbox, log into Netflix and play a video, which should work this time.
7.1 Alternatively, revert back to Sandboxie-Plus 1.0.18, log into Netflix and play a video which works again.

### Expected behavior

The sandboxed Firefox instance being able to play Netflix videos.

### What is your Windows edition and version?

Windows 7 SP1 x64

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Window Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.0.19 x64

### Is it a regression?

Sandboxie-Plus 1.0.18 x64

### List of affected browsers

I only tried Firefox 99 x64, since that was the version that worked before and was supposed to work

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
Confirmed, see the following user report from Wilders:
https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-19.445081/#post-3079804

> After updating from 18 to 19, I could no longer watch series on Viki with Firefox. After the downgrade to the 18 it works again.
> For testing:
> https://www.viki.com/v1/explore?access=free
> 
> Tested with:
> Classic x64 on Windows 7 (native) and Windows 10 (VM)

**Comment by DavidXanatos** [comment]
this is really strange, could you please test build 1.0.19 using the driver from build 1.0.18?

**Comment by bastik-1001** [comment]
I kept version 1.0.18 installed and extracted 1.0.19 for portable use. Then I launched sandman (1.0.19) and manually started Firefox in a standard box. Then I could play Netflix videos, while Firefox was under the supervision of sandman 1.0.19. Is that what I was supposed to try?

**Comment by DavidXanatos** [comment]
no but dont wary i alrerady managed to reproduce and narow in the issue fix will be ready soon

**Comment by DavidXanatos** [comment]
workaround OpenIpcPath=\??\pipe\*

**Comment by mysteriously** [comment]
Seems like fixing the issue heavy decreased video playback performance for 1.0.20

**Comment by DavidXanatos** [comment]
The initial change that broke the DRM was an isolation of symlink objects, the fix was to open the required path for pipes for read only access,
possibly you may need to open more paths for reading.

how to reproduce this performance impact, also please quantify, is it switchign from gpu accelerated to cpu only is it always cpu only just now worse, etc?

**Comment by DavidXanatos** [comment]
I created a new issue for the performance problem: https://github.com/sandboxie-plus/Sandboxie/issues/1841
