### ISSUE TITLE
[1.0.15] Blue screen during uninstallation

### ISSUE THREAD

**Issue by truemogician** [sandboxie-plus/Sandboxie#1832]
### What happened?

As the title goes, a system crash during uninstallation.  
The blue screen code is `DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS`  
The related driver is `SbieDrv.sys`  
The error code is pretty self-explaining, which indicates that something still running is relying on Sandboxie's driver. And I do have a Sandboxie process running during uninstallation. So I guess the solution is to check and terminate any running Sandboxie processes before the uninstallation.

### Download link

Not relavant

### To Reproduce

1. Run Sandboxie
2. Perform an uninstallation from Control Panel

### Expected behavior

No blue screen

### What is your Windows edition and version?

Windows 10 Professional 21H1

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relavent

### What version of Sandboxie are you running?

1.0.15 64bit

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by truemogician** [comment]
In addition, I manually terminate the Sandboxie process and perform the uninstallation after rebooting, everything goes fine then.

**Comment by isaak654** [comment]
A similar behavior was also described in #1811

**Comment by DavidXanatos** [comment]
please refer to the already posted issue as it seams th be the same problem, I'll close this as duplicate and post some more about this in the other one
