### ISSUE TITLE
Windows Start Menu Integration

### ISSUE THREAD

**Issue by u254254** [sandboxie-plus/Sandboxie#1836]
### Is your feature request related to a problem or use case?

When I installed a program to the sandbox, I need to start Sandboxie-plus, right-click a box, Run -> Run from Start Menu, and click program to start one.

### Describe the solution you'd like

Create Start Menu folder for sandbox, Sandbox Manager detects Start menu changes in the box, and clone it to box's folder.

### Describe alternatives you've considered

Create shortcut to 'Run from Start Menu' for each boxes to Start Menu.

**Comment by DavidXanatos** [comment]
I was thinking about sich a feature already for a long time, but then windows 11 came which has a useless start menu so I'm not sure how much use this feature would get on the long run,
on the otehr hand all users of classic shell/open shell or start 11, start all back or atc... would benefit from it...

**Comment by u254254** [comment]
I think there are a lot of people still using Windows 10, or Alternative Start Menu(*like Start11, StartAllBack*), and that will be great for that people. (I'm using StartAllBack)

**Comment by Trooper27** [comment]
I would love to see it in Windows 11 regardless.

**Comment by DavidXanatos** [comment]
This feature will be in one of teh over next builds like 1.2.x or alike

**Comment by DavidXanatos** [comment]
feature is scheduled for 1.4.0 and is available in the private preview build for patrons in the 10$ tier and above
