### ISSUE TITLE
One web page cause almost crash the sandbox..

### ISSUE THREAD

**Issue by MancioDellaVega** [sandboxie-plus/Sandboxie#1838]
### What happened?

In this site https://www.betflag.it/casino
When i try to play at the French roulette the animation goes very slowly and the browers Chrome
respond to commands very slowly..

![20220505173926](https://user-images.githubusercontent.com/90178919/166960777-c0a2de57-1d87-4e2d-8401-1d32c9368496.PNG)

### Download link

not relevant

### Expected behavior

The animation go more fluid

### What is your Windows edition and version?

Window 10 Home 32 bit  21H2 build 19044.1682

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Windows Defender and firewall

### What version of Sandboxie are you running?

Plus 1.0.20

### List of affected browsers

Firefox 100.0 and Chrome 101.0

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=y
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
StartRunAlertDenied=n
NotifyStartRunAccessDenied=y

[UserSettings_00640032]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=D:\DownLoads
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,5
Template=Chrome_History_DirectAccess
Template=Chrome_Passwords_DirectAccess
Template=Chrome_Cookies_DirectAccess
Template=Firefox_Bookmarks_DirectAccess
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
BoxNameTitle=n
CopyLimitKb=81920
```

**Comment by isaak654** [comment]
Please downgrade to [v1.0.19](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.19) and report if it improves the situation.

**Comment by isaak654** [comment]
Please downgrade to [v1.0.19](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.19) and [v1.0.18](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.18) and report which release improves the situation.

**Comment by MancioDellaVega** [comment]
> Please downgrade to [v1.0.19](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.19) and [v1.0.18](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.18) and report which release improves the situation (if any).

I have the same issues with both versions ..😞

**Comment by DavidXanatos** [comment]
than please try older versions, what was the last version that was fine?

**Comment by MancioDellaVega** [comment]
> than please try older versions, what was the last version that was fine?

My last version was 5.33.3 that after the latest Chrome updates it no longer worked...so now I decided to install the plus...
so this is my first attempt with these free open source versions of sandiebox..😞

**Comment by MancioDellaVega** [comment]
Today seems that work all fine...i have always the version 1.0.20...
so maybe the site did update the game software or there was something in mine
configuration that was wrong ...
