### ISSUE TITLE
See qt.io = Application Error

### ISSUE THREAD

**Issue by bjm234** [sandboxie-plus/Sandboxie#184]
About Qt > See Qt.io > Application Error with forced default browser. 
![image](https://user-images.githubusercontent.com/25015553/98075777-fc9cc100-1e3a-11eb-967e-0e748f196e58.png)
![image](https://user-images.githubusercontent.com/25015553/98075598-ac256380-1e3a-11eb-987f-b0f12d7cfcd7.png)

**Comment by bjm234** [comment]
Application Error with forced default browser - calling links from > 
![image](https://user-images.githubusercontent.com/25015553/99303504-05b86580-281f-11eb-9e71-f3748da0a0fa.png)

**Comment by bjm234** [comment]
FWIW ~ may be related
https://www.wilderssecurity.com/threads/released-sandboxie-plus-sbie-fork-versions-with-signed-driver.434924/page-5#post-2973721

**Comment by DavidXanatos** [comment]
This is somehow caused by how Qt handles link clicks, I'll have to look deeper into that for a fix.

**Comment by DavidXanatos** [comment]
I couldn't reproduce this issue in my recent build, does it still happen?

**Comment by bjm234** [comment]
![image](https://user-images.githubusercontent.com/25015553/102800098-60466380-4381-11eb-8a8d-044a5b6a92a2.png)

**Comment by bjm234** [comment]
![image](https://user-images.githubusercontent.com/25015553/103758240-ec8e9280-4fdf-11eb-84a9-8c87f87b199f.png)
![image](https://user-images.githubusercontent.com/25015553/103758295-fca67200-4fdf-11eb-9d39-f81a3e662c0d.png)
0.5.3b

**Comment by bjm234** [comment]
Works for me. 
![image](https://user-images.githubusercontent.com/25015553/103968225-7306b980-5131-11eb-8fa8-b97188a091d4.png)
0.5.3b
