### ISSUE TITLE
1.1.0 Recover Files Bug 2.0

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#1840]
### What happened?

Recover Files does not keep folder structure if the target is not the original location and will place every file in the same folder

"Special" description :
RestoreFolder
 .files
.-folder1
...-files
.-folder2
 ...-files
All the files will be put in the RestoreFolder

### Download link

xD

### To Reproduce

1 Select a Box
2 Open Recover Files
-Optional: Show All
3 Select a sandboxed folder
4 Choose a custom recover target
5 $Profit$

### Expected behavior

Folders have rights too

### What is your Windows edition and version?

W7 Ultimate SP1 x64

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

I like to live dangerously

### What version of Sandboxie are you running?

Plus 1.0.20

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
The old sandboxie controll does the same,
how would it know when the target is a custom folder from which part of the fodler structure to keep the paths?
go up to the folder entered in the recovery setings?
or based on the users selection use the folder the user selected if he did not select the sub files?

**Comment by RandomGOTI** [comment]
> The old sandboxie controll does the same, how would it know when the target is a custom folder from which part of the fodler structure to keep the paths? go up to the folder entered in the recovery setings? or based on the users selection use the folder the user selected if he did not select the sub files?

Example Path with a file to recover :  C:\Program Files\Mozilla Firefox\distribution\policies.json
Target/Custom/Browse for location/Recover to Any Folder : To the users desktop

Classic 5.55.20
With Select All : Program Files\Mozilla Firefox\distribution\policies.json will be on desktop
With only "Mozilla Firefox" folder selected : Mozilla Firefox\distribution\policies.json will be on desktop
With only  "policies.json" selected  : policies.json will be on desktop
All good 3/3

Plus 1.0.20
With All Selectected/Highlighted : policies.json will be on desktop
With only Mozilla Firefox folder selected : policies.json will be on desktop
With only policies.json selected : policies.json will be on desktop
1/3
