### ISSUE TITLE
Automate publishing of Sandboxie-Plus to Windows Package Manager

### ISSUE THREAD

**Issue by vedantmgoyal2009** [sandboxie-plus/Sandboxie#1845]
### Is your feature request related to a problem or use case?

The title says it all :)

### Describe the solution you'd like

@DavidXanatos I can create a GitHub workflow if you would like.

**Comment by DavidXanatos** [comment]
Yea that sounds useful if you can create a workflow that excludes pre-releases than please go ahead.

**Comment by isaak654** [comment]
Also, if you're interested, we would need extra help in the creation of a new workflow to automate the delivery of language updates: https://github.com/sandboxie-plus/Sandboxie/discussions/1819#discussioncomment-2621838

**Comment by vedantmgoyal2009** [comment]
Just to confirm, this discussion contains the commands to be run to update translations: https://github.com/sandboxie-plus/Sandboxie/discussions/1123.

**Comment by isaak654** [comment]
Sandboxie Plus translation files only, yes.
About Sandboxie Classic translation files (which are sometimes used in specific Plus options), there are a few forgotten batch scripts [here](https://github.com/sandboxie-plus/Sandboxie/tree/master/Sandboxie/msgs) that could be helpful.

**Comment by vedantmgoyal2009** [comment]
@DavidXanatos please give the token `workflow` permission also.

**Comment by DavidXanatos** [comment]
what is that permission needed for?

**Comment by vedantmgoyal2009** [comment]
https://github.com/sandboxie-plus/Sandboxie/runs/7931748039?check_suite_focus=true#step:2:173

**Comment by DavidXanatos** [comment]
done

**Comment by vedantmgoyal9** [comment]
> Also, if you're interested, we would need extra help in the creation of a new workflow to automate the delivery of language updates: [#1819 (comment)](https://github.com/sandboxie-plus/Sandboxie/discussions/1819#discussioncomment-2621838)

@DavidXanatos I was randomly browsing through old threads and found your comment. I'm hoping this has been solved by [lupdate workflow](https://github.com/sandboxie-plus/Sandboxie/blob/master/.github/workflows/lupdate.yml). Is there anything else where I can help and contribute to the project? 🙏🏻

**Comment by isaak654** [comment]
> Is there anything else where I can help and contribute to the project? 🙏🏻

Do you know a copyright lawyer for #3898?
