### ISSUE TITLE
A two-month-old release is shown as the latest release on GitHub

### ISSUE THREAD

**Issue by benrg** [sandboxie-plus/Sandboxie#1848]
On the GitHub main page (https://github.com/sandboxie-plus/Sandboxie) the latest release is listed as v1.0.12 / 5.55.12 dated March 4, and the download link in the readme also goes to that release, even though the latest release is really 1.0.21.

**Comment by mysteriously** [comment]
https://github.com/sandboxie-plus/Sandboxie/tags

**Comment by isaak654** [comment]
I think it's fixed now.
