### ISSUE TITLE
Use github releases to check for updates

### ISSUE THREAD

**Issue by KieranDevvs** [sandboxie-plus/Sandboxie#1850]
### Is your feature request related to a problem or use case?

Currently the app calls `https://xanasoft.com/update-v1.php?software=sandboxie-plus&version=xxx` to check for the latest version and uses the json response to get the download link for the newest MSI package. If the response does not contain a `downloadUrl` key then you are prompted to navigate to the downloads page and download it manually. Currently the PHP web app does not provide a download Url so downloads have to be done manually which is slightly inconvenient.

### Describe the solution you'd like

I'd like to remove the need for this PHP call and query the github releases directly as this seems to be the true *source of truth*. This would also guarantee a download URI to automatically download the updates from within the app if necessary and avoid the conditional logic described above.

I don't mind doing the work myself and opening a PR, I just want to get confirmation that this is something that would be accepted before I sink time into it. I have a feeling the PHP web app is used for analytics which may be deemed necessary.

### Describe alternatives you've considered

N/a

**Comment by DavidXanatos** [comment]
I don't like hard coding github url's also its always good to wait a few days after a release before pushing it vial auto update to ensure there are no new major issues.

**Comment by KieranDevvs** [comment]
> I don't like hard coding github url's also it's always good to wait a few days after a release before pushing it vial auto update to ensure there are no new major issues.

Fair enough. It might be worth considering doing beta's / release candidates to alleviate the problem of making sure no major issues are introduced.

**Comment by KieranDevvs** [comment]
> I don't like hard coding github url's also its always good to wait a few days after a release before pushing it vial auto update to ensure there are no new major issues.

Fair enough.
