### ISSUE TITLE
[Plus UI 1.0.21] Some entries still require a restart to change the interface language

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1852]
The following change introduced in Plus 1.0.21 is not totally applied for a few entries:

- changing the language no longer requires a restart on Plus UI

If you change Plus UI language from `No translation` or `American English` to other foreign languages like `Italian` or `German`, the `Copy Cell`, `Copy Row`, `Copy Panel` and `Support Sandboxie-Plus on Patreon` entries still require a restart in order to be updated:
![context_menu_entries_from_English_to_Deutsch](https://user-images.githubusercontent.com/12372772/168069009-66e9afc9-6bf4-4793-9819-0b7dde2115f8.png)

![context_menu_entries_from_English_to_Italian](https://user-images.githubusercontent.com/12372772/168070830-14f1daeb-60e6-4c1c-ace5-e8cbf2af60a8.png)

![Support_Patreon](https://user-images.githubusercontent.com/12372772/168070036-d122e223-8b1e-42ed-ad81-b632c2980434.png)

**Comment by DavidXanatos** [comment]
ok if that's all that is actually quite good :D will be fixed in next build
