### ISSUE TITLE
"The Recycle Bin on C:\ is corrupted" When opening explorer in sandboxie

### ISSUE THREAD

**Issue by lostwindsenril** [sandboxie-plus/Sandboxie#1856]
### What happened?

Hi. 
When I tried to open explorer.exe **inside sandboxie**, it always warned like this: 
```
The Recycle Bin on C:\ is corrupted. Do you want to empty the Recycle Bin for this drive?
```
![无标题](https://user-images.githubusercontent.com/24893148/168463548-67b104dc-abba-45aa-8e6f-29a98eb3d264.png)

This problem is showing on any type of **Data Protection sandbox**, including red, blue and cyan sandbox.

I've searched about this problem in this repo issues, but nothing related was founded.
However, My system language is Chinese, and I found another Chinese user talked about this problem in an article:
[https://www.konoka.top/trick/win/890/](https://www.konoka.top/trick/win/890/)
> 隐私模式可能会导致沙盒内弹出回收站已损坏的提示，按是无视即可。
Privacy mode may cause a message that the recycle bin is corrupted to pop up in the sandbox. Press Yes to ignore it.

This discovery made me wonder if the problem is related to systems languages。

### Download link

No

### To Reproduce
This problem is showing on any type of Data Protection sandbox, including red, blue and cyan sandbox.
This problem can be reproduced in 2 ways, regardless of what applications installed.
1) right click any sandbox -> Run -> Boxed tools -> Windows Explorer
2) or any application with "open folder" button. In my cases are WeChat and Baidu NetDisk.

### Expected behavior

Not showing warning box like this

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2022 ( the same as Windows 10 21H2)

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.0.20 64Bit

### List of affected browsers

Explorer.exe

### In which sandbox type you have this problem?

In an Application Compartment sandbox with data protection (cyan sandbox icon).

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
recycle bin should be disabled within the sandbox its a known issue that it does nto work properly int he box

**Comment by lostwindsenril** [comment]
> recycle bin should be disabled within the sandbox its a known issue that it does nto work properly int he box

Just wondering if there is any way to avoid this warning pop up.

**Comment by Oridjinn1980** [comment]
> Just wondering if there is any way to avoid this warning pop up.

I was also running into this issue, and I'm running the English version of Sandboxie-Plus v1.0.20, so it isn't language specific! I tried adding this rule to Resource Access, and the warning no longer showed up (at least in my testing). 
`NormalFilePath=C:\$Recycle.Bin`
If you have multiple drives, I think you would just replace "C" with whatever drive is giving you issues.

**Comment by lostwindsenril** [comment]
> > Just wondering if there is any way to avoid this warning pop up.
> 
> I was also running into this issue, and I'm running the English version of Sandboxie-Plus v1.0.20, so it isn't language specific! I tried adding this rule to Resource Access, and the warning no longer showed up (at least in my testing). `NormalFilePath=C:\$Recycle.Bin` If you have multiple drives, I think you would just replace "C" with whatever drive is giving you issues.

Great, it works! Appreciate for your tip.
