### ISSUE TITLE
Windows Defender flags the driver as a trojan.

### ISSUE THREAD

**Issue by ipoopedmypantsuups** [sandboxie-plus/Sandboxie#186]
![image](https://user-images.githubusercontent.com/73392805/98126679-dcddbb00-1e83-11eb-9573-cc46c7a90591.png)
Driver gets detected as trojan...

**Comment by deflock** [comment]
No problem. Just give him $5000 🤡

**Comment by NewKidOnTheBlock** [comment]
As long as the driver ain't signed, it's only gonna get more popular:
![getting really popular](https://user-images.githubusercontent.com/12411527/98294991-19f39b80-1fb1-11eb-8b2f-eea8cc34e9a3.png)

**Comment by DavidXanatos** [comment]
this problem is known: https://github.com/sandboxie-plus/Sandboxie/issues/95
