### ISSUE TITLE
Save As Dialogue Box is Blank in Adobe Acrobat

### ISSUE THREAD

**Issue by WSC33** [sandboxie-plus/Sandboxie#1863]
### What happened?

I have just upgraded Sandboxie to version 5.55.20, 64 bit, classic. I am trying to save a PDF document from my Sandboxie Firefox browser and the dialogue box that appears when I select “Save As” is blank except for the word PDF at the top. I use Adobe Professional DC, which I have employed through multiple versions of Sandboxie. I'm on Windows 10.

I have run this by the SB community and they can duplicate the error.  

### Download link

Not relevant.

### To Reproduce

See above.

### Expected behavior

A dialogue box

### What is your Windows edition and version?

Windows 10 

### In which Windows account you have this problem?

User account with secure desktop turned off for UAC prompts.

### Please mention any installed security software

Windows defender

### What version of Sandboxie are you running?

5.55.20, 64 abit

### Is it a regression?

The one specified above.

### List of affected browsers

Firefox 98

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

No.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
AlertProcess=Firefox
Template=RpcPortBindings
Template=AdobeDistiller
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
ForceDisableSeconds=300

[DefaultBox]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
RecoverFolder=M:
RecoverFolder=F:
RecoverFolder=E:
RecoverFolder=D:
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
ForceProcess=Mozilla
ForceProcess=Firefox
Template=AdobeAcrobatReader
Template=AdobeAcrobat
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=Firefox_Profile_DirectAccess
Template=Firefox_Session_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=Firefox_Passwords_DirectAccess
Template=Firefox_Cookies_DirectAccess
Template=Firefox_Bookmarks_DirectAccess
Template=Firefox_Force
AutoRecover=y
CopyLimitKb=877393

[UserSettings_24600398]

SbieCtrl_UserName=scott_cox
SbieCtrl_NextUpdateCheck=1653081200
SbieCtrl_AutoApplySettings=n
SbieCtrl_WindowCoords=2495,165,810,550
SbieCtrl_ActiveView=40022
SbieCtrl_RecoverTarget=E:\Zip
SbieCtrl_RecoverTarget=E:\Scanned Documents\Others\Exercise, Diet, Health\COVID-19
SbieCtrl_RecoverTarget=C:\Users\Scott Cox\Desktop
SbieCtrl_RecoverTarget=E:\Calendar Creator\Christmas Calendar 2022\Rob Cox
SbieCtrl_RecoverTarget=E:\Finances\Stock\Annual Reports\2021
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_HideWindowNotify=n
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_HideMessage=2205,CredWriteA
```

**Comment by bjm234** [comment]
adding Wilders thread
https://www.wilderssecurity.com/threads/save-as-dialogue-box-is-blank.445270/

**Comment by WSC33** [comment]
Any update or progress report on this issue?

**Comment by isaak654** [comment]
Can you confirm that this requires Adobe Acrobat DC to be set up in advance as the default PDF application within Firefox itself?

**Comment by DavidXanatos** [comment]
On a quick check as far back as 0.5.5 acrobat DC does not seam to work in a restricted box, so what version was the one you updated from, which was working?

**Comment by WSC33** [comment]
Can you tell me what that means?  I just updated SB as I always have.  Acrobat is always the default app in FF, if that's what you mean.

**Comment by WSC33** [comment]
It may have been 5.50.9 but I wouldn't swear to it.

**Comment by DavidXanatos** [comment]
hmm.. does not work for me eider, so there is something deeply broken with acrobat wight now, and without a working referenc its realy hard to figoure out what, since it was working for you at some point eider its a change in acrobat itself or a config you had made it work

**Comment by WSC33** [comment]
So the problem is with the SB product?  Can you fix this?

**Comment by DavidXanatos** [comment]
So for the Acrobat Pro DC the fix is
UseSbieWndStation=n

![grafik](https://user-images.githubusercontent.com/3890945/171343328-59f04463-77b1-4f74-8f5d-f2c0aeb1a132.png)



for the non pro version it seams there is an additional problem not sure what though

**Comment by WSC33** [comment]
I have Sandboxie-Classic-x64-v5.55.20 installed.  My interface doesn't look like yours, and I've been thru all of the settings options, and I don't see this box nor a "Compatibility" label.  Where is this on the Classic-Plus version?  Thanks.

**Comment by isaak654** [comment]
If you use Sandboxie Classic, you can only add that parameter in the Sandboxie.ini configuration file under the sandbox in question. The lead developer's goal is to encourage as many people as possible to adopt the Plus interface.

**Comment by DavidXanatos** [comment]
In build 1.1 the issue will be fixed

**Comment by DavidXanatos** [comment]
Since version 1.xx the it should have all classic features and much more.

the line needs to be added to each box or to the global settings section

**Comment by isaak654** [comment]
I would suggest to add `EnableWin32kHooks=n` under the `[GlobalSettings]` section of Sandboxie.ini and see if it works.

**Comment by WSC33** [comment]
Perfect.  Downloaded and no error. I put both command lines under the global settings in the ini.

**Comment by Germs2004** [comment]
fyi, in Sandboxie Plus 1.0.22, checking that box and adding `EnableWin32kHooks=n` to the ini did not fix the issue for me.  I'll try again when 1.1 is out.
