### ISSUE TITLE
Add language support for Plus entry "Sandboxie config has been reloaded"

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1864]
### Is your feature request related to a problem or use case?

"Sandboxie config has been reloaded" entry has no translation support at all on Plus UI:
![immagine](https://user-images.githubusercontent.com/12372772/169063213-d6de93bc-ce39-4ac0-9270-57adcc01517b.png)

### Describe the solution you'd like

Add multilanguage support for it.

**Comment by DavidXanatos** [comment]
ach darn it i moved the string to the sandman.exe but forgot to add the tr macto macro will be fixed in the next build

**Comment by isaak654** [comment]
I can't find it in the commit's history, a precise indication would be appreciated.

**Comment by DavidXanatos** [comment]
https://github.com/sandboxie-plus/Sandboxie/blob/3f7bada5beec96ec79c934439085b036daab61db/SandboxiePlus/SandMan/SandMan.cpp#L2071
