### ISSUE TITLE
Need Help Troubleshooting an Issue with Sandboxie 

### ISSUE THREAD

**Issue by Disnihil** [sandboxie-plus/Sandboxie#1869]
### What happened?

I'm trying to use Sandboxie to take a screenshot of a scene of a show on a streaming and I keep getting this error message:

SBIE2203 Failed to communicate with Sandboxie Service: detail

Prior to the end of last week, I'd regularly use Sandboxie to capture screenshots and never had any issues whatsoever. It just randomly started last week and I can't figure out how to fix this issue. Any tips? 

### Download link

Not available 

### Expected behavior

Up until last week, I was able to use Sandboxie to capture screenshots without issue. 

### What is your Windows edition and version?

Windows 10

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Spybot Search & Destroy 

### What version of Sandboxie are you running?

Sandboxie Plus (most recent version) 

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
1. Which program are you using inside the sandbox to take the screenshots?
2. It may also be useful to know the streaming service in question, with a direct link to share.
3. Which web browser are you using?
4. Please provide also an accurate list of steps to reproduce for any eventuality.
