### ISSUE TITLE
RuCaptchaBot.exe (4788): SBIE2224 Sandboxed program has crashed: RuCaptchaBot.exe

### ISSUE THREAD

**Issue by DSICARD** [sandboxie-plus/Sandboxie#1870]
### What happened with RuCaptcha Bot in sandboxie?

Hello,

I have had a problem and I have not been able to know why it occurs.

It turns out that when I open several boxes of this RucaptchaBot.exe program, there comes a point where that message appears and the program does not work well. I have to restart the sandbox and run it again, but I don't want to do that because the idea is to get v3 captchas as the VPN changes on my system with my NORTON 360 antivirus

Can someone help me to solve this problem?

### Reproducible video with steps:

https://www.loom.com/share/943972bfbc8f480bb1020889fcca829c

### Download link

https://github.com/rucaptcha/bot-x/releases

### Expected behavior

RuCaptchaBot.exe (4788): SBIE2224 Sandboxed program has crashed: RuCaptchaBot.exe

### What is your Windows edition and version?

10

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Norton 360

### What version of Sandboxie are you running?

Sandboxie Plus v1.0.20

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
#2037
