### ISSUE TITLE
Epic Games can't launch because of SBIE2101

### ISSUE THREAD

**Issue by mikwee** [sandboxie-plus/Sandboxie#1872]
### What happened?

First of all, please don't ask why I put Epic Games in a sandbox.
Each and every time I try to launch Epic, I get this error: `EpicGamesLauncher.exe (18172): SBIE2101 CreateMutant (C0000022) access=001F0001 initialized=1`
This error also occurs when trying to install it in an empty sandbox.

### Download link

https://store.epicgames.com/en-US/

### To Reproduce

1. Download the Epic Games launcher
2. Install it inside its own sandbox
3. Try to launch it

### Expected behavior

I expected the launcher to launch regularly.

### What is your Windows edition and version?

Windows 10 Pro 21H2 64-bit

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Only Windows Defender.

### What version of Sandboxie are you running?

Sandboxie Plus v0.7.2 64-bit

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Trace log

https://pastebin.com/H7yurvxx

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=BitDefenderInternetSecurity
Template=7zipShellEx
Template=LastPass
Template=WindowsRasMan
Template=Avast_Antivirus
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
KnownConflicts={FBEB98F8-64E4-4FA3-A15E-4A9F42FF962E}
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
IpcTrace=ad
PipeTrace=ad
GuiTrace=ad

[UserSettings_11C20283]

SbieCtrl_UserName=mikwee
SbieCtrl_NextUpdateCheck=1616664728
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_WindowCoords=1013,257,798,558
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_BoxExpandedView=,
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[Zoom]

ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=WindowsFontCache
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Enabled=y

[Epic_Games]

Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore

[iTunes]

Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook

[DefaultBox]

Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore

[Epic2]

Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
```

**Comment by isaak654** [comment]
> Sandboxie Plus v0.7.2 64-bit

It was released more than a year ago, I doubt the lead developer will consider it.
Also, you may want to read the suggestion posted in https://github.com/sandboxie-plus/Sandboxie/issues/1356#issuecomment-1008236793

**Comment by mikwee** [comment]
I'll update and see how it goes

**Comment by DavidXanatos** [comment]
try theoption 
ApplyElevateCreateProcessFix=y
and
MsiInstallerExemptions=y

with those two the instalation worked fine

**Comment by isaak654** [comment]
Your graphic cards error is also in #1897, you may want to try all suggestions mentioned in that issue.

More specifically:

- If you're running Windows 10, uninstall KB5014022 or other recent Windows updates.
- If you're running Windows 11, uninstall KB5014019 or other recent Windows updates.

**Comment by isaak654** [comment]
@ameaninglessname
Your graphics card error is also in #1897, you may want to try all suggestions mentioned in that issue.

More specifically:

- If you're running Windows 10, uninstall KB5014022.
- If you're running Windows 11, uninstall KB5014019.

**Comment by NewKidOnTheBlock** [comment]
I've been running ze Epic Games Launcher in a sandbox for years.
Add this launch parameter:
` -SkipBuildPatchPrereq`

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/171474842-b562e60c-4264-4b80-a707-d5f4b79c78c2.png)
try disabling that and lett us know if that helped

**Comment by mikwee** [comment]
This is probably not related to here, but after updating, I get this error any time I try to connect: `ControlService Start: The system cannot find the file specified. (2)`.
