### ISSUE TITLE
Adding a troubleshooting wizard in Sandboxie

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1875]
I would suggest adding a troubleshooting wizard in Sandboxie, which would be triggered automatically when an error is found, so that a detailed report can be saved and ready to be sent after user consent.

The report in question should match the same fields of the [problem report](https://github.com/sandboxie-plus/Sandboxie/issues/new?assignees=&labels=Confirmation+pending&template=1-problem_report.yml) template, or even more if needed.

In my opinion, it could be optionally extended to the Classic UI in order to cover the entire user base.

**Comment by DavidXanatos** [comment]
How to detect a failure? Many failure modes do not end with a crash. Often its the mouse not moving in some game, some window stay empty, or a custom message box with an error message. 
Also by default trace log is off hence can't be provided for an unexpected failure.

I was thinking about some sort of troubleshooting wizard on and off for quite some time and I think it would need to be a user interactive wizard, not like Windows's typical wizards that work like: click next, I'll do something or not don't tell you what, and afterwards it may work, or not.

I think it would work something like this:
First the user has to select what sort of program he is trying to get working, that is, if the program as such is trustworthy or suspected to be malicious. 
If its trustworthy we can proceed with the full process.

Full Process:
will try various insecure strategies including disabling token isolation, desktop isolation
followed by disabling system hooks, and security filtering
then disabling various DLL hooks 
After each step querying the user once the process terminated if worked or failed,
On failure it would move to the next pass disabling more security/isolation
On success it would refine the last disabled measures to find the culprit


Limited Process:
will not disable security measures only try to skip some optional DLL hooks
and make a trace log

**Comment by bastik-1001** [comment]
Whenever or not the wizard would be localized, it should be made clear that only reports in English can be processed properly.

Some programs send crash reports and if Sandboxie does the same I guess that it can be quite helpful to analyze crashes that are more widespread.

It should be stated where those reports are sent to and who has access to them, as they may contain private information.

The idea of a wizard that helps with configuring a certain sandbox in a way to run some software that otherwise fails to run, is interesting as well and it can potentially reduce the number of support requests.  It should be made clear that there can be drawbacks to how Sandboxie can isolate/restrict programs, when features need to be disabled for them to run.

**Comment by isaak654** [comment]
In case someone forgets the Sandboxie version that was previously working for a program, I think some kind of feature is needed to generate a history of all upgraded Sandboxie builds and obviously sorted by installation date.

**Comment by DavidXanatos** [comment]
I think this feature will be on the soon to be added agenda

**Comment by bastik-1001** [comment]
It's unclear to who has access to the reports (and the data) the user send in via this function. It's still new, so things might be subject to change, but it still could be clarified.

At least, the email address (if provided) can be considered confidential and users might wonder if those are transmitted and stored securely.

**Comment by DavidXanatos** [comment]
The data are transferred via a TLS encrypted connection ans stored on the sandboxie-plus.com server, currently only I and a Friend who administrates the server have access.
