### ISSUE TITLE
What is "SbieShellPkg.msix"?

### ISSUE THREAD

**Issue by CE1CECL** [sandboxie-plus/Sandboxie#1877]
### Is your feature request related to a problem or use case?

This isn't a feature request but rather a question.

### Describe the solution you'd like

[SbieShellPkg.zip](https://github.com/sandboxie-plus/Sandboxie/files/8748483/SbieShellPkg.zip)

When I double click this file, I get a "This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)" error. And When I open this file with 7zip, I get 3 files, all XML's. The assets don't exist anywhere so I couldn't self-sign it with WsAppBak. No one seems to know about this. Anyone have any ideas?

**Comment by DavidXanatos** [comment]
This is a sparse package see here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps it is used to provide the windows 11 compatible context menu, it is present since 1.0.22 and should be signed properly.

**Comment by isaak654** [comment]
> Anyone have any ideas?

https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-troubleshoot-app-package-signature-errors

> 0x800B010A | CERT_E_CHAINING | No certificate chain could be built to a trusted root authority from the cert that was used to sign the app package. | Continue to Step 2 to troubleshoot the certificate trust.

**Comment by CE1CECL** [comment]
> > Anyone have any ideas?
> 
> https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-troubleshoot-app-package-signature-errors
> 
> > 0x800B010A | CERT_E_CHAINING | No certificate chain could be built to a trusted root authority from the cert that was used to sign the app package. | Continue to Step 2 to troubleshoot the certificate trust.
> 
> Possibly related to the issue mentioned in [#1858 (comment)](https://github.com/sandboxie-plus/Sandboxie/discussions/1858#discussioncomment-2754720) and [#1858 (comment)](https://github.com/sandboxie-plus/Sandboxie/discussions/1858#discussioncomment-2755714)

I am using Windows 10 (not 11) and using sandboxie-plus 1.0.22, under releases I get "This app package is not supported for installation by App Installer because it uses certain restricted capabilities." But I used a CI build earlier so maybe that makes a difference. I did use Add-AppxPackage and it did install but cannot find "SbieShell.exe" anywhere (this is mentioned in AppxManifest.xml) Does this only work in 11?

**Comment by CE1CECL** [comment]
> This is a sparse package see here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps it is used to provide the windows 11 compatible context menu, it is present since 1.0.22 and should be signed properly.

Now that I am reading that, I'm seeing that there isn't supposed to be an EXE? "A sparse package contains a package manifest but no other app binaries and content. The manifest of a sparse package can reference files outside the package in a predetermined external location. "

**Comment by DavidXanatos** [comment]
Yes sparse package are a windows 11 feature iirc thay may started in a win 10 insider before 11 was  a thing but they never made it there to a production build.
Also with win 10 the normal menus work just fine, so no need for that anyways

**Comment by isaak654** [comment]
I think it probably should not be included in the Sandboxie folder of Windows systems other than Win11:
![SbieShell](https://user-images.githubusercontent.com/12372772/169694898-1681c477-6ae2-45ae-bd44-922b6ce57784.png)

**Comment by DavidXanatos** [comment]
Would be in a way nicer but then it would make the installer more complex, plus you couldn't take an installed folder and use it as portable on all systems.
So I think its best to leave it as is.

**Comment by isaak654** [comment]
A Wilders user reported an annoying RunDLL warning related to the introduction of this package:
https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-22.445247/page-3#post-3084363

> 
> Sandboxie 1.0.22 (running in portable mode).
> I get the following error when executing "uninstall all":
>
> There was a problem starting D:\SbiePlus\SbieShellExt.dll
> The specified module could not be found.

**Comment by DavidXanatos** [comment]
this is strange and i cant reproduce it, on windows 11 and 7 we don't invoke the win 11 code

**Comment by isaak654** [comment]
> this is strange and i cant reproduce it, on windows 11 and 7 we don't invoke the win 11 code

Unfortunately I was able to reproduce it on Windows 7 x64 Sp1:
![SbieShellExt_error_W7_x64_SP1](https://user-images.githubusercontent.com/12372772/170839993-5e17fd08-b5b7-4eac-a24a-0f71c5daa42d.png)

I'm on the latest CI build with Sbie Plus v1.1.1

**Comment by DavidXanatos** [comment]
ok so how to reproduce it exyctly step by stepp please

**Comment by isaak654** [comment]
> ok so how to reproduce it exyctly step by stepp please

1. Make sure to have the following Advanced options in Maintenance as below:
![Maintenance_Advanced](https://user-images.githubusercontent.com/12372772/170840766-b90016b5-f1fb-41e4-8459-d36596eef84d.png)
So no Sandboxie driver or service at all.

2. Sandbox -> Maintenance -> Disconnect
3. Sandbox -> Maintenance -> Uninstall all
4. Error is triggered at this point

I'm using the latest CI build. If you can't reproduce it, I could share the VM privately with you.

**Comment by DavidXanatos** [comment]
please check HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion value CurrentBuild what do you have there?

**Comment by isaak654** [comment]
> please check HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion value CurrentBuild what do you have there?

The value of CurrentBuild is 7601

**Comment by DavidXanatos** [comment]
hmm see here: https://github.com/sandboxie-plus/Sandboxie/blob/ed5c5578e1f1285ce09dcfcb0ce557d0cc3a6cbf/SandboxiePlus/SandMan/Windows/SettingsWindow.cpp#L251

I'll change it to a mroe explicit comparison if (settings.value("CurrentBuild").toInt() >= 22000) // Windows 11
please test the latest 1.1.1

**Comment by isaak654** [comment]
Thank you, I can't reproduce it anymore with https://github.com/sandboxie-plus/Sandboxie/commit/adc9def12888cd9c7435c7e9e860f4b4eb091361

**Comment by modz2014** [comment]
would be nice if it does not show under show more options as well
