### ISSUE TITLE
[1.0.22] Option to move sandbox up or down is disabled in a certain sort mode

### ISSUE THREAD

**Issue by SiNONiMiTY** [sandboxie-plus/Sandboxie#1879]
### What happened?

Option to Move sandbox up or down is disabled
![image](https://user-images.githubusercontent.com/9588282/169694410-9f226efa-27db-45bd-b1d8-7a46575b2c0c.png)

### Download link

N/A

### To Reproduce

1. Select a sandbox
2. Right click on it
3. Select move box/group
4. Option to move up or down is disabled
5. Hot keys are also not working

### Expected behavior

Sandbox should be movable up or down

### What is your Windows edition and version?

Windows 10 Pro Education 21H2 x64 (19044.1706)

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.0.22

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
Click on the name column headder such that the arrow disapears than the move up down wil be enabled, when ther arrow is there its aways sorted alphabetically.

**Comment by isaak654** [comment]
I have to click on the name column a couple of times to activate the option, but I do not understand why this behaviour is intended.

**Comment by DavidXanatos** [comment]
On my system its always 1 click to switch between name sort or custom sort it is intended to be able to switch between those two sort modes.

**Comment by isaak654** [comment]
Ok, so the option to move sandbox up or down doesn't work for all sort modes.
It would be a bonus imho.

**Comment by DavidXanatos** [comment]
> Ok, so the option to move sandbox up or down doesn't work for all sort modes. It would be a nice bonus imho.

how? if you have a sorting enabled the order is alrady fixed you can not move it any ware without breaking the sorting

**Comment by isaak654** [comment]
Maybe you could consider a tooltip to show above the disabled "Move up" and "Move down" buttons or enable both options and show a warning instead when you click on them and the limitation is encountered.

Otherwise we could expect more issue reports like this over the years.

**Comment by DavidXanatos** [comment]
Qt does not render tooltips for menu items, so we eider so with an error message or switch to custom sort mode when one fo the order options is pressed?

**Comment by isaak654** [comment]
With these choices, I would vote for the latter.

**Comment by SiNONiMiTY** [comment]
I tried the sort option and it worked. We should just switch to the correct sort mode when the option is pressed. Do not disable it.

**Comment by isaak654** [comment]
I can't find the fix on the latest CI build (v1.1.1): https://github.com/sandboxie-plus/Sandboxie/commit/adc9def12888cd9c7435c7e9e860f4b4eb091361

Do you think it will be added to 1.2.x or a later version?

**Comment by DavidXanatos** [comment]
commited to 1.1.1 https://github.com/sandboxie-plus/Sandboxie/commit/76d72323cb5c3640a8a410052ede2340b4005775

**Comment by Germs2004** [comment]
a couple issues related to this:
If moving Up/Down is supposed to be disabled during certain sort modes, you should also turn off the drag-drop visual targets during those modes.  When I drag a Box up between two other boxes, I see a horizontal line that shows where my Box will be if I drop it there, but if sorting is supposed to be off, that horizontal line is misleading and should not exist.
Also, even when manual sorting is disabled (when sorted by Name column), the program still flashes the screen when I drag-drop Boxes, and says "Sandboxie config has been reloaded."  It probably should not do that.
