### ISSUE TITLE
Double clicking an executable inside a fake admin Sandbox prompts UAC

### ISSUE THREAD

**Issue by RationalFragile** [sandboxie-plus/Sandboxie#1881]
### What happened?

I have UAC set to always show. When creating a shortcut for an executable that is inside a fake admin Sandbox, it runs as expected without UAC prompt. But if I double click the executable (which is inside the sandbox) on an unsandboxed explorer it prompts UAC instead of running it in the fake admin sandbox like the shortcut does.

### Download link

Not relevant

### To Reproduce

1. Take some executable that always runs as admin upon starting it (e.g. installers)
2. Create a sandbox and disable admin and enable fake admin
3. Copy the executable inside the sandbox (e.g. "C:/Sandboxes/TestSandbox/C/Users/User/Desktop")
4. Make sure you have UAC set to all operations so you can see that it requests real admin access
5. Double click the executable and you'll get the UAC prompt
6. Close and instead create shortcut by right clicking the sandbox in the list and finding the executable
7. Double click the shortcut and you won't get a UAC prompt

### Expected behavior

Double clicking the executable behaves the same as double clicking the shortcut

### What is your Windows edition and version?

Windows 10 Pro 20H2 64bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus v1.0.22 64bit

### In which sandbox type you have this problem?

In a Hardened sandbox (red sandbox icon).

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
[TestSandbox]
Enabled=y
DropAdminRights=y
FakeAdminRights=y
...
```

**Comment by bastik-1001** [comment]
The shortcut, created from within the user interface, points to 'C:\Program Files\Sandboxie-Plus\Start.exe', while it passes the link of the executable to it, so it will be launched sandboxed.

> (...) if I double click the executable (which is inside the sandbox) on an **unsandboxed** explorer (...)

Then the system tries to launch the executable unsupervised by Sandboxie. To me, that seems like the expected outcome, but maybe there is still something not working as intended.

I wonder if it would be smart to have Sandboxie add each Sandbox folder to the 'ForceFolder function' in its INI section.

**Comment by bastik-1001** [comment]
You are right, Sandboxie "captures" executed programs from those folders. I had not tried to open "normal" applications with an unsandboxed explorer. 

Thank you for your report.

**Comment by DavidXanatos** [comment]
Yes the UAC prompt is triggeresd by the process that creates an otehr process, hence from an unsandboxed explorer we can not prevent an UAC from appearing unfortunately.
