### ISSUE TITLE
Template issue with the new Edge fix to include on v1.1.1

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1888]
https://github.com/sandboxie-plus/Sandboxie/blob/15d12d77dabc0e66cd49cd0601437157ebd83372/Sandboxie/install/Templates.ini#L638-L644

- [x] 1. Replace `Template_LastPass` with a more appropriate name (https://github.com/sandboxie-plus/Sandboxie/commit/6426c5b920775d68bd257a52d1ff3b8843fd1514)

- [ ] 2. `Tmpl.Title` should require a new string in [Sbie-English-1033.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/Sbie-English-1033.txt) in order to be localized in other languages

- [ ] 3. ~~Add a ScanFile path for the other Program Files folder of MS Edge. For this, I would suggest introducing both `%ProgramFiles%` and `%ProgramFiles(x86)%`~~ Aborted because the two combined ScanFile(s) are not working in Sandboxie

**Comment by DavidXanatos** [comment]
fixed

**Comment by DavidXanatos** [comment]
localisation still todo

**Comment by isaak654** [comment]
https://github.com/sandboxie-plus/Sandboxie/commit/306ad85f4e7148c2bdfc036aab6b4904b7e70a42 - feel free to test it before merging into master branch
