### ISSUE TITLE
[Portable Mode] "FileRootPath" in Sandboxie.ini get overriden every time after restart

### ISSUE THREAD

**Issue by ameaninglessname** [sandboxie-plus/Sandboxie#1889]
### What happened?

"FileRootPath" in Sandboxie.ini get overriden every time after restart

and i have another issue within portable mode:
### Download link

Not relevant

### To Reproduce

1. Install Sanboxie in potable mode
2. Start and it would popup a window asking you which path to choose for the "FileRootPath" --- C drive or a relative folder
3. Click yes (relative folder is chosen)
4. Manually change the "FileRootPath" of Sandboxie.ini
5. Restart the program
6. Notice that the "FileRootPath" is reverted

### Expected behavior

Custom "FileRootPath" is reserved

### What is your Windows edition and version?

Edition	Windows 11 Pro Version	21H2 Installed on	‎4/‎28/‎2022 OS build	22000.708 Experience	Windows Feature Experience Pack 1000.22000.708.0

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

windows defender

### What version of Sandboxie are you running?

1.0.22

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by RandomGOTI** [comment]
i can reproduce this issue

**Comment by DavidXanatos** [comment]
is this fixed by now? i remember there was something in one of the recent builds
