### ISSUE TITLE
Programs i try to start in sandboxie suddenly does not find Graphics card

### ISSUE THREAD

**Issue by Rexei** [sandboxie-plus/Sandboxie#1897]
### What happened?

I used sandboxie plus for some programs for over a year and now it suddenly does not work anymore.. i get told  GPU is missing/does not meet requirments.

### Download link

Steam / any game

### Expected behavior

the program should start

### What is your Windows edition and version?

windows 11 home 21h2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Sophos home

### What version of Sandboxie are you running?

Sandboxie-Plus v1.0.22

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by Rexei** [comment]
![bilde](https://user-images.githubusercontent.com/25548288/170996507-7595e4ad-ad64-4b73-92bf-4605886aef07.png)
![bilde](https://user-images.githubusercontent.com/25548288/170996755-7f4266ea-27f2-446c-a4ca-6c704c13f42c.png)

**Comment by DavidXanatos** [comment]
this will be presumably related to symlink isolation,
try adding FuncSkipHook=NtOpenSymbolicLinkObject to your sandboxie ini
if that works you will need to find out which symlink is causing the issue using the trace monitor
and add
ReadIpcPath=the_symlink_path_you_found
please note there may be more than one required symlink object

**Comment by Rexei** [comment]
> 

![bilde](https://user-images.githubusercontent.com/25548288/171040154-38c914de-d366-4bbe-9b26-42a1cd90afc8.png)
added it here and still getting the error

**Comment by isaak654** [comment]
It should not be added under `[UserSettings_XXXXXXXX]`, but under the sandbox in question.

**Comment by Rexei** [comment]
> It should not be added under `[UserSettings_XXXXXXXX]`, but under the sandbox in question.

I did try that too, should have mentioned that.. 

Get the same error when i put it there

**Comment by DavidXanatos** [comment]
Then please check older builds and tell us in which exact build the issue was introduced

Also you could try ReadIpcPath=$:*

**Comment by Rexei** [comment]
> Then please check older builds and tell us in which exact build the issue was introduced
> 
> Also you could try ReadIpcPath=$:*

tried that 2nd  and did not work 
I uninstalled past 2-3 weeks of windows updates and now it works.. so one of them broke it it seems. 

if needed i can reinstall them 1 by 1 until it breaks.

**Comment by DavidXanatos** [comment]
yes please try that,
if you have KB5014019 please try this one first

you may also try setting
EnableWin32kHooks=n
but this requirers the driver to be re loaded or a reboot

**Comment by Rexei** [comment]
> yes please try that, if you have KB5014019 please try this one first
> 
> you may also try setting EnableWin32kHooks=n but this requirers the driver to be re loaded or a reboot

Reinstalled all except KB5014019  and it still works so seems that broke it, am going to reinstall it and then try to disable the thing you mentioned.

**Comment by Rexei** [comment]
> yes please try that, if you have KB5014019 please try this one first
> 
> you may also try setting EnableWin32kHooks=n but this requirers the driver to be re loaded or a reboot

Update it works on KB5014019 if i set it =n. 
Both Epic games launcher and the game in steam launch now :)
