### ISSUE TITLE
Firefox - can't run in "Default" sandbox

### ISSUE THREAD

**Issue by kimski1** [sandboxie-plus/Sandboxie#1898]
### What happened?

If I try to run Firefox in my default sandbox (right click on file and choose "sandboxed")  I get "could not invoke program:......side-by-side confirguration is incorrect" error.

I have 2 sandboxes.  If works in 1 but not my default box.  

Uninstalled and reinstalled today so it's v100+.  I can run IE and Chrome just fine.

### Download link

na

### To Reproduce

right click on Firefox.exe and choose "run sandboxed"

### Expected behavior

Firefox to open in sandbox

### What is your Windows edition and version?

Windows 10

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows defender

### What version of Sandboxie are you running?

1.0.21

### List of affected browsers

Firefox only

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

no

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=WindowsRasMan
Template=OfficeClickToRun
Template=WindowsLive
Template=OfficeLicensing
ActivationPrompt=n
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n

[DefaultBox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
RecoverFolder=Z:\
BorderColor=#00FFFF,ttl
Enabled=y
CopyLimitKb=176138

[UserSettings_0C74020E]

SbieCtrl_UserName=kimge
SbieCtrl_NextUpdateCheck=1615844137
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=4,1,1022,726
SbieCtrl_ActiveView=40022
SbieCtrl_RecoverTarget=C:\Users\kimge\Desktop\Kim
SbieCtrl_RecoverTarget=Z:\data\Business ideas\Overages
SbieCtrl_RecoverTarget=Z:\data\important documents\Taxes
SbieCtrl_RecoverTarget=Z:\data\Kim\PMI & SAFe\PMP&CAPM
SbieCtrl_RecoverTarget=Z:\john_data
SbieCtrl_RecoverTarget=C:\Users\kimge\Desktop\Real Estate Business
SbieCtrl_RecoverTarget=Z:\data\important documents\medical\John
SbieCtrl_RecoverTarget=C:\Users\kimge\Desktop
SbieCtrl_RecoverTarget=Z:\data\important downloads
SbieCtrl_RecoverTarget=Z:\downloads
SbieCtrl_RecoverTarget=Z:\john_data\projects
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_HideMessage=2203,*GUIPROXY_00000001 - chrome.exe [C0000024]
SbieCtrl_BoxExpandedView=test
SbieCtrl_AutoStartAgent=SandMan.exe

[UserSettings_17A002FE]

SbieCtrl_UserName=parents
SbieCtrl_AutoStartAgent=SandMan.exe

[test]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
```

**Comment by DavidXanatos** [comment]
so it works in test but not in default, have you tried deleting the content of the default box?

**Comment by kimski1** [comment]
I thought about that but I worry about what I'll lose if it empty it.   Right now trying to compare the bookmarks file from inside and outside of the sandbox.   

I have yet to figure out the newer interface as the help guides are not helpful.

**Comment by DavidXanatos** [comment]
try deleting the sandboxed program files folder i would gguess thats what causing your issues

**Comment by kimski1** [comment]
but I expect that will delete the application.  I actually fixed my Chrome issue so I don't need to run Firefox in Sandbox anymore.
Thanks for the assist.
