### ISSUE TITLE
Windows 10 20H2?

### ISSUE THREAD

**Issue by silvestron** [sandboxie-plus/Sandboxie#190]
Does the latest stable release work in Windows 10 20H2? I was wondering if I could update Windows or I should wait.

**Comment by 01yakiek** [comment]
Yes, it works on Windows 10 20H2.
There's also no harm to downloading it to test it yourself.

So far I've only experience crashing for 0.4.3 when launching in Sandbox folder, but it works in 0.4.4 [re-release.

**Comment by silvestron** [comment]
Thank you. You mean Sandboxie crashes when launching programs installed inside the sandbox? I think I'll wait for the next stable release if that's the case.

**Comment by 01yakiek** [comment]
No, program crashes instead. I'm sorry for the confusion.

**Comment by silvestron** [comment]
Thank you, either way this would be an issue for me because I usually install programs in sandboxes.

**Comment by bjm234** [comment]
FWIW ~ my daily rider Edgium runs okay - W10 20H2 (19042.610) + Sandboxie v5.44.0 
Chrome n' Firefox also run okay.

**Comment by skygunner** [comment]
Works fine for me. 5.43.7

**Comment by DavidXanatos** [comment]
I don't think its 20h2 related but rather a generic compatibility issue with ttat app

**Comment by tuxtard** [comment]
After updating to 20H2 I am unable to install 0.4.5. Getting this error.

![image](https://user-images.githubusercontent.com/1107497/100517467-f3c5b380-318a-11eb-9db8-fdc1ef0f58d8.png)

**Comment by DavidXanatos** [comment]
please try one of the more recent builds thay fix issues with 2004 and later

**Comment by DavidXanatos** [comment]
I'll close that for now

**Comment by kumabp** [comment]
My system edition is windows10 20H2,when I run my edge with sandboxie,it show the problem like the picture,could you help me how it occurs?

<img width="504" alt="捕获" src="https://user-images.githubusercontent.com/82689217/115099048-130c8400-9f66-11eb-9261-1d37b37f2ebc.PNG">
