### ISSUE TITLE
0.7.4 to 1.0.22 makes textures disspear in takp everquest client

### ISSUE THREAD

**Issue by mixxit** [sandboxie-plus/Sandboxie#1902]
### What happened?

My 0.7.4 sandboxie stopped working with error

![image](https://user-images.githubusercontent.com/233287/171165670-3dd94436-7c26-401c-82e6-2aed9396fef1.png)

After updating my button textures for EverQuest TAKP Client no longer showed

![image](https://user-images.githubusercontent.com/233287/171165876-5cf05c47-3621-4ac0-b48d-ed015ec6b584.png)

They work fine on 0.7.4 (still running on my laptop fine) which I seem to no longer be able to install on my main PC - i guess due to some windows update?

![image](https://user-images.githubusercontent.com/233287/171165823-aaaf2d97-a966-48f9-8e55-06f530feea16.png)

### Download link

https://wiki.takp.info/index.php/Getting_Started_on_Windows

### To Reproduce

Run client in sandboxie

See no button textures in EULA or login screens

### Expected behavior

See button textgures

### What is your Windows edition and version?

Windows 10 Home 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.0.22

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by mixxit** [comment]
Solved by installing 0.9.8d

**Comment by DavidXanatos** [comment]
disable the folowing option to resolve the issue:
![grafik](https://user-images.githubusercontent.com/3890945/171473012-fbcbba40-31ea-4107-ac4b-ddde0ef9bf35.png)
