### ISSUE TITLE
Add BreakoutProcess and BreakoutFolder to the GUI

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#1904]
### Is your feature request related to a problem or use case?

It's related to defining a breakout process or folder.

### Describe the solution you'd like

Add #1500 to the GUI. It has been available since https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.8

### Describe alternatives you've considered

Just using manually `BreakoutFolder` or `BreakoutProcess`.

**Comment by DavidXanatos** [comment]
Sure, but where? I dont feal like this deservs an own tab in options, 
but putting forced and breakout things which are teh very oposit of each otehr into teh same list seams error prone.
Should I split the space in the forced tab in top force botom breakout lists?
or is oen list fine snough may be with some solor to emphesise the options?

**Comment by lwcorp** [comment]
I think `Resource Access=>Breakout`:
![image](https://user-images.githubusercontent.com/1773306/171256609-86399573-aa4a-41f9-a42e-820a33c5cdaa.png)

**Comment by DavidXanatos** [comment]
this feature will be added in one of the later builds 1.2. or 1.3

**Comment by lwcorp** [comment]
Thanks for adding it, Can you link to the relevant PR?
In which screen will it be? Is it like in my suggested screenshot above?

Also, you're so close to 250 patrons. Let's cross our fingers by the time v1.4.0 becomes stable, it'll already have this (now also UI) option unlocked!

![image](https://user-images.githubusercontent.com/1773306/193326074-11f138de-2bbe-4d91-a2ef-ef4660e1b236.png)

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/193329428-e2e3dcea-295f-402f-a4dd-12911ebeef19.png)
