### ISSUE TITLE
Can you make paid features produce errors for free versions?

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#1906]
### Is your feature request related to a problem or use case?

Trying to run, for example, #1500 doesn't produce any errors when used in the free version.

### Describe the solution you'd like

If one tries to use a paid feature in the free version, produce an error like "you just tried to run a paid feature (in this case you tried to break out program X from Sandbox Y. This is not possible, please consider unlocking it by buying."

**Comment by DavidXanatos** [comment]
when trying to use an exclusive feature message 6004 is already issued
