### ISSUE TITLE
Allow trial versions to paid features

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#1909]
### Is your feature request related to a problem or use case?

Paid features can't be tested without paying.

### Describe the solution you'd like

Add a small period time to test paid features. You can even ask for a credit card to avoid the same persons trying to cheat again and again. But only charge it after a while.

**Comment by lwcorp** [comment]
Please rename **All** to **Allow**.

**Comment by DavidXanatos** [comment]
Except breakout processes other features allow to start a process with them enabled but the driver will kill it after 5 minutes.
For obvious reasons this mechanics cant work for breakout hence there its just disabled fully.

I'm not going into the risks and requirements of processing CC payments, using paypal is for me the most convenient way.
So if i odd to add any form or more advanced trail that would be probably only email verification or something,
may be her you have 100 re captchas if you solve > 80% you get a free 1 week cert, a sort of proof of work that its worth to you to spend an hour if your life to get a free  certificate.

**Comment by lwcorp** [comment]
Alternatively, is there a way to also give Breakout 5 minutes, then kill the (unsandboxed) process?

**Comment by lwcorp** [comment]
So if the only un-triable feature is Breakout can you confirm the following scenario:
1. Add `BreakoutProcess=Zoom.exe` to the INI file
2. Enter a sandboxed browser
3. Click a Zoom meet link
4. Zoom will be opened unsandboxed

Correct?

**Comment by DavidXanatos** [comment]
yes it should, 
if you drop me an email i can send you a custom free trail certificate

**Comment by DavidXanatos** [comment]
I could add a trivial trail for breakout based on: you can break out 5 processes and then you need to restart the sbie svc, super inconvineint but for testing good wnough, and super trivial to implement

**Comment by lwcorp** [comment]
> if you drop me an email i can send you a custom free trail certificate
Thanks! What are the limitations there?

**Comment by DavidXanatos** [comment]
It expires after a month or two

**Comment by lwcorp** [comment]
From when you issued it or from when I fill it into the program?

**Comment by DavidXanatos** [comment]
from when i sent it to you
