### ISSUE TITLE
Compatibility Template for RTSS and MSI Afterburner ?

### ISSUE THREAD

**Issue by Coverlin** [sandboxie-plus/Sandboxie#191]
What i am trying to do is get MSI Afterburner and RTSS work with sandboxed processes without having to run them also sandboxed, is it achievable ?

Links to software in question
https://www.guru3d.com/files-details/msi-afterburner-beta-download.html
https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html

**Comment by wargelo** [comment]
RTSS:
Just add the following lines to your sandbox in your Sandboxie.ini:
```
OpenPipePath=\device\namedpipe\rtss_frametime
OpenIpcPath=\Sessions\1\BaseNamedObjects\RTSSSharedMemoryV2
```

**Comment by GY8VSdYYzvL8-K6T** [comment]
What about MSI Afterburner? When I try to run it sandboxed, I get errors about "CTaskScheduler Interface -4" and my MSI Afterburner profiles also don't apply. I don't use the low-level kernel driver, but that doesn't prevent me from overclocking my GPU outside of Sandboxie sandbox.
