### ISSUE TITLE
Conflict between MS Edge feature "Startup boost" and AutoDelete=y

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1913]
###  What happened? 

* Sandboxie 5.55.22 (potentially any SBIE release)
* Windows 10 or Windows 11
* MS Edge up-to-date

> In order to auto-delete the sandbox after closing Edge, I have had to uncheck both "startup boost" and "continue running background extensions and apps when Edge is closed" under Edge's settings (Security and performance).

Original reference: https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-22.445247/page-4#post-3085612

### Reason to find a fix:
This MS Edge feature named "Startup boost" tends to automatically reactivate itself after a number of Edge updates, so I think it should be fixed without the classic recommandation to disable it manually on the Edge side.

Post n. 1 by [tes](https://www.wilderssecurity.com/members/tes.165054/)

> Sandboxie 5.55.22
Windows 11 21H2
>
>In order to auto-delete the sandbox after closing Edge, I have had to uncheck both "startup boost" and "continue running background extensions and apps when Edge is closed" under Edge's settings (Security and performance).
>
> While this now delete's the sandbox after closing Edge, it slows down Edge when starting.
>
> Is there another way? (a setting within Sandboxie perhaps?)
>
> Thank you
>
> btw - long time Sandboxie user, wouldn't use the internet without it. Much appreciation to David Xanatos for picking up the project!

---

Post n. 2 by [stapp](https://www.wilderssecurity.com/members/stapp.42977/)

_Part 1_

> Using Plus v22 I have 2 boxes, Default and tester.
> I run Edge in tester when I need to.
> Default box runs Vivaldi.
> 
> When I close tester box in the last few days. the flames stay lit and the Sandman status says Edge is running. I have to right click on the Tester box in the taskbar box options to delete content.
> 
> Default box works ok.
> 
> I know I can delete the Plus .ini as I had to before, but thought I'd mention this corruption happening again.
> 
> https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-22.445247/page-2#post-3082800

_Part 2_

> Re- above.
> Now sorted by disabling (again) startup boost in Edge settings.
>
> https://www.wilderssecurity.com/threads/auto-delete-contents-of-sandbox-microsoft-edge.445499/

_Part 3_

>    I also had the same issue with Edge
>    https://www.wilderssecurity.com/threads/sandboxie-plus-1-0-22.445247/page-4#post-3085420
>
>    Edge had re-enabled 'startup boost' which I had disabled.
>    Once I disabled it again all was well.
>
>    Edge doesn't slow down for me when this is disabled.

---
   
Post n. 3 by [DjKilla](https://www.wilderssecurity.com/members/djkilla.167990/)

_Part 1_
> I've noticed a bug in Sandboxie Classic 5.55.22 (64-bit). I always do a clean install and always use the same settings. One of the settings I set is 'Automatically delete contents of sandbox.' I noticed that many times now when I close Sandboxie it doesn't automatically delete the contents of the sandbox so I have to manually delete the contents. Never had this issue with previous versions of Sandboxie Classic. The only programs I have sandboxed is Microsoft Edge, Firefox and Thunderbird. It may be related to stapp's post above. I'll test further and see if it's only Microsoft Edge or one of the other programs I have sandboxed. 

_Part 2_
> Well, did some testing and here's what I found. Using Sandboxie Classic 5.55.22 (64bit) with Microsoft Edge and other programs sanboxed, open any other program then Microsoft Edge. Now close Microsoft Edge and reopen Microsoft Edge again. Now close Microsoft Edge and the other program and the sandboxed contents don't get deleted. This is the ONLY way to get the bug where the sandboxed contents don't get deleted. No other combinations work. It ONLY happens when you open another sandboxed program, then open Microsoft Edge twice and close twice then close the other sandboxed program. Hope this helps and adds some usefulness for a fix!

**Comment by DavidXanatos** [comment]
this is fixed in 1.1.2 that build when re creating a ox sets a GPO which disables this edge behavioure
