### ISSUE TITLE
[1.0.22] OpenClipboard=n does not block clipboard if the program is "Forced Running"

### ISSUE THREAD

**Issue by SiNONiMiTY** [sandboxie-plus/Sandboxie#1919]
### What happened?

Title says, here are the scenarios that were tested.

❌ A program executed from ```ForceFolder``` can still access the clipboard.
❌ A program executed via ```ForceProcess``` can still access the clipboard.
✔ Manually running the program via context menu and selecting the sandbox with OpenClipboard=n set works properly, it cannot access the clipboard.

I will be using ```DefaultBox (Hardened)``` with ```OpenClipboard=n``` and ```ForceFolder=D:\Downloads``` for testing.

See the following images for the scenarios

[SCENARIO 1 - Forced Running]
1. Copy a random text.
![image](https://user-images.githubusercontent.com/9588282/171697205-d4b42a02-6981-4bf0-9474-af1f3deeee4c.png)

2. Directly execute the program on the forced location "D:\Downloads"
![image](https://user-images.githubusercontent.com/9588282/171697023-23d43973-34ce-4a57-97f6-efa5eaa6c8f1.png)
![image](https://user-images.githubusercontent.com/9588282/171697384-f03ea89c-c6e2-44c4-aa85-7d0f381c7846.png)

3. Verify if the status if Forced Running
![image](https://user-images.githubusercontent.com/9588282/171697613-0ce76000-6293-4212-9d07-5a911b1fe118.png)

4. Paste the copied text from step 1.
![image](https://user-images.githubusercontent.com/9588282/171697902-a805250d-f3a6-40d8-b075-0f627352c244.png)

[SCENARIO 2 - Running]
1. Copy a random text.
![image](https://user-images.githubusercontent.com/9588282/171697205-d4b42a02-6981-4bf0-9474-af1f3deeee4c.png)

2. Execute the program via the Sandboxie Context Menu
![image](https://user-images.githubusercontent.com/9588282/171698446-c381f84d-f5d6-45bc-be1a-5e23b908ccb9.png)
![image](https://user-images.githubusercontent.com/9588282/171698496-99f915d2-6bb2-4d21-841b-9db02e98c26e.png)

3. Verify if the status if Running
![image](https://user-images.githubusercontent.com/9588282/171698761-adc7ace9-e49b-46aa-8780-4699923f7fb7.png)

4. Paste the copied text from step 1.
![image](https://user-images.githubusercontent.com/9588282/171698881-b760344a-0d14-40d6-98ae-d47b5b8d0793.png)

### Download link

N/A

### Expected behavior

Clipboard access must be blockd

### What is your Windows edition and version?

Windows 10 Pro Education 21H2 x64 (19044.1706)

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Symantec Endpoint Protection 14.3

### What version of Sandboxie are you running?

1.0.22

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by SiNONiMiTY** [comment]
While working on this, I think it is good to include issue #1367

**Comment by RandomGOTI** [comment]
The option never worked for me , maybe it wasn't supposed to
Windows 7 Ultimate SP1 x64
Plus 1.1.0 x64
Also tested Plus 0.7.5 x64 when the feature was added

**Comment by DavidXanatos** [comment]
I have investigated this issue and it seams when a process is started on windows 10 using force process, the process gets associated with a job object of windows, this prevents sandboxie from using its own job object to restrict the program, you can use ForceRestartAll=y to workaround this issue.
I'll have to look into this can be fixed properly, we could add a usemode version of OpenClipboard=n which would not be as secure but would do the job in most cases

**Comment by DavidXanatos** [comment]
So here is my analysis of the issue, it seams that on modern windows 10 the PcaSvc service when attaching a job to a process does that asynchronously such that we fail to notice this during process creation and this results in our own sandboxing job when being attached, being so only in a limited way, what breaks the clipboard isolation. 
```ForceRestartAll=y``` is a good workaround, but what would be even better would be to properly detect and handle this event.
This issue may in fact be responsible for a few other force process related issues reported in the past.

**Comment by DavidXanatos** [comment]
I have fixed the PCA job detection it now re tests that after the process was started,
and I have added a user mode aspect to ```OpenClipboard=n``` up side is that it now also works for green boxes, although without any guarantees.
