### ISSUE TITLE
Option to sort Box Groups above Boxes

### ISSUE THREAD

**Issue by Germs2004** [sandboxie-plus/Sandboxie#1922]
### Is your feature request related to a problem or use case?

When I click the Name column to sort alphabetically, Sandboxie puts my Box Groups (and child Box Groups) amongst the Boxes.  Perhaps some would prefer an option to sort Box groups at the top of the list, then the Boxes below that.  That is how Windows Explorer sorts when you sort by Type.

Current behavior when sorted by Name:
```
Box Group 1
--Box A
--Box Z
Box Group 2
--Box A
--Box Group 2B
----Box inside Group 2B A
----Box inside Group 2B Z
--Box Z
```
Desired Behavior:
Current behavior:
```
Box Group 1
--Box A
--Box Z
Box Group 2
--Box Group 2B
----Box inside Group 2B A
----Box inside Group 2B Z
--Box A
--Box Z
```

### Describe the solution you'd like

Add an option (or just make it standard behavior) to sort Box Groups above Boxes.

### Describe alternatives you've considered

If I sort by "Status", it gets closer to what I want, except then the Box names are not always alphabetic because a Box status of "No INet" causes the Box to be sorted separately than "Empty" or "Normal".

**Comment by DavidXanatos** [comment]
will be added to the next build to be enabled in the plus ini in Options/SortGroupsFirst=true
