### ISSUE TITLE
Add Move Up, Move Down buttons to menu

### ISSUE THREAD

**Issue by Germs2004** [sandboxie-plus/Sandboxie#1923]
### Is your feature request related to a problem or use case?

Currently, to move a Box or Box Group up, you have to right click on it, choose Move Box/Group, then choose Move Up.  Or, type Alt+Up.

### Describe the solution you'd like

Add two buttons to the current button menu, next to the other button icons.  One with an up arrow, and one with a down arrow.  They simply move the selected Box or Box Group up/down within their parent group.  Remember to give them tooltips :)
This would be very intuitive for new users, and convenient for anyone who does manual sorting.

**Comment by DavidXanatos** [comment]
I don't think moving boxes is a common enough action to merit it being placed in the toolbar, you can use the keyboard shortcuts, or drag and drop (which will be fixed in the next build) that should be good enough
