### ISSUE TITLE
Change Path text into a clickable link

### ISSUE THREAD

**Issue by Germs2004** [sandboxie-plus/Sandboxie#1924]
### Is your feature request related to a problem or use case?

Currently, to open Windows Explorer to view a Box's files on the host, you have to right click on it, choose Box Content, then choose Explore Content.  Clicking or double-clicking on the text on the Path column doesn't do it.

### Describe the solution you'd like

Change the text in the "Path / Command Line" column to be a clickable link.  It should underline when mouse hovers over it, like links in a web browser.  That gives the user an intuitive and fast way to instantly open an Explorer window to that path.

### Describe alternatives you've considered

Add a tiny icon next to the path text that acts as a button that does the same thing.  So the "Path / Command Line" cell would look like:

`[icon] C:\Sandboxie\MyUser\MyBox`

**Comment by DavidXanatos** [comment]
I do not think that can be done in Qt the regular way, I would need to put a widget into the cell with a qlabel.
A simple solution would be to only enable double click in the column text without any change in how it renders.
anyone else interested in this feature?

**Comment by Germs2004** [comment]
Double clicking in that cell to open Explorer to that path would be good, though the lack of visual "clicky-ness" makes it a bit less intuitive.  thank you for considering it
