### ISSUE TITLE
Application written with Chromium Embedded Framework CEF seems to have performance issue/lag

### ISSUE THREAD

**Issue by skygunner** [sandboxie-plus/Sandboxie#193]
5.43.7
Windows 10 20H2

Application example:
WeChat for Windows. Can feel it is slower when running in Sandboxie, especially when typing in Chinese, the input IME will take a bit of time , about 0.5 to 1 second, to render and display its UI and candidates. But after the UI has displayed, it will not lag anymore. 
https://cefsharp.github.io/

Program wirtten in winform doesn't have this issue. 
Inputting english letter doesn't have this issue (because this mode does not require the IME to render and display a candidate UI). 

Maybe this is due to the resources/multi threading etc has been restricted ?

Hyper-V, Device Guard or secure boot are not in use, not enabled. But I have vmware workstation pro insatlled.

**Comment by henrikx** [comment]
Possibly related? https://github.com/sandboxie-plus/Sandboxie/issues/69

**Comment by skygunner** [comment]
I'm not sure if this is related to issue 69. 
Opening the file explorer is very slow in Windows 10 20H2 or 2004. This might be another issue. 
Why I say this is because program written in winform like QQ does not have this issue.

**Comment by grnassar** [comment]
> 
> 
> I'm not sure if this is related to issue 69. However it is performance related.
> 

Seeing as #109 seems related to #69, it's very possible this one could be too I'd think.
#109 says "Chromium based browsers" aren't having the issue, but I wonder if he tried on anything other than Edge (which indeed seems to not have it, or have it less severely).  Chrome on my machine causes the problem as well.

**Comment by DavidXanatos** [comment]
theperformance issues were fixed recently

**Comment by skygunner** [comment]
I can confirm the issue has been fixed. (WeChat, Sandboxie 5.49.7)
