### ISSUE TITLE
[Plus 1.1.1] SBIE2205 Service not implemented:  Win32Init.5 and BoxDisplayOrder issues

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#1934]
1. Tor browser sandbox
TOR 11.0.13 (based on Mozilla Firefox 91.9.0esr) (32-bit) 
Download : https://dist.torproject.org/torbrowser/11.0.13/torbrowser-install-11.0.13_en-US.exe
Worked fine with 1.1.0

-With AllowBoxedJobs=n
firefox.exe (6692): SBIE2205 Service not implemented:  Win32Init.5 (00000005)
SandboxieCrypto.exe (2136): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)
Tor Starts but 'Gah. Your tab just crashed.'

-Without AllowBoxedJobs=n
SandboxieRpcSs.exe (5376): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                       
SandboxieDcomLaunch.exe (3896): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                  
Start.exe (6668): SBIE2205 Service not implemented:  Win32Init.5 (0000000000000005)                                                                
SandboxieRpcSs.exe (5376): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 - SandboxieRpcSs.exe [FF000005]

Tor doesn't start

2 BoxDisplayOrder issues

All groups are added as !Groupname to the end of the value
BoxDisplayOrder=(.....),!group1,!group2

PID's are added to the end of the value
example : 
firefox.exe (6692): SBIE2205 Service not implemented:  Win32Init.5 (00000005)
Sandboxie config has been reloaded (6692 added to BoxDisplayOrder)
BoxDisplayOrder=(.....),!group1,!group2,6692

Windows 7 Ultimate SP1 x64
Plus 1.1.1 x64

**Comment by mysteriously** [comment]
Edge does not work with this version of SBIE and all tabs in Firefox crash immediately

**Comment by isaak654** [comment]
> Edge does not work with this version of SBIE

It looks like the issue(s) with Edge and the latest Sandboxie changes have already been extensively discussed and fixed with new experimental builds posted in [this](https://www.wilderssecurity.com/threads/sandboxie-plus-1-1-1.445560/) thread.

As reported by @DavidXanatos :

> yea there were two issues, one causing a blank edge page and another causing the welcome page to appear again and again.

**Comment by 0x4E69676874466F78** [comment]
After "starting" TorBrowser, the sandbox generally breaks (no other sandbox can be run) until a full restart Sandboxie.

**Comment by mysteriously** [comment]
> Now it is the turn of Firefox-based browsers, which may require further fixes.

I wish we could disable all those software compatibility fixes like when people are expecting to run games and complicated software in sandbox without degrading performance as well as with keeping old security policies working.

**Comment by RandomGOTI** [comment]
> you can try a test build: https://xanasoft.com/Downloads/Sandboxie-Plus-x64-v1.1.test.exe

Thank you for the test build , i can confirm that the first issue is fixed
For the 2nd the only issue now is with groups within another group

Just as an example : 
_group
-box_
group1
-Box
-group2
--(boxes)
-group3
--(boxes)
_group
-box_

value would look like `group(box),group1(Box,group2(...),group3(...)),group(box)`
Starting sandman 1.1.2(v1.1.test) the value is changed to `group(box),group1(Box,group2(...),group3(...)),group(box),group2(...),group3(...)`

That will make group2 and group3 to be placed at the end
_group
-box_
group1
-Box
_group
-box_
group2
-(boxes)
group3
-(boxes)

group1: "They grow up so fast"

**Comment by 0x4E69676874466F78** [comment]
@DavidXanatos 
> you can try a test build: https://xanasoft.com/Downloads/Sandboxie-Plus-x64-v1.1.test.exe

Thanks this solves the problem.

**Comment by isaak654** [comment]
@DavidXanatos

See also the second part of https://github.com/sandboxie-plus/Sandboxie/issues/1934#issuecomment-1151702092
Is it related to https://github.com/sandboxie-plus/Sandboxie/commit/2d0f626aab47578960a3d2bbce9c73bde0643c3c ?

**Comment by RandomGOTI** [comment]
All issues are fixed with 1.1.2 build , including the one with the test build 👍
