### ISSUE TITLE
Create a new sandbox when starting a program and close it after the program terminates.

### ISSUE THREAD

**Issue by ZacharyJia** [sandboxie-plus/Sandboxie#1936]
### Is your feature request related to a problem or use case?

No.

### Describe the solution you'd like

Provide a cmd options in Start.exe, which allows users start a program with a new sandbox, and another options for delete this box after the program terminates.

**Comment by DavidXanatos** [comment]
this sounds usefull on a first glance, but I am worried that by not being able to specify any customization such boxes would be quite useless.
This would need to before running the program first take the user through the box options window to set presets

**Comment by ZacharyJia** [comment]
> This would need to before running the program first take the user through the box options window to set presets, how would you imagine that to work

How about a box option template file for the new box? A default template is used if no template is specified. 

Another user-friendly options is that, users may allowed to specify an existing box as a template box, the newly created box will follow the template box's options. For users, they could setup the box at the GUI, and for developers, it's just a box duplication, which seems easier to implement.

**Comment by DavidXanatos** [comment]
Added to next build, well somewhat, the functionality is not in start.exe, but in sandman.exe so it is contingent on sandman running.
To make a box auto remove itself ```AutoDelete=y``` and ```AutoRemove=y``` must be set on that box and it needs to be created first,
all this can be done using SbieIni.exe with it you can create a new box, set whatever settings you want including the 2 required once, and all that sing the command line.

So the envisioned usecase is to create a *.cmd script which takes the command to be run as argument and configures the temporary sandbox.
