### ISSUE TITLE
Sandboxie-Plus 1.1.1 reloads the config quite often without it being called for

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#1938]
### What happened?

After I upgraded from 1.0.22 to 1.1.1 on Windows 7 64bit using the 64bit version, I noticed that the log contains repeated reloads of the config, while using programs in one or more sandboxes.

> 16:10:22.472   Sandboxie config has been reloaded                                                                                                  
> 16:10:43.787   Sandboxie config has been reloaded                                                                                                  
> 16:11:10.164   Sandboxie config has been reloaded                                                                                                  
> 16:11:15.188   Sandboxie config has been reloaded                                                                                                  
> 16:11:16.222   Sandboxie config has been reloaded                                                                                                  
>(...)
> 16:11:17.220   Sandboxie config has been reloaded                                                                                                  
> 16:11:18.271   Sandboxie config has been reloaded                                                                                                  
> 16:11:21.264   Sandboxie config has been reloaded                                                                                                  
> 16:11:46.686   Sandboxie config has been reloaded                                                                                                  
> 16:12:23.124   Sandboxie config has been reloaded                                                                                                  
> 16:14:21.771   Sandboxie config has been reloaded
                                                                                                               

                                                                         

### Download link

Not relevant

### To Reproduce

1) Launch some application under Sandboxies control (in my case forced folder)
2) Notice how the log gets a new entry with ' Sandboxie config has been reloaded ' whenever a process is launched. It may not happen with each launch, but when a box is not running a process and I launch one, I get this message logged. 

### Expected behavior

The config not being reloaded.

### What is your Windows edition and version?

Windows 7 64bit SP1

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.1.1 64bit

### Is it a regression?

The behavior did not show in 1.0.22 64bit

### List of affected browsers

It does not seem to affect any particular application

### In which sandbox type you have this problem?

In a Hardened sandbox (red sandbox icon).

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
Template=Edge_Win11Fix
Template=RBTray
Template=7zipShellEx
Template=Listary
Template=OfficeLicensing
Template=Microsoft_Security_Essentials
ForceDisableSeconds=69
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
EditPassword=[redacted]
TemplateReject=WindowsRasMan
NetworkEnableWFP=y
EnableObjectFiltering=y
EnableWin32kHooks=y
ClosedFilePath=\Device\VMnetUserif
```

**Comment by DavidXanatos** [comment]
this issue was reported and is already fixed for the 1.1.2 release which will be up soon
