### ISSUE TITLE
Can't run edge browser with sandboxie in windows 11

### ISSUE THREAD

**Issue by dnt1996** [sandboxie-plus/Sandboxie#1940]
### What happened?

https://user-images.githubusercontent.com/31310280/173167913-be846b44-4a69-4f70-b27a-f1aad2ed829a.mp4

### Download link

Use Windows 11's built-in edge browser

### Expected behavior

edge browser works fine in sandboxie

### What is your Windows edition and version?

Windows 11 Pro 21H2 22000.708

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus v1.0.22

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=D:\Sandbox\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=y
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing

[UserSettings_0C9E021B]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by dnt1996** [comment]
This issue came up after the release of Windows updates in recent weeks

**Comment by isaak654** [comment]
What happens if you uninstall KB5014019?

**Comment by dnt1996** [comment]
> What happens if you uninstall KB5014019?

After uninstalling it worked fine

**Comment by DavidXanatos** [comment]
try adding
PreferExternalManifest=msedge.exe,y

**Comment by dnt1996** [comment]
> try adding PreferExternalManifest=msedge.exe,y

This also works without uninstalling KB5014019, thanks

**Comment by isaak654** [comment]
> > try adding PreferExternalManifest=msedge.exe,y
> 
> This also works without uninstalling KB5014019, thanks

That setting is meant to be temporary, so it would be recommended to remove it in the next stable release because of the following template inclusion:
https://github.com/sandboxie-plus/Sandboxie/blob/bab9bc38b4c510892e454e549e49fb71eefff97b/Sandboxie/install/Templates.ini#L638-L646
