### ISSUE TITLE
"Template=Edge_Win11Fix" seems to be causing some problems in Windows 10

### ISSUE THREAD

**Issue by xvim64** [sandboxie-plus/Sandboxie#1941]
### What happened?

Windows 10 x64
Sandboxie-Classic-x64-v5.56.1

1. ForceProcess=msedge.exe + without "Template=Edge_Win11Fix"  -->  freezed blank window

https://user-images.githubusercontent.com/83569599/173171660-497d0bb3-2e7c-4cc3-9add-9ac36608040a.mp4

2. ForceProcess=msedge.exe + with "Template=Edge_Win11Fix"  --> works well

https://user-images.githubusercontent.com/83569599/173171662-369532f2-20a1-43d0-8afc-462390cac1cb.mp4

3. Specifying a box in a command  -->  ???
```
"c:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "c:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
```

https://user-images.githubusercontent.com/83569599/173171663-61e8f2b0-9800-423a-90e6-1906c19d4e88.mp4

ps. Sandboxie-Classic-x64-v5.56.0 works well without these problems.

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/download/1.1.1/Sandboxie-Classic-x64-v5.56.1.exe

### Expected behavior

normal startup of msedge

### What is your Windows edition and version?

windows 10 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

windows defender

### What version of Sandboxie are you running?

 Sandboxie-Classic-x64-v5.56.1

### Is it a regression?

 Sandboxie-Classic-x64-v5.56.1

### List of affected browsers

 Microsoft Edge (Chromium), Google Chrome

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]
Template=Edge_Win11Fix
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing

[DefaultBox]
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
Enabled=y

[UserSettings_0C360207]
SbieCtrl_UserName=xvim64
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1655525427
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_EditConfNotify=n
```

**Comment by isaak654** [comment]
This is a known issue with v1.1.1 / 5.56.1 that is currently discussed in [this](https://www.wilderssecurity.com/threads/sandboxie-plus-1-1-1.445560/page-5) thread.

You may want to test the latest builds posted there by @DavidXanatos and report the result here.

More feedback is needed.

**Comment by DavidXanatos** [comment]
Or in short that's the latest build: https://xanasoft.com/Downloads/Sandboxie-Plus-x64-v1.1.test2.exe and i put a lot of hope in that one

**Comment by xvim64** [comment]
> Or in short that's the latest build: https://xanasoft.com/Downloads/Sandboxie-Plus-x64-v1.1.test2.exe and i put a lot of hope in that one

![Page1](https://user-images.githubusercontent.com/83569599/173188736-b7cd19ea-0b0c-4852-9008-46926891654d.jpg)

![Page2](https://user-images.githubusercontent.com/83569599/173188738-8501a66a-0dc0-4ac8-9007-07d45292fd10.jpg)

![page3](https://user-images.githubusercontent.com/83569599/173188740-50f30713-e140-49f2-9340-cb13ee7dfdf8.jpg)
