### ISSUE TITLE
File recovery window keeps popping up with every disk write Tor browser makes

### ISSUE THREAD

**Issue by helpthemfix** [sandboxie-plus/Sandboxie#1944]
### What happened?

When I do any action in Tor browser the File recovery window keeps popping up very annoyingly. Can it be turned off? I don't know if it's a bug or a feature.

### Download link

https://www.torproject.org/download/

### To Reproduce

1. Open Tor browser
2. Do any action that results in a disk write
3. the File recovery window keeps popping up
4. close it
5. it pops up again and again

### Expected behavior

I should be able to launch the borwser with no popups 

### What is your Windows edition and version?

Windows 10 20H2

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Version 1.1

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by RandomGOTI** [comment]
uncheck 'Show recoverable files as notifications' in sandman global settings or delete 'AutoRecover=y' from the box
