### ISSUE TITLE
LINE Still not works on Windows 10 20H2

### ISSUE THREAD

**Issue by Wintiger0222** [sandboxie-plus/Sandboxie#195]
![Cap 2020-11-15 12-19-01-722](https://user-images.githubusercontent.com/24960466/99162176-1c3ac000-273e-11eb-802e-e3eb69a92fc7.png)
Experimental Release v0.4.4 / 5.44.0 on Windows 10 20H2, Line does not works
![Cap 2020-11-15 12-36-44-529](https://user-images.githubusercontent.com/24960466/99162286-58225500-273f-11eb-83d2-bd7838737056.png)
I couldn't test Release v0.4.3 / 5.43.7 on Windows 10 20H2, Line also does not works

![image](https://user-images.githubusercontent.com/24960466/99162319-cc5cf880-273f-11eb-970b-7e05d8d1f42e.png)

To write additional Infomation, I works well, when it does not log-in
But after login, before it print chat list, LINE does freeze

**Comment by games1tw** [comment]
+1

**Comment by Wintiger0222** [comment]
![Cap 2020-12-02 10-36-39-124](https://user-images.githubusercontent.com/24960466/100816956-93848980-348a-11eb-970a-6a8667cb25a5.png)
![Cap 2020-12-02 10-38-03-650](https://user-images.githubusercontent.com/24960466/100816972-97b0a700-348a-11eb-868e-dfb88309bbf9.png)
I don't know how to works, but now line works on windows 10 20h2
but, still it stucks after reboot.
If so, removing some line in ini file seems to be working.

By the way, why generated file path includes '?' character?

**Comment by test12313op** [comment]
> ![第2020-12-02 10-36-39-124章](https://user-images.githubusercontent.com/24960466/100816956-93848980-348a-11eb-970a-6a8667cb25a5.png)
> ![第2020-12-02章10-38-03-650](https://user-images.githubusercontent.com/24960466/100816972-97b0a700-348a-11eb-868e-dfb88309bbf9.png)
> 我不知道如何工作，但是現在該產品行可以在Windows 10 20h2上運行，但是
> 重啟後仍然卡住了。
> 如果是這樣，刪除ini文件中的某些行似乎是可行的。
> 
> 順便說一句，為什么生成的文件路徑包含“？” 字符？


Which version are you downloading?

**Comment by Wintiger0222** [comment]
> > ![第2020-12-02 10-36-39-124章](https://user-images.githubusercontent.com/24960466/100816956-93848980-348a-11eb-970a-6a8667cb25a5.png)
> > ![第2020-12-02章10-38-03-650](https://user-images.githubusercontent.com/24960466/100816972-97b0a700-348a-11eb-868e-dfb88309bbf9.png)
> > 我不知道如何工作，但是現在該產品行可以在Windows 10 20h2上運行，但是
> > 重啟後仍然卡住了。
> > 如果是這樣，刪除ini文件中的某些行似乎是可行的。
> > 順便說一句，為什么生成的文件路徑包含“？” 字符？
> 
> Which version are you downloading?

Now I'm using 0.5.0

**Comment by DavidXanatos** [comment]
please see https://github.com/sandboxie-plus/Sandboxie/issues/228 the issue will be solved in the next build
