### ISSUE TITLE
[Classic 5.56.2] Blank Screen at startup of Edge and Chrome

### ISSUE THREAD

**Issue by xvim64** [sandboxie-plus/Sandboxie#1954]
### What happened?

```
Sandboxie-Classic-x64-v5.56.2
Windows 10 64-bit

// sbie-chrome.cmd
@"c:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "C:\Program Files\Google\Chrome\Application\chrome.exe"

// sbie-edge.cmd
@"c:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "c:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"

// Sandboxie.ini
[GlobalSettings]

[UserSettings_0C360207]

SbieCtrl_NextUpdateCheck=-1
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_ShowWelcome=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=n
SbieCtrl_TerminateWarn=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_ShortcutNotify=n
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_ActiveView=40021
SbieCtrl_WindowCoords=509,52,1237,806
SbieCtrl_ProcessViewColumnWidths=250,70,300

[DefaultBox]

ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=FileCopy
Template=SkipHook
Template=BlockPorts
Template=LingerPrograms
BorderColor=#00FFFF,off
Enabled=y
BoxNameTitle=y
NotifyInternetAccessDenied=n

```

https://user-images.githubusercontent.com/83569599/173813526-59a69ff3-3764-44ef-888d-17fe3b5352aa.mp4

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.1.2/Sandboxie-Classic-x64-v5.56.2.exe

### To Reproduce

Run

```
// sbie-chrome.cmd
@"c:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "C:\Program Files\Google\Chrome\Application\chrome.exe"

// sbie-edge.cmd
@"c:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "c:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
```

with Sandboxie.ini

### Expected behavior

no blank screen at startup

### What is your Windows edition and version?

Windows 10 21H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.56.2

### Is it a regression?

 Sandboxie-Classic-x64-v5.56.1

### List of affected browsers

chrome 102.0.5005.115, Edge 102.0.1245.41

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

[UserSettings_0C360207]

SbieCtrl_NextUpdateCheck=-1
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_ShowWelcome=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=n
SbieCtrl_TerminateWarn=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_ShortcutNotify=n
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_ActiveView=40021
SbieCtrl_WindowCoords=509,52,1237,806
SbieCtrl_ProcessViewColumnWidths=250,70,300

[DefaultBox]

ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=FileCopy
Template=SkipHook
Template=BlockPorts
Template=LingerPrograms
BorderColor=#00FFFF,off
Enabled=y
BoxNameTitle=y
NotifyInternetAccessDenied=n
```

**Comment by DavidXanatos** [comment]
and just to confirm 5.56.1 was fine? and 5.56.0 as well?

**Comment by xvim64** [comment]
> and just to confirm 5.56.1 was fine? and 5.56.0 as well?

in VMware (Windows 10 64-bit) Sandboxie Classic 5.56.2 works well without any problem.

but not in VMware the blank windows appears.

// Sandboxie Classic v5.56.0  -->  Chrome[Ok], Edge[OK]
https://user-images.githubusercontent.com/83569599/173961265-f408de57-f63b-42fa-9bc5-c9b6fc3ef2f9.mp4

// Sandboxie Classic v5.56.1  -->  Chrome[Blank Window], Edge[Blank Window]
https://user-images.githubusercontent.com/83569599/173961270-ca5045bd-7507-4768-bf21-7db134aec433.mp4

// Sandboxie Classic v5.56.2  -->  Chrome[Blank Window], Edge[Blank Window]
https://user-images.githubusercontent.com/83569599/173961274-5a6d5c3f-9fe3-41d8-87e8-a888bd0b980b.mp4

// Sandboxie Classic v5.56.2 + Template=Edge_Win11Fix  -->  Chrome[Blank Window], Edge[OK]
https://user-images.githubusercontent.com/83569599/173961280-19679bf2-9ec1-49ae-8e9c-4b498310e7a8.mp4

**Comment by DavidXanatos** [comment]
please try "AllowBoxedJobs=n" in 5.56.2 and let us know if that made any difference
