### ISSUE TITLE
[Plus 1.3.3] classic net block with UseRuleSpecificity causing SBIE2112 messages in standard isolation box

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#1955]
### What happened?

When using `ClosedFilePath=!<InternetAccess>,InternetAccessDevices` 

SBIE2112 Object is not accessible: \Device\Afd\Endpoint, call CreateFile (C0000022) access=0016019F initialized=1
SBIE2112 Object is not accessible: \Device\Afd\Endpoint, call CreateFile (C0000022) access=00120089 initialized=1

Other than those two lines appearing in the message log for a few more times the program works if allowed/not blocked by wf

### Download link

.

### To Reproduce

add `ClosedFilePath=!<InternetAccess>,InternetAccessDevices` to box
start program that will try to connect to the net
┐(ﾟ～ﾟ)┌

### Expected behavior

no SBIE2112

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.1.2 x64

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
I cant reproduce this issue with 1.1.3, how does this behave for others?
does it only happen with mpc-hc64.exe or with others liek firefox as well?

**Comment by RandomGOTI** [comment]
Happens with any process that asks for internet access

**Comment by isaak654** [comment]
> add ClosedFilePath=!<InternetAccess>,InternetAccessDevices to box
> start program that will try to connect to the net
> ┐(ﾟ～ﾟ)┌

I tried to reproduce it with your same OS / MS Edge on Sandboxie Plus v1.2.5, but with no success.

**Comment by RandomGOTI** [comment]
> > add ClosedFilePath=!,InternetAccessDevices to box
> > start program that will try to connect to the net
> > ┐(ﾟ～ﾟ)┌
> 
> I tried to reproduce it with your same OS / MS Edge on Sandboxie Plus v1.2.5, but with no success.

Just found out that Tor 11.5 (based on Mozilla Firefox 91.11.0esr) (64-bit) is not working at all with the classic net block but works flawlessly with WFP
even if i add it as allowed , i still get asked to allow the process access when i use PromptForInternetAccess , after spamming yes to allow all the firefox and tor processes it will freeze if i try to connect having the tor process crash

```
ProcessGroup=<InternetAccess>,tor.exe.,firefox.exe
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
```
For some reason going back to the initial mpc-hc problem if i use allow list like i did upper for tor i am not getting the sbie message anymore , but if its just block all it will show them , that may point to the problem ? 

https://github.com/sandboxie-plus/Sandboxie/commit/94e9666539bf1ef6f17702b04ba24bcb215412b6 going back before this point i remember that after allowing the connection with the promt mpc would start to play right after , now it seems to give the failed to render the file and have to press play , starting the player via playlist with url
Starting the player normally without anything to load will show just as OP , no duplicate messages

**Comment by RandomGOTI** [comment]
fixed in 1.3

**Comment by bastik-1001** [comment]
I got SBIE2112 randomly today.

> SandboxieCrypto.exe (3604): SBIE2112 Objekt ist nicht zugänglich: \Device\Afd\Endpoint, Aufruf CreateFile (C0000022) access=0016019F initialized=1

I have no idea why SandboxieCrypto wants to access the internet.

**Comment by DavidXanatos** [comment]
Because it wants to check certificate revocation lists, its normal, and if it wants to do so or not depands on other software running in the box and what it its requesting the sandboxed crypto service to do

**Comment by bastik-1001** [comment]
I had not seen the SBIE2112 before and looked it up, where this issue came up. Now SandboxieCrypto.exe gets network access, due to me adding it to the list of allowed processes to access the network.

**Comment by RandomGOTI** [comment]
UseRuleSpecificity=y also is the cause of this issue , added UseRuleSpecificity=n to the test boxes and the message nowhere to be seen , may be fixed by the fix for 2124

**Comment by bastik-1001** [comment]
> UseRuleSpecificity=y also is the cause of this issue (...)

This is most likely true, since I applied that setting to a box, which then made SandboxieCrypto.exe ask for network access and producing this message.

**Comment by Simba98** [comment]
I have a similar issue on 1.3.2, but only when the UseRuleSpecificity=y or Privacy Enhanced Sandbox (which includes UseRuleSpecificity=y).
And the git version is 2.37.3.windows.1, and installed outside of the sandbox
Use a new and clean box and add the following options.
`PromptForInternetAccess=y`
`ClosedFilePath=<BlockNetDevices>,InternetAccessDevices` // Auto added by GUI option block by denying access to network services
`ClosedFilePath=!<InternetAccess>,InternetAccessDevices` // Auto added by GUI option block by denying access to network services
`UseRuleSpecificity=y`
`ProcessGroup=<InternetAccess>,C:\Program Files\Git\`

And clone from github.
git-remote-https.exe (9396): SBIE2112 Object is not accessible: \Device\Afd\Endpoint, call CreateFile (C0000022) access=00120089 initialized=1

**Comment by Simba98** [comment]
Is it only try to match the exe name `git-remote-https.exe`?
`ProcessGroup=<InternetAccess>,*https*` // Works
`ProcessGroup=<InternetAccess>,*core*` // Won't work, which try to match _C:\Program Files\Git\mingw64\libexec\git-_**core**_\git-remote-https.exe_

**Comment by RandomGOTI** [comment]
Another confirmation UseRuleSpecificity is causing the message with classic block

@Simba98 yes , blocking is done with name not paths

**Comment by RandomGOTI** [comment]
🍝  workarounds available
