### ISSUE TITLE
[Plus 1.3] Option to enable/disable the use of SbieCtrl_HideMessage for sandman

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#1956]
### Is your feature request related to a problem or use case?

classic has the option to hide messages that are just annoying for the user and have no impact on sandbox functionality

### Describe the solution you'd like

title

**Comment by RandomGOTI** [comment]
@DavidXanatos  Oh yea , i was vague with it but was referring to the message log of the main window (advanced view)
I had the `Show Notifications for relevant log Messages` off since i prefer to look at the main window instead

Example #1955 if blocked already it will show in sbie messages regardless and could miss an error that needs attention or force to cleanup log
The toggle could be a button like keep terminated and trace logging

**Comment by DavidXanatos** [comment]
ah I see you want to hide these messages also from the log hmm.....
