### ISSUE TITLE
Windows updates break Sandboxie/Sandboxie+

### ISSUE THREAD

**Issue by guidonero** [sandboxie-plus/Sandboxie#1959]
### What happened?

Windows 10 update KB5013942 (May 2022) and KB5014699 (June 2022) prevent Sandboxie/Sandboxie+ from starting.  
Result is error message SBIE2314 "canceling process start.exe"
Google search for Sandboxie issue related to KB5013942 is documented on the web.  Subsequent update KB5014699 also causes the same problem.
The only solution I've found is to uninstall KB5013942 and KB5014699, then run MS program "wushowhide.diagcab" to prevent them from being  automatically reinstalled.  Prior to these 2 updates, and after they're uninstalled, Sandboxie executes normally.
* Is the Sandboxie development team addressing this issue, or is there a SBIE setting to solve it?

### Download link

not relevant

### To Reproduce

1. Install Windows 10 KB5013942 (this is when the issue first appears.)
2. Right-clik context menu on web browser. Select "run sandboxed."
3. Select default sandbox (or any other).
4. Sandboxie error box pops up showing SBIE2314 "canceling process start.exe"
5. Click "copy to clipboard button" and message box disappears. 
6. Sandboxed browser never happens.
7. Situation is the same when a sandbox is started directly from Sandboxie Start Menu icon.

### Expected behavior

When KB5013942 is not installed: Right-clik on Firefox; select Run sandboxed; select Default box; Firefox immediately opens in yellow-bordered window.

### What is your Windows edition and version?

Windows 10 Home, 21H2, build 19044.1645

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Avast Antivirus free ver. (note I initially tried uninstalling this before discovering that KB5013942 was the problem)

### What version of Sandboxie are you running?

5.48.5

### List of affected browsers

All

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=BitDefenderInternetSecurity
Template=WindowsRasMan
Template=Avast_Antivirus
Template=SiteAdvisor
Template=7zipShellEx
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
ForceDisableSeconds=20

[DefaultBox]

ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=C:\Videos\Colbert (mostly)
RecoverFolder=%Personal%\Downloads
RecoverFolder=C:\dwhelper
BorderColor=#00FFFF
Enabled=y
NeverDelete=n
BoxNameTitle=y
CopyLimitKb=1164290
AutoDelete=y

[UserSettings_11620276]

SbieCtrl_UserName=kenned
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1572560078
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=y
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_AutoApplySettings=n
SbieCtrl_WindowCoords=487,167,1237,632
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_HideWindowNotify=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_RecoverTarget=C:\Users\Kenned\Documents\_Kenned
SbieCtrl_SaveRecoverTargets=y

[UserSettings_1078025C]

SbieCtrl_UserName=debbie
SbieCtrl_ShowWelcome=n
SbieCtrl_NextUpdateCheck=1655474296
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_WindowCoords=822,483,819,527
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_ExplorerWarn=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_RecoverTarget=C:\Users\Debbie\Documents\Documents\Tom\Saline Celtic 2018 flyer\FINAL ARTWORK\2-up flyers
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_BoxExpandedView=DaVinci_Resolve,Photostudio,PST_Viewer,Trial_Programs

[Photostudio]

Enabled=y
ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=C:\dwhelper
RecoverFolder=%Personal%\Downloads
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
NeverDelete=n
CopyLimitKb=1164290

[Trial_Programs]

Enabled=y
ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=C:\dwhelper
RecoverFolder=%Personal%\Downloads
RecoverFolder=%Personal%
BorderColor=#00FFFF,ttl
NeverDelete=n
CopyLimitKb=1164290

[PST_Viewer]

Enabled=y
ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
NeverDelete=n
CopyLimitKb=1164290

[DaVinci_Resolve]

Enabled=y
ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%Personal%\Downloads
RecoverFolder=C:\dwhelper
BorderColor=#00FFFF,ttl
NeverDelete=n
CopyLimitKb=1164290
```

**Comment by DavidXanatos** [comment]
With KB5014699
and sbie 1.1.2 i cant reproduce this issue on my test VM with windows 10 it runs fine
