### ISSUE TITLE
Program stops due to internet restriction placed on folder it is nested in 

### ISSUE THREAD

**Issue by NyarlathotepZERO** [sandboxie-plus/Sandboxie#196]
**_Issue:_** Program stops due to internet restriction imposed on a sandbox rule which covers a folder that the program folder is nested in, even though the program it self has a rule which covers its own folder.

**_Steps to reproduce:_**
**1.** create a folder within a folder naming them as follows (eg: folder1/folder2.

**2.** create a new sandbox including a rule for folder2 to 'force folder' any file run within folder2, to open in a sandbox called 'folder2'.

**3.** create a new sandbox including a rule for folder1 to 'force folder' any file run within folder1 (and its nested folders) to open in a sandbox called 'folder1'.

**4.** impose the 'block all internet access' rule in sandboxie  for any files run within the 'folder1' sandbox.

_**Result:**_ a program that requires internet access is run in 'folder2' and it gets blocked by the 'folder1' rule, even though the folder2 rule does _not_ block internet access.

This behavior seems inconsistent with the way that sandboxie will treat the program itself. The program that is run in 'folder2' will recognize that whilst both the 'folder1' and 'folder 2' rules cover it, the rule that it applies is actually the folder2 rule.  (even though it decides to apply the internet restriction part of the 'folder1' rule)

_**Expected result:**_ if sandboxie recognizes that the folder2 rule is the rule to apply to the program being run, it should also follow every other part of that rule (including default network restrictions etc)

**Comment by Coverlin** [comment]
The settings have priority as they appear in the config (ini file)
Not a bug only a conflicting path choice , forcedfolders works with subfolders aswell so it makes sense
```
[folder2]
ForceFolder=PATH\Folder1\Folder2
[folder1]
ForceFolder=PATH\Folder1
ClosedFilePath=InternetAccessDevices
```
The above will cause no problems , ForceFolder from folder2 box has prio
```
[folder1]
ForceFolder=PATH\Folder1
ClosedFilePath=InternetAccessDevices
[folder2]
ForceFolder=PATH\Folder1\Folder2
```
This wil have everything run under folder1 sandbox

internet restriction settings apply to their respective boxes only so the described result is not accurate also the steps to reproduce are reversed... create folder1 box first to run into the ''issue''
You should try adding `BoxNameTitle=y` to your boxes cause most certainly you are not running folder2 content under folder2 box

**Comment by NyarlathotepZERO** [comment]
> The settings have priority as they appear in the config (ini file)
> Not a bug only a conflicting path choice , forcedfolders works with subfolders aswell so it makes sense
> 
> ```
> [folder2]
> ForceFolder=PATH\Folder1\Folder2
> [folder1]
> ForceFolder=PATH\Folder1
> ClosedFilePath=InternetAccessDevices
> ```
> 
> The above will cause no problems , ForceFolder from folder2 box has prio
> 
> ```
> [folder1]
> ForceFolder=PATH\Folder1
> ClosedFilePath=InternetAccessDevices
> [folder2]
> ForceFolder=PATH\Folder1\Folder2
> ```
> 
> This wil have everything run under folder1 sandbox
> 
> internet restriction settings apply to their respective boxes only so the described result is not accurate also the steps to reproduce are reversed... create folder1 box first to run into the ''issue''
> You should try adding `BoxNameTitle=y` to your boxes cause most certainly you are not running folder2 content under folder2 box

Editing the ini and moving the subfolder rule _above_ the rule for the folder it was nested in worked perfectly, thanks !
