### ISSUE TITLE
GPU no longer recognized after recent Windows 11 updates when Win32k hooks are enabled

### ISSUE THREAD

**Issue by AlexLohrer** [sandboxie-plus/Sandboxie#1965]
### What happened?

After I installed the recent Win11 updates (KB5014697+KB5013889), my GPU is no longer recognized by any sandboxed program, and so many programs fail to start or are unusable.

I saw that a similar issue was reported some days ago (#1897), and that Win32k hooks will be enabled just for Edge and Chromium apps in the upcoming release 1.1.1. However, I'd like to report this, as also the Edge browser is not working anymore with enabled Win32k hooks (the process starts but shows just a blank screen).

Btw, the update KB5014697 contains parts of the update KB5014019, which was identified as the troublemaker in the referenced issue.

### Download link

https://support.microsoft.com/en-us/topic/june-14-2022-kb5014697-os-build-22000-739-cd3aaa0b-a8da-44a0-a778-dfb6f1d9ea11

### Expected behavior

GPU is detected by sandboxed programs with Win32k hooks enabled, at least apps like the Edge browser can detect it

### What is your Windows edition and version?

Windows 11 Pro 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.22 64-bit

### List of affected browsers

Microsoft Edge 102.0.1245.44 64-bit

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
Do you have the extre edge compatybility templae enabled?

**Comment by AlexLohrer** [comment]
No. This template isn't even available for me (compatibility checks aren't disabled).

**Comment by DavidXanatos** [comment]
then update to 1.1.2 build

**Comment by DavidXanatos** [comment]
build 1.1.3 is out it should fix that issue
