### ISSUE TITLE
Enhancements on Sandboxie.ini

### ISSUE THREAD

**Issue by HikariWS** [sandboxie-plus/Sandboxie#197]
A couple things that always annoyed me on Sandboxie.ini and it seems nobody talked about it yet here.

First, it shouldn't be on %WINDIR%. It should be on %PROGRAMDATA%\Sandboxie\. With possibility of each user has their own %LOCALAPPDATA%\Sandboxie\

Second, change its encoding to UTF8. Notepadd++ doesn't show what encoding it is but is able to read and write it, but WinMerge has never understood its encoding. I have mine on a Subversion project with other stuff so I keep track of changes I do, and WinMerge is unable to understand it to show changes. I always have to copy my working copy and head versions somewhere else, use Notepad++ to change them to UTF8, then manually set WinMerge to compare them, to then apply the changes on working copy and be able to commit.

1st should be easy to apply. 2nd I guess is tricky if Sandboxie is unable to understand UTF8. It'd require a lot of rework.

**Comment by Coverlin** [comment]
Easier to set user acc's to boxes.. or settingup portable sbie for each user rather than to make that change
sbie only supports windir and it's own folder where the program resides for the config , in that order
each user already have their own usersettings section

The config is `Unicode (01200 - Unicode)`
To solve your user sided issue with WinMerge:
Go to File -> FIle Enconding and change to the correct encoding with the chackmark to use the same codepage for both
Hotkey: Alt+f+f
WinMerge 2.16.8 x64

**Comment by DavidXanatos** [comment]
>
> First, it shouldn't be on %WINDIR%. It should be on %PROGRAMDATA%\Sandboxie. With possibility of each user has their own %LOCALAPPDATA%\Sandboxie\

this is problematic as we need to load config through the driver so no user specific location is Easily accessible.

I'll leave the ini for now where it is, but the next build will be able to load an UTF8 encoded Sandboxie.ini and Templates.ini

**Comment by HikariWS** [comment]
I didn't know the driver loads the config. So yeah, no chance for per-user config. But can't it be placed on %PROGRAMDATA%?

Being able to load UTF8 alrdy helps a lot! After I upgrade I'm gonna test it. I'm also look WinMerge for the setting.

**Comment by ImSpecial** [comment]
ProgramData is easily accessible and doesn't require elevated privileges to access, a bad place for something like this.

**Comment by HikariWS** [comment]
I get it, so some trojan might edit the ini to make another trojan out of sandbox after next startup? I verified on my setup and there are files from Comodo there.

But I understand it, I just don't like having non-Windows files on %WINDIR%. If a program data file needs privileged access, maybe it could go to its program files folder.

**Comment by DavidXanatos** [comment]
> 
> But I understand it, I just don't like having non-Windows files on %WINDIR%. If a program data file needs privileged access, maybe it could go to its program files folder.

That you can do already now, place a sandboxie.ini in the folder containing the driver and reload the driver and it shell switch to using that location.

**Comment by HikariWS** [comment]
I didn't know about that. Is it on C:\Program Files\Sandboxie\32?

**Comment by DavidXanatos** [comment]
no just "C:\Program Files\Sandboxie\"
there where you have your SbieDrv.sys
