### ISSUE TITLE
Shell integration to context menu in portable mode

### ISSUE THREAD

**Issue by fygiwy** [sandboxie-plus/Sandboxie#1978]
### What happened?

I have been using older version of sandboxie-plus (v0.9.8d) for a while and everything works great. However when I update to the latest version(v1.1.3), I've noticed the shell integration to add "Run sandboxed" in explorer context menu doesn't work. It goes back to unticked when I press the apply button.
Before applying settings:
![Before apply](https://user-images.githubusercontent.com/107297370/174774207-874d6daf-c803-4179-9257-37382705e50f.png)
After pressing apply:
![Screenshot 2022-06-21 180753](https://user-images.githubusercontent.com/107297370/174774862-4543b34e-7e48-4329-a6a3-6b40449b104f.png)

This maybe because of how the later versions change the host machine registry to add to context menu which may require setup installation. This is not required in older version(if it is a requirement) like the one I mentioned above. I am looking forward for a fix or if there is any temporary workaround like editing registry manually, I would want to know how. Sorry for me bad Englesh.

 I run both versions in portable mode.

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.1.3/Sandboxie-Plus-x64-v1.1.3.exe

### Expected behavior

Shell integration should work even in portable mode

### What is your Windows edition and version?

Windows 10 Pro (19044.1415) / Windows 11 Pro (22000.588) dual boot

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

N/A

### What version of Sandboxie are you running?

Sandboxie-Plus v1.1.3

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by pozm** [comment]
This also happens when using the installer.

**Comment by DavidXanatos** [comment]
try this release: https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.2.9

**Comment by pozm** [comment]
That seemed to have worked for me.
