### ISSUE TITLE
Help! Problem installing / upgrading (KmdUtil, 193)

### ISSUE THREAD

**Issue by ATKlei** [sandboxie-plus/Sandboxie#1979]
### What happened?

Please help.
I upgradet 5 Win PC from Sandboxie to plus with no Problem, but my most used one refuses to install.
I get a error Message: KmdUtil, ControlService Start %1 ist keine zulässige Win32-Anwendung (193).
I already uninstalled and reinstalled, used CCleaner, deleted every Registry entry which was left over,
deletet any folder which was left over, but still the same Problem
Win 10, 64bit, used the 64bit installer

Any idea what i can do?
Thank you for your help
Alex
![Unbenannt1](https://user-images.githubusercontent.com/107921035/174787302-fdb30030-7014-49eb-b2a1-f38fce490da6.PNG)

### Download link

not available

### Expected behavior

Installing

### What is your Windows edition and version?

Win10pro 21H2

### In which Windows account you have this problem?

I use the built-in Administrator with Admin Approval Mode turned on.

### Please mention any installed security software

Avira

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.0.20

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by Forkas** [comment]
Win 10 x64 21H2
I confirm, an error also pops up when installing the program, the service does not start after installation.

In the Windows log
Failure to start the "Sandboxie Service" due to an error
Sandboxie Service is not a Win32 application.

**Comment by DaReaLDeviL** [comment]
![sandboxie](https://user-images.githubusercontent.com/31885936/178141715-0df90c16-b1ee-4900-af81-68b06da1ed6e.png)

Same problem here too. Can't add any box. "Driver cant connect" also when I start the application after the installation.

**Comment by Forkas** [comment]
Still no solution to the problem?

**Comment by isaak654** [comment]
I couldn't reproduce it, can you provide a set of steps to reproduce it reliably?

**Comment by DavidXanatos** [comment]
is the issue stil present after we updated the inosetup version?

**Comment by ATKlei** [comment]
You made my day! Now it is running as hell!
👍
I just bought one of your certificates.
Thank you for your work
Alexander
Am 25. Mai 2023, 21:59 +0200 schrieb DavidXanatos ***@***.***>:
