### ISSUE TITLE
ShellNew context menu show up empty with UseRegDeleteV2 enabled

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#1982]
### What happened?

After enabling UseRegDeleteV2 'Right click > New' context menu show up empty on sandboxed explorer.

https://user-images.githubusercontent.com/6871698/175113526-a0ca1053-d257-4304-84ed-bf3607e9bec3.mp4

### Download link

Not relevant

### Expected behavior

'Right click > New > Folder' entry

### What is your Windows edition and version?

Windows 10 Pro 21H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus v1.1.3

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by droped** [comment]
I don't think that's where you are supposed to add the setting

**Comment by offhub** [comment]
Fixed: https://github.com/sandboxie-plus/Sandboxie/issues/2756
