### ISSUE TITLE
GPU Error

### ISSUE THREAD

**Issue by bob81** [sandboxie-plus/Sandboxie#1983]
### What happened?

Recently after a windows 11 update i get a error GPU Error Detected. I was running Sandboxie Classic v5.55.22 Then i removed it and downloaded Sandboxie Plus v1.0.22 And still get the same 
![Screenshot 2022-06-23 073239](https://user-images.githubusercontent.com/4357950/175231366-6fdc2a4d-e253-4e40-9d47-ad6cc5b69a59.png)

New updates for windows 
Windows 11 for x64 (KB5013889), Windows 11 for x64-based Systems (KB5014697), Windows 11 for x64-based Systems (KB4023057)

### Download link

not relevant

### Expected behavior

When running games on steam 

### What is your Windows edition and version?

Windows 11

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Norton 360

### What version of Sandboxie are you running?

1.0.22

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by DavidXanatos** [comment]
please try the build 1.1.3

**Comment by bob81** [comment]
Hi thanks but  where do get it from as i only see v1.0.22 and v5.55.22 on the website

**Comment by DavidXanatos** [comment]
here: https://github.com/sandboxie-plus/Sandboxie/releases
it will be made available in the website in a week or so after we are sure there are no relevant issues

**Comment by bob81** [comment]
Thanks For your help problem fixed
