### ISSUE TITLE
Is there a maximum number of sandboxes in BoxDisplayOrder?

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#1988]
Original post by mayokey:
> When I create a new sandbox, BoxDisplayOrder= becomes duplicated, see pic, and the whole order set in "Sandbox > Set Layout and Groups" falls apart. The same happens when I try to rearrange the sandboxes and their groups. I've been observing it in recent months, so it's not tied to a specific version. If I rearrange the sandboxes/groups by manually editing sandboxie.ini, it works, but it's super uncomfortable. As I currently have 103 sandboxes, I wonder if there's perhaps a maximum number of entries that BoxDisplayOrder= can take and therefore it gets duplicated, which then no longer works for maintaining the order. Any ideas?
Win 7 Pro
Intel i7, 16 GB RAM
Sandboxie 5.55.18 
>
> Original reference (with pics): https://www.wilderssecurity.com/threads/is-there-max-number-of-sandboxes.445755/
	

Replied by @DavidXanatos:
>Well there is no explicit limit,
but there are
>
https://github.com/sandboxie-plus/Sandboxie/blob/29356a4e44271d4feb0bbbc56c70e6731124364e/Sandboxie/core/drv/conf.c#L43-L44
>
>some limitations.
You can not have more then 100 000 lines in your sandboxie.ini so amusing a minimum of 3 likes per sandbox you can have 33 thousand sandboxes.
And a config line can not be longer than 2000 charakters. I think this is the limitations you are actually running into.
>
>Unfortunately the plus ui does use sandboxie ini for this data, but i wil change this in an upcomming build to use the plus ini which has no such limitation

**Comment by RandomGOTI** [comment]
If the limitation cannot be increased `CONF_LINE_LEN` :  
Can we place plus ini with sbie ini in win dir ?
Can the change in plus be optional for those that do not run into this problem ? _yet_
What about classic build like the one reporting the issue ?



offtopic: (wihtout pinging) please reopen issue 1951 and 1955

**Comment by DavidXanatos** [comment]
These settings will be moved into the plus ini in the next build, such that it loads the old setting if no new is present but from there on uses the plus ini only.
There will be no fix to the classic build.

**Comment by DavidXanatos** [comment]
As these settings are nor in the plus ini i'll close this
