### ISSUE TITLE
I need some help here with SBiePlus.

### ISSUE THREAD

**Issue by Aparishin** [sandboxie-plus/Sandboxie#199]
Basically this is my problem:
https://youtu.be/f8XM-OTn-ZQ
Also "Data check" on launcher takes ridiculous amount of time, from 10 to 20 mins, while normally started (out of sandbox) launcher checks everything in 10-20 seconds. In past 3 weeks I could start it only once, but after getting dc due some annoying bug it happens again (sbie error spam).
Any suggestions?
At least can you tell me what's wrong and why did this keep happening again and again?

**Comment by isaak654** [comment]
Here you can find a generic explanation about the sbie2203 and sbie2205 errors:
https://xanasoft.com/sandboxie/sbie2203/
https://xanasoft.com/sandboxie/sbie2205/

Closers is a free to play game, so it should be easy to reproduce for the dev.

**Comment by Aparishin** [comment]
> Here you can find a generic explanation about the sbie2203 and sbie2205 errors:
> https://xanasoft.com/sandboxie/sbie2203/
> https://xanasoft.com/sandboxie/sbie2205/

And how this suppose to help me?
Is there any line that says "do this to preventing 2203 spam and crushing program"?
I've tried add lines to ini file like OpenProtectedStorage=y and OpenCredentials=y, changed nothing.

**Comment by NewKidOnTheBlock** [comment]
What is Closers? Some kind of game?
Could you post a download link?

**Comment by Aparishin** [comment]
@NewKidOnTheBlock yes it is game, basically mmorpg made by Naddic.
I've tried different versions of SandBoxie, from 5.33.6 (non-SBPlus) till latest SBPlus version with the same result.
5.33.6 working fine for my Guildmate, but not for me, SBPlus were kinda work, but this happens so rarely, almost like planet parade.
To be honest, until Dec 28 2020 all versions were working perfectly fine, under EnMasse, but after Dec 28 send all account data etc. to Naddic, and they changed login system from launcher to web login. And this absurd begins...
And I can download "Installer" file via sandboxed firefox or chrome and can install the game, but can't launch it properly (also it takes around 20 hours to download the game, update it and for "File Checking" via sandbox, plus every time I'm trying to launch the game it takes around 20 mins just for "File Check").

**Comment by NewKidOnTheBlock** [comment]
What a shitshow of a game.
Solution:
Download launcher.

Then:
1. Start your browser in Sandboxie.
2. Install Launcher in Sandboxie.
3. Go to their website and launch game from browser in Sandboxie.
