### ISSUE TITLE
All browsers do not work in the sandboxie (SbieDll.dll failed)

### ISSUE THREAD

**Issue by harnseen** [sandboxie-plus/Sandboxie#1994]
### What happened?

I have tried different browsers (chrome, firefox and brave) and none of them work in sandboxie plus 1.1.3. But some other software can run normally.
error: **Installation of the dynamic link library "D:\Sandboxie-Plus\SbieDll.dll failed. The process is terminating abnormally**
[Trace log](https://github.com/sandboxie-plus/Sandboxie/files/8992589/c.log)

### Download link

Not relevant

### Expected behavior

work normally

### What is your Windows edition and version?

Windows 11 Enterprise 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

windows defender

### What version of Sandboxie are you running?

sandboxie plus 1.1.3

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Trace log

https://github.com/sandboxie-plus/Sandboxie/files/8992589/c.log

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=D:\Sandbox\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
TemplateReject=Edge_Win11Fix

[UserSettings_0C6C021D]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
SbieCtrl_HideMessage=2205, ConsoleInit (C00000D4)
SbieCtrl_HideMessage=2112, AlpcConnectPort (C0000022) access=001F0001 initialized=1
BoxDisplayOrder=anyway,DefaultBox

[anyway]
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
Template=BlockTelemetry
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
UsePrivacyMode=y
BoxNameTitle=-
CopyLimitKb=81920
NeverDelete=y
FakeAdminRights=y
HideOtherBoxes=y
WriteFilePath=C:\Program Files\*
WriteFilePath=D:\*
WriteFilePath=C:\Program Files (x86)\*
NormalFilePath=E:\*
UseSbieWndStation=n
OpenFilePath=D:\Sandboxie-Plus\*
AutoRecoverIgnore=C:\Users\harns\Documents
OpenPipePath=D:\baidu download\*
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
UnrestrictedSCM=y
OpenWinClass=#

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by DavidXanatos** [comment]
hmm... are you using any 3rd parts security softwrae?
not being able to load sbiedll.dll sounds like a problem with soem 3rd party security solution preventing the needed dll injection

**Comment by harnseen** [comment]
> hmm... are you using any 3rd parts security softwrae? not being able to load sbiedll.dll sounds like a problem with soem 3rd party security solution preventing the needed dll injection

no..., only windows defender
![image](https://user-images.githubusercontent.com/42644295/176177881-e1eeac2c-089a-4d7b-a235-207dc2f248ed.png)
![image](https://user-images.githubusercontent.com/42644295/176178049-2397a66a-050e-44c1-b137-346b6517ee87.png)

**Comment by isaak654** [comment]
Another SbieDll.dll crash was also posted [here](https://www.wilderssecurity.com/threads/sandboxie-plus-v1-1-3.445696/page-2#post-3091966) on Wilders forum.

**Comment by isaak654** [comment]
I am not sure whether it applies to you, but there is a [workaround](https://www.wilderssecurity.com/threads/sandboxie-plus-v1-1-3.445696/page-3#post-3097985) for the SbieDll issue:

| @DavidXanatos |
| -------- |
> pelase try adding
> FuncSkipHook=NtOpenSymbolicLinkObject
> to your sandboxie ini
> and let me know if this resolved you rissue?
> If so we need to know what security software you are using and what symlink path it needs to be open

| User's reply |
| -------- |
> With
FuncSkipHook=NtOpenSymbolicLinkObject
in the configuration INI it did not occur since then.
>
> In the meantime I am on 5.57.7, so yesterday I had removed the entry from the INI again and today it also occurred again.
>
> Do you have any idea which symlink path must be open for Eset Internet Security?

**Comment by isaak654** [comment]
Closed for inactivity / lack of feedback.
