### ISSUE TITLE
Exit sandbox at runtime

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#1999]
### Is your feature request related to a problem or use case?

Would you like to know if the sandbox will be leaked when you press the right button in the lower right corner of the computer when a program is running in the sandbox?

### Describe the solution you'd like

Can the processes in the sandbox be killed directly after exiting the sandbox?

**Comment by Taeyeonzpx** [comment]
Right click the exit button in the lower right corner of the sandbox

**Comment by Taeyeonzpx** [comment]
> 因此，您需要一个在 UI 组件终止时终止所有沙盒进程的功能。
> 
> 当没有 UI 组件正在调整时，您将如何设想这种行为？ 防止启动强制进程？？？

Yes, I wonder if this idea is feasible? Will there be any negative impact

**Comment by Taeyeonzpx** [comment]
> 因此，您在 UI 终止时需要终止所有沙盒进程的组件。
> 
> 当没有 UI 组件正在调整的时候，如何将你看到的这种行为？ 阻止强制启动进程？？？

If the sandbox suddenly stops running (killed by other software) or crashes, will there be a leakage problem

**Comment by DavidXanatos** [comment]
the UI component does nto have ahythign todo with isolation. so the UI running or not is irrelevant.

**Comment by Taeyeonzpx** [comment]
> the UI component does nto have ahythign todo with isolation. so the UI running or not is irrelevant.

What if the Sandboxie service isolation component suddenly stops running or is killed? How should the running program in the sandbox be handled? Can you kill them all directly? Will there be isolation failure for those not killed? Can security be guaranteed?

**Comment by Taeyeonzpx** [comment]
> the UI component does nto have ahythign todo with isolation. so the UI running or not is irrelevant.

Mainly concerned about the security of such problems
