### ISSUE TITLE
Please clarify the situation of the different repos

### ISSUE THREAD

**Issue by theuserbl** [sandboxie-plus/Sandboxie#20]
Please clarify the situation of the different repos.

At first news like
https://www.heise.de/security/meldung/Windows-Sandboxing-Tool-Sandboxie-jetzt-Open-Source-4703926.html
mentioned the repo on https://github.com/sandboxie-dev, which was uploaded April, 9th, 2020. Which have also two binary releases published. The author is https://github.com/DavidXanatos
The repo was also linked on the sandboxie-website https://www.sandboxie.com/ .
Then the repo moved to 
https://github.com/sandboxie-plus

Later the sandboxie-website liked to the repo at https://github.com/sandboxie , which was uploaded on April, 14th, 2020.
The author is https://github.com/SandboxieDev

What is now the main project repo? And why existing the other one?

**Comment by DavidXanatos** [comment]
I created the first repo https://github.com/sandboxie-plus (which was renamed in the meantime) the day sophos released the sources as zip download on https://www.sandboxie.com/ April, 9th.

About a week later April, 14th one of the Sandboxie kernel developers form Sophos (https://www.wilderssecurity.com/threads/sandboxie-acquired-by-invincea.357312/page-253#post-2910609) set up the https://github.com/sandboxie/sandboxie repository.

It looks like https://github.com/sandboxie/sandboxie will be the repo for sandboxie releases that are close continuation of the original sandboxie.

And https://github.com/sandboxie-plus/Sandboxie is the repo for my fork that will focus more on adding new features and expanding functionality beyond security applications.

**Comment by quangkieu** [comment]
You should pin this issue on top or reference in the main readme

**Comment by stdedos** [comment]
I understand the approach you are taking here.

It might be better worth it though if you applied your commits on top of the official fork (since people will be able to more easily find your fork too).
