### ISSUE TITLE
Operating System String not passed along

### ISSUE THREAD

**Issue by Hiche3** [sandboxie-plus/Sandboxie#200]
When trying to install Microsoft Visual Studio, there is an error message "This version of Windows is not supported."
The installer works fine outside Sandboxie. Therefore, it appears that Sandboxie does not pass the operating system string along correctly.

1) Go to the following URL to download the free community edition of visual studio:
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16
2) Run installer sandboxed
3) The installation does not proceed due to incorrect operating system
4) Run same installer outside of Sandboxie and it is working.

**Comment by NewKidOnTheBlock** [comment]
That installer is very small (only 1.3MB). It looks like it's a downloader.
The issue might be related to #99

**Comment by Hiche3** [comment]
Working in 5.45
