### ISSUE TITLE
[Plus 1.2.0] UI issues and KmdUtil ControlService

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2001]
1. 

- [x] Global Settings - >  Compatibility
Can only see checkboxes but no text/title

![untitled](https://user-images.githubusercontent.com/19516333/176165721-25dcf12d-363c-4700-820a-bf43786aa830.png)

2. 

Before 1.2.0 Sandbox Options/Status would reflect settings from global or per box templates

e.g.
Block network files and folders, unless specifically opened.
Block access to the printer spooler
Would be faded and checked If
BlockNetworkFiles=y
ClosePrintSpooler=y

Box Status , box icon and 'Drop rights from Administrators and Power Users groups' would reflect if the template has
DropAdminRights=y

Other sandbox types and the lists goes on ...

- [x] KmdUtil ControlService Popup Message :
ControlService Stop: The pipe has been ended.
(109)

Extra
BoxDisplayOrder value in Plus ini is in quotes (")

Windows 7 Ultimate SP1 x64
Plus 1.2.0 x64

**Comment by RandomGOTI** [comment]
Offtopic : `UseFileDeleteV2=y UseRegDeleteV2=y` no longer cause the issues i had in 1.1.0 (# 1885)

**Comment by DavidXanatos** [comment]
1. will be fixed
2. thats an intentional change not to show template values
how to reproduce the KmdUtil issue? for me it works fine
> BoxDisplayOrder value in Plus ini is in quotes (")
so? thats how qt stors strings

**Comment by RandomGOTI** [comment]
> 1. will be fixed
> 
>     2. thats an intentional change not to show template values
>        how to reproduce the KmdUtil issue? for me it works fine
> 
> 
> > BoxDisplayOrder value in Plus ini is in quotes (")
> > so? thats how qt stors strings


2
sad to hear on the feature downgrade , it's usefulness will be missed.
@ kmdutil : Maintenance -> Stop All

**Comment by DavidXanatos** [comment]
was ist that usefull? it showed the value but changing it should not work proeprly as the mechanism always writes only non default values.
I think i should look into adding a better mechanism that not only shows template presets but also allows to change them.
So don't worry the or rather a better functionality will be back.

**Comment by RandomGOTI** [comment]
> was ist that usefull? it showed the value but changing it should not work proeprly as the mechanism always writes only non default values. I think i should look into adding a better mechanism that not only shows template presets but also allows to change them. So don't worry the or rather a better functionality will be back.

depending on use case , yes and the user to get into that drawback is either by trying things out and/or already knows how it works. In my case i avoid using global templates with settings i don't want to override later

**Comment by isaak654** [comment]
I was unable to reproduce the remaining KmdUtil issue after updating Plus from 1.1.2 to 1.2.3.

Perhaps a clean installation would do the trick for you?

**Comment by isaak654** [comment]
I can confirm it the Kmdutil issue, it's only Windows 7 related.

**Comment by isaak654** [comment]
I can confirm the Kmdutil issue, it's only Windows 7 related.

**Comment by isaak654** [comment]
> @ kmdutil : Maintenance -> Stop All >  ControlService Stop: The pipe has been ended.

I can confirm the Kmdutil issue, it's only Windows 7 related.

**Comment by isaak654** [comment]
According to @DavidXanatos, the KmdUtil error has been fixed for the next build.

**Comment by RandomGOTI** [comment]
Confirmed fixed 👍
