### ISSUE TITLE
OpenKeyPath broken on 5.56.3

### ISSUE THREAD

**Issue by asbai** [sandboxie-plus/Sandboxie#2006]
### Describe what you noticed and did

I've `ForceProcess=putty.exe` and `OpenKeyPath=putty.exe,HKEY_CURRENT_USER\Software\SimonTatham\*` in a sandbox, and they work fine on 5.55.22 and before. After upgrading to 5.56.3, Putty can no longer successfully access the corresponding registry subkeys and all configurations are gone.

### How often did you encounter it so far?

everytime

### Affected program

PuTTY  Release 0.76  Build platform: 64-bit x86 Windows

### Download link

https://www.chiark.greenend.org.uk/~sgtatham/putty/releases/0.76.html

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Follow `OpenKeyPath=putty.exe,HKEY_CURRENT_USER\Software\SimonTatham\*` instruction

### What is your Windows edition and version?

Win7 x64 64bit

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

none

### What version of Sandboxie are you running?

5.56.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

### Is it a regression?

AFAIK, 5.55.22 is fine

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

no

**Comment by isaak654** [comment]
#2019
