### ISSUE TITLE
media key control & denied access logging

### ISSUE THREAD

**Issue by AcThPaU** [sandboxie-plus/Sandboxie#201]
Program inside sandbox cannot access media keys (<<, | |, >> keys found on some keyboard, Bluetooth devices )

I don't know if media key works through COM or IPC. 

Is there anyway to log denied resource accesses ?

**Comment by isaak654** [comment]
It looks related to #192 issue.

**Comment by NyarlathotepZERO** [comment]
Specific hardware and driver details would be useful

**Comment by AcThPaU** [comment]
@NyarlathotepZERO I don't think it's system-specific or driver-specific problem.

AFAIK This issue has been there since the very early stage of Sandboxie (long long long before DX took over).

**Comment by NyarlathotepZERO** [comment]
> @NyarlathotepZERO I don't think it's system-specific or driver-specific problem.
> 
> AFAIK This issue has been there since the very early stage of Sandboxie (long long long before DX took over).

I have tested media keys on both a logitech and rapoo bluetooth keyboard and both work without hitch

**Comment by NewKidOnTheBlock** [comment]
Just tested by running [AIMP](https://www.aimp.ru/) audio player in Sandboxie.
All multimedia keys on my keyboard work fine: Next song, Previous song, Pause...

**Comment by AcThPaU** [comment]
@NyarlathotepZERO @NewKidOnTheBlock 

I have tested Bluetooth headphone media key on PotPlayer and works.

The issue seems to be specific to the software I was using, which is a niche Chinese music player (NeteaseMusic).

It would be ideal if someone want to investigate it, but I consider the issue closed.

Thank you all for the efforts !
