### ISSUE TITLE
Sandboxie-Classic-x64, on Windows 11, does not run Explorer correctly.

### ISSUE THREAD

**Issue by FanXiangTM** [sandboxie-plus/Sandboxie#2010]
### Describe what you noticed and did

Sandboxie-Classic-x64, on Windows 11, does not run Explorer correctly.

### How often did you encounter it so far?

every time

### Affected program

explorer.exe

### Download link

none

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Sandboxie-Classic-x64, on Windows 11, does not run Explorer correctly.

### What is your Windows edition and version?

Windows11

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

none

### What version of Sandboxie are you running?

Sandboxie-Classic-x64, v 5.56(3)

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by droped** [comment]
This is a known issue and is supposedly fixed in the 22H2 version of windows 11.
