### ISSUE TITLE
 SUPPORTER CERTIFICATE type invalid

### ISSUE THREAD

**Issue by NightmareZero** [sandboxie-plus/Sandboxie#2012]
### Describe what you noticed and did

I bought a UPPORTER CERTIFICATE and got a key like this
NAME: xxx
DATE: 05.07.2022
TYPE: PERSONAL-SMALL
SOFTWARE: Sandboxie-Plus
UPDATEKEY: xxxxx
SIGNATURE: xxxx

But the key format in the program is

NAME: xxx
LEVEL: ULTIMATE
DATE: XXXX
UPDATEKEY: xxxxx
SIGNATURE: xxxx

and certificate is invalid now
which step is wrong for me?

forgive me for writing non-technical questions here and my poor english

### Affected program

sandboxie+

### Download link

x

### Where is the program located?

Not relevant to my request.

### Expected behavior

x

### What is your Windows edition and version?

win11 x64

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Defender

### What version of Sandboxie are you running?

sandboxie+ 1.1.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
The key parser is quite tolerant just paste what you got into that edit controll and hit apply
the main reason a example was addes were peopel pasting only the upate key or only the signature in that window

**Comment by NightmareZero** [comment]
> 

But when I copy the key I got into it, it prompts me that the key is invalid

**Comment by DavidXanatos** [comment]
Did you enter the entire certificate as provided without changing order or removing single lines?

**Comment by NightmareZero** [comment]
> Did you enter the entire certificate as provided without changing order or removing single lines?

yes, i copy everything in the block

**Comment by DavidXanatos** [comment]
That is really strange the cert generator always tests teh certificates so tehre must be an issue with the input, please contact me by email to resolve this issue.
you can find my email address in my github profile

**Comment by DavidXanatos** [comment]
I could perhaps use the service to dump the file in that folder, than no query dialog would be required... not sure if that's a good solution

**Comment by wgetnz** [comment]
我发现用户名中含有中文，证书一直校验错误，我将证书内容直接复制到Certificate.dat即可解决

**Comment by DavidXanatos** [comment]
were you using the setup wizard instead of the support settings page?
there was a bug with utf8 encoding, which is now fixed
so perhaps we can close this now
