### ISSUE TITLE
Trying to run two instances of Fall Guys (EasyAntiCheat)

### ISSUE THREAD

**Issue by SoniaMalki** [sandboxie-plus/Sandboxie#2021]
### Describe what you noticed and did

Hi! 

I am trying to run two instances of fall guys on my computer, but it fails everytime. I am running aster so I can do multiseating, and I am using two account on my windows 10 computer. 
When I try to run two instances, only one is working, while the other shows an error message. So I searched on internet and they said I have to run Fall Guys on a Sandboxie instance, so it is isolated. Unfortunalty I couldn't because the EasyAntiCheat block it. I tried running it directly from my computer, then I uninstalled it and installed Epic Game launcher through Sandboxie so everything is isolated. But it throws the same error with EasyAnticheat. 
So I don't know how to isolate it so it doesn't throw an error.

I tried also to run a VM, but it is not launching at all, it tells me that something went wrong when I want to run Fall Guys in the VM. Even though, I can't share the GPU the same way I do it with Aster. 

Can you give me advice to run it twice? I have the necessary ressources, but EAC is blocking all my attemps. 

thank you 

### How often did you encounter it so far?

Everytime

### Affected program

Fall Guys, Easy Anti Cheat, Epic games

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

I want to run the program, but EAC is blocking it

### What is your Windows edition and version?

Windows 10 pri

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie-plus v1.1.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
You may try with the suggestions provided in #1192 and #1515, otherwise this is unknown territory.
