### ISSUE TITLE
Option for Immediate File Recovery dialog not to be set to always-on-top.

### ISSUE THREAD

**Issue by olliebean** [sandboxie-plus/Sandboxie#2022]
### Is your feature request related to a problem or use case?

A recent update seems to have made the File Recovery dialog, when "Enable Immediate Recovery" is enabled, to appear as an always-on-top window. Often there are multiple files being created by the sandboxed program, and it is inconvenient having an always-on-top window on screen while waiting for it to finish.

### Describe the solution you'd like

Make the always-on-top attribute of the Immediate Recovery dialog an optional setting.

**Comment by DavidXanatos** [comment]
this is the behavioure of the originals andboxie and it was requested to make the plus ui do the same,
it can be disabled by adding RecoveryOnTop=false to the [Options] group in the plus ini.
Ill add a switch for that to the next build

**Comment by olliebean** [comment]
Thanks; I've added that option to the ini.

**Comment by diieg707** [comment]
> Thanks; I've added that option to the ini.

alternatively you can leave it minimized (won't pop up when file created) or you can disable recovery on tray icon
