### ISSUE TITLE
Element.io 1.11 crashes on launch and install

### ISSUE THREAD

**Issue by Foosec** [sandboxie-plus/Sandboxie#2023]
### Describe what you noticed and did

New version of element.io crashes on launch / install. (Sandboxie reports process has crashed)

### How often did you encounter it so far?

Always

### Affected program

Element matrix client

### Download link

https://element.io/get-started#download

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

No crash :)

### What is your Windows edition and version?

Win 10 Pro Version	10.0.19044 Build 19044

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Eset antivirus

### What version of Sandboxie are you running?

Sandboxie-plus 64bit 1.1.3

### Is it a new installation of Sandboxie?

I have been in the same version for a while now.

### In which sandbox type you have this problem?

In a Sandbox with data protection (blue sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
UsePrivacyMode=y
NormalFilePath=C:\Users\Foobar\Downloads
```

**Comment by TooYoungTooSimp** [comment]
Not same software but I encontered this problem in another electron based app (Spotify), It flickers on start, then disappered.

I noticed a change in chrome_elf.dll, so I think it may be a election (upstream) bug.

**Comment by Dyras** [comment]
Same here on SB-P 1.2.3
![grafik](https://user-images.githubusercontent.com/12563436/179399004-a4978add-b69d-402f-905e-f9196cc6df2c.png)

Will try to get a trace log soon

**Comment by isaak654** [comment]
Same issue with [v1.2.3 x64](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.2.3), but it will start working fine with `SpecialImage=chrome,element.exe` under your [sandbox] section in the Sandboxie.ini configuration file. For reasons that I ignore, Element works fine out of the box without that line on [v1.0.22 x64](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.22).

**Comment by TooYoungTooSimp** [comment]
> Same issue with [v1.2.3 x64](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.2.3), but it will start working fine with `SpecialImage=chrome,element.exe` under your [sandbox] section in the Sandboxie.ini configuration file. For reasons that I ignore, the same version of Element works fine by default without that line on [v1.0.22 x64](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.22).


I tried this solution on Spotify.exe, unfortunately, it makes my PC BSOD with the error `PAGE_FAULT_IN_NONPAGED_AREA`

minidump file provided below
[Minidump.zip](https://github.com/sandboxie-plus/Sandboxie/files/9127939/Minidump.zip)

**Comment by DavidXanatos** [comment]
I think this workaround will be it.
The crash is internal to element11.exe so it just crashes when we add the special extra command aprameters.
an alternative workaround would be 
UseElectronWorkaround=n
I'll make this setting per process in future and we wil add an
UseElectronWorkaround=Element.exe,n
to the global compatybility templates

**Comment by Dyras** [comment]
Element doesn't flat out crash now on 1.2.5, but I can't get it to actually open the window when I double click the tray icon.

Is it working for you now @Foosec?

**Comment by isaak654** [comment]
> Element doesn't flat out crash now on 1.2.5, but I can't get it to actually open the window when I double click the tray icon.
>

Confirmed, but that is another issue to be opened separately.
