### ISSUE TITLE
[Plus 1.2.1] File Panel creating empty folder

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2026]
### Describe what you noticed and did

When i use the show file panel (ctrl+d) on an empty box it will create an empty folder

1. Select empty box
2. ctrl+d
3. check file root path

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

Maybe same action when a box group is selected, sbie folder

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.2.1 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

**Comment by DavidXanatos** [comment]
Well that was intentional, we have to show something

**Comment by RandomGOTI** [comment]
> Well that was intentional, we have to show something

_Expected behavior
Maybe same action when a box group is selected for empty boxes, sbie folder_(install/port directory)
Would be much better than having a empty folder created ( ͡° ͜ʖ ͡°)

**Comment by DavidXanatos** [comment]
mmh ok agreed will change it this way for the next build

**Comment by RandomGOTI** [comment]
Confirmed fixed 👍
