### ISSUE TITLE
[Plus 1.2.2] Tray menu Issue

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2027]
### Describe what you noticed and did

Without Compact box list
Only "Create New box" and "Create group" option is shown

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

.

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.2.2 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

**Comment by DavidXanatos** [comment]
fixed in next build
