### ISSUE TITLE
[Plus 1.2.3] Keybinds become unresponsive when...

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2030]
### 👉 Describe what you noticed and did

- [x] When i toggle the compact tray menu or any other UI  setting(e.g. pizza background) that has the following : sandman does a view refresh as if i just restarted the agent(also shows the starting message logs) and the F5 and ctrl+d keybinds seems to stop responding untill i relaunch the agent.

### 👉 Additional issue (this is only Windows 7 related, not Win10 or later)

- [x] **KmdUtil ControlService Popup Messages** (just an annoyance) :
ControlService Stop: The pipe has been ended.
(109)
 -Requires to press OK to continue
Happens whenever `kmdutil.exe stop SbieSvc`
regression Plus 1.2.0 x64 -> [#2001](https://github.com/sandboxie-plus/Sandboxie/issues/2001#issuecomment-1185949641) 

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

∠( ᐛ 」∠)＿

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.2.3 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

**Comment by wilders-soccerfan** [comment]
> KmdUtil ControlService Popup Messages (just an annoyance) :+1: 

I can confirm this whenever I use the option 'Uninstall All' from the maintenance menu. [Win7 Home 64bit]
