### ISSUE TITLE
[Plus 1.2.5] Delete Content with ShowRecovery=true , "Delete Content" button on File Recovery window not working

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2043]
### Describe what you noticed and did

https://github.com/sandboxie-plus/Sandboxie/commit/279cf8fb42e225471e2bea2e669a5eb6d94d882f
A issue with this pre release i have not seen reported yet 
Delete content would not work , most likely after #2024 was added , as i could only delete selection

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

.

### What is your Windows edition and version?

.

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

.

### What version of Sandboxie are you running?

.

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
what do you mean with delete selection?

**Comment by RandomGOTI** [comment]
> what do you mean with delete selection?

selecting/highligh files/folders and pressing the `Delete` button that was added in that build , the `Delete Content` button did nothing, only way to `Empty` a box is by using autodelete

**Comment by DavidXanatos** [comment]
i did not add a delete button, can you provide a video or few screenshots of what you mean exactly

**Comment by RandomGOTI** [comment]
> i did not add a delete button, can you provide a video or few screenshots of what you mean exactly

![untitled2](https://user-images.githubusercontent.com/19516333/180514613-64bc9431-9a4e-4c8e-b4ce-1984a3e8051c.png)

[Sandboxie-Plus-x64-v1.2.4.zip](https://github.com/sandboxie-plus/Sandboxie/files/9170190/Sandboxie-Plus-x64-v1.2.4.zip)

ShowRecovery=true
Right click box - > Delete Content

**Comment by DavidXanatos** [comment]
ah i see... will be fixed in 1.2.5b

**Comment by RandomGOTI** [comment]
Confirmed fixed 👍
