### ISSUE TITLE
Supporter certificate is expired on v1.2.4, but still valid on v1.2.3

### ISSUE THREAD

**Issue by DaneXtream** [sandboxie-plus/Sandboxie#2044]
### Describe what you noticed and did

I have a supporter certificate which should be valid one year:

DATE: 29.11.2021
TYPE: PERSONAL-SMALL
SOFTWARE: Sandboxie-Plus

### How often did you encounter it so far?

Always

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The certificate should expire on 29.11.2022, not before that.

### What is your Windows edition and version?

Windows 11 Pro 21H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.2.4 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

### Is it a regression?

Since 5.57.4 64-bit

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

Not relevant

**Comment by DavidXanatos** [comment]
this is a bug with the 1.2.4 binaries and will be fixed soon

**Comment by DavidXanatos** [comment]
fixed 1.2.5 is up
