### ISSUE TITLE
[Plus v1.2.5] Box context menu -> Sandbox Preset -> drop rights-related entries not working

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#2046]
### Describe what you noticed and did

In the box context menu, under "Sandbox Presets", clicking on the UAC/drop rights related entries has no effect. 
![grafik](https://user-images.githubusercontent.com/78082344/180534166-cee3de2b-1955-4922-8e5a-c7cc03b795b2.png)

### Affected program

n/a

### Download link

n/a

### Where is the program located?

Not relevant to my request.

### Expected behavior

The appropiate settings are applied

### What is your Windows edition and version?

n/a

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

n/a

### What version of Sandboxie are you running?

Sandboxie-Plus 1.2.5

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
Confirmed, I also have the same issue with the "Emulate Admin Rights" option.

**Comment by DavidXanatos** [comment]
fixed in 1.2.5b or so
