### ISSUE TITLE
SbieDrv.sys blue screen with Avast One antivirus

### ISSUE THREAD

**Issue by oklokl** [sandboxie-plus/Sandboxie#2048]
### Describe what you noticed and did

My computer has stopped.

### How often did you encounter it so far?

about once

### Affected program

windows11

### Download link

https://sandboxie-plus.com/downloads/

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

[072022-7156-01.zip](https://github.com/sandboxie-plus/Sandboxie/files/9173150/072022-7156-01.zip)

Computer freezes. If I restart quickly. If I do that, my computer does an unknown Windows system update.

And when I use the computer, the computer freezes. I had this symptom only once.

So I had no choice but to block autostart as follows.
sc stop "SbieSvc" & sc config "SbieSvc" start= demand
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieSvc" /v "Start" /t REG_DWORD /d 3 /f

Manually turn on the service when I need it.
But not because of my actions.

If I don't do this I get a blue screen once.

### What is your Windows edition and version?

windows 11 home 64bit kr inside Version 10.0.22621.232

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

avast one antivirus

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.1.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Sandboxie-Plus-x64-v1.1.3

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Crash dump

https://github.com/sandboxie-plus/Sandboxie/files/9173150/072022-7156-01.zip

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
Template=Edge_Win11Fix
Template=Avast_Antivirus
Template=WindowsLive
Template=OfficeLicensing

[UserSettings_79920656]
SbieCtrl_AutoStartAgent=SandMan.exe
BoxDisplayOrder=DefaultBox
SbieCtrl_UserName=shdfgh0629asdfk7jf
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_WindowCoords=200,150,1237,632
SbieCtrl_ActiveView=40021

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=81920
NeverDelete=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices

[UserSettings_3156042E]
SbieCtrl_AutoStartAgent=SandMan.exe
BoxDisplayOrder=DefaultBox
```

**Comment by isaak654** [comment]
Make sure to remove `Template=Avast_Antivirus` (which is not maintained at this time) and let us know.

**Comment by isaak654** [comment]
* Please consider to remove `Template=Avast_Antivirus` (which is not maintained at this time)
* Try also older builds than v1.1.3 (one release at a time): https://github.com/sandboxie-plus/Sandboxie/releases

Let us know.

**Comment by oklokl** [comment]
I have deleted avast and the symptoms are not occurring.
My guess is that the programs are fighting each other's memory.

However.
Avast is currently known as the number 1 in the world. I think it is the only anti-virus that has a lot of users and can even use a free firewall function. useful

My thoughts do not conflict with each other. How about giving technical feedback to Avast?.

Reveal the second method or how to exclude exception handling from avast (know-how, tips)

Avast is the most used program in the world. It would be a pity if it could not be used due to a conflict problem.

thank you. The `Sandboxie` program is always working well.

The part I don't like very much, very little... is the real-time process service registration. Nothing but this.

I've been using the Sandboxie program since the early days.
:)
I am an old user

The auto-start function was also created by limiting myself. People don't trust me

I suggested it because I needed it back then, but now it's uncomfortable haha
:)

As it was then, I still don't speak English, so I use Google Translate.
Sorry.

Oh, and if I'm more greedy... I hope a portable version will be released as well.

A version that can be used on the go by putting it in a USB. lightweight.
After being recommended Portable, I fell in love with it.

**Comment by DavidXanatos** [comment]
Please test with the variouse versions available if you can find out in which version of sandboxie this issue has first manifested.

**Comment by DavidXanatos** [comment]
There is already a portable version just start the Plus installer and choose extract instead fo install than it will unpack a portable build into a directory of your choosing

**Comment by oklokl** [comment]
https://sandboxie-plus.com/downloads/
`Sandboxie-Plus-x64-v1.1.3-portable.zip`
In my opinion. It would be nice to provide this as a link.
Once I've solved my problem, I'll stop asking. thank you.
:)

**Comment by DavidXanatos** [comment]
> https://sandboxie-plus.com/downloads/ `Sandboxie-Plus-x64-v1.1.3-portable.zip` In my opinion. It would be nice to provide this as a link. Once I've solved my problem, I'll stop asking. thank you. :)

why? how is that better than a self extracting archive? if you need a ip download the installer unpack it and then zip the result.
I really don't see a point in wasting githubs HDD space with providing the exact same files twice.

**Comment by oklokl** [comment]
https://portableapps.com/ 
I mainly use this site.
Portable is user-friendly.

And I can't speak English. It is very difficult to understand others
I'm sorry.

For example, it is a program that Korean users consider the best.
I'm not talking about compression programs
I give you my words like this.
https://www.bandisoft.com/bandizip/
https://www.bandisoft.com/bandizip/dl.php?portable
(referring to the services provided in this way)

There is a language cliff because I don't speak English
sorry.

**Comment by isaak654** [comment]
@oklokl 
You have the same issue described in https://github.com/sandboxie-plus/Sandboxie/issues/2051#issuecomment-1193169423, so you may want to follow the suggestions that I left there.
I did my best to look into it, so any further help would be appreciated.

**Comment by isaak654** [comment]
Since you have already replied in issue [#2051](https://github.com/sandboxie-plus/Sandboxie/issues/2051#issuecomment-1193913445), let's continue there.
