### ISSUE TITLE
High CPU usage on Vivaldi with Sandboxie-Plus-x64-v1.2.5 and ESET Internet Security

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#2049]
### Describe what you noticed and did

I tried V1.2.0 and V1.2.1, but they did not work at all, presumably because of the Certificate problem, which I am not knowledgeable enough to deal with.  Each time I was able to revert to V1.1.3 by re-installing it over the top.  That put the system back to where it was, complete with the confusing bugs that I described on 2022-05-02 and 2022-05-16 in https://github.com/sandboxie-plus/Sandboxie/issues/1835 .

Today I read that V1.2.5 had fixed the Certificate problem so I tried again, but things were different, and worse than before. When I launched Vivaldi, ESET produced the error message in the attached file below. I decided not to proceed, and closed Vivaldi.  After a couple more attempts, using buttons that opened multiple webpages, I gave up, and was again able to reinstall V1.1.3 over the top.  Presumably the Certificate problem is not fixed.

Then there was a loud whirring noise, which I assumed was the cooling system in overdrive because of overheating.  Task Manager showed that there were 50 copies of Vivaldi still running.  I closed them immediately in Task Manager, and after about 5 minutes the whirring stopped.  I shut down the PC a couple of minutes later.

That was pretty dangerous for the PC.  Could you please warn us that this current series of versions are really only alpha versions — not even beta versions — and that they should only be tested by experienced techies.  I am an experienced user with some coding, but I am not a techie.

All best wishes, David, for your work.  My wife and I rely on Sandboxie every day for browsing.
64-bit Windows 10 desktop, 21H2, V10.0.19044.1826
ESET Internet Security V15.2.11.0

![Clipboard Image](https://user-images.githubusercontent.com/16393911/180596612-2b973a6a-fd6d-4951-b4ae-65e50bf8f5fd.jpg)

### How often did you encounter it so far?

As above

### Affected program

Vivaldi.5.3.2679.70.x64

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

As above

### What is your Windows edition and version?

64-bit Windows 10 desktop, 21H2, V10.0.19044.1826

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET Internet Security V15.2.11.0

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.2.5

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than v1.0.22 / 5.55.22.

### Is it a regression?

Sandboxie-Plus-x64-v1.2.5

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Crash dump

Not relevant

### Trace log

Not relevant

### Sandboxie.ini configuration

```shell
Not relevant, but given in the previous post mentioned above.
```

**Comment by DavidXanatos** [comment]
As far as i see this error message it says that vivaldi tried to talk to download.vivaldi.com which die not have a vlaid SSL certificate,
this is in no way related to the sandboxie installer not being signed.

I tried esset internet security trail + vivaldi + sandboxie and in my test VM it worked fine.

Also running your CPU at 100% for a few minutes and even hours is not dangerous in any way.

**Comment by isaak654** [comment]
The certificate issue fixed in Plus 1.2.5 was only related to the paid features of Sandboxie Plus and it has nothing to do with the ESET warning you just shared, not even close.

**Comment by NotepadPlusUser** [comment]
Thanks, David and @Isaak654.  I will leave everything as is until the official release comes up.  If it persists with the official release, then I will follow up  with ESET and–or Vivaldi, 

No worries changing the title, which I confess was over-dramatic.

My significant comment was really that with these pre-releases (beta?), it may be wise to advise non-techies that they should probably avoid them.

**Comment by NotepadPlusUser** [comment]
SUCCESS:  I have now installed V1.2.7, and all seems to be back to as it was with V1.1.3.  I will leave it to the techies to explain why.

That still leaves the strange behaviour described in my post of 2nd May: https://github.com/sandboxie-plus/Sandboxie/issues/1835 .

I can work around it, so it is not mission critical, but it is a nuisance.  David, or @Isaak654, I'm very happy to give further details and log and ini files if that is required, but do explain clearly what you want and how to produce it.  I also understand that that there are many urgent issues to be sorted out, and few people to work on things.

**Comment by isaak654** [comment]
> That still leaves the strange behaviour described in my post of 2nd May: https://github.com/sandboxie-plus/Sandboxie/issues/1835 .
> I can work around it, so it is not mission critical, but it is a nuisance. 
> I'm very happy to give further details and log and ini files if that is required, but do explain clearly what you want and how to produce it

@NotepadPlusUser 
If you can confirm that [this workaround](https://github.com/sandboxie-plus/Sandboxie/issues/1835#issuecomment-1193094600) worked fine (for you) to open a second Vivaldi instance, then you could get in touch with the Vivaldi Team and ask them what's the current status with the bug report [VB-89933](https://github.com/sandboxie-plus/Sandboxie/issues/1783#issuecomment-1125925663) I opened months ago through their [bug report form](https://vivaldi.com/it/bugreport).

**Comment by isaak654** [comment]
> That still leaves the strange behaviour described in my post of 2nd May: https://github.com/sandboxie-plus/Sandboxie/issues/1835 .
> I can work around it, so it is not mission critical, but it is a nuisance. 
> I'm very happy to give further details and log and ini files if that is required, but do explain clearly what you want and how to produce it

@NotepadPlusUser 
If you can confirm that [this workaround](https://github.com/sandboxie-plus/Sandboxie/issues/1835#issuecomment-1193094600) worked fine (for you) to open a second Vivaldi instance, then you could get in touch with the Vivaldi Team and ask them what's the current status with the bug report [VB-89933](https://github.com/sandboxie-plus/Sandboxie/issues/1783#issuecomment-1125925663) I opened months ago.

**Comment by NotepadPlusUser** [comment]
Thanks, @Isaak654,  The situation keeps changing, and now seems confined to Vivaldi.  I will wait until Vivaldi brings out V5.4, then check the behaviour carefully and post — here first, in case I am misunderstanding the details.

**Comment by isaak654** [comment]
There is no rush, however I'm going to close this issue in favour of the original #1783
