### ISSUE TITLE
NtRenameKey support

### ISSUE THREAD

**Issue by gjf** [sandboxie-plus/Sandboxie#205]
Some strange situation occurs.

1. Run regedit.exe in a sandbox. Doesn't matter as UAC admin or not.
2. Try to create any sunkey in HKCU/SOFTWARE (but I believe it doesn't matter - in any place).
3. You will get the error SBIE2205 Сервис не реализован:  NtRenameKey
4. The subkey is not created.

Sandboxie 5.44.1 x64 on Win 20H2

**Comment by DavidXanatos** [comment]
sandboxie does not currently supprot renaming of registry keys

**Comment by gjf** [comment]
It's not renaming but creating.

**Comment by DavidXanatos** [comment]
but it calls  NtRenameKey for whatever reason and that call was never supported, its on my todo to add support for that at some point in time but its nit high priority.
there are practically no applications that would as part of normal operation rename registry keys, thats something done almost onyl by a user uing reg edit

**Comment by C-o-l-u-m-b-o** [comment]
Actually I have an application that cashes at startup - caused by this not implemented service :( -

**Comment by isaak654** [comment]
> Actually I have an application that cashes at startup

Which one?

**Comment by DavidXanatos** [comment]
This feature si ready and will be added in one of the upcoming builds, may be not the next as that might be only a minor release with some fixes only quickly followed by a large experimental release
this feature will need you to enable it with UseRegDeleteV2=y

**Comment by isaak654** [comment]
I can't find any `UseRegDeleteV2` in the source code, so I'm going to remove the "added in next build" status for now.

**Comment by DavidXanatos** [comment]
Its compelte in my local repository and waiting to be pushed to github as 1.1.0  shortly after 1.0.10 was released

**Comment by DavidXanatos** [comment]
have create a temporary branch for it: https://github.com/sandboxie-plus/Sandboxie/commit/1d29ff173e67c1168642770be1babed166eb8ef8

**Comment by droped** [comment]
The new option UseRegDeleteV2=y fails to start windows explorer with Sbie2306 and Sbie2304 error messages.

**Comment by fun29** [comment]
This message has "returned" in 5.73.3 (64 bit) when using firefox.

SBIE2205 Service not implemented:  NtRenameKey
