### ISSUE TITLE
Switching between view modes (Simple, Advanced, and Vintage) while the main window is in a maximized state causes a white flash.

### ISSUE THREAD

**Issue by Dark-Magician** [sandboxie-plus/Sandboxie#2050]
### Describe what you noticed and did

1. Maximize the main window (The main window **must** be in a **maximized** state).
2. Switch between view modes (Simple, Advanced, and Vintage).

The result:

![SandMan_WjjUndmGti](https://user-images.githubusercontent.com/19816749/180599795-02eeee1c-33e4-493d-966c-d55b3676f97e.gif)

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The transition between view modes should be instant without any flashes like so:

![SandMan_SEfLPvT93W](https://user-images.githubusercontent.com/19816749/180600061-46ae5625-9a3a-4135-97c0-af76f3275812.gif)

### What is your Windows edition and version?

Windows 10 Pro 21H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.2.5 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Since Sandboxie Plus 1.2.1 64-bit when the Vintage view mode was first introduced.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
It may look nicer without flashes, but since we destroy the entire UI and rebuild it, the flashes are unavoidable.
The transition between simple and advanced could be made this way but nto the one to and from vintage.
Since the expected usage is to set the view mode and stick to it, i think my time is better spent on actual problems that break things.

**Comment by Dark-Magician** [comment]
> since we destroy the entire UI and rebuild it, the flashes are unavoidable.

I do not think that is the problem because it only occurs when the UI is in a maximized state, not in windowed mode, regardless of how large the UI is, and the UI is presumably destroyed and rebuilt in both cases. I resized each side of the UI to 1 pixel from each edge of each side of the screen, and the flashes were not present. That is as close to a maximized state as one can get. The problem seems to be that the UI returns to a maximized state after rebuilding it. I wonder if it may be related to [this](https://github.com/sandboxie-plus/Sandboxie/issues/1968), though I have not seen that problem since the most recent Sandboxie Plus versions.

**Comment by bastik-1001** [comment]
Using 1.2.6 there are sometimes white flashes, but not as bright compared to how the other issue shows, when going from minimized to maximized. Not pretty, but no great concern. Arguably there are more important things to be fixed, but keeping it in mind when touching the UI, might be a good idea.
