### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by fusionneur** [sandboxie-plus/Sandboxie#2052]
### Describe what you noticed and did

Trying to update (via installer .exe), gives an error that COM Surrogate is running (dllhost.exe) and I am presented with option to auto-terminate the processes. If I do that, it fails to terminate the processes and an option to retry is shown with the same effect. Only option is to cancel/roll-back installation changes.

Note: Signing off and resigning in (logoff/logon) solved the issue.

### Affected program

N/A

### Download link

N/A

### Where is the program located?

Not relevant to my request.

### Expected behavior

Sandboxie is updated as usual.

### What is your Windows edition and version?

Windows 11 x64 21H2

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Eset EIS

### What version of Sandboxie are you running?

1.2.5 x64 Plus

### Is it a new installation of Sandboxie?

I just updated Sandboxie from the previous version.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
Try uninstalling rebooting and re installing

**Comment by isaak654** [comment]
* Please use [this](https://support.malwarebytes.com/hc/en-us/articles/360039025013-Run-Farbar-Recovery-Scan-Tool-to-gather-logs) tool to produce a troubleshooting log and attach it here. It could be helpful to get an overview of your system.
* Try uninstalling ESET, rebooting, updating SBIE again and reinstalling ESET a second time.

**Comment by isaak654** [comment]
The same user opened #2097 without providing a feedback on this issue.
