### ISSUE TITLE
Viewing registry changes

### ISSUE THREAD

**Issue by gjf** [sandboxie-plus/Sandboxie#206]
As far as I know the sandbox registry hive is stored in RegHive file.
To view it I used the following script:
REG LOAD HKLM\uuusandboxuuu RegHive  
REG EXPORT HKLM\uuusandboxuuu  sandbox.reg  
REG UNLOAD HKLM\uuusandboxuuu  
notepad sandbox.reg

In latest version (5.44.1) this script does not work - it shows an empty registry file.

What is wrong, what is changed and how to view registry changes now?

**Comment by DavidXanatos** [comment]
nothign changed that should have worked, try a new sandbox just in case

**Comment by gjf** [comment]
Tried that. Was Reghive file format changed?

**Comment by DavidXanatos** [comment]
No it was not

**Comment by gjf** [comment]
Seems it is new Win 10 games... it is not possible to load the hive to HKLM any more.
Changing it to HKU works but permissions are broken when trying to export subkeys into a file.

OK will wait for registry viewer feature out-of-box in Sandboxie! :-)

**Comment by woctezuma** [comment]
> 
> OK will wait for registry viewer feature out-of-box in Sandboxie! :-)

This works great: https://github.com/sandboxie-plus/Sandboxie/issues/60#issuecomment-815209594
