### ISSUE TITLE
Is Window Sandboxed misses a question mark

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2065]
### Describe what you noticed and did

The string in https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_en.ts#L1758 "Is Window Sandboxed" is missing a question mark.

I had translated that before and if I recall correctly there had been one. Now my latest translation does not include one either, but I think it should.

(Besides that my translation has a typo, since it misses a 'd' in the word sand.)

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Questions having a question mark. :)

### What is your Windows edition and version?

Not relevant

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Not relevant

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

One could say that, if I remember correctly

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
Yea first  it was called Window Finder, than on box objections i copied the string from classic that had the? but then i thought it looks strange with the question mark so i removed it.
so jets dedice once and for all
question mark at the menu 
Y 👍 
N 👎 
please vote

**Comment by DavidXanatos** [comment]
btw the the context menu

CSettingsWindow::tr("Run &Sandboxed") should be translated as "In Sandbox ausführen" and not as "Starte sandgeboxt" ;)

**Comment by DavidXanatos** [comment]
Or should we call that option in the non vintage UI mode again "Window Finder?"
i don't like a menu that sounds like a question i rather like tool descriptive labels
"Windows tester" ?

**Comment by bastik-1001** [comment]
> btw the the context menu
> 
> CSettingsWindow::tr("Run &Sandboxed") should be translated as "In Sandbox ausführen" and not as "Starte sandgeboxt" ;)

It used to be "In Sandbox ausführen", which I changed to the current, after the string got moved around, so it was not being used, as that is as short, as the source, which does not contain the word in, either. I happily change it back to what it was. :)

**Comment by bastik-1001** [comment]
If it remains a question, my preference is that it has a question mark.

> Or should we call that option in the non vintage UI mode again "Window Finder?" i don't like a menu that sounds like a question i rather like tool descriptive labels "Windows tester" ?

If you don't like questions in menus, then you'd need another word.  "Is window sandboxed?" describes what it does. Maybe "Window sandbox tester" would come close. Where it is not to be confused with Windows. "Sandbox window tester" might work as well, which seems to suggest that it test a sandboxed window, what is what the tool should do, say if it is sandboxed or not.

**Comment by bastik-1001** [comment]
Regardless of potential changes to the string, I translated it, after the latest update of the translation file and consider this issue to be obsolete.
