### ISSUE TITLE
Why is sandboxie keeps on updating my steam?

### ISSUE THREAD

**Issue by katastrophe92** [sandboxie-plus/Sandboxie#2072]
### Describe what you noticed and did

Every time when i open Steam wants to update. PC Steam and Sandboxie Steam is the same version though. What should I do. Thanks. I have the Payd Sandboxie-Plus version

### How often did you encounter it so far?

every time 

### Affected program

Steam

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Open without update needed 

### What is your Windows edition and version?

Windows 11 Pro 21H2

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie-Plus Version 1.1.3

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

Version 1.1.3

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

no

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=y
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=RTSS
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Edge_Win11Fix

[UserSettings_08B801B3]
SbieCtrl_AutoStartAgent=SandMan.exe
BoxDisplayOrder=io92,DefaultBox,alex_alex92,thenotoriousmj,New_io92,New_alex_alex92,New_thenotoriousmj
SbieCtrl_EnableAutoStart=y
BoxCollapsedView=New_alex_alex92,New_thenotoriousmj,io92,thenotoriousmj,alex_alex92,New_io92

[New_io92]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
NoSecurityIsolation=y
UsePrivacyMode=n
RunCommand=C:\Program Files (x86)\Steam\steam.exe|C:\Program Files (x86)\Steam\steam.exe
CopyLimitKb=8001920

[New_alex_alex92]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
NoSecurityIsolation=y
UsePrivacyMode=n
RunCommand=C:\Program Files (x86)\Steam\steam.exe|C:\Program Files (x86)\Steam\steam.exe
CopyLimitKb=8001920

[New_thenotoriousmj]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
NoSecurityIsolation=y
RunCommand=C:\Program Files (x86)\Steam\steam.exe|C:\Program Files (x86)\Steam\steam.exe
CopyLimitKb=8001920
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by isaak654** [comment]
I can confirm this. As far as I know, forcing the Steam update outside the sandbox should help to some extent (Steam menu ->Check for Steam Client Updates).

**Comment by DemonAk** [comment]
This is old issue
just create in steam folder file "steam.cfg" with string: BootStrapperInhibitAll=enable
it's string block check and download updates, if you need to install new version of steam, remove or rename steam.cfg, after update return file back
also you can try launch steam with parameters to block updates:
"steam.exe" -inhibitbootstrap 
or
"steam.exe" -nobootstrapperupdate

**Comment by Zymlex** [comment]
The problem is that steam perceives a forced launch in the sandbox as damage.
Create a shortcut via sendman on exe.

**Comment by DemDanV** [comment]
I encountered the same issue. Using "steam.exe -inhibitbootstrap" worked for quite some time, but it stopped working recently. However, I found a solution that works for me!

You can check the details of the solution in this [Reddit post](https://www.reddit.com/r/DotA2/comments/1pko71/comment/cd3a49k/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

In short, I created a new environment, and Steam updated successfully. I hope this helps!
