### ISSUE TITLE
Alternating coloring for list views

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2073]
### Is your feature request related to a problem or use case?

No, not really, it is just easier to follow the row, when reading the information in the columns.

### Describe the solution you'd like

Like when clicking on an entry it gets highlighted.

One line starts with no color or gradient of a shade, the next line starts with the opposite, alternating all the way down.

**Comment by DavidXanatos** [comment]
you mean like this:
![grafik](https://user-images.githubusercontent.com/3890945/181628013-a6eea83f-64af-44e6-b645-9d8f6a660a05.png)

**Comment by bastik-1001** [comment]
Yes, I was talking about what you meant, including that I wanted it to work in dark mode.

I switched to dark mode for testing, then stuck with it.

**Comment by DavidXanatos** [comment]
all done
![grafik](https://user-images.githubusercontent.com/3890945/181792812-40b3f31e-4ee4-4fd5-92bb-a28c16b872f6.png)

**Comment by bastik-1001** [comment]
Thank you. That looks nice.

**Comment by DavidXanatos** [comment]
did you just sent a paypal donation on that gmail email of mine? that paypal account does not work since years, you need to ask for it back and use the one linked on the homepage

**Comment by bastik-1001** [comment]
Yes I did. I tried using the icon, but that just directs me to the main page of paypal. Even after logging in and clicking it again, there is no way to send you money.

**Comment by DavidXanatos** [comment]
ok than we have a mess :/

**Comment by bastik-1001** [comment]
This might not be the right place to chat about it, but I reclaimed my money. Sorry for any inconvenience it caused for you.

Does the link on the website work for you? For me there is no username or e-mail. Previously I had assumed, the gmail would be the one to use, since I could send money that way.

**Comment by DavidXanatos** [comment]
For me the link works fine on the first page it asks for the amount then you select paypal click nect and then it asks for paypal.
you can email me on my gmaila ddress and I'll send you the working pp acc if you preffer that

**Comment by bastik-1001** [comment]
This was not related to this ticket, at all. I wanted to send the money, anyway, which should have worked, now that I changed my browser settings. Sorry again for the trouble that caused.
