### ISSUE TITLE
SBIE2335 Initialization failed for IBM Security Rapport

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2079]
_Originally posted by @BilleBarrett in https://github.com/sandboxie-plus/Sandboxie/discussions/2057#discussioncomment-3286805_

I have an extension  from IBM Security Rapport
Size: < 1 MBSize< 1 MBVersion: 2 . 2 . 1 2 7Version2.2.127
The client has to have it to do his banking with a certain Bank
`PID 18608: SBIE2335 Initialization failed for process RapportHelper.exe [33 / 0]`
How or where do I resolve this issue it happens in Chrome and Microsft Edge
Thanks  BilleBarrett

> Affected version: Sandboxie Plus v1.2.6
> 
> * Download link of IBM Security Rapport extension: 
> https://chrome.google.com/webstore/detail/ibm-security-rapport/bbjllphbppobebmjpjcijfbakobcheof
> * (Only if needed) Link to request a demo version of IBM Security Trusteer Rapport client:
> https://www.ibm.com/id-en/products/phishing-and-malware-protection

**Comment by BilleBarrett** [comment]
Thanks he had the Windows version I uninstalled it and added the chrome extension
Bill

 


End Point Detection & Response System
Remote Desktop Services
517 Miltwood Dr,  Greensboro, NC 27455-2709
(336) 988-0891    ***@***.***> ***@***.*** 
To subscribe to my FYI emails send an email to
 ***@***.***> ***@***.***
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’




 

From: isaak654 ***@***.***> 
Sent: Saturday, July 30, 2022 9:24 AM
To: sandboxie-plus/Sandboxie ***@***.***>
Cc: BilleBarrett ***@***.***>; Mention ***@***.***>
Subject: [sandboxie-plus/Sandboxie] SBIE2335 Initialization failed for IBM Security Rapport (Issue #2079)

 

Originally posted by @BilleBarrett <https://github.com/BilleBarrett>  in #2057 (comment) <https://github.com/sandboxie-plus/Sandboxie/discussions/2057#discussioncomment-3286805> 

I have an extension from IBM Security Rapport
Size: < 1 MBSize< 1 MBVersion: 2 . 2 . 1 2 7Version2.2.127
The client has to have it to do his banking with a certain Bank
PID 18608: SBIE2335 Initialization failed for process RapportHelper.exe [33 / 0]
How or where do I resolve this issue it happens in Chrome and Microsft Edge
Thanks BilleBarrett

Download link (version 2.2.127):
https://chrome.google.com/webstore/detail/ibm-security-rapport/bbjllphbppobebmjpjcijfbakobcheof

**Comment by isaak654** [comment]
> Thanks he had the Windows version I uninstalled it and added the chrome extension

Good to know it was useful for him.
