### ISSUE TITLE
Sandboxie doesn't upgrade properly from 5.44.1 to 5.45.0

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#208]
I just upgraded from 5.44.1 to 5.45.0.

When trying to start Sandboxie Control, this happens:
![sandboxie control](https://user-images.githubusercontent.com/12411527/101386709-d6e15c80-38bd-11eb-8a93-5ee4726b4cda.png)

So I checked the folder where Sandboxie is installed:
![sbiedrv sys](https://user-images.githubusercontent.com/12411527/101387061-3e97a780-38be-11eb-9582-03b924370fdc.png)
I checked every single file.
**SbieDrv.sys** is the only file that's stuck at "Version 5.44.1.0"
All other files were successfully upgraded.

**Comment by DavidXanatos** [comment]
In that case please do a clean install, if you keep the C:\Windows\Syndboxie.ini no settings will be lost.

**Comment by NewKidOnTheBlock** [comment]
### How to upgrade successfully:
1. Install 5.45.0
2. Select Upgrade/Overwrite
3. Reboot
4. Go to Sandboxie install folder
5. Rename or delete the outdated `SbieDrv.sys`
6. Rename `SbieDrv.sys.w10` to `SbieDrv.sys`
7. Reboot

Profit.

**Comment by DavidXanatos** [comment]
Step 5. should be done by the SbieSvc.exe automatically when no *.sys file is found, but doing it by hand wont hurt.

**Comment by Gravityzwell** [comment]
Works for me via SandboxieInstall64-v5.45.0.exe same as it has before, replacing driver automatically. Great work!

**Comment by DavidXanatos** [comment]
With build 0.5.1 I have moved to inno setup hence 
1. you will need to clean install
2. in future we should have less issues, maybe.
