### ISSUE TITLE
Can the Sandboxie wiki point to the Sandboxie documentation?

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2082]
### Is your feature request related to a problem or use case?

Currently, the wiki link (https://github.com/sandboxie-plus/Sandboxie/wiki) on Sandboxie's github page links back to the main page, (https://github.com/sandboxie-plus/Sandboxie) could it link to [https://sandboxie-plus.github.io/sandboxie-docs/](https://sandboxie-plus.github.io/sandboxie-docs/)?

### Describe the solution you'd like

The wiki linking to some resource that is helpful to users, if that can be done, easily.

**Comment by isaak654** [comment]
I cannot change the wiki link directly, with my permissions I could only create a new wiki page with a link to https://sandboxie-plus.github.io/sandboxie-docs

The alternative is asking @DavidXanatos to hide the button directly from the repository settings.

**Comment by isaak654** [comment]
I cannot change the wiki link directly, with my permissions I could create a new wiki page with a link to https://sandboxie-plus.github.io/sandboxie-docs

The alternative is asking @DavidXanatos to hide the button directly from the repository settings.

**Comment by DavidXanatos** [comment]
i have hidden it it does not seam to be possible to redirect it

**Comment by isaak654** [comment]
> i have hidden it it does not seam to be possible to redirect it

You may want to do that in the [sandboxie-docs](https://github.com/sandboxie-plus/sandboxie-docs/) repository too.

**Comment by bastik-1001** [comment]
It was just an idea to have something where users might click to get some information, to be redirected to something they may find helpful. Hiding it, is helpful in the sense that there is no confusion.

I intended to close this with my reply, but as isaak pointed out that it applies to docs as well, I don't close it, so it will not be missed. For me this issue, can be closed, otherwise.

**Comment by bastik-1001** [comment]
This ticket does not have a purpose for this repository, so I close it.
