### ISSUE TITLE
Rewrite critical parts in Rust when they are touched

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2083]
### Is your feature request related to a problem or use case?

Currently, the core components are written in C, where compilers do not care about some safety issues, whereas they are taken care of when compiling Rust. 

Since C code can call Rust code and Rust code can call C code, you may replace critical functions and components with Rust code, if you are rewriting/reworking them anyway.

Currently, there might be code that can leak memory or have a dangling pointer, or there are data races, that can be prevented by using Rust, without impacting performance.

### Describe the solution you'd like

This is a more long term goal, of the underlying language guarding against certain issues. (The same way ARM support is a long term goal.)

Writing code in Rust when new functions get added. Writing code in Rust when they are rewritten or reworked. Rewriting code in Rust where you know the original code might be prone to memory leaks or data races.

**Comment by DavidXanatos** [comment]
Trying to reduce bugs by attempting to invent a fool proof programming language is not something I appreciate. Rust is cumbersome to use and it is not really object oriented.
So no, just NO.

**Comment by DavidXanatos** [comment]
I am aware of that, but MSFT has more money then god so they can afford to redo something that already works.

**Comment by bastik-1001** [comment]
I did not comment on this after this issue was closed, since it was just a suggestion that was made unbeknownst the level of acceptance to write code in Rust; and after it was closed it was clear that it wasn't considered to be an option.

Now, even if Microsoft is using Rust, that does not change much, if others don't want to write code in it.

As I don't write code myself, and can't read those languages properly, I have no merit to assess the practicality of writing in Rust compared to C.

**Comment by isaak654** [comment]
> Now, even if Microsoft is using Rust, that does not change much, if others don't want to write code in it.

I'm confident that others can be inspired by topics like this.

**Comment by DavidXanatos** [comment]
Well as it currently stands Visual Studio does not support Rust (not even the newest 2022), only this dumbed down Visual Studio Code does (which does not share anything but the name with the real proper Visual Studio).
So rewriting parts would end up in re writing an entire module, like the entire driver. Trying to re write the SbieDll or SbieSvc or a part of it would be highly impractical as anything rust could not be debugged in Visual Studio and I have no idea to what extent if at all Visual Studio Code could handle a mixed C/Rust project.
That said for the driver this may be not completely out of question, but it would be a huge amount of work as it would mean to re do the entire driver not just a part of it.

**Comment by bastik-1001** [comment]
> Well as it currently stands Visual Studio does not support Rust (not even the newest 2022), only this dumbed down Visual Studio Code does (which does not share anything but the name with the real proper Visual Studio).

Interesting naming choice if it does not share anything with it.

> That said for the driver this may be not completely out of question, but it would be a huge amount of work as it would mean to re do the entire driver not just a part of it.

I see. While my original suggestion included the idea of mixing C and Rust, I guessed that for something like the driver this wasn't an option.
