### ISSUE TITLE
SandMan/Plus Version Crashes on Content Delete

### ISSUE THREAD

**Issue by zenforic** [sandboxie-plus/Sandboxie#209]
When deleting a Sandbox's content in the current version using the SandMan UI, both automatically and manually, the UI will show it is deleting content and then promptly crash. Let me know if you need any more details. It also does not delete the content.

**Comment by DavidXanatos** [comment]
mmh... strange for me it works try with an other sandbox, if that issue happens only for one particular sandbox we will need to investigate what strange edge case is causing the issue

**Comment by DavidXanatos** [comment]
more edit, i have found a related issue, where closing the progress dialog with the close button crashes it.
May be you just need to wait longer for the deletion to finish.
please let me know if that's the case

**Comment by zenforic** [comment]
Alright, I will do more but for now here is more info on things I've tried for now based in what you've said and other factors:

- Uninstalled, reinstalled, and cleared the Sandbox folder out (Restarted as well)
- I have technically only used one Sandbox, it was a renamed and reconfigured version of the DefaultBox (Which I had tried deleting and reconfiguring before, but still only one box). I will create another box and try as you suggested.
- The particular case you mentioned in your last comment was not the case for me, I did not close it and sometimes I even leave it in the background (systray) when it auto deletes.
- In the background case sometimes it doesn't seem to do anything and when I go to delete nothing (not even the dialog or crash happens) until I restart the program or wait a while.

If you would also like one of the many memory dumps it's produced after rashing, let me know if that would help.

Thanks.

**Comment by zenforic** [comment]
Update: I have tried manual content deletion on a brand new box, default configuration; still crashes, not sure what's going on but definitely if it's working for you, it must be something odd on my end causing some edge case.

**Comment by DavidXanatos** [comment]
I have found a possible issue please try the attached files and tel me if that solves the issue for you.

[SbiePlus-v0.5.1a.zip](https://github.com/sandboxie-plus/Sandboxie/files/5661391/SbiePlus-v0.5.1a.zip)

**Comment by zenforic** [comment]
The files you provided fixed the issue, thank you!

**Comment by zenforic** [comment]
Update: I seem to have found another issue, unrelated but happened by it. If you would like this in another issue I'd be happy to make one, but I'll detail it here as well:

Disabling forced programs via systray while the program (SandMan) is backgrounded seems to close it after setting the time (doesn't dump memory this time). Disabling forced programs works completely fine when done from the UI in the sandbox menu however.

**Comment by DavidXanatos** [comment]
ah I see.
Will fix that asap, although I think I'll go the cheep route and just don't prompt for time.
The legacy UI also does not ask for time from the tray only from the window menu.

**Comment by zenforic** [comment]
Thanks, sounds alright to me, much appreciated!
