### ISSUE TITLE
[Plus 1.3] Option to disable driver protection on a/all sandbox container(s) to run (Unsandboxed) files without having to recover/move them out and related issues

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2094]
### Is your feature request related to a problem or use case?

In the past this feature was part of disable_force.

Related issues
Breakout if configured for box1 where i want to run files that are still inside the sandbox container would not work even if there is a box2 configured to capture the process ; the process that should breakout is still sandboxed as box1 if i run (double clicking) from unsandboxed explorer.

Also if i use run sandboxed context menu to try to run in a different box when breakout is configured it will run unsandboxed and forceprocess from box2 will still not capture it (one of the workarounds to run files inside the container unsandboxed, depending on path/filename ; filename containing ` -` [space+dash eg: `Test -.rar` `Test -.zip`] causes errors but not `Test -.jpg` from what i encountered)
If i remove the breakout and do the same it will be forced inside box1 (rip that workaround)
If i use run unsandboxed context menu it will still be forced inside box1 (its working fine with forceprocess/folder outside the container)

Summary
- breakout will not work from unsandboxed explorer , will work if the file is not inside a sandbox container and another box has forceprocess
- run sandboxed/unsandboxed context menu on a file inside a sandbox container will not work correctly as from files outside the container
- the driver is like a possessive girlfriend when it comes to the files inside sandbox containers

Windows 7 Ultimate SP1 x64
Plus 1.2.8 x64

### Describe the solution you'd like

An option that would allow while using unsanboxed explorer to run files that reside in a sandbox container in a different box and/or unsandboxed without having to recover/move them out without relying on workarounds

**Comment by DavidXanatos** [comment]
why have you closed this did you found a good workaround for your usecase?
