### ISSUE TITLE
1.2.8 installer error

### ISSUE THREAD

**Issue by fusionneur** [sandboxie-plus/Sandboxie#2097]
### Describe what you noticed and did

after installer finished i got this error

![image](https://user-images.githubusercontent.com/7840350/183244374-90bff7cc-7ade-47b6-9465-9faaa44c442a.png)

>  This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. Available platform plugins are: minimal, windows, direct2d, offscreen.

### Affected program

-

### Download link

-

### Where is the program located?

Not relevant to my request.

### Expected behavior

installer ok

### What is your Windows edition and version?

Win 11

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

-

### What version of Sandboxie are you running?

1.2.8

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
Please use [this](https://support.malwarebytes.com/hc/en-us/articles/360039025013-Run-Farbar-Recovery-Scan-Tool-to-gather-logs) tool to produce a troubleshooting log and attach it here.

**Comment by DavidXanatos** [comment]
Is this the first Sbie plus install you have tried?

**Comment by isaak654** [comment]
Someone in the [Microsoft community](https://answers.microsoft.com/en-us/windows/forum/all/this-application-failed-to-start-because-no-qt/e5b31106-84a1-4196-92f3-a1ee633f68b0?page=2) had a similar alert with OneDrive and solved it by uninstalling Logitech G Hub and then reinstalling it. This indicates that a clean installation of Windows could make a difference.

**Comment by isaak654** [comment]
That's good to know, but it doesn't explain the cause, which is evidently limited to your system.
