### ISSUE TITLE
Plus-050 - signed driver not recognized on Win-8.1

### ISSUE THREAD

**Issue by neil-benn253** [sandboxie-plus/Sandboxie#210]
1) Driver being blocked during install. Disabling AV allowed successful install. 
AV never indicated that it was blocking or flagging anything. (AV is Win-Defender - aka MS Security Essentials).
Only an issue on Win-8.1 - no issue on Win-10-20H2

2) As a side-note, old version of Sbie-plus was uninstalled first (043) due to the issue of driver not overwriting successfully via "upgrade" method. 

3) "Upgrade" issue was also present on Win-10-20H2, but no AV issues were encountered, and the AV "exclusion" for earlier SbieDrv.sys was removed prior to 050 install. All good.

![Signed driver on Win-8 1](https://user-images.githubusercontent.com/71922774/101467221-26935700-3996-11eb-85f3-a47a48b37e84.jpg)

**Comment by DavidXanatos** [comment]
Than please use the "for windows 7" version

**Comment by DavidXanatos** [comment]
I have tested it on a 8.1 VM again and strangely enough it complains once but other than that the driver loads fine and is there even after a reboot working as it should

**Comment by neil-benn253** [comment]
Yes it's working OK, it was just the initial install that was blocked. Thanks.
