### ISSUE TITLE
Sandboxie can't run the 'UWP' application on windows

### ISSUE THREAD

**Issue by sandyz987** [sandboxie-plus/Sandboxie#2105]
### Is your feature request related to a problem or use case?

Sandboxie can't run the 'UWP' application on windows. When i try to open one, it show me that 'it isn't a valid win32 program'

### Describe the solution you'd like

will you support this feature?

**Comment by isaak654** [comment]
Duplicate of #19

**Comment by DavidXanatos** [comment]
since this duplicate does not add anything I'll close it now
