### ISSUE TITLE
Fails to open Windows Explorer from Sandboxie app (since build 25136.1000)

### ISSUE THREAD

**Issue by ojo11** [sandboxie-plus/Sandboxie#2109]
### Describe what you noticed and did

Schedule 25174 build.
Install the application.
Launch the application.
Give Keyboard input alt + b + 1 + r + w
Observe.

Actual Results | App failed to open explorer.exe

Expected Results | Application should be able to work without any issues.

### How often did you encounter it so far?

100% repro

### Affected program

Windows Explorer

### Download link

Not available

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Application should be able to work without any issues.

### What is your Windows edition and version?

Windows 11 25174

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Security

### What version of Sandboxie are you running?

5.57.7

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
Which application is accepting that keyboard input?

**Comment by ojo11** [comment]
Hello Isaak We are using keyboard for shortcut to reproduce the issue.

Below are two ways we can reproduce this bug:

1.	Install the application from dumps.
2.	Launch the application.
3.	Give Keyboard input alt + b + 1 + r + w
4.	Observe
(Or)
1.	Install the Sandboxie application from vendor site
2.	Launch Sandboxie control
3.	Goto Sandbox option -> DefaultBox -> Run Sandboxed -> Run Windows Explorer
4.	Observe

**Comment by ojo11** [comment]
![Fails to open Windows Explorer from Sandboxie app (Issue #2109)](https://user-images.githubusercontent.com/98554165/184024518-d1c33982-fd99-47f4-a4fa-649a676cb8a9.png)

**Comment by isaak654** [comment]
I was unable to reproduce the steps from 5 to 8 on the latest v5.57.7, could you share your Sandboxie.ini configuration file?

**Comment by isaak654** [comment]
The weird thing is that it doesn't happen on the current Win 11 RTM 21H2 (except the opening delay in #1127), while on Win 10 it works fine.

**Comment by ojo11** [comment]
do you need anything else from us?

**Comment by isaak654** [comment]
Any help that could lead to a fix in this repository would be appreciated.

**Comment by isaak654** [comment]
Any help that could lead to a fix would be appreciated.

**Comment by ojo11** [comment]
Hello Isaak - We would love to schedule a call to discuss this issue and how best to help. What is your availability?

Than you,
Oscar

**Comment by ojo11** [comment]
Would you be open to using the Teams platform during PST | UTC−08:00?

**Comment by isaak654** [comment]
I tried to send you the invite link to your email, but I received this in return:
![delivery_failed](https://user-images.githubusercontent.com/12372772/190216293-a23e1b77-b10f-4615-a79a-a2b24d841bbd.png)

**Comment by ojo11** [comment]
and that email was v-osorti@microsoft.com? perhaps you can also try oscar.ortiz@axelerate.com

**Comment by isaak654** [comment]
Just added, now you can delete your post.

**Comment by ojo11** [comment]
I joined, but how can we schedule a call with you an our engineers?

**Comment by isaak654** [comment]
I wrote you a Slack message with the invite link to share with your colleagues.

**Comment by ojo11** [comment]
Hello, we are new to slack. Can you propose the time for our engineers and your team to meet?

**Comment by isaak654** [comment]
How about tomorrow at 18:30 CEST?

**Comment by ojo11** [comment]
Yes, that works for some team members. Will we get this invite via Slack?

**Comment by isaak654** [comment]
I set up the conversation group well in advance, so there should be no notification issues.

**Comment by isaak654** [comment]
I set up the conversation group well in advance, so there should be no notification issues.
In case you have newcomers to invite or more questions, please send me a private message on Slack.

**Comment by isaak654** [comment]
I set up the conversation group well in advance, so there should be no notification issues.
In case you have newcomers to invite, you can add them to the conversation anytime or send me a DM on Slack.

**Comment by isaak654** [comment]
![Slack](https://user-images.githubusercontent.com/12372772/190717440-473fcb3d-bb79-4eac-b71c-0c45ed5b531e.png)

**Comment by DavidXanatos** [comment]
I have investigated the win UI issues a bit and it seams that it is enough not to rename a couple of window classes namely:
NoRenameWinClass=Windows.UI.Composition.DesktopWindowContentBridge
NoRenameWinClass=Windows.UI.Core.CoreWindow
NoRenameWinClass=Windows.UI.Input.InputSite.WindowClass

Unfortunately NoRenameWinClass does as of 1.3.3 not support wildcards such that NoRenameWinClass=Windows.UI.* would do the trick,
I'll add wildcard support to the next build, probably 1.3.4 and add the required value in one of the default templates.

about the instructions from the first post "Give Keyboard input alt + b + 1 + r + w"
when i do that nothing seams to be happening, nieder in a sandboxed nor in a unsandboxed explorer,
i also tried switching the system language to english, what is supposed to happen?

**Comment by DavidXanatos** [comment]
please test build 1.3.4 https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.3.4

**Comment by ojo11** [comment]
Thank you! I've shared it with the team.

**Comment by isaak654** [comment]
While this issue is fixed, there is a new one between the hardened sandboxes and Windows 11 22H2 RTM:  https://github.com/sandboxie-plus/Sandboxie/issues/2341
