### ISSUE TITLE
create service fail [Error code: 2] when run SandMan.sln 

### ISSUE THREAD

**Issue by WhianGaulin** [sandboxie-plus/Sandboxie#211]
when I run the SandMan.sln ., it compile successfully, but meet the error in running
the program want to create a service but failed and told me [Error code : 2]
the next time I compile and run it told me wrong [ Fail to connect the driver] 
what should I do?  
My visual studio version is 2019 and My Qt version is 5.12.10
Thank you very Much!

**Comment by WhianGaulin** [comment]
Also when I try to create a new box, the program is no response and then crash

**Comment by DavidXanatos** [comment]
You need to create the service and driver entries, you can do that using he maintenance menu in the sandman UI.

**Comment by WhianGaulin** [comment]
> You need to create the service and driver entries, you can do that using he maintenance menu in the sandman UI.

Thank you but it seems doesn't work.  Did you mean Sandbox-> Maintenance ->Advanced-> Install driver && Install Service? 
I clicked them but it has no reply , and I reconnect and failed

**Comment by DavidXanatos** [comment]
Do you have the kmdutill.exe in the same folder as sandman.exe? its required for these operations.

**Comment by WhianGaulin** [comment]
No I don't have

**Comment by DavidXanatos** [comment]
> 
> 
> No I don't have

thats the problem all the maintenance operations are done by callign that tool with the apropriate parameters.

**Comment by WhianGaulin** [comment]
> > No I don't have
> 
> thats the problem all the maintenance operations are done by callign that tool with the apropriate parameters.

Thank you very much 
I only compile sandMan.sln in sandboxiePlus , should I compile other sln or project in sandBoxie

**Comment by DavidXanatos** [comment]
yes
