### ISSUE TITLE
[Plus 1.3] Sbieview reflects settings from Global settings and assigned templates not just per box settings

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2111]
### Is your feature request related to a problem or use case?

In 1.2.8 the feature was still present

-It allows users to create and use their own custom type presets without a visual drawback or easily keep track of each box current config in the use of case of using templates as toggles
And looks good on sandman's run dialog ∠( ᐛ 」∠)＿ even if i don't use default presets/have the setting added to the box

### Describe the solution you'd like

Box type/Icon and status column will accurately display even if a template or global settings contains for example NoSecurityIsolation=y will show as app compartment box instead of standard isolation default box

### Describe alternatives you've considered

Nada the sea of yellow is fine too

**Comment by DavidXanatos** [comment]
what do you mean? are you saying that for you all boxes no mater what type are now yellow?
then you perhaps enabled  Options/ColorBoxIcons=true in your sandboxie-plus.ini
![grafik](https://user-images.githubusercontent.com/3890945/183766428-3efb081f-be0c-4b29-bffa-d6d7208aecad.png)

if so then the icon is rendered to match the box color selected for the box and the default box color is yellow.

**Comment by RandomGOTI** [comment]
ColorBoxIcons is not used, for example what i am reffering to , 1.2.8 and 1.3 before and after update

![128](https://user-images.githubusercontent.com/19516333/183770390-edc52c4c-9f25-4750-a19e-d1b9606ad565.png)
![13](https://user-images.githubusercontent.com/19516333/183770395-3f59dd55-ef86-42bd-9abf-cad4ecf75231.png)
1st box has a template that contains UsePrivacyMode=y
2nd box has a template that contains NoSecurityIsolation=y
3rd box has a template that contains DropAdminRights=y UsePrivacyMode=y

**Comment by DavidXanatos** [comment]
hmm... very strange for me this works just fine

![grafik](https://user-images.githubusercontent.com/3890945/183830893-b27f8864-7995-4b14-8a3e-bbbc1ca8fdb2.png)

Also notice that the status column in your case does not indicate that this settings are set,
please check your sandboxie ini and or post it here, there seams to be something wrong.

**Comment by RandomGOTI** [comment]
https://user-images.githubusercontent.com/19516333/183856533-0cfdadff-0e1c-4e94-8cbf-9601c445af41.mp4

<details>

<summary>Sandboxie.ini used</summary>

```
#
# Sandboxie-Plus configuration file
#


[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%

[New]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
BorderColor=#02f6f6,ttl
ConfigLevel=9
Template=Local_ench

[Box]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
BorderColor=#02f6f6,ttl
ConfigLevel=9
Template=Local_priv

[LOL]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
BorderColor=#02f6f6,ttl
ConfigLevel=9
Template=Local_Appcompat

[Template_Local_Appcompat]
Tmpl.Title=Appcompat
Tmpl.Class=Local
NoSecurityIsolation=y

[Template_Local_priv]
Tmpl.Title=priv
Tmpl.Class=Local
UsePrivacyMode=y

[Template_Local_ench]
Tmpl.Title=ench
Tmpl.Class=Local
DropAdminRights=y
UsePrivacyMode=y
```
</details>

plus ini defaults

**Comment by DavidXanatos** [comment]
ok i see the problem you have put the parameters into a local template
and the current code does nto evaluate templates

**Comment by RandomGOTI** [comment]
Not present on 1.3.1
