### ISSUE TITLE
Maintenance functions do not work for "portable" Sandboxie-plus x64 0.5.0 with classical Sandboxie installation 

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#212]
Use portable extraction of Sandboxie-plus x64 and copy files into the installation folder of classic Sandboxie. Sandman can be started as expected and connects/disconnect works. However none of the maintenance functions works, either hanging on the pop-up window or crashes after a while. The functions work as expected with installed Sandboxie-plus.

Sandboxie-plus x86 not tried.

PS: can't get Kmdutil.exe to install SbieDrv.sys manually with 5.45.0, was still OK with 5.44.1

**Comment by DavidXanatos** [comment]
what command are you using with Kmdutil.exe?

**Comment by superkryodev** [comment]
> what command are you using with Kmdutil.exe?

KmdUtil.exe install SbieDrv "SbieDrv.sys" type=kernel start=demand "msgfile=SbieMsg.dll" altitude=86900

SbieDrv.sys from the updated 5.45.0 release without .w10/.rc4 suffix, SbieDrv.sys.rc4 for older versions
