### ISSUE TITLE
Can Sandboxie's plus configuration protection by admins be done with UAC?

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2123]
### Is your feature request related to a problem or use case?

When using Sandboxie-Plus and setting "Config Protection" > "Only Administrator user accounts can make changes." with a normal user account, Sandboxie denies any changes. (The funny thing is, that a normal non-admin user, can set the setting, but is then prevented from doing any changes.)

### Describe the solution you'd like

Now the question is, if Sandboxie-Plus, sandman, could, instead of preventing the changes, show a UAC prompt for a user to enter admin credentials to apply changes?

The same question can be asked for the setting that restricts disabling forced processes to admin accounts.

If those can be done in a way that a normal non-admin user runs sandman, has those settings set and gets prompted by UAC, when changing the config or disabling forced processes, then this is a feature request to do so.

### Describe alternatives you've considered

Sticking to what we have now.

**Comment by DavidXanatos** [comment]
After thinking about that and looking in how veracrypt handles UAC using COM I think the most reasonable course of action would be to let sandman detect that being admin is required and then offer an option to restart itself as admin.

**Comment by DavidXanatos** [comment]
Easier fix, i will just disallow non admin users from changing this setting in the UI

**Comment by bastik-1001** [comment]
Disallowing non admin users from setting these options sounds good, as it prevents the funny part.

Can you add a menu entry to restart Sandman.exe with admin rights? In the 'Sandbox' menu, of sandman for example  "Restart Interface as admin", or in the options menu of sandman. If you want, I can open another issue for that, this is just remotely related.

**Comment by isaak654** [comment]
> Easier fix, i will just disallow non admin users from changing this setting in the UI

This was added in [v1.3.3](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.3.3).
