### ISSUE TITLE
[SBIE1409] [SBIE1402] can't find file Templates.ini and Sandboxie Ini  

### ISSUE THREAD

**Issue by WhianGaulin** [sandboxie-plus/Sandboxie#213]
I have build the solution SandboxiePlus.sln, SandboxDrv.sln, Sandbox.sln and qtsingleapp.sln
and I copied files in \Sandboxie\Bin\x64\SbieRelease to \SandboxiePlus\x64\Release

but when I open the Sbiectrl.exe, it output the messages SBIE1409 and SBIE1402, and actually the /Realase folder doesn't have templates.ini and sandboxie.ini 
Did I miss some steps? what should I do? Thank you very much!

**Comment by WhianGaulin** [comment]
I have found the templates.ini in the /install folder and sandboxie.ini in C:/windows/ folder, but still wrong
Nt Status Codes are C0000034 Object not found

**Comment by DavidXanatos** [comment]
try fully uninstalling and reainstallign sandboxie
