### ISSUE TITLE
Plus UI: Add search function to box settings

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2134]
### Is your feature request related to a problem or use case?

I am not entirely sure if classic users are not considering switching to the plus UI for not finding the settings in the newer version due to being used to the old structure.

You already implemented a tree-view, which looks similar to the classic UI, but users may still not want to switch, as they still have to try and find the setting, they used to find elsewhere.

### Describe the solution you'd like

Having a search bar in the sandbox's preference window, maybe even for the main preferences of Sandman, that either filters the tree for the term that is being entered or cycles through whatever page the term is found on.

I am not sure if that would have to be limited to the tree view or if that applies to the layout that the plus UI featured.

I have no idea if searches will be localized or if users would need to type the English terms, but those should be the majority and documentation is English anyway.

### Describe alternatives you've considered

This is more of a suggestion, since that is not a feature I need, so it could remain as it is. However, it may make it easier for users to switch from the classic UI to the plus UI. It may also be good for new users as they could find the plus UI to overwhelm them or thy simply overlook what they wanted to set.

**Comment by bastik-1001** [comment]
Some UIs have two different sets of options.

1) The basic settings view (showing only some options)
2) The advanced settings view (showing all the options)

That might be something to be considered, but I don't want to open another issue for it. It might not be helpful in making it easier for users either. It also could be bad for support requests where users needing to be asked, what options they can see (what setting view they use) or getting them to enable or disable an option the need to switch the view for.

Generally I avoid using basic setting view and try to use the advanced settings (or expert mode, whatever it is called), to see what I could change. The average user might feel different about that.

**Comment by DavidXanatos** [comment]
hmm... a search box in the settings, its not that simple as it may sound, but would be doable, the users would need to type the localized text as displayed in the UI not the english original.
Upon pressing return/enter the UI woudl autoamtically jump to the next widget containing the searched for text, and the next and then next and then cycle back to toe top.
When the tree view is enabled we coudl indeed also hide the irrelevant tree paths.

About a basic settings view, sure why not, the only problem is what options should we hide from the basic view?
if anyone can generate a comprehensive list of what to hide I can easily add it.
You can just make screenshots of the option option pages and strike out with a red line using mspaint everything that should go away.

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/184610204-fcd075ff-e8b4-40e8-a314-259b44fc9776.png)

**Comment by DavidXanatos** [comment]
do we need this also for the tabbed view?

I was thinking about what options could be hidden but it seams to me as there are not that many
we could hide stuff from the  "General Options" and obviously from the "Advanced Options" and the edit ini section tab entirely. But it looks to me as all the rest would have to stay.

what do you think?

**Comment by DavidXanatos** [comment]
PS: anyone willing to pick some icons for the sub entries from the [icons8.de](https://icons8.de/) the windows 11 (fluency) collection?

**Comment by DavidXanatos** [comment]
If you are not in the tree view mode in the options dialog, you can press Ctrl+F to switch to the tree mode with the search.

**Comment by bastik-1001** [comment]
Looks good to me.

> do we need this also for the tabbed view? (...) If you are not in the tree view mode in the options dialog, you can press Ctrl+F to switch to the tree mode with the search.

I am not sure. Does the interface return to the tabbed view, after pressing Ctrl+F, searching for something, then closing and re-open it? If that is the case, it shouldn't be needed. Maybe there can be a string in the settings window, on the left-hand side of the OK button, telling users to press Ctrl+F to search for an option. So users get to discover this function without having to switch to the tree-view.

> I was thinking about what options could be hidden but it seams to me as there are not that many
we could hide stuff from the "General Options" and obviously from the "Advanced Options" and the edit ini section tab entirely. But it looks to me as all the rest would have to stay.

It was just an alternative idea to appeal to users that might be overwhelmed in finding options they are looking for. Now that they can be searched, it should be easier. There are not that many options that seem to get hidden anyway, maybe the advanced section (although it is already separated and users don't need to go there) and those that are not recommended to tinker with, would not been seen in the basic view. Probably not worth it, from my point of view, but you may want to consider someone else's input on that matter. Those that feel overwhelmed by the option the new UI provides.

**Comment by bastik-1001** [comment]
> PS: anyone willing to pick some icons for the sub entries from the icons8.de the windows 11 (fluency) collection?

I am not good at visual UI stuff, I looked through some of them, but did not see something that is not misleading or almost the same as what the main categories have.

**Comment by DavidXanatos** [comment]
i added the search also to the normal view
![grafik](https://user-images.githubusercontent.com/3890945/184684098-dd4b3d31-71e2-45bd-a73b-1dd3cc0b2c03.png)
doe snot look super nice tehre though, but better then switching

**Comment by bastik-1001** [comment]
There might be people that disagree, but if it works it does not have to be pretty. I am not looking at the setting all the time and I guess most users would not do so either.

There is a spelling mistake in the 10th entry "toke" instead of "token".

**Comment by DavidXanatos** [comment]
> There is a spelling mistake in the 10th entry "toke" instead of "token".
>

that does not mater the debug options you see here are loaded from the plus ini so you are free to call then what you want, if you add the following to your plus ini you will get the Debug tab with these options

```
[DebugOptions]
Option01=OriginalToken|y|Keep the original unrestricted tocken
Option02=CreateToken|y|Create a new token
Option03=ReplicateToken|y|Replicate token from original
Option04=OpenToken|x|Use a unrestricted and unfiltered token dupliate
Option05=UnrestrictedToken|y|-Don't restrict the sandboxed toke
Option06=KeepTokenIntegrity|y|--Keep token integrity level
Option07=UnstrippedToken|y|--Don't strip the sandboxed toke
Option08=KeepUserGroup|y|---Keep user group
Option09=AnonymousLogon|n|--Don't set the anonymouse SID
Option10=UnfilteredToken|y|-Don't filter the original token
Option11=NoSysCallHooks|y|Don't hook system calls
Option12=NoSandboxieDesktop|y|Don't proxy desktop operations
Option13=NoSandboxieConsole|y|Don't proxy console creation
Option14=DisableComProxy|y|Don't proxy COM operations
Option15=DisableBoxedWinSxS|y|Disable Boxed WinSxS
Option16=NoSecurityFiltering|x|Disable Filtering
Option17=DisableFileFilter|y|-Disable File Filter
Option18=DisableKeyFilter|y|-Disable Key Filter
Option19=DisableObjectFilter|y|-Disable Object Filter
```

**Comment by bastik-1001** [comment]
Even though I did not intend to use the function, just suggesting something that could be useful for users considering switching, or for new users, I see myself using it, getting to an option faster than clicking through the pages.

You are right, it is not look super nice, but once some options are set there is little reason to review them. Finding them is more important.
