### ISSUE TITLE
Plus UI: checkbox to hide options that require a supporter certificate

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2137]
### Is your feature request related to a problem or use case?

This might be a bad request, but I feel like making it anyway.

My PDF reader has some editing functions, that require the software to be purchased in order to be used. Those functions can be reached via the toolbar and the menu. (Since I don't need those, I use the version that is limited.) Now that software has a checkbox in its settings to hide the elements that are only available in the PRO version. (I use that setting since I have no need for those features and functions anyway..)

### Describe the solution you'd like

Having such a setting for Sandman, so users who have decided that they aren't going to use functions, they need a supporter certificate for, can't complain about seeing options that are not available to them.

### Describe alternatives you've considered

It seems to be the case that Sandboxie is going to mark functions that require a supporter certificate, which should be helpful, and I would understand if you would not want to hide settings. There is not much being "cluttered" by them, either.

**Comment by DavidXanatos** [comment]
> seeing options that are not available to them.
is kind of the point, also these options are imho very useful so everyone should be using them.
