### ISSUE TITLE
CopyLimitKb=-1

### ISSUE THREAD

**Issue by hansnolte** [sandboxie-plus/Sandboxie#214]
Do I have to enter this value in the Sandboxie.ini?
If so, GlobalSettings or Box.

Then do I have to change something here too?
![migration](https://user-images.githubusercontent.com/7922627/101605659-bec72580-3a02-11eb-825f-19694fe694c6.png)

**Comment by DavidXanatos** [comment]
You hae to enter it in the ini,
if you enter it in the global section it will apply to all boxes
if you set it in a particular boy only to that box.
I actually havn't tested how the old UI would handle that, you could tra entering it in the showen screen it may just work

**Comment by hansnolte** [comment]
Hello David,
thank you for your explanation.

Many greetings
Hans
