### ISSUE TITLE
Couldn't update or uninstall Sandboxie

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#2140]
### Describe what you noticed and did

Today I want to update Sandboxie/Sandboxie-Plus, but after I uninstall Sandboxie-Plus, Itry to update Sandboxie, it said: 
![pic](https://user-images.githubusercontent.com/56181919/184560809-d09a80e6-d4b0-4298-a470-fe0ba00becaf.png)
![pic2](https://user-images.githubusercontent.com/56181919/184561033-194fdd3e-9b43-4b51-be5e-fe5321942bc4.png)

My computer have been reboot, but it doens't work. 

### Affected program

N/A

### Download link

N/A

### Where is the program located?

Not relevant to my request.

### Expected behavior

This bug shouldn't appear

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2021 x64 (21H2)

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

ESET Internet Security 15.2.11.0 

### What version of Sandboxie are you running?

Sandboxie 5.57.7/ Sandboxie-Plus 1.2.8b

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Maybe Sandboxie 5.57.7/Sandboxie-Plus 1.2.8b

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by 0x391F** [comment]
My the way ,I couldn't stop one KmdUtil.exe (access denied).

**Comment by 0x391F** [comment]
I tried to use PyARK (ARK tools) to delete Sandboxie's install folder, and deleted register HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieDrv, it still couldn't install, and here're 3 remaining files, then I tried to add 3 files to PyARK's pending delete files (delete files after reboot), and reboot, all files deleted successfully, and Sandboxie/Sandboxie-Plus installed successfully, everything is alright.

**Comment by isaak654** [comment]
> I tried to use PyARK (ARK tools)

Download link?

**Comment by 0x391F** [comment]
> > I tried to use PyARK (ARK tools)
> 
> Download link?

http://pysafe.cn/
https://github.com/antiwar3/py

Note: 
1. It seems only support win7 to win10 (20h1). In my physical PC (Windows 10 Enterprise LTSC 2021 x64 (21H2), it may BSoD, in my virtual machine (LTSC 2019 x64 (1809) ), it seems doens't have any problem). 
2. EIS said C:\Windows\System32\drivers\PYArkSafe.sys, which is createed by PyARK., is Win32/GenCBL.BHZ Trojan's variation, but I not sure if it's false-positive or not.

**Comment by 0x391F** [comment]
The same problem when I try to uninstall Sandboxie 5.58.1/Sandboxie-Plus 1.3.1.

**Comment by 0x391F** [comment]
The same problem when I try to uninstall Sandboxie 5.58.2/Sandboxie-Plus 1.3.2 and Sandboxie 5.58.3/Sandboxie-Plus 1.3.3.

**Comment by 0x391F** [comment]
The same problem when I try to uninstall Sandboxie 5.58.4/Sandboxie-Plus 1.3.4 and Sandboxie 5.58.5/Sandboxie-Plus 1.3.5.

**Comment by DavidXanatos** [comment]
this is strange, other users dont have this issue, try uninstalling fresh after a rebot befor anything hat the chance to run in the sandbox

**Comment by 0x391F** [comment]
This bug seems doesn't reproduced in recent versions.
