### ISSUE TITLE
How to renew a Patreon supporter certificate?

### ISSUE THREAD

**Issue by ximGBu4cyQss5P** [sandboxie-plus/Sandboxie#2144]
### Describe what you noticed and did

I'm a Patreon supporter but my supporter certificate has expired.  I'm probably missing something obvious, but I don't see a way to generate myself a new certificate.  The "get an updated certificate" link in Sandboxie Plus settings just links to the small / medium / large / etc. checkout page.  How do I get a refreshed certificate, and is there any automation for this so that folks supporting continuously through Patreon never have to really know about the expiry / renewal?

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Ideally there's some automation in place that can check to see if license is tied to an active Patreon subscription.

### What is your Windows edition and version?

Windows 10 Pro 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

1.3

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
you can get a new one on https://xanasoft.com/get_cert.php
the update should also be possible automatically, unless you have a very old certificate with out a UPDATEKEY value
you can try downloading the cert manually using https://sandboxie-plus.com/get_cert.php?UpdateKey=[updatekey]
where [updatekey] is the 128 bit hex string from your old cert.

**Comment by ximGBu4cyQss5P** [comment]
Perfect, thanks!  I hadn't found either of those links yet.  I'll close this out.

**Comment by ccchan234** [comment]
hi, i dont understand this:
Get a [Patreon subscription](https://www.patreon.com/DavidXanatos)
Patreon certificates are valid for as long as the subscription is active and unlock all features. Patreons who have ended their subscription are entitled to a residual certificate corresponding to the total amount of their support. See also https://github.com/sandboxie-plus/Sandboxie/issues/2144.

so suppose sponsor thru patreon for 5/10 euro per month; within that period of coz i expect i can use SBP.
when the month i stop sponsoring, i would expect it ends.

but what the above paragraph means? what is a residual certificate corresponding to the total amount of their support?
just a proof or can that cert be used elsewhere?

thanks
