### ISSUE TITLE
[Sandboxie-Plus] Show boxes by groups in context/right-click menu of notification icon

### ISSUE THREAD

**Issue by codewhizz** [sandboxie-plus/Sandboxie#2148]
### Is your feature request related to a problem or use case?

The context/right-click menu of Sandboxie Plus icon in notification area shows all sandboxes list. It's hard to find a box when you are dealing with lots of sandboxes.

### Describe the solution you'd like

The solution can be to show groups instead of all boxes, as created and shown in the main UI. Then it'll be less cumbersome to browse boxes. It'll be a great addition to this beautiful piece of software.

**Comment by RandomGOTI** [comment]
classic tray in a nutshell 👍

**Comment by DavidXanatos** [comment]
ah ofcause how could i forgot to add that will be there in the next build
