### ISSUE TITLE
I have some SBIE messages from Sandboxie

### ISSUE THREAD

**Issue by liuxianyue** [sandboxie-plus/Sandboxie#2149]
### Describe what you noticed and did

![入沙0816警告信息](https://user-images.githubusercontent.com/27951984/185006818-86f1e449-8054-465a-875b-14c0e332d164.png)

```
SBIE2206 Failed processing AutoExec setting -2 [C0000022]
SBIE2326 Cannot prepare registry: [11 / C0000022]
SBIE2309 Could not disable COM+/DCOM: [21 / C0000022]
SBIE2312 Could not enable BrowseNewProcess setting: [77 / C0000001]
```

### Affected program

Not Relevant

### Download link

Not available

### Where is the program located?

Not relevant to my request.

### Expected behavior

no message from  sandboxie

### What is your Windows edition and version?

win7 sp1

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

no 

### What version of Sandboxie are you running?

sandboxie 1.0.22

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a Sandbox with data protection (blue sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
NoSecurityIsolation=y
NoSecurityFiltering=y
DllSkipHook=user32.dll
DllSkipHook=msi.dll
DllSkipHook=gdi32full.dll
DllSkipHook=gdi32.dll
DllSkipHook=sxs.dll
DllSkipHook=shell32.dll
DllSkipHook=shcore.dll
DllSkipHook=userenv.dll
DllSkipHook=MsCorEE.dll
DllSkipHook=ntmarta.dll
DllSkipHook=ComDlg32.dll
DllSkipHook=acscmonitor.dll
DllSkipHook=winnsi.dll
DllSkipHook=Pdh.dll
DllSkipHook=sysfer.dll
DllSkipHook=emet.dll
DllSkipHook=snxhk64.dll
DllSkipHook=snxhk.dll
DllSkipHook=IDMIECC.dll
DllSkipHook=MsgPlusLive.dll
DllSkipHook=agcore.dll
DllSkipHook=advpack.dll
DllSkipHook=mso.dll
DllSkipHook=dwrite.dll
DllSkipHook=osppc.dll
DllSkipHook=winspool.drv
DllSkipHook=wevtapi.dll
DllSkipHook=winsta.dll
DllSkipHook=wtsapi32.dll
DllSkipHook=sfc_os.dll
DllSkipHook=d3d9.dll
DllSkipHook=imm32.dll
DllSkipHook=uxtheme.dll
DllSkipHook=zipfldr.dll
DllSkipHook=cfgmgr32.dll
DllSkipHook=setupapi.dll
DllSkipHook=sspicli.dll
DllSkipHook=pstorec.dll
DllSkipHook=wkscli.dll
DllSkipHook=netapi32.dll
DllSkipHook=iphlpapi.dll
DllSkipHook=ws2_32.dll
DllSkipHook=hnetcfg.dll
DllSkipHook=crypt32.dll
DllSkipHook=advapi32.dll
DllSkipHook=sechost.dll
DllSkipHook=secur32.dll
DllSkipHook=rpcrt4.dll
DllSkipHook=combase.dll
DllSkipHook=ole32.dll
OpenIpcPath=*
```

**Comment by bastik-1001** [comment]
How often do you get these messages and what are you doing when they appear?

E.g. first start of the application in the box, or every time the application gets started.

**Comment by liuxianyue** [comment]
thanks
Not all programs have the above situation.

The program receives a notification of inserting and unplugging a ukey device; The above situation occurs only when it is pulled out,

**Comment by DavidXanatos** [comment]
does the issue still appear with recent builds?
