### ISSUE TITLE
v0.5.0/5.45.0 can't launch electron apps

### ISSUE THREAD

**Issue by silvestron** [sandboxie-plus/Sandboxie#215]
When I launch electron apps I see only the borders/shadow of the window but the actual window is empty/transparent or white.

This happened with Sbie-Plus when I launched Typora and Xmind 2020.

Using Sbie old UI I could launch Xmind but not Typora and VS Code (didn't try the last one in Sbie-Plus).

The behavior I saw was instances of the apps repeatedly opening and closing.

**Comment by DavidXanatos** [comment]
you mean this one: https://typora.io/#windows ?

**Comment by silvestron** [comment]
Yes, sorry I didn't add the links.

[Typora](https://typora.io/#windows)
[Xmind](https://www.xmind.net/xmind2020/)
[VS Code](https://code.visualstudio.com/)

**Comment by http403** [comment]
Hello. Although it labeled as "Fixed", I'm unable to open some electron based app, namely VSCodium(a no telemetry version of VSCode) and Discord.

**Comment by benduckwdesign** [comment]
I still can't open Discord either.

**Comment by zingmars** [comment]
I'm experiencing the same issue with Discord. Oddly enough, each time I open Discord it's different - sometimes it's just a black screen, sometimes it's just a transparent screen and once in a while I get a window that has the Discord background colour, but it's just a solid and nothing else.

@DavidXanatos could you please re-open?

**Comment by jzebedee** [comment]
This issue is still occuring for me in SB+, as of 0.7.1

Same behavior as above: blank white form, constant relaunching in background

Repro application: https://www.atf.gov/n/sites/default/files/eform4473_win-1.2.0_0.zip

**Comment by sihawken** [comment]
This issue is occurring for me as well, in SB+ 0.7.2. 

Electron apps won't run when launched from a shortcut, I get a blank window. However. I noticed a really strange behavior. 

If I run it by clicking and dragging the program into Sandboxie, the Electron app will start perfectly!

I tested this out with Slack and GitHub Desktop, both which had the same behavior.

Interestingly enough, Google Chrome acted similarly. I would get a dark gray page for everything if loaded via shortcut, but when clicked and dragged, would load perfectly.

**Comment by fake-name** [comment]
Not sure if it's related, but I encounter a similar issue when launching Fusion 360 (which uses QtWebEngine internally), and a number of NodeJS based visual novel applications. 

All of the above work fine outside the sandbox.

**Comment by Pr0mises** [comment]
@sihawken's method also works for discord

@http403  @benduckwdesign @zingmars 
How do you guys isolate discord even more as it scans your whole host at startup. Does sandboxie-plus block everything out of the box or do you guys have a specific .ini file that doesn't require admin rights?

**Comment by patoniilista** [comment]
Tried dragging the discord icon to the sandboxie screen and it gets stuck at "Starting...", with the discord's logo spinning and a constant I/O activity. 
![image](https://user-images.githubusercontent.com/72221896/120495379-07004880-c393-11eb-906e-8a9dc18df34b.png)
I've waited 30 minutes, and then decided to close the application.
![image](https://user-images.githubusercontent.com/72221896/120494782-7c1f4e00-c392-11eb-9d02-314f32074724.png)
Strangely, if I open it through the explorer context menu, it results in an invisible window but it goes beyond the "Starting..." and judging by the window size, it gets to the login part and even opens the browser in the background so it can detect if a login session is already present.

**Comment by DavidXanatos** [comment]
Please try adding
```PreferExternalManifest=y```
to the ini section of your sandbox where you are using the electron app and please report if that solved the issue

**Comment by fake-name** [comment]
> Please try adding
> `PreferExternalManifest=y`
> to the ini section of your sandbox where you are using the electron app and please report if that solved the issue

That makes discord work for me. Not general NodeJS based apps.

**Comment by DavidXanatos** [comment]
what other nodeJS apps fail for you

**Comment by DavidXanatos** [comment]
Please disable the external manifest again,
and try this new SbieDll:
https://xanasoft.com/Downloads/SbieDll_5.49.8b.zip

it adds a workaround that should allow electron apps to start properly

**Comment by isaak654** [comment]
Typora, Xmind, VSCodium, Discord run fine for me after applying SbieDll_5.49.8b.
