### ISSUE TITLE
[Sandboxie-Plus] Don't display box created in one User Account to any other User Account's Sandboxie UI.

### ISSUE THREAD

**Issue by codewhizz** [sandboxie-plus/Sandboxie#2152]
### Is your feature request related to a problem or use case?

If the box is created in one User account, then Sandboxie displays it's name in all other User Account's Sandboxie UI also.

### Describe the solution you'd like

Sandboxie should only display boxes which are created in current User Account, instead of all boxes from other User Accounts.

**Comment by DavidXanatos** [comment]
you can do that by hand: 
![grafik](https://user-images.githubusercontent.com/3890945/185206937-8144fa4b-ca8a-443a-8238-712cf42d18ae.png)
its just not the default

**Comment by codewhizz** [comment]
Yes. Thank you!
