### ISSUE TITLE
Typo in options

### ISSUE THREAD

**Issue by indig0F10w** [sandboxie-plus/Sandboxie#216]
Hello, it should be "compatibility".

Thanks and have nice day.

![SB+](https://user-images.githubusercontent.com/17021548/101631124-26da3380-3a24-11eb-8ae0-12cd8b87503d.PNG)

**Comment by NebelNidas** [comment]
This should have been fixed by #252. However, I've found another one:
![image](https://user-images.githubusercontent.com/48808497/102731793-15086280-4339-11eb-89b9-907a501ceefe.png)

Shouldn't it be Firefox Quantu**m**?

**Comment by cricri-pingouin** [comment]
In "About" dialog:
"Sandboxie-Plus is a **_powerfull_** sandboxing and application virtualization tool."
Should be "powerful".

In "Edit ini file" dialog:
"The changes will be **_applyed_** automatically".
Should be "applied".

**Comment by DavidXanatos** [comment]
shoudl be fixed by now
