### ISSUE TITLE
Proxifier support

### ISSUE THREAD

**Issue by ImportTaste** [sandboxie-plus/Sandboxie#2163]
### Is your feature request related to a problem or use case?

This is an indirect continuation of the thread here: https://forum.xanasoft.com/viewtopic.php?t=28

I attempted to email you a working copy of Proxifier but I never got a response.

### Describe the solution you'd like

Please check for an email dated May 15, subject: Proxifier

### Describe alternatives you've considered

If Sandboxie were to integrate its own solution to route programs running under it through a proxy, that would be even better.

**Comment by DavidXanatos** [comment]
ah there it is, thanks will try it out soon

**Comment by DavidXanatos** [comment]
I have a workaround for you: 
DllSkipHook=ws2_32.dll
but then you will still get an error message for SansboxieRpcSS.exe otehr then the error emssage it will work just fine.

I'l add this instruction to the compatybility templates of the next build and add a proepr fix for rpcss

**Comment by DavidXanatos** [comment]
1.3.2 is out
