### ISSUE TITLE
No administrator?

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#2165]
### Describe what you noticed and did

Why does the sandbox in version 1.3.1 show that my sandbox status is no administrator?? And the color of the sandbox turns yellow? It used to be orange   Can't use impersonation administrator now? 

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

He should be orange and should not show "no administrator"

### What is your Windows edition and version?

Windows11 Home 21H2 64bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

Sandboxie-Plus 1.3.1 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by bastik-1001** [comment]
As for the changed color, there was a change within 1.3.0.

> Note: Boxes created as Security Enhanced with prior builds will be displayed as normal in the UI from now on -- The Security Enhanced icons are now repurposed for the new Super Extra Security Enhanced Box Mode -- Note: The new enhanced security features require a supporter certificate

([https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md#130--5580---2022-08-09](https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md#130--5580---2022-08-09))

**Comment by DavidXanatos** [comment]
Sandboxie 1.3.1 brings new security mechanisms, hence a box only with drop admin rights enabled is no logner considdered hatdened and hence its shown in yellow.
You need to enable the additional security features to get a box considdered extra secure.

**Comment by bastik-1001** [comment]
> Can't use impersonation administrator now?

As far as I can tell, Sandboxie still can fake admin rights.

**Comment by Taeyeonzpx** [comment]
> 

Is this just a change in color? Is the Yellow sandbox in version 1.3.1 the orange sandbox in the previous version?

> Sandboxie 1.3.1 brings new security mechanisms, hence a box only with drop admin rights enabled is no logner considdered hatdened and hence its shown in yellow. You need to enable the additional security features to get a box considdered extra secure. ![grafik](https://user-images.githubusercontent.com/3890945/185758153-ca1f5091-95b3-48e4-85c1-e453a068fb47.png)

Is this just a change in color? Is the Yellow sandbox in version 1.3.1 the orange sandbox in the previous version?

**Comment by bastik-1001** [comment]
There is a UI inconsistency in 1.3.1 (probably since 1.3.0) when switching to "Emulate Admin Rights" on a hardened box, the menu does not have "Drop Admin Rights" toggled. Within the .ini `DropAdminRights=y` is always set, no matter if Emulate Admin Rights is toggled. Within the .ini `FakeAdminRights=y` is set.

Toggling "Drop Admin Rights" switches `FakeAdminRights=y` to `FakeAdminRights=n`

**Comment by DavidXanatos** [comment]
>Is this just a change in color? Is the Yellow sandbox in version 1.3.1 the orange sandbox in the previous version?
yes

**Comment by Taeyeonzpx** [comment]
> > Is this just a change in color? Is the Yellow sandbox in version 1.3.1 the orange sandbox in the previous version?
> > yes

thank you
