### ISSUE TITLE
"Clash for Windows"   New version of agent software crashes

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#2166]
### Describe what you noticed and did

A software crash occurred in the new version "clash for windows 0.19.27". The previous version of "0.19.22" can be started normally

### Affected program

Clash for Windows

### Download link

https://github.com/Fndroid/clash_for_windows_pkg/releases

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

It should start normally like 0.19.22

### What is your Windows edition and version?

Windows 11 Home 21H2 64bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

Sandboxie-Plus 1.3.1 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by bastik-1001** [comment]
I have tried to install the app, which works fine, but for me the app is crashing as well. I have no idea, what it was supposed to do, but I wanted to try anyway to confirm that this is not an isolated case.

**Comment by Taeyeonzpx** [comment]
> 0.19.27

I also tried it on my new windows 10 virtual machine. It was the same. The "0.19.27" crashed and the "0.19.22" was normal

**Comment by Taeyeonzpx** [comment]
> I have tried to install the app, which works fine, but for me the app is crashing as well. I have no idea, what it was supposed to do, but I wanted to try anyway to confirm that this is not an isolated case.

https://github.com/sandboxie-plus/Sandboxie/issues/2166#issuecomment-1221370785

**Comment by Taeyeonzpx** [comment]
> I have tried to install the app, which works fine, but for me the app is crashing as well. I have no idea, what it was supposed to do, but I wanted to try anyway to confirm that this is not an isolated case.

I also tried it on my new windows 10 virtual machine. It was the same. The "0.19.27" crashed and the "0.19.22" was normal

**Comment by isaak654** [comment]
By 'tried on the virtual machine' you mean always in Sandboxie?

**Comment by Taeyeonzpx** [comment]
> By 'tried on the virtual machine' you mean always in Sandboxie?

Yes, I also installed a sandbox on the virtual machine to test whether the software crash is the problem of my computer. The sandbox "clash for windows 0.19.27" in the virtual machine still crashes

**Comment by isaak654** [comment]
Sandboxie contains a specific rule for an Electron app, you may want to test it for the above program as well:
https://github.com/sandboxie-plus/Sandboxie/blob/a9bebec8b907ea4c85ccd7a45302390989778573/Sandboxie/install/Templates.ini#L161

**Comment by Taeyeonzpx** [comment]
> Sandboxie contains a specific rule for an Electron app, you may want to test it for the above program as well:
> 
> https://github.com/sandboxie-plus/Sandboxie/blob/a9bebec8b907ea4c85ccd7a45302390989778573/Sandboxie/install/Templates.ini#L161

How should I test?

**Comment by isaak654** [comment]
You can try to replace the executable name and add the line on your [sandbox] in Sandboxie.ini.

**Comment by Taeyeonzpx** [comment]
> You can try to replace the executable name and add the line on your [sandbox] in Sandboxie.ini.

OK, I added this line "UseElectronWorkaround=Clash for Windows.exe,n" and it can start normally. Why? What does this rule mean? But "SBIE2205 Service not implemented: ConsoleInit (C00000D4)" pops up when starting

**Comment by isaak654** [comment]
> OK, I added this line "UseElectronWorkaround=Clash for Windows.exe,n" and it can start normally. Why? What does this rule mean? 

It means that Sandboxie is currently using a workaround for Electron apps by default, but it doesn't seem to be valid for programs with an updated Electron framework.

> But "SBIE2205 Service not implemented: ConsoleInit (C00000D4)" pops up when starting

It could be an indicator of another unspecified issue. In a few words, the program tried to do something which is not supported in Sandboxie and the operation just failed.

**Comment by Taeyeonzpx** [comment]
> It means that Sandboxie is currently using a workaround for Electron apps by default, but it doesn't seem to be valid for programs with an updated Electron framework.

Can this place be optimized? Let him decide this rule automatically

**Comment by 6Tom** [comment]
It's funny. I met you again, dear sister. Your question has really helped me a lot this time. 

This error occurred not only on "clash0.19.27", but also on "vscode1.71.0". Now I have solved the error in vscode in the same way.

Thank you dear isaak654, it's really helpful. Love you guys so much.
