### ISSUE TITLE
{Plus 1.3.1] Allow to close sandbox options dialog with Esc key

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2168]
### Is your feature request related to a problem or use case?

The new feature to search for settings seems to have taken the ability to close the dialog by pressing esc

### Describe the solution you'd like

Be able to close the dialog by pressing esc instead of cancel if i didin't change anything or if i already used the apply button

**Comment by DavidXanatos** [comment]
yes that is so isn't it better this way?

**Comment by isaak654** [comment]
I think it's weird when you press the Enter key in the search box, it keeps searching without even putting a word. 😅

**Comment by DavidXanatos** [comment]
well its a substring match search if the substring happens to be empty it matches everything

**Comment by RandomGOTI** [comment]
> yes that is so isn't it better this way?

it's slower , i'm used to esc whenever i just cruise the options or edit the local templates from the UI after pressing save
Cancel button was cosmetic for me xD

**Comment by DavidXanatos** [comment]
ok
