### ISSUE TITLE
Problem with mTLS authentication in Google Chrome

### ISSUE THREAD

**Issue by DanielKravtsov** [sandboxie-plus/Sandboxie#2177]
### Describe what you noticed and did

Problem occurs in Google Chrome when i trying to access any site with mutual tls authentication.
1. Type address https://blahblah.domain.com/
2. Choosing my personal client certificate in chrome popup window "Select a certificate"
3. Got error ERR_SSL_CLIENT_AUTH_NO_COMMON_ALGORITHMS

Problem occurs on all Sanboxie Classic versions released at least after 2021 year.
If i disable loading Chrome in sandboxie mtls authentication works correctly.
![mtls chrome via sandboxie](https://user-images.githubusercontent.com/98955576/186126502-9fcac242-24b9-4116-9de2-779eee583e11.png)

### How often did you encounter it so far?

Everytime

### Affected program

Google Chrome all versions

### Download link

Not relevan

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Web page should open correctly with mtls auth.

### What is your Windows edition and version?

Windows 10 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Kaspersky Antivirus

### What version of Sandboxie are you running?

5.58.1

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than v1.0.22 / 5.55.22.

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=Windows10CoreUI
Template=SynapticsTouchPad
Template=OfficeLicensing
Template=Kaspersky
Template=7zipShellEx
TemplateReject=WindowsRasMan
TemplateReject=WindowsLive

[DefaultBox]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
RecoverFolder=C:\Users\*DELETED*\Documents
BorderColor=#00FF00
BoxNameTitle=n
CopyLimitKb=4120000
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=Office_Outlook
Template=Chrome_Phishing_DirectAccess
Template=Kaspersky
Template=OfficeLicensing
Template=OfficeClickToRun
ProcessGroup=<InternetAccess>,chrome.exe,putty.exe
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,neon.exe,maxthon.exe,iron.exe,dragon.exe,chrome.exe
OpenFilePath=POWERPNT.EXE,C:\Users\*DELETED*\Documents
OpenFilePath=EXCEL.EXE,C:\Users\*DELETED*\Documents
OpenFilePath=WINWORD.EXE,C:\Users\*DELETED*\Documents
NotifyInternetAccessDenied=y
NotifyStartRunAccessDenied=y
AutoRecover=y
OpenWinClass=*
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
AutoRecoverIgnore=.crdownload
AutoRecoverIgnore=.tmp
ReadKeyPath=chrome.exe,HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates
ForceProcess=chrome.exe

[UserSettings_26E803E5]

SbieCtrl_HideMessage=1307,WerFault.exe [DefaultBox]
SbieCtrl_HideMessage=2205,Win32Init.4 (C0000008)
SbieCtrl_HideMessage=2224,GoogleUpdate.exe [DefaultBox]
SbieCtrl_HideMessage=2203,*GUIPROXY_00000002; MsgId: 14 - chrome.exe [00000102]
SbieCtrl_HideMessage=2101,ConnectPort (C0000022) access=001F0000 initialized=1
SbieCtrl_HideMessage=2101, ConnectPort (C0000022) access=001F0000 initialized=1
SbieCtrl_HideMessage=2205, Win32Init.4 (C0000008)
SbieCtrl_NextUpdateCheck=1661324417
SbieCtrl_AutoApplySettings=n
SbieCtrl_WindowCoords=300,275,1238,633
SbieCtrl_ActiveView=40021
SbieCtrl_UpdateCheckNotify=n
SbieCtrl__IgnoreUpdate=5.47.1
SbieCtrl__IgnoreUpdate=5.49.0
SbieCtrl__IgnoreUpdate=5.49.8
SbieCtrl__IgnoreUpdate=5.51.3
SbieCtrl__IgnoreUpdate=5.55.13
SbieCtrl_HideWindowNotify=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_BoxExpandedView=DefaultBox
```

**Comment by isaak654** [comment]
You may want to try [this](https://github.com/sandboxie-plus/Sandboxie/issues/1679#issuecomment-1065760921) workaround and report how it goes.

**Comment by isaak654** [comment]
Stale

**Comment by isaak654** [comment]
Closed due to lack of user confirmation.
