### ISSUE TITLE
ProgramData not writeable

### ISSUE THREAD

**Issue by tuxtard** [sandboxie-plus/Sandboxie#2180]
### Describe what you noticed and did

Davinci Resolve 18.0.1 free version installer fails to write in C:\ProgramData on new and empty sandbox with default settings. Tried previous versions of Sandboxie plus and Davinci Resolve but got the same result

![resolve](https://user-images.githubusercontent.com/1107497/186416512-aa519e85-428f-4fca-9375-2d1bae0903f0.jpg)
.

### Affected program

Davinci Resolve 18.0.1

### Download link

https://www.blackmagicdesign.com/products/davinciresolve

### Where is the program located?

Not relevant to my request.

### Expected behavior

Installer should be able to write to C:\ProgramData and complete installation

### What is your Windows edition and version?

Windows 11 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.3.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

not a regression

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=SynapticsTouchPad
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Edge_Win11Fix
Template=7zipShellEx

[UserSettings_0D9C0237]
SbieCtrl_AutoStartAgent=SandMan.exe
BoxDisplayOrder=DefaultBox,DaVinci
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[Test]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
UsePrivacyMode=n
```

**Comment by bastik-1001** [comment]
I just verified that I can write to Program Files and Program Data, using a sandboxed explorer. I am not in the position to test this installer.

You may want to try to set `FakeAdminRights=y` for the box. (Or enable "Make applications think they are running elevated" in the options, which sets this setting)

**Comment by tuxtard** [comment]
> 

I can confirm that I can write from sandboxed explorer to C:\ProgramData too. I can also confirm that I can install Davinci Resolve without an issue outside sandbox on the same machine, and that I can install it inside sandbox on a different machine. I did try to do a full reinstall of Sandboxie Plus and purge all config files, but it did not help.

**Comment by DavidXanatos** [comment]
I tied installing davinci on my test VM and it worked just fine.
so not sure what to do here...
have you checked if the old box folder really was deleted?
or better create a new box and try again.
do you use any 3rd party antimalware software which ma interferer?

**Comment by tuxtard** [comment]
Hm it seems that error message is misleading. Installer does create folder structure inside ProgramData which means it has write access, but then it fails writing first file, which is default-config.dat and explorer shows default-config.dat with 0 bytes.

![resolve_programdata](https://user-images.githubusercontent.com/1107497/187651035-6d31db64-303b-4478-aa8d-6502fd3621bd.jpg)

**Comment by tuxtard** [comment]
> I tied installing davinci on my test VM and it worked just fine. so not sure what to do here... have you checked if the old box folder really was deleted? or better create a new box and try again. do you use any 3rd party antimalware software which ma interferer?

I created a new box and there is no altimalware software installed other than windows defender.

**Comment by gispos** [comment]
I have the same problem.
With previous Sandboxie versions there were no problems.
The strange thing is, when the installation does work, there is no ProgramData folder, the files are under 'user'.

An update of Davinci in the sandbox does not work now either.

**Comment by offhub** [comment]
**Windows**
`C:\ProgramData` = `C:\Users\All Users` (Vista and above)

**Sandboxie**
`...\user\all` (if SeparateUserFolders=y)
`...\Box\drive\C\ProgramData` (if SeparateUserFolders=n)

**Comment by offhub** [comment]
You could try with the following setting:

MsiInstallerExemptions=y

(Plus UI > Sandbox Options > Security Hardening > Elevation restrictions >> Allow MSIServer to run with a sandboxed system token and apply other exceptions if required)

**Comment by tuxtard** [comment]
> You could try with the following setting:
> 
> ```
> MsiInstallerExemptions=y
> ```
> 
> (`Plus UI` > `Sandbox Options` > `Security Hardening` > `Elevation restrictions` >> `Allow MSIServer to run with a sandboxed system token and apply other exceptions if required`)

This helped. Thanks.

**Comment by isaak654** [comment]
#2699
