### ISSUE TITLE
[Plus 1.3.3] BorderColor/ColorBoxIcons issue

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2184]
### Describe what you noticed and did

Set
Sandboxie-Plus.ini - >`ColorBoxIcons=true`
To any box `BorderColor=#f6f602,off`

Added the full value (incl border size) `,6` to `BorderColor=#f6f602,off` from Edit INI in box options and had a BSOD , went back to sandboxie and the box was still blue despite `BorderColor=#f6f602,off,6`

I change border color from UI with HTML #f6f602 and the box color changes to yellow and check the box ini : `BorderColor=#02f6f6,off,6`

I repeat the action but HTML #02f6f6  (....) to blue (....) : `BorderColor=#f6f602,off,6`

someone pinch me so i can wake up now

#2111

### Affected program

XD

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

.

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.3.1 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

<details> <summary> Plus </summary> 

[Options]
NextCheckForUpdates=1662170454
WizardLevel=-1
UiLanguage=
DPIScaling=1
UseDarkTheme=2
UseFusionTheme=2
AltRowColors=false
UseBackground=2
LargeIcons=2
NoIcons=2
OptionTree=2
ColorBoxIcons=true
FontScaling=100
RunInDefaultBox=false
ShowNotifications=true
OpenUrlsSandboxed=2
ShowRecovery=false
InstantRecovery=true
RecoveryOnTop=true
UseAsyncBoxOps=false
EnablePanicKey=false
PanicKeySequence=Shift+Pause
WatchBoxSize=false
WatchIni=true
SysTrayIcon=1
SysTrayFilter=0
CompactTray=false
AutoBoxOpsNotify=false
AutoRunSoftCompat=true
CheckForUpdates=2
DownloadUpdates=0
UpdateChannel=0
NoSupportCheck=false 
</details>

<details> <summary> Sbie </summary> 

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=RTSS
Template=InternetDownloadManager
Template=7zipShellEx

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#f6f602,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=81920
</details>

**Comment by bastik-1001** [comment]
I can't reproduce this insofar as whatever # value I enter gets ignored. Before, I never attempted to change the color by entering a different hex-code, since I used the color picker. Now I wanted to try to reproduce this issue and added #f6f602 to the ini, for some box, but the icon of the box did not change from the default yellow. Even starting a program did not change the color of the icon.

Even setting it to on in the ini did not change the icon or the border color at all. In the Sandman UI the color picker and the icon remained at yellow. Selecting the color with the color picker, allows me to change the color for the icon and starting a program gets that border color. With the color picker I picked some color (purpleish). Editing the ini to change the color to #ed2839 (redish) had no effect on the icon nor the window color. Even restarting sandman and reloading the ini again, had no effect.

Since I never edited the code for the border color, I can't tell whenever this is something that worked before.

For this issue, setting #f6f602 does not do anything for me, neither change the color, nor have any crash or BSOD.

**Comment by RandomGOTI** [comment]
The issue happens with both classic and plus UI's, border color value  #f6f602 (yellow) appears as blue and if blue is used #02f6f6 appears as yellow in the UI, and what i mean is the hex code in the config and what appears in the UI is not matching. The color picker on the other hand has no issue on my end.

#00ffff (blue again lol) that appears as xffff00 (yellow) xD 
#ee2304 (red) appears as #0423ee (blue) in ini and so on 

On my recordings with plus version 1.2.8 , 1.3.0 and 1.3.1 issue can be seen as i show both sandbox options and ini tabs

(1.2.8 & 1.3.0 https://github.com/sandboxie-plus/Sandboxie/issues/2111#issuecomment-1210364368 )

(1.3.1 https://github.com/sandboxie-plus/Sandboxie/issues/1955#issuecomment-1214314401 )

About the BSOD , i mainly mentioned it as a "this happened and anyway back to ... " kind of thing , since i didn't get any BSOD at all for years , i disabled dumps ¯\_(ツ)_/¯ , and the only two i got recently where only related to sandboxie , first i was editing a resorce access option and i made a mistake typing it , i was editing it via the path column in the UI (plus 1.2.x ), second was this time , stopped all and used connect and got it after i finished editing the boxborder value and got to reload the ini
I did test stuff by changing config and restarting service/driver multiple times and i may have gave it a headache testing for application crash (werfault) on issue #2091 before i got to play around with ColorBoxIcons feature and noticed the BorderColor issue

**Comment by bastik-1001** [comment]
> border color value #f6f602 (yellow) appears as blue and if blue is used #02f6f6 appears as yellow in the UI, and what i mean is the hex code in the config and what appears in the UI is not matching. 

I can't reproduce that.  #f6f602 gives me a yellow icon and yellow border, #02f6f6 gives me a blue icon and a blue border. That is when being set over the UI of sandman. When editing the .ini there is no change in color, no matter what code I use, for me it remains the color I selected before, for the icon and for the actual border.

**Comment by bastik-1001** [comment]
Sandman shows #40ff99 in the color picker and in the ini it shows #99ff40 (which are the same numbers, but in a different order).

#58ffb1 becomes #b1ff58 in the .ini

**Comment by bastik-1001** [comment]
And the reason setting the color to purblish in the UI and changing the color in the ini to redish had no effect for me was due to the hexcodes being the same. Actually being the opposite of each other by accident, but written differently in the UI, and in the ini. I just went back to check if my previous attempts had not been with invalid hexcodes.

**Comment by RandomGOTI** [comment]
Hmm update on that BSOD , page fault in nonpaged area SbieDrv.sys
I just had it as i reloaded the ini file

**Comment by DavidXanatos** [comment]
can you plrease provide a kernel dump

**Comment by RandomGOTI** [comment]
> This ~~video~~ is too big.
 
(thats what she said) ( ͡° ͜ʖ ͡°)

> Try again  with a file size less than 10MB.

🙅 


👉  https://mega.nz/embed/hiZTSbba#1fTb92lw8dcQlsGFDu5rbQxBFvIw7pVuSaDPDf9gbZY

**Comment by Incog5** [comment]
Delete default box and restart the sandboxie UI: a defaultbox gets created with
BorderColor=#00ffff,ttl

Now create a new box:
BorderColor=#02f6f6,ttl
which is blue, but it still shows up as yellow

**Comment by Incog5** [comment]
@DavidXanatos 

I retested the above in a clean VM setup and fresh sandboxie plus install:

DefaultBox and NewBox have different border color values but both will show up as yellow.

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
**BorderColor=#00FFFF,ttl**
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[New_Box]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
**BorderColor=#02f6f6,ttl**
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=n
