### ISSUE TITLE
Installing MSI fails due to a directory creation?

### ISSUE THREAD

**Issue by nedsociety** [sandboxie-plus/Sandboxie#219]
Driver version 5.45.0

It seems that MSI installer fails to create C:\Config.Msi\ inside the sandbox. This results in installation failures, for example Python.

### Repro steps

Got Python x86 webinstaller (https://www.python.org/ftp/python/3.9.1/python-3.9.1-webinstall.exe) then ran it inside DefaultBox:

![image](https://user-images.githubusercontent.com/11943013/101757018-012f5600-3b1a-11eb-98db-ba2a48189a47.png)

Here's the logs:

[Python 3.9.1 (32-bit)_20201210190017_000_core_JustForMe.log](https://github.com/sandboxie-plus/Sandboxie/files/5671817/Python.3.9.1.32-bit._20201210190017_000_core_JustForMe.log)
[Python 3.9.1 (32-bit)_20201210190017.log](https://github.com/sandboxie-plus/Sandboxie/files/5671819/Python.3.9.1.32-bit._20201210190017.log)

The suspected line for failure was (core_JustForMe.log, line 309):

```
MSI (s) (BC:60) [19:00:25:066]: Create folder failed: C:\Config.Msi\
```

This makes no sense because the account had every rights -- It was an admin account and the installer was under UAC elevation.  Trying to manually create that folder within the sandboxed explorer worked smoothly.

So I actually tried to create that folder (`C:\Config.Msi\`) inside the sandbox and then ran the Python installer. Then the installation worked without failure.

**Comment by DavidXanatos** [comment]
thanks for the great report will check it out shortly and try to include a fix in the upcoming build

**Comment by DavidXanatos** [comment]
mmh... indeed what a strange bug, in my case msi always failed on the first run and succeededes on the second, or when i create the folder by hand it works right away, as expected.
This issue was introduced with windows 20H2 on 2004 it does not happen.
I'll look into fixing that asap...

thank you for the great bug report :D

**Comment by nedsociety** [comment]
> This issue was introduced with windows 20H2 on 2004 it does not happen.
Mine is still 1909 so I'm not entirely sure if it is a regression on 20H2.

**Comment by Poloxo53** [comment]
Hello,
I still have this issue with a program installation on Sandboxie-plus 1.15.12 on Windows 11 24H2

<img width="397" height="147" alt="Image" src="https://github.com/user-attachments/assets/50439455-426b-4d2f-9f73-a91df9cf28ba" />

**Comment by anmac1789** [comment]
> Hello, I still have this issue with a program installation on Sandboxie-plus 1.15.12 on Windows 11 24H2
> 
> <img alt="Image" width="397" height="147" src="https://private-user-images.githubusercontent.com/105914050/465162862-50439455-426b-4d2f-9f73-a91df9cf28ba.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIzMjQ2NzUsIm5iZiI6MTc2MjMyNDM3NSwicGF0aCI6Ii8xMDU5MTQwNTAvNDY1MTYyODYyLTUwNDM5NDU1LTQyNmItNGQyZi05ZjczLWE5MWRmOWNmMjhiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwNVQwNjMyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTc5NDRkNTA2MTZhZDI2Yzc5ZTg0MDhhNmNiMjhlMGIyZDI2ZWNiZWYyNDgxMDQ2OWNkODdjODQ3NWZkMDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4KtOFZBhlLkNuiKeRTFwH9aujklVkDNz2SckVyP6B_Y">

I am also getting the same error when installing winzip. Im using sandboxie-plus 1.16.5
