### ISSUE TITLE
SandMan does not detect the already existing DefaultBox

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#2195]
### Describe what you noticed and did

Clean VM (running Windows 11, 21H2, 64-bit):

1.) Download and install the latest version of Sandboxie-Plus (v1.3.2, 64-bit).
2.) Click through the Setup Wizard "Personally", leaving everything at default values.
3.) Exit SandMan using "Sandbox" > "Exit".
4.) Check that the Sandboxie.ini contains the [DefaultBox].
5.) Double-click the "Sandboxie-Plus" icon to start SandMan.
6.) You can see the message: "**Default sandbox not found; creating: DefaultBox**".

After each exit and restart of SandMan the message is shown!

(In addition, I can reliably reproduce it on my Windows 10 host system.)

### How often did you encounter it so far?

With each restart of SandMan.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

If the DefaultBox already exists in the Sandboxie.ini, the message should not be triggered.

### What is your Windows edition and version?

Windows 10/11 Pro, 21H2, 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

1.3.2 - 1.3.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Issue begins with version 1.1.0 and newer. Version 1.0.22 and older do not show the issue.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by APMichael** [comment]
A little update:

I have tried several older versions and found out that the message is only triggered from **version 1.1.0 and newer**. Version 1.0.22 and older do not show the issue.

``` 
|Time|         |Message|                                                    
10:49:00.755   Installation Directory: C:\Program Files\Sandboxie-Plus      
10:49:00.755   Sandboxie-Plus Version: 1.0.22 (5.55.0)                      
10:49:00.755   Current Config: C:\Windows\Sandboxie.ini                     
10:49:00.755   Data Directory: C:\Users\User\AppData\Local\Sandboxie-Plus
``` 

``` 
|Time|         |Message|                                                    
11:03:24.787   Installation Directory: C:\Program Files\Sandboxie-Plus      
11:03:24.787   Sandboxie-Plus Version: 1.1 (5.55.0)                         
11:03:24.787   Current Config: C:\Windows\Sandboxie.ini                     
11:03:24.787   Data Directory: C:\Users\User\AppData\Local\Sandboxie-Plus   
11:03:24.937   Sandboxie config has been reloaded                           
11:03:24.937   Default sandbox not found; creating: DefaultBox              
11:03:24.984   Sandboxie config has been reloaded                           
11:03:25.485   Sandboxie config has been reloaded                           
```

**Comment by APMichael** [comment]
Another small update:

I also tried it with a new Windows user profile, as well as with Microsoft Defender disabled. However, the issue still persists. So I really can't explain why the issue should not occur with other Sandboxie users?

In addition, I have tried the portable mode, with this the issue does not occur.

I can't think of any more possible tests at the moment...

**Comment by shearercole** [comment]
I have Plus installed in non-portable, and have observed this issue for the last few versions. It *appears* to be a harmless msg as it does not disturb the existing DefaultBox contents(if non-empty) or the box's config. 
Win 10 Pro x64 21H2

**Comment by DavidXanatos** [comment]
i think i know that caused the issue it it probably will be fixed in the next build

**Comment by APMichael** [comment]
@shearercole Thank you for confirming the issue.

It is correct that it does not make any changes to the Sandboxie.ini. However, there is still a write access to the Sandboxie.ini which unfortunately changes the date/time of the file. I always use this date/time to check the ini version or for unintentional changes, which no longer work as a result.

@DavidXanatos Great! :smile: I hope this fixes the problem. I will give you feedback after the installtion of the next version.

**Comment by RandomGOTI** [comment]
Installed and used kmdutil commands as the UI does in case of stop all , started sandman and 

```
|Message|                                                    

Maintenance operation completed                              
Installation Directory: C:\Program Files\Sandboxie           
Sandboxie-Plus Version: 1.3.3 (5.58.0)                       
Current Config: C:\Windows\Sandboxie.ini                     
Data Directory: C:\Users\User\AppData\Local\Sandboxie-Plus   
Sandboxie config has been reloaded                           
Sandboxie config has been reloaded                           
Default sandbox not found; creating: DefaultBox              
Sandboxie config has been reloaded                           
Sandboxie config has been reloaded                           
```

My DefaultBox even has data in it...
Did Stop all from sandman this time and relaunched... same as above

Windows 7 Ultimate SP1 x64

**Comment by APMichael** [comment]
@RandomGOTI Thanks for quickly checking the new version and confirming that the issue is still occurring.

@DavidXanatos I can also confirm that unfortunately nothing has been fixed and the issue still occurs on all systems I tested.

This issue has now also forced me back to SbieCtrl, as it has more severe effects in certain combinations:

When combining the setting "EditAdminOnly=y" together with non-administrator users, SandMan stops working at all. Because of the issue the Sandboxie.ini should be written, but this is blocked by the setting "EditAdminOnly=y", SandMan is now stuck and does not show any sandboxes anymore.

**Comment by wilders-soccerfan** [comment]
The bug "Default sandbox not found; creating: DefaultBox" is present in v1.3.3 (portable mode) also.
It was not present for me in v1.3.2 (portable mode).  [I am on Win7 SP1 Home 64bit (build 7601)]

**Comment by shearercole** [comment]
Another confirmation from me that the msg persists after upgrading to 1.3.3 (non-portable)
Win10 x64 Pro 21H2

**Comment by DavidXanatos** [comment]
this time it should be fixed for good

**Comment by APMichael** [comment]
Fix confirmed! :smile: Many thanks for this!
