### ISSUE TITLE
5.45.0 Windows 10 installer issue

### ISSUE THREAD

**Issue by skygunner** [sandboxie-plus/Sandboxie#220]
![2020-12-10_203003](https://user-images.githubusercontent.com/84759/101763778-fd57ff80-3b2a-11eb-88c5-e68d75d4f594.png)

Though there's no Sandboxie related programs are still running, but it won't install. 

Cancel and reboot solved issue.

**Comment by NewKidOnTheBlock** [comment]
I think the installer somehow refuses to overwrite the SbieDrv.sys, see #208

**Comment by DavidXanatos** [comment]
try uninsatlling reboot and than install, if that does nto help check if after the uninstall the sys file is still there and if so delete or renam it reboot again and voila

**Comment by DavidXanatos** [comment]
should be fixed with the 2004 comatybility fix
