### ISSUE TITLE
Save all SBIE messages to the EventLog

### ISSUE THREAD

**Issue by 1mm0rt41PC** [sandboxie-plus/Sandboxie#2207]
### Is your feature request related to a problem or use case?

I have 3 users who use the same PC but each has his own session. In order to detect possible configuration errors and malicious activity, I would like to have all the SBIE messages of all the users in the EventLog.

I have checked the documentation https://sandboxie-plus.github.io/sandboxie-docs/Content/SBIEMessages.html but I just have EventLog messages about the driver loading. 

### Describe the solution you'd like

Send all SBIE messages to the Windows EventLog for a better tracking

**Comment by DavidXanatos** [comment]
this sounds quite usefull,
actually it might be worth considering dropping the entire driver internal message passing and use the windows event system directly,
although a couple hacky uses around the message system would need to be properly resolved.

What you can do in the mean time is open regedit.exe go to "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SbieSvc"
and add a REG_SZ named "LogFile" with content like this "2;c:\temp\Sandboxie.log"
then all messages will be logged to that log file.
2 has no meaning in the code its called version and it must be 2 I may drop that in a future build.

**Comment by 1mm0rt41PC** [comment]
Thanks, this solution will allow me to track errors more easily while waiting for the arrival of the EventLog.

Is it possible to add the username/sid used by the process? Actually I get:
```
2022-09-02 01:46:07 SBIE1308 Program cannot start due to restrictions - powershell.exe [ChromeBox]
2022-09-02 01:46:07 SBIE1308 Program cannot start due to restrictions - powershell.exe [ChromeBox]
```
I checked and  it can probably done with Process_GetSidStringAndSessionId inside the function: https://github.com/sandboxie-plus/Sandboxie/blob/5e4a6ce1c1c51510e731bc74617c9f9e0f7a20ad/Sandboxie/core/drv/process_util.c#L1204
Is it the good way ?

I just looked at the code but I can't understand the usage of the MultiLog registry key https://github.com/sandboxie-plus/Sandboxie/blob/364c43f29bb4f4a4b667d393a5e396b93c6c62ef/Sandboxie/core/svc/DriverAssistLog.cpp#L180

**Comment by DavidXanatos** [comment]
MultiLog takens a , or ; separated list of message id's to be logged and logs it into a log file where the box name is appended to the filename before the extension

**Comment by 1mm0rt41PC** [comment]
I'have add SID to the current log https://github.com/sandboxie-plus/Sandboxie/pull/2211 if verbose mode is enabled.

**Comment by DavidXanatos** [comment]
A workaround will be added to 1.3.3 adding the ability to log also the user name

**Comment by 1mm0rt41PC** [comment]
I have added documentation on these points https://github.com/sandboxie-plus/Sandboxie/issues/2207

**Comment by 1mm0rt41PC** [comment]
I have added this info into the documentation => https://github.com/sandboxie-plus/sandboxie-docs/pull/58

**Comment by isaak654** [comment]
#2920
