### ISSUE TITLE
When I run sandman I get the error "Failed To Connect To The Server"

### ISSUE THREAD

**Issue by NameRectified** [sandboxie-plus/Sandboxie#2208]
### Describe what you noticed and did

I had reset my pc so I reinstalled sandboxie

Earlier sandbox was working really well after resetting my pc, I had started getting the error

Tried uninstalling and reinstalling many times, but dint solve the error

I am unable to even create a sandbox

### How often did you encounter it so far?

everytime

### Affected program

All prograns

### Download link

not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

create a sandbox and run applications in  it

### What is your Windows edition and version?

Windows 10 pro version 1511

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

malwarebytes was there, but I removed it because i thought it caused the problems

### What version of Sandboxie are you running?

Sandboxie-Plus version v1.2.8

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

not sure

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

no I havent changed anything

### Crash dump

https://www.mediafire.com/file/c3fmxrao4ajacjd/SandMan.exe.7184.dmp/file
[SandMan.exe.7184.zip](https://github.com/sandboxie-plus/Sandboxie/files/9469636/SandMan.exe.7184.zip) (GitHub mirror)

### Sandboxie.ini configuration (usually located in C:\Windows or in the installation folder)

```shell
couldnt find it
```

**Comment by DavidXanatos** [comment]
I dont think i still have the PDB's for this old build
could you please try the 1.3.2 and provide a fresh dump if the problem should still persist

**Comment by isaak654** [comment]
> I dont think i still have the PDB's for this old build

https://github.com/sandboxie-plus/Sandboxie/actions/runs/2816377351 (also known as 1.2.8b)
https://github.com/sandboxie-plus/Sandboxie/actions/runs/2805084955 (1.2.8)

**Comment by NameRectified** [comment]
i am still getting the same error even in v1.3.2

 also in some sbie messages sections these errors are presnt:21:00:28.173

|Time|         |Message|                                                         

21:00:28.173   Maintenance operation completed                                   
21:03:04.689   PID 0: SBIE1401: ;                                                
21:03:04.829   PID 0: SBIE1111: [C0000034 / 12]; WIN32U                          
21:03:04.858   PID 0: SBIE1103: 5.58.0;                                          
21:03:04.868   PID 0: SBIE9234: level 9153 status=C0000001 error=-1073741823;    
21:03:04.874   PID 0: SBIE1102: ;                                                
21:03:04.887   PID 0: SBIE1401: ;                                                
21:03:04.896   PID 0: SBIE1111: [C0000034 / 12]; WIN32U                          
21:03:04.906   PID 0: SBIE1103: 5.58.0;                                          
21:03:04.919   PID 0: SBIE9234: level 9153 status=C0000001 error=-1073741823;    
21:03:04.935   PID 0: SBIE1102: ;                                      

for latest dump files:https://www.mediafire.com/file/7aboc1ag2htdi46/SandMan.exe.7184.dmp/file

**Comment by NameRectified** [comment]
please sir help

**Comment by Luro223** [comment]
> help

Looks like an issue with corrupted windows or bad repack
Try with clean windows 10 then show results here

**Comment by NameRectified** [comment]
should i reset my pc? Thanks for the reply

**Comment by Luro223** [comment]
> should i reset my pc? Thanks for the reply

Yes, try to use the clean windows

**Comment by Luro223** [comment]
@NameRectified how are the results?
