### ISSUE TITLE
Match exactly a specified file

### ISSUE THREAD

**Issue by Simba98** [sandboxie-plus/Sandboxie#2216]
### Is your feature request related to a problem or use case?

I would like to allow sandboxed programs to access exactly one file, e.g. C:\a\b.txt
However, the Unix style program will try to create C:\a\b.txt.LCK for marking it as locked.
The .LCK file I would like to sandbox it.

I tried `OpenPipePath=C:\a\b.txt` , but the `C:\a\b.txt.LCK` also matches.
I guess because [Archived Sandboxie Document](https://sandboxie-website-archive.github.io/www.sandboxie.com/OpenFilePath.html) 
> When reviewing these examples, keep in mind that Sandboxie places a wildcard star at the end of the value, unless a star already appears anywhere in the value. So for example, C:\Downloads\ becomes C:\Downloads\*, while *.eml remains unchanged.

As a result, the `OpenPipePath=C:\a\b.txt` will be `OpenPipePath=C:\a\b.txt*` and matches `C:\a\b.txt.LCK`.
I have a workaround `OpenPipePath=*C:\a\b.txt`, it looks good because I will not have a drive/volume named as `AC:\`.

### Describe the solution you'd like

Perhaps allows regex `$`? For matching the end of the file.
But seems like `$` is using and it will be a incompatible change.

Perhaps remove the auto-places a wildcard star feature? Also a incompatible change.

### Describe alternatives you've considered

Maybe adding a feature that if see a @ at the start of the file name will stop auto-places a wildcard star?
E.g. `OpenPipePath=@C:\a\b.txt`

Or if I missed something... Please let me know if we can do it in current version.
Thanks.

**Comment by RandomGOTI** [comment]
Not much of a change if its * or @ or $ at the path start
The solution should be to have the the driver append a wildcard only if the path ends with a `\` ...meaning it will be `\*` as file and folders cannot have a name containing `\`
But : 
![untitled](https://user-images.githubusercontent.com/19516333/188793773-694b008e-2e58-4089-89bd-1504c6002596.png)
so if i have a rule that end with `*.mp4\*` will match that all folder contents
`*.mp4\*.txt` will only match txt files in that folder only
 `*.mp4` will work for a real mp4 files only and not be turned to match `*.mp4gfihfrgioweriog.hwegheb.hgiow.ebhgio` files  
( ͡° ͜◯ ͡°)

**Comment by Simba98** [comment]
> ( ͡° ͜◯ ͡°)

( ͡° ͜◯ ͡°), looks nice. And it would be useful if regex can be supported.

**Comment by DavidXanatos** [comment]
Prepand | to the path this isables the auto adding of *

**Comment by Simba98** [comment]
> Prepand | to the path this isables the auto adding of *

Do you mean prepend | to the path to prevent the auto adding of *?

**Comment by DavidXanatos** [comment]
OpenPipePath=|C:\a\b.txt

**Comment by Simba98** [comment]
Seems like works.
