### ISSUE TITLE
Skype version 8.88.0.401 doesn't run in Sandboxie

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2217]
_Originally posted by @erasmo52 in https://github.com/sandboxie-plus/Sandboxie/discussions/2194#discussioncomment-3541367_

Thanks for your job David. The problem In the Sandboxie Classic 5.58.2 it is not possible to execute last Skype release (8.88.0.401). It happens also in the precedent Sandboxie Classic 5.58.1. But the precedent Skype release (8.87.0.406) work fine under both Sandboxie Classic releases.
Thanks for your attention

Download: https://download.skype.com/s4l/download/win/Skype-8.88.0.401.exe

**Comment by isaak654** [comment]
Workaround: `UseElectronWorkaround=Skype.exe,n`

**Comment by erasmo52** [comment]
Thanks for your reply and your attention to my problem.
Anyway, can you tell me where I must specify the Workaround you indicated me?
Thank you again

**Comment by isaak654** [comment]
> Anyway, can you tell me where I must specify the Workaround you indicated me?

Under the [sandbox] section in the Sandboxie.ini configuration file.

**Comment by isaak654** [comment]
I doubt this can be sustainable in the long run, for example 100 electron apps = 100 additional lines. 🤔

**Comment by isaak654** [comment]
I doubt this can be sustainable in the long run, for example 100 Electron apps = 100 additional lines. 🤔

**Comment by isaak654** [comment]
If you click on the Electron label, you will find three more apps that need it, so it's not exactly an isolated case.
Apparently Sandboxie cannot handle the recent versions of the Electron framework.

**Comment by DavidXanatos** [comment]
I see... in that case I'll remove the entries in the template and instead set the UseElectronWorkaround to be off by default
