### ISSUE TITLE
Auto create Personal Folders for compatibility in Privacy Enhanced sandbox

### ISSUE THREAD

**Issue by Simba98** [sandboxie-plus/Sandboxie#2218]
### Is your feature request related to a problem or use case?

Auto create Documents and etc folders inside the Privacy Enhanced Sandbox.
Technically, we should create %SANDBOX%\user\current\Appdata etc.

Maybe program just simply assumed the %AppData%, Desktop and Documents folder exist.
However, in the Privacy Enhance Sandbox they are not, as a result, some of them will crash.

2. Also, when I try to Right-click and run a run inside the Privacy Enhanced Sandbox, the start.exe cannot find the asked file because it is blocked by Privacy Enhanced Sandbox Mode.

### Describe the solution you'd like

When the Privacy Enhanced Sandbox is created, is/after deleted.
Auto create 
%SANDBOX%\user\current\Appdata
And may be more (I am not sure how these folders are organized if user changed their locations.)
If users are using default location, they are:
%SANDBOX%\user\current\Documents
%SANDBOX%\user\current\Desktop

For 2. add an option to auto-add a temp permission(e.g. Open access or OpenAll Access) for the right-clicked file. 

### Describe alternatives you've considered

For 2., or auto-copy the required file into Privacy Enhanced Sandbox?

**Comment by isaak654** [comment]
This was added in [v1.3.3](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.3.3).
