### ISSUE TITLE
Chrome scanner says failed download - Virus detected (x64 v0.5)

### ISSUE THREAD

**Issue by cherazer65** [sandboxie-plus/Sandboxie#222]
Chrome scanner says failed download - Virus detected (x64 v0.5)

**Comment by NewKidOnTheBlock** [comment]
Looks perfectly fine to me:
https://www.virustotal.com/gui/file/f4a72043ac60e1c3d7a8f2dca515c1f701973abb5d63a8142d07373d03179a1b/detection/f-f4a72043ac60e1c3d7a8f2dca515c1f701973abb5d63a8142d07373d03179a1b-1607613108

**Comment by cherazer65** [comment]
Sorry for not sharing a screenshot, but here we are:

![Screenshot_73](https://user-images.githubusercontent.com/38266527/101796264-c0621d80-3ad6-11eb-8d67-852bf9dde238.png)
![Screenshot_72](https://user-images.githubusercontent.com/38266527/101796268-c0fab400-3ad6-11eb-9f67-54646c33283c.png)

**Comment by NewKidOnTheBlock** [comment]
Strange. 0.5.0 Plus x64 for Win10 is missing the signature:
https://www.virustotal.com/gui/file/b10cda44b80a48ce362af5a167620464c91e772fdec3538020f2b7f31a334e28/detection

**Comment by cherazer65** [comment]
I think it's varying. I've tested the version without the signed driver on virustotal and it gave me only one single false positive that day. But seems not much has changed with the signed driver. Without the signed driver I have at least been able to download and check for myself on VT, but not with the new version. Seems it was one step back regarding virus checkers. But actually really weird

**Comment by NewKidOnTheBlock** [comment]
Hmm. It's down to just 3 now.
BTW, only the driver got signed - the installer is not. That's why it triggers false positives.

**Comment by cherazer65** [comment]
So what to do? Can I still assume that it's safe to use?

**Comment by DavidXanatos** [comment]
> 
> 
> So what to do? Can I still assume that it's safe to use?

Yes.

I'll look into signing also the installers in future.

**Comment by cherazer65** [comment]
Awesome - thank you !!!

**Comment by DavidXanatos** [comment]
pleas try the 0.5.1 release it uses inno setup instead of uInstall

**Comment by cherazer65** [comment]
Oh - thanks - pretty cool. Only one scanner on virustotal reported false positive and McAfee and Chrome accepted the download. Will try and see, if it works for me ;-)))

**Comment by cherazer65** [comment]
Installed, but after starting Chrome sandbox, it threw some errors and finally got stuck here

![image](https://user-images.githubusercontent.com/38266527/101992210-83855a80-3c7f-11eb-9b78-c4698cda1f13.png)
