### ISSUE TITLE
OpenConfPath for HKCR Registry does not work in Privacy Enhanced sandbox

### ISSUE THREAD

**Issue by Simba98** [sandboxie-plus/Sandboxie#2221]
### Describe what you noticed and did

As we know the HKCR Registry key is actually a symbolic link.
Use config:
`OpenConfPath=HKEY_USERS\S_{MY_USER_SID}_Classes\*
OpenConfPath=HKEY_CURRENT_USER\SOFTWARE\Classes\*
OpenConfPath=HKEY_CLASSES_ROOT\*`
And then run Regedit in the sandbox
![image](https://user-images.githubusercontent.com/7941967/189527594-2c4c4040-3ca9-40a9-a898-189d21dc8244.png)
![image](https://user-images.githubusercontent.com/7941967/189527901-96a254c7-f857-4377-8e54-195b6f8cb012.png)

But the Regedit still can not see my personal HKCR keys, which is in `HKEY_USERS\S_{MY_USER_SID}_Classes\`.
Incorrect:
![image](https://user-images.githubusercontent.com/7941967/189528076-ab8c29cf-19f8-4fb3-a400-5ae67ab25703.png)
Outside:
![image](https://user-images.githubusercontent.com/7941967/189528097-ff3f613f-2747-4953-b621-1f0326c94ea4.png)
![image](https://user-images.githubusercontent.com/7941967/189528220-929957e5-88cc-4f86-9e1f-af4612301ab2.png)
![image](https://user-images.githubusercontent.com/7941967/189528243-489a4470-659f-4584-91dc-c18d10d62482.png)

It works well in standard sandbox.
![image](https://user-images.githubusercontent.com/7941967/189528336-7fe4cf3a-2bd6-40a2-ad49-b1e468f32ced.png)

### How often did you encounter it so far?

Everytime

### Affected program

Everyone

### Download link

NA

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

See the correct HKCR key, which should include,
1. Necessary HKLM classes keys (Default Behavior)
2. Authorized HKCU classes keys which 

### What is your Windows edition and version?

Windows 10 Enterprise 21H1

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

No, but default MD.

### What version of Sandboxie are you running?

SBIE Plus 1.3.2

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

NA

### In which sandbox type you have this problem?

In a Sandbox with data protection (blue sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

NA, default and new and clean Windows 10 install

### Sandboxie.ini configuration

```shell
[MySandbox]
OpenConfPath=HKEY_USERS\S_{MY_USER_SID}_Classes\*
OpenConfPath=HKEY_CURRENT_USER\SOFTWARE\Classes\*
OpenConfPath=HKEY_CLASSES_ROOT\*
```

**Comment by DavidXanatos** [comment]
To achieve what you want you need to use
```NormalKeyPath=\REGISTRY\USER\*_Classes\*```

The problem with OpenConfPath is that when there is a key under HKEY_USERS\Sandbox_TestBox\user\current_classes it will be opened and enumerated, the OpenKeyPath (of which OpenConfPath is just variant) expects there be no keys under open paths, however the current_classes gets always pre created during box initialization.

If you don't want to be able to write to your real _Classes the NormalKeyPath is the better choice anyways.
