### ISSUE TITLE
no network connection when updating browser

### ISSUE THREAD

**Issue by sailfish009** [sandboxie-plus/Sandboxie#2222]
### Describe what you noticed and did

1. DefaultBox -> Run -> Default Web Browser (firefox nightly 64bit 106.0a1)
2. Do Web Browser Update (program restart)
3. Go to google.com
4. 
![image](https://user-images.githubusercontent.com/17582766/189554104-fbdfca9c-db98-4066-910c-bab6a994d58e.png)

### How often did you encounter it so far?

Whenever i update web browser

### Affected program

firefox nightly 64bit 106.0a1

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Even when updating the web browser, the network connection should be normal.

After re-installing the program, when you run the updated web browser again, the network connection is normal. Perhaps the program(Sandboxie Plus 1.3.2) misunderstands the web browser update behavior as a forgery behavior.

### What is your Windows edition and version?

Windows 7 Sp1 64bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Avira antivirus, tinywall 3.2.5

### What version of Sandboxie are you running?

Sandboxie Plus 1.3.2 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

NA

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
For me ff 106.0b1 and 106.0b2 work just fine,
does any own else have this problem?

**Comment by sailfish009** [comment]
@DavidXanatos Hello, I have to add one more thing that could be the cause. That error only occurs while a program called tinywall is running. Only programs registered in tinywall program can access the web, but tinywall doesn't seem to be aware of Firefox running inside sandboxie.

**Comment by paradoxicallist** [comment]
> @DavidXanatos Hello, I have to add one more thing that could be the cause. That error only occurs while a program called tinywall is running. Only programs registered in tinywall program can access the web, but tinywall doesn't seem to be aware of Firefox running inside sandboxie.
Tor Browser 12.0a2 x64
Sandboxie-Plus 1.3.4 Security Hardened Sandbox (orange sandbox)
Windows 10 21H2 x64 EN

I run TinyWall 3.2.5 too and have no network issues running alongside Sandboxie.
