### ISSUE TITLE
Move sandbox UI bug

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2225]
### Describe what you noticed and did

Move sandbox is bugged if the target is a subgroup, the box will be moved to the group instead

Group
-Subgroup

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

.

### What is your Windows edition and version?

.

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.3.3 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

~1.2.8B

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by okrc** [comment]
Hi, 请尝试这个构建以判断是否解决了该问题？
Hi, please try [this build](https://github.com/okrc/Sandboxie/actions/runs/3041797492) to determine if it is resolved?

**Comment by RandomGOTI** [comment]
> Hi, 请尝试这个构建以判断是否解决了该问题？ Hi, please try [this build](https://github.com/okrc/Sandboxie/actions/runs/3041797492) to determine if it is resolved?

Confirming that the sandman from that build does have the issue fixed 👍
