### ISSUE TITLE
Sandboxie Plus 1.3.3 several issues

### ISSUE THREAD

**Issue by Luro223** [sandboxie-plus/Sandboxie#2230]
### Describe what you noticed and did

Hello Dear developer of sandboxie-plus!
I encountered several issues while using the latest version(1.3.3) since version 1.1.3
First Issue:
If you try to enable the security enhancements > launch any app in this sandboxie > disable security enhancements > restart sandboxie-plus(Maintenance > stop all, uninstall all) then start sandboxie again it will say "The program UseRuleSpecificify stated in box Temp_009 will be terminated in 5
minutes because the box was configured to use features exclusively available to
project suppotters." even though I disable all features for supporter
Second issue(I think global):
I use XYPlorer instead of Explorer for sandboxed apps but If I try to hover mouse > RTF file XYPlorer will be instantly terminated, I think it's an issue related to SYScalls that might affect other apps too
Here's the video:
https://user-images.githubusercontent.com/42772886/189895933-b66808d9-7266-4f01-8b3e-baa8dfcec3a3.mp4

### How often did you encounter it so far?

Always with specific action

### Affected program

XYPlorer 23.50.0.0

### Download link

https://www.xyplorer.com/

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

First:
Expected behavior for sandboxie with standard isolation

Second:
By hovering the mouse to RTF file from XYPlorer It must show the info about file (Name, Type, Size, Date of modify) without any crashes

### What is your Windows edition and version?

Windows 10 17134.81 64-BIT

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

NA

### What version of Sandboxie are you running?

Sandboxie Plus(Portable) V1.3.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Since Sanboxie Plus 1.1.3

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Nothing since Classic Sandboxie V5.31.6

### Trace log

https://gist.github.com/Luro223/ff80a84c4d30b7385bef3d25877abf3d

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=RpcPortBindings
Template=RTSS
Template=ActualWindowManager
Template=WindowsRasMan
Template=Kaspersky
Template=Proxifier
Template=7zipShellEx
Template=WindowsLive
Template=InternetDownloadManager
Template=OfficeLicensing
FileRootPath=Q:\Sandbox\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
EnableObjectFiltering=n

[UserSettings_08DA01C0]

SbieCtrl_UserName=user
SbieCtrl_NextUpdateCheck=1626104363
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_HideMessage=*
SbieCtrl_WindowCoords=200,150,660,450
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=n
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=n
SbieCtrl_AddSendToMenu=n
SbieCtrl_RecoverTarget=H:\AWZ
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_BoxExpandedView=Temp_009
SbieCtrl_AutoStartAgent=SandMan.exe

[Temp_009]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
BoxNameTitle=n
CopyLimitKb=81920
UseRuleSpecificity=y
```

**Comment by offhub** [comment]
First: `UseRuleSpecificity=y` needs to be removed from your config.

**Comment by offhub** [comment]
Second: Ok, tested with your config.

XYPlorer crashes when "Show Hover Box" selected. (Tested with 1.3.2 and 1.3.3)

![xycr](https://user-images.githubusercontent.com/6871698/189981769-690407d2-3ca2-4072-add2-bce1425b7e40.png)

**Comment by Luro223** [comment]
> Second: Ok, tested with your config.
> 
> XYPlorer crashes when "Show Hover Box" selected. (Tested with 1.3.2 and 1.3.3)

Yes, as I said the issue related to sandboxie(thumbnail previrew while hovering) this issue is still related to sandboxie it might be a compatibility for 1 app or a glocal issue for apps with similar functionality
Check tracelog you can clearly see SetError: 997 and SetError: 1400 before crashing

**Comment by Luro223** [comment]
Looks like the XYplorer is not as widely used
And the second issue is small too as a temporary workaround you can delete `UseRuleSpecificity=y` string in `[sandbox]` after using the features for enhanced isolation
Well I will close this issue in 3 days if there's no response

**Comment by DavidXanatos** [comment]
which ist the first build to introduce the xyplorer incompatibility?

About the rule specificity, i will not change anything around this handling when a user has this enabled explicitly for some manual rules it would not be good to disable it.

**Comment by Luro223** [comment]
@DavidXanatos Currently I have 23.60.0000
How to reproduce : open XYPlorer; go to Tools>Configuration>File Info Tips & Hover Box>Check hover box then go to Select Item Types(same tab) and check Office Files
Then hover mouse to any file for several seconds and xyplorer will crash without any sandboxie messages
About the rule specificity, currently I am not supporter but If I enable and disable some supporter-specific features the `UseRuleSpecificity=y` won't be deleted so I have to delete it manually by editing the ini

**Comment by Luro223** [comment]
Updated tracelog(same error) for 23.60 :
[1.txt](https://github.com/sandboxie-plus/Sandboxie/files/9616424/1.txt)

**Comment by Luro223** [comment]
@DavidXanatos I think the same issue for all versions
Tried: 0.4.1, 0.8.0, 1.0.0, 1.0.15, 1.1.3, 1.2.8b, 1.3.1, 1.3.2, 1.3.3, 1.3.4
https://user-images.githubusercontent.com/42772886/191527226-799279c6-3031-497b-adb9-1d5bcf54e637.mp4

**Comment by DavidXanatos** [comment]
the xyplore issue is unrelated to RuleSpecificity and will be fixed in the next build

**Comment by Luro223** [comment]
Ok, thanks 👍

**Comment by Luro223** [comment]
Xyplorer now works perfectly, thanks for your work!
Have a great time

**Comment by AJ-learning** [comment]
I also had the same issue in Sandboxie-Plus-x64-v1.11.4. 

The app kept reportingg that "The program UseRuleSpecificity started in box DefaultBox will be terminated in 5 minutes because the box was configured to use features exclusively available to project supporters." Even after turning off all "project supporter" features and rules in the settings. 

Thanks to the discussion here, I went into the Sandboxie.ini file and changed the value of UseRuleSpecificity=y to =n and this seems to have resolved it so far.
