### ISSUE TITLE
Sandboxie-Plus.ini keep old information

### ISSUE THREAD

**Issue by blap** [sandboxie-plus/Sandboxie#2231]
### Describe what you noticed and did

What I did:
Sandbox -> create new box
right click -> rename sandbox to whatever
or
right click -> remove sandbox

What I notice:
Sandboxie-Plus.ini keep the information of the old sandboxes names in "BoxDisplayOrder", "BoxCollapsedView" and "[SizeCache]". So I got random problems if I try to use the old names again.

### How often did you encounter it so far?

Always

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Sandboxie-Plus.ini remove the old sandbox name that was renamed or deleted.

### What is your Windows edition and version?

Windows 10 Home 64 bits

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.3.3.exe

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

None.

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=C:\Users\Admin\0.Programas\Sandbox\%SANDBOX%
NetworkEnableWFP=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=Edge_Win11Fix
Template=7zipShellEx
SandboxieLogon=y
InjectDll=...\logapi32.dll
InjectDll64=...\logapi64.dll
OpenPipePath=\Device\NamedPipe\LogAPI
StartRunAlertDenied=y
AlertProcess=EXCEL.EXE
AlertProcess=WINWORD.EXE
AlertProcess=POWERPNT.EXE
AlertProcess=notepad++.exe
AlertProcess=mpc-hc64.exe
AlertProcess=PDFXEdit.exe
AlertProcess=PDFXTools.exe
AlertProcess=Ketarin.exe
AlertProcess=chrome.exe
AlertProcess=bdcam.exe
AlertProcess=loader.exe
AlertProcess=Zoom.exe
AlertProcess=Teams.exe
AlertProcess=thunderbird.exe
AlertProcess=firefox.exe
AlertProcess=WhatsApp.exe
AlertProcess=4t-min.exe
AlertProcess=4t-min64.exe
AlertProcess=qbittorrent.exe
AlertProcess=Telegram.exe

[UserSettings_0C02020A]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by okrc** [comment]
这里bug好多呀！:rofl:
大多都是 v1.2.2 开始引入的。
能说说[SizeCache]在哪吗？我没有发现这个。

There are many bugs here!:rofl:
Many bugs exist from v1.2.2 onwards.
Can you tell me where [SizeCache] is? I didn't find this.

**Comment by blap** [comment]
Sandboxie-Plus.ini

I think `[SizeCache]` will only appear if in global settings you mark the option "Count and display the disk space..."

**Comment by okrc** [comment]
> I think `[SizeCache]` will only appear if in global settings you mark the option "Count and display the disk space..."
谢谢，我已经打开了它，但是令人沮丧的是，我还是没发现 `SizeCache`
Thanks, I've opened it, but frustratingly, I still don't find `SizeCache`

**Comment by blap** [comment]
> > I think `[SizeCache]` will only appear if in global settings you mark the option "Count and display the disk space..."
> 
> 谢谢，我已经打开了它，但是令人沮丧的是，我还是没发现 `SizeCache` Thanks, I've opened it, but frustratingly, I still don't find `SizeCache`

After mark this option, try F5 to show the space info in the column INFO.
My Sandboxie-Plus.ini:

[Options]
UiLanguage=en
NextCheckForUpdates=1663761419
PortableStart=1
ViewMode=1
UseDarkTheme=1
WizardLevel=1
DPIScaling=1
UseFusionTheme=2
AltRowColors=false
UseBackground=2
LargeIcons=2
NoIcons=2
OptionTree=2
ColorBoxIcons=false
FontScaling=100
RunInDefaultBox=false
ShowNotifications=true
OpenUrlsSandboxed=1
ShowRecovery=false
InstantRecovery=true
RecoveryOnTop=true
UseAsyncBoxOps=true
EnablePanicKey=false
PanicKeySequence=Shift+Pause
WatchBoxSize=true
WatchIni=true
SysTrayIcon=1
SysTrayFilter=0
CompactTray=false
AutoBoxOpsNotify=false
PortableRootDir=1
AutoRunSoftCompat=true
CheckForUpdates=2
DownloadUpdates=0
UpdateChannel=0
NoSupportCheck=false
KeepTerminated=false
ShowAllSessions=true
ShowFilePanel=true
PortableStop=1
NoEditInfo=false
WarnTerminate=1

[UIConfig]
DisabledRecovery=false
DisableMessages=false
BoxDisplayOrder="DefaultBox,Chrome,Chromium,Email_Thunderbird,Firefox,KETARIN,KLite_Codec_Pack_Mega,MQL5,NotepadPlus,Office_Pro_Plus_2019,PDFXChange_Pro,platform_tools,Python_3_10_7,Python_3_10_7_site,Python_3_10_7_estrategia,qbittorrent,Telegram,Video_Conferencia,WhatsApp,Rescue_and_Smart_Assistant"
BoxCollapsedView="DefaultBox,Chrome,Chromium,Email_Thunderbird,Firefox,KETARIN,KLite_Codec_Pack_Mega,MQL5,NotepadPlus,Office_Pro_Plus_2019,PDFXChange_Pro,platform_tools,Python_3_10_7,Python_3_10_7_site,Python_3_10_7_estrategia,qbittorrent,Telegram,Video_Conferencia,WhatsApp,Rescue_and_Smart_Assistant"

[MainWindow]
Window_Geometry=:ByteArray:AdnQywADAAD_________-AAABVYAAALYAAABawAAAHwAAARxAAACewAAAAACAAAABVYAAAAAAAAAFwAABVUAAALX
Window_State=:ByteArray:AAAA_wAAAAD9AAAAAAAABVYAAAKXAAAABAAAAAQAAAAIAAAACPwAAAAA
LogList_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUwAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAAE6AAAAAEAAAAAAAAD6AAAAABk
RecoveryLog_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUwAAAADAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAADAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAEhAAAAAEAAAAAAAAD6AAAAABk
Log_Splitter=:ByteArray:AAAA_wAAAAEAAAACAAABKgAAAT4B_____wEAAAACAA
Panel_Splitter=:ByteArray:AAAA_wAAAAEAAAACAAADgQAAAc0B_____wEAAAABAA
LogTab=0
Monitor_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAnwAAAAEAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAAMwAAAAEAAAAAAAAAPAAAAAEAAAAAAAAANwAAAAEAAAAAAAAB1gAAAAEAAAAAAAAD6AAAAAA6
TraceLog_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAEAQAAAAEAAAAAAAAA_gAABUoAAAAEAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAAAAAAAAEAAAAAAAAA6AAAAAEAAAAAAAAARAAAAAEAAAAAAAAEHgAAAAEAAAAAAAAD6AAAAAAj
FileTree_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAgcAAAAEAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAA2wAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAD6AAAAABk
BoxTree_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA30AAAAGAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAGAAABLAAAAAEAAAAAAAAARgAAAAEAAAAAAAAARgAAAAEAAAAAAAAARgAAAAEAAAAAAAAAQgAAAAEAAAAAAAABPQAAAAEAAAAAAAAD6AAAAACP
BoxTree_UseOrder=true

[SettingsWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAFRAAAAdQAABIsAAAJkAAABUgAAAJQAAASKAAACYwAAAAAAAAAABVYAAAFSAAAAlAAABIoAAAJj

[PopUpWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAFqAAAAXQAAA-sAAAJcAAABawAAAHwAAAPqAAACWwAAAAAAAAAABVYAAAFrAAAAfAAAA-oAAAJb

[SizeCache]
Chrome=1466181982
Chromium=1034056845
DefaultBox=0
Email_Thunderbird=2827762954
Firefox=583592359
KETARIN=4092353879
KLite_Codec_Pack_Mega=250035950
MQL5=1104359746
NotepadPlus=20500642
Office_Pro_Plus_2019=6335176940
PDFXChange_Pro=2790397791
Python_3_10_7=829265712
Python_3_10_7_site=1551094182
Telegram=630626016
Video_Conferencia=1469978104
WhatsApp=1456404850
platform_tools=17496238
qbittorrent=427308998
Python_3_10_7_estrategia=854117433
Rescue_and_Smart_Assistant=1256068606

[RecoveryWindow]
LastTarget=-1
Window_Geometry=:ByteArray:AdnQywADAAAAAAGqAAAAmQAAA6sAAAIgAAABqwAAALgAAAOqAAACHwAAAAAAAAAABVYAAAGrAAAAuAAAA6oAAAIf
TreeView_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAeYAAAADAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAADAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAABHgAAAAEAAAAAAAAD6AAAAABk

[OptionsWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAEfAAAAVAAABD0AAAJlAAABIAAAAHMAAAQ8AAACZAAAAAAAAAAABVYAAAEgAAAAcwAABDwAAAJk
Run_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMgAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAD6AAAAABk
Triggers_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdEAAAADAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAADAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAABCQAAAAEAAAAAAAAD6AAAAABk
Groups_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAABAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAABAAAAZAAAAAEAAAAAAAAD6AAAAABk
Forced_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAecAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABgwAAAAEAAAAAAAAD6AAAAABk
Stop_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAdoAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABdgAAAAEAAAAAAAAD6AAAAABk
Start_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAfQAAAABAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAABAAAB9AAAAAEAAAAAAAAD6AAAAABk
INet_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAeoAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABhgAAAAEAAAAAAAAD6AAAAABk
NetFw_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfQAAAAFAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAFAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAD6AAAAABk
Access_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAd0AAAAEAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAsQAAAAEAAAAAAAAD6AAAAABk
Recovery_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAecAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABgwAAAAEAAAAAAAAD6AAAAABk
Templates_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAcwAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABaAAAAAEAAAAAAAAD6AAAAABk

[SnapshotsWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAGcAAAAqwAAA9gAAAJtAAABnAAAAKsAAAPYAAACbQAAAAAAAAAABVYAAAGcAAAAqwAAA9gAAAJt

**Comment by okrc** [comment]
@blap Thanks, I think I've found it.

**Comment by okrc** [comment]
Hi, 请尝试这个构建以判断是否解决了该问题？在这之前，你应该先手动删除陈旧的数据。
Hi, please try [this build](https://github.com/sandboxie-plus/Sandboxie/actions/runs/3059238034) to determine if it is resolved? Before doing so, you should delete the stale data manually.

**Comment by blap** [comment]
> Hi, 请尝试这个构建以判断是否解决了该问题？在这之前，你应该先手动删除陈旧的数据。 Hi, please try [this build](https://github.com/sandboxie-plus/Sandboxie/actions/runs/3059238034) to determine if it is resolved? Before doing so, you should delete the stale data manually.

I think it is solved now. 
Thank you very much!

**Comment by blap** [comment]
> Hi, 请尝试这个构建以判断是否解决了该问题？在这之前，你应该先手动删除陈旧的数据。 Hi, please try [this build](https://github.com/sandboxie-plus/Sandboxie/actions/runs/3059238034) to determine if it is resolved? Before doing so, you should delete the stale data manually.

You solved the problem.
I will close this issue.
Thanks.
