### ISSUE TITLE
Option to import/export sandbox

### ISSUE THREAD

**Issue by blap** [sandboxie-plus/Sandboxie#2232]
### Is your feature request related to a problem or use case?

If you like to share a sandbox, you need to manually copy INI information and files.

### Describe the solution you'd like

Just a menu import/export sandbox.
It will automatically copy files and INI configuration to a zip file (or whatever) to export a sandbox.

**Comment by DavidXanatos** [comment]
This feature is scheduled for build 1.6.0
and for patreons on tears 10$ and above already now available in a private preview build, 
it uses 7z

**Comment by blap** [comment]
> This feature is scheduled for build 1.6.0 and for patreons on tears 10$ and above already now available in a private preview build, it uses 7z

Is there a place where I can find the diferences for patreons?
like the tag ["future development"](https://github.com/sandboxie-plus/Sandboxie/issues?q=label%3A%22future+development%22)?

**Comment by DavidXanatos** [comment]
there is the road-map thread: https://www.wilderssecurity.com/threads/sandboxie-roadmap.445545/
normally if a feature has a version number assigned that means its already ready for release and probably available as an internal build.

**Comment by blap** [comment]
Thanks!
