### ISSUE TITLE
Cannot start signal messanger

### ISSUE THREAD

**Issue by omatrycy** [sandboxie-plus/Sandboxie#2235]
### Describe what you noticed and did

1. Create default sandbox
2. Set admin rights for sandbox (drop rights from Administrations; make applications think they are running elevated) in admin rights tab
3. install signal in sandboxie 
4. cannot open signal

try to open in cmd from from windows (outside sandboxie) - doesnt' work:

> PS C:\Sandbox\User\signal\user\current\AppData\Local\Programs\signal-desktop> .\Signal.exe
> Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
> NODE_ENV production
> NODE_CONFIG_DIR C:\Users\User\AppData\Local\Programs\signal-desktop\resources\app.asar\config
> NODE_CONFIG {}
> ALLOW_CONFIG_MUTATIONS undefined
> HOSTNAME undefined
> NODE_APP_INSTANCE undefined
> SUPPRESS_NO_CONFIG_WARNING undefined
> SIGNAL_ENABLE_HTTP undefined
> userData: C:\Users\User\AppData\Roaming\Signal
> config/get: Successfully read user config file
> config/get: Successfully read ephemeral config file
> [5568:0915/114206.780:ERROR:network_change_notifier_win.cc(224)] WSALookupServiceBegin failed with: 0
> [1672:0915/114206.966:ERROR:network_change_notifier_win.cc(224)] WSALookupServiceBegin failed with: 0
> [5568:0915/114207.617:FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.

add param  **--in-process-gpu** - signal starts and works correctly

> PS C:\Sandbox\User\signal\user\current\AppData\Local\Programs\signal-desktop> .\Signal.exe  --in-process-gpu
> Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
> NODE_ENV production
> NODE_CONFIG_DIR C:\Users\User\AppData\Local\Programs\signal-desktop\resources\app.asar\config
> NODE_CONFIG {}
> ALLOW_CONFIG_MUTATIONS undefined
> HOSTNAME undefined
> NODE_APP_INSTANCE undefined
> SUPPRESS_NO_CONFIG_WARNING undefined
> SIGNAL_ENABLE_HTTP undefined
> userData: C:\Users\User\AppData\Roaming\Signal
> config/get: Successfully read user config file
> config/get: Successfully read ephemeral config file
> [3888:0915/114510.415:ERROR:network_change_notifier_win.cc(224)] WSALookupServiceBegin failed with: 0
> [2036:0915/114510.629:ERROR:network_change_notifier_win.cc(224)] WSALookupServiceBegin failed with: 0
> (node:2476) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use Signal --trace-deprecation ... to show where the warning was created)

Param found by error `FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.` on [stach overflow](https://stackoverflow.com/questions/70893329/gitkraken-crash-on-fedora-gpu-process-isnt-usable-goodbye)

Check in sandboxie-plus versions:
- 1.0.22 - works
- 1.1.0 - works
- 1.1.1 - doesn't work
- 1.3.2 - doesn't work
no check other versions

### How often did you encounter it so far?

Always

### Affected program

Signal messanger, version 5.59.0

### Download link

https://updates.signal.org/desktop/signal-desktop-win-5.59.0.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Signal starts and works.

### What is your Windows edition and version?

Windows 10 Pro 21H2 x64; check also on Windows 11 dev container on Hyper-V 

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

MS Defender Antivirus

### What version of Sandboxie are you running?

1.3.2 x64

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than v1.0.22 / 5.55.22.

### Is it a regression?

Since sandboxie-plus 1.1.1

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
Start sandboxie plus instalation + box configuration:

Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
UsePrivacyMode=n
BoxNameTitle=n
DropAdminRights=y
FakeAdminRights=y
CopyLimitKb=81920
```

**Comment by Luro223** [comment]
@omatrycy try to add the line on your `[sandbox]` in Sandboxie.ini
UseElectronWorkaround=Program.exe,n
where program.exe is your package name

**Comment by omatrycy** [comment]
> @omatrycy try to add the line on your [sandbox] in Sandboxie.ini `UseElectronWorkaround=Program.exe,n` where program.exe is your package name

hi @Luro223, your solution works, thanks ;)

`UseElectronWorkaround=Signal.exe,n`

**Comment by Luro223** [comment]
@omatrycy 
Always glad to help, you can close the issue
Have a great time!
