### ISSUE TITLE
Incorrect drive letter related to Sandbox file system root

### ISSUE THREAD

**Issue by Luro223** [sandboxie-plus/Sandboxie#2238]
### Describe what you noticed and did

Whenever you try to launch sandboxie in portable mode the message describes that the main sandbox location is always displayed as C:
Example when you choose the drive letter H: for sandbox root it will still say "No will choose: C:\Sandbox" even though I already changed the root location

### How often did you encounter it so far?

Always

### Affected program

NA

### Download link

NA

### Where is the program located?

Not relevant to my request.

### Expected behavior

The sandboxie must suggest the last saved file system root instead of C:

### What is your Windows edition and version?

Windows 10 1803 17134.81

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

NA

### What version of Sandboxie are you running?

Sandboxie 1.3.3

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

Sandboxie-plus 0.7.3

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=RpcPortBindings
Template=RTSS
Template=ActualWindowManager
Template=WindowsRasMan
Template=Kaspersky
Template=Proxifier
Template=7zipShellEx
Template=WindowsLive
Template=InternetDownloadManager
Template=OfficeLicensing
FileRootPath=Q:\Sandbox\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
EnableObjectFiltering=n

[UserSettings_08DA01C0]

SbieCtrl_UserName=user
SbieCtrl_NextUpdateCheck=1626104363
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_HideMessage=*
SbieCtrl_WindowCoords=200,150,660,450
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=n
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=n
SbieCtrl_AddSendToMenu=n
SbieCtrl_RecoverTarget=H:\AWZ
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_BoxExpandedView=Temp_009
SbieCtrl_AutoStartAgent=SandMan.exe

[Temp_009]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
BoxNameTitle=n
CopyLimitKb=81920
```

**Comment by Luro223** [comment]
@DavidXanatos can you please review this issue?

**Comment by offhub** [comment]
`Options > Advanced Config > Portable root folder` make it checked or select "Don't show this message again" from the dialog and it won't ask you again.  If you don't then it will ask you every time... 

From the code: (BoxPath is the parent folder and the second one is C:\Sandbox

```
tr("Sandboxie-Plus was started in portable mode, do you want to put the Sandbox folder into its parent directory?\nYes will choose: %1\nNo will choose: %2")
.arg(BoxPath)
.arg("C:\\Sandbox") // todo resolve os drive properly
```

![Ig0SMQcGoa](https://user-images.githubusercontent.com/6871698/190869465-601d86c2-efc2-46a6-895c-e604185473ad.png)

**Comment by Luro223** [comment]
@offhub is not a solution but a temporary workaround because I need this message

**Comment by DavidXanatos** [comment]
done in buildl 1.3.4 and later this message will show the right path

**Comment by Luro223** [comment]
Awesome thanks dear DavidXanatos
Have a great time!

**Comment by Luro223** [comment]
Open until fixed

**Comment by Luro223** [comment]
@DavidXanatos is it supposed to be like this?:
![004](https://user-images.githubusercontent.com/42772886/191130670-b5eab68b-6f10-42ec-91f8-fbc9de9813c5.png)
(BoxName)

**Comment by DavidXanatos** [comment]
yes although i'll add \Boxname also to the previouse line

**Comment by Luro223** [comment]
> yes although i'll add \Boxname also to the previouse line

Thanks 👍
