### ISSUE TITLE
The network firewall record is not in effect.

### ISSUE THREAD

**Issue by okrc** [sandboxie-plus/Sandboxie#2247]
### Describe what you noticed and did

This record does not take effect when a comma is used to separate multiple ports or port segments.
Examples.
`80,81`
`26000-27000,52800`

A separate port segment is in effect.
Examples.
`36000-37000`
`443`

```
NetworkAccess=Block;Port=21100,21100;Address=172.17.115.213;Protocol=TCP
NetworkAccess=Block;Port=21000;Address=172.17.115.213;Protocol=TCP
NetworkAccess=Block;Port=10920,10921;Address=172.17.115.213;Protocol=Any
NetworkAccess=Block;Port=10920,10921;Address=172.17.115.213;Protocol=Any
NetworkAccess=Block;Port=10200-10300,10340;Address=172.17.115.213;Protocol=Any
NetworkAccess=Block;Port=8090-8900;Address=172.17.115.213;Protocol=Any
NetworkAccess=Block;Port=8081;Address=172.17.115.213;Protocol=Any
NetworkAccess=Block;Port=8080;Address=172.17.115.213;Protocol=Any
```
![image](https://user-images.githubusercontent.com/29057533/190945140-72c7878a-7a4f-4743-a0ee-828cb7c87fa2.png)

### Affected program

*

### Download link

*

### Where is the program located?

Not relevant to my request.

### Expected behavior

*

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Hongrong

### What version of Sandboxie are you running?

Sandboxie-Plus v1.3.3 64, master

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
indeed, ```,``` can only be used when a program is already specified to to limitations of the parser so you need to sue soemthignlike
NetworkAccess=*,Block;Port=80,430
instead of
NetworkAccess=Block;Port=80,430

I'll fix the UI such that in such cases it created properly the *, prefix

**Comment by okrc** [comment]
I tried adding the *,prefix and it reproduced it as well.

**Comment by DavidXanatos** [comment]
are you sure?
with ```NetworkAccess=*,Block;Port=80,443```
all websites are inaccessible

**Comment by okrc** [comment]
我怀疑语言产生了歧义，我的英文不是很好。我是说这条记录不会生效。
I suspect that the language is ambiguous and my English is not very good. I mean this record will not be valid.

**Comment by okrc** [comment]
Sorry, I think I know the problem. Here is `*;` not `*,`

**Comment by DavidXanatos** [comment]
try the entry like this
```
NetworkAccess=*,Block;Port=80,443
```

**Comment by okrc** [comment]
Yes, it worked, I will try to test it again in a new environment.
