### ISSUE TITLE
[Plus 1.3.4] SBIE2205 Service not implemented:  Manifest

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2252]
### Describe what you noticed and did

PreferExternalManifest=y

|Message|                                                                     
SBIE2205 Service not implemented:  Manifest1.txt   
SBIE2205 Service not implemented:  Manifest2.txt   

Run sandboxed explorer or anything else

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

No SBIE2205 Service not implemented:  Manifest messages

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.3.4 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Plus 1.3.3 x64

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
PreferExternalManifest=y

*Clean config with nothing in global and with just defaultbox + PreferExternalManifest
```

**Comment by Luro223** [comment]
@RandomGOTI Can't reproduce the issue also why do you want to use the deprecated behaviour?

**Comment by Luro223** [comment]
@isaak654 Issue has been reproduced
1.3.3 : OK
1.3.4 : SBIE2205
![003](https://user-images.githubusercontent.com/42772886/191130352-6199351a-b63b-44d7-8f4e-e378f2de81b9.png)

**Comment by reraikes** [comment]
Also occurs repeatedly on Edge/Windows 8.1:

SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt
SBIE2205 Service not implemented:  Manifest1.txt
SBIE2205 Service not implemented:  Manifest2.txt

**Comment by isaak654** [comment]
This alone would require a v1.3.5 / 5.58.5.

Also reported in https://www.wilderssecurity.com/threads/sandboxie-plus-v1-3-4.447639/#post-3105631
