### ISSUE TITLE
Differention between Sandboxie Plus and Sandboxie

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#226]
After explaining their general differences (#165) and clarifying you don't want to merge them (#172), will you consider differentiate Sandboxie Plus from Sandboxie in the Change Logs?

You have a lot of releases, which is great, and their Change Logs are quite detailed, which is great too. But it seems almost impossible to understand which what's new items relate to Sandboxie Plus and which to Sandboxie.
It could be quite helpful if you wrote what's new/changed/fixed for each version independently, like:

### Sandboxie Plus
 ...
### Sandboxie
 ...
### Sandboxie Plus
 ...
### Sandboxie
 ...
### Sandboxie Plus
...
### Sandboxie
 ...

**Comment by DavidXanatos** [comment]
As the classical UI is deprecated and provided only for legacy use there is no point in splitting the change log.
I will not add any new major features to SbieCtrl.exe
Features like Snapshots, user interactive prompts that will be expanded upon in future builds, and other will not be supported when using SbieCtrl.exe

The reason for that is two fold,
for once the UI is really dated and not that user friendly, for example you need to save each page in the sandbox settings before you can switch to an other, etc...
second, and more important, its immeasurably more convenient to create and maintain Qt based UI's that those obsolete MFC based UI's from the late 90's.
I have to be efficient with my time and every minute not wasted on cumbersome 90's technology is a minute I can spend on actually relevant core functionality.

So ideally all users should move to the Plus build as its now no longer missing any features in comparison with the classical UI.

To help you differentiate in the change log for yourself: 
If a feature sounds like it is in any way UI related it won't be available in the legacy build. 
Features that can be set using the ini manually will work in the legacy build, but you will have to configure them in the ini.
Any security or compatibility improvements are implemented in the shared components and are available in booth builds.
As simple as that.
