### ISSUE TITLE
Tor Browser 12.0a1-12.0a2 (alpha) can't run in Sandboxie-plus 1.3.3-1.3.4

### ISSUE THREAD

**Issue by lulMeow** [sandboxie-plus/Sandboxie#2264]
### Describe what you noticed and did

the problem is exactly same as here
https://github.com/sandboxie-plus/Sandboxie/issues/1116
the same screenshot, description and repro steps apply to this as well. 

### How often did you encounter it so far?

everytime

### Affected program

Tor Browser 12.0a1-12.0a2 (alpha versions)

### Download link

https://www.torproject.org/download/

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Tor browser bundle run normally as it would outside Sandboxie

### What is your Windows edition and version?

Windows 11 pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

[1.3.3](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.3.3) - [1.3.4](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.3.4)

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Windows Security configurations. Hypervisor Enforced Code Integrity, Mandatory ASLR (Address space layout randomization), Attack Surface Reduction rules
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide
https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-hvci-enablement

### Sandboxie.ini configuration

No custom configuration applied

**Comment by Luro223** [comment]
@KitCat36 check with 1.3.4 then post results here

**Comment by paradoxicallist** [comment]
I can confirm that Tor Browser x64 w0rks on Sbie 1.3.4

**Comment by Luro223** [comment]
@paradoxicallist yeah @KitCat36 has not even tested tor.
Anyways you can close the issue if everything works for you

**Comment by RandomGOTI** [comment]
@KitCat36 stable release should still work (i have no clue about w11) with latest sandboxie, https://www.torproject.org/dist/torbrowser/11.5.2/torbrowser-install-win64-11.5.2_en-US.exe 11.5.2 (based on Mozilla Firefox 91.13.0esr) (64-bit)

**Comment by isaak654** [comment]
I couldn't reproduce this with the following systems:
- Windows 11 22H2 25179.1000 and Windows 10 21H2 19044.1889
- Tor Browser version 12.0a2 x64
- Sandboxie Plus 1.3.4 x64

Please share your exact Windows 11 build number and your Sandboxie.ini configuration file.

**Comment by DavidXanatos** [comment]
the crash will be fixed in the next build

**Comment by isaak654** [comment]
@KitCat36 
At first glance, the mentioned crashes don't seem to be strictly inherent with your initial report. 
This is the Sandman's recovery fix: https://github.com/sandboxie-plus/Sandboxie/commit/e9e21c215ed87cf1d5aa999407ab2f99d5da9e4a

**Comment by isaak654** [comment]
@KitCat36 
At first glance, the mentioned crashes don't seem to be strictly inherent with your initial report. 
He only mentioned the following Sandman's recovery fix: https://github.com/sandboxie-plus/Sandboxie/commit/e9e21c215ed87cf1d5aa999407ab2f99d5da9e4a

**Comment by isaak654** [comment]
> what should I do exactly?

At this time, I could only suggest to disable your security policy settings (one by one) and verify the issue again with v1.3.5 (when it comes out).

**Comment by Luro223** [comment]
@KitCat36 I will test tor with win10

**Comment by paradoxicallist** [comment]
Tor Browser 12.0a2 x64
Sandboxie-Plus 1.3.4 Security Hardened Sandbox (orange sandbox)
Windows 10 21H2 x64 EN

![12 0a2](https://user-images.githubusercontent.com/16800851/192070293-1363d713-449c-475f-ba6f-edef67eb4f2a.png)

**Comment by Luro223** [comment]
@paradoxicallist same for me no crashes
looks like win11 issue(again)

**Comment by isaak654** [comment]
@KitCat36 [v1.3.5](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.3.5) is out, so I would suggest you to verify the indications in this [comment](https://github.com/sandboxie-plus/Sandboxie/issues/2264#issuecomment-1256007449). 

If they do not work for you, I could try to reach the same Tor developer that helped me [the last time](https://github.com/sandboxie-plus/Sandboxie/issues/538#issuecomment-1106597048).

**Comment by isaak654** [comment]
@KitCat36 [v1.3.5](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.3.5) is out, so I would suggest you to verify the indications in [this comment](https://github.com/sandboxie-plus/Sandboxie/issues/2264#issuecomment-1256007449). 

If they do not work for you, I could try to reach the same Tor developer that helped me [the last time](https://github.com/sandboxie-plus/Sandboxie/issues/538#issuecomment-1106597048).
