### ISSUE TITLE
SandMan: File Recovery should preselect first file

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#2266]
### Is your feature request related to a problem or use case?

In the File Recovery window of SbieCtrl the first file was always preselected:
![sandboxie_recover_a](https://user-images.githubusercontent.com/33252157/191468378-02fe9140-cdd9-418b-9e67-dcb853a15593.jpg)

In the File Recovery window of SandMan this is unfortunately not the case:
![sandboxie_recover_b](https://user-images.githubusercontent.com/33252157/191468413-ff20a8ae-ec23-463c-afc6-ec1d54639891.jpg)

### Describe the solution you'd like

It would be extremely desirable if the preselection of the first file would also be implemented under SandMan. This would be a comfort gain especially when using the Immediate Recovery.

**Comment by Luro223** [comment]
@APMichael you can try to create a macro for yor sandboxie window so macro will auto-select it

**Comment by APMichael** [comment]
> @APMichael you can try to create a macro for yor sandboxie window so macro will auto-select it

This would also be a possibility, but not for everyone. In my opinion, SandMan should behave just like SbieCtrl, so that users are willing to switch from Classic to Plus.

**Comment by Luro223** [comment]
> SandMan should behave just like SbieCtrl, so that users are willing to switch from Classic to Plus.

Yeah, this will be more comfortable

**Comment by RandomGOTI** [comment]
if it will become a option it will be in the plus ini instead

**Comment by APMichael** [comment]
Works! Thank you very much for this. 👍
