### ISSUE TITLE
Safe removal of the specified sandbox

### ISSUE THREAD

**Issue by Luro223** [sandboxie-plus/Sandboxie#2268]
### Is your feature request related to a problem or use case?

Suggestion: Create a feature that allows you to shred the sandbox when deleting

### Describe the solution you'd like

The number of iterations for deleting, the specified value to overwrite with

### Describe alternatives you've considered

Random data writing for filenames and shred the filesize to zero to prevent any restoration

**Comment by DavidXanatos** [comment]
I dont add ineffective snakeoil features, see: https://github.com/sandboxie-plus/Sandboxie/issues/343 and https://github.com/sandboxie-plus/Sandboxie/issues/591 for a workaround.

A future build of sandboxie will be capable of creating a ramdisk and locating selected boxes to it

**Comment by Luro223** [comment]
@DavidXanatos I don't see any reason to add a ramdisk support as open source ImDisk Toolkit does that very well.
But if you decided to add it anyways then you can look at the souce, I think it will help you add the RamDisk feature.

**Comment by Luro223** [comment]
Also OnBoxDelete trigger seem perfect for me, thanks for mentioning it
