### ISSUE TITLE
Cannot pass through Xbox gamepad input?

### ISSUE THREAD

**Issue by kylereinfeld** [sandboxie-plus/Sandboxie#227]
Is this possible? I don't see a setting for it anywhere.

**Comment by DavidXanatos** [comment]
You will probably need to open some selected IPC paths, but I don't know which, is an Xbox gamepad the same as a ordinary xbox controller?

**Comment by kylereinfeld** [comment]
Yes, it’s an ordinary Xbox One controller. Unfortunately I don’t know what IPC paths are or how to open them. If you have any pointers I’ll gladly take them, otherwise I can do some research on my own.

**Comment by DavidXanatos** [comment]
I have such a controller I'll try it out with a sandboxed game to see if I can reproduce the issue and provide a solution

**Comment by kylereinfeld** [comment]
Awesome; let me know what you find and I’ll try it on my end as well.

**Comment by DavidXanatos** [comment]
mmh... so, I tried playing "witcher 3" and "assasins creed unity" in a sandbox with my old controller and it worked just fine without any customization.
So not sure why it fails for you. What game have you tried to use it with?

**Comment by kylereinfeld** [comment]
I tried some other games and it seems like most everything else I tried works.

The one exception (and the first one I tried to play) is a game called Pink River from the GMTK 2020 Jam: https://kebabskal.itch.io/pink-river

My intention was to use sandboxie to play jam games, which is why I tried that one. I don’t understand why that one doesn’t work, but I haven’t been able to replicate it with anything else.

**Comment by DavidXanatos** [comment]
there ware some fixes in this region recently, is this issue still present?

**Comment by kylereinfeld** [comment]
> 
> 
> there ware some fixes in this region recently, is this issue still present?

The issue seems to be fixed for me! If it matters, I did a fresh install of Sandboxie-Plus (I was using Sandboxie before).

Good stuff, thanks!

**Comment by NewKidOnTheBlock** [comment]
Can confirm. I've played a ton of games in sandbox feat. an Xbox One controller.
