### ISSUE TITLE
Hyperlinks won't open when browser is sandboxed

### ISSUE THREAD

**Issue by EXTR-cloud** [sandboxie-plus/Sandboxie#2279]
### Describe what you noticed and did

1.  I opened browser (sandboxed)
2.  I clicked on hyperlinks from other apps, and they don't open up in the browser

When I run browser without sandbox, hyperlinks work fine.

### Affected program

vivaldi, brave browsers

### Download link

not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

I click on hyperlink and it opens up in the browser

### What is your Windows edition and version?

Windows 11 Pro 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sanboxie Classic v5.58.2 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
1. This probably requires `OpenWinClass=vivaldi.exe,Chrome_MessageWindow` and/or `OpenWinClass=brave.exe,Chrome_MessageWindow`
2. Also, please share your Sandboxie.ini configuration file

**Comment by EXTR-cloud** [comment]
Added the lines to the configuration file and hyperlinks started working. Thanks.

**Comment by maarvin2104** [comment]
I am having a problem. I tried the 'If it is related to network drives, replace BlockNetworkFiles=y with BlockNetworkFiles=n and apply this line', but it is still not working. Could someone please help me? I would really appreciate a response.
