### ISSUE TITLE
Ｈelp！LINE instant messaging platform(PC version)

### ISSUE THREAD

**Issue by test12313op** [sandboxie-plus/Sandboxie#228]
Please help me
I waited almost about an hour but no response returned,it just stuck there.

Developer：LINE Corporation
Destination URL：https://line.me/zh-hant/

Sandboxie release：SandboxieInstall64-v5.45.0
Microsoft windows 10：version 20H2

![4](https://user-images.githubusercontent.com/74262001/101978557-cbf94400-3c90-11eb-916f-68f81989f09f.PNG)

![3](https://user-images.githubusercontent.com/74262001/101978559-cef43480-3c90-11eb-9a3a-932331020696.PNG)

![1](https://user-images.githubusercontent.com/74262001/101978561-d0bdf800-3c90-11eb-8d26-bc10ddb69e98.PNG)

![2](https://user-images.githubusercontent.com/74262001/101978554-c4d23600-3c90-11eb-8fbb-fb317d24b13e.PNG)

**Comment by NewKidOnTheBlock** [comment]
We got a whole bunch of issues regardine LINE:
#195 #167 #145

**Comment by DavidXanatos** [comment]
Ok there seams to be a english version of that, any chance to try it out without a cell phone?

**Comment by DavidXanatos** [comment]
I have found the issue causing that particular incompatibility, as well as a couple other problems, LINE will work with the next release of sandboxie-plus on windows 20H1 ans 20H2
