### ISSUE TITLE
[BSOD]Kernel Mode Object Filtering

### ISSUE THREAD

**Issue by Luro223** [sandboxie-plus/Sandboxie#2281]
### Describe what you noticed and did

Okay, so I updated to 1.3.5(from 1.3.4) and decided to use the Kernel Mode Object Filtering feature and encountered the BSOD(for me it was PAGE FAULT IN NONPAGED AREA(SbieDrv.sys) every time I run into the same issue) after I terminated UuuClient.exe during its initialization
![002-01](https://user-images.githubusercontent.com/42772886/192297191-ef521ec4-1ed8-468f-bc62-ef085d314a88.png)

To reproduce same issue you need to do the following:
- Enable Kernel Mode Object Filtering
- Launch UuuClient.exe and try to terminate through sandboxie during the process initialization
- It happens randomly but if you encounter error `0xc0000001 (A device attached to the system is not functioning.)` then you will get BSOD as soon as you disable Kernel Mode Object Filtering > open any app inside sandboxie > enable Kernel Mode Object Filtering
Unfortunately I cannot provide minidump as I completely disabled this feature

### How often did you encounter it so far?

Whenever I repeat the actions above

### Affected program

Universal UE4 Unlocker v3.0.21

### Download link

https://mega.nz/file/MUhUlaqa#PI0ubSy_sQc4GouDPnZbulNSgQRUNIJeXNwLb2LnKhk

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

No critical issues related to Sandboxie Driver when trying to terminate any process in any state along with using the Kernel Mode Object Filtering feature

### What is your Windows edition and version?

Windows 10 1803 (17134.81)

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie Plus V1.3.5 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Not verified

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=RpcPortBindings
Template=RTSS
Template=ActualWindowManager
Template=WindowsRasMan
Template=Kaspersky
Template=Proxifier
Template=7zipShellEx
Template=WindowsLive
Template=InternetDownloadManager
Template=OfficeLicensing
FileRootPath=Q:\Sandbox\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
EnableObjectFiltering=y

[UserSettings_08DA01C0]

SbieCtrl_UserName=user
SbieCtrl_NextUpdateCheck=1626104363
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_HideMessage=*
SbieCtrl_WindowCoords=200,150,660,450
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=n
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=n
SbieCtrl_AddSendToMenu=n
SbieCtrl_RecoverTarget=H:\AWZ
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_BoxExpandedView=Temp_009
SbieCtrl_AutoStartAgent=SandMan.exe

[Temp_009]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=n
```

**Comment by Luro223** [comment]
@isaak654 I think it's a critical issue.

**Comment by DavidXanatos** [comment]
the first 2 steps are clear, the 3rd not so much

So we enable kmof
start this tool
kill it through sb
if we don't get an error go to "start this tool" and repeat
if we get the error then disable kmof
open something random in sb 
and while it is open, enable kmof

is that the right test procedure?

**Comment by Luro223** [comment]
@DavidXanatos Any reference to the driver with the same error will cause BSOD, for my case the steps were as you described.

**Comment by DavidXanatos** [comment]
mmh... but you need to terminate the client using the terminate all feature and you need to see the  0xc0000001  error, no 0xc0000001 no BSOD later?

**Comment by Luro223** [comment]
@DavidXanatos I used `Terminate All Programs` inside sandboxie plus UI then > disabled `Kernel Mode Object Filtering` > opened explorer inside same sandbox I had BSOD before > enabled `Kernel Mode Object Filtering` without terminating any process > BSOD

**Comment by Luro223** [comment]
I have some delays with I/O requests, so the chance of me causing this error is higher

**Comment by Luro223** [comment]
I will post the MiniDump here as soon as I have a chance to restore its functionality

**Comment by Luro223** [comment]
@DavidXanatos Hardware-specific issue (OC) : 
Machine #1, Windows 10 20H2 (19042.1605) No issues
Current machine, Windows 10 1803 (17134.81) same BSOD
Machine #3 Windows 10 1803 (17134.81) No issues
Machine #4 Windows 10 1803 (17134.81) No issues
P.S. #3 and #4 has absolutely identical OS(restored from backup) changes : device specific drivers
I'm closing the question. Sorry for the inconvenience.
