### ISSUE TITLE
Problem with MetaTrader 5

### ISSUE THREAD

**Issue by blap** [sandboxie-plus/Sandboxie#2282]
### Describe what you noticed and did

I can install, but I can not run metaeditor64.exe. 
I got the error "entry point not found" for metaeditor64.exe when I tried to open it.
But I can run terminal64.exe and metatester64.exe.
[mt5setup.zip](https://github.com/sandboxie-plus/Sandboxie/files/9646640/mt5setup.zip)

### How often did you encounter it so far?

Whenever I want to open metaeditor64.exe

### Affected program

MetaTrader 5 -> metaeditor64.exe

### Download link

https://www.metatrader5.com/en/download

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Open metaeditor64.exe.

### What is your Windows edition and version?

Windows 10 Home 21H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.3.5 64-bit Portable updated from 1.3.4

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No.
Trace Log when I tried to run metaeditor64.exe:
[trace log.txt](https://github.com/sandboxie-plus/Sandboxie/files/9646697/trace.log.txt)

### Sandboxie.ini configuration

```shell
[GlobalSettings]
FileRootPath=C:\Users\Admin\0.Programas\Sandbox\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=Edge_Win11Fix
Template=7zipShellEx
InjectDll=...\logapi32.dll
InjectDll64=...\logapi64.dll
OpenPipePath=\Device\NamedPipe\LogAPI
StartRunAlertDenied=y
AlertProcess=EXCEL.EXE
AlertProcess=WINWORD.EXE
AlertProcess=POWERPNT.EXE
AlertProcess=notepad++.exe
AlertProcess=mpc-hc64.exe
AlertProcess=PDFXEdit.exe
AlertProcess=PDFXTools.exe
AlertProcess=Ketarin.exe
AlertProcess=chrome.exe
AlertProcess=bdcam.exe
AlertProcess=loader.exe
AlertProcess=Zoom.exe
AlertProcess=Teams.exe
AlertProcess=thunderbird.exe
AlertProcess=firefox.exe
AlertProcess=WhatsApp.exe
AlertProcess=4t-min.exe
AlertProcess=4t-min64.exe
AlertProcess=qbittorrent.exe
AlertProcess=Telegram.exe
NetworkEnableWFP=y
SandboxieLogon=y

[UserSettings_0C02020A]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
SbieCtrl_UserName=admin
SbieCtrl_WindowCoords=200,150,880,450
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_HideMessage=1307, WINWORD.EXE [Office_Pro_Plus_2019] *
SbieCtrl_HideMessage=1307, OfficeClickToRun.exe [Office_Pro_Plus_2019] *

[MQL5]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
FakeAdminRights=y
MsiInstallerExemptions=y
CopyLimitKb=-1
OpenProtectedStorage=y
NotifyProcessAccessDenied=y
AllowRawDiskRead=y
NotifyDirectDiskAccess=y
AllowNetworkAccess=<BlockNetAccess>,n
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
OpenIpcPath=$:*
OpenWinClass=#
RpcMgmtSetComTimeout=n
OpenDevCMApi=y
OpenSamEndpoint=y
OpenLsaEndpoint=y
HideOtherBoxes=n
```

**Comment by blap** [comment]
Running in Sandboxie Plus 1.4.2 64-bit Portable.
Metatrader from 7 oct 22.

**Comment by karine43** [comment]
Same problem here cant run [MQL5 Strategy Tester Agent]

download link https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5tester.setup.exe

application always hangup 

error in app log looks like 
`Service	service '"C:\Program Files\MetaTrader 5 Strategy Tester\MetaTester64.exe" /run /address:0.0.0.0:2001' not found`
