### ISSUE TITLE
SandMan: Explorer context menu does not work directly after a clean installation on Windows 11

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#2284]
### Describe what you noticed and did

With a clean reinstallation, the **Explorer context menu** (shell integration) usually only works after a restart of Windows.

### Clean VM (running **Windows 11**, 21H2, 64-bit):

1.) Download and install the latest version of Sandboxie-Plus (v1.3.4, 64-bit).
2.) Click through the Setup Wizard "Personally", leaving everything at default values.
3.) Wait until the entry "Open Sandboxed" is added to the Explorer context menu.
4.) Run e.g. "Microsoft Edge" in the DefaultBox via the Explorer context menu.
5.) The execution does not work, but the following error messages are displayed:

![sandboxie_context_w11_b](https://user-images.githubusercontent.com/33252157/189864088-ca26bf7a-f744-4ada-bb72-2197e9305f21.jpg)

`Start.exe (1504): SBIE2112 Object is not accessible: \Sessions\1\BaseNamedObjects\SM0:1504:120:WilError_03, call CreateMutant (C0000022) access=001F0001 initialized=1`

After restarting Windows, it then works as it should.

~~**Note: Update 1 https://github.com/sandboxie-plus/Sandboxie/issues/2284#issuecomment-1259720113**~~
~~**Note: Update 2 https://github.com/sandboxie-plus/Sandboxie/issues/2284#issuecomment-1282416049**~~
**Note: Update 3 https://github.com/sandboxie-plus/Sandboxie/issues/2284#issuecomment-1328778347**

### How often did you encounter it so far?

With each clean reinstall of Sandboxie Plus.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The Explorer context menu should work correctly immediately (as under SbieCtrl) or the user should be prompted to restart.

### What is your Windows edition and version?

Windows 11 Pro, 21H2, 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

1.3.2-1.6.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by okrc** [comment]
This problem is not very relevant to your description, it only occurs when SandMan exits. You may have triggered it by chance.

**Comment by APMichael** [comment]
> This problem is not very relevant to your description, it only occurs when SandMan exits. You may have triggered it by chance.

I can reliably reproduce the issue 100% after each reinstall. It has nothing to do with whether SandMan is exited, but occurs immediately after installation and initial setup. Exactly as I described it above. There is also no chance involved here. 

I certainly do not create an issue report just because an issue occurred once and by chance!

**Comment by APMichael** [comment]
> Sorry, maybe it's a language problem, I can't understand and reproduce your question ...

Never mind, English is not my native language either. Thanks for your reply anyway.

**Comment by APMichael** [comment]
A small update:

I can confirm the procedure of @okrc . The error message about the "initialization of the SbieDll.dll" can also be triggered by simply exiting SandMan (using "Sandbox" > "Exit") and then trying to start e.g. "Microsoft Edge" via the Explorer context menu.

In addition, with the procedure I gave above, a restart of Windows can be bypassed if you use "Sandbox" > "Maintenance" > "Stop All" instead and restart SandMan afterwards.

**Comment by APMichael** [comment]
In v1.4.0, the Explorer context menu does not seem to work at all.

The setting "Add 'Run Sandboxed' to the explorer context menu" is also no longer ticked under "Global Settings" > "Shell Integration". If you tick the setting, the tick will be removed immediately as soon as you click on "Apply".

**Comment by DavidXanatos** [comment]
> In v1.4.0, the Explorer context menu does not seem to work at all.
> 
> The setting "Add 'Run Sandboxed' to the explorer context menu" is also no longer ticked under "Global Settings" > "Shell Integration". If you tick the setting, the tick will be removed immediately as soon as you click on "Apply".

oh I'm sorry about that, I think its caused by the extension file not being signed either, i have to make a memo to myself to not only incluse a signed driver but also to always deploy a signed version of the extension

try grabbing SbieShellExt.dll and SbieShellPkg.msix from build 1.3.5 an try with those I'm pretty sure than it will work.

**Comment by APMichael** [comment]
> ... try grabbing SbieShellExt.dll and SbieShellPkg.msix from build 1.3.5 an try with those I'm pretty sure than it will work.

Thank you for your reply. Yes, with the replaced files the Explorer context menu works again. 👍

Then only the issue reported here with the SbieDll.dll error message remains. The easiest way to trigger this is to exit SandMan and then try to run a program in a sandbox via the Explorer context menu.

**Comment by isaak654** [comment]
Interestingly enough, a similar limitation is also present on [PowerToys](https://github.com/microsoft/PowerToys/issues/19124).

**Comment by DavidXanatos** [comment]
@isaak654 thanks for finding this, so it seams it is an issue with windows 11 as such.
lets see how powertoys fix this if at all

**Comment by APMichael** [comment]
The issue with PowerToys seems to be related only to the insertion of the context menu entries. With Sandboxie, this takes a few seconds, then the entries are reliably present.

The issue with Sandboxie is a different one: With the current versions of Sandboxie, it is now sufficient to simply exit SandMan once and start it again for the context menu to work without errors. (Without a restart of SandMan there are always the error messages mentioned above.)

In addition, the SbieDll.dll error message always occurs as soon as you exit SandMan and then try to run a program in a sandbox via the context menu. Unfortunately, a reboot does not change this and the SbieDll.dll issue with a non-running SandMan should therefore please be fixed.

**Comment by DavidXanatos** [comment]
@APMichael i see, will look into it asap

**Comment by boromyr** [comment]
Same exact problem, even with 1.5.3. Windows 11, UAC disabled.

**Comment by DavidXanatos** [comment]
It was not a high priority issue we have anough of those to fix already, but I'll look to fix this for 1.5.4

**Comment by lemaximedu66** [comment]
i have the same issue.

**Comment by mysteriously** [comment]
For me Run in sandbox menu does not show up at all. I've tried to disable and re-enable it. However, run unsandboxed is shown

**Comment by isaak654** [comment]
> For me Run in sandbox menu does not show up at all. I've tried to disable and re-enable it. However, run unsandboxed is shown

Since when? I can't reproduce it on both Win10 21H2 and Win11 22H2 (Plus v1.5.3). 
Probably you need to uninstall / reinstall to clean up old references.

**Comment by mysteriously** [comment]
Since Win 11 clean installation.

Dunno why you are marking my comments as offtopic...

**Comment by isaak654** [comment]
> Dunno why you are marking my comments as offtopic...

Because this issue seems to be related to a specific SbieDll error message you didn't mention.

**Comment by boromyr** [comment]
@DavidXanatos 
> try grabbing SbieShellExt.dll and SbieShellPkg.msix from build 1.3.5 an try with those I'm pretty sure than it will work.

I tried this suggestion but the problem persists, the context menu only works if the sandboxie plus gui is running.

**Comment by APMichael** [comment]
Unfortunately, only the original issue, as described in the title, has been fixed. The other two issues unfortunately still exist!

**Issues not fixed:**

1.) Exit SandMan and then try to run a program in a sandbox via the Explorer context menu. > SbieDll.dll error message!

2.) Exit SandMan and then run SandMan as administrator. Try to run a program in a sandbox via the Explorer context menu. > SbieDll.dll and SBIE2112 error message!

**Comment by lemaximedu66** [comment]
still not fixed !

**Comment by DavidXanatos** [comment]
I think I have an idea what might cause the SbieDll.dll issue you see the shell menu dll for win 11 is installed as a modern app package a so called sparse packet, and when it starts sandman.exe and it does not find an existing instance the new sandman running associated with the app package executes start.exe the token gets propagated down the line and ultimately once it reaches the sandbox causes a problem. 

in the next build there will be a fix for that, the service will check if the caller's token belongs to an app package and if so generate a new user token for the logged in session.

**Comment by boromyr** [comment]
I solved it like this for the memento:
```Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\unbox]
@="Avvia all'&esterno dell'area virtuale"
"Icon"="C:\\Program Files\\Sandboxie Plus\\SandMan.exe,0"
"MUIVerb"="Avvia nell'area virtuale"

[HKEY_CLASSES_ROOT\*\shell\unbox\command]
@="\"C:\\Program Files\\Sandboxie Plus\\Start.exe\" /box:DefaultBox \"%1\" %*"

```
Update to the desired language and with the correct installation path.

**Comment by isaak654** [comment]
[1.6.4](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.6.4) is out, could you revert any workaround and confirm the fix?

**Comment by APMichael** [comment]
The two remaining issues have been successfully fixed! 👍 Many thanks for that.

**Comment by lemaximedu66** [comment]
fixed 👍🏻 thanks !
