### ISSUE TITLE
Translation .ts files contain duplicate entries

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2289]
### Describe what you noticed and did

When opening the latest translation to translate the strings, I got the following message:

> Duplicate messages found in '{...]/sandman_de.ts':
> * Context: OptionsWindow
> * Source: Remove

### Affected program

Qt Lingusist

### Download link

not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Non-duplicate entries.

### What is your Windows edition and version?

Not relevant

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Not relevant

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
udpated the files pelase try again

**Comment by bastik-1001** [comment]
This resolved the message from Linguist. Thank you.
