### ISSUE TITLE
Windows still kill Sandboxie-Plus

### ISSUE THREAD

**Issue by xooyo** [sandboxie-plus/Sandboxie#229]
Detected: Trojan:Win32/CryptInject!ml
Status: Quarantined
Date: 12/12/2020 4:42 PM
Details: This program is dangerous and executes commands from an attacker.

Affected items:
file: E:\gx\Sandboxie-Plus-x64-v0.5.0.exe

**Comment by DavidXanatos** [comment]
please try the  0.5.1 build it uses inno setup instead of uInstall
