### ISSUE TITLE
Enchancement for content auto deletion

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#23]
Since Sandboxie appears to have code to detect when a sandbox has been created and how long it hasn't been 'cleaned' since Sandboxie issues this message:

```
Sandbox '%2' was created %3 days ago.

Please consider deleting the contents of your sandbox from time to time.

To configure automatic deletion, use the Sandbox Settings command from
the Sandbox menu in Sandboxie Control.
```

I thought that it would be a good enhancement to add a setting, which would allow one to set x days before the auto deletion function could clean up the contents of a sandbox. Right now it is only possible to set auto deletion to clean up  the contents of a sandbox once it becomes unused.

I am not sure if that is feasible or even worse a bad idea.

**Comment by DavidXanatos** [comment]
I think hat would make the tool unpredictable. i.e. when you open a app in the sandbox you wouldn't know if it will open in a clean one or if the old stuff will still be there.
Its not a good idea to go by file dates as files with different dates may still belong together.

What would be interesting would be an option like clean up on PC shutdown.
