### ISSUE TITLE
Allow user select container folder (where sandboxes will be created and stored) as same as classical Sandboxie build

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#230]
In Sandboxie Plus x64 v0.5.1, I seems couldn't find this setting.

**Comment by DavidXanatos** [comment]
Indeed you couldn't but its there:

![grafik](https://user-images.githubusercontent.com/3890945/101989545-5fd30c00-3ca1-11eb-93ca-eac63d03f0e1.png)
