### ISSUE TITLE
[Plus UI] Add tooltips for combo box items (Resource Access tab)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2300]
### Is your feature request related to a problem or use case?

_Originally posted by @lwcorp in https://github.com/sandboxie-plus/Sandboxie/discussions/1805#discussioncomment-2857954_

> Could you add tooltips for all these options? Also, why is the last one cut off? 
![image](https://user-images.githubusercontent.com/1773306/171233678-f79c0b0b-ae28-4e0f-aa01-d06bc9bbefa8.png)
> @DavidXanatos 
> I have to check if QT allows tooltips for combo box items, its cut of because the size is made to fit the column you cna resize the column to fit it all

### Describe the solution you'd like

https://stackoverflow.com/a/23381249
https://doc.qt.io/qt-6/qcombobox.html#setItemData

### Considerations

This deserves higher priority than #379, as more and more users don't know the difference between "Open" and "Open for All".
Resource Access rules are the most important part of Sandboxie.

**Comment by DavidXanatos** [comment]
may be i shoudl rename "Box Only" to "Hide Original"?

**Comment by isaak654** [comment]
> may be i shoudl rename "Box Only" to "Hide Original"?

I would still prefer tooltips over this.

**Comment by lwcorp** [comment]
Awesome! However, there are some issues there including various spelling errors (which I've handled with #2314).
If you approve my PR, it still leaves:
1. Block access to WinRT class => not too clear to those who just wish to know what this option does
2. Ignore UIPI restrictions for processes. => likewise

**Comment by lwcorp** [comment]
But what about the last 2 points?
