### ISSUE TITLE
Sandboxie is always run as administrator, and can not drop priviledge.

### ISSUE THREAD

**Issue by JerryZhongJ** [sandboxie-plus/Sandboxie#2305]
### Describe what you noticed and did

1. I have a administrator account exactly called "Administrator".
2. I run sandboxie manager in this account.
3. If I try to run program, the option "run as uac administrator" is checked and grey. And it said "This application has already run as administrator, this option is disabled". (These sentences are translated from my language, I don't how to switch the language of Start.exe now)
4. If I try to run an installer inside the sandbox, the UAC window don't pop up. The installation path is "C:\Program Files (x86)\", it says I have no right to install here.
5. In Sandbox Settings - General Options- Security, "Drop right from Administrators and Power Users Groups" is unchecked and grey.
6.  I have checked SandMan.exe, Start.exe, and SbieCtrl.exe with "Run as Administrator" not checked in compatibility settings, and so do their shortcuts.
7. I have checked UAC is enabled, it was set the second level from the top.
8. I create a new account called "test", and make it a member of Administrators.
9. I run the SandMan.exe as this account, using "runas" command. The options, including  "run as uac administrator" in start.exe and "Drop right from Administrators and Power Users Groups", are selectable.
10. I run a installer inside the sandbox, the UAC panel pop up successfully. I permit the program to be elevated, then it install successfully.

### How often did you encounter it so far?

Always

### Affected program

TIM3.4.1.22056.exe

### Download link

https://dldir1.qq.com/qqfile/qq/TIM3.4.1/TIM3.4.1.22056.exe

### Where is the program located?

Not relevant to my request.

### Expected behavior

These two options should not be grey, and selectable when I don't run as administrator.
It should ask me for elevating when I run the installer.

### What is your Windows edition and version?

Windows 11 Pro 21H2 22000.978

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie-Plus v1.3.5 64bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by okrc** [comment]
> 但是我仍不清楚沙盒内程序的权限，根据灰色的option，他们应该提权过了。但是根据没有UAC弹窗和在任务管理器看，他们是没有特权的。所以我是否应该担心它们拥有管理员权限。
这个很容易判断，利用Windows拖拽事件的权限限制。审批模式下explorer不会提权，用同样方式下沙盒中运行powershell，如果不能从explorer中拖入文件，证明该方式已被提权。

**Comment by JerryZhongJ** [comment]
好的，感谢你的建议。但我的所有东西都放在Administrator上，电脑交给我的时候就是以Administrator登录的。

或许我以后重装系统的时候考虑一下创建其他账户。
