### ISSUE TITLE
Sbie2203 connect failed chrome.exe

### ISSUE THREAD

**Issue by Yituo3712VP** [sandboxie-plus/Sandboxie#2312]
### Describe what you noticed and did

Start Chrome inside Sandboxie
https://www.bilibili.com/bangumi/play/ss41634 Regional restrictions require VPN
https://www.bilibili.com/video/BV1dS4y1v7Tq/
After testing found the issue url: 
www.bilibili.com/bangumi/* sbie2203 error (any video need TW or MAC or HK vpn)
www.bilibili.com/video/* normal

SBIE2203 Failed to connect to Sandboxie service: connect C0000022
SBIE2203 Failed to connect to Sandboxie service: *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]
SBIE2203 Failed to connect to Sandboxie service: *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]
SBIE2203 Failed to connect to Sandboxie service: *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]
SBIE2203 Failed to connect to Sandboxie service: *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]
SBIE2203 Failed to connect to Sandboxie service: *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]

### How often did you encounter it so far?

When open webpage

### Affected program

Chrome v106.0.5249.103

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

not error sbie2203

### What is your Windows edition and version?

Win10 21H1

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Kaspersky 

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.58.5

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Sandboxie-Classic-x64-v5.58.1

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

not

**Comment by isaak654** [comment]
I encountered the same type of error, but with another website:
 https://www.wilderssecurity.com/threads/sbie2203-failed-to-communicate-with-sandboxie-service.448602/
 
 ![SBIE2203](https://user-images.githubusercontent.com/12372772/199520952-0a3d65dc-9c96-46fc-8753-1a3808085df7.png)

I'm using Plus v1.5.1 x64 with Windows 10 21H2 x64 and sandboxed Edge 107.0.1418.26 x64

**Comment by isaak654** [comment]
@DavidXanatos How can I debug this?
