### ISSUE TITLE
"Cloud Music" installer does not display UI

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#2315]
### Describe what you noticed and did

the installation package is outside the sandbox, and the installation program is started in the sandbox. when the installation program starts, the UI is not displayed

### How often did you encounter it so far?

every time

### Affected program

Cloud Music

### Download link

https://music.163.com/

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

like normal startup outside the sand table

### What is your Windows edition and version?

windows11 home  22h2 64bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

Sandboxie-Plus 1.3.5 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
BoxNameTitle=y
CopyLimitKb=81920
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
FileTrace=*
FakeAdminRights=y
```

**Comment by okrc** [comment]
添加 `OpenWinClass=#` 以完成安装

**Comment by okrc** [comment]
这是一个类似问题 https://github.com/sandboxie-plus/Sandboxie/issues/1073

**Comment by Taeyeonzpx** [comment]
> 添加 `OpenWinClass=#` 以完成安装

噢噢 谢谢你 问题解决了~

**Comment by okrc** [comment]
@isaak654 Regarding [#1073](https://github.com/sandboxie-plus/Sandboxie/issues/1073), I noticed that the description on [#1076](https://github.com/sandboxie-plus/Sandboxie/discussions/1076) is that there may be a UAC issue.
I found that there is a problem with `FakeAdminRights=y` records being lost when setting `OpenWinClass=#`. Is this as expected.


https://user-images.githubusercontent.com/29057533/194703158-2ff5568d-d09d-493a-b92e-acd535f41981.mp4

**Comment by isaak654** [comment]
> I found that there is a problem with `FakeAdminRights=y` records being lost when setting `OpenWinClass=#`. Is this as expected.
...

Unfortunately I don't have an answer for this behavior. Perhaps @DavidXanatos could clarify your doubt.

**Comment by isaak654** [comment]
> I found that there is a problem with `FakeAdminRights=y` records being lost when setting `OpenWinClass=#`. Is this as expected.
...
@okrc 
Unfortunately I don't have an answer for this behavior. Perhaps @DavidXanatos could clarify your doubt.

**Comment by isaak654** [comment]
> I found that there is a problem with `FakeAdminRights=y` records being lost when setting `OpenWinClass=#`. Is this as expected.
...

@okrc 
Unfortunately I don't have an answer for this behavior. Perhaps @DavidXanatos could clarify your doubt.

**Comment by Taeyeonzpx** [comment]
> 添加 `OpenWinClass=#` 以完成安装

但是好像1.4.1版本  "不要改变窗口类名" 的这个选项在UI中没有了 ,只能通过指令的方式进行操控了吗??

**Comment by okrc** [comment]
这里
***@***.***

发件人: ***@***.***>
发送时间: 2022年10月9日 16:45
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [sandboxie-plus/Sandboxie] "Cloud Music" installer does not display UI (Issue #2315)


添加 OpenWinClass=# 以完成安装

但是好像1.4.1版本 "不要改变窗口类名" 的这个选项在UI中没有了 ,只能通过指令的方式进行操控了吗??

―

**Comment by okrc** [comment]
> 但是好像1.4.1版本 "不要改变窗口类名" 的这个选项在UI中没有了 ,只能通过指令的方式进行操控了吗??

这里
<img width="746" alt="image" src="https://user-images.githubusercontent.com/29057533/194754993-a7cbe0d5-3bf1-4f58-8ee6-84be9707a19d.png">

**Comment by isaak654** [comment]
@okrc 
I informed David through Slack, so apparently the issue you discovered with FakeAdminRights was just the tip of the iceberg:
![immagine](https://user-images.githubusercontent.com/12372772/194759769-b110bbda-938e-42ff-93a9-0ad212b028f7.png)

**Comment by okrc** [comment]
> The fix is in [a82eb28#diff-e045a61229045cc98d09e23962c98b4ee0c72cee19d17dd7c6a36d09ce31ae7a](https://github.com/sandboxie-plus/Sandboxie/commit/a82eb284118fbf97888fa90a3d4b84ccd87aaedc#diff-e045a61229045cc98d09e23962c98b4ee0c72cee19d17dd7c6a36d09ce31ae7a)

Yes, I rebuilt it and the problem has been solved.

**Comment by DavidXanatos** [comment]
the issue with "NeteaseCloudMusic_Music_official_2.10.4.200396.exe" seams to be related to desptop isolation, i have to investigate this further

you can temporarily disable a large part of the security guarantees by adding

UnrestrictedToken=y
NoSandboxieDesktop=y

to your sandboxie ini, but this is absolutely not recommended, this makes the sandbox not secure,
dong that for the instzalation of a known non malware application is ok if you disable it after instalation again.

**Comment by Taeyeonzpx** [comment]
> > 但是好像1.4.1版本 "不要改变窗口类名" 的这个选项在UI中没有了 ,只能通过指令的方式进行操控了吗??
> 
> 这里 <img alt="image" width="746" src="https://user-images.githubusercontent.com/29057533/194754993-a7cbe0d5-3bf1-4f58-8ee6-84be9707a19d.png">

噢噢  原来在这里 谢谢你
