### ISSUE TITLE
Error Status: 0xc0000001 (A device attached to the system is not functioning.)

### ISSUE THREAD

**Issue by SynapseScribe** [sandboxie-plus/Sandboxie#2316]
### Describe what you noticed and did

Got error:
"Error Status: 0xc0000001 (A device attached to the system is not functioning.)"
, while trying to terminate all programs related to CurseForge OverWolf app

### Affected program

CurseForge

### Download link

https://download.curseforge.com/#download-options

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

terminate and delete sbox contents successfully

### What is your Windows edition and version?

Win 11 x64

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Eset EIS

### What version of Sandboxie are you running?

1.4.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by Luro223** [comment]
@fusionneur I had the same issue recently. The issue related to memory(unstable memory after OC. and similar)

**Comment by Luro223** [comment]
> I don't have oc right now and never had memory issues of any sort on my current system.

OS Specific or Individual software/hardware-related issue because I can't reproduce this after I stabilized my system.

**Comment by DavidXanatos** [comment]
@fusionneur can you reproduce this issue? or was it a one time occurrence?

**Comment by e-t-l** [comment]
@DavidXanatos could we reopen this? (or should I open a new issue?) I do get this error from time to time, on every version of Sandboxie up through 1.12.6. It happens when a program **crashes** but the process remains running in Sandboxie and I try to terminate it manually in Sandman. 

I'll play around with some programs that I know aren't 100% compatible with Sandboxie and see if I can find something specific to reproduce it consistently.

**Comment by offhub** [comment]
@e-t-l 
Could you please open a new issue for this?
