### ISSUE TITLE
Simplying and clarifying Feature Comparison

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#2317]
### Is your feature request related to a problem or use case?

https://sandboxie-plus.com/feature-comparison/ is very hard to decipher.

### Describe the solution you'd like

1. The first 3 columns are Plus vs. Classic, Free and Supported. Does it mean Plus=Free and Classic=Supported?
2. If so, how come **paid** features are written as **No** for Plus/Free, but as **Yes** (no UI) for Classic/Supported? It doesn't sound logical.
3. Again, if Classic=Supposed, how come it states **As Certified** for number of PCs and expirations?
4. Why does it state **No** for **UI Dark mode**, when it seems like a completely free feature?
5. Why does it state **No** for **Start Menu Integration**, when it seems like a completely free feature?
6. Why does it state **No** for **Box Snapshots**, when it seems like a completely free feature?
7. Are there any other free options that are marked as **No**?
8. How come some options are signaled as **No** in **Pure vs. Classic", but as **Yes**  in **Free** of **Free VS Supported**?

I suggest to start from fresh based on (note the asterisk at the end):

| Feature                            | Free      | Free      |   | Paid              | Paid              | Paid                         | Paid       | Paid                         |
|------------------------------------|-----------|-----------|---|-------------------|-------------------|------------------------------|------------|------------------------------|
|                               Type |   Classic |    Plus   |   |       Small       |       Medium      |             Large            |  Business  |             Huge             |
| Usage                              | Personal  | Personal  |   | Personal          | Personal          | Personal                     | Commercial | Personal                     |
| Support   reminder                 | Yes       | Yes       |   | No                | No                | No                           | No         | No                           |
| PC’s per   Certificate             | Unlimited | Unlimited |   | All personal ones | All personal ones | All personal and family ones | 1          | All personal and family ones |
| Expiration                         | No        | No        |   | 1 year            | 1 year            | 2 years                      | 1 year     | No                           |
| Old   builds work after expiration | N/A       | N/A       |   | No                | Yes               | Yes                          | Yes        | Yes                          |
| UI Dark   mode                     | Yes       | Yes       |   | Yes               | Yes               | Yes                          | Yes        | Yes                          |
| Start Menu   Integration           | Yes       | Yes       |   | Yes               | Yes               | Yes                          | Yes        | Yes                          |
| Windows   11 Context menu          | ?         | ?         |   | Yes               | Yes               | Yes                          | Yes        | Yes                          |
| Box   Snapshots                    | ?         | Yes       |   | Yes               | Yes               | Yes                          | Yes        | Yes                          |
| Object   Filtering                 | ?         | Yes       |   | Yes               | Yes               | Yes                          | Yes        | Yes                          |
| WFP   support                      | ?         | ?         |   | Yes*              | Yes*              | Yes*                         | Yes*       | Yes*                         |
| Privacy   enchanced boxes          | ?         | ?         |   | Yes*              | Yes*              | Yes*                         | Yes*       | Yes*                         |
| Security   Enchanced boxes         | ?         | ?         |   | Yes*              | Yes*              | Yes*                         | Yes*       | Yes*                         |
| Compatybility   enchanced boxes    | ?         | ?         |   | Yes*              | Yes*              | Yes*                         | Yes*       | Yes*                         |
| Process   Breakout                 | No        | No        |   | Yes*              | Yes*              | Yes*                         | Yes*       | Yes*                         |

* Available in Classic without an UI

**Comment by okrc** [comment]
I guess it should be like this

The previous SUPPORTED and FREE refer to Classic, and "As Certified" refers to the determination based on the certificate option, which can be referred to in the diagram that follows.

**Comment by okrc** [comment]
![image](https://user-images.githubusercontent.com/29057533/194647021-ba646e65-8fed-43a3-afd9-94e7dadacb37.png)

**Comment by lwcorp** [comment]
What is **Free Classic** as opposed to **Supported Classic**?

Is it a merge of Small-Huge? If so, maybe this column should be removed and use asterisks instead to differentiate from Plus. I wonder how many use Classic anyway (maybe it's time to pull stats how many use or download Classic VS Plus).

**Comment by okrc** [comment]
SUPPORTED is a merger of Small-Huge. There are wrong colors in the first few rows of the chart I drew.

**Comment by okrc** [comment]
> Also, if the first columns only deal with Classic, why do they state **No** Start Menu Integration? Even the original Sandboxie had it.

For this, I am not sure. the PLUS version start menu integration seems to be introduced from the recent 1.4.0.

**Comment by lwcorp** [comment]
> For this, I am not sure. the PLUS version start menu integration seems to be introduced from the recent 1.4.0.

The original Sandboxie allowed right clicking inside Windows Explorer over any type of file to choose to open it in Sandboxie. Was this what added for Plus just now?

**Comment by okrc** [comment]
> The original Sandboxie allowed right clicking inside Windows Explorer over any type of file to choose to open it in Sandboxie. Was this what was added for Plus just now?

Starting from 1.4.0, it is possible to integrate the internal menu of the sandbox directly with the host start menu.This does not refer to the context menu of the right click.

**Comment by lwcorp** [comment]
Can you show a screenshot?

**Comment by okrc** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/29057533/194669809-97d91e43-875b-4f20-bb7e-c96da497a5d7.png">
<img width="463" alt="image" src="https://user-images.githubusercontent.com/29057533/194669858-403af4be-095b-4445-83f1-a9b363cb7d74.png">

**Comment by DavidXanatos** [comment]
@okrc could you please make the teble as MD than i could update it on the website

**Comment by lwcorp** [comment]
If you don't to wait, I put it in an online OCR reader, then manually edited it, hope I didn't forget anything:

| PLUS VS. CLASSIC                 | CLASSIC |              | PLUS     |          |          |                    |            |                    |
|----------------------------------|---------|--------------|----------|----------|----------|--------------------|------------|--------------------|
| LICENSE                          | FREE    | SUPPORTED    | FREE     | SMALL    | MEDIUM   | LARGE              | BUSINESS   | HUGE               |
| Usage                            |         |              | Personal | Personal | Personal | Personal           | Commercial | Commercial         |
| Support reminder                 | Yes     | No           | Yes      | No       | No       | No                 | No         | No                 |
| PCs per Certificate              |         | As Certified |          | Personal | Personal | Personal and Famiy | 1          | Personal and Famiy |
| Expiration                       |         | As Certified |          | 1 year   | 1 year   | 2 years            | 1 year     | No                 |
| Old builds work after expiration |         | As Certified |          | No       | Yes      | Yes                | Yes        | Yes                |
| UI Dark mode                     | No      | No           | Yes      | Yes      | Yes      | Yes                | Yes        | Yes                |
| Start Menu Integration           | No      | No           | Yes      | Yes      | Yes      | Yes                | Yes        | Yes                |
| Windows 11 Context menu          | No      | No           | Yes      | Yes      | Yes      | Yes                | Yes        | Yes                |
| Box Snapshots                    | No      | No           | Yes      | Yes      | Yes      | Yes                | Yes        | Yes                |
| Object Filtering                 | Yes     | Yes          | Yes      | Yes      | Yes      | Yes                | Yes        | Yes                |
| WFP support                      | No      | Yes (no UI)  | Yes      | Yes      | Yes      | Yes                | Yes        | Yes                |
| Privacy enhanced boxes           | No      | Yes (no UI)  | No       | Yes      | Yes      | Yes                | Yes        | Yes                |
| Security enhanced boxes          | No      | Yes (no UI)  | No       | Yes      | Yes      | Yes                | Yes        | Yes                |
| Compatybility enchanced boxes    | No      | Yes (no UI)  | No       | Yes      | Yes      | Yes                | Yes        | Yes                |
| Process Breakout                 | No      | Yes (no UI)  | No       | Yes      | Yes      | Yes                | Yes        | Yes                |

**Comment by megapro17** [comment]
So Sandboxie Classic is completely free and open source version that doesn't discriminate against business users
And Sandboxie Plus is version with proprietary GUI that adds a lot of restrictions to it's users, as well as a new features

**Comment by isaak654** [comment]
All feature references mentioned in this issue are outdated.
You can see the updated ones at https://sandboxie-plus.com/feature-comparison/
