### ISSUE TITLE
"Microsoft Edge 106.0.1370.37 stable" cannot run normally in sandboxie

### ISSUE THREAD

**Issue by 6Tom** [sandboxie-plus/Sandboxie#2325]
### Describe what you noticed and did

Msedge can't load any pages after today. The settings and extension pages cannot be loaded normally, either.

Msedge did receive an update today. I'm not sure whether it is relevant.

### How often did you encounter it so far?

Today (2022-10-08, 07:55 Washington time)

### Affected program

Microsoft Edge 106.0.1370.37 stable

### Download link

https://www.microsoft.com/en-us/edge

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

It should be able to browse websites, install extensions, and so on as before.

### What is your Windows edition and version?

Windows 10 Pro 21H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.3.5 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

since Sandboxie Plus 1.3.5 64-bit

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
I haven't changed the factory settings.
```

**Comment by DavidXanatos** [comment]
You can add
```
OpenIpcPath=msedge.exe,\Sessions\*\AppContainerNamedObjects\*
OpenFilePath=msedge.exe,\Device\NamedPipe\Sessions\*\AppContainerNamedObjects\*
```
to your sandboxie.ini in order to solve the edge issue.

**Comment by 6Tom** [comment]
That helps a lot, thanks. Have a nice day.

**Comment by PanoWest** [comment]
Same situation. Wasted a whole bunch of time trying to figure out what I had done.

The .ini file solution worked. Thanks.

**Comment by bjm234** [comment]
FWIW ~ I needed to disable Enhanced security, too. 
https://www.wilderssecurity.com/threads/edge-chrome-106-0-1370-37-and-sandboxie-5-58-5.448120/#post-3109082

**Comment by isaak654** [comment]
Someone reported that more calls are needed for MS Edge + the "Security enhancements" feature turned on:
- https://www.wilderssecurity.com/threads/edge-chrome-106-0-1370-37-and-sandboxie-5-58-5.448120/#post-3109097
- https://github.com/sandboxie-plus/Sandboxie/commit/c9929c626a0b6552f6045c1f2d5f6c709de72d86#commitcomment-86216466

**Comment by DavidXanatos** [comment]
i have added the missing syscalls to the aproved list

**Comment by wilders-soccerfan** [comment]
> i have added the missing syscalls to the aproved list

Is this the approved list found in Templates.ini?

**Comment by DavidXanatos** [comment]
yes

**Comment by isaak654** [comment]
After installing [v1.4.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.4.2), you have to enable the template "Enable Microsoft Edge compatibility workaround" in Options -> Global Settings -> Compatibility tab.

**Comment by 6Tom** [comment]
Understood. Thank you very much.
