### ISSUE TITLE
Make double-clicking templaes go to Edit ini Section

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#2327]
### Is your feature request related to a problem or use case?

1. Either enter an existing sandbox, then App Settings **or** Options=>Global Settings=>Compatibility
2. Double click any of them
3. In either case it takes you to a disabled App Settings screen:
![image](https://user-images.githubusercontent.com/1773306/194777794-e97a2c13-671a-4e54-b459-401a35ea2c6e.png)

### Describe the solution you'd like

Go to Edit ini Section which actually shows the bottom line of what stands behind the template, this should be default tab to show upon double clicking, then you can try other screens to learn about the template

### Describe alternatives you've considered

After a while I realize the disabled screen is irrelevant and tries other screens like Edit ini Section

**Comment by RandomGOTI** [comment]
#2301

**Comment by lwcorp** [comment]
> #2301

Just noting I observed this behavior in 1.4.1.

**Comment by RandomGOTI** [comment]
> > #2301
> 
> Just noting I observed this behavior in 1.4.1.

To translate my previous comment : this bug will be fixed in 1 4 2
