### ISSUE TITLE
Prevent VM detection

### ISSUE THREAD

**Issue by tommynanny** [sandboxie-plus/Sandboxie#234]
Hi, I am a newbie to this tool, I can't seem to be able to run a program inside Sandboxie due to VM detection. Is there a way to prevent and bypass the program from detecting the VM? 

Thanks!

![vm](https://user-images.githubusercontent.com/22390882/102146922-dace2b00-3e37-11eb-9a03-2a5a6bfe5f00.png)

**Comment by DavidXanatos** [comment]
Probably yes, but without knowing the program and its detection methods i cant say if its practical and if it it how to achieve that.

**Comment by mkyybx** [comment]
Have the exactly same issue when using the last official release of the Sandboxie. Still have no reason to trust GensShin Impact and a game shouldn't ask for admin privileges. Maybe you could try running it in real VMs (Virtual Box or VMWare) and they can be configured to hide the VM environment for the guest OS.

**Comment by DavidXanatos** [comment]
Just to clarify: is the game detecting sandboxie on a real machine.
or is it complaining about being ran on a virtual machine despite sandboxie?

**Comment by tommynanny** [comment]
https://genshin.mihoyo.com/en

ran the game on my real machine (no VM or Sandboxie) => works
ran the game on my real machine with Sandboxie (no VM) => complains about the Vm (the above image)

The game seems to be an IL2CPP build from Unity Engine, I try to apply reversed engineer but no luck so far, so I am not sure how they detect the Sandboxie as VM on a real machine... :(

**Comment by Gravityzwell** [comment]
This also happens with http://www.dmitrirender.ru/
dmitriRender_5.0.0.1_beta1.zip
Trying to install the trial throws a VM detected error.

**Comment by Gravityzwell** [comment]
Also the older version of dmitriRender throws a VM detected error. Note that it installed, but when actually invoking it, that's when the error is thrown.

https://www.softpedia.com/get/Multimedia/Video/Codec-Packs-Video-Codecs/DmitriRender.shtml
DmitriRender 3.0.0.1

**Comment by Gravityzwell** [comment]
Maybe of interest, a utility apparently to test if it is running in a VM or sandbox:
https://github.com/a0rtega/pafish

I ran this in a Sandbox and it triggered a on a few things. Not surprising since it apparently looks specifically for Sandboxie.

There are a few VirtualBox anti detection schemes. This I might try:
https://github.com/nsmfoo/antivmdetection

**Comment by bastik-1001** [comment]
#115 seems to be related to this. I think it's worthwhile to try to minimize what methods sandbox processes are able to use do detect if they are running inside a sandbox. It might be harder to avoid them being able to check which .dlls are loaded if that is possible at all.

For many things I don't understand why sandboxes are disliked by trustworthy software, but this is not the place to rant about that.

**Comment by Gravityzwell** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/98 also related.
In the case of DmitriRender, it uses starforce which is a separate DLL, and probably just calls it for detection, checking if the module is loaded as described in #98. So handling that one thing would probably handle a lot of existing cases. If starforce gets around to changing the detection method, it would involve a DLL update and new program version, so existing cases would still work.

**Comment by ameaninglessname** [comment]
#1204 Seems related.

**Comment by ameaninglessname** [comment]
I noteiced that when YuanShen.exe is running, it has a sub process:
`QtWebEngineProcess.exe   21768                    Running    10:18:41       "D:\Genshin Impact\QtWebEngineProcess.exe" --type=renderer --no-sandbox --disable-gpu-memory-buffer-video-frames --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations --disable-features=MojoVideoCapture,SurfaceSynchronization,UseModernMediaControls,UseVideoCaptureApiForDevToolsSnapshots --disable-gpu-compositing --service-pipe-token=IDeletedThis --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=IDeletedThis --renderer-client-id=2 --mojo-platform-channel-handle=3160 /prefetch:1   `

Notice the second parameter "-no-sandbox", so maybe someone could look into "QtWebEngineProcess" to see how the detection works.

"D:\Genshin Impact\QtWebEngineProcess.exe this is the path of sandbox where I installed it.


|Process|                                    |Status|   |Value|                         

launcher.exe (28108, 16804) - 10:18:40.123   Closed     \Device\HarddiskVolume3\Users              
launcher.exe (28108, 16804) - 10:18:40.123   Closed     \Device\HarddiskVolume3\ProgramData   

Would it satisfied if I opened these paths to it...

And why It cant access Users folder with "WriteFilePath=C:\Users" specified.
![image](https://user-images.githubusercontent.com/20263103/149645003-82794916-6906-40b0-9f69-3ec4d994f33d.png)

I manually created this folder "Users", so that I can open "Users" folder in sandbox.
But seems no app could access it still.

**Comment by ameaninglessname** [comment]
## Closed for QtWebEngineProcess.exe
|Process|                                              |Status|   |Value|                                                    

QtWebEngineProcess.exe (21768, 26956) - 10:18:41.110              \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_21768   
QtWebEngineProcess.exe (21768, 26956) - 10:18:41.110              \Sessions\1\BaseNamedObjects\SboxSession                                                         
QtWebEngineProcess.exe (21768, 26956) - 10:18:41.153              \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs        
QtWebEngineProcess.exe (21768, 8884) - 10:18:41.153               \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch   


## Closed for launcher.exe
|Process|                                    |Status|   |Value|                                                                                                                             

launcher.exe (28108, 16804) - 10:18:40.123   Closed     \Device\HarddiskVolume3\Users                                                                                                       
launcher.exe (28108, 16804) - 10:18:40.123   Closed     \Device\HarddiskVolume3\ProgramData                                                                                                 
launcher.exe (28108, 16804) - 10:18:40.198   Closed     \Device\HarddiskVolume3\Users\Win11\AppData                                                                                         
launcher.exe (28108, 16804) - 10:18:40.283   Closed     \Device\HarddiskVolume3\Users\Win11\AppData\Local\Temp                                                                              
launcher.exe (28108, 16804) - 10:18:40.368   Closed     \Device\HarddiskVolume3\Program Files                                                                                               
launcher.exe (28108, 16804) - 10:18:40.897   Closed     \Device\HarddiskVolume3\Users\Win11\AppData\Local\Google                                                                            
launcher.exe (28108, 16804) - 10:18:41.034   Closed     ApplicationManager_DesktopShellWindow                                                                                               
launcher.exe (28108, 28000) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo                                                                            
launcher.exe (28108, 28356) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\blob_storage                                        
launcher.exe (28108, 28000) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\Service Worker                                      
launcher.exe (28108, 28000) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\Service Worker\Database\LOG.old                     
launcher.exe (28108, 27968) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\blob_storage\2fff2aaa-6b26-45a3-800d-1a444c6e16c4   
launcher.exe (28108, 24480) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\Application Cache                                   
launcher.exe (28108, 28000) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\Service Worker\Database\LOG.old~RF51d4334.TMP       
launcher.exe (28108, 28000) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\Service Worker\Database\LOG.old                     
launcher.exe (28108, 28000) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\Service Worker\Database\LOG                         
launcher.exe (28108, 28000) - 10:18:41.099   Closed     \Device\HarddiskVolume3\Users\Win10\AppData\Local\miHoYo\YuanShen\QtWebEngine\Default\Service Worker\Database\LOG.old~RF51d4334.TMP       
launcher.exe (28108, 16804) - 10:18:52.279   Closed     ApplicationManager_DesktopShellWindow                                                                                               
launcher.exe (28108, 16804) - 10:18:55.106   Closed     ApplicationManager_DesktopShellWindow                                                                                               
launcher.exe (28108, 16804) - 10:18:55.106   Closed     ApplicationManager_DesktopShellWindow

**Comment by ameaninglessname** [comment]
#Only run YuanShen.exe will also trigger that error window

|Process|                                   |Status|   |Value|                                                                  

YuanShen.exe (7288, 11268) - 20:04:20.432   Open       \Sessions\1\Windows\SharedSection                                        
YuanShen.exe (7288, 11268) - 20:04:20.432   Open       \Sessions\1\Windows\ApiPort                                              
YuanShen.exe (7288, 11268) - 20:04:20.432   Open       \KnownDlls\PSAPI.DLL                                                     
YuanShen.exe (7288, 11268) - 20:04:20.432              \Device\HarddiskVolume3                                                  
YuanShen.exe (7288, 11268) - 20:04:20.432              \Device\HarddiskVolume4                                                  
YuanShen.exe (7288, 11268) - 20:04:20.432              \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_7288                  
YuanShen.exe (7288, 11268) - 20:04:20.432   Open       \RPC Control\SbieSvcPort                                                 
YuanShen.exe (7288, 11268) - 20:04:20.443              \Sessions\1\BaseNamedObjects\SboxSession                                 
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\user32.dll                                                    
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\win32u.dll                                                    
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\gdi32.dll                                                     
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\gdi32full.dll                                                 
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\msvcp_win.dll                                                 
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\ucrtbase.dll                                                  
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\ole32.dll                                                     
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\rpcrt4.dll                                                    
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\combase.dll                                                   
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\SHLWAPI.dll                                                   
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\MSVCRT.dll                                                    
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\Setupapi.dll                                                  
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\cfgmgr32.dll                                                  
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\bcrypt.dll                                                    
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\advapi32.dll                                                  
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\sechost.dll                                                   
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\SHELL32.dll                                                   
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\WS2_32.dll                                                    
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\OLEAUT32.dll                                                  
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\IMM32.dll                                                     
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\WINTRUST.dll                                                  
YuanShen.exe (7288, 11268) - 20:04:20.443   Open       \KnownDlls\CRYPT32.dll                                                   
YuanShen.exe (7288, 11268) - 20:04:20.443              \RPC Control\epmapper                                                    
YuanShen.exe (7288, 11268) - 20:04:20.454              \Device\DeviceApi                                                        
YuanShen.exe (7288, 11268) - 20:04:20.454              \Device\KsecDD                                                           
YuanShen.exe (7288, 11268) - 20:04:20.454   Open       \KnownDlls\NSI.dll                                                       
YuanShen.exe (7288, 11268) - 20:04:20.454   Open       \Device\Nsi                                                              
YuanShen.exe (7288, 11268) - 20:04:20.454              \Device\KsecDD                                                           
YuanShen.exe (7288, 11268) - 20:04:20.454   Open       \KnownDlls\bcryptPrimitives.dll                                          
YuanShen.exe (7288, 11268) - 20:04:20.454              \Device\CNG                                                              
YuanShen.exe (7288, 11268) - 20:04:20.454              \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs        
YuanShen.exe (7288, 27660) - 20:04:20.454              \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch   
YuanShen.exe (7288, 11268) - 20:04:20.516   Open       \ThemeApiPort                                                            
YuanShen.exe (7288, 11268) - 20:04:20.516   Open       \KnownDlls\MSCTF.dll                                                     
YuanShen.exe (7288, 11268) - 20:04:20.527   Open       \Sessions\1\Windows\ThemeSection                                         
YuanShen.exe (7288, 11268) - 20:04:20.527   Open       \Windows\Theme3342296654                                                 
YuanShen.exe (7288, 11268) - 20:04:20.527   Open       \Sessions\1\Windows\Theme1671597289                                      
YuanShen.exe (7288, 11268) - 20:04:20.527              \Sessions\1\BaseNamedObjects\Local\SM0:7288:304:WilStaging_02            
YuanShen.exe (7288, 11268) - 20:04:20.527              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02                  
YuanShen.exe (7288, 11268) - 20:04:20.527              \Sessions\1\BaseNamedObjects\Local\SM0:7288:304:WilStaging_02_p0         
YuanShen.exe (7288, 11268) - 20:04:20.527              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02_p0               
YuanShen.exe (7288, 11268) - 20:04:20.527              \Sessions\1\BaseNamedObjects\Local\SM0:7288:304:WilStaging_02_p0h        
YuanShen.exe (7288, 11268) - 20:04:20.527              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02_p0h              
YuanShen.exe (7288, 11268) - 20:04:20.538   Open       \KnownDlls\SHCORE.dll                                                    
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\windows_shell_global_counters               
YuanShen.exe (7288, 11268) - 20:04:20.538   Open       \Sessions\1\BaseNamedObjects\MSCTF.Asm.MutexDefault1                     
YuanShen.exe (7288, 11268) - 20:04:20.538   Open       \Sessions\1\BaseNamedObjects\CTF.AsmListCache.FMPDefault1                
YuanShen.exe (7288, 11268) - 20:04:20.538   Open       \Sessions\1\BaseNamedObjects\CicLoadWinStaWinSta0                        
YuanShen.exe (7288, 11268) - 20:04:20.538   Open       \Sessions\1\BaseNamedObjects\MSCTF.CtfMonitorInstMutexDefault1           
YuanShen.exe (7288, 11268) - 20:04:20.538   Open       \RPC Control\lsapolicylookup                                             
YuanShen.exe (7288, 11268) - 20:04:20.538   Open       \BaseNamedObjects\msctf.serverDefault1                                   
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\Local\SM0:7288:304:WilStaging_02            
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02                  
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02_p0               
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02_p0h              
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\Local\SM0:7288:304:WilStaging_02            
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02                  
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02_p0               
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:304:WilStaging_02_p0h              
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\Local\SM0:7288:120:WilError_03              
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:120:WilError_03                    
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\Local\SM0:7288:120:WilError_03_p0           
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:120:WilError_03_p0                 
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\Local\SM0:7288:120:WilError_03_p0h          
YuanShen.exe (7288, 11268) - 20:04:20.538              \Sessions\1\BaseNamedObjects\SM0:7288:120:WilError_03_p0h

**Comment by linax3-genuine** [comment]
i have this issue with another game.
i see it creating a 0 byte temp file and its name leads to QtSingleApplication Class and the SandMan.exe.

**Comment by BenoitAnastay** [comment]
It's all about a KernelMode Driver that's loaded to prevent cheating.

It's `mhyprot2`, it can only be run once, so at first glance there is no chance to sandbox it.

PPl are runing the game in VM, hiding to the guest the hypervision features.

**Comment by linax3-genuine** [comment]
in my case, i dont think i have this driver.

**Comment by BenoitAnastay** [comment]
@linax3-genuine 
It's mandatory to run the game one window, you can easillu check that with a simple command

```
>sc query mhyprot2

SERVICE_NAME: mhyprot2
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 3  STOP_PENDING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

**Comment by Luro223** [comment]
As mentioned in #2310 try to use https://github.com/VeroFess/SbieHide and check if your issue is resolved.

**Comment by isaak654** [comment]
### Discussed in https://github.com/sandboxie-plus/Sandboxie/discussions/3076

<div type='discussions-op-text'>

> <sup>Originally posted by **@acidhorse1972**</sup>
> Thinking about getting a Supporter Certificate when it finally offers prevention of detection of VM or hypervisor.
> That's really what I'm waiting on.</div>

> <sup>@DavidXanatos via Slack</sup>
> The use case is software which dont want to run under sandboxie or in a VM in general and the user is looking for a way to use sandboxie to run such an application in a vm. The required effort to make this work is huge

**Comment by DavidXanatos** [comment]
As anti DRM is outside the scope of sandboxie I'll close this request
