### ISSUE TITLE
BetterDiscord Installer won't render

### ISSUE THREAD

**Issue by Nypheena** [sandboxie-plus/Sandboxie#2340]
### Describe what you noticed and did

Download the installer
Run it
it never renders but everything is clickable
only renders when you set to no isolation

### How often did you encounter it so far?

always

### Affected program

BetterDiscord-Windows.exe

### Download link

https://betterdiscord.app/

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

it rendering

### What is your Windows edition and version?

windows 10 pro 21H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

F-Secure

### What version of Sandboxie are you running?

Latest plus 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

I don't know exactly but pretty sure worked in v1.1.3

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
Enabled=y
FileRootPath=C:\Sandbox\Redacted\Discord
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
Template=RpcPortBindingsExt
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=-
CopyLimitKb=-1
NeverDelete=y
LeaderProcess=Discord.exe
ProcessGroup=<StartRunAccess>,msedge.exe
NotifyStartRunAccessDenied=n
ClosedIpcPath=<StartRunAccess>,*
BreakoutProcess=brave.exe
AllowNetworkAccess=<BlockNetAccess>,n
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
DropAdminRights=y
ReadIpcPath=$:*
```

**Comment by okrc** [comment]
try add `UseElectronWorkaround=BetterDiscord.exe,y`

**Comment by DavidXanatos** [comment]
I restested it in the latest build 1.7.0 and now it works fine
