### ISSUE TITLE
[1.4.2] [W11 22H2] Most programs can't be opened in the hardened sandboxes

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2341]
_Originally posted by @isaak654 in https://github.com/sandboxie-plus/Sandboxie/discussions/2287#discussioncomment-3861681_

I was able to reproduce it with `Windows 11 22H2 x64 (22621.674)` inside the hardened sandboxes: it seems it is related to a hook named `PowerSettingRegisterNotification` that can't be run:

![PowerSettingRegisterNotification_hook](https://user-images.githubusercontent.com/12372772/195382679-c97473a4-53b1-48f4-9f51-6cb13c0ceaab.png)    

Standard sandboxes + W11 22H2 = unaffected
Hardened sandboxes with data protection + W11 22H2 = affected
Security Hardened sandboxes + W11 22H2 = affected

**Comment by okrc** [comment]
Correction, it seems that most software cannot be opened.

**Comment by isaak654** [comment]
Workaround:
![Security_options](https://user-images.githubusercontent.com/12372772/197579210-327b688c-cd3f-4c96-a001-0d5bfbe1b6e4.png)

Also, I see a connection with #2278

**Comment by DavidXanatos** [comment]
on my win 11 test VM insider dev channel orange boxes work just fine, strange...
how can i reproduce this issue?

**Comment by isaak654** [comment]
I'm on the stable branch of Windows 11 22H2 x64 - fresh Windows installation without third-party apps or tweaks involved.

**Comment by isaak654** [comment]
I'm on the stable branch of Windows 11 22H2 x64 - fresh Windows installation without third-party apps or tweaks involved.
Opening MS Edge or Windows Explorer as sandboxed is enough to reproduce it.

**Comment by isaak654** [comment]
As far as I know, there is a security feature that can only be used on new Windows 11 installations: [Smart App Control](https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003)

In the system in question, it is currently set to evaluation mode: 
![Smart_App_Control](https://user-images.githubusercontent.com/12372772/198739540-e729d0cd-4a32-4b6d-8aa6-20679c576d9c.png)

**Comment by DavidXanatos** [comment]
So when you disable this smart app controll sandboxie works fine?

**Comment by isaak654** [comment]
I'm not encouraged to disable it, because that would be a permanent change that could only be reversed with a new Windows 11 reinstallation... yes, Microsoft is getting weird.

**Comment by isaak654** [comment]
I'm not encouraged to disable it, because that would be a permanent change that could only be reversed with a new Windows 11 reinstallation... Microsoft is actually discouraging similar tests with such bold claims.

**Comment by isaak654** [comment]
I'm not encouraged to disable it, because that would be a permanent change that could only be reversed with a new Windows 11 reinstallation... Microsoft is actually discouraging it with such bold claims.

**Comment by DavidXanatos** [comment]
Fix for the general sandboxie operation:
NormalFilePath=\Device\SrpDevice

**Comment by DavidXanatos** [comment]
> I'm not encouraged to disable it, because that would be a permanent change that could only be reversed with a new Windows 11 reinstallation... Microsoft is actually discouraging it with such bold claims.

For testing I have created a clean fresh Win 11 VM and set this Smart App Control to activated.
The result:
1. You can not install sandboxie, or as far as I see it install anything that uses Inno Setup, as it creates a unsigned binary in the temp folder and SAC does not allow that to run.
2. You can just paste an unpacked signed sandboxie installation and it will work with SAC not just in evaluation but activated
3. When SAC fully is activated sandboxed edge crashes complaining that it can not load SbieDll.dll that will need to be fixed if possible, but given that other processes start its probably som parameter when creating edges worker processes which we can kill being injected in the main process
