### ISSUE TITLE
[1.4.2] Errors when opening MS Edge in blue/cyan/green sandboxes

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2342]
### I'm getting a couple of notification errors when opening Microsoft Edge in the following empty sandboxes types:

![blue](https://user-images.githubusercontent.com/12372772/195401546-08d013bd-3d4f-4a52-9076-eaa5bcc98aba.png)
![green+cyan](https://user-images.githubusercontent.com/12372772/195401612-0b243727-6bb2-4c12-bcc0-358257d62eda.png)

![Edge_errors](https://user-images.githubusercontent.com/12372772/195400801-141501f1-1cb0-49f2-8bb9-97aedf8410fb.png)

SBIE2309:

- [x] `cookie_exporter.exe: SBIE2309 Could not disable COM+/DCOM:  [21 / C0000022]`

SBIE2308:

- [x] `msedge.exe: SBIE2308 Could not create object directory:  [11 / 00000005]`

* the errors primarly happen with `Windows 11 22H2 x64 (22621.674) `
* sometimes they happen with `Windows 10 21H2 19044.2006`
* `Sandboxie Plus 1.4.2 x64` (fresh installation) + `Microsoft Edge 106.0.1370.42`
* `Template=Edge_Fix` is correctly applied in Sandboxie.ini
* they can be reproduced when opening MS Edge in empty sandboxes (blue/cyan/green types)
* they don't seem to break MS Edge, but still annoying to see or could indicate possible bugs

**Comment by mysteriously** [comment]
It crashes when you open settings in hardened sandbox

**Comment by isaak654** [comment]
> It crashes when you open settings in hardened sandbox

About the hardened sandboxes there is a separate issue #2341 (basically all programs on W11 22H2).

**Comment by isaak654** [comment]
Possible workaround to test for the SBIE2309 message:

`ReadKeyPath=cookie_exporter.exe,HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Ole`

Source: https://www.wilderssecurity.com/threads/what-is-hardened-sandbox-and-data-protection.446237/#post-3112044
