### ISSUE TITLE
QQ and TIM cannot display after updating to 22H2

### ISSUE THREAD

**Issue by Dr-TSNG** [sandboxie-plus/Sandboxie#2346]
### Describe what you noticed and did

1. Install QQ/TIM in sandbox
2. Try to start the program, the processes exist, but no window displays
3. Everything worked fine before I update to 22H2

### Affected program

TIM3.4.2.22058

### Download link

https://dldir1.qq.com/qqfile/qq/TIM3.4.2/TIM3.4.2.22058.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

QQ/TIM shows its window

### What is your Windows edition and version?

Windows 10 Pro 22H2 (22621.674)

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

Sandboxie Plus 1.4.2 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
CopyLimitKb=81920
DontOpenForBoxed=n
OpenPipePath=C:\Users\Nullptr\Documents\WeChat Files
OpenPipePath=C:\Users\Nullptr\Downloads
OpenPipePath=C:\Users\Nullptr\Documents\Tencent Files
ClosedFilePath=D:\
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
DropAdminRights=y
FakeAdminRights=y
BreakoutFolder=C:\Windows
WriteFilePath=C:\Program Files (x86)\Common Files\Tencent
WriteFilePath=C:\Program Files (x86)\Tencent
BoxNameTitle=-
```

**Comment by okrc** [comment]
我在一个干净的沙盒里并没有复现该问题。
<img width="539" alt="image" src="https://user-images.githubusercontent.com/29057533/195963727-130d316b-09ad-48a9-a188-a781a63acfa4.png">

**Comment by Dr-TSNG** [comment]
> ~我在一个干净的沙盒里并没有复现该问题。~ Try add `NoRenameWinClass=TIM.exe,*`

解决了，谢谢。能解释下是什么原理吗，挺好奇

**Comment by okrc** [comment]
```
NoRenameWinClass=TIM.exe,TXHttpWindow_SSO
NoRenameWinClass=TIM.exe,TXGuiFoundation
```
这个是更保守的设置，不过我没找到快捷键的窗口类，如果你发现了，请告诉我。





> 解决了，谢谢。能解释下是什么原理吗，挺好奇

参考 https://sandboxie-plus.github.io/sandboxie-docs/Content/OpenWinClass.html

**Comment by isaak654** [comment]
There is a generic explanation about NoRenameWinClass in [this comment](https://github.com/sandboxie-plus/Sandboxie/issues/2109#issuecomment-1250126148), but no precise documentation yet.
