### ISSUE TITLE
Add support for Microsoft Edge WebView2 apps

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2350]
### Is your feature request related to a problem or use case?

#2287 (originally posted by @6Tom)

> Dear friends, thank you very much for your hard work.
> 
> I found that all applications based on webview2 cannot run normally in the sandboxie. So may this support be added in the future?
> 
> Love you guys so much.

### Describe the solution you'd like

The same one described in #2287
I am not sure whether this should be applied in Templates.ini or elsewhere.

**Comment by DavidXanatos** [comment]
what software exactly does not work?

**Comment by okrc** [comment]
> what software exactly does not work?

All windows that use WebView2. For example, https://github.com/MicrosoftEdge/WebView2Samples/releases/tag/1.0.902-prerelease

**Comment by DavidXanatos** [comment]
for me
ExternalManifestHack=msedgewebview2.exe,y
is enough to get it working this will be included in the next build in the tempaltes.ini

**Comment by 6Tom** [comment]
Yes, originally, no webview2 app can run normally in sandboxie. But this
`ExternalManifestHack=msedgewebview2.exe,y` 
It solves the problem of many webview2 apps. I tried some webview2 apps, they can be used normally.

Thank okrc, isaak654 and DavidXanatos.
