### ISSUE TITLE
SBIE2203 *GUIPROXY_00000002 - *.exe [C0000022] on other sandbox except DefaultBox

### ISSUE THREAD

**Issue by localhost127001** [sandboxie-plus/Sandboxie#236]
`SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000002 - *.exe [C0000022]`
With my current "MySandbox" pop up showed 
In empty fresh "DefaultBox" NO pop up
In empty fresh "RandomBox" pop up showed
If I rename "MySandbox" to "Defaultbox" NO pop up

It's like the Sandboxie Service only communicate if gone through "Defaultbox" with these error type
This reminds me of the old trial era when we can only use one sandbox? maybe related?

I use Win 10 x64 and classic sandboxie btw, and yes I know I can just close the pop up. Would be nice if this pop up gone though

**Comment by DavidXanatos** [comment]
please compare the settings of the default box with the one of the box you have problems with.
Or post your Sandboxie.ini
And with what application does this issue appear?

**Comment by localhost127001** [comment]
<details>
  <summary>Click to expand</summary>
[GlobalSettings]

Template=Windows10CoreUI
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=D:\Sandbox\%USER%\%SANDBOX%

[DefaultBox]

ConfigLevel=7
AutoRecover=y
BlockNetworkFiles=y
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,off
Enabled=y
BoxNameTitle=n

[UserSettings_*******]

SbieCtrl_UserName=******
SbieCtrl_ShowWelcome=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_WindowCoords=722,225,912,641
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_NextUpdateCheck=1608656515
SbieCtrl_BoxExpandedView=DefaultBox,MyBox,Various
SbieCtrl_UpdateCheckNotify=y

[MyBox]

Enabled=y
ConfigLevel=7
AutoRecover=y
BlockNetworkFiles=y
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
BorderColor=#00FFFF,off
BoxNameTitle=n
NeverDelete=y


[Various]

Enabled=y
ConfigLevel=7
AutoRecover=y
BlockNetworkFiles=y
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,off
BoxNameTitle=n
NeverDelete=y
</details>

It's a game called The Pathless
I plays games in sandbox mostly for testing mods

**Comment by Coverlin** [comment]
`steam.exe (5928): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001 - steam.exe [C0000004]  ` 

Since it's related , i 'm getting this same sbie errorcode message for a couple applications regardless  the box they start in

This stops the popups spam from sbiectrl
`SbieCtrl_HideMessage=2203`

W7 Ultimate Sp1 x64

**Comment by localhost127001** [comment]
Yes I'm full aware of this makeup fix but by omitting the specific app lines code that's news for me. I much prefer permanent solution inside the app itself  tho. But that's up to David to close this issue or not. Thanks

**Comment by DavidXanatos** [comment]
This is a new one right you did not get it with 5.45.0 right?
If that is the case than I just fixed it.
If not I need to look further.

**Comment by DavidXanatos** [comment]
PS: no I think I only fixed the issue of Coverlin but not the on of localhost127001

@localhost127001 I don't see anything out of the ordinary in your ini config.. Cyn i someware download one of the applications you have problems with?

**Comment by localhost127001** [comment]
Sorry for my late reply, I got confused with which version that have the fix. If you mean the pre release 5.45.2
 than yes, no more *GUIPROXY_00000002 error either on new or old sandbox. Thank you

**Comment by DavidXanatos** [comment]
No problem, glad to hear its working for you now.
