### ISSUE TITLE
Making BreakoutProcess/BreakoutFolder free due to passing the required number of patrons

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#2360]
### Is your feature request related to a problem or use case?

See #1500.

### Describe the solution you'd like

The moment has finally arrived. With #1904 already done, can you please make both `BreakoutFolder` and `BreakoutFolder` free in the next released version?
> When I reach 250 patrons I'll make the BreakoutProcess feature available without the need for a support certificate.

![image](https://user-images.githubusercontent.com/1773306/196617537-fb00ad85-19e4-4ba9-a021-9b2026d6dacb.png)

**Comment by DavidXanatos** [comment]
Its already committed https://github.com/sandboxie-plus/Sandboxie/commit/3d58fe8d3f65959457ff4d855177bf10363af4e1
