### ISSUE TITLE
Breakout problem?

### ISSUE THREAD

**Issue by blap** [sandboxie-plus/Sandboxie#2366]
### Describe what you noticed and did

I have 3 boxes:
1- box named chrome with google chrome instaled in it.
2 - box named chromium with chromium instaled in it.
3 - whatever program instaled in it with Breakout program chrome.exe to try run chromium in box chromium.

Chromium is my default browser in windows 10 but only instaled in box chromium not outside this box.

- [ ] If I run any program in box 3 to run my default browser or just try to run my default browser in this box 3, Breakout program run chromium in box 1 not in box 2.
I tried to browse for file but in INI just give me BreakoutProcess=chrome.exe and not the fullpath in chromium box. Put the fullpath in INI with exe doesnt work too.

- [x] Another observation. You can remove "This feature requires a valid supporter certificate to be installed." in options:
https://github.com/sandboxie-plus/Sandboxie/blob/cc0e40446a25a12125888b75e6fed1b90285d42b/SandboxiePlus/SandMan/Forms/OptionsWindow.ui#L1568

### Affected program

Chromium

### Download link

Not relevant

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Open my default browser should open chromium in chromium box not in chrome box.

### What is your Windows edition and version?

Windows 10

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.5.0.exe

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment]
> Another observation: You can remove "This feature requires a valid supporter certificate to be installed." in options.

Confirmed:
https://github.com/sandboxie-plus/Sandboxie/blob/e00cacb0b9f00cb18eedabe705547934a71377c1/Sandboxie/core/drv/process.c#L1199-L1201

**Comment by offhub** [comment]
Did you try `BreakoutFolder`?

`BreakoutFolder=X:\SANDBOX\user\Box\drive\X\Chromium\Path\WithoutExe`

**Comment by DavidXanatos** [comment]
DRV_BREAKOUT is not defined we since many versions use a user mode only, service mediated breakout scheme

**Comment by blap** [comment]
#2121 maybe it is the same thing.

**Comment by DavidXanatos** [comment]
I cant reproduce this issue,
my setup

```
[DefaultBox]
...
BreakoutProcess=chrome.exe

[ChromeBox]
...
ForceFolder=C:\Sandbox\ChromeBox\drive\C\bin\Chrome\Application

[ChromeDev]
...
ForceFolder=C:\Sandbox\ChromeDev\drive\C\bin\Chrome Dev\Application

```


Now when is start,, in the default box, "C:\Sandbox\ChromeDev\drive\C\bin\Chrome Dev\Application\chrome.exe" is starts chrome dev in the dev box and if i start "C:\Sandbox\ChromeBox\drive\C\bin\Chrome\Application\chrome.exe" it starts normal chrone in teh chrom box

So everything seams to work fine, not sure what here fails for you...
also how did you set the sandboxed chromium to be globally the default browser?

**Comment by blap** [comment]
> I cant reproduce this issue, my setup
> 
> ```
> [DefaultBox]
> ...
> BreakoutProcess=chrome.exe
> 
> [ChromeBox]
> ...
> ForceFolder=C:\Sandbox\ChromeBox\drive\C\bin\Chrome\Application
> 
> [ChromeDev]
> ...
> ForceFolder=C:\Sandbox\ChromeDev\drive\C\bin\Chrome Dev\Application
> ```
> 
> Now when is start,, in the default box, "C:\Sandbox\ChromeDev\drive\C\bin\Chrome Dev\Application\chrome.exe" is starts chrome dev in the dev box and if i start "C:\Sandbox\ChromeBox\drive\C\bin\Chrome\Application\chrome.exe" it starts normal chrone in teh chrom box
> 
> So everything seams to work fine, not sure what here fails for you... also how did you set the sandboxed chromium to be globally the default browser?

I made this reg file to register chromium the default browser in windows:
[chromium.zip](https://github.com/sandboxie-plus/Sandboxie/files/9846989/chromium.zip)
ForceFolder in box 2 do nothing.

**Comment by blap** [comment]
> I cant reproduce this issue, my setup
> 
> ```
> [DefaultBox]
> ...
> BreakoutProcess=chrome.exe
> 
> [ChromeBox]
> ...
> ForceFolder=C:\Sandbox\ChromeBox\drive\C\bin\Chrome\Application
> 
> [ChromeDev]
> ...
> ForceFolder=C:\Sandbox\ChromeDev\drive\C\bin\Chrome Dev\Application
> ```
> 
> Now when is start,, in the default box, "C:\Sandbox\ChromeDev\drive\C\bin\Chrome Dev\Application\chrome.exe" is starts chrome dev in the dev box and if i start "C:\Sandbox\ChromeBox\drive\C\bin\Chrome\Application\chrome.exe" it starts normal chrone in teh chrom box
> 
> So everything seams to work fine, not sure what here fails for you... also how did you set the sandboxed chromium to be globally the default browser?

I got the problem now.
1- box named chrome with google chrome instaled in it had template "force google chrome to run in this sandbox".
2 - box named chromium with chromium instaled in it had template "force ungoogle chromium to run in this sandbox".

If I disable both templates, It run like was expected.

**Comment by DavidXanatos** [comment]
> If I disable both templates, It run like was expected.
> 

so is now all ok or is tehre stimm somethign in need of fixing?

**Comment by blap** [comment]
> > If I disable both templates, It run like was expected.
> 
> so is now all ok or is tehre stimm somethign in need of fixing?

Maybe templates diferentiate chrome from chromium to avoid this (both are chrome.exe), but be my guess.
