### ISSUE TITLE
[Feature request] request template for qq

### ISSUE THREAD

**Issue by lockmatrix** [sandboxie-plus/Sandboxie#2367]
### Is your feature request related to a problem or use case?

same as https://github.com/sandboxie-plus/Sandboxie/issues/2346
Win10, QQ new installed cannot display.

QQ: https://im.qq.com/download , wided used in China mainland.

### Describe the solution you'd like

Add a template for qq:
`NoRenameWinClass=QQ.exe,*`

**Comment by isaak654** [comment]
@lockmatrix 
Would you be available to provide an installation log file for QQ through an uninstaller program like "Revo Uninstaller" or similar?

**Comment by lockmatrix** [comment]
> Would you be available to provide an installation log file for QQ through an uninstaller program like "Revo Uninstaller" or similar?

I installed "Revo Uninstaller", and tried the uninstall process, but did not find any installation log or uninstallation log ...

**Comment by isaak654** [comment]
It should be generated before installing QQ, possibly in a fresh Windows system.
For more information: https://www.itechtics.com/monitor-system-file-registry-changes/

I would recommend to export both file & registry changes in a .txt or .log file to attach here.

**Comment by isaak654** [comment]
It should be exported soon after installing QQ, possibly in a fresh Windows system.
For more information: https://www.itechtics.com/monitor-system-file-registry-changes/

I would recommend to export both file & registry changes in a .txt or .log file to attach here.

**Comment by lockmatrix** [comment]
> About Revo Uninstaller, I seem to remember that this feature was only available in the Pro version.
oh, I only use the free version, I will try other tools.

**Comment by lockmatrix** [comment]
> I would recommend to export both file & registry changes in a .txt or .log file to attach here.

I wonder if it is possible to do this work by Sandboxie itself?
Sandboxie also knows which files and registry keys were modified

**Comment by okrc** [comment]
> NoRenameWinClass=QQ.exe,*

对于 QQ 来说，它似乎只在第一次启动时需要。

**Comment by lockmatrix** [comment]
> ~对于 QQ 来说，它似乎只在第一次登录时需要。~

原来如此，我说为什么我的旧沙盒不需要这个。

**Comment by lockmatrix** [comment]
> @lockmatrix Would you be available to provide an installation log file for QQ through an uninstaller program like "Revo Uninstaller" or similar?

WhatChanged dumped:
[qq_diff.zip](https://github.com/sandboxie-plus/Sandboxie/files/9845792/qq_diff.zip)

**Comment by isaak654** [comment]
This is the template I suggest to add in Templates.ini:

```
[Template_QQ]
Tmpl.Title=Tencent QQ
Tmpl.Class=Desktop
Tmpl.Url=https://im.qq.com/pcqq
Tmpl.Scan=s
Tmpl.ScanProduct={052CFB79-9D62-42E3-8A15-DE66C2C97C3E}
NoRenameWinClass=QQ.exe,*
```

If it works for you, then feel free to open a new pull request to require its inclusion in the Sandboxie releases.

**Comment by lockmatrix** [comment]
> No testing was made. If it works for you, then feel free to open a new pull request to require its inclusion in the Sandboxie releases.

It works

**Comment by 6Tom** [comment]
Thanks, this helps. Maybe you don't know, tencent's software is very rogue. But for some reason it needs to be used by many people in my country. We are really sick of it. It is the best choice to isolate it with sandboxie.

Thank you very much.
