### ISSUE TITLE
Rename Sandbox does not update FileRootPath, but it does rename the directory

### ISSUE THREAD

**Issue by CookiePLMonster** [sandboxie-plus/Sandboxie#2368]
### Describe what you noticed and did

Follow-up issue to #2357, since it can be viewed reasonably separate.

Rename Sandbox attempts to rename the sandbox directory if it matches the name of the sandbox. However, if a sandbox is relocated outside of the regular sandbox directory via a sandbox-specific `FileRootPath` option, this option is not updated (despite the directory renaming), leading Sandboxie to falsely consider the sandbox as empty. The user has to go and change the `FileRootPath` option themselves.

To reproduce:
1. Create a new sandbox named e.g. `Testing Sandbox`.
2. Go to `Sandbox Options` -> `Edit INI Section` and relocate the sandbox to another path and a directory named `Testing_Sandbox`, for example `D:\Sandboxes\Testing_Sandbox`
3. Boot anything in the Sandbox once, e.g. `explorer.exe`, so the sandbox gets populated with files.
4. Terminate all programs in the Sandbox and rename it to `Renamed Sandbox`.
5. Observe that `Testing_Sandbox` directory got renamed to `Renamed_Sandbox`, but `FileRootPath` did **not** get updated.

Tagging @okrc since they fixed the original issue and this issue is kind of related.

### How often did you encounter it so far?

Every time.

### Affected program

N/A

### Download link

N/A

### Where is the program located?

Not relevant to my request.

### Expected behavior

I would consider either of those two as valid behaviour:
* Rename Sandbox renames the directory **and** updates `FileRootPath` (if one exists) to point at that path.
**OR**
* Sandboxie does not rename the sandbox directory if `FileRootPath` is specified for that sandbox.

Personally I would prefer the first option, but the second option would also fix the issue in question.

### What is your Windows edition and version?

Windows 10 Pro 21H1

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.0 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

No

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

My sandbox contains existing programs or data.

**Comment by okrc** [comment]
`FileRootPath` is a fixed path, which is independent of the sandbox name.

**Comment by CookiePLMonster** [comment]
That doesn't seem to be the case for me:
![image](https://user-images.githubusercontent.com/7947461/196768474-b08e9127-ec09-480e-ac2b-2d10c607ac0c.png)
![image](https://user-images.githubusercontent.com/7947461/196768578-f9eef5dc-4d59-475c-aaba-f7b1bc6e32a6.png)

Notice that `FileRootPath` specifies a full path to the sandbox, at least when it's set per-sandbox. Perhaps this is the real issue here?

**Comment by okrc** [comment]
Well, since my English is very poor, I may have to re-understand what you mean. There is indeed something not as expected here.

**Comment by CookiePLMonster** [comment]
> Well, since my English is very poor, I may have to re-understand what you mean. There is indeed something not as expected here.

To put it simply:
1. If `FileRootPath` contains a full path to the sandbox, directory probably should not be renamed, or the option should be automatically updated.
2. If `FileRootPath` contains `%SANDBOX%` in path, then renaming is probably safe and can stay as-is.

**Comment by okrc** [comment]
I'm not sure it should get fixed. I'm not sure if the FileRootPath is allowed to be an absolute path or a value that must contain %SANDBOX%. When it is an absolute path, there are some additional errors.

**Comment by DavidXanatos** [comment]
fix: https://github.com/sandboxie-plus/Sandboxie/commit/3fb8d775453f864b8c53de7464ad86eae9915303

**Comment by CookiePLMonster** [comment]
Thank you! Just one note that might be worth mentioning - Rename Sandbox will **NOT** rename the directory if it doesn't match the box name! In other words Sandbox `Testing Sandbox` with `FileRootPath=D:\Sandboxes\HahaWrongName`, renamed to "Renamed Sandbox" will still keep `HahaWrongName` as a folder name.

To make the fix complete and non-breaking, it might be worth to either:
1. Rename the directory always, regardless of how it's named.
OR
2. Leave `FileRootPath` untouched if rename didn't take place.

**Comment by DavidXanatos** [comment]
its already implemented like "2. Leave FileRootPath untouched if rename didn't take place."

**Comment by CookiePLMonster** [comment]
Oh right, I missed the error check above - excellent.
