### ISSUE TITLE
some network suggestions

### ISSUE THREAD

**Issue by etianpro** [sandboxie-plus/Sandboxie#237]
Is it possible to make each Sandbox use a different network? For example, use a different proxy IP.
Thank you for your efforts.

**Comment by DavidXanatos** [comment]
that is something on my mind but its not that simple, if you have multiple connected VPN's a easy way would be to bind the socket to that adapter but for optimal isoaltion one would want somthing that is connected only to the box and to nothing else and thats quite complicated.

**Comment by etianpro** [comment]
Yes, it is very complex, expect to use proxy IP

**Comment by gtf35** [comment]
This restriction is quite effective for some programs

**Comment by maulvi** [comment]
would be great if program like proxifier working in sandboxie isolation sadly it throws error

**Comment by DavidXanatos** [comment]
further discussion on sandboxie's networking aspects please in issue #894
