### ISSUE TITLE
No video with supported format and MIME type found

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#2375]
### Describe what you noticed and did

1) Install SBIE 1.5.0
2) Open any streamable.com video found on google -> videos
3) 'No video with supported format and MIME type found' error shows up in Firefox.

Microsoft Edge (yellow sandbox) has the same issue.

I am able to play videos in both browsers using SBIE 1.4.2

### Affected program

Firefox 102.4.0esr x64

### Download link

https://www.mozilla.org/en-US/firefox/all/#product-desktop-esr

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Play a video

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Eset Endpoint Security 9.1.2057.0

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.0

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Since 1.5.0

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by bastik-1001** [comment]
Just as point of reference, Firefox 106.0.1 (64bit) on Windows 7 (64bit) can play videos from the mentioned website in Sandboxie Plus 1.5..0 (64bit), even inside a security enhanced sandbox.

**Comment by DavidXanatos** [comment]
I couldn't reproduce this with 1.7.0 chrome and firefox play videos just fine on my test system
