### ISSUE TITLE
Processes broken out of sandbox can have weird command line arguments

### ISSUE THREAD

**Issue by gexgd0419** [sandboxie-plus/Sandboxie#2377]
### Describe what you noticed and did

1. Create a sandbox.
2. Specify a breakout process, for example notepad.exe.
3. Run PowerShell in the sandbox.
4. Enter `start notepad` in the PowerShell window.
5. Notepad will complain "The system cannot find the path specified".
6. Check the spawned Notepad process using tools like Process Explorer. Its command line arguments will have a weird string in it. The string can be different each time you launch Notepad this way, and it seems like a random piece of data in memory.

Examples of the weird command line args:

- stem32\cdpusersvc.dll,-101
- stem32\drivers\fltmgr.sys,¾
- em32\themeui.dll,-2682

Trying to run Notepad in this sandbox in different ways can have different results. (Although in all cases Notepad can break out successfully)
- Start Notepad by Sandboxie's Run. Works as usual.
- Enter `notepad` or `start notepad` in Command Prompt. Works as usual.
- Enter `notepad` (not `start notepad`) in PowerShell. Works as usual.
- Enter `(New-Object -ComObject Wscript.Shell).Run("notepad")` in PowerShell. Weird command line args appear.
- Tried the WMI way of process creation, but failed.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The command line arguments should be passed correctly.

### What is your Windows edition and version?

Windows 10 Home 21H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender, Huorong

### What version of Sandboxie are you running?

v1.4.2 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by bastik-1001** [comment]
I tried to reproduce the main part of this issue, which I was successful with, having powershell use start notepad.exe or calc.exe, while those are breakout processes starts them with some appended gibberish. In my case some Asian letters are appended on Windows 7 (German, 64bit) with 1.5.0 (64bit).
