### ISSUE TITLE
Issues when trying to allow access to a single file in resource access rules

### ISSUE THREAD

**Issue by gexgd0419** [sandboxie-plus/Sandboxie#2379]
### Describe what you noticed and did

Sometimes users may want to allow access to only a single file in a certain directory, while all other files are invisible (the folder is a WriteFilePath).

Seems that users can allow access to a single file in resource access rules, and the UI elements suggest that you can do so (add a file path).

However,

- The allowed file will be incorrectly listed as a "directory". You cannot treat it as a directory, though; it should still be opened as a file. Programs that open the file directly by its path will succeed, while programs like Explorer will think it's a folder and fail to open it.
- Its attributes, such as the last modified time, are incorrect.
- The resource access rule for the single file has an implicit asterisk (*) appended, so it actually matches all files & folders that share the same name prefix. The other matching items won't get shown in directory listings, but you can still access them by their paths.

To reproduce:

- Create a directory `C:\test`, files `C:\test\a.txt`, `C:\test\a.txt.b.txt`, and a directory `C:\test\a.txt.c`.
- Create a sandbox, enable Rule Specificity, set `C:\test` as WriteFilePath, `C:\test\a.txt` as NormalFilePath.
- Open Explorer in the sandbox, and check the `C:\test` folder. A folder named `a.txt` gets shown, but Explorer cannot open it.
- You can get the content of `C:\test\a.txt` by entering `type C:\test\a.txt` in Command Prompt.
- Although `C:\test\a.txt.b.txt` and `C:\test\a.txt.c` are not shown in `C:\test`, you can access them by typing the path.
- If you add an explicit wildcard in the rule's path, like `C:\test\*.txt`, a "directory" without a name will be shown inside `C:\test`.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

- If the allowed path is a file, list it as a file, with its correct attribute data.
- If the allowed path matches multiple items, list all matching items in directory listings, instead of just one item that is made out of the given path.

Is there a way to write a resource access rule that matches exactly one item with a specified name, without any explicit or implicit wildcards?

Or maybe we can change the way Sandboxie treats rules without wildcards so:

  - If the path points to a file, do an exact match. So `C:\a.txt` matches only `C:\a.txt`, not `C:\a.txt.b.txt`.
  - If the path points to a directory, do an exact match on that directory, and also match its children. So `C:\Users` is equivalent to `C:\Users\*`. (Not `C:\Users*` as it would also match its siblings like `C:\UsersData`)
  - If the path ends with `\`, append a `*`.
  - If the path doesn't exist on the system, don't show it in directory listings.

### What is your Windows edition and version?

Windows 10 Home 21H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender, Huorong

### What version of Sandboxie are you running?

v1.4.2 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by mysteriously** [comment]
#2039

**Comment by DavidXanatos** [comment]
I have tested the scenario with 1.10.0 and could no longer reproduce the issue one of the fixes in the eman time must have resolved it :D
