### ISSUE TITLE
Can you also add trusted signatures to the software?

### ISSUE THREAD

**Issue by Gianthard-XYZ** [sandboxie-plus/Sandboxie#238]
Hello there
My English is poor
There is a small problem. I noticed that the driver now has a trusted signature
Can you also add trusted signatures to the software?
thank you very much! Hope you can understand what I mean

**Comment by DavidXanatos** [comment]
Yea I will probably do that for the next build didn't want to do that for the installers that still contained the "provisionally" driver for windows 7.
