### ISSUE TITLE
in the sandboxie two app  don't  access each othe,eg: chrome can't access clash for  Internet in sandboxie

### ISSUE THREAD

**Issue by jackwan990** [sandboxie-plus/Sandboxie#2393]
### Describe what you noticed and did

two app  don't  access each othe in the sandboxie ,eg: chrome can't access clash for  Internet in sandboxie
we  still keep the port of clash for windows  is 56492

i drag clash for window into sandboxie,and run Google Chrome Outside the sandbox.The Google Chrome can access internet with clash for window

but i drag clash for window  and Google Chrome  into sandboxie,iconfigure the  port of clash for windows ,The Google Chrome  can't access   internet with clash for window.

why  The Google Chrome  can't access  internet with clash for window  in sandboxie? 
but can access  internet  if  The Google Chrome  outside the sandboxie ?

thank you answer ！！！

### How often did you encounter it so far?

every day

### Affected program

The Google Chrome ,clash for window 

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

please tell me how to let The Google Chrome   access   internet with clash for window in the sandboxie

The Google Chrome and clash for window are both in the sandboxie

### What is your Windows edition and version?

Windows 10 教育版

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

no 

### What version of Sandboxie are you running?

Sandboxie 1.5.0 64bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no

### Sandboxie.ini configuration

```shell
Enabled=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
ProcessGroup=<InternetAccess>,chrome.exe,Clash for Windows.exe,clash-win64.exe,netsh.exe,ROUTE.EXE,SandboxieRpcSs.exe,sysproxy.exe
ProcessGroup=<InternetAccessDisabled>,
BoxNameTitle=y
CopyLimitKb=81920
AllowRawDiskRead=y
NotifyDirectDiskAccess=y
BlockNetParam=n
BlockNetworkFiles=n
LingerProcess=Clash for Windows.exe
OpenPipePath=<BlockNetDevices>,InternetAccessDevices
OpenPipePath=sysproxy.exe,InternetAccessDevices
NetworkAccess=*,Allow
DropAdminRights=y
FakeAdminRights=y
OpenIpcPath=chrome.exe,
OpenIpcPath=clash-win64.exe,
OpenIpcPath=Clash for Windows.exe,
OpenIpcPath=sysproxy.exe,
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
```

**Comment by DavidXanatos** [comment]
what is clash and where to download it?
