### ISSUE TITLE
Plus 1.5.0 x64 UI Bugs ┐(ﾟ～ﾟ)┌

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2395]
- [x] 1 Edited box options bug
Bug confirmed with force process
Add `Test.exe` (press apply to add it to ini) and double click and edit it to `Test_123.exe` click or enter and then click apply the entry is now out to buy milk ... (removed) In other words any edited entry via 2x clicking gets removed (from ini)
This bug extends to breakout , linger , leader processes
Start restrictions after a entry is edited not disabled/unchecked `ProcessGroup=<StartRunAccessDisabled>,` gets added to ini (unneeded/leftover)
Resorce access and network options not affected

- [x] 2 Start restrictions display bugged when remove is used
Add ~4 processes with random names
remove 1 ... i said just 1... whatever... press apply... the ones that didin't get intentionally removed and vanished are back...probably...maybe 
Also leftover when everything is intentionally removed `ProcessGroup=<StartRunAccess>, `

### What is your Windows edition and version?
Windows 7 Ultimate SP1 x64
### Please mention any installed security software
None/WD disabled
### What version of Sandboxie are you running?
Plus 1.5.0 x64
### Is it a new installation of Sandboxie?
I just updated Sandboxie from a previous version (to be specified). 1 4 2

**Comment by isaak654** [comment]
1. in Plus 1.5.0 x64, the renamed entry was simply moved at the top (in a list of 4 forced processes)
2. confirmed

**Comment by isaak654** [comment]
@RandomGOTI 
Please try [this build](https://github.com/sandboxie-plus/Sandboxie/actions/runs/3327456832) to confirm the fixes.

**Comment by RandomGOTI** [comment]
Everything is fixed except mentioned empty pgroups
`ProcessGroup=<StartRunAccess>,` not removed when last entry is removed from the group
`ProcessGroup=<StartRunAccessDisabled>,` is inserted/created whenever an entry is edited or removed

**Comment by DavidXanatos** [comment]
Leaving empty groups in is for now intentional, I may change it at some point for better optics...

**Comment by DavidXanatos** [comment]
fyi: in build 1.5.2 I'll add an auto clean up for the groups.
