### ISSUE TITLE
v5.45.0 broken all installer (Solved)

### ISSUE THREAD

**Issue by Yituo3712VP** [sandboxie-plus/Sandboxie#240]
Since updating this version, all installers have encountered the same error

SBIE 1231 Initialization failed for process chrome.exe [C0000038 / 66]
SBIE 1231 Initialization failed for process [C000001 / A0]
SBIE 2314 Canceling process chrome.exe

The cause of the problem is unknown
Now install the old version v5.43.7 the problem does not occur again

**Comment by DavidXanatos** [comment]
what is the last version that is problem free?
Also are you using 32 bit or 64 bit windows?
what other programs crash? You said instalelr but in the log you provided its chrome.exe

**Comment by Yituo3712VP** [comment]
> 沒有問題的最新版本是什麼？
> 您還在使用32位或64位窗口嗎？
> 還有哪些其他程序崩潰？您說過instalelr，但在日誌中提供了chrome.exe

Currently using the old version SandboxieInstall64-v5.43.7
Event log：Event ID 65 - AppModel-Runtime
Failed with 0x57 retrieving AppModel Runtime status for package Windows

[https://imgur.com/2XYO41X](url)
Same error like this

**Comment by DavidXanatos** [comment]
what program?

**Comment by Yituo3712VP** [comment]
> 什麼程序？

I mean if the program is not installed or executed in sandboxie, no errors will occur SBIE1231, SBIE2314,errors occur when trying to install in the sandbox.
Windows event log: Failed with 0x57 retrieving AppModel Runtime status for package Windows.
Currently used software: Firefox install.exe, cpuz.exe, gpuz.exe

**Comment by Yituo3712VP** [comment]
I think v0.5.1 or v0.45.0 broken the system
00:01:00 Install sandboxie x64 v5.43.7 and reboot
00:02:27 Install Firefox in the sandbox and execute it normally
00:05:31 Use revo uninstaller pro to backup and uninstall the sandbox
00:06:11 Install sandboxie-plus x64 v0.45.0 and reboot
00:08:33 sbie1231 and sbie2314 errors occur when Firefox is installed again in the sandbox
00:10:18 Use DISM /Online /Cleanup-Image /RestoreHealth and reboot
00:12:25 Install sandboxie x64 v0.45.0 again and reboot
00:13:09 Installation of Firefox in the sandbox resulted in an access denied sbie1231 error (administrator rights)
00:15:19 Uninstall v0.45.0 and use SFC, DISM to restore commands
00:16:52 Install the old version of sandboxie x64 v5.43.7 and reboot
00:17:59 Install Firefox and gpu-z in the sandbox and install and execute normally

※The system was restored 3 times, and the problem occurred after installing the new version

**Comment by DavidXanatos** [comment]
On my test setup i can install firefox to a sand box and run it without issues, strange.

**Comment by Yituo3712VP** [comment]
> 在我的測試設置中，我可以將Firefox安裝到沙盒中並運行，而不會出現問題，這很奇怪。

Today I tested sandboxie-plus-x64-v0.5.1, rebooted after installation and uninstalled using the console and rebooted again.
Then install the old version 5.43.6 and reboot, an error occurred when trying to install firefox in the sandbox
sbie 1231 initialization failed for process firefox installer.exe
system error code: access is denied. (5) 
Trying to install firefox in the sandbox with administrator rights error:only part of a readprocessmemory or writeprocessmemory request was completed

The problems are all after installing the new version of the sandbox and uninstalling
Old versions 5.43 to 5.44.1 can currently install programs in the sandbox

**Comment by Yituo3712VP** [comment]
> 在我的測試設置中，我可以將Firefox安裝到沙盒中並運行，而不會出現問題，這很奇怪。

Today I installed the new version v5.45.1 and retested the old version v5.43.7, error did not recur again, maybe it is a win10 compatibility issue

v5.45.1：Fixed the driver compatibility issue for Windows 20H1 and later

**Comment by DavidXanatos** [comment]
so its fixed? great than i'll close this one
