### ISSUE TITLE
Allow to read memory of unsandboxed processes and Breakout Programs checkboxes doesn't work

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2400]
### Describe what you noticed and did

- [x] 1. `Allow to read memory of unsandboxed processes` checkbox does not persist after the options ui is closed. (fix: https://github.com/sandboxie-plus/Sandboxie/commit/65f936b3a4f7d041cf42484287ed5fe83a619923)
- [x] 2. `Show Template` checkbox in the `Breakout Programs` tab doesn't work. But `Show Template` checkbox in the `Force Programs` tab works for both tabs. (fix: https://github.com/sandboxie-plus/Sandboxie/commit/1cb0cc0e1f0674d99fc9eeb043a516915a752f9f)

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

1. The checkbox should stay checked.
2. Checkboxes should work independently from each other.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.5.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
2 is fixed
i cant reproduce 1 though

**Comment by DavidXanatos** [comment]
found  it fixed it
