### ISSUE TITLE
[x86 builds] 32-bit users cannot run anything in sandbox because of SBIE2112 error

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2401]
Originally reported in https://www.wilderssecurity.com/threads/sandboxie-plus-v1-5-0-v1-5-1.448352/page-2
All x86 builds starting from [Release v1.5.0 / 5.60.0](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.5.0) seem interested.
Last working version for one of them is [Release v1.4.2 / 5.59.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.4.2). 

| Report 1 |
| -------- |
> I'm running Windows v10.0.18362.356 (32-bit) in VMWare Player and have installed Sandboxie v5.60.0 (32-bit). When I try to run anything sandboxed I get: "SBIE2112 Object is not accessible: \WindowsErrorReportingServicePort, call AlpcConnectPort (C0000022) access=001F0001 initialized=1".
>
> What could be causing this and how to make it work?
>
> Thank you. 

| Report 2 |
| -------- |

>  On Win7 32 bit machine unable to open Firefox or Brave in v1.5.0. Get "SBIE 2112 Object is not accessible: Windows error reporting" error message. No problems opening either browser on Win10 64 bit machines in v1.5.0.
>
> Any advice much appreciated. 
>
>----------
>
> So, it seems to be a in issue with 32-bit systems, because as mentioned above, I get the same error message on a Win7 32-bit machine. 
>
>---------
>
> SBIE2112 issue persists in 1.5.1 for Firefox and Brave on Win7 32-bit machine. No problems when roll back to 1.4.2.

**Comment by DavidXanatos** [comment]
Oh no... that will be a pain to debug will look into it though...
