### ISSUE TITLE
Failure to reboot and files left over when upgrading from Classic to Plus

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#2404]
### Describe what you noticed and did
This is a series of bug reports documenting my findings when upgrading from Sandboxie Classic to Sandboxie Plus.
I went from an old install of Classic 5.60.0 to Plus 1.5.0

I started the Sandboxie Plus Setup which successfully detected that Classic was installed, suggesting an uninstall first.

- [x] Bug A)
The Uninstaller succesfully removed most files and told me that a reboot was necessary.
I selected "Reboot Now"
The Uninstaller succesfully shut down my browser and file explorer, but was not able to shut down the lingering Sandboxie process and kept waiting forever.
![stuckscreen2](https://user-images.githubusercontent.com/12411527/203792407-e4477427-46d5-45a8-a932-a6ce1936b072.jpg)
After one minute of waiting I decided to reboot manually since I didn't see any progress.

- [x] Bug B)
After the reboot, there are files left over in the old Sandboxie Classic folder:
`SbieIni.exe.sig` 
(fix: https://github.com/sandboxie-plus/Sandboxie/commit/7d86aa2f03f4cf7b3d2467b36ceeefe66576e15f)

### Affected program

Sandboxie Uninstaller

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Bug A) The Uninstaller should be able to shut down Sandboxie Classic and reboot on its own without getting stuck waiting.

Bug B) There should be no leftovers after uninstall.

### What is your Windows edition and version?

Windows 10 Edu 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie 5.60.0

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
For bug B, I created #2409

**Comment by isaak654** [comment]
For bug B, I created the pull request #2409

**Comment by NewKidOnTheBlock** [comment]
For bug A, I've added a screenshot.
