### ISSUE TITLE
Setup Wizard doesn't honour Template selection

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#2405]
### Describe what you noticed and did

After installing Sandboxie Plus, the Setup Wizard starts.
It shows you a list of possible Compatibility Templates and asks you to make your selection.

Reproduction Steps:
- install a fresh copy of Sandboxie Plus
- run Setup Wizard
- uncheck a few boxes from the Compatibility Template list
- finish Setup Wizard
- launch Sandboxie Plus
- open General Options
-> ALL Compatibility Template boxes are CHECKED despite your earlier selection

### How often did you encounter it so far?

After fresh install & Setup Wizard

### Affected program

Sandboxie Plus Setup Wizard

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The Setup Wizard should honour my Template selection and stick to it instead of ignoring it.

### What is your Windows edition and version?

Windows 10 Edu 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.50.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
Could you post a video with the necessary steps to reproduce it?

**Comment by isaak654** [comment]
I was unable to reproduce this, even with a fresh installation of Sandboxie Plus.
If you could provide a video, it would still be appreciated.

**Comment by NewKidOnTheBlock** [comment]
I think I can come up with some screenshots this Tuesday.

**Comment by APMichael** [comment]
I have installed Sandboxie (in various versions) countless times recently in my test VM. However, I can't reproduce the problem described here either.

**Comment by NewKidOnTheBlock** [comment]
Hmm. Did a fresh install and couldn't reproduce it either.
But I could have sworn it didn't work when I upgraded my stone-age Classic to Plus. My old Classic had a couple of Compatibility Templates that weren't present anymore in the fresh Plus install.
