### ISSUE TITLE
"Don't show icons in menus" still shows an icon in the Help menu

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#2406]
### Describe what you noticed and did

Sandboxie Plus:

- open General Options
- Interface Config
- select "Don't show icons in menus"
![dontshowicons1](https://user-images.githubusercontent.com/12411527/198214939-ebb45b1f-f169-466e-98ae-9ffb6a3d8b4c.png)

- still have icons in menus:
![dontshowicons2](https://user-images.githubusercontent.com/12411527/198215019-2fefeccc-c748-4e94-9ba5-8d939b51f970.png)

### Affected program

Sandboxie Plus menus

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

There actually should be no more icons in the menu.

### What is your Windows edition and version?

Windows 10 Edu 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.50.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
> * still have icons in menus:
>       ![dontshowicons2](https://user-images.githubusercontent.com/12411527/198215019-2fefeccc-c748-4e94-9ba5-8d939b51f970.png)

That's the only icon that seems to appear in every case, maybe @DavidXanatos could clarify whether it was intended.

**Comment by DavidXanatos** [comment]
I would leave it as is changin this would be extra code as this icon is loaded differently then all others and imho it should stay

**Comment by NewKidOnTheBlock** [comment]
Once could very well debate why this option exists in the first place.
But if it does, it should actually do what it says.

**Comment by DavidXanatos** [comment]
> Once could very well debate why this option exists in the first place. But if it does, it should actually do what it says on the tin.

This feature exists to make the "Vintage Mode" in SamdMan.exe look as close as possible to SbieCtrl.exe that is no icons, but since no icons looks terrible there is a setting to be able to have vintage mode with icons, or for those who like terible 90's ui's the ability to remove icons in non vintage mode.
