### ISSUE TITLE
sbie2227 Defaultbox is located on a volume which does not support 8.3 naming. This can cause issues with older applications and installers.

### ISSUE THREAD

**Issue by darchon7** [sandboxie-plus/Sandboxie#2407]
### Describe what you noticed and did

1. start up firefox portable 106.0.2 (64-bit)

this error message pops up:

sbie2227 Defaultbox is located on a volume which does not support 8.3 naming. This can cause issues with older applications and installers.

### How often did you encounter it so far?

always

### Affected program

firefox portable 106.0.2 64-bit

### Download link

https://portableapps.com/apps/internet/firefox_portable

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

no notification popup should appear.

### What is your Windows edition and version?

windows 10 pro 21h2 64-bit b19044.2130

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

bitdefender

### What version of Sandboxie are you running?

1.5.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=Edge_Fix
Template=RpcPortBindings
Template=WindowsRasMan
Template=BitDefenderInternetSecurity
Template=7zipShellEx
Template=Listary
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=RoboForm
FileRootPath=d:\Sandbox\%USER%\%SANDBOX%
KnownConflicts=BitDefender
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%

[DefaultBox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=n
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
RecoverFolder=d:\Program Files
RecoverFolder=F:\Downloads
RecoverFolder=C:\Users\dwayne\Downloads
RecoverFolder=C:\Users\dwayne\AppData\Local\RoboForm
BorderColor=#00ffff,ttl,6
Enabled=y
OpenFilePath=<firefoxprograms>,D:\Program Files\
OpenFilePath=firefoxportable.exe,D:\Program Files\
OpenFilePath=firefox.exe,D:\Program Files\
OpenFilePath=<firefoxprograms>,F:\Downloads\
OpenFilePath=firefoxportable.exe,F:\Downloads\
OpenFilePath=firefox.exe,F:\Downloads\
OpenFilePath=robotaskbaricon.exe,%Personal%\My RoboForm Data\
OpenFilePath=robotaskbaricon.exe,C:\Program Files (x86)\Siber Systems\AI RoboForm\
OpenFilePath=qbittorrent.exe,%AppData%\qBittorrent\
OpenFilePath=qbittorrent.exe,%Local AppData%\qBittorrent\
OpenFilePath=qbittorrent.exe,H:\
OpenFilePath=operaportable.exe,D:\Program Files\
OpenFilePath=opera.exe,D:\Program Files\
OpenFilePath=chrome.exe,D:\Program Files\
OpenFilePath=googlechromeportable.exe,D:\Program Files\
OpenFilePath=rf-chrome-nm-host.exe,C:\Users\dwayne\AppData\Local\RoboForm\
OpenPipePath=qbittorrent.exe,%{374DE290-123F-4565-9164-39C4925E467B}%\
ClosedFilePath=*BitDefender*atcuf*.dll
WriteFilePath=C:\Program Files\Bitdefender\*
OpenWinClass=#
BoxNameTitle=n
BlockNetParam=y
DropAdminRights=n
FakeAdminRights=n
ClosePrintSpooler=n
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
CopyLimitKb=81920
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=n

[UserSettings_11C20289]

SbieCtrl_UserName=dwayne
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1614796928
SbieCtrl_WindowCoords=200,150,909,596
SbieCtrl_ActiveView=40021
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[UserSettings]

SbieCtrl_AutoStartAgent=SandMan.exe
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by NewKidOnTheBlock** [comment]
This error message also pops up with Chrome Portable. Just noticed today.
Seems to get triggered always in Plus 1.5.1, no matter what program you run sandboxed.

**Comment by RandomGOTI** [comment]
1.5.1 https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md#added 

> added SBIE2227 warning when a sandbox is located on a volume without 8.3 name support

https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.5.1

> Note: if you encounter the new message SBIE2227, the right course of action is to enable 8.3 name support for the volume you are using. Assuming you are using for example a RAM disk with the letter R:\, use the following command in an elevated command prompt:
`fsutil behavior set disable8dot3 R: 0`
This is not a new issue, but an old forgotten one.
The message has been added to bring attention to potential problems and offer instructions how to properly resolve the issue.

**Comment by isaak654** [comment]
A fix is planned for SBIE2227 with virtual drives in 1.5.2 / 5.60.2. For the rest, I would advise not to hide the message.

**Comment by isaak654** [comment]
A fix is planned for SBIE2227 with virtual drives in 1.5.2 / 5.60.2. 
I would advise not to hide the message and consider enabling 8.3 name support, which is a Windows feature still needed for old installers or programs with outdated libraries.

**Comment by isaak654** [comment]
#2302

**Comment by APMichael** [comment]
@darchon7 Open an elevated ("Run as administrator") command prompt, type `fsutil behavior set disable8dot3 D: 0` and press the "Enter" key. This will enable 8.3 name support for your D: drive and the error message should no longer appear.

**Comment by darchon7** [comment]
so help me understand why this setting is required by sandboxie since previous versions didn't seem to require this? also I checked all my volumes have this feature turned off except for my boot drive (C:) and I've been fine without it being enabled.

**Comment by APMichael** [comment]
It can be read here why @DavidXanatos included the message:
https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.5.1

And here:
https://www.wilderssecurity.com/threads/sandboxie-plus-v1-5-0-v1-5-1.448352/page-2#post-3112543

If you do not want to activate the function, then you can only hide the SBIE2227 message.

**Comment by isaak654** [comment]
It's the kind of Windows issue present in some programs that would erroneously suggest a Sandboxie issue. 
The lead developer must have thought that, by hiding it, one cannot directly know whether the missing 8.3 name support might be involved in a future compatibility issue.

**Comment by DavidXanatos** [comment]
Its one of the things that are super esoteric and no one would think of it,
see  this bug report: https://github.com/sandboxie-plus/Sandboxie/issues/2302
I spent a couple hours debugging this until I saw that sandboxie does everything just right and its the underlying file system that is the root of the problem.

So sbie2227 was born.

I'll release a build later today that should fix the issues with virtual drives being always miss reported as not having 8.3 support.

There is no point in disabling the message as you can easily hide it anyways.

**Comment by darchon7** [comment]
cool! tx for the explanations!

**Comment by mysteriously** [comment]
Please allow us to permanently delete DefaultBox or if is so deeply hardcoded then at least hide it from UI.

**Comment by DavidXanatos** [comment]
due to logistic reasons the bug fix release can be signed the earliest on Tuesday ...

**Comment by APMichael** [comment]
> Please allow us to permanently delete DefaultBox or if is so deeply hardcoded then at least **hide it from UI**.

That actually has nothing to do with the topic. But you just have to **edit** the **ini** and change the line `Enabled=y` to `Enabled=n`.

**Comment by DavidXanatos** [comment]
the message shoudl not be shown wrongfully in the todays build 1.5.2

**Comment by APMichael** [comment]
> the message shoudl not be shown wrongfully in the todays build 1.5.2

Confirmed! Sandboxie now also detects the enabled 8.3 name support of the RAM disk. Thanks a lot!
