### ISSUE TITLE
SBIE2112 on Win8.1 32-bit when i start a Commandline

### ISSUE THREAD

**Issue by MCSE-2000** [sandboxie-plus/Sandboxie#2410]
### Describe what you noticed and did

1. Right Click on DefaultBox
2. Start -> Commandline
3. Error: tart.exe (2216): SBIE2112 Objekt ist nicht zugänglich: \WindowsErrorReportingServicePort, Aufruf AlpcConnectPort (C0000022) access=001F0001 initialized=1
4. Error: WerFault.exe (3304): SBIE2112 Objekt ist nicht zugänglich: \WindowsErrorReportingServicePort, Aufruf AlpcConnectPort (C0000022) access=001F0001 initialized=1
![2022-10-27 17_06_16-Sandboxie-Plus v1 5 1](https://user-images.githubusercontent.com/84094043/198336239-6a41e415-09bf-4da1-9f36-e5d069d3756a.png)
![2022-10-27 17_07_04-Sandboxie-Plus v1 5 1](https://user-images.githubusercontent.com/84094043/198336272-dd23477b-f68b-4562-864e-04c8da8d47ab.png)

### How often did you encounter it so far?

Every time

### Affected program

cmd.exe

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

That the commandline works.

### What is your Windows edition and version?

Windows 8.1 Enterprise Version 6.3 (Build 9600) 32 bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus v1.51 32-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Since Sandboxie Plus v1.50 32-bit

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
this is a known issue with 32 but systems starting with 1.5.0, it will be fixed in 1.5.2 until them please stay at 1.4.2

**Comment by DavidXanatos** [comment]
build 1.5.2 is out as unsigned pre release please update
