### ISSUE TITLE
If a sandbox is empty, the file panel shows the contents of the Sandboxie install folder

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#2419]
### Describe what you noticed and did

If a sandbox is empty, the file panel shows the contents of the Sandboxie install folder

Reproduction steps:
- open Sandboxie Main Window
- enable View -> "Show File Panel"
- create a new empty sandbox
![new box](https://user-images.githubusercontent.com/12411527/198825944-5697c79c-8d78-48f2-a240-0ea0051108c3.png)
- witness the contents of the Sandboxie install folder in the file panel

### How often did you encounter it so far?

always

### Affected program

Sandboxie Plus File Panel

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

An empty box should not show files in the File Panel if it is actually empty.

### What is your Windows edition and version?

Windows 10 Edu 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.1

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
Well it has to show something so what would you suggest should be shown?

**Comment by isaak654** [comment]
I believe that the purpose of this issue is to not show anything in empty sandboxes.

**Comment by NewKidOnTheBlock** [comment]
Yes, I think it's confusing to show dozens of files and folders if the sandbox is empty.
If the box is empty, the file panel should be empty.

**Comment by paradoxicallist** [comment]
I concur, empty boxes should show nothing at all in the file panel.
