### ISSUE TITLE
How change the path of a sandbox?!

### ISSUE THREAD

**Issue by Si13n7** [sandboxie-plus/Sandboxie#242]
### How can I change the path of a sandbox to have it on a different drive?

The normal sandboxie had a nice feature of changing the entire path of a sandbox through the `BoxRootFolder` variable in the `Sandboxie.ini` file under the section of a particular sandbox.

It looks like Sandboxie-Plus removed this variable and I couldn't find a replacement for it.

So how can I change the path of a sandbox to have it on a different drive? 🤔

**Comment by NewKidOnTheBlock** [comment]
In classic it works like this:
![Zwischenablage-1](https://user-images.githubusercontent.com/12411527/102695079-6e7f6d00-4225-11eb-9d72-ed662bc028c7.png)

**Comment by Si13n7** [comment]
Thanks @NewKidOnTheBlock you gave me the needed hint. I've found a similar option in Sanboxie-Plus, but only to change it global. But the same variable also works a single sandbox. So you have to set `FileRootPath` now.

**Comment by Si13n7** [comment]
Can be closed! 😄

**Comment by DavidXanatos** [comment]
In the Plus UI like this:
![grafik](https://user-images.githubusercontent.com/3890945/102696455-c1115700-422e-11eb-9b52-2cd127cd8f1c.png)

**Comment by Si13n7** [comment]
@DavidXanatos ye, you can change it globally for all sandboxes there, but only changing it for a single sandbox is currently not available in the Plus UI.

Sorry, I think I didn't make that explicitly clear in my question, but the real question was how to do it individually for a single sandbox without affecting other sandboxes.

**Comment by DavidXanatos** [comment]
That option NewKidOnTheBlock showed is to change it globally as well.
Also BoxRootFolder is is deprecated, use FileRootPath instead, see https://xanasoft.com/sandboxie/BoxRootFolder/

You can add FileRootPath=C:\something\something\mybox to any sandbox ini file entry to move that sandboxes location that folder.
To my knowledge there is no option in the old ui to change that graphically eider.

If I would to add a graphical box relocation option to Sandboxie-plus, I would need to do that properly i.e. move the old folder to the new location and in cases where that is on a different volume that needs to be done by copy and delete what is additional work to implement.

**Comment by Si13n7** [comment]
It's okay @DavidXanatos I was just confused about the new variable name.
I don't mind if I have to use the `Sandboxie.ini` directly. 😉 

However, if I were to implement it in the Plus UI, I would add an option to the sandbox context menu. Similar to `Rename Sandbox`; additionally then `Change Sandbox Path`. I think that would be the best way to deal with all of the things that you're talking about.

**Btw, thank you very much for all the work!** ❤️
