### ISSUE TITLE
Sandboxie Plus uninstall warnings are shown without reason

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2421]
I reproduced the following behaviours on a W7 SP1 x64 OS, but I can't exclude them on more recent OSes.

- Be sure you've already installed a recent Sandboxie Plus version (in this case, _Sandboxie-Plus-x64-v1.5.1.exe_).
- Run unins000.exe from `C:\Program Files\Sandboxie-Plus`
- Select "Remove configuration files and sandboxes"
- A few seconds later:
<img src="https://user-images.githubusercontent.com/12372772/198902163-33baaa82-ae18-4165-be81-b1795ca81a75.png" alt="terminate_all_error" height="250px"> <img src="https://user-images.githubusercontent.com/12372772/198902289-db0e3d22-9aa5-4fc4-be5a-f50ef74081b1.png" alt="SBIE1401" height="250px">

### Expected behaviour

Please remove both warnings from the uninstallation process.

### Reproducible video

[Win7 x64-1.5.1.webm](https://user-images.githubusercontent.com/12372772/198902337-619cc9d9-eaf6-4f49-8644-0b66d90bc1e8.webm)

**Comment by APMichael** [comment]
I can confirm this uninstall behavior for Windows 10 and 11 as well.

**Comment by isaak654** [comment]
I would like to point out that, even if they are displayed for a reason:
- they are still annoying
- they add further delay to the uninstallation process that should be free of warnings.
- they could scare off potential Sandboxie adopters.

**Comment by isaak654** [comment]
I would like to point out that, even if they are displayed for a reason:
- they are still annoying
- they add further delay to the uninstallation process that should be free of warnings
- they could scare off potential Sandboxie adopters
