### ISSUE TITLE
Can't run Windows Sandbox using Sandboxie

### ISSUE THREAD

**Issue by farhansolodev** [sandboxie-plus/Sandboxie#2422]
### Describe what you noticed and did

- First make sure Windows Sandbox is enabled in Windows Features
- Go to C:\WINDOWS\system32 directory
- Run WindowsSandbox.exe with Sandboxie
- Select the DefaultBox and hit OK
- You should receive this error:
![image](https://user-images.githubusercontent.com/52133344/198906354-f0261cb4-2db0-4cef-98e4-ff2946876720.png)

### How often did you encounter it so far?

Whenever I try to run Windows Sandbox with Sandboxie

### Affected program

Windows Sandbox

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

A sandboxed instance of Windows Sandbox should run

### What is your Windows edition and version?

Windows 11 Pro 21H2 64-Bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

No antivirus installed

### What version of Sandboxie are you running?

Sandboxie-Plus v1.3.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
NetworkEnableWFP=y
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=RTSS
Template=OfficeLicensing
Template=Edge_Win11Fix

[UserSettings_119A028E]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[New_Box]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=n
```

**Comment by mysteriously** [comment]
May I ask why would you actually want it to work?

**Comment by APMichael** [comment]
The "Windows Sandbox" uses hardware-based virtualization and the Microsoft Hypervisor, I don't think it can work together with Sandboxie. Also, I'm not really sure what sense it makes to use the "Windows Sandbox" in Sandboxie?

**Comment by DavidXanatos** [comment]
As running virtualization software inside sandboxie is not a supported use case I'll close this issue

**Comment by farhansolodev** [comment]
> May I ask why would you actually want it to work?

To run multiple instances of Windows Sandbox.

**Comment by DavidXanatos** [comment]
How about just going for using Hyper-V directly? or VMWare or Virtual box all of those allow you many parallel instances.

**Comment by farhansolodev** [comment]
Windows Sandbox is less CPU and RAM intensive than hypervisors since instead of emulating an entire guest operating system, it instead shares resources from the host machine, for example it mounts immutable system files from the host.

Mainly wanted to run multiple instances of it for a university project, but I've since decided to use other methods.
