### ISSUE TITLE
[Plus 1.5.2 x64] SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 - SandboxieRpcSs.exe [FF000005] with UsePrivacyMode=y

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2423]
`SandboxieRpcSs.exe (PID): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 13 - SandboxieRpcSs.exe [FF000005]`

Linger processes
SandboxieRpcSs.exe
-SandboxieDcomLaunch.exe

### What is your Windows edition and version?
Windows 7 Ultimate SP1 x64
### Please mention any installed security software
None/WD disabled
### What version of Sandboxie are you running?
Plus 1.5.2 x64
### Is it a new installation of Sandboxie?
I just updated Sandboxie from a previous version (to be specified). 1 5 1

##
Edit 👉 Combined with `NoSecurityIsolation=y` there is no issue

**Comment by helpthemfix** [comment]
I get a similar error when trying to launch Librewolf (Firefox Fork)

`SBIE2203 Failed to communicate with Sandboxie Service SandboxieRpcSs.exe -SandboxieDcomLaunch.exe`

**Comment by DavidXanatos** [comment]
@RandomGOTI does this happen for you when runnying anythign or some specific software?

**Comment by mysteriously** [comment]
I got it too when I was running Edge.

BTW: Edge does not close properly if it has been running for a long time

**Comment by DavidXanatos** [comment]
did you do anything special?

**Comment by RandomGOTI** [comment]
@DavidXanatos for me it happens with anything (incl. run > run program context menu , start terminates and the 2 processes linger)

**Comment by mysteriously** [comment]
It happened few times in a row on same day. However it was few days ago so I don't recall anything specific. Win 11 22H2

**Comment by mysteriously** [comment]
> @DavidXanatos for me it happens with anything (incl. run > run program context menu , start terminates and the 2 processes linger)

Oh, I think it could happen when I was running the same browser installed on host machine in few sandboxes at the same time

**Comment by DavidXanatos** [comment]
Ok so @RandomGOTI issue is fixed its a generic incompatybility with windows 7 accidently introduced in one of the recent builds.
@mysteriously you have a different issue wof that I'll need a way to reproduce it reliably here.

**Comment by deeperfacts** [comment]
> It happened few times in a row on same day. However it was few days ago so I don't recall anything specific. Win 11 22H2

It happens also in win 10 pro x64 22h2s everything run, install, run within, etcs. their 1.9.8 latest is also messed up after the st*pid Windows Updates this July 2023.
