### ISSUE TITLE
SBIE2112 Objekt ist nicht zugänglich: \WindowsErrorReportingServicePort, Aufruf AlpcConnectPort (C0000022) access=001F0001 initialized=1

### ISSUE THREAD

**Issue by kleff100** [sandboxie-plus/Sandboxie#2425]
### Describe what you noticed and did

With recent versions of Sandboxie i cannot open sandboxed web browser Mozilla Firefox 102.4.0 ESR - see error message in subject.
Firefox alone is running smooth, also sandboxed chrome is doing the same.

### Affected program

Mozilla Firefox 102.4.0 ESR

### Download link

not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Firefox should work sandboxed...

### What is your Windows edition and version?

Win 10 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

eset EIS 16.0.22.0

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.60.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
I can not reproduce this issue on a 64 bit windows, 
there was such a bug in 1.5.1 and 1.5.0, fixed in 1.5.2 but only applying to 32 bit windows and affecting all applications

**Comment by isaak654** [comment]
I think this is about Eset Internet Security 16.0.22.0, which is the ESET version that some users reported as incompatible with Sandboxie:
https://www.wilderssecurity.com/threads/sandboxie-plus-v1-5-0-v1-5-1-v1-5-2.448352/page-4#post-3113504
