### ISSUE TITLE
UsePrivacyMode=y breaks snapshot restore in SBIE+ 1.5.1

### ISSUE THREAD

**Issue by ksmustang** [sandboxie-plus/Sandboxie#2427]
### Describe what you noticed and did

Snapshot restores fail when you:
1.	Create a snapshot for a “Standard Isolation Sandbox” sandbox
2.	Add `UsePrivacyMode=y` to the sandbox’s configuration

Attempts to restore the snapshot  will fail manually (with Snapshots Manager) or automatically (when closing & reopening the sandbox). The sandbox will be empty (except for the snapshot.ini file, snapshot folders, the ‘DON’T-USE.TXT’ file and the RegHive file).

The problem occurs because `UsePrivacyMode=y` prevents sandboxie from accessing snapshot.ini and the snapshot folders.

A workaround is to manually add `OpenFilePath=C:\Sandbox\%USER%\%SANDBOX%\snapshot*` to the sandbox configuration.

The attached example sandboxie.ini allows snapshots to work for Firefox with `UsePrivacyMode=y` enabled. Once a snapshot has been created, it can only be restored if `OpenFilePath=C:\Sandbox\%USER%\%SANDBOX%\snapshot*` is present.

Sandboxie should handle snapshot recovery properly if `UsePrivacyMode=y` is present in a sandbox’s configuration.

### How often did you encounter it so far?

Happens every time for any sandbox configured with UsePrivacyMode=y when attempting to restore a snapshot

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Snapshot restore should work properly for sandboxes configured with `UsePrivacyMode=y`

### What is your Windows edition and version?

Windows 10 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie-Pluse 1.5.1

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

Unknown - Started using snapshots in 1.5.1

### In which sandbox type you have this problem?

In a sandbox with data protection (blue sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Not relevant

### Sandboxie.ini configuration

```shell
[UserSettings_052E014C]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
BorderColor=#ff8c00,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=81920

ForceProcess=firefox.exe
UsePrivacyMode=y
AutoDelete=y


#---- Process Groups ----#
ProcessGroup=<FirefoxPM_ResourceAccess>,firefox.exe
# Enable COM timeout for browsers to allow entry of credentials to sites such as microsoft.com
RpcMgmtSetComTimeout=firefox.exe,y
#---- Registry access ----*
NormalKeyPath=<FirefoxPM_ResourceAccess>,HKEY_CURRENT_USER\SOFTWARE\Microsoft
NormalKeyPath=<FirefoxPM_ResourceAccess>,HKEY_CURRENT_USER\SOFTWARE\Mozilla
#---- C: drive access ----#
NormalFilePath=<FirefoxPM_ResourceAccess>,C:\Users\%USER%\Desktop
NormalFilePath=<FirefoxPM_ResourceAccess>,%LOCALAPPDATA%
NormalFilePath=<FirefoxPM_ResourceAccess>,%APPDATA%

#----- Open snapshot.ini and snapshot folders to enable snapshots.
OpenFilePath=C:\Sandbox\%USER%\%SANDBOX%\snapshot*
```

**Comment by DavidXanatos** [comment]
This is very strange but i can reproduce it, will look into fixing it asap

**Comment by ksmustang** [comment]
Many thanks David.

FYI, I found that `ReadFilePath`  works to allow snapshot restores and is probably a better workaround than `OpenFilePath `until you can fix the underlying issue.
