### ISSUE TITLE
Roboform extension not loading in Firefox 106.0.x

### ISSUE THREAD

**Issue by pebkacdude** [sandboxie-plus/Sandboxie#2428]
### Describe what you noticed and did

Since updating to Sandboxie Classic 5.60.1 the roboform extension for Firefox no longer loads when run sandboxed. Has happend in Firefox 106.0.1 106.0.2 & 106.0.3  64 bit and 32 bit. Works okay outside of the sandbox. Works okay in Microsoft Edge. The roboform icon appears greyed out instead of it's usual green.
<img width="124" alt="robform_greyedout" src="https://user-images.githubusercontent.com/117248691/199392349-4f6812df-29cc-4a35-a87c-185611a07270.png">

### How often did you encounter it so far?

Whenever I run Firefox in a sandbox

### Affected program

Firefox 106.0.1 with Roboform extension

### Download link

https://www.roboform.com/download

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Roboform extension icon in Firefox should be green as shown in the screenshot here from Firefox run outside of the sandbox.
<img width="122" alt="robform_green" src="https://user-images.githubusercontent.com/117248691/199393835-762c8180-1ad0-4bb8-a688-d806ea559e16.png">

### What is your Windows edition and version?

Windows 10 Home 21H1

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Webroot

### What version of Sandboxie are you running?

Sandboxie Classic 5.60.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by offhub** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/2411#issuecomment-1294956155

**Comment by pebkacdude** [comment]
Adding the line
ReadFilePath=firefox.exe,*\Program Files (x86)\Siber Systems\AI RoboForm\*
To the the box config as suggested fixes the issue.
Thank you.

**Comment by pebkacdude** [comment]
See #2411
