### ISSUE TITLE
Reusing the localization from Sandboxie for Sandboxie-Plus?

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#243]
Is it possible for you to reuse the localization from Sandboxie for Sandboxie-Plus?

Sandboxie-Plus shows a language option, but it no other than the English language can be selected.

There might be a few untranslated strings in which case Sandboxie-Plus may just display the english string, until someone manages to update the missing strings.

**Comment by DavidXanatos** [comment]
No that would be a huge lot of work, the new UI is structured only superficial like the old one, so most strings wont match.
There is a mechanism for translation the UI but it must be supply with translations do volunteers welcome.

**Comment by bastik-1001** [comment]
Alright, I was curious to see if it could be reused. Maybe with enough time volunteers could translate the strings and allow non-english speaking people to use it.

I may attempt it for German, but I better not promise anything.

**Comment by DavidXanatos** [comment]
Is in the modern day and age a translation to other languages than english still really necessary?
I would have thought that by now most computer users speak enough english.

Anyhow look into the program Qt Linguist like here: https://doc.qt.io/archives/qt-4.8/linguist-translators.html
That's how translation for Qt applications work.

**Comment by bastik-1001** [comment]
Well, since Sandboxie is a rather technical application I assume that it could be the case that users which would use this program would be able to understand enough English. Time will tell if translation requests show up.
