### ISSUE TITLE
Got a blue screen when installing the arm64 version

### ISSUE THREAD

**Issue by dnt1996** [sandboxie-plus/Sandboxie#2431]
### Describe what you noticed and did

1. Install version 1.5.1-arm64
2. Got a blue screen after click finish button in the last step

![3bcfced3f1a4a7494b54d17f37033ab](https://user-images.githubusercontent.com/31310280/200096474-7fb380de-fb68-4b06-937d-e51f28b96a13.jpg)

### How often did you encounter it so far?

every time

### Affected program

Sandboxie Plus

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.5.1/Sandboxie-Plus-ARM64-v1.5.1.exe

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Install and run

### What is your Windows edition and version?

Windows 11 Pro 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.1 arm64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by dnt1996** [comment]
Systeminfo.exe output

Host Name:                 JESSE-MATEBOOK
OS Name:                   Microsoft Windows 11 ???
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          dnt1996@live.com
Registered Organization:   N/A
Product ID:                00330-75075-85723-AAOEM
Original Install Date:     2022/11/4, 21:48:43
System Boot Time:          2022/11/5, 9:48:09
System Manufacturer:       HUAWEI
System Model:              GK-W7X
System Type:               ARM64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: ARMv8 (64-bit) Family 8 Model D4B Revision   0 Qualcomm Technologies Inc ~2438 Mhz
BIOS Version:              HUAWEI 2.09, 2022/9/21
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              zh-cn;Chinese (China)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     15,797 MB
Available Physical Memory: 7,351 MB
Virtual Memory: Max Size:  18,741 MB
Virtual Memory: Available: 9,883 MB
Virtual Memory: In Use:    8,858 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\JESSE-MATEBOOK
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5018330
                           [02]: KB5012170
                           [03]: KB5019448
                           [04]: KB5017850
Network Card(s):           2 NIC(s) Installed.
                           [01]: Bluetooth Device (Personal Area Network)
                                 Connection Name: ??????
                                 Status:          Media disconnected
                           [02]: Wintun Userspace Tunnel
                                 Connection Name: Clash
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 198.18.0.1
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by dnt1996** [comment]
Device: Huawei Matebook E Go
CPU: Snapdragon (TM) 8cx Gen 3 @ 3.0 GHz   3.00 GHz

**Comment by DavidXanatos** [comment]
do you have a kernel crash dump?

**Comment by dnt1996** [comment]
@DavidXanatos Is it this file?
[MEMORY.DMP](https://we.tl/t-HSg3IzVrDo)

**Comment by DavidXanatos** [comment]
Yes its that, thank you very much, I have analyzed the issue and located a bugcheck when the driver initialization fails, that will be fixed in the next build 1.5.3. The issue has been introduced with 1.5.1 (changelog: "Sandboxie no longer leaves behind permanent directory objects")

however on my ARM64 test systems the driver initialization succeeds just fine, so we need to debug why it fails on your system.
Could you please try the 1.5.0 ARM build https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.5.0 
when the driver initialization fails you should still get some some error messages in the message log, if not than go for dbgview https://learn.microsoft.com/en-us/sysinternals/downloads/debugview and when loading the driver look for messages from sbie there.

**Comment by dnt1996** [comment]
@DavidXanatos As you might expect, when I try to install 1.5.0-ARM64, instead of crashing the system, I get an error message.
![image](https://user-images.githubusercontent.com/31310280/200164056-50a5484e-dcba-4091-948d-37337c20b161.png)

When I try to reconnect the driver again, I get many error logs, hope this will be useful to you.
```
|Time|         |Message|                                                         

17:45:26.592   Maintenance operation completed                                   
17:45:29.841   PID 0: SBIE1401: ;                                                
17:45:29.879   PID 0: SBIE1113: MASTER TABLE;                                    
17:45:29.886   PID 0: SBIE1113: AcceptConnectPort;                               
17:45:29.908   PID 0: SBIE1103: 5.60.0;                                          
17:45:29.924   PID 0: SBIE9234: level 9153 status=C0000001 error=-1073741823;    
17:45:29.940   PID 0: SBIE1102: ;                                                
17:45:29.943   PID 0: SBIE1401: ;                                                
17:45:29.959   PID 0: SBIE1113: MASTER TABLE;                                    
17:45:29.959   PID 0: SBIE1113: AcceptConnectPort;                               
17:45:29.975   PID 0: SBIE1103: 5.60.0;                                          
17:45:29.975   PID 0: SBIE9234: level 9153 status=C0000001 error=-1073741823;    
17:45:29.991   PID 0: SBIE1102: ;                                                
17:45:29.991   PID 0: SBIE1401: ;                                                
17:45:30.006   PID 0: SBIE1113: MASTER TABLE;                                    
17:45:30.023   PID 0: SBIE1113: AcceptConnectPort;                               
17:45:30.023   PID 0: SBIE1103: 5.60.0;                                          
17:45:30.039   PID 0: SBIE9234: level 9153 status=C0000001 error=-1073741823;    
17:45:30.054   PID 0: SBIE1102: ;                                                
17:45:30.071   PID 0: SBIE1401: ;                                                
17:45:30.071   PID 0: SBIE1113: MASTER TABLE;                                    
17:45:30.087   PID 0: SBIE1113: AcceptConnectPort;                               
17:45:30.103   PID 0: SBIE1103: 5.60.0;                                          
```

**Comment by DavidXanatos** [comment]
I see you are still using the 21H2 build of win 11 I was targeting 22H2 during development, I'll need to set up 21H2 test target then to see why retrieving the master table fails.
You can wait for that or upgrade to 22H2 which is known to work fine with the current build

**Comment by DavidXanatos** [comment]
I have set up a 21H2 with all updates and can not reproduce the issue, please try updating your windows 11 instalaltion

**Comment by dnt1996** [comment]
@DavidXanatos 
After Windows 11 is upgraded to 22H2, it can run successfully. (Milestone 🎉🎉🎉)
However, many problems were found during the installation of the application in the sandbox. 
I will submit issues later in my free time, thank you for your help.

**Comment by isaak654** [comment]
>  However, many problems were found during installation of application in the sandbox.
>  I will submit issues later in my free time, thanks for your help.

I recommend starting from version 1.5.3 onwards.

**Comment by zhangshuangjun** [comment]
i have the same error

SBIE1401 Configuration file not found, using defaults
SBIE1113 Cannot find Nt system service, reason MASTER TABLE
SBIE1113 Cannot find Nt system service, reason AcceptConnectPort
SBIE1103 Sandboxie driver (SbieDrv) version 5.61.4 failed to start
SBIE9234 Service startup error level 9153 status=C0000001 error=-1073741823
SBIE1102 Sandboxie driver (SbieDrv) unloading
SBIE1401 Configuration file not found, using defaults
SBIE1113 Cannot find Nt system service, reason MASTER TABLE
SBIE1113 Cannot find Nt system service, reason AcceptConnectPort
SBIE1103 Sandboxie driver (SbieDrv) version 5.61.4 failed to start
SBIE9234 Service startup error level 9153 status=C0000001 error=-1073741823
SBIE1102 Sandboxie driver (SbieDrv) unloading
SBIE1401 Configuration file not found, using defaults
SBIE1113 Cannot find Nt system service, reason MASTER TABLE
SBIE1113 Cannot find Nt system service, reason AcceptConnectPort
SBIE1103 Sandboxie driver (SbieDrv) version 5.61.4 failed to start
SBIE9234 Service startup error level 9153 status=C0000001 error=-1073741823
SBIE1102 Sandboxie driver (SbieDrv) unloading
SBIE2331 Service start failed:  [22 / 5] 拒绝访问。


sysver :  10.0.22000.1335  / windows11 arm64

**Comment by DavidXanatos** [comment]
this issue seams to occur only on updated 21h2 windows 11 neider odler versionos of win 11 have the issue nor 22h2 I'l lookinti that version soon

**Comment by DavidXanatos** [comment]
I have found the incompatibility it will be fixed in the next build
