### ISSUE TITLE
DX12 is not supported

### ISSUE THREAD

**Issue by Nypheena** [sandboxie-plus/Sandboxie#2432]
### Describe what you noticed and did

Games with DX12 have been telling me since updating to Windows 11 that it's not supported on my system but it is and I don't know how to let it know in sandboxie

### How often did you encounter it so far?

all the time

### Affected program

All DX12 video games

### Download link

not available

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

For it to run

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Just the Windows included one

### What version of Sandboxie are you running?

1.5.1 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

yes it worked on windows 10

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
SHoudl work fine but perhaps we need to open some resource which games need DX12?

**Comment by DavidXanatos** [comment]
Cyberpunk 2077 works fine for me and as far as the internet says its DX12 only so perhaps the issue is more specific,

**Comment by isaak654** [comment]
If your Asterigos game comes from the GOG Galaxy launcher, then it may be related to #1246.

**Comment by isaak654** [comment]
> Cyberpunk 2077 works fine for me and as far as the internet says its DX12 only so perhaps the issue is more specific,

From which launcher did you get it?
