### ISSUE TITLE
Firefox fails to communicate with Sandboxie Service

### ISSUE THREAD

**Issue by mtag438** [sandboxie-plus/Sandboxie#2434]
### Describe what you noticed and did

Hello. I have run into an issue with Sandboxie where if I open the following site (watchnbastreams.com), Sandboxie displays the following message:
 WerFault.exe (9536): SBIE2203 Failed to communicate with Sandboxie service: *GUIPROXY_00000001; MsgId - WerFault.exe [FF000000]
 
Steps
Prerequisite: Turn on the following on the sandbox in Sandbox Presets: Drop Admin Rights

1. Right-click the sandbox.
2. Select Run Program from the menu.
3. Enter firefox.exe.
4. Once the browser loads enter watchnbastreams.com in the address bar.
5. Click on a stream.
6. Start playing the video

Result:
Sandboxie-Plus displays a message stating that the Sandboxie service failed to communicate.
 WerFault.exe (9536): SBIE2203 Failed to communicate with Sandboxie service: *GUIPROXY_00000001; MsgId - WerFault.exe [FF000000]
 
<img width="656" alt="sandboxie-werfault-pic" src="https://user-images.githubusercontent.com/9435084/200128025-36813ab5-1e2e-4894-a943-49226089882f.png">

### How often did you encounter it so far?

I have run into this for the past two weeks

### Affected program

Firefox 106.0.4

### Download link

https://www.mozilla.org/en-US/firefox/new/

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Sandboxie should not show an error message stating that the Sandboxie Service can not communicate with the program in the sandbox. 

### What is your Windows edition and version?

Windows 10 Home Edition 21H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.3.5

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

I have not turned on any security policy settings outside of Sandboxie.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=Edge_Win11Fix
Template=WindowsRasMan
Template=WindowsLive
Template=RpcPortBindings
Template=OfficeLicensing
Template=OfficeClickToRun
Template=7zipShellEx
EnableObjectFiltering=y
EnableWin32kHooks=y

[UserSettings_0D48022F]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
BoxDisplayOrder=DefaultBox,Streaming

[DefaultBox]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9

[Streaming]

Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
ClosePrintSpooler=y
```

**Comment by DavidXanatos** [comment]
> Sandboxie Plus 1.3.5

this bug is fixe in 1.5.1 and later please update your sandboxie installation.
