### ISSUE TITLE
sandboxie process communication isolation can be bypassed using shared variables

### ISSUE THREAD

**Issue by LYingSiMon** [sandboxie-plus/Sandboxie#2437]
### Describe what you noticed and did

![2127725a-1d09-4998-b598-bd15c1340b78](https://user-images.githubusercontent.com/51651107/200220041-f081e413-4cad-4483-a1e3-40276033f705.jpeg)

the code ：
```
#include <windows.h>
#include <iostream>

#pragma data_seg("LYSM_shared")
INT instance_count = 0;
#pragma data_seg()
#pragma comment(linker, "/SECTION:LYSM_shared,RWS")

int main()
{
	instance_count++;
	printf("instance_count:%d \n", instance_count);

	printf("finished. \n");
    
    getchar();
}
```

### How often did you encounter it so far?

Every time

### Affected program

Each program

### Download link

null

### Where is the program located?

Not relevant to my request.

### Expected behavior

The instance_count variable should have a value of 1 the first time it is opened in each sandbox

### What is your Windows edition and version?

18363.418

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

null

### What version of Sandboxie are you running?

v5.60.1

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

no

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no

### Crash dump

null

### Trace log

null

### Sandboxie.ini configuration

```shell
null
```

**Comment by DavidXanatos** [comment]
I have evaluated the issue, it seams that with this linker options you the OS can be instructed to use a shared memory page for all instances of a given application. 
Meaning Test1.exe has one counter and Test2.exe has an other, this mechanism can not be used to access 3rd party programs.
See https://learn.microsoft.com/en-us/cpp/build/reference/section-specify-section-attributes?view=msvc-170

<html><body>


S | Shared | Shares the section among all processes that load the image
-- | -- | --



</body>
</html> 

As this is a feature of the kernel's image loader I don't think there is an easy fix we could do.

Also windows does not enforces a security boundary here, in one session if you run a process as admin, as system and as unprivileged user, they all share that memory section.

Given that this is a very exotic scenario which needs to be explicitly enabled by the program during compile time, it does not pose any real threats, hence I will leave it as is.

**Comment by LYingSiMon** [comment]
Ok, I see, this problem can be turned off
