### ISSUE TITLE
File dialog window for "Add File/Folder" in "Resource Access"

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#244]
It would be nice to have the option instead of typing the strings in the "Path" field. Thanks

**Comment by DavidXanatos** [comment]
eee.... pfff... how do i do that elegantly, these edits also take reg paths and other, but ok I'll look into offering a browse button when its a file type entry

**Comment by superkryodev** [comment]
> 
> 
> eee.... pfff... how do i do that elegantly, these edits also take reg paths and other, but ok I'll look into offering a browse button when its a file type entry

Only for "file/folder" not for the rest, similar to what you already do for adding a recovery folder.

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/102698716-c1feb480-423f-11eb-8393-0535f08e5a3a.png)
will be in the next build

**Comment by superkryodev** [comment]
> 
> 
> ![grafik](https://user-images.githubusercontent.com/3890945/102698716-c1feb480-423f-11eb-8393-0535f08e5a3a.png)
> will be in the next build

Great! Many thanks
