### ISSUE TITLE
Customizable global hotkey that toggles the state of "pause forced programs"

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2441]
### Is your feature request related to a problem or use case?

Like "Hotkey for terminating all boxed processes" in `Global Options` having the builtin ability to assign a hotkey to toggle the state of force sandboxed would prove useful

### Describe the solution you'd like

>title

**Comment by DavidXanatos** [comment]
this sounds indeed usefull have put it on my todo list
