### ISSUE TITLE
Firefox Nightly Crashes (Firefox 108.0a1 64-bit)

### ISSUE THREAD

**Issue by eneerge** [sandboxie-plus/Sandboxie#2443]
### Describe what you noticed and did

1. Create a new Sandbox
2. Install Firefox Nightly into the Sandbox
3. Use "Custom" install and unselect the "Install Maintenance Service" option (probably not needed)
4. Launch Firefox Nightly

The browser takes a long time before it appears, then it either crashes and pops up the Crash Report or sits in a frozen state.

### How often did you encounter it so far?

Everytime I try to launch Firefox Nightly

### Affected program

Firefox 108.0a1 64-bit

### Download link

https://www.mozilla.org/en-US/firefox/all/#product-desktop-nightly

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Firefox Nightly opens and allows me to browse websites.

### What is your Windows edition and version?

Windows 10 Enterprise 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

 Microsoft Defender for Endpoint

### What version of Sandboxie are you running?

1.5.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

None.
Older version of Firefox (106.0.5) works fine.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=Edge_Fix
Template=OfficeLicensing
Template=OfficeClickToRun
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%

[UserSettings_2DA80421]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_UserName=snipped
SbieCtrl_NextUpdateCheck=1668189394
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=201,151,2475,1265
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[Firefox]
Enabled=y
ConfigLevel=9
AutoRecover=y
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=BlockPorts
RecoverFolder=C:\Users\snipped\Downloads
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
BorderColor=#00FFFF,ttl

[Firefox_IT]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00fd00,ttl
Template=RpcPortBindingsExt
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
NoSecurityIsolation=y
UsePrivacyMode=n
```

**Comment by ChrisDenton** [comment]
This is also being tracked in: https://bugzilla.mozilla.org/show_bug.cgi?id=1799442

Ultimately I think this is a bug in the way Sandboxie handles `NtQueryDirectoryFile`. This function can be used to fill a buffer with data structures for each directory entry. The documentation for these structures say (e.g. [FILE_DIRECTORY_INFORMATION](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_directory_information#remarks)):

> This structure must be aligned on a LONGLONG (8-byte) boundary.

However, sandboxie does not appear to ensure this happens, leading to unaligned structures being placed in the buffer.

**Comment by eneerge** [comment]
New version of Firefox works now.

**Comment by DavidXanatos** [comment]
this needs to be properly fixed

**Comment by DavidXanatos** [comment]
fixed: https://github.com/sandboxie-plus/Sandboxie/commit/8e68dce6ea3e24edfb1b8cd75ad7a1804d7282d5

**Comment by ChrisDenton** [comment]
Looks great, thanks!
