### ISSUE TITLE
Start.exe - Failed to initialize DLL initialization of dynamic link library C:\Program Files\Sandboxie-Plus\SbieDll.dll failed. Abnormal end of process.

### ISSUE THREAD

**Issue by lemaximedu66** [sandboxie-plus/Sandboxie#2447]
### Describe what you noticed and did

1. Launch any programin a sandbox with the context menu option without launching SandMan.exe (if launched, close it)
2. error

### How often did you encounter it so far?

all the times you lunch a program without SandMan.exe in the background

### Affected program

All

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

The program should launch SandMan, then execute the program.

### What is your Windows edition and version?

windows 11 22h2

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

defender

### What version of Sandboxie are you running?

1.5.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by APMichael** [comment]
Already reported: https://github.com/sandboxie-plus/Sandboxie/issues/2284#issuecomment-1259720113

**Comment by lemaximedu66** [comment]
ok sorry

**Comment by isaak654** [comment]
I'm going to close this issue as duplicate in order to highlight the other one: https://github.com/sandboxie-plus/Sandboxie/issues/2284#issuecomment-1259720113

**Comment by lemaximedu66** [comment]
Ok thank ypu
