### ISSUE TITLE
PowerShell can‘t run in a hardened sandbox.

### ISSUE THREAD

**Issue by okrc** [sandboxie-plus/Sandboxie#2449]
### Describe what you noticed and did

Add 
``` ini
OpenIpcPath=powershell.exe,\Device\BootDevice
OpenIpcPath=pwsh.exe,\Device\BootDevice
```
or
``` ini
ClosedIpcPath=pwsh.exe,\Device\BootDevice
ClosedIpcPath=powershell.exe,\Device\BootDevice
```
or
``` ini
ReadIpcPath=powershell.exe,\Device\BootDevice
ReadIpcPath=pwsh.exe,\Device\BootDevice
```
can make it work successfully.

### Affected program

pwsh 7, powershell 5

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### What version of Sandboxie are you running?

Sandboxie-Plus v1.5.3 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by mysteriously** [comment]
I don't see anything wrong with it not working in hardened sandboxed. That's the purpose I guess

**Comment by okrc** [comment]
> I don't see anything wrong with it not working in hardened sandboxed.

Why? Can you tell me your reason?

**Comment by offhub** [comment]
This is the error message I get when I run it:
```
Windows PowerShell terminated with the following error:
 The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
```
AppLocker check?

**Comment by DavidXanatos** [comment]
I cant reproduce the issue on my test VM

**Comment by offhub** [comment]
Was it Windows 11 22H2? I only had this issue with Windows 11 22H2.

**Comment by DavidXanatos** [comment]
I tested it on a windows 11 VM on a post 22h2 insider build,
I don't have a proeprly configure non insider 22h2 vm perhaps i sould set one up

**Comment by isaak654** [comment]
Do you have any update for this issue?

**Comment by okrc** [comment]
It works fine on the latest Windows 11 22H2. So this issue can be closed.
