### ISSUE TITLE
Request: Add 'Open Window' to tray icon right-click menu on Sandboxie-Plus

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#245]
Right now, it seems to be the case that I have to double-click the tray icon of the control window when I use the plus version, this can remain to be the case, but I still want to be able to right-click the icon and then select "Open Window" or "Show Window".

**Comment by DavidXanatos** [comment]
I'm surprised anyone does that but yea sure I can add that, its no afford.
