### ISSUE TITLE
Using WINSW to create service could not listed process in GUI.

### ISSUE THREAD

**Issue by MisteryMonster** [sandboxie-plus/Sandboxie#2450]
### Describe what you noticed and did

1.Download [WinSW v3.0.0-alpha.10](https://github.com/winsw/winsw/releases/download/v3.0.0-alpha.10/WinSW-x64.exe) from https://github.com/winsw/winsw/releases
3.put `someapp.exe` inside sandbox:
2.Rename `WinSW-x64.exe` to `example.exe` and Create `example.xml` with following content:
```
<service>
    <id>service-sandboxed</id>
    <name>service-sandboxed</name>
    <description>service sandboxed</description>
    <executable>D:\Sandbox\username\mybox\someapp.exe</executable>
    <arguments></arguments>
    <logmode>reset</logmode>
</service>
```
install the service by running `example.exe install` and start the service `example.exe start`

sandboxie will popup messages:`PID 4024: SBIE2227 'services (D:\Sandbox\SYSTEM\services)' is located on a volume which does not support 8.3 naming. This can cause issues with older applications and installers.` seems it's sandboxed but the process can't view via GUI, maybe relative to the `SYSTEM` account.

### How often did you encounter it so far?

everytime

### Affected program

WINSW

### Download link

https://github.com/winsw/winsw/releases

### Where is the program located?

The WINSW is outside sandbox and the example.exe is inside the sandbox.

### Expected behavior

Using WINSW to create a service with sandboxed process and display at GUI.

### What is your Windows edition and version?

Windows 10 Pro 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

not relevant

### What version of Sandboxie are you running?

Sandboxie-plus 1.5.3 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
this is a generic sandboxie warming message not related to any aprticular application,
it indicates that you have your sandbox located ona volume which does not upport 8.3 naming and those may cause issues.
Eider hide the error emssage, or enable 8.3 on all volumes

**Comment by MisteryMonster** [comment]
The point is the message show the sandbox is using SYSTEM account, but I'm with a local account so I think I can't view the sandboxed process in sandboxie GUI, the process is still running sandboxed.

**Comment by DavidXanatos** [comment]
when a service is created in the sandbox it shoudl also start in the box and it shoudl not use (by default) a system token,
Are you using a Compartment Tape (Green/Cyan) box? and have disabled 
![grafik](https://user-images.githubusercontent.com/3890945/204145392-ea4c958b-4d2d-4254-b6d8-6c8a5add9726.png)

?

**Comment by MisteryMonster** [comment]
No, I'm using new Standard box, the red line option is checked by default.

**Comment by DavidXanatos** [comment]
could you pelase post your sandboxie ini?

**Comment by MisteryMonster** [comment]
```
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=n
AllowNetworkAccess=<BlockNetAccess>,n
```
I open the traceloging, the process is also not listed. but the view & create folder & remove is all functional and it's inside the sandbox ( the someapp.exe is a http file server)

**Comment by DavidXanatos** [comment]
whyt's your FileRootPath in the global section?

**Comment by MisteryMonster** [comment]
D:\Sandbox\%USER%\%SANDBOX% and have checked Separate user folders.

**Comment by DavidXanatos** [comment]
I see...
So... when you write "install the service by running example.exe install and start the service example.exe start"
how did you get that to be done in the sandbox?
did you run it from a sandbxoed cmd.exe, did you run it form a forced folder?
Looks like what you did is somehow started a sandboxed program not starting from your user account but starting from the system account....

**Comment by DavidXanatos** [comment]
you can see sandbxoed programs of otehr logon sessions with this option:
![grafik](https://user-images.githubusercontent.com/3890945/204148475-fd746423-5982-4bb5-ac48-7c505571b743.png)

**Comment by MisteryMonster** [comment]
Oh now I see! I think the problem solved! And it's normal that I can't terminate the `Forced Running in session 0`: Error Status:0xc0000022 (Access is denied.)?

**Comment by DavidXanatos** [comment]
you will need to start sandman as admin to terminate processes running in boxes of otehr users (system user included)

**Comment by MisteryMonster** [comment]
Great it works! Thanks! (but the `Terminate all program` not works, only right click `Terminate` works.)
