### ISSUE TITLE
Reorganize CMD options

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#2451]
### Is your feature request related to a problem or use case?

2 related command prompt options are found in different places.
The first one is found at **Run=>Command Prompt**.
The other is found at **Run=>Boxed Tools=>Command Prompt (32-bit)**.
It seems they're identical except the former uses 64-bit.

![image](https://user-images.githubusercontent.com/1773306/201467948-8ff32a6c-a3ba-4208-95f4-4a54401071b5.png)

![image](https://user-images.githubusercontent.com/1773306/201467935-6ab9dd1a-fae5-4259-a6e3-d93a617e3917.png)

### Describe the solution you'd like

Move the first one into **Run=>Boxed Tools** as well because it runs sandboxed just like the other.

I thought to suggest to also rename it to Command Prompt (64-bit), but that would require naming the third one **Command Prompt (64-bit as Admin)** which I guess is too long.

Although perhaps also rename **Box Tools** since all the options **above** Box Tools run sandboxed so they're box tools too.

**Comment by DavidXanatos** [comment]
idk...
I often use Command Prompt, while the other I use very rarely... but yea logically the entry should join its two other siblings in the sub menu....
Then I wonder howeever if we should move default web browser and default main client as well?
these entries being here are inspired by the classic interface but given that in the plus ui the user can add arbitrary new entries to the run menu, perhaps so generic run options are no longer nececery?

So the menu would look like this:

![grafik](https://user-images.githubusercontent.com/3890945/204143422-8cab7495-141d-467a-a040-d622a3bdf913.png)

of cause except for the vintage view as we want to keep that vintage, and since I don't use it I don't care how it looks as long as other are happy with it ;)

**Comment by lwcorp** [comment]
I like the proposed look, but still it makes it seem like everything Boxed Tools will run unsandboxed.
Should Boxed Tools maybe be renamed to **Predefined Tools**?

**Comment by DavidXanatos** [comment]
mmh... true... perhaps just "Run from Predefined" does not sound good but has the right meaning, may be just "Run Menu" ?

**Comment by DavidXanatos** [comment]
I think what we will need perhaps sooner than later will be place in the global options where to configure tool entries to be shown in all boxes

**Comment by lwcorp** [comment]
"Run Menu" will again be confusing as the "external" items are also run items.

**Comment by DavidXanatos** [comment]
> "Run Menu" will again be confusing as the "external" items are also run items.

I'm open for suggestions

**Comment by lwcorp** [comment]
Run Predefined Tools

**Comment by DavidXanatos** [comment]
> Run Predefined Tools

somehow to long and to complicated
how about just 
"More tools"?

**Comment by lwcorp** [comment]
Sounds good to me. 

Maybe also rename the regular CMD to 64-bit?

What does the 32-bit version do? It's only CMD after all. Can it even run like that without Sandboxie?

**Comment by DavidXanatos** [comment]
Yea you can run C:\Windows\Syswow64\cmd.exe just fine

**Comment by lwcorp** [comment]
So without Sandboxie the default CMD is 32-bit, but in the Sandboxie the default is 64-bit?
In any case, what's the difference?
![image](https://user-images.githubusercontent.com/1773306/204639936-15707687-04c7-42be-a591-6fffc607f8d0.png)

**Comment by offhub** [comment]
`The %windir%\System32 directory is reserved for 64-bit applications on 64-bit Windows. Most DLL file names were not changed when 64-bit versions of the DLLs were created, so 32-bit versions of the DLLs are stored in a different directory. WOW64 hides this difference by using a file system redirector.`
See for more info: https://learn.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector

**Comment by lwcorp** [comment]
So %windir%\System32\cmd.exe => 64-bit CMD while %windir%\Syswow64\cmd.exe => 32-bit CMD?

**Comment by offhub** [comment]
Yes, it is.

To check it from CMD:
`ECHO %PROCESSOR_ARCHITECTURE%`

**Comment by lwcorp** [comment]
Cool! Although `%PROCESSOR_IDENTIFIER%` still mentions 64...

But what does it actually change being 32-bit or 64-bit in CMD?

**Comment by DavidXanatos** [comment]
> Cool! Although `%PROCESSOR_IDENTIFIER%` still mentions 64...
> 
> But what does it actually change being 32-bit or 64-bit in CMD?

Well for me the main reason to use 32-bit CMD is to test new versions of SbieDll.dll without having to restart the sbiesvc service (which uses the 64 bit dll only). It saves only a few seconds on every try but with hundreds of builds that adds up to a worth while time saving.
