### ISSUE TITLE
Command Prompt (as Admin) doesn't run as Admin

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#2452]
### Describe what you noticed and did

1. Right click a box
2. Choose **Run=>Boxed Tools=>Command Prompt (as Admin)**:
![image](https://user-images.githubusercontent.com/1773306/201468646-64497aa2-9ba6-4aa3-8868-1293bf12f4c7.png)
Alternatively, manually launch `cmd.exe` inside a sandbox with **Run as UAC Administrator**:
![image](https://user-images.githubusercontent.com/1773306/201468577-cc8c1d75-435a-4032-af90-3f24fe680c06.png)
3. Approve UAC warning
4. Run an elevated CMD program (like `net session` - I tried many, see [these examples](https://stackoverflow.com/questions/7985755/how-to-detect-if-cmd-is-running-as-administrator-has-elevated-privileges) and also [these](https://superuser.com/questions/667607/check-if-current-command-prompt-was-launched-as-the-administrator), another example is [FLTMC.exe](https://ss64.com/nt/fltmc.html))
5. Get a permission denied error

### How often did you encounter it so far?

Whenever I try to run an elevated CMD program using Sandboxie (it works when not using Sandboxie)

### Affected program

cmd.exe

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

The elevated CMD program should run normally (just like running it from CMD Admin without Sandboxie).

### What is your Windows edition and version?

Windows 10 Home 22H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.3 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
Obviusly sandboxie is doing its job and isoalting windows components which should only be used by real admins.
When runnign somethign sandboxies the process is admin only with regard to other sandboxed resources, unsandboxed processes will not see the boxed process as admin and should not allow it access.
The "net" command accesses variouse windows administration facilities exposed by RPC interlaces which for security reasons are restricted.

If you disable Security Isolation i.e. create a green box your admin commands should work but this also results in boxed programs being able to alter some OS parameters, not sure you you would want that.

**Comment by lwcorp** [comment]
So what does it allow to do that normal CMD doesn't?

**Comment by offhub** [comment]
**Example**:
```
OpenFilePath=X:\Windows\System32\TEST.TXT
```

With normal CMD:
```
echo.>TEST.TXT
Access is denied.
```

With Admin CMD:
```
echo.>TEST.TXT
You can create empty TEST.TXT file in the `System32` folder.
```

**Comment by lwcorp** [comment]
can=can't?
