### ISSUE TITLE
[Plus 1.6.1] File recovery window issues via box context menu

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2458]
- [x] Box Context menu : 
`Recover files` : Will not switch to a existing `%Sandbox% - File Recovery` window if already open , window is not ontop of main sandman window like when delete content is used (RecoveryOnTop=true)
`Delete content` :  Can open multiple windows instead of switching to the already open one if action is repeated

- [ ] RecoveryOnTop (Show the Recovery Window as Always on Top) not working , (=false) will not remove the ontop when using `Delete content` (ShowRecovery=true)

- [ ] Feature request : have file recovery window be like `Box contents` -> `Browse files` window (single window; switch to it if already open and not always on top of sandman main window if RecoveryOnTop=false)

### What is your Windows edition and version?
Windows 7 Ultimate SP1 x64
### Please mention any installed security software
None/WD disabled
### What version of Sandboxie are you running?
Plus 1.5.3 x64
### Is it a new installation of Sandboxie?
I just updated Sandboxie from a previous version (to be specified). 1 5 2

**Comment by DavidXanatos** [comment]
So request 3 is the same as 1?

Whats about request 2 do you want the on top state of an already open window to change?
IMHO its enough when the setting affects only newly opened windows and there it seams to me as if it works fine.

anyhow I have uploaded build 1.6.2b to the update server using the live updater from the UI or you can install it by running "UpdUtil.exe update sandboxie-plus /channel:stable" from an elevated command prompt in the installation directory

**Comment by DavidXanatos** [comment]
@RandomGOTI please let me know if there is anythign more to do or if everythign works now ok

**Comment by RandomGOTI** [comment]
> So request 3 is the same as 1?
> 
> Whats about request 2 do you want the on top state of an already open window to change? IMHO its enough when the setting affects only newly opened windows and there it seams to me as if it works fine.
> 
> anyhow I have uploaded build 1.6.2b to the update server using the live updater from the UI or you can install it by running "UpdUtil.exe update sandboxie-plus /channel:stable" from an elevated command prompt in the installation directory

To clear up the mess a little that  i made in the OP 

**Always on top**
 Both recovery windows that get opened from manual or automatic recover or delete actions should follow the state of RecoveryOnTop value ; if false no recovery window is ontop of sadman window when it opens  If true  both windows are ontop of sandman window when are opened
As of 1 6 2 stable the RecoveryOnTop option is ignored by both manual actions (recover / delete)

**No duplicate windows / Switching to existing window matching the box** 
As of 1 6 2 stable those 2 issues :
Repeating the action of starting the manual delete when ShowRecovery=true will open %Sandbox% - File Recovery window each time 
Repeating the action of starting the manual recovery will only open one %Sandbox% - File Recovery window as the second action is ignored(nothing happens)


Will test the patch 1 6 2b that has the fix later 👍

**Comment by DavidXanatos** [comment]
please test build 1.6.3 and close the issue when everything is fine
