### ISSUE TITLE
Netease Cloud Music can't use the network

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#2459]
### Describe what you noticed and did

I installed it in the sandbox, started it, waited 10 seconds, and he would not be able to access the network

### How often did you encounter it so far?

every time

### Affected program

Cloud Music

### Download link

https://music.163.com/

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

The network should be accessed normally

### What is your Windows edition and version?

Windows11 Home 22H2 64bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

Sandboxie-Plus 1.5.3 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
Enabled=y
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=y
CopyLimitKb=-1
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
FileTrace=*
NeverDelete=y
DropAdminRights=y
DblClickAction=!options
FakeAdminRights=y
OpenWinClass=#
```

**Comment by Taeyeonzpx** [comment]
> I can't reproduce the issue. Do you have more info?
> 
> Windows 11 22H2 64bit
> 
>  sbiencmnw.mp4

I also follow the network firewall as you do, and everything in the network becomes normal. But before I do, the network access is abnormal. The playlist automatically pauses after 10 seconds of music playing, and all the playlists become gray, indicating that the network cannot be accessed. I don't know why, but it may be that my network environment is wrong. In short, thank you for your reply. I have tested several times, and thank you very much. At the same time, I hope you like listening to Chinese songs

**Comment by okrc** [comment]
@Taeyeonzpx 关于这个，我可以确定能够复现。但是，我不确定它具体是什么原因。
这会发生在初次安装后，如果安装后经过某些操作可以连上网后，它不会再复现。因为它在我的另一个沙盒里正常工作，创建一个空沙盒，将 FileRootPath 指向该路径，它同样也可以工作。

I can be sure that this can be reproduced. However, I am not sure what the specific reason is.
This will happen after the initial installation. If you can connect to the Internet after some operations, it will not reappear. Because it works normally in my other sandbox, create an empty sandbox and point the FileRootPath to this path. It also works.

**Comment by Taeyeonzpx** [comment]
> @Taeyeonzpx 关于这个，我可以确定能够复现。但是，我不确定它具体是什么原因。 这会发生在初次安装后，如果安装后经过某些操作可以连上网后，它不会再复现。因为它在我的另一个沙盒里正常工作，创建一个空沙盒，将 FileRootPath 指向该路径，它同样也可以工作。
> 
> I can be sure that this can be reproduced. However, I am not sure what the specific reason is. This will happen after the initial installation. If you can connect to the Internet after some operations, it will not reappear. Because it works normally in my other sandbox, create an empty sandbox and point the FileRootPath to this path. It also works.

对 好像经过了什么操作之后 就复现不出来了  但是有没有可能是网易云服务器的问题呢?

**Comment by okrc** [comment]
> 对 好像经过了什么操作之后 就复现不出来了 但是有没有可能是网易云服务器的问题呢?

I'm not so sure, and there isn't enough evidence to prove it.
我不太确定，并没有足够多的证据证明这一点。

**Comment by Taeyeonzpx** [comment]
> > 对 好像经过了什么操作之后 就复现不出来了 但是有没有可能是网易云服务器的问题呢?
> 
> I'm not so sure, and there isn't enough evidence to prove it. 我不太确定，并没有足够多的证据证明这一点。

我确定有这个问题  每次打开网易云后10秒 必定断网   不管是更新网易云还是重新在沙盘里装网易云都会断网  可能存在细小的bug   但是监控网络之后在关掉监控 就不会再断网了   很奇怪

**Comment by isaak654** [comment]
@Taeyeonzpx Translators don't always do their job well, so please share the corresponding English sentences too, or I'll have to lock this issue.

> There may be small bugs, but after monitoring the network, it will not be disconnected after turning off the monitoring. Very strange

This piece of sentence is not very clear to me, however the trace option "Network firewall" has a documented bug that is currently in pending state, so it shouldn't be used at this time when `NetworkEnableWFP=y` is enabled: https://github.com/sandboxie-plus/Sandboxie/issues/2471#issuecomment-1320843031

**Comment by isaak654** [comment]
@Taeyeonzpx Translation tools don't always do their job well, so please share the corresponding English sentences too, or I'll have to lock this issue.

> There may be small bugs, but after monitoring the network, it will not be disconnected after turning off the monitoring. Very strange

This piece of sentence is not very clear to me, however the trace option "Network firewall" has a documented bug that is currently in pending state, so it shouldn't be used at this time when `NetworkEnableWFP=y` is enabled: https://github.com/sandboxie-plus/Sandboxie/issues/2471#issuecomment-1320843031

**Comment by okrc** [comment]
> This piece of sentence is not very clear to me (after automatic translation from Chinese)

Turn on the option and then turn it off and the program works fine (this is random, it may not always take effect)
