### ISSUE TITLE
Issue creating new sandboxes with a space in its name

### ISSUE THREAD

**Issue by sirflimflam** [sandboxie-plus/Sandboxie#246]
Sandboxie Plus appears to fail rather ungracefully when you attempt to create a new sandbox with spaces in its name. It blurts out several errors at once:

09:14:52.747   PID 19292: SBIE2203: Failed to set configuration setting Enabled in section Visual Novels: c000000d;   
09:14:52.750   SBIE1405 Configuration file error in line 51:  syntax error                                             
09:14:53.254   Sandboxie config has been reloaded               

Renaming a pre-existing sandbox to one with spaces appears to be fine.

**Comment by DavidXanatos** [comment]
Yes it does and that will be fixed in the next build

**Comment by typpos** [comment]
More generally:

You can create a sandbox called "con". This (surprisingly) successfully creates a new folder "con" when you start a sandboxed app, but you can't operate on that folder in Windows Explorer: trying to browse / rename / delete the folder fails.

A number of names are illegal for files and folders in Windows (aka Explorer and friends) although the names are legit for NTFS.

Examples: CON PRN AUX NUL COM1 COM2 COM3 COM4 COM5 COM6 COM7 COM8 COM9 COM0 LPT1 LPT2 LPT3 LPT4 LPT5 LPT6 LPT7 LPT8 LPT9 LPT0

I suggest sandboxie ensures that sandbxo names are "Windows safe".

**Comment by DavidXanatos** [comment]
@typpos yea good idea will add that in the next build 👍

**Comment by DanielKonopka** [comment]
The issue also appears when trying to create a sandbox with minus sign character in the name, or, if you rename an existing sandbox to have minus sign character in the name.
