### ISSUE TITLE
Strange behavior when naming a new sandbox with a previously used box name

### ISSUE THREAD

**Issue by esalkin1** [sandboxie-plus/Sandboxie#2460]
### Describe what you noticed and did

I was having an issue whereby in a sandbox named Daz_3d any browser acted as if they were offline. 
(The sandbox had been working fine previously)
I deleted the sandbox and created a new one with the same name (Daz_3d). 
The new box had the same issues!
I deleted it.
I  shutdown SBIE+, uninstalled it and rebooted.
Reinstalled SBIE+ and created a default box which worked fine.
Created another new box with the name Daz_3d.
It had the same connection issues!!!
Created a box named Daz3d (no underscore) and that worked file!!!

Is there something left behind when you remove a sandbox that can get corrupt???

BTW, Ping and trace route worked fine on the problem named sandbox.

### Affected program

Ffirefox 106.0.5 (x64), Chrome 106.0.5249.119 (x64), Daz Central 1.5.0.20 (x64)

### Download link

https://www.daz3d.com/dazcentral

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Removing a sandbox should remove all traces of it in the system.  At a minimum move all traces to the Recycle Bin.

### What is your Windows edition and version?

Win 10 Pro 22H2  120.2212.4180.0

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

MS Defender

### What version of Sandboxie are you running?

SBIE-Plus V1.5.

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
NetworkEnableWFP=y
FileRootPath=\??\%SystemDrive%\Sandbox\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Edge_Fix
Template=7zipShellEx
SeparateUserFolders=n

[UserSettings_097C0165]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y


[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[Daz3D]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=n
```

**Comment by DavidXanatos** [comment]
if you delete the box folder than there should be nothign left
perhaps soem component did not like the "_" in the name

**Comment by esalkin1** [comment]
That is what I have always assumed.  So I just tried it with a new box named "Test_Box" and that one worked fine.  It must be something corrupt in WinDoze wonderful registry where nothing ever goes wrong.
