### ISSUE TITLE
ReadIpcPath=$:explorer.exe still produces SBIE2111

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2465]
### Describe what you noticed and did

This may work with any program, but it works every time with PotPlayer, which is the case I use that as example.

1) Install PotPlayer into the system (outside any sandbox)
2) Set `NotifyProcessAccessDenied=y` to a box (To be noticed when something tries to access process memory)
3) Set `ReadIpcPath=$:explorer.exe` to the same box (To avoid be notified for explorer.exe
4) Launch Potplayer (PotPlayerMini64.exe) inside that sandbox
5) See the following messages to be logged: (just one as example, they are all the same)

> PotPlayerMini64.exe (PID): SBIE2111 Process is not accessible: $:explorer.exe, call OpenProcess (C0000022) access=00000040 initialized=1 

Please note that `OpenIpcPath=$:explorer.exe` does not produce SBIE2111, but that's not what I want to use.

### How often did you encounter it so far?

Any time a box is set to issue SBIE2111, while ReadIpcPath=$:explorer.exe is set

### Affected program

At least Firefox and Potplayer

### Download link

https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup64.exe

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Due to having set `ReadIpcPath=$:explorer.exe` no SBIE2111 to be issued for explorer exe. (I still want to get SBIE2111 for some other process.)

### What is your Windows edition and version?

Windows 7 64bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.5.3 64bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

I am not sure, since I had SBIE2111 disabled, after enabling it with the first version that got this feature, but disabling the message as I saw those messages and did not set any IPCpath

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
This is the box config for PotPlayer.

Enabled=y
ConfigLevel=9
AutoRecover=y
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#0077ff,ttl,2
DropAdminRights=y
BoxNameTitle=n
CopyLimitKb=81920
DontCopy=.mp4
DontCopy=.mp3
DontCopy=.avi
DontCopy=.mkv
ClosePrintSpooler=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
ForceProcess=PotPlayerMini64.exe
LeaderProcess=DTDrop64.exe
LeaderProcess=PotPlayerMini64.exe
ProcessGroup=<BlockNetAccess>,dllhost.exe
ProcessGroup=<BlockNetDevices>,
ProcessGroup=<InternetAccess>,PotPlayerMini64.exe
NotifyInternetAccessDenied=n
BlockNetworkFiles=y
HideOtherBoxes=y
ReadIpcPath=$:explorer.exe
OpenClipboard=n
UseRegDeleteV2=y
AllowNetworkAccess=!<InternetAccess>,n
AllowNetworkAccess=<BlockNetAccess>,n
UseRuleSpecificity=y
UseSecurityMode=y
NotifyProcessAccessDenied=y
```

**Comment by bastik-1001** [comment]
This is also happening in the standard box, I just selected my box-type, but that is apparently not bound to the type.

**Comment by DavidXanatos** [comment]
Well pot player seams to want to open a write access
access=00000040 is PROCESS_DUP_HANDLE which allows to duplicate an own handle into a target process

**Comment by bastik-1001** [comment]
Then I think, this issue does not have any merit, unless there would be a distinct message for read access and write access.

I mainly set that for the box I run my browser in, since I wanted to be notified, when something tries to access other processes' memory. I just found out that with PotPlayer it was way easier to reproduce.

This issue is not valid, as it isn't a bug that those messages show up.
