### ISSUE TITLE
SbieDrv.sys REFERENCE_BY_POINTER BSOD

### ISSUE THREAD

**Issue by dumpsters** [sandboxie-plus/Sandboxie#2471]
### Describe what you noticed and did

Been having these for a while now randomly, spotify triggers it sometimes (when running in a sandbox), sometimes just happens without any program running in the sandbox. Maybe this crash dump will be useful.

### Affected program

SbieDrv.sys, Spotify

### Download link

Not available

### Where is the program located?

Not relevant to my request.

### Expected behavior

Not blue screen

### What is your Windows edition and version?

Windows 10 Education 21H1

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.4.1 64bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Crash dump

https://files.catbox.moe/2w3m2e.dmp
[2w3m2e.zip](https://github.com/sandboxie-plus/Sandboxie/files/10043173/2w3m2e.zip) (GitHub mirror)

**Comment by isaak654** [comment]
@DavidXanatos 
PDB's build for v1.4.1 x64: https://github.com/sandboxie-plus/Sandboxie/actions/runs/3191918999

**Comment by DavidXanatos** [comment]
hmm.. the issue is with loggin firewall when WFP support is enabled,
pelase disable firewall tracing as a workaround.

**Comment by dumpsters** [comment]
> hmm.. the issue is with loggin firewall when WFP support is enabled, pelase disable firewall tracing as a workaround.

I've been using simplewall, do you think that has something to do with it?

**Comment by isaak654** [comment]
The lead developer probably referred to one of the tracing functions in Sandboxie Plus:
<img src="https://user-images.githubusercontent.com/12372772/202931606-8affa3db-3fd8-496e-b0ff-712c63762a04.png" alt="NetFwTrace" height="250px">

**Comment by isaak654** [comment]
@DavidXanatos Is this issue related to the fix in commit d09e2ed?

**Comment by DavidXanatos** [comment]
yes
