### ISSUE TITLE
Firefox and Edge will not run in a sandbox

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#2472]
### Describe what you noticed and did

The following error has been around at least since mid-October, and has persisted through various updates of Windows 10 Pro (including 21H2 —>22H2), Sandboxie, Firefox and Edge.

THE ERROR:
1. Sandboxie-Plus UI —> Right-click on the sandbox DefaultBox.
2. Run —> Run Program —> Enter 'Firefox.exe' —> OK.
3. Tbe browser does not launch, but instead an error screen launches: 
  — Title: firefox.exe - Application Error
  — Message: The application was unable to start correctly (0xc0000005). Click OK to close the application. 

FURTHER DETAILS:
 * Same result whether the sandbox is initially empty or not.
   — Same result in any other sandbox, including new RAM sandboxes created a fortnight ago.
   — Same result launching Firefox from the Start Menu with Sandboxie's forcing on.
   — Same result using the command 'Firefox' in a RunBox with forcing on.
 * Same results with the Edge browser.
 * But no problems launching Firefox or Edge outside a sandbox, with the Start Menu, or with the bare command 'Firefox' or 'MSEdge', when forcing is paused.
  — And no problem using the commands Sandboxie /dfp Firefox and Sandboxie /dfp MSEdge.
 * No problems with Vivaldi and Brave, my other two browsers.

 * Same behaviour in all the points above on my wife's notebook, which I maintain with almost exactly the same software, settings and updates as my own desktop (except that I have not yet added RAM sandboxes to the notebook).

### How often did you encounter it so far?

Every time — it is not intermittent.

### Affected program

Firefox and Edge

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

CURRENT VERSIONS:
My PC is a 64-bit custom desktop, my wife's is a 64-bit Dynabook SATELLITE PRO C50-H notebook.
Both PCs have:
 * Windows 10 Pro 22H2, V10.1.19045.2251
 * Sandboxie-Plus-x64-v1.5.3 
 * Firefox 64-bit V107.0 
 * EdgeEnterpriseX64V107.0.1418.52

All software on the PC is fully updated.  As far as I am aware, I have made no changes to the software apart from the updates as they came in.

About a fortnight ago, I installed the old versions Firefox 105.0.3 and Sandboxie-Plus 1.4.2 on my desktop.  I did these installations over the top without uninstalling the previous versions.  There was no change in behaviour, and I updated them again straight afterwards.

### What is your Windows edition and version?

Windows 10 Pro 22H2, V10.1.19045.2251m 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET Internet Security V16.0.24.0

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.5.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

Unsure.  Probably 1.4.2

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by offhub** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/1545#issuecomment-1291012565

**Comment by offhub** [comment]
[Disabling the Banking & Payment protection in ESET solves the issue.](https://support.eset.com/en/kb5704-pause-or-disable-banking-payment-protection-in-eset-windows-home-products)

**Comment by offhub** [comment]
OR

You could add following rule to the your config:
`
DenyHostAccess=ekrn.exe,y`

**Comment by NotepadPlusUser** [comment]
Thank you very much, Isaak654 and offhub.  The fact that ESET is the cause was a total surprise!  I don't use ESET's Banking & Payment protection, so I simply turned it off, rather than trying to implement the more complicated workarounds.  All is now well on the desktop and notebook — much appreciated.

Not good, however, from ESET.  They have an excellent agent Microbe here in Australia, and I have written to them to alert them to the problem and to these posts, including the fact that it has been around for some time and publicly commented on.  Hopefully they will have some influence over the situation — although just possibly it could be associated with Russia's invasion of Ukraine.

**Comment by tdtc-hrb** [comment]
3Q.
OS: Windows 10 1809(LTSC)
Sandboxie-Plus: v1.5.3
ESET: v16.0.24.0
Chrome: v107.0.5304.107(64-bit)

Using portable Chrome.
Right-click "DefaultBox" to Run->Run Program-"D:sandbox_sChrome-binchrome.exe".
Offhub's video solved my problem. Thanks

**Comment by mysteriously** [comment]
This feature is useless anyway if you use sandboxie where you have pretty much full control over your banking sandbox.

Also, you can search HKEY_LOCAL_MACHINE\SOFTWARE\ESET if there is any way to switch registry setting to disable it.

**Comment by isaak654** [comment]
Thank you for the confirmations provided above.
I'm closing this duplicate issue in favour of the original #1545, which will remain open until it is resolved.

**Comment by NotepadPlusUser** [comment]
Microbe has now contacted ESET, and an ESET developer has come back to Microbe, to say that ESET has classified this issue as a bug, which is expected to be resolved in future updates.
