### ISSUE TITLE
Is it safe to install Sandboxie-Plus over the official version?

### ISSUE THREAD

**Issue by iPyGuy** [sandboxie-plus/Sandboxie#248]
I have the last official build (5.33.3) of Sandboxie installed and I wanted to install the latest version of Sandboxie-Plus (0.5.1) but I had a few questions.

1. Do I need to uninstall the official Sandboxie first and then install Sandboxie-Plus or can I leave 5.33.3 installed and just install Sandboxie-Plus over it?
1. Also, I notice in the releases section there are both legacy versions and Plus versions of Sandboxie provided. Do I need to install both or can I just install the Plus version?
1. After installing the Plus version, will all my existing sandboxes/settings carry over?

Sorry if these sound like stupid questions, I am just being careful because I have like 20 sandboxes and they all have important stuff in them and I don't want to mess something up and damage or lose all of those existing sandboxes.

**Comment by DavidXanatos** [comment]
First make a backup of your C:\windows\sandboxie.ini if there is something important than always have a backup!

Than uninstall old sandboxie and when prompted opt for keeping the sandboxie.ini

Than install sandboxie plus only, it will use the existing sandboxie.ini with all the settings and configurations.

**Comment by iPyGuy** [comment]
Thank you for responding.

I can confirm that everything is working properly after following the steps you listed!
