### ISSUE TITLE
Inaccurate disk space usage during downloading huge file

### ISSUE THREAD

**Issue by mysteriously** [sandboxie-plus/Sandboxie#2481]
### Describe what you noticed and did

1. Open MS Edge
2. Start downloading >5GB file slowly to a OpenFilePath location which is NOT system or Sandbox partition
3. Monitor disk usage on System (Sandbox) partition and on OpenFilePath Partition

a) File on OpenFilePath partition has been created when downloading started. It was also increasing its size during downloading.
b) After a long time, some weird ~17GB *.tmp file has been created on SystemDrive\temp. It was at least twice the size of full file I was trying to download and much heavier than size of the data that has already been downloaded
c) When I deleted the ~17GB *.tmp file, SystemDrive available disk space has not been increased.
d) When I closed Edge SystemDrive available disk space came back to normal immediately

### Affected program

Microsoft Edge 107.0.1418.42

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Consume disk space only on partition with OpenFilePath

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Eset Endpoint Security 9.1.2060.0

### What version of Sandboxie are you running?

1.5.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

![image](https://user-images.githubusercontent.com/17072890/203446997-bfbc82d9-2ce7-4fd0-92d1-37fcfac506b5.png)

**Comment by DavidXanatos** [comment]
this is strange, also i tryed downloading a file to a open file path and coudl not reproduce this issue,
did it happen more than once?

**Comment by mysteriously** [comment]
Yes. I will try to record a video about it
