### ISSUE TITLE
"Located on a volume that does not support naming (8.3 naming), which can cause problems with older applications and installers."

### ISSUE THREAD

**Issue by FanXiangTM** [sandboxie-plus/Sandboxie#2482]
### Describe what you noticed and did

"SBIE2227 'Browser (G:\Sandbox\SYSTEM\Browser)' 位于一个不支持命名(8.3 naming)的卷上，这可能导致旧的应用程序和安装程序出现问题。"

The sandbox file is placed on the F or G drive. this will be the case. And if the sandbox file is located on drive E or D, the

https://pic7.58cdn.com.cn/nowater/webim/big/n_v221cb1140be3a46968d3f743d5220178d.png

### How often did you encounter it so far?

Every day, every time

### Affected program

All

### Download link

不相关

### Where is the program located?

Not relevant to my request.

### Expected behavior

Find out the cause and fix the problem

### What is your Windows edition and version?

Windows11 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET Internet Security

### What version of Sandboxie are you running?

Sandboxie classic 5.60.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by offhub** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/2407#issuecomment-1293134953

**Comment by DavidXanatos** [comment]
enable 8.3 naming for the driver where your box is located or globally for all drives
or hide the warning message
