### ISSUE TITLE
SUPPORTER CERTIFICATE - Where can be installed

### ISSUE THREAD

**Issue by tusiromania** [sandboxie-plus/Sandboxie#2483]
### Is your feature request related to a problem or use case?

Hi
I spent the last two hours trying to figure out where I could install the certificate I bought.
it is not at all intuitive in the program, where it can be entered.

Can someone help me?
how is it installed?

### Describe the solution you'd like

I believe that an easier way to enter this certificate would help more people.

**Comment by offhub** [comment]
**For Sandboxie-Plus**:

`Options > Global Settings > Support > You can copy and paste your certificate to the text area > OK`

> **Then it will ask for your confirmation to move the certificate file to the Sandboxie-Plus folder**:

`"You will need to provide administrator permission to move to this folder" > Continue.`

**For Sandboxie-Classic**:

`You can copy the Certificate.dat from your Sandboxie-Plus installation into the installation folder of the classic installation.`


https://user-images.githubusercontent.com/6871698/203371472-53396a43-afe0-48c6-a1a4-c75ef9a0d4de.mp4
