### ISSUE TITLE
MSYS2 - installation problem

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#2493]
### Describe what you noticed and did

It is not possible to install MSYS2. Once the installer is launched it starts over and over again in infinite loop.
1. Right-click on a sandbox, select **msys2-x86_64-20221028.exe** and select OPEN.
2. A whole tree of installer-related processes show up. The processes disappear (terminated autonomously) and show up again.
3. Nothing happens.

![image](https://github.com/sandboxie-plus/Sandboxie/assets/93145383/cc2b2e48-0777-436b-83e9-94586e021956)

My sandbox presets:
1. Drop Admin Rights
2. Block Internet Rights
Besides these presets, everything by default.

### How often did you encounter it so far?

Always

### Affected program

msys2-x86_64-20221028

### Download link

https://github.com/msys2/msys2-installer/releases/download/2022-10-28/msys2-x86_64-20221028.exe

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

I would like to be able to launch the installer and install the application within my sandbox.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

Microsoft Security Essentials

### What version of Sandboxie are you running?

1.5.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by DavidXanatos** [comment]
this installer is wired it starts with a console and then closes it,
do you know which installer framework this is and where to find the sources?
Qt also uses it it seams see @3153

**Comment by isaak654** [comment]
> do you know which installer framework this is and where to find the sources?

According to the documentation of [MSYS2 Installer](https://www.msys2.org/docs/installer/#cli-usage-examples):

> The GUI installer utilizes the [Qt Installer Framework](https://doc.qt.io/qtinstallerframework/) which also offers CLI options for automation.

By the way, the source code is available at https://github.com/qtproject/installer-framework

**Comment by DavidXanatos** [comment]
yes i have identified the issue will be fixed in the next build
