### ISSUE TITLE
Edge is all white in Sandboxie Classic starting today.

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#2496]
### Describe what you noticed and did

I added the following two lines below, last week and Edge worked.
OpenIpcPath=msedge.exe,\Sessions\*\AppContainerNamedObjects\*
OpenFilePath=msedge.exe,\Device\NamedPipe\Sessions\*\AppContainerNamedObjects\*
Today, is went back to being white.
The last Windows update was 11-9-2022.
Windows 11 Version 10.0.22000 Build 22000
Microsoft Edge Version 107.0.1418.56 (Official build) (64-bit)

### How often did you encounter it so far?

Ever time I open Edge

### Affected program

Microsoft Edge Version 107.0.1418.56 (Official build) (64-bit)

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Shows webpages not just a white screen.

### What is your Windows edition and version?

Windows 11 Version 10.0.22000 Build 22000

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

5.60.3

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

None

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
OpenFilePath=c:\windows\system32\spool\printers\*
AllowSpoolerPrintToFile=y
OpenFilePath=firefox.exe,%UserProfile%\AppDataLocalLow\Mozilla\temp-*
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
ForceDisableSeconds=300

[DefaultBox]
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=Edge_Force
Template=AdobeDistiller
Template=AdobeAcrobatReader
Template=AdobeAcrobat
Template=Chrome_Profile_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=Chrome_Sync_DirectAccess
Template=Chrome_Preferences_DirectAccess
Template=Chrome_Passwords_DirectAccess
Template=Chrome_Cookies_DirectAccess
Template=Chrome_History_DirectAccess
Template=Chrome_Bookmarks_DirectAccess
Template=Chrome_Force
Template=Firefox_Profile_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=Firefox_Session_DirectAccess
Template=Firefox_Passwords_DirectAccess
Template=Firefox_Cookies_DirectAccess
Template=Firefox_Bookmarks_DirectAccess
Template=Firefox_Force
Template=Edge_Profile_DirectAccess
Template=Edge_Phishing_DirectAccess
Template=Edge_Sync_DirectAccess
Template=Edge_Preferences_DirectAccess
Template=Edge_Passwords_DirectAccess
Template=Edge_Cookies_DirectAccess
Template=Edge_History_DirectAccess
Template=Edge_Bookmarks_DirectAccess
Template=IExplore_ProtectedStorage
Template=IExplore_Feeds_DirectAccess
Template=IExplore_Cookies_DirectAccess
Template=IExplore_History_DirectAccess
Template=IExplore_Favorites_RecoverFolder
Template=IExplore_Favorites_DirectAccess
Template=IExplore_Force
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
Enabled=y
AutoDelete=y
NeverDelete=n

[UserSettings_0CC60227]
SbieCtrl_UserName=artvi
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1670033250
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_WindowCoords=-9,151,2426,843
SbieCtrl_ActiveView=40021
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_HideMessage=2205,ConsoleInit (C00000D4)
```

**Comment by offhub** [comment]
It looks like the issue occurs because you didn't enable the `Edge_Fix`.

Remove the following lines from your config:
```
OpenIpcPath=msedge.exe,\Sessions*\AppContainerNamedObjects*
OpenFilePath=msedge.exe,\Device\NamedPipe\Sessions*\AppContainerNamedObjects*
```

then add the following line, under `[GlobalSettings]`, to your config:
```
Template=Edge_Fix
```

**Comment by jedimasterspaz** [comment]
Thanks, it worked.
Can you explain what the difference is between what the first 2 lines do and then what the single line does?
Why did DavidXanatos suggest the 2 lines and it worked for Win10 and 11, and now I need to replace the 2 lines with this new line? 
Also, should I replace those 2 lines for the new line everywhere?
If you have the time, I would appreciate know more about how things work.
You can close the case,

**Comment by isaak654** [comment]
The two lines are already included in the Edge_Fix template, plus a couple of additional fixes:
https://github.com/sandboxie-plus/Sandboxie/blob/9272a077cd92257b48dc57e5649604bd4c8904d0/Sandboxie/install/Templates.ini#L642-L655
