### ISSUE TITLE
Delete complete Sandboxie Plus content 

### ISSUE THREAD

**Issue by ewald81375** [sandboxie-plus/Sandboxie#2497]
### Describe what you noticed and did

Leaving Firefox (started with Sandboxie Plus) will show me the attached message. As you can see there are some Outlook files, because sometimes I open Outlook with Sandboxie Plus.
My Question: 
Can I delete all shown files with the red marked button ("Löschen") and only files in Sandboxie Plus will be deleted and   n o t  the orginal Outlook files?  
Thanks and best regards
Ewald 

![2022-11-26_11h11_59](https://user-images.githubusercontent.com/85554956/204083720-4a924956-eecb-42d7-8662-35fa10e12d42.png)

### Affected program

Firefox 107.0 

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

I expect the deletion of all files only in Sandboxie Plus

### What is your Windows edition and version?

Windows 10 Home 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sanboxie Plus

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

Not relevant

### Trace log

not relevant

**Comment by DavidXanatos** [comment]
yes these buttons only delete the sandboxed copies not the original fiels on the host
