### ISSUE TITLE
Will sandboxie have network speed limit function? 

### ISSUE THREAD

**Issue by shutaozhenzhen** [sandboxie-plus/Sandboxie#25]

**Comment by DavidXanatos** [comment]
I don't see that as being something in the scope of the project, but since possibly/probably it may be easy to add and I love overloading my projects with every conservable enhancement, i'll put it on the very bottom of my todo list

**Comment by robdplatt** [comment]
@shutaozhenzhen You might try running [Clumsy ](https://jagt.github.io/clumsy/)within the sandbox to achieve what you're after.

**Comment by DavidXanatos** [comment]
further discussion on sandboxie's networking aspects please in issue #894
