### ISSUE TITLE
Recovering files

### ISSUE THREAD

**Issue by darrepac** [sandboxie-plus/Sandboxie#250]
Hi

Using sandboxie on Win10.
I have some fails to recover files. Here are the step.
I save a file then I am able to recover it.
If I make some modifications (still through the software launched through sandboxie) and wants to save back into the same file than in previous step, I cannot recover the files (failed message). So each time I modify the file, I need to change the filename.

Is it normal?

**Comment by DavidXanatos** [comment]
What error message? do you recover to same location?
When you recover the file gets moved out of the sandbox to a real location
When you sane again i guess the file is re created int he sandbox, recovering agian to a non custom location may fail as there is already a file outside with that name

**Comment by darrepac** [comment]
**What error message? do you recover to same location?**
Error message is not saying much than "failed to recover"

**When you recover the file gets moved out of the sandbox to a real location**
When it succeeds, yes

**When you sane again i guess the file is re created int he sandbox, recovering agian to a non custom location may fail as there is already a file outside with that name**
So, if I recover file A in folder X. Then I modify again the file and want to recover the modified file, it is normal that I cannot receover file named A in folder X?

**Comment by DavidXanatos** [comment]
You will need to pick a different folder.
