### ISSUE TITLE
[1.6.0] Support settings drop down menu items multiply when Apply is clicked

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2501]
### Describe what you noticed and did

1. Open `Options > Global Settings > Support`
2. Enable `Check periodically ...`
3. Click `Apply`
4. Open `Drop down menu`

![vmconnect_20221127_104914_286](https://user-images.githubusercontent.com/6871698/204124789-efabcc2f-2bdc-4d24-bc79-c45beada7bd8.png)

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Not to multiply.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.6.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by okrc** [comment]
https://github.com/okrc/Sandboxie/commit/3c67f63f517e77fab1362d640485c29514043b8a Try [this build](https://github.com/okrc/Sandboxie/actions/runs/3557810572).
