### ISSUE TITLE
[ESET] Error when launching firefox or chrome with Eset internet security installed

### ISSUE THREAD

**Issue by gab12** [sandboxie-plus/Sandboxie#2504]
### Describe what you noticed and did

I just installed ESET internet. (Before Eset I had no problem with sandboxie and the same configuration)
When I launch firefox or chrome in the sandbox with "ESET NOD32 Antivirus" compatible mode, I get an error message and the browsers do not launch. The sandbox does not launch either:" the application failed to start correctly"

![Capture d’écran 2022-11-28 164241](https://user-images.githubusercontent.com/6320898/204319814-ad8cee5c-a732-4292-953c-bf3d48bbfea0.png)

When I remove the "ESET NOD32 Antivirus" compatible mode from the sandbox, the browsers launch fine and work but I get an error pop-up (non-blocking)

![Capture d’écran 2022-11-28 164318](https://user-images.githubusercontent.com/6320898/204319979-ddbbfb90-eaed-42e9-8d21-ec3afc7e0754.png)

"SBIE2112 Objet non accessible : \BaseNamedObjects\NODCOMM49554745To31524B45CommPortAlpc, appel AlpcConnectPort (C0000022) access=001F0001 initialized=1"
could you help me ?

Note: With sandboxie disabled, I have no problem.

### How often did you encounter it so far?

systematic

### Affected program

Firefox 107.0, Chrome 107.0

### Download link

https://proxy.eset.com/li-handler/?branch=fr&prod=eis&transaction_id=odcm_download|ggl|fr|oksckhikof30h3f3pglrv2uqqap24hz165laouit88a0u79deo4xsjiaikwubpzmwucid

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

launch browser without error

### What is your Windows edition and version?

Windows 11

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET internet security

### What version of Sandboxie are you running?

Sandboxe 5.60.3

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=Edge_Fix
Template=Edge_Win11Fix
Template=VirtualDesktopManager
Template=RpcPortBindings
Template=Windows10CoreUI
Template=FireFix_for_Win7
Template=OfficeClickToRun
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
ActivationPrompt=n
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
TemplateReject=NOD32
TemplateReject=BitDefenderInternetSecurity
TemplateReject=ComodoInternetSecurity
TemplateReject=FSecure
TemplateReject=Kaspersky



[UserSettings_07DC0191]

SbieCtrl_UserName=chad
SbieCtrl_NextUpdateCheck=1670000723
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_WindowCoords=574,24,1042,632
SbieCtrl_ActiveView=40021
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_RecoverTarget=D:\Bibliothèque\Downloads
SbieCtrl_RecoverTarget=D:\
SbieCtrl_RecoverTarget=D:\Bibliothèque\Desktop
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=y
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_HideMessage=2211,BITS
SbieCtrl_BoxExpandedView=Chrome,Edge,Excel,Firefox,Lecteur_PDF,Sandboxe_avec_Internet,Sandboxe_Sans_Internet,Tor,Vivaldi,VLC

[Firefox]

Enabled=y
ConfigLevel=9
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=Firefox_Bookmarks_DirectAccess
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=AutoRecoverIgnore
BorderColor=#00FFFF,ttl
AutoDelete=y
NeverDelete=n
NotifyInternetAccessDenied=y
CopyLimitKb=2097177
LeaderProcess=firefox.exe
AutoRecoverIgnore=*.fdmdownload
AutoRecoverIgnore=.fdmdownload
ForceFolder=C:\Program Files\Mozilla Firefox
ProcessGroup=<InternetAccess>,firefox.exe,browsernativehost.exe,fdm.exe,KeePass.exe,plugin-container.exe,Apowersoft Online Launcher.exe,pingsender.exe,net.downloadhelper.coapp-win-64.exe,tor.exe,fx_cast_bridge.exe,adb.exe,Zoom.exe,default-browser-agent.exe,slack.exe
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
AutoRecover=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%

[Chrome]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
ForceFolder=C:\Program Files\Google
NotifyInternetAccessDenied=y
AutoDelete=y
NeverDelete=n
ForceProcess=chrome.exe
ForceProcess="c:\program files (x86)\google\chrome\application\chrome.exe"
CopyLimitKb=695956
ProcessGroup=<InternetAccess>,<ChromePrograms>,Zoom_cm_ds_mU6YvXksO+WHV4IhaQ+V46I06GZZ1etYyzMpo@hW7zWYgcoHRjOMki_kfd5298db7c32c115_.exe,Zoom.exe,chrome.exe,GoogleUpdate.exe
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
LingerProcess=TSVNCache.exe
```

**Comment by isaak654** [comment]
Duplicate of #1545
