### ISSUE TITLE
Conflict: portable sandboxie read config from non-portable sandboxie

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [sandboxie-plus/Sandboxie#2505]
### Describe what you noticed and did

1. Install sandboxie
2. Open sandman, create generic sandbox
3. Stop All, exit sandman
4. Run portable sandboxie

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

If started from portable then read sandboxie.ini from portable sandboxie folder, not from %windir%.

Currently I had to remove the driver and service and rename sandboxie.ini in %windir%, only then running from the portable all works works as expected.

### What is your Windows edition and version?

Windows 10 Pro 21H1 64 bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

1.5.3 64bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
What you expect can not work as there can only be one SbeiDrv.sys loaded at once.
So its not possible (without a major redesign) to have the poertable sandboxie use a different driver and those sandboxie.ini then the installed sandboxie.

Portable mode is only intended to be used when no regular installation is available.

**Comment by 0x4E69676874466F78** [comment]
@DavidXanatos 
Why not tell the driver which sandboxie.ini to use when we run sandman? (If there is the sandboxie.ini next to sandman.exe then take it).

Imagine I bring a portable sandboxie to a friend who already installed sandboxie.

**Comment by bastik-1001** [comment]
The installed version of Sandboxie has to trump over the portable instance of Sandboxie, since the installed version has the desired configuration, set by whomever had access to set it. This includes forced folder and forced processes, among other settings. Starting a portable instance should not override the non-portable settings, since that can have undesired consequences for the owner of that computer. I expect my browser to start sandboxed, which it would not, if my sandbox.ini would be ignored, due to me allowing some else to start a portable version of Sandboxie.

**Comment by DavidXanatos** [comment]
@0x4E69676874466F78 stooping is not enough, the driver does not know whom started it, so it only goes by its own file path.
Hence if you start an installed sandboxie from a portable instance, it will still start the installed driver not the own portable one.

To achieve what you want you must stop and uninstall the installed driver/service and install the portable driver/service in its place.
Once you are done you need to uninstall those and re install the non portable once.

**Comment by 0x4E69676874466F78** [comment]
Yes I understand, but for convenience it would be nice to transmit the path at startup.
However, as I understand you are not interested in it, ok then I will close the issue.
