### ISSUE TITLE
Does sandboxie-plus have plans to add multiple languages?

### ISSUE THREAD

**Issue by lxitdn** [sandboxie-plus/Sandboxie#251]
When will the multilingual version be released? Expect.

**Comment by DavidXanatos** [comment]
When enough volunteers offer to do the translation into their respective languages.

**Comment by bastik-1001** [comment]
This is kind of related to my question #243.

Can someone create the required .ts files for translation? I don't have Qt installed, and can't create the files from the source, but I could use Linguist to load the .ts files and translate them into German.

I guess that if there is enough interest there will be someone for other languages. The .ts file is an XML format and could even be edited without special tools, although it seems to be wise to use Linguist for it.

**Comment by DavidXanatos** [comment]
Her there are:
https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_de.ts
https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/QSbieAPI/qsbieapi_de.ts

**Comment by bastik-1001** [comment]
Thank you for providing them, I update my initial fork, so I can edit them with Linguist and create a pull request once I am done.

**Comment by typpos** [comment]
Please make sure the impact on future development effort is understood before going for this: Once translations are in place, they will need to be maintained for every future feature and feature change. It's a fair overhead and creates ongoing skill (translator) dependencies.

**Comment by DavidXanatos** [comment]
Nah... wherever a translation is outdated you just get some english strings sprinkled in, that's fine and better than having no translation at all.

**Comment by typpos** [comment]
Ok. Sounds durchführbar.  :-)

**Comment by DavidXanatos** [comment]
> 
> 
> Ok. Sounds durchführbar. :-)

Dass tut es indeed, Muhahahaahaha.....!!!

**Comment by isaak654** [comment]
@DavidXanatos I didn't finish to look up for all english strings, because there are in multiple files and it's a bit time-consuming... could you provide sandman_en.ts and qsbieapi_en.ts too for easier access?

**Comment by bastik-1001** [comment]
@DavidXanatos Can you 'cook-up' a German translation file I can place in the Sandboxie-Plus folder in order to select it in the menu, so that I can test if the translated strings break something, by being too long or something?

Unless it is more complicated. I know that you commented on the pull request that you might change the strings into a single file, so I would wait until you decided how it is done, before moving on.

**Comment by DavidXanatos** [comment]
There is a bug in the current build that makes it fail to load translations, ups...
I'll upload a revised version that will handle translations properly.

**Comment by DavidXanatos** [comment]
Here is the german lang pack + required patch: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.5.2/Sandboxie-Plus-v0.5.2-LangPack+Patch.zip
Copy the files of the appropriate bigness to your installation directory, and you should be able to select german language, after one more restart of the UI you should all german strings.

I have moved your translation from the qsbieapi file to the sandman file so only very few strings should be missing.

**Comment by bastik-1001** [comment]
Thank you for providing the patch and the required language package.

It loaded fine and it looks like it would not be overly long at any point. Within the UI I noticed that I forgot two letters in two words and that I will have to add an 'n' to two entries to make it sound and look better. Those are minor things, not like that it would be reversing the meaning or one would be unable to get what the words were supposed to be.

Once you are done with the re-factorization of the language system and the strings being in one place I will make these changes/typo fixes and translate new strings that may got introduced.

**Comment by DavidXanatos** [comment]
> 
> 
> Once you are done with the re-factorization of the language system and the strings being in one place I will make these changes/typo fixes and translate new strings that may got introduced.

that is already done and commited to the repo

**Comment by bastik-1001** [comment]
With multiple languages being available you may want to state in the documentation that users shall provide screenshots with the language being set to English as you can give only support to things you can read and understand.

Unless of course the translation is at fault and the screenshots would be to show where the issue with some wording lies.

**Comment by typpos** [comment]
How about showing a unique id on each dialog, eg, greyed code in corner of
dlg, like #D4F

If clicked, could show context menu with options..

A: Create tech support report including app version, OS version, app state,
stack state, sandbox details, etc, copied to clipboard. Bonus for adding
replay info, eg, last 10 user actions.

B: open browser to go to github support page for that window/dialog/state.
This would allow all previously created support info relevant to that
dialog sit in the easiest to access place. Reduces support requests.

C: (maybe/a bit far out)  Re-roll this dialog in English.

D: (also far out) render ALL open  sandboxie windows and dialogs to a
single bitmap to clipboard. Often users screenshot the wrong dialog, or
dialogs are modal and parent dlgs can't be reached.

**Comment by lxitdn** [comment]
> > 一旦完成了语言系统的重新分解并将字符串放在一个地方，我将进行这些更改/打字错误修复，并翻译可能引入的新字符串。
> 
> 已经完成并提交回购协议

![QQ截图20201226100633](https://user-images.githubusercontent.com/16263881/103144342-fe13a700-4762-11eb-968d-d2a825a8620d.png)
![QQ截图20201226100650](https://user-images.githubusercontent.com/16263881/103144344-010e9780-4763-11eb-97d2-f670fe098240.png)
![QQ截图20201226100714](https://user-images.githubusercontent.com/16263881/103144345-023fc480-4763-11eb-8d04-de1bc89a9b10.png)

I have already translated the local language, how should I submit it?

**Comment by DavidXanatos** [comment]
You can zip the file and upload it in this thread,
or you can fork the project add the file ans submit it as a pull request.
