### ISSUE TITLE
[UI] The Checkbox-State That Should Not Be

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#2521]
### Describe what you noticed and did

In user interface design terms, what does a checkbox do?
How does it work for the user?

A checkbox is either checked or it is empty.
If it is checked, it means `ON` or `TRUE` or `YES`
If it is empty, it means `OFF` or `FALSE` or `NO`

There should never be a third checkbox state.

Imagine an options menu with a checkbox that asks "Do you want to use the Dark Theme?"
Checkbox ticked means "Yes, switch to Dark Theme please."
Checkbox empty means "No, I don't want Dark Theme."
What will happen if the checkbox is half-ticked? Will it turn on Dark Theme every uneven weekday except Monday? Will it turn off Dark Theme during nighttime? Will it launch a nice game of Global Thermonuclear War? 

There should never be a third checkbox state.

Enter Sandma-, I mean Sandboxie Plus:
![4 box WTF](https://user-images.githubusercontent.com/12411527/205712563-999db5d0-ee37-4f14-bc66-74e3f3da08f1.png)
No.

![5 box WTF](https://user-images.githubusercontent.com/12411527/205712661-30d52c61-4a56-4753-8bfc-b2fe46de0644.png)
Just no.

![3 box WTF](https://user-images.githubusercontent.com/12411527/205713920-f5bc85f2-ace6-4afb-98cc-df62b42b46b9.png)
HELL-NO.

Yes, I've noticed the asterisk, but that doesn't answer a user's question what will happen if you indeed half-check all those boxes that may be switched into a third state.
Will it turn those options `ON`? Will it turn them `OFF`? You are left without a clue what Sandboxie might do.

If a Sandboxie user makes choices in the options menu, the outcome should be predictable and reliable. No guessing games. That's why there should never be a third checkbox state.

### Affected program

Sandboxie Plus Global Settings

### Download link

https://youtu.be/bYJGt67Mwmo

### Where is the program located?

Not relevant to my request.

### Expected behavior

Global Settings checkboxes should only know two states.

ON
![2 box on](https://user-images.githubusercontent.com/12411527/205718245-8eccf019-9465-4298-8da4-1da8b97d8290.png)

or OFF
![1box off](https://user-images.githubusercontent.com/12411527/205718343-88b0bb51-478b-4afb-b777-8ff9ea8df0dd.png)

There should never be a third checkbox state.

### What is your Windows edition and version?

Windows 10 Edu 22H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by RandomGOTI** [comment]
tristate c boxes are fine , if the user is in doubt do what you know.. turn it either on or off and the unknown is no longer a problem :neutral_face:

**Comment by DavidXanatos** [comment]
Some options are intended to query the user what to do once they are triggered for the first time with the option to remember the decision, here the undetermined state means no decision remembered, ask (again).
Other options are meant to act differently based on other presets, unless set to a defined value explicitly.
The only alternative would be to use combo boxes every ware what IMHO would not be a good UI design.
