### ISSUE TITLE
Can you add functionality similar to DeepFreeze software?

### ISSUE THREAD

**Issue by lxitdn** [sandboxie-plus/Sandboxie#2528]
### Is your feature request related to a problem or use case?

For example, DeepFreeze software, after the system restarts, will automatically restore to the original setting state

Or disk mode like VMware, (non-persistent): when you shut down or restore a snapshot, changes made to the disk are discarded

### Describe the solution you'd like

Add a switch, the sandbox is persistent or non-persistent, automatically abandon the changes to the sand table when closing the sandbox, and if you need to save, you can turn off the switch

**Comment by DavidXanatos** [comment]
thats alread yimplemented

![grafik](https://user-images.githubusercontent.com/3890945/206894447-8745da59-5831-4d0b-af2a-f75ec6fd1bba.png)

when you have a snapshot, this obtion will revert to the last active snapshot  instead of deleting everything, once the last probram in the box terminates

**Comment by lxitdn** [comment]
> thats alread yimplemented
> 
> ![grafik](https://user-images.githubusercontent.com/3890945/206894447-8745da59-5831-4d0b-af2a-f75ec6fd1bba.png)
> 
> when you have a snapshot, this obtion will revert to the last active snapshot instead of deleting everything, once the last probram in the box terminates

No, you are emptying the sandbox,
That's what I meant
Proportion:
I installed TikTok in the sandbox, but if I don't manage it, the cache will get bigger and bigger, I want to keep the latest installed state, every time I open it, it is the state that was just installed, not emptying the sandbox,

**Comment by offhub** [comment]
You can take a snapshot of the box and revert it to a previous snapshot by using Snapshots Manager.
(`Right click to the box > Snapshots Manager`)

OR (to automate)

1. Open the program.
2. Make your changes.
3. Close the program.
4. Take a snapshot.
5. Enable the auto delete. (**This action will revert the box to its previous snapshot**)
