### ISSUE TITLE
Latest Discord won't run in Privacy Enhanced box

### ISSUE THREAD

**Issue by TFWol** [sandboxie-plus/Sandboxie#2529]
### Describe what you noticed and did

Versions `1.0.9007` and earlier had worked, but after the latest Discord update `1.0.9008`, program won't run.

Went nuclear and installed a fresh version of Sandboxie `1.5.3` with the default Privacy Enhanced Box (Blue Box) in Windows Sandbox (and other test machines) and see the exact same issues.
Discord is installed inside the box only.

Reproduce:
1. Run installer in sandbox, an installer error will occur, but that would happen with previous versions but would still work.
2. Run Discord in sandbox

You'll see the process open in process manager, spawn WerFault, then close.

~~Trace log can be provided if needed, but you will probably see the exact same thing since everything is default.~~

### How often did you encounter it so far?

Everytime

### Affected program

Discord 1.0.9008

### Download link

https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Discord window to open.

### What is your Windows edition and version?

Windows 10 Pro 21H1

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus  1.5.3 x64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a sandbox with data protection (blue sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Nothing was changed.

### Trace log

[Trace Log](https://gist.githubusercontent.com/TFWol/588edd715dfb60718eeb4fc63fcb12cd/raw/0ddd8340bdca4e27d342a7dd4374ea7131b20417/Discord_Trace.log)

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
NetworkEnableWFP=y
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsLive
Template=OfficeLicensing
Template=Edge_Fix

[UserSettings_90A007A5]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[Discord]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#f88501,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=y
OpenPipePath=C:\Users\WDAGUtilityAccount\Desktop\DiscordSetup.exe
FileTrace=*
PipeTrace=*
KeyTrace=*
IpcTrace=*
```

**Comment by okrc** [comment]
This may be because the program cannot read the start menu directory, you can try to run cmd in the sandbox and create this folder.
``` cmd
md "%AppData%\Microsoft\Windows\Start Menu\Programs"
```

**Comment by TFWol** [comment]
Thanks for the post. That actually solved the issue and saved me a lot of time.

I was going to look into paths last since that was never a problem before despite the log errors being pretty much the same.
Guess they changed the installer.

**Comment by NJT145** [comment]
I needed to copy the content of `%USERPROFILE%\AppData\Local\Discord` inside of my sandbox.
Now, in my "Sandboxie.ini", I have two  `WriteFilePath` command:
```
WriteFilePath=C:\Users\nejat\AppData\Local\Discord
WriteFilePath=C:\Users\nejat\AppData\Roaming\discord
```
