### ISSUE TITLE
An issue about automatically deleting content after a process in the last sandbox terminates

### ISSUE THREAD

**Issue by lxitdn** [sandboxie-plus/Sandboxie#2531]
### Is your feature request related to a problem or use case?

This feature must be completely finished in the sandbox before it can be cleaned up

1: I found that if the program is not closed, the computer is directly closed, and the sandbox will not automatically delete the content

2: After the end of some programs, the resident program will remain and the content cannot be automatically deleted

### Describe the solution you'd like

Wouldn't it be better to put this function and driver hooks? For example, if I restart the computer next time without closing the program, the driver will start and the sandbox content will be automatically deleted? Or do you have a better way?
![Snipaste_2022-12-13_11-27-10](https://user-images.githubusercontent.com/16263881/207219379-98f6d087-44a4-4b6b-9818-d7907c5a8650.png)

**Comment by DavidXanatos** [comment]
Its not good to put to much into drivers, such things should be done in user mode so service or ui component.
The proper fix seams to be to let sandman check on startup if boxes marked to auto delete are not deleted and then delete them after a reboot
