### ISSUE TITLE
SandMan steal window focus when full-screen ( return to desktop )

### ISSUE THREAD

**Issue by MisteryMonster** [sandboxie-plus/Sandboxie#2534]
### Describe what you noticed and did

Open Sandboxie-plus GUI ( both background and foreground have tested ) play game in full-screen, and use focus.exe (https://www.happydroid.com/focus) to log, when jump to desktop it display "SandMan.exe" (once i had glimpse when it popup an update check when it's not full-screen, maybe is relevant? )

### How often did you encounter it so far?

sometime

### Affected program

full-screen gaming

### Download link

https://www.happydroid.com/focus

### Where is the program located?

Not relevant to my request.

### Expected behavior

when it's full-screen. it should keep silent.

### What is your Windows edition and version?

Windows 10 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

no relative

### What version of Sandboxie are you running?

1.6.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
I will add a gaming mode to a upcoming build

**Comment by DavidXanatos** [comment]
@MisteryMonster please try the preview build 1.6.1b which you can get by runnign the online upater of the 1.6.1 pre release
let me know if the issue is solved to your satisfaction

**Comment by MisteryMonster** [comment]
Seems like the problem is solved! Thanks!
