### ISSUE TITLE
Another Windows Installer Service issue

### ISSUE THREAD

**Issue by MichaelDietzel** [sandboxie-plus/Sandboxie#2537]
### Describe what you noticed and did

I created a fresh default sandbox in Sandboxie Classic 5.60.3 and tried to install Audials Music 2022 Special Edition by Computer Bild in it. It fails with a Windows Installer Service error that looks different from the errors described in the following two issues
- #1
	- Slightly different error message
	- also occurrs in Windows Server 2016 which is based on and 1809 as well as Windows 8.1
-  #567
	- Config option in Sandboxie Classic does not help (ExposeBoxedSystem=y)
	- the described checkbox in Sandboxie plus does not help

I also tried Sandboxie classic 5.40.1 that ist the first one to include the fix and it does not help.
Also using a Sandbox without isolation did not help.

Installing outside of a Sandbox runs fine.

This is the exact message I am getting:
![Sandboxie Windows Installer](https://user-images.githubusercontent.com/14862324/207988511-2191f073-06f7-4655-a836-7d461a31b1be.PNG)
Edit: The error message from the screenshot so it can be searched for if others face the same problem: `The Windows Installer Service could not be accessed. This can occur if you are running Windows in safe mode, of if the Windows Installer is not correctly installed. Contact your support personnel for assistance.`

### Affected program

Audials Music 2022 Special Edition by Computer Bild

### Download link

https://www.computerbild.de/download/Audials-Music-2022-Kostenlose-Spezial-Version-32181841.html

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

I'd expect the installer to run successfully as many others do and not abort with an error message without finishing installing.

### What is your Windows edition and version?

Windows 10 enterprise 21h2 LTSC, Windows Server 2016 Datacenter, Windows 8.1 Pro

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender Antivirus, Windows Firewall Control

### What version of Sandboxie are you running?

Sandboxie Classic 5.60.3, Sandboxie-Plus v1.5.1, Sandboxie Classic 5.40.1

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by offhub** [comment]
You could try with the following:
```
MsiInstallerExemptions=y
```

(`Plus UI` > `Sandbox Options` > `Security Hardening` > `Elevation restrictions` >> `Allow MSIServer to run with a sandboxed system token and apply other exceptions if required`)

But I couldn't run it without the following:
```
NoSecurityIsolation=y
```

Windows 10 22H2

**Comment by MichaelDietzel** [comment]
Thanks a lot! I can confirm this works despite Sandboxie showing some warnings. Sorry for not finding the option myself. But maybe having this error message documented here will help others find this solution.
