### ISSUE TITLE
Steam won't start

### ISSUE THREAD

**Issue by Nietod** [sandboxie-plus/Sandboxie#2540]
### Describe what you noticed and did

Steam and other programs won't start. I always get Access Denied (5). Some programs work others including steam won't. And I'm not talking about a certain game. I'm talking about the steam launcher itself.

### Affected program

Steam

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

It starts like it should

### What is your Windows edition and version?

Windows 10 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Kaspersky Total Security

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by TFWol** [comment]
You should probably give them a log or something. Your issue is very vague.
Also might want to fix your win10 version.
You probably meant 22H2.

Just a side note, but I receive no such error when I run Steam on 22H2 with the same sandbox type.

**Comment by isaak654** [comment]
I agree with the previous post.

Other things that could be useful to locate the issue:
1. providing your Sandboxie.ini configuration file
2. uninstalling temporarily Kaspersky Total Security - if this works for your issue, then it is recommended to contact Kaspersky's [Technical Support](https://www.kaspersky.com/about/contact)

**Comment by isaak654** [comment]
I agree with the previous post.

Other things that could be useful to locate the issue:
1. providing your Sandboxie.ini configuration file
2. uninstalling temporarily Kaspersky Total Security - if this works for your issue, it is recommended to contact Kaspersky's [Technical Support](https://www.kaspersky.com/about/contact)

**Comment by isaak654** [comment]
I agree with the previous post.

Other things that could be useful to locate the issue:
1. provide your Sandboxie.ini configuration file
2. uninstall temporarily Kaspersky Total Security - if this works for your issue, it is recommended to contact Kaspersky's [Technical Support](https://www.kaspersky.com/about/contact)

**Comment by Nietod** [comment]
changed nothing...worked after few days
