### ISSUE TITLE
[5.61.2 x86] SBIE2205 Service not implemented:  Wow64FunctionTurboThunkControl C00000BB

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2546]
_Originally posted by @marcinkit in https://github.com/sandboxie-plus/Sandboxie/discussions/2542#discussioncomment-4452072_

> Sandboxie classic 5.61.2 on win10;
> 
> SBIE2205 Service not implemented:  Wow64FunctionTurboThunkControl C00000BB
> 
> reverted to Sandboxie-Classic-x86-v5.59.2 which is the last release which is trouble free, error free.

A similar issue was already reported in past:
https://www.wilderssecurity.com/threads/sandboxie-plus-v1-5-0-v1-5-1-v1-5-2.448352/page-4#post-3113578

> Windows v10.0.18362.356 (32-bit), Sandboxie v5.60.2, Firefox v106.0.3. When I start Firefox sandboxed I get a bunch of "SBIE2205 Service not implemented: Wow64FunctionTurboThunkControl C00000BB" messages and then when I close/terminate too. Security software: Windows Defender

**Comment by DavidXanatos** [comment]
fixed in 1.6.2b
