### ISSUE TITLE
Shortcut icon from .lnk file not displayed anymore

### ISSUE THREAD

**Issue by DaneXtream** [sandboxie-plus/Sandboxie#2552]
### Describe what you noticed and did

Basically I had all sandboxes with a double-click action set to a shortcut:

`DblClickAction="V:\PortableApps\Brave.lnk"`

The icon was displayed in Sandboxie-Plus 1.6.1, but not anymore in 1.6.2.
The sandbox type does not matter.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The shortcut icon should be displayed.

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.6.2 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
in 1.6.2 the icon mechanism was changed to allow to specify arbitrary icons
you can set the icon on the general page of the box options:
![grafik](https://user-images.githubusercontent.com/3890945/208851535-b1cbf9f2-7ce0-46b2-a8d2-ffe7fe412ea6.png)

also when selecting a double click action the icon will be auto set

**Comment by DaneXtream** [comment]
Yes, I read the change log for 1.6.2, but... there was a different kind of behaviour in 1.6.1.

If one does not check the "Custom icon" thing, then the default icon should be taken from DblClickAction, if any.

Am I right?
