### ISSUE TITLE
Cant complie Sandboxie Plus

### ISSUE THREAD

**Issue by kyrahm** [sandboxie-plus/Sandboxie#2562]
### Describe what you noticed and did

Cant complie Sandboxie Plus. Windows Driver Kernel Kit is installed. Visual Studio 2022.
Text errors:
Cant include ntfs.h: No such file or directory (box.c)
Cant include ntfs.h: No such file or directory (api.c)
Cant include ntfs.h: No such file or directory (conf.c)
Cant include ntfs.h: No such file or directory (conf_expand.c)
Cant include ntfs.h: No such file or directory (dll.c)
Cant include ntfs.h: No such file or directory (conf_user.c)
Cant include ntfs.h: No such file or directory (driver.c)
Cant include ntfs.h: No such file or directory (file.c)
Cant include ntfs.h: No such file or directory (file_xlat.c)
Cant include ntfs.h: No such file or directory (gui.c)
Cant include ntfs.h: No such file or directory (ipc.c)
Cant include ntfs.h: No such file or directory (ipc_sam.c)
Cant include ntfs.h: No such file or directory (ipc_spl.c)
Cant include ntfs.h: No such file or directory (ipc_port.c)
Cant include ntfs.h: No such file or directory (ipc_lsa.c)
Cant include ntfs.h: No such file or directory (key.c)
Cant include ntfs.h: No such file or directory (obj.c)
Cant include ntfs.h: No such file or directory (mem.c)
Cant include ntfs.h: No such file or directory (process.c)
Cant include ntfs.h: No such file or directory (process_force.c)
Cant include ntfs.h: No such file or directory (process_api.c)
Cant include ntfs.h: No such file or directory (process_low.c)
Cant include ntfs.h: No such file or directory (process_util.c)
Cant include ntfs.h: No such file or directory (session.c)
Cant include ntfs.h: No such file or directory (syscall.c)
Cant include ntfs.h: No such file or directory (log_buff.c)
Cant include ntfs.h: No such file or directory (thread.c)
Cant include ntfs.h: No such file or directory (verify.c)
Cant include ntfs.h: No such file or directory (util.c)
Cant include ntfs.h: No such file or directory (wpf.c)
Cant include ntfs.h: No such file or directory (token.c)

### Affected program

Not relevant

### Download link

Not available

### Where is the program located?

Not relevant to my request.

### Expected behavior

-

### What is your Windows edition and version?

Windows 11

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

-

### What version of Sandboxie are you running?

-

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
you need to install a compatible WDK https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
since you are using VS 2022 go for 10.0.22621.0
also note that this WDK can not compile drivers for windows 7 only 8+ so you should go to the project settings of the driver and set the target platform to win 10

If you want to compile for windows 7 use a WDK < 10.0.22000 but than you will need VS 2019 as the older WDK's are note compatible with vs 2022

**Comment by isaak654** [comment]
#1420
