### ISSUE TITLE
How to configure capacity to monitor keyboard/mouse input for only selected programs?

### ISSUE THREAD

**Issue by NJT145** [sandboxie-plus/Sandboxie#2567]
### Is your feature request related to a problem or use case?

No i dont think it is a problem

### Describe the solution you'd like

While I am running programs in a sandbox, I see that I cannot use shortcut input to do something that this program configures.
For example, I am running an app that starts/stops video play when pressing ALT+SPACE, but I cannot do it because app is installed in sandbox and it cannot see my ALT+SPACE command.
What I need is to do is to give access to keyboard inputs for only that programs.
Is there a way to do that?

**Comment by offhub** [comment]
You could try with `Application Compartment (NO Isolation)` type sandbox. (`NoSecurityIsolation=y`, which requires a supporter certificate otherwise box will be terminated after 5 minutes.)

**Comment by okrc** [comment]
Add
`OpenWinClass=*`
?

**Comment by offhub** [comment]
That setting works too. If the application has a system tray icon, it will not appear in the systray. [*](https://github.com/sandboxie-plus/Sandboxie/issues/192#issuecomment-764214525) [**](https://github.com/sandboxie-plus/Sandboxie/issues/192#issuecomment-726136814)

**Comment by okrc** [comment]
> it will not appear in the systray.

@offhub I'm under the impression that older versions didn't have this problem (not sure). The tray works fine in `Windows Sandbox`.

**Comment by offhub** [comment]
@okrc

https://user-images.githubusercontent.com/6871698/209811225-cdc4cb42-7f8a-429e-947c-4cf8d9411619.mp4

**Comment by okrc** [comment]
@offhub 可能因为翻译产生了误解。

在 v1.6.3 添加`OpenWinClass=*`确实会造成系统托盘不显示。我并没有否认这个问题存在。但它会在`Windows Sandbox`中显示。

There may be misunderstandings due to translation.
Adding `OpenWinClass=*` in v1.6.3 does cause the systray to not show up. I'm not denying that this problem exists. But it will show up in `Windows Sandbox`.

**Comment by NJT145** [comment]
I remember that `OpenWinClass=*` will also let access to folders outside of sandbox. And that is what I don't want because files in sandbox are different then files outside sandbox.
Another thing is that I want to allow access for only one program, and not all programs in sandbox.

**Comment by DavidXanatos** [comment]
OpenWinClass=* has no impact on file access, but a sandboxed application will be able to send mouse and keyboard commands to other windows on the desktop so its a security issue.
I don't see how this could break tray but will investigate it.

What @NJT145 requests is a support for global hot keys this is doable just a bit work, so it wont be in any time soon unless some higher tier patreon request it.

**Comment by DavidXanatos** [comment]
with recent sbie versions i cant reproduce the tray issue also we have a hotkey support request issue already https://github.com/sandboxie-plus/Sandboxie/issues/192 so I'll close this one
