### ISSUE TITLE
MSEdge cannot be opened in the hardened sandbox of Windows 11 22H2.

### ISSUE THREAD

**Issue by okrc** [sandboxie-plus/Sandboxie#2571]
### Describe what you noticed and did

MSEdge cannot be opened in the hardened sandbox of Windows 11 22H2.

### Affected program

MS Edge 108.0.1462.54 64-bit

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Not relevant

### What is your Windows edition and version?

Windows 11 Pro 22H2 (22621.963) 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus 1.6.3 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
It works with Win11 22H2 on VM. Are you trying to run it from the shortcut? If so:

```
NormalFilePath=Start.exe,|%UserProfile%\Desktop\*.lnk
```

**Comment by okrc** [comment]
> NormalFilePath=Start.exe,|%UserProfile%\Desktop\*.lnk

I start it from the SandMan right click menu, even `msedge.exe` under `Program File` doesn't start.

```
MSEdge Version: 108.0.1462.54 64-bit
Windows Version: 22621.963
```
*Doesn't work only in hardened sandbox*

**Comment by offhub** [comment]
May bad, you wrote in the report `Security Hardened Sandbox` (orange) and tested with `Hardened Sandbox with Data Protection` (red)... You are right, with the orange box it doesn't open.

**Comment by offhub** [comment]
On my tests, it affects both boxes. Reloading the configuration with `Reload ini file` or restarting the GUI fixes the problem for me. Probably something to do with syscall settings not being applied at first start.

`- reloading the configuration with the SandMan command "Options -> Reload ini file" now updates the list of approved syscalls`

**Comment by okrc** [comment]
> On my tests, it affects both boxes. Reloading the configuration with `Reload ini file` fixes the problem for me. Probably something to do with syscall settings not being applied at first start.
> 
> `- reloading the configuration with the SandMan command "Options -> Reload ini file" now updates the list of approved syscalls`
> 
> EDIT:
> 
> **To reproduce it:** `SandMan `> `Sandbox `> `Maintanence `> `Stop All `> `Delete Sandboxie.ini` > `Maintanence `> `Connect `> `Create a new Orange/Red box` > `Try to run anything on it`

I can't get help from these hints. because I can't run it.

However, I found a solution, adding `WriteFilePath=msedge.exe,%UserProfile%` before the first launch of the empty security hardening sandbox can run successfully.

**Comment by offhub** [comment]
Is this problem happening on the host/real system or `Windows Sandbox`?

**Comment by okrc** [comment]
> Is this problem happening on the host/real system or `Windows Sandbox`?

host/real system

**Comment by DavidXanatos** [comment]
So issue https://github.com/sandboxie-plus/Sandboxie/issues/2574 os fixed,
but we still have issues with the red box, unless we open some extra paths right?

**Comment by okrc** [comment]
@DavidXanatos it only happens in orange sandbox.

**Comment by DavidXanatos** [comment]
for me booth orange and red boxes work fine

**Comment by okrc** [comment]
I also can't reproduce it under a clean virtual machine, I have now closed this issue.

**Comment by offhub** [comment]
MSEdge crashes when I click the `three-dot menu button`. Same VM (Win11 22H2) and MSEdge version. 🤔 **See Video 1**

Fix: `ApproveWinNtSysCall=QueryWnfStateData` **See Video 2**

**Video 1:** crash

https://user-images.githubusercontent.com/6871698/210152399-080db45d-d074-4f7e-9377-c954023a4490.mp4



**Video 2:** fix

https://user-images.githubusercontent.com/6871698/210152404-ce3060c1-d57a-4f2a-83c1-9ab3076f7a41.mp4

**Comment by offhub** [comment]
Tested on clean VMs:

- Windows 11 22H2 (22621.963, December updates) and Microsoft Edge Version 108.0.1462.54 (Official build) (64-bit):
    Crashes every time i click on the `three-dot menu button` without `QueryWnfStateData`.

- Windows 11 21H2 (22000.1335, December updates) and Microsoft Edge Version 108.0.1462.54 (Official build) (64-bit):
    Crashes every time i click on the `three-dot menu button` without `QueryWnfStateData`.

- Windows 10 22H2 (19045.2364, December updates) and Microsoft Edge Version 108.0.1462.54 (Official build) (64-bit):
    No crash (**NOT**: The freezes/crashes I encountered while testing on my own system were probably caused by the `AllowBoxedJobs=y` setting.)

- Windows 10 21H2 (19044.2364, December updates) and Microsoft Edge Version 108.0.1462.54 (Official build) (64-bit):
    No crash

**Comment by DavidXanatos** [comment]
thx fix will be added to next build
