### ISSUE TITLE
Load startup item function

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#2586]
### Is your feature request related to a problem or use case?

This function enables the program installed in the sand table to be automatically started when starting the program in the sand table

### Describe the solution you'd like

Add the function of "Start Auto Startup Item" or "Load Auto Startup Item" to the right-click menu of the sand table

**Comment by offhub** [comment]
You can try these settings to see if they meet your needs:

1. (Box only run menu entry) `Sandboxie Plus` > `Right clik on the sandbox` >`Sandbox Options` > `General Options` > `Run Menu` > `Add program`
2. (Global run menu entry) `Sandboxie Plus` > `Options` > `Interface Config` > `Run Menu` > `Add program`
3. (Triggers) `Sandboxie Plus` > `Right click on the Sandbox` >`Sandbox Options` > `Advanced Options` > `Triggers`:

    - `On Box Init` (Triggers when a program is executed in an _empty_ sandbox.)

    - `On Box Start` (Triggers when a program is executed if there are no other programs running in the sandbox.)
    
    Also you can manually execute triggers using:
       `Sandboxie Plus` > `Right click on the Sandbox` > `Run` > `More Tools` > `Execute Autorun Entries`

**Comment by Taeyeonzpx** [comment]
> 3\. `Sandboxie Plus` > `Right click on the Sandbox` > `Run` > `More Tools` > `Execute Autorun Entries`

oh, thank you. It seems that this is the function I want. It implements the function I want to load startup items. But can they move to the previous menu?

**Comment by Taeyeonzpx** [comment]
> 3\. `Sandboxie Plus` > `Right click on the Sandbox` > `Run` > `More Tools` > `Execute Autorun Entries`

oh, thank you. It seems that this is the function I want. It implements the function I want to load startup items. But can they move to the previous menu?

**Comment by DavidXanatos** [comment]
you mean like this:
![grafik](https://user-images.githubusercontent.com/3890945/210347915-0c8cc024-23f6-4a1c-8d2d-105f85ff2dbe.png)

ok i can change it this way

**Comment by DavidXanatos** [comment]
you mean like this:
![grafik](https://user-images.githubusercontent.com/3890945/210390526-743f4052-3a32-4eee-8346-399641b7e128.png)

**Comment by Taeyeonzpx** [comment]
> you mean like this: ![grafik](https://user-images.githubusercontent.com/3890945/210390526-743f4052-3a32-4eee-8346-399641b7e128.png)
> 
yes, that's what I mean. I think this function is commonly used and should be placed in a prominent position

**Comment by DavidXanatos** [comment]
it has ben moved in the recent builds already
