### ISSUE TITLE
How to upgrade from classic Sandboxie?

### ISSUE THREAD

**Issue by HerrBert233** [sandboxie-plus/Sandboxie#259]
Hi,

what is the correct upgrade procedure when still having the classic Sandboxie installed (v5.33.1)? Can settings and sandboxes be migrated?

Best,
Herbert

**Comment by DavidXanatos** [comment]
First make a backup of your C:\windows\sandboxie.ini just in case

Than uninstall old sandboxie and when prompted opt for keeping the sandboxie.ini

Than install sandboxie plus release, it will use the existing sandboxie.ini with all the settings and configurations.

**Comment by isaak654** [comment]
#1810

**Comment by isaak654** [comment]
#1821
