### ISSUE TITLE
Game crashes after 2 hours

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#2590]
### Describe what you noticed and did

Added folders and exe of Steam and Team Fortress 2 to sandbox Direct access, there was a crash after 2 hours. Deleted folders and exe from sandbox Direct access, added these folders to Full access. In full access there was a crash in 5 hours. If add folders and exe Steam and Team Fortress 2 in both direct and full access will this solve the problem with crashes like hl2.exe and steamerrorreporter.exe?

### How often did you encounter it so far?

-

### Affected program

Steam, Team Fortress 2

### Download link

Free to Play: https://store.steampowered.com/app/440/Team_Fortress_2/

### Where is the program located?

Not relevant to my request.

### Expected behavior

No crashes.

### What is your Windows edition and version?

Windows 10 LTSC 2021 x64

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Avast Premium Security

### What version of Sandboxie are you running?

5.40 x64 (the same happens with Plus 1.6.4)

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

5.40 x64

### In which sandbox type you have this problem?

Standard isolation sandbox.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

-

### Crash dump
Dumps of hl2.exe :
https://pastebin.com/QehiZvMn
https://pastebin.com/VGLNveTQ
Dump of steam.exe :
https://pastebin.com/qY4mWt67
Dump of steamwebhelper.exe : 
https://pastebin.com/CbpS9p9V

### Trace log

-

### Sandboxie.ini configuration

```
#
# Sandboxie configuration file
#

[GlobalSettings]
DefaultBox=1
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=RTSS
Template=OfficeLicensing
Template=Edge_Fix
Template=Avast_Antivirus
Template=7zipShellEx

[UserSettings_2E140420]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[1]
Enabled=y
BlockNetworkFiles=y
BorderColor=#00ff55,on,6
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=9
BoxNameTitle=y
CopyLimitKb=-1
AutoDelete=y
OpenPipePath=C:\Steam
OpenPipePath=C:\Steam\steamapps\common\Team Fortress 2
OpenPipePath=C:\Steam\steamapps\common\Team Fortress 2\hl2.exe
OpenPipePath=C:\Steam\steam.exe
OpenPipePath=C:\Steam\steamerrorreporter.exe
OpenPipePath=C:\Steam\steamerrorreporter64.exe
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
```

```shell
Added folders and files first to Direct access, then to Full access.
Dont transfer files with a size of 1 KB. The value 0 isnt set.
```

**Comment by offhub** [comment]
Can you upgrade Sandboxie to latest version (5.61.4) as the version you are using (5.40?) is quite old?

[https://github.com/sandboxie-plus/Sandboxie/releases](https://github.com/sandboxie-plus/Sandboxie/releases)

**Comment by isaak654** [comment]
The report is still incomplete.

1. Is it a 32-bit or a 64-bit system?
2. Is it Windows 10 LTSC _2021_? If different, please specify.
3. Can you explicitly confirm that no crash dump files (*.dmp) were found with a global search in the system (including sandboxed locations)?
4. Considering you've already reproduced the issue on a new empty sandbox, please attach your [GlobalSettings] lines in Sandboxie.ini.

**Comment by isaak654** [comment]
If you attach also the crash dump (provided it was obtained with [Plus v1.6.4](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.6.4)), I could pin this issue to keep it relevant for a while.

**Comment by isaak654** [comment]
Those links will expire in a month and it is not certain that David will look at them in time.

1. If they are not too heavy, I would suggest to zip the .dmp files and attach them in this issue: 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
2. Alternatively, you can also send the .dmp files by [email](https://xanasoft.com/contact/).

**Comment by isaak654** [comment]
According to [this post](https://forum.xanasoft.com/threads/sandboxie-classic-x64-v5-55-8-hl-exe-crashes-and-steam-exe-follows.255/post-1616), the issue has already been fixed:

> Finally i reached windows 10 with Sandboxie-Classic-x64-v5.66.4.exe and now all runs fine. :)
