### ISSUE TITLE
Sandboxie error message "Access denied (5)"

### ISSUE THREAD

**Issue by IDragonheartI** [sandboxie-plus/Sandboxie#2597]
### Describe what you noticed and did

I wanted to start any program in my installed Sandboxie version, but no matter with any "sandboxes" or settings there is the same error message (refer to link)

I tried several versions (newest classic and pro version and 1.4.1 of Sandboxie Plus)
I also tried to give admin rights to the box and add my .exe to the direct access list.

![hh](https://user-images.githubusercontent.com/122385210/211608186-d651a253-f66b-49c2-acd0-ab70ab6678e8.JPG)

It means something like "SBIE 1231 Initialization failed for process [C0000038 / 66]
system error
access denied (5)

### How often did you encounter it so far?

every time I tried it with different Versions

### Affected program

Not relevant, every .exe

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

I expected to see any program start inside the sandbox, but theres just "ACCESS DENIED"

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-Bit  (Version 10.0.19044 Build 19044)

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Kaspersky Internet Security without license

### What version of Sandboxie are you running?

Sandboxie Plus 1.6.4 (but tried with older versions too)

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

since Sandboxie 1.4.1 at least

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Nothing

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
FileRootPath=E:\DESKTOP\Sandbox\%SANDBOX%
NetworkEnableWFP=y
DefaultBox=DefaultBox
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Microsoft_MSMQ
Template=Kaspersky
Template=Edge_Fix
Template=AdobeAcrobatReader
Template=7zipShellEx
FakeAdminRights=y

[UserSettings_083E01A7]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=n
FakeAdminRights=n

[steam1]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=n
FakeAdminRights=y
```

**Comment by DavidXanatos** [comment]
this is a very strange issue,
with the MSG1231 i can pinpoint the issue to be related to early process initializationa round console set up,
howeever i could nto reproduce this issue neider on 19043.1682 nor 19045.2364
I don't have a vm with build 19044 on hand.
Could you please try updating your windows to build 19045 and let me know if this fixed the issue.
Although that would be strange ig only this eine build would have a problem.
An other potential source of problems here may be some other 3rd party security software which also messes with early process creation. Are you using anything that sort?

**Comment by isaak654** [comment]
@DavidXanatos 
As mentioned in OP, the user installed a trial version of Kaspersky Internet Security. 
Assuming it is the latest one, you can download it from  [here](https://www.kaspersky.com/downloads/internet-security-free-trial#download).

**Comment by DavidXanatos** [comment]
I tried this right now and did not notice any conflicts on 19045

**Comment by ZeChArtiahSaher** [comment]
same issue no clue as to what it is

**Comment by Nitrex69** [comment]
This problem fixes itself by sandboxing its own txt file (DONT-USE.txt) i haven't confirmed whether this is the solution or not since ive had the same problem with sandboxie constantly outputting "Program could not be invoked Access is denied [5]", but it appears one action made by accident fixes it

**Comment by Nitrex69** [comment]
You may also have to add more permissions to sandman.exe, well that's exactly what I did yesterday so perhaps the both "fixes" work hand-in-hand

**Comment by bierdosenhalter** [comment]
i have the same problem

**Comment by MagicJinn** [comment]
I was getting this error when running an exe from a remove network drive. Once I copied it to C it worked fine. Very strange.

**Comment by PembaTamang** [comment]
Same issue on the latest version 1.15.3 / 5.70.3. I also have Kaspersky installed.
Nothing seems to run

SBIE1231 Initialization failed for process Android_Multi_Tool_v1.2.9.1.exe [C0000038 / 66]
SBIE1231 Initialization failed for process Android_Multi_Tool_v1.2.9.1.exe [C0000001 / A8]
SBIE2314 Cancelling process Android_Multi_Tool_v1.2.9.1.exe
SBIE1231 Initialization failed for process Android_Multi_Tool_v1.2.9.1.exe [C0000038 / 66]
SBIE1231 Initialization failed for process Android_Multi_Tool_v1.2.9.1.exe [C0000001 / A8]
SBIE2314 Cancelling process Android_Multi_Tool_v1.2.9.1.exe
![image](https://github.com/user-attachments/assets/9aac677d-1834-4500-8783-c1adaf7daa85)
