### ISSUE TITLE
[Plus 1.6.5] Cleanup button in Sandman has stopped working after clicking a second time

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2599]
### Describe what you noticed and did

Start Sandman
Click on the Cleanup button 
wait ~5s
Click again

![Cleanup_button](https://user-images.githubusercontent.com/12372772/211665684-97ff75e1-20e0-4395-9fc7-d7f649d05297.png)

### How often did you encounter it so far?

everytime

### Affected program

sandman.exe

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

No issues ┐(ﾟ～ﾟ)┌   

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Sandboxie-Plus Version: 1.6.5 (5.61.5) 64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by offhub** [comment]
I can confirm this issue as well with `Cleanup` or `Cleanup Trace Log`.

**Comment by isaak654** [comment]
I have just had a BSOD with Plus 1.6.5 x64 after clicking the menu `Options -> Reload ini file`:
![W7_crash_with_1.6.5](https://user-images.githubusercontent.com/12372772/211656835-849bea3c-c91b-472f-aa83-c1694b6b74b7.png)

This was on my W7 SP1 x64 VM. 
Considering I cannot reproduce it anymore, I also provided a kernel memory dump of over 200 MB to @DavidXanatos via Slack.
