### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by nulledone** [sandboxie-plus/Sandboxie#26]
I generally use sandboxie as a container for specific apps that I want to make portable. It works like a charm but some feedback may help you make everything better. Since it became open source I'm very happy that wonderful people are trying to improve this program. 

For better tracking of these, you can close this issue and make seperate for each of them. 

1. Spoof computer info (like username and basic stuff)
2. Option to Act like stock windows: Apps launched in sandbox think it is a fresh install, hence they won't see any other thing on the computer. 
3. Support (unify) for customized user files location: When a stock user folder (my pictures/documents etc) moved outside of sandbox, gather writes onto that folder into "SANDBOX/user" instead of "SANDBOX/drive/d/customuserfolder/custom" 
4. Show active COM and IPC while adding COM/IPC access to Sandbox.
5. Ability to check writes to registry made inside sandbox
6. Rework file mitigation, this causes a lot of issues when using game setups etc.
7. Make context menu better: Maybe make a tree under run sandboxed. Also run unsandboxed tweak must be added to the app ( there's a registry about it).
8. Sandbox only user files' access: granting full access to everything but user files.
9. Interface rework: this one is probably in the works.
10. Steam Sandbox: for running two instances or another special use cases.
11. Temp Sandbox: Every change is deleted when the app is closed. 

I also would like to thank everyone who is contributing to this program.

**Comment by DavidXanatos** [comment]
1. I already had that on my todo
2. same
3. ok
4. was an my todo
5. ??? please explain
6. ??? please explain
7. you mean like this:
![image](https://user-images.githubusercontent.com/3890945/82759565-8fe2bc80-9dee-11ea-8f98-fa75085a7400.png)
8. was also on my todo
9. yes it is as you can see at point 7 :D
10. ??? please explain
11. I think there is already a setting for that

btw: here is my roadmap: https://www.wilderssecurity.com/threads/sandboxie-plus-sbie-fork.427755/#post-2909567

**Comment by nulledone** [comment]
5- Basically 'regedit' but that will show differences in the sandbox meaning which shows registry keys that have changed.


6-I think this is about game repacks where the archiver use temporary windows folder and cause issues while writing files. Also while writing large files app warns about mitigating then to sandbox is failed since size is above 10.mb (default) I don't remember what was the original issue so you may disregard if you don't have anything in your mind


7-I was meaning right clicking on a file or folder normally, there's only one button that pops up and makes you choose your sandbox. I think instead of this we can make that button like tree.


9-that UI looks very well, thanks for your contribution. I am looking forward for remake.


10- A sandbox that is optimized for Steam since it updates itself everytime it ran under sandbox,but after seeing your roadmap I can see that this can be implemented under Plug-ins and Scripting.


11-That setting as far as I know applies to all sandboxes not a chosen one.

**Comment by deflock** [comment]
> btw: here is my roadmap: https://www.wilderssecurity.com/threads/sandboxie-plus-sbie-fork.427755/#post-2909567

You serious? Are you planning to release a first alpha version before 2030? 😂😅
