### ISSUE TITLE
PDF-XChange Editor / Editor Plus installation aborted

### ISSUE THREAD

**Issue by greatsteins** [sandboxie-plus/Sandboxie#2602]
### Describe what you noticed and did

1. Download [64 bit MSI Installer](https://www.tracker-software.com/product/pdf-xchange-editor/download?fileid=695) or [Zipped EXE Installer(32/64 bit)](https://www.tracker-software.com/product/pdf-xchange-editor/download?fileid=686)
2. Install either the MSI or EXE, with or without UAC permission.
3. Installation aborted with error 2203
![aborted](https://user-images.githubusercontent.com/122541831/212119327-88f840d7-bbb7-4a62-8973-2428414dd1ee.png)

### How often did you encounter it so far?

Whenever I proceed the installation

### Affected program

PDF-XChange Editor installer

### Download link

https://www.tracker-software.com/product/pdf-xchange-editor/download?fileid=695

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

Complete the installation process.

### What is your Windows edition and version?

Windows 8.1 64 bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Kaspersky Internet Security

### What version of Sandboxie are you running?

Sandboxie Classic 5.61.4

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than v1.5.3 / 5.60.3.

### Is it a regression?

Sandboxie-Classic-x64-v5.57.7 had also happened, not sure if it happened in earlier versions or not.

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
Most likely an error occurred during printer driver installation. Try moving the error window to the side so you can see what it was processing when it stopped.

You could try with the following setting:
(Sbie > Configure > Edit Configuration: Copy and paste under your box settings. Ex. [DefaultBox])

> **Note**: Msi Installer Exemptions should not be required, but if you encounter issues installing a msi package which you trust, this option may help the installation complete successfully. You can also try disabling drop admin rights.

```
MsiInstallerExemptions=y
```


**Optional**:
```
FakeAdminRights=y
```

> **Note**: The program may crash when using the print features!

**Comment by greatsteins** [comment]
> Most likely an error occurred during printer driver installation. Try moving the error window to the side so you can see what it was processing when it stopped.
> 
> You could try with the following setting: (Sbie > Configure > Edit Configuration: Copy and paste under your box settings. Ex. [DefaultBox])
> 
> > Note: Msi Installer Exemptions should not be required, but if you encounter issues installing a msi package which you trust, this option may help the installation complete successfully. You can also try disabling drop admin rights.
> 
> ```
> MsiInstallerExemptions=y
> ```
> 
> **Optional**:
> 
> ```
> FakeAdminRights=y
> ```
> 
> > Note: The program may crash when using the print features!

MsiInstallerExemptions=y

This works.

The installation proceeded with above setting alone.
It still works with "Drop admin rights" & "FakeAdminRights=y" on.

Returning to the original setting, the installer did not show which step was interrupted, but probably as you said about the printer installation.
![H1](https://user-images.githubusercontent.com/122541831/212249433-f1419844-ed64-4a60-8dd5-be5f2ed0279e.png)

Thanks for the help.
