### ISSUE TITLE
Not possible to empty sandbox which contains symlink

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#2606]
### Describe what you noticed and did

It is not possible to empty (Delete Content/Remove Sandbox) sandbox which contains symlink. All other files are removed but symlink stays and makes it unable to empty sandbox folder.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Expected behavior is to make it possible to empty sandbox which contains symlink.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

User account with UAC protection completely turned off.

### Please mention any installed security software

Microsoft Security Essentials

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DaneXtream** [comment]
I've seen a similar behaviour with Windows Explorer if you copy/move/delete a folder which contains directory junctions or symbolic links, so it may not be Sandboxie's fault here...

**Comment by Mitch037** [comment]
> I've seen a similar behaviour with Windows Explorer if you copy/move/delete a folder which contains directory junctions or symbolic links, so it may not be Sandboxie's fault here...

I cannot confirm this (Win7x64). A moment ago I created a new folder and put a symlink there and had no problem with deleting it. The only time I encounter the issue is when a symlink is created within a Sandboxie sandbox folder(s).

**Comment by DavidXanatos** [comment]
I cant reproduce the supposed inability of sandman to delete a box containing symlinks, please provide a step by step guide to reproduce.

**Comment by offhub** [comment]
Something like this:


https://user-images.githubusercontent.com/6871698/216631400-d707fec7-4c22-4aad-813e-6c86b4643540.mp4
