### ISSUE TITLE
The EnumServicesStatusW API is very slow.

### ISSUE THREAD

**Issue by RisingYoung-Learn** [sandboxie-plus/Sandboxie#2607]
### Describe what you noticed and did

1. I found that the CATIA application started slowly in Sandbox. Through the ProcMon tool, I found that calling the EnumServicesStatus interface was slow;
2. I wrote a C++console program that calls the EnumServicesStatusW interface ten times and counts the total time. The code is as follows:

#include<windows.h>
#include<winsvc.h>

#include<iostream>
#include<cstdio>
#include <chrono>

int main(int argc, char* argv[])
{
auto start = std::chrono::duration_ cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_ since_ epoch()).count();
for(size_t idx = 0; idx < 10; ++idx)
{
DWORD ret = 0;
DWORD size = 0;
LPENUM_ SERVICE_ STATUS st = (LPENUM_SERVICE_STATUS)LocalAlloc(LPTR, 64 * 1024);
SetLastError(0);
SC_ HANDLE sc = OpenSCManager(NULL, NULL, SC_MANAGER_ALL_ACCESS);
DWORD errCode = GetLastError();
if (NULL == sc)
{
std::wcout << "OpenSCManager error code:" << errCode << std::endl;
continue;
}
else
{
std::wcout << sc << errCode << std::endl;
}
SetLastError(0);
BOOL status = EnumServicesStatus(sc, SERVICE_WIN32, SERVICE_STATE_ALL, (LPENUM_SERVICE_STATUS)st, 1024 * 64, &size, &ret, NULL);
errCode = GetLastError();
if (FALSE == status)
{
std::wcout << "EnumServicesStatus error code:" << errCode << std::endl;
continue;
}
for (int i = 0; i < ret; i++)
{
wprintf(TEXT("Count %d ---> "), i);
wprintf(TEXT("%-20s%-50s"), st[i].lpServiceName, st[i].lpDisplayName);
switch (st[i].ServiceStatus.dwCurrentState)
{
case(SERVICE_RUNNING):
std::cout << "running" << std::endl;
break;
case(SERVICE_STOPPED):
std::cout << "stopped" << std::endl;
break;
}
}
}
auto end = std::chrono::duration_ cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_ since_ epoch()).count();
std::cout << "Sum time: " << end - start << " (ms)." << std::endl;
system("pause");
return 0;
}

3、
Sandboxie operation results are as follows:
![2](https://user-images.githubusercontent.com/54743518/212535658-740e2577-92dd-489b-9952-dd4ea86ae971.png)

The results of direct operation are as follows:
![1](https://user-images.githubusercontent.com/54743518/212535668-50ae85b9-f5ef-4264-baa6-8d2734b95e7c.png)

### How often did you encounter it so far?

Appears every time you use.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Functions such as EnumServicesStatusA/W and EnumServicesStatusExA/W need to improve efficiency. The efficiency loss of direct operation on the operating system is less than one time that of Sandbox.

### What is your Windows edition and version?

Windows 10 21H1 and Windows Server 2016 1607

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie plus 1.6.3 64 

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]

[UserSettings_4BC00582]
SbieCtrl_AutoStartAgent=SandMan.exe

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by DavidXanatos** [comment]
Sandboxie, due to its many restrictions needs to proxy various operations through its service component, hence some additional delays are sometimes unavoidable. That said a slow down by factor 7 is really a lot, hence I'll take a look into this if it can be improved.
