### ISSUE TITLE
Problem displaying sandbox settings in the Hebrew language

### ISSUE THREAD

**Issue by htht2001** [sandboxie-plus/Sandboxie#2608]
### Describe what you noticed and did

![image](https://user-images.githubusercontent.com/97393694/212540371-e0f686f2-de81-4ace-86f8-b97a23bc4a56.png)
It's a problem because of the alignment to the right
It is not possible to use the settings in this way

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Option to use sandbox settings

### What is your Windows edition and version?

Windows 10 - Windows srver 2022

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET Endpoint Antivirus

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.61.4 - Sandboxie-Classic-x64-v5.61.5

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by bastik-1001** [comment]
Did you use Sandboxie Classic at any point, since it went open source? I'm just curious whenever there was a version that ever worked for you.

**Comment by htht2001** [comment]
No, now I'm using it for the first time

**Comment by isaak654** [comment]
Please uninstall the current version without leaving traces and report back if the issue is still present after installing version [5.49.5](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.7.3).

**Comment by isaak654** [comment]
Forget about my previous request. 
After installing Hebrew as display language in Windows 10 21H2 x64, I tried a number of Classic releases:

[5.49.5](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.7.3) = right to left not working
[5.48.0](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.7.0) = not working
[5.47.1](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.6.7) = working
[5.46.4](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.5.5) = working

So the regression happens for the first time in Classic 5.48.0... 45 commits of difference to check than version 5.47.1:
https://github.com/sandboxie-plus/Sandboxie/compare/0.6.7...0.7.0

**Comment by DavidXanatos** [comment]
this is very strange the latest release works for me just fin on windows 10:

![grafik](https://user-images.githubusercontent.com/3890945/213393584-044ccb01-5e83-419d-9c4b-d9e87f0a0d71.png)

is it may be requried to change the os language as well?

**Comment by isaak654** [comment]
> is it may be requried to change the os language as well?

Yes, you also need to install Hebrew as main display language.

**Comment by isaak654** [comment]
> is it may be requried to change the os language as well?

Yes, you must also install Hebrew as main display language.

**Comment by DavidXanatos** [comment]
I found the issue and fixed it

**Comment by lwcorp** [comment]
Thanks! Can you link to the fix to learn from it?

**Comment by DavidXanatos** [comment]
https://github.com/sandboxie-plus/Sandboxie/commit/5f25c92b6c0088dcfa3855c97982703b9fc29b04

**Comment by lwcorp** [comment]
Wow, so few changes for such a big impact. :-)
