### ISSUE TITLE
"Failed to download installer" when trying to update.

### ISSUE THREAD

**Issue by olliebean** [sandboxie-plus/Sandboxie#2615]
### Describe what you noticed and did

1. In the manager app for Sandboxie Plus, click on "Check for updates" in the Help menu when there is an update available.
2. When the update is detected, click "Yes" to download the installer.
3. After apparently downloading the installer (the network shows data being downloaded, and a progress bar is shown and appears to complete), the update fails with "Failed to download installer from: https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.6.6/Sandboxie-Plus-x64-v1.6.6.exe"

### How often did you encounter it so far?

Whenever I try to update from the Sandboxie Plus manager app.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The installer should be downloaded successfully and then run to install the update. (Note that manually downloading and installing the update, from the exact same URL as the Sandbox manager reports a failure to download from, works without issues.)

### What is your Windows edition and version?

Windows 10 Pro 21H2

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Microsoft Defender (built-in antivirus)

### What version of Sandboxie are you running?

Sandboxie Plus v1.6.5

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

For several versions now, I am unsure exactly when it started.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
I have made a small change on the update server, in the metadata, could you please retry now

**Comment by olliebean** [comment]
I'm still getting the same error.

**Comment by DavidXanatos** [comment]
hmm... ok will check it out further, thanks for the fast feadback :)

**Comment by DavidXanatos** [comment]
strange i cant reproduce it, anyone else with this issue?

**Comment by olliebean** [comment]
Could I ask where the installer should be downloaded to, so I can check if the file is actually being downloaded to there? Is it possible it could be a file/directory permission issue?

**Comment by offhub** [comment]
"`%TEMP%\sandboxie-updater`" folder.

**Comment by olliebean** [comment]
Thanks. That folder did not exist, and was not being created. However I created the folder manually, and running the update check in the manager, the installer was successfully downloaded into it. So it seems the problem was caused by the `%TEMP%\sandboxie-updater` folder not pre-existing, or possibly by the manager failing to create that folder.

**Comment by offhub** [comment]
There may be a problem with folder permissions on your system. You can check it with the command below.

Windows > Run > CMD:
```
ICACLS %temp%
```

The result should look like the following.

```
C:\Users\ADMINI~1\AppData\Local\Temp NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                                     BUILTIN\Administrators:(I)(OI)(CI)(F)
                                     YourPCName\Administrator:(I)(OI)(CI)(F)
```

**Comment by olliebean** [comment]
The results for `NT AUTHORITY\SYSTEM`, `BUILTIN\Administrators`, and my username are all `(I)(OI)(CI)(F)`.
