### ISSUE TITLE
Winzip 27 Windows installer error 

### ISSUE THREAD

**Issue by anmac1789** [sandboxie-plus/Sandboxie#2616]
### Describe what you noticed and did

I downloaded winzip 27 installer from the official website and I enabled windows installer. I still get an error. When I used pkzip from pkware, everything installed correctly but not with Winzip. What is the issue around winzip ?

![Screenshot 2023-01-17 163325](https://user-images.githubusercontent.com/103609429/213017283-3882524b-582e-4a17-ba28-0531f2f26c35.png)

![Screenshot 2023-01-17 163417](https://user-images.githubusercontent.com/103609429/213017285-e6e29e28-14f6-4e94-b2ed-72c242170ffd.png)

### How often did you encounter it so far?

Whenever initiating winzip installer with sandbox

### Affected program

Winzip 27 and sandboxie-plus 1.6.6

### Download link

https://www.winzip.com/en/

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

It should install everythin correctly and should use winzip forever bypassing the 21 day trial

### What is your Windows edition and version?

Windows 11 pro for workstation

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

brand new re-format windows 11 workstation install with all windows updates

### What version of Sandboxie are you running?

1.6.6

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

not application

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

I do not know

**Comment by isaak654** [comment]
You can only install it if you manually set `MsiInstallerExemptions=y` in your sandbox or from the Plus UI in the following way:

`Plus UI` > `Sandbox Options` > `Security Hardening` > `Elevation restrictions` >> `Allow MSIServer to run with a sandboxed system token and apply other exceptions if required`

Note: at the end of the Winzip installation, there will be a number of messages `SBIE2205 Service not implemented: schtasks.exe` because Sandboxie blocks all the attempts to add new scheduled tasks.

**Comment by anmac1789** [comment]
> You can only install it if you manually set `MsiInstallerExemptions=y` in your sandbox or from the Plus UI in the following way:
> 
> `Plus UI` > `Sandbox Options` > `Security Hardening` > `Elevation restrictions` >> `Allow MSIServer to run with a sandboxed system token and apply other exceptions if required`
> 
> Note: at the end of the Winzip installation, there will be a number of messages `SBIE2205 Service not implemented: schtasks.exe` because Sandboxie blocks all the attempts to add new scheduled tasks.

what can i do about those messages ?

**Comment by isaak654** [comment]
I suggest to ignore them, by hiding them you would not realise what happens.

**Comment by anmac1789** [comment]
> I suggest to ignore them, by hiding them you would not realise what happens.

Ok I will test this and see what happens. I have another question, lets say if the winzip installed on windows and the trial period ended the normal way is there a way to continue to use it beyond the trial period or does it have to be a completely new installation in sandbox on a new windows fresh install ?

**Comment by anmac1789** [comment]
> > Also, how do I allow mapped network drives?
> 
> #1617 and/or switching `BlockNetworkFiles=y` to `BlockNetworkFiles=n`

Where do I put these commands?

**Comment by isaak654** [comment]
If you are in the main Sandboxie Plus window and you've closed any running program in the sandbox:

* Go to Options menu -> Edit ini file -> confirm yes
* Replace `BlockNetworkFiles=y` with `BlockNetworkFiles=n` below [DefaultBox] or any other sandbox you want
* Save the ini file and close it

If needed, you could also add `NormalFilePath=\Device\Mup` to your sandbox by repeating the previous steps.

**Comment by anmac1789** [comment]
> If you are in the main Sandboxie Plus window and you've closed any running program in the sandbox:
> 
> * Go to Options menu -> Edit ini file -> confirm yes
> * Replace `BlockNetworkFiles=y` with `BlockNetworkFiles=n` below [DefaultBox] or any other sandbox you want
> * Save the ini file and close it
> 
> If needed, you could also add `NormalFilePath=\Device\Mup` to your sandbox by repeating the previous steps.

NormalFilePath=\Device\Mup what does this do?

**Comment by isaak654** [comment]
- `NormalFilePath` is not well-documented, but there are references [here](https://sandboxie-plus.github.io/sandboxie-docs/Content/ResourceAccess.html) and [here](https://github.com/sandboxie-plus/Sandboxie/search?q=NormalFilePath).
- About the `\Device\Mup` handle: https://superuser.com/a/717973

**Comment by anmac1789** [comment]
> * `NormalFilePath` is not well-documented, but there are references [here](https://sandboxie-plus.github.io/sandboxie-docs/Content/ResourceAccess.html) and [here](https://github.com/sandboxie-plus/Sandboxie/search?q=NormalFilePath).
> * About the `\Device\Mup` handle: https://superuser.com/a/717973

Ok thank you I will test this out and see what happens

**Comment by DavidXanatos** [comment]
I have taken a look in this installer and could reproduce the error message in a default box, 
to resolve the issue please enable special exceptions for the msi installer: MsiInstallerExemptions=y

![grafik](https://user-images.githubusercontent.com/3890945/215271237-9444fdf7-ec14-4f33-a269-79a67f16125d.png)

With this the installer works fine.

**Comment by isaak654** [comment]
#2699

**Comment by baigmirza09** [comment]
# [Download & Install Winzip 27 Windows Installer 🔽💹⏬](https://corlubar.com/dl/)

**Comment by anmac1789** [comment]
> I have taken a look in this installer and could reproduce the error message in a default box, to resolve the issue please enable special exceptions for the msi installer: MsiInstallerExemptions=y
> 
> ![grafik](https://user-images.githubusercontent.com/3890945/215271237-9444fdf7-ec14-4f33-a269-79a67f16125d.png)
> 
> With this the installer works fine.

are you sure it's winzip 77 ? from the official website
