### ISSUE TITLE
Option to remove a <section> from sandboxie.ini using sbieini.exe

### ISSUE THREAD

**Issue by LexKul** [sandboxie-plus/Sandboxie#2620]
### Is your feature request related to a problem or use case?

I am using a bat script to create a sandbox and params with sbieini.exe.
But it's not possible to remove the sandbox with sbieini.exe.
This can only be done from the Sandbox GUI Sandboxie-Plus by selecting Delete Sandbox from the context menu.

### Describe the solution you'd like

Add option to delete section from sandboxie.ini for delete the sandbox similar to the option in the GUI.
Like: sbieini.exe delete /boxes <sandboxname>

**Comment by DavidXanatos** [comment]
You can delete a sandbox like this
```
SbieIni.exe set BoxName * ""
```

**Comment by LexKul** [comment]
Thanks! This is worked nice!
