### ISSUE TITLE
Microsoft Edge Dev build 111.0.1633.0 will not launch when sandboxed

### ISSUE THREAD

**Issue by nakamachi-edgeuser** [sandboxie-plus/Sandboxie#2631]
### Describe what you noticed and did

 Version 108/109 of Microsoft Edge were able to start.
 After updating to Dev build 111.0.1633.0, Microsoft Edge could not start.

### How often did you encounter it so far?

everytime

### Affected program

Microsoft Edge Dev build 111.0.1633.0,  platform : Windows 64-bit

### Download link

https://www.microsoft.com/ja-jp/edge/business/download?form=MA13FJ

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

open without error

### What is your Windows edition and version?

Windows 10 IoT Enterprise 2019 LTSC

### In which Windows account you have this problem?

I use the built-in Administrator with Admin Approval Mode turned on.

### Please mention any installed security software

Windows Defender Antivirus

### What version of Sandboxie are you running?

Version 5.49.0 / [1.6.7 64-bit](https://github.com/sandboxie-plus/Sandboxie/issues/2631#issuecomment-1406214056)

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Standard sandbox

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing

[UserSettings_18060302]

SbieCtrl_UserName=testuser
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_WindowCoords=187,127,1024,619
SbieCtrl_ActiveView=40021
SbieCtrl_ReloadConfNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_BoxExpandedView=browser_worker
SbieCtrl_HideWindowNotify=n
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_HideMessage=*

[browser_worker]

ConfigLevel=8
BlockNetworkFiles=y
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
BorderColor=#00FFFF,off,6
Enabled=y
BoxNameTitle=-
AutoDelete=y
NeverDelete=n
CopyLimitKb=512000
CopyLimitSilent=y
ForceFolder=C:\Program Files (x86)\Microsoft\Edge\Application
```

**Comment by offhub** [comment]
The Sandboxie version you are using is quite old. Please try again after updating Sandboxie to the latest version.

https://github.com/sandboxie-plus/Sandboxie/releases

**Comment by nakamachi-edgeuser** [comment]
> The Sandboxie version you are using is quite old. Please try again after updating Sandboxie to the latest version.
> 
> https://github.com/sandboxie-plus/Sandboxie/releases

Ok thank you. I will try the new version.

**Comment by MuddyBleach** [comment]
Something has definitely went wrong last days.

Win 10 22H2
Edge  Dev 111.0.1633.0
Sandboxie-Plus 1.67

Webpages  do not load while displaying "**This page is having problem. Error code:** out of memory"
Same for internal configuration pages (about: ..).
When trying to reach any settings from the menu only dummy blank fields pop up.


P.S.
I can also confirm as a witness that a regular Edge 109 installation recently could not start on a completely different pc having Win 8 and an older version of Sandboxie.

**Comment by isaak654** [comment]
No problem here with the following configuration:

- Windows 10 Pro 21H2 (64 bit)
- Version 109.0.1518.70 (official build) (64 bit)
- Sandboxie Plus v1.5.3 (64 bit)
- Standard sandboxie.ini (new empty sandbox)

**Comment by isaak654** [comment]
No problem here with the following configuration:

- Windows 10 Pro 21H2 (64 bit)
- MS Edge version 109.0.1518.70 (official build) (64 bit)
- Sandboxie Plus v1.5.3 (64 bit)
- Standard sandboxie.ini (new empty sandbox)

**Comment by MuddyBleach** [comment]
It would be too early to post a separate issue for the unpolished Dev channel Edge  updates. 

But new incompatibilities Edge Dev 111.0.1633.0 contains, as they apparently do not cause problems besides this Sandboxie specific use case. will most possiby surivive into the much more whidely used stable versions soon. 

So my message above might be a kind of premonitory alarm.

**Comment by offhub** [comment]
Version 109.0.1518.70 (Official build) **stable** (64-bit) - OK
Version 110.0.1587.22 (Official build) **beta** (64-bit) - OK
Version 111.0.1633.0 (Official build) **dev** (64-bit) - "This page is having problem. Error code: out of memory"

**Comment by DavidXanatos** [comment]
go to your templates ini and comment out
ExternalManifestHack=msedge.exe,y
ExternalManifestHack=msedgewebview2.exe,y
then reload the config
and try again, in windows 10 this works

**Comment by DavidXanatos** [comment]
I'll add this change to the templates.ini of the next build.
it looks to me like the current edge 109 works fine without this fix on windows 10/11  anyways, so it should be safe to remove it.

**Comment by MuddyBleach** [comment]
Yes, the worlkaround is effective.

**Comment by akkocton** [comment]
Hi and Good day everyone...
i wonder if im on the right thread
i have a problem also
and open a webview game
but it is crashing, is there any new solution here? TIA

![image](https://user-images.githubusercontent.com/123893747/215345373-c6b13e29-be41-485c-8277-6eca91890c9d.png)

**Comment by akkocton** [comment]
Hi and Good day everyone...
i wonder if im on the right thread
i have a problem also
and open a webview game
but it is crashing, is there a solution to this,? Thanks in advance
![image](https://user-images.githubusercontent.com/123893747/215345489-26cc02eb-37ec-47d9-a531-3522727a0add.png)
![image](https://user-images.githubusercontent.com/123893747/215346112-37604ae1-3987-491b-9d0c-c53503d1b136.png)

**Comment by isaak654** [comment]
@akkocton 
What is your Edge version? In case, please comment out the following line in the Templates.ini file and report if it works:
https://github.com/sandboxie-plus/Sandboxie/blob/756e360aa71d6d57105839bfa1dd85d9582ad55c/Sandboxie/install/Templates.ini#L656

**Comment by akkocton** [comment]
> @akkocton What is your Edge version? In case, please comment out the following line in the Templates.ini file and report if it works:
> 
> https://github.com/sandboxie-plus/Sandboxie/blob/756e360aa71d6d57105839bfa1dd85d9582ad55c/Sandboxie/install/Templates.ini#L656

Still not working, my webview version 
and i have updated sandboxie 70c x64
![image](https://user-images.githubusercontent.com/123893747/215415302-aeb7a125-5f1d-4172-b998-9e5357da3042.png)

**Comment by isaak654** [comment]
@akkocton
I have no other ideas, feel free to open a new [problem report](https://github.com/sandboxie-plus/Sandboxie/issues/new/choose).

**Comment by Initsnow** [comment]
> > [@akkocton](https://github.com/akkocton) What is your Edge version? In case, please comment out the following line in the Templates.ini file and report if it works:
> > 
> >   
> >     
> >       [Sandboxie/Sandboxie/install/Templates.ini](https://github.com/sandboxie-plus/Sandboxie/blob/756e360aa71d6d57105839bfa1dd85d9582ad55c/Sandboxie/install/Templates.ini#L656)
> >     
> >     
> >          Line 656
> >       in
> >       [756e360](/sandboxie-plus/Sandboxie/commit/756e360aa71d6d57105839bfa1dd85d9582ad55c)
> >     
> >   
> >   
> >     
> > 
> >         
> >           
> >            ExternalManifestHack=msedgewebview2.exe,y
> 
> Still not working, my webview version and i have updated sandboxie 70c x64 ![image](https://user-images.githubusercontent.com/123893747/215415302-aeb7a125-5f1d-4172-b998-9e5357da3042.png)

Did you find any way to solve this?
