### ISSUE TITLE
[1.7.0] SandMan crashes when hovering over Run menu if there are any custom Run Menu entries are defined and OptaneShellExt is enabled.

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2637]
### Describe what you noticed and did

1. Install `Intel Optane Pinning Shell Extension`. (Comes with chipset driver? Intel RST 17.11.0.1000)
2. Restart SandMan.exe.
3. Add a custom Run Menu entry. (SandMan > Sandbox Options > General Options > Run Menu)
4. Hover over the `Run` menu. (SanMan > Right click on a box to open sandbox context menu > Run)
5. SandMan.exe crashes.
6. Disabling the `Intel.Optane.Pinning.ShellExt.OptaneIconOverlay` fixes the issue. (with NirSoft ShellExView)

###
pw is `sandboxie`
[pw-is-sandboxie.zip](https://github.com/sandboxie-plus/Sandboxie/files/10520761/pw-is-sandboxie.zip)

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

It is in the zip file

### Where is the program located?

Not relevant to my request.

### Expected behavior

The app shouldn't crash.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.7.0 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Since Sandboxie Plus v1.6.7 64-bit

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Crash dump

It is in the zip file

### Sandboxie.ini configuration

```shell
[Global Settings]
RunCommand=Command Prompt|"C:\Windows\System32\cmd.exe"
RunCommand=PowerShell|"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
RunCommand=PowerShell 7|"C:\Program Files\PowerShell\7\pwsh.exe"
```

**Comment by DavidXanatos** [comment]
please test 1.7.1 when its out i think the issue is an over bearing crash catcher, the issue wasnt present on the previouse build right?

**Comment by offhub** [comment]
Only crashes with 1.7.0.

**Comment by DavidXanatos** [comment]
I have updated the installers please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0a

**Comment by offhub** [comment]
Still crashing after the update. (1.7.0a)

**Comment by DavidXanatos** [comment]
I have updated the installers once again please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0b

**Comment by offhub** [comment]
Still crashing with v1.7.0**b**.
