### ISSUE TITLE
[1.7.0] SandMan crashes when double click on a template entry

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2640]
### Describe what you noticed and did

1. SandMan > Options > Global Settings > Compatibility > Double click on an entry
2. SandMan crashes

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The app shouldn't crash.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.7.0 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
I have updated the installers please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0a

**Comment by offhub** [comment]
Still crashing after the update. (1.7.0a)

**Comment by DavidXanatos** [comment]
I have updated the installers once again please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0b

**Comment by offhub** [comment]
No crash with 1.7.0b.
