### ISSUE TITLE
1.7.0 has no signature; triggers Windows security and 4 detections on virustotal

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#2646]
### Describe what you noticed and did

1.7.0 has no signature
It triggers a Windows alert
https://www.virustotal.com/gui/file/ead7251d4961b7c4f0f7560c0957777de36cb3b47b8c2436ffe45fb228674b30/details

### Affected program

Sandboxie Plus 1.7.0

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.7.0/Sandboxie-Plus-x64-v1.7.0.exe

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

I'd expect a signature.
Version 1.6.5, 1.6.6 and 1.6.7 all featured signatures and scored 0 virustotal detections, example:
https://www.virustotal.com/gui/file/439a938e42af88910be2e2107b524cb6f71887a7a8f87533db52282526571612/

### What is your Windows edition and version?

Windows 10 Edu 22H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.7.0

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
Pre releases will usually not be signed to make the release process faster.
