### ISSUE TITLE
ProtonVPN fails to connect when running in a standard sandbox

### ISSUE THREAD

**Issue by Ciao223344** [sandboxie-plus/Sandboxie#2647]
### Describe what you noticed and did

Hi, when I try to use ProtonVPN on a box with standard isolation, it doesn't work. I can open this program with sandboxie plus and it work, but when I try to connect myself to the VPN, the program blocks himself. Can anybody help me? Sorry for my bad english.

### How often did you encounter it so far?

Always

### Affected program

ProtonVPn 2.3.2

### Download link

https://protonvpn.com/download

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

I expected that when I use the connect button of the VPN, it works and connect the box to the VPN's servers.

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus 1.6.6

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

I think not but i'm not very sure.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
DefaultBox=DefaultBox
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Edge_Fix
SeparateUserFolders=n
EnableObjectFiltering=n

[UserSettings_0C7E0210]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[Box_With_Problem]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
UseSecurityMode=n
UsePrivacyMode=n
```

**Comment by Ciao223344** [comment]
Nobody can help me?

**Comment by offhub** [comment]
Right click on the sandbox >  From the menu: Select `Sandbox Options` > From Left: Select `Edit Ini Section` > From Right: Click on the `Edit Ini` > Add following code to the bottom of the list > `Save` > `OK`

```
OpenPipePath=\Device\NamedPipe\fbcc7f21-ca4f-4bc6-9812-e540376dee35
OpenIpcPath=*\BaseNamedObjects\*ebmv0l*
```

**Comment by Ciao223344** [comment]
Thank you for your reply! After entering what you have indicated to me, in the program after I press the button, the screen freezes for a while but then the program works again but it isn't connected to the VPN.

**Comment by offhub** [comment]
Can you try to connect with Wireguard protocol. (ProtonVPN>settings>Connection>Protocol>Select Wireguard)

**Comment by offhub** [comment]
Remove the previous rules and try with the following rules:

```
OpenIpcPath=\DEVICE\NETBT_TCPIP_{*-*-*-*-*}
OpenIpcPath=*\BaseNamedObjects\*ebmv0l*
OpenPipePath=\Device\NamedPipe\*-*-*-*-*
```

**Comment by Ciao223344** [comment]
Sorry, don't work. could it be that it tries to access files like ProtonTAP and fails and for this it freeze?

**Comment by offhub** [comment]
Try these:

```
OpenIpcPath=*\BaseNamedObjects*\net.pipe:*
OpenIpcPath=\DEVICE\NETBT_TCPIP_{*-*-*-*-*}
OpenPipePath=\Device\NamedPipe\*-*-*-*-*
```


https://user-images.githubusercontent.com/6871698/216473265-3856ff69-f215-470d-b698-187e7daefc25.mp4

**Comment by Ciao223344** [comment]
It works!!!  Thanks a lot

**Comment by e-t-l** [comment]
Out of curiosity, what happens when you run a VPN in a sandbox? Does it still become the default network adapter for the whole computer? What is the benefit of sandboxing a VPN?

**Comment by Ciao223344** [comment]
Does it still become the default network adapter for the whole computer?
Depends from the sandbox. If you use virtualbox, you can have tons of ip (One for sandbox) and your IP stay on your principal PC; in sandboxie plus, with the free version, unfortunately, the VPN also if opened in the sandbox change the entire network of the PC.
What is the benefit of sandboxing a VPN?
I wanted to make more Microsoft rewards accounts, but I didn't do nothing for lack of time and decrease of earned points.

**Comment by GY8VSdYYzvL8-K6T** [comment]
> Try these:
> 
> ```
> OpenIpcPath=*\BaseNamedObjects*\net.pipe:*
> OpenIpcPath=\DEVICE\NETBT_TCPIP_{*-*-*-*-*}
> OpenPipePath=\Device\NamedPipe\*-*-*-*-*
> ```

Thank you! I am very glad I found this topic!

**Comment by GY8VSdYYzvL8-K6T** [comment]
Does "OpenPipePath=\Device\NamedPipe\*-*-*-*-*" open up path to basically any named pipe? I assume "*-*-*-*-*" is a wildcard that means "any".
