### ISSUE TITLE
Steam game (Project Winter) does not work

### ISSUE THREAD

**Issue by applenick21** [sandboxie-plus/Sandboxie#265]
Steam game (Project Winter) does not work, only black window. Other games work well. Sandboxie-Plus v0.5.1.
**UPD:** this game works well in sandbox from Avast.

**Comment by isaak654** [comment]
Please try the new Sandboxie-Plus v0.5.2 and let us know. It was released one hour after your post.

**Comment by isaak654** [comment]
Please try the new Sandboxie-Plus v0.5.2 and let us know.

**Comment by applenick21** [comment]
Thanks it helped
