### ISSUE TITLE
%USER% expands to "system" instead of currently_logged_in_user

### ISSUE THREAD

**Issue by DonEstefan** [sandboxie-plus/Sandboxie#2653]
### Describe what you noticed and did

1. I use a windows account named "xxx" and moved the user folder to d:\xxx. 
2. I followed https://sandboxie-plus.com/sandboxie/filerootpath/ and set
```ini
[GlobalSettings]
FileRootPath=D:\%USER%\Sandboxie\%SANDBOX%
```
This worked for many years.

3. Some sandboxie-releases ago (around the time [this issue](https://github.com/sandboxie-plus/Sandboxie/issues/2407) was created), I started geting error messages when starting a sandbox:
`PID 7852: SBIE2227 'Browser (D:\SYSTEM\Sandboxie\Browser)' is located on a volume which does not support 8.3 naming. This can cause issues with older applications and installers.`
However, the newer sandboxie-plus releases did not solve the problem.  `fsutil 8dot3name query d:` shows that 8dot3-Nams are active. So this it not really about missing 8.3 names.
Today I realized, that the `%user%` variable stopped dynamically providing my logged_in user name. It statically returns the "system" user name instead . 
So sandboxie started using a non existent path  (D:\SYSTEM does not exist)

However, sandboxie seems to be working fine and seems to be putting files in the right folder (D:\xxx\...). I'm not sure what to make of this...

### How often did you encounter it so far?

always, in the last couple of sandboxie releases

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

- Sandbox should start witout error message.
- `%USER%` should contain the name of the currently logged in user

### What is your Windows edition and version?

Win10 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.6.7 64 bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

since 5.60.0 (approximately)

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]
FileRootPath=D:\%USER%\Sandboxie\%SANDBOX%
```

**Comment by mysteriously** [comment]
I can confirm it, SBIE v1.6.6, Win11 22h2

**Comment by DavidXanatos** [comment]
where exactly do you see %USER% returning "system" ?

**Comment by mysteriously** [comment]
I cant start an app which is installed on non system partition (the same partition where sandbox folder is located).. The same error like mentioned in first post appears.


Also, when I use Junction, I receive access denied error

---------------------------
Sandboxie Start
---------------------------
Could not invoke program:



"X:\Program Files\someapp\someapp.exe"

System Error Code:

Access is denied.

 (5)
---------------------------
OK   
---------------------------

**Comment by DavidXanatos** [comment]
hmpf... to clarify it once more:
SBIE2227 is not an error just an info message to enable 8.3 naming support on all volumes which are used to hold sandboxes.
It is not generated in response to an error, or anything, the service, whenever a process is started in a sandbox which was inactive before, resolves the box's root path and checks if said path is located on a volume supporting 8.3 naming, if not then it issues the sbie message.

if it resolves %user% to the actual user or to system at this stage is irrelevant.

Everything should run just fine, as fine as it can on a non 8.3 naming supporting device, despite of this warning.

@mysteriously please elaborate how your are using Junctions.
