### ISSUE TITLE
[1.7.0c] SandMan.exe crashes time to time

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2654]
### Describe what you noticed and did

I have attached crash dumps.

pw is `sandboxie`
[fourDmps_pw-is_sandboxie.7z.zip](https://github.com/sandboxie-plus/Sandboxie/files/10539190/fourDmps_pw-is_sandboxie.7z.zip)

### How often did you encounter it so far?

sometimes

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Shouldn't crash

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.7.0c 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

Since Sandboxie Plus v1.6.7 64-bit

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
are you doing anything special when this happens?
or is it fully random, i see where it crashes but there is no apparent reason... were you by any chance deleting sandboxes when this happened?

**Comment by offhub** [comment]
> are you doing anything special when this happens?

I can't say anything for sure.

> were you by any chance deleting sandboxes when this happened?

I can't say for sure, since most of the boxes are set to auto-delete, Also I've done a lot of deleting and trace logging over the last few days.

**Comment by DavidXanatos** [comment]
With deleting I meant removing the entire box not just deleting its content.

**Comment by DavidXanatos** [comment]
which was the last version you used before v1.6.7?

**Comment by offhub** [comment]
> Since Sandboxie Plus v1.6.7 64-bit

I have mistakenly given wrong information while filling out the form. _Since_ -> _After_ (SandMan.exe version 1.7.0.2 and 1.7.0.3 according to event log)

**Comment by offhub** [comment]
I'm closing this issue as I haven't had any crashes since 1.7.1/1.7.2.
