### ISSUE TITLE
SandMan UI Bug

### ISSUE THREAD

**Issue by okrc** [sandboxie-plus/Sandboxie#2659]
- [x] When the program exits, `QApplication::quit()` does not trigger `closeEvent()` for the subwindow
- [x] When the program receives a message and does not run to completion, if `app.sendMessage(const QString &)` is executed again, it will fail and open the task in a new instance. The SandMan interface then falsely dies when the initial message task completes.

**Comment by DavidXanatos** [comment]
"When the program exits", how, by precising X by using the exit command from the menu, by windows sending a close message like when closing form task manager?
how exactly to reproduce?

**Comment by okrc** [comment]
https://user-images.githubusercontent.com/29057533/216144816-3a864302-68a7-456f-b208-035bd31bdff8.mp4

https://user-images.githubusercontent.com/29057533/216146416-d9bf8770-34f2-49b0-bb15-2e3227a1fde7.mp4

**Comment by DavidXanatos** [comment]
I see thank you very much, I'll look into it asap
