### ISSUE TITLE
Sandboxie-Plus-x64-v0.5.2.exe says it is going to install 0.5.1

### ISSUE THREAD

**Issue by katchy3132** [sandboxie-plus/Sandboxie#267]
When I run Sandboxie-Plus-x64-v0.5.2.exe I get this screen : 

![image](https://user-images.githubusercontent.com/3707138/102995929-c15d6b00-452a-11eb-8228-4d435b1e9b19.png)

**Comment by DavidXanatos** [comment]
haha... no its fine i just mised to update the title of the installer
