### ISSUE TITLE
Spotify interface is completely black when running in sandboxie

### ISSUE THREAD

**Issue by Bryan2333** [sandboxie-plus/Sandboxie#2673]
### Describe what you noticed and did

1. Download the installation program from Spotify
2. Install the spotify in the sandboxie
3. Run the spotify 

Here is the screenshot of it

![spotify1](https://user-images.githubusercontent.com/31512600/217771501-cfb2d50c-3598-4b3c-92e2-ec71b93cb9ea.PNG)

And I'm not able to login in. When I install spotify outside the sandbox, it runs normally.

I have never met this problem in previous version of sandboxie like 1.6.4

### How often did you encounter it so far?

Whenever I launch it

### Affected program

latest version of Spotify

### Download link

https://www.spotify.com/us/download/windows/

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

The login menu show up normally.

### What is your Windows edition and version?

Windows 10 LTSC 2019

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.7.2 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No.

**Comment by offhub** [comment]
You could try adding the code below to your box configuration:

`ExternalManifestHack=Start.exe,y`

OR

`ExternalManifestHack=y`

**Comment by Bryan2333** [comment]
> You could try adding the code below to your box configuration:
> 
> `ExternalManifestHack=Start.exe,y`
> 
> OR
> 
> `ExternalManifestHack=y`

It works, thx.

**Comment by Bryan2333** [comment]
The workaround only works once after installation. When I open spotify again, it still become completely black.

**Comment by offhub** [comment]
It opens for me without issue with both settings. (Windows 10 22H2)

Try this instead of the above:

`PreferExternalManifest=y`

**Comment by DavidXanatos** [comment]
please test if this issue is present in the 1.8.0 preview build

**Comment by Bryan2333** [comment]
> please test if this issue is present in the 1.8.0 preview build

I'm sorry that My laptop is running Linux and I have no other devices running Windows. I would like someone to check it.

**Comment by TooYoungTooSimp** [comment]
> please test if this issue is present in the 1.8.0 preview build

It works with `PreferExternalManifest=Spotify.exe,y`.

Without this config. Spotify remains black (in fact if waiting for a long time, normal ui will appear in latest stable build)

**Comment by DavidXanatos** [comment]
please test 1.8.2

**Comment by isaak654** [comment]
[v1.8.2 = v5.63.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.8.2) in terms of compatibility, so the previous comment still applies.

**Comment by DavidXanatos** [comment]
ah right... can you reproduce this issue? when i did my testing recently with the new changes spotify laoded just fien for me

**Comment by isaak654** [comment]
I can confirm this issue with v1.9.0 x64 after installing and running Spotify inside a standard box.
Workaround: https://github.com/sandboxie-plus/Sandboxie/issues/2673#issuecomment-1493208618

**Comment by DavidXanatos** [comment]
the workaround will be added to the next tempaltes.ini

**Comment by emlece1** [comment]
I tried these, but

{ PreferExternalManifest=Spotify.exe,y }
{ ExternalManifestHack=Start.exe,y }
OR
{ ExternalManifestHack=y }

I tried using the latest sand box and also the [v1.8.2 = v5.63.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.8.2) but cant get it done, i don't know which box are you talking about.
I tried adding the given code under the 
sandbox options >> edit ini section, but I still get the black screen,

even when I add the given settings under
C:\Users\User\AppData\Local\Sandboxie-Plus\Sandboxie-Plus.ini
or C:\Windows\Sandboxie.ini

still its not working..

**Comment by emlece1** [comment]
> You could try adding the code below to your box configuration:
> 
> `ExternalManifestHack=Start.exe,y`
> 
> OR
> 
> `ExternalManifestHack=y`

I tried these, but

{ PreferExternalManifest=Spotify.exe,y }
{ ExternalManifestHack=Start.exe,y }
OR
{ ExternalManifestHack=y }

I tried using the latest sand box and also the [v1.8.2 = v5.63.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.8.2) but cant get it done, i don't know which box are you talking about.
I tried adding the given code under the 
sandbox options >> edit ini section, but I still get the black screen,

even when I add the given settings under
C:\Users\User\AppData\Local\Sandboxie-Plus\Sandboxie-Plus.ini
or C:\Windows\Sandboxie.ini

still its not working..

**Comment by emlece1** [comment]
> > please test if this issue is present in the 1.8.0 preview build
> 
> Tested on v5.63.2. It works with `PreferExternalManifest=Spotify.exe,y`.
> 
> Without this config. Spotify remains black (in fact if waiting for a long time, normal ui will appear in latest stable build)

I tried these, but

{ PreferExternalManifest=Spotify.exe,y }
{ ExternalManifestHack=Start.exe,y }
OR
{ ExternalManifestHack=y }

I tried using the latest sand box and also the [v1.8.2 = v5.63.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.8.2) but cant get it done, i don't know which box are you talking about.
I tried adding the given code under the 
sandbox options >> edit ini section, but I still get the black screen,

even when I add the given settings under
C:\Users\User\AppData\Local\Sandboxie-Plus\Sandboxie-Plus.ini
or C:\Windows\Sandboxie.ini

still its not working..

**Comment by e-t-l** [comment]
> I tried these, but
> { PreferExternalManifest=Spotify.exe,y }

I am still getting the black screen, even after setting `PreferExternalManifest`, on v1.11.4

I also tried setting `Template=OpenCOM` and that caused Spotify to crash immediately.

> The workaround will be added to the next Templates.ini.
> For more details about the origin of the issue:
> ![](https://user-images.githubusercontent.com/12372772/233789476-3755fe64-1ce4-4112-a5a7-0d67d3ea3552.png)

Does the ExternalManifest workaround work when spotify is _installed_ inside the box, too?

**Comment by antho1703** [comment]
I have the same problem spotify black screen on the latest version v1.11.4 what to do thank you?

**Comment by antho1703** [comment]
Please i can help

**Comment by antho1703** [comment]
Please i need help

**Comment by antho1703** [comment]
> Vous pouvez essayer d'ajouter le code ci-dessous à la configuration de votre box :
> 
> `ExternalManifestHack=Start.exe,y`
> 
> OU
> 
> `ExternalManifestHack=y`

Where is in sandboxie you write the command ?

**Comment by antho1703** [comment]
> > J'ai essayé ceux-ci, mais 
> > { PreferExternalManifest=Spotify.exe,y }
> 
> J'obtiens toujours l'écran noir, même après le réglage `PreferExternalManifest`, sur la version 1.11.4
> 
> J'ai également essayé le réglage `Template=OpenCOM`, ce qui a provoqué le crash immédiat de Spotify.
> 
> > La solution de contournement sera ajoutée au prochain Templates.ini. 
> > Pour plus de détails sur l'origine du problème :
> > ![](https://user-images.githubusercontent.com/12372772/233789476-3755fe64-1ce4-4112-a5a7-0d67d3ea3552.png)
> 
> La solution de contournement ExternalManifest fonctionne-t-elle également lorsque Spotify est _installé_ dans la boîte ?

Have you found a solution, please?

**Comment by AP2020C** [comment]
Where can I find the configuration file where to add PreferExternalManifest=Spotify.exe,y?

**Comment by antho1703** [comment]
![1 spotify](https://github.com/sandboxie-plus/Sandboxie/assets/98899553/5113bfb4-aac7-43b1-81a9-84de6bc02425)

By adding ca with version 1.11.4 spotify works and no longer makes black screen

**Comment by antho1703** [comment]
> Merci. Cependant... J'ai modifié le fichier comme ça `Enabled=y ConfigLevel=9 AutoRecover=y BlockNetworkFiles=y Template=OpenBluetooth Template=SkipHook Template=FileCopy Template=qWave Template=BlockPorts Template=LingerPrograms Template=Chrome_Phishing_DirectAccess Template=Firefox_Phishing_DirectAccess Template=AutoRecoverIgnore RecoverFolder=%{374DE290-123E-4565-9164-39C4925E467B}% RecoverFolder=%Personal% RecoverFolder=%Favorites% RecoverFolder=%Desktop% BorderColor=#00FFFF,ttl DropAdminRights=y FakeAdminRights=n PreferExternalManifest=y` Et il était toujours noir.
> 
> L'ajout `PreferExternalManifest=Spotify.exe,y ExternalManifestHack=y Template=OpenCOM ` ne démarre plus : l'icône du sandboxie change avec des points rouges puis redevient jaune.
> 
> Suppression du modèle = OpenCOM Spotify démarre, mais il est toujours noir

Just add in ini :

Template=OpenCOM
NoSecurityIsolation=y

no other juste this

**Comment by AP2020C** [comment]
Aside from the fact that the precise usefulness of an unprotected area escapes me, THIS IS A CONSPIRACY! Sandboxie claims to be paid to have this feature and spotify refuses to work sandboxed.
How do I use Spotify in Sandboxie Free?

**Comment by antho1703** [comment]
![image](https://github.com/sandboxie-plus/Sandboxie/assets/98899553/082a8168-d894-4333-b04f-12a8b5029bda)


I have a new error when I open spotify with sandboxing sandbox and I click on connection no web page opens for me to connect .. I’m stuck ... need help please

**Comment by isaak654** [comment]
Considering the lack of response, I don't think it makes sense to recycle this issue further. Please continue in the issue #3538 or open a new one if different or no longer relevant.
