### ISSUE TITLE
Sandboxieinstall64-v5.45.1 no installation prompt multilingual?

### ISSUE THREAD

**Issue by dsyo2008** [sandboxie-plus/Sandboxie#268]
![图片](https://user-images.githubusercontent.com/3739056/103001316-b5dc6500-4567-11eb-861a-6cc3989d76fa.png)
Sandboxie 5.45 can install prompts in multiple languages. Do you want to remove multilingualism?

**Comment by isaak654** [comment]
Probably it's something related to this recent commit: #257

**Comment by gjf** [comment]
In Russian the interface is completely broken:
[
![Безымянный](https://user-images.githubusercontent.com/322186/103034800-c942fc80-4576-11eb-8c9a-5202e3baea39.png)
](url)

**Comment by DavidXanatos** [comment]
there wer no changes to the russion language files.

But I updated the nullsoft instaler version to a much newer one i really hope that wasn't waht broke the localization.

**Comment by diversenok** [comment]
If you save Russian text into [CP-1251](https://en.wikipedia.org/wiki/Windows-1251) and then decode it back as [CP-1252](https://en.wikipedia.org/wiki/Windows-1252), it will look precisely like the text on the screenshot.

**Comment by gjf** [comment]
> there wer no changes to the russion language files.
> 
> But I updated the nullsoft instaler version to a much newer one i really hope that wasn't waht broke the localization.

The problem is with installer only.
The program itself works OK and the interface is OK also.

**Comment by dsyo2008** [comment]
No, it does display Chinese when re installing, but the interface is still English after installing

**Comment by DavidXanatos** [comment]
I have fixed the encoding on the simp-chinese file and compiled a new SbieMsg.dll
her is the patch for the Chinese users: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.5.2/Sandboxie-v5.45.1-Patch-Fixed-Chinese-Lang.zip

**Comment by DavidXanatos** [comment]
No what worries me is the Russian language as said that one wasn't changed but is broken in the installer that's not good not good at all.
I don't want to switch back to the old NSIS installer version as it results in much more false positives of the 32 bit installer package in VT.

**Comment by DavidXanatos** [comment]
Did russian worked in the previosue build?
I tried the 5.45.0 installer and picked Russian and on my system it also looked broken.
Also how did you got Russian selected as i tested 5.45.1 the language dialog did not offer me Russian only a few other languages.

![grafik](https://user-images.githubusercontent.com/3890945/103129676-e9b7a780-4699-11eb-8880-de6089bc85aa.png)

**Comment by dsyo2008** [comment]
> 
> 
> I have fixed the encoding on the simp-chinese file and compiled a new SbieMsg.dll
> her is the patch for the Chinese users: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.5.2/Sandboxie-v5.45.1-Patch-Fixed-Chinese-Lang.zip

Thank you very much. The problem has been solved.

**Comment by DavidXanatos** [comment]
Your welcome, its my duty to solve problems I caused myself.

**Comment by gjf** [comment]
> No what worries me is the Russian language as said that one wasn't changed but is broken in the installer that's not good not good at all.
> I don't want to switch back to the old NSIS installer version as it results in much more false positives of the 32 bit installer package in VT.

Yeah, 5.45.0 works OK on the same system with the same Russian default locale.
![5450](https://user-images.githubusercontent.com/322186/103132694-fc8ca500-46b6-11eb-9870-3cbff33c57ad.png)
![5451](https://user-images.githubusercontent.com/322186/103132695-fd253b80-46b6-11eb-93c0-76fffa802121.png)

**Comment by sarome3578** [comment]
The same problem occurs in Japanese. and when I click windows key, the displayed font is strange like picture. Would you fix it?
![start](https://user-images.githubusercontent.com/76502720/103137404-0d1b3a80-470c-11eb-8d9e-547978e07070.jpg)

**Comment by DavidXanatos** [comment]
I have uploaded a fixed pair of installers that should solve the issue

**Comment by PhoenixCA196** [comment]
Hello, maybe a sugesstion as NSIS usually has langauge problems and some other "charms" wouldn't it be better if you use Inno setup for installer?, it's easier to work with any most of langauge problems can be fixed faster.

**Comment by DavidXanatos** [comment]
Nah... I'm only fixing security/compatibility issues in the classic build, for anything else there is the plus build, also it uses inno setup already.
