### ISSUE TITLE
Cannot switch languages ​​other than English in ARM64

### ISSUE THREAD

**Issue by dnt1996** [sandboxie-plus/Sandboxie#2681]
### Describe what you noticed and did

![image](https://user-images.githubusercontent.com/31310280/218301842-4a20a392-4e17-4015-9e06-356f8897aea0.png)

### Affected program

Not relevant

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.7.2/Sandboxie-Plus-ARM64-v1.7.2.exe

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Language should be switched correctly.

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Defender

### What version of Sandboxie are you running?

1.7.2-arm64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
will be fixed in the next build, it was a compatibility issue with Qt6 which is used for the arm64 build
