### ISSUE TITLE
"Add 'Run Sandboxed' to the explorer context menu" option does not work in ARM64 version

### ISSUE THREAD

**Issue by dnt1996** [sandboxie-plus/Sandboxie#2685]
### Describe what you noticed and did

1. Check the "Add 'Run Sandboxed' to the explorer context menu" option.
2. Click the OK button.
3. "explorer context menu" does not change.

### Affected program

Not relevant

### Download link

1.7.2

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

-

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Defender

### What version of Sandboxie are you running?

1.7.2-arm64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by okrc** [comment]
Is there a `SbieShellPkg.msix` file in the installation directory?

#2415
https://github.com/sandboxie-plus/Sandboxie/pull/2359#issuecomment-1283973997

**Comment by sepcnt** [comment]
1.7.2 also do not work on x64 (Windows 11)

**Comment by dnt1996** [comment]
@okrc The file you mentioned does not exist.

**Comment by okrc** [comment]
@dnt1996 https://github.com/sandboxie-plus/Sandboxie/issues/2447#issuecomment-1310329165

**Comment by okrc** [comment]
@DavidXanatos Will the `SbieShellPkg.msix` file packaged by `x64\makeappx.exe` work on `ARM64` devices?
https://github.com/sandboxie-plus/Sandboxie/commit/9850c6d25864ac00ffe6a4b55c64c0b82a718596#diff-a81abec1c466dab0b09cb78f450059de78fe7fa04153b4243934d96307cedb92R324

**Comment by DavidXanatos** [comment]
it should yes
