### ISSUE TITLE
Potential memory issue with Sandboxie

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2686]
### Describe what you noticed and did

I have set `NotifyProcessAccessDenied=y` for some boxes, where it shows me whenever something got denied access, like it is intended to be. That is pretty much always `explorer.exe`, but sometimes there are strings instead of a real process.

This is either just some bits flipping on my computer, or some issue inside Sandboxie, which is why I am opening this issue. In the best case, that is just on my end, but I wanted to allow others to report on that as well. I had seen that before, was not worried, but if that is something that's seen by a wider range of people there might be an issue with how Sandboxie operates.

```
- PotPlayerMini64.exe (7156): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess (C0000022) access=00000040 initialized=1￨￨￨￨￨￨￨￨.exe
- PotPlayerMini64.exe (5324): SBIE2111 Prozess ist nicht zugänglich: $:ex￨￨￨￨￨.exe, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- PotPlayerMini64.exe (3740): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess (C0000022) access=00000040 initialized=￨￨￨￨￨￨￨￨.exe
- PotPlayerMini64.exe (5020): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess (C0000022) access=00000040 initia￨￨￨￨￨￨￨￨￨￨￨4
- PotPlayerMini64.exe (1760): SBIE2111 Prozess ist nicht zugänglich: $:explore￨￨￨4, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- PotPlayerMini64.exe (8168): SBIE2111 Prozess ist nicht zugänglich: $:explo￨￨￨￨8, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- PotPlayerMini64.exe (4324): SBIE2111 Prozess ist nicht zugänglich: $:exp￨￨￨￨￨.exe, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- PotPlayerMini64.exe (5304): SBIE2111 Prozess ist nicht zugänglich: $￨￨￨￨￨￨￨.exe, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- PotPlayerMini64.exe (5452): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenPr￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨.exe
- PotPlayerMini64.exe (4148): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess (C0￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨2
- PotPlayerMini64.exe (600): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess (C0000022) access=00000040 i￨￨￨￨￨￨￨￨￨￨￨￨￨￨6
- PotPlayerMini64.exe (10516): SBIE2111 Prozess ist nicht zugänglich: $:explorer￨￨.exe, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- firefox.exe (11024): SBIE2111 Prozess ist nicht zugänglich: $:explorer.￨￨rebox, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- PotPlayerMini64.exe (7736): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess (C0000022) a￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨24
- PotPlayerMini64.exe (10476): SBIE2111 Prozess ist nicht zugänglich: $:explor￨￨￨52, Aufruf OpenProcess (C0000022) access=00000040 initialized=1
- PotPlayerMini64.exe (6228): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess ￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨.exe
- PotPlayerMini64.exe (1760): SBIE2111 Prozess ist nicht zugänglich: , Aufruf Ope￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨.exe
- PotPlayerMini64.exe (9132): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess ￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨￨88
- PotPlayerMini64.exe (6120): SBIE2111 Prozess ist nicht zugänglich: , Aufruf OpenProcess (C0000022) access=00000040 initializ￨￨￨￨￨￨￨￨￨￨rebox
```

There seems to be a pattern to it. This is not bound to the current version or some special application. The reason why Firefox only shows up once, might be me launching it not as often, whereas I use the player to play some file, close it and open it again for some other file.

1) Create a new box (or use existing ones) with `NotifyProcessAccessDenied=y`
2) Start application that seemingly wants to write to explore.exe, like Potplayer
3) Observe PotPlayerMini64.exe (6120): SBIE2111 Prozess ist nicht zugänglich: $:explorer.exe, Aufruf OpenProcess (C0000022) access=00000040 initialized=1 messages that are supposed to be there, but at random there are examples just like above.

Those happened in hardened boxes, but I am not sure if it is limited to those types of boxes. I can't say whenever or not this also happens on an empty box, since the observed malformed strings do not appear every time.

### How often did you encounter it so far?

Mostly when the process gets started, but not sonsitently

### Affected program

Should be any that attempts to write to explorer.exe

### Download link

Not applicable, I guess.

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Those malformed strings should not show up, when they are a result of how Sandboxie opperates.

### What is your Windows edition and version?

Windows 7, SP1, 64 bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defeneder

### What version of Sandboxie are you running?

Sandboxie-Plus 1.7.2 (64 bit)

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

I have seen those before, but never thought to report them

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
[player]
Enabled=y
ConfigLevel=9
AutoRecover=y
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00eeff,ttl,2
DropAdminRights=y
BoxNameTitle=n
CopyLimitKb=81920
DontCopy=.mp4
DontCopy=.mp3
DontCopy=.avi
DontCopy=.mkv
ClosePrintSpooler=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
ForceProcess=PotPlayerMini64.exe
LeaderProcess=DTDrop64.exe
LeaderProcess=PotPlayerMini64.exe
ProcessGroup=<BlockNetAccess>,dllhost.exe
ProcessGroup=<BlockNetDevices>,
ProcessGroup=<InternetAccess>,PotPlayerMini64.exe
NotifyInternetAccessDenied=n
BlockNetworkFiles=y
HideOtherBoxes=y
ReadIpcPath=$:explorer.exe
OpenClipboard=n
UseRegDeleteV2=y
AllowNetworkAccess=!<InternetAccess>,n
AllowNetworkAccess=<BlockNetAccess>,n
UseRuleSpecificity=y
UseSecurityMode=y
NotifyProcessAccessDenied=y
UseFileDeleteV2=y
```

**Comment by DavidXanatos** [comment]
have you observed this issue with 1.8.0 as well?

**Comment by bastik-1001** [comment]
I only switched to 1.8.0 recently, but I have not seen it with that version. It may have been just an issue on how it got displayed in the log, but I wanted to report on that, since it might not be the case.

I suggest to not investigate this any further, as it appears to have disappeared in 1.8.0. Let's keep this issue open and I keep an eye open and report back if that happens again, otherwise I will close the issue.

**Comment by bastik-1001** [comment]
It might have been a glitch, in one way or another, but since version 1.8.0 (now running 1.8.1), seemed to have fixed this, I am closing this issue. If anyone runs into it, they may re-open the issue.
