### ISSUE TITLE
[REQUEST] Start to SysTray

### ISSUE THREAD

**Issue by Valinwolf** [sandboxie-plus/Sandboxie#269]
I would like to see the ability to have the SandMan interface start with windows without being an open window. This could be a setting or a hardcoded behavior.

_P.S.: You are doing amazing work! You are definitely one of my favorite software authors!_

**Comment by DavidXanatos** [comment]
that should already work this way, if it doesn't than unckecl apply check and apply the auto start checkbox in the settings

**Comment by Valinwolf** [comment]
I think I figured it out I selected start with Windows in the installer and it's opening it a second time because of how the installer sets it to auto start. So perhaps the title should be changed from request to installer bug?

**Comment by DavidXanatos** [comment]
yea but just fixed it for the next build
