### ISSUE TITLE
Guitar Rig installation in sandbox cause error getting file security

### ISSUE THREAD

**Issue by mio-19** [sandboxie-plus/Sandboxie#2691]
### Describe what you noticed and did

1. Install Guitar Rig 5 or 6
2. see `error getting file security`

### Affected program

Guitar Rig

### Download link

https://www.native-instruments.com/

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

Installed

### What is your Windows edition and version?

25295 insider

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

1.7.2

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by mio-19** [comment]
![image](https://user-images.githubusercontent.com/57285379/218318583-8b6282dc-fdcd-4d43-8aa2-dc450cbe9ee6.png)

**Comment by DavidXanatos** [comment]
please provide a direct download link its not obviuse to me where to find the software in question on that site, it ahs so mayn variosue things on it

**Comment by bastik-1001** [comment]
There appears to be a demo for Guitar Rig 6: https://www.native-instruments.com/en/products/komplete/guitar/guitar-rig-6-pro/downloads/

There is also Guitar Rig 6 Player (not sure if affected by the issue of this issue), which is free: https://www.native-instruments.com/en/products/komplete/guitar/guitar-rig-6-player/

**Comment by DavidXanatos** [comment]
With ```MsiInstallerExemptions=y``` installation works just fine with the latest 1.8.0
