### ISSUE TITLE
I ran Firefox 76 in Sandoxie 5.28 and got entries in catroot2\dberr.txt

### ISSUE THREAD

**Issue by Jimmy03** [sandboxie-plus/Sandboxie#27]
I know 5.28 is old, but any idea why this happens with Firefox 76?
Is it because Firefox is now doing their own sandboxing?  
  
I did an sfc /scannow and all appears ok, I just get those dberr.txt entries when running Firefox 76 in the default box.  Only the dberr.txt within the actual sandbox was affected.

**Comment by DavidXanatos** [comment]
u can't help you with the closed source versions sorry.
