### ISSUE TITLE
Installer Signing

### ISSUE THREAD

**Issue by Valinwolf** [sandboxie-plus/Sandboxie#270]
Are there plans to sign the installer so it shows a verified publisher?

**Comment by NewKidOnTheBlock** [comment]
See #238

**Comment by Valinwolf** [comment]
Ah, makes sense.

**Comment by DavidXanatos** [comment]
The inconvenient thing about that is that for getting the EV cert I needed to collaborate with a local company and for legal reasons while they are signing stuff for me I don't have the cert myself so whenever I need something signed I need to send that to my friend there.

I have tried signing the releases and for the 32 bit build it only helped marginally: from 16 false positives down to 12 so it does not seam worth the afford.

**Comment by Valinwolf** [comment]
It's probably something to do with it previously being signed with a "malicious" cert, where the binary signature is now in the database now. 

I was considering creating an NPO for the purpose of helping open source projects to get their drivers and installers signed. That kind of fizzled out when I realized the expense of getting the ball rolling, but I'm looking at a possible promotion at work soon so that may change. If I do get it set up, I would be happy to give you an automated way of signing executables or even giving you direct access to the cert. But that all hinges on a possibility.

**Comment by DavidXanatos** [comment]
> It's probably something to do with it previously being signed with a "malicious" cert, where the binary signature is now in the database now.

No I don't think so I have now also switched to a more recent SDK/WDK and from VS2015 to VS2019 the files shouldn't look anything alike.

Its also strange that the most false positives are in the 32 bit version and not in the 64 bit to me it all looks like its just Shoddy detection from the AV's
If it would have been something I did i would expect the false positives on booth versions to be roughly the same.

What is also quite BS is that even after signing the 32 bit installer the false positives only went down from 16 to 12 WTF

If you can provide a convenient signing solution that would be great. Expect to have to set up an own server for that (locally not in some data center) as the EV certificates are provided only on hardware tokens not a *.pfx files.

**Comment by Valinwolf** [comment]
> > It's probably something to do with it previously being signed with a "malicious" cert, where the binary signature is now in the database now.
> 
> No I don't think so I have now also switched to a more recent SDK/WDK and from VS2015 to VS2019 the files shouldn't look anything alike.
> 
> Its also strange that the most false positives are in the 32 bit version and not in the 64 bit to me it all looks like its just Shoddy detection from the AV's
> If it would have been something I did i would expect the false positives on booth versions to be roughly the same.
> 
> What is also quite BS is that even after signing the 32 bit installer the false positives only went down from 16 to 12 WTF

That is very strange... I definitely agree with that assessment, though.

> If you can provide a convenient signing solution that would be great. Expect to have to set up an own server for that (locally not in some data center) as the EV certificates are provided only on hardware tokens not a *.pfx files.

Good to know. I'll make sure to look into getting a "small office" for the NPO. There used to be a lot of offsite hardware hosts, but it's become a very small business and mostly on the other side of the planet from me. It would be nice to migrate my current servers to personal hardware that I have extensive control of. I've never done any EV code signing, so it'll be a new venture entirely for me. Again though, it's going to hinge on me getting this promotion. Best part is the promotion is less work than I do now, so I'll have more time and money to work on pet projects like an NPO. 😁

**Comment by isaak654** [comment]
> I have tried signing the releases and for the 32 bit build it only helped marginally: from 16 false positives down to 12 so it does not seam worth the afford.

@DavidXanatos
Please consider to sign all files in 64 bit builds... who still uses a 32 bit OS these days?

**Comment by stephtr** [comment]
Starting with [today's release](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.6.5) the installer and all contained files are now signed!

**Comment by typpos** [comment]
It's signed !!! Chrome happy! Me putting champagne in fridge. Thank you David.
