### ISSUE TITLE
AnyDesk completely blank

### ISSUE THREAD

**Issue by Nypheena** [sandboxie-plus/Sandboxie#2701]
### Describe what you noticed and did

Download AnyDesk.exe and run

![image](https://user-images.githubusercontent.com/16083155/218914728-7c20c919-6154-467a-aa58-1be23284ef08.png)

### How often did you encounter it so far?

always except when I click to close and it pops up with asking if I wanna install then it finally displays

### Affected program

AnyDesk

### Download link

https://anydesk.com/en/downloads/windows

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

It's expected to display this

![image](https://user-images.githubusercontent.com/16083155/218914839-6b4c2a61-1d1b-42e7-801a-d7b6b0b189d8.png)

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

What it ships with microsoft Defender

### What version of Sandboxie are you running?

Latest

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

I don't know

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no

### Trace log

[AnyDesk.log](https://github.com/sandboxie-plus/Sandboxie/files/10738866/AnyDesk.log)

**Comment by offhub** [comment]
Try adding the following line to your box config:

```
OpenIpcPath=*\BaseNamedObjects*\ad_*
```

**Comment by DavidXanatos** [comment]
plese try 1.8.0 once its out it has a couple improvements which shoudl help

**Comment by offhub** [comment]
> Though if I install into the sandbox it doesn't wanna run and seems to leave a rundll32.exe open indefinitely after install and its attempt to make anydesk.exe --service run also quits

1. Terminate all programs in the sandbox when the installation process gets stuck (Don't delete)
2. Right click on the sandbox > Run > Run from Start Menu > Desktop > AnyDesk (click NO to UAC)

**Comment by Tha14** [comment]
> > Try adding the following line to your box config:
> > ```
> > OpenIpcPath=AnyDesk.exe,*\BaseNamedObjects*\ad_*
> > ```
> 
> That Worked
> 
> Though if I install into the sandbox it doesn't wanna run and seems to leave a rundll32.exe open indefinitely after install and its attempt to make anydesk.exe --service run also quits

Anydesk seems to use a mutex to prevent running multiple instances of it; so if you're running it on host and try to run it inside sandboxie, with the ipc resource access enabled, the window that is supposed to appear will terminate instead.

It would be nice if sandboxie could manage it's own IPC like it does it's files and registry but it is probably hard to implement.

So if you want to use anydesk inside sandboxie you will have to first terminate the anydesk instance running on you host.

**Comment by DavidXanatos** [comment]
> 
> It would be nice if sandboxie could manage it's own IPC like it does it's files and registry but it is probably hard to implement.
> 

Sandboxie already does this, but it seams this part is quite bugged/incomplete, the issue will be fixed in the next build 1.8.1

**Comment by jon-peel** [comment]
Hello, I cannot get AnyDesk to run inside SandboxIE (1.16.0)
I tried the INI tweak, and I enabled "Drop Rights", but anydesk displays the blank screen, as posted above.

**Comment by offhub** [comment]
@jon-peel 

The previous setting is required if the AnyDesk service is running outside the sandbox.

If you only use AnyDesk from within the sandbox, add the following setting to your configuration and then try running AnyDesk. [^1]

Note: This setting reduces sandbox isolation!

```ini
OpenIpcPath=AnyDesk.exe,\RPC Control\epmapper
```

```ini
DropAdminRights=y
FakeAdminRights=y
```

[^1]: Tested with AnyDesk 9.5.9.

**Comment by birdie-github** [comment]
Which sadly means this issue is still reproducible/not resolved.

**Comment by Temtaime** [comment]
Still not working with latest sandboxie. Using tweaks from this issue makes no difference.

@DavidXanatos can you reopen the issue, please ?

**Comment by birdie-github** [comment]
> Still not working with latest sandboxie. Using tweaks from this issue makes no difference.
> 
> [@DavidXanatos](https://github.com/DavidXanatos) can you reopen the issue, please ?

This
```
OpenIpcPath=AnyDesk.exe,\RPC Control\epmapper
```

Fixes the issue entirely.

**Comment by offhub** [comment]
You can also try these settings.

```ini
StartService=AnyDesk
PreferExternalManifest=AnyDesk.exe,y
```

**Comment by Nypheena** [comment]
only version that works for me is 8.0.8.0, newer versions won't load and I'm not installing their service nor allowing them through to host pc just to display stuff
