### ISSUE TITLE
I have some questions about virtualization solutions V1 and V2

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#2702]
### Is your feature request related to a problem or use case?

Is there any difference between the newly introduced V2 and V1 solutions? Is V1 the same solution used in previous versions, and does V2 have any performance and security advantages over V1?

### Describe the solution you'd like

nothing

**Comment by DavidXanatos** [comment]
V12 is the old way as sandboxie always worked
V2 (https://sandboxie-plus.com/sandboxie/delete-v2/) is a new method, it has no security advantages or disadvantages, but it makes host folder and key renaming work from within the sandbox properly, as well as fixes various minor inconsistencies the V1 implementation causes in certain edge cases, overall delete V2 provides a better compatibility.
