### ISSUE TITLE
Pre-defined sandboxie location for each sandbox

### ISSUE THREAD

**Issue by Luro223** [sandboxie-plus/Sandboxie#2709]
### Is your feature request related to a problem or use case?

I think it will be useful if you add the pre-defined location for each sandbox.

### Describe the solution you'd like

For example I have the volume K: I: R:
K: for documents and office apps
I: for games
R: as a RamDisk for temporary and untrusted apps
I'd like to use the following sandboxes for each location individually as a feature inside each sandboxie like "Pre-defined location of [sandbox]" this will be a really useful feature for others too.

**Comment by bastik-1001** [comment]
Unless I misunderstand what you are asking for, you can already set custom locations for each box.

`FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%` is the default location, but you can set `FileRootPath=` to some other location per sandbox, even on another drive like `FileRootPath=I:\Games\%SANDBOX%`.

The new box wizard in Sandboxie Plus allows to select the folder the sandbox is stored in, after selecting to configure the advanced options.

**Comment by DavidXanatos** [comment]
you can choose the location when creating a sandbox in the new box creation wizard
![grafik](https://user-images.githubusercontent.com/3890945/219939508-abecd294-250b-4f77-9581-1d9b3c384669.png)

**Comment by Luro223** [comment]
@DavidXanatos @bastik-1001 Ok, I thibk the issue is resolved then, Thanks for your reply and time.
