### ISSUE TITLE
Run Un-Sandboxed runs inside sandbox

### ISSUE THREAD

**Issue by Germs2004** [sandboxie-plus/Sandboxie#2710]
### Describe what you noticed and did

1) Put a program or PDF file in a sandbox.
2) Navigate to that folder with regular Windows Explorer.
3) Right click on the exe or pdf file, and choose Run Un-Sandboxed.

Expected: Program runs outside the sandbox, or PDF opens outside of sandbox.

Actual: Program/PDF opens inside the sandbox.  I can see the processes in the treeview of the Sandboxie program, and if I do the drag/drop tool onto the program's window, Sandboxie confirms the program is running in the sandbox that the files are stored in.

Reason to fix: Troubleshooting a sandboxed program.  I want to see if the program is broken due to Sandboxie or for some other reason, so I want to run the program momentarily without Sandboxie protection.

### How often did you encounter it so far?

every time

### Affected program

every program, every PDF file

### Download link

Not relevant

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Program runs outside the sandbox, or PDF opens outside of sandbox.

### What is your Windows edition and version?

Windows 11 Pro 64 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Defender

### What version of Sandboxie are you running?

1.7.2

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

I think so, but don't remember

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
[Options]
SortGroupsFirst=true
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
TemplateReject=WindowsLive
TemplateReject=OfficeLicensing
TemplateReject=OfficeClickToRun
TemplateReject=7zipShellEx
Template=WindowsRasMan
Template=Edge_Fix
DefaultBox=DefaultBox

[MyTestSandbox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
UseFileDeleteV2=y
UseRegDeleteV2=y
AllowNetworkAccess=!<InternetAccess>,n
BoxNameTitle=n
DropAdminRights=y
FakeAdminRights=y
CopyLimitKb=81920
```

**Comment by offhub** [comment]
(Workaround?) Create a shortcut with the following target:

```
"C:\Program Files\Sandboxie-Plus\Start.exe" /disable_force
```

You can then drag and drop applications/files onto this shortcut to run them outside the sandbox.
