### ISSUE TITLE
Unable to install Edge extensions. Could not unzip extension

### ISSUE THREAD

**Issue by mysteriously** [sandboxie-plus/Sandboxie#2713]
### Describe what you noticed and did

I can not install some Edge extensions due to 'Could not unzip extension' error. It works if I delete Sandboxie.ini, create new box and add Template=Edge_Fix to [GlobalSettings]

https://microsoftedge.microsoft.com/addons/detail/sponsorblock-for-youtube-/mbmgnelfcpoecdepckhlhegpcehmpmji

![image](https://user-images.githubusercontent.com/17072890/220471107-39e23665-569c-4c42-a697-289542cb9a52.png)

![image](https://user-images.githubusercontent.com/17072890/220471139-f1b57d9b-6cee-4141-82af-a8b95ebc1f76.png)

### How often did you encounter it so far?

Every time

### Affected program

Edge 109.0.1518.78

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Extension has been installed

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Eset Endpoint Security 10

### What version of Sandboxie are you running?

1.6.6

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

no

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
How to troubleshoot it? There is nothing in SBIE messages
```

**Comment by offhub** [comment]
I couldn't reproduce the issue. Tested on VM:
```
Windows 11 22H2 [22621.1105]
Microsoft Edge Version 109.0.1518.61 (Official build) (64-bit)
ESET is not installed
```

> How to troubleshoot it? There is nothing in SBIE messages
1. Sandboxie-Plus > `View` > Enable `Trace Logging`
2. From lower pane > Select: `Trace Log` > Disable: `Monitor Mode` > Select `Type: File` and `Status: Closed`
3. Start the Edge browser in sandbox and try to install the extension and close the browser after getting the error.
4. Selecting the sandbox from the list will show if there is any blocked file/folder access.
    - If there is no blocked access, the problem may be caused by another program.*
    - If there is blocked access, you may need to change the file rules accordingly.
    - Try with the new browser profile.

*You can monitor file system activity using Process Monitor.
`https://learn.microsoft.com/en-us/sysinternals/downloads/procmon`

**Comment by mysteriously** [comment]
Thanks, I will take a look at that.

I commended out pretty much everything from global section and replaced sandbox settings with default from default sandboxie.ini. The issue still occured

**Comment by mysteriously** [comment]
1. Delete Sandboxie.ini
2. Create new box
3. Add `Template=Edge_Fix` to Sandboxie.ini in [GlobalSettings]
4. Open Edge in the sandbox you just created
5. SponsorBlock for YouTube can be installed
6. Clear the content of the box
7. Add `ClosedFilePath=%SystemDrive%\Users*\Music*` to Sandboxie.ini in [GlobalSettings]
8. Reload the .ini file **twice** if you used 3rd party program to edit it!*
9. SponsorBlock for YouTube can not be installed anymore

* I will add more info here https://github.com/sandboxie-plus/Sandboxie/discussions/2633

**Comment by DavidXanatos** [comment]
|Process|                                  |Type|     |Status|   |Value|                                                                                                                

msedge.exe (29532, 21708) - 17:12:13.960   File (U)   Closed     \Device\HarddiskVolume4\Users\Root\AppData\Local\Temp\scoped_dir29532_1687080842\CRX_INSTALL\icons\music-note.svg   
msedge.exe (29532, 21708) - 17:12:13.960   File (U)   Closed     \Device\HarddiskVolume4\Users\Root\AppData\Local\Temp\scoped_dir29532_1687080842\CRX_INSTALL\icons\music-note.svg   

your ClosedFilePath=%SystemDrive%\Users*\Music* is to unspecific and blocks the icon file for the extension, or something along this line.

fix your closed path and problem solved
