### ISSUE TITLE
Make Certificate.dat file unreadable by sandboxed programs

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2722]
### Describe what you noticed and did

1. Add `ClosedFilePath=%SbieHome%\Certificate.dat`
2. Run `cmd.exe` as sandboxed
3. `type "%ProgramFiles%\Sandboxie-Plus\Certificate.dat"`
4. `Certificate.dat` can be read

```
cmd.exe File (D) Trace \Device\HarddiskVolume1\Program Files (FA) 00100080.01.00000021                                  
cmd.exe File (D) Trace \Device\HarddiskVolume1\Program Files\Sandboxie-Plus (FA) 00100001.01.00000021                   
cmd.exe File (D) Trace \Device\HarddiskVolume1\Program Files\Sandboxie-Plus (FA) 00100080.01.00000021                   
cmd.exe File (D) Trace \Device\HarddiskVolume1\Program Files\Sandboxie-Plus\Certificate.dat (FA) 00000080.01.00200000   
cmd.exe File (D) Trace \Device\HarddiskVolume1\Program Files\Sandboxie-Plus\Certificate.dat (FA) 00120089.01.00000060   
```

https://github.com/sandboxie-plus/Sandboxie/blob/f103741fe35c3694b782f915489fb2a16248dbcc/Sandboxie/core/drv/file.c#L1357-L1374

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Certificate.dat should not be read by sandboxed programs.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.7.2 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by sepcnt** [comment]
File access right in %SbieHome% is so weird: it seems that you cannot create or modify file in this dir but you cannot ban access as well.
