### ISSUE TITLE
An error is reported after Ansys Fluent 2020R1 starts.

### ISSUE THREAD

**Issue by RisingYoung-Learn** [sandboxie-plus/Sandboxie#2725]
### Describe what you noticed and did

1. Download the trial version of Ansys Fluent 2020R1, download address: https://www.ansys.com/products/fluids/ansys-fluent/ansys-fluent-trial
2. Install the Fluent program in step 1.
3. Drag the desktop shortcut Fluent 2020 R1 into SandMan.
4. Click the Start button in the Fluent launcher.
<img width="735" alt="fluent launcher" src="https://user-images.githubusercontent.com/54743518/221744153-41b7b8e0-5ddb-4233-8843-fffc1b4fea05.png">

6. After Fluent starts, an error message is output in the Console.
<img width="1011" alt="fluent error" src="https://user-images.githubusercontent.com/54743518/221744194-18602aed-cae4-46ab-9874-5763be7d803b.png">

### How often did you encounter it so far?

Appears every time you use.

### Affected program

Ansys Fluent 2020R1

### Download link

https://www.ansys.com/products/fluids/ansys-fluent/ansys-fluent-trial

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Fluent starts normally without outputting any error messages. Same behavior as running outside of Sandboxie.

### What is your Windows edition and version?

Windows Server 2019 Standard 

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie plus 1.7.2 64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]
DefaultBox=DefaultBox
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=AdobeLicensing
Template=7zipShellEx

[UserSettings_4BC00582]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
MsiInstallerExemptions=y
UnrestrictedToken=y
UnfilteredToken=y
KeepTokenIntegrity=y
UnfilteredToken=y

[UserSettings_AFFE086D]
SbieCtrl_AutoStartAgent=SandMan.exe
```

**Comment by DavidXanatos** [comment]
The trail request page sends me to registration which wants a customer ID hence please paste a direct downlaod link to the trail
