### ISSUE TITLE
Sandboxie Plus 0.52 - supportforum and documentation not sandboxed

### ISSUE THREAD

**Issue by KlausiMeier** [sandboxie-plus/Sandboxie#273]
Hi,
opening the supportforum or documentation from help menu, a new, unboxed browser session is starting for it.
This is a risky topic for me, if I just move on browsing from there...

Would be good for me to implement the question to start sandboxed and in which one.
Or simply to start it in the default box or in an already opened boxed browser automatically.

Can you check this, please?

Thanks a lot.

**Comment by DavidXanatos** [comment]
pffff.... that is a bit convoluted to do doe to ways how Qt handles link clicks but yea its doable and I was thinking if its worth the afford...
Will add it to the next build.
