### ISSUE TITLE
Some SandMan UI issues 

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2733]
### Describe what you noticed and did

1. `Sandbox Options` > `Advanced Options` > `Users` > `Remove` button does not work.
2. ` *32` is added to the end of 32-bit application names in program selection lists. (someprogram.exe *32)
3. When `UseFileDeleteV2` and/or `UseRegDeleteV2` is set to `Y` globally and `Virtualization scheme: Version 1` is selected from sandbox settings, `UseFileDeleteV2` and/or `UseRegDeleteV2` settings are not set to `N` accordingly.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

1. It should remove the selected user.
2. It should trim the unnecessary parts.
3. It should also set it to `N` for the sandbox if they are set to `Y` globally.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.8.0 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
1 and 3 fixed, 2 is intentional

**Comment by offhub** [comment]
2. However, when we select the program from the list and assign it to a setting, it causes that setting to not work. (ex. `ForceProcess=example.exe *32`) The suffix must be manually deleted for the setting to work.

**Comment by DavidXanatos** [comment]
sure? useing this menu
![grafik](https://user-images.githubusercontent.com/3890945/224804700-06835eb5-66ee-410d-9146-1b7dd9fff535.png)

for me worked just fine no *32 was added to the ini
