### ISSUE TITLE
NIKKE has detected a virtual environment and cannot run.

### ISSUE THREAD

**Issue by Brouzy** [sandboxie-plus/Sandboxie#2734]
### Describe what you noticed and did

Install NIKKE for PC in Sandboxie.
Start nikke_launcher.exe in Sandboxie.
Login account.
Start the game.
![未标题-3](https://user-images.githubusercontent.com/20435074/222968399-1f30956e-b6bc-4014-bf9c-21538086d65e.png)

### Affected program

nikke.exe

### Download link

https://nikke-jp.com/nikkeminiloader0.0.6.169.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

The game runs normally.

### What is your Windows edition and version?

Windows 10 Enterprise 21H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus 1.7.2 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
NetworkEnableWFP=y
DefaultBox=China
FileRootPath=F:\\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=Edge_Fix

[UserSettings_0CC2021B]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[China]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=QQ
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
AutoRecover=y
ClosedFilePath=G:\
ClosedFilePath=E:\
ClosedFilePath=D:\
ClosedFilePath=%AppData%\clash_win
ClosedFilePath=%UserProfile%\.config
ClosedFilePath=%UserProfile%\AppData\Local\Microsoft
ClosedFilePath=%UserProfile%\AppData\Local\Google
AllowNetworkAccess=<BlockNetAccess>,n
BoxNameTitle=n
CopyLimitKb=81920
NeverDelete=y
```

**Comment by bastik-1001** [comment]
It appears to be a multiplayer game, so they may try to check if the program is run in a virtual environment to limit the development or the usage of cheats.

Something you may try is using [SbieHide](https://github.com/VeroFess/SbieHide). It may or may not work. If it works and people use it to cheat, there might be an arms race, as they might feel the need to try to detect Sandboxie by some other means.

**Comment by Brouzy** [comment]
OK, I use SbieHide to avoid the pop-up "detected a virtual environment" prompt.
But when the game starts, it appears four times "nikke.exe (18996): SBIE2205 The service is not implemented: NtQueryDirectoryObject" and then freezes.

**Comment by bastik-1001** [comment]
This might turn this into a feature request to implement this service. I have no idea what the chances are for that to happen.

As I side note, I am glad that the third-party software was helpful, in the sense of getting around the virtual environment prompt.

**Comment by isaak654** [comment]
Enabling the Debug tab might be worth a try if you want to experiment with several compatibility settings: https://github.com/sandboxie-plus/Sandboxie/issues/2134#issuecomment-1215466315

**Comment by isaak654** [comment]
It might be worth a try to enable the Debug tab if you want to experiment with several compatibility settings: https://github.com/sandboxie-plus/Sandboxie/issues/2134#issuecomment-1215466315

**Comment by DavidXanatos** [comment]
I'm surprized anythign is using NtQueryDirectoryObject normally programs don't need to list the NT namespace, also while the error says its nto implemented, this doe snto mean that an error is returned, only hat the view returned by the unmodified NtQueryDirectoryObject does nto include the sandboxed items.
Hence perhaps the actuall issue is a different once, and this error is just a red herring.
I'll add an api trace function to one of the upcomming builds with it you should be able to determine when thee program actually terminates if its in proximity to NtQueryDirectoryObject  or unrelated

**Comment by TFWol** [comment]
> I'm surprised, anything is using NtQueryDirectoryObject (normally programs) don't need to list the NT namespace,

I only did a quick search for the error and haven't looked at workarounds yet, but a good example program to see how often the error fires is when using [Git GUI](https://git-scm.com/download/win) . 
It's with every key press in the Git Bash tool. Still works, but sometimes freezes the SB gui.

**Comment by DavidXanatos** [comment]
@TFWol ah great.... it seams to be a pattern with those tools that originated with linux that they do exotic things under windows....
I'll look inti it, Git Bash tool is a good text candidate, surely even open source what one could wish for more :D

**Comment by DavidXanatos** [comment]
in the next build the NtQueryDirectoryObject  will be fixed, if that helps NIKE or not is a different story

**Comment by GunGunGun** [comment]
> in the next build the NtQueryDirectoryObject will be fixed, if that helps NIKKE or not is a different story

I can confirm, it works in App Compart box:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/6913739/828078cb-87ff-48e7-9bbc-9e00fe2d1d4d)

This is such a good game, glad that it's playable in Sandboxie.
