### ISSUE TITLE
"Windows installer service could not be accessed" etc (again)

### ISSUE THREAD

**Issue by AP2020C** [sandboxie-plus/Sandboxie#2739]
### Describe what you noticed and did

> The Windows Installer Service could not be accessed. This can occur if you are running Windows in safe mode, or if the Windows Installer is not correctly installed. Contact your support personnel for assistance.

Appears while I try to install some programs in Sandboxie Plus 1.0.20.
I tried (unhappily) to disable Protect sandboxed system, as suggested https://github.com/sandboxie-plus/Sandboxie/issues/567
but the problem remained.

### How often did you encounter it so far?

Today every time I tried to install this program. In general, there are programs that refuse to be installed in Sandboxie and give errors similar to this one.

### Affected program

Audials one 2023 (trial)

### Download link

https://audials.com/en/download

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

Being able to install this, and other programs, in Sandboxie without letting the program know it is in Sandboxie

### What is your Windows edition and version?

Windows 10 Edu 22H2 x64

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.0.20

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Initially it was a standard sandbox

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=WindowsRasMan
Template=7zipShellEx
Template=OfficeClickToRun
Template=WindowsLive
Template=OfficeLicensing

[DefaultBox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Enabled=y
CopyLimitKb=1191162
BoxNameTitle=n
FakeAdminRights=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices

[UserSettings_1D080342]

SbieCtrl_UserName=***
SbieCtrl_NextUpdateCheck=1653223019
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_WindowCoords=896,408,1024,632
SbieCtrl_ActiveView=40021
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_RecoverTarget=C:\Users\***\Desktop\temp
SbieCtrl_RecoverTarget=C:\Users\***\Desktop
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_AutoApplySettings=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_BoxExpandedView=***
SbieCtrl_AutoStartAgent=SandMan.exe
BoxCollapsedView=***
```

**Comment by DavidXanatos** [comment]
Try an up to date build, and use ```MsiInstallerExemptions=y```
this way installation forked for me just fine.

**Comment by DavidXanatos** [comment]
Yes when its on it runs the msiserver with a system token that incerases the potential attack surface so its recommended to not have it on when not required.
