### ISSUE TITLE
Update to v5.45.1, only English interface is available.

### ISSUE THREAD

**Issue by FanXiangTM** [sandboxie-plus/Sandboxie#274]
Update to v5.45.1, only English interface is available. I had to uninstall and reinstall the previous version

**Comment by DavidXanatos** [comment]
but after reinstall all is fine?

**Comment by FanXiangTM** [comment]
> 但是重新安装后一切都好吗？

I mean, version 5.45.1 no longer provides languages other than English, so I had to uninstall and install version 5.43.6

**Comment by isaak654** [comment]
> 
> 
> > 但是重新安装后一切都好吗？
> 
> I mean, version 5.45.1 no longer provides languages other than English, so I had to uninstall and install version 5.43.6

Italian language loads fine on my end, more likely it's some specific encoding issue related to eastern languages.

**Comment by isaak654** [comment]
> 
> 
> > 但是重新安装后一切都好吗？
> 
> I mean, version 5.45.1 no longer provides languages other than English, so I had to uninstall and install version 5.43.6

A new patch was released today and it should fix your issue:
https://github.com/sandboxie-plus/Sandboxie/issues/268#issuecomment-751214490

**Comment by DavidXanatos** [comment]
i have uploaded a new pair of installers for the classical version that should solve the localization issues.
