### ISSUE TITLE
Breakout non-executable files: allows specified files to be opened outside the sandbox

### ISSUE THREAD

**Issue by gexgd0419** [sandboxie-plus/Sandboxie#2741]
### Is your feature request related to a problem or use case?

I'm using an IM software inside a sandbox. Its "received files" folder is outside the sandbox directory, and it can write to the folder directly.

Usually I'd prefer to open the files in "received files" folder outside the sandbox (or inside another sandbox). As the folder is outside the sandbox directory, I can just open the files using Explorer, and they won't be automatically sandboxed. The IM software also allows to open the received files via its own UI, but as it is running sandboxed, the program used to open the specified file will also be run in the same sandbox.

`ForceFolder` can force all programs and non-executable files to be opened in a sandbox. `BreakoutFolder` can break out programs, but not non-executable files. The program used to open a file in a breakout folder still runs inside the sandbox.

### Describe the solution you'd like

You can give `BreakoutFolder` the ability to break out non-executable files as well, just like its counterpart `ForceFolder`.

Also, opening files in breakout folders should work when the program used to open the file is a Metro/UWP app.

**Comment by DavidXanatos** [comment]
There are 4 factors used in the force process mechanism
1. If the parent process is sandboxed itself
2. Process Name and Process Path
3. The Current Working Directory the program is to be started in
4. The Path of a, if present, document passed as an argument to the program

When opening the file from the IM software the opening program falls certainly into case 1 and perhaps in case 3 depending on how its started by the IM software software.

Can you check using a took like TaskExplorer what working directory does the viewer process get?

**Comment by DavidXanatos** [comment]
SECURITY WARNING: if you set a folder sandboxed processes can write to as break out folder, any malware will be able to put a malicious executable there and execute it without sandboxie protection. So please DO NOT DO THAT!!!

I think what will be needed here is a new feature BerakoutDocument where you can specify folders and document extensions which are to be broken out this way it could be sued safely as long as you don't specify *.cmd or other unsafe extensions explicitly.

**Comment by blap** [comment]
> SECURITY WARNING: if you set a folder sandboxed processes can write to as break out folder, any malware will be able to put a malicious executable there and execute it without sandboxie protection. So please DO NOT DO THAT!!!
> 
> I think what will be needed here is a new feature BerakoutDocument where you can specify folders and document extensions which are to be broken out this way it could be sued safely as long as you don't specify *.cmd or other unsafe extensions explicitly.

manually specify extensions to be open will be excellent!

**Comment by DavidXanatos** [comment]
please note that this feature is now available in the patreon insider builds for the higher tiers
