### ISSUE TITLE
SBIE1231 Initialization failed for process  [C0000001 / A4]

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#2747]
### Describe what you noticed and did

When I run software, it tries to start subprocess which fails to run

```
|Time|         |Message|                                                                                 

21:18:45.709   SubprocessName.exe (12396): SBIE1231 Initialization failed for process  [C0000001 / A4]   
21:18:45.709   PID 3788: SBIE2314 Cancelling process SubprocessName.exe                                  
```

How can I troubleshoot it. The software opens, but I can not interact with it few seconds later

### How often did you encounter it so far?

Always

### Affected program

Not relevant

### Download link

Not available

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Process.exe should be able to start Subprocess.exe

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET Endpoint Security 10.0.2045.0

### What version of Sandboxie are you running?

Sandboxie-Plus v1.8.0

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
as there are no more infos and the user is gone i'll close this
