### ISSUE TITLE
QInputDialog shows extra "?"

### ISSUE THREAD

**Issue by hippalectryon-0** [sandboxie-plus/Sandboxie#2748]
### Describe what you noticed and did

All the QInputDialog objects in Sandboxie use the default flags, and therefore have a "?" option next to the closing "X" option. However, this "?" button doesn't do anything.

Example:
![image](https://user-images.githubusercontent.com/6502864/224846475-2ea49746-1566-473f-be23-3a2fff51c72f.png)

 It can easily be removed, for instance by adding `QApplication::setAttribute(Qt::AA_DisableWindowContextHelpButton);` in `main.cpp` before line 59 https://github.com/sandboxie-plus/Sandboxie/blob/bf11630f2ef30e5ebbcc876807433cddb5bfcc75/SandboxiePlus/SandMan/main.cpp#L59

### How often did you encounter it so far?

Not relevant

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Either the question mark should have a purpose, or be removed

### What is your Windows edition and version?

Not relevant

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie Plus 1.8.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
fix commited, 
seams in qt6 this flag is obsolete: https://bugreports.qt.io/browse/QTBUG-70431
