### ISSUE TITLE
"Microsoft Edge 111.0.1661.43 stable" cannot run normally in sandboxie

### ISSUE THREAD

**Issue by 6Tom** [sandboxie-plus/Sandboxie#2754]
### Describe what you noticed and did

Msedge cannot load any pages since the last update. The settings and extension pages cannot be loaded normally, either.

### How often did you encounter it so far?

Since today (2023-03-15, 18:57 Washington time)

### Affected program

Microsoft Edge 111.0.1661.43 stable

### Download link

https://www.microsoft.com/en-us/edge

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

It should be able to browse websites, install extensions, and so on as before.

### What is your Windows edition and version?

Windows 11 Pro 22H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.6.7 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

Since 1.6.7 64-bit

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
I haven't changed the factory settings.

I also tested it in VMware virtual machine and the result is the same.
```

**Comment by offhub** [comment]
The Sandboxie version you are using is old. Please try again after updating Sandboxie to the latest version.

https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.7.2

**Comment by 6Tom** [comment]
Thank you very much for your reply. It has been resolved.

I'm really sorry. Last time there was an update, I was doing other things, so I closed the update. Later, I forgot. I thought I was using the latest version.
