### ISSUE TITLE
Installer title outdated?

### ISSUE THREAD

**Issue by nedsociety** [sandboxie-plus/Sandboxie#276]
![image](https://user-images.githubusercontent.com/11943013/103093990-72edc080-463f-11eb-94e2-540a92a44f05.png)

It installed 0.5.2 as intended (Sandboxie-Plus-x64-v0.5.2.exe) though.

**Comment by DavidXanatos** [comment]
Yes!
I forgot to update the title, wont happen in future I made the title now being read from a provided viable like for the filename.
