### ISSUE TITLE
Simplified mechanism to add new browser templates

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2761]
### Is your feature request related to a problem or use case?

Original reference: https://www.wilderssecurity.com/threads/new-box-creation-wizard-for-1-7-0-or-so.449445/#post-3122225

> For browsers for instance, there are a list just for convenience so the user can tick the boxes of what he
wants to give Sandboxie access to for each browser. It should be easier to add and remove browsers to that predefined list. Some browsers are hardly used, Slimjet, so their presence is based on an old assumption, and at the expense, nowadays, of someone more used.
>
> The user should only have to browse to the browsers exe, click it and, voila, it shows up in the list with all options to tick like now. And, those that exist should be easier to remove with just a "Remove" button. I know many that find it tedious to add their browser, when they finally have figured out how to do it, as the default one so they skip Sandboxie instead. And I think you can see that with my example, it would be very easy to handle this and that would be a huge step forward for user convenience and for creating a more modern functionality in Sandboxie. A functionality that has been the same now in ages and, as I said, quite old fashioned compared to how smooth "add and remove" functions are in other programs in general.
>
> So if one changes browser often, try new ones, then the action now is, unsimple.
>
> As I mentioned, there are some handlings in Sandboxie that has been with it since the beginning, things that it is time to modernize.
I mostly think of Classic version. 

### Describe the solution you'd like

Developer's reply: https://www.wilderssecurity.com/threads/new-box-creation-wizard-for-1-7-0-or-so.449445/#post-3122235

> basically nowadays there is Chrome and FireFox and _nothing_ else
all these so called various other browsers are just forks of one of the two,
so knowing how they behave we could indeed simplify the mechanism of adding new browser templates,
the user would only need to browse to the browser file and then browse to the user profile location,
with this info we should be able to detect if it is chromium or firefox based and generate the right paths.
> 
> I will put that on my todo, if you don't see it in a few weeks please remind me, or open a github feature request for this.

**Comment by blap** [comment]
related #2366

**Comment by DavidXanatos** [comment]
I'm working on that should be in the next build
