### ISSUE TITLE
SandboxiePlus/SandMan/main.cpp/main() function called multiple times, and also again on SandMan exit

### ISSUE THREAD

**Issue by Sapour** [sandboxie-plus/Sandboxie#2767]
### Describe what you noticed and did

The SandboxiePlus/SandMan/main.cpp/main() function is called twice in quick succession on SamdMan.exe start, and also again on SandMan.exe exit. I assume this is to do with Qt.

To reproduce - just put a statement like `OutputDebugStringA("START");` at beginning of main(), open DebugView and launch/shutdown SandMan.exe.

Not that familiar with Qt, but I briefly looked into it and thing's like this can apparently occur if you hook up Signal/Slot in Qt GUI designed, as well as in the code. As I said though, I'm not that familiar with Qt, so could be completely off with idea.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

IF it's expectd for SandMan.exe's main() function to be called twice on startup and once on exit, you can ignore this, but it seem's a bit odd it is called multiple times.

### What is your Windows edition and version?

Win 10 Enterprise 22H2 x64

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

N/A

### What version of Sandboxie are you running?

Sandboxie Plus 1.8.1 pre-release

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
I can't reproduce this issue

**Comment by Sapour** [comment]
I was using Portable, so that's probably the issue. Let me confirm though before closing.
