### ISSUE TITLE
LibreWolf issues on YouTube in v.1.8.2

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#2780]
### Describe what you noticed and did

1. Use LibreWolf to go on YouTube
2. Get this error message: 
![image](https://user-images.githubusercontent.com/12563436/229348555-dd4f7b96-9208-44d6-9417-36d21258a0fb.png)

3. Watch a video, it probably works
4. Pause the video
5. Unpause the video
6. Notice it doesn't really unpause, it just spins

### How often did you encounter it so far?

Whenever I go on YouTube

### Affected program

LibreWolf, latest version

### Download link

LibreWolf's website, same thing probably happens with Firefox

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

It should work as intended, as it did in 1.8.1

### What is your Windows edition and version?

Windows 10 Edu 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.8.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Sandboxie-Plus 1.8.2

### In which sandbox type you have this problem?

In a hardened sandbox with data protection (red sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

The exact same as here:

https://github.com/sandboxie-plus/Sandboxie/issues/2778#issue-1650355999

**Comment by offhub** [comment]
Try 1.8.2**a**
https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.8.2/Sandboxie-Plus-x64-v1.8.2a.exe
