### ISSUE TITLE
[Plus UI] Tray indicator for pending updates keeps blinking even after disabling updates check

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2790]
### Original reference: https://www.wilderssecurity.com/threads/sandboxie-plus-1-7-2.450341/#post-3140293

> How do I stop the tray icon &nbsp; ![IconSun.jpg](https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/17ac1af2f3442440dc4568ac15080f096838231f/SandboxiePlus/SandMan/Resources/IconSun.png) from blinking without installing an update? 
>
> Notify setting gets greyed out as soon as I untick the box which means Notifications are disabled too, I assume.
>
> ![108730-4544bc15f6ec34ae48692557db47403a](https://user-images.githubusercontent.com/12372772/230436006-8ef3b0e0-9b41-4364-9439-45dd5e351a02.png)
>
> Seems that when sbie is aware of an update and start blinking, it gets stubborn and wants you to apply it wanting or not.

**Comment by DavidXanatos** [comment]
The idea is that in this state you can click on the tehre is an update label and when choosing cancel it will go away, but I noticed that the cancel button is missing ups
