### ISSUE TITLE
The default sandbox name "New Box" in the new create sandbox guide is translated.

### ISSUE THREAD

**Issue by okrc** [sandboxie-plus/Sandboxie#2792]
### Describe what you noticed and did

https://github.com/sandboxie-plus/Sandboxie/blob/82d394b1f8b09a80233c031308ac65a9dd3ad7bd/SandboxiePlus/SandMan/Wizards/NewBoxWizard.cpp#L184-L188

Whether this is expected behavior.

### What version of Sandboxie are you running?

Sandboxie Plus 1.8.3 64bit

**Comment by DavidXanatos** [comment]
whats wrong in having
"Neue Sandbox"
"Nowa piaskownice"
etc...
in other languages?

**Comment by okrc** [comment]
https://user-images.githubusercontent.com/29057533/230560621-9482e470-b0d5-4478-82b3-a54cd1d799a9.mp4

**Comment by DavidXanatos** [comment]
oh right non asci languages... i see the problem

**Comment by bastik-1001** [comment]
What's the ideal solution? Have the default string be static English, saying "New Box"?

This seems to be better than to let non ASCII translations differ, which would be another solution.

Support path names and thereby boxnames that can include non ASCII characters?
