### ISSUE TITLE
Custom icon for the installer

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2795]
### Is your feature request related to a problem or use case?

Can the installer have a custom icon, that has some reference to Sandboxie?

With 1.8.x, the icon of the installer changed from some icon that is pretty familiar to many people, as it is being used for many installers, to some new icon that looks very different. To me, the arrow pointing down to something I can't tell what it is supposed to be, looks like a downloader. (There is software that has an offline installer and an online installer, where it would be accurate to assume that the downward arrow, is representing that.)

Since the icon is not being recognized by users, yet, why not have the installer show an icon that relates to Sandboxie? Maybe even that it is an installer, if possible. That way, users can tell the Sandboxie installer apart from other installers.

### Describe the solution you'd like

Evaluate if the installer can easily be build with an icon that relates to Sandboxie, instead of being generic.

### Describe alternatives you've considered

Leaving it, as it is, or for the sake of sticking out, replacing the installer with another icon that won't be the default, everyone else uses.

**Comment by isaak654** [comment]
I agree, the new installer icon cannot represent Sandboxie at all: 
![ugly_installer_icon](https://user-images.githubusercontent.com/12372772/230584165-17f1a46e-8f15-4b8a-a4fa-3407f73b3819.png)

**Comment by DavidXanatos** [comment]
yea I ques its simply enough to set a custom icon in inno setup https://jrsoftware.org/ishelp/topic_setup_setupiconfile.htm so I'll cook something up for the next release, probably just the normal sandboxie ison with a sidewhise or downwards pointing arrow?
also feal free to post icon suggestions

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/230600622-038da167-a82f-4497-a2a0-7ee3f726c4f0.png)
![grafik](https://user-images.githubusercontent.com/3890945/230600646-93084ef9-8b30-4491-bd11-d036fced8d02.png)

something liek this

**Comment by bastik-1001** [comment]
The normal Sandboxie icon with something like an arrow, should do the trick. Many icons seem to have an arrow that points down or sideways, so I guess that there is a reason for it.

Other icons I saw are boxes, showing what gets installed or unpacked.
[WPS](http://kdl1.cache.wps.com/ksodl/helpimages/install_icon.png)
[Icon in a box](https://cdn.dribbble.com/users/2167336/screenshots/6734911/icon-installer.png)
[Adobe on a box with an upward arrow](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/b9335359-78f7-4b56-bb68-2d069fdf6aa0/d1makqx-9e1f7b6c-8754-40d4-9536-5d6d69661637.jpg/v1/fill/w_256,h_256,q_75,strp/adobe_installer_icon_by_philosoraptus.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwic3ViIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl0sIm9iaiI6W1t7InBhdGgiOiIvaS9iOTMzNTM1OS03OGY3LTRiNTYtYmI2OC0yZDA2OWZkZjZhYTAvZDFtYWtxeC05ZTFmN2I2Yy04NzU0LTQwZDQtOTUzNi01ZDZkNjk2NjE2MzcuanBnIiwid2lkdGgiOiI8PTI1NiIsImhlaWdodCI6Ijw9MjU2In1dXX0.pYnLnEF9QPYOUJfpQu8y84aXw5oY84XniRRucfcPXfI)

**Comment by DavidXanatos** [comment]
here you go: https://github.com/sandboxie-plus/Sandboxie/blob/master/Installer/SandManInstall.ico

**Comment by DavidXanatos** [comment]
About unboxing icons, this looks lice in high DPI but we are old school we need a 16x16 icon as well LOL

**Comment by bastik-1001** [comment]
> About unboxing icons, this looks lice in high DPI but we are old school we need a 16x16 icon as well LOL

Yes, you are right, it has to work for everyone.

**Comment by DavidXanatos** [comment]
Yea, i like these arrows also use them in the old task explorer installer, i think i got the idea initially from true crypt they also just added such an arrow to their installer to distinguish it from the actual executable.

**Comment by bastik-1001** [comment]
I guess that if someone comes along with a nice improvement on the installer icon, like that it scales higher or ensures that is can be recognized in any size, like you did at the lowest scale, you'd welcome it.

**Comment by DavidXanatos** [comment]
sure

**Comment by bastik-1001** [comment]
Added with 1.8.4, so I am closing it.
