### ISSUE TITLE
Sandman: Disable forcing rules per sandbox

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2797]
### Is your feature request related to a problem or use case?

When using the global function to disable processes being forced into sandboxes, this obviously applies to all sandboxes and when some program starts or spawns a new process, that happens outside the sandbox without being intended.

E.g. box A and box B, where something is forced into one box and something else in the other, while the software is installed in the actual system. When software runs in a sandbox, while the other needs to be started outside the box to be updated, then it can happen that software runs without Sandboxie, if all rules are disabled. This can also be true, when the software that gets updated, starts a browser (to present the change-log or whatever) that would be forced into a box, it gets started unsandboxed. Of course, all of that is to be expected, but usability may be improved.

### Describe the solution you'd like

A function, probably in the right click menu of a box, where one can disable the rules for that box, without opening the settings.

Similar to Sandbox Presets > "Block Internet Access", just reading "Disable forcing rules" or similar.

Having it only being set temporarily, might be too much to implement. It seems easier if the option toggles the rules.

### Describe alternatives you've considered

The reason the request is limit to Sandman, is that I don't know how the old UI handles that. Whenever it allows to control the setting via a menu, it may get added to there as well.

**Comment by offhub** [comment]
Actually, there is such a feature, but it only takes effect if it is forced by the name of the process. If the process forcing is defined in a process group/template, the change made for the process is not effective.

`Right click on a running process under the sandbox` > `Preset` > `Force into this sandbox` (toggleable)

**Comment by bastik-1001** [comment]
@offhub This seems to require that the process that should not be forced into a box, needs to run inside the box to be disabled from running. If there are multiple processes being forced, all of them have to be started for them to be disabled. Changing the box setting seems easier. Thank you for your input and providing the clear instruction.

**Comment by offhub** [comment]
You are right. Wouldn't running it outside the sandbox achieve the same result?

1. Right click > Run Sandboxed > Run Outside the Sandbox

2. Right click > Run Un-Sandboxed
    > Global Settings > Shell Integration > Add "Run Un-Sandboxed" to the context menu

3. If it's a Sandboxie shortcut: `Ctrl+Shift + Double click` to run it Un-Sandboxed.

**Comment by bastik-1001** [comment]
Potentially, this would work. Maybe not in all cases, when a program is launched again, during an update process or that update process calls something that is desired to be forced into another box, like the browser.

Normally, I just disabled the forced rules globally, when I update something, but I had the issue that something got executed outside the sandbox, as I did not expect a new process being opened, while I updated some other software. It was desired to have the update take place outside the sandbox, which is why I made this request, since I looked for a way to quickly disable force rules for one box, but not the others.

**Comment by mysteriously** [comment]
This is one of the most useful feature requests I have seen lately.

**Comment by DavidXanatos** [comment]
this indeed sounds usefull, will add it to the next build for which I update the driver

**Comment by bastik-1001** [comment]
It might be the case that this is not as easy as it seems, depending on how this can be implemented.

If it ignores the force rules for that box, when the setting is toggled, then it should be fine. Just if it disables the forces rules and not all of them are active to begin with.

Like the box `Office` having two forced rules
- `pdf-viewer.exe` (enabled/checked)
- `wordproceesor.exe` (disabled/unchecked)

So toggling the forced rules to be ignored, Sandboxie has to return to the initial state, when it is going to change them. If this works, by just ignoring the rules for that box, then my 'concern' isn't valid.

**Comment by DavidXanatos** [comment]
yea that's why I mentioned a new driver there will be a new settign in the ini to disbale all forced entries of the box that has it

**Comment by DavidXanatos** [comment]
```DisableForced=y``` will be added to the next driver build
is the name fine or are tehre any better suggestions?

**Comment by bastik-1001** [comment]
Sounds good to me. If someone wants to complain, they still have time to do so.

**Comment by isaak654** [comment]
> is the name fine or are tehre any better suggestions?
 
Personally I would suggest `DisableForcedRules=y`, as it leaves no room for interpretation.

**Comment by DavidXanatos** [comment]
DisableForcedRules is not corect nglich there are no forced rules,
DisableForceRules would be correct
yea i can use that sounds good

**Comment by isaak654** [comment]
#2851
