### ISSUE TITLE
Sandboxed Program is detecting Sandboxie + invalid signature

### ISSUE THREAD

**Issue by Hiche3** [sandboxie-plus/Sandboxie#28]
Sandboxie 5.40.1.

![Sandboxie](https://user-images.githubusercontent.com/65008496/81379985-b3f48d00-90cf-11ea-909e-75a4ea75897a.png)

No such message with Sandboxie 5.33.3.

**Comment by DavidXanatos** [comment]
That's bullshit complaining about a program not being signed is lazy and doesn't improve security in the least, just ignore it.

**Comment by Hiche3** [comment]
My concern is a program's ability to detect that it is being sandboxed.
Are you saying that programs are always able to notice that they are running inside of Sandboxie?

**Comment by DavidXanatos** [comment]
Its not detecting that its sandboxed its detecting that it was started by a process called start.exe and that this process does not have a digital signature.
