### ISSUE TITLE
Please release the new portable version as ZIP, not RAR, and share more details

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#280]
While [version 0.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.2) stated "If a Sandboxie-Plus.ini is created in its root directory it will operate in a fully portable mode", It seems [version 0.52](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.5.2 ) silently ("This is a maintenance release it does not bring any major new features") released it as an official feature ("Sandboxie-Plus-Portable-v0.5.2.rar").

This is great news! But can you please release it as ZIP and not RAR so it'll be natively accessible in Windows?
The RAR file is 25.9 MB but quickly using https://cloudconvert.com/rar-to-zip just made it 32Mb, not a noteworthy difference. Besides, all your other archives are released in plain ZIP.

Regardless, does the portable version have any downsides?

Last but not least, does it delete the INI file as well as c:\Sandbox upon exit?

**Comment by DavidXanatos** [comment]
it was always a official feature the old plus installers hat a extract option that just unpacked the content to a folder what you now get in the zip. I had to switch to innosetup which does not provide such a unpack option.

Ok fine will do zip even though uploads to github are painstakingly slow...

No it dos not perform such sort of cleanup on exit, might be a good idea to add that functionality though.

**Comment by lwcorp** [comment]
Thanks for changing to ZIP! Can you do so for this release too?

Yes, please delete those items too to make it truly portable. Does it mean currently exiting it deletes only the driver?

**Comment by mpheath** [comment]
@DavidXanatos

Note: InnoSetup can just unpack the files by using some extra conditions added to the setup script. I have no preference in rar vs zip vs exe for unpacking, so do not consider this as what I am interested in.

A minimal example of unpack/extract or install with InnoSetup.

```
#define MyAppName "AppName"
#define MyAppVersion "1.0"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
DefaultDirName={pf}\{#MyAppName}
; If component extract is selected, it will be extraction rather than an uninstallable setup.
Uninstallable=not IsComponentSelected('extract')

[Types]
Name: "install"; Description: "Install"
Name: "extract"; Description: "Extract"

[Components]
Types: install; Name: "install"; Description: "Install"; Flags: exclusive
Types: extract; Name: "extract"; Description: "Extract"; Flags: exclusive

[Files]
; Both extract and install.
Source: "{app}\readme.txt"; DestDir: "{app}"; Flags: ignoreversion
; Only extract.
Source: "{app}\portable.txt"; DestDir: "{app}"; Flags: ignoreversion; Components: extract
```

Require a folder named `{app}` containing 2 files named `readme.txt` and `portable.txt` to compile. A vague example though perhaps can inspire some ideas. Some InnoSetup installers use this concept or something similar.

**Comment by DavidXanatos** [comment]
That's not good enough:
type selection should come before folder selection,
when install is selected creation of startmenu entries and alike should be suppressed and all the options from the [Tasks] section should be omited to.
Could you please provide an example where this is done this way

**Comment by mpheath** [comment]
@DavidXanatos

The order of pages is unchangeable. So a good GUI solution to meet your standards without coding custom pages to replace the standard pages is not something I can do.

Inno Setup 6 has a builtin argument `/portable=1`, though code may still be needed to set the folder selection path to `{src}\...` or something similar. Omitting of lines can be done though whole sections can not be done. So parameter like `Task: ...`, `Check: ...` are used on each line.

The latest Plus installer seems not to have Types or Components so will omit. What comes before the folder selection page is the commandline. I doubt it may meet you approval, though here it is:

```
#define MyAppName "SandboxieTest"
#define MyAppVersion "1.0"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
DefaultDirName={code:InstallPath|SandboxieTest}
Uninstallable=not IsPortable
; Allow /CURRENTUSER to be used with /PORTABLE=1 to avoid admin requirement.
PrivilegesRequiredOverridesAllowed=commandline

[Files]
; Both portable and install.
Source: "{app}\readme.txt"; DestDir: "{app}"; Flags: ignoreversion
; Only if portable.
Source: "{app}\portable.txt"; DestDir: "{app}"; Flags: ignoreversion; Check: IsPortable

[Tasks]
; Only if install.
Name: "startmenuentry"; Description: "Start when Windows starts"; Check: not IsPortable

[Registry]
; Only if install.
Root: HKCU; Subkey: "Software\SandboxieTest"; ValueName: "SandboxieTest_Autorun"; ValueType: string; ValueData: "1"; Flags: uninsdeletekey; Tasks: startmenuentry

[Messages]
; Include with commandline /? message
HelpTextNote=/PORTABLE=1%nEnable portable mode.%n

[Code]
// Return the path to use for the value of DefaultDirName. 
function InstallPath(name: string): string;
begin
  if ExpandConstant('{param:portable|0}') = '1' then begin
    result := ExpandConstant('{src}') + '\' + name;
  end else begin
    result:= ExpandConstant('{autopf}') + '\' + name;
  end;
end;

// Return True or False for the value of Check.
function IsPortable(): boolean;
begin
  if ExpandConstant('{param:portable|0}') = '1' then begin
    result := True;
  end;
end;
```

No arguments does the install. Use of arguments:

```
setup.exe /portable=1 /currentuser
```

does the portable extraction of files. Without `/currentuser` will cause the UAC prompt to display.

If not good enough, then the zip file is good.

p.s. In latest *Sandboxie-Plus-x64-v0.5.2.exe* installer, Msgbox about provisional driver displays like a literal `\r\n` in `'.../releases/\r\ndo you...'` instead of newline. Consider using `'.../releases/' + #13#10 + 'do you...'` for newlines in PascalScript.

**Comment by DavidXanatos** [comment]
Great, that's almost workable, but is there a way to make it not offer to create start menu entries?

**Comment by isaak654** [comment]
> 
> 
> Great, that's almost workable, but is there a way to make it not offer to create start menu entries?

https://jrsoftware.org/ishelp/index.php?topic=setup_allownoicons

AllowNoIcons=yes in [Setup] section.

**Comment by mpheath** [comment]
@isaak654

Good find. `AllowNoIcons` shows a checkbox on the "*Select Start Menu Folder*" group page for the user to choose icons or no icons on install. The setting shows as already active in the Sandboxie-Plus install. `AllowNoIcons` setting is OK as it is now.

What would be user friendly is to have no icon choices, no icon creation and no group page on portable mode. Where to extract the files is the primary concern for portable mode. This requires some other changes to the setup script. 

@DavidXanatos

Updated previous setup script example with:

 * Added `DefaultGroupName=SandboxieTest` in `[Setup]` section for icon creation.
 * Added `[Icons]` section and an icon creation line.
 * Updated `[Code]` section and added function `ShouldSkipPage()` to skip group page when in portable mode.

The `Check: not IsPortable` at the icon creation line will ensure that the icon does not get created on portable mode. Use `Check: not IsPortable` or `Check: IsPortable` where behavior between install and portable mode is required. Use `if IsPortable then` in the `[code]` section to check for portable mode.

**Comment by DavidXanatos** [comment]
@mpheath brilliant, that works like a charm!
Will add the required changes and make this the default way of providing portable builds.

One thing still would be nice to have a page that asks if the user wants portable or not, but that's a minor detail.

**Comment by mpheath** [comment]
This setup script has a Custom page as 1st page with 2 radio buttons:

 * Normal Installation
 * Portable Extraction

You can rename the text if you prefer something better with the RadioInstallText and RadioPortableText preprocessor directives at top of the script. The Custom page will not show if `/portable=1` argument is passed to the installer.

The setting of `DisableDirPage=no` is set so the code section can hide the Dir page on reinstall though always show it for install and portable.

The directive constant of `{#MyAppName}` is used also in the code section to sync the AppName everywhere where needed.


```
#define MyAppName "SandboxieTest"
#define MyAppVersion "1.0"
#define RadioInstallText "Normal Installation"
#define RadioPortableText "Portable Extraction"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
DefaultDirName={code:InstallPath|{#MyAppName}}
; Handled in code section as always want DirPage for portable mode.
DisableDirPage=no
DefaultGroupName={#MyAppName}
Uninstallable=not IsPortable
; Allow /CURRENTUSER to be used with /PORTABLE=1 to avoid admin requirement.
PrivilegesRequiredOverridesAllowed=commandline

[Files]
; Both portable and install.
Source: "{app}\readme.txt"; DestDir: "{app}"; Flags: ignoreversion
; Only if portable.
Source: "{app}\portable.txt"; DestDir: "{app}"; Flags: ignoreversion; Check: IsPortable

[Tasks]
; Only if install.
Name: "startmenuentry"; Description: "Start when Windows starts"; Check: not IsPortable

[Icons]
; Only if install.
Name: "{group}\{#MyAppName}"; Filename: "{app}\readme.txt"; Check: not IsPortable

[Registry]
; Only if install.
Root: HKCU; Subkey: "Software\{#MyAppName}"; ValueName: "{#MyAppName}_Autorun"; ValueType: string; ValueData: "1"; Flags: uninsdeletekey; Tasks: startmenuentry

[Messages]
; Include with commandline /? message.
HelpTextNote=/PORTABLE=1%nEnable portable mode.%n

[Code]
var
  CustomPage: TInputOptionWizardPage;
  Portable: boolean;

// Return True or False for the value of Check.
function IsPortable(): boolean;
begin
  if (ExpandConstant('{param:portable|0}') = '1') or Portable then begin
    result := True;
  end;
end;

// Return the path to use for the value of DefaultDirName.
function InstallPath(name: string): string;
begin
  if (ExpandConstant('{param:portable|0}') = '1') or Portable then begin
    result := ExpandConstant('{src}') + '\{#MyAppName}';
  end else begin
    result := ExpandConstant('{autopf}') + '\{#MyAppName}';
  end;
end;

// Create the custom page.
// Source: https://timesheetsandstuff.wordpress.com/2008/06/27/the-joy-of-part-2/
procedure InitializeWizard;
begin
  CustomPage := CreateInputOptionPage(wpWelcome, 'Installation Type', 'Select Installation Option',
                                      'Choose the installation mode', True, False);
  CustomPage.Add('{#RadioInstallText}');
  CustomPage.Add('{#RadioPortableText}');

  // Default - Normal Installation if not argument /PORTABLE=1.
  if ExpandConstant('{param:portable|0}') = '1' then begin
    CustomPage.SelectedValueIndex := 1;
  end else begin
    CustomPage.SelectedValueIndex := 0;
  end;
end;

// Get mode setting from Custom page and set path for the Dir page.
function NextButtonClick(CurPageID: integer): boolean;
begin
  if CurPageID = CustomPage.ID then begin
    Portable := not (CustomPage.SelectedValueIndex = 0);
    WizardForm.DirEdit.Text := InstallPath('{#MyAppName}')
  end;
  result := True
end;

// Detect if already installed.
// Source: https://stackoverflow.com/a/30568071
function IsUpgrade: Boolean;
var
  S: string;
  InnoSetupReg: string;
  AppPathName: string;
begin
  InnoSetupReg := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppName")}_is1');
  AppPathName := 'Inno Setup: App Path';
  Result := RegQueryStringValue(HKLM, InnoSetupReg, AppPathName, S) or
            RegQueryStringValue(HKCU, InnoSetupReg, AppPathName, S);
end;

// Skip Custom page and Group page if portable.
function ShouldSkipPage(PageID: integer): boolean;
begin
  if PageID = CustomPage.ID then begin
    if ExpandConstant('{param:portable|0}') = '1' then
      result := True;
  end else if PageID = wpSelectDir then begin
    if not IsPortable and IsUpgrade then
      result := True;
  end else if PageID = wpSelectProgramGroup then begin
    if IsPortable then
      result := True;
  end;
end;
```

It is based on the previous setup script so it basically supercedes it. So the same rules apply with `Check: ...`, ...

**Comment by DavidXanatos** [comment]
@mpheath great, now its perfect, thank you very much :-)

**Comment by mpheath** [comment]
@DavidXanatos Glad to help. It has been an interesting experience and it has allowed me to learn some new things about Inno Setup. Cheers!

**Comment by mpheath** [comment]
@DavidXanatos Sorry for being a nuisance. Had to update previous code with a subtle cosmetic fix. Portable mode was displaying the Start Menu folder setting on the Ready page. This can be confusing as no Start Menu folder will be created. So, `WizardForm.NoIconsCheck.Checked := True;` is used to avoid it being displayed.

The test strings on the Custom page has been moved into `[CustomMessages]` section. Probably the setup will be multiple languages so the Custom Messages for the Custom page may later end up in a translated *language*.isl files.

Hope it is perfect now.

**Comment by DavidXanatos** [comment]
@mpheath even better, thanks :D

**Comment by lwcorp** [comment]
After all this lengty discussion, you've never again released the portable version, why is it?
Will you consider releasing it again hopefully constantly?

**Comment by DavidXanatos** [comment]
You can run the installer and choose to just extract that gives you the portable version.
Its an all in one package, no need for a separate zip that contains the exact same files as you get form extracting the installer.
