### ISSUE TITLE
Sandman crashes if multiple "Open in Sandbox" windows are opened and one of them is closed via right click on taskbar

### ISSUE THREAD

**Issue by mysteriously** [sandboxie-plus/Sandboxie#2803]
### Describe what you noticed and did

1. Create Enhanced Isolation sandbox (orange)
2. OpenFilePath to path with multiple files (like PDFs)
3. Select 5 PDFs, right click, open in Sandbox
4. Select the sandbox you created, open two files in it
5. Close 3rd "Open in Sandbox" window via right click on taskbar
6. Sandman crashes

If you need Sandbox config or sandman dump, I can upload to cloud and email the link

### Affected program

Sandman

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.8.3/Sandboxie-Plus-x64-v1.8.3.exe

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Close 3rd "Open in Sandbox" window via right click on taskbar without causing Sandman to crash

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.8.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by bastik-1001** [comment]
For me, it does not crash with 1.8.4 64bit on Windows 7 64bit. I followed the steps to reproduce. I also tried closing the dialog directly. Neither way resulted in Sandman crashing.

Is "OpenFilePath" required to trigger this issue?
Does it happen with other files like TXT?
