### ISSUE TITLE
Renaming groups in GUI is broken

### ISSUE THREAD

**Issue by TFWol** [sandboxie-plus/Sandboxie#2804]
### Describe what you noticed and did

Renaming groups will break the group in the GUI and in the ini
This has been around for a long while ~v1.6.x if not further? (I don't know when it started)

Problem seen on all test machines including fresh install on baseline Windows.

1. Create a Group, **TestGroup** for example
2. Verify it's there in the ini as `ProcessGroup=<TestGroup>,`
3. Double click your test group to go in rename mode, you'll notice the name becomes `Group: TestGroup` when it should stay as `TestGroup`
4. Hit apply and now the name shows up as truncated `roup: TestGrou`
5. Go to ini and see it shows up as `ProcessGroup=Group: TestGroup,`

This breaks a lot of things. Firewall rules, other groups it's in, anything that references it, etc.

The problem gets compounded as you keep trying to rename the group, even if you try to correct it in the GUI, like renaming it back to `TestGroup`, it will be truncated and the ini format will be messed up.

### How often did you encounter it so far?

Everytime a group is edited

### Affected program

N/A

### Download link

N/A

### Where is the program located?

Not relevant to my request.

### Expected behavior

When a group is renamed, it should be as typed.

### What is your Windows edition and version?

Windows 10 Pro 21H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

N/A

### What version of Sandboxie are you running?

Sandboxie Plus  1.8.4 x64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by bastik-1001** [comment]
I was able to reproduce the issue with the same version. Nice catch.

Either the feature was not used (which is what I hope), or it got overlooked (what would be bad as it can lead to unexpected results.)
