### ISSUE TITLE
Can you consider supporting Alipay purchases?

### ISSUE THREAD

**Issue by kinlaevl** [sandboxie-plus/Sandboxie#2813]
### Is your feature request related to a problem or use case?

In China, it is difficult to use PayPal to pay in euros, and the general income is not high. My daily income is only 16 euros. 

### Describe the solution you'd like

please consider platforms that support other payment channels and refer to automatic differential pricing such as steam.

### Describe alternatives you've considered

接入自动发货平台，他们会支援各种支付而无需你费心。

**Comment by DavidXanatos** [comment]
I'll look into it

**Comment by DavidXanatos** [comment]
further replies in https://github.com/sandboxie-plus/Sandboxie/issues/2882
