### ISSUE TITLE
we could not verify the certificate error

### ISSUE THREAD

**Issue by sirdoug69** [sandboxie-plus/Sandboxie#2814]
### Describe what you noticed and did

Hello,
I have seen this error happen on a few computers over the past 2 years.
When I launch Sandboxie Browser the browser will come up with a blank white webpage with error:
"we could not verify the certificate: reason = error"

Same error on Chrome, Edge, Firefox.
This installation worked a few months ago on this PC.
On my daughter's laptop, Sandboxie has never worked.

I have uninstalled and reinstalled a few times with the latest build.
I manually tried to find any lingering stuff in the registry and removed it.
I could not find any files or directories left over.

Note 1: Right after the installation of version sandboxie-plus-v64-v1.3.2.exe when Sandboxie comes up the first time, the Introduction screen comes up and the option to select Personal or Commerical is faded out (personal is selected but faded out) and I can only click Next or Cancel. I have a theory it's forcing Comercial option which is causing me to get the certificate error because I don't have a certificate.

Note 2: During the uninstall I get error "Could not invoke program: terminate_all System Error Code: The system cannot find the file specified (2). I click OK and it continues to successfully uninstall.

Note 3: One installation is on a Win10 Pro VM running on Hyper-V that worked for a few months then stopped.  I also have standalone ASUS laptop that has never worked.  Both the same error.  I have had problems on other PCs too.

Note 4: I have 2 Desktop PCs on Win 10 Pro that is on my MS domain and works fine. All my comnputers are up to date with MS patches.

Please advise.
Thanks!

### How often did you encounter it so far?

always

### Affected program

Edge, Chrome.

### Download link

not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

I should be able to bring up the Web browser in Sandboxie.

### What is your Windows edition and version?

Windows 10 Pro

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

BitDefender or Avast

### What version of Sandboxie are you running?

sandboxie-plus-v64-v1.3.2 (also downloaded latest as of 4/9/2023.

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
DefaultBox=DefaultBox
TemplateReject=WindowsRasMan
TemplateReject=WindowsLive
TemplateReject=OfficeLicensing
TemplateReject=OfficeClickToRun
TemplateReject=BitDefenderInternetSecurity
TemplateReject=7zipShellEx

[UserSettings_11740275]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10

[UserSettings_2D280416]
SbieCtrl_UserName=DINGDONG
SbieCtrl_NextUpdateCheck=1681698926
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
```

**Comment by offhub** [comment]
Try disabling Bitdefender's "Encrypted web scan" setting.

Bitdefender > Protection > Online Threat Prevention > Settings > Encrypted web scan

**Comment by isaak654** [comment]
It would be interesting to know whether the mentioned browsers have at least one extension in common.

**Comment by isaak654** [comment]
It would be interesting to know whether the mentioned browsers have at least one extension in common. If not, maybe you could try attaching a reproducible video with the error in question.

I have just installed BitDefender Total Security on Windows 10 22H2 x64 and cannot detect any issue with sandboxed Edge or Firefox (standard isolation).

**Comment by sirdoug69** [comment]
Note: I have bitdefender on most PCs and some with Avast.  Most PCs work with either one.  Plus it worked for about 2 months before it stopped working on a win10 VM.  So I don't really think it's Bitdefender.  Some PCs are standalone and some are on a Windows AD Domain.  I was trying to use Dev mode (F12) on edge but it didn't help me find what cert it's talking about.
Note 2: I tried yesterday with a Sandboxie DEV Cert installed too.  No dice.
Note 3: I tried different DNS servers, but most of my PCs use OPENDNS for parental controls.
Makes me think it's a MS Patch that came along for certain device driver that broke it.  I find it really weird that I'm the only person having this issue.  Popping up for past 2 years or more on about 4 PCs I have worked on.  
Can you recommend any logs for me to look at?  I already looked at Event Viewer but there are a ton of different logs in event viewer.

**Comment by offhub** [comment]
After taking a snapshot of the virtual machine, uninstall 3rd party security software. If you don't get the same error after uninstalling, it means there is a conflict between these software and Sandboxie. Depending on the result, it may be necessary to review the compatibility templates.

**Comment by isaak654** [comment]
@sirdoug69

What happens if you enable [this](https://github.com/sandboxie-plus/Sandboxie/issues/2177#issuecomment-1223843023) option or the other ones located in the `Access isolation` group?

> Can you recommend any logs for me to look at? I already looked at Event Viewer but there are a ton of different logs in event viewer.

[CONTRIBUTING.md#how-to-help-with-sandboxie-issues](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md#how-to-help-with-sandboxie-issues)

**Comment by bastik-1001** [comment]
> When I launch Sandboxie Browser the browser will come up with a blank white webpage with error:
> "we could not verify the certificate: reason = error"

Can you provide a screenshot of a browser, showing that error and the URL bar?

> Same error on Chrome, Edge, Firefox.

While Chrome and Edge are based on Chromium, which could explain why they show the same message, I expect Firefox to show a different message, even if that is similar. If they are indeed exactly the same, it seems to suggest that something else is showing that message. It is strange that the message appears with two different security products.

**Comment by sirdoug69** [comment]
> @sirdoug69
> 
> What happens if you enable [this](https://github.com/sandboxie-plus/Sandboxie/issues/2177#issuecomment-1223843023) option or the other ones located in the `Access isolation` group?
> 
> > Can you recommend any logs for me to look at? I already looked at Event Viewer but there are a ton of different logs in event viewer.
> 
> [CONTRIBUTING.md#how-to-help-with-sandboxie-issues](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md#how-to-help-with-sandboxie-issues)

Sorry, I am not sure where to find those options.  I don't know where to find the Context Options are.  Under Options/Global Settings I don't see anything like that.

**Comment by sirdoug69** [comment]
> > When I launch Sandboxie Browser the browser will come up with a blank white webpage with error:
> > "we could not verify the certificate: reason = error"
> 
> Can you provide a screenshot of a browser, showing that error and the URL bar?
> 
> > Same error on Chrome, Edge, Firefox.
> 
> While Chrome and Edge are based on Chromium, which could explain why they show the same message, I expect Firefox to show a different message, even if that is similar. If they are indeed exactly the same, it seems to suggest that something else is showing that message. It is strange that the message appears with two different security products.

Attached screen shots.  Firefox seems to load fine, until you try to go to a Website.  I provided 2 Firefox snips.
![Firefox1](https://user-images.githubusercontent.com/130414129/234161650-92144980-8b4a-497a-8bda-0518ba94214a.PNG)
![Firefox2](https://user-images.githubusercontent.com/130414129/234161652-1ebe2b84-7dbe-486f-b643-8360f7d2ad42.PNG)
![Chrome](https://user-images.githubusercontent.com/130414129/234161654-cafafcb7-432e-492a-8e23-3ff2dad69a50.PNG)
![Edge](https://user-images.githubusercontent.com/130414129/234161655-6c805880-5f2c-42f0-b078-779483b62d9d.PNG)

Thanks for helping folks!  Sorry if I don't get back quickly.  Life is busy as know. :)

**Comment by DavidXanatos** [comment]
Do you have SandboxieCrypto.exe running in the sandbox?

**Comment by isaak654** [comment]
> Sorry, I am not sure where to find those options. I don't know where to find the Context Options are. Under Options/Global Settings I don't see anything like that.

You can access to `Sandbox Options` with a [right-click on your sandbox](https://sandboxie-plus.github.io/sandboxie-docs/Content/PlusMigrationGuide.html#sandbox-context-menu), then:

Security Options -> Security Isolation -> check all the options under Access Isolation.

**Comment by sirdoug69** [comment]
> Do you have SandboxieCrypto.exe running in the sandbox?

no, just doing basic install.

**Comment by sirdoug69** [comment]
> > Sorry, I am not sure where to find those options. I don't know where to find the Context Options are. Under Options/Global Settings I don't see anything like that.
> 
> You can access to `Sandbox Options` with a [right-click on your sandbox](https://sandboxie-plus.github.io/sandboxie-docs/Content/PlusMigrationGuide.html#sandbox-context-menu), then:
> 
> Security Options -> Security Isolation -> check all the options under Access Isolation.

Ok, what do you mean right click on your Sandbox?  Do you mean the DefaultBox?  Do you mean the Sanboxed browser?  Neither gives me Security Options.

Here are some more detailed pics you can see what Edge has spun up in the background.
![Big Screen Shot](https://github.com/sandboxie-plus/Sandboxie/assets/130414129/23fa4331-0e17-4369-a258-2619b572efe0)
![Only Options Area I can find](https://github.com/sandboxie-plus/Sandboxie/assets/130414129/4069730b-1e19-41cf-b693-ab02d59b05b6)

**Comment by isaak654** [comment]
> Ok, what do you mean right click on your Sandbox? Do you mean the DefaultBox? 

DefaultBox is a sandbox, so this term includes DefaultBox or any other sandbox name you might set up.

>  Neither gives me Security Options

Security Options is the third tab on the left side [here](https://user-images.githubusercontent.com/130414129/237552885-4069730b-1e19-41cf-b693-ab02d59b05b6.PNG).

**Comment by isaak654** [comment]
> Ok, what do you mean right click on your Sandbox? Do you mean the DefaultBox? 

DefaultBox is a sandbox, so this term includes DefaultBox.

>  Neither gives me Security Options

Security Options is the third tab on the left side [here](https://user-images.githubusercontent.com/130414129/237552885-4069730b-1e19-41cf-b693-ab02d59b05b6.PNG).

**Comment by isaak654** [comment]
> Ok, what do you mean right click on your Sandbox? Do you mean the DefaultBox? 

DefaultBox is a sandbox, so it includes DefaultBox.

>  Neither gives me Security Options

Security Options is the third tab on the left side [here](https://user-images.githubusercontent.com/130414129/237552885-4069730b-1e19-41cf-b693-ab02d59b05b6.PNG).

**Comment by bastik-1001** [comment]
Since the error shown by the browsers is related to something being unable to verify the certificate, I wonder if there is no issue with a website that does not provide any encryption and therefore does not present any certificate to be inspected.

These days, there are fewer sites that don't support https and I did not find a selection, but there is [http://go.com/](http://go.com/), which can be used for testing if whatever is causing the issue, is interfering with unencrypted connections.

It still may fail, but maybe the reason in the message changes from "error" to "untrusted".
