### ISSUE TITLE
Indicate a sandbox having or being run with debug options

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2816]
### Is your feature request related to a problem or use case?

It is possible to run some box or boxes with debug options for testing-purposes, then forget that those are set and run programs with potentially unsafe debug options, by accident.

### Describe the solution you'd like

SandMan has a status column, where you can add the word `DEBUG`, whenever a box has any debug option set. This might not even be a string exposed for translation, as I am guessing anyone messing with the debug options to be able to read the documentation and therefore being able to understand it. (I could be wrong, as they might just use a translation tool. Though they still should know what they are doing.)

If you feel fancy, you can add an entry to the log. "$boxname has been initialized with debug options $debugname" or something like that. (While still assuming, those entries not to be seen by that many people, maybe that line should be exposed for translation.)

**Comment by DavidXanatos** [comment]
we already have somethign liek this,
try adding ```UnrestrictedToken=y``` to a box, the icon should become maganta and the status column should say "NOT SECURE"
see https://github.com/sandboxie-plus/Sandboxie/blob/cdd715359d0981551eaf72a4332e1e9d419e6b81/SandboxiePlus/SandMan/SbiePlusAPI.cpp#L615

what other options should we worn the user about?

**Comment by bastik-1001** [comment]
This issue might be obsolete, since there is a warning for unsafe options.

The main idea, was to indicate that any debug option has been set and is enabled for a box, without the need to think if the option itself is risky.  Letting it up to the user to decide, since they need to know what they are doing. My assumption was, that warning per option could be overkill, and required that every option needed to be checked against. I am not sure, if my intended approach would have been easier.

If unsafe options are accounted for, and there is no need to indicate that any debug option has been set, then we can close this issue.
