### ISSUE TITLE
Add debugging options for supporter certificate related issues

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2817]
### Is your feature request related to a problem or use case?

Allowing to simulate behavior, when it comes to a user not having a supporter certificate, it being about to expire, it being expired and the grace period having expired.

Sandboxie behaves different, in certain cases, whenever or not there is a valid certificate. Reporters of issues, may not have such a certificate and trying to reproduce certain behaviors by those who have can't be replicated accurately, for those that have certificates.

### Describe the solution you'd like

Having debug options added that make Sandboxie behave differently.

`IgnoreCertificate=y` where Sandboxie behaves like there would be no certificate for that box, so it shows the same messages, when features are used that require such a certificate, terminates the processes after the amount of time, like it would normally do, etc.
`Fakeexpiryimminent=y` behave like the certificate is about to expire and needs to be renewed.
`Fakeexpired=y` behave like the certificate has expired.
`Fakegraceperiodexpired=y` behave like the user has installed Sandboxie for a long time and gets shown the dialog to consider supporting the project.

The latter three are to test the usability, to inspect the dialogs and messages, one normally does not get to see.

**Comment by DavidXanatos** [comment]
I actually have some hacks like that in my private builds for testing, so its actually useful.
That said most of that only affects the UI, and the driver does not care for about to expire or in grace period it only have one Boolean flag certified = y/n and this can be tested by renaming the certificate.dat to something else reloading the settings and after the text back again.
So if I add this it will be be in the plus.ini and only for the ui, what do you think?

**Comment by DavidXanatos** [comment]
https://github.com/sandboxie-plus/Sandboxie/blob/b2b06261bc7fef118ce183202acd4187fbc8cec9/SandboxiePlus/SandMan/SandMan.cpp#L2162

**Comment by bastik-1001** [comment]
> So if I add this it will be be in the plus.ini and only for the ui, what do you think?

Good enough for me. :)

**Comment by bastik-1001** [comment]
What do I have to add to the Sandboxie.ini for those options to be applied?

When I add them to a box or to the global section, like `CertFakeAboutToExpire=y, `Sandman does not show a dialog, even after closing and opening again. I might be doing something wrong.

**Comment by DavidXanatos** [comment]
you need to add it to the Sandboxie-Plus.ini
