### ISSUE TITLE
UI: Display issue, bug, or normal behavior?

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2824]
### Describe what you noticed and did

You added some little icons to the UI to indicate the elevation level of a process. (Correct me if I am wrong.) Not all processes have this icon, even though I think all of them should have that icon. Furthermore, sometimes processes are not listed with their process name in the status column, too. This is probably a separate thing and not related.

1) See that some processes have the yellow icon in the UI, while others don't.
2) There is also one process that does not have its name in the status column.

I point to a screenshot to make it clearer.

![Display issues](https://user-images.githubusercontent.com/1449429/232210314-c753d435-b555-4686-9093-50f48e739bb6.png)

Are those bugs in the software, just display issues, or something that is working as intended?

### Affected program

I am not sure if that is limited to something, but Firefox.

### Download link

Not relevant.

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

If I am understanding it correctly, all the processes (I marked) should have that icon and the process name should be listed in the status.

### What is your Windows edition and version?

Windows 7 64bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.8.4 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon). Edit: This also happens in a yellow box.

### Can you reproduce this problem on a new empty sandbox?

Edit: I started Firefox in a new empty box, and the UI shows the same behavior.

**Comment by DavidXanatos** [comment]
It is normal that not all have the yellow new icon also som may have an orange one instead
no extra icon normal token
yellow icon restricted token
orange icon appconainer token (only available on green boxes)
firefox and chrome run thair workers with different elvels of isolation not all get a restricted or app container token

**Comment by bastik-1001** [comment]
Thank you, that explains it.
