### ISSUE TITLE
SBIE2205 for Steam and Chromium (both fail to launch)

### ISSUE THREAD

**Issue by ghost-420** [sandboxie-plus/Sandboxie#283]
![winver_IuytBVfWTV](https://user-images.githubusercontent.com/29991266/103138372-c6373180-4686-11eb-8228-50e4531911e1.png)
```
SBIE2205 Service not implemented:  Win32Init.4 (C0000008) by process: 17256
SBIE2205 Service not implemented:  Win32Init.4 (C0000008) by process: 19056
SBIE2205 Service not implemented:  Win32Init.4 (C0000008) by process: 17256
SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001 - steamerrorreporter.exe [FF000000] by process: 19056
```
> **Same "Win32Init.4" error for Chromium 87.0.4280.88**

> **Steam will still fail to launch with the ```-no-browser``` launch argument, which is supposed to block Chromium from loading (since Steam Web Helper cannot run); can't be 100% on that.**

Sandboxie (SandMan UI) v0.4.5 / 5.44.1 used to function fine, now it doesn't, along with all versions newer than 0.4.5; suspect a Windows security update broke something in Sandboxie.

INI for Steam:
```
Enabled=y
ConfigLevel=7
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
UnrestrictedSCM=y
ExposeBoxedSystem=y
BoxNameTitle=-
DropAdminRights=n
CopyLimitKb=81920
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
OpenPipePath=D:\Steam
OpenDefaultClsid=y
Template=WindowsFontCache
Template=qWave
OpenWinClass=#
OpenProtectedStorage=y
OpenCredentials=y
```
[ResourceMonitor.txt](https://github.com/sandboxie-plus/Sandboxie/files/5742254/ResourceMonitor.txt)
[APICallLog.txt](https://github.com/sandboxie-plus/Sandboxie/files/5742255/APICallLog.txt)
[assert_steam.exe_20201225082322_1.dmp.zip](https://github.com/sandboxie-plus/Sandboxie/files/5742185/assert_steam.exe_20201225082322_1.dmp.zip)

**Comment by DavidXanatos** [comment]
The latest build contains more debug information in the SBIE2203 message could you please reproduce the issue and post the log messages again.

**Comment by ghost-420** [comment]
Logs from v0.5.4
[ResourceMonitor.txt](https://github.com/sandboxie-plus/Sandboxie/files/5785874/ResourceMonitor.txt)
[APICallLog.txt](https://github.com/sandboxie-plus/Sandboxie/files/5785875/APICallLog.txt)

**Comment by DavidXanatos** [comment]
could you please post also the normal log with the actual SBIE2203 message it should have a new field MsgID that tells me what exactly went wrong

sorry for the late reply

**Comment by ghost-420** [comment]
Can't replicate the SBIE2205 issue on v0.6.0 / 5.46.5. Steam now works alongside its Chromium web engine.
[SBIE_PLUS-0.6.0_Steam-1.zip](https://github.com/sandboxie-plus/Sandboxie/files/5885982/SBIE_PLUS-0.6.0_Steam-1.zip)

___ 
These are the current issues I've found.
* Steamwebhelper crashes randomly, outputs this message after crash: \
![SandMan_KiQzZXhjcb](https://user-images.githubusercontent.com/29991266/106115453-aa033600-6105-11eb-97d2-6fa428f3b850.png)
* Steam causes the Resource Monitor to fail, greatly slowing down Steam, and locking up SandMan: \
![SandMan_v3sdjYZyU0](https://user-images.githubusercontent.com/29991266/106116189-796fcc00-6106-11eb-800e-e1f7f246280e.png)

**Comment by DavidXanatos** [comment]
messag 1241; to  much log entries disable resource access monitor or some of the trace options

is the 2101 message related to any particular problem or just there?

so now its working can this issue be closed?

**Comment by DavidXanatos** [comment]
for the SBIE 2101  we have already an own issue https://github.com/sandboxie-plus/Sandboxie/issues/118
