### ISSUE TITLE
Problems with broken characters when installing in Korean

### ISSUE THREAD

**Issue by VenusGirl** [sandboxie-plus/Sandboxie#2833]
The installer has a problem with breaking Korean characters.
It should be UTF-8 (BOM), but has it been changed to something else recently?

### Describe what you noticed and did

![XXX1](https://user-images.githubusercontent.com/53147200/232540173-032c64ae-16d4-4717-92e6-dfd50aff473c.png)
![XXX2](https://user-images.githubusercontent.com/53147200/232540182-803e7f81-0350-4f9c-a3bc-9bc13c8f08bf.png)
![XXX3](https://user-images.githubusercontent.com/53147200/232540183-66dd3354-7a25-4270-8cd2-d6d2dc2d1a7a.png)

### How often did you encounter it so far?

From the last version...

### Affected program

installer

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The encoding seems to have changed.

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
Although this issue has already been theoretically fixed at the repository level, it still occurs in version v1.9.1.
There is nothing else I can do, except continuing to encourage @DavidXanatos to renew the build process: https://github.com/sandboxie-plus/Sandboxie/issues/2847#issuecomment-1518981284

**Comment by isaak654** [comment]
> Korean.isl should be UTF-8 (BOM) but has it changed to a different encoding?

The original mistake was made in one of your pull requests that incorrectly restored UTF-8, then I restored UTF-8 BOM through  PR #2841, but @DavidXanatos forgot to include the latest Korean.isl in the build process (as happened [here](https://github.com/sandboxie-plus/Sandboxie/issues/2847#issuecomment-1518981284) for another language).

**Comment by DavidXanatos** [comment]
should be fixed in 1.9.2
