### ISSUE TITLE
WeChat crashing when starting on arm64

### ISSUE THREAD

**Issue by mio-19** [sandboxie-plus/Sandboxie#2838]
### Describe what you noticed and did

1. Install WeChat in a sandbox, add `SpecialImage=chrome,wechat.exe`
2. Launch it

### Affected program

Wechat

### Download link

https://pc.weixin.qq.com/?lang=en_US

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

.

### What is your Windows edition and version?

25300 insider

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

v1.9.0

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by mio-19** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/2674#issuecomment-142531745 This workaround doesn't work for a

**Comment by isaak654** [comment]
It was included a few versions ago in [Templates.ini](https://github.com/sandboxie-plus/Sandboxie/blob/3bb4c1f2b0c68c25df18cba46e35a7b7daa7cfce/Sandboxie/install/Templates.ini#L504). 
Could you check if anything changes by removing it from both Sandboxie.ini and Templates.ini?

**Comment by mio-19** [comment]
> It was included a few versions ago in [Templates.ini](https://github.com/sandboxie-plus/Sandboxie/blob/3bb4c1f2b0c68c25df18cba46e35a7b7daa7cfce/Sandboxie/install/Templates.ini#L504). Could you check if anything changes by removing it from both Sandboxie.ini and Templates.ini?

It didn't change anything.

The message is the same

```
WeChat.exe (8832): SBIE2224 Sandboxed program has crashed: WeChat.exe [WeChat]
```

**Comment by DavidXanatos** [comment]
could you please test of you can use this command on your system:
![grafik](https://user-images.githubusercontent.com/3890945/233775118-4811e0a1-72b8-4fce-b982-223ca5437b07.png)

does it properly show a run dialog on your system?
