### ISSUE TITLE
Enable private vulnerability reporting for this repository

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2843]
GitHub has recently introduced a feature called [Private vulnerability reporting](https://github.blog/2023-04-19-private-vulnerability-reporting-now-generally-available/), which would allow security researchers to privately disclose a vulnerability without relying on back-and-forth emails. Unfortunately, it is currently not enabled for this repository.

You can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by DavidXanatos** [comment]
Should be enabled now
