### ISSUE TITLE
[1.8.4/1.9.0] Plus entry in Languages.iss was not updated correctly in the installer

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2847]
1. Download [Sandboxie-Plus-x64-v1.9.0.exe](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.0)
2. Open the installer and set Italian as language
3. Move forward until the following screen:

![Sandboxie-Plus-x64-v1.9.0.exe](https://user-images.githubusercontent.com/12372772/233811770-dfa259bc-cbad-4ea5-9589-a0bc8a823b8a.png)

The last line was already translated in the repository weeks ago and doesn't reflect what appears in the installer:
https://github.com/sandboxie-plus/Sandboxie/blob/71e5bdba245957393186ed1c1618c8e9d3fe1ed9/Installer/Languages.iss#L229

[Note: this also happened with v1.8.4](https://user-images.githubusercontent.com/12372772/230728889-1c97974d-9391-4556-8c8c-3c4431b30898.png), but still no fix.

**Comment by DavidXanatos** [comment]
right this needs a fix... I'll look into changing the release build process such as to reduce dependencies on hard coded assets and use instead assets from github.

**Comment by DavidXanatos** [comment]
fixed with 1.9.2 the installers are built from files included in the new assets.zip artefact which is assembled form the latest files on github
this should resolve the outdated installer files issue once and for all
