### ISSUE TITLE
Update to v5.45.1, Japanese display is also strange in some places.

### ISSUE THREAD

**Issue by jp-Man** [sandboxie-plus/Sandboxie#285]
When installing the program, sometimes Japanese font is strange. And when I click start button, also Japanese font is broken.
Could you fix them? Thanks.
![2020-12-26](https://user-images.githubusercontent.com/76592026/103146799-97f24880-4791-11eb-90c2-be6b8f68f4ec.png)
![install](https://user-images.githubusercontent.com/76592026/103146800-988adf00-4791-11eb-885f-0f7c4a62e26e.png)
![start](https://user-images.githubusercontent.com/76592026/103146801-99237580-4791-11eb-9bcc-c13c4e78eb69.png)

**Comment by DavidXanatos** [comment]
I have uploaded a fixed installer please use it..
the bad links you will need to delete by hand though
