### ISSUE TITLE
Limiting the number of same log messages

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2856]
### Is your feature request related to a problem or use case?

In some cases, the same log message is repeated dozens of times and is unpleasant. Instead, it's better not to show the same log messages consecutively over a period of time.

### Describe the solution you'd like

Current:
```
00:07:07.157 Access to ABC is blocked for some reason
00:07:07.557 Access to ABC is blocked for some reason
00:07:08.157 Access to ABC is blocked for some reason
00:07:08.557 Access to ABC is blocked for some reason
00:07:09.157 Access to ABC is blocked for some reason
00:07:09.557 Access to ABC is blocked for some reason
00:07:10.157 Access to ABC is blocked for some reason
```

Instead: (three second period)
```
00:07:07.157 Access to ABC is blocked for some reason
00:07:10.157 Access to ABC is blocked for some reason (x6)
```

### Describe alternatives you've considered

Or a feature similar to `Monitor mode` (Trace log) could be considered for normal logging.

**Comment by DaneXtream** [comment]
Do you suggest merging only the message or the line itself? 
What if you need the timestamp to investigate an issue for its frequency?

Anyway, it is a nice feature but it should be implemented like in the Console of Chromium browsers, meaning that, when you click the parent line it should be expanded into multiple child lines, each one having its own unique details (like timestamp for e.g.):
![image](https://user-images.githubusercontent.com/59374963/237034391-62b97136-f714-4905-b2e1-b2394aa493d3.png)

**Comment by offhub** [comment]
Of course, it would be even better if the grouped messages could be expanded so that we could access the details of these messages when we need them.
