### ISSUE TITLE
Running the Insert chart in Word in the sandbox fails

### ISSUE THREAD

**Issue by lmou523** [sandboxie-plus/Sandboxie#2863]
### Describe what you noticed and did

![image](https://user-images.githubusercontent.com/59944420/234751191-a52e96e5-5421-4eb4-b470-914960b23c17.png)
![image](https://user-images.githubusercontent.com/59944420/234751240-3024d59f-e417-47c7-891b-2d378c1ae332.png)
![image](https://user-images.githubusercontent.com/59944420/234751341-8fa3dcce-442e-490f-96cb-e545a79c9c7e.png)
![image](https://user-images.githubusercontent.com/59944420/234751386-6489deeb-bb10-4ab0-b067-6f958807c560.png)
![image](https://user-images.githubusercontent.com/59944420/234751431-74e6954f-06c1-472f-8641-f9c9368324ac.png)
![image](https://user-images.githubusercontent.com/59944420/234751494-19e0b405-2c79-49bc-a9eb-d1c84f3df231.png)

The excel startup command line appears to be truncated

### How often did you encounter it so far?

every time

### Affected program

office 2016

### Download link

不相关

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

excel opens normally

### What is your Windows edition and version?

windows 10 pro workstation 22h2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

windows Defender

### What version of Sandboxie are you running?

sandboxie5.64.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie-Plus configuration file
#

[GlobalSettings]
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing

[UserSettings_084E01A2]
SbieCtrl_WindowCoords=174,30,724,450
SbieCtrl_UserName=lmdd
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_ActiveView=40021
SbieCtrl_ExplorerNotify=n
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_ReloadConfNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_TerminateWarn=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_AutoApplySettings=n

[DefaultBox]
ConfigLevel=10
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
OpenFilePath=%Desktop%\Tem\DebugLog\*
BorderColor=#00FFFF,ttl,6
Enabled=y

[UserSettings_176402EB]
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
SbieCtrl_UserName=teclink
SbieCtrl_NextUpdateCheck=1683011338
SbieCtrl_WindowCoords=137,297,1066,506
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EditConfNotify=n
SbieCtrl_ReloadConfNotify=n
SbieCtrl_ExplorerNotify=n
```

**Comment by lmou523** [comment]
Outside the sandbox, word initiates excel's command behavior
![image](https://user-images.githubusercontent.com/59944420/237021809-f096a650-599b-4824-ad74-bafbfed10031.png)
The command behavior of excel when it starts
![image](https://user-images.githubusercontent.com/59944420/237022124-52b367f9-f6db-49eb-b1d3-f2ed1ad8e02d.png)

It has two more excel directories "

According to my research, when calling createprocessinternalw, word in the sandbox was passed the correct command line when excel started, but excel didn't have those two " symbols when Excel started

**Comment by offhub** [comment]
Did you try with the latest version?

**Comment by lmou523** [comment]
> Did you try with the latest version?

yes
