### ISSUE TITLE
System tray icon hourglass overlay gets stuck when operation is stopped

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2869]
### Describe what you noticed and did

System tray icon hourglass overlay gets stuck when operation is stopped.

1. Delete Content
2. Right click and stop the operation before the operation is complete.
3. The hourglass is stuck.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

It shouldn't be stuck.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.2846)

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.9.2 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

**Comment by DavidXanatos** [comment]
I can not reproduce this issue when i test it the icon always properly reverts to no hour glass

**Comment by offhub** [comment]
Try adding a `OnBoxDelete` trigger to the box.

1. Set `OnBoxDelete` trigger (ping 1.1.1.)
2. Enable `Run box operations asynchronously whenever possible (like content deletion)`
3. Run anything in the box and close it.
4. Delete the contents of the box
5. Right click and stop the operation before the operation is complete.



https://github.com/sandboxie-plus/Sandboxie/assets/6871698/5ed320d6-887f-4805-ac4c-257819e41d77

**Comment by DavidXanatos** [comment]
thanks found it
