### ISSUE TITLE
Firefox 112.0.2 crashed with Sandboxie 5.64.2

### ISSUE THREAD

**Issue by asbai** [sandboxie-plus/Sandboxie#2879]
### Describe what you noticed and did

1. Install firefox 112.0.2 inside or outside a sandbox.
2. Luanch firefox.
3. Firefox start and show "Gah. Your tab just crashed."

Except that the tab cannot render a web page correctly, the settings, bookmark manager, plug-in manager and other windows are working normally.

If we disable sandboxie and run firefox out of it, everything is ok.

### How often did you encounter it so far?

everytime

### Affected program

Firefox 112.0.2 x64

### Download link

https://www.mozilla.org/en-US/firefox/112.0.2/releasenotes/

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Firefox not crash

### What is your Windows edition and version?

Win7 x64 64bit

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

none

### What version of Sandboxie are you running?

5.64.2

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than v1.5.3 / 5.60.3.

### Is it a regression?

not sure

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by DavidXanatos** [comment]
try latest firefox 113.0 with it i have no issues

**Comment by asbai** [comment]
Hi David, 

Thanks for your quickly reply.

> try latest firefox 113.0 with it i have no issues
Firefox 113 still in the beta channel, did you try Firefox 112.0.2 with sandboxie?

**Comment by DavidXanatos** [comment]
As it works fine on my system, what else may have changed, does reverting to a older sandboxie version help?

**Comment by asbai** [comment]
> As it works fine on my system, what else may have changed, does reverting to a older sandboxie version help?

I think no, I actually upgraded to 5.64.2 because I got this issue on sandboxie 5.55.22.  

Here is the ff's crash report: https://crash-stats.mozilla.org/report/index/2d252b1b-7a03-4ad4-9f77-f3ad30230502#allthreads

Again, if we let firefox 113 run out of the sandbox, then it works fine. But when I run it under the sandbox, even if it is a newly created sandbox that has not modified any configuration at all, firefox will crash. :((

**Comment by bastik-1001** [comment]
I used Firefox (64bit) 112 to 112.0.2 (current) with Sandboxie 1.8.4 to 1.9.2 (current) and did not see Firefox crashing.

**Comment by lissyx** [comment]
Not sure how much it relates, but this signature https://crash-stats.mozilla.org/signature/?product=Firefox&process_type=utility&signature=__delayLoadHelper2%20%7C%20_tailMerge_oleaut32.dll%20%7C%20mozilla%3A%3Amscom%3A%3AProcessRuntime%3A%3AProcessRuntime&date=%3E%3D2023-06-02T12%3A00%3A00.000Z&date=%3C2023-06-09T12%3A00%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-version&_sort=-date&page=1 shows a lot of volume on close time, from a 112.0.2 release and there's `SbieDll.dll` listed, and it would relate at least to 5.47.0, with many if not all crashed on Windows 10 32-bits.

**Comment by junkit** [comment]
I have the same problem with Firefox portable.  Running the latest, version 114.0.2 64-bit.  Running on Windows 11 Pro 64-bit.  Firefox runs fine, right out of the folder.  Interestingly, Sandboxie-Plus and Firefox portable work fine on my Windows 10 box.  Tried deleting the sandboxie.ini file and let Sandboxie-Plus recreate it, just in case it was the problem, but no joy.  I tried both v1.9.6 and v1.5.3, as I had fewer problems with that v1.5.3 in the past.  They both exhibited the same behavior.  I also tried the non-portable version of Firefox, v114.0.2, and had the same result, "Gah. Your tab just crashed.".

For S&Gs, I tried running Edge with Sandboxie-Plus, and that's when things got ugly.  My PC crashed, with a 2 second blue screen, then my PC automatically rebooted.  After my PC came back up, I immediately tried it again.  Got the same result.  I never even saw Edge.  Just blue screen, then reboot.

**Comment by lissyx** [comment]
@junkit Could you look into `about:crashes` and share IDs of those and submit them ?

**Comment by junkit** [comment]
@lissyx  Are you asking about "about:crashes" from Firefox?  If so, when I first launch FF in sandboxie and issue about:crashes, the response is "No crash reports have been submitted."  However, if I then try to do somewhere, say duckduckgo.com (it doesn't matter where), the tab crashes with "Gah. Your tab just crashed." and an offer to restore the crashed tab.  If I now type about:crashes, the tab crashes with "Gah. Your tab just crashed." again. So about:crashes now crashes the tab that worked before.  Crazy...

**Comment by lissyx** [comment]
Yes. Can you try to run the same profile outside of sandboxie so we can at least collect those crash reports ?

**Comment by junkit** [comment]
The exact same instance of FF portable works on my Windows 10 PC with SB.  I copied the FF portable folder between the two PCs.  Oh, and it works on my Win 10 laptop as well.

**Comment by lissyx** [comment]
> So I did that. Crashed the FF tab in SB. Closed FF. Then opened FF again, outside the SB and FF reports "No crash reports have been submitted." Doesn't, by definition, SB keep the data separated from the non-sandboxed version of FF?

I know nothing about Sandboxie. There should be a folder with the pending crashes, e.g. `$HOME/.mozilla/firefox/Crash\ Reports/pending/` so outside of the profile itself.

**Comment by junkit** [comment]
You know nothing about Sandboxie?  Are you talking about Sandboxie, versus Sandboxie-Plus?  Is that the confusion?  I'm using SB-plus.  

The folder "$HOME/.mozilla/firefox/Crash\ Reports/pending/" doesn't exist.  The "Crash Reports" folder only has an empty events folder and several InstallTimexxxxxxxx files.  Keep in mind, Firefox itself is not crashing.  Only the Tab.  Firefox itself is still running. 

Just for grins, I selected "New private window".  It popped up at first and then it gave me the "Gah. Your tab just crashed.", but Firefox kept running.  I'm sure it's because it is trying to load some information onto it's home page.  I have all my various versions of FF start with a blank page.  Maybe that's why they don't crash.  I can still go through its menus, etc.  It does not crash.

Thanks for your help!

**Comment by lissyx** [comment]
> You know nothing about Sandboxie? Are you talking about Sandboxie, versus Sandboxie-Plus? Is that the confusion? I'm using SB-plus.

Neither. I'm tracking issues on audio decoding on Firefox, and Sandboxie or Sandboxie-Plus might be related to some, so that's why i'm interested. The tl;dr is that I have seen in crash data some where either of those project's DLL are present, so I'd like to make sure we dont have a crash related here.

> 
> The folder "$HOME/.mozilla/firefox/Crash\ Reports/pending/" doesn't exist. The "Crash Reports" folder only has an empty events folder and several InstallTimexxxxxxxx files. Keep in mind, Firefox itself is not crashing. Only the Tab. Firefox itself is still running.

Of course, you need to find where that is on your system, and with Sandboxie/Plus in the play and Portable Firefox, I have 0 idea where that could be. The tab crashing indicated a `content` process has crashed. If you have empty folders then we're stuck with nothing actionable unfortunately.

**Comment by junkit** [comment]
I looked on my whole PC for the relevant crash reports (using Everything) and found none, except an old Thunderbird crash.

Anyway, I don't think this is a FF issue, as it still runs and doesn't crash.  Also, as I mentioned before Edge does crash the whole OS.  So this is a Sanboxie-Plus/Windows 11 issue.

Thanks anyway!
