### ISSUE TITLE
Sandboxie Plus: restore maximized state from systray 

### ISSUE THREAD

**Issue by vitidev** [sandboxie-plus/Sandboxie#288]
First, maximize window and close.

systray icon -> contenxt menu -> show/hide = open maximized window, as expected
double left mouse click on systray icon = restore latest manual changed size and position before maximized state.

**Comment by typpos** [comment]
Related (v0.6.5):  Restored-Window-Size is not remembered when closing Sandboxie-Plus main window and then re-opening from tray icon. Interestingly, column widths in sandbox-grid are recalled.

**Comment by NewKidOnTheBlock** [comment]
Can confirm this behavious for Sandboxie Classic.
When you first open Sandboxie Control, it always forgets the window size and location.
E.g. when you had it maximized or snapped to the left or right border of the screen.
It always opens in some limbo state where the menu bar is off screen.

**Comment by isaak654** [comment]
@NewKidOnTheBlock Did you try to apply [this](https://i.imgur.com/5hYXnmu.jpg) for Sbiectrl.exe?

**Comment by NewKidOnTheBlock** [comment]
No. I didn't. But I set a text scaling for my entire Windows of 110%.

**Comment by isaak654** [comment]
> SB should remember that it was maximized, though.

About the maximized state in Sandboxie Classic, I think it's normal behavior... definitely it looks awful on my monitor (2560x1440).

The only good thing to ask (as a new issue) is to implement high dpi support because Sandboxie Classic wasn't done to support high dpi scaling.

**Comment by DavidXanatos** [comment]
I wont be fixing minor UI issues with the classic ui that I did not cause myself.
Also the sandman UI seams to handle high DPI ok.

I know many people would like some UI development for the classic UI but that's just to much work for to little improvement.
