### ISSUE TITLE
About purchase a Sandboxie-Plus supporter certificate in China

### ISSUE THREAD

**Issue by occultID** [sandboxie-plus/Sandboxie#2882]
### Is your feature request related to a problem or use case?

 I'm sorry I'm not good at English, so I used translation software for my consultation.

About the sandboxie plus supporter certificate, I would like to understand the difference between buying it in your store and buying it on your Patreon, such as the expiration date, feature limitations, etc.

I want to buy a medium or large supporter certificate, but in China I and most Chinese income levels are much lower than those in developed regions such as Europe and the United States. And PayPal doesn't serve very well in China, Chinese has its own credit card system instead of Visa or Mastercard. I hope you will consider offering more appropriate prices for low- and middle-income areas like China, and offer additional payment methods such as WeChat Pay or Alipay.

### Describe the solution you'd like

I hope you will consider offering more appropriate prices for low-and-middle-income areas like China, and offer additional payment methods such as WeChat Pay or Alipay. Thank You.

**Comment by okrc** [comment]
#2813

**Comment by DavidXanatos** [comment]
We have created a stripe account which offers Alipay, and added it to the site, please try if it works.

If buying a real cert is to expensive just for testing we always have the 2,5€ test product which does not actually sell anything.

About offering geofanced pricing, I'm not sure about how to do that, also we wouldn't want westerners to hop on a Chinese VPN and get a 50% discount. Steam deals with this issue with IP bans, DRM and payment method validation. That's a lot of afford on one side and is not really consumer friendly on the other. 
I mean it wouldn't be out of the question to offer a discounted cert which is limited to 1 PC, has online activation which is geo-locked to the region it was sold for, and re checks it every 30 days, etc... but then that's Online DRM of the worse sort, something I actually deeply despise.

**Comment by kinlaevl** [comment]
> 

I did not find this purchase channel.
And it is almost impossible for the Chinese to use their local ip to access the Internet, and the method based on ip judgment may not be effective.
Like myself, I use network proxy and ip diversion 7*24, otherwise github will not be accessible.
This habit has been around for 7 years.
Also, it is difficult for Europe and the United States to use VPN to purchase in China, because some exist to block the VPN protocol.

**Comment by DavidXanatos** [comment]
its there just click on check out and then select somethign different then paypal:

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/d270d07c-3293-49d3-9bc6-2f7856bf5c3d)

**Comment by DavidXanatos** [comment]
since we now have allipay I'll close this
