### ISSUE TITLE
Sandboxie Plus: can't open the explorer

### ISSUE THREAD

**Issue by vitidev** [sandboxie-plus/Sandboxie#289]
sandboxie classic - explorer runs correctly

The same sandbox in the SandboxePlus (Run - Run explorer) cause error:

![Image 1](https://user-images.githubusercontent.com/2243958/103175093-2b9a4680-4870-11eb-907e-d82374fa7625.png)

translate

    Can't call the program
    "explorer.exe....
    system error code
    cannot find the file specified
    (2)

Win10 x64 Pro 1909

**Comment by DavidXanatos** [comment]
yea i know i broke that in the last build the language pack binary has a fix for that already: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.5.2/Sandboxie-Plus-v0.5.2-LangPack+Patch.zip

**Comment by bjm234** [comment]
![image](https://user-images.githubusercontent.com/25015553/103176263-5075c600-483e-11eb-844d-e8fc1608a0ea.png)
