### ISSUE TITLE
"Disable Security Isolation" causes a game to stop playing audio

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#2893]
### Describe what you noticed and did

1. Tick "Disable Security Isolation" (Security Options\Security Isolation) in box options
1.1. It is ticked by default in Application Compartment box. It is unticked by default in Standard box.
2. Launch [Pizza Syndicate](https://www.mobygames.com/game/2864/fast-food-tycoon/)

As a result the game has no audio. If the setting is unticked then the game's audio works fine.

### How often did you encounter it so far?

Always

### Affected program

Pizza Syndicate

### Download link

N/A

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

It would be expected that the game would play audio with "Disable Security Isolation" ticked.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Microsoft Security Essentials

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.3 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by bastik-1001** [comment]
I have not been using compartment type boxes, but it is indeed not to be expected to have those break something that works in a standard box. If anything, I expected a standard box and especially a hardened box to cause more compatibility issues.

Thank you for tracking compatibly in [this discussion](https://github.com/sandboxie-plus/Sandboxie/discussions/2927).

**Comment by bastik-1001** [comment]
I am on Windows 7 and I can reproduce this. I had never used a compartment box before, since I never felt the need to do so, but there is at least one game that plays audio in a normal box, but fails to play any sound when I run it in a compartment type box.

**Comment by DavidXanatos** [comment]
issue fixed, it was actually a major bug in app compartment mode handling it probably broke quite a lot other things to

**Comment by bastik-1001** [comment]
Then this being fixed, should make quite a lot of people happy.

**Comment by DavidXanatos** [comment]
You can try the new SbieDll.dll with the old build to test the fix already now
[SbieDll_1.10.1.1.zip](https://github.com/sandboxie-plus/Sandboxie/files/12063421/SbieDll_1.10.1.1.zip)

**Comment by DavidXanatos** [comment]
I cant reproduce the new issue i have pushed the new dll as 1.10.0a update please try updating the latest 1.10.0 version using the online update and set to the preview channel it should download the 1.10.1 sbiedll.dll and test if it works

**Comment by offhub** [comment]
It installs version 1.9.8.

**Comment by DavidXanatos** [comment]
updater should now update to 1.10.0b please try this build it should properly fix the issue for good
