### ISSUE TITLE
Sandboxie's expiration dialogs do not say anything about the free contributor certificates

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2896]
### Is your feature request related to a problem or use case?

As indicated in #2892 and #2926, there seem to be users who are unaware of the [free ways](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md#non-monetary-contributions) to get a contributor certificate.

### Describe the solution you'd like

All expiration dialogs in Sandboxie should contain a footnote about getting a contributor certificate. Because of this lack of transparency, we are potentially losing many users willing to contribute to the documentation.

**Comment by isaak654** [comment]
#2926

**Comment by DavidXanatos** [comment]
how is that:

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/2a72698c-88d0-4ce7-9f85-03f7cb04791e)

**Comment by isaak654** [comment]
It looks fine, maybe the support page could be improved as well:
![support_page](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/d01ba387-b98d-48dc-8f02-3717ce9e725a)

**Comment by DavidXanatos** [comment]
I have updated the links the first now goes to=sbie-obtain-cert and the renew links go to=sbie-renew-cert which all currently still point to the same location as to=sbie-get-cert but it gives us the ability to replace to=sbie-get-cert with a page explaining all the options and dispatching the user to the right place.

how about that:
![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/3fc05365-859f-4978-8a68-961223341eb7)

CharGPT is really great!!! 
I would have never come up with a sentence like this on my own: "Your support plays a vital role in the advancement and maintenance of Sandboxie."

**Comment by isaak654** [comment]
I've noticed a couple of typos, see pull #2932.
