### ISSUE TITLE
Sandboxed apps use copy of original user folder data

### ISSUE THREAD

**Issue by Mahdi321** [sandboxie-plus/Sandboxie#290]
What me and probably all users want is that it start from an empty folder and builds its own data. (Not copy them from appdata)
In current behavior sandboxed apps still can steal user data

**Comment by DavidXanatos** [comment]
I know its on my todo but its a big change...

**Comment by DavidXanatos** [comment]
since we already have this feature request here: https://github.com/sandboxie-plus/Sandboxie/issues/194 I'll close this one

**Comment by Mahdi321** [comment]
My request is different.
I want that you remove the code that copies content from user profile to sandbox. Why such thing should exists at all !!

**Comment by DavidXanatos** [comment]
Well if you show a file to a sandboxed program and the program wahts to write to it, you need to first make a copy such that it can modify an own instance instead of your original.
That code is necessary.

**Comment by bastik-1001** [comment]
Maybe it is an misunderstanding at what kind of security sandboxie was supposed to provide? It aims to prevent changes to be made to the files on a system as well as the system itself and not that something can read what the user has reading access to. Ideally one should create a separate user for the sandboxed applications to limit what user data those would have access to. Surely there can be restrictions placed on what files a sandbox can even read and the easier this can be set-up the more users would benefit from a sandbox in which a rogue application can even steal less user data.

**Comment by quangkieu** [comment]
How about if we create a new windows user profile and specify Sandboxie to run under that account?
