### ISSUE TITLE
Intel GPA installation error

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [sandboxie-plus/Sandboxie#2904]
### Describe what you noticed and did

1. Get Intel® Graphics Performance Analyzers (Intel® GPA).
2. Run a installer.
3. Choose installation path, I chose to D:\IntelSWTools\GPA
4. Wait for a while during installation process.
5. There will be a error.
![Intel GPA error](https://github.com/sandboxie-plus/Sandboxie/assets/24764335/864c936a-ec80-4d3b-bb89-c0da99d10571)

### How often did you encounter it so far?

Every time

### Affected program

gpa_23.1.1678843911_release-external_x64_standalone

### Download link

https://registrationcenter-download.intel.com/akdlm/irc_nas/18426/gpa_21.4.1639653662_release-external_x64_standalone.msi

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

Installation should be completed as normal.

### What is your Windows edition and version?

Windows 10 Pro 22H2 19045.2846

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.64.3

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than v1.5.3 / 5.60.3.

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
Try adding the following setting to the Sandboxie configuration.
`MsiInstallerExemptions=y`

#### Sandboxie.ini

> [DefaultBox]
.
.
.
MsiInstallerExemptions=y

**Comment by gandalfthewhite19890404** [comment]
> Try adding the following setting to the Sandboxie configuration. `MsiInstallerExemptions=y`
> 
> #### Sandboxie.ini
> > [DefaultBox]
> > .
> > .
> > .
> > MsiInstallerExemptions=y

Now i have this
![image](https://github.com/sandboxie-plus/Sandboxie/assets/24764335/41acb8df-38bb-4965-8128-6b280f35a1c2)

BUT software was installed. Should I create another issue topic?
