### ISSUE TITLE
Possibility of docking 'Sandboxie-Plus Notifications' into the tabs

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#2907]
### Is your feature request related to a problem or use case?

When a new event occurs, 'Sandboxie-Plus Notifications' window pops up.

### Describe the solution you'd like

Instead, I would like to dock 'Sandboxie-Plus Notifications' window as an additional tab, next to 'Sbie Messages', 'Trace log' and 'Recovery log'.

### Describe alternatives you've considered

It could also be displayed as a built-in window, the same way as 'Show File Panel' is.

**Comment by DavidXanatos** [comment]
The events in the PopUp notifications are all already included in the "Sbie messages" tab to disable the pop Ups you can use:

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/ad3b2394-81c6-4cf1-80a8-55910585168f)

that should already cover teh request if i understood it right.

**Comment by isaak654** [comment]
I would suggest rephrasing the option above as `Don't show the popups for all SBIE messages`.
