### ISSUE TITLE
(support) installers: Sandboxie vs Sandboxie-old?

### ISSUE THREAD

**Issue by grnassar** [sandboxie-plus/Sandboxie#291]
With the recent release, there seems to be a third option: Sandboxie Plus 0.5.2, with the new UI, and then SandboxieInstall and SandboxieInstall-old, both 5.45.1.  Do they both have the old UI?  What's the difference between the two otherwise?

**Comment by DavidXanatos** [comment]
The -old files have broken localization of the installer, they were the once i uploaded originally, after uploading the fixed once i kept the old files to not loose the download stats of those.
