### ISSUE TITLE
[Plus UI] Can't rename any sandbox when Show File Panel is enabled

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2912]
### Describe what you noticed and did

1. Enable the `Show File Panel` option in the View menu
2. Attempt to rename any existing sandbox (with existing data)
3. Error: https://github.com/sandboxie-plus/Sandboxie/blob/30ca30416c39201fd14212de3a7c79049515f05f/SandboxiePlus/SandMan/SandMan.cpp#L3034

Workaround: disable the file panel from the View menu.

Note: this can only be reproduced with existing sandboxes filled with data, not a new one.

### How often did you encounter it so far?

When the File Panel is shown on the main screen.

### Affected program

Conflict between File Panel and the Rename Sandbox feature.

### Expected behavior

I would like to be able to rename any existing sandbox (filled with data) even when the file panel is enabled.

### What is your Windows edition and version?

Windows 10 22H2 x64

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus v1.9.3 x64

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

No, only on all existing sandboxes filled with data.

### Sandboxie.ini configuration

```
[GlobalSettings]
TemplateReject=7zipShellEx
TemplateReject=RTSS
Template=OfficeLicensing
FileRootPath=X:\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
TemplateReject=WindowsRasMan
TemplateReject=WindowsLive
NetworkEnableWFP=n
```

**Comment by bastik-1001** [comment]
I can reproduce this with the same version of Sandboxie on the 64bit version of Windows 7.

This occurs, when `%sandbox%` is used in the file root path. When the path is something like `X:\Box\fixedstring`, the sandbox can be renamed while the data panel is open without producing this error.

**Comment by isaak654** [comment]
David has asked me via Slack to run [this](https://github.com/sandboxie-plus/Sandboxie/actions/runs/5006162772) test build to confirm the fix, but unfortunately I have received a crash dump in return (just sent to him).

**Comment by DavidXanatos** [comment]
new build should not crash
