### ISSUE TITLE
Don't show "No Inet" when WFP exceptions exist

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#2919]
### Is your feature request related to a problem or use case?

Problem: Sandboxie-Plus main window shows "No INet" even though WFP config contains permissive settings.

### Describe the solution you'd like

In Sandboxie-Plus main window, column "Status", show
* No INet = No internet access of any kind
* WFP = Internet access blocked with WFP, but at least one permissive setting exists

### Describe alternatives you've considered

Open sandbox settings and manually check if the sandbox is really locked down, before starting a program in it.

**Comment by bastik-1001** [comment]
Either "WFP" would need to change to "Restricted Internet" to include cases where WFP isn't used, but Internet access is restricted by blocking access to the network devices, or a third string has to be introduced for those cases like "Blocked Network Devices", although that might be confusing.

When I set up a box, with no Internet, but then allow Internet access I know that I make these changes, but when someone sets up a box for others to use, the label "No INet" can be confusing.

**Comment by DavidXanatos** [comment]
yea makes sence the labels are a bit confising... I'll look into fixing that one, 

but on a general note: should we may be replace these labels with icons this way we can put more in the status column and when the icons would have tool tips it would be clear what they mean?

**Comment by typpos** [comment]
To me, the essential change is simply to change "no inet" when there isn't, as it presents a risk.

Less important: I'd like to be able to quickly scan through 60+ sandboxes and see which ones have risk settings, eg, inet. Either icons with a consistent colour scheme (red=risk, green=safe) and fixed column position, or otherwise labels shown only for risky things, ie, if inet is off, show nothing as it clutters the column.

Icons are better as I can easily scan across many sandboxes, and they make better use of UI space. However, they are more work to implement (difficult to make nice ones; dark/bright mode; copy cell behaviour, etc) and I don't think it's worth it unless you're having fun.

Tooltips could be used for text labels so the text can be kept short.

**Comment by DavidXanatos** [comment]
Status wise we have currently
Auto Delete which is rendered as an overlay on the actual box icon
No INet
Network Share access
Drop admin rights
There will be an icon indicating ram disk and or encryption also rendered as an overlay on the actual box icon

and it might be nice to add a bunch more
like an icon indicating there are pending files to recover
an icon indicating is MSI exemptions are in place

**Comment by bastik-1001** [comment]
This can also be optional, so users can choose.

Please remember that there are people that can't tell some colors apart, red and green for the most part. To those the same icon with a red and green will probably fail.
