### ISSUE TITLE
Sandboxie Plus: Always show "Sandboxie window boder" not working on inactive/background sandboxed windows

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#292]
Inactive sandboxed windows do not show coloured borders despite "Always show" is chosen (on Windows x64 20H2). It would be nice to be able to set a different border colour on inactive windows.

**Comment by DavidXanatos** [comment]
what do you mean with inactive you mean put in the background?

**Comment by superkryodev** [comment]
Yes

**Comment by DavidXanatos** [comment]
imho that's normal behavior else it would be much more work

**Comment by superkryodev** [comment]
> 
> 
> imho that's normal behavior else it would be much more work

It's your call, although "always show" is then neither accurate nor much different from "when tiltle is in focus". In fact the latter is actually for "mouse hover" only and does not paint coloured borders when a sandboxed windows is in focus and active (eg text entering via keyboard) while the mouse cursor is outside the window.
