### ISSUE TITLE
Cache Sandboxie messages within the Plus UI

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2920]
### Is your feature request related to a problem or use case?

Sandman displays Sandboxie messages in the window, but those are cleared when Sandman is being terminated or when the language of the UI is changed, or when the view is changed from advanced to something else and back. (Maybe there are other ways to trigger them not being shown anymore.)

Sometimes I terminate Sandman and open it again, which does not let me see what it logged before. More often I change the language to check how a setting or an option is label. 

### Describe the solution you'd like

Cache those messages and display them, as backlog, just as they were when they got logged, when starting it again or when the interface is reloaded, upon changing the language. No need to change the language they are displayed in.

### Describe alternatives you've considered

Using the feature to log to file. This just means having to care to look at the file, which is not as convenient as looking at "Sbie Messages".

**Comment by isaak654** [comment]
Another alternative is to cache the messages via Windows registry: [Log Messages To A File](https://sandboxie-plus.github.io/sandboxie-docs/Content/MessagesFromSandboxie.html#log-messages-to-a-file)

**Comment by isaak654** [comment]
#2207

**Comment by DavidXanatos** [comment]
Well sandboxie is quite privacy conscious so except from a few startup relates driver messages nothing gets logged to for example the windows event log.

The thing is SandMan may be closed when applications run and throw messages, starting it when a boxed process starts is optional.

Now sandboxie can be configured to make the sbiesvc log all messages to C:\Windows\Sandboxie.log but that's not default and for debugging only.

I'm thinking log files are so 1990 we could add an option to log all sbie messages to the windows even log, and make sandman on start load a reasonable backlog from there.

This would not only cover UI changes, but also restart and even not running when a event happens...


what do you think?

**Comment by bastik-1001** [comment]
I appreciate the privacy conscious approach, which should be the default way for things. Good that you have that in mind.

I have enabled logging via the driver before, just in case to have something to look at when I think there is something I need to look at. I don't look at it by default. The message window of Sandman is always open, so I look at the messages that appear there. The issue was opened due to what could be missed by doing something that clears them, unexpectedly.

Maybe, adding a feature to log to the Windows event log, is a good idea. I can't tell. It also depends on how much work all of this entails. My idea was simple, store message to some place, read some of them back from there so the user can still see them, even when the UI is restarted, the language is changed, etc. It might not be worth the code.

**Comment by DavidXanatos** [comment]
related request https://github.com/sandboxie-plus/Sandboxie/issues/2207

**Comment by DavidXanatos** [comment]
in UI cache will be added with the next build, we need this for the troubleshooting wizard when in a mode without the message log

**Comment by bastik-1001** [comment]
Does that need to be enabled? It does not seem to be active, since when I switch languages, the message log is cleared.

**Comment by bastik-1001** [comment]
Ignore my previous assertion, this feature works.
