### ISSUE TITLE
Renaming a box with sandboxed run entries can break those entries.

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2921]
### Describe what you noticed and did

1) Create a new box (like `NewBox2`) where the path contains %sandbox% (Users are separated as well)
2) Add something to the sandbox, like placing `example.exe` at C:\example\ or something similar
3) Add a run entry, via the options for that box or by selecting the running process and select "Pin to Run Menu", where adds `RunCommand=example.exe|"C:\Sandbox\username\NewBox2\drive\C\example\example.exe"` to its ini section.
4) The entry in the run menu shows the icon and works just fine.
5) Rename the box to something else, like "Example"
6) (Obviously) the entry still points to the path with NewBox2 and therefore does not show the icon or function anymore

This might also be a problem when the box now named "Example" points to entries in NewBox2, and since the name NewBox2 is available, a newly created box can have that name, get filled with content that matches the run entry for Example and so Sandboxie executes example.exe from NewBox2, even though the user intended it to be from the Example box.

### Affected program

Sandman.exe

### Download link

This repo.

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Trying to ensure that when a box is renamed, its run entries are not being broken.

I am not sure, if whenever it gets added via the box option or the right click menu, it can simply contain %sandbox% instead of the folder name.

### What is your Windows edition and version?

Windows 7, should not matter

### In which Windows account you have this problem?

A local account (Standard user)., Not relevant to my request.

### Please mention any installed security software

Defender, but should not matter

### What version of Sandboxie are you running?

1.9.3 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (explicitly mentioned in this issue).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

**Comment by DavidXanatos** [comment]
Starting with 1.9.4 box root paths will be replaced by %BoxRoot%
please note that this fix will not be retroactively applied to already created RunCommand entries
