### ISSUE TITLE
camera buffering on discord sandboxie plus

### ISSUE THREAD

**Issue by Gorie2019** [sandboxie-plus/Sandboxie#2925]
### Describe what you noticed and did

i downloaded discord
then downloaded sandboxie-plus
logged into discord, joined a call and tried turning on camera, it acts like its going to turn on but it just sits there buffering the entire time

### How often did you encounter it so far?

everytime

### Affected program

discord

### Download link

not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

camera to turn on

### What is your Windows edition and version?

windows 11

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

protection is disabled

### What version of Sandboxie are you running?

newest sandboxie plus

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no

**Comment by DavidXanatos** [comment]
please reffer to the original issue: https://github.com/sandboxie-plus/Sandboxie/issues/1669
