### ISSUE TITLE
Unable to run Telegram

### ISSUE THREAD

**Issue by UnreaI** [sandboxie-plus/Sandboxie#293]
Sandboxie-Plus v0.5.2
Telegram v2.5.1
Windows 10 Pro 10.0.19041

Here is the error:
Telegram.exe (24508): SBIE2101 Object name not found: \Device\NamedPipe\hmpalert, error CreateFile (C0000022) access=0012019F initialized=1
PID 19092: SBIE2314 Canceling process Telegram.exe [24508 / 7]

**Comment by isaak654** [comment]
Did you enable Hitman Pro Alert template included in sandboxie?

**Comment by UnreaI** [comment]
> Did you enable Hitman Pro Alert template included in sandboxie?

No, I don't have that installed, however I do have SpyShelter Premium and Sophos Home Premium running. I just enabled Hitman Pro template and tried again. Telegram still wont open, no error popup this time. Telegram process is running in the background according to Task Manger however nothing showed up.

**Comment by isaak654** [comment]
I tried Telegram Desktop v2.5.1 with [this](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.5.3a) pre-release of Sandboxie-Plus-x64 and it works for me in a clean windows installation (and a new sandboxie.ini file too).

**Comment by UnreaI** [comment]
Okay, the problem is Sophos. I uninstalled it and everything works now. Kinda funny since this was owned by the same company haha
Thanks for the help! 👍
