### ISSUE TITLE
Firewall Rules - Enable a way to toggle via command line

### ISSUE THREAD

**Issue by TFWol** [sandboxie-plus/Sandboxie#2939]
### Is your feature request related to a problem or use case?

There are many occasions where I would like to quickly disable/enable internet to a program/group in a sandbox right before starting it, or even during specific operations.

There will be times where I'd like a program to have network access, but maybe not the python.exe in in its venv when starting up, only enabling it when I need a task performed later. 

Being able to quickly toggle internet access on/off for the group without constantly checking and unchecking boxes would make the whole process easier.

### Describe the solution you'd like

I would like a built-in method to toggle a defined firewall rule via commandline. 

It could maybe be done like below:
```
start.exe /box:<boxname> /fwrule <toggle/on/off> "<rule name>"
```

### Describe alternatives you've considered

Currently I have to rely on a script I made to parse the .ini to manipulate the entry.
It's a very hacky solution though and requires me to rebuild it for every rule in each sandbox I want to control.

**Comment by DavidXanatos** [comment]
do we really need that you should  be able to toggle any sansboxie.ini setting using the SbieIni.exe

**Comment by TFWol** [comment]
Interesting, that was sort of hidden since the docs lead to the archived forum.
I'll have to play around with this.
Thanks for pointing it out.

**Comment by TFWol** [comment]
@isaak654 I see #2901 is locked so I can't make a comment to direct it to this as a Solution, could you point it to this issue?

btw, here's a simple, limited use, script I threw together for myself using SbieIni.exe in case people are searching for ideas.
```powershell
<#
# Rough example to turn a sandbox's firewall rule on/off
# Assumes firewall rule has a simple layout ending in ",Allow;Protocol=Any" 
# and Sandboxie installed in typical location.
# Adjustments needed otherwise

# Example:
Sandbox name is "Some Box"
Ini entry is: 
NetworkAccess=<someGroup>,Allow;Protocol=Any

Running script to disable (include <>'s if group):
.\script.ps1 -Sandbox "Some_Box" -Program "<someGroup>" -Action "disable" 

#>

param (
	[Parameter(Mandatory=$true)][string]$Sandbox,
	[Parameter(Mandatory=$true)][string]$Program,
	[Parameter(Mandatory=$true)][string]$Action
)
$sbieini = "C:\Program Files\Sandboxie-Plus\SbieIni.exe"
$DisabledRule = "$Program,Allow;Protocol=Any"
$EnabledRule = "$Program,Allow;Protocol=Any"

$IsDisabled = (& $sbieini query $Sandbox NetworkAccessDisabled) -contains $DisabledRule
$IsEnabled = (& $sbieini query $Sandbox NetworkAccess) -contains $EnabledRule

if ($Action -eq "enable" -and $IsDisabled) {
	& $sbieini delete $Sandbox NetworkAccessDisabled "$DisabledRule"
	& $sbieini append $Sandbox NetworkAccess "$EnabledRule"
}
elseif ($Action -eq "disable" -and $IsEnabled) {
	& $sbieini delete $Sandbox NetworkAccess "$EnabledRule"
	& $sbieini append $Sandbox NetworkAccessDisabled "$DisabledRule"
}
```
