### ISSUE TITLE
[Plus UI] Sbie Messages, Trace Log, Recovery Log tabs should never hide some columns

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2940]
### Describe what you noticed and did

https://github.com/sandboxie-plus/Sandboxie/assets/12372772/00f697aa-7cab-45db-9fe6-906a3ddd3cad

Workaround: use the `Reset all GUI options` feature (unfortunately, it also resets any customized font scaling).

### How often did you encounter it so far?

Whenever I try to hide all columns in the Sbie Messages tab, Trace Log tab, Recovery Log tab.

### Affected program

Sandboxie Plus UI.

### Expected behavior

- [x] It shouldn't be possible to hide the `Message` column from the Sbie Messages tab
- [x] It shouldn't be possible to hide the `Process`, `Type`, `Status`, `Value` columns from the Trace Log tab
- [x] It shouldn't be possible to hide the `Box name` and `File Path` columns from the Recovery Log tab

### What is your Windows edition and version?

All Windows versions.

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.4 x64 (test build).

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

**Comment by isaak654** [comment]
I've just tested 82ca352338468c99a8ecbf5f6cddca105972ed6b and I have to report that the fix didn't work for the Trace Log columns.

In the following video, there is only the `Reset Columns` entry that loops infinitely through multiple right-clicks on the Trace Log columns:

https://github.com/sandboxie-plus/Sandboxie/assets/12372772/b41d7611-6fc6-41d7-91b3-ac81fded947a

**Comment by isaak654** [comment]
It looks like that you also excluded the Count column from being hidden... may I ask how the number of counts can be useful in a trace log?

**Comment by DavidXanatos** [comment]
i was just a bit over enthusiastic about setting foxed columns

**Comment by isaak654** [comment]
I think it is a bit too early to rejoice:

https://github.com/sandboxie-plus/Sandboxie/assets/12372772/fd4b3b39-7102-488a-9d4d-ef664fd16841

I was able to reproduce it with Plus 1.9.3 (official) / 1.9.4 (official) / 1.9.5 (test build with testsigning on) in Windows 10 22H2 x64 so far. 

I have no idea why I can't reproduce it in Win 7... in my Windows 10 machine I've already tried using a fresh Sandboxie-Plus.ini &  fresh Plus 1.9.3 / 1.9.4 installations with no result...

**Comment by DavidXanatos** [comment]
I think you just need to reset the gui once, at some point you must have disabled all columns here

**Comment by isaak654** [comment]
> I think you just need to reset the gui once, at some point you must have disabled all columns here

That didn't work and the issue persists with 1.9.5 x64 stable.

**Comment by offhub** [comment]
`Reset all GUI options` probably isn't resetting the lower sections. With SandMan.exe closed, try deleting the relevant lines from Sandboxie-Plus.ini.

`[MainWindow]`

**Comment by isaak654** [comment]
It didn't work, of course I also quit and restarted SandMan.exe.

**Comment by isaak654** [comment]
> With SandMan.exe closed, try deleting the relevant lines from Sandboxie-Plus.ini.

That was the point, now it's fixed, thanks!
So the bug we have here is the inaccuracy of the `Reset all GUI Options` feature.
