### ISSUE TITLE
[Plus UI] Crash after pressing the button "Show NT Object Tree" several times

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2943]
It seems it is possible to reproduce a sudden crash after pressing the Trace Log button "Show NT Object Tree" several times. 

At that time, I was simply taking a trace log related to a sandboxed session of notepad, until SandMan.exe completely crashed (without involving notepad, which remained sandboxed).

Crash dump: [SandMan.exe.7228.zip](https://github.com/sandboxie-plus/Sandboxie/files/11536105/SandMan.exe.7228.zip) (from `%LocalAppData%\CrashDumps\SandMan.exe.7228.dmp`)

- Microsoft Defender Antivirus
- Windows 10 Pro 22H2 x64 (no VM)
- It could be reproduced in any sandbox type (at least on my setup)

**Comment by DavidXanatos** [comment]
this is a generic error with how we handle teh customized QTreeViewEx control's model indexes wil have to look into a proepr fix

**Comment by isaak654** [comment]
This can be still reproduced with cfdc7bf (1.9.6 test build).

**Comment by DavidXanatos** [comment]
please test the newest commit thoroughly it should fix the issue, and hopefully not cause another one

**Comment by isaak654** [comment]
"Show NT object structure" takes around 3-6 seconds to switch off, while if you switch it on is rather immediate. Is it expected?

**Comment by DavidXanatos** [comment]
looks normal to me booth operations take quite a while

**Comment by isaak654** [comment]
This time I'm not sure, so I've shared with you a screen recording on Slack so you can get an idea.
