### ISSUE TITLE
Plus UI: Turn SBIE message IDs into clickable links

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#2953]
### Is your feature request related to a problem or use case?

Sandboxie logs messages into its message tab in the Plus UI (Sandman.exe) with the IDs like SBIE2217, but a user would have to search for it, if he wants to check if he can change it or what might be causing it.

### Describe the solution you'd like

Since I am not sure, if the old UI could do that, I only suggest that for the plus UI.

Namely, having the message log of the UI turn IDs into links to documentation. So a message that contains SBIE2217 looks like this:

> process.exe (PID): [SBIE2217](https://sandboxie-plus.github.io/sandboxie-docs/Content/SBIE2217.html) Message that is translated [possibly other codes, like NT codes]

By proving a link to documentation, the user gets access to that information easily in his browser, can search for more information or follow instructions rather easily, copy content from the documentation.

### Describe alternatives you've considered

This is just to guide people to where they can help themselves. It may or may not help to improve the experience of using Sandman. There might be other ways to get this done.

Edit: Those links may point to other places than github, like [https://sandboxie-plus.com/sandboxie/sbie2217/](https://sandboxie-plus.com/sandboxie/sbie2217/), it was just meant to be an example.

**Comment by DavidXanatos** [comment]
I like the idea and with Qt it should be easy enough, I hope we will see...

**Comment by bastik-1001** [comment]
Tooltips, that provide some deeper information, that goes beyond the message that got logged, can still be helpful. Links and tooltips are not mutually exclusive.

**Comment by DavidXanatos** [comment]
Not good, Qt natively does not support rich text in QTreeWidget's :/ so no simple link adding

**Comment by DavidXanatos** [comment]
![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/b885f090-3761-4d6d-bb41-db5195f27d62)

**Comment by DavidXanatos** [comment]
this isinternally not the best solution we crate a qlabel for each line whcih contains a link,
but it works and we shoudl have have infinite log lines anyways so it hsould not be to wastefull

**Comment by bastik-1001** [comment]
This seems to work just fine. I triggered a message to test and the link send me to helpful information.

**Comment by offhub** [comment]
When clicking on the links in the pop-up message window, the links do not open.
