### ISSUE TITLE
Sandboxie-Plus-x64-v1.9.4 causes blue screen on boot at Win10X64

### ISSUE THREAD

**Issue by 7starsseeker** [sandboxie-plus/Sandboxie#2957]
### Describe what you noticed and did

After update Sandboxie-Plus to v1.9.4 and restart, my computer goes into the bluescreen loop on boot. It shows "Driver_corrupted_mmpool".
after uniinstall Sandboxie-Plus-x64-v1.9.4 in secure mode, all things seem well.
The system of my computer is Win10X64 22H2.
The previous version, such as Sandboxie-Plus-x64-v1.9.3, is fine.

### How often did you encounter it so far?

every time on boot

### Affected program

sandboxie-plus-x64-v1.9.4

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.4

### Where is the program located?

Not relevant to my request.

### Expected behavior

please fix it

### What is your Windows edition and version?

Windows 10 pro x64 22h2

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Huorong security

### What version of Sandboxie are you running?

1.9.4 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (explicitly mentioned in this issue).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
this is not good could you please provide a crash dump

**Comment by 7starsseeker** [comment]
sorry, but I don't know how to generate a crash dump file...
I just could report it via here...

**Comment by DavidXanatos** [comment]
on my windows 10 22h2 it works fine could you pelse post your sandboxie ini and the exact build number of your version also if you are using HVCI or alike

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/13be74f9-aadb-456c-8291-a9ee697c4364)


type msinfo32  in a command promot and enter and post this screen:

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/714cc957-8200-4501-ae33-cc6b68b106a3)


A crach dump should be autoamtically created and put into C:\Windows\Minidump

**Comment by 7starsseeker** [comment]
OK, I will close this comment and to post a new comment with those files.

**Comment by isaak654** [comment]
#2958
