### ISSUE TITLE
sbie:// links are not working

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2959]
### Describe what you noticed and did

1. Create a new box
2. Select another box type
3. Click on a link

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The links should work.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.2965)

### In which Windows account you have this problem?

An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.9.4 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by bastik-1001** [comment]
Yes, the links in Sandman don't work. For me, they don't do anything.

**Comment by offhub** [comment]
The links in the `Box Options` do not work.

**Comment by DavidXanatos** [comment]
which once exactly there are a few?

**Comment by offhub** [comment]
`Sandbox Options` > `General Options` > `Box Options` > `General Configuration` > `Box Type Presets:`
