### ISSUE TITLE
Don't close submenus on mouse-leave

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#2963]
### Is your feature request related to a problem or use case?

Win10x64
SB+ 1.9.3

A usability gripe with sandboxie is that submenus close rather quickly when the mouse does not hover. This makes it difficult to navigate deep nested menus in the application and in particular the traybar context menu.

Would it be ok to switch off the submenu timeout? I don't know if this is an accessibility feature or a cross-platform idea in Qt, but other applications on Windows don't exhibit this behavour.

Repro:
* tray icon context menu > Rclick > BoxName > Run > Standard Applications > (move mouse away from menu)
* menu closes

likewise for SB+ sub-menus.

On my system, the default timeout is set to 400ms. Maybe I'm slow or not precise enough...

### Describe the solution you'd like

Menus stay visible. There is no need to auto-close until they lose focus.

### Describe alternatives you've considered

Something like so, but there might be a better solution...

SandMan\main.cpp

````
// Stop submenus from closing
class PreventSubMenuTimeoutStyle : public QProxyStyle {
public:
	PreventSubMenuTimeoutStyle(QStyle* style = 0) : QProxyStyle(style) {}

	int styleHint(StyleHint stylehint, const QStyleOption* opt = nullptr,
		const QWidget* widget = nullptr, QStyleHintReturn* returnData = nullptr) const
	{
		if (stylehint == SH_Menu_SubMenuSloppyCloseTimeout) return -1;
		return QProxyStyle::styleHint(stylehint, opt, widget, returnData);
	}
};

...
QtSingleApplication app(argc, argv);
app.setQuitOnLastWindowClosed(false);

// qDebug() << "default timeout equals " << app.style()->styleHint(QStyle::SH_Menu_SubMenuSloppyCloseTimeout);
auto st = new PreventSubMenuTimeoutStyle(app.style());
app.setStyle(st);
````

**Comment by DavidXanatos** [comment]
I don't see a quick fix at a first glance,
we can go with this one.

**Comment by DavidXanatos** [comment]
nope that seam to break some ohther UI parts wil have to test it further

**Comment by typpos** [comment]
I'm overriding `SH_Menu_SubMenuDontStartSloppyOnLeave` which seems to have limited use in Qt:
https://github.com/search?q=repo%3Aqt%2Fqtbase%20SH_Menu_SubMenuDontStartSloppyOnLeave&type=code
https://github.com/search?q=repo%3Aqt%2Fqtbase%20m_dont_start_time_on_leave%20&type=code
https://github.com/search?q=repo%3Aqt%2Fqtbase%20QMenuSloppyState&type=code
