### ISSUE TITLE
Sandboxie-Plus: Sandbox file system root setting in Sandboxie.ini is not respected in portable mode

### ISSUE THREAD

**Issue by superkryodev** [sandboxie-plus/Sandboxie#298]
In portable mode since 0.5.3a and upon connection to SBIE, the sandbox file system root is changed automatically to ..\SandBoxes relative to the portable Sandboxie-Plus directory irrespect whether the root is set in Sandboxie.ini.

**Comment by DavidXanatos** [comment]
yes that's the idea for portable mode thats very usfull isn't it?
you can disable this behavioure with 
[Options]
PortableRootDir=false

**Comment by superkryodev** [comment]
> 
> 
> yes that's the idea for portable mode thats very usfull isn't it?
It is. However portable could be used for keeping the registry clean while storing in the sadboxies in other locations
> you can disable this behavioure with
> [Options]
> PortableRootDir=false

Ah, thanks. Perfect!

**Comment by DavidXanatos** [comment]
I'll add a checkbox for the user to select if he wants this behavioure or not that will show in portable mode.

**Comment by superkryodev** [comment]
> 
> 
> I'll add a checkbox for the user to select if he wants this behavioure or not that will show in portable mode.

Much appreciated
