### ISSUE TITLE
SandMan: Timestamp of the Sandboxie.ini

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#2985]
### Describe what you noticed and did

Just a reminder as it probably gets lost in the Wilders Security Forums:

Since version 1.9.4 SandMan updates the timestamp of the Sandboxie.ini at every startup.

Since the box grouping is saved in the Sandboxie.ini, its timestamp is also updated after opening and directly closing the Sandbox Options (using Cancel = no changes).

---

https://www.wilderssecurity.com/threads/sandboxie-plus-1-9-4-1-9-5.451545/#post-3147860
https://www.wilderssecurity.com/threads/sandboxie-plus-1-9-4-1-9-5.451545/#post-3147861
https://www.wilderssecurity.com/threads/sandboxie-plus-1-9-4-1-9-5.451545/#post-3147903
https://www.wilderssecurity.com/threads/sandboxie-plus-1-9-4-1-9-5.451545/page-2#post-3147995

### How often did you encounter it so far?

See description

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

It would be desirable if the timestamp of the Sandboxie.ini would only be updated if the data in it has actually changed. Without a change in the data, the timestamp should not be updated.

### What is your Windows edition and version?

Windows 10 Pro, 22H2, 64-bit

### In which Windows account you have this problem?

An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

1.9.5

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

1.9.4

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
changing timestamp when sandman starts <- fixed
changing of timestamp when opening and canceling <- not reproduced 

found new issue colapsing/expanding a sandbox changes sandboxie.ini as that info is also storred there.
how to fix, 
don't save that info at all?
or save in plus ini?

**Comment by APMichael** [comment]
> changing timestamp when sandman starts <- fixed

Great, thanks for the quick fix.

> changing of timestamp when opening and canceling <- EDIT: found it i think

Good, because this always happens with my SandMan, on all my systems.

> found new issue colapsing/expanding a sandbox changes sandboxie.ini as that info is also storred there.
> how to fix,
> don't save that info at all?
> or save in plus ini?

Since data respectively a setting is changed here, this is ok for me. As far as I know, this was already the case with the "original" Sandboxie.

**Comment by DavidXanatos** [comment]
I have moved that data back to the plus ini, expanding or comapsing a group happens fast and is not that relevant, so loosing thet preset sometimes when monkeying around with different sandboxie.ini's is acceptable imho

**Comment by APMichael** [comment]
> I have moved that data back to the plus ini, expanding or comapsing a group happens fast and is not that relevant, so loosing thet preset sometimes when monkeying around with different sandboxie.ini's is acceptable imho

I fully agree with you. Thanks again for the quick implementation. 👍
