### ISSUE TITLE
[1.9.6] When the Trace Logging feature is enabled, the Keep Terminated feature is also enabled with it

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2988]
### Describe what you noticed and did

1. Enable the `Trace Logging`
2. Will also turn on the `Keep Terminated` 

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

https://github.com/sandboxie-plus/Sandboxie/suites/13224525377/artifacts/720425973

### Where is the program located?

Not relevant to my request.

### Expected behavior

No other feature other than the `Trace Logging` should be enabled with it.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.2965)

### In which Windows account you have this problem?

An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.9.6 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/9303566c-5d9b-4c60-bcdb-fa38ac3e4a4b

**Comment by DavidXanatos** [comment]
this is not a but but new intended behavioure,
without it the stack trace in the trace log would not work properly, as we use the process objects to cache the symbols
