### ISSUE TITLE
Sandboxie uses the HOSTS file from the host

### ISSUE THREAD

**Issue by blap** [sandboxie-plus/Sandboxie#2993]
### Describe what you noticed and did

I changed Windows HOSTS inside a box and Sandboxie Plus uses HOSTS from the host.

### How often did you encounter it so far?

Always when I changed HOSTS inside a box

### Affected program

All

### Download link

Not relevant

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Sandboxie Plus uses "..Windows\System32\Drivers\etc\HOSTS" from a box. I think it will be a good idea Sandboxie Plus uses HOSTS from a box, avoiding editing HOSTS from the host. Manipulate the INI file of a box with many IPs and many times can be exhausting without any kind of automation.

### What is your Windows edition and version?

Windows 10 Home 22H2 64-bit

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.6 64-bit Portable

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version.

### Is it a regression?

Not relevant to my request.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No.

**Comment by isaak654** [comment]
Your outcome might be related to a combination of the following points:

> An account with UAC protection completely turned off.
>
> In a standard isolation sandbox (yellow sandbox icon).

Furthermore, this seems to be one of the limitations described in [Privacy Concerns](https://sandboxie-plus.github.io/sandboxie-docs/Content/PrivacyConcerns.html):

> Windows DNS Host Cache
> 
> Sandboxie does not prevent the logging and storage of DNS Hosts files (Your DNS cache) on your Windows machine. This is written to C:\Windows\System32\drivers\etc in Windows.

Personally I would be glad if something could be done for it.

**Comment by isaak654** [comment]
#1814

**Comment by offhub** [comment]
[According to the roadmap](https://www.wilderssecurity.com/threads/sandboxie-roadmap.445545/), there will be DNS filtering in future versions.

**Comment by DavidXanatos** [comment]
This behavior can not be realistically changed, DNS resolution usually works like this: a sandboxed process asking a service on the host to resolve a host name that service then checks the hosts HOSTS file, the system wide DNS cache, and then the remote DNS server.

So a sandboxed HOSTS file is here completely left aside.
This is why there is a custom DNS filter feature in the insider build of Sandboxie and will in due time find its way into the public release.
This filter works by intercepting the API's directly in the Sandboxed process which further down would the road would ask the hosts dns resolver service.

**Comment by blap** [comment]
> This behavior can not be realistically changed, DNS resolution usually works like this: a sandboxed process asking a service on the host to resolve a host name, that service then checks the host's HOSTS file, the system wide DNS cache, and then the remote DNS server.
> 
> So a sandboxed HOSTS file is here completely left aside. This is why there is a custom DNS filter feature in the insider build of Sandboxie and will in due time find its way into the public release. This filter works by intercepting the API directly in the sandboxed process which further down the road would ask the hosts dns resolver service.

It will be possible to change the DNS server of a box?

**Comment by DavidXanatos** [comment]
> 
> It will be possible to change the DNS server of a box too?

That is currently not in the scope of the feature, this would add substantial complexity.
What would be the use case for that?

**Comment by blap** [comment]
> > It will be possible to change the DNS server of a box too?
> 
> That is currently not in the scope of the feature, this would add substantial complexity. What would be the use case for that?

The idea was to be an alternative to HOSTS.
Some DNS servers block ads and others things. And some layer of privacy with dnscrypt.
I got the problem now.
It will be like creating a VPN driver to control something like this.

**Comment by DavidXanatos** [comment]
ok but than wouldn't you waht this blocking for the entire system?
Why only block adds in the sandbox but not on the host?

**Comment by blap** [comment]
> ok but then wouldn't you want this blocking for the entire system? Why only block ads in the sandbox but not on the host?

My real example here: I have an old 2 core notebook to test things. Using a big file HOSTS will consume a lot of resources here. I put thunderbird in a box, but many emails had ads and I need to load external images. So sometimes I use an DNS server to block ads in thunderbird. I don't know yet an easy way to do that.
