### ISSUE TITLE
SandMan: Empty lines when using "Copy Panel"

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#2995]
### Describe what you noticed and did

If you copy the "Sbie Messages" using "Copy Panel" and then paste them into a text editor, the lines with IDs are missing the complete text.

Example (the last two lines are messages with SBIE1301):
```
|Zeit|         |Nachricht|                                                

11:52:48.938   Installation Ordner: C:\Program Files\Sandboxie-Plus       
11:52:48.938   Sandboxie-Plus Version: 1.9.6 (5.64.6)                     
11:52:48.938   Aktuelle Konfiguration: C:\WINDOWS\Sandboxie.ini           
11:52:48.938   Datenordner: C:\Users\Admin\AppData\Local\Sandboxie-Plus   
11:52:48.938   Sandboxiekonfiguration wurde neu geladen                   
17:50:30.781                                                              
17:50:33.226                                                              
```

I guess this is a side effect of #2953.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

"Copy Panel" should provide a complete copy.

### What is your Windows edition and version?

Windows 10 Pro, 22H2, 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

1.9.6

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

I guess since 1.9.5 with fix #2953.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by bastik-1001** [comment]
I can reproduce this, and I also guess that my suggested change is the cause of it.

**Comment by APMichael** [comment]
Fix confirmed! :smile: Many thanks for that! 👍
