### ISSUE TITLE
Can't install some applications utilizing the Nullsoft installer: The file does not have an app associated with it for performing this action.

### ISSUE THREAD

**Issue by birdie-github** [sandboxie-plus/Sandboxie#3]
I'm running Windows 10 LTSC (which is based on Windows 1809) with all updates installed: Microsoft Windows Version 1809 (OS Build 17763.973). I'm running SandBoxie 5.33.1 - the application says it's the latest available version - no updates found.

I cannot install some applications which use the Nullsoft installer.

Sandboxie  is installed by default, nothing has been changed in its config.

Here's a sample application: https://www.hdtune.com/files/hdtune_255.exe

The errors are: The file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page. Unable to execute file in the temporary directory. Setup aborted. Error 1223: The operation was canceled by the user.

![error0](https://user-images.githubusercontent.com/4958603/79009073-3e3be680-7b4e-11ea-8f63-3204962ac327.png)

![error1](https://user-images.githubusercontent.com/4958603/79009083-4431c780-7b4e-11ea-81d5-67961cf61b6a.png)

The application can be installed directly without using SandBoxie. I'm a local administrator. UAC is off. I've verified that the installer unpacks a payload in the temporary location and it's a valid exe file though it doesn't have the usual extension (exe).

Here's the global settings section:
```
[GlobalSettings]

Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
```
(Strangely I don't remember ever installing MS Office or Windows Live).

**Edit: the issue affects Windows 10 built-in Administrator account only.**

**Comment by DavidXanatos** [comment]
Strange for me it worked just fine
![grafik](https://user-images.githubusercontent.com/3890945/79050835-ef18b300-7c2c-11ea-9b99-fd94ddeedbbf.png)


Here's the global settings section:
```
[GlobalSettings]

Template=7zipShellEx
Template=AdobeLicensing
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
FileRootPath=G:\Sandbox\%SANDBOX%
```

May be try clearing the sandbox content...

The most recent version here is 5.40.1, you can always find the most recent release at https://github.com/DavidXanatos/Sandboxie/releases
The version check in older Sophos builds wont longer work.

**Comment by birdie-github** [comment]
I'm using Windows 10 LTSC and it's reproducible right away. You can download it and trial it for 90 days: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise - choose "ISO - LTSC".

**Comment by birdie-github** [comment]
@DavidXanatos 

Cannot test the latest 32bit released version due to:

![error](https://user-images.githubusercontent.com/4958603/79051210-7a3e7c80-7c1e-11ea-94b0-d5f09edeb3d4.png)

**Comment by birdie-github** [comment]
@DavidXanatos 

After disabling drivers signatures verification I managed to make SandBoxie work, alas the error persists:

![error in 5 40 1](https://user-images.githubusercontent.com/4958603/79051340-313af800-7c1f-11ea-8a28-349964668d23.png)

**Comment by DavidXanatos** [comment]
So the first errors were on a x64 version?

About "disabling drivers signatures verification", bloody windows, i will re-upload a fixed 32 bit installer asap.

**Comment by birdie-github** [comment]
> So the first errors were on a x64 version?

Yes, they were from my host OS, now I'm testing in a VM as I'm too lazy to reboot.

> About "disabling drivers signatures verification", bloody windows, i will re-upload a fixed 32 bit installer asap.

Thank you! :-)

**Comment by DavidXanatos** [comment]
ok the 32 bit installer should now work.

i tested the 64 bit version of LTSC and it worked for me:
![grafik](https://user-images.githubusercontent.com/3890945/79051916-2e4a0280-7c33-11ea-8400-5921dbb1647b.png)

**Comment by birdie-github** [comment]
OK, then I will reinstall W10 LTSC again and recheck. It's OK if you close this bug report.

**Comment by birdie-github** [comment]
@DavidXanatos 

I've realized what the issue is, hooray! SandBoxie shows this error when **you're using it under the built-in Administrator account** (it's disabled by default). If you're using a newly created account (e.g. created during an installation) there's no error. Hope you can now reproduce it and fix it.

**Comment by DavidXanatos** [comment]
@birdie-github 

Indeed from the built in administrator i can reproduce this error as well.

I will look into it.

**Comment by DavidXanatos** [comment]
I have been investigating this issue and it seams that the elevation mechanism of sandboxie fails when run under the admin account as there is no such thing like elevation.

The proper fix would be to detect that its running as admin and skip this mechanism in such case,

**Comment by birdie-github** [comment]
@DavidXanatos 

> The proper fix would be to detect that its running as admin and skip this mechanism in such case,

This sounds like a simple fix, no?

**Comment by birdie-github** [comment]
@DavidXanatos 

Are you going to fix this issue? No rush, I'm just curious.

**Comment by DavidXanatos** [comment]
@birdie-github 
I intent to fix that somehow at some point but as the issue affects only the built in Administrator account and no other user accounts its not very high priority unfortunately.

**Comment by DavidXanatos** [comment]
I found a fix and its quite easy first we don't apply any out of palce atempts to elevate using uac, also we use teh enw fake admin rights option for the build in administrator account by default
