### ISSUE TITLE
Sandboxie Created Official GitHub Repository

### ISSUE THREAD

**Issue by DavidBerdik** [sandboxie-plus/Sandboxie#30]
It seems the the Sandboxie team moved the download to an official repository: https://github.com/sandboxie/sandboxie

I am not suggesting that this version of the repository be removed, but it might be worth keeping an eye on the official repo for changes.

**Comment by Gravityzwell** [comment]
I don't see a binary release at the other repo, and maybe never will unless they donate the kernel certificate, and that may be impossible even if they wanted to.

**Comment by DavidXanatos** [comment]
Tom already purchased a EV Certificate so a signed release should appear in the weeks to come.

**Comment by DavidBerdik** [comment]
@Gravityzwell Oh yes I know that. I was planning on sticking with this repo, as it seems more well-supported. I was merely pointing out that perhaps that repository might be worth keeping an eye on for patches, although it seems that @DavidXanatos already knew about it.

@DavidXanatos Ah okay! I assumed that it was official. Since you know about it, I'll close this.
