### ISSUE TITLE
Why so many alerts?

### ISSUE THREAD

**Issue by doclucas** [sandboxie-plus/Sandboxie#300]
I know there were some false positives reported for avast and other AVs, but I am now getting alerts from:
- Google chrome says the file is potentially dangerous, when downloading
- Windows smart screen says the same when trying to install
- Symantec endpoint protection flags the downloaded file as not trustworthy and blocks installation

Why so many alerts?

**Comment by NewKidOnTheBlock** [comment]
See #238

**Comment by DavidXanatos** [comment]
Any executable is potentially dangerous, just that for some chrome & co don't tell you that.
