### ISSUE TITLE
Firefox 114 crashes in security enhanced box, when start restrictions are enabled

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3019]
### Describe what you noticed and did

I updated Firefox from 113 to 114 and after that Firefox crashed with the box I dedicated to it, without changes to Sandboxie or updating it. 

The starting process crashes, but Firefox shows and window and can be used.

I tried another box and Firefox worked just fine, so I knew it was related to the box I was using, so I disabled some setting, until I found what was causing it, apparently.

0) Have Firefox 114 installed into the system
1) Create a new box with security enhancement (orange box) or security hardened box with privacy (red box, the one that I was using originally)
2) Keep the default settings while setting up
3) Enable start restrictions to allow only listed programs to start
4) Add firefox.exe to the list of allowed processes (ClosedIpcPath=!<StartRunAccess>,* gets added to the ini)
5) Start Firefox

This gets me the following error message from a Windows dialog (German):

> Die Ausnahme "unknown software exception" (0xc0000417) ist in der Anwendung an der Stelle 0xecc6d099 aufgetreten.
> 
> Klicken Sie auf "OK", um das Programm zu beenden.

Removing `ClosedIpcPath=!<StartRunAccess>,* ` (allowing every program to be started), lets me start firefox just as before.

### How often did you encounter it so far?

Whenever I start and close Firefox 114

### Affected program

Firefox 114 64bit

### Download link

https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Firefox not crashing, when start restrictions are being set.

### What is your Windows edition and version?

Windows 7 64bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Default Windows

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.6 64bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

1.9.6 64bit worked with Firefox 113, but not with 114

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).
And in the security hardened box with data protection (red icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by bastik-1001** [comment]
Obviously, Mozilla changed how Firefox does something, since Firefox 113 did not produce this result.

Of course, I can't be sure, what the change, is that is causing it. Their public release notes contain the following:
> Users on macOS, Linux, and Windows 7 can now use FIDO2 / WebAuthn authenticators over USB.

I am not sure, if that requires some syscall that is not being allowed when a security hardened is used and start-up restrictions are in place, or whatever.

**Comment by offhub** [comment]
Can you try with these settings?

![SandMan_20230607_213016_484](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/8e6cd617-fc81-4aff-a961-3cd83b5a5b39)

**Comment by offhub** [comment]
Try adding the following setting with everything enabled.

`NormalFilePath=\Device\Null`

**Comment by bastik-1001** [comment]
Re-enabling the security enhancements, which includes the device restrictions, while having the start restrictions in place and having `NormalFilePath=\Device\Null` works just fine. There is no crash.

**Comment by offhub** [comment]
It's the same problem, but it gives different errors due to the difference in operating systems. (?)

`https://www.wilderssecurity.com/threads/firefox-114-0-werfault-exe-error-messages.451656/`

**Comment by bastik-1001** [comment]
With the original setup, I got a message that firefox.exe has crashed, along with the Windows error showing the message I mentioned in the issue I opened and that werfault.exe could not be started due to start restrictions.

The linked thread does not show any message from Windows nor does Sandboxie report firefox.exe having crashed, as far as I can tell, but it is very much likely that the issue is the same.

**Comment by offhub** [comment]
> Looks like Firefox 114.0 (64-bit) is causing Werfault.exe error messages in Sandboxie Plus 1.9.6 (64-bit).

WerFault.exe was executed to generate a report when a process crashed, but Sandboxie's start restrictions prevented it from running.

We don't know if the workaround fixes or suppresses the problem. Perhaps @DavidXanatos can give a more appropriate answer.

**Comment by DavidXanatos** [comment]
The \Device\Null is a dummy for a device that does not do anything
so its safe to open it for all I'll add the
NormalFilePath=\Device\Null
line to the next build

**Comment by bastik-1001** [comment]
The crashes I got did not show up in `about:crashes`.

There was another Firefox release to address a start-up crash, I seemingly wasn't effected by.

**Comment by lissyx** [comment]
I'm asking because I see huge volume crashes like https://crash-stats.mozilla.org/report/index/08c605c8-4957-4e8c-ac05-10c480230612#tab-details with low volume clients, and to the best of my knowledge there's always a `SbieDll.dll` module listed.

**Comment by offhub** [comment]
Version 5.33.3 belongs to a rather old version before it became open source.

`SbieDll.dll 5.33.3.0 43588FC20E52483C81425ACC0511F94F1 SbieDll.pdb Invincea, Inc.`
