### ISSUE TITLE
Software compatibility

### ISSUE THREAD

**Issue by Dave3225413** [sandboxie-plus/Sandboxie#302]
Hi ! I've been looking for an answer to this on google but I can't find an answer. 

On Sandboxie Plus v.0.5.2, after install, the "software compatibility" setting pops up, pointing at several programs (antivirus, windows 10 COre UI etc...). I would like to be sure exactly what its going to do if I enable and apply it : 

-will it change the settings of the third party program (windows, bitdefender, etc) ? 
-or will it change the settings of sandboxie alone ?
-both ?

I really need to be sure what it is going to do before it does it...

Thanks for the help :)

![image](https://user-images.githubusercontent.com/76817407/103414786-ac628680-4b7f-11eb-8cbb-12bbc7da22e3.png)

**Comment by bjm234** [comment]
Compatibility templates open a hole in Sandboxie.  No changes are made in 3rd party. 
Most templates are old (Antivirus) and may or may not help with compatibility. 
You may leave them Disable and run 3rd party for an issue.  You may Enable or Disable at any time.

**Comment by isaak654** [comment]
> Compatibility templates open a hole in Sandboxie.

Sometimes they can help to close holes, it depends on the configuration of each template.
Only problem is that there aren't many templates in Sandboxie at this moment and not enough template creators.
This page is good enough to know the most common used parameters:
https://sandboxie-website-archive.github.io/www.sandboxie.com/SandboxieIni.html

**Comment by Dave3225413** [comment]
Thanks a lot for your enlightening answers!
