### ISSUE TITLE
Secure Downloads

### ISSUE THREAD

**Issue by BilleBarrett** [sandboxie-plus/Sandboxie#305]
When I download a document or a file I have to shut down Sandboxie Plus v.0.5.3a to be able to retrieve the items
I can follow the link to the Downloads folder but it is still on the Sandbox and I can't get it, until I shutdown Plus
This does work on the regular Sandboxie

**Comment by DavidXanatos** [comment]
I don't quite understand what you mean, you should be able to use explorer to copy the files out of the sandbox at any time.

**Comment by BilleBarrett** [comment]
Sorry, yes but I have to drill down to the downloads folder C:\Sandbox\BilleB\DefaultBox\drive\M\Downloads to copy the file, 
but if I terminate SandboxiePlus a window opens giving me the option of where I need to move the file

Now I have to restart my bowser and restore all my links to I can access all my clients again

I see you work on Saturday also, 
Happy New Year



Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
This is my reply mail signature

"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by BilleBarrett** [comment]
I do not have a problem drill down to the downloads folder, but my Sandboxie clients will and have no idea how to find these downloads.
Old Sandboxie open a windows the recovery window and let my clients decide where to put downloads, be for I can upgrade time to SandboxiePlus that has to happen. 
Some of my clients are real time users that down load may documents everyday
They will panic if they have to go looking for the downloads.

**Comment by DavidXanatos** [comment]
mmh... I think what you may be looking for is the AutoRecover=y option
in the plus build this is set to off by default when creating a new sand box, while on the classic one it was enabled.
You can set the value eider in the INI or find it in the Box options on the File Recovery page.

Happy New Year :-)

**Comment by DavidXanatos** [comment]
I'm quite surprised how many people actually use all that recovery things, for me that was always a sort of annoyance, the first thing to turn of.
I'll add a checkbox to the sandbox creation screen such that when creating a new box this can be choose outright.
I thin that is a good compromise between default on and default off..

**Comment by BilleBarrett** [comment]
I will have to  look on a client's computer I have already switched back to
PLUS

Remote Desktop Services
BilleBarrett@Gmail.com
336-988-0891
*Sent from my Gmail account*

*Microsoft does not make unsolicited call to people or contact on the
Internet*
