### ISSUE TITLE
Green box Failed to start the edge browser

### ISSUE THREAD

**Issue by lmou523** [sandboxie-plus/Sandboxie#3050]
### Describe what you noticed and did

Start your default browser with sbie-plus

### How often did you encounter it so far?

every time

### Affected program

Microsoft Edge 版本 114.0.1823.51 (正式版本) (64 位)

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Normal use of software

### What is your Windows edition and version?

windows11 pro 22h2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

windows Defender

### What version of Sandboxie are you running?

1.9.6 64bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
FileRootPath=C:\Users\32888\Desktop\sbiedir\Sandbox\%SANDBOX%
Template=7zipShellEx
Template=OfficeLicensing
Template=WindowsLive

[UserSettings_176402EB]
SbieCtrl_AutoStartAgent=SandMan.exe
BoxGrouping=:DefaultBox
SbieCtrl_EnableAutoStart=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10

#UnfilteredToken=y
#OriginalToken=y
#UnrestrictedToken=y
NoSecurityIsolation=y
#OpenCredentials=y
#RunServicesAsSystem=y

#OpenFilePath=*
#OpenKeyPath=*
```

**Comment by offhub** [comment]
It works on my VM.
> Windows 11 22H2 (22621.1848) [Hyper-V]
Microsoft Edge 114.0.1823.51

**Comment by lmou523** [comment]
> It works on my VM.
> 
> > Windows 11 22H2 (22621.1848) [Hyper-V]
> > Microsoft Edge 114.0.1823.51

On my machine it gives an error
![image](https://github.com/sandboxie-plus/Sandboxie/assets/59944420/dc442d84-96b0-49a4-8b52-f36f293c2d45)

**Comment by isaak654** [comment]
There is a [SbieDll](https://github.com/sandboxie-plus/Sandboxie/issues?q=label%3ASbieDll) label containing all SbieDll.dll issues, so you may want to check them in order to find a workaround or solution.

**Comment by wilders-soccerfan** [comment]
The Sandman UI shows SBIE1222  (I see only one post related to this message, #1143).

**Comment by DavidXanatos** [comment]
this issue is expected when not installing under program files, you can resolve it using the troublishooting wizard in the latest 1.10.x line of builds 
1222 is wrong and indicates an unrecognized message,
the new build has a dedicated message 2181, and offers to fix the issue

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/742d16a9-d546-4d1e-9ea7-4b4629e60ca4)

**Comment by Loyrli** [comment]
Indeed, I solved the problem by reinstalling the program in the default location.
