### ISSUE TITLE
Portable mode uses absolute path in configuration (not portable)

### ISSUE THREAD

**Issue by Nazosan** [sandboxie-plus/Sandboxie#3053]
### Describe what you noticed and did

The new portable mode is a nice feature I am grateful to see.  However, it does use an absolute path for the file system root and I could find no way listed to reference the root of Sandboxie itself.  There are variables for each individual sandbox and that sort of thing, but ultimately most come back to FileSystemRoot which contains an absolute path that would, therefore, have to be changed any time the drive letter it's running from is changed.  If you're actually running this from a USB flash drive it's potentially possible to have to manually change it virtually every time it's used.  It also doesn't want to accept relative paths (such as .\) which I wouldn't necessarily expect it to, but did try to be sure.

### Affected program

Sandboxie.ini / SandMan.exe

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

All it needs is a variable referencing the root folder of SandBoxie itself.  Eg %SandboxieRoot% or something to that effect.  With this it should be possible to avoid absolute paths in portable mode for normal operations.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.8 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
> All it needs is a variable referencing the root folder of SandBoxie itself. Eg %SandboxieRoot% or something to that effect. With this it should be possible to avoid absolute paths in portable mode for normal operations.

There is, it's called `%SbieHome%` ([Expandable Variables](https://sandboxie-plus.github.io/sandboxie-docs/Content/ExpandableVariables.html)).

**Comment by Nazosan** [comment]
Oh, I apologize then.  I do believe it should set this by default when installing in portable mode then (it puts an absolute path automatically.)  Possibly it would be useful if it had a link to that page in the configuration settings regarding these things too as it has separate links for each of the three main paths that go to pages which would lead one to believe those are the only variables.

**Comment by typpos** [comment]
Note that in Virtualization Scheme 2, deleted files are referenced by their device path (Harddisk Volume) in file "FilePaths.dat", for example:
* \Device\HarddiskVolume14\test.txt|1

So, when you remove and re-insert a drive and "HarddiskVolume14" changes for that drive, then your deleted files may reappear, or may vanish on a different drive, etc.

This applies regardless to if you run sanboxie portable or installed.

**Comment by DavidXanatos** [comment]
One should not put the sandbox folder inside %sbiehome% you an put it one layer up as the sandman UI offers to do in portable mode see the portable root folder option:
![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/2f624489-96d1-4044-8738-ce9e7b6a334d)

About the Virtualization Scheme 2 this is indeed somewhat of an issue, but with v1 its also partialy present when the driver letter of the usb stick changes, basically it just guaranteed to work for the windows partition C:\
I'll look if we can improve on that perhaps saving with the DOS drive letter when possible an using NT paths only when no DosDevice for that partition is available.

**Comment by typpos** [comment]
Maybe consider Volume GUIDs (GetVolumeNameForVolumeMountPointW). 

Though it might be enough to just limit the scope and be explilcit about what's supported by SB. Some scenarios are rare but high effort.

**Comment by DavidXanatos** [comment]
In the next build we will use the DOS drive letter in FilePaths.dat
