### ISSUE TITLE
can you make a function switch to hide your own sandbox processes in the sandbox

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#3054]
### Is your feature request related to a problem or use case?

a switch controls the display or hiding of processes
![屏幕截图 2023-06-23 214941](https://github.com/sandboxie-plus/Sandboxie/assets/89934966/ecdc73e0-b676-4993-9dd4-e43ada4dc2f9)

### Describe the solution you'd like

A switch, or hidden in non debug mode, displayed in debug mode

**Comment by bastik-1001** [comment]
This option can be found in the global settings, under the interface config in the tab user interface.
