### ISSUE TITLE
how to use triggers to create a new folder on box init?

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#3060]
### Describe what you noticed and did

how to use triggers to create a new folder on box init?

### Affected program

no relevant

### Download link

no relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

no relevant

### What is your Windows edition and version?

not relevant

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

no relevant

### What version of Sandboxie are you running?

1.9.7

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by diieg707** [comment]
i just want to create a random folder on C:\ on box init, but i don't know how that trigger feature suppose to work. some help would be appreciated

**Comment by offhub** [comment]
You can do this by defining a script for the trigger.

1. Create a bat file and move it to a permanent location.

    **CreateFolder.bat**:
    `md "C:\test"`

3. Create a On Box Init trigger.

    `AutoExec="X:\ScriptPath\CreateFolder.bat"`

> **Note** If you are using a data-protected sandbox, you must make the script path accessible.
`NormalFilePath=X:\ScriptPath\`

**Comment by isaak654** [comment]
#3059

**Comment by diieg707** [comment]
> You can do this by defining a script for the trigger.
> 
> 1. Create a bat file and move it to a permanent location.
>    **CreateFolder.bat**:
>    `md "C:\test"`
> 2. Create a On Box Init trigger.
>    `AutoExec="X:\ScriptPath\CreateFolder.bat"`
> 
> > Note If you are using a data-protected sandbox, you must make the script path accessible.
> > `NormalFilePath=X:\ScriptPath\`

is it possible to execute a command without the need to create a .bat file? like insert the command directly into sandboxie trigger tab

**Comment by offhub** [comment]
`cmd.exe /c md "C:\test"`

**Comment by offhub** [comment]
Triggers other than `On Box Delete` and `On File Recovery` can only execute commands in the sandbox.

**Comment by diieg707** [comment]
> Triggers other than `On Box Delete` and `On File Recovery` can only execute commands in the sandbox.

that's all i needed though, thank you for your assistance bro ❤️

**Comment by offhub** [comment]
Actually, there is a way, but I wouldn't recommend it.

> **Warning**
<details>
<summary>Programs defined as BreakoutProcess run outside the sandbox and can put your system at risk! The responsibility is yours.</summary>

1. Go to `C:\Windows\System32`
2. Find `cmd.exe`
3. Copy and paste `cmd.exe` to the same or a different location, then rename it to whatever you like. (I'll use cmdUNBOXED.exe as an example.)
> **Warning** 
4. Set `cmdUNBOXED.exe` as `BreakoutProcess`. (Sandbox Options > Program Control > Breakout Programs)
> **Warning** This program will always work outside the sandbox. Do not use it with commands that could damage your system!
5. Other triggers you define using this program will also work outside the sandbox.

</details>

> **Warning**
