### ISSUE TITLE
boxed winrar cannot create new folder inside "defaultbox" folder on root directory

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#3062]
### Describe what you noticed and did

I created a symbolic link folder on desktop using this command:

mklink /D C:\Users\Admin\Desktop\container C:\Sandbox\Admin\DefaultBox\container

source: C:\Sandbox\Admin\DefaultBox\container
symbolic link: C:\Users\Admin\Desktop\container

then opened boxed winrar and clicked "extract to", selected the symbolic link created on desktop, then click new folder, then an error occur:

"The system cannot find the file specified"

unboxed winrar works normally creating the folder inside symbolic link

![2023-06-27 12 08 00](https://github.com/sandboxie-plus/Sandboxie/assets/54504707/7e3bec53-8197-483c-8548-b2040145a9ca)

### Affected program

all boxed programs

### Download link

not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

"The system cannot find the file specified"

### What is your Windows edition and version?

22H2 22621.963

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

ESET

### What version of Sandboxie are you running?

1.9.8

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
Does it work when uploading from source location? (source: C:\Sandbox\Admin\DefaultBox\container)

**Comment by diieg707** [comment]
> Does it work when uploading from source location? (source: C:\Sandbox\Admin\DefaultBox\container)

hi, it doesn't work either, it's because the symbolic link was created inside sandbox root folder

**Comment by diieg707** [comment]
the "DefaultBox" folder has some sort of write protection:

if i put destination path: C:\Sandbox\Admin\ and click new folder it winrar will generate new folders

![2023-06-27 13 45 55](https://github.com/sandboxie-plus/Sandboxie/assets/54504707/d69277b8-b3b7-47e8-a642-2da0c49c9bf0)

but if i set destination path: C:\Sandbox\Admin\DefaultBox and click new folder an error appear
![2023-06-27 13 48 12](https://github.com/sandboxie-plus/Sandboxie/assets/54504707/557b4d19-548f-41cc-a161-7040bb23db7b)

**Comment by diieg707** [comment]
i wanted to make a folder inside "defaultbox" and copy files there through programs like chrome and winrar
