### ISSUE TITLE
Sandboxie - Firefox slowdown and error messages

### ISSUE THREAD

**Issue by CaliSunUSA** [sandboxie-plus/Sandboxie#3065]
### Describe what you noticed and did

Last week I stared to receive sandboxie pop-up error messages (screenshot attached) . I updated sandboxie and Firefox to latest versions but I still keep getting pop-up messages and firefiox runs very slow at that point. After I restart my computer, everything seems to work fine for  while and later messages start again.

System:
Windows 10
Firefox v114.0.2
Sandboxie-Plus v1.9.8

![SandBoxie Error - 2023-06-28](https://github.com/sandboxie-plus/Sandboxie/assets/67880003/6d019cc0-777e-4130-969a-87c905d64aac)

### How often did you encounter it so far?

daily

### Affected program

Firefox

### Download link

N/A

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

no error messages

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Avast and ZoneAlarm Firewall

### What version of Sandboxie are you running?

Sandboxie-Plus v1.9.8

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by CaliSunUSA** [comment]
Besides getting Sandboxie error messages, new Firefox tabs keep crashing while inside Sandboxie. This does not happen when running Firefox outside of Sandboxie

![Sandboxie-Firefox tab error2](https://github.com/sandboxie-plus/Sandboxie/assets/67880003/fd38b1ad-03ab-44ac-b3ed-9e730cf42b9b)

**Comment by Dyras** [comment]
Does it happen on 1.8.4?
https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.8.4
If not, can you update 1 version at a time and see when it starts happening?

**Comment by CaliSunUSA** [comment]
Late response due to vacation.
- I have uninstalled FireFox and re-installed latest version: 115.0.2
- Cleared out content from all Boxes and installed latest version of Sandboxie-plus 1.10.0

Everything seems to work fine, so I went ahead and re-installed all my Firefox plugins. So far everything seems to work fine.
Will report back if error message returns.

**Comment by CaliSunUSA** [comment]
Error message returned.
While trying to open another instance of Firefox within another box (which I have done many times before) I received this message:

![Sandboxie error 07-20-2023](https://github.com/sandboxie-plus/Sandboxie/assets/67880003/7090f079-3ed0-4b26-93d6-004db728fa48)

**Comment by Dyras** [comment]
Check out my last post and we'll go from there in case that doesn't work.
