### ISSUE TITLE
Run Explorer cannot be launched

### ISSUE THREAD

**Issue by bigheadming** [sandboxie-plus/Sandboxie#307]
Version 0.5.3b under Windows 10 Home.

When trying to run Explorer, I can see the task started under SandboxieRpcSs.exe, but Explorer does not show up. Soon, I see then this task disappeared.

**Comment by bigheadming** [comment]
It looks like the explorer cannot be launched when the sandbox configuration is set to  "Hardened" when creating a new sandbox. The explorer in "Default sandbox" can be launched without problem. Here is the content in Edit ini. Please let me know if you need more info. Thanks.

Enabled=y
ConfigLevel=7
AutoRecover=n
BlockNetworkFiles=y
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#ff55aa,off,4
DropAdminRights=y
ProtectRpcSs=y
BoxNameTitle=y
BlockNetParam=y
CopyLimitKb=81920
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n

**Comment by DavidXanatos** [comment]
the problem was ProtectRpcSs=y as this is now deprecated and removed the issue should be gone
