### ISSUE TITLE
something wrong with explorer.exe in the data protection sandbox

### ISSUE THREAD

**Issue by 0warning0error** [sandboxie-plus/Sandboxie#3077]
### Describe what you noticed and did

1. run program, input explorer.exe /e,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}, and click to run
2. open a file in explorer
3. it crashed and shows sbie2112 error

### How often did you encounter it so far?

Every time I open a file in explorer

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

The explorer shouldn't crash

### What is your Windows edition and version?

Windows 11 22H2 (22621.848)

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

no

### What version of Sandboxie are you running?

sandboxie plus 1.9.2 64bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

since 1.9.2

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Crash dump

https://stuecnueducn-my.sharepoint.com/:f:/g/personal/51215902159_stu_ecnu_edu_cn/EmB0OIg3CUBEpYFc4ynM6uIBH5TkhgSRi6xjbA6rPOwpjA?e=cOng4c

### Trace log

https://www.jianguoyun.com/p/DTZyPUkQ7NvhCxi19o8FIAA

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
DefaultBox=DefaultBox
FileRootPath=\??\f:\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%

[UserSettings_0596015C]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
BoxGrouping=:DefaultBox,guochanruanjian

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#f88501,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
BoxNameTitle=n
CopyLimitKb=81920
UsePrivacyMode=y

[guochanruanjian]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#0423ee,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseSecurityMode=y
UsePrivacyMode=y
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
BoxNameTitle=-
CopyLimitKb=81920
```

**Comment by offhub** [comment]
According to crash reports, the crashes seem to be caused by `nppShell.dll`.

You can see if the following solution also applies to `nppShell.dll` (You can see if the following solution also applies to nppShell.dll. Follow the same steps, adapting them for "C:\Program Files\Notepad++\contextMenu\nppShell.dll").

https://github.com/sandboxie-plus/Sandboxie/issues/2011#issuecomment-1616423805

> **Workaround**: Right click the `nppShell.dll` -> click Property -> click tab Security -> click button Advanced. Find the unknown user with shorter SID -> click Disable Inheritance -> click Delete. Restart your sandboxie and now it should be able to run the browser without error.

**Comment by 0warning0error** [comment]
I seem to understand where is the problem. NPP registered the right-click menu and this may cause crash. Explorer.exe doesn't crash after I uninstall npp.
