### ISSUE TITLE
sandboxie-plus.com slow to respond

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#308]
https://sandboxie-plus.com takes between 1.4 and 4 seconds to load, including when simply refreshing the page (Chrome <F5>).

Surprising, as you seem to host this via CloudFlare and my ping time to the resolved edge server is only 7ms.

This is mainly an FYI, not a major issue, so feel free to close and ignore.

**Comment by DavidXanatos** [comment]
seams to be fin now may be CF had issues
