### ISSUE TITLE
Couldn't run Aliyun Drive in sandboxie

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#3089]
### Describe what you noticed and did

1. Install Aliyun Drive in real system
2. Run it in Sandboxie
3. 
![1](https://github.com/sandboxie-plus/Sandboxie/assets/56181919/33431df6-f737-407c-8cf1-232100c11ef4)
(Translateion: Sorry, Aliyun Drive have an unhandled exception. )

### Affected program

Aliyun Drive

### Download link

https://cdn.aliyundrive.net/downloads/apps/desktop/aDrive.exe

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

This bug shouldn't appear. 

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2021 x64 (21H2)

### In which Windows account you have this problem?

An account with UAC protection set to Always notify.

### Please mention any installed security software

ESET Internet Security 16.1.14.0

### What version of Sandboxie are you running?

Sandboxie 5.64.8/Sandboxie-Plus 1.9.8

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by zhongerjunze** [comment]
不管是安装在沙盒内还是沙盒外，都需要在快捷方式后加上` --no-sandbox`才能启动。
如果想在沙盒外面启动，需要在沙盒内创建一个包含上述启动项的快捷方式，再将外部的快捷方式链接到内部的快捷方式。
————
Whether it is installed inside or outside the sandbox, you need to add '--no-sandbox' to the end of the shortcut to start.
If you want to launch outside of the sandbox, you need to create a shortcut inside the sandbox that contains the above launches, and then link the external shortcut to the internal shortcut.
--Translated By Microsoft

**Comment by offhub** [comment]
Try this setting:

```ini
SpecialImage=chrome,aDrive.exe
```

**Comment by 0x391F** [comment]
> Try this setting:
> 
> ```ini
> SpecialImage=chrome,aDrive.exe
> ```

It works. How this setting works?

**Comment by offhub** [comment]
https://github.com/sandboxie-plus/Sandboxie/blob/62fe001a77a8d1d89e63319a85394b90ec6ce090/CHANGELOG.md?plain=1#L3347-L3348
