### ISSUE TITLE
Documentation not Open Source?

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#309]
Is documentation intentionally not open source (eg, on github instead of sandboxie-plus.com), or am I missing a repo?

If it's not, it would be great to have documentation be publicly editable. It would be good to treat documentation in the same way as source code. One can't really exist without the other. It would also allow me and others to add to/modify it.

**Comment by DavidXanatos** [comment]
There is a website dump of the original sandboxie website, see #31
it can be accessed via: https://sandboxie-website-archive.github.io/www.sandboxie.com/AllPages.html

**Comment by isaak654** [comment]
There is already a repo, just not much advertised:
https://github.com/Sandboxie-Website-Archive/sandboxie-website-archive.github.io

**Comment by typpos** [comment]
Thanks, I know of this repo as well as other bits and pieces. However..

That repo is an archive/dump of the old website. It's not being updated and even has "archive" in it's name. It's also not easily maintainable because it's raw html.

Random example 1: release 0.5.3 has a new feature, "added "ClsidTrace=*" option to trace COM usage". Where is this documented? If it's not documented and I have time to contribute, where should that go?

Random example 2: Issue #299 asks about docu for config. Partially answered in #299, but no documentation or link added to readme at top of source or some kind of single-point-get-started information index. The next person wondering about the same question will have to search for it or ask again.

So, I'm basically suggesting..
* A single and obvious documentation starting point, for example, the readme at the top of this repo
* An easily maintainable documentation system (not raw html as in sandboxie-website-archive)
* Open source (not sandboxie-plus.com, unless that content is held in a repo and mirrored across)
* Progressive move towards documentation in a single location. Removal of legacy reference sites after merging across information

**Comment by DavidXanatos** [comment]
Well I ported the HTML documentation to markup using a tool and doing some manual clean up and put it into my word press on (sandboxie-plus.com) using a markup plugin. So its maintainable and up datable.

Now github understands markup so we could probably somehow get the documentation into the repo.
But I'm to lazy for that and its almost 300 pages. 

In my experience documentation on github is only for advanced users, for the masses a website is much better.

**Comment by typpos** [comment]
> Well I ported the HTML documentation to markup

Can I get a copy of those markdown files to try a few things?

What is the legal situation with the original documentation? The dump of the sandboxie site states "Copyright Sandboxie Holdings. All rights reserved" and the "open sourcing" statement explicitly refers to source code only and talks about shutting down the website and forum. Did anyone get permission to use/mod it?

**Comment by DavidXanatos** [comment]
>
> Can I get a copy of those markdown files to try a few things?

I have it only in word press, but if you want to spend a few hours copy and pasting 300 pages I guess I can create you an account with read access to the page editor.
Or I can send you an exported XML of my word press DB but the export plugin only takes the html representation. So that would be cleanuped and trivial to convert to MD fully automatically.

Its a bit a mess, I have updated to a multi side wordpress and now in the new instance its all html but the MD plugin converts it to MD with one button click. I should see where in the old DB it stored the MD representation and just export these...

> 
> What is the legal situation with the original documentation?

Unclear!

I got the following statement some months ago from one of the company guys in their forum:

> 
> First of all, thank you for giving feedback on the open source code so quickly. I wasn't expecting anyone to be so quick with it.
> 
> Second, I can't officially announce that people can leech the website for historical purposes, but one of the reasons I recently posted the old-forums was for this purpose. Sophos doesn't care about the copyright of that content and would rather give it to the community.
> 

So I would not out it into the Sbie+ repository if anything than in a separate one in case it gets nuked.

**Comment by quangkieu** [comment]
I would suggest that if we have it in some GitHub repo, we could have some GH action to auto pushed new pull request into document repo for new config ini setting and its summary from your release note or some code file. Sorry I did not browse the c code yet.
So that if someone have time could expand that page for more detail or its function related to other config.

**Comment by DavidXanatos** [comment]
Voila: https://github.com/DavidXanatos/sandboxie-docs

I exported the original hand optimized MD from my old DB to individual *.md files with a quickly bodged up tool and created a new repo.
Not that all the links are broken as WP wanted only he page name while github wants it to end with .md I have only fixed [AllPages.md](https://github.com/DavidXanatos/sandboxie-docs/blob/main/Content/AllPages.md) with quick find and replace ```)``` => ```.md)```

**Comment by typpos** [comment]
> Voila: https://github.com/DavidXanatos/sandboxie-docs

Great. I'll have a look.

> > legal situation
> Unclear!

Bit of a bummer! Putting work into updating the docs to latest features creates derivative work and is then at risk, although likely near zero risk. (I'm mainly interested in creating a clean structured document for new features, not just trying to copy across the old reference.)

**Comment by typpos** [comment]
Enabled github.io:    https://typpos.github.io/sandboxie-docs/

Will have a look at this when I get time.

**Comment by DavidXanatos** [comment]
ah that cool, did the same: https://davidxanatos.github.io/sandboxie-docs/
also I have updated my tool to fix the images and link on the fly and committed a new version of the files that should work in github out of the box.
although the images seam to work only on gitbug but not on github pages. not wure whats the correct format to make it work on booth :/

**Comment by typpos** [comment]
I created a pull request with some basic documentation updates.


A few topics arose:

#### Legal status of classic sandboxie

It is a problem that there is no explicit formal approval to use the legacy help texts and imagery. As new Sandoxie(-plus) features get documented, text will merge with classic docs and if it's ever nuked, it's all gone. We could leave classic docs in separate repo and don't attempt to update and merge as feature progress, but that's not a nice solution for feature enhancements. To get formal approval would really help.

#### Donating

I wrote the landing page to invite users and to encourage contributions and donations. Not sure how to deal with the "donate" bit. On the one hand it's open source and various people contribute, on the other hand, Xanatos.com incurs expenses for EV cert (?) etc. This may get confusing down the road if you canvas donations but also have several people contribute. I'm not fussed, but it should be resolved on the documentation pages so (new) people know who/what they are donating for. Feel free to ignore me.

#### Legal - General

The landing page and other pages in the repo and on sandboxie-plus.com make undertakings about PC safety when using sandboxie. I am not a lawyer but had some "interesting" far-out experiences in my other life. Might be good  to put some legal qualifier somewhere and/or ensure that the license agreement on install covers this. Sub-plot: License is not viewed with a silent install. Again, feel free to ignore me.


#### Sandboxie vs Sandboxie-Plus

For long-term users and followers of this repo all is good. For new users the current documentation will be impenetrable and there needs to be some hand-holding about choosing classic vs plus, and where to get help for plus. Maybe call the old sandboxie installer SandboxieClassic....exe. Feel free to ignore me.

**Comment by DavidXanatos** [comment]
@typpos 
I created a slack channel for sandboxie-plus, if you send me an email address than I can send you an invite.
That would be more convenient for communication.

**Comment by isaak654** [comment]
UPDATE:
Documentation has been moved to: https://github.com/sandboxie-plus/sandboxie-docs
