### ISSUE TITLE
Sandboxie Website Archive

### ISSUE THREAD

**Issue by DavidBerdik** [sandboxie-plus/Sandboxie#31]
Since the original Sandboxie website is closing and it contains lots of useful information, I have made a copy of the website and made it available at http://sandboxie-website-archive.github.io/. This archive includes the old Sandboxie forums.

**Comment by DavidXanatos** [comment]
Very cool thank you very much :-)

**Comment by DavidBerdik** [comment]
You're welcome! By the way, the archive is also available as a GitHub repo at https://github.com/Sandboxie-Website-Archive/sandboxie-website-archive.github.io.

**Comment by rugabunda** [comment]
> 
> 
> You're welcome! By the way, the archive is also available as a GitHub repo at https://github.com/Sandboxie-Website-Archive/sandboxie-website-archive.github.io.

david can you pull this up for me somehow? https://forums.sandboxie.com/phpBB3/viewtopic.php?f=11&t=26535&p=136064#p136064

**Comment by DavidBerdik** [comment]
> david can you pull this up for me somehow? https://forums.sandboxie.com/phpBB3/viewtopic.php?f=11&t=26535&p=136064#p136064
> 
> topic regarding driver verifier

Is this the one you are talking about?

https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic750b750b.html?f=11&t=25636&p=132997#p132997

**Comment by GH01** [comment]
Thank you for the archive.

But how to search (or filter with a user name) in the old forums?

**Comment by DavidBerdik** [comment]
@GH01 You're welcome! Unfortunately, the search functionality in the forum archive is not functional, but you might be able to find what you're looking for by using the GitHub repository search tool.

**Comment by me-20201219** [comment]
I am using Windows 8.1 x64 and I have the same Problem:
SBIE2224 Sandboxed program has crashed: ffmpeg.exe [JDownloader]

**Comment by DavidXanatos** [comment]
I have ported the relevant support pages over to my website https://xanasoft.com/sandboxie/allpages/ that copy will be kept up to date and contain information about new functions.

**Comment by DavidBerdik** [comment]
Great! For archival purposes though, I am going to continue to hosting the archive on GitHub.

**Comment by DavidXanatos** [comment]
> 
> 
> Great! For archival purposes though, I am going to continue to hosting the archive on GitHub.

Yes definitely! 
Also you have the old forum that one is valuable to and should stay available, I'm not going to mirror that.
