### ISSUE TITLE
Can't open Typora

### ISSUE THREAD

**Issue by silvestron** [sandboxie-plus/Sandboxie#310]
The same issue reported in #215 is still present in v5.45.2 even though it is labeled as fixed in the next built.

**Comment by DavidXanatos** [comment]
When I was testing it I could install and open Typora in a sandbox on windows 20H2
please post your sandboxie ini and a log from the resource monitor using the latest build
Also please try if it makes a difference where Typora is installed in our out side the box.

**Comment by silvestron** [comment]
Typora is installed inside its own sandbox but I just tried to launch VS Code which is installed outside the sandbox and it has the same issue. Still, not all electron apps seem to have the problem. I was able to successfully launch [Mark Text](https://github.com/marktext/marktext), which is another app similar to Typora in terms of functionality.

However I'm running Windows 10 1909, I haven't upgraded to 20H2 yet.

Here's my sandvoxie.ini, I've edited out the settings of the other sandboxes:

```
[GlobalSettings]

ActivationPrompt=n
AutoRecover=n
BlockNetworkFiles=y
BorderColor=#00FFFF,off
BoxNameTitle=y
ClosedFilePath=C:\Program*\brave.exe
ClosedFilePath=C:\Program*\chrome.exe
ClosedFilePath=C:\Program*\firefox.exe
ClosedFilePath=C:\Program*\iexplore.exe
FileRootPath=C:\Sandboxie\%SANDBOX%
NotifyInternetAccessDenied=y
NotifyStartRunAccessDenied=y
Template=Windows10CoreUI
Template=FireFix_for_Win7
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=7zipShellEx
Template=AutoRecoverIgnore
Template=BlockPorts
Template=LingerPrograms
Template=WindowsDefender

[Notes]

Enabled=y
ConfigLevel=7
CopyLimitKb=100000
DropAdminRights=y
NeverDelete=y
```

Here's the [resource monitor log](https://gist.github.com/silvestron/ec7eef8efca80c006cb8a46d7cecc752). By the way, as soon as I clicked on *copy content to clipboard and close window* I got a SBIE2301 message, and the message had no actual text, just the code.

**Comment by MarcelFine** [comment]
Starting VS Code with "code.exe --disable-gpu" solved the issue for me.

**Comment by silvestron** [comment]
I just tested it and can confirm that worked with Typora too.

Regarding the issue itself, I upgraded to Windows 20H2 and the problem is still persistent. The bug has been introduced in version 5.45.0 (if not earlier, I might have missed some updates) because this problem wasn't present before.

**Comment by DavidXanatos** [comment]
could you please test with which build the issue was introduced exactly

**Comment by silvestron** [comment]
I tested a bunch of builds, these are the results:

- 5.43.5 works
- 5.43.6 works
- 5.43.7 works
- 5.44.0 works
- 5.44.1 doesn't work

**Comment by DavidXanatos** [comment]
I don't get it why it does not fail for me, could you try the plus UI and send me the resource access log from there, there its mroe verbose also send the message log in case there were any.

Also can you zip and upload the exact typora instalation you have someware
I tested with version 0.9.98.0

**Comment by silvestron** [comment]
I am using version 0.9.96, however I just tried 0.9.98 in a new sandbox and it has the same issue.

I was thinking, since disabling GPU acceleration seems to circumvent the problem, could the the issue be related to hardware or graphics drivers? I am using Intel integrated graphics, according to [Intel ARK](https://ark.intel.com/content/www/us/en/ark/products/97453/intel-pentium-processor-g4600-3m-cache-3-60-ghz.html), Intel HD Graphics 630.

**Comment by DavidXanatos** [comment]
> 
> 
> I was thinking, since disabling GPU acceleration seems to circumvent the problem, could the the issue be related to hardware or graphics drivers? I am using Intel integrated graphics, according to [Intel ARK](https://ark.intel.com/content/www/us/en/ark/products/97453/intel-pentium-processor-g4600-3m-cache-3-60-ghz.html), Intel HD Graphics 630.

Possibly... I ever only tested it in a VM which may not have all the fancy acceleration features a real system has, I'll test it on my host machine lets see if that changes anything.

**Comment by DavidXanatos** [comment]
could you pelase try the workaround in https://github.com/sandboxie-plus/Sandboxie/issues/440
does it help here to?

**Comment by silvestron** [comment]
I tried it and with hardware acceleration enabled the transparent/empty window issue is still there. However when I tried Typora with hardware acceleration disabled I saw some improvements. Launching the app was very fast. Without `OpenWinClass=#` the app used to be a little slow, either at launch or during use.
