### ISSUE TITLE
Separate protection against box removal and content deletion

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3104]
### Is your feature request related to a problem or use case?

Right now, there is the option to "protect this sandbox from deletion or emptying", which avoids the sandbox and its contents being removed via the user interface. This is fine if both are desired.

The use case for having the two being separate is, when the box (its settings) are important (or desired to be preserved), while the content isn't important.

One of my use cases is that the program is installed normally, just run with Sandboxie, in the box I created for it. In most of these instances, the files that are produced, downloaded or created are either recovered or have no importance to me.

### Describe the solution you'd like

Being able to prevent a box from being removed by accident, while the files can be removed with Sandman.

### Describe alternatives you've considered

Creating a backup of the Sandboxie.ini, so a box could be restored from there.

**Comment by DavidXanatos** [comment]
I coudl turn the current check box into a combo box, or use a 3 stare checkbox?

**Comment by bastik-1001** [comment]
I am not a UI expert. :)

I am also not sure if a combo box covers all use-cases, but I can't think about all of them. Mine would be covered by the combo box.

**Comment by RandomGOTI** [comment]
could keep the neverdelete=y as it is and expand by adding two more suboptions to allow either content deletion or removing the box
something like allowboxremove and allowdeletecontent 🤷‍♂️ 
 users then can use the box context menu in sandman to do these actions bypassing the protection
 (if it's only neverdelete=y the behaviour is unchanged)

**Comment by bastik-1001** [comment]
As a side effect of partially toggling "Protect this sandbox from deletion or emptying", "Auto delete content when the last sandboxed process terminates" gets grayed out in the UI. I guess that some people like to auto delete the content, while wanting to make sure the sandbox itself (all its settings) remains present.
