### ISSUE TITLE
existing BoxNameTitle=process.exe,- removed when toggling other options

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#3106]
### Describe what you noticed and did

Case 1 
title ; when default BoxNameTitle=n does not exist in the ini when toggling neverdelete for example
turning neverdelete off will replace it with BoxNameTitle=n
Case 2
Changing BoxNameTitle will remove the per process options (removes exceptions to the global rule)

### How often did you encounter it so far?

everytime

### Affected program

sandman

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

case 1 bug
case 2 the user should decide if to keep or remove those options

### What is your Windows edition and version?

7 ultimate sp1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

1.10.0 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by bastik-1001** [comment]
I can reproduce case 1.

I can recreate case 2, when I set the box name to be shown for certain processes, then changing BoxNameTitle with the UI to be shown or not shown, the entry becomes BoxNameTitle=y or BoxNameTitle=n, without it applying per process basis. The user might not do that intentionally, so there is a point in making the user aware that they are discarding per process options for this setting.
