### ISSUE TITLE
'Download signature is not valid' error when attempting to install Script Debugger addon

### ISSUE THREAD

**Issue by TFWol** [sandboxie-plus/Sandboxie#3107]
### Describe what you noticed and did

1. Highlight **Script Debugger** in Optional Addons
2. Click **Install**

Error:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/9045213/a4ec0dd0-26dd-47c8-8f40-6dbcfc9c67f7)

### How often did you encounter it so far?

Every time

### Affected program

N/A

### Download link

N/A

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Addon should install

### What is your Windows edition and version?

Windows 10 Pro 21H2 64bit

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator).

### Please mention any installed security software

None

### What version of Sandboxie are you running?

1.10.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
fixed try again

**Comment by TFWol** [comment]
Thanks, that worked!
