### ISSUE TITLE
Exclude specific boxes processes from 'Terminate all processes'

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#3108]
### Is your feature request related to a problem or use case?

Sandboxed program that is preferably kept running , while still be able terminate all other boxes processes if needed.

### Describe the solution you'd like

a protected box list in ini global section to exclude them from terminate all processes (_not terminate all programs box context menu_)

**Comment by DavidXanatos** [comment]
I was thinking about something like this already, although different  in as far as I thought to add a checkbox per sandbox to exclude particular sandboxes from termination.
Would this satisfy your request?

**Comment by bastik-1001** [comment]
I see the value in this. It just needs to be clear to the user that when they terminate ALL processes, it does not apply to those that have been added as exception. I am considering cases where the one setting it up is different from the one that uses it in the end.

**Comment by DavidXanatos** [comment]
This will be added in the next build.
Press the panic button hot key 3 times with less then 1 second between clicks to terminate all with NO exceptions

Question: Do we need a global menu option to terminate all with no exceptions?
Keep in mind that selecting all boxes and using the context menu will also terminate all with no exceptions
