### ISSUE TITLE
CreateMutex, GetLastError error ( Ipc_GetName )

### ISSUE THREAD

**Issue by vmtest888** [sandboxie-plus/Sandboxie#3112]
### Describe what you noticed and did

c++ source

```
HANDLE h = CreateMutex(NULL, NULL, L"55555");
printf("%p %p\n", h, GetLastError());

HANDLE h1 = CreateMutex(NULL, NULL, L"Global\\55555");
printf("%p %p\n", h1, GetLastError());

system("pause");
```

### Affected program

text.exe

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

outside the sandbox

```
0000000000000098 0000000000000000
000000000000009C 0000000000000000
```

inside the sandbox
```
0000000000000210 0000000000000000
0000000000000208 00000000000000B7
```

GetLastError() is ERROR_ALREADY_EXISTS

### What is your Windows edition and version?

windows 10

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

no

### What version of Sandboxie are you running?

v1.0.11 / 5.55.11

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
indeed, the symlink got Global is wrong will be fixed in the next build

**Comment by vmtest888** [comment]
![image](https://github.com/sandboxie-plus/Sandboxie/assets/26427035/e922929a-9c40-4ed6-85d6-8a68132238c8)

5.56.1 still returns ERROR_ALREADY_EXISTS

**Comment by DavidXanatos** [comment]
that is strange for me it works fine, 
![image](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/6eab8ef5-3d21-47bf-bf63-ffd74003c946)

**Comment by vmtest888** [comment]
![image](https://github.com/sandboxie-plus/Sandboxie/assets/26427035/b9b8a34a-b3b6-4705-aa03-a5423944dcec)

···
[DefaultBox]
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
Enabled=y
```

The ini configuration file is the default, my system is win10, sure strange

**Comment by vmtest888** [comment]
![image](https://github.com/sandboxie-plus/Sandboxie/assets/26427035/3e7bc999-3c50-4eaa-8f30-f5276eb1b3f2)

Restarting the computer will work. It may be that the matching link already exists. Close question.
