### ISSUE TITLE
'Addon already installed!' error when clicking 'Show Stack Trace'

### ISSUE THREAD

**Issue by TFWol** [sandboxie-plus/Sandboxie#3114]
### Describe what you noticed and did

1. Enable Trace Logging
2. Run a program
3. In Trace Log window click Show Stack Trace
4. Dialog box pops up `To use the stack traces feature the DbgHelp.dll and SymSrv.dll are required, do you want to download and install them?` 
![image](https://github.com/sandboxie-plus/Sandboxie/assets/9045213/242258e8-cd6c-4ab2-8442-5f41f6500a1f)
5. Click **Yes** (**No** just cancels)
6. Error `Addon already installed!` displays
![image](https://github.com/sandboxie-plus/Sandboxie/assets/9045213/db019bf5-554a-4449-b37e-086148691334)
7. Repeating Steps 3 onward has same result every time.

### Affected program

N/A

### Download link

N/A

### Where is the program located?

Not relevant to my request.

### Expected behavior

Trace to appear or something; I don't know what the new feature is supposed to show me.

### What is your Windows edition and version?

Windows 10 Pro 21H2 64bit

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator)., An account with UAC protection completely turned off.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

1.10.0 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
crimidy... not cool if the right vc redist is nto installed the load of the dlls fails and then we are running in a circle.
i can eider add a lot of additional dll's or redo this addon to install the full debugger toolset from MSFT,
i think to be on the safe side that it always works for everyone I'll go with the later and install the full package.

**Comment by offhub** [comment]
I have the same problem even though I have 'Debugger and Tools' installed on my system.

**Comment by DavidXanatos** [comment]
you are right the default remote debugger tools don't bring all required dll's

**Comment by TFWol** [comment]
Confirmed fix working.

![image](https://github.com/sandboxie-plus/Sandboxie/assets/9045213/de7ae07a-8eab-4ebc-8cce-2d8791d8ab80)
