### ISSUE TITLE
allow setting default text editor

### ISSUE THREAD

**Issue by fusionneur** [sandboxie-plus/Sandboxie#3116]
### Is your feature request related to a problem or use case?

on win 11, trying any of 'options' > edit sandboxie/templates/sandboxie-plus ini file, results in notepad not opening even if the UWP app is properly installed and able to run.

### Describe the solution you'd like

being able to set my default text/configuration editor. eg. vscodium or notepad++

**Comment by offhub** [comment]
You can already do this. See [here.](https://github.com/sandboxie-plus/Sandboxie/issues/1475#issuecomment-1007330627)

**Comment by DavidXanatos** [comment]
![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/cd7080ce-d218-4b70-8f79-4f9fdf3d249c)
