### ISSUE TITLE
Sandboxie-Plus driver fails to load with error "Failed to connect to the driver" in Windows 10 pro 64-bit

### ISSUE THREAD

**Issue by dipu500** [sandboxie-plus/Sandboxie#3117]
After open the Sandboxie-Plus show the error message "Failed to connect to the driver". When I click start driver in the maintenance option of the Sandboxie-Plus following error message is appear "ControlService Start: A device attached to the system is not functioning.(31)"
I take screenshots of all error message in the event viewer. And also attach a screenshot of system information of computer. If any other information needed please tell me.

![sandboxie](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/86aff5fb-1f77-432f-8107-28fb3cbc8808)
![sand1](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/4b7b97a3-b0de-452c-831b-ba8167a22528)
![sand2](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/ed712671-17de-48db-98a2-c030e95b37ec)
![sand3](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/ba3c8f09-bcbe-400e-b88c-6a68beeb4564)
![sand4](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/a519231b-926f-47f3-b569-753b1438aec9)
![sand5](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/043aaa7e-f885-45c8-8cac-5f2d87d5ac7e)
![sand6](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/f8e8ac94-5f8a-4915-ba01-2736c277f497)
![sand7](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/bb9cc04e-b763-4414-b392-34faecbd0e1c)
![system info](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/641ed96e-f95b-4f59-bfc4-b0cb70e10360)

### How often did you encounter it so far?

Whenever I open the app

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Sandboxie Driver load

### What is your Windows edition and version?

Windows 10 Pro(64-bit) 10.0.10586 Build 10586 

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Windows defender

### What version of Sandboxie are you running?

Sandboxie-Plus v1.9.8

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

This computer setup with CR system provided by fuji company. So I don't know if they changed any security policy or not. But I can surely 
tell you that they changed update policy as I can not update the os through windows update and also firewall was off from begining as CR application conflict with firewall.

**Comment by bastik-1001** [comment]
Have you tried to uninstall Sandboxie and try with a fresh install? Make sure to create a back-up of your Sandboxie.ini, to be able to restore that.

I don't think I know what CR means in this context.

Do you have control over the system, or are you restricted by something? Since you mention that Windows updates are not available.

**Comment by DavidXanatos** [comment]
The problem is the WIN32U dll not being loaded by sbiedrv, ```/ 12``` indicates that the failure happened directly when trying to open the file WIN32U.dll was introduced in windows 10 14393 but the user is using an extremely old 10586 build in which the dll is not present.

I'll add a fix to the driver for that but given that "Windows 10 Pro(64-bit) 10.0.10586 Build 10586" is no longer supported and does not receive any security fixes i would strongly recommend to update the windows installation.

**Comment by DavidXanatos** [comment]
You can use EnableWin32kHooks=n in the global settings section of your sandboxie ini to disable the incompatible feature in the current and older sbie builds.

**Comment by dipu500** [comment]
> The problem is the WIN32U dll not being loaded by sbiedrv, `/ 12` indicates that the failure happened directly when trying to open the file WIN32U.dll was introduced in windows 10 14393 but the user is using an extremely old 10586 build in which the dll is not present.
> 
> I'll add a fix to the driver for that but given that "Windows 10 Pro(64-bit) 10.0.10586 Build 10586" is no longer supported and does not receive any security fixes i would strongly recommend to update the windows installation.

I can't update windows installation through windows update. May be It's company policy to disable windows update for some reason. So please fix the driver for my windows version if it is technically possible. Thanks for   your commitment to fix this problem.

**Comment by dipu500** [comment]
I can not find global settings section of sandboxie ini. Where I should write it?
![sandboxie 2](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/351a9ce4-57ee-45e1-9af1-c959b63b9ea6)

**Comment by dipu500** [comment]
> You can use EnableWin32kHooks=n in the global settings section of your sandboxie ini to disable the incompatible feature in the current and older sbie builds.
I can not find global settings section of sandboxie ini. Where I should write it?

![image](https://github.com/sandboxie-plus/Sandboxie/assets/140065831/158f30c9-c023-40a0-97e6-57a197113207)

**Comment by offhub** [comment]
`C:\Windows\Sandboxie.ini`

If the `Sandboxie.ini` file does not exist, create one with the same name, add the following lines and save it.

```

[GlobalSettings]
EnableWin32kHooks=n


```

**Comment by dipu500** [comment]
> 



> `C:\Windows\Sandboxie.ini`
> 
> If the `Sandboxie.ini` file does not exist, create one with the same name, add the following lines and save it.
> 
> ```
> 
> [GlobalSettings]
> EnableWin32kHooks=n
> ```

I created "Sandboxie.ini" text file in the path "C:\Windows"  and added  above mentioned line and saved it but same error message is appearing when I open Sandboxie-Plus.

**Comment by DavidXanatos** [comment]
1.10.1 should fix your issue
