### ISSUE TITLE
change the time of program 

### ISSUE THREAD

**Issue by jackcore21** [sandboxie-plus/Sandboxie#3119]
### Is your feature request related to a problem or use case?

NO

### Describe the solution you'd like

no

### Describe alternatives you've considered

no

**Comment by jackcore21** [comment]
Hello, I would like to inquire if your program has the capability to adjust the time for a specific program. I previously attempted to use the tool "RunAsDate" but it was ineffective in changing the real time. In order for the program to work, I had to change the operation time of my Windows 10. Could you please let me know if your program can make a real-time adjustment for a specific program?

**Comment by bastik-1001** [comment]
(Time what is time)

I am curious if the use-case is about the time of the day, like needing some program to think it's 12:00 (or something like that), or if a program is supposed to be made think it would be a certain date, like the 1st of July 2023.

**Comment by DavidXanatos** [comment]
this is currently not supported

**Comment by bastik-1001** [comment]
While this is not currently supported, is it something that you think is feasible? I mean, you did not close it, right away, as something that is outside the scope of the project. That still might be the case.

**Comment by coltsfootrock** [comment]
A lot of folk used to use this runasdate to spoof trial period checks on software etc.
Wonder how some security software would react to Sbie engineering dates.
Not something that I personally think should have any priority.

**Comment by DavidXanatos** [comment]
oh thats brilliant, so no need for me to add it?
just use this tool in sandboxie an done

**Comment by bastik-1001** [comment]
It might be a language issue, but the request mentions the time, so I am still not sure if the request is about the time of the day. There might be programs that use dark-mode only after a certain time of the day or something else is tied to the time. It might be better to ask the software developer for an option.

The only software I know, where this applies, is a game, namely Animal Crossing, where the time in the game is the actual time. I have not played that, but I believe not only night and day, but that also certain events were bound to the time.

One might be better off with a VM, where you should be able to set time and date, or another location with a different timezone. Something trying to prevent that, can still request the time and other information when it has access to the internet.

However, the tool runasdate should be able to provide a way to set time and date. I have not tested it.

Given that Sandboxie Plus has an addon manager (upcoming releases will have it), a tool for spoofing the time and date, could be provided via that manager, like runasdate.

**Comment by wutaijieing** [comment]
🙂
bat:

date 2023/07/01
"C:\Program Files\Sandboxie-Plus\SandMan.exe" /box:01 /terminate
ping -n 1 127.0.0.1>nul
"C:\Program Files\Sandboxie-Plus\SandMan.exe" /box:01 delete_sandbox
ping -n 1 127.0.0.1>nul
"C:\Program Files\Sandboxie-Plus\SandMan.exe" /box:01 D:\8899\se\AndroidUtility.exe
ping -n 5 127.0.0.1>nul
w32tm /config /manualpeerlist:"time.nist.gov" /syncfromflags:manual /reliable:yes /update
w32tm /resync
w32tm /resync
w32tm /config /manualpeerlist:"time.windows.com" /syncfromflags:manual /reliable:yes /update
w32tm /resync
w32tm /resync


Terminate and delete_ Sandbox is optional

**Comment by ccchan234** [comment]
there are only 2 threads on this topic, the other not used is here:https://github.com/sandboxie-plus/Sandboxie/issues/3179

i just wanna say, today i test run RunAsDate inside sandboxie plus, it worked.
so if author of sandboxie hesitate to add this function, which is reasonable, at this moment
we other used could try this way.

tools are tools, one use it to defend his/her/their digital rights or use it to steal is all about the personnel involved.

**Comment by unoukujou** [comment]
> oh thats brilliant, so no need for me to add it? just use this tool in sandboxie an done

Please reconsider.

RunAsDate tool is very "basic" and fails to do its job in my own testing. 50% chance that it works, or it doesn't.

Some apps still get the system time.

Some apps load other exe/DLL and grab info from those processes. RunAsDate does not protect child processes. And even the main process 50% of the time still has a way to read the system date even under RunAsDate.

It's still possible for me to achieve what I need to do by a scrpit that changes my system date. So whether you add this or not, it's not gonna stop a person who's determined to do something from doing it.

But it would sure be a lot better if I can have a specific date set in a sandbox and make sure everything that runs in that sandbox can only see the date which I specify.

In a legitimate use case, there are certain malware that act normally to gain a users trust, but only act maliciously on a very specific certain date. Christmas, New Year, or some other random date. Would be nice to be able to easily test untrusted apps to find behavior differences based on a date. Anyway... A useful feature regardless. Maybe it can be an optional add-on in the add-on manager or something like that.
