### ISSUE TITLE
Steam Accoun Manager not started

### ISSUE THREAD

**Issue by mrwhaler** [sandboxie-plus/Sandboxie#312]
SAM (Open Sourse) has a startup function in the sandbox. But I can’t run it. The first time was only a Werfault error. Enabled bug logging in services. Since then more bugs have appeared on startup. I’m installing a log.

> WerFault.exe (4184)   17:14:47.091        WinClass   Progman      X
___         
> WerFault.exe (1572)   17:18:31.428        WinClass   Progman      X          
> WerFault.exe (5648)   17:18:31.977        Ipc        $:SAM.exe    X          
> WerFault.exe (5648)   17:18:31.977        WinClass   Progman      X          
> WerFault.exe (5648)   17:18:32.308        Ipc        $:SAM.exe    X          
___
SAM.exe (5152): SBIE2224 Sandboxed program has crashed: SAM.exe [DefaultBox]
WerFault.exe (5704): SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (5704): SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1

**Comment by DavidXanatos** [comment]
Great being open source makes things easier, usually...
will check it out soon

**Comment by NewKidOnTheBlock** [comment]
This has been two years (sic!) ago. Is it still broken?
