### ISSUE TITLE
GOG (Good Old Games) offline game installer crashes at launch

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#3132]
### Describe what you noticed and did

1, Launch any GOG installer
2. Get an error message
![4hNQVcKuHgwRf3CF](https://github.com/sandboxie-plus/Sandboxie/assets/93145383/140f755a-0271-4a46-94ea-3033611977fa)

I have been able to reproduce it with 3 different GOG games/installers. Test with both Standard and Application Compartment box.
I would like to ask other users to share their experience in this regard.

### How often did you encounter it so far?

Always

### Affected program

GOG installer 

### Download link

Login required: `https://www.gog.com/downloads/hrot_demo/en1installer0`

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Launch the installer properly.

### What is your Windows edition and version?

Windows 7 x64 SP1

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

Microsoft Security Essentials

### What version of Sandboxie are you running?

1.10.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### Is it a regression?

1.10.1

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
Have you tried with the offline installer?

`https://content-system.gog.com/open_link/download?path=/open/galaxy/client/2.0.67.2/setup_galaxy_2.0.67.2.exe`

**Comment by offhub** [comment]
Try running the games by adding the `-force-d3d9` command line argument.

**Comment by offhub** [comment]
Are these game installers downloaded separately or installed through GOG Galaxy? It would be better if you provide proper download links.

**Comment by RandomGOTI** [comment]
Can confirm the Exception EAccessViolation with an old gog game offline installer using sb+ 1.10.x
I used a new gog game offline installer in june with the 1.9.x and didn't had any issue (unable to test the same installer with sb+ 1.10.x at this time)

**Comment by offhub** [comment]
Are you running Windows 7 x64 or Windows 7 x64 SP1? I can open the game with Sandboxie on a Windows 7 x64 SP1 virtual machine without any errors.

It would be better if someone could try it without a virtual machine. Maybe it's a graphics issue.

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/45f2cdcb-d36a-48c3-ba69-22e921b80623

**Comment by RandomGOTI** [comment]
> > I used a new gog game offline installer in june with the 1.9.x and didn't had any issue
> 
> Then it would mean that there has been a regression across recent Sandboxie releases.
> 
downgrade to 1.10.0

**Comment by RandomGOTI** [comment]
> > > > I used a new gog game offline installer in june with the 1.9.x and didn't had any issue
> > > 
> > > 
> > > Then it would mean that there has been a regression across recent Sandboxie releases.
> > 
> > 
> > downgrade to 1.10.0
> 
> Can you confirm it works properly with 1.10.0 but doesn't work with 1.10.1?

https://github.com/sandboxie-plus/Sandboxie/issues/3132#issuecomment-1648391936 1.9.x was the last time i used sbie with a gog offline installer prior to this issue and yes the 1.10.1 changes is what caused this error

**Comment by offhub** [comment]
@Mitch037 If you watched the updated video, there was also the installation part.

If you watched the updated video, there was also the installation part. But your problem seems to be caused by the latest update. (1.10.1)

**Comment by DavidXanatos** [comment]
you can run the online updater set to download version updates to get 1.10.1a which resolves this issue
