### ISSUE TITLE
Addons Installation Failed! due to missing folders

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3135]
### Describe what you noticed and did

1. Uninstall Sandboxie Plus if it is installed and delete the `%ProgramFiles%\Sandboxie-Plus` folder if it remains.
2. Install Sandboxie Plus
3. Open `Addons Manager` (Options > Global Settings)
4. Try to install
    - `File Checker`: It will throw an `Addon Installation Failed!` error because the `bin` folder does not exist in %ProgramFiles%\Sandboxie-Plus directory.
    - `SbieHide.dll`: It will throw an `Addon Installation Failed!` error because the `SbieHide` folder does not exist in %ProgramFiles%\Sandboxie-Plus directory.
    - `LogAPI.dll`: It will throw an `Addon Installation Failed!` error because the `LogAPI` folder does not exist in %ProgramFiles%\Sandboxie-Plus directory.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The appropriate folders should also be created when installing addons.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.3208)

### In which Windows account you have this problem?

A Microsoft account (Administrator)., An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.10.1 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by wilders-soccerfan** [comment]
I tried only for "File Checker" on Win7SP1x64 (v1.10.1, portable folder):
1. Clicking "Install" does create the folder `bin` with two files. Status shows "Installed".
2. Clicking "Remove" deletes the two files. Folder `bin` is not deleted. Status still "Installed".
3. I must manually remove `bin` folder, reopen Global settings and select "Remove" to clear status.

OT: imo, the "Remove" button should be renamed "Uninstall"

**Comment by offhub** [comment]
You probably didn't have any problems installing addons because the portable version runs from a folder that doesn't require administrator rights.

**Comment by DavidXanatos** [comment]
short update on this, it seams we cant use windows file copy mechanics to create a dir when admin rights are requried it can only do that when user rights are enough, despite being able to adk for admin rights when copying to an existing folder.

So I'll move the addon functionality to the updutil.exe this is actually quite a nice improvement.

also the format of the addond ata wil change so after the next build is out the old builds will not be able to handle the data returned by the server, as booth previosue builds were pre releases i think this is fine and we dont need to maintain backwards compatybility for this.

**Comment by bastik-1001** [comment]
> Also the format of the addon data will change (...)

Do users from 1.10.0 and 1.10.1 need to uninstall/remove the addons or can they be updated with the upcoming release?

**Comment by DavidXanatos** [comment]
> > Also the format of the addon data will change (...)
> 
> Do users from 1.10.0 and 1.10.1 need to uninstall/remove the addons or can they be updated with the upcoming release?

they wil need to reinstall some of them, some will work though not being listed as installed some will not work and not be listed

**Comment by DavidXanatos** [comment]
> > Also the format of the addon data will change (...)
> 
> Do users from 1.10.0 and 1.10.1 need to uninstall/remove the addons or can they be updated with the upcoming release?

they will need to reinstall some of them, some will work though not being listed as installed some will not work and not be listed.

Basicall the once that will work are those that install fine on nonportable builds.

**Comment by bastik-1001** [comment]
I think that it is smart to mention this in the release description and in the change-log. While I don't know how many downloaded addons, there have been enough downloads of the pre-releases for users to be confused about why an addon is no longer listed as installed and the rest.

**Comment by DavidXanatos** [comment]
Yes I'll emphasis this in the next release note
