### ISSUE TITLE
explorer stuck on loading video thumbnails, thumbnails won't load

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#3137]
### Describe what you noticed and did

video thumbnails won't load, go to a folder containing videos and the explorer gets stuck on loading the thumbnails, they won't load

![2023-07-25 00 22 04](https://github.com/sandboxie-plus/Sandboxie/assets/54504707/f1cfb3d7-c203-483b-a848-7cc73d61348e)

### How often did you encounter it so far?

whenever open folder containing some videos

### Affected program

not relevant

### Download link

not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

explorer gets stuck on loading video thumbnails, but they won't load

### What is your Windows edition and version?

w11 22h2 22621.1702

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

ESET

### What version of Sandboxie are you running?

plus 1.9.8

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
I had no problem previewing the thumbnails. Do you have a codec pack installed or a non-default setting on your system?

Windows 11 22H2 (22621.1848)


https://github.com/sandboxie-plus/Sandboxie/assets/6871698/a366a212-54c1-46d6-9b07-00bde9b62fc5

**Comment by diieg707** [comment]
> you hav

hi, now that you mentioned actually i have a very non-default setting on your system, i use a lite os called "exceptional 11" windows 11 x-lite (fbconan), no codec packs installed. btw, what codec pack do you recommend? i'm gonna check if it's a codec related issue

**Comment by diieg707** [comment]
hi, i installed the k-lite codec pack and it fixed the problem, thank you for mentioning it was a codec issue

**Comment by offhub** [comment]
Thank you for feedback.
