### ISSUE TITLE
Brave (browser) bookmarks get written to unsandboxed Brave, without template being enabled

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3139]
### Describe what you noticed and did

[Originally reported](https://forum.xanasoft.com/viewtopic.php?f=12&t=626) by the user forSandboxie.

Brave is apparently able to set and delete bookmarks while being sandboxed, as the bookmarks are available outside Sandboxie. (The unsandboxed browser should not have the bookmarks created while being run inside Sandboxie)

There are no templates enabled, nor are open folders defined.

### How often did you encounter it so far?

Everytime bookmarks are created

### Affected program

Brave Version 1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit)

### Download link

Official

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Sandboxed bookmarks should not affect unsandboxed bookmarks, unless the user sets that to be the case.

Edition Windows 10 IoT Enterprise LTSC (64-bit) Version 21H2 OS build 19044.3208 Experience Windows Feature Experience Pack 1000.19041.1000.0

### What is your Windows edition and version?

Edition Windows 10 IoT Enterprise LTSC (64-bit) Version 21H2 OS build 19044.3208 Experience Windows Feature Experience Pack 1000.19041.1000.0

### In which Windows account you have this problem?

Not relevant to my request. (I don't know which account type is used.)

### Please mention any installed security software

Unknown

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.8 64bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

[https://forum.xanasoft.com/download/file.php?id=158&sid=5daed0449da76193cb6e70c24141b34a](https://forum.xanasoft.com/download/file.php?id=158&sid=5daed0449da76193cb6e70c24141b34a)

**Comment by offhub** [comment]
It is caused by the browser's data synchronisation. It is not caused by a Sandboxie bug.

You can work around this by hiding the `Default` user profile from the sandboxed browser.
 ```
WriteFilePath=%LocalAppData%\BraveSoftware\Brave-Browser\User Data\Default\
```

**Comment by bastik-1001** [comment]
Thanks, again. I copied the information to the forum, for easy access. I will close the issue, once the user confirms your conclusion.
