### ISSUE TITLE
MS Edge just shows white screen

### ISSUE THREAD

**Issue by AlexLohrer** [sandboxie-plus/Sandboxie#3143]
### Describe what you noticed and did

Already for many months, I can't run MS Edge sandboxed. It just shows a white screen (or sometimes a black screen after clicking around for a while).

I already tried several things:
Apply Template=Edge_Fix
Change all 4 settings under Global Settings / Sandboxing features
Create a new Sandbox with virtualization scheme 2
Install Edge in a sandbox instead just running it there
Grant admin rights and allow MSIServer

But nothing helped so far.

What I found in the trace log so far is the following error message:
15:19:55.378	msedge.exe	7336	11840	Debug (U)	Trace 		CreateProcess: C:\Program Files (x86)\Microsoft\Edge\Application\115.0.1901.188\identity_helper.exe ("C:\Program Files (x86)\Microsoft\Edge\Application\115.0.1901.188\identity_helper.exe" --type=utility --utility-sub-type=winrt_app_id.mojom.WinrtAppIdService --lang=de --service-sandbox-type=none --mojo-platform-channel-handle=6232 --field-trial-handle=2108,i,6071168343451488038,7440860577844842398,262144 /prefetch:8); err=122

The cv_debug.log, which is referenced somewhere in the trace log, contains the following:
{"logTime": "0730/131055", "correlationVector":"183D66E17B6643F1BF73902A8E26B6DA","action":"FETCH_UX_CONFIG", "result":""}
{"logTime": "0730/131055", "correlationVector":"fOLleqHYHEFNAzTiUfr2eP","action":"EXTENSION_UPDATER", "result":""}
{"logTime": "0730/131726", "correlationVector":"804D6241DE724B02BD6140D5C4B50C9F","action":"FETCH_UX_CONFIG", "result":""}
{"logTime": "0730/131726", "correlationVector":"HuejusdERhNKIOIG0LRS+9","action":"EXTENSION_UPDATER", "result":""}
{"logTime": "0730/131818", "correlationVector":"1419B8044E3B4042B3B361E1B48A4B1E","action":"FETCH_UX_CONFIG", "result":""}
{"logTime": "0730/131818", "correlationVector":"EeBh52837JAscB0P7GAW+8","action":"EXTENSION_UPDATER", "result":""}
{"logTime": "0730/134456", "correlationVector":"62FD988FDF324C27B27A37E65E6FBFC3","action":"FETCH_UX_CONFIG", "result":""}
{"logTime": "0730/134456", "correlationVector":"mPh9A1FiIupFOt9JxMA7po","action":"EXTENSION_UPDATER", "result":""}

### How often did you encounter it so far?

Everytime I open MS Edge sandboxed

### Affected program

MS Edge 115.0.1901.188 64-Bit

### Download link

https://www.microsoft.com/en-us/edge/business/download?form=MA13FJ

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

MS Edge runs when sandboxed

### What is your Windows edition and version?

Windows 11 Pro 22H2 Build 22621.1992

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.8. 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Trace log

https://drive.google.com/file/d/1col3QYvT8E4ShClMErkytX2Np9RnJxk7/view?usp=sharing

### Sandboxie.ini configuration

```shell
[GlobalSettings]
FileRootPath=\??\%SystemDrive%\Sandbox\%SANDBOX%
SeparateUserFolders=n
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=LogitechSetPoint
DefaultBox=DefaultBox
EnableWin32kHooks=n
NetworkEnableWFP=y
SandboxieLogon=y

[UserSettings_11E40282]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
SbieCtrl_RecoverTarget=C:\Users\Alex\Desktop
BoxDisplayOrder=DefaultBox,Edge
BoxGrouping=:DefaultBox,Edge

[Edge]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=Edge_Force
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
FakeAdminRights=y
BoxNameTitle=n
DropAdminRights=y
CopyLimitKb=81920
ClosedFilePath=msedge.exe,C:\Users\Alex\Desktop\Downloads
ClosedFilePath=msedge.exe,E:\
```

**Comment by AlexLohrer** [comment]
I'd like to add that this problem occurs on two different computers, both with Windows 11 22H2. So I can't imagine that I'm the only one with this issue. An update to Sandboxie 1.10.4 didn't help.

Additionally, I just found out that Edge is in fact running and web pages are loading, because I can see the cursor changing when hovering over things like the URL bar. And I can copy text out of the window to make it visible, but the window remains completely white/black.

**Comment by AlexLohrer** [comment]
I assume that there's a connection between this issue and #3198, as the problem is actually the same and I'm also using Win11 with Intel graphics. In contrast to the linked issue, however, my Edge browser doesn't even show the title bar and I can't fix the issue by adding `NoRestartOnPAC=y` to the sandbox configuration. However, adding this setting fixed another problem for me, see #3235.

**Comment by offhub** [comment]
Try enabling Win32k Hooks.

`EnableWin32kHooks=y`

**Comment by AlexLohrer** [comment]
Thanks for the tip. Unluckily that doesn't help. As I mentioned in the beginning, I already changed all 4 settings under Global Settings / Sandboxing features. I just tried again by also adding Win32kHooks manually in the global config and/or box config, but still same result.

**Comment by offhub** [comment]
Yes, I know, but I wanted to be sure. Because it was opening when I enabled hooks in the virtual machine.

Try after setting `ExternalManifestHack=msedge.exe,y`

**Comment by AlexLohrer** [comment]
Adding `ExternalManifestHack=msedge.exe,y` to the global config did the trick. Thanks again for your excellent support! 👏

**Comment by fanch8-design** [comment]
Hello, I have the same problem of Edge white screen in sandbox mode

Where I should try this command please ? 

EnableWin32kHooks=y

and

ExternalManifestHack=msedge.exe,y
