### ISSUE TITLE
Cosmetic Typo in Windows 7 Provisional Driver Installation Dialog

### ISSUE THREAD

**Issue by TeslaMagic** [sandboxie-plus/Sandboxie#315]
Current...

Windows 7 requires a provisional driver package, you will have to
download it from GitHub release page
https://github.com/sandboxie-plus/Sandboxie/releases/\r\ndo you
have it downloaded?

Should read...

Windows 7 requires a provisional driver package, you will have to
download it from GitHub release page
https://github.com/sandboxie-plus/Sandboxie/releases/
Do you have it downloaded?

Or...

Windows 7 requires a provisional driver package. You will have to
download it from GitHub release page
https://github.com/sandboxie-plus/Sandboxie/releases/
Do you have it downloaded?

**Comment by DavidXanatos** [comment]
thanks will be fixed in the next build
