### ISSUE TITLE
[Plus 1.10.2] Process Suspend/Resume context menu

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#3156]
### Describe what you noticed and did

Right click on sandboxed process in sandman
-Resume remains disabled for suspended processes
-Resume not disabled for terminated processes (KeepTerminated=true)

### Affected program

sandman

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

.

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.10.2 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
anyone else with this issue? i cant reproduce it right now
