### ISSUE TITLE
[Plus 1.10.2] Protect this sandbox from deletion or emptying UI issue

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#3157]
### Describe what you noticed and did

Toggling from partial check (NeverRemove=y) to full check (NeverDelete=y) results in both options in config
Toggling from empty(off) to full same as above

### Affected program

sandman

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

NeverRemove replaces NeverDelete option in config and vice versa depeding on the checkbox status partial or full

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1.10.2 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
its intended to have booth options checked, why woudl this be a bug?

**Comment by RandomGOTI** [comment]
> its intended to have booth options checked, why woudl this be a bug?

NeverDelete=y still retains the old function to prevent both content deletion and box removal , thought this was intented

**Comment by DavidXanatos** [comment]
i would leave it as is its more explicit this way
