### ISSUE TITLE
Set a folder that is not quarantined

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#3161]
### Is your feature request related to a problem or use case?

This function is added on top of the fast recovery function, which requires some operation. Setting non isolated folders can exempt the fast recovery operation

### Describe the solution you'd like

You can set a non isolated folder or drive letter

**Comment by DavidXanatos** [comment]
you mean OpenFilePath? we already have https://sandboxie-plus.com/sandboxie/openfilepath/
or how would you request be different than this functionality?

**Comment by Taeyeonzpx** [comment]
> you mean OpenFilePath? we already have https://sandboxie-plus.com/sandboxie/openfilepath/ or how would you request be different than this functionality?

Oh, thank you very much. That's what I want to talk about, but hasn't this feature been added to the GUI yet?

**Comment by Taeyeonzpx** [comment]
> you mean OpenFilePath? we already have https://sandboxie-plus.com/sandboxie/openfilepath/ or how would you request be different than this functionality?

I seem to have tried this method before, but the reason why it didn't work before seems to be due to incorrect access permission settings

**Comment by Taeyeonzpx** [comment]
> you mean OpenFilePath? we already have https://sandboxie-plus.com/sandboxie/openfilepath/ or how would you request be different than this functionality?

Setting it to fully open now is successful. Thank you
