### ISSUE TITLE
Add mechanism to open websites for addons

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3166]
### Is your feature request related to a problem or use case?

The upcoming addon manager does not allow users to read on about details of those addons.

### Describe the solution you'd like

Some way, the user can access the website (whenever available or appropriate) of an addon. Be it a button on the right side, under "install" or a right click menu or a column with a clickable link.

### Describe alternatives you've considered

Maybe it is tricky for the file checker or some bundle of things, where you could point to documentation about the components, instead.

**Comment by DavidXanatos** [comment]
haha yes that was planned hence the entry in the addons.json for info_url
but how do we best show it? double click? make the name row a clickable link?
a button?
i need suggestions for the UI design

**Comment by bastik-1001** [comment]
I am open to all these ways. To me there is no preferred way, which is why I did not suggest a specific method. In any case Sandman will present them with a dialog to ask if they want to open a browser sandboxed or not, showing the URL so the user know where they will end up. If that would not be the case, I'd prefer to know where I get to, when I choose to open the website, so a column with a link would ensure that.

Since I have no idea, what is easier to implement, works for most people and is desirable from a UI perspective.
