### ISSUE TITLE
Sandboxie-Plus-x64-v1.10.3 crash on startup

### ISSUE THREAD

**Issue by rcdevice** [sandboxie-plus/Sandboxie#3174]
### Describe what you noticed and did

I  have upgrade Sandboxie plus from 1.9.8 to  1.10.3 , keep settings and all boxes. 
but when I startup ,it get crashed!

So I can't test new features any more.

![Snap4](https://github.com/sandboxie-plus/Sandboxie/assets/30013680/4a3753ea-1f29-44f3-bf7a-2f7ef62cacb5)

### How often did you encounter it so far?

always

### Affected program

Sandboxie manager

### Download link

Sandboxie-Plus-x64-v1.10.3

### Where is the program located?

Not relevant to my request.

### Expected behavior

I think this may be a compatibility BUG, and legacy Settings from previous versions may cause the program to crash

### What is your Windows edition and version?

Windows 10 LTSC 21H2 64bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

All off

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.10.3.

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
could you please provide a few crash dumps

**Comment by rcdevice** [comment]
[DMP.zip](https://github.com/sandboxie-plus/Sandboxie/files/12288701/DMP.zip)
Thank you！
