### ISSUE TITLE
Not possible to install VirtualBox USB Support drivers

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#3183]
### Describe what you noticed and did

1. Create a new box
2. Download [VirtualBox (6.1.0)](https://download.virtualbox.org/virtualbox/6.1.0/VirtualBox-6.1.0-135406-Win.exe)
3. Launch installation of VirtualBox
4. Get an error message
![image](https://github.com/sandboxie-plus/Sandboxie/assets/93145383/4cee3438-d2d9-4756-9347-c73d0c4eb74c)

### How often did you encounter it so far?

Always

### Affected program

VirtualBox 6.1.0

### Download link

https://download.virtualbox.org/virtualbox/6.1.0/VirtualBox-6.1.0-135406-Win.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

If it is possible I would like to be able to install the application correctly.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

Microsoft Security Essentials

### What version of Sandboxie are you running?

1.10.3a

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by isaak654** [comment]
I think there are two conflicting replies on the subject:
https://github.com/sandboxie-plus/Sandboxie/issues/1207#issuecomment-1027332012
https://github.com/sandboxie-plus/Sandboxie/issues/3295#issuecomment-1712731364

**Comment by DavidXanatos** [comment]
right, that's the right one: https://github.com/sandboxie-plus/Sandboxie/issues/1207
the other one was not well though through focusing only on the default use case with a yellow box
