### ISSUE TITLE
Latest wechat installer stuck

### ISSUE THREAD

**Issue by mio-19** [sandboxie-plus/Sandboxie#3185]
### Describe what you noticed and did

1. Download wechat 3.9.6 from https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe and run the installer in a newly created sandbox
2. See `"C:\Windows\SysWOW64\cmd.exe" netsh advfirewall firewall delete rule name="WeChat" program="C:\Program Files\Tencent\WeChat\WeChat.exe"` running and installer stuck

### Affected program

Wechat 3.9.6

### Download link

https://pc.weixin.qq.com/?lang=en_US

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

-

### What is your Windows edition and version?

Windows 11 Pro 22H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

1.9.8 64 bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by isaak654** [comment]
I'm unable to reproduce it with [v1.10.4 x64](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.10.4).

**Comment by ouyanmao** [comment]
I was able to launch WeChat 3.9.6.1000，test build with the following configuration line: SpecialImage=chrome,wechat.exe

![img]https://upload.cc/i1/2023/08/24/Fptnwf.png[/img]


The program works normally, hope it can help you.
