### ISSUE TITLE
Various Unity-based games freeze a long time at startup

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#319]
Edit: 
Summary based on responses:
* Issue affects various Unity-based games
* Symptom: Game starts; black screen and freezes for 5+ minutes, then runs ok
* May be related to version of Windows or version of Sandboxie as some games ran fine a long time ago

Original issue:

A number of "GoG" 3D games freeze on start in sandboxie (v.5.45.1 and earlier).

Examples:
* Undermine  (very small game, so probably good for testing)
* Iron Harvest Deluxe

The symptoms are always the same:
* Application starts
* Application goes to all-black full screen
* (sometime) mouse cursor changes to game cursor shape
* After a few seconds mouse cursor changes to Windows "waiting blue circle" and application freezes
* Clicking on screen results in Windows "close or wait" message box

This happens regardless to..
* Enabling/disabling network
* Setting "NoAddProcessToJob=y"  (I believe this is redundant with v5.45.1 anyway?)
* Starting the application via "sandboxie > sandbox > start from start menu", or via sandboxed windows explorer
* Starting the application with sandboxie > sandbox > start any application > check start as UAC admin > ...

Typical sandbox config:

[DefaultBox]

ConfigLevel=7
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
BorderColor=#00FFFF,ttl
Enabled=y
NotifyInternetAccessDenied=n
CopyLimitKb=49152
CopyLimitSilent=y
ClosedFilePath=InternetAccessDevices
NoAddProcessToJob=y

**Comment by typpos** [comment]
Resource access log example:

[resource access log.txt](https://github.com/sandboxie-plus/Sandboxie/files/5763082/resource.access.log.txt)

**Comment by GoldJohnKing** [comment]
Hi, I've encountered similar problem with both Sandboxie (Classic) and Sandboxie-Plus on Windows Server 2019. It should also reproduce with all Windows 10 equal or newer than version 1809. This does not happen on Windows Server 2016 (Windows 10 version 1607) at all. All those freezing games are Unity games, and the Unity engine logged these, which is the only major difference between inside and outside Sandboxie:

```
[WARNING] Detected possible sandbox. Raw Input does not work correctly in a sandbox with default security settings.
[WARNING] Unable to initialize Raw Input! This error can be caused by running Unity sandboxed.
Attempting to fallback to Direct Input...
Direct Input initialized!
```

The games freeze for a quarter or half an hour, then started successfully. I've tested many Unity games, some of them are ok, while others all have the same problem.

Would you please check if your freezing games are Unity games? And if it is, check the Unity engine log to find out if we are having the same problem. We should try to specify the cause so that developers may fix this.

My list of Unity games that have startup freezing issue:
- Untitled Goose Game
- Cuphead
- GRIS
- Candleman
- Creaks
- Wintermoor Tactics Club
- The Last Tinker: City of Colors
- DORAEMON STORY OF SEASONS
- Cat Quest
- Risk of Rain 2

**Comment by typpos** [comment]
Very useful thanks..

> The games freeze for a quarter or half an hour

Indeed! After a 5min black-screen stall it moves on to the start screen.

> Would you please check if your freezing games are Unity games?

UnderMine and Iron Harvest are Unity games and I did have this problem with other Unity games. Unsure if it happened exclusively to Unity games.

> check the Unity engine log

I do not get unity crash logs. There is a Player.log which lists stuff seemingly not relevant to any issue.

> Candleman

It did work a long time ago (2018?). Just tried and now has the same issue. which correlates to your comments.

Other observations..
* UnderMine runs fine in Windows 10 Sandbox.
* UnderMine runs fine in Sandboxie v5.45.1 installed inside Windows 10 Sandbox.
* SysInternals' Process Monitor (file & registry monitor) shows that Undermine.exe stalls after accessing file System32\BluetoothApis.dll, and after taking a break sets a registry value. Looks all fine at that level, but procmon.exe isn't reporting everything that's going on with locks etc.

**Comment by GoldJohnKing** [comment]
> I do not get unity crash logs. There is a Player.log which lists stuff seemingly not relevant to any issue.

No, not the crash log. Unity game would generate logs while running, it should be located in:
`<GameRootFolder>\<GameName>_Data\output_log.txt`
or
`%AppData%\LocalLow\<StudioName>\<GameName>\output_log.txt`

**Comment by NewKidOnTheBlock** [comment]
When I ran my Humble Trove Marathon, I found that these games either freeze like described above or outright refuse to run  in Sandboxie:
- Grotto
- American Fugitive
- Elephant in the Room
- Divinoids
- Spiral Scouts
- Almost There
- Vape Escape
- Avernum 3
- Momodora
- Zodiac XX
- Strafe
- Ihmost
- Etherborn
- Before I forget
- Forager
- One Step from Eden
- Silence
- Tales from Off-Peak City

**Comment by GoldJohnKing** [comment]
That's great, so we can rename the issue title to a more accurate topic. 👍

**Comment by typpos** [comment]
Changed title. Feel free to suggest a better one.

**Comment by typpos** [comment]
> check the Unity engine log

No such log with UnderMine. However, another game with this issue is "Bad North". It creates Unity logs and the difference to non-sandboxed runs are:

8 times:
```
<RI> Failed to get device info:
The handle is invalid.
(Filename:  Line: 970)
```
And then just like @GoldJohnKing reported:

```
[WARNING] Detected possible sandbox. Raw Input does not work correctly in a sandbox with default security settings.
[WARNING] Unable to initialize Raw Input! This error can be caused by running Unity sandboxed.
Attempting to fallback to Direct Input...
Direct Input initialized!
```

After 5 minutes the game starts and runs ok. Enough time to fetch a beer.

**Comment by GoldJohnKing** [comment]
I've just tried the newest release version v0.5.3b. Fortunately, the `Raw Input` from Unity game logs disappeared, which seems to be solved by the version (read the changelog). Unfortunately, however, Unity game startup still freezes.

So raw input is not the exact problem, we need to readdress the cause.

> 8 times:
>
> ```
> <RI> Failed to get device info:
> The handle is invalid.
> (Filename:  Line: 970)
> ```

This happens to me, too, but only for some of the Unity games, not all of them. (Haven't reproduced yet since v0.5.3b.)

**Comment by GoldJohnKing** [comment]
I captured several logs during Unity game startup procedure, and found those games freeze before it search for compatible XInput library.

Take Untitled Goose Game as an example:

```
Initialize engine version: 2018.4.1f1 (b7c424a951c0)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 780 Ti (ID=0x100a)
    Vendor:   
    VRAM:     3029 MB
    Driver:   26.21.14.4614
Begin MonoManager ReloadAssembly
- Completed reload, in  0.162 seconds
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.447600 ms
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
UnloadTime: 0.327200 ms

==================================================================================
<-- The game freezes a few minutes here, then continues. -->
==================================================================================

Searching for compatible XInput library...
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_3.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_3.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_3.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_3
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_3.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_3
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_3.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_3.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_3.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_2.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_2.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_2.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_2
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_2.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_2
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_2.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_2.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_2.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_1.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_1.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_1.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_1
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_1.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/xinput1_1
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_1.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_1.dll
Fallback handler could not load library D:/GAMES/Untitled Goose Game/Untitled_Data/Mono/libxinput1_1.dll
Found Xinput1_4.dll.

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 3373.
Total: 17.713500 ms (FindLiveObjects: 0.314800 ms CreateObjectMapping: 0.048800 ms MarkObjects: 17.302600 ms  DeleteObjects: 0.046800 ms)

connected to steam as user CODEX
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

setting initial controller
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
```

I use [LogApiDll](https://github.com/sandboxie-plus/LogApiDll) together with Sandboxie-Plus to capture API called by the game, only found it `sleep 10` during and after the freeze.

**Comment by NewKidOnTheBlock** [comment]
I'm picking up issues that mention other games that might be directly related:
- Project Winter #265 
- Life is Feudal #101

-> Does anybody have those and can reproduce?

**Comment by GoldJohnKing** [comment]
Nope, I don't think these three are the exact same issue, because they are crash, not freeze but finally startup fine:

> - StarCraft 2 #110 = Starcraft Engine
> - Life is Feudal #101 = ?
> - Lost Ark MMORPG #92 = Unreal Engine

However, this one could be related:

> Project Winter #265 = ?

I'm pretty sure it's Unity engine.

**Comment by NewKidOnTheBlock** [comment]
It takes exactly 5 minutes of freeze until an affected Unity game starts in sandbox.
I'll keep adding titles to my list as I encounter them.

**Comment by typpos** [comment]
After some digging, I think the 5 minute freeze may be caused by the Unity app calling irprops.cpl!BluetoothFindFirstDevice which for some reason stalls 5 minutes while running in sandboxie.

* https://docs.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothfindfirstdevice

I attached a trivial x64 .NET console app ([Program.cs.txt](https://github.com/sandboxie-plus/Sandboxie/files/5865697/Program.cs.txt)) to demonstrate: Outside sandboxie it returns immediately, inside sandboxie, it freezes 5 minutes and then completes.

Can someone please confirm, and are there resource access settings to fix this?

**Comment by hg421** [comment]
> 
> 
> After some digging, I think the 5 minute freeze may be caused by the Unity app calling irprops.cpl!BluetoothFindFirstDevice which for some reason stalls 5 minutes while running in sandboxie.
> 
>     * https://docs.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothfindfirstdevice
> 
> 
> I attached a trivial x64 .NET console app ([Program.cs.txt](https://github.com/sandboxie-plus/Sandboxie/files/5865697/Program.cs.txt)) to demonstrate: Outside sandboxie it returns immediately, inside sandboxie, it freezes 5 minutes and then completes.
> 
> Can someone please confirm, and are there resource access settings to fix this?

You're right, this test program stalls while waiting on an ALPC port when running in a sandbox.
The following resource access rule appears to solve the problem:
![rule](https://user-images.githubusercontent.com/78082344/106007415-8fee3700-60b6-11eb-8ec7-bbbf19c1e444.png)
I'm not sure about the box isolation consequences of this though...

**Comment by DavidXanatos** [comment]
> 
> 
> > After some digging, I think the 5 minute freeze may be caused by the Unity app calling irprops.cpl!BluetoothFindFirstDevice which for some reason stalls 5 minutes while running in sandboxie.
> > ```
> > * https://docs.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothfindfirstdevice
> > ```
> > 
> > 
> > I attached a trivial x64 .NET console app ([Program.cs.txt](https://github.com/sandboxie-plus/Sandboxie/files/5865697/Program.cs.txt)) to demonstrate: Outside sandboxie it returns immediately, inside sandboxie, it freezes 5 minutes and then completes.
> > Can someone please confirm, and are there resource access settings to fix this?
> 
> @typpos You're right, this test program stalls while waiting on an ALPC port when running in a sandbox.
> The following resource access rule appears to solve the problem:
> ![rule](https://user-images.githubusercontent.com/78082344/106007415-8fee3700-60b6-11eb-8ec7-bbbf19c1e444.png)
> I'm not sure about the box isolation consequences of this though...

they are not good, opening the epmapper disables pretty much the entire COM isolation

the question would be if it's possible to find a more fine grain rule to make it work.

I'll check this out shortly.

**Comment by DavidXanatos** [comment]
@typpos how does the example program runs on your system in the sandbox does it find any devices when epmaper is closed`?

**Comment by DavidXanatos** [comment]
I have extended the mechanism used for print spooler to also open the IPC port required to access bluetooth devices this should fix the issue.

**Comment by typpos** [comment]
> how does the example program runs on your system in the sandbox does it find any devices when epmaper is closed`?

I don't have any bluetooth devices / radio.

Run inside sandbox:
* Returns null. GetLastWin32Error() returns 1753 - There are no more endpoints available from the endpoint mapper.

Run outside sandbox:
* Returns null. GetLastWin32Error() returns 6 - The handle is invalid.


> I have extended the mechanism used for print spooler to also open the IPC port required to access bluetooth devices this should fix the issue.

Great! Does/can this include the option to block access to BT entirely and return immediately?

**Comment by DavidXanatos** [comment]
full access it successfuly enumerated my BT headphones once I connected a usb BT dongle to my test VM,
with a ini option this can be blocked than it should fail quickly

**Comment by typpos** [comment]
Verified working:

* Undermine: :thumbsup:
* Candleman: :thumbsup:
* Light Fall Lost Worlds: :thumbsup:
* Sunless Skies: :thumbsup:
* Iron Harvest: :thumbsup:
* Bad North: :thumbsup:

Thanks, David!

**Comment by Agoutii** [comment]
On cause of freezing during load appears to be triggered by the Unity Crash Handler interactions. Renaming or otherwise removing UnityCrashHandler64.exe has reliably fixed several Unity applications which failed to launch sandboxed (Sandboxie v1.1.3). From memory, launching as (sandboxed) administrator also corrected some previously.

**Comment by NewKidOnTheBlock** [comment]
@Agoutii Interesting. 
Some games steadfastly refuse to start in my box with internet access turned off `AllowNetworkAccess=n` and only start if given internet access.
