### ISSUE TITLE
Add "Sandboxie\All Sandboxes" SID into token with SandboxieLogon

### ISSUE THREAD

**Issue by diversenok** [sandboxie-plus/Sandboxie#3191]
### Is your feature request related to a problem or use case?

The tokens generated with `SandboxieLogon` allow distinguishing sandboxes based on the user, but they are missing a common  property that allows addressing all sandboxes at once. Some examples where having a Sandboxie equivalent of `ALL APPLICATION PACKAGES` SID would be useful include SACL-based auditing policies, AppLocker rules, etc. Currently, I can create rules/ACEs for `Sandboxie\Default_Box` or any other specific sandbox, but not all of them at once. 

### Describe the solution you'd like

Sandboxie can add a custom SID into token groups and provide a SID-name mapping for it like it does for per-sandbox accounts. I suggest mapping `S-1-5-100-0` to `Sandboxie\All Sandboxes` and adding it as enabled mandatory group.  This SID cannot collide with existing sandbox SIDs (due to a different length) and follows the same pattern Windows uses for virtual account logon (see `NT SERVICE\ALL SERVICES`, `NT VIRTUAL MACHINE\Virtual Machines`, etc.).

### Describe alternatives you've considered

For some scenarios it might be possible to replace group membership with a custom token attribute. However, because `Everyone`  is disabled for sandboxed tokens, it becomes impossible to address them in some policies without doing so per-sandbox. A common enabled group that doesn't automatically grant any extra access seems like a perfect solution.

**Comment by DavidXanatos** [comment]
I finally found some time to add this great suggestion, sorry it took so long, it will be included in 1.14.1, it will however require the option SandboxieAllGroup=y to be set, as to implement it nicely we use ZwCreateToken to create a proper new shiny token for the sandboxed process, instead of hacking up the original token.

**Comment by DavidXanatos** [comment]
ok its in but reports say that it does not work when the user uses a msft account, 
so I'll leave this open, as a bug report

**Comment by DavidXanatos** [comment]
fixed in 1.14.2
