### ISSUE TITLE
Firefox hang up during the start

### ISSUE THREAD

**Issue by mustwakeup** [sandboxie-plus/Sandboxie#3199]
### Describe what you noticed and did

I can´t use firefox 116 and up, with sandboxie in every version.
Firefox hang up during the start.
But this not happen with firefox 115.1.0esr, even if I update over firefox 116 or when I start firefox every version without sandboxie.
With edge this not  hapen.
My sistem is w10 x 64, firefox without extensions, and I have uninstall/reinstall, create a new profile, open in safe mode with firefox and sandboxie many times.

### How often did you encounter it so far?

many times.

### Affected program

firefox 116

### Download link

not relevant.

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Firefox hang up during the start.

### What is your Windows edition and version?

w10 22h2 x64

### In which Windows account you have this problem?

A local account (Standard user)., A Microsoft account (Administrator).

### Please mention any installed security software

eset smart security

### What version of Sandboxie are you running?

5.65.5

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

firefox 116

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no.

### Crash dump

not relevant.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=NOD32
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
ForceDisableSeconds=357

[DefaultBox]
ConfigLevel=10
AutoRecover=y
BlockNetworkFiles=y
Template=Firefox_Force
Template=Edge_Force
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=E:\HENRIQUE
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,on,6
Enabled=y
BoxNameTitle=n
AutoDelete=y
NeverDelete=n

[UserSettings_176A02A2]
SbieCtrl_UserName=userx64
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1692540943
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
```

**Comment by isaak654** [comment]
Please edit the title accordingly.

**Comment by offhub** [comment]
I always use the Firefox browser in the sandbox and have not encountered this problem. There may be a conflict with ESET software.

Try adding the following lines to `[DefaultBox]`.

```
WriteFilePath=%AppData%\Mozilla\Firefox\
WriteFilePath=%LocalAppData%\Mozilla\Firefox\
```

**Comment by mustwakeup** [comment]
Edit.

I have randomly try other versions of sandboxie and version Sandboxie-Classic-x64-v5.55.22 works well with firefox but not edge.
Version Sandboxie-Classic-x64-v5.64.2 works well with edge but not firefox.

Thanks.

**Comment by bastik-1001** [comment]
> irefox in w7 stop the upgrade in v15, and in w10 my problem is start for firefox 116 (until firefox 115 I don´t have problem with updates). Everything in windows 7 goes well. Either eset stop the updates in w7 and because that in w7 firefox and others programs have lower versions than in w10.

On versions of Windows below 10 (including Windows 7) there won't be new major Firefox versions. Users on old platforms are (or have been) migrated to the extended release branch (ESR), which gets "only" security updates. [English support document](https://support.mozilla.org/en-US/kb/firefox-users-windows-7-8-and-81-moving-extended-support).

([German version](https://support.mozilla.org/de/kb/firefox-nutzer-win-7-8-81-umstellung-firefox-esre) of that document.)

**Comment by mustwakeup** [comment]
Thanks bastik-1001 for your help, but I now that.

**Comment by DavidXanatos** [comment]
whats the status on that does it still need fixing ?

**Comment by mustwakeup** [comment]
Hi.

Yes, firefox don´t work with sandboxie, even with browser protection disable, scrip, banking and  privacy disable.
Thanks.

**Comment by mustwakeup** [comment]
Hi there, sorry for delay.
Over the time i can be more especific wiht this problem. 
What i know now in windows 10: 
- with firefox ESR sandboxie works fine all the time (now I use v 115.8.0);
- with current firefox (v123) what happens is, after install current version, every time i open firefox, it works fine, but if i select  "pause forcing programs", to change something in firefox, this means open firefox without sandboxie,  now the first time i open firefox again sandboxie, it´s freeze, and can´t use for this moment  now firefox sandboxie. Only works without sandboxie.

Thanks in advance.

**Comment by mustwakeup** [comment]
I open in Mozilla suport a issue like I have done here.

https://support.mozilla.org/en-US/questions/1441484#answer-1641296

Thanks in advance.

**Comment by mustwakeup** [comment]
The situation is the same.
