### ISSUE TITLE
Run Sandboxed and Run from folder doesn't use the same working dir

### ISSUE THREAD

**Issue by GunGunGun** [sandboxie-plus/Sandboxie#3203]
### Describe what you noticed and did

Video: https://streamable.com/lar7kk

### How often did you encounter it so far?

Everytime

### Affected program

Sengoku Rance and a lot of similar applications that use config in realative path

### Download link

Not available, require purchasing

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Run in Sandboxed should be able to open the game as normally as running from sandboxed folder.

### What is your Windows edition and version?

Windows 10 22H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

None

### What version of Sandboxie are you running?

1.10.5

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

No

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
Shouldn't be related to Sandboxie.ini anyways
```

**Comment by DavidXanatos** [comment]
This issue should aready be fixed plrease try
