### ISSUE TITLE
What should I do to directly use CMD to call Start.exe without starting SandMan?

### ISSUE THREAD

**Issue by 77525317** [sandboxie-plus/Sandboxie#3206]
### Describe what you noticed and did

Portable Sandbox (Sandbox PLUS) When I copy it to another computer, can not be directly called with CMD, so I use CMD to set SbieSvc.exe as a WINDOWS service, but still can not start normally, then what should I do to be able to directly use CMD to call Sandbox without starting SandMan.exe. Thank you, sir

### Affected program

Start.exe

### Download link

Start.exe

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

then what should I do to be able to directly use CMD to call Start.exe without starting SandMan.exe. Thank you, sir

### What is your Windows edition and version?

win11

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

1

### What version of Sandboxie are you running?

plus1.9

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

1.9

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

no

### Crash dump

1

### Trace log

1

### Sandboxie.ini configuration

```shell
1
```

**Comment by offhub** [comment]
Before running Start.exe, you must install the required SbieDrv and SbieSvc.

1. Disable auto start
     > Options > Global Settings > Shell Integration > uncheck `Start UI when a sandboxed process is started`

    or from config:

    **Sandboxie.ini:**
    >```
    > [UserSettings_XXX]
    > SbieCtrl_EnableAutoStart=n
    > ```

2. Install SbieDrv/SbieSvc and Start SbieSvc

    **InstallSbie.bat:**
    > ```
    > @echo off
    > 
    > REM This .BAT file must be run as administrator from the Sandboxie folder.
    > 
    > set PortDir=%~dp0
    > cd /d "%PortDir%"
    > KmdUtil.exe install SbieDrv ""%PortDir%SbieDrv.sys"" type=kernel start=demand msgfile=""%PortDir%SbieMsg.dll"" altitude="86900"
    > KmdUtil.exe install SbieSvc ""%PortDir%SbieSvc.exe"" type=own start=auto msgfile=""%PortDir%SbieMsg.dll"" display="Sandboxie Service" group="UIGroup"
    > KmdUtil.exe start SbieSvc
    > ```

**Comment by qq1972474341** [comment]
> 在运行 Start.exe 之前，必须安装所需的 SbieDrv 和 SbieSvc。
> 
> 1. 禁用自动启动
>    > 选项 > 全局设置 > Shell 集成 > 取消选中`Start UI when a sandboxed process is started`
>    
>    
>    或来自配置：
>    **沙盒.ini：**
>    > ```
>    > [UserSettings_XXX]
>    > SbieCtrl_EnableAutoStart=n
>    > ```
> 2. 安装 SbieDrv/SbieSvc 并启动 SbieSvc
>    **安装Sbie.bat：**
>    > ```
>    > @echo off
>    > 
>    > REM This .BAT file must be run as administrator from the Sandboxie folder.
>    > 
>    > set PortDir=%~dp0
>    > cd /d "%PortDir%"
>    > KmdUtil.exe install SbieDrv "%PortDir%SbieDrv.sys" type=kernel start=demand msgfile="%PortDir%SbieMsg.dll" altitude="86900"
>    > KmdUtil.exe install SbieSvc "%PortDir%SbieSvc.exe" type=own start=auto msgfile="%PortDir%SbieMsg.dll" display="Sandboxie Service" group="UIGroup"
>    > KmdUtil.exe start SbieSvc
>    > ```

感谢问题解决
