### ISSUE TITLE
 Issue with configuring the original folder of a symbolic link created using mklink to OpenPipePath

### ISSUE THREAD

**Issue by mystique** [sandboxie-plus/Sandboxie#3207]
### Describe what you noticed and did

1. Create a new folder on the D drive: D:\test.
2. Use mklink to create a symbolic link for this folder on the C drive:
   `mklink /j C:\test D:\test`
3. Add the following configuration to the sandbox for testing:
   `OpenPipePath=D:\`
4. Right-click on the sandbox, go to Run->Standard Applications->Windows Explorer.
5. In Windows Explorer, navigate to C:\test, right-click, and choose "New Folder." You will receive the following error prompt:
<img width="345" alt="error" src="https://github.com/sandboxie-plus/Sandboxie/assets/561788/1dcd9ad8-19a8-4480-afbd-3d8caa477c92">

6. If you execute the mkdir command in Run->Standard Applications->Command Prompt, you will be able to successfully create a new folder.

### How often did you encounter it so far?

everytime

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Windows Explorer running in a sandbox can create folders in symbolic links.

### What is your Windows edition and version?

Windows 11 Enterprise 22H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.10.5 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
I don't know if it's a bug or not, but why don't you use the link path or both as the OpenPipePath?

`OpenPipePath=C:\test\`

or 

`OpenPipePath=C:\test\`
`OpenPipePath=D:\test\`

**Comment by mystique** [comment]
> 

This is because my habit of using Sandboxie involves only protecting the C drive, while I set other drives as `OpenPipePath`. Then, I move the application's configuration folders, which are typically located in system directories like `C:\ProgramData` and `C:\Users\[username]\Roaming` on the C drive, to a non-system drive. After that, I use the `mklink` command to create symbolic links to the original paths. This makes it convenient to preserve the configurations after reinstalling the operating system.

However, some content in these folders is also written by the application during installation. When I use Sandboxie to run the installation program for application updates, the installer sometimes prompts an error stating that it's unable to write files to symlinked folders.

**Comment by DavidXanatos** [comment]
this issue was already solved with our recent improvements regarding symlink handling

**Comment by DavidXanatos** [comment]
the issue will be fixed in 1.12.0
