### ISSUE TITLE
When I installed Sandboxie 5.45.1 or 5.45.2 it gets stuck at the License.txt

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#321]
I made sure that nothing is running in Sandboxie.  I have tried the install regularly or as an Administrator.  Then a message comes up saying:
Cannot create or update Sandboxie program files. 
Please make sure that Sandboxie Control is not running,
and that no programs are running sandboxed.

Then click OK to retry the installation.

Otherwise click Cancel to abort the installation.

Ultimately I have to uninstall and, reboot, and reinstall. 
I've had this problem on 3 PC so far.

I'm trying to setup an automated install via an RMM and this problem is a bad wrinkle.

By the way, how do I do a silent install on Sandboxie.

Thanks for all that you do.

**Comment by typpos** [comment]
> I made sure that nothing is running in Sandboxie.

I take it you are performing an upgrade, not a fresh install. I had the exact same problem with several recent upgrades. The new installer somehow failed to kill off and remove the old sandboxie service and the upgrade failed. At this point I was unable to perform an uninstall. The only way to remedy this was to reboot to "unlock" the service. So, uninstall first, then install, while keeping your settings.

Release notes for v5.45.2 say "If you have issues with an update installation, just uninstall the previous version keeping the sandboxie.ini and reinstall the new build." so it's probably a known issue. Don't know if there is an open issue for this.... Well, there is now. :-)

If you are keen, you can open the installer executable with 7zip and extract the files for a "manual" install process.


> By the way, how do I do a silent install on Sandboxie.

Sandboxie installers are built with NSIS (https://nsis.sourceforge.io/Main_Page). You can perform a silent install (https://nsis.sourceforge.io/Docs/Chapter3.html#installerusagecommon) with command line parameter "/S" (must be capital letter S), for example:
`SandboxieInstall64-v5.45.2.exe /S`
However, this does not start and show the sandboxie taskbar icon or main window.

**Comment by TooYoungTooSimp** [comment]
well, I'm pretty sure it's because sbie
 driver doesn't stop properly. It just looks like stuck at license.txt but actually not. You can check sbie service status in sc.exe then you can find it's 'waiting to stop' but never ends.

My solution is reboot pc then install update immediately.

**Comment by bastik-1001** [comment]
Is that still an issue for anybody? There have been some releases since then.

**Comment by NewKidOnTheBlock** [comment]
The last few upgrades went all smoothly. I didn't have to uninstall the old version.
I think this can be closed.
