### ISSUE TITLE
The word addon should be written with a hyphen

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#3214]
_Originally posted by @NewKidOnTheBlock in https://github.com/sandboxie-plus/Sandboxie/pull/3213#issue-1856480137_

> The word _addon_ should be written with a hyphen -> _add-on_
> 
> Prime example: 
> ![add-on](https://user-images.githubusercontent.com/12411527/261579746-8b5c42ad-8f91-4d8d-a479-d4cce139710b.png)
> 
> In Sandboxie it occurs without hyphen: "Addons Manager"
> It should read like this -> "Add-ons Manager"

**Comment by NewKidOnTheBlock** [comment]
Another example:
![add-on2](https://github.com/sandboxie-plus/Sandboxie/assets/12411527/cc281b80-4763-409b-8cce-f7ff45c4d33c)

...and a link to LEO:
https://dict.leo.org/englisch-deutsch/add-on

**Comment by DavidXanatos** [comment]
well if that is the right way to write it then please update it in the UI strings, no objections
