### ISSUE TITLE
You do not have a link to Inetc.zip in the installation manual

### ISSUE THREAD

**Issue by Vponed** [sandboxie-plus/Sandboxie#322]
I had to look. Here it is: https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip
Please add it.

**Comment by DavidXanatos** [comment]
why should I add that to the installer and what does it do exactly?

**Comment by Vponed** [comment]
> why should I add that to the installer and what does it do exactly?

I apologize, I did not immediately figure it out and instead of installing the program, I began to collect it, pulling up everything I needed)))
But the link in the assembly does indeed have a description of the file, but there is no file itself. So I offered to drop the link directly to the download

**Comment by Coverlin** [comment]
https://nsis.sourceforge.io/Inetc_plug-in
`*butwhy.jpg*`

**Comment by DavidXanatos** [comment]
And why would I need that? its an offline installer.

**Comment by DavidXanatos** [comment]
I think I'll close this one if more more input is coming
