### ISSUE TITLE
Download SHA256 checksums on releases

### ISSUE THREAD

**Issue by Ginnder** [sandboxie-plus/Sandboxie#323]
For each release/build, would it be possible to add a commit message detailing the download sha256, or md5sums for each asset file from the release?

Or... Is there a way to check this?

Thanks, Paranoid.

**Comment by CodeGeassCC** [comment]
The DL link is https protocol,so checksum is unnecessary.
But it is appreciated if install package and *.exe & *.dll files in the package are signed with cert.

**Comment by Ginnder** [comment]
https:// yup, odds are no man-in-the-middle attacks. but that wouldn't be my concern.

But I can't find a way to validate the author (the images aren't signed)
And I can't seem to ensure the files posted on the release page match what the author of the post uploaded.

**Comment by exdysa** [comment]
99503998e3939feaa013d513d2a916cf732701cca98d0fc06613a72880eff905  Sandboxie-1.14.6.zip
95dbd294f511335bb0b368c487abe48e8d72aa4b165cba94d32cef71a5e46916  Sandboxie-Classic-x64-v5.69.6.exe
f53222341d96aee525929c10b1681cbe8c03db036789e7115f000f5d82356eff  Sandboxie-Classic-x86-v5.69.6.exe
4163597d710dda0340c8a9d59fa5caf5b0299d4db2245c835f5af503378eaceb  Sandboxie-Plus-ARM64-v1.14.6.exe
f15f19781eace45d840a8ca1328446699f9016e2f1ec7c4bfbd35d4f944d8fd4  Sandboxie-Plus-x64-v1.14.6.exe
267278596914f4bd465547a64512df5adb5bc0155bf8490bb0a31d0bb573830e  Sandboxie-Plus-x86-v1.14.6.exe
adb9db1dbba32562e479b478f997e4b7b19ad2f7600078ca866cfa388721128b  Sandboxie-1.14.6.tar.gz

This was a valid concern that remains unaddressed.

**Comment by isaak654** [comment]
Currently, @GitHub doesn't have a built-in support for [checksums in releases](https://github.com/orgs/community/discussions/23512), so you might want to report this issue there as well.

As a workaround, I suggest to check the last WinGet commits [here](https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/Sandboxie), which provide checksums in the related `InstallerSha256` entries. In this case, pre-release versions are not covered, but they're not signed anyway: https://github.com/sandboxie-plus/Sandboxie/issues/2646#issuecomment-1407468786

**Comment by exdysa** [comment]
4 years later we are still waiting for checksums, and md5 function has been *removed*. I don't think I will make a splash in this case.

I am grateful for your .yaml files, maybe consider serving them or linking them alongside releases page? Cheers

**Comment by DavidXanatos** [comment]
Well 4 years later and we have the installers digitally signed with a EV Code Signing certificate,
this is much better than a checksum, which, whomever man in the middles your connection, can easily change as well together with the installer files.

![grafik](https://github.com/user-attachments/assets/0f746476-1b1b-44dd-b835-747e476f5b2f)

**Comment by exdysa** [comment]
I disagree, given its centralization, much less the avenue of disputable security improvements. A very vocal audience seems to support my position, given the sentiments expressed within the issue links provided above. I think it is unfair to maintainers that the onus be placed on their shoulders, given they are so busy making great open software solutions like Sandboxie possible. My intention is only to politely highlight the matter.
