### ISSUE TITLE
Sandboxie-Plus UI freezes when replacing contributor certificate under a non-administrator account

### ISSUE THREAD

**Issue by TGKx** [sandboxie-plus/Sandboxie#3234]
### Describe what you noticed and did

SBIE Plus v. 1.10.5 running as a normal (non-admin) account under Windows 10

Go to Options/Global Settings/Support & Updates
Paste in new certificate into the dialog box
Click Apply

Receive dialog box saying file exists, click replace, and the action freezes the UI and you must terminate it.  

I was able to work around this by running the SBIE UI as administrator and then it allowed me to replace the certificate.  I think what may be happening is the UAC popup is being suppressed and thus the file replacement can't occur which hangs the UI.

### How often did you encounter it so far?

Every time

### Affected program

SBIE Plus v1.10.5

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Pasting the certificate into the dialog box and clicking apply should result in an immediate replacement and a dialog box saying the licensing has been updated.

### What is your Windows edition and version?

Windows 10 64 Bit Build 19045

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

None

### What version of Sandboxie are you running?

SBIE Plus 1.10.5 64 bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### Is it a regression?

Non Relevant

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

Not relevant

**Comment by DavidXanatos** [comment]
strange i cant reproduce that one, do you have some 3rd party software which suppresses the UAC,
when i test it from a non admin account it shows me a windows where I can login as an admin user to complete the operation
