### ISSUE TITLE
[Plus UI] Side logo cut-off in the About window

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#3249]
_Originally posted by @wilders-soccerfan in https://www.wilderssecurity.com/threads/sandboxie-plus-1-11-0.452253/page-2#post-3160161_

> Minor issue: Sandman UI=>Help=>About (text on the left, below logo, only partially displayed)
> 
> ![Side logo cut-off in the About window](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/1a6d8b61-a603-4064-9e56-eebe3afd479e)
> 1. I'm on Win7 SP1 x64
> Sandman DPI: Native, 100.
> This machine is a tower with an Acer monitor (1680x1050).
> 2. On another Win7Pro laptop (v1.10.2) and Win10 21H1 laptop (v1.10.5), the 'about' screen is blank just below the sandbox image. I have hardly ever opened 'about' screen before, so I don't even know what it used to (or should) look like. So, no big deal for me.
> 3. The 'about' screen glitch appears with v1.11+(0, 0a,0b,0d).

**Comment by wilders-soccerfan** [comment]
Thanks @isaak654 for posting it here. The cut text ("Eternal"?) started only with v1.11.0. No text at all in v1.10.5.
My other machines (W7 pro, W10) with sbie v1,0.2/v1.10.5, show no text either. What does it look for others?

**Comment by DavidXanatos** [comment]
Does anyone else have this issue?
Yea the text is new but it should still not get cut, does it get cut only on w7 machines?

**Comment by offhub** [comment]
You need to set resolution to 1680x1050 and/or increase DPI to 100%+ from Windows. (restart SandMan.exe)

**Comment by wilders-soccerfan** [comment]
> You need to set resolution to 1680x1050 and/or increase DPI to 100%+ from Windows. (restart SandMan.exe)
Was 1680x1050. Now that David has fixed it, I'll wait for the next build. Your DPI suggestion is noted. Thanks
