### ISSUE TITLE
Start.exe /listpids returns nothing

### ISSUE THREAD

**Issue by csmit195** [sandboxie-plus/Sandboxie#325]
Hi, I have 12 boxes, i've tried to listpids for all of them, and the default box, just returns nothing.

![image](https://user-images.githubusercontent.com/5733443/103757330-59e00900-505c-11eb-9c98-e65b9a79049c.png)

I tried doing: Start.exe /listpids
and: Start.exe /box:CSGO_1 /listpids

Is this happening for anyone else? and what is the fix?

**Comment by typpos** [comment]
I don't think you're running anything in DefaultBox. Process Ids belong to running executables, not sandboxes. I get PIDs for processes running in the DefaultBox just like any other (v0.5.3.b)

FYI - Is your screenshot leaking login credentials?

**Comment by csmit195** [comment]
And yes sir, it is,those accs are rand generated, idm if people take em, also please actually read what I wrote lol.

I said, I tried Start.exe /box:CSGO_1 /listpids

Which checks the other boxs, even wehn I load stuff in default box, i still get an empty return from the cmd.

**Comment by typpos** [comment]
> also please actually read what I wrote lol.

I did.  Your screenshot and punctuations are creating ambiguities.

Try this at a command prompt to check the default box:

`"c:\Program Files\Sandboxie\Start.exe" /listpids | more`

Note the pipe command to make things visible if run at a command prompt. Start.exe is not a console application.

To check a specific box:

`"c:\Program Files\Sandboxie\Start.exe" /box:CSGO_1 /listpids | more`

**Comment by csmit195** [comment]
sorry... works.
