### ISSUE TITLE
Close button minimizes Sandboxie instead of terminating it

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#3253]
### Is your feature request related to a problem or use case?

Currently, by default, if you click close button [X] then Sandboxie gets minimized to the System Tray.

### Describe the solution you'd like

Add an option to terminate the application by clicking close button [X].

**Comment by DavidXanatos** [comment]
you can choose in the settings which behavior you want:
![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/3eeb096a-d7d6-41b5-b600-6b4f3a231144)

also when the UI is not running there is no box auto clean up this requires the UI component.

**Comment by DavidXanatos** [comment]
not at all, classic is not being actively developed we just drag it along and if we break something fix it.
