### ISSUE TITLE
Sandboxie does not start any program

### ISSUE THREAD

**Issue by sendc** [sandboxie-plus/Sandboxie#326]
I get the error shown in the screenshot below whenever I try to run a program with Sandboxie-Plus (Right-click -> Run Sandboxed).

I should note that I am using a Windows Insider build (10.0.20257.1).

Potential remedies I have already tried:
- Uninstall & remove Sandboxie.ini in \Windows & reinstall Sandboxie-Plus 0.5.3
- Stop & Restart Sandboxie Driver and Sandboxie Service
- Create new Sandbox & delete old one

It's a shame because I really like Sandboxie-plus. It works flawlessly on all my PCs except on the one using Windows Insider.

![Sandboxie](https://user-images.githubusercontent.com/73389001/103774272-27dd9100-4fe1-11eb-95b8-b20542754de6.png)

**Comment by DavidXanatos** [comment]
https://xanasoft.com/Files/SbieDriver_new.zip
but not that this drivers are only signed with the leaked certificate and those may offend some anti malware fools.
