### ISSUE TITLE
Not possible to install Epic Games Launcher

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#3261]
### Describe what you noticed and did

1. Download and launch [the installer of Epic Games Launcher](https://store.epicgames.com/download)
2. While installing the application I get an error message: **The Windows Installer Service Could Not Be Accessed**
3. The installation process stops and reverts any changes considering the installation failed

According to [the official Microsoft support thread](https://support.microsoft.com/en-us/topic/-the-windows-installer-service-could-not-be-accessed-error-when-you-try-to-install-a-program-in-windows-7-or-windows-vista-fd0c3d5f-76f0-ba9d-d830-059c0943e13d), that seems to be related to the issue, it might be caused by the fact that the MSIServer service cannot be started. Indeed, following the suggestion from the Microsoft thread, I tried to launch the service in the box via CMD by **net start MSIServer**. In response I got an error message: **The service did not start due to logon failure**.

Tried in both yellow and green box. The installer of Epic Games Launcher outside of Sandboxie works flawlessly.

### How often did you encounter it so far?

Always

### Affected program

Epic Games Launcher

### Download link

https://store.epicgames.com/download

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

It would be expected to be able to properly install Epic Games Launcher

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

Microsoft Security Essentials

### What version of Sandboxie are you running?

Sandboxie Plus 1.11.0 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by isaak654** [comment]
Could you verify if it's related to issue #2699?
