### ISSUE TITLE
SandMan v1.10.5-1.11.0e crashed in Vintage view

### ISSUE THREAD

**Issue by lue611** [sandboxie-plus/Sandboxie#3264]
### Describe what you noticed and did

I have installed TIM and WeChat in sandboxie. When I right-click on TIM or WeChat in the sandbox interface, I find that the sandbox reports an error and displays the following image
system is win 10 19045.2251
note: this error only occurs in Vintage view, while in simple view and advance view it works fine
![image](https://github.com/sandboxie-plus/Sandboxie/assets/43984245/85ef7577-e6f0-4d72-a78c-4a1eae05e5ee)
![image](https://github.com/sandboxie-plus/Sandboxie/assets/43984245/61e2c378-1fa3-4a9f-be9d-4489c3af2464)

here is the error file
[SandMan-v1.10.5 30.08.2023 12-23-40,920.zip](https://github.com/sandboxie-plus/Sandboxie/files/12471996/SandMan-v1.10.5.30.08.2023.12-23-40.920.zip)

**Comment by isaak654** [comment]
I can confirm this issue in version 1.11.0e as well.
