### ISSUE TITLE
Voov Meeting can't run

### ISSUE THREAD

**Issue by lue611** [sandboxie-plus/Sandboxie#3270]
### Describe what you noticed and did

I installed Voov Meeting in a new sandbox, but after installed and tried to run voov meeting, it has been terminated
other apps seem to run fine
![1](https://github.com/sandboxie-plus/Sandboxie/assets/43984245/101eb17a-2f41-4173-a3b4-11c333a0d145)

### Affected program

Not relevant

### Download link

https://voovmeeting.com/download-center.html?from=1001

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

/

### What is your Windows edition and version?

win10 22H2

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator).

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie plus V1.10.5

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by mnixry** [comment]
This is a known issue, see: https://github.com/sandboxie-plus/Sandboxie/issues/1842#issuecomment-1291975271

**Comment by lue611** [comment]
> This is a known issue, see: [#1842 (comment)](https://github.com/sandboxie-plus/Sandboxie/issues/1842#issuecomment-1291975271)

Thanks, it works
