### ISSUE TITLE
right click on Explorer inside sandbox doesn't work

### ISSUE THREAD

**Issue by mio-19** [sandboxie-plus/Sandboxie#3271]
### Describe what you noticed and did

1. Open explore
2. Find some exe file
3. Right click
```
PID 10188: SBIE2205 Service not implemented: WMI OemWMIMethod::OemWMIfun
PID 10188: SBIE2205 Service not implemented: WMI IWbemServices 24
```

### How often did you encounter it so far?

Everytime

### Affected program

Explorer

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

-

### What is your Windows edition and version?

Windows 11 Pro 22621.2215

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

1.11.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by mio-19** [comment]
My computer got the new explorer update and this issue persists. 

Right click on folder is fine.

Right click on a exe file:

```
PID: 3912: SBIE2205 Service not implemented:  WMI OemWMIMethod::OemWMIfun
PID: 3912: SBIE2205 Service not implemented:  WMI IWbemServices 24
WerFault.exe: SBIE2112 Object is not accessible: Unnamed object, call ConnectPort (C0000022) access=001F0000 initialized=1
```

 And then the explorer window went into an unresponsive state

**Comment by isaak654** [comment]
#1580

**Comment by DavidXanatos** [comment]
I can not reproduce this issue, I suspect one of your installed shell extensions tries to use WMI, please try disabling shell extensions and report back which is the culprit.

**Comment by creeduk** [comment]
I have the same issue, I moved to Windows 11 and a new PC. My old install works great on Win 10. I have tried plus and classic. I can right click on any folder, but if I click a file it crashes. Maybe a specific option?
Which Shell options is that the Configure > Shell integration? That seems to be extremal shell not those inside the SB?

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

At least that's what makes sense to me.

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

**Comment by isaak654** [comment]
He was probably referring to disabling third-party / system shell extensions one by one with tools like Autoruns, ShellExView, etc.

**Comment by isaak654** [comment]
He was probably referring to disabling third-party/system shell extensions one by one with tools like Autoruns, ShellExView, etc.

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

If you search `OemWMIfun` on any search engine, you should be able to find a reference related to some Huawei application.

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

If you search `OemWMIfun` on different search engines, you should be able to find a reference related to some Huawei application: https://blog.acedroidx.top/HuaweiBatteryControl/

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

If you search `OemWMIfun` on different search engines, you should be able to find a reference related to some Huawei application, for example: https://blog.acedroidx.top/HuaweiBatteryControl/

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

If you search `OemWMIfun` on different search engines, you should be able to find references like https://blog.acedroidx.top/HuaweiBatteryControl/

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

If you search `OemWMIfun` on different search engines, you should be able to find references like https://blog.acedroidx.top/HuaweiBatteryControl/

Are you using Huawei apps?

**Comment by isaak654** [comment]
He was probably referring to disabling third-party shell extensions one by one with tools like Autoruns, ShellExView, etc.

If you search `OemWMIfun` on different search engines, you may find references like https://blog.acedroidx.top/HuaweiBatteryControl/

Are you using Huawei apps?

**Comment by creeduk** [comment]
NO a very new Win11 install with basic apps like Office etc., then I added sandboxie, created a new one but I tested default and mine and any time I right click a file (to do open with or properties etc.) it crashes the explorer window.

**Comment by isaak654** [comment]
> NO a very new Win11 install with basic apps like Office etc., then I added sandboxie, created a new one but I tested default and mine and any time I right click a file (to do open with or properties etc.) it crashes the explorer window.

Please provide a trace log with the latest stable version. For instructions, see [here](https://sandboxie-plus.github.io/sandboxie-docs/PlusContent/TraceLog.html).

**Comment by isaak654** [comment]
> NO a very new Win11 install with basic apps like Office etc., then I added sandboxie, created a new one but I tested default and mine and any time I right click a file (to do open with or properties etc.) it crashes the explorer window.

Please provide a trace log with the latest stable version of Sandboxie Plus. For instructions, see [here](https://sandboxie-plus.github.io/sandboxie-docs/PlusContent/TraceLog.html).

**Comment by isaak654** [comment]
Please provide a trace log with the latest stable version of Sandboxie Plus. For instructions, see [here](https://sandboxie-plus.github.io/sandboxie-docs/PlusContent/TraceLog.html).

**Comment by creeduk** [comment]
Just to confirm as I switched from plus to classic (hoping to resolve this) do I need to add plus back or can I get a trace from classic?

**Comment by isaak654** [comment]
There is a Sandboxie Trace link with the instructions for both editions on the page provided above.

**Comment by creeduk** [comment]
Sorry it took a while, work meant I was not on this machine, then figuring the trace on classic I think I got it, to be sure I added plus on top and got one from both.
[Sandboxie_PLUS_and_classic_log.zip](https://github.com/sandboxie-plus/Sandboxie/files/14389938/Sandboxie_PLUS_and_classic_log.zip)

Still same version, I will also try latest update as it has updated since I reported this.

**Comment by offhub** [comment]
@creeduk 
According to your log, this may be a problem caused by the Notepad++ context menu. You can see if the same problem occurs by adding the following setting to your configuration.

```
ClosedFilePath=explorer.exe,*\NppShell.dll
```

**Comment by creeduk** [comment]
@offhub That did it, THANKS!!

My first test did not seem to work (I added after the trace. I fond the new line was removed so I added it before the trace and then is stuck and voila no crash on right click.
Why do you think that is? I have notepad++ on my other BUT I have portable on my other on this it is installed and the version is newer on here. Some extra integration, or the weird way Win11 handles the contextual now?

**Comment by wilders-soccerfan** [comment]
> @offhub That did it, THANKS!!
> 
> My first test did not seem to work (I added after the trace. I fond the new line was removed so I added it before the trace and then is stuck and voila no crash on right click. Why do you think that is? I have notepad++ on my other BUT I have portable on my other on this it is installed and the version is newer on here. Some extra integration, or the weird way Win11 handles the contextual now?

NppShell.dll may not be part of the portable version. I don't see it in my portable notepad++ folder.

**Comment by creeduk** [comment]
Thankyou that is probably it. I usually keep those apps portable for ease, this time I just installed it direct so that will explain it. Again thank you now I can get my contextual menu items :)
