### ISSUE TITLE
Computer crashed suspiciously while playing Warframe

### ISSUE THREAD

**Issue by CoreDiagram** [sandboxie-plus/Sandboxie#3279]
### Describe what you noticed and did

1. Game froze on loading screen while joining multiplayer team.
2. Clicked Windows button to bring up the Windows tool bar.
3. Right clicked on Warframe icon and on Exit but nothing happened.
4. Started Task Manager but Task Manager was not visible.
5. Right clicked on Windows icon and initiated Restart of computer.
6. Windows Prompt (There were two unknown programs preventing restart). Then it shut down after a while.
7. Took longer than normal to restart.
8. This is the first time this has happened after first and only install of Sandboxie Plus around a month back.

### How often did you encounter it so far?

This is the first time

### Affected program

The problem was solely on sandboxed "Warframe"(It's a multiplayer game which I installed via Steam))

### Download link

https://www.warframe.com/landing

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

I had installed Sandboxie Plus around a month back. I had already installed Steam and Warframe on my laptop. I also installed Steam and Warframe within Sandboxie Plus. The game and Steam worked fine for a month.

Today, while playing Warframe and specifically during joining a multiplayer team, the game froze. I minimized the game but I couldn't terminate it even via Task Manager. I was also unable to access any other system tool.

I had to restart the computer.

Both, system installed Steam and the said system installed game, Warframe, were updated today before this issue happened.

Kindly guide me as to why this issue probably happened and how I can prevent this from happening again.

### What is your Windows edition and version?

Windows 10 Home Single Language 64 bit Ver. 22H2

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

McAfee Antivirus

### What version of Sandboxie are you running?

v1.10.5

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

no

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

### Did you previously enable some security policy settings outside Sandboxie?

no

**Comment by bastik-1001** [comment]
It sounds like a freeze rather than a crash. Do you have some dump if it was indeed a crash?

If Sandboxie is still accessible, while some program froze up under its control, you can try to terminate the process(es) from the GUI. With a recent version of Sandboxie Plus, you can also suspend a process under its control (and resume it), in an attempt to get control over the system resources.

**Comment by hg421** [comment]
If you can't get the Sandboxie GUI to show up, you could also try using the global "terminate all sandboxed processes" hotkey. It is configured in the global settings: 
![img](https://github.com/sandboxie-plus/Sandboxie/assets/78082344/e2d75957-6021-4548-9abf-5b3a37952418)

**Comment by DavidXanatos** [comment]
as there is no more feadback and we now habe a bring sandman in front hotkey i think this can be closed
