### ISSUE TITLE
Fallout 76 crashes after 5 seconds on steam

### ISSUE THREAD

**Issue by Boes0184** [sandboxie-plus/Sandboxie#3281]
### Describe what you noticed and did

my friend bought fallout 76 and when he started it up it starts up, on steam en then after 5 seconds u see, start fallout 76, so i think it crashes or something
whe tryde almost everything
switching drives
reinstalling
downloading stuff
much more 
buth it didnt work
can someone help us

### How often did you encounter it so far?

everytime

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

fallout 76 starting up

### What is your Windows edition and version?

windows 10

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

.

### What version of Sandboxie are you running?

.

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

.

### Crash dump

.

### Trace log

.

### Sandboxie.ini configuration

```shell
.
```

**Comment by bastik-1001** [comment]
This report lacks some details. It does not mention Sandboxie's involvement.

Does FO 76 run on the system, without it being sandboxed? If it does not work with the normal system, if it is installed to the system, Sandboxie can't help, nor will it be the problem. If it is only installed in the sandbox, please mention it.

If it runs with the normal system, but fails to work under Sandboxie's supervision, what version of Sandboxie is being used? E.g. 1.10.5

Does that happen in the standard box, or were you trying some other box type?
