### ISSUE TITLE
Spotify black, uninstalled, uninstalable

### ISSUE THREAD

**Issue by AP2020C** [sandboxie-plus/Sandboxie#3285]
### Describe what you noticed and did

I tried to launch spotify, which I had installed in a dedicated area in Sandboxie a while ago, and it appeared black.
I deleted the contents of the virtual area to install it again, but it initially tells me to run the programme without admin privileges, so I changed the area settings by restricting privileges, from quick options.
Now, trying to run the exe downloaded from the official site, I get
PID 3520: SBIE2217
PID 3520: SBIE2219
Followed by Operation cancelled by user code 1223.

### How often did you encounter it so far?

At each attempt

### Affected program

Spotify installer

### Download link

https://download.scdn.co/SpotifySetup.exe

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

Getting Spotify installed in a virtual area and properly working to play music

### What is your Windows edition and version?

Windows 10 Edu x64 22H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Defender

### What version of Sandboxie are you running?

Plus 1.5.3

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

none

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=Edge_Fix
Template=WindowsRasMan
Template=7zipShellEx
Template=OfficeClickToRun
Template=WindowsLive
Template=OfficeLicensing
NetworkEnableWFP=y
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%

[Spotify]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
DropAdminRights=y
FakeAdminRights=n
```

**Comment by kokofixcomputers** [comment]
I cannot reproduce your issue. I have been successfully able to install spotify using a standard sandbox
