### ISSUE TITLE
File Structure Icons

### ISSUE THREAD

**Issue by PARAViRTUALiZATiON** [sandboxie-plus/Sandboxie#3286]
### In order to provide a better overview, the file structure of SandBoxie+ could be provided with self-explanatory symbols:

_Ideally, those provided by the operating system itself can be linked for this purpose. Because every operating system on which SandBoxie+ can interact already has its own system symbols for these elements and subcategories (green marked area, in the attached graphic)._
 
![PNG](https://github.com/sandboxie-plus/Sandboxie/assets/140122360/1dbae7f1-87ce-405c-9a00-5717b84af19f)

**Comment by DavidXanatos** [comment]
you mean for the files in the file view side panel?

**Comment by PARAViRTUALiZATiON** [comment]
This mainly refers to the files directly in the target storage directory of the host system.

The icons of the sandbox containers are also located there, which currently do not seem to match the user configuration colors.


At this point it should be mentioned that SandBoxie+ creates a temporary file in the %TEMP% directory when it starts (but does not remove it automatically after completion - perhaps this can also be corrected)

- _Ideally, this temporary file would not be created at all, if possible or moved to the respective portable installation directory of SandBoxie+ if it is absolutely necessary for it to function._

**Comment by DavidXanatos** [comment]
about the icons not matching see here: https://github.com/sandboxie-plus/Sandboxie/issues/3047
about the icons of "files directly in the target storage directory of the host system."
reghive has no extension so we cant set an icon, the others we could but would that add so much from a usability standpoint, imho that juct complicates things unnececerly

about the TEMP file its used by the qtsingleapplication library to coordinate multiple instances, it should get deleted on close I'll check that out

**Comment by PARAViRTUALiZATiON** [comment]
This is just as understandable; perhaps there is a compromise solution between effort and benefit.

Certainly it would be less accurate for the recognizable data structure of SandBoxie+, but if this would mean too much work overall, using the system symbols of e.g. (%SystemRoot%) like SHELL32.dll would still be unnecessary.

For structural elements for which there may not be an optimally matching symbol, various other system symbols are available that could prove visually helpful due to their distinctiveness or similarity compared to this symbol identification, rather than none at all.

Of course, completely freely available and comparable icons, such as those currently used in SandBoxie+, would be a conceivable alternative in terms of use, or in the file panel of the application itself, as long as the possible effort here is in proportion to the benefit.

> _Either way and regardless of that, respect for the development of the fabulous software project so far to everyone involved, a few more or less icons won't distract from it..._

**Comment by DavidXanatos** [comment]
I think given how the sub folders are created it would add unnecessary complexity, and a solution involving the UI component to add desktop.ini files after the fact seams hacky
