### ISSUE TITLE
Sandboxed process debugging experience is inconsistent

### ISSUE THREAD

**Issue by CookiePLMonster** [sandboxie-plus/Sandboxie#3288]
### Describe what you noticed and did

First of all, I have no idea if I am trying to achieve something supported or not, but considering how launching sandboxed processes from Explorer is supported - maybe this use case is too.

I found Sandboxie to be a good tool for isolating games I wish to debug, and I have moderate success debugging these sandboxed games (running in a **yellow** sandbox) via an unsandboxed Visual Studio. I am able to just specify the path to inside the sandbox and Visual Studio is able to spawn a debug my process:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/7947461/66f3b9a2-7854-491f-bb64-5fed0444ee22)

However, this doesn't **always** work, and I have not been able to figure out what is the specific variable that causes this setup to work or not. When it "doesn't work", Visual Studio spawns the process, then claims it's been terminated (and detaches) despite the game still starting properly, albeit with a different Process ID.

In this case, the setup from the above screenshot randomly didn't work, then I logged out and back in to try it again, and it worked. I also have cases (right now as I type this bug report) where I can do this to process A inside the sandbox, but I cannot do this to process B inside the very same sandbox.

### How often did you encounter it so far?

Not every time, without a specific pattern

### Affected program

Various video games

### Download link

N/A

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

A sandboxed process should spawn consistently every time

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus v1.10.5

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

### Trace log

When the application fails to launch, the Trace log is empty

### Sandboxie.ini configuration

```shell
Sandbox config:


Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=Local_Steam_Overlay
ConfigLevel=10
FileRootPath=F:\Sandbox\%USER%\%SANDBOX%
UseFileDeleteV2=y
UseRegDeleteV2=y
DropAdminRights=y
FakeAdminRights=y
```
```

**Comment by DavidXanatos** [comment]
Try NoRestartOnPAC=y

**Comment by CookiePLMonster** [comment]
It's tricky, because I can't reproduce this issue anymore when starting games from Visual Studio. I can, however, still reproduce it when starting one particular game from Steam, but considering that Steam has many more unknowns than launching from a debugger, I am not sure if it's the same issue. That said, for Steam's issue `NoRestartOnPAC=y` did not help.

I will try this flag next time VS fails to properly create a process and report back.

**Comment by CookiePLMonster** [comment]
@DavidXanatos Update - I ran into this issue again and I can confirm that `NoRestartOnPAC=y` helps. Thanks!

I'm not sure if this means I should close the issue - as I don't know if this config option works something around or is intended to be used in use cases like mine.
