### ISSUE TITLE
[SOLUTION] SBIE 2224 error after a windows update

### ISSUE THREAD

**Issue by needmypandora** [sandboxie-plus/Sandboxie#3291]
### Describe what you noticed and did

I dont know if anyone else come up with this but If you are getting SBIE 2224 error and Werfault.exe opening and closing together with your programs **(most probably because of a windows update)** try deleting "Windows" folder in the "[BOXNAME]\drive\C\" directory. Your programs should work now.

### How often did you encounter it so far?

Many times.

### Affected program

Not every but some programs were affected

### Download link

Not relevant

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Maybe the setup can clear "Windows" folder in a sandbox post-install?

### What is your Windows edition and version?

Windows 11 Pro 22H2 22621.2215

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Defender

### What version of Sandboxie are you running?

5.66.1 Classic

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

No.

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

### Did you previously enable some security policy settings outside Sandboxie?

No.

**Comment by cospking** [comment]
Can confirm that this occurred for me as well, first I thought it had something to do with **KB5030219**, so after uninstalling it everything worked again.

But today the new Moment Update made it happen as well, deleting the Windows folder in the Sandbox helped.

**Comment by DavidXanatos** [comment]
what files were contained in the offending windows folder?

**Comment by needmypandora** [comment]
> what files were contained in the offending windows folder?

I really dont know exactly. I should have deleted one by one but no longer have the issue.
