### ISSUE TITLE
Troubleshooting log entries are not translated

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3293]
### Describe what you noticed and did

> Starting troubleshooting script: installer
> Troubleshooting script terminated

Are displayed in English, and don't seem to appear in the .ts files.

There might be others.

### Affected program

Sandboxie Plus 1.11.2

### Download link

This repo.

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

The strings being available to be translated.

### What is your Windows edition and version?

not relevant

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

not relevant

### What version of Sandboxie are you running?

Sandboxie 1.11.2 (64bit)

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
there is a mechanism for translating troubleshooting scripts using a de.json or it.json contianing the original englishc and the translated strings i'll provide an exampel for the next build

**Comment by bastik-1001** [comment]
Now, I understand that they don't from Sandman directly.

**Comment by DavidXanatos** [comment]
here it is: https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/Troubleshooting/lang_de.json
please continue with the scripts from ...\Troubleshooting\Sandboxing\SBIEMSG\*

**Comment by isaak654** [comment]
What do you think about self-hosting for free a platform with native GitHub support like [Weblate](https://docs.weblate.org) in order to aggregate all the strings to be translated?

**Comment by isaak654** [comment]
I don't think many people will notice it, what do you think about self-hosting for free a platform with native GitHub support like [Weblate](https://docs.weblate.org) in order to aggregate all the strings to be translated?

**Comment by isaak654** [comment]
I don't think many people will notice it, what do you think about self-hosting for free a platform with native GitHub support like [Weblate](https://docs.weblate.org) in order to aggregate all the strings to be translated?

For example, just think of the [Japanese translation](https://github.com/sandboxie-plus/Sandboxie/compare/master...Justice-Goto-3939:Sandboxie:master) that is currently relegated in a secondary repository. In this case, a platform to centralize all the progress, even if it is incomplete, would be useful.

**Comment by isaak654** [comment]
I don't think many people will notice it, what about self-hosting for free a platform with native GitHub support like [Weblate](https://docs.weblate.org) in order to aggregate all the strings to be translated?

For example, just think of the [Japanese translation](https://github.com/sandboxie-plus/Sandboxie/compare/master...Justice-Goto-3939:Sandboxie:master) that is currently relegated in a secondary repository. In this case, a platform to centralize all the progress, even if it is incomplete, would be useful.

**Comment by bastik-1001** [comment]
While I am not able to read people's minds, the least amount of barriers there are and the easier it is, the more people will contribute. Translating the whole interface is a lot of work, translating a single word or line is not that much work and can be shared easily, probably with someone still trying to ensure consistency.

One question, that does not need to be answered here, is how many lines make someone eligible for a contributor certificate?! Obviously, is that this will be the case if someone translates the interface from scratch, but how much would a single person have to add to apply? Surely, that is for David to decide, but some estimate should be given in the document for contributors.

**Comment by DavidXanatos** [comment]
since it seams that this weblate supports qt linguist we could try it, have to check how easy it is to install with mysql.

About how much contribution is requires that's a good question, any suggestions?

**Comment by bastik-1001** [comment]
> About how much contribution is requires that's a good question, any suggestions?

I can't put a number or percentage on that.  One might compare it to the documentation, where it is supposed to be a meaningful contribution, not just adding a missing dot.

Overall APMichael's contribution, for example, is far more than just helpful, it's meaningful to the project, which creates an eligibility to a contributor certificate, in my mind. The same is true for the new kid, that fixes mistakes in the change-log.

**Comment by DavidXanatos** [comment]
@APMichael 
@NewKidOnTheBlock 

Please send me an email to get a supporter certificate

**Comment by DavidXanatos** [comment]
https://weblate.xanasoft.com/projects/sandboxie-plus/ up and running

**Comment by isaak654** [comment]
> `https://weblate.xanasoft.com/projects/sandboxie-plus/` up and running

There is no space between CPopUpRecovery and the rest of the source string to be translated, which makes things messy:

![English string in Weblate](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/3ce4fee7-714f-44b2-b15a-8fae7de4d566)

Source: https://weblate.xanasoft.com/translate/sandboxie-plus/sandman-ui/de/?offset=1&q=&sort_by=-target&checksum=#nearby

**Comment by isaak654** [comment]
> `https://weblate.xanasoft.com/projects/sandboxie-plus/` up and running

There is no separation between CPopUpRecovery and the rest of the source string to be translated, which makes things messy:

![English string in Weblate](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/3ce4fee7-714f-44b2-b15a-8fae7de4d566)

Source: https://weblate.xanasoft.com/translate/sandboxie-plus/sandman-ui/de/?offset=1&q=&sort_by=-target&checksum=#nearby

**Comment by isaak654** [comment]
> `https://weblate.xanasoft.com/projects/sandboxie-plus/` up and running

There is no separation between CPopUpRecovery and the rest of the source string to be translated, which makes things messy:

![English string in Weblate](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/3ce4fee7-714f-44b2-b15a-8fae7de4d566)

The key should be `CPopUpRecovery`, while the English string should be `Recover && Open/Run`.

Source: https://weblate.xanasoft.com/translate/sandboxie-plus/sandman-ui/de/?offset=1&q=&sort_by=-target&checksum=#nearby

**Comment by isaak654** [comment]
> `https://weblate.xanasoft.com/projects/sandboxie-plus/` up and running

There is no separation between CPopUpRecovery and the rest of the source string to be translated, which makes things messy:

![English string in Weblate](https://github.com/sandboxie-plus/Sandboxie/assets/12372772/3ce4fee7-714f-44b2-b15a-8fae7de4d566)

In my opinion, the key should be `CPopUpRecovery`, while the English string should be `Recover && Open/Run`.
Alternatively, you could put the English string where it's missing.

Source: https://weblate.xanasoft.com/translate/sandboxie-plus/sandman-ui/de/?offset=1&q=&sort_by=-target&checksum=#nearby

**Comment by bastik-1001** [comment]
Since the login data for the forum are not valid, I tried to create a new account. I attempted it several times, but there is no mail in my inbox nor spam. I tried to send a report via the website, but it states "Die Nachricht konnte nicht an den Administrator gesendet werden. " (The message could not be sent to the administrator.)

I intended to use the same name (bastik-1001, for both) and e-mail address, that I use in the forum. Is there anything else, I can do?

**Comment by DavidXanatos** [comment]
it needs a new account, it should sen the email may be it got delayd

**Comment by bastik-1001** [comment]
I had assumed that it required a new account, after, the other did not work, I had expected an error, then a queue, but there was no e-mail to be found. I'll be a bit more patient.

**Comment by DavidXanatos** [comment]
email delivery was broken now it works, please try again

**Comment by offhub** [comment]
I tried three different emails yesterday and still haven't received a confirmation email.

**Comment by DavidXanatos** [comment]
we found another issue with the email server and fixed it please try again

**Comment by offhub** [comment]
It works now.

**Comment by DavidXanatos** [comment]
@all try non google email addresses perhaps we did to much testing and now google does not like us for a few hours

**Comment by bastik-1001** [comment]
I tried, before the fix, with the specific google address and after the fix with the same address. Now that might explain why I don't get an email, even though the website states that is has sent the activation link. I am going to attempt that tomorrow, or so, again.

**Comment by offhub** [comment]
If the troubleshooting lang files are not set to UTF 8 BOM, some characters seem to be corrupted. Is it just me or is this happening to you as well?

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/7209107f-5484-47eb-8c8c-6a22531c6ce8

**Comment by bastik-1001** [comment]
It worked.

@offhub, yes, I see that as well, which I think is what the thumb up mean in this context, but I wanted to confirm it in text.

**Comment by APMichael** [comment]
**For information**: In order to compare the files of "Sandboxie Core" correctly in Weblate, the commented out messages would have to be deleted in all files (source and translations) or all commented out messages of the source would have to be added in all translations. This is because every commented out message that is missing in the translation creates an offset, so that the source and translation no longer match.

---

@bastik-1001: Thank you very much for your [kind words](https://github.com/sandboxie-plus/Sandboxie/issues/3293#issuecomment-1779788251). And sorry for the late response. 😄

**Comment by DavidXanatos** [comment]
Is there no way to tell weblate what a comment is and to ignore it?
that said, I think we can get rid of all unneeded messages, there is no really a point in keeping them.

**Comment by DavidXanatos** [comment]
PS: as I have no experience with weblate yet any advice how to proceed/fix issues/etc would be greatly appreciated.

**Comment by APMichael** [comment]
> Is there no way to tell weblate what a comment is and to ignore it? ...
> PS: as I have no experience with weblate yet any advice how to proceed/fix issues/etc would be greatly appreciated.

This is also the first time I have heard of Weblate, so unfortunately I am not familiar with it either.

**Comment by bastik-1001** [comment]
I am curious to how this will work out, with those strings in "Sandboxie Core", which I am not going to touch, unless there is a change in those files, like new strings.

**Comment by DavidXanatos** [comment]
How do we proceed with this, @isaak654 requested this to be set up it looks like a nice piece of software, but as I repeatedly mentioned I have 0 experience with it so is there anyone willing to learn how to use it, or do I have to take time of coding to learn weblating?

**Comment by DavidXanatos** [comment]
I have copied all untranslated strings in english into the polisch core translation file, so that now all strings are aligned linewhise with the reference file, but weblate still shows me most as untransalted

**Comment by offhub** [comment]
According to the [documentation](https://docs.weblate.org/en/latest/formats/qt.html#weblate-configuration), the "Monolingual base language file" setting should be empty for bilingual TS files.

![firefox_20231105_212433_977x](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/a2ad508d-9cec-41eb-85c1-3b20a3720f95)


![20231105_213103_389x](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/14173831-3f95-4fad-8404-e54899ad3afa)

---

> I have copied all untranslated strings in english into the polisch core translation file, so that now all strings are aligned linewhise with the reference file, but weblate still shows me most as untransalted

https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

**Comment by DavidXanatos** [comment]
i already pressed update ther: https://weblate.xanasoft.com/projects/sandboxie-plus/sandboxie-core/#repository
