### ISSUE TITLE
Not possible to launch any VM in VirtualBox

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#3295]
### Describe what you noticed and did

1. Install and launch VirtualBox (6.0.2.4)
2. Create and start a VM (Virtual Machine)
3. Get an error message: `E_FAIL (0x80004005)`
![image](https://github.com/sandboxie-plus/Sandboxie/assets/93145383/6f005307-be35-4729-abb5-11142dcd7c9f)
4. Sandboxie log says:
> VBoxSVC.exe: SBIE2103 Denied attempt to load system driver 'vboxdrv [VIRTUALBOX] (StartService)'
> VirtualBox.exe: SBIE2103 Denied attempt to load system driver 'vboxdrv [VIRTUALBOX] (StartService)'
5. VirtualBox system service (vboxsds) is required to be run before launching the application. However, regardless of that, Sandboxie log still displays an error when launching VirtualBox:
> VBoxSVC.exe: SBIE2103 Denied attempt to load system driver 'vboxdrv [VIRTUALBOX] (StartService)'

and launching any VM ends with the aforementioned error message `E_FAIL (0x80004005)`.

### How often did you encounter it so far?

Always

### Affected program

VirtualBox 6.0.2.4

### Download link

https://download.virtualbox.org/virtualbox/6.0.24/VirtualBox-6.0.24-139119-Win.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

It would be expect to be able to launch any VM in VirtualBox properly.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie Plus 1.11.2 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
this wil not work VM software usually needs drivers and sbie prevents loading of those

**Comment by sepcnt** [comment]
https://forums.virtualbox.org/viewtopic.php?p=275019 may help. Though outdated somehow...

**Comment by DavidXanatos** [comment]
As this is not something we can make work I'll close this
