### ISSUE TITLE
GOG Galaxy not working properly

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#3297]
### Describe what you noticed and did

1. Install and launch the latest version of [GOG Galaxy](https://www.gog.com/galaxy) (2.0.71.2)
2. Log into a GOG account
3. After about 10s after logging into a GOG account get an error message:
![goggalaxy1](https://github.com/sandboxie-plus/Sandboxie/assets/93145383/72772bea-ef63-4bed-92a1-3d0efd630663)
4. It turns out that **GalaxyCommunication.exe**, a process executed by a GOG service, gets multiplied ad infinitum what probably causes the app to close down
![goggalaxy0](https://github.com/sandboxie-plus/Sandboxie/assets/93145383/6e9cb1a4-3834-422e-ad05-4190a2a80120)

Tested with both green and yellow box. The green box approach has been described above. The yellow box cannot launch the GOG-related service and as a result it is not possible to log into GOG account via GOG Galaxy (the logging process hangs ad infinitum). Tested outside Sandboxie, works fine with no issues.

### How often did you encounter it so far?

Always

### Affected program

GOG Galaxy 2.0

### Download link

https://gog-cdn-fastly.gog.com/open/galaxy/client/2.0.71.2/setup_galaxy_2.0.71.2.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

It would be expected that **GalaxyCommunication.exe** process doesn't get multiplied ad infinitum.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie Plus 1.11.2 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by isaak654** [comment]
#1246

**Comment by DavidXanatos** [comment]
the underlying issue with service handling will be fixed in the next build to run gog a green compartment type box is required with the following options
```
UnrestrictedSCM=y
RunServicesAsSystem=y
NoSecurityIsolation=y
Template=RpcPortBindingsExt
```
I'll look if its possible to add workarounds to make this obsolete but that will take time as there are at least two more issues when trying to run in a yellow box
