### ISSUE TITLE
Windows Services Manager in Standard Applications

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#3298]
### Is your feature request related to a problem or use case?

It would be really useful to have a shortcut to Windows Services Manager in Run\Standard Applications.

### Describe the solution you'd like

A shortcut in Run\Standard Applications pointing at Windows Services Manager (services.msc).

**Comment by DavidXanatos** [comment]
why isn't it good enough to set a global custom run menu entry?
in my expirience the sandboxed services.msc is not super reliable to i would not want to add a hard coded link to it as this insinuates it working great.
