### ISSUE TITLE
How to generate UpdUtil.exe file?

### ISSUE THREAD

**Issue by t-anh** [sandboxie-plus/Sandboxie#3302]
### Describe what you noticed and did

I downloaded source code from tag v1.11.2 - latest release.
The use VS 2019 to build Sandboxie classic with Build Release + win32 and Release + win64.
After that, i right click on /install/SandboxieVS.nsi and select "Complie NSIS script".
But error occurred because \Bin\x64\SbieRelease\UpdUtil.exe file not found.
Please guide me to generate UpdUtil.exe file.

### Affected program

Not relevant

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.11.2

### Where is the program located?

Not relevant to my request.

### Expected behavior

Complie NSIS script successfully.

### What is your Windows edition and version?

Windows 10 pro 22H2 64 bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

ESET Endpoint Antivirus

### What version of Sandboxie are you running?

v1.11.2 / 5.66.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
File > Open Project/Solution > SandboxieTools > SandboxieTools.sln

**Comment by t-anh** [comment]
@offhub 
Thank for your quick answer.
I open SandboxieTools.sln and build with Release and x64 but the following error occurred.
> Identifier "SYSTEM_SUPPORTED_PROCESSOR_ARCHITECTURES_INFORMATION" undefined

Could you help me to fix this error?

**Comment by DavidXanatos** [comment]
You need a newer windows SDK i think the 22000 or newer

**Comment by t-anh** [comment]
Thanks you very much!
I have generated UpdUtil.exe successfully.
