### ISSUE TITLE
The professional version is priced too high

### ISSUE THREAD

**Issue by csznet** [sandboxie-plus/Sandboxie#3303]
### Is your feature request related to a problem or use case?

no

### Describe the solution you'd like

I am a student from a developing country with very little disposable income, but I still want to obtain a professional version credential. The official store sells credentials for a minimum price of 12 euros, which I cannot afford.

**Comment by ttimasdf** [comment]
“我是学生，白送我”。
丢人不？

**Comment by DavidXanatos** [comment]
You can email me to get a discount coupon.

**Comment by kokofixcomputers** [comment]
> You can email me to get a discount coupon.

Can i get one too?? @DavidXanatos if yes what is your email?

**Comment by DavidXanatos** [comment]
you can find my email on my website and in my github profile, and sure you can get a discount if you ask for one by email.
