### ISSUE TITLE
"Add 'Run Sandboxed' to the explorer context menu" option does not work in builds from github actions

### ISSUE THREAD

**Issue by mio-19** [sandboxie-plus/Sandboxie#3305]
### Describe what you noticed and did

0. Allow testsigning drivers
1. Enable the option
2. Click `Apply`
3. The option is disabled

### Affected program

"Not relevant

### Download link

"Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

-

### What is your Windows edition and version?

22621 pro

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

https://github.com/sandboxie-plus/Sandboxie/commit/555cb59a692f542ad080d956997b16024c777c40 https://github.com/sandboxie-plus/Sandboxie/actions/runs/6158762710

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### Is it a regression?

-

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

-

### Crash dump

-

### Trace log

-

### Sandboxie.ini configuration

```shell
-
```

**Comment by offhub** [comment]
Some features may not work because automated builds do not contain the required sig files. ([#1124](https://github.com/sandboxie-plus/Sandboxie/issues/1124#issuecomment-902194166),  [#1248](https://github.com/sandboxie-plus/Sandboxie/issues/1248#issuecomment-974654194))

**Comment by mio-19** [comment]
I found a class CSecretCheckBox in code indicated that this option has some hidden special state in Windows 11. I triggered that and `Run Sandboxed` is now in the right click menu. Note that I am using the classical context menu on Windows 11.

**Comment by mio-19** [comment]
SbieShellPkg.msix will not install if it is not signed
