### ISSUE TITLE
Wechat backup can't work

### ISSUE THREAD

**Issue by lue611** [sandboxie-plus/Sandboxie#3308]
### Describe what you noticed and did

WeChat's chat log backup function requires the phone and computer to be on the same network for it to work, but when I try to backup my chat logs, WeChat shows that it's not on the same network, as shown in the picture below (but in fact the two devices are connected to the same wireless network)
![Screenshot_2023-09-15-21-18-43-05](https://github.com/sandboxie-plus/Sandboxie/assets/43984245/18ecfd2c-48f6-45b3-85d2-988d8baf4ab8)
![image](https://github.com/sandboxie-plus/Sandboxie/assets/43984245/a1b1dd58-8557-40c8-8948-65cb2dbe605a)

### Affected program

Not relevant

### Download link

https://pc.weixin.qq.com/?lang=en_US

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

/

### What is your Windows edition and version?

win10 21H1

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

1.10.5

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by ZedG2** [comment]
运行 `wf.msc` ，在入站规则里对 `C:\Sandbox\<SandboxName>\WeChat\drive\C\Program Files (x86)\Tencent\WeChat\WeChat.exe` 增加两条规则，分别允许公用网络和专用网络。

**Comment by chengnan049** [comment]
And https://www.chiphell.com/thread-2578668-1-1.html
