### ISSUE TITLE
The new version is not compatible with AliWangWang

### ISSUE THREAD

**Issue by asbai** [sandboxie-plus/Sandboxie#3310]
### Describe what you noticed and did

1. download "https://download.alicdn.com/wangwang/AliIM_taobao_(10.01.03C).exe".
2. Install and start it in a sandbox.

### How often did you encounter it so far?

everytime

### Affected program

AliWangWang

### Download link

https://download.alicdn.com/wangwang/AliIM_taobao_(10.01.03C).exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Application start normally.

### What is your Windows edition and version?

Win7 x64 64bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

none

### What version of Sandboxie are you running?

5.66.2

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### Is it a regression?

Since 5.65.5，and It works fine on version 5.64.8

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
It's probably related to this fix. https://github.com/sandboxie-plus/Sandboxie/issues/2734#issuecomment-1637021243
