### ISSUE TITLE
Alibaba DingTalk 7.x crashes in SbieDll.dll

### ISSUE THREAD

**Issue by ttimasdf** [sandboxie-plus/Sandboxie#3312]
### Describe what you noticed and did

DingTalk 7.0 crash when running in Sandboxie 1.10.5

This issue is likely caused by a common component in Alibaba products, which may related to #3310. 

the crash report file `C:\Sandbox\<username>\<sandbox_name>\drive\C\Program Files (x86)\DingDing\main\current\DingTalk.RPT
` generated by dingtalk error reporter:

```
//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address: 550E809A 01:0005709A C:\Program Files\Sandboxie-Plus\SbieDll.dll

Registers:
EAX:00000000
EBX:FBAD0C88
ECX:0000000E
EDX:FB891188
ESI:FB891188
EDI:00000020
CS:EIP:0033:550E809A
SS:ESP:002B:EEFFECA0 EBP:00000000
DS:002B ES:002B FS:0053 GS:002B
Flags:00010246

Call stack:
Address   Frame     Logical addr Module
Get Call statck by stackwalk64 
```

### How often did you encounter it so far?

every time on application launch

### Affected program

DingTalk 7.0.11.3139102

### Download link

https://dtapp-pub.dingtalk.com/dingtalk-desktop/win_installer/Release/DingTalk_v7.0.11.3139102.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

The program should start normally without issue.

### What is your Windows edition and version?

Windows 11 Pro 22H2 64 bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Kaspersky Free Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus 1.10.5 64 bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=7zipShellEx
Template=Kaspersky
Template=Listary
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan
Template=OfficeClickToRun
DefaultBox=DefaultBox
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
SandboxieLogon=y
EditAdminOnly=y
StartRunAlertDenied=y
MonitorStackTrace=n


[UserSettings_053C014B]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_UserName=<username>
SbieCtrl_NextUpdateCheck=1694497524
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=y
SbieCtrl_AddQuickLaunchIcon=y
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=295,316,1650,937
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_BoxExpandedView=MSOffice
SbieCtrl_HideMessage=2205,GdiInit.00000001
#BoxGrouping=:<box_list>


[Ding]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00fd00,ttl,6
Template=RpcPortBindingsExt
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=OfficeClickToRun
Template=OfficeLicensing
Template=OpenProtectedStorage
ConfigLevel=10
NoSecurityIsolation=y
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
BoxNameTitle=-
OpenCredentials=y
StartProgram="C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe" /service
NotifyDirectDiskAccess=y
NotifyProcessAccessDenied=y
RpcMgmtSetComTimeout=n
OpenSamEndpoint=y
OpenLsaEndpoint=y
OpenProtectedStorage=y
LingerProcess=OfficeClickToRun.exe
LingerProcess=smartscreen.exe
OpenPipePath=WINWORD.EXE,*.doc
OpenPipePath=WINWORD.EXE,*.docx
OpenPipePath=EXCEL.EXE,*.xls
OpenPipePath=EXCEL.EXE,*.xlsx
OpenPipePath=POWERPNT.EXE,*.ppt
OpenPipePath=POWERPNT.EXE,*.pptx
RunCommand=Power&Shell|C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
NormalFilePath=C:\Users\<username>\AppData\Local\Temp
```

**Comment by ttimasdf** [comment]
I didn't notice any crash dump .dmp file generated as the application launch the CrashDumper.exe automatically after crash and make some network requests. Trace log shows it iterating the .pdb files, likely collecting its own diagnostic logs.

**Comment by DavidXanatos** [comment]
very likely hence i'll mark this as fixed in next build like the other issue

**Comment by ttimasdf** [comment]
Confirming v1.11.4 resolved this issue
