### ISSUE TITLE
SandBoxie+ (Always on Top) & (Background Process-PopUp)

### ISSUE THREAD

**Issue by PARAViRTUALiZATiON** [sandboxie-plus/Sandboxie#3320]
### Describe what you noticed:

If a Programwindow inside of the SandBoxie+ Container force the same Setting as SandBoxie+ (Always on Top), it can stay over the SandBoxie+ UI. This as possible shouldn't be that Case, Because if this Program is - as for example - something dangerous, it could stop the User for interact with SandBoxie+ or the System to stop or close this Process, maybe until a sucsessful System-Shutdown.

> Especially and also then, if it would open many Processes in the Backgroud at a Time, like PopUp's, this could also complicate or block any normal Interaction - with SandBoxie+.

#

### Expected Behavior:

A Process in a Container of SandBoxie+ should be able to stay over any other inside it's Containment, but not over the SandBoxie+ UI.

**Comment by DavidXanatos** [comment]
This is why we have the "panic button" terminale all boxes hot key.
We cannot reliably prevent a sandboxed process from requesting to be (Always on Top), we could add a user mode filtering to prevent this, but an application aware of sandboxie could always issue a direkt syscall to the Win32k driver and bypass that filtering.

**Comment by DavidXanatos** [comment]
I was thinking we could add an other hot key to bringt the sandman UI as top most in front, that would allow to solve such situations without killing everything
