### ISSUE TITLE
Error 1719. Windows Installer service could not be accessed

### ISSUE THREAD

**Issue by 0xDEADFED5** [sandboxie-plus/Sandboxie#3322]
### Describe what you noticed and did

![Clipboard 1](https://github.com/sandboxie-plus/Sandboxie/assets/39973293/384b4e26-fedb-48cd-ad86-b03c438dc65a)

### How often did you encounter it so far?

each time i try to install Acrobat Pro

### Affected program

Adobe Acrobat Pro

### Download link

https://www.adobe.com/acrobat/free-trial-download.html

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

installation

### What is your Windows edition and version?

Windows 11 Education 21H2 22000.2416

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft

### What version of Sandboxie are you running?

1.11.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by 0xDEADFED5** [comment]
also for Adobe Acrobat DC

**Comment by 0xDEADFED5** [comment]
shit, just found

MsiInstallerExemptions=y

**Comment by isaak654** [comment]
#3322

**Comment by isaak654** [comment]
#2699
