### ISSUE TITLE
Bug on Update Checker

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#333]
![image](https://user-images.githubusercontent.com/133706/103934629-f7573d80-512d-11eb-9580-f260b147c5d3.png)

**Comment by DavidXanatos** [comment]
So you managed to check for updates in the very minute between me finishing uploading the new build to github and updating the update data on the server, you win a cookie ;)

**Comment by stdedos** [comment]
I DON'T SEE MY COOKIE 😀

Isn't it bug in the update-checker-logic, however?
How does it compare 5.45.2 and 5.46.0 and it decides `5.45.2 > 5.46.0`? 😕

**Comment by DavidXanatos** [comment]
For simplicity and in case the version format may change it always assumes the version on server is the latest so if the strings don't match it says there is an update.
I'm going to get some smarter server side script that would not do such mistakes but I haven't head time yet to do that.

Cookies are out, hers a medal: 🥇

**Comment by stdedos** [comment]
As long as you are aware of it, I'm fine 😀

You can use this ticket as a placeholder "until you find time" :tm:

**Comment by stdedos** [comment]
I DIDN'T MANAGE TO REPLICATE IT 😛
