### ISSUE TITLE
SSL on update check website broken cannot check for updates.

### ISSUE THREAD

**Issue by thakyZ** [sandboxie-plus/Sandboxie#3333]
### Describe what you noticed and did

So upon opening the application, I get a message from Sandboxie-Plus that reads: "Failed to check for updates, error: server not reachable."
To go and fix this issue, I did the following:
1. Went to the update url which I got from this line: [OnlineUpdater.cpp#L13](https://github.com/sandboxie-plus/Sandboxie/blob/9cb2462b043cbc0b73e7e6805a58e3cfce511b80/SandboxiePlus/SandMan/OnlineUpdater.cpp#L136C12-L136C48)
2. Noticed my browser returned with an error "SSL_ERROR_RX_RECORD_TOO_LONG"
3. Removed the `s` from https and got a page from my ISP (Comcast):
![image](https://github.com/sandboxie-plus/Sandboxie/assets/950594/482db1f8-3620-4030-a617-90c433989856)
4. After pressing "Proceed Anyway" the update checker started working until whatever on the ISP side or a cookie ended up making it happen again.

### How often did you encounter it so far?

Whever I launch or check for updates until fixed, and then occurs eventually again.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

My ISP should not be marking your website as a potential risk, I don't know how to go about fixing it as I have not personally encountered it on my servers.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender Antivirus, Malware Bytes (free) (not constantly running)

### What version of Sandboxie are you running?

Sandboxie-Plus v1.11.2 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by offhub** [comment]
Turn off the Advanced Security feature or report it to Comcast.
https://www.xfinity.com/support/articles/report-blocked-website
