### ISSUE TITLE
Add a command line switch to minimize SandMan to the system tray

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#3335]
### Is your feature request related to a problem or use case?

https://forum.xanasoft.com/viewtopic.php?f=12&p=1559

### Describe the solution you'd like

Add a new command line switch to minimize Sandboxie Plus' GUI to the system tray.

Note that this already exists for Sandboxie Classic's GUI: https://github.com/sandboxie-plus/Sandboxie/blob/9cb2462b043cbc0b73e7e6805a58e3cfce511b80/Sandboxie/apps/start/start.cpp#L581-L589

`/nosbiectrl` is documented in [StartCommandLine.md](https://github.com/sandboxie-plus/sandboxie-docs/blob/a51191d53b562027e42c60c59a100f1e75a6c088/Content/StartCommandLine.md?plain=1#L41-L44) page, but currently there isn't anything about SandMan.

**Comment by DavidXanatos** [comment]
here is in fact such a command line argument "...\SandMan.exe -autorun" will start sandman UI minimized to tray.

**Comment by isaak654** [comment]
Ok, but I don't see how it compares to `"C:\Program Files\Sandboxie-Plus\Start.exe" /nosbiectrl notepad.exe`
Is there an alternative command to `/nosbiectrl` for SandMan?

**Comment by DavidXanatos** [comment]
I don't think /nosbiectrl does anything, i just checked in the code it sets dont_start_sbie_ctrl but that variable is not evaluated anyware
also the original user asked for a way to start sandman in the tray and this is achieved by  "...\SandMan.exe -autorun"
