### ISSUE TITLE
Install Classic and New UI side-by-side

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#334]
I would be willing to try and use the new UI, but I'd like to have some transitional period where I use both of them. Why is it complicated to have both of them installed (if not running) at the same time?

_With literally no understanding of the code_, it feels to me that the UI is simply a client to the Driver (server); so there shouldn't be a problem using different UIs against (the same, probably) Driver.

**Comment by DavidXanatos** [comment]
Actually when you install the Plus package you get sbiectrl.exe installed alongside just that no startmenu entries are created for it.
So if you want you can use it instead or use booth, that's no problem.

**Comment by stdedos** [comment]
Is it complicated to have an optional shortcut for `sbiectrl.exe` (default-off)?

"If it's not on the Start Menu search, it's nowhere"

**Comment by DavidXanatos** [comment]
Go to: C:\ProgramData\Microsoft\Windows\Start Menu\Sandboxpe-Plus\ and create whatever links you need, they won't be removed when you install a new version, so its a one time work.

**Comment by stdedos** [comment]
I meant to also have the automation behind it.
I guess you don't want to support it; no worries.

It seems I managed to somehow to install it and I have everything too.
If someone is looking for the shortcuts, here's all of them: [Sandboxie.zip](https://github.com/sandboxie-plus/Sandboxie/files/5783639/Sandboxie.zip)
