### ISSUE TITLE
If a program is run on RAM and Encrypted boxes when the sandbox root folder is not present, the programs will not run

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3349]
### Describe what you noticed and did

If a program is run on RAM and Encrypted boxes when the sandbox root is not present, the programs will not run.

### Ram Box:

1. Create a Ram Box
2. Rename BoxRootFolder or set `FileRootPath` to different folder (e.g. C:\Sandbox to C:\Sandbox_)
3. Run a program in the sandbox
4. 
```
SBIE2230 Failed to mount root for New_Box [xx / yy]
SBIE2335 Initialization failed for process Start.exe [xx / yy]
```

**Result**: Sandboxie creates an empty file with the box name instead of the junction folder. (e.g. C:\Sandbox\user\New_Box)

### Encrypted Box:

1. Create an Encrypted Box
2. Rename BoxRootFolder or set `FileRootPath` to different folder (e.g. C:\Sandbox to C:\Sandbox_)
3. Run a program in the sandbox
4. 
```                                                                   
SBIE2241 Box image file C:\Sandbox\user\New_Box.box could not be opened   
```

**Result**: Sandboxie does not create any folders.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

If the box root folder does not exist when the program is run on boxes with these settings enabled, folder linking must be performed after these folders are created.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.3448)

### In which Windows account you have this problem?

A Microsoft account (Administrator)., An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.11.3 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In an encrypted sandbox (black sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
I ant reproduce this one, also the Encrypted Box deletes the folder when it unmounts to not sure how you renamed it? mounting manually renaming and then trying to run something?

**Comment by offhub** [comment]
Let's assume that the `C:\Sandbox` folder is set as the root, and that this folder has not yet been created. In this situation, when we try to run the Ram/Encrypted boxes that we have previously configured, we get the above errors.

**Comment by DavidXanatos** [comment]
aaa i see you mean the folder which contains the sandbox root folder,ok wil check this out asap

**Comment by DavidXanatos** [comment]
Rambox fixed,
encrypted box, well that works as expected, when you move the box image out of the way if can not mount it, and we don't have a way to find it.

**Comment by offhub** [comment]
Encrypted Box:

1. If there is no matching .box file when we want to mount the box image, a password window opens to create a new .box file.
   - After this stage, a new .box file cannot be created because the root folder does not exist.
   - If the root folder does not exist, it should be created first.
2. However, the window to mount the box image opens as if the .box file had been created successfully, and when the password is entered it gives the error: `SBIE2241 Box image file C:\Sandbox\user\New_Box.box could not be opened   `
