### ISSUE TITLE
Undelete Feature

### ISSUE THREAD

**Issue by gjf** [sandboxie-plus/Sandboxie#335]
Is it possible to implement undelete feature?
I mean all files those are deleting in sandbox in fact will remain at place so it would be possible to investigate them after all process in sandbox will be finished?

**Comment by DavidXanatos** [comment]
In fact that's on my todo and it should be reasonably easy to implement.

**Comment by gjf** [comment]
I remember that - we have discussed it several months ago :)
So - just kind reminder.

**Comment by DavidXanatos** [comment]
since we have a thread for that already i'll close this one
