### ISSUE TITLE
Lock All Encrypted Boxes should only terminate programs on encrypted boxes

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3350]
### Describe what you noticed and did

Locking all encrypted boxes should only terminate programs on encrypted boxes

1. Run a program in yellow box
2. Run a program in black box
3. Sandbox Menu > Lock All Encrypted Boxes
4. Programs on all boxes will be terminated, whether they are running on the encrypted box or not.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Locking all encrypted boxes shouldn't terminate programs running on non-encrypted boxes.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.3448)

### In which Windows account you have this problem?

A Microsoft account (Administrator)., An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.11.3 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In an encrypted sandbox (black sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by wilders-soccerfan** [comment]
I also see all boxes terminated (with or without Step 2). Win7x64SP1 and sbie v1.11.3.

**Comment by DavidXanatos** [comment]
that's intended behavior, but I see how splitting that might be useful
