### ISSUE TITLE
SpotX batch file doesn't run sandboxed

### ISSUE THREAD

**Issue by MathewJake365** [sandboxie-plus/Sandboxie#3352]
### Describe what you noticed and did

1. Right click on "Install_New_theme.bat" and click "Run Sandboxed".
2. Click OK in Sandboxie-Plus - Run Sandboxed window.
3. The below error message shows in a [#] cmd.exe [#] window, 

![Screenshot 2023-10-01 192659](https://github.com/sandboxie-plus/Sandboxie/assets/87035602/10d5fcc2-ca27-45cc-86bb-6c0f5e5ddac7)

4. Press a key, and the window closes.

### How often did you encounter it so far?

Every time I run this file.

### Affected program

SpotX 1.8 - Install_New_theme.bat

### Download link

https://github.com/SpotX-Official/SpotX/releases/download/1.8/Install_New_theme.bat

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

It should run in Windows Powershell and complete patching the Spotify for Windows desktop client.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Bitdefender Total Security

### What version of Sandboxie are you running?

Sandboxie Plus 1.11.3 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No.

**Comment by offhub** [comment]
(to install) Use `DropConHostIntegrity=y` [***](#678) or (for Spotify) `Application Compartment` box.

**Comment by MathewJake365** [comment]
> (to install) Use `DropConHostIntegrity=y` #678 or (for Spotify) `Application Compartment` box.

Thank you. Adding `DropConHostIntegrity=y` to the Edit ini Section in the Box Options fixed this issue.

**Comment by e-t-l** [comment]
@MathewJake365 Could you share your full .ini for the sandbox that Spotify is in? (Is Spotify.exe itself installed inside the sandbox or outside of it?)

Because I'm still getting this issue #3285 when I try to run Spotify right after installing it with SpotX and I'm trying to figure out why
