### ISSUE TITLE
Internet Download Manager - Starts itself inside of SB!

### ISSUE THREAD

**Issue by Dean-Corso** [sandboxie-plus/Sandboxie#3353]
### Describe what you noticed and did

Internet Download Manager is trying to load itself inside of Sandboxie since the version Sandboxie-Classic-x64-v5.65.5. The last version I used before was Sandboxie-Classic-x64-v5.64.8 and this is not loading IDM inside of Sandboxie (correctly). It even starts to run IDM inside of SB when its already running outside. Now I switched back to last working version I did use Sandboxie-Classic-x64-v5.64.8. The higher versions I was trying to use was Sandboxie-Classic-x64-v5.65.5, Sandboxie-Classic-x64-v5.66.2 & Sandboxie-Classic-x64-v5.66.3 which having that new problem.

Info: You have to install the IDM Integration Module for your browser what does send download info's to the main idm.exe application. Just exit idm.exe when its running and in browser you can deactivate & activate the AddOn / Extension which is then trying to get a connection to the main idm app to verify whether it's running or not. When it's not running then it will try to start it and here the problem happens since version 5.65.5.

### How often did you encounter it so far?

Everyday since using version 5.65.5

### Affected program

Internet Download Manager 6.41 (latest)

### Download link

https://www.internetdownloadmanager.com/download.html

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

The Internet Download Manager (idm.exe) should just run only outside of Sandboxie. Even when its not running it should just get started outside of a Sandboxie by itself and never start inside of SB (only if I force / want it).

### What is your Windows edition and version?

Windows 10 22H2 64 bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.64.8 <-- switched back to working version

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### Is it a regression?

Sandboxie-Classic-x64-v5.65.5

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by offhub** [comment]
> The Internet Download Manager (idm.exe) should just run only outside of Sandboxie. Even when its not running it should just get started outside of a Sandboxie by itself and never start inside of SB (only if I force / want it).

> [!IMPORTANT]
Make sure no IDM applications are running in the sandbox.

`BreakoutProcess=IDMMsgHost.exe`

**Comment by Dean-Corso** [comment]
Hi @offhub,

I tried adding the 2 new parameters into my SB XY config but this doesn't work and IDM gets started inside of SB and after few seconds IDM in SB does exit with this message of SB...

`SBIE2205 Dienst nicht implementiert: NtSaveKey`

When using the older version Sandboxie-Classic-x64-v5.64.8 then it does start IDM outside of SB but also this gets closed after few seconds. I did notice that there is a problem when using VPN service AddOn / Extension in browser in combination with a installed IDM browser AddOn / Extension. Some VPN tool don't work together with IDM AddOn (Chromium based browser) which are working in Firefox. So when I have enabled VPN AddOn and disable & enable IDM AddOn in browser then the IDM icon is showing a disabled icon and is now loading the IDM.exe inside of SB (latest versions as I said already) and exit it again. In case of older version it starts it outside or does exit the outside running IDM process. All in all in both cases its not working good and as expected.

Example: When IDM is running outside (normal case / starts with Windows) and I start my browser in SB then everything is working fine so far. When I start VPN AddOn to browse then all is still working good so far but not very long (+/- hour etc) and then the IDM AddOn is changing the icon stratus from normal / Ok to disabled status and when I now disable / enable the IDM AddOn in about:addons then its still showing the disabled icon state but its now trying to start the IDM process again (inside of SB in latest versions) and then the error happens as I told above. Only thing what I can do is not using VPN.

Do you have some clue how to handle that problem to prevent it? So there are 2 problems.

- IDM should not start inside of SB (like the older version) what happens in latest versions
- IDM AddOn in browser running in SB should not loose the connection to the outside main IDM process to run into a disable state where I can not enable it again when I keep running the VPN AddOn. Thank you.

**Comment by Dean-Corso** [comment]
No. Its running and working but when the IDM icon does change to disabled (as I told already) then the ABG is not showing anymore of course and I need to enable / disable the AddOn and then the problem started to run IDM inside of SB. Somehow pretty bad that behavior. SB is trying to run IDM, IDMIntegrator64 & IDMMsgHost inside and IDM does exit thren with the error I did post SBIE2205 and the other 2 executable keep running in SB. So in normal only IDM.exe should run only and the other 2 exe files are not needed to use because the ABG (download window of IDM / context menu) is working and sending the information's to the main IDM application. But in case of those trouble (I told etc) the other 2 apps getting started. So the questions is when everything is working fine all all browsers and just running IDM.exe only why does it then happen that the ABG suddenly stops working as before (whats the reason for that?) and getting into a disabled status (icon) and is loading then the DMIntegrator64 & IDMMsgHost & IDM.exe inside of SB what then runs into the SBIE2205 error. Somehow its pretty illogical.

**Comment by offhub** [comment]
Interesting... When I first installed the IDM application, it was starting in the sandbox, but now it starts outside with or without the above settings.

On the test system, IDM.exe is launched by svchost.exe. On your system, it is probably started by the browser and therefore starts in the sandbox. Maybe it's caused by a setting in your configuration.

If you share your Sandboxie configuration, I can test with your settings.

Also try these settings:
```
BreakoutProcess=IDMMsgHost.exe
BreakoutProcess=IDMIntegrator64.exe
BreakoutProcess=IDM.exe
```
If you are getting the SBIE2205 error without BreakoutProcess settings, it probably means that the connection between IDM and the browser extension cannot be established. It may also be a problem caused by the VPN extension.

Do these two extensions continue to work properly even if they are used together for a long time outside the sandbox?

**Comment by Dean-Corso** [comment]
Hi again,

so I tried adding your 3 lines into my TEST Sandboxie but this just started the IDM processes right away in this Sandboxie without running any VPN AddOn. I also that error again each time (NtSaveKey). In Taskmanager I can see the leftover of IDMIntegrator64.exe which still runs in this SB and when I terminate this app then the IDM.exe does start again inside of this SB also it runs already outside. Somehow those BreakoutProcess commands do not work to prevent starting the apps inside of SB or for what are the command for?

All in all this problem also happens without VPN AddOn. There must be a connection / communication problem of IDM extension inside of browser to the outside running IDM process. So if they don't have a working communication then the browser extension just starts the IDM / IDMIntegrator64 / IDMMsgHost processes inside of SB = Wrong. So this happens all the time in a loop again & again and the only thing what I can do to make it work is to disable the AddOn then termniate all IDM processes and start the main IDM.exe process normally from outside new. Now I start the browser in SB new too and then it works for a while but this help (workaround) to make the browser in SB working normally to get IDM connection to main IDM outside working etc. So that pretty bad of course. When using the older SB version then this does not happen (staring IDM inside of SB).

The two AddOn's just working together for a while (+/- hour etc) and then something happens with IDM in browser (loosing connection to IDM outside etc) and the icon of IDM AddOn does change to disabled state (X cross) and can't be used anymore. In this case I have to disable VPN connection and disable & enable IDM AddOn and then IDM AddOn works again (X cross removed). But also without that VPN AddOn the problem does occur sooner or later.

So my SB config for my boxes are same when using that older & latest SB versions.

```
[GlobalSettings]

Template=Edge_Fix
Template=Edge_Win11Fix
Template=Windows10CoreUI
Template=FireFix_for_Win7
Template=RpcPortBindings
Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=InternetDownloadManager
Template=OfficeLicensing

[BOX]

Enabled=y
ConfigLevel=10
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
```

**Comment by offhub** [comment]
Are there any IDM related files in the sandbox folder? (in C:\Sandbox\user\BOX\drive\C\Program Files (x86)\Internet Download Manager\\)

**Comment by Dean-Corso** [comment]
So far I can see there are not files / path of IDM inside of the SB. There is just "...\drive\C\Program Files\" folder inside. So to answer your question, No files.

**Comment by offhub** [comment]
1. Add to your config `BreakoutProcess=ping.exe`
2. Run sandboxed CMD
3. Run `ping 1.1.1.1`
4. Does ping command run outside the sandbox?

**Comment by wilders-soccerfan** [comment]
Could this issue have something to do with the fact that template support
 for Internet Download Manager has been removed since v5.65.1?

**Comment by offhub** [comment]
I don't think so, it works just fine without that template in the virtual machine.

**Comment by Dean-Corso** [comment]
> @offhub
    Add to your config BreakoutProcess=ping.exe
    Run sandboxed CMD
    Run ping 1.1.1.1
    Does ping command run outside the sandbox?

I did run CMD inside of SB and did execute the ping command and the Ping.exe gets executed inside of this SB not outside.

**Comment by offhub** [comment]
Does `BreakoutProcess=ping.exe` work in version 5.64.8?

**Comment by Dean-Corso** [comment]
Ok I tried both versions older & latest adding that command BreakoutProcess=ping.exe to my SBox XY and reload the configuration and in both cases the PING.EXE process gets started inside of this SBox where the CMD process got started. The command "BreakoutProcess" seems really just not to work with Sandboxie Classic version. Does it work for you?

**Comment by offhub** [comment]
Yes, it works.

Do you reload the configuration after making changes to it?

**Comment by Dean-Corso** [comment]
Hi again,

ok wait, now I see I made a mistake when testing the BreakoutProcess= command in my SBox. I just did add this command on a wrong SBox (similar name). Sorry @offhub my fault. Now I did make the tests again with the older & latest SB adding that command BreakoutProcess=ping.exe and it works and the ping.exe gets executed outside if SB in both versions. The only different I could recognize was this...

```
BreakoutProcess=ping.exe / Run CMD.exe inside of SB / entering ping 1.1.1.1
------------------------------------------------------------------------------------
Sandboxie-Classic-x64-v5.64.8: ping.exe gets executed outside of SB and ping info getting piped into
 CMD.exe process which is running inside of SBox.

Sandboxie-Classic-x64-v5.66.3: ping.exe gets executed outside of SB and a new CMD.exe process 
gets started also outside of SB where the ping results are shown.
```
...so that are the different I can see so far. No idea why also another CMD process is getting started outside. Anyway, I will check this now again out with IDM process and send another feedback after.

**Comment by Dean-Corso** [comment]
Ok I'm back with some new results. I did test now again the latest SB version "Sandboxie-Classic-x64-v5.66.3" and just did add the "BreakoutProcess=IDM.exe" but this does not prevent loading IDM.exe inside of the SB another time = fails. Then I tried adding all 3 process of IDM...
```
BreakoutProcess=IDM.exe
BreakoutProcess=IDMIntegrator64
BreakoutProcess=IDMMsgHost.exe
```
...and this works to prevent anything to start inside of the SB = Good so far.

The only thing what is still bad is that when using VPN AddOn (connected) and if I now disable IDM in AddOn menu and enable it back right away (switch on/off) then IDM icon returns in disabled state (IDM integration Module in right mouse context menu is also gone) and there is no chance to make it work to enable it SO LONG I keep connected with the VPN AddOn. Now I just unconnected the connection to VPN (Stop) then right away the IDM icon does change the status from disable to enabled = working again. That's the only disadvantage when using IDM AddOn + connected VPN AddOn. No idea why this happens but its a little bad to de-connect VPN each time when IDM goes into disabled state and you wanna use it.

**Comment by Dean-Corso** [comment]
PS: I got just a little tiny question to the 2 Sandboxie versions classic & plus. I was always using the classic version and would like to know whether I could upgrade to SB Plus and keep my created Sandboxies +10 alive / same without to get them deleted or anything like that. Just wanna know whether it is working same and sure as installing classic version (upgrade to higher or lower versions) when installing the Plus version etc. Or does it mean I have to total uninstall SB Classic first and installing Plus new? In this case I have to backup some boxes. Otherwise makes it any better sense to use the Plus version compared to Classic? All I can see & read is that the core is same and just the GUI in plus version is more modern and expanded. What do you say?

**Comment by offhub** [comment]
1. Backup `C:\Windows\Sandboxie.ini` and `C:\Sandbox` folder.
2. Uninstall Sandboxie Classic (select YES to keep your config) and then reboot.
![vmconnect_20231010_135711_384](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/eca48a8d-a765-4832-bba4-b5c7de89912e)
4. Install Sandboxie Plus and then reboot.

As well as being more modern, the Plus interface has sections that allow you to use new features easily. Even if you have enabled some new features from the configuration file, the Classic interface does not have the menus/windows to allow you to use them properly.

There are also different view modes available in the Plus interface. One of these is the "`Vintage View (like SbieCtrl)`" mode. In this mode you can use the interface in a view similar to the classic view (see links below).

https://sandboxie-plus.github.io/sandboxie-docs/Content/PlusMigrationGuide.html
https://sandboxie-plus.com/feature-comparison/

**Comment by DavidXanatos** [comment]
so whats the final status? do we need to fix anything or is all ok now?
