### ISSUE TITLE
Process Restrictions enable/disable not working correctly

### ISSUE THREAD

**Issue by a82kd** [sandboxie-plus/Sandboxie#3355]
### Describe what you noticed and did

1. Created a new sandbox with standard template (but affects other templates as well)
2. Create two process restrictions. E.g. just use to dummy names such as test.exe and test2.exe.
3. Both items should be checked when created. Now remove both checkmarks and click "Apply".
--> one of them is checked again. And its not possible to deactivate both rules. One gets always checked again after hitting the apply button.
--> also if you toggle block/allow on a rule, sometimes a second rule get created.

### How often did you encounter it so far?

always

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Disable all process restrictions

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

tried to times, regular pc with Norton, and VM with Defender, happens in both

### What version of Sandboxie are you running?

1.11.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
you mean on this page: 
![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/15d0e094-30f5-4538-81c0-d1d6171462d6)
to me its works fin cant reprodue it

**Comment by a82kd** [comment]
Ah, no, Network Options > Process Restrictions

**Comment by offhub** [comment]
While all programs in the `<InternetAccessDisabled>` group should appear unchecked, only the first program appears unchecked.

![sbieiadchk01](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/e6baace4-e5b9-4720-8ac8-772ee0c1bb7d)

```
ProcessGroup=<InternetAccessDisabled>,test1.exe
ProcessGroup=<InternetAccessDisabled>,test2.exe,test3.exe
ProcessGroup=<InternetAccessDisabled>,test4.exe,test5.exe,test6.exe
```
