### ISSUE TITLE
Dark Mode URL color

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#336]
Maybe prefer a different color for URLs in Dark Mode? (e.g. `#0033cc`, https://www.color-hex.com/color/0033cc)

![Screenshot-SandMan_2021-01-07_21-30-04](https://user-images.githubusercontent.com/133706/103937624-b103dd80-5131-11eb-9c52-ba7c68ea79eb.png)

**Comment by DavidXanatos** [comment]
blue on black is not very readable, i kind of like the orange, its so hard to miss ;)

**Comment by stdedos** [comment]
I thought you wanted to stay true to the blue 😉 

Whatever rocks your boat 😀

**Comment by stdedos** [comment]
You forgot to mention this in the changelog notes / close it.

Let me help you 😀
