### ISSUE TITLE
Games launched from sandbox cannot use dx.graphic.3d for screenshots. Is this not supported?

### ISSUE THREAD

**Issue by 769687520** [sandboxie-plus/Sandboxie#3360]
### Is your feature request related to a problem or use case?

It's still because I don't know how to set it up, and I still can't take screenshots of dx.graphic.3

### Describe the solution you'd like

I hope there can be a solution

**Comment by isaak654** [comment]
It is recommended to provide a link to a free trial version, a list of reproducible steps, the sandbox type where you're having this issue, Windows version, Sandboxie version, the presence of security software or security settings.

**Comment by isaak654** [comment]
It is advisable to provide a link to a free trial version, a list of reproducible steps, the sandbox type where you're having this issue, Windows version, Sandboxie version, the presence of security software or security settings.

**Comment by 769687520** [comment]
His feedback to me is that the window is protected, making it impossible to take screenshots. I have tried many games and have been prompted like this, how to set the sandbox to remove protection!

**Comment by 769687520** [comment]
Sandboxiev1.11.3
