### ISSUE TITLE
Missing Smartscreen warnings in Sandboxie 5.46.4 (post #3)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#338]
**Problem:** A sandboxed Microsoft edge session crashed in Sandboxie Classic 5.46.0_x64 with Template_Edge_Profile_DirectAccess enabled in a clean sandbox, after running multiple malicious tests available on the MS site: https://demo.smartscreen.msft.net/

Windows 10 2004 x64

**Comment by DavidXanatos** [comment]
Hi,

Thanks, I have evaluated the dump and found the cause, will be fixed in the
next build.

Cheers
David

Am Do., 7. Jan. 2021 um 21:40 Uhr schrieb isaak654 <notifications@github.com

**Comment by isaak654** [comment]
> 
> Hi, Thanks, I have evaluated the dump and found the cause, will be fixed in the next build. Cheers David

@DavidXanatos 
Great, I hope that it will fix Smartscreen warnings too, because they are missing inside sandboxes.

For example this warning appears when you visit an insecure website in an unsandboxed Edge session with Smartscreen enabled, but not in a sandboxed Edge session:

<img title="smartscreen warning" src="https://i.ibb.co/tXsGjx8/smartscreen.png">

Could you provide that in all sandboxed Edge sessions?

**Comment by DavidXanatos** [comment]
@isaak654 no I don't think so the non functional smart screen is something probably unrelated, will have to debug it.

Although stuff like smart screen is one of the first things I thoroughly disable an all my systems, so first I'll need to repair it so that it works at least outside the sandbox LOL

**Comment by isaak654** [comment]
@DavidXanatos In the meantime I've received additional crashdumps, always related to SbieSvc:
https://mega.nz/file/Wh0EjDQB#fjQRHCldEiiGHOH4Z2LC7ddQoqCg-UmYZGViooGePog
https://mega.nz/file/mpsEAJCD#bfqfcgBbISNwAfU8FyPRkqgMLd0npq16I9J_rTUoIPQ

**Comment by isaak654** [comment]
Crash issue was fixed in 5.46.1, now the remaining issue is about Smartscreen warnings not being displayed in the sandboxes.

**Comment by isaak654** [comment]
Crash issue was fixed in 5.46.1, so I changed the title to reflect the remaining issue.

**Comment by isaak654** [comment]
Missing Smartscreen support was fixed in Classic 5.48.5 and 5.49.0

**Comment by bjm234** [comment]
> Missing Smartscreen support was fixed in Classic 5.48.5 and 5.49.0
SmartScreen works okay with https://demo.smartscreen.msft.net/
Thanks @isaak654
