### ISSUE TITLE
Allow turning off hotkeys, and make the key configurable 

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#3399]
### Is your feature request related to a problem or use case?

Your hotkeys announced in todays beta V1.12.0 are an excellent idea (and I have already created a toggle shortcut for forcing). 

But I have already created a number of global hotkeys. mostly using Directory Opus.  I really don't want conflicts with them.  

### Describe the solution you'd like

Could you please:
* Make each hotkey optional, so that it can be turned off.
* If it's not too complicated, could the key combination used be configurable.

I don't install betas, so perhaps you have already implemented one or both of these requests.  I couldn't find anything about hotkeys on the websites.

**Comment by DavidXanatos** [comment]
all hot keys are off by default, and all can be changed in the settings

**Comment by NotepadPlusUser** [comment]
Thanks very much, David,  Full consideration for users' individual ways of working — as always.
