### ISSUE TITLE
Just a quick Thank You to Dev team.....

### ISSUE THREAD

**Issue by BurntDog** [sandboxie-plus/Sandboxie#340]
I have been using Sandboxie for many years (feels like a decade or more) now and just wanted to say, Thank you very much
for keeping this alive and now offering it for free and opensource. Your work is very appreciated and helps many users stay safe.

Thank you very much.
BurntDog

old names AKA"
Cyclo-Techtwister
DiGgErx

**Comment by rugabunda** [comment]
Huge thanks! You guys are doing an excellent job, thank you for everything you do!

**Comment by HikariWS** [comment]
I'm supporting him on patreon, we can do it with 5 USD. It's angering to have to do that after buying the lifetime license, but of course it's not his fault what the company did and in some months he had improved Sandboxie more than they did in latest years.
