### ISSUE TITLE
Concise open url dialog box

### ISSUE THREAD

**Issue by prsyahmi** [sandboxie-plus/Sandboxie#3401]
### Is your feature request related to a problem or use case?

![image](https://github.com/sandboxie-plus/Sandboxie/assets/1040494/a7456ee6-e9eb-4704-9ab9-cfff210317c2)

This dialog box pops up rarely and I forgot what "yes" is for and "no" is for and I had to read the entire length of sentence to figure it out. This is happening to me since tzuk's sandboxie.

### Describe the solution you'd like

![image](https://github.com/sandboxie-plus/Sandboxie/assets/1040494/29b01fd2-dbda-4cc1-a032-33563e317049)

**Comment by DavidXanatos** [comment]
done will be in 1.12.0a
![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/5759e030-4b90-4cd1-9d93-0d6616a68548)
