### ISSUE TITLE
[v1.11.4 to v1.12.0 Pre-release] Online updater does not respect portable mode

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#3406]
### Describe what you noticed and did

Updating via the updater does not respect portable mode.
Meaning it'll install that creates unwanted files on the system drive, such as start menu shortcuts, registry, and so on.

### Affected program

Not relavant.

### Download link

Not relavant.

### Where is the program located?

Not relevant to my request.

### Expected behavior

It should extract portably instead of install unwanted files on the system drive.

### What is your Windows edition and version?

Not relevant.

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Not relevant.

### What version of Sandboxie are you running?

v1.11.4 to v1.12.0 pre-release

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment]
@offhub Possibly fixed with https://github.com/sandboxie-plus/Sandboxie/commit/12a85fbcb49e8f22596dabc9f21a5f538246d003#diff-0fa11bb0824fee86fc4c36c20a040983aaac1ef2c6d052c3a0d7eef1d1668f99
If not, feel free to comment or reopen the issue.
