### ISSUE TITLE
Is there a way to add specific program shortcuts in SbieCtrl in Sandboxie Classic? 

### ISSUE THREAD

**Issue by trewqaGGG** [sandboxie-plus/Sandboxie#3407]
So in the defaultbox "Run Program" context menu, there are only five options, which don't seem to be editable. Can I add or remove options in that list so I don't have to manually paste a certain file path to run an application in sandboxie every time? It would greatly improve workflow.

**Comment by offhub** [comment]
There is no such feature for the Classic interface. If you want to _add_ to the `Run Menu`, you should use the Plus interface.

#### Per Sandbox Run Menu:

Sandboxie Plus > Right click on the sandbox > Sandbox Options > General Settings > Run Menu

#### Global Run Menu (for all sandboxes):

Sandboxie Plus > Options > Global Settings > Shell Integration > Run Menu

**Comment by DavidXanatos** [comment]
the classic ui will not receive any new features
