### ISSUE TITLE
[Bug] Disabling updates does not actually disable the update check on startup.

### ISSUE THREAD

**Issue by gettysburg** [sandboxie-plus/Sandboxie#3408]
### Describe what you noticed and did

Disabling updates does not actually disable the update check on startup, as can be seen here:

![image](https://github.com/sandboxie-plus/Sandboxie/assets/2256003/892f7fdc-97ff-47cd-9fe7-f1a3a60ce567)

Another potential bug could be Sandboxie not actually saving update settings (for example interval) to the global `.ini` file.

### How often did you encounter it so far?

On every SandMan.exe launch.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

I expect my settings to be respected by the program, and additionally, maybe parameters being saved to the global `.ini` file for manual editing.

### What is your Windows edition and version?

Windows 11 Enterprise 22H2 (Build 22621.1992)

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie-Plus 1.11.4

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

Not sure.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
DefaultBox=Sandbox
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EnableWin32kHooks=n

[UserSettings_08DA01C0]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:Sandbox

[Sandbox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=C:\Users\User\Downloads
BorderColor=#0000ff,on,6
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
ClosePrintSpooler=y
NotifyProcessAccessDenied=y
CopyLimitKb=8192
AllowBoxedJobs=y
DropAdminRights=y
CopyBlockDenyWrite=y
NotifyDirectDiskAccess=y
```

**Comment by bastik-1001** [comment]
Do you see network requests being made? Or attempts to make them?

The screenshot shows that the update check has failed, which can considerably be the case, when updates are disabled, in which case it should only print that automatic updates are disabled, if anything about updates at all.

Settings for the user interface are saved in `%USERS%\$USERNAME\AppData\Local\Sandboxie-Plus\Sandboxie-Plus.ini`

Different users, on the same machine, may have different preferences for the interface.

**Comment by DavidXanatos** [comment]
There seams to be a missunderstanding, this log line is generated by the software compatybility mechanism, when trying to enumerate windows updates here: https://github.com/sandboxie-plus/Sandboxie/blob/b32d544137159671cf56d2bc8ea2f095312b63cc/SandboxiePlus/SandMan/SbiePlusAPI.cpp#L1206
but I see how this message can be missinterpreted, will change it in the next build

**Comment by gettysburg** [comment]
@bastik-1001 No, I do have a firewall installed which blocks incoming and outgoing traffic by default though and could take a look, but since this is related to Windows Updates, there is no real purpose.

@DavidXanatos Thanks for clarifying, Windows Updates are disabled and I install them from the Update Catalog manually.

**Comment by gettysburg** [comment]
I just realized that the

```res = updateSearcher->Search(criteria, &searchResult);```

call likely fails because SandMan.exe is running as a standard user, without administrator permissions, and UAC set to it's maximum level.

Now it all makes sense, and I understand what you are doing, iterating installed updates for compatibility checks.
