### ISSUE TITLE
exporting box - could we have extra options?

### ISSUE THREAD

**Issue by teampem** [sandboxie-plus/Sandboxie#3409]
### Is your feature request related to a problem or use case?

feature request - export box with more options (such as passwords/split archives)

### Describe the solution you'd like

Currently sandboxie does a great job to export to a 7z file, but would it be able to have some options we can maybe change in the settings? Such as

Password protected (either prompt or put into settings)
Split archive (so we could for example a very large box every 750mb/2gb/100mb) choices

These options are already avilable in 7zip but not in sandboxie. This would be great to make sure that data is secure and easier for cloud syncing or drives that use fat32

### Describe alternatives you've considered

In theory you can get 7zip to re-do the exported box but it's a few extra steps that should be easy to implement.

**Comment by bastik-1001** [comment]
@David
While I have no idea how popular the export/import function is, and I am not sure if you have any reports or data on that, having the requested features being added by just some settings in the ini, that is without a prompt, the password or passwords will be readable. Users may like that it is easier to use, compared to typing it a couple of times. If there are dialogs or options for these features, more users can notice and use them (if they use the feature to begin with).

**Comment by DavidXanatos** [comment]
hmm.... that sounds usefull, its good to be able to set some optons like compression rate password, may be recovery record, etc... will look into that
