### ISSUE TITLE
how to enable hardening filters, aka "ClosePrintSpooler=y" and where are they listed online? 

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#341]
ClosePrintSpooler=y
OpenSmartCard=n

Is this to be added under sandboxie.ini, globa/user/individual sandboxes?

Is there a list of filters somewhere we can see them?

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/103993227-92cfc900-5195-11eb-8ee0-aaf908d85cfb.png)

![grafik](https://user-images.githubusercontent.com/3890945/103993259-9fecb800-5195-11eb-84b3-ae2e0b955ea2.png)



you can also set those globally if you want

**Comment by rugabunda** [comment]
tx david
