### ISSUE TITLE
Process conhost.exe called by cmd.exe run outside of Sandboxie-Plus v0.5.4

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#342]
I launched a batch file (*.bat) in Sandboxie, but only cmd.exe ran in Sandboxie-Plus, conhost.exe not. 

![1](https://user-images.githubusercontent.com/56181919/103983950-272e3180-517e-11eb-9862-45d11f1f4ff1.PNG)

I confirm this conhost.exe is called by cmd.exe which is ran in Sandboxie.

**Comment by 0x391F** [comment]
Sandboxie legacy build also have this problem.

**Comment by DavidXanatos** [comment]
conhost.exe is started by SbieSvc.exe and its normal that is starts outside.
