### ISSUE TITLE
Sandboxie Classic — Running Java program as administrator within sandbox opens Java process in real windows. Is this expected behaviour?

### ISSUE THREAD

**Issue by trewqaGGG** [sandboxie-plus/Sandboxie#3420]
### Describe what you noticed and did

So I downloaded a preinstalled game off the web, intending to run it completely within my sandboxie sandbox. In the instructions, it said to run as administrator, and I _thought_ I had solved the problem of breaching out of my sandbox when running as administrator by running it as administrator with a sandboxed file explorer instead of a real one, but I only tested it with a batch script. So anyways, I ran the executable of the game in administrator mode with a sandboxed file explorer, but lo and behold, it opened up a Java process in my REAL PC, and could be seen with task manager. Is this some kind of expected behaviour where java programs elicit for sandboxie to open a Java runtime in my real computer but which doesn't affect anything else? Or I don't know. This seems to be a huge security vulnerability, and I am quite worried about the implications of my opening an unsafe game in what I thought would be a secure environment. 

### Affected program

Age of Civilizations II

### Download link

https://uploadhaven.com/download/5b4bfd027e5949117e7bf4c6b8772434

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

The game to run completely within Sandboxie's supervision even when run in administrator mode, and for nothing to affect my real PC.

### What is your Windows edition and version?

Windows 10 Home Edition 20H2

### In which Windows account you have this problem?

A Microsoft account (Standard user).

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Classic v5.66.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by trewqaGGG** [comment]
Update: It seems for every time I have run a program in administrator mode inside sandboxie, besides a simple batch script, has opened a process inside my real computer. This time I tried it with another game executable and it opened an exe process in my computer.

**Comment by DavidXanatos** [comment]
The link is not downloadable.
If you are referring to conhost.exe this is normal behavior the process is started by the sandboxie service to handle the terminal of console applications

**Comment by trewqaGGG** [comment]
Sorry, that link only seems to be accessible when the referrer is from a certain website. Here is a working link:
https://uploadsome.com/en/uMEtctn6dmzbfZT/file

I realise this result happens for any program, regardless of if ran as administrator or not.

>If you are referring to conhost.exe

I was not referring to conhost.exe, I am saying that any program run in Sandboxie seems to open a process that is visible from regular task manager. Is this expected behaviour?

But specifically, for the Age of Civilizations II game executable, it opened a Java process that could be visible with task manager, and that also didn't have the Sandboxie "[#]" prefix in its window title. It did show the Java process inside sandboxie control, and I could terminate it from there, but I really had no way of knowing if it is still really in Sandboxie's supervision or not.

**Comment by bastik-1001** [comment]
> I am saying that any program run in Sandboxie seems to open a process that is visible from regular task manager. Is this expected behaviour?

Yes, that is normal and should always have been the case. It's not a VM, and Sandboxie does not try to hide the presence of processes from the real system. You can terminate processes with the regular task manager. What did make you think that the regular task manager was not being able to see those processes?

> It did show the Java process inside sandboxie control, and I could terminate it from there, but I really had no way of knowing if it is still really in Sandboxie's supervision or not.

As the process seems to be governed by Sandboxie, it was running within the sandbox. As far as I can tell, you did not describe anything, that suggests it not being under the supervision of Sandboxie. You should be able to tell by the user that is shown in the task manager.

**Comment by trewqaGGG** [comment]
> You should be able to tell by the user that is shown in the task manager

When I have a sandboxie process running, I can't see any other user in the task manager besides my own. What did you mean by that?

> As the process seems to be governed by Sandboxie, it was running within the sandbox. As far as I can tell, you did not describe anything, that suggests it not being under the supervision of Sandboxie.

I did say the Java process did not have the "[#]" prefix & suffix in its name like other sandboxed processes would.

**Comment by bastik-1001** [comment]
> When I have a sandboxie process running, I can't see any other user in the task manager besides my own. What did you mean by that?

I forgot that the default view of the task manager does not show that information. The details tab should show that information. Alternatively, Sysinternals Process Explorer shows the username and the integrity of processes or David's TaskExplorer.

It should show _sandboxie/yourboxname_ if `SandboxieLogon=y` is being set, otherwise _anonymous_ and the level should be _untrusted_ in any case.

> I did say the Java process did not have the "[#]" prefix & suffix in its name like other sandboxed processes would.

I got that, but took that for a glitch in how that is sign is added to the process window name. I was not clear enough.

**Comment by diversenok** [comment]
Also keep in mind that Task Manager doesn't refresh the user column in the detailed process view, so it might occasionally show a wrong (outdated) value. It happens when a process starts suspended as a normal user but gets forced into a sandbox on resume, which swaps its token and, therefore, changes the associated user. If Task Manager happened to cache the old username, it will continue showing it.

![image](https://github.com/sandboxie-plus/Sandboxie/assets/30962924/cf88a4a7-a68f-4d7e-9dc7-6f44ff95e73e)
