### ISSUE TITLE
UNEXPECTED_KERNEL_MODE_TRAP BSOD when opening any web link from sandboxed Microsoft 365 app (e.g. Outlook, Word)

### ISSUE THREAD

**Issue by e-t-l** [sandboxie-plus/Sandboxie#3427]
### Describe what you noticed and did

I am trying to use Microsoft Office 365 in a sandbox. It is installed on the host system. I can open apps like Outlook, Word, OneNote, etc., and they launch with no issue - Outlook can Send/Receive, and OneNote is signed into Microsoft acct and can sync with cloud. However, if I try to open any web link, I get a UNEXPECTED_KERNEL_MODE_TRAP blue screen.

### How often did you encounter it so far?

Every time

### Affected program

Microsoft Office 365

### Download link

https://c2rsetup.officeapps.live.com/c2r/download.aspx?ProductreleaseID=O365ProPlusRetail&platform=x64&language=en-us&version=O16GA

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Web links should open in Firefox, which is a BreakoutProcess.

### What is your Windows edition and version?

Windows 11 Enterprise 22H2 64-bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.11.4 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Crash dump

https://github.com/e-t-l/Sandboxie/blob/temp-files/110923-20156-01.dmp

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=WindowsRasMan
Template=OfficeClickToRun
Template=OfficeLicensing
Template=WindowsLive
ForceDisableSeconds=600000

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
BreakoutProcess=firefox.exe
BreakoutProcess=betterbird.exe
BreakoutProcess=acrobat.exe
OpenPipePath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*

[UserSettings_0CBE021F]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_HideMessage=1307,AcroCEF.exe [_Acrobox] *
SbieCtrl_HideMessage=2211,BITS
BoxGrouping=:OfficeBox

[OfficeBox]
Enabled=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=Office_Outlook
Template=OfficeClickToRun
Template=OfficeLicensing
Template=OpenProtectedStorage
ConfigLevel=10
BreakoutProcess=firefox.exe
BreakoutProcess=betterbird.exe
BreakoutProcess=acrobat.exe
OpenPipePath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*
BlockNetParam=n
ForceProcess=OUTLOOK.EXE
RpcMgmtSetComTimeout=n
```
```

**Comment by e-t-l** [comment]
Things I have already tried, with no success:
- Make sure Firefox was not already running when opening the web link
- `DisableForceRules=y`
- `OpenWinClass=*`
- `OpenSamEndpoint=y`
`OpenLsaEndpoint=y`
- `StartProgram="C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe" /service`
`LingerProcess=OfficeClickToRun.exe`
- `OpenIpcPath=\RPC Control\SECLOGON`
`OpenIpcPath=\RPC Control\LRPC*`
- `RpcPortBinding=kernel32.dll,'0497b57d-2e66-424f-a0c6-157cd5d41700@ncalrpc:',Resolve=AppInfo,TimeOut=y`
`RpcPortBindingIfId=AppInfo,{0497b57d-2e66-424f-a0c6-157cd5d41700}`
- `OpenIpcPath=*\BaseNamedObjects\MSSPHTB_*`
`OpenIpcPath=*\BaseNamedObjects\OfficeSharedLocks_*`
`OpenIpcPath=*\BaseNamedObjects\WMS Notif Engine*`
`OpenIpcPath=*\BaseNamedObjects\MAPI-*`

**Comment by offhub** [comment]
I tried it with a free trial in a virtual machine without a Microsoft account, but it did not crash. Does it crash even if Breakout is not set?

**Comment by e-t-l** [comment]
> Does it crash even if Breakout is not set?

Yes, it still crashes even after removing BreakoutProcess rules. 

When you tried to replicate it, did you use the Samdboxie.ini config I pasted?

**Comment by offhub** [comment]
I used the configuration from the first message as is.

Do you have the same problem with other browsers?

#### Without "BreakoutProcess=firefox.exe" (Windows 11 22H2)

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/ca1bc585-b8d9-4e5e-a9ed-b2d6e72c973d

**Comment by e-t-l** [comment]
### Update
I'm now less suspicious of Office 365 and think it's specifically something about opening browsers in Sandboxie. (Presumably something to do with the SBIE driver, given that it's a kernel trap error.) 

I recently tried to open Microsoft Edge in any sandbox, including my default one, it immediately triggered the same BSOD. It was not launched from a within an app; I just used Sandboxie-Plus's  Run dialog to execute "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"

```
Enabled=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#02f6f6,ttl,6
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
Template=RemoteDesktop
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
ForceProcess=remoteplay.exe
ForceProcess=DS4Emulator.exe
ForceProcess=ds4Emulator64.exe
BlockNetParam=n
OpenDevCMApi=y
MsiInstallerExemptions=y
RpcMgmtSetComTimeout=n
NormalKeyPath=\REGISTRY\USER\*_Classes\*
DisableForceRules=n
ReadKeyPath=*
```

**Comment by e-t-l** [comment]
I am suspecting more and more that the problem is with Microsoft Edge specifically, because apparently Office programs, including Outlook, have a default setting that uses Edge instead of the global default browser!

![](https://i.redd.it/1i9f0i3mwcmb1.png)

**Comment by offhub** [comment]
Similar crashes have been reported, but the problem has not been resolved yet. (#2958)

1. The problem is not reproducible by the developer.

2. The information and dump files presented are not sufficient to solve the problem.


Maybe it would be helpful if you write down your hardware information and any non-default Windows security settings you have made.


Also, how long have you been using Sandboxie and when did this problem start?

**Comment by e-t-l** [comment]
> Similar crashes have been reported, but the problem has not been resolved yet. (https://github.com/sandboxie-plus/Sandboxie/issues/2958)

I know, when the BSOD started happening, scouring that issue thread was the first thing I did. One thing I noticed is that at least one person there was encountering BSODs on Windows Enterprise. I'm also on Enterprise, so I wonder if that could somehow be related. Assuming that you and David don't use Enterprise, you can switch your Windows license to it (and safely switch it back) using https://github.com/massgravel/Microsoft-Activation-Scripts, if you want to see if that makes a difference.

> Maybe it would be helpful if you write down your hardware information and any non-default Windows security settings you have made.

Sure thing. This is a brand new gaming laptop (specs below). Settings are all default, no overclocking or anything like that. (Setting up apps in Sandboxie was one of the first things I wanted to do on a fresh install, hoping that it would provide an extra layer of security and virtualization. It's proving to be quite the adventure to figure it all out, but I persist.)
- Lenovo Legion Pro 5i gen 8 (16IRX8)
- CPU: 13th Gen Intel(R) Core(TM) i7-13700HX, 2100 Mhz
- GPU: Nvidia GeForce RTX 4070 Laptop GPU
- BIOS: Lenovo KWCN38WW, 6/20/2023
- Windows 11 Enterprise 64-bit
- Windows build version 10.0.22621

I have some Group Policy objects configured which I don't _think_ should affect anything, but just in case: You can download my exported [Registry.pol](https://github.com/e-t-l/Sandboxie/blob/temp-files/Registry.pol) (should be viewable using a program like [NetTools](https://nettools.net/how-to-read-the-contents-of-registry-pol-files/)).

> Also, how long have you been using Sandboxie and when did this problem start?

I've only been using it for maybe a few weeks, as I mentioned it's a new computer and I still consider it in the "getting everything set up" phase. Just in case it was some kind of corrupted Sandboxie driver, I completely uninstalled Sandboxie, then installed v1.12.0, but the BSOD still occurs.

**Comment by e-t-l** [comment]
I had an idea regarding the Edge issue. After changing Outlook settings per the screenshot to open links in Default Browser, I noticed that when I opened al ink, in the Sandboxie-Plus GUI I was still seeing a MSEDGE.EXE process spawn in OfficeBox immediately preceding the BSOD crash. It made me wonder if, somewhere in the program files or registry keys that were virtualized in OfficeBox, there remained some setting that made Office apps think Edge was the default browser. 

I created a new sandbox, OfficeBox2, and copied over the .INI configuration from OfficeBox. In this newly created, empty OfficeBox2 sandbox, I can run Outlook, open a link, and it will breakout/open Firefox as expected, with no BSOD!

So, while I still don't know what _exact_ file, regkey, etc. caused the fatal conflict in the original OfficeBox, I am fairly certain it is a thing of the past, and I will be able to keep using Office apps in OfficeBox2 without fear of any more BSODs. Up to you whether to keep this Issue open or close it. Appreciate your help, @offhub!

> I am suspecting more and more that the problem is with Microsoft Edge specifically, because apparently Office programs, including Outlook, have a default setting that uses Edge instead of the global default browser!
> ![](https://camo.githubusercontent.com/c1b3eed5323a617b0ebdf921cf5f8bca84e70532c7d38baaea70505a07cc5a68/68747470733a2f2f692e726564642e69742f316939663069336d77636d62312e706e67)

**Comment by reraikes** [comment]
> Similar crashes have been reported, but the problem has not been resolved yet. (#2958)

FWIW...

Since receiving no response to my last comment on Jun 7, 2023, my system has remained totally stable (no anomalies whatsoever) with Sandboxie removed (I'd been using Sandboxie without any problems for the past 15+ years).

Today, I installed Sandboxie 5.66.4 only to be met with BSOD's once I log in, as previously described in #2958.

I do not use Outlook.

**Comment by e-t-l** [comment]
@reraikes 
> Today, I installed Sandboxie 5.66.4 only to be met with BSOD's once I log in, as previously described in https://github.com/sandboxie-plus/Sandboxie/issues/2958.
> I do not use Outlook

Yeah, if you see my comment above yours, I determined the issue was with Edge, not with Outlook specifically.

I notice you keep saying you get BSODs not immediately after installing Sandboxie, but specifically *when you log in*. Am I to understand that you can install Sandboxie, and the system will run fine for the rest of the session, and it's only when you restart the machine (or logout-then-login) that you get the BSOD?

Apologies if I'm repeating anything that's already been said in that thread, but have you tried:
- Disabling all your startup programs and services, including any Task Scheduler tasks that may run on startup/logon?
- Disabling Sandboxie's automatic startup? (in other words, if SBIE *doesn't* start up automatically when you log in, does the system still crash? Is it SBIE's *presence* on your computer that triggers the BSOD, or specifically the fact the SBIE is *running?*)
- Because my issue was caused by Edge, why don't you try adding the following to your global "Sandboxie.ini" file:
`ProcessGroup=<StartRunAccess>,msedge.exe`
`ClosedIpcPath=<StartRunAccess>,*`
`BreakoutProcess=msedge.exe`
I'm still relatively new to SBIE but I *think* those settings should fully prevent Edge from starting in your sandboxes.

You could also try fully uninstalling MS Edge from your device by following [this guide](https://gist.github.com/ave9858/c3451d9f452389ac7607c99d45edecc6).

If your BSODs still persist, then I think your issue is unrelated to this one.

**Comment by kolomeets80** [comment]
Turning off kernel-mode hardware-enforced stack protection resolved this issue, allowing Edge to launch in any Sandbox.

**Comment by e-t-l** [comment]
> Turning off kernel-mode hardware-enforced stack protection

Where is this setting located? It sounds like a Windows setting, not a Sandboxie one, right? Can it be deactivated for Edge specifically or is a system-wide thing?

**Comment by reraikes** [comment]
>Where is this setting located?

https://www.bleepingcomputer.com/tutorials/how-to-enable-kernel-mode-hardware-enforced-stack-protection-in-windows-11/

**Comment by kolomeets80** [comment]
You got it right. Your link is correct.

**Comment by reraikes** [comment]
Turning off Kernel-mode Hardware-enforced Stack Protection in Windows 11 resolves the BSOD's that started for me on May 21, 2023, which have prevented me from using Sandboxie ever since.  Thank you @kolomeets80!

@DavidXanatos,

Are you able to reproduce this problem now that we know its source, and more importantly, do you believe a change to Sandboxie is possible so that wholesale disabling of Kernel-mode Hardware-enforced Stack Protection in Windows 11 is not required?  For the moment, I'm going to remove Sandboxie again and re-enable Kernel-mode Hardware-enforced Stack Protection in Windows 11 as I fear a Windows update may turn it back on at some point.  I wasn't even aware of this setting and certainly didn't turn it on in the first place.

**Comment by DavidXanatos** [comment]
@reraikes 

please add the following 4 lines to your [GlobalSettings] section

DisableWinNtHook=CreateEnclave
DisableWinNtHook=LoadEnclaveData
DisableWinNtHook=InitializeEnclave
DisableWinNtHook=CallEnclave


this should fix the BSOD with MsEdge, please confirm it is working for you.

**Comment by reraikes** [comment]
@DavidXanatos

Is this just a test to confirm the source of the problem?  I would not like to see this as a long-term fix as one could easily get into trouble on a new installation if you don't get those changes in instantly before the BSOD's begin.  Even the possibility of a single BSOD scares me to death as file corruption can result when they occur.  Given the current state of things, I don't install Sandboxie until I've done a full backup immediately before and then a full restore afterward if any BSOD's occur.

**Comment by DavidXanatos** [comment]
The problematic syscalls will be added to an exclusion list in 1.12.2 ensuring the driver will never hook this syscalls.

Loading them from [GlobalSettings] is just a temporary measure to confirm the fix works on your system.
btw: after adding these lines you need to reboot the PC or reload the sbie driver as these are only evaluated on driver load.

**Comment by reraikes** [comment]
Thank you for the explanation.  A little later today, I'll do a backup and reinstall Sandboxie with the changes to [GlobalSettings].

Out of curiosity...
Is there some code in Sandboxie that's altering the stack such that the new security check in Windows is getting triggered?

**Comment by DavidXanatos** [comment]
No, its strange that CallEnclave causes such a crash I'll have to investigate this further but given that other ntdll syscall seams to be fine it may be a windows bug, I'll have to investigate if this can be triggered without the sbie driver as well.

**Comment by reraikes** [comment]
The addition of the four 'DisableWinNtHook' entries appears to get rid of the BSOD's upon login to Windows.

Is all these msedge instances not terminating when Edge is closed expected?

![Edge](https://github.com/sandboxie-plus/Sandboxie/assets/36712448/6e80f97c-686c-4aa6-942c-b29c55dfe0ba)
