### ISSUE TITLE
TrustedInstaller.exe: SBIE2205 Service not implemented:  TrustedInstaller 800706BA

### ISSUE THREAD

**Issue by 0xDEADFED5** [sandboxie-plus/Sandboxie#3437]
### Describe what you noticed and did

tried to install some shady shit, got error:

TrustedInstaller.exe: SBIE2205 Service not implemented:  TrustedInstaller 800706BA

### How often did you encounter it so far?

the error popped up like 50 times, it's a feisty one

### Affected program

custom installer by some dude in Russia

### Download link

probably a bad idea

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

installation

### What is your Windows edition and version?

Windows 11 Education 23H2 22631.2715

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Defender

### What version of Sandboxie are you running?

1.11.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]
Template=7zipShellEx
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_083C01AD]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
MsiInstallerExemptions=y
```

**Comment by DavidXanatos** [comment]
Running trusted installer is no longer a supported usecase, it was a thing under iirx XP or vista but not 7 or later.

**Comment by 0xDEADFED5** [comment]
okay.  i think it was triggered by a vanilla Adobe installer.  does TI just widen the scope too much for stuff that needs to be sandboxed?  i wish i had 2000 hours in a day so i could dive into this and learn some more.

**Comment by DavidXanatos** [comment]
Its not an issue with atack surface but with TI using to many undocumented COM API's it probably could be made to work given unlimted afford, but as its a MSFT tool used for servicing windows and office only its not needed for instaling fo 3rd party applications, where it is needed is when these 3rd party applications want to install some windows component, here its advisable to just find out what it is and install it outside teh sandbox manually, once its found it should not try to use TI.
Anyhow I'll close this for now.
