### ISSUE TITLE
[ Firefox 120.0 ] SBIE2205 Service not implemented: CredWriteA

### ISSUE THREAD

**Issue by xvim64** [sandboxie-plus/Sandboxie#3441]
### Describe what you noticed and did

<img width="466" alt="CredWriteA" src="https://github.com/sandboxie-plus/Sandboxie/assets/83569599/f217a8e5-c560-4838-9cc7-01c45e6e8e33">

After upgrading Firefox to v120.0, The "CredWriteA" popup message appears.

### How often did you encounter it so far?

Whenever I open the Firefox 120.0.

### Affected program

Firefox 120.0

### Download link

https://download-installer.cdn.mozilla.net/pub/firefox/releases/120.0/win64/

### Where is the program located?

The program is installed outside the sandbox.

### Expected behavior

CredWriteA Implementation(?) in the Sandboxie

### What is your Windows edition and version?

Windows 11 23H2 64bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.67.0

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (Sandboxie-Classic-x64-v5.66.4)

### Is it a regression?

Sandboxie-Classic-x64-v5.66.4

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by APMichael** [comment]
I can confirm this for Firefox v120. I also receive this error message from time to time.

https://www.wilderssecurity.com/threads/sbie2205-error.452907/

**Comment by Jimmy03** [comment]
I'm getting this too on Firefox 120.0 / Sandboxie Plus v1.11.4

What are the implications of using it with this error active?

**Comment by APMichael** [comment]
> What are the implications of using it with this error active?

I have not noticed any negative effects. Firefox v120 works flawlessly, despite the error message from Sandboxie.

@DavidXanatos has already been able to reproduce the issue, so it should be fixed with the next update.

**Comment by DavidXanatos** [comment]
try https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.12.1

**Comment by APMichael** [comment]
@DavidXanatos, the fix unfortunately has a small side effect. If a sandboxed Acrobat Reader is closed under the current version 1.12.1, the following error message is now always displayed:

`Acrobat.exe: SBIE2205 Dienst nicht implementiert: CredEnumerateA`

**Comment by DavidXanatos** [comment]
ok will fix that in the next build
