### ISSUE TITLE
Wemod can't launch with sandboxie

### ISSUE THREAD

**Issue by Reti153125801** [sandboxie-plus/Sandboxie#3451]
### Describe what you noticed and did

Download wemod-setup.exe from wemod.com and perform the installation normally
Execute only for one second when loading and restart new processes infinitely

Monitor software logs: wemod terminates after one second and starts a new process

wemod.exe","8130","(0x4c) Process has terminated","Ran for 1 secs. Average CPU use 3.12%.","c:\sandbox\User\defaultbox\user\current\appdata\local\wemod\app-8.13.1\wemod.exe","""C:\Users\User\AppData\Local\WeMod\app-8.13.1\WeMod.exe"" --type=gpu-process --user-data-dir=""C:\Users\User\AppData\Roaming\WeMod""--disable-features=SpareRendererForSitePerProcess\,WinRetrieveSuggestionsOnlyOnDemand /prefetch:2"

### How often did you encounter it so far?

First time install wemod

### Affected program

Wemod v8.13.1

### Download link

https://www.wemod.com/

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Load normally

### What is your Windows edition and version?

win10 22h2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Kaspersky

### What version of Sandboxie are you running?

sandboxie classic x64 v5.66.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]
Template=Kaspersky
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing

[DefaultBox]
ConfigLevel=10
AutoRecover=y
BlockNetworkFiles=y
NetworkAccess=Block;Port=137,138,139,445
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=%Desktop%
BorderColor=#00FF00,on,6
Enabled=y
BoxNameTitle=n
AutoDelete=y
NeverDelete=n
```

**Comment by offhub** [comment]
I can confirm, WeMod's GPU process keeps crashing and restarting. (Works fine on VM)

Try adding `--disable-gpu`

`"%LocalAppData%\WeMod\app-8.13.1\WeMod.exe" --disable-gpu`
