### ISSUE TITLE
SBIE2205 Service not implemented CredReadA

### ISSUE THREAD

**Issue by joewee393** [sandboxie-plus/Sandboxie#3453]
### Describe what you noticed and did

Pops up regularly. May have started since Firefox 120.00 was installed, not sure.

### How often did you encounter it so far?

whenever a new website is opened

### Affected program

Firefox 120.0

### Download link

not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

no error message

### What is your Windows edition and version?

Windows 10 Home 64 bit 

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

MS Defender Antivirus

### What version of Sandboxie are you running?

5.66.4

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by APMichael** [comment]
Already fixed in version 1.12.1/5.67.1.

Please note this report: https://github.com/sandboxie-plus/Sandboxie/issues/3441
