### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by BilleBarrett** [sandboxie-plus/Sandboxie#346]
The critical update is putting my clients down, PatchmyPC is updating to it, and then Chrome will not load
SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
This is a mess

**Comment by DavidXanatos** [comment]
Is it the today release or the yesturday once?
There is a 5.46.1 hotfix release just released like an hour ago,
it resolves a crash issue with sbiesvc

**Comment by BilleBarrett** [comment]
I think it was yesterday, v5.46, PatchmyPc picked it up and changed all my clients that I have on it
I just upgraded a client to v5.46.1

1 I uninstalled the old version

2 I had to reboot the system 

3 reinstall the new version

Still getting opening errors 

So far so good

Thanks for the comeback

I will be staying on the Classic version until I have everyone up to date

I do like it, just frustrated with the downloads feature

Bill e. Barrett

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
This is my reply mail signature

"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by JimCarls** [comment]
I can't download the most recent release without warnings. Both Firefox and Chrome are warning "this is not commonly downloaded and may be dangerous (using this URL:  https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.5.4b/Sandboxie-Plus-x64-v0.5.4.exe)  I haven't seen messages like this before, so I'm not running the installer.

**Comment by bjm234** [comment]
> I can't download the most recent release without warnings. Both Firefox and Chrome are warning "this is not commonly downloaded and may be dangerous (using this URL: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.5.4b/Sandboxie-Plus-x64-v0.5.4.exe) I haven't seen messages like this before, so I'm not running the installer.

Warn you about unwanted and uncommon software: 
Lets you know if you're about to download potentially unwanted software or uncommon software that may contain a virus or make unexpected changes to your computer. 

I've run the installer.  It's safe.

**Comment by DavidXanatos** [comment]
should be fixed in 0.5.4c

**Comment by BilleBarrett** [comment]
👍😎

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
This is my reply mail signature

"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/
