### ISSUE TITLE
Korean installer (Korean.isl) script error...

### ISSUE THREAD

**Issue by VenusGirl** [sandboxie-plus/Sandboxie#3463]
### Describe what you noticed and did

In 1.12.2 Pre-release

Sandboxie/Installer/isl/Korean.isl

Korean.isl's encoding is not currently UTF-8 BOM
There is a problem with the Korean display.
I don't know why, but it seems to have changed.

You must change the Korean.isl encoding to UTF-8 BOM.

![Sandbox1](https://github.com/sandboxie-plus/Sandboxie/assets/53147200/e04082ad-023e-41ad-ae97-15fd43b3c5de)

### How often did you encounter it so far?

In 1.12.0 Pre-release

### Affected program

In 1.12.0 Pre-release

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Normal Screen in Sandboxie-Plus-x64-v1.12.1

![Sandbox2](https://github.com/sandboxie-plus/Sandboxie/assets/53147200/0a72c11a-df3d-4d49-bda9-9a50b8d4e46a)

### What is your Windows edition and version?

Windows 11 64bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.12.2 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### Is it a regression?

Not relevant

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

Not relevant

### Crash dump

Not relevant

### Trace log

none

### Sandboxie.ini configuration

```shell
Not relevant
```

**Comment by isaak654** [comment]
> I don't know why, but it seems to have changed.

@VenusGirl You did it by mistake in #3448
A small tip to prevent this from happening is to check that the first line has not been modified before creating a pull request.

**Comment by offhub** [comment]
You can upload files that contain the Byte Order Mark (BOM) character using `Add File > Upload Files`.

Most likely, the Byte Order Mark (BOM) character will not be preserved in the content copied to the Web Editor.
