### ISSUE TITLE
Firefox crashes in sandboxie after idle some time

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#3464]
### Describe what you noticed and did

https://crash-stats.mozilla.org/report/index/c0d68892-0f06-4328-b82a-b7e900231129#tab-details
Some bugs related to this seems also cause by SbieSvc.dll, see: [https://crash-stats.mozilla.org/signature/?product=Firefox&signature=shutdownhang+%7C+ZwDeviceIoControlFile&date=%3E%3D2023-11-22T11%3A15%3A00.000Z&date=%3C2023-11-29T11%3A15%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1](https://crash-stats.mozilla.org/signature/?product=Firefox&signature=shutdownhang+%7C+ZwDeviceIoControlFile&date=%3E%3D2023-11-22T11%3A15%3A00.000Z&date=%3C2023-11-29T11%3A15%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1), for example, https://crash-stats.mozilla.org/report/index/9aa2b0ed-c734-46c0-b93a-3efcf0231129#tab-details. 

### Affected program

Firefox 120.0

### Download link

https://ftp.mozilla.org/pub/firefox/releases/120.0/win64/zh-CN/Firefox%20Setup%20120.0.exe

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

This bug shouldn't appear. 

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2019 x64 (10.0.19044.3693)

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

ESET Inernet Security 17.0.15.0

### What version of Sandboxie are you running?

Sandboxie-Plus 1.12.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Crash dump

https://crash-stats.mozilla.org/report/index/c0d68892-0f06-4328-b82a-b7e900231129#tab-details

**Comment by offhub** [comment]
Can you try turning off the following settings?

https://github.com/sandboxie-plus/Sandboxie/issues/3443#issuecomment-1826753604

If it is a crash caused by the above, this problem will be fixed by ESET.

https://forum.eset.com/topic/38819-eis-170150-browser-script-scanner-breaks-firefox-in-sandboxie/#comment-176515

**Comment by 0x391F** [comment]
> Can you try turning off the following settings?
> 
> [#3443 (comment)](https://github.com/sandboxie-plus/Sandboxie/issues/3443#issuecomment-1826753604)
> 
> If it is a crash caused by the above, this problem will be fixed by ESET.
> 
> https://forum.eset.com/topic/38819-eis-170150-browser-script-scanner-breaks-firefox-in-sandboxie/#comment-176515

This setting has been turning off, because it will causing Firefox's tabs crash.

**Comment by 0x391F** [comment]
This bug seems doesn't reproduce any more.
