### ISSUE TITLE
sample 634d066fd4f9a8b201a3ddf346e880be unable to be terminate on windows 7 x64

### ISSUE THREAD

**Issue by Kwansy98** [sandboxie-plus/Sandboxie#3482]
### Describe what you noticed and did

sample 634d066fd4f9a8b201a3ddf346e880be is a netwire family malware which is using DebugActiveProcess to debug a subprocess svchost.exe. While debug established, in Windows 7, sample itself can not be terminated by TerminateProcess nor sandboxie interface, including qtGUI's "terminate all process" button and sbiedll!SbieDll_KillAll. The only way i found to terminate the sample it is to use  TerminateThread to kill all of its threads.
This is not a sandboxie bug, but it might be better if sandboxie ended the process properly :)
https://www.virustotal.com/gui/file/ebcda4a079c878809ffda53ec1f48fde31a6aff4901dbbd15c5b75f6edcb6f81

### Affected program

634d066fd4f9a8b201a3ddf346e880be

### Download link

`hxxp://43.138.13.175/file/634d066fd4f9a8b201a3ddf346e880be`

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

This is not a sandboxie bug, but it might be better if sandboxie ended the process properly :)

### What is your Windows edition and version?

Windows 7 x64   7601

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

no

### What version of Sandboxie are you running?

all version has this problem

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
can this be reproduced on windows 10?

**Comment by Kwansy98** [comment]
> can this be reproduced on windows 10?
No, currently it only appears in Windows 7, but I have not tested older versions.

**Comment by DavidXanatos** [comment]
I think in this case the best fix would be to simply always set DBG_TERMINATE_PROCESS right away, a simple fix for a fringe problem.
