### ISSUE TITLE
Report the error after opening the program

### ISSUE THREAD

**Issue by MaxLHy0424** [sandboxie-plus/Sandboxie#3486]
### Describe what you noticed and did

1. Opening the program;
2. Wait a minute;
3. The program is Report the error.
![image](https://github.com/sandboxie-plus/Sandboxie/assets/142279449/928f220f-3143-4f06-bb9d-f93bffc99385)

### How often did you encounter it so far?

It happens often.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Sandboxie-Plus can be opened normally.

### What is your Windows edition and version?

Windows 11 23H2 (Canary Channel, Build 26002.1010)

### In which Windows account you have this problem?

A Microsoft account (Administrator)., An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie-Plus v1.12.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Sandboxie-Plus v1.12.0

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
could you please provide the dmp files generated when crashing
