### ISSUE TITLE
Sandboxie-Plus > UI: Issues with non-modal tool windows [bug, priority:low]

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#349]
Several child windows of Sandboxie-Plus are configured as non-modal tool windows instead of modal dialogs, which causes undesired application states and exits. This includes:
* Settings dialog
* File Recovery dialog
* Snapshot manager dialog

Reproduce:
* Run Sandboxie-Plus v0.5.4b
* On the sandbox list, select and right-click on a sandbox and select "Sandbox Options" in context menu
* Application displays options dialog
* The child window is not modal. You can click back on the Sandboxie-Plus main window

Issues:
* You can close the main window. The child window remains open. The tray icon remains open at this point. If you now close the child window, then the tray icon vanishes and the application exits.
* Likewise, if you have opened several child windows, then close the main window and then close one of the child windows, then all child windows close and the application exists.
* You can open a second settings window. If you make a change in one window, then it does not stay in sync (live nor after "apply") with the other settings window. Since these settings windows are instantiated at the same on-screen location, this can cause confusion to unsuspecting users, potentially double-saving and wiping changed settings.
* You can minimize the child window. As it is set to not have a taskbar icon, it minimizes to the bottom of the desktop, possibly behind other active windows.
* You can minimize the child window. If you then minimize and restore the main window, then the child window also restores.

**Comment by DavidXanatos** [comment]
I'll leave the windows non modal but I'll fix the errors resulting from this
