### ISSUE TITLE
Sandboxie v5.67.3 x64 does not allow low-level disk access by default

### ISSUE THREAD

**Issue by Adalantares** [sandboxie-plus/Sandboxie#3490]
### Describe what you noticed and did

1. Installing the program in the sandbox (located on the second system disk)
2. Running the program in the sandbox
3. SBIE2224 Sandboxed program has crashed: oodag.exe [Box1]

### How often did you encounter it so far?

This error appeared from Sandboxie Classic x64 v5.55.0 to the current version. There were no problems in previous versions.

### Affected program

O&O Defrag x64, Auslogics Disk Defrag x64  

### Download link

https://www.oo-software.com/en/download/archive?product=OOD23PRO

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

The program should analyze system disks and defragment them.

### What is your Windows edition and version?

Windows 7 Ultimate 64-bit SP1

### In which Windows account you have this problem?

I use the built-in Administrator account., I use the built-in Administrator with Admin Approval Mode turned on.

### Please mention any installed security software

Norton Internet Security, but it is completely disabled

### What version of Sandboxie are you running?

Sandboxie Classic x64 v5.67.3.exe

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Sandboxie Classic x64 v5.55.0 

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
well a defrag took is probably not something that one would expect to work when sandboxed, as it needs low level disk access

**Comment by isaak654** [comment]
I think this is related to #705

**Comment by Adalantares** [comment]
> well a defrag took is probably not something that one would expect to work when sandboxed, as it needs low level disk access

Yes, I understand what you're saying.
There is a list of programs that defragment disks and so that you don’t install each one and then remove it. It would be nice to test them in different boxes, at least at the "disk analysis" level.

Is it possible to set "low level access" in new versions? 
If yes, then let me know how or do you mean about “Full access” and “Direct access”?

In versions without this error, you can even defragment the disk without problems using different defragmenters.
*But this process is best done outside the sandbox.

**Comment by DavidXanatos** [comment]
for me the O&O tool crashed also in  v5.55.0 (plus v1.0.0) I don't think we want to support this usecase and with build 1.12.3 and the removal of SeManageVolumePrivilege we add even more limitations.

You can try using a green box and disable security filtering:
NoSecurityIsolation=y
NoSecurityFiltering=y
this is the most insecure config there is but it might just work

also i assume you know you should NOT defrag an SSD only mechanical hard drives, right?
