### ISSUE TITLE
All browsers do not work in sandboxie

### ISSUE THREAD

**Issue by NRicode** [sandboxie-plus/Sandboxie#3503]
### Describe what you noticed and did

With fresh installation of sandboxie (latest version 1.12.4 released today), not a single browser can work in it, the errors are all the same:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/106366188/592ea429-d257-4cb9-be09-bac3b5414d35)

For this example, I am testing out librewolf browser, but edge, firefox, and literally any other browser doesn't work. This only affect browser applications, normal apps are functioning just fine.

### How often did you encounter it so far?

all the time

### Affected program

all browsers

### Download link

-

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

-

### What is your Windows edition and version?

windows 11 home

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

ms defender

### What version of Sandboxie are you running?

latest version 1.12.4 as of today

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

-

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

-

### Crash dump

-

### Trace log

-

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
DefaultBox=DefaultBox
FileRootPath=D:\sandboxie\Sandboxie-Plus\Sandbox\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=7zipShellEx
Template=Edge_Fix
Template=OfficeClickToRun
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_087C01BD]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
BreakoutProcess=msedge.exe
DropAdminRights=y
FakeAdminRights=n
```

The main cause is the inability to inject sandboxie's dll into any browser process, but it injects just fine on any other app. Not sure what caused this. Ms edge compatibility is enabled. The last version before this also doesn't work. This includes all the other chromium based app like steam, discord, etc. Same exact errors for these apps

**Comment by offhub** [comment]
What was the last version that worked properly? (version 1.11.4 or 1.12.2)

**Comment by DavidXanatos** [comment]
[SbieDll_1.12.5.zip](https://github.com/sandboxie-plus/Sandboxie/files/13706504/SbieDll_1.12.5.zip)
please try this sbiedll.dll stop sandboxie using the maintenance menu command stop all replace the dll's in the instalation folder and restart sandboxie

**Comment by DavidXanatos** [comment]
> This replacement dll didn't work. I'm new to sandboxie, it has never worked. Can this issue be replicated on your machine?

no here it works fine there was a minor bug where chrome browsers did not terminate last process that the dll addresses

**Comment by NRicode** [comment]
> > This replacement dll didn't work. I'm new to sandboxie, it has never worked. Can this issue be replicated on your machine?
> 
> no here it works fine there was a minor bug where chrome browsers did not terminate last process that the dll addresses

Do you have any idea what might cause the dll hooks to fail? I think it is something specific with my system.

**Comment by isaak654** [comment]
> Do you have any idea what might cause the dll hooks to fail? 

https://github.com/sandboxie-plus/Sandboxie/issues/3050#issuecomment-1665701740

**Comment by NRicode** [comment]
> > Do you have any idea what might cause the dll hooks to fail?
> 
> [#3050 (comment)](https://github.com/sandboxie-plus/Sandboxie/issues/3050#issuecomment-1665701740)

Alright, seems like this one. The language is pretty technical, but am I supposed to reinstall sandboxie to C:/program files or uac prompt for kmdutil coming for the next update?

**Comment by NRicode** [comment]
Alright it works now, however I noticed this new error for this specific version 1.12.4 today, it doesn't cause any problem currently
![image](https://github.com/sandboxie-plus/Sandboxie/assets/106366188/6bc66ac1-5dcc-4a65-a98f-11e5e7003f56)

**Comment by isaak654** [comment]
> Alright it works now, however I noticed this new error for this specific version 1.12.4 today, it doesn't cause any problem currently

That's another issue: #2996
Apparently @DavidXanatos is waiting for someone to provide clear steps, since he was unable to reproduce it.

**Comment by isaak654** [comment]
That's another issue: #2996
Apparently @DavidXanatos is waiting for someone to provide clear steps, since he was unable to reproduce it.

**Comment by bastik-1001** [comment]
Sandboxie-Plus 1.12.4 64bit failed to start start.exe with the message that the Lowlevel.dll could not be loaded into the process, for a confidential box type, while the rest worked fine. I reverted to 1.12.3 and the problem is gone.

**Comment by offhub** [comment]
@bastik-1001 
Did the troubleshooting script not resolve the issue?

> `Sandboxie-Plus` > `Help` > `Troubleshooting Wizard` > `Fix issues with sandboxing` > `Issues with a web browser` > Next > `Another` > Next > `SBIE2181: Failed to load SbieDll.dll` > Next

**Comment by bastik-1001** [comment]
@offhub 

I had not tried that. Now I tried 1.12.4 with the new dlls and if the troubleshooting script resolves this. The result is the same.

Just to be sure, it still works with 1.12.3, which I went back to, again.

**Comment by offhub** [comment]
@bastik-1001 Try the files in this comment.
https://github.com/sandboxie-plus/Sandboxie/issues/3503#issuecomment-1861075776

**Comment by bastik-1001** [comment]
@offhub,

I had tried them. First 1.12.4 vanilla, then 1.12.4 with new dlls. Then 1.12.4 vanilla and the new dlls with the troubleshooting script, which did not resolve it. Maybe I was not clear enough, that I tried with the replaced dlls.

**Comment by offhub** [comment]
@bastik-1001 
> Maybe I was not clear enough, that I tried with the replaced dlls. 

Sorry, I forgot.

It would be appropriate to open a separate issue for this.
