### ISSUE TITLE
Error Status: 0x0000065b (Function Failed During Execution)

### ISSUE THREAD

**Issue by Arkadiumx** [sandboxie-plus/Sandboxie#3504]
### Describe what you noticed and did

Password cannot be applied to confidential red box preset. It says "could not access BoxName.box" and asks for a new password every attempt.

I recorded a demonstration showing the steps I took to reproduce this error
https://www.youtube.com/watch?v=mbad8i1sZoc

*****UPDATE** | This can be worked around by creating a red box preset and then adding imdisk encryption password _after_ creating it. The error still exists when creating the red + black box **from the wizard**.

### How often did you encounter it so far?

Whenever trying to set box password

### Affected program

N/A

### Download link

N/A

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Create confidential box with red preset
Set password
Click run program
Prompt for password
Enter password
Access to box

### What is your Windows edition and version?

Windows 10 22H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Windows Security

### What version of Sandboxie are you running?

1.12.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

1.12.3

### In which sandbox type you have this problem?

In an encrypted sandbox (black sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

N/A

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
FileRootPath=X:\Thumbs.db\Sandbox\%SANDBOX%
TemplateReject=OfficeLicensing
TemplateReject=WindowsLive
DefaultBox=Firebox
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%

[UserSettings_0C02020A]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
BoxGrouping=:Firefox

[Firefox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#0423ee,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UsePrivacyMode=y
UseSecurityMode=y
UseFileImage=y
ConfidentialBox=y
UseFileDeleteV2=y
UseRegDeleteV2=y
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
ProtectHostImages=y
```

**Comment by offhub** [comment]
It fails because the root directory has not yet been created. (#3349)

Workaround:
Run the DefaultBox box once or create the root directory manually.

**Comment by Arkadiumx** [comment]
> It fails because the root directory has not yet been created. (#3349)
> Workaround: Run the DefaultBox box once or create the root directory manually.

It says this was fixed though? Shouldn't the box creation spawn the root directories automatically?

**Comment by DavidXanatos** [comment]
there were multiple issues and the missing root was decided to be not worth fixing as it would require some logig tu be duplicated in driver and service for very litel benefit.
But I can add a hacky solution, creating said root without adding sandbox icon or alike should be good enough and wil solve the issue without code dupliation
