### ISSUE TITLE
[Function Recovery] Recovery "Is Window Sandboxed?"

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#351]
![1](https://user-images.githubusercontent.com/56181919/104094836-58e0ee80-528b-11eb-9fea-13a2ff733139.PNG)

**Comment by DavidXanatos** [comment]
that is very messy to implement when using Qt, is that really used by anyone?

**Comment by quangkieu** [comment]
I used it to find which process throw those warnings or error dialog or windows name. I know autoit3, process explorer has these tool part of package. But it would be helpful so we do not have to includes them in portal usb
