### ISSUE TITLE
Windows Explorer has difficulty navigating when running in a sandbox with data protection enabled on Windows 11

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3517]
### Describe what you noticed and did

When you click back to go to previous folders, the content area remains the same, only the path in the address bar changes.

UsePrivacyMode=y

1. Open sandboxed Windows Explorer
2. Navigate to 'C:\Program Files (x86)\Microsoft\Edge\Application' folder by clicking
3. Try going back to previous folders by clicking back
4. The content area remains the same

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/8eb49349-c80f-426e-b768-6d190418153d

### How often did you encounter it so far?

Every time

### Affected program

Sandboxed Windows Explorer

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

It should work just like outside the sandbox.

### What is your Windows edition and version?

Windows 11 Pro 22H2 64-bit (22621.2861)

### In which Windows account you have this problem?

A local account (Administrator)., An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.12.6 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a sandbox with data protection (blue sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
UsePrivacyMode=y
```

**Comment by offhub** [comment]
Workaround:
```
UsePrivacyMode=y
ReadFilePath=explorer.exe,%ProgramData%\Microsoft\Windows\AppRepository\Packages\*
```

**Comment by DavidXanatos** [comment]
I think we need to open some subset of %ProgramData%\ in privacy enchanced boxes

**Comment by DavidXanatos** [comment]
I'll add
NormalFilePath=%ProgramData%\Microsoft\Windows\AppRepository
to the next build that location is basically like programfiles\windows apps so it needs to be accessible and shouldnt be very personal

**Comment by DavidXanatos** [comment]
After revieving the other folders there all of %ProgramData%\Microsoft\ seams to be writable only for processs with administrative privileges, hence the entire NormalFilePath=%ProgramData%\Microsoft\ should be safe to be made readable like C:\program files as there should be no personal data in that location
