### ISSUE TITLE
The sandbox is not self-cleaning

### ISSUE THREAD

**Issue by wendig0x** [sandboxie-plus/Sandboxie#3518]
### Describe what you noticed and did

1. Install LibreWolf
2. Install Mailvelope plugin for Firefox
3. Install Gpg4win in Windows
4. Configure Mailvelope to use Gpg4win
5. Configure Sandboxie to autorun when LibreWolf starts and to clean the sandbox when all programs in the sandbox are finished
6. Close LibreWolf
7. The sandbox is not self-cleaning because Gpg4win processes are still running.

### Affected program

LibreWolf

### Download link

https://mailvelope.com/  https://www.gpg4win.org/ https://librewolf.net/

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

The sandbox should terminate Gpg4win processes spawned by LibreWolf

### What is your Windows edition and version?

Win 11 22H2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.12.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by APMichael** [comment]
Have you also defined LibreWolf as the "Leader Process"?

https://sandboxie-plus.com/sandboxie/leaderprocess/

**Comment by wendig0x** [comment]
Hmmm... I'll have to create a separate sandbox for the browser:)

Yeah, its work, tnx!
