### ISSUE TITLE
OpenFilePath directories are not enumerated within their parent folders

### ISSUE THREAD

**Issue by antiufo** [sandboxie-plus/Sandboxie#3519]
### Describe what you noticed and did

1. Create a new "Sandbox with Data Protection" (leaving all the default settings)
2. Outside the sandbox, `mkdir C:\Test1` and `mkdir C:\Test2`
3. Sandbox options -> Resources -> Files -> Add `C:\Test1` as "Normal" and `C:\Test2` as "Open", save settings
4. Run `cmd` inside the sandbox
5. `dir C:\`

Actual outcome:
```
 Directory of C:\

2023-12-23  14:52    <DIR>          .
2023-12-23  14:52    <DIR>          ..
2023-12-23  14:52    <DIR>          Program Files
2023-12-23  14:52    <DIR>          Program Files (x86)
2023-12-23  14:50    <DIR>          Test1
2023-12-23  14:52    <DIR>          Users
2023-12-23  14:52    <DIR>          Windows
               0 File(s)              0 bytes
               7 Dir(s)  157,686,128,640 bytes free

```
Notice that only Test1 is visible, but not Test2.
Interestingly, if I `cd C:\Test2`, then I can use the folder as expected (creating a file inside the sandboxed cmd actually creates it in the real C:\Test2)

Additionally:
`dir C:\Te*` only displays Test1, whereas
`dir C:\Te*2` successfully displays Test2.

I discovered this issue because some programs (understandably) fail to launch if they can't see and enumerate their own parent folders

### How often did you encounter it so far?

I can reproduce it consistently

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Both `Test1` and `Test2` should be visible when `dir`'ing `C:\`

### What is your Windows edition and version?

Windows 10.0.19044.3803 (x64)

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

1.12.5

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a sandbox with data protection (blue sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=Edge_Fix
Template=Edge_Win11Fix
Template=RpcPortBindings
Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=n

[New_Box_1]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#f88501,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UsePrivacyMode=y
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
NormalFilePath=C:\Test1
OpenFilePath=C:\Test2
```

**Comment by offhub** [comment]
The same problem seems to exist with directives other than OpenFilePath. Only one item is enumerated per drive(?).
