### ISSUE TITLE
SandMan Crashes Immediately Win 11

### ISSUE THREAD

**Issue by DTrix-cut** [sandboxie-plus/Sandboxie#3520]
### Describe what you noticed and did

Sandman crashes everytime on new PC, sends crash dump.

### Affected program

NA

### Download link

NA

### Where is the program located?

Not relevant to my request.

### Expected behavior

SandMan to run.

### What is your Windows edition and version?

Windows 11 Home Version 10.0.22621 Build 22621

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Norton Security

### What version of Sandboxie are you running?

1.12.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Crash dump

https://file.io/UXDLZEIuURgP

**Comment by isaak654** [comment]
Does it work with [1.12.5](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.12.5)?

**Comment by DavidXanatos** [comment]
based on the crash dump its a already fixed issue
