### ISSUE TITLE
right click a sandbox shortcut - click run unsandboxed in order to open the file without sandbox

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#3528]
### Is your feature request related to a problem or use case?

use case:
a sandbox shortcut showing on desktop
right click on the shortcut - click run unsandboxed in order to open the file unsandboxed.

on the current situation if we right-click a sandbox shortcut and click run unsandboxed the file still runs inside sandbox

### Describe the solution you'd like

use case:
a sandbox shortcut showing on desktop
right click on the shortcut - click run unsandboxed in order to open the file unsandboxed.

on the current situation if we right-click a sandbox shortcut and click run unsandboxed the file still runs inside sandbox

**Comment by offhub** [comment]
This seems to be an issue with Windows 11 and legacy context menu items.

**Comment by offhub** [comment]
The source of this problem seems to be that the shortcuts use SandMan.exe as a launcher. Can you try changing `SandMan.exe` in the target box of the sandbox shortcut to `Start.exe`?

![sbie3528sctrgt01](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/c1abb816-5a91-4870-81f5-66f374153ac5)

**Comment by diieg707** [comment]
> The source of this problem seems to be that the shortcuts use SandMan.exe as a launcher. Can you try changing `SandMan.exe` in the target box of the sandbox shortcut to `Start.exe`?
> 
> ![sbie3528sctrgt01](https://private-user-images.githubusercontent.com/6871698/293383828-c1abb816-5a91-4870-81f5-66f374153ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjIyMDcsIm5iZiI6MTcwMzg2MTkwNywicGF0aCI6Ii82ODcxNjk4LzI5MzM4MzgyOC1jMWFiYjgxNi01YTkxLTQ4NzAtODFmNS02NmYzNzQxNTNhYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTQ1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzM2ZDczM2Q2OTJmY2Y5ODgxYzcyZWQ4ZTIxMGUzZmU0ZjNiMDRhNDQ0ZjRhZjRhNWJhZWQ4MDNlYjg4YjA1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GgFrtOTfZaeklQHz4MI9XfpxQKbHBJFLBU7qs1iPfXE)

hi, i changed and it worked

**Comment by diieg707** [comment]
@offhub can you tell the @DavidXanatos to fix this thing so we wouldn't have to do this all the time?

**Comment by Taeyeonzpx** [comment]
> > The source of this problem seems to be that the shortcuts use SandMan.exe as a launcher. Can you try changing `SandMan.exe` in the target box of the sandbox shortcut to `Start.exe`?
> > ![sbie3528sctrgt01](https://private-user-images.githubusercontent.com/6871698/293383828-c1abb816-5a91-4870-81f5-66f374153ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjIyMDcsIm5iZiI6MTcwMzg2MTkwNywicGF0aCI6Ii82ODcxNjk4LzI5MzM4MzgyOC1jMWFiYjgxNi01YTkxLTQ4NzAtODFmNS02NmYzNzQxNTNhYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTQ1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzM2ZDczM2Q2OTJmY2Y5ODgxYzcyZWQ4ZTIxMGUzZmU0ZjNiMDRhNDQ0ZjRhZjRhNWJhZWQ4MDNlYjg4YjA1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GgFrtOTfZaeklQHz4MI9XfpxQKbHBJFLBU7qs1iPfXE)
> 
> hi, i changed and it worked

The shortcuts created before were all using SandMan.exe. Do I need to modify all the previous shortcuts to Start.exe?

**Comment by Taeyeonzpx** [comment]
> 此问题的根源似乎是快捷方式使用 SandMan.exe 作为启动器。您可以尝试将`SandMan.exe`沙箱快捷方式的目标框中更改为吗`Start.exe`？
> 
> ![sbie3528sctrgt01](https://private-user-images.githubusercontent.com/6871698/293383828-c1abb816-5a91-4870-81f5-66f374153ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjQ1ODcsIm5iZiI6MTcwNDQyNDI4NywicGF0aCI6Ii82ODcxNjk4LzI5MzM4MzgyOC1jMWFiYjgxNi01YTkxLTQ4NzAtODFmNS02NmYzNzQxNTNhYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDMxMTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTRjMGRiMGU2ZjQxYjcwMmI0YmIwYTY4OGQ0YTUyMzljZjkyMDIyMWY0ODkzNmQyYzU1YjQ3M2IwMThiOWRiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lB8pAUPjuTm7dDctrlmGG14rlgUD9QjJug1yt-5dNbc)

The shortcuts created before were all using SandMan.exe. Do I need to modify all the previous shortcuts to Start.exe?

**Comment by Taeyeonzpx** [comment]
> The source of this problem seems to be that the shortcuts use SandMan.exe as a launcher. Can you try changing `SandMan.exe` in the target box of the sandbox shortcut to `Start.exe`?
> 
> [![sbie3528sctrgt01](https://private-user-images.githubusercontent.com/6871698/293383828-c1abb816-5a91-4870-81f5-66f374153ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjQ3OTgsIm5iZiI6MTcwNDQyNDQ5OCwicGF0aCI6Ii82ODcxNjk4LzI5MzM4MzgyOC1jMWFiYjgxNi01YTkxLTQ4NzAtODFmNS02NmYzNzQxNTNhYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDMxNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2MxMGNlODc0NDJhMWExYjhjZTY5ODUzMDczNDYxYWMwZGE0ZjU4YzNmN2I1ZDA5YWI1NmUzZGMyOTA0ZjA0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qDkdLu1O93E86aTnytq-YictBFa0tq1VMxRprNQrAfA)](javascript:void(0))

The shortcuts created before were all using SandMan.exe. Do I need to modify all the previous shortcuts to Start.exe?

**Comment by DavidXanatos** [comment]
the issue will be fixed int he next build but pelase not that the shelle xtensions will need to be re registered for the fix to work, that is uncheck apply check apply done
