### ISSUE TITLE
Can’t connect to spotify with sandboxie

### ISSUE THREAD

**Issue by antho1703** [sandboxie-plus/Sandboxie#3538]
### Describe what you noticed and did

When launching spotify in a standard sandbox on sandboxie when clicking on connection no web page works

### How often did you encounter it so far?

ALL

### Affected program

Spotify

### Download link

https://www.spotify.com/fr/download/windows/

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Help for connexion

### What is your Windows edition and version?

Windows 10 22H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.12.6

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Sandboxie Classic 5.57.7

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by antho1703** [comment]
![image](https://github.com/sandboxie-plus/Sandboxie/assets/98899553/8b6552e4-67ba-48cb-a54e-a7a24ddd783b)

![image](https://github.com/sandboxie-plus/Sandboxie/assets/98899553/d4b64c32-20db-4f4e-8544-6e18aa84cc90)

Nothing start ..

**Comment by Dyras** [comment]
Does it work if you install Spotify inside the sandbox?

**Comment by isaak654** [comment]
#2673

**Comment by antho1703** [comment]
> Est-ce que ça marche si vous installez Spotify dans le bac à sable ?

No

**Comment by kokofixcomputers** [comment]
Can you tell me your setup?

**Comment by kokofixcomputers** [comment]
Or update then try again?

**Comment by kokofixcomputers** [comment]
If it works please close this issue

**Comment by antho1703** [comment]
> Si cela fonctionne, veuillez fermer ce problème

I found solution on forum thanks to DisableRTBlacklist=y

**Comment by antho1703** [comment]
> ### Décrivez ce que vous avez remarqué et fait
> Lors du lancement de Spotify dans un sandbox standard sur sandboxie en cliquant sur la connexion, aucune page Web ne fonctionne
> 
> ### À quelle fréquence l’avez-vous rencontré jusqu’à présent ?
> TOUS
> 
> ### Programme concerné
> Spotify
> 
> ### Lien de téléchargement
> https://www.spotify.com/fr/download/windows/
> 
> ### Où se trouve le programme ?
> Le programme est installé uniquement en dehors du bac à sable.
> 
> ### Comportement attendu
> Aide pour la connexion
> 
> ### Quelle est votre édition et version de Windows ?
> Windows 10 22H2
> 
> ### Dans quel compte Windows avez-vous ce problème ?
> Un compte local (Administrateur).
> 
> ### Veuillez mentionner tout logiciel de sécurité installé
> Windows Defender
> 
> ### Quelle version de Sandboxie utilisez-vous ?
> Sandboxie Plus 1.12.6
> 
> ### Est-ce une nouvelle installation de Sandboxie ?
> J'ai récemment fait une nouvelle installation propre.
> 
> ### Est-ce une régression ?
> Sandboxie Classique 5.57.7
> 
> ### Dans quel type de bac à sable rencontrez-vous ce problème ?
> Dans un bac à sable d'isolation standard (icône de bac à sable jaune).
> 
> ### Pouvez-vous reproduire ce problème sur un nouveau bac à sable vide ?
> Je peux également le confirmer sur un nouveau bac à sable vide.
> 
> ### Avez-vous déjà activé certains paramètres de stratégie de sécurité en dehors de Sandboxie ?
> _Pas de réponse_
> 
> ### Décharge sur incident
> _Pas de réponse_
> 
> ### Journal de suivi
> _Pas de réponse_
> 
> ### Configuration de Sandboxie.ini
> _Pas de réponse_

**Comment by m4tbuz** [comment]
hello I actually have the same problem I have the latest version of sandboxie and windows 11 I really need your help
THANKS
