### ISSUE TITLE
Make it possible to disable forced folder warning

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3569]
### Is your feature request related to a problem or use case?

With the implementation of #650, Sandman warns when a user selects a folder that could be too broad and cause issues, when being forced.

I added re-enabled a previously set forced folder and set a new forced folder to an already created box. Both are located at C:\Program Files\ (e.g. Program Files\LibreOffice). I got warned, twice, that this could break Windows, which I would not assume to be the case.

### Describe the solution you'd like

I'd like to be able to disable the warning, either by selecting, "Yes, I know that I could break stuff. I know what I am doing, don't show it again." or by some setting in the ini, like `iknowwhatiamdoing=y`

### Describe alternatives you've considered

Fine-tuning the warning to be shown, only if the user selected a folder that is really at risk at breaking Windows. (The warning in itself is useful, but it might also scare some, even if that is not intended.)

**Comment by DavidXanatos** [comment]
ups the filter was to broad now it should only warn for C:\ and C:\windows\*
