### ISSUE TITLE
Translation for Quick Recovery is not shown

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#357]
From Line 483

> %1 is eligible for quick recovery from %2.
The file was written by: %3

Is translated into German, but with 0.5.4b it is not displayed in the UI. It was also not shown before, but I had assumed the string to have been replaced before I updated the language.

**Comment by DavidXanatos** [comment]
that must be used in CPopUpWindow::AddFileToRecover
