### ISSUE TITLE
Sandman, suspend all processes

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3582]
### Is your feature request related to a problem or use case?

Right now, it is possible to terminate all processes via a menu entry or hotkey (if set). The same functionality can be useful for suspending all processes.

### Describe the solution you'd like

A menu entry, probably in the sandbox menu, to suspend and another to resume all processes. And hotkeys to do that, as well.

### Describe alternatives you've considered

Just suspending all processes, having the user to resume the processes manually.

**Comment by bastik-1001** [comment]
Sandboxie 1.13.1 (64bit) on Windows 7 can use hotkeys, like making SandMan topmost, but the shortcut to suspend all processes (I tried several, CTRL-ALT-Y or CTRL-ALT-Z) does not seem to have any effect. It does not matter if Sandboxie has key focus or not.

**Comment by isaak654** [comment]
@bastik-1001 The title of this issue is rather incomprehensible, could you fix it according to the changes introduced in 1.13.1?
