### ISSUE TITLE
[Plus UI] Notification window is stuck when a modal dialog shows up

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#3586]
### Affected program

Sandboxie Plus 1.12.7 x64 and lower versions.

### Describe what you noticed and did

1. Copy and paste the following lines in Templates.ini file:
```
[Template_Explorer_fix]
Tmpl.Title=Explorer fix for Windows 11
Tmpl.Class=Misc
Tmpl.ScanScript=if(system.version().major == 11) return true;
FakeAdminRights=explorer.exe,n
```
2. Apply the line `Template=Explorer_fix` in the [GlobalSettings] section of Sandboxie.ini
2. Reinstall Sandboxie Plus to restore the Templates.ini file back to its default state
3. Run SandMan.exe
4. Go to Options menu -> Reload configuration
5. According to the notification window below, there is a missing template set globally (this is expected because I've reinstalled Sandboxie Plus in step three), but the real issue is the window itself getting in the way without the ability to hide, move, resize or even close it:

<img alt="Sandboxie Plus notification window" src="https://github.com/sandboxie-plus/Sandboxie/assets/12372772/c93c3b06-bf29-4c52-9156-2846f5ac36c5" height="150px">

Furthermore, only with the ALT+TAB keyboard shortcut I can get around it by switching to the following modal dialog asking for precedence:

<img alt="Sandboxie Plus dialog for missing template" src="https://github.com/sandboxie-plus/Sandboxie/assets/12372772/cec1ba23-ca75-49a1-b9e3-fe8977749bb7" height="150px">

This is clearly not intuitive, as well as annoying.

### Expected behavior

The notification window should not be in foreground when a modal dialog shows up.

**Comment by DavidXanatos** [comment]
with the latest fix when the notification window Stops being top most (5 sec having been showed) the message box will be forced to front.

**Comment by isaak654** [comment]
Personally I struggle to find any use in displaying the notification window for 5 seconds without being able to do anything with it, as if it were a time-based splash screen that had to be read. So far, in my opinion, it is only a partial fix at best.

**Comment by isaak654** [comment]
Personally I struggle to find any use in displaying the notification window without being able to do anything with it, as if it were a time-based splash screen that must be read with nowhere to click. This time, the notification window remains stuck for 5 seconds, so at best it is a partial fix.

**Comment by isaak654** [comment]
Personally I struggle to find any use in displaying the notification window without being able to do anything with it, as if it were a time-based splash screen that must be read with nowhere to click. This time the notification window remains stuck for 5 seconds, so at best it is a partial fix.

**Comment by DavidXanatos** [comment]
Well I agree, the thing is that while we use Qt to bring the Notification window in front we use direct Windows API calls.
So we generate a certain inconsistency, Qt thinks the Message Box Dialog is on top but windows keeps the Notification window on top even after we have cleared the TopMost flag.

I see to possible fixes:
1. When Notification window is TopMost and we see a message box being there we make it TopMost as well
2. We remove the message box entirely and move the template cleanup to the Troubleshooting wizard

Probably option 2 would be most elegant

**Comment by DavidXanatos** [comment]
I improved the current fix now the delay is only 1 sec,
still think option 2 is what we should do in the long run

**Comment by isaak654** [comment]
I think it's acceptable now, thanks for the effort.
