### ISSUE TITLE
"Sandbox with Data Protection and Security Hardening" cannot be invoked and run by right-clicking on the shortcut on the desktop and selecting "Run in Sandbox" / right-clicking on "Sandboxie Plus User Interface - Run - Standard Application".

### ISSUE THREAD

**Issue by RimacC2-EV** [sandboxie-plus/Sandboxie#3590]
### Describe what you noticed and did

<img width="342" alt="image" src="https://github.com/sandboxie-plus/Sandboxie/assets/125170682/422ca682-8a50-46c4-a202-76a4ff067f8b">
1,Create a new "Sandbox with Data Protection and Security Hardening",
2,Select the virtualization solution as Version 2,
3,disable network access and check "Make the app think it's running with admin privileges".
4,Click "Done".
5,Right-click on the shortcut on the desktop and select "Run in Sandbox" / Right-click on the Sandboxie Plus user interface and right-click on the "Sandbox with Data Protection and Security Hardening" you just created and select "Run - Standard Application" in the context menu to check if you get the same error.

### How often did you encounter it so far?

Whenever I do the above action

### Expected behavior

The sandbox should open shortcuts on the desktop/run standard applications (e.g. default browser, Windows Explorer, etc.) as normal

### Affected program

Shortcuts to all programs

### Download link

Not available

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.12.7 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a hardened sandbox with data protection (red sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows Home China 21H2 64-bit

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Microsoft Defender Antivirus，360 Total Security

### Trace log

Sorry, I can't open the website.

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=Edge_Fix
Template=OfficeClickToRun
Template=OfficeLicensing
Template=QQ
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_02DE00F4]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
BoxGrouping=:DefaultBox,New_Box,New_Box_1,New_Box_2

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10

[New_Box]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#e8e803,ttl
Template=RpcPortBindingsExt
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UsePrivacyMode=y
NoSecurityIsolation=y
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y

[New_Box_1]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
DropAdminRights=y
FakeAdminRights=y

[New_Box_2]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#0423ee,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UsePrivacyMode=y
UseSecurityMode=y
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
DropAdminRights=y
FakeAdminRights=y
NotifyProcessAccessDenied=y
InjectDll=\addons\LogAPI\logapi32.dll
InjectDll=\addons\SbieHide\SbieHide.x86.dll
InjectDll64=\addons\LogAPI\logapi64.dll
InjectDll64=\addons\SbieHide\SbieHide.x64.dll
ProtectHostImages=y
```

**Comment by offhub** [comment]
You must open the application's working folder with the `NormalFilePath` directive. [****](https://sandboxie-plus.github.io/sandboxie-docs/PlusContent/privacy-mode.html)

```
NormalFilePath=%AppData%\secoresdk\360se6\Application\
```
