### ISSUE TITLE
Unable to start File Explorer from sandboxed cmd.exe [bug]

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#362]
v0.5.4b Win 10 Pro

Reproduce:
1. Create new sandbox
2. Start cmd.exe inside sandbox
3. On command prompt, enter "explorer" <ENTER>
4. Sandboxie shows error:
`SBIE2224 Sandboxed program has crashed: explorer.exe [AAA]`

The above happens on my physical PC. Doing the same in Windows 10 Sandbox results in explorer.exe briefly starting up and then silently exiting.

Notes:
* I can start notepad.exe from sandboxed command prompt just fine
* I can start sandboxed File Explorer from the sandboxie context menu
* This used to work with some older version of sandboxie

**Comment by DavidXanatos** [comment]
Normaly explorer just tries to eider set itself up as shell or use an existing explorer instance to open a folder window. 
I know that a very old sbie version like 3.xx or earlier used to fake some registry keys to make explorer think a custom shell is installed.
But the current version don't do that anymore instead it uses some explorer start parameters to get the desired behavior.

to get explorer to run properly you need to start it like this ```explorer.exe /e,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}```
