### ISSUE TITLE
Revert or provide a way to opt out of the new sandbox directory structure for volumes without drive letters

### ISSUE THREAD

**Issue by benrg** [sandboxie-plus/Sandboxie#3632]
### Is your feature request related to a problem or use case?

Before recent versions of Sandboxie Plus, the overlay filesystem tree for a volume mounted at `D:\path\descriptive-name-of-mount-point` was located at `SandboxName\drive\D\path\descriptive-name-of-mount-point`. After recent changes, it's located at `SandboxName\drive\{1d4c338a-fe94-420c-9435-337eed8a97bb}`.

I prefer the old scheme because:

* The fact that you can give a unique descriptive name to a mount point instead of a single letter is a notable advantage of directory mount points. I don't want to have to remember which random GUID corresponds to which directory.
* Under the old scheme, you can box up the contents of a directory into a container volume, mount it at the location of the old directory, and generally not break things. With the new directory structure one has to hunt down any sandbox that has overlay modifications to that directory subtree and move the subtree to the new GUID location (provided that one can figure out the correct GUID—I do know how to do that but it's not obvious).
* I don't think I want overlay files to follow the mount point if I move it, which seems to be the only advantage of the new scheme. That might be useful for removable volumes mounted on drive letters since contention for letters can lead to them being mounted at different places (and I see now that a `UseVolumeSerialNumbers` option has existed for a while to deal with that), but that doesn't happen with named mount points.

### Describe the solution you'd like

Any one of

* Revert the change for everyone (I think most users wouldn't notice)
* A per-sandbox option to get the old behavior (in sandboxie.ini; I don't care whether it's exposed in the GUI)
* A per-sandbox option to ignore all outside-sandbox reparse points (mount points, junctions, and symlinks) and just store every overlay file at its apparent location in the directory tree and not its final resolved location, since I think that's actually the behavior I want most of the time

**Comment by DavidXanatos** [comment]
I see how this might be useful but it also might be a big problem when you mount the same volume into two different directories
trying to make this switchable complicates things quite a bit.
I'm looking into it right now and we may need to roll back some of the recent changes and retool some of the path handling to make it flexible.

Generally I like the idea of more flexibility so lets see how doable this will be.

**Comment by DavidXanatos** [comment]
With build 1.3.1 the old behavioure will be reverted as default and to use the new 1.12.x behavioure one needs to add UseVolumeGuidWhenNoLetter=y to the sandboxie ini.
I wont add yet a UI checkbox yet.
