### ISSUE TITLE
Update from within SandMan does not work properly

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3634]
### Describe what you noticed and did

> [!NOTE]
> Try with a non-portable and non-debugging version installation. The supporter certificate must be entered and a valid SandMan.exe.sig must be present.

1. Check for updates
2. Click Yes to start the installation
3. SandMan.exe will close without running the installer
4. Rename SandMan.exe.sig to SandMan.exe.sig_.
5. Restart SandMan.exe
6. Repeat the first two steps
7. This time the installer will start successfully

https://www.wilderssecurity.com/threads/sandboxie-plus-v1-12-8-v1-12-9.453446/page-2#post-3184431
https://forum.xanasoft.com/viewtopic.php?f=12&t=740

### How often did you encounter it so far?

Every time

### Expected behavior

SandMan.exe should run the installer when it closes.

### Affected program

Sandboxie Plus

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.12.9 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.4046)

### In which Windows account you have this problem?

A local account (Administrator)., A Microsoft account (Administrator)., An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

**Comment by DavidXanatos** [comment]
is this issue stil present in 1.13.5 ?

**Comment by offhub** [comment]
If the installer comes with a valid signature file, the installation will work properly. Most likely, the required signature files were not available on the server when this problem occurred. Tested with 1.13.0 -> 1.13.3 -> 1.13.5.

**Comment by DavidXanatos** [comment]
perhaps then I'll close this one
