### ISSUE TITLE
Expectations regarding the characteristics of the system that prevent the program from interfering with power operation

### ISSUE THREAD

**Issue by love-code-yeyixiao** [sandboxie-plus/Sandboxie#3640]
### Is your feature request related to a problem or use case?

Some of the programs running in the sandbox may interfere with some of the power operations of the system by calling the apis provided by windows, such as screen savers, automatic system locking, and so on. It is also possible to delay system logout by receiving Windows messages. But sometimes we don't want them to affect our behavior.I would like to include a check option for this feature in the security Settings of the sandbox option.

### Describe the solution you'd like

Hook the SetThreadExecutionState function on the user-mode application in the sandbox, returning an error directly. The Windows message hook (SETWINDOWSHOOKEX series functions) is used to discard the WM_QUERYENDSESSION messages received by the window process of the program in the sandbox and the WM_QUERYENDSESSION messages in the message queue.

**Comment by offhub** [comment]
CI build: https://github.com/sandboxie-plus/Sandboxie/actions/runs/8130377450

When you run any program:

```
SandboxieRpcSs.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
SandboxieRpcSs.exe: SBIE2303 Could not hook GetClassNameA (1)
SandboxieRpcSs.exe: SBIE2303 Could not hook AttachThreadInput (1)
SandboxieRpcSs.exe: SBIE2318 DLL initialization failed for 'user32.dll'
SandboxieDcomLaunch.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
SandboxieDcomLaunch.exe: SBIE2303 Could not hook GetClassNameA (1)
SandboxieDcomLaunch.exe: SBIE2303 Could not hook AttachThreadInput (1)
SandboxieDcomLaunch.exe: SBIE2318 DLL initialization failed for 'user32.dll'
Start.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
Start.exe: SBIE2303 Could not hook GetClassNameA (1)
Start.exe: SBIE2303 Could not hook AttachThreadInput (1)
Start.exe: SBIE2318 DLL initialization failed for 'user32.dll'
cmd.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
cmd.exe: SBIE2303 Could not hook GetClassNameA (1)
cmd.exe: SBIE2303 Could not hook AttachThreadInput (1)
cmd.exe: SBIE2318 DLL initialization failed for 'user32.dll'
```

**Comment by love-code-yeyixiao** [comment]
> CI build: https://github.com/sandboxie-plus/Sandboxie/actions/runs/8130377450
> 
> When you run any program:
> 
> ```
> SandboxieRpcSs.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
> SandboxieRpcSs.exe: SBIE2303 Could not hook GetClassNameA (1)
> SandboxieRpcSs.exe: SBIE2303 Could not hook AttachThreadInput (1)
> SandboxieRpcSs.exe: SBIE2318 DLL initialization failed for 'user32.dll'
> SandboxieDcomLaunch.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
> SandboxieDcomLaunch.exe: SBIE2303 Could not hook GetClassNameA (1)
> SandboxieDcomLaunch.exe: SBIE2303 Could not hook AttachThreadInput (1)
> SandboxieDcomLaunch.exe: SBIE2318 DLL initialization failed for 'user32.dll'
> Start.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
> Start.exe: SBIE2303 Could not hook GetClassNameA (1)
> Start.exe: SBIE2303 Could not hook AttachThreadInput (1)
> Start.exe: SBIE2318 DLL initialization failed for 'user32.dll'
> cmd.exe: SBIE2303 Could not hook SetThreadExecutionState (0)
> cmd.exe: SBIE2303 Could not hook GetClassNameA (1)
> cmd.exe: SBIE2303 Could not hook AttachThreadInput (1)
> cmd.exe: SBIE2318 DLL initialization failed for 'user32.dll'
> ```

The function in the first line of the error message does not exist in "user32.dll" ,I will revise it when I have time.

**Comment by DavidXanatos** [comment]
i commited a fix for this issue

**Comment by bastik-1001** [comment]
Is this issue still requiring work, or could it be closed?

**Comment by love-code-yeyixiao** [comment]
I think it could be closed.



---Original---
From: "Sebastian ***@***.***&gt;
Date: Thu, Mar 21, 2024 02:28 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [sandboxie-plus/Sandboxie] Expectations regarding thecharacteristics of the system that prevent the program from interfering withpower operation (Issue #3640)




 
Is this issue still requiring work, or could it be closed?
