### ISSUE TITLE
DisproveWinNtSysCall

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3641]
### Is your feature request related to a problem or use case?

Ever since `ApproveWinNtSysCall` got added, I toyed with the idea of having DisproveWinNtSysCall which does the opposite and trumps `ApproveWinNtSysCall`, since that is built-in and removing an `ApproveWinNtSysCall` entry from the template is only temporal and also might be needed for some application. This was meant as a way to fine tune what a process in a certain sandbox can do.

### Describe the solution you'd like

Adding `DisproveWinNtSysCall` to be added per sandbox, like `My-own-box` with the line `DisproveWinNtSysCall=CreateMailslotFile`, for example.

This appears to apply only to hardened type boxes.

**Comment by DavidXanatos** [comment]
The problem is that this settings are not per sandbox but only global, so it would be quite a rework to make this be configurable per box.

**Comment by bastik-1001** [comment]
Since it was just an idea and not something I have a practical application or need for, I am not requesting this feature, due to it being work that is not really needed. If someone else wants this, please comment. I am going to close this, but if there is still interest it can be opened again or someone might create a new issue.
