### ISSUE TITLE
[NOT AN ISSUE]

### ISSUE THREAD

**Issue by User5959** [sandboxie-plus/Sandboxie#365]
So I  am forced to use this sketchy  program called zoom and it's unencrypted  so can Sandboxie Plus protect me from it, like if a attacker tries to inject malware into my computer through it so will Sandboxie prevent that malware from running on my main computer

**Comment by quangkieu** [comment]
From my understand, they are public company so there is less of reason they become attacker. But you need more worry that they collect your information as there is somewhat connection to Chinese government.
You could set sandboxie to lock down most folder, its process visibility to your system.
But I would suggest to run it in full virtual machine like built-in Windows Sandbox, Hyper-V, VMware, VirtualBox.
As you still need at least to run Explore and mostly you have to open AppData path, which most of your info in there. Zoom could pull thing in there

**Comment by quangkieu** [comment]
@DavidXanatos, I wonder if you have any template for these kind of setting to lock down the visibility of all thing? I guess windows user name will be visible as it part of the path.

**Comment by DavidXanatos** [comment]
@quangkieu 
Anonymouse boxes its something on my todo, hide username and redirect all accesses to an empty/dummy user profile

**Comment by User5959** [comment]
@quangkieu  How to set Sandboxie to lockdown folders?
