### ISSUE TITLE
"Recycle bin for drive * is corrupted"

### ISSUE THREAD

**Issue by Arkadiumx** [sandboxie-plus/Sandboxie#3665]
### Describe what you noticed and did

I've only noticed this happening on my cyan box for stable diffusion. The only things installed to that box are SD Automatic1111, Git, and Python 3.10.10

Adding "NormalFilePath=[Drive]:\$Recycle.Bin" for both of my sandboxed drives works as a temp fix but I don't know what that does exactly and I'd like to fix the corrupted message if possible instead. Or atleast disable the message or recycle bin entirely.

The popup message is very disruptive since it always appears ontop and pops up alot when cicking on things in sandboxed explorer.

### How often did you encounter it so far?

Every time I make a cyan box and install the mentioned programs.

### Expected behavior

Recycle bin to work normally as it does in other boxes

### Affected program

Sandboxie

### Download link

Not Relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.12.9

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In an Application Compartment sandbox with data protection (cyan sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

WIndows 10 Pro 22H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Defender

**Comment by DavidXanatos** [comment]
this is not a good workaround as it allows sandboxed programs to read the content of the recycle bin which may contain personal data.
I'm looking into a better fix right now.

**Comment by DavidXanatos** [comment]
with build 1.13.2 this was added to the PMod template
´´´
NormalFilePath=?:\$Recycle.Bin\*
WriteFilePath=?:\$Recycle.Bin\**\*
´´´

this opens only access to the bin folder but not to any files stored within it outside the sandbox.
this to work required support for the new ** placeholder 
with earlier builds usage of the above directives will open access to deleted files outside of teh sandbox

**Comment by Arkadiumx** [comment]
Do I need to use 1.13.2 for this to work? How do I add it?

**Comment by isaak654** [comment]
> Do I need to use 1.13.2 for this to work? How do I add it?

You can check the fix with one of the following steps:

1. Copy and paste the three lines above into the local Templates.ini file of your Sandboxie installation.
2. Go to the [Templates.ini](https://github.com/sandboxie-plus/Sandboxie/blob/71adb2f8599855fde933cd2b7cd64427d714666a/Sandboxie/install/Templates.ini) source file, download it from the down arrow button and overwrite it in your local Sandboxie installation.
3. Update Sandboxie Plus to version [1.13.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.13.2).

**Comment by isaak654** [comment]
> Do I need to use 1.13.2 for this to work? How do I add it?

You can check the fix with one of the following steps:

1. Copy and paste the three lines above into the local Templates.ini file of your Sandboxie installation.
2. Go to the [Templates.ini](https://github.com/sandboxie-plus/Sandboxie/blob/71adb2f8599855fde933cd2b7cd64427d714666a/Sandboxie/install/Templates.ini) source file URL, download it from the down arrow button and overwrite it in your local Sandboxie installation.
3. Update Sandboxie Plus to version [1.13.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.13.2).

**Comment by isaak654** [comment]
> Do I need to use 1.13.2 for this to work? How do I add it?

You can check the fix with one of the following steps:

1. Copy and paste the three lines above into the local Templates.ini file of your Sandboxie installation.
2. Go to the [Templates.ini](https://github.com/sandboxie-plus/Sandboxie/blob/71adb2f8599855fde933cd2b7cd64427d714666a/Sandboxie/install/Templates.ini) source file link, download it from the down arrow button and overwrite it in your local Sandboxie installation.
3. Update Sandboxie Plus to version [1.13.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.13.2).

**Comment by isaak654** [comment]
> Do I need to use 1.13.2 for this to work? How do I add it?

You can check the fix with one of the following steps:

1. Copy and paste the three lines above into the local Templates.ini file of your Sandboxie installation.
2. Go to the [Templates.ini](https://github.com/sandboxie-plus/Sandboxie/blob/71adb2f8599855fde933cd2b7cd64427d714666a/Sandboxie/install/Templates.ini) source file link, download the file from the down arrow button and overwrite it in your local Sandboxie installation.
3. Update Sandboxie Plus to version [1.13.2](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.13.2).

**Comment by offhub** [comment]
@DavidXanatos 

I get this error when these settings are in the Templates.ini file. However, if these settings are in a different location (box, global or template), I do not get an error.

**Comment by DavidXanatos** [comment]
where in the Templates.ini ? the TemplatePModPaths is only included in privacy enchanced boxes

**Comment by offhub** [comment]
Under TemplatePModPaths.
