### ISSUE TITLE
Automatic start Sandboxie

### ISSUE THREAD

**Issue by D1mar0n** [sandboxie-plus/Sandboxie#367]
Good day! Please add the ability to disable the launch of the program with the system. Previously, it was possible to configure the service to start manually and disable the automatic launch of the program, but when the context menu was right-clicked on the application and launched, the "Sandboxie Management" was launched and the selected program was launched in it. Now this does not work, you need to first start the "Sandboxie Management" yourself, and then start the program selected to run in the "Sandboxie" program.

I also want to ask if you have any plans to make "Sandboxie Plus" multilingual? Thank you in advance.

**Comment by BurntDog** [comment]
There is a option to check or uncheck in settings, unless you mean the driver/service.

**Comment by D1mar0n** [comment]
Thanks!!! 👍
На 12.01.2021 15:52:35, BurntDog <notifications@github.com> писал:
There is a option to check or uncheck in settings, unless you mean the driver/service.

**Comment by bastik-1001** [comment]
There are already translations for the plus version.

> 
    yuhao2348732 - ZH
    nkh0472 - CN
    bastik-1001 - DE (NewKidOnTheBlock as well for the not yet released spelling mistakes)
    JNylson - PT
    lufog - RU

**Comment by D1mar0n** [comment]
Good day! Yesterday I installed Sandboxie Plus version. When launching programs in it, the program window does not have a yellow frame, as in the classic version. Is this how it should be or is it a mistake?
На 12.01.2021 20:41:14, Dima Ivanov <dimaivanov2001@gmail.com> писал:
Отличная новость! Из из России. Спасибо за русскую локализацию.👍
На 12.01.2021 18:52:01, Sebastian G. <notifications@github.com> писал:
There are already translations for the plus version.
yuhao2348732 - ZH nkh0472 - CN bastik-1001 - DE (NewKidOnTheBlock as well for the not yet released spelling mistakes) JNylson - PT lufog - RU

**Comment by DavidXanatos** [comment]
start sandman.exe on sandboxed process launch will be added to the next build

the yellow border should be working check your settings and if sandman.exe is running

**Comment by D1mar0n** [comment]
Thanks. Works fine. 👍

Отправлено с iPhone
