### ISSUE TITLE
Too many SBIE1242 notifications when running some program in Sandboxie-Plus, and it doesn't show any detail

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#368]
For example, run VMWare Workstation Pro 16.1.0 and start a VM: 
![1](https://user-images.githubusercontent.com/56181919/104299296-f40cda80-54bc-11eb-91d4-b23531d31d0f.png)

**Comment by DavidXanatos** [comment]
That one indicated a resource access monitor log overflow,
disable resource logging

**Comment by 0x391F** [comment]
Could Sandboxie-Plus add some options so that users could choose:

1. Wipe oldest line

or

2. Stop logging and show a messge. 

Only need to show 1 message because too many message will cause very high CPU usage.

**Comment by DavidXanatos** [comment]
Yea... will have to think about how to improve that.

**Comment by 0x391F** [comment]
By the way, it would be better if add a option to set monitor buffer size.

**Comment by DavidXanatos** [comment]
we have now an option to set the buffer size
