### ISSUE TITLE
Sandboxie-Plus fails to connect to driver after update.

### ISSUE THREAD

**Issue by RimacC2-EV** [sandboxie-plus/Sandboxie#3689]
### Describe what you noticed and did

1. Download the old version of Sandboxie-Plus.
2. Download the update package and install it (Sandboxie-Plus is open/uninstalled before running the program).
3. After the update is complete, open Sandboxie-Plus.
4. When the GUI loads, it will show a window that says "Unable to connect to driver"
5. The problem is reproduced,and Sandboxie-Plus cannot be used normally.(It will be fixed after a reboot, so I advise to add a reboot request window to fix the problem.And because of this,it may not be an issue)

### How often did you encounter it so far?

Whenever I update the Sandboxie-Plus

### Expected behavior

Sandboxie-Plus runs normally / requests a restart to apply its changes.

### Affected program

Sandboxie-Plus itself.

### Download link

Not available

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

Yes, it did, but no .dmp file has been created in the system.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.13.2 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### Is it a regression from previous versions?

Yes,the problem has stayed since the version 1.12.7

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows Home China 21H2 64-bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Defender Antivirus，360 Total Security

### Trace log

Sorry, I can't open the website.

### Sandboxie.ini configuration

```shell
Unavailable
```

**Comment by bastik-1001** [comment]
> (...) I advise to add a reboot request window to fix the problem.

Please, let's only reboot if that is necessary.

**Comment by RimacC2-EV** [comment]
However,this may affect some registry keys that work after a restart······ We may need some explanation from the maintainers.
@DavidXanatos @isaak654

**Comment by DavidXanatos** [comment]
I think clicking on start service in the maintenance menu would have solved that as well no need for a forced restart

**Comment by RimacC2-EV** [comment]
Now the error has been resolved. But while I was testing the bug, Sandboxie-Plus sent some .dmp files and crashed······ I don't know if I've broken Sandboxie-Plus······ 
[SandMan-v1.13.2 11.03.2024 13-13-31,914.dmp](https://github.com/sandboxie-plus/Sandboxie/files/14553822/SandMan-v1.13.2.11.03.2024.13-13-31.914.dmp)
@DavidXanatos 
[SandMan-v1.13.2 11.03.2024 13-17-20,955.dmp](https://github.com/sandboxie-plus/Sandboxie/files/14553825/SandMan-v1.13.2.11.03.2024.13-17-20.955.dmp)
[SandMan-v1.13.2 11.03.2024 13-17-20,695.dmp](https://github.com/sandboxie-plus/Sandboxie/files/14553827/SandMan-v1.13.2.11.03.2024.13-17-20.695.dmp)

**Comment by DavidXanatos** [comment]
is the issue still present?

**Comment by RimacC2-EV** [comment]
> is the issue still present?

No, the probability of this issue appearing may be greatly reduced (or it has already been fixed), these crash dumps are additional bugs that I triggered when debugging the issue (one of the bugs has been repeated twice) and I want to send it to you to see them.
