### ISSUE TITLE
Apps are running very slowly in Sandboxie

### ISSUE THREAD

**Issue by User5959** [sandboxie-plus/Sandboxie#369]
Apps are running extremely slow in Sandboxie my device's information is:

Processor	AMD A9-9420e RADEON R5, 5 COMPUTE CORES 2C+3G     1.80 GHz
Installed RAM	4.00 GB (3.83 GB usable)
Device ID	7A1F8551-538E-4053-9082-050005DB335E
Product ID	00327-35178-75414-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by bastik-1001** [comment]
What kind of apps are you using with Sandboxie?

My computer is also no longer considered powerful, but I can use the browser, a word processor and image viewer without really noticing in. With a video player I can feel that it is slower, so I don't use Sandboxie with that.

**Comment by User5959** [comment]
I am using zoom cloud meetings in a Sandboxie environment
