### ISSUE TITLE
Permanently Re-sizable or Larger "Run Sandboxed" Window

### ISSUE THREAD

**Issue by ThioJoe** [sandboxie-plus/Sandboxie#3697]
### Problem

When using the Windows context menu "Run Sandboxed" option, the window that pops up is very narrow and can cut off the names of sandboxes.

I'd like to systematically name sandboxes like "App Compartment 1" , "App Compartment Private 1", etc. But it was cutting off the ends of the names so I had to adjust the names, otherwise I'd have to expand the window to see every time.

See video example
https://github.com/sandboxie-plus/Sandboxie/assets/12518330/55cf404a-52a2-45c4-b0ca-50e368111e14

### Possible Solution

A setting for customizing the "Run Sandboxed" window size in some way. Either specifying exact dimensions, and/or an option to auto-size the width to fit the names. Perhaps also this setting could auto-size the height of the window in the case of many sandboxes so you don't have to scroll.

**Comment by DavidXanatos** [comment]
Hi @ThioJoe the feature will be included in the next build 1.13.6
I have seen you mentioned you may want to do a YoutTube video about Sandboxie, if you have any technical or background questions, please don't hesitate to ask, you can find my email address in my github profile.
