### ISSUE TITLE
SBIE2101 OpenProcess

### ISSUE THREAD

**Issue by gilch** [sandboxie-plus/Sandboxie#37]
I'm trying out your release of Sandboxie, and keep running into the following error:
```
SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1
```
This seems to happen when I invoke the sandboxed application's embedded Python interpreter.

I tried searching the old Sandboxie forums, but the only solution I saw talked about whitelisting IPC access. I'm not sure how safe that would be for an untrusted application.

Can you explain what is going on? Can this problem be fixed for the next release? Is the provided error message enough or do you need something more specific from me?

**Comment by DavidXanatos** [comment]
It wouldn't be very safe to whitelist any IPC communication.
Was the solution you found more specific in what ipc paths to whiteist?
what application causes the issue in the first place?

**Comment by gilch** [comment]
> what application causes the issue in the first place?

If you want to try reproducing the issue, I downloaded the application from here: https://opserver.de/down/ZorroBeta.zip The main executable in the zip folder, zorro.exe, registers as malicious on [VirusTotal](https://www.virustotal.com/gui/file/7796fa9e928c33f6ceb49157a1455d7883b424cc12df96ac72fd4b65c9ebc1b2/detection), but only two of the engines detect it, and they're heuristic ones, which tend to have a higher rate of false positives. So I sandboxed it to be safer. It's not doing anything *obviously* weird in the sandbox, but malware is not always obvious right away.

To see the error, unzip the folder and run the zorro.exe program in a new sandbox with default settings. Select the PythonTest script in the GUI and click [Test]. Zorro says it's compiling, and then the Sandboxie errors appear, and then Zorro crashes.

> Was the solution you found more specific in what ipc paths to whiteist?

Not really, [he basically said](https://community.sophos.com/products/sandboxie/f/forum/119809/constant-sbie2101-object-name-not-found-errors) to use the Resource Access Monitor to find out what IPC it was using and whitelist that in SandboxSettings.

I tried the Resource Access Monitor and saw the line 
```
Ipc      X  $:Zorro.exe
```
appear in the output when Zorro crashes on that PythonTest script.

**Comment by adoxa** [comment]
I had a similar problem trying to run an Alawar game. I tracked it down to `\Device\Nsi`. The fix was: Restrictions > Internet Access > Allow All Programs; Resource Access > Blocked Access > Edit > `\Device\Afd*`. That will again block internet access, but now allowing access to `\Device\Nsi`. I don't know what the ramifications of that are, though, nor if it will help with your problem.

**Comment by DavidXanatos** [comment]
I have tested it and I'm not sure which script to select, i tryed a fiew like calculate pi and thay worked with 1.0.9
can any user hfo this software please 
a) test if it now works fine 
and if not 
b) tell me exactly step by step how to reproduce th issue

**Comment by gilch** [comment]
It was the PythonTest script before. Not all of the scripts use Python. I'll need to upgrade my Sandboxie version to test again.

**Comment by gilch** [comment]
OK, I installed Sandboxie+ v1.0.9 over my old install and tried Zorro sandboxed again. It doesn't seem to have any problems in the new Sandboxie version. I'm not seeing the issue I had before.

**Comment by DavidXanatos** [comment]
very good than we can close this
