### ISSUE TITLE
Thunderbird, when run sandboxed while residing outside of sandbox, does not finish, error message "7-Zip - cannot create temp folder archive"

### ISSUE THREAD

**Issue by JaapvanderLeer** [sandboxie-plus/Sandboxie#3702]
### Describe what you noticed and did

First of all, this is not an important issue, I bring it up because it can influence other software. 

Background: I want to run a second instance of Thunderbird, and therefore, I made a restricted Sandbox which prevents the second instance from seeing the first running instance. Recently the setup in the sandbox became corrupt (message at restart "Could not load XPCOM". Well know problem),
I decided to cleanup everything in the sandbox and do a fresh install .

When running the installer "Thunderbird Setup 119.0b6" from inside the sandbox, everything goes fine. 
When running the same installer when it is located outside of the sandbox, running it sandboxed from the context menu, the install fails. Message: "7 ZIP: Can not create temp folder archive." From further investigation, I found the installer expands an internal zip-file in a second tread. Apparently, this second tread does not get the correct sandbox-settings or something like that.

From Trace, the following file exception was reported when running sandboxed from file outside of sandbox:
File     X          \Device\HarddiskVolume3\Users\Fam. van der Leer_2\AppData\Local\Temp

Note: AppData is write-only in this setup.                                                                                                                                                                 

### How often did you encounter it so far?

Always when running the installer sandboxed form te context menu.

### Expected behavior

I expected the installer to run the same as when launched from inside the sandbox.

### Affected program

Thunderbird Setup 119.0b6

### Download link

https://archive.mozilla.org/pub/thunderbird/releases/119.0b6/win64/en-US/

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did, but no .dmp file has been created in the system., No, not at all.

### What version of Sandboxie are you running now?

1.12.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### Is it a regression from previous versions?

not known

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 11

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Microsoft Defender

### Did you previously enable some security policy settings outside Sandboxie?

None

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=RpcPortBindings
Template=AdobeDistiller
Template=WindowsRasMan
Template=AdobeLicensing
Template=AdobeAcrobatReader
Template=SnagIt
Template=OfficeLicensing
Template=Edge_Fix
FileRootPath=D:\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EnableObjectFiltering=n
ForceDisableSeconds=60
NotifyForceProcessDisabled=y
TemplateReject=WindowsLive

[DefaultBox]

ConfigLevel=10
AutoRecover=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
Enabled=y
AutoDelete=y
NeverDelete=n
DeleteCommand="C:\Program Files\Sandboxie\sdelete.exe" -p 1 -s -q "%SANDBOX%"
BoxNameTitle=n
BorderColor=#00FFFF
CopyLimitKb=149152
NotifyInternetAccessDenied=y
ProcessGroup=<InternetAccess>,iexplore.exe,Acrobat.exe,AdobeARM.exe,wmplayer.exe,dllhost.exe,googletalkplugin.exe,AcroRd32.exe,biclient.exe,chrome.exe,ABSIE_BG.exe,emule.exe,firefox.exe,msedge.exe
ClosedFilePath=!<InternetAccess>,InternetAccessDevices

[UserSettings_0C36020C]

SbieCtrl_UserName=famva
SbieCtrl_ShowWelcome=n
SbieCtrl_WindowCoords=484,380,1650,843
SbieCtrl_ActiveView=40021
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=y
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_AutoApplySettings=n
SbieCtrl_NextUpdateCheck=1621149565
SbieCtrl_BoxExpandedView=DefaultBox,Waf
SbieCtrl_AutoStartAgent=SandMan.exe

....

[Example_for_thread]
Enabled=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
BoxNameTitle=-
OpenPipePath=C:\Users\Fam. van der Leer_2\OneDrive*
OpenPipePath=%Personal%
OpenPipePath=%Desktop%
WriteFilePath=C:\Program Files\
WriteFilePath=!,%Local Appdata%
WriteFilePath=%Appdata%
AutoRecover=y
NeverRemove=y
```

**Comment by offhub** [comment]
Try this:
`WriteFilePath=!,%Local Appdata%` -> `WriteFilePath=%Local Appdata%\*\*`

**Comment by JaapvanderLeer** [comment]
The issue is not: it does not work. The issue is: it works differently in case the install file is started form the sandbox or is started outside of the sandbox, running sandboxed form the conext menu. That should not differ.
And by the way: when launcehed from within the sandbox, the install goes perfect - the writefilepath blocks writes to het main system and everything comes in the sandbox.

**Comment by offhub** [comment]
I get the same error in both cases. From which location within the sandbox are you running the file?

**Comment by JaapvanderLeer** [comment]
I downloaded the file 119,0b6.exe, using Edge (standard webbrowser) sandboxed, into the download directory (in the sandbox) and instructed Edge to run the executable file sandsboxed. I 've just tried again and there was no error message.

**Comment by offhub** [comment]
MS Edge creates this folder itself if the temp folder does not exist. But the Thunderbird installer does not perform the same action.

- Create the temp folder using a trigger at box init (`AutoExec=cmd /c md "%LocalAppData%\Temp"`)
- Use the snapshot feature (Run the sandboxed cmd, create the temp folder then take a snapshot)
- Use a less generic rule (`WriteFilePath=%LocalAppData%\*\*`) [If you use this rule, a temp folder will be created when the Thunderbird installer is run, at least that's what happened in my tests]

**Comment by JaapvanderLeer** [comment]
For me, it is not important to be able to run the installer from outside the sandbox, as the use-case is to install Thunderbird in the Sandbox and that is possible. So I am not looking for a solution to run the installer sandboxed from the context menu.

The point I wanted to make is that Sandboxie reacts differently when a folder is normal vs when the folder is write-only. 

In the normal situation, when a file is written to the temp-folder, the temp-folder is created in the sandbox, irrespective if it already exists in the real world. The file is then written into the sandboxed temp folder. In the write-only situation, it is not. 

Should Sandboxie not act consistently in this case?

**Comment by offhub** [comment]
I don't think this is a problem with Sandboxie. If you try to run the Thunderbird installer outside the sandbox after changing the name of the temp folder in the host location, you get the same error.

**Comment by JaapvanderLeer** [comment]
Your observation is correct: in normal mode, is the temp directory does not exist on the host, it is not duplicated in the sandbox. This is, what happens after a rename: the directory on the host does not exist any more.

In normal mode, if the temp directory does exist on the host, a shadow copy is made in the Sandbox to contain the file. 
In write only mode, if the temp directory on the host exists, *no* shadow compy is made. If this yes|no is the correct functionality, see my last comment.  It depends on the exact meaning of write-only.

**Comment by JaapvanderLeer** [comment]
The issue is still there with Sanmdboxie 1.13.7 .
