### ISSUE TITLE
Sandboxie service on Windows 24H2 crashes MS Office C2R executable

### ISSUE THREAD

**Issue by sfc9982** [sandboxie-plus/Sandboxie#3708]
### Describe what you noticed and did

1. Install Sandboxie on Windows Insider Dev `26080.1201.ge_release_svc_prod2.240310-0750` (KB5037135)
2. `OfficeClickToRun.exe` under `C:\Program Files\Common Files\microsoft shared\ClickToRun` or `C:\Program Files\Microsoft Office 15\ClientX64` fails to boot.

### Expected behavior

boot normal

### Affected program

OfficeClickToRun

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did. I'm going to share the .dmp file(s) in a later comment.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.12.9

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 11 Insider Dev `26080.1201.ge_release_svc_prod2.240310-0750` 

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Kaspersky Endpoint Security

**Comment by sfc9982** [comment]
1. I'm not mean that Office C2R cannot run in Sandboxie, it's when Sandboxie service enabled in Windows, C2R cannot run at the same time.

**Comment by sfc9982** [comment]
2. Though I have Kaspersky Anti-Virus installed, but I believe it's not releated to it. Because things were fine before I upgrade to ge_release from ni_release of Windows.

**Comment by DavidXanatos** [comment]
try disabling the "Microsoft Office Click-to-Run" compatibility tempalte in the global settings

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/b1502e7f-e717-455a-8083-75319506dc7d)

**Comment by sfc9982** [comment]
@DavidXanatos Thanks, it works and solved my problem.
