### ISSUE TITLE
Sandboxie-Plus Portable: SandMan frequently doesn't show sandboxes when loaded

### ISSUE THREAD

**Issue by Francesco-Cocchioni** [sandboxie-plus/Sandboxie#371]
Hello,

i'm using Sandboxie-Plus in portable mode. When i launch SandMan it is very frequent that it doesn't show any sandbox nor it shows the message that config file is loaded, like in the image below:

![image](https://user-images.githubusercontent.com/3011259/104354262-3e1bad80-5509-11eb-8144-881fe8c9424d.png)

If i close and reopen SandMan, everything works fine:

![image](https://user-images.githubusercontent.com/3011259/104354679-da45b480-5509-11eb-91f0-8197ae7119dd.png)

This problem can be reproduced opening and closing sandman multiple times; there is a 50% chance that the sandbox are not shown like in image one. In my case the first run when i reboot the PC always has this problem.

**Comment by isaak654** [comment]
Latest version is 0.5.4c, please update and check again:
https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.5.4c

**Comment by isaak654** [comment]
Try the latest stable v0.5.4c and check again:
https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.5.4c

If the issue still persists, you can move your sandboxie.ini from c:\windows to let say c:\temp while the sandboxie driver is unloaded, than start sandboxie and when it loads the driver it will recreate a sandboxie.ini in c:\windows, than open it for editing and paste the content of the saved one in temp folder.

Otherwise, please attach your Sandboxie.ini lines.

**Comment by Francesco-Cocchioni** [comment]
Same problem with the latest version:

![image](https://user-images.githubusercontent.com/3011259/104420925-eae24300-557a-11eb-845a-04a79bdd349a.png)

Sanboxie.ini content:

[GlobalSettings]

FileRootPath=""MYPATH""\Sandbox\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%SANDBOX%
IpcRootPath=\Sandbox\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n

[Programs]

Enabled=y
ConfigLevel=7
AutoRecover=n
BlockNetworkFiles=y
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=WindowsFontCache
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00ffff,ttl,6
BoxNameTitle=n
BlockNetParam=y
DropAdminRights=n
CopyLimitKb=204800
CopyLimitSilent=n
NeverDelete=y
AutoDelete=n

Sandboxie-Plus.ini content:

[Options]
NextCheckForUpdates=1611049687
PortableStart=1
PortableRootDir=1
Language=
DarkTheme=false
CheckForUpdates=1
ShowNotifications=true
OpenUrlsSandboxed=2
WatchIni=true
OnClose=ToTray
ShowSysTray=true
AutoRunSoftCompat=false
PortableStop=1

[MainWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAALaAAABugAABKEAAAPBAAAC2wAAAdkAAASgAAADwAAAAAAAAAAAB4AAAALbAAAB2QAABKAAAAPA
LogList_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAboAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABVgAAAAEAAAAAAAAD6AAAAABk
ResMonList_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAnwAAAAFAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAFAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAA7AAAAAEAAAAAAAAD6AAAAABk
ApiLogList_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAnwAAAADAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAADAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAABtAAAAAEAAAAAAAAD6AAAAABk
Log_Splitter=:ByteArray:AAAA_wAAAAEAAAACAAAAwAAAANsB_____wEAAAACAA
Panel_Splitter=:ByteArray:AAAA_wAAAAEAAAABAAABAAH_____AQAAAAEA
LogTab=0
BoxTree_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAlYAAAAFAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAFAAAAxgAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAD6AAAAABk

[PopUpWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAONAAAB2gAAA_IAAAIXAAADjgAAAfkAAAPxAAACFgAAAAAAAAAAB4AAAAOOAAAB-QAAA_EAAAIW

[SettingsWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAMxAAAB_QAABWwAAANmAAADMQAAAf0AAAVsAAADZgAAAAAAAAAAB4AAAAMxAAAB_QAABWwAAANm

[OptionsWindow]
Window_Geometry=:ByteArray:AdnQywADAAAAAAMrAAAB6AAABiYAAAOmAAADLAAAAgcAAAYlAAADpQAAAAAAAAAAB4AAAAMsAAACBwAABiUAAAOl
Run_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAccAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABYwAAAAEAAAAAAAAD6AAAAABk
Groups_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAeEAAAABAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAABAAAB4QAAAAEAAAAAAAAD6AAAAABk
Forced_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAccAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABYwAAAAEAAAAAAAAD6AAAAABk
Stop_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAbgAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABVAAAAAEAAAAAAAAD6AAAAABk
Start_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAdIAAAABAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAABAAAB0gAAAAEAAAAAAAAD6AAAAABk
INet_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAdIAAAABAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAABAAAB0gAAAAEAAAAAAAAD6AAAAABk
Access_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAccAAAAEAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAAEAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAZAAAAAEAAAAAAAAAmwAAAAEAAAAAAAAD6AAAAABk
Recovery_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAccAAAACAQAAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABYwAAAAEAAAAAAAAD6AAAAABk
Templates_Columns=:ByteArray:AAAA_wAAAAAAAAABAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAiEAAAACAQEAAQAAAAAAAAAAAAAAAGT_____AAAAgQAAAAAAAAACAAAAZAAAAAEAAAAAAAABvQAAAAEAAAAAAAAD6AAAAABk

**Comment by isaak654** [comment]
Some slashes are missing from your lines because you didn't post the lines between the code tags:

![tempsnip](https://user-images.githubusercontent.com/12372772/104454837-bab09980-55a6-11eb-88a5-7cdb9a39f342.png)

Please edit your previous post according to my suggestion.

And you should update your FileRootPath with a real path (or with a path that seems real, if you don't want to reveal it intentionally here).

**Comment by DavidXanatos** [comment]
fixed in 0.5.5 build
