### ISSUE TITLE
  GXT.exe does not work 

### ISSUE THREAD

**Issue by a1waysbeta** [sandboxie-plus/Sandboxie#3716]
### Describe what you noticed and did

 Install GXT_6_Setup.exe, unable to start, personal guess is similar to QQ and other social software, missing template 

### Expected behavior

 Add template, normal works. 

### Affected program

Not relevant

### Download link

http://58.42.238.212:8888/ClientFiles/GXT_6_Setup.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus-x64-v1.13.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

win11 can 26080 x64

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

microsoft Defender

**Comment by offhub** [comment]
Try this setting:

```
NoRenameWinClass=GXT.exe,*
```

**Comment by a1waysbeta** [comment]
it works. thanks.
