### ISSUE TITLE
How change the path of a sandbox?!

### ISSUE THREAD

**Issue by sqrxz** [sandboxie-plus/Sandboxie#3721]
### Describe what you noticed and did

I simply want to change the path where all sandboxes were created. I searched this and it was possible in 2020 https://github.com/sandboxie-plus/Sandboxie/discussions/1768#discussioncomment-2503401 however I am unable to find one that works with the current GUI of the program. this seems rather strange since I've also read that the sandboxes have been modified to be more portable, why assume you'd want them stuck in your C: drive?

### Expected behavior

I just want to know how to change the path where all sandboxes are created

### Affected program

not relevant

### Download link

why is this required?

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie plus 1.12.6.64 bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Win 10 AME 22H2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

simplewall

**Comment by bastik-1001** [comment]
With Sandman (the sandbox manager of Sandboxie-Plus) you can change where sandboxes are created by default, by setting the file system root in the "Global Settings" > Advanced Config > [Sandboxie Config]

Whenever you set up a new box with the box creation wizard, you are able to select a different path.

For existing sandboxes, you have to set the File Root Path in its ini-section. [https://sandboxie-plus.github.io/sandboxie-docs/Content/FileRootPath.html](https://sandboxie-plus.github.io/sandboxie-docs/Content/FileRootPath.html)

After you changed the path, you need to move or copy the files and folders of the sandbox from where it is to where you specified in the INI.

**Comment by sqrxz** [comment]
Thank you, this worked. had to remake a shortcut to a file inside one of the boxes but it's working fine now.
