### ISSUE TITLE
Sandman: Optionally extend the screenshot protection to the UI

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3739]
### Is your feature request related to a problem or use case?

Users make use of Sandboxie as a privacy tool, even though it has not been the first goal, but past changes (like the privacy mode) add to the usefulness as a privacy tool, so users could appreciate if the user interface of Sandboxie-Plus prevents it that something in its UI is leaked, by it being screenshotted, maybe as a mistake.

### Describe the solution you'd like

Since, Sandboxie recently got the feature to prevent screenshots to be taken of sandboxed windows, (and soon to be released sandboxed processes being prevented from taking screenshots) it should be possible to add this as an optional feature to SandMan.

### Describe alternatives you've considered

I assume that Sandboxie Control is out of scope, as it is not subject to change. If that is not correct, it could be added to it as well.

**Comment by love-code-yeyixiao** [comment]
![image](https://github.com/sandboxie-plus/Sandboxie/assets/92030377/65fab126-f3b2-4eb1-b153-1e5173f57fa0)
![image](https://github.com/sandboxie-plus/Sandboxie/assets/92030377/542a1ce9-b680-4886-ae8f-fd2bc631b8bf)

Which feature you are saying?

**Comment by bastik-1001** [comment]
I was indeed talking about the latter. I don't expect the user interface to have that option, and probably won't enable it for myself, but find it to be useful for others that might take screenshots with the main window of Sandman open, potentially showing a window title or something users consider to be private information.

**Comment by DavidXanatos** [comment]
So sandman should hide its own windows form being captured?

**Comment by bastik-1001** [comment]
> So sandman should hide its own windows form being captured?

Yes, this was the idea, based on the perception that if Sandboxie can do that for windows under its control, users may expect Sandboxie to do it for itself.

**Comment by offhub** [comment]
This is not a Sandboxie bug, but windows covered by the screen protection setting will appear black instead of transparent after minimizing to the system tray and restoring from the system tray. Is it possible to fix this?

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/501dc400-a531-4831-a91a-13c0eceef421

**Comment by DavidXanatos** [comment]
I don' think this behavior can be simple remedied

**Comment by offhub** [comment]
This setting has no effect if SandMan.exe is started with the -autorun parameter.
