### ISSUE TITLE
Recovery legacy Sandboxie build delete contents behaviour for Sandboxie-Plus

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#374]
1. Show "Quick Recovery" when delete contents, if it have been enable. 
     If sandbox is empty, show message "The sandbox is empty, There is nothing to delete." 
 2. Show the amount of files and folders, and the total size. 
![1](https://user-images.githubusercontent.com/56181919/104468155-08c99b00-55af-11eb-9ef2-41bdd74fad7f.PNG)

**Comment by DavidXanatos** [comment]
I find that behavior really mighty annoying, but if you want, I'll add a setting where you can enable the recovery window to be always shown when a non empty sandbox is about to be emptied.
Not sure If I'll add 2 though....
