### ISSUE TITLE
Auto-termination after elapsed time

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3740]
### Is your feature request related to a problem or use case?

Sandboxie allows users, that are lacking a valid supporter certificate, to test some functions by limiting the duration the box can be used for. This function could be used to provide a custom timeout for any kind of box.

Sometimes, I start videos/clips in a sandboxed player, minimize it to tray and forget about it. It could be closed to free resources.

### Describe the solution you'd like

Allowing users to set a time, per box, in a unit that seems reasonable, after which the sandbox terminates all processes running in that box. I am not sure to what it is bound when it is used as a limitation, but the same can apply to this a feature.

**Comment by love-code-yeyixiao** [comment]
I think you can actually use the trigger mechanism to start a batch script while the sandbox is running, delay it with the “timeout” command, and end the process you want to end when the command is finished.
For example:

timeout /T 600
taskkill /f /im ***.exe

**Comment by bastik-1001** [comment]
`taskkill` fails, CMD gets started with the cmdline and taskkill starts. However, it does not do anything. It seemingly wants to end the processes of the current user, starting the sandbox, as when I run tasklkill in a sandboxed CMD, it asks for the password of the current user. `whoami` shows that CMD sees me as the starting user account, not the sandbox account, while the task manager shows the limited sandbox account (as expected.)
