### ISSUE TITLE
Could not invoke program

### ISSUE THREAD

**Issue by 3DPixel** [sandboxie-plus/Sandboxie#376]
Hello,

I'm trying to open an email as in a suspicious email that I need to check in a safe environment.

The email has been saved to my pc as an .eml
If I right click on the file and click 'Run Sandboxed' I get this error message:

![Screenshot_1](https://user-images.githubusercontent.com/26568496/104484943-c78eb680-55c1-11eb-8d97-9f8424f1a3fa.png)

Is this being caused because Sandboxie is trying to open the file and doesn't know how to open it?
How can I open this safely please?
Thanks

Sandboxie-Plus 0.5.4c
Office 365 ver 16

**Comment by APMichael** [comment]
I see that you are using MS Office 365 and therefore Outlook. Unfortunately, MS Office 365 (and MS Office 2016 C2R, Click-to-Run) does not seem to work with Sandboxie anymore. Probably something has been changed by Microsoft. (MS Office 2019 C2R and all MSI versions work fine on the other hand). 

https://www.wilderssecurity.com/threads/ms-office-365-2016-c2r-click-to-run-no-longer-works-with-sandboxie.435875/

**Comment by Damnatus** [comment]
I have a variant of this error with different system code error (14001). Don't know if this is the right place to add

![Screenshot 2021-01-19 183338](https://user-images.githubusercontent.com/7227343/105072663-5a2dca80-5a86-11eb-862d-b05fcc71b22b.png)

Version: Sandboxie Plus 0.5.5

**Comment by DavidXanatos** [comment]
eml is not a program, open an email viever that understands eml files and than open it with it

about 14001 its different it emans the box is broken delete content and try again
