### ISSUE TITLE
KeePass "Out of Memory" crash

### ISSUE THREAD

**Issue by SSJPKXL** [sandboxie-plus/Sandboxie#3768]
### Describe what you noticed and did

If I make many changes to my KeePass database, perform database cleanup, and save database about 15-20 times, it eventually crashes with "Out of Memory" error and stating that error report is copied to clipboard, but clipboard is empty.

### Expected behavior

No crashes

### Affected program

KeePass

### Download link

https://keepass.info/download.html

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did, but I accidentally removed / lost the .dmp file(s).

### What version of Sandboxie are you running now?

1.13.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 19045

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

### Sandboxie.ini configuration

```shell
[KP]
Enabled=y
ConfigLevel=10
BlockNetworkFiles=y
Template=BlockPorts
Template=FileCopy
Template=SkipHook
Template=LingerPrograms
Template=AutoRecoverIgnore
BorderColor=#00FFFF,ttl,6
NotifyInternetAccessDenied=n
ClosedFilePath=InternetAccessDevices
CopyLimitKb=512000
ForceProcess=KeePass.exe
DropAdminRights=y
IsProtectScreen=y
NotifyStartRunAccessDenied=n
IsBlockCapture=y
```

**Comment by GY8VSdYYzvL8-K6T** [comment]
The latest version - 2.56. Just to clarify. to reproduce the issue, one must be updating data, performing database maintenance (cleaning up old entries), and re-saving database changes very frequently (every 30 seconds or less). It never ever happened outside of Sandboxie.

**Comment by GY8VSdYYzvL8-K6T** [comment]
I apply the following mitigtation policies to KeePass.exe, but they don't cause crashes when KeePass is not sandboxed:
Control Flow Guard
ASLR - High Entropy
ASLR - Force Relocate
Heap Termination on Corruption
Extension Point Disablement
Remote Load Disablement
Low Integrity Load Disablement

I am testing to see if removal of all mentioned policies improves the situation.

**Comment by GY8VSdYYzvL8-K6T** [comment]
Testing without any mitigation policies applied to KeePass.exe produced the same crash. Now testing to see is removing library files it uses (to force it to use system library files) helps with the issue.

**Comment by offhub** [comment]
Try without `IsBlockCapture=y`

**Comment by offhub** [comment]
This problem also affects other applications. When you open Windows Explorer in the sandbox and navigate between folders, Windows Explorer becomes unusable after a period of time.

`IsBlockCapture=y`

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/11c94cdf-0924-4998-9f82-0d505d22d97e

**Comment by GY8VSdYYzvL8-K6T** [comment]
Yes! That appears to do the trick!

**Comment by SSJPKXL** [comment]
Crashes were fixed in the latest preview for KeePass, but parts of GUI (such as check-boxes) remain blacked-out in KeePass, WinSCP, and some other programs...

**Comment by SSJPKXL** [comment]
Any updates regarding blacked-out UI elements? I'd like to take and post a screenshot of that UI bug, but I don't know how to do it when "BlockScreenCapture=y" ...
