### ISSUE TITLE
Sandboxie 1.13.4 with IsBlockCapture=y brakes on Windows 7

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3769]
### Describe what you noticed and did

0) Have Windows 7 64bit (I could not reproduce this on Windows 10)
1) Install Sandboxie 1.13.4 or update it
2) Have a sandbox with IsBlockCapture=y enabled
3) Try to start something via Right-click > Run > Run Program
4) See that the UI for start.exe is not rendered correctly
![brokenUI](https://github.com/sandboxie-plus/Sandboxie/assets/1449429/3ada1c87-5213-45cc-b5b6-a52842b6ec8f)
5) Close the element for starting with Run
6) Start explorer.exe (Run > Standard Applications Windows Explorer)
7) See that it is not rendered properly
![Explorer](https://github.com/sandboxie-plus/Sandboxie/assets/1449429/6fe189cb-8d26-42a5-939d-6b292c20cfb0)
8) Trying to close it by clicking on the X fails, also ALT+F4 does not close explorer.exe (it can be terminated with the Sandman UI)
9) Have IfranView 4.66 64bit installed on the machine
10) Start it in the box and see that its UI misses the icon and the toolbar button. (Trying to open a file via the menu opens a blank folder.)
![irfanview](https://github.com/sandboxie-plus/Sandboxie/assets/1449429/d2c1480e-e163-437d-aa0f-586b64fc6b2b)
11) With the system Firefox 115.9.1esr (64-Bit) at first I did not notice it behaving differently, but I had to kill Firefox once I attempted to fullscreen while playing a Youtube video, since I heard the video playing, by the audio that was still running, but I could not interact with the UI of Firefox anymore, nor could I see the video being played.
12) Suspending all processes while Firefox 115.9.1esr (64-Bit) is run and IsBlockCapture is set to be disabled, I can resume the processes and keep using Firefox. However, when IsBlockCapture is set to be enabled, the UI of Firefox does not respond anymore, after the processes are resumed.

By the looks of it, IsBlockCapture=y does not work properly on Windows 7. I was not able to reproduce this on Windows 10. Don't focus on Firefox, it was the first I tested the feature for enabling for everyday use, but with I did not try to workaround by tweaking other settings.

### How often did you encounter it so far?

Every time IsBlockCapture=y is set

### Expected behavior

Sandboxie itself behaving normally, other programs should work fine for the most part.

### Affected program

Sandboxie 1.13.4 itself, explorer.exe, Irfanview

### Download link

Can be provided if needed.

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.13.4 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### Is it a regression from previous versions?

Sandboxie-Plus 1.13.3 did not include the feature

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 7 64 bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

MSE

### Sandboxie.ini configuration

```shell
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=[redacted]
BorderColor=#02f6f6,ttl
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
IsProtectScreen=n
IsBlockCapture=y
```

**Comment by bastik-1001** [comment]
The easiest solution could be to disable the feature for systems below Windows 10. If the root cause is easy to fix, this would be the better option.

BTW, in every instance IsBlockCapture=y was used, I just wanted to check if the program behaves normally, I did not test if the feature itself was holding up to its intended usage.

**Comment by GY8VSdYYzvL8-K6T** [comment]
It makes a bunch of GUI parts pitch-black. Why? How is BlockCapture different from ProtectScreen?

**Comment by offhub** [comment]
ProtectScreen: HOST to Sandbox
BlockCapture: Sandbox to HOST

**Comment by DavidXanatos** [comment]
the issue was a bit deeper going than BlockCapture now its properly fixed and BlockCapture works now on windows 7
