### ISSUE TITLE
Installer incorrect startup Entry

### ISSUE THREAD

**Issue by Shadowized** [sandboxie-plus/Sandboxie#377]
I think I've discovered a small bug in Sandboxie-Plus installers.

the Installer is not setting the correct application path with the tickbox to start with windows, instead of setting the installer path to the program, it sets the ```SandboxiePlus_AutoRun``` entry in CurrentVersion\Run to ```"{app}\\SandMan.exe\" -autorun"``` resulting in the program failing to start with windows, and requiring me to manually edit it each time I uninstall/reinstall to upgrade.

I verified and confirmed this behavior in a VM with the default path unchanged as well just to rule out my system.

**Comment by DavidXanatos** [comment]
found and fixed for the next release
