### ISSUE TITLE
Explorer.exe does not work in sandbox if Avast Free Antivirus installed on Win11 Pro.

### ISSUE THREAD

**Issue by takahiro-itou** [sandboxie-plus/Sandboxie#3777]
### Describe what you noticed and did

1. Open Sandboxie Plus 1.13.4
2. Right click a box
3. Select "Run" (実行)  -> "Standard Applications" (標準的なアプリケーション）-> "Windows Explorer" (Windows エクスプローラ)
4. Then the window is open, but
    - no items are displayed. or
    - explorer is freezed, I can't operate anything.
5. Wait a bit, then window will be closed.

### How often did you encounter it so far?

Always.

### Expected behavior

The explorer shows folder and files. and does not crash.

### Affected program

Explorer.exe

### Download link

Not available

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Did the program or any related process close unexpectedly?

Yes, it did, but no .dmp file has been created in the system.

### What version of Sandboxie are you running now?

Sandboxie Plus v1.13.4 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 Pro 22H2 or 23H2 64bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Avast Free Antivirus

**Comment by takahiro-itou** [comment]
https://github.com/sandboxie-plus/Sandboxie/assets/6907757/978387d6-262b-4df2-8032-29a73e6692f1

**Comment by takahiro-itou** [comment]
Uninstall Sandboxie (delete all boxes and Sandboxie.ini) and  Re-Install (Clean Install) sandboxie v1.13.4 again.
But the problem is not resolved.

https://github.com/sandboxie-plus/Sandboxie/assets/6907757/a3eab250-6c1f-47f4-af09-85912968dc8a

Sandboxie.ini configuration is:
```
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=7zipShellEx
Template=Avast_Antivirus
Template=Edge_Fix
Template=OfficeClickToRun
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_084801A4]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
```

**Comment by takahiro-itou** [comment]
After uninstall Avast Free Untivirus. Then explorer in sandbox does work correctly. See below movie.
Expected (correct) behaivor:

https://github.com/sandboxie-plus/Sandboxie/assets/6907757/e87a9ec1-77c5-45d8-9eab-7640a3433ae5

Remark:
Comparing the two videos, I noticed that the  "WerFault.exe" and "SandboxieCrypto.exe" process exists as child of explorer.

**Comment by offhub** [comment]
Try this setting:

```
ClosedFilePath=explorer.exe,*\ashShell.dll
```

**Comment by GY8VSdYYzvL8-K6T** [comment]
The right way to run explorer.exe in Sandboxie is to use "C:\Windows\explorer.exe /e,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}" , but how do you force to run Explorer.exe by default with that command? If you set Explorer.exe for ForceProcess, then it becomes unusable as soon as your PC boots into Windows.

**Comment by DFP86** [comment]
I have the same problem....

**Comment by takahiro-itou** [comment]
Thanks @offhub !
I confirmed that explorer does work well by your proposed settings.
And, thanks to your commit.
