### ISSUE TITLE
calc.exe terminating after start

### ISSUE THREAD

**Issue by ToCSharp** [sandboxie-plus/Sandboxie#378]
Hello,

Calculator in Windows 10 not working in Sandboxie. And notepad.exe is OK.
Windows 10 Pro 20H2 19042.685 in VMware.

Last events:
LdrFindEntryForAddress(0x00007FF9FDEF0000) [c:\windows\system32\calc.exe]
LdrFindEntryForAddress(0x00007FF9FDEF0000) [c:\windows\system32\calc.exe]
LdrFindEntryForAddress(0x00007FF9FDEF0000) [c:\windows\system32\calc.exe]
VirtualQueryEx(\Device\HarddiskVolume2\Windows\System32\calc.exe, MemoryRegionInformation, BaseAddress=0x000001C878930000) [c:\windows\system32\calc.exe]
VirtualQueryEx(\Device\HarddiskVolume2\Windows\System32\calc.exe, MemoryRegionInformation, BaseAddress=0x000001C878930000) [c:\windows\system32\calc.exe]
VirtualQueryEx(\Device\HarddiskVolume2\Windows\System32\calc.exe, MemoryRegionInformation, BaseAddress=0x000001C878930000) [c:\windows\system32\calc.exe]
VirtualQueryEx(\Device\HarddiskVolume2\Windows\System32\calc.exe, MemoryRegionInformation, BaseAddress=0x000001C878930000) [c:\windows\system32\calc.exe]
VirtualQueryEx(\Device\HarddiskVolume2\Windows\System32\calc.exe, MemoryRegionInformation, BaseAddress=0x000001C878930000) [c:\windows\system32\calc.exe]
ExitProcess(0) [c:\windows\system32\calc.exe]
DumpProcess(7664) [c:\windows\system32\calc.exe]
GetModuleHandle(ntdll.dll) [c:\windows\system32\calc.exe]
QuerySystemInformation(SystemBasicInformation) [c:\windows\system32\calc.exe]
QuerySystemInformation(SystemProcessorInformation) [c:\windows\system32\calc.exe]
QueryProcessInformation(\Device\HarddiskVolume2\Windows\System32\calc.exe, ProcessImageInformation) [c:\windows\system32\calc.exe]
TerminateProcess() [c:\windows\system32\calc.exe]

Calculator itself is not important for me, it is first try. I starting to deep dive in Sendboxie to add some anti detection. May be you can add me to slack for more free talk. Mail in my github profile

**Comment by NewKidOnTheBlock** [comment]
That might be related to the fact that Calc is not a regular program, but a Windows Store App.

**Comment by ToCSharp** [comment]
Yes, you right. calk.exe is just launcher of windows universal.
https://github.com/DavidXanatos/sandboxie-docs/blob/main/Content/ForceFolder.md
Another consideration is that metro apps are not supported. If your default application for opening a specific file type is a Windows Metro app (such as Windows 10 photo viewer), the application will launch outside the Sandbox.
But application is not running outside the Sandbox.
To try you can run sandboxed cmd and type "C:\Windows\System32\calc.exe".

It is the way to detect sandbox, to run app which is not runnable in sandbox.
explorer.exe also don't run without strange arg, which just tells, that we want open disks.
explorer.exe /e,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
So sandboxie run it from gui context menu.

So the issue is to add opportunity to add such programs paths to ini, to run outside the Sandbox.
Like "disable_force" for start.exe.

And change "calc" to "notepad" in docs:
https://github.com/DavidXanatos/sandboxie-docs/blob/main/Content/StartCommandLine.md

**Comment by ToCSharp** [comment]
After adding some anti detection, Sandboxie can replace Cuckoo Sandbox Monitor in some cases.
https://github.com/cuckoosandbox/monitor

**Comment by DavidXanatos** [comment]
> 
> So the issue (open other issue?) is to add opportunity to add such programs paths to ini, to run outside the Sandbox.

No no no no no!!!
There will be no exceptions of that sort as those can pose a major security breach.

The only thing that could be reasonable done is to detect start atempt's of this modern apps, log an appropriate error message containing that app details and the desired command line arguments.
Than the SandMan.exe could offer to start that application with these arguments outside but only with an appropriate warning that said application would handle sandboxed files which may be potentially dangerous.

**Comment by quangkieu** [comment]
As you mentioned the modern app, there are 2 types right now. Full isolated like Calc. And Hyprid app like Windows Terminal. For the second, the gui is modern, isolated but all service, back end process is win32. That how they run cmd, powershell. So modern app does not mean sandboxed by windows

**Comment by DavidXanatos** [comment]
since we have already a request for that: https://github.com/sandboxie-plus/Sandboxie/issues/19
Ill close this one
