### ISSUE TITLE
[Feature Recovery] Double-click to add program to Internet Access Restrictions whitelist for Sandboxie-Plus

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#380]
Legacy build:
![1](https://user-images.githubusercontent.com/56181919/104578952-3ff18800-5653-11eb-8596-34bbf4c345c1.PNG)

Plus build couldn't double-click to add program to Internet Access Restrictions whitelist:
![2](https://user-images.githubusercontent.com/56181919/104579057-631c3780-5653-11eb-89c5-6ed2f008efdb.PNG)

**Comment by DavidXanatos** [comment]
There will be no double click but something much much better

if you enable this:
![grafik](https://user-images.githubusercontent.com/3890945/104817783-b80ea800-5823-11eb-88f3-94d0658028b8.png)

The prompt will have an additional option to yes, as seen in this screenshot

![grafik](https://user-images.githubusercontent.com/3890945/104817772-9f05f700-5823-11eb-9bff-3559b4e5c8cf.png)

When the drop down option is chosen it means yes and it adds the program to the list of allowed applciations.
