### ISSUE TITLE
Sandboxie high CPU usage on Windows 10

### ISSUE THREAD

**Issue by motcaiten0** [sandboxie-plus/Sandboxie#3804]
### Describe what you noticed and did

Hi everyone, i have big trouble with sandboxie.
On windows 7, sandboxie work fine with ~100 box = 600 account game (game logic) take 50% CPU usage.
But on Windows 10, sandboxie not good, only 5 box = 30 account game take 100% CPU usage (task manager 100%, HWmonitor = 100% and max watts and temp CPU so high, process explorer = 2%)
If i login without sandboxie, 30 account game on Windows 10 = 2% CPU usage task manager, temp fine, HWmonitor low watts.
So, is trouble is sandboxie not good in windows 8 8.1 10 11, my community (game private) have ~50 people got trouble like me and all go on windows 7.
The game without sandboxie still take low CPU usage, game within sandboxie take high CPU usage, i'm tried "Run thiss program in compatibility mode for Windows 7" and still high CPU usage. Only way can fix is back to windows 7
P/s: Sandboxie and Sandboxie Plus same trouble, test today last update.

### How often did you encounter it so far?

always

### Expected behavior

Make game in sandboxie take CPU usage lower like Windows 7

### Affected program

Not relevant

### Download link

not available

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

plus x64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro, LTSC and Windows 11

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Windows Defender

**Comment by motcaiten0** [comment]
There when i login 30 account on Windows 10
![image](https://github.com/sandboxie-plus/Sandboxie/assets/166610022/1502c2e4-449b-4e97-ba29-ddc1545d6703)

**Comment by offhub** [comment]
Have you tried with older versions?

**Comment by motcaiten0** [comment]
> Have you tried with older versions?

Yeah i did, tried ~30 verison windows 10 11 winserver 2019, 2022, and with ~50 version sandboxie,
Only way is back to windows 7.
I can upload my game and auto login (~150mb) with video test, you can test by yourself.

**Comment by offhub** [comment]
Have you tried it in the Application Compartment type sandbox? Also, can you share your sandboxie configuration as well.
