### ISSUE TITLE
When I change the BlockDNS and BlockPorts options, the Apply button is not activated

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3807]
### Describe what you noticed and did

1. Change the settings.
2.  'Apply' remains grayed out.
3. Even if you change and save other settings in the same window, the changes in these settings are not applied.

### How often did you encounter it so far?

Every time

### Expected behavior

After making changes to these options, the Apply button should be activated, and when applied, the necessary settings should be added to or removed from the configuration depending on the change made.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.13.5 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.4291)

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Windows Defender

**Comment by bastik-1001** [comment]
This is very easy to reproduce. I get the same result.
