### ISSUE TITLE
Fail to create directory for new snapshot

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#381]
![1](https://user-images.githubusercontent.com/56181919/104588877-f14aea80-5660-11eb-89ec-a3d0802b24e8.PNG)
Still failure after reboot system.

**Comment by DavidXanatos** [comment]
does that only happen when the sandbox is empty?

**Comment by DavidXanatos** [comment]
assuming its this case its fixed in the next build

**Comment by 0x391F** [comment]
> 
> 
> does that only happen when the sandbox is empty?

Yes, you're right.
