### ISSUE TITLE
Enabling "DropAdminRights/FakeAdminRights" adds "BlockInterferePower and ForceProtectionOnMount" to the INI

### ISSUE THREAD

**Issue by SandboxerX86** [sandboxie-plus/Sandboxie#3825]
### Describe what you noticed and did

Create New Box and select Standard Sandbox
Open Sandbox Options and go to Security Options
Check "Drop rights from Administrators and Power Users groups", "Make applications think they are running elevated" or both under Elevation Restrictions and apply
Check the INI settings for that sandbox and you will see that these 2 lines have been added in addition to the corresponding ones
DropAdminRights=y
FakeAdminRights=y
**BlockInterferePower=n
ForceProtectionOnMount=n**

This does not happen if "Make applications think they are running elevated" is selected during the sanbox creation wizard using Advanced Options as enabling that option in there only adds DropAdminRights and FakeAdminRights to the INI.

### How often did you encounter it so far?

Always

### Expected behavior

BlockInterferePower=n and ForceProtectionOnMount=n should not be added to the INI

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus v1.13.4 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

**Comment by SandboxerX86** [comment]
I found another bug related to this.

Create New Box, select Standard Sandbox and check Configure advanced options
Click Next on the first window and check "Make applications think they are running elevated" under Admin Options on the second one. You will see DropAdminRights=y and FakeAdminRights=y are added to the INI
Open Sandbox Options and go to Security Options
Uncheck "Drop rights from Administrators and Power Users groups", "Make applications think they are running elevated" or both under Elevation Restrictions and apply
DropAdminRights=y and FakeAdminRights=y are deleted from the INI but BlockInterferePower=n and ForceProtectionOnMount=n are added.

Seems like clicking on "Drop rights from Administrators..." and/or "Make applications think...." add those two extra settings, doesn't matter if the click is for turning em On or Off.

**Comment by SSJPKXL** [comment]
What does ForceProtectionOnMount do? I can't find in documents, which are very scattered.

**Comment by offhub** [comment]
See https://github.com/sandboxie-plus/Sandboxie/pull/3736
