### ISSUE TITLE
can't install rust with rustup-init and windows gnu toolchain

### ISSUE THREAD

**Issue by m0rph3usX** [sandboxie-plus/Sandboxie#3826]
### Describe what you noticed and did

Seems linke a similar issue, which should be fixed already?
https://github.com/sandboxie-plus/Sandboxie/issues/3481

Using Sandboxie v.1.13.3

1. create a complete new sandbox
2. drag n drop "rustup-init.exe" to sandbox
4. install rust with "x86_x64-pc-windows-gnu" toolchain
  - press [2] key (customize installation)
  - enter "x86_x64-pc-windows-gnu"
  - press [ENTER]
  - press [ENTER]
  - press [y] and [ENTER]
  - press [1]

https://github.com/sandboxie-plus/Sandboxie/assets/44797288/fb55c573-4089-4835-a5d2-7322e0c5f692

### How often did you encounter it so far?

every time

### Expected behavior

Install rust without errors

### Affected program

rustup-init.exe

### Download link

https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

v.1.13.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

-

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Win10 Pro 22H2, Build 19045.4291

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator).

### Please mention any installed security software

none

### Did you previously enable some security policy settings outside Sandboxie?

-

### Sandboxie.ini configuration

```shell
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
```

**Comment by offhub** [comment]
Probably hard linking issue @DavidXanatos 

> run cmd as admin
```bat
MKLINK /H "%temp%\test.ini" "C:\Windows\Sandboxie.ini"
```
> Incorrect function.

![sbie3826hl](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/02e57605-964c-43f0-8f85-cfb742f7dcda)

**Comment by DavidXanatos** [comment]
hmm.. hard links complicate things, as they are a level lower than symlinks and junctions, if you hard link a file booth actual paths are actually representing the real file on a filesystem level. There is not real path and link path... Meaning: 
1. You can not hard link files across volumes, you can only create hard links on the same partition
2. We can not apply our usual access controls even the driver at the level it operates currently would fail to protect a host file for which a sandboxed hard link was created, as for it it looks like the file is a sandboxed file.
3. The sandbox being on a different volume than the linked file could not work, full stop.
So how do we get it to work: 
a. We redirect the operation to the SbieSvc and make it ensure that only files residing in the sandbox already can be hard linked.
b. We add a mechanism to SbieDll ensuring that if a program tries to hard link a host file the file is first copied into the sandbox and only then the SbieSvc is invoked to create the box to box hardlink.

**Comment by DavidXanatos** [comment]
This actually looks simpler then expected, we can adapt the file rename logic a bit to cover link creation, same restrictions same conditions, we can rename or link only to a file we have a write access to which we don't get for host files.
A fix should be included in the next build.
