### ISSUE TITLE
NSIS Can't find KmdUtil.exe, and neither can I.

### ISSUE THREAD

**Issue by tbacon1** [sandboxie-plus/Sandboxie#383]
I get the following error when trying to create the installer:

ReserveFile: "${BIN_ROOT_$%SBIE_BUILDARCH%}\KmdUtil.Exe" -> no files found.
Usage: ReserveFile [/nonfatal] [/r] [/x filespec [...]] file [file...] | [/nonfatal] /plugin file.dll
Error in script "C:\Sandboxie\Sandboxie-master\Sandboxie\install\SandboxieVS.nsi" on line 215 -- aborting creation process

Looked for KmdUtil.exe myself, and I couldn't find it anywhere in the Sandboxie directory.

Also, the documentation for copying the NSIS updates needs to be updated, the NSIS Modern UI directory has changed (at least on my system). The language files folder is found in the root of the contrib folder, not in the Modern UI folder.

**Comment by DavidXanatos** [comment]
compile the entire solution than you will get kmdutill.exe

here is a batch script to create the installers
```
set SbieVer=5.45.2

set SBIE_BUILDARCH=x64
"C:\Program Files (x86)\NSIS\makensis.exe" -- %~dp0\..\Sandboxie\install\SandboxieVS.nsi

set SBIE_BUILDARCH=Win32
"C:\Program Files (x86)\NSIS\makensis.exe" -- %~dp0\..\Sandboxie\install\SandboxieVS.nsi
```

Alsoyou dont use a modern NSIS but an old 2.5, see the readme.txt in the install dir
