### ISSUE TITLE
Can't run software

### ISSUE THREAD

**Issue by yunyty** [sandboxie-plus/Sandboxie#386]
Hi,

I'm using Windows 10 Ver 1909 Build 18363.1316

SBIE1231 Initialization failed for process Launcher.exe [C0000038 / 66]
SBIE1231 Initialization failed for process  [C0000001 / A8]
SBIE2314 Canceling process Launcher.exe

![image](https://user-images.githubusercontent.com/16714994/104811788-8bad5880-5830-11eb-947e-5a905c4298dd.png)

**Comment by necros2k7** [comment]
![image](https://user-images.githubusercontent.com/16452453/104813965-6a8f3c80-581d-11eb-857e-242c0aae4db3.png)

**Comment by DavidXanatos** [comment]
the connection error should be fixed in nect build, till then just pres connect again than it works
