### ISSUE TITLE
Delay in launching forced programs after version 1.12.9

### ISSUE THREAD

**Issue by ILoveSandboxie** [sandboxie-plus/Sandboxie#3868]
### Describe what you noticed and did

Hello, sorry for the English and Thanks in advance.
As per the title, I don't know if it only happens to me, when I set forced programs up to version 1.12.9 they are started in a very short time, while in subsequent versions this is not the case.
I use Windows 10 Home (x64) Build 10586.1176 (1511/TH2)
Best regards.

### How often did you encounter it so far?

Always.

### Expected behavior

Like previous versions.

### Affected program

Everyone.

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.12.9 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression from previous versions?

The issue was introduced the first time in Release v1.13.0 / 5.68.0

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Home (x64) Build 10586.1176 (1511/TH2)

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

COMODO antivirus

**Comment by offhub** [comment]
When I tried it on a virtual machine, I did not experience any loading delay. How much of a delay are you talking about? What are your Sandboxie settings?

**Comment by love-code-yeyixiao** [comment]
There are few features introuduce in the follow 1.13.0 version(https://github.com/sandboxie-plus/Sandboxie/compare/v1.12.9...v1.13.0?diff=split&w=#):
In Sandboxie/core/dll/dllhook.c,1245, the hook in SbieDll was changed,and the trace mechinsal was also changed.(https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md#added-7)
In Sandboxie/core/drv/syscall.c,the mechinsal was also changed.(https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md#fixed-7)

Maybe the two changes make the speed slow.

**Comment by ILoveSandboxie** [comment]
Hi, sorry but I expressed myself badly.
Forced programs start normally, but if, for example, if I set a forced program in the sandbox to watch video files and I click on a video file associated with that program, a delay of 6 or more seconds occurs, which does not happen until to version 1.12.9

**Comment by offhub** [comment]
Which app?

**Comment by ILoveSandboxie** [comment]
The example app is Potplayer.

**Comment by DavidXanatos** [comment]
it seams the issue is related to slow start of sandboxiecrypto.exe when the process is already runnign in the sandbox the delay is not present

**Comment by DavidXanatos** [comment]
After a 3 hour investigation I have identified and fixed the issue, the issue was with the new way sandboxie hooks the scm functions, and may have caused other issues as well, thanks for reporting the issue
