### ISSUE TITLE
INVALID OWNER (CreateFile)

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#3869]
### Describe what you noticed and did

When trying install [UnityHubSetup.exe](https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe) in sandbox, I found that installation process checks owner of temp file and refuses to proceed installation.

![image](https://github.com/sandboxie-plus/Sandboxie/assets/25817412/bb082778-0270-4258-9645-a5002b8becf8)
![image](https://github.com/sandboxie-plus/Sandboxie/assets/25817412/d79b6380-4db3-4588-af8f-f04454d602cc)

### How often did you encounter it so far?

Always.

### Expected behavior

An opportunity to get around this problem.

### Affected program

Unity Hub Installer

### Download link

https://unity.com/download#how-get-started

### Where is the program located?

Any.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

1.13.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie-Plus from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

10.0.17763.5458

### In which Windows account you have this problem?

A local account (Administrator). An account with UAC protection completely turned off.

### Sandboxie.ini configuration

```shell
UsePrivacyMode=n
UseSecurityMode=n
DropAdminRights=n
FakeAdminRights=n
ProtectHostImages=y
AllowRawDiskRead=n
NotifyDirectDiskAccess=y
BlockNetworkFiles=y
BlockNetParam=y
NtNamespaceIsolation=y
RestrictDevices=y
SysCallLockDown=y
ClosePrintSpooler=y
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
```

**Comment by offhub** [comment]
Please try with the [latest release](https://github.com/sandboxie-plus/Sandboxie/releases/latest) version.

I tried it on three different versions of Windows (on Hyper-V) and had no problems installing it on any of them.

Sandboxie-Plus 1.13.7
Windows 10 1803, Windows 10 22H2, Windows 11 23H2

> ProtectHostImages=n
```ini
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
SandboxieLogon=y
UsePrivacyMode=n
UseSecurityMode=n
DropAdminRights=n
FakeAdminRights=n
ProtectHostImages=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=y
BlockNetworkFiles=y
BlockNetParam=y
NtNamespaceIsolation=y
RestrictDevices=y
SysCallLockDown=y
ClosePrintSpooler=y
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
```
