### ISSUE TITLE
The download gave a trojan virus

### ISSUE THREAD

**Issue by CoolDude562** [sandboxie-plus/Sandboxie#387]
This is a serious virus that can cause massive harm to the victim. Download Sandboxie at your own risk. If I were you I wouldn't download it at all.

**Comment by pingogeek** [comment]
where did you download from? close issue if not from official source

**Comment by isaak654** [comment]
@CoolDude562 It doesn't really mean anything if you don't describe what you did exactly.

**Comment by DavidXanatos** [comment]
Consult virus total, and keep in mind that stuff that has < ~15 detections normally is harmless and just the detection is bogus.

**Comment by isaak654** [comment]
> 
> 
> Consult virus total, and keep in mind that stuff that has < ~15 detections normally is harmless and just the detection is bogus.

I agree, this is a clear example of false positive:
https://www.virustotal.com/gui/file/91cc7e28c188ca7d29215be9561f11ebdcb8bf50e603b9253ad5a7b2652d8b48/detection

Only three AVs detect SbieSvc.exe incorrectly as malware

The solution in this case is: get in touch with Microsoft to fix their issue:
https://www.microsoft.com/en-us/wdsi/filesubmission/
