### ISSUE TITLE
Is there any IDE that you can even install and run in Sandboxie?

### ISSUE THREAD

**Issue by trewqaGGG** [sandboxie-plus/Sandboxie#3870]
### Describe what you noticed and did

So almost a year ago now, I tried installing Visual Studio inside Sandboxie. As I discovered and rediscovered just now the problem that installing Visual Studio does not work in Sandboxie has existed for years and has not yet been solved.
https://github.com/sandboxie-plus/Sandboxie/issues/2730

Today I wiped away my tears and decided to try for another IDE, Jetbrains Rider.
To my unastonishment, although the installation seems to have successfully completed, running it (even in administrator mode) yields this error:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/148734655/54993802-4a13-42eb-bab0-cd799eacc245)

So I must ask, is there really any IDE that you can install and run in Sandboxie Classic?

Windows 10 20h2
classic 5.66.4

**Comment by DavidXanatos** [comment]
for me it installed and runs fine
