### ISSUE TITLE
[Windows 10 v.2004] Key insertion/detection fail?

### ISSUE THREAD

**Issue by lst97** [sandboxie-plus/Sandboxie#39]
Hi DavidXanatos, after I update to Windows 10 20H1, I can only do English input. Any idea? 
Thank you.

The right hand-side is sandboxie, non-sandboxie on the left.

![InstantGif_2020 05 31-14 33_01](https://user-images.githubusercontent.com/16495912/83344568-dc2c8000-a34b-11ea-8bb7-aa7744e25a87.gif)

I can't find other log for sandboixe but only Resource Access Monitor. Hope it would help.
[RAM.txt](https://github.com/sandboxie-plus/Sandboxie/files/4707406/RAM.txt)

_- Sandboixe info
Version 5.40.1 (64 bit)_

- OS info
_Edition:       Windows 10 Pro
Version:       2004
OS build:     19041.264
Experience:  Windows Feature Experience Pack 120.2202.130.0_

**Comment by DavidXanatos** [comment]
e.... hmm...
have you tried using an empty sandbox?

**Comment by lst97** [comment]
> e.... hmm...
> have you tried using an empty sandbox?

I just tried to create a new sandboxie environment call "test", run the browser again, and I can't type Chinese as before.
The temporary solution is that I have to type the words outside the sandbox, than copy to the browser.

I believe it's because of the Windows 10. I use 1909 before, and it's working fine, after I update to 2004, it become a problem.

**Comment by DavidXanatos** [comment]
> 
> I believe it's because of the Windows 10. I use 1909 before, and it's working fine, after I update to 2004, it become a problem.

That is likely, I will put it on the long long list of tings to fix.

But please understand that it will take some time to get to it there are som many issues right now...

**Comment by lst97** [comment]
It will be no problem, as long as I can just copy && past, and I am not using Chinese so often. For me I am not brave and experience enough to continue this wonderful project, Respect.

Please let me know if there're a fix, I am more than happy to test it for you.

**Comment by DavidXanatos** [comment]
Ok will do when I have  a fix I will post it in this issue

**Comment by LakeishaKowalczyk** [comment]
What input method editor do you use? Most  IME require setting resource access permissions. Microsoft's own IME may also need to be set after an update

Maybe you can search for "your IME name + Sandboxie" for a solution

For your information
http://yong.dgod.net/read.php?tid=2659&fid=2
https://github.com/rime/weasel/issues/143

**Comment by lst97** [comment]
> 
> 
> What input method editor do you use? Most IME require setting resource access permissions. Microsoft's own IME may also need to be set after an update
> 
> Maybe you can search for "your IME name + Sandboxie" for a solution
> 
> For your information
> http://yong.dgod.net/read.php?tid=2659&fid=2
> [rime/weasel#143](https://github.com/rime/weasel/issues/143)

My IME is the stock from Microsoft which is ChtIME.exe I tried to forced it to run in sandboixe, and it didn't work.

And I am not sure what the BaseNamedObjects && OpenWinClass string I should enter.

Also I found the post from long time ago showing sandboixe have that problem before, and it get fixed internally not by adding IRC access.

Thanks for the information.

**Comment by LakeishaKowalczyk** [comment]
> 
> 
> > I believe it's because of the Windows 10. I use 1909 before, and it's working fine, after I update to 2004, it become a problem.
> 
> That is likely, I will put it on the long long list of tings to fix.
> 
Just out of curiosity, coulde you show your list，want to see see your list

**Comment by Xegony** [comment]
> Ok will do when I have a fix I will post it in this issue

Thank you

**Comment by skygunner** [comment]
Windows 10 20H2:

Google Pinyin V2/V3, input works without any settings.

Microsoft Pinyin, failed

rime, failed. 

Run rime in the sandboxie like this will work:
"D:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "C:\Sandbox\username\DefaultBox\drive\D\Program Files (x86)\Tencent\WeChat\WeChat.exe"
"D:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "D:\Program Files (x86)\Rime\weasel-0.14.3\WeaselServer.exe"

Both Google Pinyin and Rime is slow while inputting Chinese in sandboxie, will take some time before showing up the inputted keys and candidates. 

Run Microsoft Pinyin in sandboxie won't work. 

For Rime, someone mentioned adding this 
\Device\NamedPipe\username\WeaselNamedPipe to resource file access , full access, I don't know how to do this.

**Comment by sky96111** [comment]
Try
Options-Global Settings-Sofeware Compatibility-[✓]Windows10 Core UI
and Apply.
It works for me.

**Comment by DavidXanatos** [comment]
this is applyed automatically sinde the 0.5.4d build
