### ISSUE TITLE
autocad 2025 installation problem

### ISSUE THREAD

**Issue by SJK9906** [sandboxie-plus/Sandboxie#3906]
### Describe what you noticed and did

download autodesk atuocad 2025
run installer
see the rror

### How often did you encounter it so far?

5 times

### Expected behavior

installer install without eny error

### Affected program

Auto desk Aatuocad 2025

### Download link

https://www.autodesk.it/education/edu-software/overview?sorting=featured&filters=individual

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Did the program or any related process close unexpectedly?

Yes, it did. I'm going to share the .dmp file(s) in a later comment.

### What version of Sandboxie are you running now?

sandboxie plus v1.13.7 

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

no autocad never work on sandboxie

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

windows 23H2 pro 64bit

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator)., A Microsoft account (Standard user)., A Microsoft account (Administrator)., An account with secure desktop turned off for UAC prompts., An account with UAC protection completely turned off., An account with UAC protection set to Always notify., I use the built-in Administrator account., I use the built-in Administrator with Admin Approval Mode turned on., I reproduced it under a Guest account.

### Please mention any installed security software

windows defender

### Trace log

[autocad 2025.zip](https://github.com/sandboxie-plus/Sandboxie/files/15351921/autocad.2025.zip)

### Sandboxie.ini configuration

```shell
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00ffff,ttl,6
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10
MsiInstallerExemptions=y
NeverDelete=y
NeverRemove=y
AllowRawDiskRead=y
NotifyDirectDiskAccess=y
AllowBoxedJobs=y
CallTrace=*
FileTrace=*
PipeTrace=*
KeyTrace=*
IpcTrace=*
GuiTrace=*
ClsidTrace=*
NetFwTrace=*
ApiTrace=y
DebugTrace=y
ErrorTrace=y
```

**Comment by SJK9906** [comment]
dump link https://mega.nz/file/krNUlLKR#5ig1k5-EqLUqwDLqlGo-K1C66x1tG9fuhY74BTCvt9Y
all are made manually from task manage after siing Error in autocad installer
Error Code: 327742

**Comment by SJK9906** [comment]
dump link https://mega.nz/file/kXUgwYyb#5ig1k5-EqLUqwDLqlGo-K1C66x1tG9fuhY74BTCvt9Y
all are made manually from task manage after siing Error in autocad installer
Error Code: 327742

**Comment by love-code-yeyixiao** [comment]
Duplicate #3795 
Please not to submit the same issue over and over again.
