### ISSUE TITLE
Can I install this if I already have the old version 5.28?

### ISSUE THREAD

**Issue by Jimmy03** [sandboxie-plus/Sandboxie#392]
Will this upgrade the old installation, or do I need to uninstall it before installing Sandboxie Plus?

I have the original Sandboxie 5.28  
  
Edit: I assume this will work?  Are there any other potential issues?
https://github.com/sandboxie-plus/Sandboxie/issues/259  
  
Also thanks for bringing this essential program back to life.

**Comment by NewKidOnTheBlock** [comment]
When going from Sophos -> Plus, I'd recommend:
1. Backup Sandboxie.ini in C:\Windows\
2. Uninstall
3. Reboot
4. Install SB plus
