### ISSUE TITLE
Chrome stopped printing

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#3926]
### Describe what you noticed and did

[gazuzzaki over at the forums posted](https://forum.xanasoft.com/viewtopic.php?f=16&t=808):

 ERROR:
No error message. Just grayed out Print/Preview dialog. See attached screenshot.

TIMING:
First encountered Monday, May 20th, 2024 after the latest Chrome update.

STEPS TO REPRODUCE:
Any attempt to print, such as Ctrl+P, while Chrome is running in Sandboxie. Printing works fine outside the sandbox. Verified on several machines.

OTHER BROWSERS:
Tested with Firefox - unaffected. Printing in Firefox, including installed directly into a sandbox, works as expected.

### Expected behavior

To print, I assume.

### Affected program

Google Chrome Version 125.0.6422.61 (Official Build) (64-bit)

### Download link

Not provided

### Where is the program located?

This was not stated.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Classic 5.68.7 (64-bit)

### Is it a new installation of Sandboxie?

The original installations date from ~2016 and are being regularly updated.

### Is it a regression from previous versions?

No, I've never encountered this issue before.

### In which sandbox type you have this problem?

This was not mentioned. Although personally, I'm a user since Tzuk's times, I don't know how to answer this question. I am not aware of there being different types of sandboxes.

### Can you reproduce this problem on a new empty sandbox?

Yes.

### What is your Windows edition and version?

Windows 10 Home Version 22H2 OS build 19045.4412

### In which Windows account you have this problem?

Standard user.

### Please mention any installed security software

None, except Windows Defender that came by default with Windows 10.

### Did you previously enable some security policy settings outside Sandboxie?

No.

### Sandboxie.ini configuration

[GlobalSettings]

Template=Edge_Fix
Template=Edge_Win11Fix
Template=VirtualDesktopManager
Template=AdobeDistiller
Template=AdobeAcrobatReader
Template=WindowsRasMan
Template=7zipShellEx
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
ActivationPrompt=n

[DefaultBox]

ConfigLevel=10
AutoRecover=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Enabled=y
DropAdminRights=y

[UserSettings_25CC03D3]

SbieCtrl_UserName=secretary
SbieCtrl_NextUpdateCheck=1716839498
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=572,460,873,517
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
BoxDisplayOrder=Browsing_Dubious,DefaultBox,Specific_Purpose(Amazon,Quickbooks),Forced_Acrobat,Forced_Acrobat_Full,Forced_Chrome,FORCED_Firefox,Forced_iexplore,Forced_MS_Office,Forced_Skype,Forced_USB,Forced_VideoLAN,RingCentral_Admin_DO_NOT_CLEAN,Camera_Testing_Leave_Alone,Web_design,WZ_HVAC,Z_FB_Ondrej_DONT_delete
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_RecoverTarget=D:\Dropbox (Sontag, Inc.)\3-HR\New Hire Documents
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_HideMessage=2308,[41 / C0000024]
SbieCtrl_HideMessage=2224,AcroCEF.exe [Forced_Acrobat]
SbieCtrl_HideMessage=2321,[C0000022 / 77]
SbieCtrl_HideMessage=2335,msedge.exe [88 / 0]
SbieCtrl_HideMessage=2191,firefox.exe
SbieCtrl_HideMessage=2224,msedge.exe [Forced_iexplore]
SbieCtrl_HideMessage=2192
SbieCtrl_HideMessage=2214,MSIServer
SbieCtrl_HideMessage=2219,SandboxieDcomLaunch.exe [Forced_Acrobat_Full]
SbieCtrl_HideMessage=2220,SandboxieDcomLaunch.exe [Forced_Acrobat_Full]
SbieCtrl_HideMessage=2101,ConnectPort (C0000022) access=001F0000 initialized=1
SbieCtrl_HideMessage=2219,SandboxieDcomLaunch.exe [Forced_Chrome]
SbieCtrl_HideMessage=2220,SandboxieDcomLaunch.exe [Forced_Chrome]
SbieCtrl_HideMessage=2219,SandboxieDcomLaunch.exe [Z_FB_Ondrej_DONT_delete]
SbieCtrl_HideMessage=2220,SandboxieDcomLaunch.exe [Z_FB_Ondrej_DONT_delete]
SbieCtrl_HideMessage=2220,SandboxieDcomLaunch.exe [FORCED_Firefox]
SbieCtrl_HideMessage=2219,SandboxieDcomLaunch.exe [FORCED_Firefox]
SbieCtrl_HideMessage=2214,bits
SbieCtrl_HideMessage=2219,SandboxieDcomLaunch.exe [WZ_HVAC]
SbieCtrl_HideMessage=2220,SandboxieDcomLaunch.exe [WZ_HVAC]
SbieCtrl__IgnoreUpdate=5.49.0
SbieCtrl__IgnoreUpdate=5.51.3
SbieCtrl__IgnoreUpdate=5.53.3
SbieCtrl__IgnoreUpdate=5.55.7
SbieCtrl__IgnoreUpdate=5.55.8
SbieCtrl__IgnoreUpdate=5.55.10
SbieCtrl__IgnoreUpdate=5.55.13
SbieCtrl__IgnoreUpdate=5.55.20
SbieCtrl__IgnoreUpdate=5.55.22
SbieCtrl__IgnoreUpdate=5.56.3
SbieCtrl__IgnoreUpdate=5.57.7
SbieCtrl__IgnoreUpdate=5.59.2
SbieCtrl__IgnoreUpdate=5.60.0
SbieCtrl__IgnoreUpdate=5.60.3
SbieCtrl__IgnoreUpdate=5.51.6
SbieCtrl__IgnoreUpdate=5.64.8
SbieCtrl__IgnoreUpdate=5.65.5
SbieCtrl__IgnoreUpdate=5.66.2
SbieCtrl__IgnoreUpdate=5.66.4
SbieCtrl__IgnoreUpdate=5.67.3
SbieCtrl__IgnoreUpdate=5.67.9
SbieCtrl__IgnoreUpdate=5.68.3
SbieCtrl__IgnoreUpdate=5.68.7
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_SettingChangeNotify=n
SbieCtrl_BoxExpandedView=Browsing_Dubious,Forced_Acrobat,FORCED_Firefox,Forced_iexplore,FORCED_RingCentral,Forced_VideoLAN

[Browsing_Dubious]

ConfigLevel=10
AutoRecover=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Enabled=y
CopyLimitKb=300420

[Forced_Chrome]

ConfigLevel=10
AutoRecover=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Enabled=y
DropAdminRights=y
ForceProcess=chrome.exe

[Forced_Acrobat]

ConfigLevel=10
AutoRecover=y
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Enabled=y
DropAdminRights=y
ForceProcess=acrobat.exe
ForceProcess=adobe_updater.exe
ForceProcess=acrord32.exe
ForceProcess=acrobatinfo.exe

[UserSettings_25D003C2]

SbieCtrl_UserName=waltadmin
SbieCtrl_ShowWelcome=n
SbieCtrl_NextUpdateCheck=1596077706
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_WindowCoords=200,150,1237,703
SbieCtrl_ActiveView=40021
SbieCtrl_AutoApplySettings=n

[Forced_VideoLAN]

ConfigLevel=10
AutoRecover=y
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Enabled=y
DropAdminRights=y
ForceProcess=vlc.exe

[Forced_iexplore]

ConfigLevel=10
AutoRecover=y
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Enabled=y
DropAdminRights=y
ForceProcess=msedge.exe
ForceProcess=iexplore.exe

[FORCED_RingCentral]
ConfigLevel=10
AutoRecover=y
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Enabled=y
DropAdminRights=y

[FORCED_Firefox]
ConfigLevel=10
AutoRecover=y
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Enabled=y
DropAdminRights=y
ForceProcess=firefox.exe

Edit: Updated post with new information provided by the user.

**Comment by DavidXanatos** [comment]
does this issue started with a particular chrome build?
Or windows update, or sandboxie release?

**Comment by ITSWNY** [comment]
Unable to print from MS Edge starting today. 
We force Edge to run sandboxed
Running Edge outside of sandbox; it prints fine. In sandbox, grayed out on the print preview screen like original poster's Chrome

Sandboxie-Plus-x64-v1.13.7
Windows 10

Recently installed windows updates:
KB5036892
KB5036608
KB5034763

Uninstalled, updated to latest stable, deleted sandbox (That's the extent of my Sandboxie troubleshooting toolkit unfortunatly)

**Comment by bastik-1001** [comment]
The original reporter replied to the question if a previous version works:

> Printing from sandboxed Chrome DOES work with:
> 
> Chrome:
> Version 124.0.6367.202 (Official Build) (64-bit)
> 
> Printing from sandboxed Chrome does NOT work with:
> 
> Chrome:
> Version 125.0.6422.61 (Official Build) (64-bit)
> 
> So yes, it looks like the issue really is related to the latest version of Chrome.
>

**Comment by WSC33** [comment]
I have exactly the same issue with Chrome which seems to have started with the latest Chrome release.  The print works fine outside of Sandboxie.  I have Version 5.68.7, 64 bit of Sandboxie.

Thanks.

WSC33

**Comment by offhub** [comment]
Can you print from the system dialog? `Ctrl+Shift+P`

**Comment by DavidXanatos** [comment]
Seams chrome is using some new COM based printing function, in a Green Box with Template=OpenCOM printing works

**Comment by DavidXanatos** [comment]
Which is the exact chrome version which introduced this issue?

**Comment by WSC33** [comment]
For me it was Version 125.0.6422.113 (Official Build) (64-bit).

**Comment by WSC33** [comment]
"Seams chrome is using some new COM based printing function, in a Green Box with Template=OpenCOM printing works"

Are you going to release a patch or is there a setting chang that I need to make?  I have the latest Classic SB.

**Comment by WSC33** [comment]
"Can you print from the system dialog? Ctrl+Shift+P"

No, it jams and lockes up the screen.  I have to kill the web page to exit.

**Comment by Tsimmes** [comment]
Also cannot print from Microsoft Edge with Sandboxie 5.68.7, 64 or x64-v5.68.4. Print icon greyed out, All printing functions work fine when Sandboxie is uninstalled.

**Comment by new-userAOI** [comment]
I have the same behavior on edge(ver:125.0.23.35) with the latest versions of Microsoft kbs. printing and blank page screen, unable to print anything, error message: "print preview failed".
sandboxie version: 5.67.7 (64 bits)
do you foresee a correction in the future?
Sincerely,

**Comment by jedimasterspaz** [comment]
I opened Template.ini for Sandboxie Classic, to edit it, the comment section in the beginning said not to edit Template.ini.  Do I edit it anyway?

**Comment by jedimasterspaz** [comment]
I opened Template.ini for Sandboxie Classic to edit it, but the comment section at the beginning said not to. Should I edit it anyway? If I do, how do I get past the permissions issue?

**Comment by Tsimmes** [comment]
It's been well over three weeks now; no printing function from within Chrome or Edge. I purchased my original version of Sandboxie from Tzuk; maybe you folks should stop asking for donations until you get this figured out.

**Comment by brianshmrian** [comment]
I was able to get printing to work again in Sandboxie+Chrome by passing the following launch flag to chrome

--disable-features=PrintCompositorLPAC

I found the suggestion here: https://support.google.com/chrome/thread/276904963/print-preview-failed-google-chrome?hl=en

**Comment by lwcorp** [comment]
Thanks! But please be aware this "fix" might only temporary, you're just buying time as well as running a command line parameter without letting the user knows. 
1. Are you sure disabling this feature has no downside?
1. Does it leave any way to run without this command line parameter to find out if Chrome itself fixed the issue?
1. In that Chrome ticket report, they clearly stated in [comment #35](https://issues.chromium.org/issues/339994760#comment35):
> I continue to recommend that we do not support running Chrome outside of the normal installation directory, and other things might continue to break if you choose to do so going forward.

Their quote makes it seem this issue is just a symptom - in the future if you can't somehow trick Sandboxie Chrome to think it's the real Chrome, it will lose more and more features.

**Comment by DavidXanatos** [comment]
We did a similar thing with electron apps and gpu renderer long time ago and it still works.
This Less Privileged App Container are not compatible with non green sandboxie boxes.
