### ISSUE TITLE
If FileRootPath of the sandbox is set to a network drive, the Notepad program running in the sandbox cannot save files properly.

### ISSUE THREAD

**Issue by pangshangji** [sandboxie-plus/Sandboxie#3927]
### Describe what you noticed and did

1. Create a new box.
2. Map a network drive locally as a T drive.
3. open Sandboxie.ini，add FileRootPath=\??\T:\Sandbox\%USER%\%SANDBOX% under the new sandbox.
4. Starting Notepad in a newly created sandbox and saving it to the Documents folder after entering content will result in an error message.

### How often did you encounter it so far?

every

### Expected behavior

Can be saved to the network drive normally.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.13.7 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 pro 22H2 64-bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Defender Antivirus

**Comment by DavidXanatos** [comment]
oh this is not a supported usecase!!!
there are a hundred things with that which could fail

**Comment by bastik-1001** [comment]
Can you explain briefly, what the issue is and why this isn't something that is supported? I am just curious and don't seem to mind that it is not.
