### ISSUE TITLE
[Usability] Add "auto scroll" in sbie messages, resource monitor, api call log context menu

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#393]
Because it's hard to see clearly when logs increase fast.

**Comment by isaak654** [comment]
I hope to see this someday, I'm using this feature a lot in Process Monitor.

**Comment by offhub** [comment]
It doesn't activate when I select `Auto Scroll` from the menu.

**Comment by DavidXanatos** [comment]
indeed will be fixed in the next release sorry about that
