### ISSUE TITLE
v2rayn running in sandboxie can change the system proxy

### ISSUE THREAD

**Issue by clk01** [sandboxie-plus/Sandboxie#3930]
### Describe what you noticed and did

v2rayn will change the system proxy to off by default, but why can a program running in sandboxie change the system settings?

### How often did you encounter it so far?

open v2rayn everytime

### Expected behavior

A program in sandboxie should not be able to change settings outside of sandboxie.

### Affected program

v2rayn

### Download link

https://github.com/2dust/v2rayN/releases

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

sandboxie plus 1.13.7

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than 1.5.3 / 5.60.3.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

windows 11 23h2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

MSE

**Comment by offhub** [comment]
Can you provide step-by-step instructions on how to reproduce the issue? Also, share your Sandboxie configuration.

**Comment by clk01** [comment]
https://github.com/sandboxie-plus/Sandboxie/assets/59333258/99dc3024-9674-4a0e-9293-b3d3917eeacb

**Comment by offhub** [comment]
You can block wininet.dll, but this time the proxy server may not work. Maybe there is a better solution? @DavidXanatos 

```
ClosedFilePath=*\wininet.dll
```

**Comment by clk01** [comment]
> You can block wininet.dll, but this time the proxy server may not work. Maybe there is a better solution? @DavidXanatos您可以阻止wininet.dll，但这次代理服务器可能无法正常工作。也许有更好的解决方案？@DavidXanatos
> 
> ```
> ClosedFilePath=*\wininet.dll
> ```

I don't think it's a matter of changing a configuration, a program running in sandboxie shouldn't be able to change settings outside of sandboxie. These are the changes that can be found, and maybe there are changes that aren't found. It's a security issue.

**Comment by clk01** [comment]
> You can block wininet.dll, but this time the proxy server may not work. Maybe there is a better solution? @DavidXanatos
> 
> ```
> ClosedFilePath=*\wininet.dll
> ```

**Comment by DavidXanatos** [comment]
wininet.dll uses a RPC call to a unsandboxed windows service which allows unprivileged processes to change that setting, this access is granted in a default template:

[Template_RpcPortBindings]
# windows proxy auto discovery
#Tmpl.ScanService=WinHttpAutoProxySvc
RpcPortBinding=WinHttp.dll,'ncalrpc:',Resolve=WPAD,TimeOut=y
RpcPortBindingSvc=WPAD,WinHttpAutoProxySvc

When you remove this from your tempaltes ini the access will be blocked,

we can look into
