### ISSUE TITLE
Add "Kill on Job Close" job limit on sandboxed process

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#3934]
### Is your feature request related to a problem or use case?

AFAIK Firefox uses "Kill on Job Close" job limit on its child process. 

### Describe the solution you'd like

I think sandboxie could add it on sandboxed process and make it more reliably when killing all sandboxed processes/clear sandbox,

**Comment by 0x391F** [comment]
By the way, I don't know if Sandboxie should limit global atoms access or not.

**Comment by love-code-yeyixiao** [comment]
Sandboxie uses isoations based on tokens,so it's not necessary to limit atom access,even if we don't block it,it will still not be able to access global atoms.

**Comment by love-code-yeyixiao** [comment]
And sandboxie allows processes to create their own jobs,so if a process use that,they can use freely.
Sandboxie mainly use unit "Sandbox" instead of job,so it's not necessary to do that.

**Comment by DavidXanatos** [comment]
see ProcessServer::KillAllHandler this is already in use
