### ISSUE TITLE
test 123 issue ini

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3946]
### Describe what you noticed and did

1. a
2. b
3. c

### Expected behavior

asd

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.13.5 64-bit

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.4291)

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Windows Defender

### Sandboxie.ini configuration

```ini
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
```

**Comment by offhub** [comment]
@isaak654 Can you delete this issue?

**Comment by isaak654** [comment]
> @isaak654 Can you delete this issue?

Only @DavidXanatos can do that.
