### ISSUE TITLE
Sandboxie Conflict software with Mirilis Action

### ISSUE THREAD

**Issue by Quassar89** [sandboxie-plus/Sandboxie#3958]
### Describe what you noticed and did

I wanna run Vivaldi in Sandboxie Plus 1.13.7 with runing software Called Action!
https://mirillis.com/pl/products/action.html

But when run software gather Vivaldi is killed.

### How often did you encounter it so far?

Always since i try run vivaldi inside sandboxie

### Expected behavior

Run both software with out issue.

### Affected program

Vivaldi (lates stable)

### Download link

https://mirillis.com/pl/pobierz-action

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.13.7 

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 22H2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

disabled all.

### Sandboxie.ini configuration

```ini
Its default. No extra settings etc.
```

**Comment by offhub** [comment]
Can you provide step-by-step instructions on how to reproduce the issue?

**Comment by offhub** [comment]
Please try it with the following setting:
```ini
ClosedFilePath=*\Mirillis\Action!\*
```

**Comment by Quassar89** [comment]
> ```ini
> ClosedFilePath=*\Mirillis\Action!\*
> ```

Used that one and worked
i recorded video as reproduce issue and fix apply

1) Run unsandboxed vivaldi 
2)Run Sandboxed vivaldi and crash (still 2 process runing i killed them and wiped box)
3)Apply fix manual in ini file and test with sucess.

https://www.youtube.com/watch?v=3kNHuBaw6n0

**Comment by Quassar89** [comment]
I did yet 4th test with out fix solution
i runed sandboxie but with Admin right, also work.

Looks like conflict with standard user.
Because i now sit on standard account, long time ago i used only admin acc in windows and that why i dont had problem in past.
