### ISSUE TITLE
DLL injection and LowLevel DLL fail on Win11 26100.712

### ISSUE THREAD

**Issue by SSJPKXL** [sandboxie-plus/Sandboxie#3966]
### Describe what you noticed and did

WinSCP, PuTTY, and Tixati do not work with the latest Sanboxie pre-release (any box type) on Windows 26100.712. Launching mentioned apps produces errors about DLL injection and LowLevel library.

### How often did you encounter it so far?

Always on Windows 26100

### Expected behavior

No errors

### Affected program

PuTTY, WinSCP, Tixati

### Download link

N/A

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did, but no .dmp file has been created in the system.

### What version of Sandboxie are you running now?

5.69 Classic

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 26100.712

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

None

**Comment by DavidXanatos** [comment]
I can not reproduce this issue
