### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by Pugfeidbrull** [sandboxie-plus/Sandboxie#397]
Provisional.Windows.7.Drivers.zip
324 KB
324 KB (331,813 bytes)
VirusTotal: 1 / 62
SHA-256	7811f1465d87965e1640b885ba7b6af5bb5a9f0415375f184dde3b003666fd2d
─────────────────────────────────────
Sandboxie-Classic-x64-v5.46.2.exe
2.79 MB 2.79 MB (2,926,243 bytes)
VirusTotal: 3 / 69
SHA-256	64114b8c428e7fee3820a7fa34f067a2bd61b6321bd6366249682b8ac43357c2
─────────────────────────────────────
Sandboxie-Classic-x86-v5.46.2.exe
2.27 MB
VirusTotal: Not able to download. Virus detected by Chrome, Edge, Firefox
"Sandboxie-Classic-x86-v5.46.2.exe Failed - Virus detected"
─────────────────────────────────────
Sandboxie-Plus-x64-v0.5.4c.exe
15.1 MB 15.1 MB (15,850,361 bytes)
VirusTotal: 0 / 70
SHA-256 9E68C3EBC1F9AA8ACCB2C92AFF9BF312BF521E0EFFB50A92F5A2F834E718E508
─────────────────────────────────────
Sandboxie-Plus-x86-v0.5.4c.exe
13 MB 12.9 MB (13,586,941 bytes)
VirusTotal: 0 / 69
SHA-256 743EC3BD20C86C6790357A207EBD8989F7F7E6A5DA67BD7EA78E303CBA174D43
─────────────────────────────────────
Source code
Sandboxie-0.5.4c.zip
(zip)
3.14 MB (3,295,451 bytes)
VirusTotal: 0 / 58
SHA-256	ed4647c6e5dd27b6251c2c4e66d3f2fb30e55fdadb9501cfdf080c5536e15620
─────────────────────────────────────
Source code
Sandboxie-0.5.4c.tar.gz
(tar.gz)
2.66 MB (2,796,049 bytes)
VirusTotal: 0 / 49
SHA-256	2ae235fd59d5f3dfd95e51281a0e36ea48d62f6ae3fad5102768e6b552283018

**Comment by abclution** [comment]
Yup getting malware and virus hits on it as well. 

Defender says: Win32/Wacatac.D9!ml

Sandboxie-Plus-x64-v0.5.4d.exe

**Comment by 0x391F** [comment]
I guess one reason is the install package doesn't have digital signature?

**Comment by typpos** [comment]
> Yup getting malware and virus hits on it as well.
> Defender says: Win32/Wacatac.D9!ml
> Sandboxie-Plus-x64-v0.5.4d.exe

Not at my end..
* Sandboxie-Plus-x64-v0.5.4d.exe
* sha256 03622313B75F684983E89963E913BD9AD0C21437E56B03E8D29009779FFA60F2
* VirusTotal says clean: https://www.virustotal.com/gui/file/03622313b75f684983e89963e913bd9ad0c21437e56b03e8d29009779ffa60f2/detection
* No MS Defender issue either

**Comment by ZetaoYang** [comment]
> Yup getting malware and virus hits on it as well.
> 
> Defender says: Win32/Wacatac.D9!ml
> 
> Sandboxie-Plus-x64-v0.5.4d.exe

Same with MS Defender.

**Comment by isaak654** [comment]
A `Trojan:Win32/Wacatac.D9!ml` warning by Microsoft Defender appeared to me in `C:\Program Files\Sandboxie\32\SbieSvc.exe` in a clean Windows 10 20h2 installation.

Proof is [here](https://www.virustotal.com/gui/file/91cc7e28c188ca7d29215be9561f11ebdcb8bf50e603b9253ad5a7b2652d8b48/detection).

People interested in Sandboxie should contact Microsoft to report it as incorrect malware:
https://www.microsoft.com/en-us/wdsi/filesubmission/

I just did it and I received [this](https://user-images.githubusercontent.com/12372772/104935021-04d0bb00-59ab-11eb-8ed4-d1582c62c6fe.png) confirmation email.

**Comment by abclution** [comment]
Problem is I started getting malware after running the portable version. Specifically chrome search/startup page replacing malware.
Literally in the middle of a reinstall so I can't check in a VM to verify but I think that this release may have been compromised.

**Comment by DavidXanatos** [comment]
The hash values are correct so VT reports false positives.

**Comment by isaak654** [comment]
> 
> Literally in the middle of a reinstall so I can't check in a VM to verify but I think that this release may have been compromised.

All Sandboxie releases are hosted in Github and they take all support requests very seriously:
https://support.github.com/contact

Most likely you were infected in your local machine. The only purpose of Sandboxie is to lock third-party software into a sandbox out of which they can't permanently modify the host system, so you still need a realtime antimalware protection to prevent the sandboxed content to be infected.

**Comment by Jimmy03** [comment]
Hopefully Sandboxie Plus can get a digital signature at some point.
