### ISSUE TITLE
[Feature Request] Add path whitelist function 

### ISSUE THREAD

**Issue by bigfoxtail** [sandboxie-plus/Sandboxie#398]
I want some of the software to access only certain folders to prevent privacy leakage, but it is very difficult for the current software to implement this requirement.
Please help me, thanks!

**Comment by DavidXanatos** [comment]
Such a thing is already on my todo fore some time now but its not super trivial

**Comment by bigfoxtail** [comment]
> Such a thing is already on my todo fore some time now but its not super trivial

Thank you very much, hope to use this function soon

**Comment by isaak654** [comment]
Update: if you have new suggestions, please post on the new issue #890, thanks.
