### ISSUE TITLE
Problem accessing a relative symlink with a target that starts with a dot

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3981]
### Describe what you noticed and did

The dot and the character after it are lost when the path is parsed.

```bat
@echo off

cd /d "%temp%"
md ".test"
mklink /d "testlink" ".test"
echo Sandboxie >"%temp%\.test\testfile.txt"
"C:\Program Files\Sandboxie-Plus\Start.exe" "%temp%\testlink\testfile.txt"
```

##### Result: (fail - sandboxed)
...\\AppData\Local\\Temp\\`est`\\testfile.txt

##### Result: (success - unsandboxed)
...\\AppData\Local\\Temp\\`.test`\\testfile.txt

### How often did you encounter it so far?

Every time

### Expected behavior

It should work without truncating the target folder name like outside the sandbox.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.14.1 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.4412)

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Microsoft Windows Defender

### Sandboxie.ini configuration

```ini
[DefaultBox]
```

**Comment by DavidXanatos** [comment]
please test the latest CI build also please test the other cases to ensure the fix did not break anything
