### ISSUE TITLE
Can't edit stored passwords in a sandboxed Chrome or Brave browser

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#3986]
### Describe what you noticed and did

1. Install Chrome Portable (https://portableapps.com/apps/internet/google_chrome_portable)
or Brave (https://github.com/brave/brave-browser/releases/download/v1.66.118/BraveBrowserStandaloneSetup.exe)
into a Sandbox
2. Store the password for a website
3. Go to Settings -> Password Manager
4. Try to edit or delete a stored password by clicking on an entry in the list
![can't edit or delete passwords in sandboxed chrome](https://github.com/sandboxie-plus/Sandboxie/assets/12411527/cead2636-1378-49bb-981d-7d42b0e4bdbe)
-> You are notified that `CredentialUIBroker.exe` has crashed.
Chrome still keeps running, but stored passwords cannot be edited or deleted.

### How often did you encounter it so far?

Every time

### Expected behavior

It should be possible to edit passwords in Chrome or Brave

### Affected program

Chrome 125, Brave 1.66, possible all Chrome-based browsers

### Download link

https://portableapps.com/apps/internet/google_chrome_portable

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus x64 1.13.7

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 22H2 64bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Defender

### Sandboxie.ini configuration

```ini
#
# Sandboxie configuration file
#

[GlobalSettings]
NetworkEnableWFP=y
FileRootPath=D:\Sandbox\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=OfficeLicensing
TemplateReject=Edge_Fix
TemplateReject=WindowsLive
TemplateReject=AdobeAcrobatReader
TemplateReject=7zipShellEx
DefaultBox=NoWeb
UsbSandbox=USB_Box

[UserSettings_0C980217]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y

[Brave]
Enabled=y
BlockNetworkFiles=y
BorderColor=#00ffff,ttl,6
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10
BoxNameTitle=n
ClosePrintSpooler=y
CopyLimitKb=81920
AllowNetworkAccess=<BlockNetAccess>,n
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
DropAdminRights=y
FakeAdminRights=y

[Template_Local_SharedTemplate]
Tmpl.Title=Shared Template
Tmpl.Class=Local
#DisableWizardSettings=n
#RemoveDefaultAll=n
#RemoveDefaultRecovers=n
#RemoveDefaultTemplates=n
Tmpl.Comment=Add your settings after this line.
```

**Comment by offhub** [comment]
Try without `FakeAdminRights=y`.

**Comment by NewKidOnTheBlock** [comment]
That did it.
The passwords seem to require some kind of Windows login.
