### ISSUE TITLE
chrome.exe: SBIE2181 LowLevel.dll detour failed to load SbieDll.dll into target process.

### ISSUE THREAD

**Issue by Tushar49** [sandboxie-plus/Sandboxie#3990]
### Describe what you noticed and did

I am trying to launch my chrome.exe from sandbox, directly as well as through an application. But I get following error:
chrome.exe: SBIE2181 LowLevel.dll detour failed to load SbieDll.dll into target process.
---------------------------
chrome.exe - DLL Initialization Failed
---------------------------
Initialization of the dynamic link library D:\Programs\Sandboxie-Plus\SbieDll.dll failed. The process is terminating abnormally. 
---------------------------
OK   
---------------------------

### How often did you encounter it so far?

Always

### Expected behavior

Chrome should open up 

### Affected program

Google Chrome, MS Edge

### Download link

Not Relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did, but I don't know how to attach the .dmp file(s).

### What version of Sandboxie are you running now?

Sandboxie Plus v1.13.7

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 Pro

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

None

### Sandboxie.ini configuration

```ini
#
# Sandboxie configuration file
#

[GlobalSettings]
FileRootPath=D:\Programs\Sandbox\%SANDBOX%
Template=7zipShellEx
Template=Edge_Fix
Template=NortonInternetSecurity
Template=OfficeClickToRun
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_146C0271]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:DefaultBox,AirExplorer

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10

[AirExplorer]
Enabled=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
ClosePrintSpooler=y
RunCommand=AirExplorer.exe|"%BoxRoot%\drive\D\Programs\AirExplorer\AirExplorerCracked\AirExplorer.exe"

[Template_Local_SharedTemplate]
Tmpl.Title=Shared Template
Tmpl.Class=Local
#DisableWizardSettings=n
#RemoveDefaultAll=n
#RemoveDefaultRecovers=n
#RemoveDefaultTemplates=n
Tmpl.Comment=Add your settings after this line.
FuncSkipHook=NtOpenSymbolicLinkObject
```

**Comment by offhub** [comment]
Duplicate of #3050

`Sandboxie-Plus` > `Help` > `Troubleshooting Wizard` > `Fix issues with sandboxing` > `Issues with a web browser` > Next > `Another issue` > Next > `SBIE2181: Failed to load SbieDll.dll` > Next

**Comment by DavidXanatos** [comment]
I'll close that for now as a likely cause and solution are already linked, if the issue persists please let us know

**Comment by isaak654** [comment]
> Do mitigations reduce security?

This is not a mitigation, but a permission fix needed on non-default Sandboxie Plus installation paths: https://github.com/sandboxie-plus/Sandboxie/issues/3050#issuecomment-1665701740
At this time, there is no known way to prevent it.

**Comment by isaak654** [comment]
> Do mitigations reduce security?

Not this one, this is a permissions fix needed on non-default Sandboxie Plus installation paths: https://github.com/sandboxie-plus/Sandboxie/issues/3050#issuecomment-1665701740
Currently there is no known way to prevent the issue on non-default paths.
