### ISSUE TITLE
I can't run Plants VS zombies in the sandboxie

### ISSUE THREAD

**Issue by Smarita-New** [sandboxie-plus/Sandboxie#3992]
### Describe what you noticed and did

I just trying to run Plants VS zombies in the sandboxie,but this game can't run in the sandboxie

### Expected behavior

It's displayed a error message: Resource file not found: properties\resources.xml
![图片](https://github.com/sandboxie-plus/Sandboxie/assets/140679579/e6036722-4bc1-4c6d-9072-da22aefecea5)

### Affected program

Plants vs. Zombies 1.0.0.1051

### Download link

https://pvz.lanzoux.com/iau42bc

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxies Plus 1.13.7

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 24H2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Microsoft Denfender Antivirus

**Comment by Smarita-New** [comment]
Although the displayed Resource file not found: properties\resources.xml,but this file it is exist

**Comment by isaak654** [comment]
It's unclear whether you closed this issue by mistake or whether you solved it yourself.

**Comment by DavidXanatos** [comment]
I just tested the game and when run from its instalation directory it works just fine the shown error comes only when its run from a diferent directory, and I assume that woudl be tha case also when unsandboxed, so i think this was closed on purpose
