### ISSUE TITLE
Cheat Engine admin screen is stuck with UAC disabled

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#4005]
> _Originally posted by @NixonSchool_
>
> I can't make that long report that's too much. Fix the latest 20mb version x64-v1.13.7 - its not getting admin, yet I don't have UAC on win10. Its stuck at admin screen. 
![image](https://github.com/sandboxie-plus/Sandboxie/assets/139177099/690e6490-fa74-4ba9-84b6-5001613fb923)

**Comment by DavidXanatos** [comment]
CheatEngine75.exe rons on my test system with a recent build just fine with and without the UAC being enabled.
With no UAC the pop up pops up for a second and then goes away.
It was eider a problem with an old build or soemthign is broken in your particualr windows instalaltion.
