### ISSUE TITLE
SBIE 9234 error -1073741670

### ISSUE THREAD

**Issue by Jark5455** [sandboxie-plus/Sandboxie#4015]
### Describe what you noticed and did

1. Install Sandboxie-Plus 1.13.7
2. Receive "Failed to connect to driver" error.

### How often did you encounter it so far?

Every time I open Sandboxie Plus

### Expected behavior

Sandboxie Plus should be able to successfully connect to the driver

### Affected program

All Programs

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.13.7 64-Bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 11 Home 23H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Defender

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```ini
[GlobalSettings]
EnableWin32kHooks=n
```

**Comment by Jark5455** [comment]
Any update?

**Comment by offhub** [comment]
A security application or setting may be preventing the driver from loading.

1. Ensure you are using the official installer.
2. Verify that the service and drivers are running.

Please share the output of the following command with us.
```
cmd /k "sc query SbieSvc & sc query SbieDrv"
```

<details>
  <summary>Example output</summary>
  
  ```txt
SERVICE_NAME: SbieSvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

SERVICE_NAME: SbieDrv
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
  ```
  
</details>

**Comment by Jark5455** [comment]
The output I am getting is 

```
SERVICE_NAME: SbieSvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

SERVICE_NAME: SbieDrv
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

I am not aware of any security software I have installed that could be interfering with the driver. The only thing I could maybe think of is maybe a video game anticheat? I have both FaceIT and Valorant installed on this machine.

**Comment by offhub** [comment]
It's possible that anticheat software like `FaceIT` and `Riot Vanguard` could be causing issues with driver loading. To troubleshoot this, you could try uninstalling these anticheat programs one by one and then testing if the driver loads properly without them. This process will help identify if they are indeed the cause of the loading issue. Remember to reinstall any software you remove once you've determined the root of the problem.

**Comment by Jark5455** [comment]
I uninstalled both of those and it still is not working. Is there any more system details I can provide?
