### ISSUE TITLE
Registry key blocking not working

### ISSUE THREAD

**Issue by Lostion1** [sandboxie-plus/Sandboxie#4021]
### Describe what you noticed and did

So iam using FTPRush v1.1.3 (not v2 and v3, but v2 has the same problem), the problem is Windows 11 breaks the .rar function of the program if you want to upload a .rar to your FTP Server it simply shows empty folders instead of .rars

The solution is to block access to this registry key: HKEY_CLASSES_ROOT\SystemFileAssociations\.rar\CLSID

Well i tried to block the key in the normal sandbox but it isn't working at all? Function is still broken and when iam tracking the registry accesses with "Process Monitor" it shows that FTPRush still can access the key.

I run Sandboxie in the portable version.

### How often did you encounter it so far?

Everytime i started FTPRush in the sandbox

### Expected behavior

Should block the registry key.

### Affected program

FTPRush v1.1.3

### Download link

https://www.wftpserver.com/de/ftprush_v2.htm

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus-x64-v1.13.7

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

Only tested the latest version.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 Pro 23H2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Only Windows Defender

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```ini
[GlobalSettings]
FileRootPath=C:\Users\USERNAME\Downloads\Sandbox\%SANDBOX%
IpcTrace=ad
PipeTrace=ad
GuiTrace=ad

[UserSettings_02AC00E3]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
ClosedKeyPath=ftprush.exe,HKEY_CLASSES_ROOT\SystemFileAssociations\.rar\CLSID
```

**Comment by offhub** [comment]
Do any of these work?

```ini
ClosedKeyPath=ftprush.exe,*\SystemFileAssociations\.rar\CLSID\*
```

OR

```ini
ClosedKeyPath=ftprush.exe,HKEY_LOCAL_MACHINE\SOFTWARE\Classes\SystemFileAssociations\.rar\CLSID\*
```

**Comment by Lostion1** [comment]
Wow both actually are working. That is interesting! Thank you very much!
