### ISSUE TITLE
Could the cheapest Patreon supporter certificate enjoy the advanced features?

### ISSUE THREAD

**Issue by ccchan234** [sandboxie-plus/Sandboxie#4025]
### Is your feature request related to a problem or use case?

i hope this is the authenic link: https://www.patreon.com/DavidXanatos

this is the cheapest level at the moment:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/37549409/6f0fea27-22da-40cd-be93-05dce653760e)

i browsed thru all the patroen sponsor levels, and all use the word "use premium software features".
but i would like to TRY the advanced functions like socks5 proxy.

so i would like to ask for a clarification, whether the cheapest patreon could result in using of the advanced features.

if it's requiring just HKD25 per month which is like 3 USD / month, many people could afford it, thinking of it like a subscription of 3 USD/mo.

thank you.

### Describe the solution you'd like

i know the terms changed from small/medium/large to now general/advanced?

### Describe alternatives you've considered

a table, thanks

**Comment by ccchan234** [comment]
you know, the terms are somehow troublesome.
the link to buy an advanced cert ONLY mentioned encryption.
https://xanasoft.com/product/sandboxie-plus-advanced-upgrade/#google_vignette

**Comment by ccchan234** [comment]
ps: after some digestion of the materials, this is what i guess:

1. i'll have to pay ~USD3/mo to obtain a general support cert
AND
2. i'll have to buy a 25.00 (euro) advanced cert to use the advanced features.

the 2nd item wont function without the 1st, so it's now a 25 euro (for lifetime) with a USD3/mo subscription service.

is that?

thank you.

**Comment by DavidXanatos** [comment]
3€ and up levels give you a certificate where you can use the basic features and the box encryption,
to use proxy injection you need the 10€ and up tier that gives you also access to not public insider builds.

The advanced encryption pack used to give you only encryption on top of an existing certificate with 1.14.0 that added public proxy support it will unlock also the proxy features, previously these were only available on the aforementioned patreon tiers. I'll update that when 1.14.x gets out of being a preview.

If you are not getting a patreon subscription to use all features available in the public build you need a basic certificate Home or Personal and to that the Advanced Upgrade.

You can not combine a patreon certificate with a store bought one.

**Comment by ccchan234** [comment]
10 euro per month is not easily tolerated...... thanks

**Comment by love-code-yeyixiao** [comment]
> 10 euro per month is not easily tolerated...... thanks

You can earn a certificate by contributing to an open source repository. Even an individual premium certificate is sufficient.

**Comment by ccchan234** [comment]
> > 10 euro per month is not easily tolerated...... thanks
> 
> You can earn a certificate by contributing to this open source repository or docs repository. Even an personal advance certificate is sufficient.This won't spend you any money....only time.

i could help,
can you help by assigning some task to me that guarantee an advanced cert?

i dont mind spending sometime for that, but if after spending some time for that and results in no cert, that's ridiculously stupid. thank you.

**Comment by ccchan234** [comment]
> 3€ and up levels give you a certificate where you can use the basic features and the box encryption, to use proxy injection you need the 10€ and up tier that gives you also access to not public insider builds.
> 
> The advanced encryption pack used to give you only encryption on top of an existing certificate with 1.14.0 that added public proxy support it will unlock also the proxy features, previously these were only available on the aforementioned patreon tiers. I'll update that when 1.14.x gets out of being a preview.
> 
> If you are not getting a patreon subscription to use all features available in the public build you need a basic certificate Home or Personal and to that the Advanced Upgrade.
> 
> You can not combine a patreon certificate with a store bought one.
pls let me clarify again, it could be due to culture differences that we count things differently.


i currently do have a basic supporter cert,
do you mean the 25 euro advanced ENCRYPTION pack is going to be renamed advanced pack so I could apply it onto a basic supporter cert?

or, if at worst, my basic supporter cert is not uptodate/expired,
the cheapest way for me to use the proxy feacture is:
it is USD3/mo pateron suport
with a one time 25euro for life time (and this adv pack will not function without the basic supporter cert, however also mean it functions as long as i got a working basic supporter cert)?

thank you.


btw, it's really hard, at least for me, to undersand a value with a ",".
(i know it's the europe way)
omitting it completely may help?
i.e. 25 euro instead of 25,00 euro.

thanks

**Comment by love-code-yeyixiao** [comment]
> ok i saw that cant combine pateron cert /w shop one thx

在欧洲，他们通常用","代替"."所以说 ”25,00 EUR“ equals to  ”25.00欧元“。

**Comment by love-code-yeyixiao** [comment]
> > > 10 euro per month is not easily tolerated...... thanks
> > 
> > 
> > You can earn a certificate by contributing to this open source repository or docs repository. Even an personal advance certificate is sufficient.This won't spend you any money....only time.
> 
> i could help, can you help by assigning some task to me that guarantee an advanced cert?
> 
> i dont mind spending sometime for that, but if after spending some time for that and results in no cert, that's ridiculously stupid. thank you.

比如说，你可以为文档仓库（sandboxie-docs）添加一些新功能的文档文件（但我们的维护者已经N个月没有管理那里啦！所以说除非你发邮件给他要求，他应该不会主动给你）
For example,you can add some files about new features for sandboxie-docs.

**Comment by ccchan234** [comment]
> > > > 10 euro per month is not easily tolerated...... thanks
> > > 
> > > 
> > > You can earn a certificate by contributing to this open source repository or docs repository. Even an personal advance certificate is sufficient.This won't spend you any money....only time.
> > 
> > 
> > i could help, can you help by assigning some task to me that guarantee an advanced cert?
> > i dont mind spending sometime for that, but if after spending some time for that and results in no cert, that's ridiculously stupid. thank you.
> 
> 比如说，你可以为文档仓库（sandboxie-docs）添加一些新功能的文档文件（但我们的维护者已经N个月没有管理那里啦！所以说除非你发邮件给他要求，他应该不会主动给你） For example,you can add some files about new features for sandboxie-docs.

====================

i do want to help,
but i never tried before.

actually if you could make list, i could help sometimes -- even without reward.
i have used sandboxie since 1x years ago, and bought a lifetime license? (forgot the terms)

btw, i agree that the documentation is not up to date.

when i search for sandboxie portable,
it contain an old document BEFORE open source era,
and then a empty page.

what i know is that now sandboxie plus could be used as portable.

**Comment by ccchan234** [comment]
> 3€ and up levels give you a certificate where you can use the basic features and the box encryption, to use proxy injection you need the 10€ and up tier that gives you also access to not public insider builds.
> 
> The advanced encryption pack used to give you only encryption on top of an existing certificate with 1.14.0 that added public proxy support it will unlock also the proxy features, previously these were only available on the aforementioned patreon tiers. I'll update that when 1.14.x gets out of being a preview.
> 
> If you are not getting a patreon subscription to use all features available in the public build you need a basic certificate Home or Personal and to that the Advanced Upgrade.
> 
> You can not combine a patreon certificate with a store bought one.

~btw, i dont see a 10euro option in pateron.
the closet one is USD10.
is this what you mean?
USD10 is OK, there is a 20%~

wow, ok, i just know that 1 USD is 1 euro at this moment.

![image](https://github.com/sandboxie-plus/Sandboxie/assets/37549409/2a917367-1cfc-4af8-b4be-f2e85d8664e4)

10USD/mo is ok. i'll sponsor on patron when necessary, thank you.
