### ISSUE TITLE
Can sandboxie-plus work alike air gap? thx

### ISSUE THREAD

**Issue by ccchan234** [sandboxie-plus/Sandboxie#4026]
### Is your feature request related to a problem or use case?

i dont trust governments, neither microsoft. i could trust open source solutions.

the most safe way for me (except targeted by CIA or KGB), would be to use a air gapped win10.

however in this era, it's really almost impossible to stay so,
i am a student, i need online LLMs for help in study, need google for answers to questions.
and may be some photo/charts to help in study.

currently i just put them into a sandboxie-data protected box, and use simplewall as the firewall (i used since long time ago).

would like to hear other setups.

thank you.

### Describe the solution you'd like

the developing socks5 proxy may help in other ways?

or have some control over the network?

### Describe alternatives you've considered

completely plug off the lan cable.

**Comment by love-code-yeyixiao** [comment]
In my mind,I only know air gapped is about disconnecting from Internet.So what solution do you want?

**Comment by ccchan234** [comment]
> In my mind,I only know air gapped is about disconnecting from Internet.So what solution do you want?

could you google "virtual air gap" on your own?
thank you

**Comment by love-code-yeyixiao** [comment]
> virtual air gap

In my search results, the principle of this technique is only disconnection.So you also could do it by Unpluging the network cable.
You didn't say what you want,disconnecting in global or only for sandboxed processes?

**Comment by love-code-yeyixiao** [comment]
> virtual air gap

In my search results, the principle of this technique is only disconnection.So you also could do it by Unpluging the network cable.
You didn't say what you want,disconnecting in global or only for sandboxed processes?

**Comment by ccchan234** [comment]
> > virtual air gap
> 
> In my search results, the principle of this technique is only disconnection.So you also could do it by Unpluging the network cable. You didn't say what you want,disconnecting in global or only for sandboxed processes?

unplug LAN cable is too tough for people,
so some solutions are there for an online system, somehow make it harder for spyware to send back user data.

the spyware need data + internet access for it's work.

so in your online system, if you remove one from the spyware, then it works alike air gap i.e. "virtual air gap".

currently the sandboxie-plus /w box-data protection works alike.

SBP also have build in firewall (however since i used to use simplewall so i keep on using simplewall).

i am just asking if there will be more sophisticated functions, because those commercial solutions may provide more.

some commercial ones are like:
Ericom Software
https://www.ericom.com › Glossary
·
[翻譯這個網頁](https://translate.google.com/translate?hl=zh-TW&sl=en&u=https://www.ericom.com/glossary/what-are-virtual-air-gaps/&prev=search&pto=aue)
Virtual Air Gaps:Employs virtualization to isolate systems within the same physical hardware. Though connected, these virtual instances are shielded from each ..

SBP is container i think.

**Comment by ccchan234** [comment]
i am thinking if the proxy function could help in some way.
i cant test it so i dont have any idea how it works in SBP yet.
let's see. thanks

**Comment by love-code-yeyixiao** [comment]
What I can be sure of is that the proxy doesn't help with this.
Have you tried Encryption Box?

**Comment by ccchan234** [comment]
> What I can be sure of is that the proxy doesn't help with this. Have you tried Encryption Box?

i think the proxy could help:

![image](https://github.com/sandboxie-plus/Sandboxie/assets/37549409/a06fbe4f-d418-4d3b-9fed-1409432a0af3)


suppose under an openwrt router, which is FOSS and trustable, 
there is a linux socks5 proxy server (trustable).
the win10 IP 192.168.8.3 is blocked for internet in openwrt, but allowed in local LAN.

so programs in the win10 itself, they will try access internet thru 192.168.8.1, and will be blocked.

however, if with the sandboxie adv cert,
which i dont have now.
i'll believe it ask for a socks5 proxy server, username and passwd,
and the programs inside the sandboxie could route thru IP .8.3, into .8.2 and then go internet.

depend on how well sandboxie protected the socks5's username and passwd,
if a spyware on the win10 host /w admin right still COULD not obtain the proxy username and passwd,
then the system is practically air gapped (for the host win10) but still allow web browsing.

true LAN cable unplug with no internet access is too tough for today's life,
so fake air gap systems, that allow web browsing, but with some mechanism to prevent spyware sending data back,
is one way.

indeep one could have 1 PC that is completely unplugged, and one that allow web browsing in this way.

**Comment by ccchan234** [comment]
this is another setup i am thinking. problem for the win10 host is that 
1. it may want M$ update, 
2. wechat voice chat + recorder may need direct access and cant go under sandboxie.
3. i use google drive client to upload/dnld huge files e.g. 750GB/day

![image](https://github.com/sandboxie-plus/Sandboxie/assets/37549409/8ad194d9-20f6-47c5-a560-3a8d64c79e27)


SBP and/or the containers could be put onto ext USB,
all with box-DP.
the lowest thus dont have access to data and could be used for danger software.
the middle one is with internet access removed, could be used for e..g notepad
the top one used only for trustable software, as they have both internet and access to your data.


then only problem as above mentioned is how to due with the win10 system on drive C.

i could use shadow defender for that but it would be troublesome.

**Comment by ccchan234** [comment]
it seems one may only need one single openwrt router, but the setup is not fully safe yet.

router .....    win10 + SBP

the router could block the win10 host,
yet the router would have a socks5 proxy server e.g. i used sockd aka dante, requiring username + passwd.


one can setup a sandbox with the above info, such that the win10 host 's process are air gapped,
but the programs inside the sandbox can route thru sockd and get on internet.

the only problem is that i haven't have time/chance to install the adv cert version, but from this github i already knew that the proxy IP, username and password are typed into the sandbox's config by the user thru the win10 host's GUI. also, unless otherwise, the packets sent by the programs inside the sandbox will contain the proxy server IP, username and password AS PLAIN TEXT. so unless something like TLS is setup, this config is far from a working "virtual air gap" but quite close.

i myself trust no body so i dislike close source windows very very much.
i would like to use it safely. thanks

**Comment by ccchan234** [comment]
hi, after some time, i discussed with some ppl again, this works some sort alike zero trust security.

anyway. 

currently there are 2 schemes to implement it, i have tested part of it and have not truely implemented.

the "easier" method is to have 3 openwrt subrouters, the harder one is to make 1 openwrt subrouters perform the work of such 3 subrouters.

i'l post next.

**Comment by ccchan234** [comment]
Here's a summary of the document:

# Zero Trust Network Setup Guide

This is a technical guide that describes how to set up a sophisticated home network with enhanced security and flexible routing options. The key features include:

## Main Features
1. **Enhanced Security** - Uses a "zero trust" approach where devices are blocked by default and must use specific encrypted channels to access the internet
2. **Flexible Routing** - Allows different programs to use different internet paths (local ISP, various VPNs, or proxies)
3. **Centralized Control** - All traffic management happens at a central router running OpenWRT
4. **Device Segregation** - Different rules for different devices:
   - Windows PC: Strict control with encrypted tunneling
   - Tablet: More relaxed rules with transparent proxy

## Technical Implementation
- Uses OpenWRT router as the main control point
- Implements SSL/STunnel for encryption
- Combines multiple technologies (SOCKS5 proxy, VPNs, transparent proxy)
- Includes detailed firewall rules and network architecture

This would be useful for network administrators or tech enthusiasts interested in setting up a secure home network with advanced routing capabilities. It's particularly relevant for those interested in privacy, security, and having fine-grained control over their internet traffic.



# Zero Trust Network Setup with Multiple Routing Paths

## Network Architecture
```plaintext
Internet
    ↑
Main Router (192.168.0.1)
├─→ BLOCKS Win10's IP (192.168.1.100)
└─→ Allows Sub Router
    ↑
Sub Router (192.168.1.1) - OpenWRT
├─→ FIREWALL RULES:
│   ├─→ For Win10 (192.168.1.100):
│   │   ├─→ BLOCK all direct traffic
│   │   ├─→ BLOCK DNS requests
│   │   ├─→ BLOCK gateway functionality
│   │   └─→ ALLOW only SSL/STunnel :8443
│   │
│   └─→ For Tablet (192.168.1.101):
│       ├─→ ALLOW gateway usage
│       ├─→ ALLOW DNS
│       └─→ Redirect traffic to transparent proxy
│
├─→ LISTENING: SSL/STunnel Server :8443
│   └─→ Decrypts traffic and forwards to Dante
│
├─→ LISTENING: Dante SOCKS5 :1080 (requires username/password)
│   ├─→ user_local → Direct to Local ISP
│   ├─→ user_proxy1 → HomeProxy → Country1
│   ├─→ user_proxy2 → HomeProxy → Country2
│   ├─→ user_vpn1 → NordVPN → VPN Country1
│   └─→ user_vpn2 → ExpressVPN → VPN Country2
│
├─→ LISTENING: HomeProxy/sing-box :1081 (1 instance)
│   └─→ Manages multiple proxy outbounds in single config
│
└─→ VPN Clients (multiple instances)
    ├─→ NordVPN (tun0)
    └─→ ExpressVPN (tun1)
    ↑
SSL/STunnel encrypted connection
    ↑
Win10 PC (192.168.1.100)
├─→ LISTENING: SSL/STunnel Client localhost:8443
└─→ Proxifier Rules:
    ├─→ Program1 → localhost:8443 (user_local/pwd) → Local ISP
    ├─→ Program2 → localhost:8443 (user_proxy1/pwd) → Country1
    ├─→ Program3 → localhost:8443 (user_proxy2/pwd) → Country2
    ├─→ Program4 → localhost:8443 (user_vpn1/pwd) → VPN1
    └─→ Program5 → localhost:8443 (user_vpn2/pwd) → VPN2
```

## OpenWRT Firewall Rules
```bash
# Block Win10 from forwarding traffic (acting as gateway)
iptables -I FORWARD -s 192.168.1.100 -j DROP

# Block Win10's DNS requests (UDP and TCP)
iptables -I INPUT -s 192.168.1.100 -p udp --dport 53 -j DROP
iptables -I INPUT -s 192.168.1.100 -p tcp --dport 53 -j DROP

# Allow Win10's SSL/STunnel connection only
iptables -I INPUT -s 192.168.1.100 -p tcp --dport 8443 -j ACCEPT

# Block all other Win10 input
iptables -I INPUT -s 192.168.1.100 -j DROP

# Tablet transparent proxy (HTTP and HTTPS)
iptables -t nat -A PREROUTING -s 192.168.1.101 -p tcp --dport 80 -j REDIRECT --to-port 3128
iptables -t nat -A PREROUTING -s 192.168.1.101 -p tcp --dport 443 -j REDIRECT --to-port 3128
```

## Key Components

1. **Main Router**
   - Implements initial zero-trust by blocking Win10
   - Only allows communication with sub router

2. **Sub Router (OpenWRT)**
   - SSL/STunnel (1 instance)
   - Dante SOCKS5 (1 instance, multiple users)
   - HomeProxy (1 instance, multiple outbounds)
   - VPN clients (multiple instances)
   - Firewall rules for both Win10 and Tablet

3. **Win10 PC**
   - SSL/STunnel client
   - Proxifier for program-specific routing
   - Can only connect through SSL/STunnel

4. **Tablet**
   - Uses transparent proxy
   - No restrictions except traffic redirection

## Security Features

1. **Zero Trust**
   - Main router blocks Win10 completely
   - Sub router enforces strict access control

2. **Encrypted Tunnel**
   - SSL/STunnel protects all credentials and traffic
   - Prevents credential sniffing

3. **Authentication**
   - All Win10 access requires Dante username/password
   - Different credentials for different routing paths

4. **Centralized Control**
   - All routing decisions made at sub router
   - Single point of control and logging

5. **Flexible Routing**
   - Programs can use different IPs based on needs
   - Supports local ISP, multiple proxies, and VPNs

## Traffic Flow

1. Win10 Program wants internet access:
   - Proxifier sends to local SSL/STunnel with specific credentials
   - SSL/STunnel encrypts and sends to sub router
   - Sub router decrypts and passes to Dante
   - Dante checks credentials and routes accordingly

2. Tablet wants internet access:
   - Traffic automatically redirected to transparent proxy
   - No user configuration needed
   - Works with all apps

**Comment by ccchan234** [comment]
if a program can run inside sandboxie, of course i'll run it inside sandboxie with proxy.

if cant, then use proxifier alone.

**Comment by ccchan234** [comment]
This appears to be a detailed network configuration guide for a "3-Router Single LAN" setup. Here's a summary:

# OpenWRT 3-Router Single LAN Setup Guide

## Overview
A technical guide for setting up three sub-routers on a single LAN, where each router provides a different internet path:
1. **SubRouter1**: Direct ISP connection
2. **SubRouter2**: Proxy-based routing
3. **SubRouter3**: VPN-based routing

## Key Features
- Centralized management through a main router (192.168.1.1)
- Enhanced security for Windows 10 machine with restricted access
- Each path uses encrypted tunneling (STunnel) and authenticated SOCKS5 (Dante)
- Flexible routing options for other devices (phones, tablets, etc.)

## Technical Details
- Complete configuration files for OpenWRT
- Firewall rules for security
- STunnel and Dante proxy configurations
- HomeProxy/sing-box setup for proxy routing
- OpenVPN configuration for VPN routing

This would be useful for network administrators or tech enthusiasts who want to:
- Set up multiple internet paths in their network
- Implement strict access controls for specific devices
- Maintain a single LAN while having multiple routing options

The guide is particularly relevant for those interested in network security and traffic management while keeping the network architecture relatively simple.






Here's the detailed configuration for the single-LAN setup:

````markdown:z0/z/zero-trust-scheme/3routers-single-lan.md
# OpenWRT 3-Router Configuration (Single LAN)

## Network Layout
```plaintext
Internet
    ↑
Main Router (192.168.1.1)
├─→ DHCP: 192.168.1.100-200
├─→ BLOCKS Win10 (192.168.1.5) from internet
└─→ Routes to Sub Routers:
    │
    ├─→ SubRouter1 (192.168.1.2)
    │   ├─→ STunnel :8443 → Dante :1080
    │   ├─→ Dante (user1/pwd1)
    │   └─→ OUTPUT: Direct ISP
    │
    ├─→ SubRouter2 (192.168.1.3)
    │   ├─→ STunnel :8443 → Dante :1080
    │   ├─→ Dante (user2/pwd2)
    │   ├─→ HomeProxy/sing-box :1081
    │   └─→ OUTPUT: Via Proxy
    │
    └─→ SubRouter3 (192.168.1.4)
        ├─→ STunnel :8443 → Dante :1080
        ├─→ Dante (user3/pwd3)
        └─→ OUTPUT: Via VPN
```

## Main Router Configuration

### Network Settings
```bash
# /etc/config/network
config interface 'lan'
    option type 'bridge'
    option ifname 'eth0'
    option proto 'static'
    option ipaddr '192.168.1.1'
    option netmask '255.255.255.0'
```

### DHCP Settings
```bash
# /etc/config/dhcp
config dhcp 'lan'
    option interface 'lan'
    option start '100'
    option limit '100'
    option leasetime '12h'
```

### Firewall Rules
```bash
# Block Win10 internet access
iptables -I FORWARD -s 192.168.1.5 -j DROP

# Allow Win10 to reach only sub routers
iptables -I FORWARD -s 192.168.1.5 -d 192.168.1.2/32 -j ACCEPT
iptables -I FORWARD -s 192.168.1.5 -d 192.168.1.3/32 -j ACCEPT
iptables -I FORWARD -s 192.168.1.5 -d 192.168.1.4/32 -j ACCEPT
```

## Common Sub-Router Configurations

### Network Settings (for each router)
```bash
# /etc/config/network
config interface 'lan'
    option type 'bridge'
    option ifname 'eth0'
    option proto 'static'
    option ipaddr '192.168.1.X'  # 2, 3, or 4
    option netmask '255.255.255.0'
    option gateway '192.168.1.1'
```

### Base Firewall Rules (for each router)
```bash
WIN10_IP="192.168.1.5"

# Allow Win10 only to STunnel
iptables -I INPUT -s $WIN10_IP -p tcp --dport 8443 -j ACCEPT
iptables -I INPUT -s $WIN10_IP -j DROP

# Block Win10 DNS requests
iptables -I INPUT -s $WIN10_IP -p udp --dport 53 -j DROP
iptables -I INPUT -s $WIN10_IP -p tcp --dport 53 -j DROP
```

### STunnel Config (/etc/stunnel/stunnel.conf)
```ini
[dante-socks]
accept = 8443
connect = 127.0.0.1:1080
cert = /etc/stunnel/stunnel.pem
key = /etc/stunnel/stunnel.pem
verify = 0
```

### Dante Config (/etc/dante.conf)
```plaintext
logoutput: syslog
internal: 127.0.0.1 port = 1080
external: eth0

socksmethod: username none

client pass {
    from: 127.0.0.1/32
    to: 0.0.0.0/0
    log: connect disconnect error
}

socks pass {
    from: 127.0.0.1/32
    to: 0.0.0.0/0
    command: bind connect udpassociate
    log: connect disconnect error
}
```

## SubRouter2 (HomeProxy) Specific

### HomeProxy Config (/etc/homeproxy/config.json)
```json
{
  "inbounds": [
    {
      "type": "socks",
      "tag": "socks-in",
      "listen": "127.0.0.1",
      "listen_port": 1081
    }
  ],
  "outbounds": [
    {
      "type": "vmess",
      "tag": "proxy-out",
      "server": "proxy.example.com",
      "server_port": 443,
      "uuid": "your-uuid",
      "security": "auto"
    }
  ],
  "route": {
    "rules": [
      {
        "outbound": "proxy-out"
      }
    ]
  }
}
```

## SubRouter3 (VPN) Specific

### OpenVPN Config (/etc/openvpn/client.conf)
```conf
client
dev tun
proto udp
remote vpn.example.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert client.crt
key client.key
comp-lzo
verb 3
```

## Win10 Client Setup

### STunnel Configs
```ini
; stunnel1.conf (Direct ISP)
[dante-socks]
client = yes
accept = 127.0.0.1:8443
connect = 192.168.1.2:8443

; stunnel2.conf (HomeProxy)
[dante-socks]
client = yes
accept = 127.0.0.1:8444
connect = 192.168.1.3:8443

; stunnel3.conf (VPN)
[dante-socks]
client = yes
accept = 127.0.0.1:8445
connect = 192.168.1.4:8443
```

### Proxifier Rules
```plaintext
Rule 1: Direct ISP
- Programs: [Program1]
- Target: localhost:8443
- Proxy: SOCKS5 user1/pwd1

Rule 2: Via Proxy
- Programs: [Program2]
- Target: localhost:8444
- Proxy: SOCKS5 user2/pwd2

Rule 3: Via VPN
- Programs: [Program3]
- Target: localhost:8445
- Proxy: SOCKS5 user3/pwd3
```

## Other Devices
- Connect to main router WiFi
- Choose gateway based on needed route:
  - Direct ISP: 192.168.1.2
  - Proxy: 192.168.1.3
  - VPN: 192.168.1.4
````

Key points:
1. Single LAN makes management simpler
2. Each sub-router provides a different route
3. Win10 still restricted to STunnel access
4. Other devices can freely choose their gateway

Would you like me to explain any specific part in more detail?



Let me explain each major component in detail:

1. **Main Router (192.168.1.1)**
- Acts as the central DHCP server and gateway
- Key security features:
```bash
# Blocks Win10 (192.168.1.5) from accessing internet directly
iptables -I FORWARD -s 192.168.1.5 -j DROP

# Only allows Win10 to access the sub-routers
iptables -I FORWARD -s 192.168.1.5 -d 192.168.1.2/32 -j ACCEPT  # To SubRouter1
iptables -I FORWARD -s 192.168.1.5 -d 192.168.1.3/32 -j ACCEPT  # To SubRouter2
iptables -I FORWARD -s 192.168.1.5 -d 192.168.1.4/32 -j ACCEPT  # To SubRouter3
```

2. **Sub-Routers Common Setup**
- Each sub-router needs:
  - STunnel (for encrypted connection from Win10)
  - Dante (for SOCKS5 proxy with authentication)
  - Specific firewall rules to block Win10 direct access

3. **Traffic Flow Examples**:
```plaintext
Win10 → SubRouter1 (Direct ISP):
└─→ Win10 → STunnel(local:8443) → 192.168.1.2:8443 → Dante(user1/pwd1) → Internet

Win10 → SubRouter2 (Proxy):
└─→ Win10 → STunnel(local:8444) → 192.168.1.3:8443 → Dante(user2/pwd2) → HomeProxy → Internet

Win10 → SubRouter3 (VPN):
└─→ Win10 → STunnel(local:8445) → 192.168.1.4:8443 → Dante(user3/pwd3) → VPN → Internet
```

4. **Other Devices (Android/iOS)**:
```plaintext
Example: Android phone wants to use VPN
1. Connect to main router's WiFi
2. Get IP (e.g., 192.168.1.101)
3. Change gateway to 192.168.1.4 (SubRouter3)
4. All traffic automatically routes through VPN
```

Would you like me to dive deeper into any specific aspect? For example:
1. STunnel + Dante setup details
2. HomeProxy configuration
3. VPN routing
4. Win10 Proxifier rules
5. Other device gateway settings

**Comment by ccchan234** [comment]
ps: portable programs are preferred over installed programs e.g. use rclone mount instead of google desktop app for windows.
