### ISSUE TITLE
Proxy exclusion

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#4036]
### Is your feature request related to a problem or use case?

Some browser extensions may need to connect to a local IP address on the host system to function properly.

### Describe the solution you'd like

NetworkUseProxy=*,Address=example.com;Port=1080;Auth=No;**NoProxy=192.168.0.0-192.168.255.255,172.17.160.1**

NetworkUseProxy=*,Address=example.com;Port=1080;Auth=No;**BypassProxy=192.168.0.0-192.168.255.255,172.17.160.1**

**Comment by tdtc-hrb** [comment]
In the 13 series, use IE to set the proxy;
In the 14 series, how to set it?
Using the non-commercial version

**Comment by tdtc-hrb** [comment]
Run -> Run from start menu -> Programs -> Accessories -> Internet Explorer.lnk
