### ISSUE TITLE
why node.js msi setup error then rollback?

### ISSUE THREAD

**Issue by LY1806620741** [sandboxie-plus/Sandboxie#4038]
### Describe what you noticed and did

why node.js msi setup error then rollback?

error:
```shell
The Windows Installer Service could not be accessed. This can occur if you are running Windows in safe mode, or if
the Windows Installer is not correctly installed. Contact your support personnel for assistance.
```

![image](https://github.com/sandboxie-plus/Sandboxie/assets/25952861/4852bacd-7729-4091-a0f0-d54667599f99)

### How often did you encounter it so far?

2

### Expected behavior

setup then normal  use

### Affected program

node-v20.15.0-x64.msi

### Download link

https://nodejs.org/dist/v20.15.0/node-v20.15.0-x64.msi

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus v1.13.7 x64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows11 Pro 23H2 64-bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Microsoft Defender

### Sandboxie.ini configuration

```ini
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=Edge_Fix
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_0305015D]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:DefaultBox,开发环境,play
BoxGrouping=开发环境:develop,New_Box

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10

[Template_Local_SharedTemplate]
Tmpl.Title=共享模板
Tmpl.Class=Local
#DisableWizardSettings=n
#RemoveDefaultAll=n
#RemoveDefaultRecovers=n
#RemoveDefaultTemplates=n
Tmpl.Comment=在此行之后添加您的设置。

[develop]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
FileRootPath=D:\Sandbox\develop
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
OpenPipePath=D:\code
FakeAdminRights=y

[play]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#02f6f6,ttl
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10
FileRootPath=D:\Sandbox\play
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y

[New_Box]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
SeparateUserFolders=n
```

**Comment by offhub** [comment]
You could try with the following setting:
```
MsiInstallerExemptions=y
```

(`Plus UI` > `Sandbox Options` > `Security Hardening` > `Elevation restrictions` >> `Allow MSIServer to run with a sandboxed system token and apply other exceptions if required`)

**Comment by LY1806620741** [comment]
Sorry I've been busy lately, this really works
