### ISSUE TITLE
Use monospace font at Sandbox Options > Edit Ini Section

### ISSUE THREAD

**Issue by starscaledragon** [sandboxie-plus/Sandboxie#4041]
### Is your feature request related to a problem or use case?

When editing the configuration at "Edit Ini Section", the text editor uses variable space font which makes text editing awkward. 

### Describe the solution you'd like

Use a monospaced inside the text editor under "Edit Ini Section", probably Consolas or whatever the system provides.

**Comment by offhub** [comment]
> Sandboxie Plus > Options > Global Settings > Interface Config > Interface Options > Ini Options > à

**Comment by starscaledragon** [comment]
Thanks a lot, this is exactly what I needed.
