### ISSUE TITLE
password?

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#4053]

**Comment by love-code-yeyixiao** [comment]
In fact, I don't know if you've ever tried it, but when running an application that requires a UAC licence under a standard account, Windows asks you for the password to the administrator account.
BTW, I don't really understand what you want exactly, I have two interpretations of this.
One: You want us to implement a password in Sandboxie itself that is specific to each sandbox, and that you need to enter the password before running a programme in it.
Two: You want us to not just call the built-in UAC interface when a program requests UAC, but at the same time have us ask for the account password again.

Translated with DeepL.com (free version)

**Comment by love-code-yeyixiao** [comment]
After quarters of finding,I found two funcations which maybe are helpful for this.

1. CredUICmdLinePromptForCredentialsA
[MSDN](https://learn.microsoft.com/zh-cn/windows/win32/api/wincred/nf-wincred-creduicmdlinepromptforcredentialsa)
2. CredUIConfirmCredentialsA
[MSDN](https://learn.microsoft.com/zh-cn/windows/win32/api/wincred/nf-wincred-creduiconfirmcredentialsa)

**Comment by love-code-yeyixiao** [comment]
CREDUIWIN_SECURE_PROMPT
CREDUIWIN_ENUMERATE_ADMINS
These two flags will be very useful.

**Comment by love-code-yeyixiao** [comment]
The demo succeed.
[TestCerd.zip](https://github.com/user-attachments/files/16114745/TestCerd.zip)
   ```
 PCREDUI_INFOW info = new CREDUI_INFOW();
    ULONG nLen = 0;
    LPVOID* blob = (LPVOID*)malloc(1000);
    HANDLE connectHandle = NULL;
    LSA_STRING* str = (PLSA_STRING)malloc(sizeof(LSA_STRING));
    BOOL saved = false;
    char* qwq = const_cast<char*>(MSV1_0_PACKAGE_NAME);
    info->cbSize = sizeof(CREDUI_INFO);
    info->hbmBanner = NULL;
    info->hwndParent = NULL;
    info->pszCaptionText = L"UAC-Review";
    info->pszMessageText = L"To test";
    
    memset(blob, 0, 1000);
    memset(str, 0, sizeof(LSA_STRING));

    str->Buffer = qwq;
    str->Length = strlen(MSV1_0_PACKAGE_NAME) + 1;
    str->MaximumLength = strlen(MSV1_0_PACKAGE_NAME) + 1;


    LPWSTR username = (WCHAR*)malloc(100), password = (WCHAR*)malloc(100), appName = const_cast<WCHAR*>(L"TestCerd.exe");
    memset(username, 0, 100);
    memset(password, 0, 100);
    if (CredUIPromptForCredentialsW(info, appName, NULL, 0, username, 100, password, 100, &saved, CREDUI_FLAGS_COMPLETE_USERNAME | CREDUI_FLAGS_EXPECT_CONFIRMATION | CREDUI_FLAGS_REQUEST_ADMINISTRATOR | CREDUI_FLAGS_USERNAME_TARGET_CREDENTIALS | CREDUI_FLAGS_VALIDATE_USERNAME | CREDUI_FLAGS_DO_NOT_PERSIST| CREDUI_FLAGS_INCORRECT_PASSWORD| CREDUI_FLAGS_PASSWORD_ONLY_OK) == NO_ERROR) {
        LPWSTR user = (WCHAR*)malloc(100),domain = (WCHAR*)malloc(100);
        memset(user, 0, 100);
        memset(domain, 0, 100);
        CredUIParseUserNameW(username, user, 100, domain, 100);
        HANDLE tempToken = NULL;
        if(LogonUser(user, domain, password, LOGON32_LOGON_BATCH, LOGON32_PROVIDER_DEFAULT, &tempToken))
            MessageBox(NULL, L"Successful Really", L"Tips", MB_OK);
        else
            MessageBox(NULL, L"Login Failed", L"Tips", MB_OK);
        CloseHandle(tempToken);
        free(user);
        free(domain);
    }

clean:
    SecureZeroMemory(password, sizeof(password));
    free(str);
    free(username);
    free(password);
    LsaDeregisterLogonProcess(connectHandle);
```
It can work normally in a standrad sandbox.

**Comment by DavidXanatos** [comment]
Not sure what you are requesting are you looking for encrypted sandboxes: https://sandboxie-plus.com/boxencryption/
