### ISSUE TITLE
Firefox crash when I use Sandboxie-Plus.

### ISSUE THREAD

**Issue by pbtdej35692hotmail** [sandboxie-plus/Sandboxie#4055]
### Describe what you noticed and did

1.start firefox.exe in sandbox.
2.firefox.exe crashed.
-When I use Virtualization scheme version 2.
Firefox window didn't diplay at all.
![image](https://github.com/sandboxie-plus/Sandboxie/assets/174184315/f0e8da34-bdb7-4305-b475-25710cab8adb)

[In AppData~Local~CrashDumps.zip](https://github.com/user-attachments/files/16110643/In.AppData.Local.CrashDumps.zip)
OR 
-When I use Virtualization scheme version 1.
I can see firefox windows,but every tab crashed.Like this:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/174184315/8e03e809-70ef-4c4e-b2e2-4eeb0f52db80)

And urls like about:preferences is right.

![image](https://github.com/sandboxie-plus/Sandboxie/assets/174184315/1ce5cea5-bc6a-4dd4-8ba0-b36c99da321c)
[AppData~Roaming~Mozilla~Firefox~Crash Reports~pending.zip](https://github.com/user-attachments/files/16110890/AppData.Roaming.Mozilla.Firefox.Crash.Reports.pending.zip)
There is nothing in CrashDumps.

### How often did you encounter it so far?

It had never happened before.And now evertime I open firefox in sandbox .

### Expected behavior

Firefox can be used in sandboxie.

### Affected program

Firefox 115.12.0esr-win64

### Download link

https://ftp.mozilla.org/pub/firefox/releases/115.12.0esr/win64/zh-CN/Firefox%20Setup%20115.12.0esr.exe

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did. See the link to the .dmp file(s) I have attached here.

### What version of Sandboxie are you running now?

Plus 1.13.7 and 1.14.3

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression from previous versions?

This problem didn't happen until now when I using 1.13.7.And I didn't install any software duing that time. 

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows7 Sp1

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

360 Anti virus. Huorong

### Did you previously enable some security policy settings outside Sandboxie?

No.

### Sandboxie.ini configuration

```ini
[GlobalSettings]
FileRootPath=F:\SANDBOX\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
EnableWin32kHooks=y
EditAdminOnly=y
ForceDisableAdminOnly=y
Template=WindowsRasMan
Template=TIM
Template=QQ
Template=Listary
Template=AdobeLicensing
Template=7zipShellEx
Template=AdobeDistiller
Template=Microsoft_MSMQ
Template=Edge_Fix
Template=AdobeAcrobatReader
DefaultBox=DefaultBox

[UserSettings_133A02B6]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
SbieCtrl_UserName=yvzhou
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_WindowCoords=200,150,928,527
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_BoxExpandedView=DefaultBox,zzKyzgYB,New_Box,New_Box_1

[DefaultBox]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#ffc814,ttl,6
Template=OpenProtectedStorage
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
FakeAdminRights=y
CopyLimitKb=-1
OpenCredentials=y
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
UnrestrictedSCM=y
MsiInstallerExemptions=y
AllowSpoolerPrintToFile=y
AllowRawDiskRead=y
NotifyDirectDiskAccess=y
OpenProtectedStorage=y
ReadIpcPath=$:*
OpenPrintSpooler=y
OpenIpcPath=*\BaseNamedObjects*\__ComCatalogCache__
OpenIpcPath=\RPC Control\OLE*
OpenIpcPath=\RPC Control\LRPC*
OpenIpcPath=\RPC Control\epmapper
RpcMgmtSetComTimeout=n
NoSecurityIsolation=y
NoSecurityFiltering=y
AllowNetworkAccess=<BlockNetAccess>,n
UseFileDeleteV2=y
UseRegDeleteV2=y
NeverDelete=y
NeverRemove=y

[zzKyzgYB]
Enabled=y
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#9290ff,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UsePrivacyMode=n
BoxNameTitle=y
CopyLimitKb=-1
MsiInstallerExemptions=y
DropAdminRights=y
OpenPrintSpooler=y
AllowSpoolerPrintToFile=y
StartProgram="F:\Mozilla Firefox\firefox.exe" -private-window
StartProgram="F:\下载\Umi-OCR.Rapid v1.3.4测试版\Umi-OCR 文字识别.exe"

[New_Box]
Enabled=y
BlockNetworkFiles=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
SeparateUserFolders=n
AutoRecover=y

[New_Box_1]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
AutoRecover=y
```

**Comment by pbtdej35692hotmail** [comment]
I mean Firfox didn't crahs in plus1.13.7 for a long time. Suddenly,I found every tab I opened crashed.After I reboot,firefox always crash.

**Comment by APMichael** [comment]
Obviously, the sandbox is not deleted using "AutoDelete" after a program is closed. The contents of the sandbox should therefore be deleted manually (context menu: "Delete Content" > button: "Delete Content"). After this, Firefox may already be working again.

**Comment by offhub** [comment]
Have you tried with a new profile on a new box?

new box:
```ini
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=n
UseRegDeleteV2=n
AutoDelete=n
UseRuleSpecificity=y
WriteFilePath=?:\*
NormalFilePath=%SystemRoot%\*
NormalFilePath=%ProgramFiles%\Mozilla Firefox\*
```

new box > run sandboxed:
```bat
cmd /c "cd /d "%ProgramFiles%\Mozilla Firefox" && firefox -CreateProfile TestUser & firefox -P TestUser"
```

**Comment by pbtdej35692hotmail** [comment]
> Have you tried with a new profile on a new box?
> 
> new box:
> 
> ```ini
> Enabled=y
> BlockNetworkFiles=y
> RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
> RecoverFolder=%Personal%
> RecoverFolder=%Desktop%
> BorderColor=#02f6f6,ttl
> Template=OpenBluetooth
> Template=SkipHook
> Template=FileCopy
> Template=qWave
> Template=BlockPorts
> Template=LingerPrograms
> Template=AutoRecoverIgnore
> ConfigLevel=10
> UseFileDeleteV2=n
> UseRegDeleteV2=n
> AutoDelete=n
> UseRuleSpecificity=y
> WriteFilePath=?:\*
> NormalFilePath=%SystemRoot%\*
> NormalFilePath=%ProgramFiles%\Mozilla Firefox\*
> ```
> 
> new box > run sandboxed:
> 
> ```batchfile
> cmd /c "cd /d "%ProgramFiles%\Mozilla Firefox" && firefox -CreateProfile TestUser & firefox -P TestUser"
> ```

Thank you.
It works!
Can you tell me why it works?
And how can i use firefox without crashing in a normal sandbo?
Thank you

**Comment by offhub** [comment]
1. Remove these lines from the box config
```ini
UseRuleSpecificity=y
WriteFilePath=?:\*
NormalFilePath=%SystemRoot%\*
NormalFilePath=%ProgramFiles%\Mozilla Firefox\*
```

2. Delete Content
3. Run Firefox with a new profile as sandboxed
    - If Firefox does not crash, this may be a profile-related problem.
    - If Firefox crashes, it is most likely caused by a third-party program.
 
> And how can i use firefox without crashing in a normal sandbo?

You need to find out which program is causing the crash and prevent that program from interfering with the sandboxed Firefox with ClosedFilePath.

https://github.com/sandboxie-plus/Sandboxie/assets/6871698/3f7ec327-eba2-45f6-af06-1e0bcf618e52

#### From explorer:
1. Go to "Program Files" and "Program Files (x86)"
2. Select all
3. Shift+Right click > Copy as path
4. Paste it into Notepad

#### From Notepad:
1. Ctrl+H
2. Find what: `"C` 
3. Replace with: `NormalFilePath=C`
4. Find what: `"`
5. Replace with: ` ` (empty)

#### From SandMan:
1. Open box options
2. Go to Edit Ini
3. Copy the list from notepad and paste it here
4. Save
5. By disabling them one by one (or three at a time) from the "Resource Access" list, you can find the path that is causing Firefox to crash. (Do not disable the three rules added with UseRuleSpecificity!)

**Comment by pbtdej35692hotmail** [comment]
Thank you for your reply.
I have solved this problem.
360 Total Security causede this.Adding "WriteFilePath=C:\Program Files (x86)\360" can solve it.
I am sorry for not checking third-party program before opening the issue.

By the way,can you tell me how to avoid firefox logging automatically and syncing on a new empty sandbox?

**Comment by offhub** [comment]
Try blocking signedInUser.json:

```ini
WriteFilePath=firefox.exe,*\Mozilla\Firefox\Profiles\*\signedInUser.json
```

OR

With this setting, Firefox will open as if you were opening it for the first time:

```ini
WriteFilePath=firefox.exe,*\Mozilla\Firefox\Profiles\**\*
```

**Comment by pbtdej35692hotmail** [comment]
It works.
Thank you very much.
