### ISSUE TITLE
Administrators cannot change the sandbox configuration

### ISSUE THREAD

**Issue by fzxx** [sandboxie-plus/Sandboxie#4057]
### Describe what you noticed and did

![1](https://github.com/sandboxie-plus/Sandboxie/assets/53783792/9eaf7921-5e8b-400e-8c9d-3047a7308181)
Administrator account
![2](https://github.com/sandboxie-plus/Sandboxie/assets/53783792/27364987-34db-4e04-9a92-bc14c00341ce)

### Expected behavior

Administrators can save configurations

### Affected program

sandboxie plus

### Download link

not

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus v1.14.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

Sandboxie Plus v1.13.7 is normal

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Win10 22h2 / Win11 23h2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

not

**Comment by offhub** [comment]
I can reproduce the problem with the built-in administrator account.

**Comment by DavidXanatos** [comment]
"great" will fix that first thing tomorrow

**Comment by DavidXanatos** [comment]
@offhub  please try the latest CI build

**Comment by offhub** [comment]
The latest CI build fixes issues #4057 and #4068.
