### ISSUE TITLE
Allow setting Encrypted box image size during Sandbox creation

### ISSUE THREAD

**Issue by TFWol** [sandboxie-plus/Sandboxie#4059]
### Is your feature request related to a problem or use case?

I recently had a hard time understanding what was happening when apps in the encrypted box were breaking. I wasn't aware of the initial 2GB image creation until I received help in #4058.

### Describe the solution you'd like

Could information about this be easier to find? 
I think it'd be useful to also include setting the initial image size from the box creation wizard.

![image](https://github.com/sandboxie-plus/Sandboxie/assets/9045213/6c3672c7-e439-467d-b110-4b0ffba244b9)

**Comment by offhub** [comment]
After clicking the Finish button, you can specify the disk image size in the new password dialog.

![sbie4058rs](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/1b8f02d9-b395-4568-92eb-efa25f7d2ff2)

**Comment by TFWol** [comment]
@offhub Thanks, I figured out why I wasn't seeing this; I had an AutoHotkey GUI automation script I had running when it shouldn't have. Specifically a `Winhide` function 😅
