### ISSUE TITLE
The name of the sandbox is too long, causing an error in sbie2327

### ISSUE THREAD

**Issue by fzxx** [sandboxie-plus/Sandboxie#4064]
### Describe what you noticed and did

1. Rename the sandbox fd9uu84h9849tt_984198416149641
2. Run Telegram
3. Error code sbie2327
4. Rename the sandbox fd9uu84h9849tt
5. Telegram is up and running.

### Expected behavior

Normal operation

### Affected program

Telegram v5.2.3.0

### Download link

https://telegram.org/dl/desktop/win64_portable

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus x64 v1.14.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Win10 22h2 / Win11 23h2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

not

### Sandboxie.ini configuration

```ini
[GlobalSettings]
Template=Edge_Fix
Template=OfficeLicensing
Template=WindowsLive
DefaultBox=fd9uu84h9849tt_984198416149641

[UserSettings_4BC00582]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:fd9uu84h9849tt_984198416149641

[fd9uu84h9849tt_984198416149641]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10
```

**Comment by offhub** [comment]
<details>
  <summary>I can confirm that this issue occurs when the box name is longer than 29 characters.</summary>
  
#### Run outside the sandbox:
  
```bat
@echo off

set lockFile=%TEMP%\lockfile-issue4064

if exist "%lockFile%" (
	echo Another instance is running.
	timeout 3
	exit /b
) else (
	type NUL >"%lockFile%"
)

set sbiePath=%ProgramFiles%\Sandboxie-Plus
set boxName=LongerThan29Characters_BoxName
set progName=msedge.exe

pushd "%cd%"
cd /d "%sbiePath%"

SbieIni.exe set %boxName% Enabled y
Start.exe /reload
Start.exe /box:%boxName% %progName%

echo See the message log. (Press any key to remove the box)
pause > nul

Start.exe /box:%boxName% /terminate
Start.exe /box:%boxName% delete_sandbox
SbieIni.exe set %boxName% * ""
Start.exe /reload

del "%lockFile%"
popd
exit /b
```
  
</details>

**Comment by fzxx** [comment]
![3](https://github.com/sandboxie-plus/Sandboxie/assets/53783792/95d085e3-bbd9-4580-9a0d-6270d49d50cd)
> Don't use virtualized COM, Open access to hosts COM infrastructure (not recommended
Long name, no error will be reported after selection
