### ISSUE TITLE
Border Breaks when using DPI Scaling

### ISSUE THREAD

**Issue by JordaneParis** [sandboxie-plus/Sandboxie#4066]
### Describe what you noticed and did

I'm experiencing the same issue reported in the ticket #1512 already fixed in Sandboxie +. 

https://github.com/sandboxie-plus/Sandboxie/issues/1512

The border doesn't match the window if the window is moved from one screen to another

Could you please implement the same fix in Sandboxie classic ?

### How often did you encounter it so far?

Always

### Expected behavior

The color border should match the window in each used screens. 

### Affected program

Firefox or EDGE

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

5.69.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Professionnel 22H2 Build 19045.4529

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

F-Secure

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```ini
I would prefer not sharing my sandboxie.ini that isn't related to the screen's borders bug. (Already fixed)
```

**Comment by JordaneParis** [comment]
Hello staff/dev team, 
Could I have a confirmation that this problem has been taken into account ? 

Thank you very much in advance !

**Comment by DavidXanatos** [comment]
Sandboxie classic is not being actively developed, unless its something that got broken which was working before or a security issue I don't have time to fix it.

Please use Sandboxie+
