### ISSUE TITLE
download blocked by Defender SmartScreen

### ISSUE THREAD

**Issue by MrHunYardi** [sandboxie-plus/Sandboxie#407]
All installers for latest release are blocked by MS Edge via Defender SmartScreen. 

![image](https://user-images.githubusercontent.com/77677163/105040015-9c90e080-5a61-11eb-8829-95e787469240.png)

I reported that I think the file is safe, but I guess that you might want to work with MS to get this whitelisted. 

![image](https://user-images.githubusercontent.com/77677163/105040166-cf3ad900-5a61-11eb-95f1-e182511e2827.png)

Wanted to evaluate software for sandbox features.

**Comment by DavidXanatos** [comment]
Any binary could harm you PC, no exception, 
press the 3 dots and opt to keep the file,
as simple as that.
