### ISSUE TITLE
Locale Emulator

### ISSUE THREAD

**Issue by fzxx** [sandboxie-plus/Sandboxie#4072]
### Is your feature request related to a problem or use case?

Some software has to run in a specific language, and it would be great if the sandbox could emulate the language.

### Describe the solution you'd like

Refer to another project, https://github.com/xupefei/Locale-Emulator

**Comment by love-code-yeyixiao** [comment]
There is already a draft pull request,but not for this issue,it's my own idea.[#4024](https://github.com/sandboxie-plus/Sandboxie/pull/4024)

**Comment by Vstory** [comment]
Great idea

**Comment by DavidXanatos** [comment]
I have merged the pull request and fixed many bugs not sure if it does all it needs to but what it does seams to work ok now, will be in included in the next build

**Comment by fzxx** [comment]
> 我已经合并的请求和固定的许多错误不确定如果它不会它所需要的，但它不会接缝工作确定现在，将包括在建立下一个

Sandboxie Plus x64 v1.14.5, change language EN-US, run Beyond Compare registrar; wrong registration code generated.
https://www.scootersoftware.com/files/BCompare-zh-5.0.1.29877.exe
The registration machine requires an English system to generate the registration code properly. 
[keygen.zip](https://github.com/user-attachments/files/16361577/keygen.zip)
https://github.com/xupefei/Locale-Emulator The project runs fine with the registrar
