### ISSUE TITLE
Some programs are unable to load language files

### ISSUE THREAD

**Issue by fzxx** [sandboxie-plus/Sandboxie#4073]
### Describe what you noticed and did

1. Run ToYcon directly, the language file loads successfully, and Chinese is displayed
2. Run ToYcon on the sandbox, the language option disappears, and English is displayed
[ToYcon.zip](https://github.com/user-attachments/files/16177095/ToYcon.zip)

Win10 22h2 right-click to run, the language file loads normally; Drag and drop, the language file does not load properly
Win11 23h2 right-click to run, drag and drop, language file does not load.

### Expected behavior

The sandbox runs ToYcon, there is a language option, and Chinese is displayed

### Affected program

ToYcon

### Download link

See the attachment above

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus x64 v1.14.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Win10 22h2 / Win11 23h2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

not

**Comment by offhub** [comment]
It fails because the working directory is not set as the program folder.

|Working Directory|Program's Folder|SbieHome|
|---|---|---|
|Sandboxed|No|Yes|
|Unsandboxed|Yes|No|


### Workaround

Create a shortcut (or sandboxed shortcut) to the program and set the "Start In" value to the program's directory.

**Comment by bastik-1001** [comment]
Can Sandboxie do something about it? If so, this issue should remain open until that is done and replaces the workaround. If not, this could be something for the documentation, like known issues or something like that.

**Comment by fzxx** [comment]
> 可以沙盘做些什么呢？ 如果是这样，这个问题应当继续开放，直到完成和替换解决方法。 如果不是，这可能是一些文件，如已知的问题或者类似的东西。

![1](https://github.com/user-attachments/assets/7a90cad1-ade9-482e-8ec7-fb72984865ab)

Maybe the option could be added here, somehow it works? @DavidXanatos

**Comment by DavidXanatos** [comment]
in the next build we will auto take the apps parent folder as workign dir
