### ISSUE TITLE
Getting two advanced supporter certificate popups everytime I open Sandbox Settings on any sandbox

### ISSUE THREAD

**Issue by mike406** [sandboxie-plus/Sandboxie#4074]
### Describe what you noticed and did

After upgrading to 1.14.3 anytime I open Sandbox Settings for any sandbox, including a default one, I get prompted with two popups about the advanced supporter certificate that I need to dismiss before the settings open.

### Expected behavior

I was not using any "advanced" restricted features prior to upgrading to 1.14.3 so I am unsure why I am seeing this popup when just opening up settings. I was previously on version 1.13.7.

### Affected program

Any

### Download link

N/A

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

1.14.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 22h2

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Defender, MBAM

**Comment by offhub** [comment]
This issue occurs when the user selects the `Use a Page Tree in the Box Options instead of Nested Tabs` checkbox or when the selected view mode uses this option.
> Sandboxi Plus > Options > Global Settings > Interface Config > User Interface :
Use a Page Tree in the Box Options instead of Nested Tabs *

#### Sandboxie-Plus.ini
```ini
[Options]
.
OptionTree=1
.
```

### Workaround:
You can temporarily deselect this option.

**Comment by DavidXanatos** [comment]
aaaarrrg... wtf will fix that asap
