### ISSUE TITLE
Hide Tray Icon

### ISSUE THREAD

**Issue by JordaneParis** [sandboxie-plus/Sandboxie#4075]
### Is your feature request related to a problem or use case?

My demand is not realy related to an issue, it's more a GUI confort use case. 

Since I use sandboxie classique to execute always the same program with a shordcute on my desktop. 
After getting ready with my setup, I would like to be able to hide the tray icon. 

### Describe the solution you'd like

Is it possible to work this way to give me the possibility to do it in the sandboxie.ini or anything else ? 

It would be awesome to add the line in sandboxie.ini so if I want the tray icon back I can remove the line from the .ini. 

Or something like that. 

### Describe alternatives you've considered

I tried the way to do it manually. But I cannot remove it from active icons with windows settings. And particulary if I want to automate it with a script. It' a pain to edit binary data from tray menu in windows and can corrupt my whole system.

**Comment by offhub** [comment]
This setting is available in the Plus UI.

**Comment by bastik-1001** [comment]
The old user interface is no longer being worked on. David, the developer, said that it is not supposed to get new features or options to enable features. (Otherwise, there is no objection against this feature request.)

Like offhub said, with SandMan, the new UI of Sandboxie-Plus you have the option to display classic icons, the plus icons or no icons in the tray.

Options > Global Settings > Shell Integration > [System Tray] > "Show Icon in Systray" there is a drop-down menu.

**Comment by JordaneParis** [comment]
I'm not sure where to follow the developers' discussions. Nevertheless, I don't quite understand if the feature request will be approved or not. I would love to get that improvement even without a GUI modification. Sandboxie.ini is enough to me.

**Comment by e-t-l** [comment]
> I would love to get that improvement even without a GUI modification. Sandboxie.ini is enough to me.

@JordaneParis the sandboxie.ini file only sets parameters for the sandboxes and the programs that run inside them. The tray icon is a hard-coded part of the interface for the sandboxie program executable itself. So your feature request is, by definition, a "GUI modification" that would require updating the entire sandboxie classic program. Devs have already decided this will not happen (although I don't blame you for not knowing that ahead of time).

We highly recommend you switch to Sandboxie Plus, which gives you the option to hide the tray icon along with lots of others. There are no benefits to sticking with Classic, and it's not hard to switch. All your same sandboxes and ini files will work exactly the same in Plus as they did in Classic.

**Comment by DavidXanatos** [comment]
Hide no tray will be added to plus UI in next build 1.15.2

![image](https://github.com/user-attachments/assets/45fdba2d-8113-4d46-9309-d09b4b4b3c7a)
