### ISSUE TITLE
The operation of the Final Fantasy XIV game in the sandbox will lead to a significant reduction in the game's frame rate.

### ISSUE THREAD

**Issue by Canplayer** [sandboxie-plus/Sandboxie#4084]
### Describe what you noticed and did

I run the Final Fantasy XIV game in a sandbox. Normally, when not running in the sandbox, the frame rate in the main city can be around 70 - 80. However, if running under the default settings of the sandbox, the frame rate will directly drop to around 30 - 50. Through my attempts and experiments, I found that if the two parameters "OriginalToken=y" and "NoSysCallHooks=y" are used, the frame rate will return to the normal level, but I know that this will cause security problems. Now, is there any good solution to solve the frame rate problem of this type of memory I/O-intensive game? 
![屏幕截图 2024-07-14 145729](https://github.com/user-attachments/assets/44071055-4168-42d0-a4cd-4a10e6425b72)
![屏幕截图 2024-07-14 145543](https://github.com/user-attachments/assets/3491e436-b386-48ba-a94b-86ddbc48b127)

### How often did you encounter it so far?

Every time

### Expected behavior

Hope to solve the problem of too low game frame rate without affecting security. 

### Affected program

Final Fantasy XIV Chinese version

### Download link

https://ff.web.sdo.com/web8/index.html#/download

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

1.14.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 11 23H2 22631.3880

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Microsoft Defender

### Did you previously enable some security policy settings outside Sandboxie?

no

### Sandboxie.ini configuration

```ini
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
AutoRecover=n
BoxNameTitle=-
CopyLimitKb=-1
ForceFolder=E:\Users\Canplayer\Downloads\FF14 mods
OpenPipePath=E:\Users\Canplayer\Downloads\FF14 mods
UseFileDeleteV2=y
UseRegDeleteV2=y
BreakoutProcess=msedge.exe
#OriginalToken=y
#NoSysCallHooks=y
```

**Comment by Vstory** [comment]
For what reason the game needs to run in the sandbox, I'm just curious

**Comment by Canplayer** [comment]
@Vstory prevents breaking the game itself when testing mods

**Comment by SandboxerX86** [comment]
Your problem could be related to this other one: [https://github.com/sandboxie-plus/Sandboxie/issues/3977#issuecomment-2174247289](https://github.com/sandboxie-plus/Sandboxie/issues/3977#issuecomment-2174247289)

Look at the solution that DavidXanatos gives and try to see if it fixes it.

**Comment by bastik-1001** [comment]
Since the other issue about performance and FPS in games is still open, this is a duplicate. I am closing this, since the other issue links to this in case the information are still relevant.
