### ISSUE TITLE
Automatically deleting sandbox content always yields an error

### ISSUE THREAD

**Issue by Vstory** [sandboxie-plus/Sandboxie#4085]
### Describe what you noticed and did

![image](https://github.com/user-attachments/assets/d89fd14a-2b54-48fd-9bb2-527bff12a307)
After the sandbox program is opened and ended, the sandbox content is automatically deleted, which always results in an error.
Is this related to virtualization solution 2?

### How often did you encounter it so far?

No

### Expected behavior

Delete sandbox content as normal.

### Affected program

Standard sandbox

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

1.14.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Win11 24H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

NO

### Did you previously enable some security policy settings outside Sandboxie?

NO

### Trace log

NO

### Sandboxie.ini configuration

```ini
Template=AdGuard
Template=Edge_Fix
Template=Microsoft_MSMQ
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan
DefaultBox=DefaultBox
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
EditAdminOnly=y
ForceDisableAdminOnly=y
ForgetPassword=y
```

**Comment by JordaneParis** [comment]
Are you sure you don't have any window open in read mode (Registry, Windows Explorer or other) in sandboxie folders ? 
Or an application in access (read, write).
AdGuard ?

**Comment by Vstory** [comment]
> Are you sure you don't have any window open in read mode (Registry, Windows Explorer or other) in sandboxie folders ? Or an application in access (read, write). AdGuard ? Ad Guard ?

All programs in the sandbox have been terminated, and then manually deleted, but an error is still displayed.

**Comment by Vstory** [comment]
The installer is downloaded from the github release page. This issue has been resolved, and the sandbox can automatically delete the content after restarting with administrator privileges.

![20240715_204404_466_copy](https://github.com/user-attachments/assets/f471b83e-3dbe-45bb-96bd-16205763d80b)

**Comment by Vstory** [comment]
This problem has come up again, I suggest opening an issue.

![Image](https://github.com/user-attachments/assets/60b754b3-3e4a-4114-a6f7-dd2313c38496)
