### ISSUE TITLE
Problems with modal windows

### ISSUE THREAD

**Issue by lufog** [sandboxie-plus/Sandboxie#409]
1) Some modal windows block main window but not shown itself:
<details>
  <summary>Show spoiler (gif with problem visualization)</summary>

![WJ5aOfwgYH](https://user-images.githubusercontent.com/10379487/105044703-1764f600-5a78-11eb-8b17-91fdad5f55bd.gif)

</details>

2) If enabled "Always on Top" all modal windows showed behind main window:

<details>
  <summary>Show spoiler  (gif with problem visualization)</summary>

![N6vu9Wa2F3](https://user-images.githubusercontent.com/10379487/105044312-a291bc00-5a77-11eb-8494-ef581c2734ad.gif)

</details>

SBIE version is 0.5.5 / 5.46.4 (64 bit)

**Comment by DavidXanatos** [comment]
I see... will be fixed in next build
