### ISSUE TITLE
force_children test

### ISSUE THREAD

**Issue by dxq3** [sandboxie-plus/Sandboxie#4092]
### Describe what you noticed and did

- create bat file:  start "" notepad.exe
- run "C:\Program Files\Sandboxie-Plus\Start.exe" /fcp /force_children <path_to_bat>
I got 3 errors 1241, 1231, 2314

### Expected behavior

unsandboxed cmd and sandboxed notepad

### Affected program

Not relevant

### Download link

Not available

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus-x64-v1.14.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

11 23h2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

no security software

**Comment by offhub** [comment]
These errors occur on a Windows 11 23H2 when the UWP version of Notepad is enabled and the `NoAddProcessToJob=y` option is set. Try with another non-UWP app. #19 #1489

<details>
  <summary>Test.bat</summary>
  
Save to file and run outside the sandbox.
```bat
@echo off

pushd "%cd%"
cd /d "%ProgramFiles%\Sandboxie-Plus"

SbieIni.exe set "TestBox" "Enabled" "y"
SbieIni.exe set "TestBox" "NoAddProcessToJob" "y"
Start.exe /reload
Start.exe /box:TestBox /fcp cmd.exe /c "start "" notepad.exe"

popd

exit /b
```
  
</details>

**Comment by dxq3** [comment]
thx offhub! I knew about uwp, but forgot notepad becomes too) And fcp and  force_children is same command... So stuped mistakes from me
