### ISSUE TITLE
Logic Issue

### ISSUE THREAD

**Issue by JordaneParis** [sandboxie-plus/Sandboxie#4098]
### Describe what you noticed and did

I am encountering a problem securing sandox access to my files. I want to remove root access from Program Files but I need to open one of the program files folders. If I follow the documentation. CloseFilePath=c:\Program Files\ will take priority over
OpenFilePath=c:\Program Files\ThisFolder 
Is there A way to do this that I missed ? 

### How often did you encounter it so far?

always

### Expected behavior

CloseFilePath=C:\Program Files\ROOT
OpenFilePath=C:\Program Files\ThisFolder

I want to remove permission to Firefox to write in my program file root folder without closing the rest of the folders. 

### Affected program

Firefox

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

5.69.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Professionnel 22H2 Build 19045.4529

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

F-Secure

**Comment by DavidXanatos** [comment]
Yes, you need to enable rule specificity:

![grafik](https://github.com/user-attachments/assets/442fda64-729d-4ff1-a9b5-11865d20a2d1)
