### ISSUE TITLE
Some bugs in Sandboxie-Plus v0.5.5

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#410]
1. In Global Settings - Advaned Options - Sandbox file system root, the default value is 
`\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%`
 , and "Separate user folders" is selected. 

- Case 1: If "Separate user folders" is selected, when I select `D:\test` in "select directory", it changed to `D:\test\%SANDBOX%`, but it should be `D:\test\%USER%\%SANDBOX%`, i.e. `%USER%\%SANDBOX%` should directly append at the end of the path user select. 

- Case 2: If user unselect "Separate user folders", the path should change to `%SystemDrive%\Sandbox\%SANDBOX%`, i.e. delete `\%USER%` before `\%SANDBOX%`, when user select "Separate user folders" again, the path should change to `%SystemDrive%\Sandbox\%USER%\%SANDBOX%`, i.e. append `\%USER%` before `\%SANDBOX%`. 

2. When "always on top" is enabled, the main UI will cover all pop-up window such as Global Settings, but Create New Box is OK. 

3. When dragging & dropping a file/program/shortcut to Sandboxie-Plus main window, It lack a "Run As UAC Administrator" option. 

4. Compare with Sandboxie-Plus 0.5.4d, ver 0.5.5 lacks snapshot taken time.

**Comment by isaak654** [comment]
@0x391F I think you should include all paths containing slashes inside code blocks.

Example:
`\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%`

**Comment by 0x391F** [comment]
> 
> 
> @0x391F I think you should put all paths containing slashes inside code blocks, for a better reading.
> 
> Example:
> `\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%`

OK.
