### ISSUE TITLE
Running onedrive in the sandbox requires re-logging each time 

### ISSUE THREAD

**Issue by ydx1013** [sandboxie-plus/Sandboxie#4105]
### Describe what you noticed and did

Running onedrive in the sandbox requires re-logging each time 

### How often did you encounter it so far?

always

### Expected behavior

can run onedrive

### Affected program

onedrive

### Download link

"Not available".

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

always cannt run  1.14.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

yes

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

win10 pro 22h2

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

no

### Did you previously enable some security policy settings outside Sandboxie?

no

### Sandboxie.ini configuration

```ini
Enabled=y
BlockNetworkFiles=y
BorderColor=#02f6f6,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y


# OneDrive
ClosedClsid={71DCE5D6-4B57-496B-AC21-CD5B54EB93FD}
ReadFilePath=\Device\MountPointManager
ReadFilePath=%AllUsersProfile%\Microsoft\Windows\Caches
ReadFilePath=%UserProfile%\AppData\Local\Microsoft\Windows
ClosedIpcPath=*\Shell.CMruPidlList
OpenPipePath=D:\
OpenSamEndpoint=y
OpenLsaEndpoint=y
```

**Comment by love-code-yeyixiao** [comment]
Try `OpenCredentials=y`

**Comment by ydx1013** [comment]
it works，thank you，but，i still cant use the ‘file on-demand’ function，there is the descriptions 

https://support.microsoft.com/en-us/office/save-disk-space-with-onedrive-files-on-demand-for-windows-0e6860d3-d9f3-4971-b321-7092438fb38e


and i try the method to reset my onedrive：

%localappdata%\Microsoft\OneDrive\onedrive.exe /reset
%localappdata%\Microsoft\OneDrive\onedrive.exe

**Comment by ydx1013** [comment]
> Try `OpenCredentials=y`

it works，thank you，but，i still cant use the ‘file on-demand’ function，there is the descriptions

https://support.microsoft.com/en-us/office/save-disk-space-with-onedrive-files-on-demand-for-windows-0e6860d3-d9f3-4971-b321-7092438fb38e

and i try the method to reset my onedrive：

%localappdata%\Microsoft\OneDrive\onedrive.exe /reset
%localappdata%\Microsoft\OneDrive\onedrive.exe
