### ISSUE TITLE
Bug pop-up notification window after start SandMan

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#411]
![изображение](https://user-images.githubusercontent.com/25817412/105063288-4bb3d300-5ac7-11eb-80ac-2053b3af3e1e.png)

**Comment by DavidXanatos** [comment]
make the notification window bigger and tell me what messages you got exactly

**Comment by lufog** [comment]
I think this is the same problem as #409 first spoiler gif.

**Comment by Zymlex** [comment]
This window has a resizing function, but it can't be changed, it as limited in size.

**Comment by Zymlex** [comment]
This window:

![изображение](https://user-images.githubusercontent.com/25817412/105606539-b75ab080-5de5-11eb-9d78-ce00f7701518.png)
