### ISSUE TITLE
alias for a sandbox

### ISSUE THREAD

**Issue by NightmareZero** [sandboxie-plus/Sandboxie#4112]
### Is your feature request related to a problem or use case?

Now, the name of the sandbox can only use English characters. Can an alias function be added to use i18n when displaying the name, but the actual name is still in English? It's a bit difficult to distinguish now
I have dozens of "Application Compartments with Data Protection", even grouping them makes it too difficult to distinguish each one

### Describe the solution you'd like

Add sandbox alias, just use this name for display

**Comment by fzxx** [comment]
@DavidXanatos Currently, aliases are only displayed on the main interface, and it is recommended to add them to the Run Options and Tray menus.
