### ISSUE TITLE
Add EventLog monitoring for ForceFolder / ForceProcess

### ISSUE THREAD

**Issue by 1mm0rt41PC** [sandboxie-plus/Sandboxie#4113]
### Is your feature request related to a problem or use case?

On a shared server, I have multiple users and in order to debug what was catched by ForceFolder and ForceProcess I need to have some log but even with the reg `HKLM\SYSTEM\CurrentControlSet\Services\SbieSvc` I'm not able to view what was catched.

### Describe the solution you'd like

I would like to have a Windows eventlog indicating that the driver has caught process XXXX due to rule YYYYY.

### Describe alternatives you've considered

None

**Comment by 1mm0rt41PC** [comment]
Nice job !!!! Thank you !

**Comment by offhub** [comment]
Is there an SBIE message for ForceFolder / ForceProcess?

**Comment by DavidXanatos** [comment]
there is one for the it fails because its disabled, there is non on succes,
do we need such a message?

**Comment by DavidXanatos** [comment]
Yes I think this will be usefull, will need to look how to do that,
I want it in the sbie log in the plus UI but not popping up eider in plus nor in classic.

Will add it to the next build
