### ISSUE TITLE
"SbieDll.dll" couldn't be initialized [Solved: use 32-bit version of Tor Browser]

### ISSUE THREAD

**Issue by Damnatus** [sandboxie-plus/Sandboxie#412]
Hi,

When I try to run Tor Browser in Sandboxie I got an error message that sbiedll.dll could not be initialized. Tor Browser is not able to connect to the internet then but still responsive within the sandbox. I tried it with a new default , hardened and even legacy box (via template) next to my dedicated Tor Browser box. 

All the same except the default box that started to have #376 in 0.5.5 instead. 

I don't know which info might be useful, so please tell me what you need from me if you need anything.

![Screenshot 2021-01-19 183420](https://user-images.githubusercontent.com/7227343/105074181-53a05280-5a88-11eb-8f37-0273bd67a602.png)

**Comment by tutak-kat** [comment]
Well for me tor is not working at least 1.5 years while Sophos still was responsible for development, and since that time nothing changed.
I also several months ago asked the same question and post was removed in just a few hours without any explanation????

Obviously people think that tor is only for criminals and pedos.. so they don't care.

**Comment by Coverlin** [comment]
@Damnatus @tutak-kat 
Tor works for me , but the only way i made it to work with sbie was to install the x86 (32bit) version
[https://archive.torproject.org/tor-package-archive/torbrowser/10.0.8/](url) search for torbrowser-install-10.0.8_en-US.exe 
or for the lang you want

**Comment by Damnatus** [comment]
> 
> 
> @Damnatus @tutak-kat
> Tor works for me , but the only way i made it to work with sbie was to install the x86 (32bit) version
> [https://archive.torproject.org/tor-package-archive/torbrowser/10.0.8/](url) search for torbrowser-install-10.0.8_en-US.exe
> or for the lang you want

Oh FFS!
I forgot about the 64-bit issue with Tor and that it only works with the 32-bit version!
It has been very long since I built my system from scratch and that detail slipped my mind when setting it up.    
Thanks @Coverlin!

**Comment by isaak654** [comment]
It would still be great to know why 64-bit version didn't work.
