### ISSUE TITLE
How does Sandboxie-Plus know what I selected in the Setup Wizard menu? [question]

### ISSUE THREAD

**Issue by NOTgate** [sandboxie-plus/Sandboxie#4120]
### Is your feature request related to a problem or use case?

How does Sandboxie-Plus know what I selected in the Setup Wizard menu?
![image](https://github.com/user-attachments/assets/7c0827b5-8d68-4765-9694-916d15be73f0)

### Describe the solution you'd like

I want to know where Sandboxie-Plus saves invisible settings!

**Comment by DavidXanatos** [comment]
It saves it in the registry you can review the driver code to find out where.
As for commercial use of the Plus UI a license is needed (there is no free option for businesses, unless they want to be stuck to the ugly old classic UI), we don't want people after the trial has expired to just switch to personal and keep using it in violation of the license terms, hence I wont give further advice where the data are stored and how to alter them.
