### ISSUE TITLE
cpu rate limit per sandbox

### ISSUE THREAD

**Issue by Kizuno18** [sandboxie-plus/Sandboxie#4138]
### Describe what you noticed and did

<img width="121" alt="image" src="https://github.com/user-attachments/assets/f66a0a42-ba86-4811-80bb-a9f7c04365f9">
i've applied this settings into the ini file, but still not apllying

### Expected behavior

ive tried to limit cpu by box and it not work

### Affected program

not relevant

### Download link

latest version

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did. See the link to the .dmp file(s) I have attached here.

### Crash dump

no crash

### What version of Sandboxie are you running now?

latest

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

no

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

win 11 64bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

kaspersky

### Sandboxie.ini configuration

```ini
Enabled=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#ac36f6,on,6
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
DropAdminRights=y
BoxOptions=FakeAdminRights=y
BoxOptions=HideHostProcesses=y
HideHostProcesses=y
FakeAdminRights=y
BoxNameTitle=-
NotifyProcessAccessDenied=y
AllowClipboard=y
HideFirmwareInfo=y
CpuRateControl=y
CpuRate=1
CpuLimit=1
MemoryLimitMb=256
RunCommand=rclient|F:\Repos\rclient.exe -no-update
AutoDelete=y
```

**Comment by offhub** [comment]
The CPU rate limit feature is not available in Sandboxie. In addition, your configuration contains several invalid settings.

```ini
BoxOptions=FakeAdminRights=y
BoxOptions=HideHostProcesses=y
HideHostProcesses=y
AllowClipboard=y
CpuRateControl=y
CpuRate=1
CpuLimit=1
MemoryLimitMb=256
```

**Comment by Kizuno18** [comment]
oh, I knew I shouldn't have trusted the configuration suggestions that the
gpt chat gave me 😰
Thanks for The information, in additional, let me ask, already have plans
to the rate cpu limit feature?

**Comment by DavidXanatos** [comment]
emmm.... There is no way to CPU rate limit in user mode, and we cant manipulate the kernel that much eider due to windows patch guard.
So this feature is not possible.

But you can use the CPU affinity option to limit processes in a sandbox to a selected count of cores, so its the next best thing to rate limiting and on modern systems with 8+ cores it gives you a 12% cpu granularity that should be good enough
