### ISSUE TITLE
installed program

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [sandboxie-plus/Sandboxie#4139]
### Is your feature request related to a problem or use case?

unable to instal a software in a senbx in early installed on the host because the installer detect host installation

### Describe the solution you'd like

possibility to hide installed program and services on host from sandboxed program

**Comment by love-code-yeyixiao** [comment]
Try Privacy Mode.
`UsePrivacyMode=y`

**Comment by SK-9906** [comment]
this doen't work:
<img width="960" alt="{FBAF300A-17B9-41B2-A48C-701EFC1EDEB0}" src="https://github.com/user-attachments/assets/0959da2d-3646-45e2-9a62-71b5d087b7cb">

**Comment by DavidXanatos** [comment]
the HKLM/SOFTWARE key is not hidden and C:\Program Files isn't eider,
you could set up manual rules to hide some selected keys, boldly hiding HKLM/SOFTWARE would break everything

**Comment by offhub** [comment]
```ini
WriteKeyPath=*\Software*\Microsoft\Windows\CurrentVersion\Uninstall\*
```
