### ISSUE TITLE
B.A.S.E. game launcher crashes upon startup

### ISSUE THREAD

**Issue by Jimmi212** [sandboxie-plus/Sandboxie#4148]
### Describe what you noticed and did

When I want to open the program through sandboxie, it does not open and this inscription appears:
![IMG_20240812_145854_263](https://github.com/user-attachments/assets/de930e19-f90d-4047-b55d-0a60c3c095d8)

https://github.com/user-attachments/assets/27f03c62-6152-46ed-b40c-f326d4b786b1

### How often did you encounter it so far?

The game launcher was updated on 08/06/2024, before that everything was working fine

### Expected behavior

I want the launcher to open and open multiple windows

### Affected program

No

### Download link

No

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did, but I don't know how to attach the .dmp file(s).

### Crash dump

 Official site: https://baseplatform.online/royalquest

### What version of Sandboxie are you running now?

Sandboxie plus 1.14.6 64 bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

No

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Win 10 pro 22h2

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Microsoft Defender 

### Did you previously enable some security policy settings outside Sandboxie?

No

### Trace log

I don't see SBIE2224 error

### Sandboxie.ini configuration

```ini
## Sandboxie configuration file
#
[GlobalSettings]
[UserSettings_08DA01C0]SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=yBoxGrouping=:DefaultBox,New_Box
[DefaultBox]
Enabled=yBlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttlTemplate=OpenBluetooth
Template=SkipHookTemplate=FileCopy
Template=qWaveTemplate=BlockPorts
Template=LingerProgramsTemplate=AutoRecoverIgnore
ConfigLevel=10
[New_Box]Enabled=y
BlockNetworkFiles=yRecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetoothTemplate=SkipHook
Template=FileCopyTemplate=qWave
Template=BlockPortsTemplate=LingerPrograms
Template=AutoRecoverIgnoreConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=yAutoRecover=y
```

**Comment by offhub** [comment]
Could you please provide the name of the game launcher and an official link to download it?

> List of crash dump locations to check out:
>  - C:\\Users\\%Username%\\AppData\\Local\\CrashDumps
>  - C:\\Windows\\Minidump
>  - C:\\Sandbox\\%User%\\DefaultBox\\user\\current\\AppData\\Local\\CrashDumps
>  - C:\\Sandbox\\%USER%\\%SANDBOX% (only if you previously set EnableMiniDump=y in the sandbox section of your Sandboxie.ini file)
>  - C:\\Windows\\MEMORY.DMP (known as %SystemRoot%\\MEMORY.DMP)

> Tip: You can upload the .dmp file(s) on a file storage service, then share the resulting link below.

**Comment by Jimmi212** [comment]
Yes, the game is called Royal Quest, here is the official site: https://baseplatform.online/royalquest

**Comment by offhub** [comment]
Does the launcher open after adding the following setting to your configuration?

```ini
WriteFilePath=BASE.exe,%ProgramData%\B.A.S.E\*
```

**Comment by Jimmi212** [comment]
Sorry for the confusion, should I add this to the Sandboxie.ini file, if so it doesn't work unfortunately
