### ISSUE TITLE
Snapshot question: "The system cannot find the path specified."

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#415]
v0.5.5 & v5.46.4

Trying to understand snapshots..

Are snapshots meant to be partially immutable? After I create a snapshot, I can't create files in the sandbox. Example:
* new sandbox
* start sandboxed command prompt. 
* Create c:\test
* cd \test
* Create a file, eg: dir > t1
* exit command prompt
* create snapshot
* start sandboxed command prompt
* cd \test
* dir
* (ok. lists file t1)
* dir > t2
* Error prompt "The system cannot find the path specified."

However, I can create another directory, eg, "test2" and add a file to that.

Why?

**Comment by DavidXanatos** [comment]
no that's a bug while the snapshot itself should be immutable all files within it from the view point of a sandboxed application should be over writable by creating a copy in the current state

**Comment by DavidXanatos** [comment]
will be fixed in tn next build

**Comment by typpos** [comment]
Works in v0.6.0.
