### ISSUE TITLE
Sandboxie-Plus > Create New Box Dialog: Issues & Suggestions [Priority: low]

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#417]
v0.5.5

Low priority!

1. Title bar: "Sandboxie-Plus - Create New Box" not "SandboxiePlus new box".
2. Title bar: Remove dead "?" help button
3. Windows Task bar: Don't show window icon for modal dialog
4. Fix height. Allow only width resizing. (just like "take snapshot" dialog)
5. Move all controls to far left and fix left position. They move inward and space out awkwardly when horizontally resized.
6. Combine Template dropdown with Existing Box dropdown to save user an extra click and remove clutter. Dropdown can start with "Template: Default", "Template: Hardened", "Template: Legacy Sandboxie Settings", and then if at least one sandbox exists: "-- separator bar --", "MyBox1", "MyBox 2",...
7. "Legacy Sandboxie Behaviour" instead of "Legacy (old sbie..)"
8. Pre-fill box name with an unused name, eg, "New Box" "New Box 01" "New Box 02" ...
9. Show dialog centered to parent window, instead of remembering last open position
10. Fix tab order
11. Keep it in front of main window if "always on top"
12. Change "Enter a name for the new box" to "Sandbox Name". Generally don't give instructions in labels.
13. In dropdown list of sandboxes, provide correctly capitalized and ordered list of sandbox names.
14. On successful close and creation of sandbox, select the new sandbox in the main window and scroll to be visible

**Comment by DavidXanatos** [comment]
1. fixed
2. fixed
3. I'll leave it in there as all the Qt native mesageboxes also have the icon
4. ok
5. ok
6. no i like it like this with the radio buttons
7. ok
8. ok
9. ok
10. ok
11. ok
12. ok
13. ok
14. ok

**Comment by typpos** [comment]
All good!

Are these fine-grain items actually useful for you? They're mostly straight off check lists, but I'm not sure if you're focusing on quality UI or rather other more core dev stuff?

Re 3.: Fine. (FYI - this creates a few small inconsistencies with app focus, for example, a single ALT-TAB does not change away from Plus because main window is second in line, can't be focused, so flips back to dialog. [no need to respond; only fyi)
