### ISSUE TITLE
Cannot start outside of Sandboxie-Classic-x64-v5.46.4.exe

### ISSUE THREAD

**Issue by BilleBarrett** [sandboxie-plus/Sandboxie#418]
After upgrade to v5.46.4 I cannot start program outside of Sandboxie dropped back to previous version and I can
i.e. right click on Chrome & click on run sandbox is missing

**Comment by ImSpecial** [comment]
Not sure if we have any 54+ year IT techs that can help you here...

**Comment by aephlux** [comment]
I ran into similar issue but managed to fix it. 

Right click sandboxie control, show window
Go to configure, windows shell intergration
Run sandbox action, uncheck/check > add right click action "Run sandboxed" to files and folders
click OK.

**Comment by mm36** [comment]
After I install 5.46.4 not only the context menu "run sandboxed" disappeared. It can not auto start when windows boot up.
Please bring back these features.

**Comment by BilleBarrett** [comment]
I just checked on a new install, at 1st it was not there and then I followed you instructions and the Sandboxie Web Browser appear and it was there on the right click of Chrome

Thanks you

Bill

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
This is my reply mail signature

"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by NewKidOnTheBlock** [comment]
5.46.4 user here.
Context menu is alive and well.

Did you try uninstalling and re-installing 5.46.4?
* Make a backup of your C:\Windows\Sandboxie.ini first to be sure

**Comment by mm36** [comment]
Problems solved.

Thank You.

**Comment by APMichael** [comment]
Just to be sure: Was the report closed because the previous post read "Problems solved" or because the issue was fixed?

There is a bug in the setup of the Classic version 5.46.4. With a clean reinstallation (with previous uninstallation) certain registry values are no longer set (autostart, context menu).

Therefore you have to start "Sandboxie Control" manually from the start menu and then just click OK under "Configure" > "Windows Shell Integration". Afterwards everything is entered correctly in the registry again.

All previous versions always opened "Sandboxie Control" after installation and set the registry values automatically.

**Comment by BilleBarrett** [comment]
It would seem that I follow the recommendation of config > Windows Shellintergration and make sure all boxes are checked

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891
"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/
