### ISSUE TITLE
ClosedKeyPath block everything inside sandbox

### ISSUE THREAD

**Issue by Lukak9876** [sandboxie-plus/Sandboxie#4230]
### Describe what you noticed and did

I want to close reading at the following KeyPah : HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\*
Because I want to recreate Edge policies but in the sandbox : HKEY_USERS\Sandbox_USER_Test\machine\software\policies\microsoft\Edge
And when I use ClosedKeyPath=msedge.exe,HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\* it blocks the path outside and inside the sandbox. Is there a way to block the KeyPath of the local machine and only consider the path present in the sandbox ?

### How often did you encounter it so far?

Always

### Expected behavior

Block the precise path, only outside the sandbox

### Affected program

Edge

### Download link

Not revelant

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie v5.69.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 10

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

-

### Did you previously enable some security policy settings outside Sandboxie?

-

### Sandboxie.ini configuration

```ini
I can't share the sandboxie.ini
```

**Comment by offhub** [comment]
Use `WriteKeyPath`

**Comment by offhub** [comment]
See [WriteKeyPath](https://sandboxie-plus.github.io/sandboxie-docs/Content/WriteKeyPath/)
