### ISSUE TITLE
Opening a program in several sandboxes at once

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#4231]
### Is your feature request related to a problem or use case?

[Jim28 proposes](https://forum.xanasoft.com/threads/opening-a-program-in-several-sandboxes-at-once.2579/)
> to add the ability to open a program in several sandboxes at once.
For example, by dragging the shortcut of the desired program onto the sandbox group icon.

### Describe the solution you'd like

Being able to start a program simultaneously in several sandboxes.

The proposal mentions drag and drop onto a group. It could be done by modifying the dialog that appears when "run sandboxed" is selected from the shell menu, where one may select more than one box, while pressing the CTRL key. Maybe there are other ways to make that work easily.

Edit:  The requestor does not have a preference, considering the example he has given and what I added. Arguably, they don't have to exclude each other.

**Comment by DavidXanatos** [comment]
I don't like this, why not create a *.cmd file which wold once dropped upon open the doped program in a list of pre configured boxes?

**Comment by DavidXanatos** [comment]
Will be added by enabling box picker to do multi selection when holding down ctrl in the next build
