### ISSUE TITLE
"ForceDisableAdminOnly" is weird

### ISSUE THREAD

**Issue by showgot** [sandboxie-plus/Sandboxie#4233]
### Describe what you noticed and did

My account is administrators
![001](https://github.com/user-attachments/assets/4d08c07f-7411-4d34-b5ba-7432bdadb162)

If `[GlobalSettings]
ForceDisableAdminOnly=y`
"Run Outside Sandbox" is disappear on select box window（ctrl+shift is work）
![002](https://github.com/user-attachments/assets/df6b6174-bfc6-4568-8c99-3847ed6b9a7f)

unless set "Start.exe" to run as an administrator
![003](https://github.com/user-attachments/assets/6e92b24e-4127-4a7b-9c3d-34380e9a5a11)

I think this happened after 5.68.7
Did I do anything wrong?

### Expected behavior

I want "Run Outside Sandbox" get back

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

sandboxie classic x64 5.69.8

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

windows 10 19044.4780

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

nothing

**Comment by offhub** [comment]
With version `1.14.1/5.69.1`, Sandboxie now checks if the requesting application runs with administrative privileges in addition to being part of the Administrators group. I don't know if this is a change made intentionally.

**Comment by DavidXanatos** [comment]
this was not intentioanl will be fixed in next build
