### ISSUE TITLE
There was a problem using Bilibili UP's self-developed software

### ISSUE THREAD

**Issue by PoisonGZ** [sandboxie-plus/Sandboxie#4237]
### Describe what you noticed and did

The following message appeared when I used SandboxiePlus to run the software after I downloaded it
![image](https://github.com/user-attachments/assets/26971fdd-74aa-47d5-853f-37266e7d21f4)
Since the software is relatively large, I can only provide the link to download the software directly
![image](https://github.com/user-attachments/assets/8ebc43e5-2694-4596-9dc8-46d7916d99e4)

Url：https://pan.baidu.com/s/1G_uXeoLWOVArUtYG7-TQqg?pwd=6666 
url Password：6666
7z Password：bilibili-秋葉aaaki
Sorry, because my English is poor, so I used the translation tool to post this question

### How often did you encounter it so far?

Every time

### Expected behavior

Normal operation will not have this prompt, will go directly to the software

### Affected program

StableDiffusionWebUILauncher.exe

### Download link

Url：https://pan.baidu.com/s/1G_uXeoLWOVArUtYG7-TQqg?pwd=6666  url Password：6666 7z Password：bilibili-秋葉aaaki

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.14.8

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 22631.4169

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

There is no

**Comment by PoisonGZ** [comment]
![image](https://github.com/user-attachments/assets/eefdd284-2e06-42dd-8277-e42da32998d6)
It looks like the software uses relative paths to access folders in its own directory, but SandboxiePlus directs the folders to sandboxiePlus's own directory

**Comment by offhub** [comment]
Create a shortcut (or sandboxed shortcut) to the program and set the "Start In" value to the program's directory.

**Comment by PoisonGZ** [comment]
Thanks for your help, the program is now running normally with your help
