### ISSUE TITLE
Blurry apps when sandboxed

### ISSUE THREAD

**Issue by Ailbeenlynd** [sandboxie-plus/Sandboxie#4239]
### Describe what you noticed and did

Apps are crisp and clear when unsandboxed or when forced to always run in sandbox, but when using context menu (right click) to sandbox an app or when using "Run Sandboxed from Start menu", or when a forced-sandboxed app starts another instance of itself, the app window becomes all blurry. I am running at 225% DPI in windows display settings (4K monitor). none of the programs tested have compatibility DPI set. This affects programs installed inside and outside sandbox.

### How often did you encounter it so far?

every time

### Expected behavior

Windows apps should appear crisp like when unsandboxed

### Affected program

all windows programs (firefox, notepad, etc)

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

5.69.8

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

I only reproduced it with Sandboxie Classic.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 21H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

None

**Comment by Ailbeenlynd** [comment]
Interestingly, I seemed to have fixed it by stopping SbieSvc.exe (sc stop sbiesvc) and then setting and unsetting DPI compatibility for SbieSvc.exe, Start.exe, and SbieCtrl.exe. Now it's no longer blurry. The setting/unsetting might have reset some Windows internal states relative to sandboxed apps or the Sandboxie executables.

**Comment by Ailbeenlynd** [comment]
So DPI is still messed up (blurry) when an executable opens another instance of itself or opens another executable -- the secondary execution is blurry. So there's perhaps still an issue to be looked into.

**Comment by DavidXanatos** [comment]
does anyone else has this issue?

**Comment by Ailbeenlynd** [comment]
This may not be a Sandboxie issue. I think what happened was that I set some of the Sandboxie .exes to system enhanced DPI setting at one point (because the classic window is too small on a high res monitor), and they were not cleared properly by Windows. Whenever an app was initiated by those .exes (e.g., Start.exe) they inherited the altered DPI setting (blurry). "Forced programs" were started differently (by driver?) and were crisp. Clearing DPI settings for Sandboxie's .exes in Windows file properties fixed this issue.
