### ISSUE TITLE
Sandboxie-Plus: "Failed to recover some files" when quick recovery, legacy build is OK

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#424]
![1](https://user-images.githubusercontent.com/56181919/105275646-baf8f800-5b97-11eb-8b8f-5459e818bb09.PNG)
I did the same operation in legacy build (immediate recovery), it worked well. 
By the way, I think the description in plus build is ambiguous. When I save a *.doc file in sandbox, plus build pop up "quick recovery" immediately, legacy build is "immediaty recovery". I think "immediaty recovery" is more appopriate.

**Comment by DavidXanatos** [comment]
is teh issue still present in 0.6.5? i fixed a resovery related bug ther which may have been responsible for this to

**Comment by 0x391F** [comment]
> 
> 
> is teh issue still present in 0.6.5? i fixed a resovery related bug ther which may have been responsible for this to

Yes, it is.

**Comment by r4taw2mg** [comment]
Have you tried closing the file before recovering? I've had some cases where the recovery failed on open files.

**Comment by 0x391F** [comment]
> 
> 
> Have you tried closing the file before recovering? I've had some cases where the recovery failed on open files.

Yes. 
-------------------------
I did a test: 

Legacy build:
Immediate recovery (sandboxed programs still running): success
Quick recovery (sandboxed programs has been terminated): success

Plus build:
Immediate recovery (the sandboxed programs still running): failed
Quick recovery (sandboxed programs has been terminated): success

**Comment by DavidXanatos** [comment]
Is the issue stil present in the 1.0.x builds?

**Comment by DavidXanatos** [comment]
the latest build fixed somethign recovery related is the issue still presetn for you?

**Comment by 0x391F** [comment]
> the latest build fixed somethign recovery related is the issue still presetn for you?

Yes, it is.

**Comment by DavidXanatos** [comment]
since i fail to reproduce this, could you please upload a video demonstrating the issue such that i have a step by step instruction to follow
