### ISSUE TITLE
Add "Description" field inside the sandbox settings

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#4243]
### Is your feature request related to a problem or use case?

[Gaiko suggests adding](https://forum.xanasoft.com/threads/add-description-field-inside-the-sandbox-settings.2593/) a field for user notes in the sandbox settings.

### Describe the solution you'd like

Some place for the user to leave notes to himself or those that are supposed to use the box.

Since there is a limit how many lines the sandboxie.ini can contain, either there has to be a limit or it could be stored in some other file, like the sandboxie-plus.ini

### Describe alternatives you've considered

It's not my idea, but I see how it can be useful, to note: "I enabled setting X to test Y, remember to revert it." or "This box is just for testing..."

**Comment by Vstory** [comment]
good idea
