### ISSUE TITLE
[Feature Recovery] File recovery log

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#425]
![1](https://user-images.githubusercontent.com/56181919/105281714-a707c300-5ba4-11eb-8728-12b6843f8ca3.PNG)

**Comment by DavidXanatos** [comment]
whats the use case for this?

**Comment by bastik-1001** [comment]
Maybe the use case is not being sure if all files have been recovered and using that window as an overview. I am not saying that this is the intended usage for that function.
