### ISSUE TITLE
"Reset columns" doesn't work; Add "Resize log list columns to fit contents" [Priority: low]

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#426]
![1](https://user-images.githubusercontent.com/56181919/105335347-dbdd3f80-5bcf-11eb-86b3-808c017ac4a0.PNG)
![2](https://user-images.githubusercontent.com/56181919/105335358-ded83000-5bcf-11eb-8ea6-e13b3e7518cc.PNG)

**Comment by bastik-1001** [comment]
The "Reset column" function selects the default columns, which are all in that case. For me it works, When I deselect one or more and then click on "Reset column" all of them are shown again.

**Comment by DavidXanatos** [comment]
> 
> 
> The "Reset column" function selects the default columns, which are all in that case. For me it works, When I deselect one or more and then click on "Reset column" all of them are shown again.

that's the plan, so I can close this one, all's fine

**Comment by bastik-1001** [comment]
The original author of this ticket/issue also asked to add a function to resize the columns to fit the content of them. That sounds like a feature request to me.
