### ISSUE TITLE
Sandboxed Firefox causes WIFI connection disconnect

### ISSUE THREAD

**Issue by CaliSunUSA** [sandboxie-plus/Sandboxie#4278]
### Describe what you noticed and did

After latest update to Release v1.14.9, when using Firefox inside Sandboxie, USB WIFI permanently Looses connection . It happens anywhere between 2-10 minutes of use. When I run Firefox outside of Sandboxie, there is no connection issue at all. 

System info:
Firefox 131.0 (64-bit)
Windows 10 Pro 22H2 64-bit
USB WIFI Info:
![2024_10_01_22_05_02_Window](https://github.com/user-attachments/assets/9d9875c2-6c2e-41af-a20b-a75192c62ed4)

### How often did you encounter it so far?

every time

### Expected behavior

no connection issue

### Affected program

Firefox 131.0 (64-bit)

### Download link

N/A

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Release v1.14.9

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### Is it a regression from previous versions?

Release v1.14.9

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Avast

### Did you previously enable some security policy settings outside Sandboxie?

N/A

**Comment by offhub** [comment]
What was the previous version you used?

**Comment by CaliSunUSA** [comment]
I upgraded from v1.14.8

**Comment by CaliSunUSA** [comment]
I can confirm that this only happens with USB Based WIFI card on my desktop.
Build-in WIFI card on my laptop does not experience any issues.

**Comment by CaliSunUSA** [comment]
This morning I upgraded to v1.14.10
So far, so good.

**Comment by CaliSunUSA** [comment]
Closing as this issue has not returned.
