### ISSUE TITLE
Deleting content from box fail with multiple users accounts

### ISSUE THREAD

**Issue by Ouro17** [sandboxie-plus/Sandboxie#4288]
### Describe what you noticed and did

1. Create 2 local accounts users in windows (User A and B)
2. Install sandboxie
3. On one user(A for example), use the defaultbox
4. log out user A and switch to the other user B
5. On B, use the default box
6. Try to delete the content of default box, it will fail
![Screenshot_2](https://github.com/user-attachments/assets/2f92592f-5b7e-4913-a38d-7a440f445322)
![Screenshot_1](https://github.com/user-attachments/assets/8fcb748f-2bf9-4041-86b9-ee00c795b2f2)

8. Switch back to user A
9. Delete content on user A default box, it will work
![Screenshot_3](https://github.com/user-attachments/assets/fbaadd4e-98d7-4042-98f6-a715f9b9ff1c)
![Screenshot_4](https://github.com/user-attachments/assets/7fa93d3f-1e35-4e59-83bf-75ca21bb52c1)

The **??** in front of the folders seems rather suspicious to me.
Does any one else has the same issue?

### How often did you encounter it so far?

Whenever the user that is not the first logging in the computer tries to delete contents from any boxes

### Expected behavior

The content of the box should be deleted

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus v1.14.10

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 Pro 64 bits

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator).

### Please mention any installed security software

Microsoft Defender Antivirus

### Sandboxie.ini configuration

```ini
[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
DropAdminRights=y
ClosePrintSpooler=y
UseFileDeleteV2=y
UseRegDeleteV2=y
ProcessGroup=<system>,rundll32.exe,dllhost.exe
ProcessGroup=<FirefoxServices>,RuntimeBroker.exe,CompPkgSrv.exe
ProcessGroup=<Browsers>,firefox.exe,chrome.exe
ProcessGroup=<StartRunAccess>,<system>,<FirefoxServices>,<Browsers>,explorer.exe
ProcessGroup=<InternetAccess>,<Browsers>
ClosedIpcPath=!<StartRunAccess>,*
AutoRecover=y
SandboxieLogon=y
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
NeverRemove=y
ForceProcess=<Browsers>
RunCommand=Firefox|firefox.exe
RunCommand=Chrome|chrome.exe
```

**Comment by camheelio** [comment]
I have the same problem with only one user. It happens since the update to 1.14.10, which was parallel with the Windows 11 Update 24H2 (26100). Sandboxie drop this error when trying to empty the sandbox from UI or when the content should be automatically deleted. First I though about access rights, but I can delete the sandbox folder from Explorer by hand without any problem and when I have done this, the automatically deletion works 2 or 3 times and then it happens again.

**Comment by APMichael** [comment]
I myself only use Windows 10 so far and the issue has never occurred there.

I guess it is caused by Windows 11, either by a recent update or by the feature upgrade 24H2.
(https://www.wilderssecurity.com/threads/sandboxie-plus-1-14-10.455134/#post-3211299)

Maybe @DavidXanatos can reproduce it in his VM and find out what caused it?

**Comment by offhub** [comment]
#4085, #4142

**Comment by Gishmasters** [comment]
I Think problem on this  moment - C:\Sandbox\%SANDBOX% - if rename %SANDBOX% to another name foe Example BOX1, and reboot then all works without problem. But after another reboot C:\Sandbox\BOX1 suddenly rename to C:\Sandbox\%SANDBOX%  and deleting is broke.

**Comment by Gishmasters** [comment]
So, i find the solution. 

#
# Sandboxie configuration file
#

[GlobalSettings]
Template=Edge_Fix
Template=NOD32
Template=OfficeClickToRun
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan
**FileRootPath=D:\Install\Sandboxie\Sandbox\%SANDBOX%** **this make by default**

[UserSettings_085201AC]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#027df7,off,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=Edge_Force
ConfigLevel=10
**FileRootPath=D:\Install\Sandboxie\Sandbox\%SANDBOX%**   **but this must to do manually -add this line and deleting works**
UseSecurityMode=y
UseFileDeleteV2=y
UseRegDeleteV2=y
ForceFolder=D:\Install\Sandboxie\Web
AutoDelete=y
AutoRecover=y

**Comment by Gishmasters** [comment]
Hello, **DavidXanatos**! Did you check this issue? Will it be resolve soon :))) Problem only on Win 11 24H2, and what interesting - if restart sandbox with admin rights - then no problem with sandbox emptying. But somethimes after pc rebooting problem appear again. So i think is some issue with right are present.

**Comment by Gishmasters** [comment]
I think found the solution. 

In global settings  - allow checkbox  :  run sandman ui with admin rights.

**Comment by Gishmasters** [comment]
> Another workaround is ticking the "Use volume serial numbers for drivers" in File Options.

Sadly to say, but it doesnt help. I hope **DavidXanatos** will solve this soon. I repeat that is actual for win11 24h2 users, on any other(23h2 or on win10) it doesnt happens.

**Comment by camheelio** [comment]
A working woraround is, to create an automated action (Advanced Options -> Triggers) when sandbox is terminated with the command:

`C:\windows\system32\cmd.exe /c rmdir /s /q [sandboxfolder]`

insert your sandbox path at the end (I have not tested if you can use the %SANDBOX% placeholder to make it working with different user-sandboxes; using environment variables like %WINDIR% is definitvely not working)
Then you should remove the check from "Auto delete content ..."
It will do technically the same as the option, removing the complete folder for this sandbox.

**Comment by Gishmasters** [comment]
Almost 2 months have passed, but still  To DO marker(((( Is any chanse that issue will resolve soon?
