### ISSUE TITLE
For versions > v1.14.1 / 5.69.1, http(s) proxy does not work for web browsers in the same sandbox

### ISSUE THREAD

**Issue by monetjoe** [sandboxie-plus/Sandboxie#4292]
### Describe what you noticed and did

I tried versions from 1.12.x to latest version and found that v1.14.1 / 5.69.1 is a boundary to divide this problem (v1.14.1/5.69.1 itself works)

### Expected behavior

Solve this problem in the latest version

### Affected program

Web browsers, http(s) proxy apps

### Download link

https://www.microsoft.com/en-us/edge/download

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.14.1+ / Sandboxie Classical 5.69.1+

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Win10 Edu 22H2 64Bit

### In which Windows account you have this problem?

A local account (Administrator)., Not relevant to my request.

### Please mention any installed security software

Huorong

**Comment by offhub** [comment]
1. **Open the Configuration File**  
   Navigate to `Options > Edit Templates.ini` to open the `templates.ini` file.

2. **Modify the RpcPortFilter Settings**  
   Locate the following lines and comment them out by adding a `#` at the beginning:

   ```ini
   #RpcPortFilter=WPAD,1,WinHttpResetAutoProxy
   RpcPortFilter=WPAD,2,AutoProxySaveProxyCredentials
   RpcPortFilter=WPAD,3,AutoProxyStoreSavedProxyCredentialsForClient
   RpcPortFilter=WPAD,4,AutoProxyDeleteSavedProxyCredentials
   #RpcPortFilter=WPAD,5,AutoProxyReindicateAllProxies
   #RpcPortFilter=WPAD,6,ReadProxySettingsInternal
   RpcPortFilter=WPAD,7,WinHttpWriteProxySettings
   RpcPortFilter=WPAD,8,WinHttpSetProxySettingsPerUser
   #RpcPortFilter=WPAD,9,WinHttpConnectionUpdateIfIndexTable
   RpcPortFilter=WPAD,10,WinHttpConnectionSetPolicyEntries
   RpcPortFilter=WPAD,11,WinHttpConnectionDeletePolicyEntries
   ```

3. **Save Your Changes**  
   After editing, be sure to save the `templates.ini` file.

4. **Reload the Configuration**  
   To apply the changes, go to `Options > Reload configuration`.

5. **Verify Functionality**  
   Check if the changes are working as intended by testing your proxy settings or functionality in Sandboxie.

**Comment by monetjoe** [comment]
> 1. **Open the Configuration File**
>    Navigate to `Options > Edit Templates.ini` to open the `templates.ini` file.
> 2. **Modify the RpcPortFilter Settings**
>    Locate the following lines and comment them out by adding a `#` at the beginning:
>    ```ini
>    #RpcPortFilter=WPAD,1,WinHttpResetAutoProxy
>    RpcPortFilter=WPAD,2,AutoProxySaveProxyCredentials
>    RpcPortFilter=WPAD,3,AutoProxyStoreSavedProxyCredentialsForClient
>    RpcPortFilter=WPAD,4,AutoProxyDeleteSavedProxyCredentials
>    #RpcPortFilter=WPAD,5,AutoProxyReindicateAllProxies
>    #RpcPortFilter=WPAD,6,ReadProxySettingsInternal
>    RpcPortFilter=WPAD,7,WinHttpWriteProxySettings
>    RpcPortFilter=WPAD,8,WinHttpSetProxySettingsPerUser
>    #RpcPortFilter=WPAD,9,WinHttpConnectionUpdateIfIndexTable
>    RpcPortFilter=WPAD,10,WinHttpConnectionSetPolicyEntries
>    RpcPortFilter=WPAD,11,WinHttpConnectionDeletePolicyEntries
>    ```
> 3. **Save Your Changes**
>    After editing, be sure to save the `templates.ini` file.
> 4. **Reload the Configuration**
>    To apply the changes, go to `Options > Reload configuration`.
> 5. **Verify Functionality**
>    Check if the changes are working as intended by testing your proxy settings or functionality in Sandboxie.

Ok, I tested it just now, it works now, issue closed

**Comment by DavidXanatos** [comment]
Whats the issue exactly, what does "proxy does not work for web browsers in the same sandbox" you mean when you have the proxy running sandboxed and it want to change global proxy settings?

**Comment by monetjoe** [comment]
> Whats the issue exactly, what does "proxy does not work for web browsers in the same sandbox" you mean when you have the proxy running sandboxed and it want to change global proxy settings?

When both proxy app and web browser are in the same sandbox <= v1.14.1, if users run the proxy, their broweser IPs will be successfully changed by the proxy app. However, this function does not work for versions > v1.14.1 because the default template.ini has been updated, users with the above requirement have to manually modify the template.ini after updating their sandboxie to versions > v1.14.1 to keep that function working.

@offhub had told me how to modify the template.ini to solve this problem in the previous response, this issue was closed by me but then reopened by @isaak654

**Comment by isaak654** [comment]
The problem with editing the Templates.ini file is that with each subsequent version of Sandboxie you will have to constantly reapply the workaround [here](https://github.com/sandboxie-plus/Sandboxie/issues/4292#issuecomment-2408525813), so I wonder if there is a more reliable solution.

**Comment by monetjoe** [comment]
Hi, this bug has reappeared for a long time after ≈v1.16. But commenting RpcPortFilters out in the Templates.ini does not work at this time. Could you please give us an alternative solution? @bastik-1001 @DavidXanatos @offhub

**Comment by offhub** [comment]
@monetjoe Have you tried adding `OpenWPADEndpoint=y` to the affected sandbox? This disables WPAD filtering and may restore proxy functionality. Also, could you verify whether it works with earlier Sandboxie versions? The issue may be related to a Windows-side change.

**Comment by monetjoe** [comment]
> [@monetjoe](https://github.com/monetjoe) Have you tried adding `OpenWPADEndpoint=y` to the affected sandbox? This disables WPAD filtering and may restore proxy functionality. Also, could you verify whether it works with earlier Sandboxie versions? The issue may be related to a Windows-side change.

`OpenWPADEndpoint=y` does not work. If you use v1.14.1-, there will be no need to change Templates.ini to let proxies work. If you update v1.14.1 to v1.14.1+ by covering installation, proxies may work after modifying RpcPortFilter in Templates.ini. If you directly install latest version in a clean path rather than update to the latest version, no matter how you change Sandboxie.ini or Templates.ini, proxies will never work.
