### ISSUE TITLE
Sandboxie-Plus breaks Windows in-place upgrade attempts and Windows Update

### ISSUE THREAD

**Issue by plofhaan** [sandboxie-plus/Sandboxie#4294]
### Describe what you noticed and did

On Windows 11 version 24H2 build 26100.2033 with Sandboxie-Plus 1.14.10, I tried to repair Windows with an in-place upgrade using the Windows Update method (i.e. as opposed to using the method to download and mount the official ISO file from Microsoft). The in-place upgrade couldn't proceed due to this error:
![Repair Windows 11 -- in-place upgrade](https://github.com/user-attachments/assets/253e4070-e941-4d90-a12e-2d2007992ccb)
Next, I closed the window shown in the above screenshot, and I let it clean up after itself before I manually uninstalled Sandboxie-Plus with the option to remove its config files and sandboxes. The uninstall went successful, but still didn't fix my issue, even after a reboot. I even tried portable Revo Uninstaller in Hunter mode to reinstall/uninstall Sandboxie-Plus to remove all leftover traces of Sandboxie-Plus (and rebooted after that). Whatever I do, any attempt to repair Windows with an in-place upgrade cannot get past the same exact screenshot shown above so, the only option is to close the window again to let it clean up after itself again. This also includes the method to download and mount the official ISO file from Microsoft, then choose to run Setup from there.

Another problem is that, during my first attempt to repair Windows with an in-place upgrade like how I described above, after I decided to close the window shown in the above screenshot, Windows Update broke. Now it looks like this:
![Windows Update error](https://github.com/user-attachments/assets/08a3e299-6ff1-4dbd-b3ab-cc277c78ed11)
Deleting the contents of the _C:\Windows\SoftwareDistribution\Download_ folder (and rebooting after) doesn't help, and neither does running the built-in Windows Update troubleshooter.

### How often did you encounter it so far?

Persistently with every attempt

### Expected behavior

After Sandboxie-Plus has already been completely uninstalled, it should not block Windows in-place upgrades in this manner.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.14.10

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression from previous versions?

No

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 version 24H2 build 26100.2033

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Windows Security (Defender)

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by offhub** [comment]
Last night, I started the repair process in the virtual machine using 'Repair Install Windows 11 via Windows Update,' and by morning, the repair was successfully completed. I didn’t encounter any errors related to Sandboxie either.

What did it say in the 'more information' section of the error?

`https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/#One`

![vmconnect_20241014_141639_655](https://github.com/user-attachments/assets/6e92153e-55f0-401c-830a-5b3306160ea6)

**Comment by misternop** [comment]
Why is this garbage application that runs in portable mode so garbage to leave all sorts of traces in windows that is so significant Microsoft prevents upgrade to windows 11 24h2?

How can this be called portable mode? Where are uninstall processes to remove all traces? Once I sort this out I will never install this garbage again. You have no clue what portable mode means.

**Comment by misternop** [comment]
To fix this problem I downloaded latest Sandboxie Plus x64 installer 1.14.10 and used revouninstaller to trace install then installed it / extracted it in portable mode where my old one was previously located. Then ran Sandboxie and in menu under maintenance used remove all then used RevoUninstaller to remove all other traces (which included some registry entries and some prefetch files and its own folder) and FINALLY windows has passed its check to upgrade to 24H2.

Note - just running older version that I had installed in portable mode and using maintenance remove all did not help on its own for whatever reason (possibly registry entries?) only after tracing with revouninstaller and extracting new version and doing above process it helped. Dunno if extracting to exact location old one was in was important but that's what I did.

**Comment by plofhaan** [comment]
@offhub 
I didn't click on the 'more information' link, but the repair update did have an error code 0xc1900209 in Update History to indicate that an incompatible app had prevented the in-place upgrade from being able to proceed.

As you know, 1.14.10 hadn't been released yet when 24H2 came out. I was still on 1.14.9 when I upgraded from 23H2 to 24H2 by using the Installation Assistant. This upgrade did not produce any errors nor any abnormalities besides the known issues that have already been acknowledged by MS (and this issue that relates to Sandboxie-Plus).

Sandboxie-Plus was/is installed by using the normal method, not the portable mode. Each time when I update Sandboxie-Plus to the latest version, I always just grab the installer from here, and let it perform the update by replacing the previous version. I do not run SandMan.exe. Instead, I only run SbieCtrl.exe (yeah, I know...). The Scan method that I used in Revo Uninstaller in Hunter mode was the Advanced method, and I let it remove any and all leftovers that it reported in the scan results.

Windows Update un-stuck itself automagically after letting the laptop sit idle for several hours. All the while, I periodically kept checking by running _explorer ms-settings:windowsupdate_ and closing the Windows Update window again each time until finally, at very long last, I saw that Windows Update had automatically started scanning for available updates immediately when the Windows Update window opened from running the command. After this scan was completed, the error in Windows Update was gone, and the failed repair update in Update History was gone also. This scan did not find any new available updates. I can confirms that Definition updates for Windows Security are now being downloaded an installed like normal again by Windows Update.

**Comment by plofhaan** [comment]
> To fix this problem I downloaded latest Sandboxie Plus x64 installer 1.14.10 and used revouninstaller to trace install then installed it / extracted it in portable mode where my old one was previously located. Then ran Sandboxie and in menu under maintenance used remove all then used RevoUninstaller to remove all other traces (which included some registry entries and some prefetch files and its own folder) and FINALLY windows has passed its check to upgrade to 24H2.
> 
> Note - just running older version that I had installed in portable mode and using maintenance remove all did not help on its own for whatever reason (possibly registry entries?) only after tracing with revouninstaller and extracting new version and doing above process it helped. Dunno if extracting to exact location old one was in was important but that's what I did.

When I run SandMan, there is no option to 'remove all' in the menu under Maintenance. With Revo Uninstaller in Hunter mode I re-installed/uninstalled Sandbxie-Plus 1.14.10 x64 using its installer with the same (default) install location, and did remove all traces that you mentioned. When I upgraded Windows to 24H2, it passed the check **without** complaing about Sandboxie-Plus (1.14.9).

**Comment by DavidXanatos** [comment]
Which entries were left according to Revo Uninstaller ?

**Comment by isaak654** [comment]
In my case:
```
C:\Users\Test\AppData\Local\Sandboxie-Plus\addons.json
C:\Users\Test\AppData\Local\Temp\qtsingleapp-sandma-xxxx-1-lockfile
C:\Users\Test\Desktop\Sandboxed Web Browser.lnk
C:\Users\Test\AppData\Local\Temp\sandboxie-updater
C:\Users\Test\AppData\Local\Temp\iu-14D2N.tmp\_unins.tmp
---
SBIE files in C:\Windows\Prefetch\:
KMDUTIL.EXE-xxxxxxxx.pf
SANDBOXIE-PLUS-X64-V1.14.10.E-xxxxxxxx.pf
SANDBOXIE-PLUS-X64-V1.14.10.T-xxxxxxxx.pf
SANDBOXIEDCOMLAUNCH.EXE-xxxxxxxx.pf
SANDBOXIERPCSS.EXE-xxxxxxxx.pf
SANDMAN.EXE-xxxxxxxx.pf
SBIESVC.EXE-xxxxxxxx.pf
START.EXE-xxxxxxxx.pf
UPDUTIL.EXE-xxxxxxxx.pf
```

**Comment by plofhaan** [comment]
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache | C:\Program Files\Sandboxie-Plus\SandMan.exe.ApplicationCompany - sandboxie-plus.com
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache | C:\Program Files\Sandboxie-Plus\SandMan.exe.FriendlyAppName - Sandboxie Manager
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache | C:\Program Files\Sandboxie-Plus\Start.exe.ApplicationCompany - Sandboxie-Plus.com
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache | C:\Program Files\Sandboxie-Plus\Start.exe.FriendlyAppName - Sandboxie Start
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\UFH\SHC | 14  - C:\ProgramData\Microsoft\Windows\Start  Menu\Programs\Sandboxie-Plus\Run any program sandboxed.lnk C:\Program  Files\Sandboxie-Plus\Start.exe /box:__ask__ run_dialog
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\UFH\SHC | 15  - C:\ProgramData\Microsoft\Windows\Start  Menu\Programs\Sandboxie-Plus\Run Web browser sandboxed.lnk C:\Program  Files\Sandboxie-Plus\Start.exe default_browser
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\UFH\SHC | 16  - C:\ProgramData\Microsoft\Windows\Start  Menu\Programs\Sandboxie-Plus\Sandboxie Start Menu.lnk C:\Program  Files\Sandboxie-Plus\Start.exe /box:__ask__ start_menu
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\UFH\SHC | 17  - C:\ProgramData\Microsoft\Windows\Start  Menu\Programs\Sandboxie-Plus\Sandboxie-Plus.lnk C:\Program  Files\Sandboxie-Plus\SandMan.exe
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store | C:\Program  Files\Sandboxie-Plus\SandMan.exe - 53 41 43 50 1 0 0 0 0 0 0 0 7 0 0 0  28 0 0 0 d0 97 32 0 98 5d 33 0 1 0 0 0 0 0 0 0 0 0 0 a 73 22 0 0 4b 73  49 d6 44 3 db 1 0 0 0 0 0 0 0 0 2 0 0 0 28 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0  20 0 0 0 0 0 0 0 0 0 0 0 59 32 7 0
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store | C:\Program  Files\Sandboxie-Plus\SbieCtrl.exe - 53 41 43 50 1 0 0 0 0 0 0 0 7 0 0 0  28 0 0 0 d0 f7 33 0 a5 d3 34 0 1 0 0 0 0 0 0 0 0 0 0 a 73 20 0 0 4b 73  49 d6 44 3 db 1 0 0 0 0 0 0 0 0 2 0 0 0 28 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  0 0 0 0 0 0 0 0 0 0 0 0 a 1c a e
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store | C:\Program  Files\Sandboxie-Plus\unins000.exe - 53 41 43 50 1 0 0 0 0 0 0 0 7 0 0 0  28 0 0 0 85 a6 32 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 a 0 21 0 0 4b 73 49  d6 44 3 db 1 0 0 0 0 0 0 0 0 2 0 0 0 28 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  0 0 0 0 0 0 0 0 0 0 47 93 0 0 0 0
HKEY_CURRENT_USER\Software\Xanasoft |  
HKEY_CURRENT_USER\Software\Xanasoft\Sandboxie-Plus |  
HKEY_CURRENT_USER\Software\Xanasoft\Sandboxie-Plus\SbieShellExt |  
HKEY_CURRENT_USER\Software\Xanasoft\Sandboxie-Plus\SbieShellExt\Lang |  
HKEY_CURRENT_USER\Software\Xanasoft\Sandboxie-Plus\SbieShellExt\Lang | Explore Sandboxed - Run &Sandboxed
HKEY_CURRENT_USER\Software\Xanasoft\Sandboxie-Plus\SbieShellExt\Lang | Open Sandboxed - Run &Sandboxed

C:\Users\username\AppData\Local\Sandboxie-Plus
C:\Users\username\AppData\Local\Sandboxie-Plus\Sandboxie-Plus.ini
C:\Users\username\Desktop\Sandboxed Web Browser.lnk
C:\WINDOWS\Prefetch\SANDBOXIE-PLUS-X64-V1.14.10.E-xxxxxxxx.pf
C:\WINDOWS\Prefetch\SANDBOXIE-PLUS-X64-V1.14.10.T-xxxxxxxx.pf
C:\WINDOWS\Prefetch\SANDBOXIE-PLUS-X64-V1.14.10.T-xxxxxxxx.pf
C:\WINDOWS\Prefetch\SANDBOXIE-PLUS-X64-V1.14.10.T-xxxxxxxx.pf
C:\WINDOWS\Prefetch\SANDBOXIE-PLUS-X64-V1.14.10.T-xxxxxxxx.pf
C:\WINDOWS\Prefetch\SANDMAN.EXE-xxxxxxxx.pf

**Comment by V6ser** [comment]
Still having the same problem on the latest version. I can't believe this, I'll try Revo Uninstaller as the OP said, I hope this works. I thought my system was corrupted or something...

**Comment by offhub** [comment]
After the upgrade fails, please share the relevant files from the following folder:

`C:\$WINDOWS.~BT\Sources\Panther`

- ActionableReport.html
- CompatData_*.xml
- *_APPRAISER_HumanReadable.xml
- *_APPRAISER_SetupOutput.xml
- *_APPRAISER_SetupOutputHw.xml
- *_APPRAISER_Migration.xml
- setupact.log
- setuperr.log
- ScanResult.xml

These files will help us identify which files or entries are causing the issue. Your assistance is greatly appreciated.

**Comment by Kronzky** [comment]
I am having a similar issue, with _Sandboxie Classic_ being complained about.
The thing is, that was uninstalled years ago, and there's no reference at all to sandboxie in the whole Registry. (Which means I can't remove it, and cannot proceed any further in the installation.)

![sandboxie](https://github.com/user-attachments/assets/a9ca97d4-e

[ScanResult.zip](https://github.com/user-attachments/files/18293997/ScanResult.zip)
b3e-4610-94b5-9bbc7b86e109)

**Comment by offhub** [comment]
@Kronzky Which version?

**Comment by offhub** [comment]
@Kronzky Probably one of the previous versions before it became open-sourced. (Sandboxie 5.33.3)

Even if the old version is not installed on the system, a shortcut pointing to a file from that version may also cause this error. My recommendation is to either remove the old files from previous versions from the system or archive them in a compressed file (zip or 7-zip).

**Comment by Kronzky** [comment]
It looks like it's not the Registry where Windows Update is getting its information from. It seems to scan your whole harddrive for apps it doesn't like.
Once I deleted my old Sandboxie folder, and told Windows Update to "rescan" it then proceeded to the next stage, and is installing Win11 right now (hopefully).

**Comment by offhub** [comment]
### If you're encountering issues during a Windows 11 24H2 upgrade, follow these steps to resolve potential conflicts with outdated Sandboxie files:

> [!WARNING]
> Don't forget to backup your Sandboxie configuration files.

1. If you have Sandboxie installed, update it to the [latest](https://github.com/sandboxie-plus/Sandboxie/releases/latest) version.
2. Remove<sup>1</sup> all files from versions **prior to 5.68.1 (Sandboxie Classic)** or **1.13.1 (Sandboxie Plus)**. This includes files such as:  
   - Individual files: `.exe`, `.dll`, `.sys`
   - Installer files: `Sandboxie-Classic-<version>.exe` or `Sandboxie-Plus-<version>.exe`  
   - Shortcut files that point to outdated files located in Windows user locations

3. Even if Sandboxie isn't currently installed, leftover files from older versions or extracted portable files can still cause issues during the upgrade. Make sure to remove<sup>1</sup> any files extracted to a folder for portable use as well.

4. After updating to the latest version and/or removing<sup>1</sup> the outdated files, try the Windows 11 24H2 upgrade again.

---

<sup>1</sup> Move the files to an archive file or delete them
