### ISSUE TITLE
Chome error messages

### ISSUE THREAD

**Issue by Hiche3** [sandboxie-plus/Sandboxie#43]
Sandboxie is throwing the following error messages when running Google Chrome:

SBIE2303 Could not hook CoGetObject (33, 1655)
SBIE2303 Could not hook RegisterDragDrop (33, 1655)
SBIE2318 DLL initialization failed for 'ole32.dll'

I haven't noticed any problems, and apparently this issue has been around for a while:
https://community.sophos.com/products/sandboxie/f/forum/115348/anyone-seeing-occasional-ole-init-hook-failed-errors-from-sandboxie#pi2151=1

**Comment by DavidXanatos** [comment]
same a https://github.com/sandboxie-plus/Sandboxie/issues/68 i thnk
