### ISSUE TITLE
The `codeium` `language_server_windows_x64` service does not start properly.

### ISSUE THREAD

**Issue by YuHuanTin** [sandboxie-plus/Sandboxie#4304]
### Describe what you noticed and did

When I start codeium in jetbrains with the new created sandbox, it starts a `language_server_windows_x64.exe` process, then it crashes after a while and codeium is disabled.

Editing the configuration file and deleting `UseFileDeleteV2=y` will make the **program work**, because of this, the **default** sandbox does not have this problem, whereas **new sandboxes** are created with this configuration item by default, which results in the error

### How often did you encounter it so far?

every time

### Expected behavior

This process normally provides functionality for codeium

### Affected program

WebStorm 2024.2.3 Build #WS-242.23339.15, built on September 25, 2024, com.codeium.intellij (1.22.4)

### Download link

Additional processes downloaded by codeium plugins

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Did the program or any related process close unexpectedly?

Yes, it did, but no .dmp file has been created in the system.

### What version of Sandboxie are you running now?

Sandboxie-Plus Version 1.14.9

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 LTSC 21H2 19044.4170

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Huorong

### Sandboxie.ini configuration

```ini
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
AutoRecover=y
UseFileDeleteV2=y
UseRegDeleteV2=y
MsiInstallerExemptions=y
```

**Comment by DavidXanatos** [comment]
Will be fixed in the next build it seams for whatever reason, language_server_windows_x64.exe issues a file rename operation with the same source and destination this broke our handling in delete v2, with delete v1 it worked because it does not handle host folder rename.

An other workaround would be to delete ```C:\Users\[user]\.codeium\database\9c0694567290725d9dcba14ade58e297\3\MODEL_EMBED_6591``` as then the the rename operation is box only.
