### ISSUE TITLE
Sandboxie plus can not work when the pc with Endpoint  Security software such as 360Safe 

### ISSUE THREAD

**Issue by qutmdsec** [sandboxie-plus/Sandboxie#431]
My Computer is Win7 x64,  have installed  the  QI-ANXIN Skylar Endpoint Security software . The SandMan push the Notice:
Start.exe(4064): SBIE2101 Object name not found: \WindowsErrorReportingServicePort, error AlpcConnectPort(C0000022) access=001F0001 initalized=1
PID 1188: SBIE2314 Canceling process Start.exe [4064 / 7]

**Comment by DavidXanatos** [comment]
Don't think I can fix that as I don't have "QI-ANXIN Skylar Endpoint Security" you could talk to the authors if they want to provide me with a free copy for testing...
