### ISSUE TITLE
Why is it not possible to run several MSI installers without errors?

### ISSUE THREAD

**Issue by anmac1789** [sandboxie-plus/Sandboxie#4330]
### Describe what you noticed and did

I have seen multiple problems with msi installers either on this forum and as well as my own personal tryouts with programs that use MSI installers. Why does it not work and/is are problematic ? what is the deep rooted issue with msi installers and sandboxie?

### How often did you encounter it so far?

everytime i use winzip, other msi installer programs

### Expected behavior

I expect all the programs to work correctly and install without errors

### Affected program

winzip, others, everything from voidtools

### Download link

1. https://www.winzip.com/en/pages/download/winzip/?lang=en&hd=Download%20Rar%20Opener%20Software%20with%20Ease
2. https://www.voidtools.com/Everything-1.4.1.1026.x64.msi
3. too many to list

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

Yes, it did, but I don't know how to attach the .dmp file(s).

### What version of Sandboxie are you running now?

Sandboxie Plus v1.14.10

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

latest Windows 10 x64 22H2

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator).

### Please mention any installed security software

malware bytes, windows defender

### Sandboxie.ini configuration

```ini
#
# Sandboxie configuration file
#

[GlobalSettings]
Template=7zipShellEx
Template=AdobeAcrobatReader
Template=OfficeClickToRun
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan
Template=Edge_Fix
DefaultBox=DefaultBox
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%

[UserSettings_0C700213]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
MsiInstallerExemptions=y
FakeAdminRights=y
BlockNetworkFiles=n
```

**Comment by isaak654** [comment]
#2699

**Comment by isaak654** [comment]
Not all MSI installers work in the same way and the lead maintainer currently does not know how to detect in real time when they fail in order to provide real-time corrections.

**Comment by anmac1789** [comment]
> Not all MSI installers work in the same way and the lead maintainer currently does not know how to detect in real time when they fail in order to provide real-time corrections.

then whats the point in making this software ?

**Comment by isaak654** [comment]
> then whats the point in making this software ?

Anyone can contribute to the source code. If you cannot wait and want some automation, it is better to look for other software or fork the repository to create a competing product.

**Comment by isaak654** [comment]
> then whats the point in making this software ?

Anyone can contribute to the source code. If you cannot wait and want further automation, it is better to look for other software or fork the repository to create a competing product.

**Comment by isaak654** [comment]
> then whats the point in making this software ?

Anyone can contribute to the source code. If you cannot wait and want further automation, you should look for other software or fork the repository to create a competing product.

**Comment by DavidXanatos** [comment]
At least winzip installs ok, there is a setting to improve msi installer compatibility

![image](https://github.com/user-attachments/assets/b445b17d-ca07-4622-b10a-7f1656832687)

Its not on by default as it reduces the level of isolation.

I see many users not finding this option, Perhaps we should add a automated warning message when an msi installer is run without that option, one that must be disabled per box.

**Comment by DavidXanatos** [comment]
see works just fine:

![image](https://github.com/user-attachments/assets/19c97781-aad5-46c7-bfc4-0a95a50d51dc)
