### ISSUE TITLE
The ability to allow sandboxed programs to burn removable storage devices.

### ISSUE THREAD

**Issue by love-code-yeyixiao** [sandboxie-plus/Sandboxie#4333]
### Is your feature request related to a problem or use case?

I helped a user without Github Account sumbit this issue.

The requested user tried using the following config:
DllSkipHook=user32.dll
DllSkipHook=msi.dll
DllSkipHook=gdi32full.dll
DllSkipHook=gdi32.dll
DllSkipHook=sxs.dll
DllSkipHook=shell32.dll
DllSkipHook=shcore.dll
DllSkipHook=userenv.dll
DllSkipHook=MsCorEE.dll
DllSkipHook=ntmarta.dll
DllSkipHook=ComDlg32.dll
DllSkipHook=acscmonitor.dll
DllSkipHook=winnsi.dll
DllSkipHook=Pdh.dll
DllSkipHook=sysfer.dll
DllSkipHook=emet.dll
DllSkipHook=snxhk64.dll
DllSkipHook=snxhk.dll
DllSkipHook=IDMIECC.dll
DllSkipHook=MsgPlusLive.dll
DllSkipHook=agcore.dll
DllSkipHook=advpack.dll
DllSkipHook=mso.dll
DllSkipHook=dwrite.dll
DllSkipHook=osppc.dll
DllSkipHook=winspool.drv
DllSkipHook=wevtapi.dll
DllSkipHook=winsta.dll
DllSkipHook=wtsapi32.dll
DllSkipHook=sfc_os.dll
DllSkipHook=d3d9.dll
DllSkipHook=imm32.dll
DllSkipHook=uxtheme.dll
DllSkipHook=zipfldr.dll
DllSkipHook=cfgmgr32.dll
DllSkipHook=setupapi.dll
DllSkipHook=sspicli.dll
DllSkipHook=pstorec.dll
DllSkipHook=wkscli.dll
DllSkipHook=netapi32.dll
DllSkipHook=iphlpapi.dll
DllSkipHook=ws2_32.dll
DllSkipHook=hnetcfg.dll
DllSkipHook=crypt32.dll
OpenIpcPath=\BaseNamedObjects_ComCatalogCache_
OpenIpcPath=\RPC Control\epmapper
OpenIpcPath=\RPC Control\LRPC*
OpenIpcPath=\RPC Control\OLE*
RpcMgmtSetComTimeout=n
OpenPipePath=*
NoSecurityIsolation=y
NoSecurityFiltering=y
OpenDevCMApi=y

to run a program named rufus.

### Describe the solution you'd like

According to him, Rufus started to fail when formatting the partition and began writing data to it. He hopes to add an option to allow the to fully burn the partition without having to disable so many security features.

**Comment by DavidXanatos** [comment]
that should be possible by just specifying the right openpipepath, the youser does not need to disable all these hooks just open tie right path to the volume

**Comment by e-t-l** [comment]
> just open the right path to the volume

Is there some documentation, either from Sandboxie or some other Windows resource, to instruct users how to identify pipe paths?
