### ISSUE TITLE
"Run Sandboxed" from the quick-previewer should have only one option

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#4339]
### Is your feature request related to a problem or use case?

"Run Sandboxed" from _here_ should not give many entries

![image](https://github.com/user-attachments/assets/e3e37240-abc1-4d1a-88f6-17aca44784c0)

### Describe the solution you'd like

Auto-run-sandboxed based on the "containing" sandbox

**Comment by stdedos** [comment]
_PS: Write your commits as "Fixes https://github.com/sandboxie-plus/Sandboxie/issues/4339", and it will auto-close_ 🎉

**Comment by DavidXanatos** [comment]
oh cool will try to do that in future is there a simmilar format for a feature request as its not a fix

**Comment by stdedos** [comment]
It can be also "Resolves": https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

(Here it speaks mostly of PRs, but it works with simple commits too)
