### ISSUE TITLE
one button to beat em all

### ISSUE THREAD

**Issue by Lazariseth** [sandboxie-plus/Sandboxie#434]
Please, Mr. Xanatos, we need a button to kill all processes in a selected sandbox next the API-Button on top.

Thank you and all the people very much for all the great work!

**Comment by DavidXanatos** [comment]
Why not use the context menu?

**Comment by bastik-1001** [comment]
@DavidXanatos I noticed that the menu on the top closes all processes in all sandboxes without warning or prompt, while the context menu of a sandbox closes all processes in a selected sandbox without warning or prompt. If you decide to add a button to close processes there should be an indication if that applies only to the selected sandbox or all of them.

**Comment by Lazariseth** [comment]
> @DavidXanatos I noticed that the menu on the top closes all processes in all sandboxes without warning or prompt, while the context menu of a sandbox closes all processes in a selected sandbox without warning or prompt. If you decide to add a button to close processes there should be an indication if that applies only to the selected sandbox or all of them.

Correct, and you can select different sandboxes to close it with this Button. For example, i only want to kill Sandbox 1, 3 and 5. Many Greets!

**Comment by DavidXanatos** [comment]
> 
> 
> > @DavidXanatos I noticed that the menu on the top closes all processes in all sandboxes without warning or prompt, while the context menu of a sandbox closes all processes in a selected sandbox without warning or prompt. If you decide to add a button to close processes there should be an indication if that applies only to the selected sandbox or all of them.
> 
> Correct, and you can select different sandboxes (at the same time - use ctrl) to close it with this Button. For example, i only want to kill Sandbox 1, 3 and 5. Many Greets!

again: Why not use the context menu?

I don't like buttons in the toolbar that apply only to selected items, selected items are what the context menu is for,
we are not on apple with only one mouse button.

@bastik-1001 I'll add a prompt for the user to confirm the termination

**Comment by Lazariseth** [comment]
Ahh i see, im sorry, its my misstake! Thanks!
