### ISSUE TITLE
sandboxie-Plus can't install MSI package

### ISSUE THREAD

**Issue by cisko99za** [sandboxie-plus/Sandboxie#4345]
### Describe what you noticed and did

i've tried with Sandboxie-Plus-x64-v1.15.1 and also Sandboxie-Plus-x64-v1.14.10 to install MSI package MasterPDFEditor-setup-x64.msi link to download is available here: https://code-industry.net/public/MasterPDFEditor-setup-x64.msi
![shot_01](https://github.com/user-attachments/assets/5d06f565-bbf1-4eb9-b2c0-eebe5e61fed8)

i've read some Issue pages here and tried to untick this option, but can't solve the issue
![shot_02](https://github.com/user-attachments/assets/786b35c4-2652-4eba-a00c-aed0357eca5f)

### Expected behavior

sandboxie start to install MSI but ended prematurely

### Affected program

Not relevant

### Download link

https://code-industry.net/public/MasterPDFEditor-setup-x64.msi

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus-x64-v1.15.1

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

windows 11 x64 23H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Defender AV

**Comment by cisko99za** [comment]
thanks for reply.
with the Troubleshooting Wizard i get error to open reg key (and installer roll back, so does not work)
![shot_01](https://github.com/user-attachments/assets/be0ba97e-0de1-4aa8-9e30-21d65cd2ce4c)
with `DropAdminRights=n` work fine, and i can install with this setting:
![shot_02](https://github.com/user-attachments/assets/61e3064b-441e-4252-aa98-859aa11689fb)
instead about that:
```
FakeAdminRights=y
MsiInstallerExemptions=y
```
idk how to edit these setting

**Comment by offhub** [comment]
If you've set it up through the user interface, there's no need to make changes in the configuration. You can also change the `MsiInstallerExemptions` and `DropAdminRights` settings after installation.

**UI**: (checked = y, unchecked = n)
- DropAdminRights = "Drop rights from ..."
    - FakeAdminRights = "Make applications ..."
- MsiInstallerExemptions = "Allow MSIServer ..."

**Config**:
Sandboxie-Plus > Right click on the sandbox > Sandbox Options > Edit Ini Section

**Comment by cisko99za** [comment]
yes, also solution to edit INI file work great.
a big thank you for your support.
solved issue
