### ISSUE TITLE
Can't open Firefox 84.0.2 in Sandboxie-Plus v. 0.5.5

### ISSUE THREAD

**Issue by mtag438** [sandboxie-plus/Sandboxie#435]
OS version: Windows 10 Home Edition (build 1904 - 10.0.18363)
Sandboxie version: Sandboxie-Plus-x64-v. 0.5.5
Firefox version: 84.0.2
Processor: AMD Ryzen 9 4900HS

First I checked for a new version of Sandboxie-Plus in the app. The version I had installed was v. 0.5.2. When I installed the upgrade I then tried to open Firefox v. 84.0.2 in Sandboxie-Plus. I right-clicked the existing sandbox and opened Firefox with the Run Program option in the drop-down menu. But when I did this I got the following error message:
<img width="576" alt="sandboxie-bug" src="https://user-images.githubusercontent.com/9435084/105570037-a0985900-5d14-11eb-8412-870c5950ca32.png">

Then I tried again by right-clicking the icon for the program and selecting Open in Sandbox but I ran into the same error again. Then I deleted the contents from the sandbox and tried to run Firefox but still couldn't open it in the sandbox.
Next, I uninstalled the app so I could do a clean install. I then tried to open Firefox in the sandbox but still ran into the same error.

Once I uninstalled v 0.5.5 and returned to 0.5.2 I was able to open Firefox in the sandbox again. 

What would cause this to happen?

**Comment by mtag438** [comment]
This is the sandboxie.ini.
```

[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=Windows10CoreUI
Template=7zipShellEx
TemplateReject=WindowsRasMan
TemplateReject=WindowsLive
TemplateReject=OfficeLicensing
TemplateReject=OfficeClickToRun
TemplateReject=FireFix_for_Win7

[DefaultBox]

Enabled=y
ConfigLevel=7
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl

[StreamWatch]

Enabled=y
ConfigLevel=7
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
CopyLimitKb=116551

[UserSettings_0D48022F]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_UserName=rotte
SbieCtrl_WindowCoords=200,150,1237,632
SbieCtrl_ActiveView=40021
SbieCtrl_NextUpdateCheck=1611976709
SbieCtrl_HideWindowNotify=n
SbieCtrl_ProcessViewColumnWidths=250,70,300

```

**Comment by mtag438** [comment]
[SxsTrace_mod.txt](https://github.com/sandboxie-plus/Sandboxie/files/5859759/SxsTrace_mod.txt)

**Comment by DavidXanatos** [comment]
That is strange on my systemit works just fine,
anyone else with that problem?

**Comment by bastik-1001** [comment]
Just to give feedback, for me Firefox 84.0.2 (installed into the system not the sandbox) works with Sandboxie Plus 0.5.5 (64bit on Windows 7). The browser runs in the sandbox I created for it, but also in others.

**Comment by LukeSeers** [comment]
I've just reinstalled windows so it's totally fresh with the latest sandboxie-plus and I'm also struggling to install firefox(Firefox 84.0.2)
![image](https://user-images.githubusercontent.com/16389426/105624963-b6457580-5e1d-11eb-8dd8-ced7b6b33f4d.png)

There is a work around which I use: https://portableapps.com/de/apps/internet/firefox_portable

**Comment by mtag438** [comment]
> That is strange on my systemit works just fine,
> anyone else with that problem?

Does it work after you update from a previous version of Sandboxie-Plus? That was when I first ran into the issue.

The first time it happened I also saw this in the console:

```
SBIE1411 Sandbox DefaultBox specifies unknown template Windows10CoreUI
SBIE1411 Sandbox StreamWatch specifies unknown template Windows10CoreUI
SBIE1411 Sandbox TemplateSettings specifies unknown template Windows10CoreUI

```

**Comment by NewKidOnTheBlock** [comment]
@mtag438 It looks to me like you have 2 Firefox installed:
One regularly and you are trying to install another copy of Firefox in Sandboxie on top.
This would result in your 2 Firefox profiles in Appdata\[User]\Mozilla competing against each other.

@LukeSeers Check this out.
You can grab the full Firefox installer here: https://www.mozilla.org/de/firefox/all/#product-desktop-release
Last I checked the full installer can be installed and run in Sandboxie (as long as you don't make it compete with a Firefox profile installed outside a sandbox).

**Comment by NewKidOnTheBlock** [comment]
> 
> 
> > That is strange on my systemit works just fine,
> > anyone else with that problem?
> 
> Does it work after you update from a previous version of Sandboxie-Plus? That was when I first ran into the issue.
> 
> The first time it happened I also saw this in the console:
> 
> ```
> SBIE1411 Sandbox DefaultBox specifies unknown template Windows10CoreUI
> SBIE1411 Sandbox StreamWatch specifies unknown template Windows10CoreUI
> SBIE1411 Sandbox TemplateSettings specifies unknown template Windows10CoreUI
> ```

Relevant: https://github.com/sandboxie-plus/Sandboxie/issues/413#issuecomment-763141546

**Comment by mtag438** [comment]
> @mtag438 It looks to me like you have 2 Firefoxes installed:
> One normally and another sandboxed copy on top.
> This would result in your 2 Firefox profiles in `%APPDATA%\Mozilla\Firefox\Profiles\` competing against each other.

Would it be possible to setup Sandboxie-Plus or Firefox so that it can distinguish between the two profiles? What I find strange is I never had this issue with the previous version of Sandboxie-Plus only the current one. I did reinstall and tried cleaning up the .ini file to see if that would help. Going to try and load Firefox again in 0.5.5 and see what happens.

**Comment by DavidXanatos** [comment]
Yea in future the deprecated template ehaders will be left in the templates ini and i have rea added teh removed once to the 0.6 release

any more problems or can i close this issue?

**Comment by mtag438** [comment]
@DavidXanatos Yeah Sandboxie-Plus is working now. I'll ask my question about Firefox and Sandboxie-Plus in a different post.

**Comment by marxenegls** [comment]
Check recovery for files first, 
Then delete the sandoxie's contents,
disable Firefox - meaning upgrade ff outside the  sandbox 
after the relaunch close up again, set enable ff sandboxie and launch  [-a deep clean and a new Firefox conf  basically] 

- it always fixed pretty much every issue i've had been using sandboxie over a decade

**Comment by marxenegls** [comment]
Did you pin firefox to taskbar or start menu? If you did so than using the same launch icon would cause the issue you've mentioned, even if you launched it from the drop-down start menu - i know this issue - every time it upgrades automatically, without me going through the procedure i mentioned earlier, the same issue would occur +/- broken paths and config etc i assume i never dug deep into it, because i never had to - anyways, why do i bother ? - it seems you don't any longer - i guess anyone else coming with a similar issue might use the hint - thank u - u'r more than welcome git ; )
