### ISSUE TITLE
[Sandboxie Classic] Window title starts blinking after running WSCC portable

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#436]
I can reproduce this in any version of Sandboxie Classic edition (including 5.46.4 64 bit).

Steps:
1) Download WSCC (Portable) or WSCC 64-bit (Portable) from [here](https://www.kls-soft.com/wscc/downloads.php).
2) Extract it to a local folder
3) Run wscc.exe in any sandbox you like (empty or non-empty doesn't matter)
4) Put Sandboxie control window in foreground... you'll start noticing that Window title related to wscc.exe will blink incessantly without stopping.

I don't know if this can be considered a bug, but this behavior happens to me only after running this program. 
Any tecnical explanation would be useful to understand why this happens.

**Comment by DavidXanatos** [comment]
i think sandboxies function to show the window border may do something strange

**Comment by DavidXanatos** [comment]
mmh... its not really a bug rather an artifact of something strange wscc does yo will alo notice tht it has the sbie markings [#] doubled,
but mostly important it has no functionality impact aside of looking strange so just ignore it

**Comment by isaak654** [comment]
@DavidXanatos Ok, but what means sbie markings [#] doubled?  Any tecnical explanation?
