### ISSUE TITLE
 tray icon right-click option

### ISSUE THREAD

**Issue by naskater** [sandboxie-plus/Sandboxie#439]
Suggest add an empty sandbox to the tray icon right-click option

**Comment by DavidXanatos** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/272
we have this request already

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/125159249-93faa680-e176-11eb-9c59-5c5a2e91d152.png)

happy?

**Comment by isaak654** [comment]
@DavidXanatos 
Nice, but now these vertical menu separators don't look good anymore... I would suggest to resize them properly or remove them or just matching the new textarea with the menu separators.

![tray_menu_1](https://user-images.githubusercontent.com/12372772/125159442-a1fcf700-e177-11eb-8081-eda14e780283.png)

![tray_menu_2](https://user-images.githubusercontent.com/12372772/125159425-8c87cd00-e177-11eb-8a3e-88e7b294155d.png)

**Comment by DavidXanatos** [comment]
Well its a trade of... if I move the list box more to the right, the vertical line you marked in yellow will only go 1 sell down than stop and than continue at the bottom over terminate all processes.
sooo... I would need to ad an own line at the exact right offset to blend with the original one, and that may fail for different dpi monitors.
hence I would opt for leaving it as is, this way at least all the icons are aligned ;)

**Comment by isaak654** [comment]
@DavidXanatos 
It looks strange to me that the context menu is not dpi aware.
Otherwise you could consider to hide the vertical separator in this way:
![tray_menu_3](https://user-images.githubusercontent.com/12372772/125161158-083a4780-e181-11eb-9a9b-7c13f49fd704.png)

**Comment by DavidXanatos** [comment]
It surely is dpi aware but its not a guarantee to always move everything by the right offset IMHO.
So the additional line may end up a few px off from the original one...
i have no idea how to remove the vertical line entierly, this menu is rendered by Qt, i presume that can be done with the stylesheets, but hunting down the solution is imho not worth the afford
