### ISSUE TITLE
libcrypto and libssl are not included in latest pre-release build of Sandboxie Plus

### ISSUE THREAD

**Issue by lufog** [sandboxie-plus/Sandboxie#4392]
### Describe what you noticed and did

1. Run something via  "Run Sandboxed" (context menu)
2. Get 2 "SandMan.exe - System Error" errors
![image](https://github.com/user-attachments/assets/42939116-7ea7-49da-8082-166380ab94e3)
![image](https://github.com/user-attachments/assets/a241936b-424f-4ba3-843e-e04d0cd12d2c)

### How often did you encounter it so far?

Whenever I try to run something via  "Run Sandboxed" (context menu)

### Expected behavior

Previous pre-release `1.15.1` contains the files `libcrypto-3-x64.dll` and `libssl-3-x64.dll`. So I guess they weren't included in the pre-release  `1.15.2` due to an oversight.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.15.2 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

The issue was introduced the first time in v1.15.2 64-bit

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 11 Pro 23H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender Antivirus (disabled)

**Comment by offhub** [comment]
Yes, after a change in the copying script, some SSL files were not copied to certain versions. You can use libcrypto and libssl DLLs from the previous version.
