### ISSUE TITLE
Apps in a sandbox cannot detect the change of system color scheme (Light / Dark) immediately

### ISSUE THREAD

**Issue by w568w** [sandboxie-plus/Sandboxie#4400]
### Describe what you noticed and did

1. Open Sandboxie-Plus, create a new standard sandbox.
2. Download any app that can immediately respond to system theme changes (they usually have an option in settings like "Follow/Sync system light/dark mode"), such as [Joplin](https://joplinapp.org/). 
3. Execute the app in that sandbox, ensure the option is enabled and toggle system theme setting between light and dark.
4. The app does not change its color scheme based on the system theme, staying as it was. The app must be completely closed and restarted in the sandbox for it to adopt the new theme.

### How often did you encounter it so far?

Always.

### Expected behavior

At the step 4, the app should respond to the system theme change immediately, just like outside the sandbox.

### Affected program

Joplin

### Download link

https://joplinapp.org/download/

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.14.10 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 Home 24H2 64-bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Microsoft Defender

### Did you previously enable some security policy settings outside Sandboxie?

I enable the following device security options:

- Memory access protection
- Firmware protection, version 3
- Local Security Authority protection
- Microsoft Vulnerable Driver Blocklist
- Microsoft Pluton Security processor
- Secure boot

Memory integrity was disabled.

### Trace log

https://pastebin.com/raw/QRHFfpzX

### Sandboxie.ini configuration

```ini
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=y
```

### Additional information

Strange enough, in the trace log I saw that Joplin *did* open `HKEY_USERS\S-1-5-21-312343828-2241121946-1491808978-1001\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize` when toggling, which reflects the system color scheme immediately.

**Comment by w568w** [comment]
**Additional information**

Strange enough, in the trace log I saw that Joplin *did* open `HKEY_USERS\S-1-5-21-312343828-2241121946-1491808978-1001\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize` when toggling, which reflects the system color scheme immediately.

**Comment by offhub** [comment]
Please try again after adding the following Resource Access rule to your configuration, then closing and reopening the application.

**Per box setting**: Sandboxie-Plus > Right click on the sandbox > Sandbox Options > Edit Ini Section > Copy and paste the line to the bottom of the list > OK


**Global Setting**: Sandboxie-Plus > Options > Global Settings > Edit Ini Section > Copy and paste the line to the bottom of the list > OK

_For specific program_:
```ini
OpenKeyPath=Joplin.exe,*\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\*
```

_For any program_:
```ini
OpenKeyPath=*\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\*
```

**Comment by offhub** [comment]
> By the way, do you think there should be a more persistent solution? For example, adding this path to the default resource access template.

We can create a template for Joplin, but it will only be activated once Joplin is detected as installed on the system. In other cases, the user will need to manually enable or disable it from the template list.
