### ISSUE TITLE
Boxes with "MPC-HC64.exe and madVR" leave non-responding tasks when closed

### ISSUE THREAD

**Issue by KztyAQ** [sandboxie-plus/Sandboxie#4409]
### Describe what you noticed and did

Steps taken:
- Started standard yellow box containing Media Player Classic x64 2.3.8, madVR, and LAV Filters
- Played some MKV video file
- Closed standard yellow box containing Media Player Classic x64 2.3.8, madVR, and LAV Filters
- Executed "taskkill.exe /F /FI \"status eq NOT RESPONDING""
- A non-responding task was found and killed

### How often did you encounter it so far?

Any time MKV video files are played in yellow box containing Media Player Classic x64 2.3.8, madVR, and LAV Filters

### Expected behavior

Closing yellow box containing Media Player Classic x64 2.3.8, madVR, and LAV Filters after playback should not leave any unresponding tasks.

### Affected program

MPC-HC64.exe and madVR

### Download link

https://github.com/clsid2/mpc-hc/releases/download/2.3.8/MPC-HC.2.3.8.x64.zip

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

5.70.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 24H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

N/A

### Did you previously enable some security policy settings outside Sandboxie?

N/A

**Comment by offhub** [comment]
Can you provide step-by-step instructions on how to reproduce the issue?

```ini
LeaderProcess=mpc-hc64.exe
```

**Comment by EnfLzSp** [comment]
Here are thorough steps and my Sandboxie configuration for Media Player Classic sandbox:
1. Create the following yellow box
```
[MPC]
ConfigLevel=10
Template=FileCopy
Template=LingerPrograms
Template=AutoRecoverIgnore
BorderColor=#00FFFF,ttl,6
SandboxieLogon=y
UseCreateToken=y
BlockInterferePower=y
OpenSamEndpoint=n
OpenPrintSpooler=n
BlockAccessWMI=y
BlockWinRM=y
HideNonSystemProcesses=y
HideSbieProcesses=y
HideOtherBoxes=y
HideDiskSerialNumber=y
HideFirmwareInfo=y
EnableWin32kHooks=n
ForceProcess=madTPG.exe
ForceProcess=madHCCtrl.exe
ForceProcess=MPC-HC64.exe
LeaderProcess=MPC-HC64.exe
ClosedFilePath=InternetAccessDevices
BlockScreenCapture=MPC-HC64.exe,y
DropAdminRights=y
BlockNetworkFiles=y
HideNetworkAdapterMAC=y
RandomRegUID=y
BlockLocalConnect=y
CoverBoxedWindows=y
```
2. Download a sample MKV file, such as this one - https://getsamplefiles.com/download/mkv/sample-2.mkv
3. Play downloaded sample MKV file in Media Player Classic sandbox
4. Close Media Player Classic sandbox
5. Execute taskkill.exe /F /FI "status eq NOT RESPONDING" 

You should see a reponse about one non-responding process being killed with PID related to Media Player Classic sandbox processes, even though processes forced to run within the sandbox (MPC-HC64.exe, madHCCtrl.exe, madTPG.exe) are closed and don't show on the list of running processes in any task managers.

**Comment by offhub** [comment]
What is the result of this command? `tasklist.exe /FI "status eq NOT RESPONDING"`

**Comment by KztyAQ** [comment]
Fixed in the latest version of Sandboxie.

**Comment by KztyAQ** [comment]
Fixed in the latest version of Sandboxie.
