### ISSUE TITLE
Firefox version update outside of sandboxie, breaks sandboxed Firefox.

### ISSUE THREAD

**Issue by CaliSunUSA** [sandboxie-plus/Sandboxie#4431]
### Describe what you noticed and did

I was running Firefox v 133.0 just fine (Inside and outside of sandboxie).
Last night Firefox I ran outside of sandboxie got upgraded to 133.0.3
This morning I am unable to run sandboxed Firefox, I just get this error message.
Previously, upgrading outside of sandboxie was never an issue.

  
<img width="278" alt="Firefox Version problem" src="https://github.com/user-attachments/assets/e3a9ae10-d03a-4edf-8b84-419377ce1f62" />

### How often did you encounter it so far?

This morning

### Expected behavior

Sandboxed version of Firefox would inherit version from un-sandboxed version.

### Affected program

Firefox 133.0.3

### Download link

firefox.com

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus-x64-v1.15.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### Is it a regression from previous versions?

1.15.0

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 64bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Avast

**Comment by offhub** [comment]
See https://github.com/sandboxie-plus/Sandboxie/issues/4424#issuecomment-2536567271

**Comment by CaliSunUSA** [comment]
following steps in above mentioned link worked.

**Comment by offhub** [comment]
This is not a Windows 11 specific issue, it's actually quite an old problem, see #744, [#1125](https://github.com/sandboxie-plus/Sandboxie/issues/1125#issuecomment-902634314).
