### ISSUE TITLE
Sandman crashes when right-clicking on a box group

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#445]
To reproduce:

1. Install Sandboxie Plus 0.6.0
2. Using SbieCtrl, create a new box group and move at least one box to it (e.g. DefaultBox) (couldn't find a way to do this in Sandman...)
3. Close and exit SbieCtrl
4. Open Sandman and right click on the box group
5. Sandman crashes with `STATUS_ACCESS_VIOLATION` (0xC0000005)

**Comment by DavidXanatos** [comment]
thanks will be fixed in the next build
