### ISSUE TITLE
Waterfox Browser doesn't work with Sandboxie

### ISSUE THREAD

**Issue by dickyharper** [sandboxie-plus/Sandboxie#446]
Hello 

When I want to use the Waterfox browser with Sandboxie I get the error in the picture. I tried the instructions on the help page. The result was the same. After getting the error, I can only close the browser from the sub taskbar. On the other hand, Edge browser works normally.
I'm very new to using Sandboxie. I'm sorry if I overlooked an obvious setting.
Waterfox sandbox .ini file:
```
Enabled=y 
ConfigLevel=7
AutoRecover=n
BlockNetworkFiles=y
Template=Waterfox_Profile_DirectAccess
Template=Waterfox_Session_DirectAccess
Template=Waterfox_Bookmarks_DirectAccess
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
UnrestrictedSCM=y
ExposeBoxedSystem=y
OpenPrintSpooler=y
OpenProtectedStorage=y
OpenCredentials=yes

```
Sandboxie versions I get the error: 0.5.5 / 0.6.0 / 5.46.4
Windows 10 x64 20h2
Waterfox version: g3.0.2

**Comment by dickyharper** [comment]
![Ekran görüntüsü 2021-01-27 192618](https://user-images.githubusercontent.com/50758669/106021252-a5268e00-60d5-11eb-9594-8ac423916ae1.png)

**Comment by DavidXanatos** [comment]
ah yes...
the problem is that waterfox.exe is not recognized as a firefox based browser

to fix that add to your sandboxie.ini in the global section

SpecialImage=firefox,waterfox.exe

I'll add built in detection for firefox forks to the next build

**Comment by dickyharper** [comment]
> 
> 
> ah yes...
> the problem is that waterfox.exe is not recognized as a firefox based browser
> 
> to fix that add to your sandboxie.ini in the global section
> 
> SpecialImage=firefox,waterfox.exe
> 
> I'll add built in detection for firefox forks to the next build

Yeah, that worked. Thanks for Sandboxie and other work.
