### ISSUE TITLE
request feature about Windows Registry 

### ISSUE THREAD

**Issue by amayra** [sandboxie-plus/Sandboxie#45]
can you add a simple registry viewer or reader for sandbox

**Comment by deflock** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/26
http://qwww.mitec.cz/wrr.html + DefaultBox\RegHive

**Comment by DavidXanatos** [comment]
i would liek that but its work and as logn as i can do that with the nromal reg editor the priority is very low.

but I an add a convinient menu entry open box reg that would mount the hive (if its not alrady mounted), open reg edit an dpoint it to the root of the hive file, and once you close reg edit automatically unmount the hive file.

**Comment by DavidXanatos** [comment]
i put a simple reg extraction feature on my todo https://github.com/sandboxie-plus/Sandboxie/issues/60
