### ISSUE TITLE
Update Checker bug in Sandboxie 5.46.4 x64

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#450]
I'm on Sandboxie 5.46.4 x64, and when I check updates it says there is no new available version. 
New available version is 5.46.5 x64, but the program doesn't detect it.

**Comment by DavidXanatos** [comment]
try again info was not updated on server

**Comment by isaak654** [comment]
It detects it now, but there is still a bug.

Steps:
1) Press Yes when the dialog asks to open a web browser
2) Press No when it asks to open the web address in a virtual area
3) Sandboxie Control will crash suddenly at this point.

**Comment by DavidXanatos** [comment]
fixed in next build
