### ISSUE TITLE
Can't use any of the new versions here on github

### ISSUE THREAD

**Issue by Whispofearth** [sandboxie-plus/Sandboxie#453]
I have an error with Unsigned drivers, which windows deletes, and i can't ignore this.
I just tried to load my steam in sandbox mode , and it says SBIE2101 error somehow , couldnt find anything about it.
Anyway to make windows not deleting the Unsigned drivers the installer wants to install.
![sandobox](https://user-images.githubusercontent.com/78115424/106062348-54c42600-60ff-11eb-9a63-7e19ff39d0ac.png)

Already tried to turn off windows firewall + windows defenders, still no success.

**Comment by Whispofearth** [comment]
[https://imgur.com/maQHwbR](url)

**Comment by Whispofearth** [comment]
#
![sandobox1](https://user-images.githubusercontent.com/78115424/106080922-aa5cfa80-6120-11eb-949d-d14ff112fb5f.png)

**Comment by DavidXanatos** [comment]
Just ignore the driver error, windows 8 loads the driver signed for 10 just fine, except a one time complaint.

the error you get with process terminated show me that the driver is in fact loaded and working.

but the error you see seams to be a new bug, probably the same as https://github.com/sandboxie-plus/Sandboxie/issues/449
