### ISSUE TITLE
I can't ınstall Repack games within sandboxed

### ISSUE THREAD

**Issue by RealJameski** [sandboxie-plus/Sandboxie#455]
When everytıme try download hıghly compressed games got this error please fix this ı can download without sandboxed just fıne. Link old sandboxie classic thread someone fixed this problem
https://community.sophos.com/sandboxie/f/forum/112943/isdone-dll-and-unarc-dll-errors
![Ekran görüntüsü 2021-01-28 062643](https://user-images.githubusercontent.com/78128485/106085858-0d0ac200-6132-11eb-82fd-e635791e3d91.png)

**Comment by DavidXanatos** [comment]
Try complaining with FitGirl ;)

Ok seriously have you tried disabling file migration limit?
Or have the files located in the sandbox to begin with.

If that does not help that seriously ask FitGirl  what non standard obfuscation etc... has been used that breaks here.

**Comment by typpos** [comment]
Does this help?
* Sandbox Settings > Resource Access > File Access > Full Access
  * %Local AppData%\Temp\is-?????.tmp*

**Comment by RealJameski** [comment]
I fıxed doing like this thanks guys. 
![Ekran görüntüsü 2021-01-29 220556](https://user-images.githubusercontent.com/78128485/106316944-9a5b2d00-627e-11eb-9411-f00f5397f66b.png)
