### ISSUE TITLE
"The RPC Server is unavailable" when running Windows Fax and scan

### ISSUE THREAD

**Issue by shmu26** [sandboxie-plus/Sandboxie#457]
I open the print dialogue in a web page in Google Chrome, choose "fax" from the list of printers, and "Windows Fax and scan" comes up. When I try to send the fax, I get the error in the title line.

**Comment by DavidXanatos** [comment]
possibly....
what windows version do you have?

try adding ```OpenPrintSpooler=y``` to your sandboxie.ini

**Comment by shmu26** [comment]
I have Windows 10 20H2 x64. I added it to the ini, which now is as follows:
`
[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun

[UserSettings_1212028F]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
SbieCtrl_HideMessage=2101, ConnectPort (C0000022) access=001F0000 initialized=1

[DefaultBox]

Enabled=y
ConfigLevel=7
AutoRecover=n
BlockNetworkFiles=y
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
ForceProcess=chrome.exe
OpenPrintSpooler=y
`
I reloaded the ini
Now I get a different error from Windows Fax: "The service has not been started"

**Comment by DavidXanatos** [comment]
was that ever working? could you try older versions.

**Comment by shmu26** [comment]
To tell you the truth I never tried it before. I didn't have a fax modem before.

**Comment by shmu26** [comment]
I tried v. 5.45.0 
Same issue.

**Comment by DavidXanatos** [comment]
when you find a working version i'll please reopen this issue for now i'll close it
