### ISSUE TITLE
Sandboxie-Plus v0.6.0 - Creating a new box doesn't create any folder on drive

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#458]
I tried to create a new sandbox called "New Box" and I can't find any folder inside `C:\Sandbox\username\` (except DefaultBox).
The consequence is that "Explore Content" option doesn't work for the "New Box".

Sandboxie-Plus v0.6.0 x64

Sandboxie.ini:

> [GlobalSettings]
> 
> `FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%`
> SeparateUserFolders=y
> `KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%`
> `IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%`
> EditAdminOnly=n
> ForceDisableAdminOnly=n
> ForgetPassword=n
> Template=WindowsLive
> Template=OfficeLicensing
> 
> [UserSettings_08BA01C1]
> 
> SbieCtrl_AutoStartAgent=SandMan.exe
> SbieCtrl_EnableAutoStart=y
> BoxDisplayOrder=DefaultBox
> 
> [DefaultBox]
> 
> Enabled=y
> ConfigLevel=7
> AutoRecover=n
> BlockNetworkFiles=y
> Template=qWave
> Template=BlockPorts
> Template=LingerPrograms
> Template=Chrome_Phishing_DirectAccess
> Template=Firefox_Phishing_DirectAccess
> Template=AutoRecoverIgnore
> RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
> RecoverFolder=%Personal%
> RecoverFolder=%Desktop%
> BorderColor=#00FFFF,ttl
> 
> [New_Box]
> 
> Enabled=y
> ConfigLevel=7
> AutoRecover=n
> BlockNetworkFiles=y
> Template=qWave
> Template=BlockPorts
> Template=LingerPrograms
> Template=Chrome_Phishing_DirectAccess
> Template=Firefox_Phishing_DirectAccess
> Template=AutoRecoverIgnore
> RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
> RecoverFolder=%Personal%
> RecoverFolder=%Desktop%
> BorderColor=#00FFFF,ttl

**Comment by hg421** [comment]
The same problem ("Explore Content" not working because there is no sandbox folder) happens after deleting the contents of a box.

**Comment by hg421** [comment]
I would suggest to show a message box, such as "this sandbox is empty", if one attempts to explore an empty sandbox

**Comment by DavidXanatos** [comment]
> 
> 
> I would suggest to show a message box, such as "this sandbox is empty", if one attempts to explore an empty sandbox (similar to the one that you get when you try to delete an empty box)

yes
