### ISSUE TITLE
Configuration file error in line 1: line too long (UTF8 encoding)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#461]
Problem: if you change Templates.ini encoding to UTF8 or UTF8-BOM, Sandboxie will produce errors like this:

![utf8_not_supported](https://user-images.githubusercontent.com/12372772/106158858-7c110680-6184-11eb-9c22-8ce460bf5532.png)

Some advantages to support UTF8 encoding: 
1) It would allow to save storage space:
![storage_space](https://user-images.githubusercontent.com/12372772/106159412-0c4f4b80-6185-11eb-872f-44d6ce8adfc7.png)
2) It would allow to resolve the corruption issue mentioned in #402
3) Changing Templates.ini encoding to UTF8-BOM (with Sandboxie Classic installed) can trigger multiple dialog windows that you can't even close, unless you terminate Sandboxie Control from Windows Task manager. Another reason to support UTF8 encoding.

**Comment by DavidXanatos** [comment]
I'm not sure how expedient that would be, the files are parsed by the driver directly and I would guess that may be some required UTF8 to Unicode functions may nto be available. In the kernel mode you cant use most of the normal windows facilities.

**Comment by isaak654** [comment]
> 
> 
> I'm not sure how expedient that would be, the files are parsed by the driver directly and I would guess that may be some required UTF8 to Unicode functions may nto be available. In the kernel mode you cant use most of the normal windows facilities.

An attacker could craft a small script to convert the template file in utf8-bom and screw up your Sandboxie Classic configuration.
Fortunately I wasn't able to trigger the dialog windows loop on Sandboxie Plus, but Classic users should be concerned about this.

**Comment by DavidXanatos** [comment]
Well the attacker would have to be outside the sandbox and have admin rights so he can break whatever he wants

**Comment by isaak654** [comment]
> 
> 
> Well the attacker would have to be outside the sandbox and have admin rights so he can break whatever he wants

Good point, but there is still the issue mentioned in #402.
I provided a workaround for it, but it could still be confusing for some users.

**Comment by DavidXanatos** [comment]
I'm not saying no, yet, I'll have to look into it.

also I'm very hesitant changing things that may royally screw up something that may result in som odd hard to reproduce bugs.

**Comment by DavidXanatos** [comment]
Sooo adding utf8 to the driver is a mess but doable, in the end I need to "manually" do the utf8 to unicode decoding
