### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by NiggaInTheNight** [sandboxie-plus/Sandboxie#467]
Hi i tries to update sandbox from 5.27, but all new versions on last half of year, but have a strange problem. Applications inside box works normal up to time to close. When i close application inside box(not sandbox) i take error sbie 2224. I tries portable versions, install, tries default box, import old ini, create strong and weak boxes - no changes. As result some application cant work inside sandbox because they run child processes and waiting for successful result of executing. Win7x64.

// Updated. Restored sbie code.

**Comment by DavidXanatos** [comment]
could you please test old versions and tell me exactly which is the last version that have worked for you?

**Comment by NiggaInTheNight** [comment]
I ties to downgrade version up to work, but im limited by current repository. I didnt found working version here and idk where i can take old sandoxie repo. Where i can take 5.27-5.40?

**Comment by DavidXanatos** [comment]
> 
> 
> I ties to downgrade version up to work, but im limited by current repository. I didnt found working version here and idk where i can take old sandoxie repo. Where i can take 5.27-5.40?

pff... that will be difficult as those are from the sophos days and no longer online

**Comment by hg421** [comment]
Wayback Machine has some older versions archived,
e.g. 5.30 here:
https://web.archive.org/web/20190617225727/https://www.sandboxie.com/SandboxieInstall.exe

Or try other captures
https://web.archive.org/web/*/https://www.sandboxie.com/SandboxieInstall.exe

**Comment by DavidXanatos** [comment]
since no one else has this issue and we have no way to properly debug it i'll close this
