### ISSUE TITLE
Brave support

### ISSUE THREAD

**Issue by linkcell** [sandboxie-plus/Sandboxie#468]
As reported [here](https://github.com/brave/brave-browser/issues/12082), please help us use sandboxie with Brave!

Brave stopped running inside Sandboxie.
All tabs go "oh snap!".
Not sure what exactly made this happen but it was one of the updates this past week.

Brave supports requested to reach out to you here.

Thank you for your attention

**Comment by NewKidOnTheBlock** [comment]
Huh?
This is Brave Portable win64-1.18.78-69 running in SB Classic 5.46.4:
![brave](https://user-images.githubusercontent.com/12411527/106352263-c956ba80-62e1-11eb-8dc9-c1acaa0d3fff.png)

**Comment by DavidXanatos** [comment]
see https://github.com/sandboxie-plus/Sandboxie/issues/446 try adding ```SpecialImage=firefox,brave.exe``` to your sandboxie ini and I'll add brave.exe to the built in list in the next build for everyone
