### ISSUE TITLE
CSandBox::IsEmpty always returns true if the box name is a reserved device name

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#470]
`CSandBox::IsEmpty` always returns true if the box name is a reserved device name (such as `con`, `nul`, etc.)
Therefore trying to delete the contents of such boxes with Sandman will fail with the message "This box is already empty",
even when it isn't.

While Sandman blocks creating boxes with names that are reserved device names, SbieCtrl will happily do that and Sandboxie works fine with them.
(Not saying that this is a good idea as there are still side effects though, e.g. exploring the contents with Windows Explorer will not work and most Windows tools won't correctly handle them)

**Comment by bastik-1001** [comment]
Beside that bug being present, shouldn't it be prevented that SbieCtrl can create boxes with reserved names and that Sandboxie will work with them, as they are causing issues with Windows tools?

**Comment by hg421** [comment]
> 
> 
> Beside that bug being present, shouldn't it be prevented that SbieCtrl can create boxes with reserved names and that Sandboxie will work with them, as they are causing issues with Windows tools?

Yeah, probably.. Although it still wouldn't prevent you from editing the ini directly with those names

So we would need to reject such ini files as invalid
(This is what already happens with other bad names, i.e. >32 characters or containing something other than letters, digits and underscores, you get a 'syntax error')

**Comment by DavidXanatos** [comment]
The next build will have the required check also added to the classic UI such that boxes with reserverd names cant be created anymore
