### ISSUE TITLE
Wrong template title in upcoming release

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#477]
https://github.com/sandboxie-plus/Sandboxie/blob/032365a3873d783bb7127fb09b4499680d99339e/Sandboxie/install/Templates.ini#L2805

You should change the title in SkipHook list or something like that.

**Comment by DavidXanatos** [comment]
yes indeed thanks

**Comment by isaak654** [comment]
@DavidXanatos 
I think you can remove these lines from Templates.ini:
https://github.com/sandboxie-plus/Sandboxie/blob/a9d9739e8d4c0b29ed0bad46014d49c86ed6f3be/Sandboxie/install/Templates.ini#L2878-L2882

I refactored Seamonkey templates some week ago, so it can't be considered deprecated anymore.
