### ISSUE TITLE
Sandboxie-Plus Slack Channel

### ISSUE THREAD

**Issue by DavidXanatos** [sandboxie-plus/Sandboxie#479]
There is a Sandboxie-Plus Slack Channel all regular contributors are welcome to join, just send me an email and you will get a invite.

**Comment by isaak654** [comment]
@diversenok I hope you don't mind, but I've just sent you an invite to our channel. You're free to accept or decline if you wish.

**Comment by isaak654** [comment]
@DavidBerdik and @Valinwolf
As Sandboxie contributors, I've just sent you an invite to join the Sandboxie-Plus Slack Channel. You're free to accept it or ignore it if you wish.

@stephtr and @mpheath
If you would like to join the Sandboxie-Plus Slack Channel, you can share your email privately [here](https://www.eng2ita.net/forum/index.php?action=contact) and I'll add you upon request.

**Comment by DavidBerdik** [comment]
@isaak654 Joined! Thank you!

**Comment by isaak654** [comment]
@flamencist and @henrikx
 If you would like to join the Sandboxie-Plus Slack Channel, you just need to confirm the invitation I sent to your emails.

**Comment by isaak654** [comment]
@yfdyh000
If you would like to join the Sandboxie-Plus Slack Channel, you just need to confirm the invitation I sent to your email. 
Thank you for your previous hint!

**Comment by isaak654** [comment]
@NewKidOnTheBlock
If you would like to join the Sandboxie-Plus Slack Channel, you can share your email privately by filling this [form](https://www.eng2ita.net/forum/index.php?action=contact) and I'll add you upon request.

**Comment by isaak654** [comment]
@mpheath
If you would like to join the Sandboxie-Plus Slack Channel, you can fill my website's [contact form](https://www.eng2ita.net/forum/index.php?action=contact) and I'll send you the invite. Alternatively, I can reply you with my email address in case you prefer to reach me in this way.  :slightly_smiling_face:

**Comment by Aholicknight** [comment]
invite please

**Comment by isaak654** [comment]
> invite please

I've just discussed about it with the main developer, only the regular contributors are welcome and that isn't going to change.

**Comment by isaak654** [comment]
> invite please

I've just discussed about it with the main developer, only the regular contributors are welcome to Slack  and that isn't going to change.

**Comment by isaak654** [comment]
> invite please

I've just discussed about it with the main developer, only the regular contributors are welcome on Slack and that isn't going to change anytime soon.

**Comment by isaak654** [comment]
@lufog @Zerorigin @Hulen
If you would like to join the Sandboxie-Plus Slack Channel, you can fill my website's [contact form](https://www.eng2ita.net/forum/index.php?action=contact) and I'll be sure to send the invite for each of you as soon as I can.

**Comment by isaak654** [comment]
@ojo11
If you would like to join the Sandboxie-Plus Slack Channel, you can fill my website's [contact form](https://www.eng2ita.net/forum/index.php?action=contact) and I'll be sure to send the invite as soon as I can.

**Comment by isaak654** [comment]
@VenusGirl @vedantmgoyal2009 @okrc @fmbxnary @offhub @RandomGOTI @1mm0rt41PC @APMichael @blap

If you would like to join the Sandboxie-Plus Slack channel, you can fill my website's [contact form](https://www.eng2ita.net/forum/index.php?action=contact) with your GitHub name / email contact and I'll make sure to send the invite for each of you as soon as I can. Otherwise, feel free to ignore this message.

**Comment by isaak654** [comment]
@offhub  Out of curiosity, would you be available to become a collaborator with triage permissions?

**Comment by offhub** [comment]
@isaak654 Yes, I would.

**Comment by isaak654** [comment]
@offhub 
<img src="https://user-images.githubusercontent.com/12372772/202909009-e37a28e9-09a9-4d8e-b04c-6d7d1ad64246.png" height="100px"> 

Feel free to [email him](https://xanasoft.com/contact/) to be invited on the Slack channel.

**Comment by isaak654** [comment]
@offhub You have a new Slack message, let me know there what you think about it.

**Comment by isaak654** [comment]
@offhub I've forwarded you a use case about `BlockInterferePower=y` on Slack, I hope it helps you.
