### ISSUE TITLE
666+

### ISSUE THREAD

**Issue by Zyntax3rror** [sandboxie-plus/Sandboxie#48]
This is an old bug and hopefully very simple to fix

menu is broken(grayed out text) after right click on >666 sandboxes

![666](https://user-images.githubusercontent.com/16851233/84288844-05b28c00-ab42-11ea-92ff-80d3fc5fc49d.PNG)

**Comment by DavidXanatos** [comment]
if you send me a ini with 666 sandboxes I will take a look.

**Comment by Zyntax3rror** [comment]
Here is 999 :)
juste paste them after your default sandbox

[sbox999.zip](https://github.com/sandboxie-plus/Sandboxie/files/4801782/sbox999.zip)

**Comment by DavidXanatos** [comment]
I have looked into the issue and it is not trivial to fix, it would require redoing parts of the SbieCtrl menu handling code.
So if you really need more then 666 sandboxes consider using the new Plus UI SandMan.exe, it is Qt based an does not have sch limitations.
