### ISSUE TITLE
[Enhancement] Full Unrestricted Access to All Resources (Hardwares, Softwares or Storage Files), need only Multiple Instance Functionality

### ISSUE THREAD

**Issue by ajayalag1974** [sandboxie-plus/Sandboxie#482]
First of all, thanks for the great program.

I am using Sandboxie for irregular use case and for that purpose I need all the programs running under any sandbox have Full Unrestricted Access to All Resources (Hardwares, Softwares or Storage Files) just like a non-sandboxed program, just want to keep Multiple Instance functionality and remove/disable all security/privacy features or restrictions.

**Issue in my Use Case**  - I am launching OBS software multiple times in different sandboxes and each OBS instance needs to access softwares/windows/resources running under any of the Sandbox or Without Sandbox to use or capture them (use case is long but this is what I need to achieve for my use case). Moreover virtual camera started by one OBS instance is only accessible in that particular OBS Sandbox, I need inter-sandbox access.

**Comment by ajayalag1974** [comment]
![InkedCapture_LI](https://user-images.githubusercontent.com/76968826/106398253-d7b6ea80-6437-11eb-8ee7-c0c5592df4be.jpg)
See screenshot of OBS opened in Sandbox 2 and trying to capture window under Sandbox 1, in this case it can capture only some kind of windows but when open OBS without Sandbox it can capture all of the windows in whatever Sandbox.

It could be that when in Sandbox, OBS don't have access to particular resources/services which allows it to capture those windows.

I experimented by giving access to resources. Not an expert just tried with some common sense and suggestion here and there.
![Capture](https://user-images.githubusercontent.com/76968826/106398362-5dd33100-6438-11eb-963c-cb1f528af1a8.PNG)

**Comment by TooYoungTooSimp** [comment]
Similar use case, but on my case. I run obs in real system and a web meeting soft in sandbox. that meeting app can't access obs's virtual cam. So if it is possible to let sandboxed app access the camera, it would be nice.

**Comment by DavidXanatos** [comment]
the thng is that if you opel all access than th different instances will see each oehr breakingthe multiple instance functionality.

So I'll close this issue asits no strait forward way to add it to sandboxie in the desired way
