### ISSUE TITLE
Sandboxie-Plus: Automatic light/dark theme selection

### ISSUE THREAD

**Issue by stephtr** [sandboxie-plus/Sandboxie#483]
Sandboxie-Plus has a nice dark theme. It would be useful, if it would by default automatically select the theme according to Windows 10's settings.

![image](https://user-images.githubusercontent.com/5764184/106398324-76c8eb80-6412-11eb-848f-ba9ed0a2b820.png)
Instead of this checkbox, one could have a select control with [Light, Dark] on Windows < 10 and [Use Windows mode, Light, Dark] for supported versions of Windows 10.

**Comment by ImSpecial** [comment]
What if one uses Windows "Light theme" but want the Sandmans "Dark theme"?

Seems unnecessary. But I guess in today's age, lots like Windows doing things for them...

**Comment by stephtr** [comment]
That's why in my idea you can choose between "Follow Windows", "Light theme only" and "Dark theme only".
This is definitely a low priority/impact feature, but is easy and quick to achieve.
