### ISSUE TITLE
Notes for "Release v0.6.5 / 5.47.0"

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#485]
I hate to be nit-picky and pedantic af, but ...
> **Added**
> * added detection for waterfox.exe, Palemoon.exe, basilisk.exe and brave.exe firefox forks

AFAIK Brave is not a Firefox fork. If that's a typo it's fine, but I cannot read the changes to verify that (neither if the code is somehow messed up too).

> * when DefaultBox is not found by the SandMan UI, it will be recreated

I am not against it (especially given https://github.com/sandboxie-plus/Sandboxie/issues/364's particularity), but maybe that's not user-friendly

> * reworked file migration behaviour, removed hardcoded lists in favour of templates
> -- you can now use "CopyAlways=", "DontCopy=" and "CopyEmpty=" that support the same syntax as "OpenFilePath="
> -- "CopyBlockDenyWrite=program.exe,y" makes a write open call to a file that won't be copied fail instead of turning it read only

I know it's a new feature, but `CopyBlockDenyWrite` is not documented anywhere. Normally, I wouldn't fuss about it, but the `,y` portion bothers me. It is considered a valid value to have `program.exe,n`? If so, what does it mean? `program.exe` is monitored for the `CopyBlockDenyWrite` purposes, but not acted upon?
Or does `,y` mean something else entirely?

(Also, on the side; it's not a good idea to keep both https://sandboxie-plus.com/sandboxie/helptopics/ and https://sandboxie-plus.github.io/sandboxie-docs/; at least reference each other, so people that've seen both don't need to dig their history - or if some page is "more complete" of the other one)
(Also also, https://sandboxie-plus.github.io/sandboxie-docs/Content/SandboxieIni.md is broken \[from https://sandboxie-plus.github.io/sandboxie-docs/Content/AllPages.html ])

**Comment by isaak654** [comment]
> 
> 
> I hate to be nit-picky and pedantic af, but ...
> 
> > **Added**
> > 
> > * added detection for waterfox.exe, Palemoon.exe, basilisk.exe and brave.exe firefox forks
> 
> AFAIK Brave is not a Firefox fork. If that's a typo it's fine, but I cannot read the changes to verify that (neither if the code is somehow messed up too).

David is very fast to publish new builds, personally I would suggest to slow down a bit with the releases.

Anyway, there is an additional fix now in my pull request:
https://github.com/sandboxie-plus/Sandboxie/pull/484/commits/d41059dc72f1f84937c5b132e9ae45589749382a#diff-a92c62c0a6d2e2f1bf1354166acd4b60cefb44d1e756920da1bf20b443a91031

**Comment by LukeSeers** [comment]
> > * when DefaultBox is not found by the SandMan UI, it will be recreated
> 
> I am not against it (especially given #364 particularity), but maybe that's not user-friendly

Some users might get confused, but that can be easily solved by not allowing the user to remove it. If David does go with this idea, I would suggest to also make a simple option somewhere in the settings to be toggleable so that a more experienced user can remove/hide it.

**Comment by stdedos** [comment]
> David is very fast to publish new builds, personally I would suggest to slow down a bit with the final releases.

That's kind of okay; I saw changelog fixes that have been touching on CI/CD stuff. 

His releases are not that big, and, if he is using quick releases to "train himself" to follow CI/CD (ie release quickly, as I don't see a way to unit test or E2E), then that's a price that has to be paid anyway.

**Comment by DavidXanatos** [comment]
Ups you are right brave is chromium based, will have that fixed for the next release, the prsets can be overwriten using the ini anyways and practically firefox handled just like chrome just with less extra workarounds so not a significat oversight.

```CopyBlockDenyWrite=y``` return an deny write error for all programs that try to open a file that cant be migrated
```CopyBlockDenyWrite=n``` try to open file as read only for all programs that try to open a file that cant be migrated


```CopyBlockDenyWrite=program.exe,y``` return an deny write error for pogram.exe that try to open a file that cant be migrated
```CopyBlockDenyWrite=program.exe,n``` try to open file as read only for pogram.exe that try to open a file that cant be migrated

the n option is the default behavior, so setting it has no consequence, but may be desired if in future the default behavior gets changed. 

also you can  use !program.exe to negate and <program_groupe> as well its the same syntax as with OpenFilePath and alike.

**Comment by typpos** [comment]
> ..suggest to slow down a bit with the final releases.

I would prefer regular releases. Fine if they are "for internal use".


> .. SandboxieIni.md is broken

Fixed once David pulls.


>  .. not a good idea to keep both [documentation sets]

Agreed, and consolidating some of the general Sandboxie web presence would be great (github, xanatos forum, wilders, xanatos.com, github.io, classic docs vs Plus docs, etc).

**Comment by DavidXanatos** [comment]
> 
> > .. not a good idea to keep both [documentation sets]
> 
> Agreed, and consolidating some of the general Sandboxie web presence would be great (github, xanatos forum, wilders, xanatos.com, github.io, classic docs vs Plus docs, etc).

Yes but how to do that elegantly?


PS:
about Config=program.exe,y
1. this applies currently only to selected settings not to all
2. I'll extend this for the next build to prioritize match modes
so Config=program.exe,value is highest priority
while Config=!program.exe,value is lesser priority
and Config=value is lowest priority
this scheme should bring the highest flexibility

**Comment by stdedos** [comment]
> > > .. not a good idea to keep both [documentation sets]
> > 
> > 
> > Agreed, and consolidating some of the general Sandboxie web presence would be great (github, xanatos forum, wilders, xanatos.com, github.io, classic docs vs Plus docs, etc).
> 
> Yes but how to do that elegantly?

Some time-delayed 301, with a user-friendly informative text?
I am not claiming to know how easy or complex is that for all case; however, the sooner it's done the better.

As soon as a source is a strict subset of another, just immediately deprecate it.

> PS:
> about Config=program.exe,y
> 
> 1. this applies currently only to selected settings not to all
> 2. I'll extend this for the next build to prioritize match modes
>    so Config=program.exe,value is highest priority
>    while Config=!program.exe,value is lesser priority
>    and Config=value is lowest priority
>    this scheme should bring the highest flexibility

The proposed scheme is good, however:
For security purposes, at least everything that lessens the security should follow:
"Explicit Deny > Explicit Allow > Implicit [Deny, Allow] (User's Option, default:Deny)"

I am not sure how to extrapolate the inverse case, however.

**Comment by stdedos** [comment]
btw, for the SBIE messages, Github wiki is a fine place to have these.
See e.g. https://github.com/koalaman/shellcheck/wiki/SC2031

**Comment by DavidXanatos** [comment]
> > PS:
> > about Config=program.exe,y
> > 
> > 1. this applies currently only to selected settings not to all
> > 2. I'll extend this for the next build to prioritize match modes
> >    so Config=program.exe,value is highest priority
> >    while Config=!program.exe,value is lesser priority
> >    and Config=value is lowest priority
> >    this scheme should bring the highest flexibility
> 
> The proposed scheme is good, however:
> For security purposes, at least everything that lessens the security should follow:
> "Explicit Deny > Explicit Allow > Implicit [Deny, Allow] (User's Option, default:Deny)"
> 
> I am not sure how to extrapolate the inverse case, however.


I do not think that I'll use process specific presets for security/isolation related options, as a process in the sandbox can always rename itself and this way bypass such a restriction.

Currently this options are only used for compatibility related stuff.

**Comment by stdedos** [comment]
SHA1 hashes instead of filenames?
SHA2 file hash from signature? 😛

**Comment by DavidXanatos** [comment]
> 
> 
> SHA1 hashes instead of filenames?
> SHA2 file hash from signature? 😛

that would mean updating all the presets whenever an app gets updated, so the user-friendliness is still lacking

**Comment by isaak654** [comment]
> 
> > ..suggest to slow down a bit with the final releases.
> 
> I would prefer regular releases. Fine if they are "for internal use".
> 

Regular releases are fine, but it would be better to have some internal releases before giving the final release to the public.

**Comment by stdedos** [comment]
> > SHA1 hashes instead of filenames?
> > SHA2 file hash from signature? 😛
> 
> that would mean updating all the presets whenever an app gets updated, so the user-friendliness is still lacking

There is a middle ground for signed apps: The app executable is included in the signature.

**Comment by stdedos** [comment]
... on the release notes side: I think it would make it easier for everyone (including you) to auto-close one ticket with one commit (https://github.blog/2013-01-22-closing-issues-via-commit-messages/), and track release notes too (https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0b1.rst#full-list-of-fixes-and-enhancements)

**Comment by DavidXanatos** [comment]
I'm really not a fan of signatures as its a slippery slope towards an apple-fication of PC's i.e. making users unable to  run their own code on their own devices, sooner or later, like on the iphone

I really really really hate everything that's sold under the label of security but only means taking away the choice of the user, wether its driver signature, even worst secure boot, or just hiding the button to run unsigned code away from the user.

The notion of signature == secure is simply invalid.
That is unless you the user was the one to sign it yourself.

I'm telling you in future there will be a world crisis because someone forgot to renew a certificate in time, or a hacker managed to get some essential certificate blacklisted.

that rant aside...

Inside the sandbox a malicious application can just start an instance of a process that is allowed to do something and inject some code into that process to do things. 

So really if you allow any process in a particular sandbox to do something you must expect that if that sandbox gets infected any process in the sandbox will be able to do that allowed action, eider by renaming or by code injection.

**Comment by NewKidOnTheBlock** [comment]
> I'm telling you in future there will be a world crisis because someone forgot to renew a certificate in time, or a hacker managed to get some essential certificate blacklisted.

Point in case: Mozilla forced signing of all add-ons. When they forgot to renew a certificate, this policy basically acted like a remote kill switch for all add-ons worldwide.
ZAP! All your add-ons are disabled.

**Comment by stdedos** [comment]
> that rant aside...

I don't disagree, but having certificates on some 100Ms downloaded app, "it's not a bad idea" either... 

> Inside the sandbox a malicious application can just start an instance of a process that is allowed to do something and inject some code into that process to do things. 
> 
> So really if you allow any process in a particular sandbox to do something you must expect that if that sandbox gets infected any process in the sandbox will be able to do that allowed action, eider by renaming or by code injection. 
> 

You then block renaming with my suggestion 😄 (for those special apps anyway). 
But yeah, I forgot that in Windows, injection is a "state of mind"... Oh well. Ignore me. I'll just go rant in my corner....

**Comment by DavidXanatos** [comment]
@stdedos 

What I could do as a sort of security feature would be to disallow any unapproved process from starting and any unapproved dll from loading.
When they are located in a sandbox.
The user would be presented with a prompt to allow or deny the loading of this binary image and sbie would remember the choices by hash value.

So apps outside the box would run without any fuss
apps installed into the sandbox would need to be approved by the user.
and when they get updated approved again.

I somehow like the idea, would add an additional layer of security.

Also I may implement it such that a user can approve an entire snapshot at once tan only new files would need approval bu binaries from whin an approved snapshot would be handled like files on the normal system.
