### ISSUE TITLE
0.6.5 regression: sandbox window border width no longer adjustable

### ISSUE THREAD

**Issue by ylluminate** [sandboxie-plus/Sandboxie#488]
After updating from the previous version to 0.6.5 I've found that my settings for "Sandboxed window border" width are no longer respected. They seem to just force to 5 and do not go down to 2 or 1, for example.

**Comment by DavidXanatos** [comment]
for me this seams to still work fine, anyone else with this issue?

**Comment by isaak654** [comment]
I disabled border option in 5.47.0, now I can't no longer apply any different color from black. I can't set a different color, because it will always appear black. Color selector is broken:

![broken_border](https://user-images.githubusercontent.com/12372772/106460484-b5eb5100-6493-11eb-8fd0-98cce47599bd.png)

**Comment by bastik-1001** [comment]
For me that function is also working as before, in 0.6.5

**Comment by ylluminate** [comment]
There was a message previously by @isaak654 wherein he said:
```
I disabled border option in 5.47.0, now I can't no longer apply any different color from black. I can't set a different color, because it will always appear black. Color selector is broken: <a broken png was attached>
```

I'm no longer seeing their message...

**Comment by isaak654** [comment]
> 
> 
> There was a message previously by @isaak654 wherein he said:
> 
> > I disabled border option in 5.47.0, now I can't no longer apply any different color from black. I can't set a different color, because it will always appear black. Color selector is broken:
> 
> I'm no longer seeing their message...

https://github.com/sandboxie-plus/Sandboxie/issues/494

**Comment by DavidXanatos** [comment]
I an not reproduce this issue what is the entry in your sandboxie ini for the BorderColor of the affected box?

**Comment by ylluminate** [comment]
Two boxes affected:
```
BorderColor=#0400ff,on,2
```
```
BorderColor=#ff160a,on,2
```

**Comment by DavidXanatos** [comment]
well the setting says 2 does the plus UI also display 2?

can it be that you are still running the old sbiectrl someware in paralell that one has a fixed width those woudl draw its own thick border over the thin one

**Comment by ylluminate** [comment]
That's the problem, no: the config says 2, but the display is 5:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/OAugrW8m/dba4540a-91c2-4368-9434-1b51529f7998.jpg)

I'm running 0.6.5.

**Comment by DavidXanatos** [comment]
and sbiectrl.exe is NOT running?

**Comment by ylluminate** [comment]
I just update to 0.6.7 and the border width is working again!  Not sure how or why, but yeah...
