### ISSUE TITLE
This application cannot run under a virtual machine (sandboxie 5.45.2-5.47.0) 64bit

### ISSUE THREAD

**Issue by InfernalMercenary** [sandboxie-plus/Sandboxie#490]
Hi there, I am getting "This application cannot run under a virtual machine" (sandboxie 5.45.2-5.47.0) 64bit for 
"Sayatoo Subtitle Maker v2.3.7.5529" upon starting after installation.
I am using Windows 7 Ultimate SP1 x64.
Installer is here:
https://drive.google.com/file/d/1lZquRbC-QhwraUn47G6TL4YkrqEr6pol/view?usp=sharing

Thank you!

![sayatoo vm](https://user-images.githubusercontent.com/78334775/106414138-deb91980-6486-11eb-9f09-8a314a8fc9e6.jpg)

**Comment by Gravityzwell** [comment]
Also:
https://github.com/sandboxie-plus/Sandboxie/issues/234
https://github.com/sandboxie-plus/Sandboxie/issues/98
https://github.com/sandboxie-plus/Sandboxie/issues/115
