### ISSUE TITLE
Sandboxie Plus v0.6.5 / 5.47.0 Message SBIE2303 SBIE2318

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#491]
SBIE2303 Could not hook NdrClientCall2 (33, 487)
SBIE2318 DLL initialization failed for 'rpcrt4.dll'

OS:Windows 7 Ultimate SP1 x64
Previous version(s) didn't show any errors

**Comment by DavidXanatos** [comment]
Do you have IPC tracing enabled?

**Comment by RandomGOTI** [comment]
> Do you have IPC tracing enabled?

FileTrace=A
PipeTrace=A
KeyTrace=A
IpcTrace=A
GuiTrace=A
DebugTrace=n

Yes, under global settings , had them since https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.4.5

**Comment by DavidXanatos** [comment]
ok the issue is caused by IpcTrace=A
apparently the new tracing code i added in the last build does not work on 7,
I'll make it always disabled on 7 in the next build

**Comment by RandomGOTI** [comment]
Thank you @DavidXanatos , while i commented the line out i enabled DebugTrace and it seems to to show some errors aswell, could it be also incompatible with w7 ?

SandboxieRpcSs.exe (8476): SBIE2101 Object name not found: \WindowsErrorReportingServicePort, error AlpcConnectPort (C0000022) access=001F0001 initialized=1   
PID 8452: SBIE2314 Cancelling process SandboxieRpcSs.exe [8476 / 7]                                                                                            
.exe (9000): SBIE2204 Cannot start sandboxed service RpcSs (1)                                                                                             
.exe (9000): SBIE2204 Cannot start sandboxed service DcomLaunch (-4)

**Comment by isaak654** [comment]
@RandomGOTI I would suggest to fill a new issue for new questions... when David closes an issue, usually it's closed for good.
