### ISSUE TITLE
5.47.0 Classic bug: New Microsoft Edge is not automatically deleted

### ISSUE THREAD

**Issue by Seeadler1** [sandboxie-plus/Sandboxie#493]
Since 5.47.0 new Edge is no longer automatically deleted in the sandbox after exiting (program end-primary programs). In 5.46.5 edge was deleted. Firefox and Chrome are automatically deleted. 
So I went back to 5.46.5 first.

Regards

**Comment by NewKidOnTheBlock** [comment]
Hmm, are you sure?
![Zwischenablage-2](https://user-images.githubusercontent.com/12411527/106462977-1334d180-6497-11eb-95be-ec60ea3f8b00.png)

**Comment by Seeadler1** [comment]
I use auto-delete. I close edge and it remains in the sandbox. Not so with Chrome and Firefox. With 5.46.5 it was no problem.
![Image 1](https://user-images.githubusercontent.com/77801595/106467145-8b51c600-649c-11eb-9bbb-b7066a513828.png)

**Comment by Deadite333** [comment]
Seems to be an issue with Vivaldi too. Noticed auto-delete didn't work and the browser couldn't be re-opened till I deleted manually.

**Comment by Seeadler1** [comment]
5.47.1 is the solution!

Thank you very much!!!
