### ISSUE TITLE
Border color changes in Sandboxie Classic are not reflected in the appearance settings

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#494]
Basically I can't select a different border color in the color selector interface that appears broken:

![broken_border](https://user-images.githubusercontent.com/12372772/106460484-b5eb5100-6493-11eb-8fd0-98cce47599bd.png)

EDIT: I can reproduce it on Sandboxie-Classic-x64-v5.46.4 and Sandboxie-Classic-x64-v5.46.5 too. It seems an old bug to me.

**Comment by DavidXanatos** [comment]
I an not reproduce this issue what is the entry in your sandboxie ini for the BorderColor of the affected box?

**Comment by isaak654** [comment]
> 
> 
> I an not reproduce this issue what is the entry in your sandboxie ini for the BorderColor of the affected box?

BorderColor=#80FFFF,ttl

**Comment by DavidXanatos** [comment]
hmm that looks fine very strange, so even when you pick lets say red in the picker the preview square stays black?
Or doe sit change just that the tool later ignores it and does not draw the border properly?

**Comment by isaak654** [comment]
> 
> 
> hmm that looks fine very strange, so even when you pick lets say red in the picker the preview square stays black?
> Or doe sit change just that the tool later ignores it and does not draw the border properly?

When I try to pick any color, all previews stay black (like in the image above).

**Comment by DavidXanatos** [comment]
what do you mean with all previews, there should be only one in the border page that gets update only once you've clicked ok after picking a color.

Those in the red square are supposed to be always black:
![grafik](https://user-images.githubusercontent.com/3890945/107227670-f9a60380-6a1b-11eb-9d7d-95fedde43234.png)

**Comment by isaak654** [comment]
> Those in the red square are supposed to be always black

I can still set a new border color that will be shown in all sandboxed programs, but unfortunately the new color is not reflected in the color selector and in the color preview in the appearance screen.

For example:
1) Double-click on the yellow color when you are in the color selector
2) Ok
3) Apply
4) New color is not there. To know exactly what color is it, I have to look in sandboxie.ini


![after_applying_border](https://user-images.githubusercontent.com/12372772/107229028-9c12b680-6a1d-11eb-8847-99ae91043769.png)

**Comment by isaak654** [comment]
Fixed in Sbie Classic 5.48.5.
