### ISSUE TITLE
Installer bug of Classic version still present

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#495]
There is a bug in the setup of the Classic version 5.46.4, 5.46.5, 5.47.0 and 5.47.1. With a clean reinstallation (with previous uninstallation and reboot) certain registry values are no longer set (autostart, context menu).

Therefore, you must now always start "Sandboxie Control" manually from the start menu and then just click OK under "Configure" > "Windows Shell Integration". Afterwards everything is entered correctly in the registry again.

All previous versions always opened "Sandboxie Control" after installation and set the registry values automatically.

---

One more note: after uninstalling, the file "SboxHostDll.dll" still remains.

---

In addition, I noticed a possible typo: The new template [Template_FileCppy] should probably be called [Template_File**Copy**], right?

**Comment by jedimasterspaz** [comment]
Is this the same issue I reported earlier, that was closed but still plagues me; where the install hangs at the License.txt part of the install?

**Comment by APMichael** [comment]
Many thanks for fixing the bugs and the new version 5.48.0. 😃 

JFYI: After uninstalling, the file "SboxHostDll.dll" still remains.
