### ISSUE TITLE
Sandboxie-Plus x64 Portable version bug

### ISSUE THREAD

**Issue by StrollStars** [sandboxie-plus/Sandboxie#496]
System: Win7 64x / Win10 64x
Software: Sandboxie-Plus-x64-v0.6.5.exe / Sandboxie-Plus-x64-v0.6.0.exe

I run Sandboxie-Plus-x64-v0.6.5.exe as Extraction all files to a directory for portable use. Then I run SandMan.exe, everything's fine. But after I clicke the Global Settings, the program exited. I guess it is because the Sandboxie.ini is not loaded. The Sandboxie.ini is an empty file.

**Comment by DavidXanatos** [comment]
some issus with portable mode have been fixed some time ago including nto properly connecting
