### ISSUE TITLE
Sandboxie Steam Error

### ISSUE THREAD

**Issue by Bruggerr** [sandboxie-plus/Sandboxie#498]
System: Windows 7 64bit

With the new versions of Sandboxie, Steam no longer works.
The last working version = 5.46.1
![Steam](https://user-images.githubusercontent.com/78363852/106471828-55174500-64a2-11eb-84ed-ac7a75244f31.JPG)

**Comment by NewKidOnTheBlock** [comment]
Hmm.
I've just started my Steam Sandbox.
I could download a game and even run it, all while in SB Classic 5.47.0

**Comment by isaak654** [comment]
> 
> 
> Hmm.
> I've just started my Steam Sandbox.
> I could download a game and even run it, all while in SB Classic 5.47.0+
> 
> Could you create a fresh new box (that isn't based on any existing boxes) and try again?
> If that doesn't help, could you post your Sandboxie.ini?

Did you test it on Windows 7 64bit too? It could represent a different game-changer.

**Comment by Bruggerr** [comment]
I reinstalled the sandbox in the latest version and installed Steam in a new box. 
After the installation runs once, if you exit it and want to start it again later, the error message appears again and again.
It only runs smoothly in version 5.46.1.
My system = Windows 7 64bit
The Provisional.Windows.7.Drivers.zip is still needed for the installation

Contents of the ini


[GlobalSettings]

Template=7zipShellEx
Template=FireFix_for_Win7
FileRootPath=F:\Sandbox\%USER%\%SANDBOX%

[DefaultBox]

ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCppy
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Enabled=y

[UserSettings_172A02DE]

SbieCtrl_UserName=richard
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_WindowCoords=358,211,1082,615
SbieCtrl_ActiveView=40021
SbieCtrl_HideMessage=2314,steam.exe [3848 / 7]
SbieCtrl_BoxExpandedView=DefaultBox,Steam
SbieCtrl_UpdateCheckNotify=n


[Steam]

Enabled=y
ConfigLevel=8
BlockNetworkFiles=n
Template=SkipHook
Template=FileCppy
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl

**Comment by NewKidOnTheBlock** [comment]
I've spotted one that looks outdated:
 Template=WindowsFontCache

I'd recommend making a backup of your Sandboxie.ini
Then uninstall
Then install latest version
This should create a fresh default Sandboxie.ini without any leftovers.

**Comment by Coverlin** [comment]
Can confirm Steam is not working on newer versions than 5.46.1 on win7 64
same error

**Comment by Bruggerr** [comment]
I tested version 5.47.1, 1 day it worked. The next day the error was there again.
I removed the line Template = WindowsFontCache

**Comment by DavidXanatos** [comment]
mmh... is this issue present only on windows 7?
not on 10?
that complicates things as my dev environment is 10,
and remote debugging is a pain...
