### ISSUE TITLE
Sandman UI: driver version information

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#500]
The Sandman UI displays the "driver version" in the status bar -- well, at least initially, as that somehow disappears when you move your mouse over the main menu strip and doesn't come back...
However this still shows `5.46.0` in the latest release (0.6.5/5.47.0).
![screenshot](https://user-images.githubusercontent.com/78082344/106501879-f19e0f00-64c3-11eb-8682-afc32a262225.png)

It looks like the GetVersion API returns `MY_VERSION_COMPAT` instead of `MY_VERSION_STRING`:
https://github.com/sandboxie-plus/Sandboxie/blob/cb9b4b0f9f55636c4aa8c8880008a88b156653cc/Sandboxie/common/my_version.h#L24-L26

Is that behavior intended? (And even if it is, I think the display in Sandman should be changed as it might be kind of confusing...)

**Comment by DavidXanatos** [comment]
its intended yes i know i should change it although probably I'll just remove it.

**Comment by shearercole** [comment]
On latest Plus 1.3.2, the UI (both message area & About page) still displays 5.58.0 instead of 5.58.2 ?
What is the reasoning behind returning MY_VERSION_COMPAT instead of MY_VERSION_STRING ? Thanks!

```
|Time|         |Message|                                                             

19:07:09.409   Installation Directory: C:\Program Files\Sandboxie-Plus               
19:07:09.409   Sandboxie-Plus Version: 1.3.2 (5.58.0)     <-------------
19:07:09.409   Current Config: C:\WINDOWS\Sandboxie.ini                              
19:07:09.409   Data Directory: C:\Users\Administrator\AppData\Local\Sandboxie-Plus     
```
