### ISSUE TITLE
3-byte UTF-8 characters corrupt sandboxie.ini on save

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#503]
Sandboxie Service corrupts sandboxie.ini on write when the configuration contains a larger number of 3-byte UTF-8 characters.

To re-assure users, you need a fair number of such characters to trigger this.

Repro:

* Install v0.6.5
* Edit sandboxie.ini
* Ensure sandboxie.ini is in UTF-8 BOM format
* Add one or several `RecoverFolder=xxx` settings and include a larger sequence of 3-byte UTF-8 characters, for example, U+8888 ( 袈 ). The number of characters you need depends on the size of your sandboxie.ini file. For a newly installed "empty" file, you will need around 750 characters.
* Save the ini
* Plus reloads ini
* In Plus edit a setting for your sandbox
* Save
* File is corrupted. Errors show.

**Comment by DavidXanatos** [comment]
👍
