### ISSUE TITLE
Sandboxie-Plus silently drops first config edit after Sandboxie Service restarts

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#506]
v0.6.5

* Start Plus
* System > Services: Stop and Start Sandboxe Service
* Edit any sandbox setting. Save.
* Actual behaviour: The change is silently dropped.
* Desired behaviour: Error message, or auto-connect and save on first try
* Edit and save again works fine

Similarly, while the service is stopped, Plus silently ignores sandbox settings edits.

Notes:
* Creating a new sandbox shows an appropriate error (great)
* Stopping the service kills Sandboxie Classic  (fine by me)

**Comment by isaak654** [comment]
I'm not able to reproduce this on 0.9.2, but I need further confirmation.

**Comment by typpos** [comment]
Isaak, feel free to close if it can't be reproduced easily on 0.9.2.
