### ISSUE TITLE
Versioning Typo In Provisional Windows 7 Drivers For Sandboxie Classic v5.47.1

### ISSUE THREAD

**Issue by TeslaMagic** [sandboxie-plus/Sandboxie#507]
The Provisional.Windows.7.Drivers.zip contains the following:
SbieDrv.sys.5.47.0.x64.rc4
SbieDrv.sys.5.47.0.x86.rc4

They should be:
SbieDrv.sys.5.47.1.x64.rc4
SbieDrv.sys.5.47.1.x86.rc4

You cannot install v5.47.1 without changing the file names of the drivers.

**Comment by NewKidOnTheBlock** [comment]
The driver hasn't been updated in SBClassic 5.47.1
Driver is still at 5.47.0
![sbiedrv](https://user-images.githubusercontent.com/12411527/106568339-74aa7e00-6533-11eb-9657-6bf8c7b84777.png)

**Comment by DavidXanatos** [comment]
I have re uploaded the driver package now it should befine
