### ISSUE TITLE
In Traditional Chinese environment, Auto language detection got wrong

### ISSUE THREAD

**Issue by TragicLifeHu** [sandboxie-plus/Sandboxie#509]
(For Sandboxie-Plus only)

In Traditional Chinese environment (zh-tw), the language will be detected as Simplified Chinese (zh-cn). This might caused by the profile name of Simplified Chinese: zh.

zh is just means Chinese, with no parameters (tw or cn). In this case, Traditional Chinese will be directed to Simplified Chinese first.

For solution, I think it is better to rename language profile zh to zh-CN to avoid further issues.

Thanks in advance.

**Comment by DavidXanatos** [comment]
yea will do that asap, thanks for the heads up
