### ISSUE TITLE
Features questions

### ISSUE THREAD

**Issue by victorca25** [sandboxie-plus/Sandboxie#51]
I’ve been reading your roadmap of ideas and it’s really impressive, great ideas all over the place.

From reading them, I also have a couple of questions just to know if they are feasible:
- about the portable sandboxes, would it be possible to compact (zip?) the sandboxes for easier migration? For example, like Thinstall/ThinApp does that generates a single executable (and afaik, deflates on scratch space when executed). This could also morivate a behavior similar to the distribution of Docker images in some sort of hub (like portableapps.com). I currently use sandboxie in combination with Python virtualenv to manage different environments and app versions and this sounds interesting 
- something, similar would be sandbox snapshotting, to easily revert to a prior version. A simple way could be by compacting the sandbox. The problem would be the data duplication, but I don’t know if an alternative is too complicated 
- lastly, about the networking, if not including the firewall functionality directly, did I understand correctly that your idea is to attach a virtual networking device to each sandbox? That would be very interesting

**Comment by DavidXanatos** [comment]
1. zipping would be possible but IMHO the overhead would be to large.

2. some thign like this is on my todo, it would behave liek sandboxie behaves towards the system, when you create a snapshot you get a new root dir and all new changes go there and from the apps view point overwrite the old data.
The sandboxed registry would however be copied enteirly

3. Not really just in that sense as the ap would see a virtual mac but it would not be a functional device, the traffic would go through its regular route through the real device.

**Comment by victorca25** [comment]
Thanks for your reply!

> 1. zipping would be possible but IMHO the overhead would be to large.
What if it's only used for portability? i.e., copy a sandbox from one computer to another. The use case is for example to share a development environment with all the required dependecies

> 2. some thign like this is on my todo, it would behave liek sandboxie behaves towards the system, when you create a snapshot you get a new root dir and all new changes go there and from the apps view point overwrite the old data.
>    The sandboxed registry would however be copied enteirly
Aha! I didn't know that, that's really interesting, great to know!

> 3. Not really just in that sense as the ap would see a virtual mac but it would not be a functional device, the traffic would go through its regular route through the real device.
I understand. I will look for options on how to do something like that, it can be really useful for some cases.

Cheers!!

**Comment by DavidXanatos** [comment]
> I understand. I will look for options on how to do something like that, it can be really useful for some cases.

What use case exactly do you have in mind?

**Comment by victorca25** [comment]
Initially, just to experiment, but I was thinking about port forwarding rules to, for example, host isolated API endpoints in separate sandboxes. Maybe I'm mixing it too much with containers, but TBH, containers in Windows are not extremelly efficient hehe.

**Comment by Vincent14** [comment]
@victorca25 did you manage to port forward any service hosted in a box to an external computer?
