### ISSUE TITLE
New templates in Sandboxie.ini

### ISSUE THREAD

**Issue by silvestron** [sandboxie-plus/Sandboxie#516]
Thank you, David, for all your work (and everyone else who's contributing) and adding new features to Sandboxie!

I noticed

```
Template=SkipHook
Template=FileCppy
```

added to every sandbox in the Sandboxie.ini file in the last updates. I tend to move the templates to the global settings because I usually edit the ini file. Would these templates work if I move them under the global settings? I'm asking because I've noticed in Sandboxie-Plus some thing don't work in the global settings, like `BorderColor`, however I'm using Classic.

**Comment by DavidXanatos** [comment]
Yes that should work there just fine
