### ISSUE TITLE
Path of Exile (F2P game) VULKAN renderer mod

### ISSUE THREAD

**Issue by Rngexile** [sandboxie-plus/Sandboxie#517]
The F2P game Path of Exile (https://www.pathofexile.com/) **runs fine in graphics renderer mod VULKAN (or DirectX11) under Sandboxie-Plus v0.55 and v0.6.0 (and 5.33.6 Sophos version)** with DefaultBox or my usual dedicated box.
VULKAN mod allows a general better experience and will later be the main supported renderer.

**The game does works in DirectX11 mod with v0.6.5.
But it does not works in VULKAN mod with v0.6.5 in either DefaultBox or my usual dedicated box.** 
I didn't see any meaningfull diff between ressource monitor logs of v0.6.0 and v0.6.5.

Steps to reproduce with sandboxie-plus v0.6.5 : 
1-install PoE game (needs internet access and download it)
2-Launch the Client.exe or directly PathOfExile_x64.exe (in x64 OS) in a Defaultbox : by default the game will start in DirectX11 mod
3-Go in Options > Graphics > Display Settings > Renderer and change to use VULKAN
4-**Click the "Save" button ...and wait indefinitely. The game freezed. The PoE' process have to be manually terminated.** 

If you try to configure the VULKAN renderer mod in the product_config.ini of the game, oustide, sandboxie-plus, then launch the game in defaultbox, then the game will start but still freez before the login screen. The PoE' process have to be manually terminated. 

OS : Windows 10 x64 20H2 19042.746 (lasts updates)
GPU : NVIDIA Geforce 1070 with latest graphics drivers 461.40 (tried with few months old 456.71 : does not changes anything)

Thank you for your hard work on Sandboxie-plus !

**Comment by NewKidOnTheBlock** [comment]
Generally speaking, Sandboxie works with Mantle and Vulcan games.
As I don't have that game, I can't test it.

**Comment by DavidXanatos** [comment]
Could you please test if it worked with Release v0.5.5
if it is what i thing it is that 0.5.5 shouldn't work eider.

you can now enforce the 0.6.0 behavior on a per process basis like
RpcMgmtSetComTimeout=program.exe,n
That should than solve the issue.

**Comment by DavidXanatos** [comment]
PS: 0.6.7 should also fix that btw

**Comment by NewKidOnTheBlock** [comment]
So I started my sandboxed Steam, downloaded 35GB, started it and then switched to Vulkan:
![20210203172919_1](https://user-images.githubusercontent.com/12411527/106788019-b9780700-6650-11eb-97a5-e30dff0dfbba.jpg)
I even restarted the game to make sure it's actually using Vulkan.

**Comment by Rngexile** [comment]
Thank you for your test NewKidOnTheBlock. The diff between us was v0.6.5 VS v0.6.7 and NVIDIA VS AMD GPU. And both were involved, imho.

I've updated Sandboxie-Plus to v0.6.7, re-tested and resolved my problem. Sandboxe-Plus asked me something i didn't expect and i think it may not be an expected behaviour (from a user perspective).

So, with v0.6.7, and Path of exile launched in my install box (tried too with defaultbox and others), i changed the renderer from DirectX11 to Vulkan, i waited few seconds ... then i've had a prompt from sandboxie-plus to copy two small files in the box : 
![sandboxie_prompts](https://user-images.githubusercontent.com/78466348/106815230-d70a9800-6673-11eb-8631-d7c8428568e1.png)

I don't know why sandboxie-plus asked me that because i have a copy limit of +40GB and there were already files in GLCache repertories inside the box.

Anyway, after a manual copy-paste from these files inside the box, Vulkan worked. I have then tested to let sandboxie copy the files (in another poe box) and Vulkan worked too.
It seems to me that for whatever reason, when i updtated sandboxie-plus from v0.5.5 (and v0.6.0) to v0.6.5+ the GLCache files needed to be changed and the changed were proposed by sandboxie-plus in v0.6.7. 

Now, i can even delete the repertories under GLCache in the real filesystem, then launch PoE within a sandbox and it recreate the repertories and the 2 small files (purged) inside the box and everything still works with Vulkan.

Thank you for your support and long live to Sandboxie-Plus !

**Comment by NewKidOnTheBlock** [comment]
I'd recommend adding the line
`OpenPipePath=X:\Games\SteamSB\`
to your Steambox. That way, you don't have to shovel Terabytes of data around.

**Comment by Rngexile** [comment]
Nice catch typpos, thank you !

Indeed NewKidOnTheBlock, openpipepath to installation game folder (steam or dedicated poe client) is the proper way and i use it since few years (playing poe+sandboxie since 2013 XD). I've let 40GB file copy size limit when i reinstalled PoE game last year with the sophos sandboxie version 5.336 and didn't want to check the size of GPU cache files and all the other stuff outside the installation game folder.
Same logic for my other boxes to run the poe client, but without the openpipepath or openfilepath ofc.
That way i can install/update the PoE client with a dedicated BoxInstall then play PoE with BoxPoE1, BoxPoE2, ... each box with its own set of configuration, profiles, shader cache ...

[Example config for Boxes.txt](https://github.com/sandboxie-plus/Sandboxie/files/5926516/Example.config.for.Boxes.txt)

**Comment by Sawtaytoes** [comment]
I had the same issue. Baldur's Gate 3 isn't running in Vulkan mode with Sandboxie. Something about WerFault. Might be unrelated.
