### ISSUE TITLE
Chrome cannot make Facebook Messenger call 

### ISSUE THREAD

**Issue by bean224466** [sandboxie-plus/Sandboxie#518]
Facebook Messenger calls (video or audio) cannot be initiated from Chrome or Brave in Sandboxie Plus. 
The only error message comes from Facebook saying "Something went wrong".

UPDATE: After installing Sandboxie Plus V.0.7 the error message in Facebook Messenger asks to allow camera and microphone access but they are already allowed. It seems that Sandboxie is blocking access.

Windows 10 Pro 64-bit, v 20H2
Brave v1.20.103 Chromium: 88.0.4324.152

**Comment by isaak654** [comment]
Please verify if this was fixed in Sandboxie Plus V.0.7.1.

**Comment by bean224466** [comment]
Alas, no. I checked it with Chrome, Opera, Vivaldi and Brave. "Something went wrong" is all I get.

**Comment by DavidXanatos** [comment]
what was the last version of sandboxie where this was working?

**Comment by bean224466** [comment]
Sorry, I have no idea.

**Comment by DavidXanatos** [comment]
can you try to find out by testing with older versions?

**Comment by bean224466** [comment]
I tried versions 0.5.5 and 0.6.7
Neither worked

**Comment by bill6248** [comment]
> I tried versions 0.5.5 and 0.6.7
> Neither worked

i met the same problem. Have you found a solution？

**Comment by isaak654** [comment]
Microphone access in MS Edge has been fixed for me with Plus v1.5.3: https://github.com/sandboxie-plus/Sandboxie/issues/1208#issuecomment-1307116424

In case of further problems, please refer to that issue.
