### ISSUE TITLE
Software Compatibility - all entries are unticked by default

### ISSUE THREAD

**Issue by darkred** [sandboxie-plus/Sandboxie#521]
Using Sandboxie-Plus 0.6.7 in win10 x64

I've noticed after Sandboxie Plus installation and on every system launch
that all entries in the "Software Compatibility" window are unticked by default (and there's no checkbox to check all at once),
and when you click Ok, no configuration entry is applied - instead, the window will reappear on next system launch.

<details>
<summary>Screenshot</summary>

![2021-02-03_192816](https://user-images.githubusercontent.com/723651/106785480-1cb86800-6656-11eb-8f6f-344220621fc8.jpg)
</details>

The displayed message:
> Click Ok to apply configuration settings, which will improve compatibility with these settings.

suggests that just pressing Ok would apply all configuration settings.

---

For reference, in previous versions (pre open-source),
all entries in the list were all ticked by default (you had to doubleclick each one to toggle it),
and pressing Ok would apply all configurations settings.

<details>
<summary>Screenshot</summary>

![2021-02-03_192717](https://user-images.githubusercontent.com/723651/106785943-a9fbbc80-6656-11eb-9106-9556f2523f78.jpg)
</details>

&nbsp;
Thank you

**Comment by DavidXanatos** [comment]
fixed in  the next plus build

**Comment by darkred** [comment]
Thank you for fixing this.

**Comment by darkred** [comment]
@DavidXanatos 

update: although in the new build, the entries are indeed ticked by default, pressing Ok doesn't 
unfortunately the "Software Compatibility" window reappears on every windows start:
![](https://user-images.githubusercontent.com/723651/110209003-d6436c80-7e92-11eb-8d48-1532a3cbbc9e.jpg)

STR
I updated to Sandboxie-Plus 0.7.2 (in win10 x64).
I pressed Ok at the "Software Compatibility" window.
On every windows restart, the "Software Compatibility" window keeps on reappearing. 

I even tried installing Sandboxie-Plus in a windows 10 virtual machine, and it occurs consistently.

---

By the way, I'd like to make a suggestion that came up:
when the Sandboxie-Plus installer completes, to automatically launch the Sandboxie-Plus control (the system tray icon). 
This is the behavior of Sandboxie classic, and what I am accustomed to.
Currently you have to launch it manually,
Not seeing it in the system tray as expected after installation, 
might give the wrong impression that a problem has occurred/it crashed.
