### ISSUE TITLE
Resource access improvement

### ISSUE THREAD

**Issue by nulledone** [sandboxie-plus/Sandboxie#529]
Top one is current, below is my suggestion.

![Resource Access](https://user-images.githubusercontent.com/29547468/106915116-96eff780-66fd-11eb-9f66-f9fd55271cd5.jpg)

**Comment by DavidXanatos** [comment]
I like the current more compact design

**Comment by nulledone** [comment]
It is actually less compact currently in my opinion. You click another button for something to unfold.

I advise you to rethink maybe. Some users more dependant on adding file and folder whereas other's just use the key itself.
