### ISSUE TITLE
Microsoft Teams: SBIE2205 Service not implemented CredReadA

### ISSUE THREAD

**Issue by Francesco-Cocchioni** [sandboxie-plus/Sandboxie#530]
Hello,

i got this error: 

SBIE2205 Service not implemented CredReadA

when i try to use Microsoft Teams with sandbox. This error occurred after inserting the account email in the first screen after launching Teams.

Step to reproduce it:
Install Teams inside the sandbox (No problem)
Launch Teams from the sandbox (No problem)
Insert the email and click log in.

At this point the error appears in the notification windows, and Microsoft Teams doesn't ask for the password but instead show a windows saying that a problem has occurred.

I'm using version 0.6.7 of Sandboxie Plus. 

Is it possibile to fix this?

Thanks

**Comment by DavidXanatos** [comment]
Just a guess but try opening credential storage or protected storage

![grafik](https://user-images.githubusercontent.com/3890945/106932658-4a65e580-6718-11eb-8098-38b4a54887aa.png)

**Comment by Francesco-Cocchioni** [comment]
Unfortunately the problem is not solved.

The error: "SBIE2205 Service not implemented CredReadA" disappeared, but Teams shows the same error windows (error code 6).

Attached you can find microsoft Teams logs; it seems a problems with SSO
[Log.txt](https://github.com/sandboxie-plus/Sandboxie/files/5927615/Log.txt)

**Comment by DavidXanatos** [comment]
is the problem stil present with version 0.7.0?

**Comment by DavidXanatos** [comment]
On my system it seams to work just fine I can log without issues.
May be you are using a MSFT windows account instead of a local one, and that's the cause of the issues.
In which case I would recommend to switch to a local account that has better privacy aspects anyways.

**Comment by Francesco-Cocchioni** [comment]
With version 0.7.0 i can log in and use the app.

I found two major problems when using the app:

- Under settings-->devices no system microphone or speaker is shown at first. After about 10-15 minutes they appears; until then no call are possible.

- When the devices appear, the next time Teams is opened, it ask again for the credential; if you log in and close the program after few minutes (before the devices appear) then at the next start it automatically log in.

Looking at the log, for the second problem the cause seems the SSO again:

`warning -- SSO: correlationId - wamMigration Set logout to true, forces login during next app restart.`

Teams is based on Electron which use Chromium; should some Chrome compatibility settings be added also to Teams?

I use a local account on my PC.

**Comment by alasalto** [comment]
Hello, 
The same goes for me. I got this error. Installation was successful using previous version of Sandboxie plus.




![SBxie_ServNotImplem](https://user-images.githubusercontent.com/79168126/108114435-133cf000-7099-11eb-9824-f498201f9174.jpg)

**Comment by DavidXanatos** [comment]
try adding:
OpenIpcPath=\RPC Control\AudioClientRpc
OpenDevCMApi=y
for the sound and webcamisss

and 

SpecialImage=chrome,Teams.exe

for it to get the chrome treatment


@alasalto 
installation of themes into the sandbox?
so on 0.6.7 it works and on 0.7.0 it fails?

**Comment by alasalto** [comment]
@DavidXanatos 
First things first, thank you for your support and the time you took developing and improving Sandboxie software as well as giving guidande to users.
Unfortunately that error persists.
The above-mentioned issue show up during the setup of 'FreeFileSync', a sync software. Error appears at the end of the installation routine, when it is trying to create a file, 'install.dat' by means of a windows powershell routine.

**Comment by Francesco-Cocchioni** [comment]
I tried adding
OpenIpcPath=\RPC Control\AudioClientRpc
OpenDevCMApi=y

to the "Edit init section" of the sandbox. Unfortunately this don't solve the problem; the devices did not appears.

Regarding 
SpecialImage=chrome,Teams.exe
it generate an error on start:
![image](https://user-images.githubusercontent.com/3011259/108421946-351fa980-7236-11eb-8fd8-38a4fa5527d3.png)

**Comment by alasalto** [comment]
@DavidXanatos
Just tried SB-plus v0.71 to install 'FreeFileSync' with no successful results. It's still no possible to install that software into a Sanboxie own sandbox
I was tinkered with many options with no result. 0.67 was the last build that showed results as expected, flawlessly. Please bear with me!

**Comment by isaak654** [comment]
> 
> 
> @DavidXanatos
> Just tried SB-plus v0.71 to install 'FreeFileSync' with no successful results. It's still no possible to install that software into a Sanboxie own sandbox
> I was tinkered with many options with no result. 0.67 was the last build that showed results as expected, flawlessly. Please bear with me!

I can riproduce the same FreeFileSync issue in Sandboxie Classic 5.48.5:

![freefilesync](https://user-images.githubusercontent.com/12372772/108722341-55e04b80-7523-11eb-8045-5f352f85bb42.png)

**Comment by d4k0** [comment]
Same problem here with FreeFileSync. It seems to have started with version 0.7.0.

**Comment by d4k0** [comment]
@alasalto @isaak654 
It seems that `install.dat` is now created correctly with Sandboxie Plus 0.7.2, although the error message is still displayed (but I think this was also the case in older versions).

**Comment by DavidXanatos** [comment]
> 
> It seems that `install.dat` is now created correctly with Sandboxie Plus 0.7.2, although the error message is still displayed (but I think this was also the case in older versions).

can you please verify this, is the issu introduced on 0.7.0 now gone?

**Comment by d4k0** [comment]
@DavidXanatos 
Yes, the problem with FreeFileSync and ```install.dat``` not being created is fixed. There is still a message about a not implemented service, but this was also the case in older versions (even in the original Sandboxie) and doesn't corrupt the installation of FreeFileSync.

However, I can't say anything about the CredReadA problem.

**Comment by alasalto** [comment]
@DavidXanatos @d4k0 
Thank you. Just tried it out w/ Sandboxie Plus 0.7.2 on a Windows 10 Pro v2004. Now, it is possible installation to be completed with minor issues as regard of a popup message showing up about a service not implemented during any of the installation stages.
