### ISSUE TITLE
Option to disable Sbie Message

### ISSUE THREAD

**Issue by GunGunGun** [sandboxie-plus/Sandboxie#531]
Some applications spam Sbie Messages and usually crash SandMan.exe after a while, can you please add an option to disable Sbie Message or is there an option to disable it in Sandboxie.ini config.

Screenshot: https://i.imgur.com/qWSjz8v.png

Thanks!

**Comment by typpos** [comment]
Please try the latest version, 0.6.7, instead of 0.2.2. There is a "dismiss" button in a new "Sandboxie-Plus Notifications" window. Alternatively, use ini setting `SbieCtrl_HideMessage`.

![image](https://user-images.githubusercontent.com/28550406/107002897-0211fa80-67e0-11eb-88e3-31f1f5b85a1e.png)

**Comment by Coverlin** [comment]
^ Where does the OP says he wants to turn off Plus Notifications or Messages from sbie in classic ?
Sandman's messages log (Advanced view) is not affected by the classic hide message option , and personally would like for David to keep that as an option in the future for people who still want to know if theres a message but do not want plus/classic popups

**Comment by GunGunGun** [comment]
@typpos I tried both v0.5.5 and 0.6.7 - Portable Installation, both just doesn't work on my Windows 7 that's why I have to stick with v0.2.2.

No DefaultBox, not connected: https://i.imgur.com/I4azAys.png
Service doesn't start: https://i.imgur.com/uKdmQzk.png
Driver is not working: https://i.imgur.com/x3u34xG.png

I will open a new issue for this problem.
