### ISSUE TITLE
[Sandboxie-Plus v0.6.7][Portable Installation][Windows 7 64bit] Service can't start, driver warning and no DefaultBox

### ISSUE THREAD

**Issue by GunGunGun** [sandboxie-plus/Sandboxie#535]
I tried to install Sandboxie-Plus 0.6.7 - Portable Installation, and I can't get it to work on my Windows 7 64-bit, but if I downgrade to Sandboxie-Plus v0.2.2 - Portable Installation, everything works fine.

No DefaultBox, not connected: https://i.imgur.com/I4azAys.png
Service doesn't start: https://i.imgur.com/uKdmQzk.png | I tried to start Sandboxie Service from services.msc, still no luck: https://i.imgur.com/3fjMzKq.png
Driver is not working: https://i.imgur.com/x3u34xG.png

Please let me know if I can provide more information. 

Thanks.

**Comment by Coverlin** [comment]
![Untitled](https://user-images.githubusercontent.com/34079190/107130632-23eea880-68d8-11eb-8a8a-82b0005c9abd.png)

**Comment by GunGunGun** [comment]
@Coverlin Sorry but I don't know how to install Provisinal Window 7 Driver with Sandboxie Plus Portable Installation.
I tried to rename SbieDrv.sys.5.46.4.x64.rc4 in the zip file to SbieDrv.sys and replaced SbieDrv.sys in Sandboxie Plus folder but didn't work.

**Comment by Coverlin** [comment]
> @Coverlin Sorry but I don't know how to install Provisinal Window 7 Driver with Sandboxie Plus Portable Installation.
> I tried to rename SbieDrv.sys.5.46.4.x64.rc4 in the zip file to SbieDrv.sys and replaced SbieDrv.sys in Sandboxie Plus folder but didn't work.

You have to use KmdUtil.exe inside the extracted Sandboxie Plus folder
Rename the downloaded prov driver SbieDrv.sys.5.47.1.x64.rc4 in this case to SbieDrv.sys.rc4 and place it in the Sandboxie Plus folder
Do a or b
a)  Use notepad or any text editor and type `KmdUtil.exe rc4 SbieDrv.sys.rc4` Save it as .bat inside the Sandboxie Plus folder and then run it
b) Right click on Kmdutil.exe and click create shortcut , right click the shortcut , click properties ,  at shorcut target add `rc4 SbieDrv.sys.rc4` , apply and use the shortcut
![1](https://user-images.githubusercontent.com/34079190/107147315-fea07f80-6955-11eb-9342-3fc6ddb82ee9.png)

You can then use sandman maintenance to connect

**Comment by isaak654** [comment]
I would suggest to include a readme.txt or a premade install.bat file in the zip archive.

**Comment by DavidXanatos** [comment]
> I would suggest to include a readme.txt or a premade install.bat file in the zip archive.

good idea will do that with the next build 
although the setup should normally do that and ask for the unpacked package zip on its own when ran in a windows 7 system

**Comment by DavidXanatos** [comment]
now the package comes with an install batch script
