### ISSUE TITLE
Sandboxed app fails to reset its registry settings

### ISSUE THREAD

**Issue by GH01** [sandboxie-plus/Sandboxie#539]
Hi,
I'd like to know if this ancient issue can be resolved:
https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic72317231.html

**Comment by DavidXanatos** [comment]
mmh... yea.. the entire registry part was a bit neglected in the past, it also fails to rename registry keys, although almost no app ever does that except regedit.exe
I will look into fixing that in due time but its not high priority.

**Comment by DavidXanatos** [comment]
this should be resolved when using delete-v2 scheme in sandboxes
