### ISSUE TITLE
Disable Sandboxie-Plus Notifications

### ISSUE THREAD

**Issue by BrianSDX2** [sandboxie-plus/Sandboxie#540]
Is there an option to completely disable Sandboxie-Plus notifications. I am not concerned with the error that is being displayed or any errors for that matter. If this functionality is not in place could it be added to a future release?

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/107225784-88655100-6a19-11eb-8c1c-9c62abdb78c8.png)

its already in.

When this is unchecked, no SBIE messages will trigger a pop up,
that said if there is something to decide, like allow/deny migration or allow/deny internet access etc... the pop up will be shown.

It will also be shown (and auto hide once done) when a large file is migrated to the sandbox, as that hangs the application on which behalf it is being done untill its finished, a progress indicator showing the copy progress seamed expedient.
