### ISSUE TITLE
Event ID 4625 when executing chrome in the sandbox

### ISSUE THREAD

**Issue by Yituo3712VP** [sandboxie-plus/Sandboxie#543]
An error occurs every 2 minutes when starting the chrome browser in the sandbox 
Event ID: 4625
Account For Which Logon Failed:
Security ID: NULL SID
Account Name: ADMIN
Account Domain:
Failure Information: Failure Reason: Unknown user name or bad password
Status: 0xc000006E
Sub Status: 0xc000006E
Processing information:
Caller handler ID: 0x2368
Caller handler name: C:\Program Files\Google\Chrome\Application\chrome.exe

The error log is increased once in about 2 minutes
10:30:26,10:32:51,10:34:09,10:36:41
The browser is not executed in the sandbox, and event logging errors stop increasing.
Sandboxie Version 5.47.0 x64
Chrome Version  88.0.4324.150

**Comment by DavidXanatos** [comment]
in which log do you get this system or application?

also i cant reproduce it her locally.

**Comment by Yituo3712VP** [comment]
> in which log do you get this system or application?
> 
> also i cant reproduce it her locally.

From windows event log
<EventData>
  <Data Name="SubjectLogonId">0x46590</Data> 
  <Data Name="TargetUserSid">S-1-0-0</Data> 
  <Data Name="TargetUserName">ADMIN</Data> 
  <Data Name="TargetDomainName">ADMIN</Data> 
  <Data Name="Status">0xc000006e</Data> 
  <Data Name="FailureReason">%%2313</Data> 
  <Data Name="SubStatus">0xc000006e</Data> 
  <Data Name="LogonType">2</Data> 
  <Data Name="LogonProcessName">Advapi</Data> 
  <Data Name="AuthenticationPackageName">Negotiate</Data> 
  <Data Name="WorkstationName">ADMIN</Data> 
  <Data Name="TransmittedServices">-</Data> 
  <Data Name="LmPackageName">-</Data> 
  <Data Name="KeyLength">0</Data> 
  <Data Name="ProcessId">0x267c</Data> 
  <Data Name="ProcessName">C:\Program Files\Google\Chrome\Application\chrome.exe</Data> 
  <Data Name="IpAddress">-</Data> 
  <Data Name="IpPort">-</Data> 

Same Event log 4625 Audit Failure
02/27/2021 01:13:58 Unknown user name or bad password
02/27/2021 01:22:37 Failed login
02/27/2021 01:36:12 Unknown user name or bad password

Chrome version 88.0.4324.190
Sandbox 5.47.0  classic x64
