### ISSUE TITLE
UTF-8 (with and without BOM) problem

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#544]
Name group: `Мессенджеры`
![image](https://user-images.githubusercontent.com/25817412/107462983-fee48900-6ba8-11eb-892b-cf46c7504d2d.png)

Names groups: `Менеджеры закачек` and `Браузеры`
![image](https://user-images.githubusercontent.com/25817412/107463206-5551c780-6ba9-11eb-8e4a-fc49485a7d5f.png)

**Comment by Zymlex** [comment]
It looks like Sandboxie.ini got corrupted at some point. Changing the encoding to UCS-2 BE with BOM and back to UTF-8 with BOM and then restarting SandMan helped, but I don't know how long it will last.

**Comment by DavidXanatos** [comment]
how did that happen?
do you have a copy of the broken file?

**Comment by Zymlex** [comment]
Similar problem has not appeared. As I see SandMan always save UTF-8 BOM file as UCS-2 LE BOM.
