### ISSUE TITLE
Quick Question about Old Sandboxie

### ISSUE THREAD

**Issue by Jimmy03** [sandboxie-plus/Sandboxie#546]
I just installed this months Windows updates for 1909, and now after every restart i am prompted to allow

service control manager configuration tool / SC.EXE "start SbieSvc" 

This is for old Sandboxie 5.28, I guess something changed with Windows. I chose not to allow it, just to be safe and Sandboxie systray icon was flashing with exclamation mark issue. (no service)

So I think I will just keep Sandboxie closed for now, backup the ini, uninstall it, and then install SB Plus

**Comment by bastik-1001** [comment]
I don't see that there is a question, but Sandboxie needs the service to communicate with the driver to provide the isolation features. I am not sure why you get repeated prompts to allow it, if it was already present and Sandboxie was not installed again.

**Comment by DavidXanatos** [comment]
That issue may arise when windows decides to remove the driver. Just re installing sbie should fix the issue
