### ISSUE TITLE
Hardware Acceleration not working in Discord

### ISSUE THREAD

**Issue by JustinTimberland** [sandboxie-plus/Sandboxie#547]
Just as the title says HW Acceleration doesn't work, when turned on and the program is restarted the UI doesn't render. I have an Nvidia GPU and I am on the latest windows update 20H2 Feb 2021.

I am happy to give any extra info required

**Comment by DavidXanatos** [comment]
pleas check out this issue https://github.com/sandboxie-plus/Sandboxie/issues/440 and the there presented workaround does it solve your issue as well?

**Comment by JustinTimberland** [comment]
No sadly no difference, the only thing that changed anything was the other option with a custom manifest but then other issues seem to arise and the program doesn't want to connect online. Maybe this is something that could be fixed with some sort of app template?

**Comment by DavidXanatos** [comment]
you mean this one:
![grafik](https://user-images.githubusercontent.com/3890945/107709148-09944080-6cc5-11eb-8085-6b14f885adc1.png)

with it enabled the UI works but other things fail?

**Comment by JustinTimberland** [comment]
PID 3412: SBIE2164394153: ; 
PID 3412: SBIE2164394155: Discord.exe [Discord5]; 
Discord.exe (9368): SBIE1090652213: ConnectPort (C0000022) access=001F0000 initialized=1; Unnamed object

These messages come up and the program starts asking for admin access, If I give it access it then fails to connect online and is stuck on "checking for updates" even though its fully updated.

**Comment by zingmars** [comment]
I have the same situation. Enabling dummy Manifest files allows discord to start, but the updater will ask for admin permissions. If I don't allow them, the updater will fail to connect. It will work if I give it administrator privileges, but that's obviously not desirable.

**Comment by DavidXanatos** [comment]
this was fixed in tne last build
