### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by MFaisalZaki** [sandboxie-plus/Sandboxie#55]
Dear Sir,

I hope everything is going great with your project.
I'm sorry to say that but when I downloaded your latest release and tried to build it on windows 10 it fails. 

So is there a step by step build process or is it a must to build it on windows 7 with the given driver kit.

Thanks.

**Comment by DavidXanatos** [comment]
I use windows 10 my self, but the windows 7 driver kit is a must, it installs just fine on win 10.
For the SandMan component you will also need the Qt Framework i used version Qt5.11.2 but any newer should also work.
