### ISSUE TITLE
Not working when elevation is needed

### ISSUE THREAD

**Issue by opus-x** [sandboxie-plus/Sandboxie#550]
Sandboxie works as expected when running an app without elevation. When elevation is needed Sandboxie returns error 346 (blocked by parental guidance). I have an (online Microsoft) administrator account and parental guidance is enabled only for two other accounts on the system. 

Sandboxie-plus v0.6.7 (5.47.1), and previous versions
Windows 10 20H2 build 19042.789

**Comment by DavidXanatos** [comment]
please refer to: https://github.com/sandboxie-plus/Sandboxie/issues/3318
