### ISSUE TITLE
[Isolation enhancement] Block elevated processes from manipulating local user accounts

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#553]
It seems that Sandboxie fails to block sandboxed elevated processes from manipulating local user accounts.

For example, by running `net user USERNAME PASSWORD` from an elevated command prompt it is possible to set a new password for *any* local user account on the machine.
It is also possible to modify group membership, e.g. adding/removing user accounts from the local Administrators group.
Also you can completely remove a user with `net user USERNAME /DELETE`.

![screen](https://user-images.githubusercontent.com/78082344/107800948-bc18e180-6d5f-11eb-8b80-88ee212316bb.png)
(Those commands really affect the "real" user account and are not isolated in the sandbox)

I think that sandboxed processes should definitely be disallowed from making such changes...

**Comment by DavidXanatos** [comment]
There is a temporary workaround, 
ClosedIpcPath=\RPC Control\samss lpc
collateral damage unknown, but it solves the issue

I'll have to add a IPC port filter for that one to properly only block requests that are problematic while allowing read only queries
