### ISSUE TITLE
Chrome/Edge does not restore tabs if ran out of Sandbox before

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#558]
Hi,

Since Chrome introduced changes in user profiles, Sandboxed Chrome has issues with restoring tabs from previous session.

How to reproduce:
1. Create new Sandbox, run Chrome in it, set up to 'continue where you left off' on startup , open any webpage and quit Chrome
2. Run Chrome outside of Sandboxie and close it
3. Open Chrome sandbox in the same sandbox like in point 1. Chrome will not restore the session correctly.

Chrome used to store user profile in C:\Users\<username>\AppData\Local\Google\Chrome\User Data\Default
For over 6 months it stores it in C:\Users\<username>\AppData\Local\Google\Chrome\User Data\Profile 1

**Comment by isaak654** [comment]
> 
> Chrome used to store user profile in C:\Users<username>\AppData\Local\Google\Chrome\User Data\Default
> For over 6 months it stores it in C:\Users<username>\AppData\Local\Google\Chrome\User Data\Profile 1

I installed Chrome a month ago (in a clean Windows 10 install) and my user profile was located in the default folder.

**Comment by NewKidOnTheBlock** [comment]
Chrome Portable does: https://portableapps.com/apps/internet/google_chrome_portable

**Comment by mysteriously** [comment]
I have crean Chrome profile outside of Sandboxie. Then I have multiple sandboxes to run the chrome. Every time I start Chrome outside of sandbox, I have issues with lost session in sandboxed chrome.

How should I fix it?

**Comment by isaak654** [comment]
> 
> 
> I have crean Chrome profile outside of Sandboxie. Then I have multiple sandboxes to run the chrome. Every time I start Chrome outside of sandbox, I have issues with lost session in sandboxed chrome.
> 
> How should I fix it?

I've already reported something similar in issue #370... no fix at the moment.

**Comment by DavidXanatos** [comment]
I think the proper solution to this behavior is to set the chrome profile folder as a WriteFilePath (https://sandboxie-plus.com/sandboxie/writefilepath/)
in the plus UI its called hidden.
This way sandboxes chrome will have an entirely own copy of the profile

**Comment by isaak654** [comment]
> 
> 
> I think the proper solution to this behavior is to set the chrome profile folder as a WriteFilePath (https://sandboxie-plus.com/sandboxie/writefilepath/)
> in the plus UI its called hidden.
> This way sandboxes chrome will have an entirely own copy of the profile

It makes sense, but are you sure there isn't another way? If it becomes the new default approach, it would require massive changes in the browser part of templates.ini.

**Comment by mysteriously** [comment]
Sorry but this idea is not even close. I want to have clean Chrome profile as default, then configure each Sandboxed Chrome instance completely differently.

**Comment by koliu** [comment]
I ran into the same problem.
Brave has the same problem, but Firefox does not.
Therefore, this problem may lie in Chromium-based browsers.

**Comment by NewKidOnTheBlock** [comment]
HUH? Sandboxie behaves exactly like expected.
You ran Google Browser in sandbox. The session gets saved in the sandbox.
The next time you run Google Browser in sandbox, it continues exactly where you left.

Of course it doesn't take into account any changes you did to your session _outside_ the sandbox.

**Comment by koliu** [comment]
> Huh? Sandboxie behaved exactly like expected. You ran Google Browser in sandbox. The session gets saved in the sandbox. The next time you run Google Browser in sandbox, it continues exactly where you left.
> 
> Of course it doesn't take into account any changes you did to your session _outside_ the sandbox.

Thank you for pointing out what should be done correctly.
However, I think maybe try to reproduce this situation first to get us in sync.

1. Install Chrome in the OS.
2. Run Chrome in a sandbox.
3. Set the Chrome settings to "continue where you left off'" at startup.
4. Open any web page and keep these tabs open.
5. 'Eixt' Chrome directly.
6. Run Chrome directly on the operating system (not in the sandbox) and exit...
7. Run Chrome in the sandbox again. Then, we will encounter the problem that all tabs (session) are cleared.

Note: Chrome can be replaced by Brave.

It works fine when running Chrome in the sandbox, if we don’t perform step 6 above, the session will be saved correctly in the sandbox.
But after performing this step, the next time we start it in the sandbox, all tabs (session) will be cleared.

**Comment by Zo-Bro-23** [comment]
I'm experiencing the exact same problem as described by @koliu. Do any of you have any suggestions? I'm new to Sandboxie, so I don't really understand what's going on. I thought it might help if I go to Sandbox Settings >> Resource Access >> File Access and block access to the Chrome folder, but that just made things worse. Write-Only Access seems to work, but extensions and Chrome Apps get uninstalled on startup. What is the solution for this problem? Would really appreciate it if someone could help me out. Cheers!

**Comment by mysteriously** [comment]
1. I am using session buddy extension for chrome to save last sessions.
2. I never run chrome outside of sandbox.
3. I use chocolatey to update chrome

**Comment by Zo-Bro-23** [comment]
Got it. Here's how I fixed it:
1. I removed the default profile from my sandbox Chrome
2. I created a different profile with the same email
So even though it has the same email, Chrome sees the two profiles as different user accounts, so the closed tabs are stored in a separate folder. Hope I explained it clearly!

**Comment by mysteriously** [comment]
Can you elaborate step by step, please?
2. Inside or outside of main chrome sandbox?

Outside of sandbox I have clean profile without any extensions. I have multiple sandboxes with various configuration

**Comment by Zo-Bro-23** [comment]
Both my sandbox and my outside chrome sandbox have similar configurations. I cloned the outside sandbox chrome into the sandbox. I deleted the default user and added a new user with similar configurations (inside the sandbox). That made sure that the tabs were restored properly.

**Comment by mysteriously** [comment]
Does your solution work with multiple sandboxes with various configurations?

**Comment by Zo-Bro-23** [comment]
Yup 👍

**Comment by mysteriously** [comment]
Thanks. However I decided to uninstall Chrome anyway

**Comment by mysteriously** [comment]
This happens with MS Edge as well... Since we are not able to sign into Edge, it is quite severe

**Comment by offhub** [comment]
Chrome saves session files with a timestamp at the end. When you restart the browser, it loads the newest session files which are created outside of the sandbox.

Example:
```
###
Open - Edge (Sandboxed)
	Tabs_0001 (Created/Modified)
	Sessions_0001 (Created/Modified)
Close - Edge (Sandboxed)

Open - Edge (UNSandboxed)
	Tabs_0002 (Created/Modified)
	Sessions_0002 (Created/Modified)
Close - Edge (UNSandboxed)

Open - Edge (Sandboxed)
	LOADS Tabs_0002 (Because it's newer)
	LOADS Sessions_0002 (Because it's newer)
Close - Edge (Sandboxed)
.
.
.
###
```

Try this rule:

`WriteFilePath=msedge.exe,*\AppData\Local\Microsoft\Edge\User Data\Default\Sessions\*`

**Comment by mysteriously** [comment]
You don't seem to understand the issue.
I mentioned that allowing write access will prevent having multiple sandboxes with separate configuration.

Also, the issue affects only one sandbox, not all of them

**Comment by offhub** [comment]
[WriteFilePath](https://sandboxie-plus.com/sandboxie/writefilepath/) doesn't allow write access outside of the sandbox. It hides host/real files and folders from sandboxed programs but allows creation inside the sandbox.

In your terms:

WriteFilePath = Blacklist/Ignore
OpenFilePath = Whitelist/Write access

**Comment by mysteriously** [comment]
Thank you. I will test it and let you know
