### ISSUE TITLE
SandMan Looks Strange in HiDPI Screen

### ISSUE THREAD

**Issue by TooYoungTooSimp** [sandboxie-plus/Sandboxie#56]
![image](https://user-images.githubusercontent.com/6648049/84922836-02e30880-b0f9-11ea-9d5a-51198df36d10.png)
The font on the middle tab bar is too small
IIRC, Qt has a function call to auto adjust on HiDPI screen.
`Qt::AA_EnableHighDpiScaling` from [this link](https://doc.qt.io/qt-5/highdpi.html) may be helpful.

**Comment by DavidXanatos** [comment]
will add high dpi support to th enxt build, thx
