### ISSUE TITLE
Change Windows scaling issues for high-DPI devices

### ISSUE THREAD

**Issue by Ygarr** [sandboxie-plus/Sandboxie#560]
Ability to "Disable display scaling on high DPI settings check box" within Sandoxie.
![2021-02-14_07-59-35](https://user-images.githubusercontent.com/14309871/107869790-a3f9ad00-6e9a-11eb-91cd-4cff7d84133c.png)

**Comment by DavidXanatos** [comment]
for the UI or for the programs running inside the samdbox?

**Comment by DavidXanatos** [comment]
please provide more details or I'll close the issue

**Comment by Ygarr** [comment]
UI of sandboxplux is ok, need for Apps inside sandbox

**Comment by DavidXanatos** [comment]
seams to be fixed in build 1.0.9 already
