### ISSUE TITLE
Sandbox with some apps directly uses catdb than blocks access to it

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#561]
CAPI2:
`
The Cryptographic Services service failed to initialize the Catalog Database. The ESENT error was: -1032.
`

ESENT:
`
Catalog Database (2268,D,50) Catalog Database: An attempt to open the file "C:\Windows\system32\CatRoot2\{127D0A1D-4EF2-11D1-8608-00C04FC295EE}\catdb" for read / write access failed with system error 32 (0x00000020): "The process cannot access the file because it is being used by another process. ".  The open file operation will fail with error -1032 (0xfffffbf8).
`
  
![image](https://user-images.githubusercontent.com/25817412/107878068-ffb84a80-6f1b-11eb-82f8-d8f3c96c8123.png)

**Comment by Zymlex** [comment]
The problem arises when updating Windows, installing drivers, some DISM install/uninstall operations.

**Comment by Zymlex** [comment]
There is also a second base, it grew after some operations and I noticed this for one of the sandboxes:
![image](https://user-images.githubusercontent.com/25817412/107880495-cc30ec80-6f2a-11eb-9635-549c00d866d6.png)

It is a different path and a different sandbox, but the file is copied, which does not happen for firefox sandbox.

**Comment by DavidXanatos** [comment]
so the issue is that the original file ls being locked for as long as a sandbox is active?

**Comment by Zymlex** [comment]
> 
> 
> so the issue is that the original file ls being locked for as long as a sandbox is active?

Yes.

I have not yet delved into what exactly is blocking a file, SB service or working app process.

**Comment by DavidXanatos** [comment]
that will be SandboxieCrypto.exe i think the solution should be to just always migrate the file into the sandbox such that the original does not gets locked

**Comment by Zymlex** [comment]
Is it possible to configure this in sandboxie.ini? The sandbox is always deleted when the app is closed.

**Comment by DavidXanatos** [comment]
try adding 

```CopyAlways=SandboxieCrypto.exe,*\catdb```

the the global section of your sandboxie ini

**Comment by DavidXanatos** [comment]
is the issue resolved?

**Comment by Zymlex** [comment]
[0.7.2 / 5.49.0] - 2021-03-05
Changed:
- SandboxieCrypto now always migrates the CatRoot2 files in order to prevent locking of real files

Thanks!

**Comment by e-t-l** [comment]
Does anyone know what exactly this file does, and why it gets created in every sandbox? I've noticed the file size can get to be pretty large (some of my sandboxed catdb files are 4x bigger than the "real" one), so I'm wondering if it's something that needs to stick around in order for programs to work? Otherwise, it seems like it would be simplest to add a sandbox config line like:
`ReadFilePath=C:\Windows\System32\catroot2\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\catdb` 
to prevent the creation of sandboxed duplicates. @DavidXanatos what do you think?
