### ISSUE TITLE
When user delete contents without terminate all processes, should terminal all sandboxed processes first, then delete contents. 

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#562]
When I delete contents without terminate all processes, Sandboxie legacy build always terminate all processes and delete contents without any problem, but plus build usually throw an error message: "Error deleting sandbox folder: _______". 
By the way, I think here is a typo in Sandbox context menu: Delete content should be Delete Contents.

**Comment by isaak654** [comment]
Known issue: https://www.wilderssecurity.com/threads/sandboxie-plus-0-7.436454/#post-2990678

DeleteError is returned here:
https://github.com/sandboxie-plus/Sandboxie/blob/9f562c8bd8a799d485ee2fe10f139e298e9f4c90/SandboxiePlus/QSbieAPI/Sandboxie/SandBox.cpp#L156

**Comment by DavidXanatos** [comment]
this isue should already have been fixed in the recent builds
