### ISSUE TITLE
"Windows installer service could not be accessed" on install of an application into sandbox

### ISSUE THREAD

**Issue by boldcompany** [sandboxie-plus/Sandboxie#567]
Apologies for asking such a specific question, but it may be relevant to other users down the line.

If installing a program into a Sandboxie sandbox, and this error is shown:
"Windows installer service could not be accessed."
What is the most straightforward way to resolve?

Windows installer service is definitely installed and working on the native system, as the application installer in question runs without issues in native Windows. It only fails in a Sandboxie sandbox.
A few workarounds have been tried but none seem to work.

**Comment by kristibektashi** [comment]
Install the application outside the sandbox and simply launch it in the sandbox.

**Comment by DavidXanatos** [comment]
the msi installer should wok in a default config box, what software is making troubles?

**Comment by boldcompany** [comment]
Thank you both for your notes.

Application is: https://installers.ilok.com/iloklicensemanager/LicenseSupportInstallerWin64.zip
as shown here: https://www.ilok.com

When I install the app outside the sandbox and launch it in the sandbox, it doesn't function in a way that other apps in the sandbox can successfully access it. This is why I was trying to install it in the sandbox.

**Comment by DavidXanatos** [comment]
The issue was with installing Bonjour64.msi
to fix the issue with the MSI installer you need to disable protection of sanboxed system processes by adding ExposeBoxedSystem=y to your sandbox
or through the UI:

![grafik](https://user-images.githubusercontent.com/3890945/114268757-23bb7800-9a03-11eb-8364-864b0dc30df8.png)

**Comment by boldcompany** [comment]
@DavidXanatos, thank you!!

**Comment by pantau000** [comment]
doesn't work for me, still get the same error when trying to instal bonjour
