### ISSUE TITLE
YT downloader weird issue

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#568]
OS:Windows 7 Ultimate SP1 x64
Issue happens with version sandboxie 5,47/0.6.5 and up
program : ytapplications.com

The program gets stuck at "Downloading" but does not start , on 5.46.5 the downloads start without issue

**Comment by DavidXanatos** [comment]
could you please test all versions in between and tell me which one broke it exactly.

**Comment by isaak654** [comment]
@DavidXanatos 
I've just checked the release page and there is no other version between 5.46.5 and 5.47... the initial report seems fine to me.

**Comment by DavidXanatos** [comment]
I have run a test and on my test system it worked just fine with 0.6.5, on windows 7 SP1 and windows 10 2004
