### ISSUE TITLE
Another SBIE2101?

### ISSUE THREAD

**Issue by Quilding** [sandboxie-plus/Sandboxie#572]
I found a few old SBIE2101 issues but this one looks slightly different. I have no idea what that object path is. Neither do AltaVista. The below lines are from starting CMD from the Run menu within Sandboxie. Same problem if I run Sandboxie as Admin. However, this is a company computer with somewhat limited permissions.
Start.exe (2056): SBIE2101 Object name not found: \Device\NamedPipe\MemDef, error CreateFile (C0000022) access=0012019F initialized=1
PID 5048: SBIE2314 Cancelling process Start.exe [2056 / 7]

Any suggestions?

Regards

**Comment by Quilding** [comment]
Ok, MemDef = Memory Defence, probably a result of Cylance Protect service running.

**Comment by DavidXanatos** [comment]
probably on my systems cmd starts just fine so i'll close this issue
