### ISSUE TITLE
[v0.7.0/5.48.0] Free Download Manager

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#573]
Just for your information: If someone wants to use the "Free Download Manager" with version 0.7.0/5.48.0, it will only work after adding the following setting.
```
RpcMgmtSetComTimeout=fdm.exe,y
```
Without this setting, the user interface will not appear.

**Comment by DavidXanatos** [comment]
Thanks will be properly fixed in the next build

**Comment by APMichael** [comment]
With the new version 0.7.1/5.48.5 it works again without "RpcMgmtSetComTimeout=fdm.exe,y". Thanks a lot!
