### ISSUE TITLE
Sandboxie Windows 7 drivers (SbieDrv.sys.5.47.1.x64.rc4) doesn't work with Sandboxie Classic 5.48.0

### ISSUE THREAD

**Issue by RobertD64** [sandboxie-plus/Sandboxie#575]
The newest Sandboxie Classic version 5.48.0 when paired up with >>> SbieDrv.sys.5.47.1.x64.rc4 when installing on my Windows 7 (x64) operating system. All I get is a flashing exclamation point in the systray. I went back to the previous version that worked which is 5.47.1.

**Comment by Coverlin** [comment]
> The newest Sandboxie Classic version 5.48.0 when paired up with >>> SbieDrv.sys.5.47.1.x64.rc4 when installing on my Windows 7 (x64) operating system. All I get is a flashing exclamation point in the systray. I went back to the previous version that worked which is 5.47.1.

![speechless](https://user-images.githubusercontent.com/34079190/108160910-a8b89e00-70f2-11eb-9081-d91037b96aee.png)

01101100 01101111 01101100

**Comment by Jimmy03** [comment]
Sounds like my issue: https://github.com/sandboxie-plus/Sandboxie/issues/546

**Comment by DavidXanatos** [comment]
thay wont work thay must be the same version always grab the newest windows 7 compatybility package
