### ISSUE TITLE
How to build latest version of Sandboxie-Plus from this repository

### ISSUE THREAD

**Issue by kristibektashi** [sandboxie-plus/Sandboxie#577]
Also how do I enable test signing so that I can actually install the driver? (Windows 10 Insider Build 21313)

**Comment by DavidXanatos** [comment]
enter 
```bcdedit /set testsigning on```
in an elevated command prompt and reboot

**Comment by kristibektashi** [comment]
@DavidXanatos How can I build latest version of Sandboxie-Plus from this repository?

**Comment by DavidXanatos** [comment]
See the CI action: https://github.com/sandboxie-plus/Sandboxie/blob/master/.github/workflows/main.yml

it should give you an idea how to do that, or just fork the project and let CI do the job for you

**Comment by kristibektashi** [comment]
@DavidXanatos What is a CI?

**Comment by isaak654** [comment]
> 
> 
> What is a CI?

https://docs.github.com/en/actions/guides/about-continuous-integration
