### ISSUE TITLE
Win32/Agent.ABZW.gen

### ISSUE THREAD

**Issue by AmyRose1288** [sandboxie-plus/Sandboxie#58]
﻿时间;扫描程序;对象类型;对象;检测;操作;用户;信息;哈希;此处首次所见
2020/6/18 11:08:31;文件系统实时防护;文件;C:\Users\AMYROS~1\AppData\Local\Temp\SandboxieInstall-64-bit-124376625.exe;Win32/Agent.ABZW.gen 特洛伊木马 的变种;通过删除清除;DESKTOP-F8EFMOR\Amy Rose;在应用程序新建的文件上发生事件: C:\Users\Amy Rose\Downloads\Programs\SandboxieInstall-v5.41.0.exe (50DA78360ED571CF247467CADCB8ABB3138D95A9).;1CFEF2633C66D72D109321B030186AD754FF9F49;

**Comment by DavidXanatos** [comment]
see: https://github.com/sandboxie-plus/Sandboxie/issues/52
its a false positive
