### ISSUE TITLE
can't start in guest account after forcing winmail into sandbox

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#580]
I used ForceFolder to force windows mail(e.g., C:\Program Files\Windows Mail) into sandbox, and turned on guest account. When I logged into guest account, it was preparing the desktop and said errors of winmail and winsock. I removed that ForceFolder and waited a while, not immediately, it works. However, I can't find my network adapter in guest account, the network adapter is shown in standard account.

**Comment by DavidXanatos** [comment]
should you even see it in the build in gues account? its a restricted one
