### ISSUE TITLE
Why does sandboxie ask to allow  large files inside sandbox AFTER immediate recovery?

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#581]
When I complete a download and do an immediate recovery after about 60 seconds sandboxie plus says "would you like to allow files larger than this inside the sandbox". Why does it ask this? Its already been recovered. I don't understand, its very annoying and unnecessary.

**Comment by DavidXanatos** [comment]
Because somethign wahts to open the file for writing inside the sandbox, but as you say its recovered its now outside, so for write access it would need to be copied backin

**Comment by rugabunda** [comment]
> 
> 
> Because somethign wahts to open the file for writing inside the sandbox, but as you say its recovered its now outside, so for write access it would need to be copied backin

But I checked off "remember this" and it keeps on asking over and over again with every new file.

**Comment by rugabunda** [comment]
I guess I can disable file size limits instead, and or "message 2102 when file is too large"
