### ISSUE TITLE
[Feature Request] UI suggestions for Sandboxie Plus Settings

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#582]
1) Shorten the distance between 'Restart required' text and the language selector
2) Add another informative 'Restart required' next to 'Use Dark Theme'

Something like this, but not necessarily with the same spacing:
![selector_plus](https://user-images.githubusercontent.com/12372772/108399504-7904b580-721a-11eb-9216-9df970d404b1.png)

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/108869545-97dac180-75f7-11eb-8fbe-6abae1cdfd0d.png)

**Comment by isaak654** [comment]
I think `(fully applied after a restart)` would be better.

**Comment by DavidXanatos** [comment]
ok

**Comment by NewKidOnTheBlock** [comment]
`(requires restart)`
...would be my solution.
