### ISSUE TITLE
"PreferExternalManifest=" prevents some games from starting correctly – possible bug?

### ISSUE THREAD

**Issue by matheuswillder** [sandboxie-plus/Sandboxie#583]
I've been using Sandboxie for years to isolate games and some other related stuff. This has no security reasons, it just allows me to easily revert some modifications and settings (and also toggle between the progress saved in a game).

Some time ago I noticed that the Grand Theft Auto IV game no longer started under the Sandboxie supervision, showing the error **SecuLauncher: failed to start application. [2000]**. Resource Monitor don't show any errors. Today I was able to do tests to find out when the problem started.

The problem started in the **[Release v0.4.5 / 5.44.1](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.4.5)**, and additing "_PreferExternalManifest=y_" option in _Sandboxie.ini_ lets the game start normally.

This is a bug or is it the desired behavior?

Sorry for my English and thank you for continuing the development of this amazing tool.

**Comment by NewKidOnTheBlock** [comment]
Where do you need to put that parameter?
Global Settings? User settings? or the Sandboxes?

**Comment by Rngexile** [comment]
"PreferExternalManifest=y" is added in the sandbox ini config when you go to the sandbox config : "Advanced options > Miscellaneous > **Compatibility**" then check the box "force usage of custom dummy manifest files (legacy behaviour)".

change log of sandboxie-plus 0.4.5 : 
"now by default Sbie's application manifest hack is disabled, as it causes problems with version checking on Windows 10 -- to enable old behaviour add "PreferExternalManifest=y" to the global or the box specific ini section"

Not security related, but compatibility parameter to try for some applications. Good we have now the option to do that.

**Comment by matheuswillder** [comment]
@NewKidOnTheBlock
> Where do you need to put that parameter?
Global Settings? User settings? or the Sandboxes?

It can be a global option (which applies to all boxes) or per box.

@Rngexile
> Not security related, but compatibility parameter to try for some applications. Good we have now the option to do that.

I think now I understand better. As the changelog says that the option enabled (old behavior) causes problems I figured this could be a bug since the current behavior that caused this problem.

Thank you for the answers.
