### ISSUE TITLE
[5.48.0] Many games don't work anymore in latest Sandboxie

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#584]
Sandboxie 5.48.0 breaks many games that used to run before.
While this issue started with only a single game (_Rage2_), it has expanded to many other games.

Games that **work** in SB 5.48.0 without any modifications:
- Elite Dangerous
- Halcyon 6
- Night in the Woods
- The Alto Collection
- World War Z

Games that work **if** you add `RpcMgmtSetComTimeout=y`
- Rage2
- Silent Sector

Games that still **fail** to launch:
- Into the Breach
- Just Cause 4

This is my Sandbox.ini:

```
[GlobalSettings]

Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=D:\Sandbox\%SANDBOX%
TemplateReject=AdobeAcrobatReader

[UserSettings_0C980217]

SbieCtrl_UserName=XXX
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=406,273,1237,703
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_ReloadConfNotify=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_TerminateWarn=n
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
BoxDisplayOrder=Default,Epic
SbieCtrl_ShortcutNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_BoxExpandedView=Default,Epic

[Epic]

Enabled=y
ConfigLevel=8
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
OpenPipePath=D:\Epic Games\
CopyLimitKb=2222222
RpcMgmtSetComTimeout=y
```

Thanks to the new line, I can now successfully launch _Rage2_ and _SilentSector_. Thanks!

**Comment by Rngexile** [comment]
**RpcMgmtSetComTimeout=ex.exe,"y"** could be a usual workaround on some games & applications. 
It works with Path Of Exile game on my system and i suppose we'll just have to try that sometimes (seems easier than let David change Sandboxie internals each time for each applications specific dll that could need that parameter to "y", idk).

**"RpcMgmtSetComTimeout=rage2.exe,y"** in its sandbox config

**Comment by NewKidOnTheBlock** [comment]
I got a couple more games in the Epic Sandbox, so I tried to launch all of them in Sandbox:

- Elite Dangerous -> works
- Halcyon 6 -> works
- Night in the Woods -> works
- The Alto Collection -> works
- World War Z - works

These don't work:
- Into the Breach
- Just Cause 4
- Rage2

So I've edited my Sandbox.ini as you suggested and also added lines for the other non-working titles, like this:


```
[GlobalSettings]

Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=X:\Sandbox\%SANDBOX%
TemplateReject=AdobeAcrobatReader

[UserSettings_0C980217]

SbieCtrl_UserName=XXX
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=406,273,1237,703
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_ReloadConfNotify=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_TerminateWarn=n
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
BoxDisplayOrder=Default,Epic,Steam
SbieCtrl_ShortcutNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_BoxExpandedView=Default,Epic,Steam

[Epic]

Enabled=y
ConfigLevel=8
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
OpenPipePath=X:\Epic Games\
CopyLimitKb=2222222
RpcMgmtSetComTimeout=rage2.exe,y
RpcMgmtSetComTimeout=justcause4.exe,y
RpcMgmtSetComTimeout=breach.exe.exe,y
```

Thanks to the new lines I can now succesfully launch Rage2. Thanks!
I thought: why not copy the method and add another two lines for the remaining games.
For some reason, this doesn't help, Just Cause 4 and Into the Breach still refuse to launch.

**Comment by isaak654** [comment]
@NewKidOnTheBlock 

You can enable RpcMgmtSetComTimeout for all executables in the sandbox using the following command:
RpcMgmtSetComTimeout=y

**Comment by NewKidOnTheBlock** [comment]
Update:
I reverted back to 5.47.1 and suddenly Into _The Breach_ worked again.

**Comment by Rngexile** [comment]
From the changelog of 5.48.0/0.7.0 : 

> improved IPC handling around RpcMgmtSetComTimeout, "RpcMgmtSetComTimeout=n" is now the default behavioure
> -- required exceptions have been hard coded for specific calling dll's
> 
> FIXED SECURITY ISSUE: "\Device\DeviceApi\CMApi" is now filtered by the driver (thanks hg421)
> -- this allowed elevated processes to change hardware configuration, to disable filtering use "OpenDevCMApi=y"

With your tests already done, only David could tell us if RpcMgmtSetComTimeout hard coded stuff is related to your problems.
Maybe add here your box's logs (minimum IPC&Pipe) when you try to run JustCause4 or IntoTheBreach : configure logs > activate logs > execute the game ... wait few seconds ... > disable logs and copy all logs to file.txt then close game.exe.
One log with RpcMgmtSetComTimeout=y and one without it.

I think i remember David saying that closing "\Device\DeviceApi\CMApi" would even make trouble with Firefox.
You could test this in your Epix box (security issue then) : "OpenDevCMApi=y"

As another player has found, the compatibility option "force usage of custom dummy manifest files" could help with some games. You could try it for your Epic box, even if nothing in the changelog seems to adress it.

I suppose the first traces could help, before going full debug logs or external tools.

**Comment by NewKidOnTheBlock** [comment]
Good news!
With 5.48.5 _Rage2_ and _IntoTheBreach_ work out of the box (SCNR).
They don't require any extra configuration lines anymore. They just work.
