### ISSUE TITLE
Sandboxie control don't autostart.

### ISSUE THREAD

**Issue by Achaean** [sandboxie-plus/Sandboxie#585]
Latest stable version (classic), on Win 10 x64 Pro, b.1909.

Sandboxie control don't autostart, after launching a sandboxed program.
The respective (Windows Shell) option, doesn't seem to work.

Bye!!!  :-)
A.

**Comment by NewKidOnTheBlock** [comment]
Are you sure you checked this?
![96009393-e48be000-0e40-11eb-9157-6087bef34edb](https://user-images.githubusercontent.com/12411527/108604473-75099c80-73ae-11eb-871b-79dfea8725b0.png)

**Comment by Achaean** [comment]
Dead sure!
Or, at least...so I think.  :-)

![Screenshot_1](https://user-images.githubusercontent.com/3608053/108605820-43e59800-73bf-11eb-8af1-7a52deb206f0.png)

**Comment by DavidXanatos** [comment]
try re installign justin case, also have you used the plusbuild in the mean time?
it my have set itself up as the sbie agent so that the service does nto try to strttle legacy ui
if oyu have the line ```SbieCtrl_AutoStartAgent=SandMan.exe``` in your sandboxie ini, remove it

**Comment by Achaean** [comment]
Oh, I think you found it!
Indeed I tried the + build, some time ago.

Just in case to confirm it, where sandboxie.ini lives?
I know it sounds silly, but I can locate the Templates and 2 desktop INIs, but not the sandboxie one.  :-(

**Comment by bjm234** [comment]
C:\Windows\Sandboxie.ini

**Comment by Achaean** [comment]
**Indeed!**
Removing this line and rebooting, solved the problem.
