### ISSUE TITLE
Show "Getting Started Tutorial" after Sandboxie first time installed. 

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#587]
It would be helpful to getting started with Sandboxie.

**Comment by DavidXanatos** [comment]
you can start it from the help menu, its not cool to force it on advanced users who just re install the tool

**Comment by quangkieu** [comment]
Hey, I wonder if we could have help menu flashing for few seconds on new install to hint new user look there
If so we could have change log under for adv users so that could hint multiple things
