### ISSUE TITLE
whitelist 127.0.0.1 and run installers from closed/hidden folder

### ISSUE THREAD

**Issue by readtheslash** [sandboxie-plus/Sandboxie#590]
How to whitelist 127.0.0.1 if network is blocked? Can't run Firefox installer from outside, if that installer is in a folder closed or hidden to sandbox.

**Comment by DavidXanatos** [comment]
currently you can not, you have to use an external firewall for that

**Comment by readtheslash** [comment]
The 2nd problem may be misunderstood. "From outside" means to insert installers into sandbox.

**Comment by DavidXanatos** [comment]
> Can't run Firefox installer from outside, if that installer is in a folder closed or hidden to sandbox.

but yes of cause you cant that folder is closed or hidden, that's intended behavior

**Comment by readtheslash** [comment]
> but yes of cause you cant that folder is closed or hidden, that's intended behavior
How about running a program without telling the path?

**Comment by DavidXanatos** [comment]
> 
> 
> > but yes of cause you cant that folder is closed or hidden, that's intended behavior
> 
> How about running a program without telling the path?

its not about telling the installer must be able to read itself so there is no good workaround for that currently
