### ISSUE TITLE
Offering help to translate to spanish latam

### ISSUE THREAD

**Issue by sebadamus** [sandboxie-plus/Sandboxie#593]
Hi,

Cant pay for patron, where I live now is like communism and very difficult to send money (USD), so unfortunately cant give you monetary hints.

But I can offer spanish translation, if you have a Crowdin or similar, or XML something you can guide me to start... I can do it!

Thanks for the project!

**Comment by DavidXanatos** [comment]
Hi,

you will need his file
https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_es.ts
and 
https://doc.qt.io/qt-5/qtlinguist-index.html

thanks :-)

**Comment by sebadamus** [comment]
Sorry, just read your response I didnt get the alert by email, strange... I am suscribed, will see my profile if any error. 
Will help with the translation!

**Comment by sebadamus** [comment]
> 
> 
> Hi,
> 
> you will need his file
> https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_es.ts
> and
> https://doc.qt.io/qt-5/qtlinguist-index.html
> 
> thanks :-)

Hi again, do you know any windows or linux app to open the .ts file and translate it?
I read the link you send me but I might thing I need to install the QT Studio (sorry if I understood wrong) to use the Qt Linguist Tool.

Thanks,

**Comment by sebadamus** [comment]
https://github.com/lelegard/qtlinguist-installers/releases

Found it 🥇 sorry.

**Comment by isaak654** [comment]
No .txt file, you need to provide the new .ts file translated in your language.

**Comment by sebadamus** [comment]
> No .txt file, you need to provide the new .ts file translated in your language.

Is it going good this way? please confirm and will continue.  Also if I need to upload the file some other way you need.

https://pastebin.com/pjxN9nrz

Thanks!

**Comment by isaak654** [comment]
@sebadamus 
It looks fine as a start, except a few extra lines that David didn't include by default in all new translations...  they are needed to translate the dialog buttons like Ok, Cancel, Apply.

I produced this file for you, it contains a new section called _QPlatformTheme_:
https://gist.githubusercontent.com/isaak654/c4d83d36158c4488a67673133303ba2e/raw/05151b53aee09031bc122e60d97ea70772ccce29/sandman_es_2(wip).ts

Please tell me when you take it, my intention is to remove this link as soon as possible.

Once you've completed the translation (or at least at 80%), I could create a pull request for you, but for the next ones (to create for new incremental updates) I would suggest to take care of it by installing and using locally [Github Desktop](https://desktop.github.com) as client, it helps to deal with a lot of strings.

**Comment by isaak654** [comment]
You can also test the translation locally in Sandboxie Plus by exporting it with Linguist as _sandman_es.qm_ in 'File' menu -> 'Release as'. The same file needs to be copied and pasted in the _translations_ folder of Sandboxie Plus (when the program is closed). Plus will recognize it after applying the translation in the settings.

**Comment by isaak654** [comment]
You can also test the translation locally in Sandboxie Plus by exporting it with Linguist as sandman_es.qm in 'File' menu -> 'Release as'. The same file needs to be overwritten in the translations folder of Sandboxie Plus (when the program is closed). Plus will recognize it after applying the translation in the settings.

**Comment by sebadamus** [comment]
There @isaak654 ! could get the file you send, will continue to translate to spanish there and then postback here, hope to end it soon.
Am am not using the Sandboxie-Plus, kind of old stile... (still in latest Classic), but can try as you told then!

**Comment by sebadamus** [comment]
Okay @issak645 have just finished translating, here is the file (from the file you gave me I continued)
https://pastebin.com/UTM74iYw

Its Spanish Latinamerican, kind of neutral spanish.  Did not use accents, but can be added in future version if this one goes well.

Tell if I can do something else to help.

**Comment by isaak654** [comment]
I've just merged two commits with your changes and something more (see the history for more info):
https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_es.ts

You might want to download the TS file again and translate a new updated english string... it's minor and you can take all the time you want in order to take confidence with Github Desktop.

**Comment by sebadamus** [comment]
OK @isaak654 there is the translations done to the file you lastly gave me, will try to understand this github web (if my head explodes will try with the desktop version), thanks!
[sandman_es.ts.txt](https://github.com/sandboxie-plus/Sandboxie/files/6851504/sandman_es.ts.txt)

**Comment by isaak654** [comment]
@sebadamus About the pull request, I replied you here: https://github.com/sandboxie-plus/Sandboxie/pull/1021#issuecomment-883770813

**Comment by isaak654** [comment]
@sebadamus Could you provide the translation of Plus installer in Spanish under [CustomMessages] section?
https://github.com/sandboxie-plus/Sandboxie/blob/master/Installer/Languages.iss

**Comment by sebadamus** [comment]
Hi @isaak654, I dont know what happended but github started to send me notifications as it should, something was bad with my accound I think and I didnt get any kind of github  notifications (posts, pulls, mentions) so seems now its working back (I got thousand of notifs in a day from every thing I am suscribed)

So, please tell me if you need some more spanish translation and would help!!!

**Comment by sebadamus** [comment]
Just have done it @isaak654, I added one draft yesterday and another just now, dont know if I am messing up the githup pulls stuff, sorry if so... tellme what to do.

**Comment by isaak654** [comment]
No problem here, I already merged your PR.

I would like to ask you an opinion about this issue related to the distribution of language updates that is quite imperfect:
[ [Plus UI] Create a new workflow to improve delivery of language updates](https://github.com/sandboxie-plus/Sandboxie/issues/1595)

Since it doesn't seem to get attention, I would appreciate if you could reply there.

**Comment by sebadamus** [comment]
Hi @isaak654, can you "sync" the sandman_es.ts to the main SandMan.pri because I think there are some missing sources.  Here I post the image of the source text "Pause Forcing Programs" that in spanish seems to remain in english and cant find the source entry in the sandman_es.ts (but can find it in sandman_en.ts), maybe there are other sources missing that I could fix if I have the updated entries in sandman_es.ts

I read https://github.com/sandboxie-plus/Sandboxie/discussions/1123 that there is a way to sync it but cant find lupdate.exe in my Linguist QT install folders (I am running it with wine in linux)

![imagen](https://user-images.githubusercontent.com/1787753/156937966-a09351bc-7ebc-4c1d-b8d4-5b009158b85c.png)

**Comment by isaak654** [comment]
I have just updated the guide with a basic method that explains how to look up for your lupdate path with the cross-platform Qt Creator tool.

**Comment by sebadamus** [comment]
> 

Hi @isaak654,

Meanwhile I get in with the git dowload stuff and the lupdate, if you have avaiable a new updated spanish .ts file that can be attached here, I would be please to start translating.

Also, I would like to ask if the "español de España" item that appears in the UI Language selection box, can be changed to "Spanish Neutral" because there are several spanish kinds that we spanish talking people understand but are little different.  I try to translate always in neutral (not Spain, not Mexico, not Argentina, not Peru, not Chile... there are a lot more!)

I have already correct some terms I found just using my own translate... will update then with your lupdated file or when I deploy the project in my computer env.

Thanks,

**Comment by isaak654** [comment]
> Also, I would like to ask if the "español de España" item that appears in the UI Language selection box, can be changed to "Spanish Neutral" because there are several spanish kinds that we spanish talking people understand but are little different.

You can customize it easily from Qt Linguist -> Edit menu -> Translation File Settings -> switch the latest dropdown menu to "Any Country". I'll see to add a new "Changing the Target Locale" chapter in the localization notes.

**Comment by isaak654** [comment]
> Also, I would like to ask if the "español de España" item that appears in the UI Language selection box, can be changed to "Spanish Neutral" because there are several spanish kinds that we spanish talking people understand but are little different.

You can customize it easily from Qt Linguist -> Edit menu -> Translation File Settings -> switch the latest dropdown menu to "Any Country" -> save the .ts file from the File menu.

I'll see to add a new "Changing the Target Locale" chapter in the localization notes.

**Comment by isaak654** [comment]
> Also, I would like to ask if the "español de España" item that appears in the UI Language selection box, can be changed to "Spanish Neutral" because there are several spanish kinds that we spanish talking people understand but are little different.

You can customize it easily from Qt Linguist -> Edit menu -> Translation File Settings -> switch the latest dropdown menu to "Any Country" -> save the .ts file from the File menu.

I'm not sure how it could change the UI Language entry on the Plus UI, this is something you need to test with multiple attempts.

I'll see to add a new "Changing the Target Locale" chapter in the localization notes.

**Comment by sebadamus** [comment]
This is the nearest one I could find in the latest dropdown, will try...
![imagen](https://user-images.githubusercontent.com/1787753/160473630-55a82bdf-7f01-401b-bac6-1cf10bb6524e.png)
