### ISSUE TITLE
The latest version breaks installers

### ISSUE THREAD

**Issue by Smurf451** [sandboxie-plus/Sandboxie#595]
### Setup
Windows 10
Sandboxie Classic 5.48.0

### Issue
All codex installers are broken after upgrading to 5.48.0.
Sandboxie itself issues a SBIE2224 error
The installer throws a runtime error 229
![runtimeerror229](https://user-images.githubusercontent.com/79382489/108609714-0b9a8580-73d0-11eb-8653-b96b1039b112.gif)

In order to work, the installer relies on several .dlls located in `AppData\Local\Temp`
![installerblocked](https://user-images.githubusercontent.com/79382489/108609788-b317b800-73d0-11eb-9d59-4e40c2f4acfb.gif)

This issue does not occur in 5.47.1

**Comment by DavidXanatos** [comment]
Try adding 
RpcMgmtSetComTimeout=y
AllowRawDiskRead=y
OpenDevCMApi=y
OpenSamEndpoint=y

and tell me which of those fixed the issue

**Comment by Smurf451** [comment]
Tested again with 5.48.5

`RpcMgmtSetComTimeout=y`
Runtime error 229

`AllowRawDiskRead=y`
Runtime error 229

`OpenDevCMApi=y`
Runtime error 229

`OpenSamEndpoint=y`
Runtime error 229

```
RpcMgmtSetComTimeout=y
AllowRawDiskRead=y
OpenDevCMApi=y
OpenSamEndpoint=y
```
Runtime error 229

**Comment by DavidXanatos** [comment]
and on the previouse version it worked? fine?
that's strange as with this settings you should be able to disable the new isoaltions

**Comment by Smurf451** [comment]
@DavidXanatos I've uploaded the necessary file to test at Cryptpad:
https://cryptpad.fr/file/#/2/file/Vvaz615h4P9ecW18pWZwTgOx/

**Comment by Smurf451** [comment]
With 5.49.0 they are all working now.
Excellent.
