### ISSUE TITLE
Can't add a user to a sandbox. When I apply settings, the user disappears

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#597]
Hello! Using the latest version of Sandboxie-Plus, and for whatever reason I can't add a user to my sandbox. Whenever I try to, the user just disappears when I press "apply".

Anyone else with the same issue?

**Comment by isaak654** [comment]
I can reproduce the same bug in Sandboxie-Plus 0.7.1 x64.
