### ISSUE TITLE
This artifact

### ISSUE THREAD

**Issue by russellcoinpay** [sandboxie-plus/Sandboxie#6]
I often rely on him for reverse software
For example, what registry will a software change
What files will be written
I run it with sandboxie
Used to reverse software
Do differential registry
Even containers are created on windows, similar to flatpak, there will be no residue when deleting
If it can be combined with virtualization to achieve driver virtualization, then the real container.

**Comment by DavidXanatos** [comment]
emm... I have trouble understanding your english could you please try to re formulate your issue.

**Comment by quangkieu** [comment]
From what I read, he either try to do container in sandboxie or sandboxie in container to virtualize driver.

**Comment by russellcoinpay** [comment]
Can it be more difficult to use vt-x to further develop on this basis to realize a virtualized driver?
