### ISSUE TITLE
0.7.1 SBIE2214 Installer msi

### ISSUE THREAD

**Issue by bjm234** [sandboxie-plus/Sandboxie#600]
![image](https://user-images.githubusercontent.com/25015553/108641973-78655c80-7470-11eb-8db9-001f65535e25.png)
![image](https://user-images.githubusercontent.com/25015553/108641984-874c0f00-7470-11eb-83c6-be3d7b152913.png)
![image](https://user-images.githubusercontent.com/25015553/108641991-9632c180-7470-11eb-919b-26ae26d8ed59.png)
[https://www.screentogif.com/] Installer msi
[ScreenToGif.2.27.3.Setup.zip](https://github.com/sandboxie-plus/Sandboxie/files/6018808/ScreenToGif.2.27.3.Setup.zip)

**Comment by isaak654** [comment]
I think you could be of greater help here if David invites you to test the releases internally before the public (imho).

I can reproduce this issue too, for all msi installers with "FakeAdminRights=y" and "DropAdminRights=y" in my sandbox.

**Comment by ImSpecial** [comment]
What's the issue? It's literally telling you that it's failing to start due to "dropped rights".

**Comment by isaak654** [comment]
It should work for all installers, according to the changelog of the latest version:

> -- With "FakeAdminRights=y" and "DropAdminRights=y" installers should still work

**Comment by bjm234** [comment]
Chrome n' Edge don't like Drop Rights.  And ScreenToGif msi doesn't like Drops Rights.
Since, 0.7.1 annotates Drop Rights (Recommended).   Thought I'd try "DropAdminRights=y" & "FakeAdminRights=y" with exe & msi installer.  Just to see whats what.

**Comment by isaak654** [comment]
No problem with .exe files here, it's just allergic to .msi installers.

**Comment by bjm234** [comment]
> No problem with .exe files here, it's just allergic to .msi installers.
Yes, exe feels okay.

**Comment by ImSpecial** [comment]
Key word is "**should**".

You're playing a compatibility game here, some things won't like a setting, and some are fine with them, you cannot have both an On & Off light switch, either have a hardened sandbox that will more often break compatibility, or a more laxed one without that setting. Or have both for different reasons.

**Comment by DavidXanatos** [comment]
emm... what fails here is that with drop admin rights enabled you cant start services (like MSI installer) in the sandbox at all,
If you go for fake admin but not drop rights the installation will work and be similarly secure, as long as you don't clock ok on a UAC prompt, but that one shouldn't appear anyways.

With the new setting to (by default) not run services as system the aforementioned behavior can be changed though, i.e. allow service starts when drop rights is off and they are than started with a normal user token.
I may relax this for the next build just have to think if that's surely secure enough.

Also note that the problems with elevated processes were since since 3.0x to 4.x or even earlier present, just after fixing like half a dozed Security Vulnerabilities recently that all were caused by allowing to much to elevated processes, I thought screw it sandboxed processes should not have to be elevated in the first place. Hence the new feature and the recommendation.

**Comment by ImSpecial** [comment]
@DavidXanatos 

You need to start leaning more on the side of compatibility, more then security for the default settings. Sandboxie was never meant to be some malware testing tool, its for running legitimate stuff while keeping your system clean, untouched, prevent win-rot, etc.

If people want a super-hardened box for malware/shady installers then they can tweak their own settings away from the defaults to do so and then can expect more breakage with software. All IMO of course, what are your thoughts?

**Comment by bjm234** [comment]
> @DavidXanatos
> 
> You need to start leaning more on the side of compatibility, more then security for the default settings. Sandboxie was never meant to be some malware testing tool, its for running legitimate stuff while keeping your system clean, untouched, prevent win-rot, etc.
> 
> If people want a super-hardened box for malware/shady installers then they can tweak their own settings away from the defaults to do so and then can expect more breakage with software. All IMO of course, what are your thoughts?

Regarding "the default settings".  Drop Rights is not default with DefaultBox. 
![image](https://user-images.githubusercontent.com/25015553/108724912-d7b88080-74f3-11eb-8884-d6c4a4d90eca.png)
I added ... just as test....since, 0.7.1 deems Recommended.

**Comment by bjm234** [comment]
> emm... what fails here is that with drop admin rights enabled you cant start services (like MSI installer) in the sandbox at all,
> If you go for fake admin but not drop rights the installation will work and be similarly secure, as long as you don't clock ok on a UAC prompt, but that one shouldn't appear anyways.
> 
"Make application think" without "Drop rights" is not doable with my 0.7.1 Plus UI DefaultBox.

**Comment by bjm234** [comment]
@DavidXanatos 
Just now noticed Ask for UAC Elevation | Drop Admin Rights | Emulate Admin Rights with Sandbox Presets menu.  
![image](https://user-images.githubusercontent.com/25015553/108900213-5d692880-75e7-11eb-92a9-cf59e2113ecf.png)
Sandbox Presets option is accurately reflected with Elevation restriction boxes.  
Ask for = no boxes | Drop Admin = one box | Emulate Admin = both boxes. 
![image](https://user-images.githubusercontent.com/25015553/108901318-bc7b6d00-75e8-11eb-95a2-a762d4c7787f.png)

**Comment by DavidXanatos** [comment]
My goal is to really only need the 3 options in the presets menu, but untill everything runs perfectly fine its intended to also be able to use the settings to set a more advanced preset by only checking the emulate admin option without checking the drop rights.

**Comment by bjm234** [comment]
Okay..... I hear ya'.  Sorry, for only now noticing 3 options in the preset menu.

**Comment by DavidXanatos** [comment]
In the next build MSI server will be able to work correctly when DropAdminRights is in place :D
