### ISSUE TITLE
Missing values between Sbie Plus and Classic

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#604]
1) No copyright info in Sandboxie Plus installer, while Sandboxie Classic installer has it.
2) No File version in Sandboxie Plus installer, while Sandboxie Classic installer has it.
3) No Product version in Sandboxie Classic installer, while Sandboxie Plus installer has it.
4) Copyright info missing from unins000.exe in Sandboxie Plus folder. HitmanPro attempted to upload it automatically for better recognition after a manual scan.

![installers](https://user-images.githubusercontent.com/12372772/108673104-61138700-74e3-11eb-9de3-df76fa299683.png)

![uninst000](https://user-images.githubusercontent.com/12372772/108673028-3f1a0480-74e3-11eb-9d8f-ff81bb6ed17a.png)

**Comment by DavidXanatos** [comment]
will be fixed in the next build

**Comment by isaak654** [comment]
All fixed except this:

3) No Product version in Sandboxie Classic 5.49.0.0 installer, while Sandboxie Plus installer has it.
