### ISSUE TITLE
disable migration/recovery if apps aren't installed on Host

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#608]
If 3rd-party apps, e.g., Firefox, is installed in sandbox but not Host OS, file migration or file recover (I'm not sure) causes sandbox escape. Migration and recovery are automatic, I didn't manually do that; even if an app is on Host, sandboxie should also prevent automatic migration/recovery. I once found a folder "Mozilla" in C:\ProgramData , but Firefox wasn't on Host.

**Comment by DavidXanatos** [comment]
Migration is into the box so no risk there,
quick recovery prompts the user so no "escape" without clicking on ok or alike

About the folder "Mozilla" in C:\ProgramData you probably had a Firefox compatibility template enabled that allows access to the real location

**Comment by readtheslash** [comment]
Will you modify the default template? Sandboxie automatically choose templates if Firefox is installed.
