### ISSUE TITLE
Cannot start msi as UAC Admin

### ISSUE THREAD

**Issue by gjf** [sandboxie-plus/Sandboxie#610]
When trying to install any msi file in Sandbox with UAC Admin permissions the error appears saying "%1 is not Win32 application. (193)".
Without permissions msi installs OK.
Windows 10 x64, Sandboxie Classic 5.48.5

**Comment by DavidXanatos** [comment]
define "Sandbox with UAC Admin permissions"

**Comment by gjf** [comment]
![Безымянный](https://user-images.githubusercontent.com/322186/108836092-7bcc2580-75e1-11eb-81e3-6d4dcbad04f8.png)

**Comment by DavidXanatos** [comment]
ah I see... that's normal the UAC Admin option works only with executable.
start the msi without this option it will ask later on its won for uac elevation.

**Comment by gjf** [comment]
OK thank you. Case's closed.
