### ISSUE TITLE
Memory usage increases after sandbox runs though close the sandbox

### ISSUE THREAD

**Issue by Wangnibaba** [sandboxie-plus/Sandboxie#615]
Desktop Window Manager(dwm.exe) consumes a lot of memory after running a process in a sandbox(about 650MB while 90MB normally).

**Comment by DavidXanatos** [comment]
does that happen with any process on your system or only with particular once, and how long does it take to reach this value?

**Comment by DavidXanatos** [comment]
Is this issue still present?

**Comment by Wangnibaba** [comment]
Yeah，I have updated the Windows system and use the graphics drive version which don't have memory lack problem but the problem still exists

**Comment by Wangnibaba** [comment]
Yeah，I have updated the Windows system and use the graphics drive version which don't have memory lack problem but the problem still exists

**Comment by DavidXanatos** [comment]
Please thy the build 0.8.1 to be released today, does it fix the issue

**Comment by DavidXanatos** [comment]
how dow sit look with 1.0.9 there were a few fixed in between

**Comment by DavidXanatos** [comment]
since there is no more feadback on that and we havnt received more reports of this sort I'll close this
