### ISSUE TITLE
Question: How to direct write all network shares?

### ISSUE THREAD

**Issue by TooYoungTooSimp** [sandboxie-plus/Sandboxie#616]
I have some network shared folders in my LAN, and I want them can be direct modified by sandboxed program. How should I configure the sandbox rule?
Thanks.

**Comment by TooYoungTooSimp** [comment]
As for now, I can add one share like adding
![image](https://user-images.githubusercontent.com/6648049/109276584-2b5aff00-7851-11eb-9473-03861c575a3c.png) in OpenPipePath page. But when I have many shares, repeating this will be not so elegant.

**Comment by DavidXanatos** [comment]
you can use wildcard *
like 
```OpenPipePath=\\MyNas\*```

**Comment by TooYoungTooSimp** [comment]
thanks for your reply.
Is it possible to many devices?
Like `\\*` works for all computers in my lan ?
Will it conflicts to Windows internal path like `\\.\` ?
Looking forward to your further information.

**Comment by DavidXanatos** [comment]
yes it will conflict and open holes in the sandbox

**Comment by TooYoungTooSimp** [comment]
So if all my computers' names begin with same string like `DESKTOP-***`, is it possible to use `\\DESKTOP-*` to achieve my goal?

**Comment by DavidXanatos** [comment]
yes i think that should work

**Comment by TooYoungTooSimp** [comment]
Ok I'll give it a try

**Comment by TooYoungTooSimp** [comment]
Works confirmed, thanks for your guidance.

**Comment by DavidXanatos** [comment]
your welcome
