### ISSUE TITLE
What about refactoring the Credentials template?

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#618]
https://github.com/sandboxie-plus/Sandboxie/blob/003020feee5a38d1c9719577a535eae782fbbb33/Sandboxie/install/Templates.ini#L148-L151

https://github.com/sandboxie-plus/Sandboxie/blob/28a3109653e3a702adb7504155956b83bcf74a76/Sandboxie/msgs/Sbie-English-1033.txt#L3259-L3261

In my opinion there are two choices: 
1) keep it, but under a different template name/category and/or with a different localization string like: `Save outside sandbox:  Account information for websites, apps and networks` or just `Save outside sandbox:  Windows credentials`
2) remove it

**Comment by DavidXanatos** [comment]
i would remove it
