### ISSUE TITLE
Steam installation issue with some antiviruses

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [sandboxie-plus/Sandboxie#619]
Application - Steam Installer.
https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe
Installation does not get launched, I have got an error:
```
SBIE2205 Сервис не реализован:  Win32Init.4 (C0000008)
SBIE2205 Сервис не реализован:  Win32Init.4 (C0000008)
```

Condition - installed Kaspersky Endpoint Security, tested with 11.5.0.590.
https://aes.s.kaspersky-labs.com/endpoints/keswin11/11.5.0.590/russian-INT-21.2.16.590.0.458.0/3430383139357c44454c7c31/keswin_11.5.0.590_ru_aes56.exe
Disabling antiviral protection does not fix issue, only way to get installer to work - uninstall Kaspersky Endpoint Security.

Long time ago I tested it with Kaspersky Endpoint Security 10 SP2, 11 - all they cause same error with Steam Installer
Last working Kaspersky Endpoint Security - 10.2.6.3733 SP1 MR4, BUT it is not supported anymore since June 2020

Such issues may occure with some other antiviruses, so please- report if you have same issue.

If any other information needs to be provided aor any actions to be done - ask and I will do it.

**Comment by NewKidOnTheBlock** [comment]
Installer works fine here.
That said, I already got a regular install of Steam outside the sandbox on my system.
It requires its own service `"C:\Program Files (x86)\Common Files\Steam\SteamService.exe" /RunAsService`

**Comment by isaak654** [comment]
@gandalfthewhite19890404 

You may try to block the access to some Kaspersky DLL like this one (if available for your product):

`ClosedFilePath=*klsihk*.dll`

Source:
https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic8e068e06.html?f=11&t=23420&p=124072#p124069

I still miss that community.

**Comment by gandalfthewhite19890404** [comment]
@isaak654
No, still does not work.

**Comment by isaak654** [comment]
It doesn't have to be the same DLL, you could always try with other files (including executables).

**Comment by gandalfthewhite19890404** [comment]
Mark issue as solved and close, please.
Tested with latest stable SB 1.0.15 and KES 11.8.0.384 (56 bit), W10 Pro x64, all settings are default.
