### ISSUE TITLE
[Feature Req] Reverse Fileaccess logic for Block

### ISSUE THREAD

**Issue by blovas** [sandboxie-plus/Sandboxie#623]
I always wanted to use Sandboxie for running browsers in a separate area. Being paranoid the only thing that bogs me all the time is the IMHO incorrect logic of the BLOCK file/folder access.

In the current implementation the BLOCK overrides all other access right. This makes sense, however it also creates a lot of complications.  For example you cannot create a block access now with let's say %Programdata% while providing read or write right to a specific subfolder! This makes no sense to me.  In order to achieve something like this you'd need to list everyt single subfolder underneath Programdata with a block access only to allow a single folder to go through.

GOAL>  Reverse the logic on the BLOCK access path, so that folders you EXPLICITLY configure for read or write access OVERRIDE the blocking rule. This way we could achieve something like a whitelist style firewall> A program would be BLOCKED compeltely from the filesystem (even for reads) except the folders you list.

Yes, I know that the sandboxed program wouldn't be able to CHANGE data in any of the folders, but it would still be able to READ your stuff from your folders. This is what I would like to prevent...

**Comment by DavidXanatos** [comment]
something liek this is already in the making
