### ISSUE TITLE
Option to block screen capture inside the sandbox

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [sandboxie-plus/Sandboxie#624]
See: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity
Example code:
https://github.com/Cingozr/SetWindowDisplayAffinity
https://github.com/ysc3839/NoScreenCap
At the moment, any application in the sandbox can get a fullscreen shot and thus get the contents of the windows of other sandboxes (and not just sandboxes).

**Comment by DavidXanatos** [comment]
these examples only show how to protect one window globaly its used now to protect encrypted black boxe content, but it does nto help to iplement the oposit, i.e. whats requested here.
Does anyone have some workign examples how to globaly block screeshoting?

**Comment by 0x4E69676874466F78** [comment]
Yes it's just an example of system functionality for specific windows. 
This is only if we want to protect the windows of a particular sandbox. 

I haven't dug into the API, but in your case you probably need to hijack the function to call the screenshot of the screen.

**Comment by bastik-1001** [comment]
`BlockScreenCapture=y` and `CoverBoxedWindows=y` have been added months ago, the former aims at preventing sandboxed apps capturing the screen and the latter tries to hide sandboxed apps from being captured. So, even if there might be cases in which it can't be used, I consider this to be implemented.
