### ISSUE TITLE
Templates and notification messages messed up since 0.6.7

### ISSUE THREAD

**Issue by cretoo** [sandboxie-plus/Sandboxie#628]
The add templates section is messed up, lacks description since version 0.6.7. 

https://i.imgur.com/egXDIr2.png

**Comment by DavidXanatos** [comment]
do you still have this issue in the latest build?

**Comment by cretoo** [comment]
Yes, this issue is still present in the lastest build.

**Comment by DavidXanatos** [comment]
what about the latest build now?
