### ISSUE TITLE
No isolation between Sanboxed and non-Sandboxed google Chrome.  (Sandboxie-plus - 0.7.1)

### ISSUE THREAD

**Issue by smithy49** [sandboxie-plus/Sandboxie#632]
Under Resource Access i've entered this: **C:\Users\username\AppData\Local\Google\Chrome\User Data\Default** 
and selected All programs | Direct in the hope that sandoxie-plus will ignore global chrome settings.  However opening and closing tabs in sandboxed chrome still affects the non-sandboxed chrome and vice versa.

Also when **sandboxed** chrome is open and i start **non-sandboxed** chrome i get this error: **_Profile error occurred_
Something went wrong when opening your profile. Some features may be unavailable.**  This error only occurs if the non-sandboxed chrome is open.

Platform: Windows 10 - 1909

**Comment by DavidXanatos** [comment]
Direct means its not isolated, not at all
if you dont eterenything it can be read but writes are redirected to the sandbox
for what you want you need "WritePath" a.k.a. "Hidden"
than the original system path will be hidden but the sandboxed program will be able to write into the sandboxed equivalent of that path

**Comment by smithy49** [comment]
Thanks, issue now resolved. Some documentation on Sandboxie-plus would be very helpful.

**Comment by smithy49** [comment]
Hi David,
I'm a little confused with the latest version of Sandboxie-Plus V-0.7.2.
In my Windows 10 tray i see two icons Sandboxie Control and Sandboxie-Plus. (see sandboxie-plus.PNG)
When I download a file in sandboxed chrome i get two notifications, one from classic sandbox and one from Sandboxie-Plus. (see sandboxie-plus-2.PNG)

This shouldn't be happening. 
So now i have options in Sandboxie Control which is classic Sandboxie and options in Sandboxie-Plus.
Is this a bug?
I've attached two photos.
Thanks.


 On Saturday, 6 March 2021, 11:25:29 GMT, DavidXanatos <notifications@github.com> wrote:  
 
 


Closed #632.

**Comment by isaak654** [comment]
@smithy49 I can't see the images you tried to post, please open a new issue.

**Comment by bjm234** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/652
