### ISSUE TITLE
SandboxieRpcSs.exe is not hidden from sandboxed application.

### ISSUE THREAD

**Issue by kaovilai** [sandboxie-plus/Sandboxie#634]
`HideHostProcess=SandboxieRpcSs.exe` is not working

The process were still able to detect presence of `SandboxieRpcSs.exe` when running inside sandbox.

**Comment by DavidXanatos** [comment]
because its not a host process, the SandboxieRpcSs.exe runs with one instance for every active sandbox in that sandbox.

**Comment by kaovilai** [comment]
Are there solutions?

**Comment by Trung0246** [comment]
Is this issue relate to this? Since some programs are able to detect the presence of SandboxieRpcSs.exe and I'm not sure if it considered to be VM evasion: https://github.com/sandboxie-plus/Sandboxie/issues/115

**Comment by kaovilai** [comment]
> Are these issues relate to this? Since some programs are able to detect the presence of SandboxieRpcSs.exe and I'm not sure if it considered to be VM evasion: #115, #234 

yep
> I wonder if randomizing the name for process SandboxieRpcSs.exe will avoid this problem or anything else I'm unaware of?

Well, if the randomization pattern cannot be detectable it might work. Sandboxie-plus is open-source afterall.

**Comment by kaovilai** [comment]
closing.. dupe of #234 and #115 .. but mainly #115 is my concern.
