### ISSUE TITLE
evelauncher.exe (26176): SBIE2205 Service not implemented:  CreateDesktop

### ISSUE THREAD

**Issue by Enrage2** [sandboxie-plus/Sandboxie#635]
Hi, I am new to Sandboxie and am trying to run another instance of eve online game launcher as it saves me from using a VM. But I get this error **evelauncher.exe (28656): SBIE2205 Service not implemented:  CreateDesktop** whenever I launch the program and the launcher does launch but it's empty. Not sure what it's asking me to do. Any advice? Thank you!
![Untitled](https://user-images.githubusercontent.com/80006198/109870667-5c01c500-7ca5-11eb-8f5e-280ea6e0c621.png)

**Comment by NewKidOnTheBlock** [comment]
So Eve requires its very own service?
(if you got a regular Eve installation you can check with `Win` -> `services.msc`)

**Comment by NewKidOnTheBlock** [comment]
I just saw it's on Steam.
I got the same error message in SB Classic 5.47.1

**Comment by DavidXanatos** [comment]
the problem is that that sandboxie normalyl blocks the  CreateDesktop API call, except form chroem and firefox, 
i'll add an option 
UseSbieWndStation=y
or 
UseSbieWndStation=program.exe,y

**Comment by Allsystemsnormal** [comment]
I have been trying to get eve to launch also but keep running into the same things as the op has. 
I'm not sure how to change the settings so i can add the  UseSbieWndStation=y or UseSbieWndStation=program.exe,y

**Comment by DavidXanatos** [comment]
you edit the c:\windows\sandboxie.ini file and add those lines to the box sections you need them in

**Comment by Allsystemsnormal** [comment]
How do i know which one to use and which box to put them in?

**Comment by DavidXanatos** [comment]
add it to the box you want to run the software in

**Comment by Allsystemsnormal** [comment]
Tried both UseSbieWndStation=y and UseSbieWndStation=program.exe,y and still getting SBIE2205 Service not implemented:  CreateDesktop. Even tried running it as admin. Also noticed that after a while i have to reenter those changes into the ini file every 5 minutes. Not sure why it's not working.
