### ISSUE TITLE
[Sbie Plus] Unusual Windows 7 detection for Windows 8.1 users

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#636]
Original issues: [here](https://www.wilderssecurity.com/threads/released-sandboxie-plus-sbie-fork-versions-with-signed-driver.434924/page-37#post-2993168) and [here](https://www.wilderssecurity.com/threads/sandboxie-plus-0-7.436454/page-3#post-2992104)

> I have uninstalled a old version of Sandboxie.
>I just tried installing the latest release of Sandboxie Plus on my Windows 8.1 laptop and it won't install.
> I get to the window where it's saying I need the provisional driver for Windows 7. Does it say this no matter what version of Windows it is being installed on?
> What do I do when I get to this window that pops up?

> Well it is getting worse for me. I uninstalled all versions of classic and Plus and tried to reinstall newest plus on Win 8.1
> 1. It told me I needed win 7 drivers?
> 2. Tried to install latest classic version.
> It told me I needed digitally signed something
> 3. Just re-ran the classic exe file and it installed
> 4. I now have edge listed as a option and it seems to be working
> 5. I got my releases from here
> Release Release v0.7.1 / 5.48.5 · sandboxie-plus/Sandboxie · GitHub
> I tried the Plus-x64-0.7.1 and that told me I needed win 7 drivers
> I then installed this Classic x64-5.48.5 (worked after two tries)
> But when I go to "About" it says I have plus installed (see image)
> do I have the latest versions?

Imho this should be investigated, as it seems that OS detection is not reliable for current Windows 8.1 systems.

**Comment by r4taw2mg** [comment]
Same problem here with the installer for 0.7.2: asking for Win7 driver during an install on Win8.1.

This was my first try of installing the Sandboxie sucessor. Before that I had the old non-oss version running.

**Comment by DavidXanatos** [comment]
just give it the w7 driver, nut sure why the detection fails in the past it worked.

**Comment by r4taw2mg** [comment]
I won't get any other problems, installing a Win7 driver? I do not want to install additional stuff that is not really needed.

BTW: My system was not upgraded from Win7. It started as a Win8 install.

**Comment by DavidXanatos** [comment]
> 
> 
> I won't get any other problems, installing a Win7 driver? I do not want to install additional stuff that is not really needed.
> 
> BTW: My system was not upgraded from Win7. It started as a Win8 install.

The drivers are binary identical, just signed differently.

the windows 10 driver is signed by MSFT and does nto upset any anti malware fools

the windows 7 driver is signed using a leakedcode certificate those results in a but load of false positives, 
the problem is that you cant obtain new code signing certificates for windows 7 that would run past march or so,
its a MSFT thing thay want to kill w7 support one way or an other.

**Comment by isaak654** [comment]
@DavidXanatos 

So he needs to use windows 7 drivers even if it has windows 8.1...

I think it has something to do with the following article:
[Microsoft: No Driver Updates Allowed for Win7 and Win8](https://www.osr.com/blog/2020/10/15/microsoft-driver-updates-allowed-win7-win8)

**Comment by isaak654** [comment]
Manual installation of Windows 7 drivers is no longer needed since the integration in v0.7.3 / 5.49.5, so this issue might be closed accordingly.
