### ISSUE TITLE
Vivaldi unable to save any file to HD

### ISSUE THREAD

**Issue by HikariWS** [sandboxie-plus/Sandboxie#639]
I had finally tried back to run Chromium browsers inside Sandboxie. ATM I have only Vivaldi installed (when the issue started many months ago, I was using Chrome and Brave) so it's the only I can try.

At first it all worked fine and none of those ugly issues happened. But when I tried to download a few files they never finished downloading and I had to download them on Firefox, which is on another sandbox. There's no error msg, downloads just don't finish. I kept using and same issue happened with some other downloads.

Oddest thing was when I tried to make a backup of TabFern, it also failed to save, also with no error msg. That made me believe it was some issue with Sandboxie and Vivaldi.

I then removed it from ForceProcess and now I rebooted PC, tried to save TabFern backup and it worked fine.

So, yeah, Vivaldi is unable to save downloaded files or internal files when it's sandboxed. Back to letting it free :/

**Comment by strx5** [comment]
I have just downloaded a couple files from Filecroco and Majorgeeks and made a backup of uBlock settings. The files were saved to \DefaultBox\drive\D.  I'm on Windows 7 x64, using Vivaldi 3.6.2165.40 32bit Portable. What web-sites did you have problems downloading from?

**Comment by HikariWS** [comment]
I'm using Vivaldi 3.5.2115.81 on Win10. I tried to download from limetorrents.info.

**Comment by strx5** [comment]
I've downloaded a magnet link, a torrent-file and even the files, linked to that torrent/magnet, via qBittorent which ran sandboxed. I was also able to open the downloaded files with Potplayer in the sandbox. Try updating Vivaldi. (What else?..)

**Comment by HikariWS** [comment]
Tnx for taking the time to test it :)

Yeah next step is to update everything. I'm 1 version behind on Vivaldi and still on Sandboxie 5.46.5. Due to trouble when upgrading Sandboxie, I'm avoiding do it and staying some versions behind. I'm gonna upgrade them then reenable Vivaldi on sandbox and try it again.

**Comment by DavidXanatos** [comment]
I'll close this for now if the issue still appears in a recent build please open a new issue
