### ISSUE TITLE
About driver signing in Windows 7

### ISSUE THREAD

**Issue by matheuswillder** [sandboxie-plus/Sandboxie#641]
Some time ago I received a notification of a answer that was published in the Microsoft Community about the driver signature in Windows 7:
https://answers.microsoft.com/en-us/windows/forum/windows_7-hardware/windows-7-and-10-driver-signing/ad230fb1-df94-4992-a937-3afd52249a36

I believe it must be the solution to the problem but as the builds continue with the provisional driver, I decided to open this issue just in case @DavidXanatos missed the answer posted there.

**Comment by isaak654** [comment]
The link points to an invalid github url, this is the correct one:
https://answers.microsoft.com/en-us/windows/forum/windows_7-hardware/windows-7-and-10-driver-signing/ad230fb1-df94-4992-a937-3afd52249a36

**Comment by matheuswillder** [comment]
>The link points to an invalid github url, this is the correct one:

Thank you, edited.

**Comment by DavidXanatos** [comment]
The solution is none unfortunately, with those patches the explorer recognizes the certificate yes, but the windows kernel still refuses to load it.
So the provisional driver is here to stay unfortunately for the foreseeable future.
