### ISSUE TITLE
File Migration preset appears duplicated in Settings

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#642]
File Migration preset is duplicated in Sandboxie Classic 5.49.0 and 5.48.5. 
This may confuse some users... I would suggest to change the title to one of them if you really want to keep both presets (although I think that the old one should be removed without accommodating the users with the old template applied).

![duplicated_file_migration_preset](https://user-images.githubusercontent.com/12372772/110136232-bc8d2100-7dcf-11eb-826b-bf793cb62e75.png)

**Comment by NewKidOnTheBlock** [comment]
It's also duplicatedin the Templates.ini:
`
[Template_FileCopy]
Tmpl.Title=#4295
Tmpl.Class=Misc
DontCopy=*.url
CopyEmpty=*\microsoft\windows\explorer\thumbcache_*
CopyEmpty=*\microsoft\windows\explorer\iconcache_*
# firefox
CopyAlways=*\places.sqlite
CopyAlways=*\xul.mfl
# windows installer etc
CopyAlways=*\qmgr0.dat
CopyAlways=*\qmgr1.dat
CopyAlways=*\infcache.1
CopyAlways=*\cbs.log
# internet explorer 10 web cache
CopyAlways=*\webcachev*.dat

[...]

#
# Deprecated templates
#

[Template_Neon_Force]

[Template_Neon_Bookmarks_DirectAccess]

[Template_Neon_History_DirectAccess]

[Template_Neon_Cookies_DirectAccess]

[Template_Neon_Passwords_DirectAccess]

[Template_Neon_Preferences_DirectAccess]

[Template_Neon_Profile_DirectAccess]

[Template_Neon_WallpaperAccess]

[Template_Neon_Separator]

[Template_DefenseWall]

[Template_ActiveSync]

[Template_WindowsFontCache]

[Template_Windows10CoreUI]

[Template_FireFix_for_Win7]

[Template_FileCppy]
Tmpl.Title=#4295
Tmpl.Class=Misc
DontCopy=*.url
CopyEmpty=*\microsoft\windows\explorer\thumbcache_*
CopyEmpty=*\microsoft\windows\explorer\iconcache_*
# firefox
CopyAlways=*\places.sqlite
CopyAlways=*\xul.mfl
# windows installer etc
CopyAlways=*\qmgr0.dat
CopyAlways=*\qmgr1.dat
CopyAlways=*\infcache.1
CopyAlways=*\cbs.log
# internet explorer 10 web cache
CopyAlways=*\webcachev*.dat
`

**Comment by isaak654** [comment]
Issue fixed in 5.49.8.
