### ISSUE TITLE
better visibile download installer link

### ISSUE THREAD

**Issue by Taschenbuch** [sandboxie-plus/Sandboxie#646]
maybe I am blind, but i found it quite hard to find the download link for the installer.
when i google for sandboxie i end up on this website without a download link:
sandboxie-plus.com
Then i am linked to this github repo but there is no direct download link or link to the release page in the readme. I had to click on "tags" -> "release" to find the releases. For people who are not programmers which are familiar with github, this is very hidden.

It would be nice, to have a link to the installer download directly very visible on the sandboxie-plus.com website and in the github repo readme. 

edit: okay i see there is a tiny release section on github on the right which i could have clicked too. But that is still too hidden

**Comment by DavidXanatos** [comment]
ok I'll improve that

**Comment by adriwitek** [comment]
Sorry for the comment but i've been searching in the files and I still dont know how to install sandboxie plus. 
i run cmd's but nothing seems to work

**Comment by DavidXanatos** [comment]
just download and install: https://github.com/sandboxie-plus/Sandboxie/releases/download/0.7.2/Sandboxie-Plus-x64-v0.7.2.exe

**Comment by DavidXanatos** [comment]
https://sandboxie-plus.com/download/
