### ISSUE TITLE
Incorrect check for sandbox name validity [bug]

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#649]
Sandboxie Classic 5.49.0

New validity check tests for matching start of string instead of whole string when checking sandbox names against special device names.

Example: Unable to create sandbox "consort" because it starts with "con".

Related suggestions & bugs:
* Would be good if all components would use the same shared code, say, a common function "IsValidBoxName()", for these tests (Classic, Plus, Driver, etc etc)
* "clock$" need not be tested as "$" is an invalid char
* Potentially similar issue in project "Start" > delete.cpp > ProcessFiles line 820
* Disallow "GlobalSettings" as a sandbox name, or create an appropriate fix as the headings in .ini overlap
* Disallow "UserSettings_xxx" for same reason
 

Line 191:
https://github.com/sandboxie-plus/Sandboxie/blob/a6a56633dfd15cde45e52f9304c8acb2f7ce35ec/Sandboxie/apps/control/CreateDialog.cpp#L178-L195

**Comment by DavidXanatos** [comment]
I have fixed the issue with the device names.
