### ISSUE TITLE
Warn or prevent broad "forced folder" settings

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#650]
Issue: Setting "Forced Folder" over-enthusiastically to "C:\\" prevents windows from booting.

Current:
* Sandboxie classic (5.49.0) warns a user (somewhat ambiguously and not to the point) when they set Force Folder to, for example, "C:\\".
* Sandboxie Plus (0.7.2) does not warn the user.

Suggestions:
* Classic and Plus to warn user properly
* Prevent any settings in the UI and in the INI that essentially break Windows.

**Comment by DavidXanatos** [comment]
will be added to plus in next build, that is UI only manually editing ini allows the user still to breaks things,
wil not be added to classic ui

**Comment by isaak654** [comment]
> If "Force Program" is added without the use of "Browse for File", no warning will be displayed.

This has been recently fixed in the latest CI builds.
