### ISSUE TITLE
Sandboxie-plus v0.7.2 (5.49.0) is installing both Classic version and Sandboxie-Plus

### ISSUE THREAD

**Issue by smithy49** [sandboxie-plus/Sandboxie#652]
I'm a little confused with the latest version of Sandboxie-Plus V-0.7.2.
In my Windows 10 tray i see two icons Sandboxie Control and Sandboxie-Plus. (see sandboxie-plus.PNG)
When I download a file in sandboxed chrome i get two notifications, one from classic sandbox and one from Sandboxie-Plus. (see sandboxie-plus-2.PNG)
I don't think this shouldn't be happening. 
So now i have options in Sandboxie Control which is classic Sandboxie and options in Sandboxie-Plus.
Is this a bug?
I've attached two photos.
Thanks.

![sandboxie-plus-2](https://user-images.githubusercontent.com/6471037/110242918-11f03c00-7f50-11eb-98ef-b903b3fa6887.PNG)
![sandboxie-plus](https://user-images.githubusercontent.com/6471037/110242925-161c5980-7f50-11eb-90cb-2d3dbaa1467b.PNG)

**Comment by bjm234** [comment]
Users may set Start UI preference.
![image](https://user-images.githubusercontent.com/25015553/110249290-81136380-7f43-11eb-9e6d-8f1b00fcbf28.png)
