### ISSUE TITLE
Sandboxie-Pluse (0.7.2) no longer recovers files to folder.

### ISSUE THREAD

**Issue by smithy49** [sandboxie-plus/Sandboxie#657]
Sandboxie-Plus 0.7.1 prompted file recovery of downloaded files to selected folder.

Version 0.7.2 does not prompt file recovery even after **Enable Immediate Recovery** is checked.

Browser: Sandboxed Chrome.

**Comment by bjm234** [comment]
![image](https://user-images.githubusercontent.com/25015553/110338826-74e7de80-7ff5-11eb-8285-aed6d9aafdd8.png)
0.7.2

**Comment by smithy49** [comment]
I don't see Chrome-File Recovery at all.
You should explain what you are doing so that i can duplicate your steps.
What I get is a file recovery prompt, when it actually **works**.
Version 0.7.1 worked well.

**Comment by bjm234** [comment]
Hmm...I'm doing same as I've done with 0.7.1.  
Download 3 files as test.  
Close Chrome

**Comment by bjm234** [comment]
```
Immediate Recovery is an extension of Quick Recovery. Both Quick and Immediate Recovery scan the list of folders configured in Sandbox Settings > Recovery > Quick Recovery, and suggest an easy way to move any files (or folders) found out of the sandbox.

Quick Recovery is invoked by explicit request, or just before the sandbox is deleted, that is, typically it is invoked after the sandboxed programs have finished running. By contrast, Immediate Recovery works within the sandboxed program, and identifies files as soon as they are created and eligible for recovery.
```
https://xanasoft.com/sandboxie/immediaterecovery/

**Comment by DavidXanatos** [comment]
> 
> 
> So are you saying that i should close Chrome to recover files?
> I did try that but i did not see the window above.
> However when Sandboxie-Plus does work i see the recovery prompt shown below.
> That's the way it should work but the prompt doesn't appear every time i download a file, so it seems to me there is a bug.
> I really wish **David Xanatos** replies since he is the author.
> 
> ![sandbox](https://user-images.githubusercontent.com/6471037/110457853-01ac9e00-80c3-11eb-8250-97420c35e0af.PNG)


For me Immediate recovery with chrome works as always the dialog appears as soon as the download finishes

you should add the default Immediate recovery exclusion template to not get notifications about *.tmp and *.crdownload as these are imcomplete

**Comment by DavidXanatos** [comment]
please let me know if this issue is still presetnt since the affected build a lot of fixed were aplpied

**Comment by smithy49** [comment]
Using v1.0.3 and problem seems to be resolved.
Thanks
    On Sunday, 19 December 2021, 12:39:04 GMT, DavidXanatos ***@***.***> wrote:  
 
 


please let me know if this issue is still presetnt since the affected build a lot of fixed were aplpied

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
