### ISSUE TITLE
usability in global settings

### ISSUE THREAD

**Issue by readtheslash** [sandboxie-plus/Sandboxie#658]
Is it usable to include admin right emulation in global settings? And if ForceFolder and ForceProcess are in global settings, it should ask which sandbox to use instead of DefaultBox.

**Comment by DavidXanatos** [comment]
You can use admin right emulation in global settings.

> And if ForceFolder and ForceProcess are in global settings, it should ask which sandbox to use instead of DefaultBox.
> 

That's problematic to implement as ForceFolder and ForceProcess are done by the driver it would necessitate to invoke a user mode component to display a box selection prompt.
