### ISSUE TITLE
Feat Req: Option to enforce loading by file destination

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#66]
Sandboxie allows users to force folders and programs system wide into sandboxie,  this causes issues for example if you enforce firefox, but also use TOR, which also uses firefox.exe, but does not function in sandboxie currently. There are myriad of circumstances where forcing programs can have unwanted consequences, please consider adding an option to force programs based on their directory, so other programs with the same name but operating in a different directory wont be inadvertently pulled into Sandboxie.

Thanks!

**Comment by DavidXanatos** [comment]
sounds useful have put it on my todo list

**Comment by rugabunda** [comment]
Marvelous thanks David

**Comment by AndhikaWB** [comment]
@rugabunda is this feature already added? I don't think you should close unresolved issue/feature request.

**Comment by DavidXanatos** [comment]
yea keeping it open helps me keep my todo organized

**Comment by DavidXanatos** [comment]
> 
> 
> Sandboxie allows users to force folders and programs system wide into sandboxie, this causes issues for example if you enforce firefox, but also use TOR, which also uses firefox.exe, but does not function in sandboxie currently. There are myriad of circumstances where forcing programs can have unwanted consequences, please consider adding an option to force programs based on their directory, so other programs with the same name but operating in a different directory wont be inadvertently pulled into Sandboxie.
> 

How is that differen from frocefolders?
