### ISSUE TITLE
sandboxie plus no longer works with firefoxportable

### ISSUE THREAD

**Issue by darchon7** [sandboxie-plus/Sandboxie#661]
when i run firefoxportable via the latest ver of sandboxie plus:

"C:\Program Files\Sandboxie-Plus\start.exe" "D:\Program Files\FirefoxPortable6\firefoxportable.exe"

i get an "Application Error", the application was unable to start correctly (0xc0000005). Click ok to close the application."

but i have no problems running it without sandboxie.

**Comment by NewKidOnTheBlock** [comment]
Did you try the full installer?
https://www.mozilla.org/de/firefox/all/#product-desktop-release

That one always worked for me in SB, making the portable version unnecessary.

**Comment by DavidXanatos** [comment]
is that the same issue as: https://github.com/sandboxie-plus/Sandboxie/issues/651#issuecomment-796485265
strangely for me the latest desktop firefox start and opens websites just fine
does the issue appear for you with 0.7.2  as well and 0.7.1 was fine?

**Comment by DavidXanatos** [comment]
is the issue only when its installed inside sandboxie?

**Comment by DavidXanatos** [comment]
does this

ClosedFilePath=*BitDefender*atcuf*.dll
WriteFilePath=C:\Program Files\Bitdefender\*

solve your issue? like for the #651 issue?

**Comment by isaak654** [comment]
> 
> 
> does this
> 
> ClosedFilePath=_BitDefender_atcuf*.dll
> WriteFilePath=C:\Program Files\Bitdefender*
> 
> solve your issue? like for the #651 issue?

You didn't write it correctly, you should put it in code tags.
Like this:
```
ClosedFilePath=*BitDefender*atcuf*.dll
WriteFilePath=C:\Program Files\Bitdefender\*
```

**Comment by darchon7** [comment]
yup just tried:

ClosedFilePath=*BitDefender*atcuf*.dll
WriteFilePath=C:\Program Files\Bitdefender\*

that totally fixed it.

**Comment by DavidXanatos** [comment]
ok great that I'll close this one right away as we have a duplicate
