### ISSUE TITLE
RETITLED: firefox.exe does not follow openfilepath rules since version 5.42 (windows 10 pro x64 1903)

### ISSUE THREAD

**Issue by nik-gr** [sandboxie-plus/Sandboxie#664]
EDIT: with so many open issues I thought to try to assist by tracing where the issue started, so since 5.42 firefox.exe does not get direct access to files although there are openfilepath rules for those files and in such configuration it runs VERY slow. I have the steps that reproduce the problem at a follow post below. The issue existed with older versions of waterfox as well so it has nothing to do with the version of firefox (right now I'm using ff 85.0.2)
__

I'm using sandboxie 5.49.0 on  windows 10 pro 1903 x64. I had the same problems with waterfox classic and it was the reason I ended up staying with sophos version a few months ago

I have firefox as a portable app at an unsandboxed path of my choice and my firefox profile in a similar path. 
From the sandbox I run it, firefox.exe has access to the profile but direct access only to few of the files there but it doesn't follow those rules: 
- It successfully gets direct access to places.sqlite but 
- I give direct access to key4.db, logins.json, logins-backup.json, it never saves there any new logins-passwords (not inside sandbox as well)
- I give direct access to sessionstore.jsonlz4, sessionCheckpoints.json, sessionstore-backups\recovery.jsonlz4, it only creates same files with .tmp (sessionstore.jsonlz4.tmp etc)

I checked online and it seems that ff creates X.tmp files when it fails to get write access to X files. The problems perhaps are not limited only to those, for sure whatever happens has a big performance impact, ff is much slower and I have the feeling it gets worse by time much more than it should be expected from having it running for a long time. 

*None of these issues exist with sophos versions, the same sandboxie.ini and firefox works as it's supposed to

**Comment by RandomGOTI** [comment]
Does this version works ? https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.6.0

**Comment by nik-gr** [comment]
Oh that was a mistyped, I'm using the latest version 5.49.0 not 3.49.0 (I just corrected the initial post). When I tried sandboxie-plus in the past I think it was earlier than the version you mention and the problem was there for waterfox classic. I will check the one you mention tomorrow and update

**Comment by nik-gr** [comment]
ok now I see why you asked me to check that version @RandomGOTI , nope the same issue is there as well. 
simple steps to reproduce it:
1. Put firefox application files at e:\test\ff\
2. Have the profile folder at E:\test\profile\
3. create a sandbox named firefox with this configuration:

> [firefox]
> 
> ConfigLevel=8
> Template=SkipHook
> Template=FileCopy
> Template=AutoRecoverIgnore
> BorderColor=#00FF80
> AutoDelete=y
> ProcessGroup=<InternetAccess>,firefox.exe
> ProcessGroup=<firefoxG>,*
> OpenFilePath=firefox.exe,E:\test\profile\places.sqlite
> OpenFilePath=firefox.exe,E:\test\profile\favicons.sqlite
> OpenFilePath=firefox.exe,E:\test\profile\key4.db
> OpenFilePath=firefox.exe,E:\test\profile\logins.json
> OpenFilePath=firefox.exe,E:\test\profile\logins-backup.json
> OpenFilePath=firefox.exe,E:\test\profile\sessionstore.jsonlz4
> OpenFilePath=firefox.exe,E:\test\profile\sessionCheckpoints.json
> OpenFilePath=firefox.exe,E:\test\profile\sessionstore-backups\recovery.jsonlz4
> 
4. Run firefox sandboxed: 
> start  /hide_window /box:firefox cmd /c E:\test\FF\firefox.exe -no-remote -profile E:\test\profile

5, Try to save some login-password, bookmark a place, open multiple tabs and restart/terminte+restart
The bookmarked page is still there, favicons.sqlite is updated, no logins are saved, no session restore happens

I understand places.sqlite was hardcoded accessible and now it is through FileCopy template but I'm not sure that is the reason behind it, favicons.sqlite is also directly accessible even though it is not included at the FileCopy template
But for the rest of the files in the profile that I have above for whatever reason the openfilepath rule is not respected

**Comment by DavidXanatos** [comment]
could you please try older versions to find out which version introduced that issue?

**Comment by nik-gr** [comment]
Hi @DavidXanatos, it is the version I mention. With version 5.41.2 it works as expected, version 5.42 introduces the issue

**Comment by nik-gr** [comment]
Any updates with this?

**Comment by DavidXanatos** [comment]
I tried version 0.7.3 and could not reproduce the issue,
does it for you still appear?

**Comment by nik-gr** [comment]
ok, that is strange... Yes, I updated to 0.7.3/5.49.5 but the problem still exists with my configuration, no session restore is happening,  no saved logins remain saved

**Comment by nik-gr** [comment]
Update:
places.sqlite gets updated even if I don't have openfilepath for it (as expected because of the included filecopy template)
favicons.sqlite gets updated even if I don't have openfilepath for it (why? hardcoded?)
Just to be sure I even used an almost clean sandboxie.ini with only a couple of global settings and only the firefox sandbox and the issue is still there

**Comment by isaak654** [comment]
@nik-gr As far as I know, favicons.sqlite is not hardcoded, but available as an optional template: https://github.com/sandboxie-plus/Sandboxie/blob/3a3e5be67749c7d37c7bc1f2678cdd1df3e5ba02/Sandboxie/install/Templates.ini#L166-L171

Do you have some third-party security software that could interfere with the recent versions of Sandboxie?

**Comment by nik-gr** [comment]
This is a very delayed update, I had my hands full and no time to deal with it. 

So I am on a new pc but with the exact same configuration and all. Only difference is the windows 10 version, here I have windows 10 20H2 Pro (and any changes I might had done in the registry of the old pc but I doubt it could have made any difference). 
The issue does not seem to exist on this version of widows. I have sandboxie 5.49.7 installed (but the same version still have the issue on the old pc with 1903). 

So I am closing this, @DavidXanatos just to keep in mind in case you remember,
> 
> 
> I tried version 0.7.3 and could not reproduce the issue,
> does it for you still appear?

if you tested it on a newer version than 1903 Pro, that might be the reason for that
