### ISSUE TITLE
How to run NFS shared app in sandbox

### ISSUE THREAD

**Issue by clarklee92** [sandboxie-plus/Sandboxie#666]
Dear developers:
  Recently  I catch an issue when I try to use Sandbox in remote NFS storage：
![image](https://user-images.githubusercontent.com/20755443/110757280-29982f00-8286-11eb-96af-3a7ee7afae78.png)
   
 The storage disk was mounted by `mount.exe 9.136.64.42:/myshare E:\` . I could double click to execute every app locally. If sandbox execution permissions need to be increased, please inform me, thanks !

**Comment by DavidXanatos** [comment]
add
```BlockNetworkFiles=n```
to your sandboxie ini

**Comment by clarklee92** [comment]
> add
> `BlockNetworkFiles=n`
> to your sandboxie ini

Thanks! that works.
