### ISSUE TITLE
Sandboxie Plus >= 0.71, Win10, Unigine and AMD.  'CRITICAL_PROCESS_DIED' BSOD

### ISSUE THREAD

**Issue by A2Razor** [sandboxie-plus/Sandboxie#667]
**Summary:** Windows 10 LTSC 1809 and Windows 10 20H2, on Sandboxie Plus > version 0.70, coupled with AMD graphics hardware / drivers triggers 'CRITICAL PROCESS DIED' BSOD --> immediately on launching Unigine benchmarks (witnessed in Valley and Heaven, may effect others).

**Backstory / Observations:**  Configured a new laptop by cloning my main desktop's drives over to it {runs Windows 10 LTSC}.  Post peer2peer adjust and driver installation, immediately hit an intermittent lockup -- 'CRITICAL PROCESS DIED' -- {_about 50% of the time_} when starting Unigine Heaven and Unigine Valley -- **which I of course had under a Sandbox**.  ---> This connection was not immediately apparent.

Long story short, several hours later, lots of troubleshooting further and trying various drivers, running memtest, etc.  I found that I could increase the rate of crashes to "always" / every-time by removing the NVidia component and forcing Unigine to start on the integrated graphics {Ryzen 4600H} ... instead of passthrough from the discrete NVidia card.

Curious if the problem was caused by AMD's drivers, I started Unigine on my desktop.  Low and behold, it also crashed on my 6900 XT {_being that the desktop was an exact duplicate of the laptop's contents, minus hardware differences_}.  I then tried various graphics cards in said desktop.  {_Geforce 1650S, 980 Ti, Vega64 FE, and a few other old ones_}  The result is that all AMD cards locked up identically, whereas the NVidia cards did not.   ---> At this point I finally ran the benchmark tools outside of a Sandboxie, to realize that they did not crash on any of the tested hardware.

- It's AMD specific coupled with Sandboxie Plus, ****and**** something Unigine's graphics benchmarks do {as I've not found any game or benchmark otherwise to cause such}.
- Does not seem to impact NVidia hardware.
- fresh Windows 10 installation, AMD drivers, Sandboxie Plus -- same BSOD observed
- AMD drivers 19.12.1 through 21.2.3, no difference.
- Sandboxie Plus version 0.70 is not effected.  {seems to have started with 0.71's additions}
- Some BSOD minidumps from the laptop are attached.

[Minidump.zip](https://github.com/sandboxie-plus/Sandboxie/files/6122246/Minidump.zip)

Laptop [for reference]: Gateway Creator Series 15.6" FHD Performance Notebook, AMD Ryzen 5 4600H, NVIDIA 1650 GTX {GWTN156-2BK}

**Sandbox parameters:**

[StressTest]

ConfigLevel=8
AutoRecover=n
Template=SkipHook
Template=FileCopy
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
BorderColor=#00ffff,off,6
Enabled=y
NeverDelete=y
FileRootPath=E:\\Sandboxie\\%USER%\\%SANDBOX%
BoxNameTitle=n
BlockNetworkFiles=y
BlockNetParam=y
DropAdminRights=y
ClosePrintSpooler=y
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
CopyLimitSilent=n
AutoDelete=n

EDIT:
I may have jumped the gun on the claim that 0.70 is stable here {per that it started in 0.71}.  Have been repeatedly launching Unigine on 0.70 and just managed to lock up the laptop again with the same BSOD code.

-- It's definitely stable **without** Sandboxie though..  Yet sadly, the hint of where to look in code changes for the cause seems to be wrong.  Something in 0.71 causes higher crash frequency, though.  Will keep experimenting and hope that I find something solid of a version where this started happening, since I know I used to launch Unigine _without-issue_ under a Sandbox.  Both on the old iteration of Sandboxie (pre Sandboxie Plus), and post the OpenSource migration.

**Comment by DavidXanatos** [comment]
could you try to find our which exact version of sandboxie introduced the error
how does Release v0.6.7 / 5.47.1 behave?

**Comment by A2Razor** [comment]
> 
> 
> could you try to find our which exact version of sandboxie introduced the error
> how does Release v0.6.7 / 5.47.1 behave?

When I go under 0.71, it takes a lot of tries {and I mean A LOT} to get a crash, so this might take awhile to have some confidence that there won't be some exotic crash eventually.

But yeah, working on it as we speak to try to get you some hint.

**Comment by DavidXanatos** [comment]
try adding
AllowRawDiskRead=y
OpenSamEndpoint=y
OpenDevCMApi=y
BlockWinRM=n
to your ini for testing doe it change the behavior of the issue in post 0.7.1 and later builds?

**Comment by DavidXanatos** [comment]
also do you have the trace log enabled?

**Comment by A2Razor** [comment]
> try adding
> AllowRawDiskRead=y
> OpenSamEndpoint=y
> OpenDevCMApi=y
> BlockWinRM=n
> to your ini for testing doe it change the behavior of the issue in post 0.7.1 and later builds?

Behavior doesn't seem to change on 0.7.2 with those added to the ini.  e.g, still crashes every time when testing on my desktop.

> also do you have the trace log enabled?

I did not, yet before trying again I threw "DebugTrace=y" in there as well -- and enabled trace from the GUI.  Don't seem to be able to dump anything before the system locks up. {yet it happens very fast too}

Symptom wise, it immediately occurs with the benchmark's window creation {within a split second of starting the benchmark}.  Window edges appear, BSOD right-after.  Interestingly ... it seems that choosing OpenGL as the API used by Heaven, and disabling all advanced features {such as tessellation}, doesn't alter crash. {can't get any benchmark to start by altering the benchmark settings}  I also tried fullscreen, windowed mode, and various resolutions for the sake of completeness.

- Whatever it is, it's something the benchmark does in-common between all 3D API's during its init.



Did not succeed in getting 5.33-6 to crash.  Also tested Sandboxie Plus 0.5.5, which did BSOD immediately {got lucky and didn't spend much time there}.

Since this is so variable sometimes {minus on the latest Plus builds}, I'm still not completely convinced that 5.33-6 is stable.  Trying to rule out if that's a fluke or not, so we can know if this is infact part of the changes in Plus, before trial running more versions.  -- I mean, I did not run Unigine clearly in quite awhile since I didn't even notice this until now.

So it's always possible that some other changes (such as to Windows) are involved.  Yet so far, 5.33-6 has survived many hours of benchmark starts and stops, and that's looking less likely.

**Comment by NewKidOnTheBlock** [comment]
I'd never have come up with the idea to run a benchmark in Sandboxie, but here it goes:
![valley](https://user-images.githubusercontent.com/12411527/110908761-90adf600-830f-11eb-9b34-82d76ed0c14c.jpg)
...works fine with AMD Vega56 + Sandboxie 5.49.0

**Comment by A2Razor** [comment]
> I'd never have come up with the idea to run a benchmark in Sandboxie, but here it goes:
> ...works fine with AMD Vega56 + Sandboxie 5.49.0 @ Unigine Valley
> I was able to complete an entire benchmark run.

Interesting.  I do notice that you mentioned "5.49" rather than 0.7.2, so I assume classic control panel is running, and while doubtful that SandMan specifically is the cause ... at the same time I never tried running the benchmark with it closed, or on a classic iteration.  _I'll give that a shot too when I get the chance._

Far as benchmark duration, on the chance that a Unigine benchmark starts I have no stability problems with it thereafter {as in, running the benchmark itself won't crash}.  Crashes only occur during startup / window creation.

> 
> Your setup sounds like a total clusterfuck.
> You got an AMD laptop APU (with graphics) + Nvidia GPU, that means you have _both_ graphics drivers installed at the same time. That's already asking for trouble, but for some reason you decide to run the benchmark on the weak(er) APU instead of the GPU. What is the point of this whole exercise?

Installing just the AMD drivers for the 4600H results in the same crash.  With the NVidia discrete (1650) installed, and selected for Unigine, the crash still occurs yet is less frequent.  Desktop also exhibits the crash on a variety of hardware, though..

The point of the exercise?  **That's a fair question.**  There is no reason that I 'need' to have Unigine running under Sandboxie.  I could just as easily _"don't do that"_ and ignore this all, being that it's the only software I've found to pose a problem.  That said, where one program triggers a bluescreen, I'm sure there's more out there.

In the past, I believe I put a collection of stress testing tools under a Sandbox as an easy way to save the defaults in transfering them between systems.  Yet certainly it's not that I expect to compromise a system by running them.

**Comment by A2Razor** [comment]
-- Still testing on this when time permits.  Yet I believe I've at least ruled out that a system on 5.33-6 cannot be crashed by Unigine.  If it can, it's near impossible to do so [being that I've launched Unigine well over a thousand times, heh].

Will try another few versions of Sandboxie Plus before letting it go.  As NewKidOnTheBlock pointed out, it's only benchmarking tools {so far} and most people aren't even going to think to run something like this in a Sandbox.  Not critical by **ANY** measure.  -- I'll probably close this one myself unless I can pinpoint the exact version it starts on _with certainty_.

I'm also positive (tested on now four separate machines and multiple fresh installs), that this does not happen with only NVidia drivers present.  So it may not even entirely be the changes to Sandboxie to blame here.  It also seems far more common on Windows 10 LTSC, yet it CAN happen on mainstream as well.

**Comment by NewKidOnTheBlock** [comment]
There are a handful of games that use Unigine.
For example [Oil Rush](https://www.pcgamingwiki.com/wiki/Oil_Rush) - which also runs fine in Sandboxie 5.49.0 ;-P
![oil rush](https://user-images.githubusercontent.com/12411527/111540285-41ccea00-876f-11eb-90ac-a449b81e1770.jpg)

**Comment by A2Razor** [comment]
Never played OilRush, I'll give it a shot for the sake of seeing if it applies to 'games' built on the Engine, or if it's something specific the benchmarks attempt such as hardware / temperature polling.

**Comment by NewKidOnTheBlock** [comment]
They surely are best known for their benchmarks.
But there is also professional simulation software and games:
https://en.wikipedia.org/wiki/Unigine#Unigine-based_projects

**Comment by A2Razor** [comment]
Was ultimately not able to track down the specific version of Sandboxie Plus that caused the issue to crop up, yet that's fortunately because as of AMD's 21.3.2 drivers **it appears the BSOD has stopped-happening** and is no longer reproducible {on any of my systems, with any hardware combination -> including the originally tested laptop}.

On downgrading drivers, the crashes return, and on transitioning to the latest they discontinue.  Whatever this is / was, it was some form of a driver interaction specifically with the Unigine benchmarks, yet it no longer occurs as of the latest graphics driver release.

-- Also, no dice in reproducing on Unigine based games, only the Unigine benchmark software.  {_I personally suspect hardware polling {e.g, temps} _ -- built into the benchmark tools}

**Comment by NewKidOnTheBlock** [comment]
@A2Razor BTW, Oil Rush has become free to celebrate its 10th anniversary:
https://store.steampowered.com/app/200390/Oil_Rush/
