### ISSUE TITLE
Sandboxie Classic and Plus- hangs on win 7x86 sp1 pc

### ISSUE THREAD

**Issue by tutak-kat** [sandboxie-plus/Sandboxie#670]
Hi,
yesterday I found that problem on 2 win7 sp1 laptops, for ex. if I tried to change settings in Classic ( didn't try anything more than changing the color of sandbox from yellow to red or changing thickness of box) that action froze sandboxie.
On the same 2 laptops on Plus version if I try to change anything in options / global settings they also froze.

On my main pc win 7x64 sp1 everything works without any problem.
I don't remember what was the last version which works before, just installed new version above.
After I deinstalled everything, clean all leftovers on disk and registry and sanboxie.ini but still have the same problem.
Any ideas how to resolve that?
Thanks

**Comment by tutak-kat** [comment]
I also tried to directly edit sandboxie.ini to change color or width of box but it remain the same in program - not accepted.

Just now I tried to install on win 7 x86 latest version of Classic 0.7.2 and got flashing icon in tray with error (after restart):
SBIE1102 Sandboxie driver (SbieDrv) unloading
SBIE9234 Service startup error level 9153 status=C000035A error = -1073740966
and next 6 messages the same as the above one

**Comment by tutak-kat** [comment]
just made a mistake - I installed classic version 5.49 not plus ver 0.72

**Comment by isaak654** [comment]
@tutak-kat You just need to redownload the updated provisional package, read this: https://github.com/sandboxie-plus/Sandboxie/issues/648

**Comment by isaak654** [comment]
@tutak-kat You just need to redownload and apply the updated drivers package for Windows 7, read this: https://github.com/sandboxie-plus/Sandboxie/issues/648
Download for release v0.7.2 / 5.49.0: [here](https://github.com/sandboxie-plus/Sandboxie/releases/download/0.7.2/Provisional.Windows.7.Drivers.zip)

**Comment by tutak-kat** [comment]
Thanks isaak654 that resolved the problem
