### ISSUE TITLE
"smart" installer = difficulty installing into sandbox

### ISSUE THREAD

**Issue by boldcompany** [sandboxie-plus/Sandboxie#673]
Thanks in advance if you can help with this case:

There is a .exe installer for an application which (a) checks to see if the application is already installed and registered in the system, (b) tries to refuse to install if so, and then (c) if the refusal is overridden, doesn't write any files from the installer that it can detect as already installed in the system.

Suppose that a user already has this application installed natively (unsandboxed), but wants a second installation of the application in a sandbox for testing purposes. The user doesn't want to uninstall the native unsandboxed version, but instead needs both the unsandboxed and the sandboxed versions side by side. They need to both be installed in the standard default install locations.

There doesn't seem to be a way to configure a sandbox such that the installer run under it will (a) ignore system registry and (b) block read access to the already-installed files (unless the user manually specifies all the individual locations the user wants blocked) so that the installer will proceed to actually install.

The best thing would seem to be simply blocking the sandboxed installer from reading anything outside the sandbox, but there doesn't seem to be a way to do this - or is that wrong?

There is a setting under "Options -- File Options -- Raw Disk access" by which the user can disallow "elevated sandbox applications to read the harddrive" but this doesn't seem to have an effect on this situation.

Any ideas? Of note, this seems related to #194.

**Comment by DavidXanatos** [comment]
you can use
https://davidxanatos.github.io/sandboxie-docs/Content/WriteFilePath.html
https://davidxanatos.github.io/sandboxie-docs/Content/WriteKeyPath.html

to hide host locations from the sandboxed, than you should be able to install that app, what locations to hide though, you will need to figure out on your own

**Comment by boldcompany** [comment]
@DavidXanatos , thank you very much for taking the time to point out WriteFilePath and WriteKeyPath - much appreciated! This is very useful.

The challenge, if there are numerous circumstances like this for a user, is to spend the large amount of time tracking down exactly what to block. This is good for a one-off case, but it would be pretty tedious to specify WriteFilePath for dozens or hundreds of apps in an ongoing testing project.

One setting feature that would help is basically: "Don't allow read or write of anything at all on any drive in the system except (a) in the sandbox itself, and (b) the minimal system locations required to run sandboxie and the sandboxed app."

What do you think about that in the context of #194? 

Thanks again for the time you're taking to address these questions.

**Comment by DavidXanatos** [comment]
> 
> 
> One setting feature that would help is basically: "Don't allow read or write of anything at all on any drive in the system except (a) in the sandbox itself, and (b) the minimal system locations required to run sandboxie and the sandboxed app."
> 
> What do you think about that in the context of #194?
> 

I love it!

How ever creating a list of "minimal system locations required" will be a huge pain and to some extent system dependent...
Not sure if we could in some way work with a stock windows image as redirection target...

**Comment by typpos** [comment]
> How ever creating a list of "minimal system locations required" will be a huge pain 

On Windows 10, you could consider the Windows 10 Sandbox virtual image. I believe most of these are links to real system files, so would work with "if file on real system exists inside vhdx, then it's a base image file".
* ````C:\ProgramData\Microsoft\Windows\Containers\BaseImages````

**Comment by isaak654** [comment]
Update: if you have new suggestions, please post on the new issue #890, thanks.
