### ISSUE TITLE
Xanasoft.com error 522

### ISSUE THREAD

**Issue by bean224466** [sandboxie-plus/Sandboxie#674]
For some days now, xanasoft.com (and, of course, forum.xanasoft.com) returns error 522

**Comment by DavidXanatos** [comment]
yes I know: https://blog.malwarebytes.com/malwarebytes-news/2021/03/ovh-cloud-datacenter-destroyed-by-fire/

should be back on Monday, hopefully.

**Comment by bean224466** [comment]
Ouch.

**Comment by isaak654** [comment]
For anyone who wants to view Sandboxie documentation, there is a github version available at https://davidxanatos.github.io/sandboxie-docs

**Comment by DavidXanatos** [comment]
as it seams the server is gone for good, so in the days to come i will need to set it up again from scratch

**Comment by DavidXanatos** [comment]
server is up and  runnign again
