### ISSUE TITLE
Hide content of other sandboxes

### ISSUE THREAD

**Issue by tsao-chi** [sandboxie-plus/Sandboxie#677]
I reinstalled Windows and put everything into sandboxie for security through isolation.

Some programs are not fully trusted by me and I don't want them to read content of other sandboxes.

I tried hiding `C:\Sandbox` in `Resource Access`, and then I ran into trouble when I launched any program installed in sandbox.
```
... (3040): SBIE1231 Initialization failed for process  [C0000001 / A4]
```

**Comment by DavidXanatos** [comment]
yea that's to be expected

**Comment by tsao-chi** [comment]
Is it possible to accomplish this purpose?

**Comment by isaak654** [comment]
It's not the same thing, but you can move each sandbox into a different drive using FileRootPath:
https://davidxanatos.github.io/sandboxie-docs/Content/FileRootPath.html

You can also lock the configuration file using the options in Sandboxie Classic & Plus.
