### ISSUE TITLE
Sandboxed console programs cannot read output buffer

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#678]
This is a problem that I've already encountered several times; but only today I finally found out what the root cause is.

Basically, when a console application running in a sandbox tries to read the console output buffer (e.g. using `ReadConsoleOutput`) then it will always get an access denied error. Depending on the application this could lead to unexpected behavior or crashes. Examples where this occurs:
- the `Write-Progress` cmdlet in Powershell throws an unexpected error (breaking scripts using it)
- for testing: [Console.MoveBufferArea](https://docs.microsoft.com/de-de/dotnet/api/system.console.movebufferarea) which can be invoked in Powershell
- The NodeJS interactive console crashes after entering any command (with no apparent reason)
- ... and probably more

I decided to try and hunt down this issue after stumbling onto it again today. What I eventually found as common point was the issue with `ReadConsoleOutput` and after digging a bit more I found the reason why it always denied access:

The `conhost.exe` process that provides the console window runs outside the sandbox and with medium integrity level. But the actual sandboxed programs are running with "untrusted" integrity level. [As described here](https://docs.microsoft.com/en-us/windows/console/console-buffer-security-and-access-rights), there is an extra access check for so-called "wrong-way verbs", i.e. *writing* to the input buffer or *reading* from the output buffer. In those cases, Windows will always deny access if the requesting process has lower integrity level than `conhost.exe`.

So, after discovering this I tried simply lowering the integrity level of the corresponding `conhost.exe` process to "untrusted". And bingo, that indeed fixed the issue!

Now I wonder if we could just make SbieSvc do that by default for `conhost.exe` processes belonging to sandboxed processes? Are there possible side effects? At least I didn't notice any obvious ones...

**Comment by DavidXanatos** [comment]
do you have a quik and easy example how I could test that ithout wrinting an own test app that captchures the consoleoutput?

**Comment by hg421** [comment]
@DavidXanatos Yes, e.g. in Powershell you can call the `Console.MoveBufferArea` .NET function:

    [Console]::MoveBufferArea(0, 0, 10, 10, 10, 0)
or try this:

    Write-Progress -Activity Test

**Comment by DavidXanatos** [comment]
is that supposed  not to work in a sandbox?
strangely for me the command seamed to work the same in ad out of the sandbox,
the second one does not seam to do anything

**Comment by DavidXanatos** [comment]
I have added the option to auto drop the console host process integrity
```- added option to drop the console host process integrity use "DropConHostIntegrity=y"```
willbe included in the next build, pleae let me know if it fixes your issues

**Comment by hg421** [comment]
Thanks. It is really a curious issue, maybe something has changed between Windows versions, since I can reproduce the documented block behavior even without Sandboxie on my 1909 machine by following this:
1. start cmd.exe
2. drop integrity of cmd.exe (but not of conhost.exe) to 'Low'
3. run `powershell -Command Write-Progress -Ac Test`

which gives an internal Powershell error. But following the exact same steps on another machine running 20H2 did not produce any error...

---

Funny thing is, the Conhost source code is actually available as part of the [Windows Terminal repo](https://github.com/microsoft/terminal). And it shows that there is in fact supposed to be an API block based on integrity levels. See:

https://github.com/microsoft/terminal/blob/ea3e56db8134bad477ce15fc82a385820ee8723b/src/server/ApiDispatchers.cpp#L1033
https://github.com/microsoft/terminal/blob/ea3e56db8134bad477ce15fc82a385820ee8723b/src/server/ProcessPolicy.cpp#L35-L64

Sadly the function that actually decides about whether the block is applied (`Microsoft::Console::Internal::ProcessPolicy::CheckIntegrityLevelPolicy`) is not part of the repo but only stubbed there...

**Comment by DavidXanatos** [comment]
did 
DropConHostIntegrity=y

solve your issue?

**Comment by hg421** [comment]
> 
> 
> did
> DropConHostIntegrity=y
> 
> solve your issue?

Just tested it, yes it does! Now everything works fine on 1909 too. (Thanks again for adding the option!)

**Comment by DavidXanatos** [comment]
great!
