### ISSUE TITLE
Where is the "explore sandbox feature" so I can recover files?

### ISSUE THREAD

**Issue by kimski1** [sandboxie-plus/Sandboxie#679]
I cannot figure out the new sandboxie.   The GUI is designed for developers not those of us that want to use it to protect our computer.   Some files I download via sandboxed browser recover automatically and others do not.  I have NO idea how to manually recover them. 

Update:  I see the latest version has a recover option but I can't figure out where to go to download the latest.  Is it on https://www.sandboxie-plus.com/?  That site doesn't seem to be working.

Can someone please help me?  I cannot find any help guides to explain this.

**Comment by hg421** [comment]
Latest version can be found here on Github:
https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.7.2


Then "Explore content" is here (opens an file explorer window in which you can view/copy/move the files in the sandbox)
![screen](https://user-images.githubusercontent.com/78082344/111082928-409b8300-850b-11eb-86f3-e391e12d2dda.png)

If you want to recover files (move them to the same location outside the sandbox) you might want to use the "Recover files" option.

**Comment by isaak654** [comment]
> Is it on https://www.sandboxie-plus.com/? That site doesn't seem to be working.

It should be back on Monday (hopefully).
If you want to view Sandboxie documentation, there is a github version available at https://davidxanatos.github.io/sandboxie-docs

**Comment by kimski1** [comment]
Thank you.  I tried to install it but it keeps complaining about the app being open.  I closed all version of it but it still wont work.   Even though it didn’t install it ruined my current version.    When I run the install now I now get “control service interrogate” errors even though I didn’t do anything different and now my previous version doesn’t work!

Any ideas?

Kim

**Comment by isaak654** [comment]
> 
> Thank you. I tried to install it but it keeps complaining about the app being open. I closed all version of it but it still wont work. Even though it didn’t install it ruined my current version. When I run the install now I now get “control service interrogate” errors even though I didn’t do anything different and now my previous version doesn’t work! Any ideas? 

You shouldn't keep Sandboxie Classic and Plus installed at the same time.
Please look at here: [How to upgrade from classic Sandboxie?](https://github.com/sandboxie-plus/Sandboxie/issues/259)

If you need more support about the errors you're receiving, please attach some screenshot here.
Personally I never encountered these “control service interrogate” errors, so we need more details to support you properly.

**Comment by kimski1** [comment]
I was upgrading my Plus. not classic.   

![error](https://user-images.githubusercontent.com/75213353/111083946-8bef6a80-84e6-11eb-86a8-957936d75a98.JPG)

If I hit okay it procedes but when it gets to  "extracting license.txt" it says it can't continue as sandbox is running, but it's not.

![error2](https://user-images.githubusercontent.com/75213353/111084167-6a42b300-84e7-11eb-9193-f1ad53a7191b.JPG)

 I found the uninstall steps I believe but was hoping not to do that as I didn't recover my latest browser bookmarks.  I should have done that before but thought updating a version whouldn't break the current.

**Comment by kimski1** [comment]
I found the bookmarks data so I chose to uninstall it using the download file.   I restarted my computer and the app is still installed, but no default sandbox.   Not sure now which to use to install as the file located at https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.7.2 is only to overwrite or uninstall.....
