### ISSUE TITLE
An error will be reported when you double-click the program, and the right-click will be normal when the sandbox is running

### ISSUE THREAD

**Issue by lxitdn** [sandboxie-plus/Sandboxie#680]
I have added the forced operation of the sandbox, but when I double-click the program, an error will be reported. The right-click will work when the sandbox is running. What is the problem? I tested the old version and it seems there is no such problem
![QQ截图20210315230348](https://user-images.githubusercontent.com/16263881/111175107-07cedd00-85e3-11eb-88bf-b557fd48e6bc.png)

**Comment by isaak654** [comment]
Please specify which version of Sandboxie are you using and which version was working the last time.

**Comment by lxitdn** [comment]
> Please specify which version of Sandboxie has the problem and which version was working the last time.

I will appear in Sandboxie-Plus-0.7.2 and Sandboxie-Classic-x64-v5.49.0, and I tested that SandboxieInstall-533-6 will not appear and will work normally

**Comment by DavidXanatos** [comment]
can you test in which version this error got introduced?

**Comment by DavidXanatos** [comment]
On a clean windows 10 20h2 with 0.7.2 forced telegram starts just fine for me, it must be some setting or a like that is causing the issue.

**Comment by lxitdn** [comment]
> On a clean windows 10 20h2 with 0.7.2 forced telegram starts just fine for me, it must be some setting or a like that is causing the issue.

Oh, I’m not sure which version started to cause this problem, but mine seems to be all right now, no errors are reported, thank you
