### ISSUE TITLE
"Send to sandbox" option either missing or I cannot find it in sandboxie plus

### ISSUE THREAD

**Issue by fake-name** [sandboxie-plus/Sandboxie#682]
Basically the title.

I've used sandboxie extensively for probably 5+ years now, pretty much 98% of the time via the "send to" dialog option that the "classic" version inserted into the right-click -> send-to menu option.

Recently, I updated to the new Qt GUI, and it's basically the only option that the previous UI had that is now missing.

Is this actually not present? Or am I just blind?

Digging around, this appears to have been provided by the [`AddSendToMenu`](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/apps/control/ShellDialog.cpp#L41) option in the old GUI, backed by the [`SyncSendToMenu`](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/apps/control/ShellDialog.cpp#L777-L881) function.

Unless this function is completely renamed in the new Qt UI, it appears to indeed have been removed. Is there any chance this way of using sandboxie can be restored?

Otherwise, the new UI is very nice and I'd like to continue using it.

**Comment by Coverlin** [comment]
run sandboxie control (sbiectrl.exe) from install folder and add it from there

**Comment by fake-name** [comment]
I.... didn't realize the old UI was installed along with the new one. Derp!
