### ISSUE TITLE
When upgrading Sandboxie on my, or others computers, the installer gets stuck on License.txt.

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#686]
The upgrade works sometimes, but most of the time it doesn't work.
If I download the Sandboxie exe and change the name to SBI.exe and run the following batch file, it works every time.
The first part just waits for Chrome and Firefox to close.

Is it just me and my customers that have a problem with upgrading.

Echo On
cd %userprofile%\Downloads
:closechrome
tasklist /fi "IMAGENAME eq Chrome.exe" | find /I /N "Chrome.exe"
if NOT ERRORLEVEL 1 goto notclosechrome
goto closefirefox
:notclosechrome
timeout 10
goto closechrome

:closefirefox
tasklist /fi "IMAGENAME eq Firefox.exe" | find /I /N "Firefox.exe"
if NOT ERRORLEVEL 1 goto notclosefirefox 
goto firefoxclosed
:notclosefirefox
timeout 10
goto closefirefox

:firefoxclosed
"C:\Program Files\Sandboxie\Start.exe"  /terminate
net stop SbieSvc
taskkill /IM SbieCtrl.exe
taskkill /F /IM SbieCtrl.exe
rem SBI.exe /remove /S
SBI.exe /S
net start SbieSvc
SbieCtrl.exe
exit /b

**Comment by isaak654** [comment]
1) Which Sandboxie version did you have before the upgrade?
In case you don't remember, please look at [this](https://github.com/sandboxie-plus/Sandboxie/issues/713#issuecomment-807822827) post.

2) Which Sandboxie version did you use to upgrade?

**Comment by jedimasterspaz** [comment]
I've been having problems with installing and getting stuck at License.txt for months.  5.49 is even failing with the batch file, now.

Thanks

**Comment by isaak654** [comment]
So this is still related to #321.

I would suggest to backup your C:\Windows\Sandboxie.ini in another drive, then uninstall your current Sandboxie version, reboot, and reinstall again 5.49.

If the issue still persists, please send me the Sandboxie.log file contained in C:\Windows

**Comment by isaak654** [comment]
@jedimasterspaz Just in case, there could be an alternative solution here:
https://github.com/sandboxie-plus/Sandboxie/issues/713#issuecomment-811085291

In order to follow that method, you need to run a Sandboxie-Plus installer to extract all the files in a directory for portable use

If you decide to try it, don't forget to reboot at the end in order to know if it worked.

**Comment by jedimasterspaz** [comment]
When we hit the next update, I will try uninstalling 5.49 first, reboot, and install 5.5x.
Is there a way to just update to the next version without rebooting?
I'm trying to do auto-updating with an RMM.

Thanks, Mark

**Comment by jedimasterspaz** [comment]
You can close this, please.
