### ISSUE TITLE
"runas /user"command :  The RPC server is unavailable

### ISSUE THREAD

**Issue by r21N8AeVeov8** [sandboxie-plus/Sandboxie#688]
Windows 10.0.17763.316
Sandboxie-Classic-x64-v5.49.0
![26554](https://user-images.githubusercontent.com/80880561/111589023-49d46a80-87ff-11eb-9ce8-00759364ba63.jpg)
Like 360 Sandbox:
![226708](https://user-images.githubusercontent.com/80880561/111723668-e1d56100-889e-11eb-87f5-54c491fe21c7.jpg)

**Comment by isaak654** [comment]
Try adding `OpenIpcPath=\RPC Control\seclogon` in the sandbox of your sandboxie.ini configuration file

It's in the second example here: https://davidxanatos.github.io/sandboxie-docs/Content/OpenIpcPath.html

> The second example exposes the resource provided by the Windows Run As service. It can let a sandboxed program launch another program using the credentials of a different user. However, the launched program will execute outside of the control of Sandboxie.

**Comment by r21N8AeVeov8** [comment]
> Try adding `OpenIpcPath=\RPC Control\seclogon` to the sandboxie.ini configuration file, under your sandbox section.
> 
> It's in the second example here: https://davidxanatos.github.io/sandboxie-docs/Content/OpenIpcPath.html
> 
> > The second example exposes the resource provided by the Windows Run As service. It can let a sandboxed program launch another program using the credentials of a different user. However, the launched program will execute outside of the control of Sandboxie.
> > Note: The examples in this page, if applied, will create vulnerabilities within the sandbox. They are meant only to show why some resources are blocked, and how they can be un-blocked and exposed for use, if necessary.



> Try adding `OpenIpcPath=\RPC Control\seclogon` to the sandboxie.ini configuration file, under your sandbox section.
> 
> It's in the second example here: https://davidxanatos.github.io/sandboxie-docs/Content/OpenIpcPath.html
> 
> > The second example exposes the resource provided by the Windows Run As service. It can let a sandboxed program launch another program using the credentials of a different user. However, the launched program will execute outside of the control of Sandboxie.
> > Note: The examples in this page, if applied, will create vulnerabilities within the sandbox. They are meant only to show why some resources are blocked, and how they can be un-blocked and exposed for use, if necessary.

**Comment by r21N8AeVeov8** [comment]
> Try adding `OpenIpcPath=\RPC Control\seclogon` to the sandboxie.ini configuration file, under your sandbox section.
> 
> It's in the second example here: https://davidxanatos.github.io/sandboxie-docs/Content/OpenIpcPath.html
> 
> > The second example exposes the resource provided by the Windows Run As service. It can let a sandboxed program launch another program using the credentials of a different user. However, the launched program will execute outside of the control of Sandboxie.
> > Note: The examples in this page, if applied, will create vulnerabilities within the sandbox. They are meant only to show why some resources are blocked, and how they can be un-blocked and exposed for use, if necessary.

Thanks, this isn't what i want.

**Comment by isaak654** [comment]
> Thanks, this isn't what i want.

I see, you want it enabled by default without the workaround... it wasn't clear to me before your edit.

**Comment by isaak654** [comment]
> Thanks, this isn't what i want.

I see, you want it enabled by default and sandboxed like 360 Sandbox, while Sandboxie doesn't do that... it wasn't clear to me before your edit.

**Comment by DavidXanatos** [comment]
I have checked out this 360 Securits sandbox and its even worse then the comodo sandbox, you cant run applications inside with admin privileges, MSI installer does not work, no access to SCM, etc.... 

with regard to the runas specific issue, I'll check if it can be made working securely in sandboxie

**Comment by DavidXanatos** [comment]
Sooo...

in the next build when adding ```OpenIpcPath=\RPC Control\SECLOGON``` to sandboxie ini those enabling runas to work
the created process will be kept under the supervision of sandboxie.

I have not yet finished researching if allowing access to the seclogon service can cause other potential issues to use the option with care
