### ISSUE TITLE
Is it possible to isolate the sandbox in the chroot?

### ISSUE THREAD

**Issue by vebmaster** [sandboxie-plus/Sandboxie#689]
Hello.
Is it possible to make a chroot for the sandbox?
So that applications don't have access to all files?

**Comment by DavidXanatos** [comment]
currently ou could use WriteFilePath to achive that but I have abetter solution on my todo

**Comment by isaak654** [comment]
Update: if you have new suggestions, please post on the new issue #890, thanks.
