### ISSUE TITLE
Cant seem to get Internet explorer working in sandbox in v0.7.2

### ISSUE THREAD

**Issue by NyarlathotepZERO** [sandboxie-plus/Sandboxie#691]
I used to have Internet explorer working as a 'forced program' in a specific sandbox, never had a problem. I just updated to 0.7.2 and I can no longer get it to run successfully.

I have tried enabling all the specific 'internet explorer' templates, also the ';' templates.
I tried forcing the folder as well as the .exe its self (also each separately)
I tried forcing the IE shortcut link

The sandbox is just the default sandbox settings (aside from the changes I mentioned above)

Ways I got it to run were;
1. By right clicking on the sandbox>Run>Run from start menu; then browsing to the IE shortcut.
2. Set the link as a 'forced program' Then when I right click the sandbox and hit Run>Run program. Then without even setting a program to run, it is automatically launched. 
3. Using the 'run program' option from right clicking the sandbox, then choosing the iexplore.exe from the default folder.

When updating Sandboxie, I deleted contents off all sandboxes, then removed them all, starting with (what I thought was) a completely fresh sandbox, ini etc.

I'm kind of out of ideas, but in case it helps, below is the ini section for the IE sandbox.

Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=IExplore_Favorites_RecoverFolder
Template=IExplore_ProtectedStorage
Template=IExplore_Credentials
Template=IExplore_Feeds_DirectAccess
Template=IExplore_Cookies_DirectAccess
Template=IExplore_History_DirectAccess
Template=IExplore_Favorites_DirectAccess
Template=IExplore_Force
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ForceProcess=C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessories\Internet Explorer.lnk
BoxNameTitle=n
BlockNetParam=y
DropAdminRights=n
FakeAdminRights=n
ClosePrintSpooler=n
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
StartProgram=C:\Program Files\Internet Explorer\iexplore.exe
CopyLimitKb=81920
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=n

**Comment by DavidXanatos** [comment]
could you please check whats the last version it was working for you?

**Comment by NyarlathotepZERO** [comment]
> could you please check whats the last version it was working for you?

Sandboxie-Plus-x64-v0.6.0

**Comment by DavidXanatos** [comment]
Are you sure its not related to this issue: https://www.wilderssecurity.com/threads/sandboxie-technologies-sbie-open-source.428156/page-36#post-2991938

**Comment by isaak654** [comment]
> 
> 
> Are you sure its not related to this issue: https://www.wilderssecurity.com/threads/sandboxie-technologies-sbie-open-source.428156/page-36#post-2991938

I can reproduce the same issue of @NyarlathotepZERO on Sandboxie 5.49.0, and the workaround reported above (unticking the option "Enable third party extensions") didn't work for me.

In order to reproduce the crash of iexplore.exe, it's enough to put this in the sandbox:
`Template=IExplore_Force`

**Comment by NyarlathotepZERO** [comment]
> Are you sure its not related to this issue: https://www.wilderssecurity.com/threads/sandboxie-technologies-sbie-open-source.428156/page-36#post-2991938

I opened IE (non sandboxed), unchecked the aforementioned box and then reloaded IE as a forced folder. This fixed the issue of IE not loading, perfectly.

Although it is a tad strange that I had it working fine in the earlier version of Sandboxie.
Thanks for the solution David.

**Comment by isaak654** [comment]
Weird, two different workarounds for the same issue...
