### ISSUE TITLE
drag and drop text doesn't work on firefox with Sandboxie-Plus-x64-v0.7.2

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#692]
when try to drag a text and drop it on another field it doesn't work on firefox with Sandboxie-Plus-x64-v0.7.2.

it does work on sandboxie classic

**Comment by DavidXanatos** [comment]
which classic version?

**Comment by diieg707** [comment]
> ich classic version?

it works in classic version

this problem occurs in the latest version Sandboxie-Plus-x64-v0.7.2

**Comment by DavidXanatos** [comment]
That should not be possible plus and classic have the same core components, there is no reason why something should work with one but not the other.

**Comment by diieg707** [comment]
hello, i just downloaded the newest sandboxie plus 0.7.2 and now if a select and drag a text it will drop on another field, on both chrome and firefox

you can close it now, thank you the attention

**Comment by isaak654** [comment]
> 
> 
> hello, i just downloaded the newest sandboxie plus 0.7.2 and now if a select and drag a text it will drop on another field, on both chrome and firefox
> 
> you can close it now, thank you the attention

Maybe you meant the newest 0.7.3, the title says you already tried 0.7.2.
