### ISSUE TITLE
I want something very specific

### ISSUE THREAD

**Issue by litch0** [sandboxie-plus/Sandboxie#694]
Hello good day, I don't have much experience with this repository and I want to know some information.
1. Which resources do this application limit?
    - File system ?
    - Network ?
    - Registry ?
    - User ?
2. Is It possible to build a command line interface for the project?
    - something like `sandboxie --allow-network --bind C:/dev:C:/dev`
3. does It provide a library for other applications to use?
4. Is it possible to build it using clang or gcc? (the mingw one)

**Comment by quangkieu** [comment]
Hey here is quick list that I got from my usage
File system: you could limit access write/read-only/block to actual object, folders, file list (exclude style), apply to name pipes. There is some reqired open pipes. Everything is redirect to its silos if not allow to actual objects
Network: only enable/disable access, use firewall if you want more control
Registry: same as file
User: not sure

**Comment by litch0** [comment]
When I ran the portable version of the application I noticed that it creates isolated systems in boxes, but I did not find exactly in the code where these creation takes place and which library is responsible for such a task. Is there any documentation in this part?
I was testing with the Sanboxie Plus.

Also, Just out of curiosity, do you know any place where I can get MSBuild with the necessary dependencies to build the project, according to [this] (https://stackoverflow.com/questions/42696948/how-can-i-install -the-vs2017-version-of-msbuild-on-a-build-server-without-instal) I need this command
`vs_buildtools.exe --add Microsoft.VisualStudio.Workload.MSBuildTools --quiet` however when I tried it, he wanted to install the IDE together, on top of that I didn't get v141 of the MSVC, nor MFC, ATL but I did install Windows Driver Kit

**Comment by DavidXanatos** [comment]
building should be realyl strat forward plese see the github actions for the auto build for details
