### ISSUE TITLE
Audio and video stutter in Chromium based browsers

### ISSUE THREAD

**Issue by akanderson001** [sandboxie-plus/Sandboxie#695]
I've noticed that when using Chromium based browsers, such as Brave, to watch videos while Sandboxed the audio and the video will both stutter.  This is most prevalent when the video playback is fullscreen.  If playback is done outside of the Sandbox the quality is unaffected.

**Comment by danieldaeschle** [comment]
Same problem.

**Comment by isaak654** [comment]
1) Do you have hardware acceleration enabled in the sandbox? And outside of the sandbox?
2) Do you have one or more third-party security software installed on the system (excluding Windows Defender)?

**Comment by akanderson001** [comment]
I've tried it both with and without acceleration on with no difference when sandboxed.  Outside the sandbox the audio and video playback is unaffected. 

No third party security software installed at all.  This is on a fresh install of Windows 10 Pro.

The version I'm running is v0.72 and to be honest until recently I've only used Firefox for video playback for streaming but since it's not Chromium based there has never been an issue.  I switched to Brave due to its ability to block much more of the unwanted popups compared to Firefox.  I'll install one of the original versions of plus later today to see if it also has the same issue come up.

**Comment by isaak654** [comment]
@akanderson001
 
Unfortunately I can't reproduce it on latest Microsoft Edge and Sandboxie Classic 5.4.9, are you sure it's related to all Chromium browsers? In order to not clutter this discussion, it would be great if you could share your sandboxie.ini configuration file with this service: https://gist.github.com

**Comment by isaak654** [comment]
@akanderson001
 
Unfortunately I can't reproduce it on latest Microsoft Edge and Sandboxie Classic 5.49.0, are you sure it's related to all Chromium browsers? In order to not clutter this discussion, it would be great if you could share your sandboxie.ini configuration file with this service: https://gist.github.com

**Comment by danieldaeschle** [comment]
I was watching disneyplus. Don't know if DRM encoding is too heavy. But there is a difference when watching it without sandboxie.

**Comment by isaak654** [comment]
> 
> 
> I was watching disneyplus. Don't know if DRM encoding is too heavy. But there is a difference when watching it without sandboxie.

If it's a DRM problem, you should have some improvement by allowing the direct access to the entire profile folder for your browser in Sandbox Options > App Templates.

**Comment by isaak654** [comment]
> 
> 
> I was watching disneyplus. Don't know if DRM encoding is too heavy. But there is a difference when watching it without sandboxie.

If it's a DRM issue, you should have some improvement by allowing the direct access to the entire profile folder for your browser in Sandbox Options > App Templates (Plus edition) or in Sandbox Settings > Applications (Classic edition).

If your browser is not on the application list, or you are using a portable one, or you're using a custom profile name, you may need to open the entire profile path manually, like in the first example of this page:
https://davidxanatos.github.io/sandboxie-docs/Content/OpenFilePath.html

If the browser is on the application list, but you have just a different profile name (from Default), another alternative consists to put this line on the GlobalSettings section of your sandboxie.ini: `Ovr.Tmpl.Chrome=%Local AppData%\Google\Chrome\User Data\*`
The template name (Chrome) is defined in the templates.ini file inside the Sandboxie installation folder.

**Comment by danieldaeschle** [comment]
Thanks, that helped indeed! Thanks!

**Comment by isaak654** [comment]
> 
> 
> Thanks, that helped indeed! Thanks! Another trick to increase performance? :D
> I think it's nearly the same as native but just some minor difference.

You just allowed direct access to the unsandboxed profile, that is equal to less protection. Considering that it works for you, maybe you could consider to remove the entire profile access in order to create your custom OpenFilePath rule, for example allowing a single folder at a time:

`OpenFilePath=%Local AppData%\Google\Chrome\User Data\WidevineCDM\*`

I think most streaming sites use this WidevineCDM folder in Chromium browsers, but I would like some user testing about it.

**Comment by danieldaeschle** [comment]
Seems like it works.

**Comment by akanderson001** [comment]
I started going through the different revisions of Sandboxie-Plus in order to see when or if any of them started presenting with a playback issue.  Between each version I completely uninstalled the program to ensure there would be no lingering files that could interfere with this process.  The last one that had no playback issues of any kind when Brave was sandboxed and a video was played in it was v.0.6.0.

When I installed v0.6.5 the playback was initially okay but within 45-60 seconds it began to have the same issue as I initially reported.  I uninstalled it and went back to v0.6.0 and the video could be played for the full duration without issue.  The video being used is https://www.youtube.com/watch?v=1RTiaTGuKnM because why not, it's a kitten.

I'll be posting the sandoxie.ini from the v0.6.0 and v0.7.2 so you can see can see them both an try to determine what may be causing the playback issue.

**Comment by akanderson001** [comment]
Okay both the Sandboxie.ini files have been loaded and saved accordingly with the link you provided.

**Comment by isaak654** [comment]
> 
> 
> Okay both the Sandboxie.ini files have been loaded and saved accordingly with the link you provided.

Ok, share me the URL(s) here and I'll take a look.

**Comment by akanderson001** [comment]
Here they are:  
https://gist.github.com/akanderson001/9db15ca675ea8508d6cf83f05cd5e7bb#file-gistfile1-txt
https://gist.github.com/akanderson001/8beaf399ab46cc58adb94ddc60a2e987#file-gistfile1-txt

**Comment by isaak654** [comment]
@akanderson001 
I suggest to change `BorderColor=#00FFFF,ttl` to `BorderColor=#00FFFF,ttl,6` and add `BoxNameTitle=-` into your sandbox in 0.7.2.

**Comment by akanderson001** [comment]
Both changes were made without any change to the playback.  In a windows mode you can tell the stuttering is present and then it becomes much more prevalent in full screen mode.  If you'd like I can install screen recorder software to show what I'm seeing with Brave before and after sandboxing.

**Comment by isaak654** [comment]
> 
> 
> If you'd like I can install screen recorder software to show what I'm seeing with Brave before and after sandboxing.

No problem.

I'd like to know if you have reproduced the same issue with another Chromium based browser, and if yes, which one. This would help to restrict the problem.

**Comment by DavidXanatos** [comment]
how is it behaving with the latest version 0.7.3?

**Comment by Dyras** [comment]
@DavidXanatos where can I download 0.7.3?

**Comment by DavidXanatos** [comment]
So with 0.7.3 its working fine?

**Comment by Dyras** [comment]
Using Chrome in a sandbox I notice nothing off about the video or audio

**Comment by danieldaeschle** [comment]
i watched a movie recently and there was a little lag sometimes...
