### ISSUE TITLE
"Force into this sandbox" doesn't work the same as right click + run sandboxed?

### ISSUE THREAD

**Issue by Oridjinn1980** [sandboxie-plus/Sandboxie#696]
On Sandboxie-Plus v0.7.2, if I right click a program and run it as sandboxed in the sandbox I want, everything works how I expect it to. However, if I right click on the program in sandboxie's gui after I run it that first time, and select the preset option to "Force into this sandbox", it no longer follows options that I have set for the sandbox. For example, inside the sandbox, I have changed several PATH variables. If I Right-click to run it manually, these path values are followed. If I just double click to run the program while it's set to force run in the sandbox, it uses the previous values that are set for the rest of the system. Is this working as intended?

**Comment by isaak654** [comment]
Here you can read my finding:
https://github.com/sandboxie-plus/Sandboxie/issues/691#issuecomment-803464000

Suggestion: try to remove any `BoxNameTitle=n` from your sandboxes or to replace it with `BoxNameTitle=-` if you really need it.

**Comment by Oridjinn1980** [comment]
> 
> 
> Here you can read my weird finding:
> [#691 (comment)](https://github.com/sandboxie-plus/Sandboxie/issues/691#issuecomment-803464000)

That does work! Pretty weird. Seems like Sandboxie altering window titles causes a variety of issues? I don't remember setting this anywhere, but it seems like "Sandboxie Indicator in title" handles this in the ini? Just set it to not change anything, and seems to be working fine.

**Comment by isaak654** [comment]
I'm glad it worked for you too.
Please don't close this issue until @DavidXanatos will look at this.

**Comment by DavidXanatos** [comment]
seams fixed
