### ISSUE TITLE
saving files with Firefox inside Sandboxie takes 14x as long as without

### ISSUE THREAD

**Issue by darchon7** [sandboxie-plus/Sandboxie#697]
i've tested on the latest 0.7.2 and when i save a file on the same website in Firefox, it takes 14 secs before the Save dialog box appears. without Sandboxie, it takes Firefox 1 sec.

what could be causing this delay?

**Comment by APMichael** [comment]
Unfortunately, the issue is still not fixed. Please take a look at this report: #519

**Comment by darchon7** [comment]
yup this is the same issue as #519. i'm closing this ticket since it's a duplicate of that.
