### ISSUE TITLE
Enhanced privacy protection

### ISSUE THREAD

**Issue by Nacho-Neko** [sandboxie-plus/Sandboxie#699]
Can the directory accessed by the program be redirected?
for example ：C:/user/me  redirect  —> D:/user/me

**Comment by silvestron** [comment]
I'm not sure if it would work, but you can try using symlinks.

**Comment by Nacho-Neko** [comment]
no , it cant ..

**Comment by DavidXanatos** [comment]
this is a often requested feature and on my todo
https://github.com/sandboxie-plus/Sandboxie/issues/398
https://github.com/sandboxie-plus/Sandboxie/issues/194

**Comment by DavidXanatos** [comment]
you can use WriteFilePath to achive that than the sandboxed processes will not see the content of this way configured folders but thay will be able to cerate own sandboxed folders in thair place

**Comment by Nacho-Neko** [comment]
Can the specified process not run in the sandboxie?  such as Chrome .
I run QQ in sandboxie , when i open qq url message, it will open Chrome  in sandboxie.  but I want to be merged into my browser window

**Comment by isaak654** [comment]
Update: if you have new suggestions, please post on the new issue #890, thanks.
