### ISSUE TITLE
Adobe Reader

### ISSUE THREAD

**Issue by BilleBarrett** [sandboxie-plus/Sandboxie#700]
Today I was working with my PDF files and I noticed that they were not getting put in Sandboxie
Is there some thing I need to do to get them back in Sandboxie-plus [latest version]
Thank you
[GlobalSettings]

FileRootPath=C:\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=y
Template=WindowsRasMan
Template=WindowsLive
Template=KeyScrambler
Template=OfficeLicensing
Template=OfficeClickToRun
Template=RoboForm
StartRunAlertDenied=n
NotifyStartRunAccessDenied=y

[DefaultBox]

Enabled=y,BilleB,Administrators
ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=M:\Downloads
BorderColor=#FF00FF,ttl
BoxNameTitle=y
AutoDelete=y
NeverDelete=n
CopyLimitKb=454152
Template=SkipHook
Template=FileCppy
Template=Edge_Profile_DirectAccess
Template=Edge_Sync_DirectAccess
Template=Edge_Preferences_DirectAccess
Template=Edge_Passwords_DirectAccess
Template=Edge_Cookies_DirectAccess
Template=Edge_History_DirectAccess
Template=Edge_Bookmarks_DirectAccess
Template=Edge_Force
Template=WindowsDefender
Template=Firefox_Force
Template=Firefox_Bookmarks_DirectAccess
Template=Firefox_Cookies_DirectAccess
Template=Firefox_Passwords_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=Firefox_Session_DirectAccess
Template=Firefox_Profile_DirectAccess
Template=Chrome_Profile_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=Chrome_Sync_DirectAccess
Template=Chrome_Preferences_DirectAccess
Template=Chrome_Passwords_DirectAccess
Template=Chrome_Cookies_DirectAccess
Template=Chrome_History_DirectAccess
Template=Chrome_Bookmarks_DirectAccess
Template=Chrome_Force
Template=Office_Outlook
Template=AdobeAcrobatReader
Template=AdobeAcrobat
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,neon.exe,maxthon.exe,iron.exe,dragon.exe,chrome.exe,C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
ProcessGroup=<FireFox>,C:\Program Files\Mozilla Firefox\firefox.exe
OpenDefaultClsid=y
UnrestrictedSCM=n
ProtectRpcSs=y
ExposeBoxedSystem=n
OpenProtectedStorage=n
OpenCredentials=n

[UserSettings_10FE026B]

SbieCtrl_UserName=billeb
SbieCtrl_NextUpdateCheck=1610901568
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=200,150,1237,632
SbieCtrl_ActiveView=40021
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_TerminateWarn=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
SbieCtrl_RecoverTarget=M:\Downloads

[UserSettings_4BC00582]

SbieCtrl_UserName=administrator
SbieCtrl_WindowCoords=200,150,1237,632
SbieCtrl_ActiveView=40021
SbieCtrl_RecoverTarget=M:\Downloads
SbieCtrl_SaveRecoverTargets=y

**Comment by isaak654** [comment]
> 
> Today I was working with my PDF files and I noticed that they were not getting put in Sandboxie
> Is there some thing I need to do to get them back in Sandboxie-plus [latest version]
> Thank you
> [GlobalSettings]
> ....

Could you describe the exact steps needed to reproduce your issue?

**Comment by APMichael** [comment]
If you use Adobe Reader and want it and all PDF files to always open with Sandboxie, then Adobe Reader must be set as a "Force Process".

Add the following setting to your [DefaultBox]:
```
ForceProcess=acrord32.exe
```

**Comment by BilleBarrett** [comment]
I have tried to find where I force a program into Sandboxie-plus but I can’t find it

Please tell me how

Thank you

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891

M A O A 
"Make American One Again"


"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by APMichael** [comment]
I only use the Classic version, so I cannot help with the Plus version. Sorry! I hope someone else can give you a hint.

**Comment by BilleBarrett** [comment]
Since I have Sandboxie classic running on another computer I compared the ini file and copied over the info and now it works

I would rather use the ini editor to do this

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891

M A O A 
"Make American One Again"


"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by BilleBarrett** [comment]
Ok I am using the plus version on my  main computer to learn how it works, I put the classic on all my clients computers

Thanks for you concern

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891

M A O A 
"Make American One Again"


"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by DavidXanatos** [comment]
click on a sandbox, than on sandbox options, and you wil find forced process options there:
![grafik](https://user-images.githubusercontent.com/3890945/111909393-6837a180-8a5d-11eb-9aee-a0de48cc1eb0.png)

**Comment by BilleBarrett** [comment]
I must be doing something wrong when I click on Sandboxie-plus and then click on options I get this, not what you showing

Did I do something wrong



 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891

M A O A 
"Make American One Again"


"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by BilleBarrett** [comment]
I think I do not have a default profile, I just created one and I found what you are talking about

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891

M A O A 
"Make American One Again"


"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by BilleBarrett** [comment]
I got it fixed, just didn't  know how  to get to the settings, needed to
right click on the profile in plus window

**Comment by BilleBarrett** [comment]
David I’m beginning to get the hand of the plus version of Sandboxie

The Classic version seems to be very solid, I have recommend a larger client [25] computer to start using Classic Sandboxie in their Domain

Taking a vacation next week [last one 10 years ago]

Bill e. Barrett

 

 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891

M A O A 
"Make American One Again"


"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/

**Comment by BilleBarrett** [comment]
David last night my main computer which I run Sandboxie-plus on did a Microsoft  update 21H1 and after Sandboxie-plus 7.3 stopped Chrome and Microsoft Chrome from see the internet

I’m not sure why, I spend the entire morning working un it until I uninstalled Sandboxie-plus and  the 2 browser started working, also renamed sandboxie.ini if you want to see it

I did see and error that said that Chrome could not find parameters 

This may be a fluke, I installed Sandboxie 5.49.5 and I’m up.
Not going to look at it again until Laster this week

Bill



 

Barrett Computers [Remote Desktop Services]
517 Miltwood Dr,  
Greensboro, NC 27455-2709
(336) 988-0891

M A O A 
"Make American One Again"


"You operating system and Data are only as good as you last backup"
Life is not a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside, thoroughly used up, totally worn out,
and loudly proclaiming... 
 'Wow! What a ride!’
 <https://www.facebook.com/DesktopRemoteServices/> https://www.facebook.com/DesktopRemoteServices/
