### ISSUE TITLE
HELP PLZ 

### ISSUE THREAD

**Issue by Rishi2912** [sandboxie-plus/Sandboxie#702]
![help](https://user-images.githubusercontent.com/81079008/111901140-180c0f80-8a5c-11eb-9fc5-a5f846c86cf5.jpg)
can't seem to get around it :(

**Comment by rawlife56** [comment]
That means the sandbox in which you are opening doesn't have access to that folder. 
Looks like you have blocked that folder in the resource access of that sandbox and it can't simply view the file you are opening in that folder.

**Comment by Rishi2912** [comment]
> That means the sandbox in which you are opening doesn't have access to that folder.
> Looks like you have blocked that folder in the resource access of that sandbox and it can't simply view the file you are opening in that folder.

that's not the case I have already checked another thing I have noticed, the file doesn't start after installing sandboxie, I have tried it 4 times, whenever I install sandboxie, the steam.exe shows an error message that "the path location may be wrong or you do not have permission to access the file" even when I'm trying to run it normally not on sandbox, whenever I uninstall sandboxie the problem seems to go away.

**Comment by sebadamus** [comment]
So, you mean that i.e. your sandoboxie box folder is in c:\username\sandboxiename\ and you have **Steam installed outside the box** and anyway... it wont start if you have Sandboxie installed?

Or, your Steam is installed inside the sandbox folder, so it gives that error when you try run it?

**Comment by DavidXanatos** [comment]
Did you add steam.exe to your forced programs?
