### ISSUE TITLE
Donate link leads to a broken page

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#707]
**Describe the bug**
1. Set Sandboxie-Plus to simple view
2. Click "Support Sandboxie-Plus with a Donation" and you're sent to this page:
https://xanasoft.com/donate/
Which in turn says
"Not Found
It looks like nothing was found at this location. Maybe try a search?"

**Expected behavior**
We should probably be sent to the Patreon page instead

**Screenshots**

![grafik](https://user-images.githubusercontent.com/12563436/112130083-5e7e7d00-8bc8-11eb-94a3-86df09db717d.png)

**Comment by DavidXanatos** [comment]
thanks fixed
