### ISSUE TITLE
renaming a dir hides its contents

### ISSUE THREAD

**Issue by menaquinoneK2** [sandboxie-plus/Sandboxie#71]
1. Create a dir on host eg. `c:\1`
2. Create a file(or dir!) inside the `c:\1` dir, eg. `echo a>a`
3. open explorer inside the sandbox
4. look inside `c:\1`, you see file `a`
5. go back out and rename `1` to `2`
6. go inside `2`, there's no `a` file anymore

now, rename it back from `2` to `1` and contents are back
if you made something new in `2`, then after renaming `2` to `1` their contents are now seen as merged

**Comment by DavidXanatos** [comment]
bugs bugs everyware....

When I try the same thing with the registry editor I cant rename a key that exists on the host also not good

but how to fix that... I mean 
a) create a full copy on rename
b) store some metadata indicating the new name 

I think we should go with B even though its more work

**Comment by DavidXanatos** [comment]
This fix is ready and will be added in one of the upcoming builds, may be not the next as that might be only a minor release with some fixes only quickly followed by a large experimental release
this feature will need you to enable it with UseFileDeleteV2=y

Also I haven't yet sorted out the handling of snapshots not sure if that will be done till the release.

With this change sandboxie will no longer create dummy deletion mark files/folders, instead it will maintain a data file of deleted and also of renamed paths.

Also currently renaming a file always creates a boxed copy, in a later stage that could be improved to use the same relocation mechanism as will be now used for folders.
