### ISSUE TITLE
Can't recover files to network drives. 

### ISSUE THREAD

**Issue by Tomcat86878** [sandboxie-plus/Sandboxie#711]
Hi, 

every time I try to save and recover files to a network share, the files is not recovered to the network share itself, but to a destination beginning with \device\mup\NAME_OF_SHARE\FOLDER. The file then can be found under C:\device\mup\NAME_OF_SHARE\FOLDER but not on the share itself.

Please also see the screenshot attached:
![grafik](https://user-images.githubusercontent.com/76661281/112540603-aa8d1580-8db2-11eb-877a-e816fab42c01.png)

Is this a misconfiguration on my side?

Best,
Tom

**Comment by DavidXanatos** [comment]
What have you configured as the recovery fodler?

**Comment by Tomcat86878** [comment]
Hi David,

the network drive is configured as a recovery folder (drive letter as well as network path). 

![grafik](https://user-images.githubusercontent.com/76661281/113573721-f9407800-961a-11eb-9e42-1bdb247b4b62.png)

Best regards,
Tom

**Comment by DavidXanatos** [comment]
I see, the intended behavioure in such cases is to ask for a folder to recover to, 
I will fix that.
would you actually intent the file to be recovered to the network share without asking?
That would be problematic to implement, as qt has no direct awareness of windows network shares and your actual user may not be authenticated with that share.

**Comment by Tomcat86878** [comment]
Hi David,

the recovery function is asking for a folder to recover to. 

![grafik](https://user-images.githubusercontent.com/76661281/113579812-1d08bb80-9625-11eb-8bae-5adc6587bf0f.png)

This behaviour is totally fine, but it would be great if the recovery path would be set to the actual network share. So it is okay, that it asks for the recovery location, but the prefilled recovery location does not represent the actual network share, but a location on the C: drive. 

Would it be possible, that the prefilled recovery location is set to the network drive, so that I just could click on recover and the file would be saved to the location I selected in the sandbox application (in this case Firefox)?

I also attached a screencast of the current behaviour, probably this helps.


https://user-images.githubusercontent.com/76661281/113582156-542c9c00-9628-11eb-8cf0-67736035958a.mp4

As you can see, I select the network drive as location to save to, Sandboxie then opens the recovery dialog, which is prefilled with \device\mup\NAME_OF_SHARE\PATH_TO_FILE. As a result, the file is saved to C: instead of the network share.  

Best regards,
Tom
