### ISSUE TITLE
Impossible to open firefox after an update to 5.49 64bits

### ISSUE THREAD

**Issue by gab12** [sandboxie-plus/Sandboxie#714]
**Describe the bug**
I have sandboxie 5.48.5 64bits. It worked with firefox.
I updated Sandboxie to the 5.49 64bit, after impossible to open My firefox 87.0 64bit.

**To Reproduce**
1. open firefox

**Result**
Message : "The application haven't started correctly (0xc0000005).

**Screenshots**
![image](https://user-images.githubusercontent.com/6320898/112556668-f8ae1300-8dca-11eb-9d11-5f24f6647e1d.png)

**System and installed software (please provide the following information):**
 - Windows 10
 - Sandboxie classic 5.49 64bit

**Comment by isaak654** [comment]
Try [this](https://github.com/sandboxie-plus/Sandboxie/issues/715#issuecomment-807939585) or [this](https://github.com/sandboxie-plus/Sandboxie/issues/651#issuecomment-798783873) (only if you have Bitdefender or another security software different from Windows Defender).

**Comment by isaak654** [comment]
Try [this](https://github.com/sandboxie-plus/Sandboxie/issues/715#issuecomment-807939585) or [this](https://github.com/sandboxie-plus/Sandboxie/issues/651#issuecomment-798783873) (only if you have Bitdefender).

**Comment by DavidXanatos** [comment]
It is strange that this error appears from 5.48.5 to 5.49.0 ...
did deleting these folders help?

**Comment by sebadamus** [comment]
> 
> 
> It is strange that this error appears from 5.48.5 to 5.49.0 ...
> did deleting these folders help?

Deleting firefox folders changed my error message from the one I post here:
https://github.com/sandboxie-plus/Sandboxie/issues/715#issue-841527551
to: _"Message : "The application haven't started correctly (0xc0000005)."_ as @gab12 shows in this post.

**Comment by gab12** [comment]
Hello,

I confirm. I have Bitdefender Tota Security.
Bitdefender+firefox+sandboxie 5.48.5 worked but with Sandboxie 5.49.0. I have an error (I retested).
I added the new rude ( [#651 ](https://github.com/sandboxie-plus/Sandboxie/issues/651#issuecomment-798783873) and now all works. Thank you very much @isaak654

**Comment by DavidXanatos** [comment]
So the problem is recolved than I'll close this issue
