### ISSUE TITLE
Sandboxie Start, Could not invoke program: System Error Code (14001)

### ISSUE THREAD

**Issue by sebadamus** [sandboxie-plus/Sandboxie#715]
**Describe the bug**
After installing v0.7.2 I get the "Could not invoke program" when trying to open Firefox.

**To Reproduce**
1. Right click on DefaultBox inside SandboxiePlus Panel, Run, Run Web Browser
2. Also tried to first open a cmd (normal) and a cmd (admin) sandboxed, and executing from command line with the exe direcly.
3. I get the error popup Sandboxie Start window, saying "could not invoque program..." some more text (in spanish like my windows) ...System Error Code... and finally the error (14001) .  

**Expected behavior**
That Firefox 87.0 open normally as before with v0.7.2

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1787753/112567479-a87d8380-8dbf-11eb-91c1-ab6f1f089fa9.png)

**System and installed software (please provide the following information):**
 - Windows 10 20H2 19042.868
 - Sandboxie Plus 0.7.2
 - Sandboxie Plus 0.7.1
 - Bitdefender Free version (tested with the protection turned off, too)

**Additional context**
I had two sandboxies DefaultBox and BoxDev.  The first comes from log ago, like when sandboxie classic version and worked fine with Sandboxie Plus 0.7.1
Then with 0.7.1 I created a the new sandboxie called BoxDev (the error appear here too)
**THIS MIGHT BE OF INTEREST**
**Then with 0.7.2 I created a new sandboxie a Default, a Legacy and a Hardened one... each one opens fine Firefox!!! so the problem might be with 0.7.2 that "wont understand" something of 0.7.1 sandboxies version**

**Trace Log when the error appears**

|Process|                               |Type|     |Status|    |Value|                                                                                                                                                
Start.exe (7632, 4088) - 22:42:15.782   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:15.782   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:15.782   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:15.782   Ipc        open        \BaseNamedObjects\[CoreUI]-PID(6904)-TID(7020) a9559e31-4868-452b-9346-94c86cc0202c                                                                    
Start.exe (7632, 4088) - 22:42:15.782   Ipc        Open        \BaseNamedObjects\[CoreUI]-PID(7632)-TID(4088) 70dc8610-ac5d-45f9-9306-96796aba4509                                                                    
Start.exe (7632, 4088) - 22:42:15.721   WinClass               UserAdapterWindowClass                                                                                                                                 
Start.exe (7632, 4088) - 22:42:15.721   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:15.721   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:15.721   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:15.721   Ipc        open        \BaseNamedObjects\CoreMessagingRegistrar                                                                                                               
Start.exe (7632, 4088) - 22:42:12.394   WinClass   closed      Progman                                                                                                                                                
Start.exe (7632, 4088) - 22:42:12.394   WinClass               $:explorer.exe                                                                                                                                         
Start.exe (7632, 4088) - 22:42:12.394   WinClass               Progman                                                                                                                                                
Start.exe (7632, 4088) - 22:42:12.394   WinClass   open (2)    Shell_TrayWnd                                                                                                                                          
Start.exe (7632, 4088) - 22:42:09.977   Ipc        Open        \KnownDlls\WS2_32.dll                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.977   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:09.977   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:09.977   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:09.977   Ipc        open        \BaseNamedObjects\msctf.serverDefault1                                                                                                                 
Start.exe (7632, 4088) - 22:42:09.874   Ipc        open        \Sessions\1\BaseNamedObjects\MSCTF.CtfMonitorInstMutexDefault1                                                                                         
Start.exe (7632, 4088) - 22:42:09.874   Ipc        open        \Sessions\1\BaseNamedObjects\CicLoadWinStaWinSta0                                                                                                      
Start.exe (7632, 4088) - 22:42:09.874   Ipc        open        \Sessions\1\BaseNamedObjects\CTF.AsmListCache.FMPDefault1                                                                                              
Start.exe (7632, 4088) - 22:42:09.874   Ipc        open        \Sessions\1\BaseNamedObjects\MSCTF.Asm.MutexDefault1                                                                                                   
Start.exe (7632, 4088) - 22:42:09.771   Ipc        Open        \KnownDlls\MSCTF.dll                                                                                                                                   
Start.exe (7632, 4088) - 22:42:09.741   Debug      trace       CreateProcess: E:\DefaultBox\drive\C\Program Files\Mozilla Firefox\firefox.exe ("C:\Program Files\Mozilla Firefox\firefox.exe"); err=14001             
Start.exe (7632, 4088) - 22:42:09.730   Debug      trace       CreateProcess: E:\DefaultBox\drive\C\Program Files\Mozilla Firefox\firefox.exe ("C:\Program Files\Mozilla Firefox\firefox.exe" ); err=14001            
Start.exe (7632, 7720) - 22:42:09.719   ComClass               {C2F03A33-21F5-47FA-B4BB-156362A2F239} Immersive Shell                                                                                                 
Start.exe (7632, 4088) - 22:42:09.719   Ipc                    \Sessions\1\BaseNamedObjects\C:*Users*admin*AppData*Local*Microsoft*Windows*Caches*cversions.3.ro                                                      
Start.exe (7632, 4088) - 22:42:09.719   Ipc                    \Sessions\1\BaseNamedObjects\C:*Users*admin*AppData*Local*Microsoft*Windows*Caches*{3DA71D5A-20CC-432F-A115-DFE92379E91F}.3.ver0x000000000000000f.db   
Start.exe (7632, 4088) - 22:42:09.719   Ipc                    \Sessions\1\BaseNamedObjects\C:*Users*admin*AppData*Local*Microsoft*Windows*Caches*cversions.3.ro                                                      
Start.exe (7632, 4088) - 22:42:09.659   ComClass               Windows.Foundation.PropertyValue                                                                                                                       
Start.exe (7632, 7552) - 22:42:09.659   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 7552) - 22:42:09.659   Pipe                   \Device\HarddiskVolume8                                                                                                                                
Start.exe (7632, 7720) - 22:42:09.628   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0h                                                                                              
Start.exe (7632, 7720) - 22:42:09.628   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0                                                                                               
Start.exe (7632, 7720) - 22:42:09.628   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03                                                                                                  
Start.exe (7632, 7720) - 22:42:09.598   ComClass               Windows.Internal.StateRepository.FileTypeAssociation                                                                                                   
Start.exe (7632, 4088) - 22:42:09.598   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0h                                                                                              
Start.exe (7632, 4088) - 22:42:09.598   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0                                                                                               
Start.exe (7632, 4088) - 22:42:09.598   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03                                                                                                  
Start.exe (7632, 4088) - 22:42:09.598   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0h                                                                                              
Start.exe (7632, 4088) - 22:42:09.598   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0                                                                                               
Start.exe (7632, 4088) - 22:42:09.598   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03                                                                                                  
Start.exe (7632, 4088) - 22:42:09.598   Ipc                    \RPC Control\OLEEA2948E9D04CBA75390963EC2080                                                                                                           
Start.exe (7632, 4088) - 22:42:09.587   Ipc                    \RPC Control\epmapper                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.587   Ipc                    \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch                                                                                 
Start.exe (7632, 4088) - 22:42:09.587   Ipc                    \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs                                                                                      
Start.exe (7632, 4088) - 22:42:09.587   Ipc                    \RPC Control\epmapper                                                                                                                                  
Start.exe (7632, 7552) - 22:42:09.576   Pipe       (19)        \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume8                                                                                                                                
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\00000046                                                                                                                                       
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume3                                                                                                                                
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume6                                                                                                                                
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume4                                                                                                                                
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume11                                                                                                                               
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume9                                                                                                                                
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume5                                                                                                                                
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4940) - 22:42:09.576   Pipe                   \Device\HarddiskVolume1                                                                                                                                
Start.exe (7632, 7552) - 22:42:09.576   Pipe                   \Device\DeviceApi                                                                                                                                      
Start.exe (7632, 7552) - 22:42:09.576   Ipc        Open        \KnownDlls\cfgmgr32.dll                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.576   Pipe                   \Device\MountPointManager                                                                                                                              
Start.exe (7632, 4088) - 22:42:09.576   Pipe                   \Device\HarddiskVolume8                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.545   Ipc        (3)         \Sessions\1\BaseNamedObjects\windows_shell_global_counters                                                                                             
Start.exe (7632, 4088) - 22:42:09.545   Ipc                    \BaseNamedObjects\windows_shell_global_counters                                                                                                        
Start.exe (7632, 4088) - 22:42:09.545   Ipc                    \Sessions\1\BaseNamedObjects\windows_shell_global_counters                                                                                             
Start.exe (7632, 4088) - 22:42:09.545   Ipc                    \Sessions\1\BaseNamedObjects\C:*Users*admin*AppData*Local*Microsoft*Windows*Caches*{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x0000000000000003.db   
Start.exe (7632, 4088) - 22:42:09.545   Ipc                    \Sessions\1\BaseNamedObjects\C:*Users*admin*AppData*Local*Microsoft*Windows*Caches*cversions.1.ro                                                      
Start.exe (7632, 4088) - 22:42:09.534   Ipc        (49)        \Sessions\1\BaseNamedObjects\windows_shell_global_counters                                                                                             
Start.exe (7632, 4088) - 22:42:09.534   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:09.534   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:09.534   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000003.db                 
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000003.db                            
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000003.db                 
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000003.db                            
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro                                                                    
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro                                                                               
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000003.db                 
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000003.db                            
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000003.db                 
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000003.db                            
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro                                                                    
Start.exe (7632, 4088) - 22:42:09.502   Ipc                    \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro                                                                               
Start.exe (7632, 4088) - 22:42:09.502   Ipc        open        \RPC Control\lsapolicylookup                                                                                                                           
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro                                                                    
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro                                                                               
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\__ComCatalogCache__                                                                                                       
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \BaseNamedObjects\__ComCatalogCache__                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.491   Ipc        open        \KernelObjects\MaximumCommitCondition                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.491   Ipc        Open        \KnownDlls\clbcatq.dll                                                                                                                                 
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\__ComCatalogCache__                                                                                                       
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \BaseNamedObjects\__ComCatalogCache__                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:09.491   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:09.378   Ipc        (62)        \Sessions\1\BaseNamedObjects\windows_shell_global_counters                                                                                             
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0h                                                                                              
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03_p0                                                                                               
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:120:WilError_03                                                                                                  
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:09.378   Pipe                   \Device\CNG                                                                                                                                            
Start.exe (7632, 4088) - 22:42:09.378   Ipc        Open        \KnownDlls\bcryptPrimitives.dll                                                                                                                        
Start.exe (7632, 4088) - 22:42:09.378   File       closed      \Device\HarddiskVolume8\WINDOWS\system32\apphelp.dll                                                                                                   
Start.exe (7632, 4088) - 22:42:09.378   File       closed      \Device\HarddiskVolume8\Windows\system32\apphelp.dll                                                                                                   
Start.exe (7632, 4088) - 22:42:09.378   File       closed      \Device\HarddiskVolume8\WINDOWS\SYSTEM32\apphelp.dll                                                                                                   
Start.exe (7632, 4088) - 22:42:09.378   File       closed      \Device\HarddiskVolume8\WINDOWS\System32\apphelp.dll                                                                                                   
Start.exe (7632, 4088) - 22:42:09.378   Ipc        (2)         \Sessions\1\BaseNamedObjects\windows_shell_global_counters                                                                                             
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0h                                                                                            
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02_p0                                                                                             
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SM0:7632:304:WilStaging_02                                                                                                
Start.exe (7632, 4088) - 22:42:09.378   Ipc        open        \Sessions\1\Windows\Theme2444083954                                                                                                                    
Start.exe (7632, 4088) - 22:42:09.378   Ipc        open        \Windows\Theme3606061404                                                                                                                               
Start.exe (7632, 4088) - 22:42:09.378   Ipc        open        \Sessions\1\Windows\ThemeSection                                                                                                                       
Start.exe (7632, 8244) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch                                                                                 
Start.exe (7632, 4088) - 22:42:09.378   Ipc        open        \ThemeApiPort                                                                                                                                          
Start.exe (7632, 4088) - 22:42:09.378   Ipc                    \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs                                                                                      
Start.exe (7632, 4088) - 22:42:09.316   Ipc                    \RPC Control\epmapper                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\IMM32.dll                                                                                                                                   
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\OLEAUT32.dll                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\SHCORE.dll                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\COMDLG32.dll                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\sechost.dll                                                                                                                                 
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\advapi32.dll                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\combase.dll                                                                                                                                 
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\rpcrt4.dll                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\ole32.dll                                                                                                                                   
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\MSVCRT.dll                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\SHLWAPI.dll                                                                                                                                 
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\SHELL32.dll                                                                                                                                 
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\ucrtbase.dll                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\msvcp_win.dll                                                                                                                               
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\gdi32full.dll                                                                                                                               
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\gdi32.dll                                                                                                                                   
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\win32u.dll                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\user32.dll                                                                                                                                  
Start.exe (7632, 4088) - 22:42:09.306   Ipc                    \Sessions\1\BaseNamedObjects\SboxSession                                                                                                               
Start.exe (7632, 4088) - 22:42:09.306   Ipc                    \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_7632                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \RPC Control\SbieSvcPort                                                                                                                               
Start.exe (7632, 4088) - 22:42:09.306   Drive                  \Device\HarddiskVolume4                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Drive                  \Device\HarddiskVolume11                                                                                                                               
Start.exe (7632, 4088) - 22:42:09.306   Drive                  \Device\HarddiskVolume1                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Drive                  \Device\HarddiskVolume3                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Drive                  \Device\CdRom0                                                                                                                                         
Start.exe (7632, 4088) - 22:42:09.306   Drive                  \Device\HarddiskVolume8                                                                                                                                
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\PSAPI.DLL                                                                                                                                   
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \Sessions\1\Windows\ApiPort                                                                                                                            
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \Sessions\1\Windows\SharedSection                                                                                                                      
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\kernelbase.dll                                                                                                                              
Start.exe (7632, 4088) - 22:42:09.306   Ipc        Open        \KnownDlls\kernel32.dll

**Comment by sebadamus** [comment]
_OK, my bad I think... I delete every folder called "firefox"and "mozilla" inside each sandboxie box folder, opened again firefox a no error appeared.

**These were the folders that prevent Firefox to start:**
\sandbox\user\current\AppData\Roaming\Mozilla
\sandbox\user\all\Mozilla
\sandbox\drive\C\Users\admin\AppData\LocalLow\Mozilla
\sandbox\drive\C\Users\admin\AppData\Local\Temp\mozilla-temp-files
\sandbox\drive\C\Users\admin\AppData\Local\Mozilla
\sandbox\drive\C\Users\admin\AppData\Roaming

Deleting these files solve the problem, maybe its only me but if it happens something similar with other program, hope it helps!
(solved)

**Comment by sebadamus** [comment]
Thanks @isaak654! adding _this_ to [GlobalSettings] section in c:\windows\sandboxie.ini solved the problem completely.
I change **WriteFilePath** because I have the Bitdefender Free version.

Also, I did not need _"ClosedFilePath=*BitDefender*atcuf*.dll_" line added, it works just fine adding only:
```
WriteFilePath=C:\Program Files\Bitdefender Antivirus Free\*
```
Any extra explanation why? if not will see this way how it works from now on.

PS: I have atcuf64.dll and atcuf32.dll repeated in some bitdefender directories inside C:\Program Files\Bitdefender Antivirus Free.

**Comment by isaak654** [comment]
> 
> 
> Thanks @isaak654! adding _this_ to [GlobalSettings] section in c:\windows\sandboxie.ini solved the problem completely.
> I change **WriteFilePath** because I have the Bitdefender Free version.
> 
> Also, I did **not need** `ClosedFilePath=*BitDefender*atcuf*.dll` line added, it works just fine adding only:
> 
> ```
> WriteFilePath=C:\Program Files\Bitdefender Antivirus Free\*
> ```
> 
> Any extra explanation why? if not will see this way how it works from now on.
> 
> PS: I have atcuf64.dll and atcuf32.dll repeated in some bitdefender directories inside C:\Program Files\Bitdefender Antivirus Free.

Something is changed in Plus 0.7.2 & Classic 5.49.0. @DavidXanatos is trying to investigate it.

I discovered that fix for pure case because in one log I noticed an entry related to Bitdefender and I knew that workaround from the old releases (when Sandboxie was owned by Invincea).

**Comment by DavidXanatos** [comment]
But is it confirmed that the changes in in Plus 0.7.2 & Classic 5.49.0 cause issues only in combination with Bitdefender?

**Comment by isaak654** [comment]
> 
> 
> But is it confirmed that the changes in in Plus 0.7.2 & Classic 5.49.0 cause issues only in combination with Bitdefender?

Till now, three users confirmed it in #715, #661, #651, I think it's enough.

**Comment by DavidXanatos** [comment]
So the issue is Bitdefender related, but does it go away also when deleting the sandbox? or only when adding these rules?

**Comment by DavidXanatos** [comment]
can you provide me a guide how to reproduce this error starting with a default empty sandbox

**Comment by sebadamus** [comment]
OK, I removed:
```
ClosedFilePath=*BitDefender*atcuf*.dll
WriteFilePath=C:\Program Files\Bitdefender Antivirus Free\*
```
from the sandboxie.ini file and no problems so far... I installed 0.74 yesterday, dont know if it is solved because of this.

My Bitdefender is the free one, version 1.0.21.234

Will report back here if the first post error happens again.

Thanks
