### ISSUE TITLE
Can you block a program from accessing the entire registry?

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#717]
**Is your feature request related to a problem? Please describe.**
**Resource Access=>Registry Access** expects you to specify whole keys.

**Describe the solution you'd like**
A way to specify the entire registry and not specific keys, and pretend it's accessible nonetheless.

**Describe alternatives you've considered**
I tried the "key" **\\REGISTRY\\** and it seemed to work, but it got the relevant program to crash due to no access.
Could there be a more elegant way? Maybe to pretend the registry is blank rather than no access.
Alternatively, have an allowed list approach - only let the program access a specific key.

**Comment by Dyras** [comment]
Out of curiosity, does it work if you input a "*"?

**Comment by lwcorp** [comment]
"*" works just as well, thanks. But just as well, it makes the relevant program crash due to no access.

**Comment by Dyras** [comment]
Which program is it?

**Comment by lwcorp** [comment]
My test happened to have been [on Pop Peeper](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.6.7).

**Comment by DavidXanatos** [comment]
You can not block the entier registry access, as somm access is needed but you may have success with using this option:
https://davidxanatos.github.io/sandboxie-docs/Content/WriteKeyPath.html
it hides the real registry and allows writing to the boxed copy unlike close

**Comment by lwcorp** [comment]
> You can not block the entier registry access, as somm access is needed but you may have success with using this option:
> https://davidxanatos.github.io/sandboxie-docs/Content/WriteKeyPath.html
> it hides the real registry and allows writing to the boxed copy unlike close

True, but it only hides specific entries.

**Comment by DavidXanatos** [comment]
well you can hide a root path that would hide all below that path

**Comment by lwcorp** [comment]
What's the difference between hiding these 5 and everything?

![image](https://user-images.githubusercontent.com/1773306/121080828-9d45cb80-c7e4-11eb-96c6-b808dbba692f.png)
