### ISSUE TITLE
Move "sandboxie-core" in this organization

### ISSUE THREAD

**Issue by Neustradamus** [sandboxie-plus/Sandboxie#72]
Can you move https://github.com/DavidXanatos/sandboxie-core here?

Time to add commits from https://github.com/DavidXanatos/sandboxie-core in this repository in the same time.

**Comment by DavidXanatos** [comment]
sandboxie-core was a way for me to commit changes to the other fork, as this seams to be dead there is no point in maintaining the core repo
all my changes to the classical sandboxie can be find here anyways: https://github.com/sandboxie-plus/Sandboxie/tree/master/Sandboxie

**Comment by Neustradamus** [comment]
The goal is to have the real fork of https://github.com/sandboxie/sandboxie in this organization:
- https://github.com/sandboxie-plus

**Comment by DavidXanatos** [comment]
And what would be the point of having a fork of a apparently dead project?

**Comment by Neustradamus** [comment]
@DavidXanatos: Can you move https://github.com/DavidXanatos/sandboxie-core into this organization?

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository
