### ISSUE TITLE
Internet Restrictions seems not to work right (MANPROXY)

### ISSUE THREAD

**Issue by sebadamus** [sandboxie-plus/Sandboxie#724]
**Describe the bug**
I want a box with blocked internet access for every program except some.
It seems to work with Firefox, Chrome... but i.e. I have an extension that uses an additional .exe file to get video streams and save to disk.  Adding this .exe to the exclusions manually or by accepting it from the popup that asks  to allow it and remember, wont work, also wont work by clicking right clicking Preset and Allow Internet Access.
Seems to give also some "MANPROXY" errors in SBie Messages might have something to do with https://github.com/sandboxie-plus/Sandboxie/issues/643#issue-823199043

**To Reproduce**
1. First I block internet access from sandbox preset (screenshot below)
2. Go to sandbox config, Program Groups and add to "InternetAccess" the program I want to allow "net.downloadhelper.coapp-win-64.exe" (see screenshot)
3. There in Internet Restrictions I enable Block Internet and Promp User (this one so it will ask me to allow internet)
4. Each time I open manually net.downloadhelper.coapp-win-64.exe it asks for internet access even if click on remember.  Even if it is already added manually.  If I open Firefox, the it test the extension and again asks for allow each time, but seems not to work.

**Expected behavior**
Adding the .exe or .exe programs involved in the allowed/exeptions lists should let them go internet.

**Screenshots**
1)
![imagen](https://user-images.githubusercontent.com/1787753/112733749-8f401880-8f20-11eb-8464-62f690830b83.png)
2)
![imagen](https://user-images.githubusercontent.com/1787753/112733692-35d7e980-8f20-11eb-858f-9f7d59a0749b.png)
3)
![imagen](https://user-images.githubusercontent.com/1787753/112733767-aa128d00-8f20-11eb-8c6f-fb53720f3e74.png)

**System and installed software (please provide the following information):**
    Windows 10 20H2 19042.868
    Sandboxie Plus 0.7.2
    Bitdefender Free version (tested with the protection turned off, too)

**Comment by DavidXanatos** [comment]
not sure about the manpoxy errors,
the issue with net.downloadhelper.coapp-win-64.exe is that its located inside the sandbox
and you can not white list things located inside.

**Comment by sebadamus** [comment]
Yes, you are absolutely right, sorry.
