### ISSUE TITLE
PDF/Print is displayed as Print in Sandboxie-Plus

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#727]
**Describe the bug**
On Sandboxie-Classic, PDF/Print is displayed as PDF/Print.
On Sandboxie-Plus, PDF/Print is displayed as Print.
This is confusing, as it implies it has nothing to do with PDF-programs.

I'm planning on adding templates for PDF-programs, and putting them under "Print" would be really confusing.

**To Reproduce**
1. Open the settings of a sandbox in Sandboxie-Plus
2. Click on "App templates"
3. Click "All Categories" next to "Filter Categories"
4. Notice how it says "Print"

**Expected behavior**
I think the names should be consistent.

**Screenshots**
What it currently looks like:
![grafik](https://user-images.githubusercontent.com/12563436/112747355-34a4cc00-8fb5-11eb-9527-8bc38887f417.png)
What it should look like:
![grafik](https://user-images.githubusercontent.com/12563436/112747361-38d0e980-8fb5-11eb-88e1-675bfa6cb306.png)

**Comment by DavidXanatos** [comment]
fixed in next build
