### ISSUE TITLE
Rename Sandboxie to sandboxie

### ISSUE THREAD

**Issue by Neustradamus** [sandboxie-plus/Sandboxie#73]
Can you rename https://github.com/sandboxie-plus/Sandboxie to sandboxie?

**Comment by DavidXanatos** [comment]
why?

**Comment by Neustradamus** [comment]
It will be better and after the change, there is no break.

**Comment by AndhikaWB** [comment]
What is exactly better? Moreover, https://github.com/sandboxie/sandboxie already exists.

**Comment by Neustradamus** [comment]
@DavidXanatos: Have you done the change before closing?

Can you rename https://github.com/sandboxie-plus/Sandboxie to sandboxie?

You must click on gear, and rename Sandboxie to sandboxie :)

Thanks in advance.

**Comment by DavidXanatos** [comment]
why do you want the S to not be capital? github accepts booth s and S as the same

**Comment by Neustradamus** [comment]
@DavidXanatos: Can you change the "S" to "s"?

The capital letter is not needed and no lost, GitHub creates redirections.
