### ISSUE TITLE
[Feature request] Prevent Sandboxie Classic & Plus upgrades before a certain release

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#738]
**Is your feature request related to a problem? Please describe.**
It's related to issue #686 and #713

**Describe the solution you'd like**
In order to prevent those issues in future, I would suggest to update both Sandboxie Classic & Plus installers in order to prevent the upgrade process for all existing sbie (classic&plus) versions prior to [Release v0.5.5 / 5.46.4](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.5.5), giving only the chance to uninstall the previous releases and keeping the option to maintain or remove sandboxie.ini.

**Comment by DavidXanatos** [comment]
The next installers when they detect an opposite version will prompt to remove it first.

**Comment by isaak654** [comment]
Ok, just wait before closing this. I need a day to confirm the fix.
