### ISSUE TITLE
Is there a way to load a single system driver?

### ISSUE THREAD

**Issue by ShyamBhagat2004** [sandboxie-plus/Sandboxie#748]
[The Block Drivers Page](https://sandboxie-plus.com/sandboxie/blockdrivers/) on the website states that this feature is deprecated.

The error I am receiving is :
`GenshinImpact.exe (10348): SBIE2103 Denied attempt to load system driver 'mhyprot2 [DefaultBox]'`

I am quite sure this is an annoying, kernel-level anti-cheat. Let me know if there is a way to load this.

**Comment by DavidXanatos** [comment]
For security reasons loading drivers is a very bad idea
