### ISSUE TITLE
在sandboxie玩守望先锋(Overwatch)会崩溃

### ISSUE THREAD

**Issue by AsimovGod** [sandboxie-plus/Sandboxie#749]
https://www.battlenet.com.cn/support/zh/article/48252
弹出改错误，有办法修复或者屏蔽吗

**Comment by DavidXanatos** [comment]
please write in englisch

**Comment by God-Asimov** [comment]
Playing Overwatch in Sandboxie will crash. The crash information is as follows：
https://www.battlenet.com.cn/support/zh/article/48252

**Comment by God-Asimov** [comment]
Thanks, this problem has been resolved.

**Comment by m986883511** [comment]
我也是，完了会守望就会奔溃
