### ISSUE TITLE
Harmonization and add missing files in releases section

### ISSUE THREAD

**Issue by Neustradamus** [sandboxie-plus/Sandboxie#75]
Currently there are:

5.41.2 / Assets 6
- SandboxieInstall32-v5.41.2.exe / 2.34 MB
- SandboxieInstall64-v5.41.2.exe / 2.92 MB
- SbiePlus32-v0.2.2.zip / 12.2 MB
- SbiePlus64-v0.2.2.zip / 15 MB
- Source code (zip)
- Source code (tar.gz)

5.41.1 / Assets 6
- SandboxieInstall32-v5.41.1.exe / 2.34 MB
- SandboxieInstall64-v5.41.1.exe / 2.92 MB
- SbiePlus32-v0.2.1.zip / 12.2 MB
- SbiePlus64-v0.2.1.zip / 15 MB
- Source code (zip)
- Source code (tar.gz)

5.41.0 / Assets 7
- SandboxieInstall-v5.41.0.exe / 5.33 MB
- SandboxieInstall32-v5.41.0.exe / 2.23 MB
- SandboxieInstall64-v5.41.0.exe / 2.79 MB
- SbiePlus32.zip / 12.1 MB
- SbiePlus64.zip / 14.9 MB
- Source code (zip)
- Source code (tar.gz)

5.40.2 / Assets 6
- Sandboxie-Plus-x64.zip / 10.4 MB
- Sandboxie-Plus-x86.zip / 8.43 MB
- SandboxieInstall32-v5.40.2.exe / 2.23 MB
- SandboxieInstall64-v5.40.2.exe / 2.78 MB
- Source code (zip)
- Source code (tar.gz)

5.40.1 / Assets 4
- SandboxieInstall32-v5.40.1.exe / 2.24 MB
- SandboxieInstall64-v5.40.1.exe / 2.79 MB
- Source code (zip)
- Source code (tar.gz)

5.40.0 / Assets 6
- SandboxieInstall32.exe / 2.23 MB
- SandboxieInstall32_xp.exe / 2.23 MB
- SandboxieInstall64.exe / 2.79 MB
- xp_src_patch.zip / 44.3 KB
- Source code (zip)
- Source code (tar.gz)

Some releases have not all files and the name are not good:

For 5.40.0, we must have:
- SandboxieInstall-v5.40.0.exe
- SandboxieInstall32-v5.40.0.exe
- SandboxieInstall32_xp-v5.40.0.exe
- SandboxieInstall64-v5.40.0.exe
- xp_src_patch-v5.40.0.zip
- Source code (zip)
- Source code (tar.gz)

For 5.40.1, we must have:
- SandboxieInstall-v5.40.1.exe
- SandboxieInstall32-v5.40.1.exe
- SandboxieInstall32_xp-v5.40.1.exe (if you want)
- SandboxieInstall64-v5.40.1.exe
- Source code (zip)
- Source code (tar.gz)

For 5.40.2, we must have:
- SandboxieInstall-v5.40.2.exe
- SandboxieInstall32-v5.40.2.exe
- SandboxieInstall32_xp-v5.40.2.exe (if you want)
- SandboxieInstall64-v5.40.2.exe
- Sandboxie-Plus-x64-v5.40.2.zip or SbiePlus64-v5.40.2.zip
- Sandboxie-Plus-x86-v5.40.2.zip or SbiePlus32-v5.40.2.zip
- Source code (zip)
- Source code (tar.gz)

For 5.41.0, we must have:
- SandboxieInstall-v5.41.0.exe
- SandboxieInstall32-v5.41.0.exe
- SandboxieInstall32_xp-v5.41.0.exe (if you want)
- SandboxieInstall64-v5.41.0.exe
- Sandboxie-Plus-x64-v5.41.0.zip or SbiePlus64-v5.41.0.zip
- Sandboxie-Plus-x86-v5.41.0.zip or SbiePlus32-v5.41.0.zip
- Source code (zip)
- Source code (tar.gz)

For 5.41.1, we must have:
- SandboxieInstall-v5.41.1.exe
- SandboxieInstall32-v5.41.1.exe
- SandboxieInstall32_xp-v5.41.1.exe (if you want)
- SandboxieInstall64-v5.41.1.exe
- Sandboxie-Plus-x64-v5.41.1.zip or SbiePlus64-v5.41.1.zip
- Sandboxie-Plus-x86-v5.41.1.zip or SbiePlus32-v5.41.1.zip
- Source code (zip)
- Source code (tar.gz)

For 5.41.2, we must have:
- SandboxieInstall-v5.41.2.exe
- SandboxieInstall32-v5.41.2.exe
- SandboxieInstall32_xp-v5.41.2.exe (if you want)
- SandboxieInstall64-v5.41.2.exe
- Sandboxie-Plus-x64-v5.41.2.zip or SbiePlus64-v5.41.2.zip
- Sandboxie-Plus-x86-v5.41.2.zip or SbiePlus32-v5.41.2.zip
- Source code (zip)
- Source code (tar.gz)

**Comment by DavidXanatos** [comment]
yeeeaaa...... no
realistically only the last release is relevant or the users so its not of much benefit to retroactively add missing files.

Also at some point the SbiePlusXX-v0.*.*.zip fill be replaced with an installer, etc....
