### ISSUE TITLE
OpenWinClass does not support specifying process names

### ISSUE THREAD

**Issue by 344389541** [sandboxie-plus/Sandboxie#750]
https://sandboxie-plus.com/sandboxie/openwinclass/

```
OpenWinClass=$:program.exe

Permits a program running inside the sandbox to use the PostThreadMessage API to send a message directly to a thread in a target process running outside the sandbox. This form of the OpenWinClass setting does not support wildcards, so the process name of the target process must match the name specified in the setting.
```

https://github.com/sandboxie-plus/Sandboxie/blob/dc0e3dc617d314103247faeddd98699983300aff/Sandboxie/core/dll/guiclass.c#L179
https://github.com/sandboxie-plus/Sandboxie/blob/124d926c65c738c392841100961ffdb6301e0f51/Sandboxie/core/drv/gui.c#L189

But the code doesn't seem to support this usage

**Comment by DavidXanatos** [comment]
See here: https://github.com/sandboxie-plus/Sandboxie/blob/3a3e5be67749c7d37c7bc1f2678cdd1df3e5ba02/Sandboxie/core/dll/guimsg.c#L737

it seams this option will work only on windows xp where sbie manages the GUI isolation itself
