### ISSUE TITLE
Is this a bug or a feature?

### ISSUE THREAD

**Issue by JimCarls** [sandboxie-plus/Sandboxie#753]
I opened Chrome in Sandboxie Plus 0.07.3 and it took perhaps 5-8 minutes before it stopped displaying messages like the one below and stabilized:

![Screenshot - 04_02_21 , 9_57_39 PM](https://user-images.githubusercontent.com/26904403/113466244-ddad5580-93ff-11eb-80f4-b1db79bc7170.png)

While this was happening, the Task Manager showed the disk usage at a 100% during the entire time. The first message displayed was about a file "catdb" and then it alternated between what seemed like the same set or types of files. It has never taken this long to come up and stabilize. I'm wondering if I need to simply clear the cache, but these messages don't really give me any clue. Thanks!

**Comment by DavidXanatos** [comment]
This just indicates that sandboxie is creating a few sandboxed copies of large riles, and the pogress of these operations.
