### ISSUE TITLE
Telegram runs slowly in Sandboxie-Plus 

### ISSUE THREAD

**Issue by vebmaster** [sandboxie-plus/Sandboxie#754]
**Describe the bug**
Telegram runs slowly in Sandboxie-Plus.
For example, when I type a message, my typing slows down. Sometimes the program freezes completely, I have to kill the process and reopen it.

**System and installed software (please provide the following information):**
 - Windows 10 Pro 20H2 19042.804
 - Sandboxie-Plus-x64-v0.7.0.exe (md5 61648a0d5c3d6f4b896502a21dca3563)
 - Run on host OutpostPro Firewall Pro 9.3 (4934.708.2079)

**Additional context**
The "Sandboxie-Classic-x64-v5.48.0.exe" version does not have this problem.
On Sandboxie-Plus-x64-v0.7.3.exe version does not have this problem.

**Comment by Dyras** [comment]
If the latest version works, then what's the problem?

**Comment by vebmaster** [comment]
> If the latest version works, then what's the problem?

I first posted the bug and then downloaded and installed the latest version :)
Thanks.
