### ISSUE TITLE
Why are files copied?

### ISSUE THREAD

**Issue by 344389541** [sandboxie-plus/Sandboxie#758]
My current version is V0.7.3。 To test, I put copyLimitKB =100

Start by running xenos64.exe, which requires administrator privileges,
Then use Xenos64 to launch another program  that requires administrator privileges,
takeown.exe will copy files to the sandbox, sbie 5.33 will not. (WinHook_Loader64.exe is just a test program)

![image](https://user-images.githubusercontent.com/26427035/113701480-c8d80700-970a-11eb-9999-d1989ffad6ba.png)

![image](https://user-images.githubusercontent.com/26427035/113701730-1f454580-970b-11eb-8b12-7808e31f5c88.png)

![image](https://user-images.githubusercontent.com/26427035/113701325-975f3b80-970a-11eb-96ea-568aaedcf40d.png)

![image](https://user-images.githubusercontent.com/26427035/113701363-a3e39400-970a-11eb-8d0f-c17a4fa4e215.png)

![image](https://user-images.githubusercontent.com/26427035/113702217-cb872c00-970b-11eb-8aa7-3596c8cea96f.png)

![image](https://user-images.githubusercontent.com/26427035/113702354-f96c7080-970b-11eb-9eac-cdc7de371e86.png)

xenos link:
https://github.com/DarthTon/Xenos

[winhook_loader64.zip](https://github.com/sandboxie-plus/Sandboxie/files/6264159/winhook_loader64.zip)

**Comment by 344389541** [comment]
call stack
![image](https://user-images.githubusercontent.com/26427035/113704149-58cb8000-970e-11eb-9d7c-97f429ed6160.png)

**Comment by DavidXanatos** [comment]
please provide also the dll

**Comment by DavidXanatos** [comment]
also please provide the other files pdb, etc...

**Comment by DavidXanatos** [comment]
on my system it does not try to run run takeown, there is somethign strange with your setup, or there are steps missing to reproduce the issue

**Comment by 344389541** [comment]
Winhookload.exe and this DLL are just an empty project。
The permissions for Xenos64 are  “ANONYMOUS LOGON”，  I debug sbiedll.DLL which calls ShellExecuteEx to start a new process

![image](https://user-images.githubusercontent.com/26427035/113800603-d385b100-9789-11eb-8a58-d2142adaf65a.png)

![image](https://user-images.githubusercontent.com/26427035/113800568-c36dd180-9789-11eb-9388-63417dba18ed.png)


[Release.zip](https://github.com/sandboxie-plus/Sandboxie/files/6268510/Release.zip)

**Comment by 344389541** [comment]
```
"C:\Program Files\Sandboxie-Plus\Start.exe" /env:__COMPAT_LAYER=RUNASINVOKER  C:\Users\Administrator\Desktop\fps\mytools\Xenos64.exe
```
After I add __COMPAT_LAYER= RunAsInvoker, the takeown will not be called
