### ISSUE TITLE
Messages from Sandboxie no longer able to be hidden

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#76]
Looks like runtimebroker constantly loads with a new PID or something of that nature, and is a constant annoyance, no matter how many times I hide it, it just keeps coming; if i don't block it other errors begin appearing

**Comment by rugabunda** [comment]
Same thing is happening now in vlc player.... but with dllhost.exe, after hiding the message, it continues to reappear 100x worse
![Sandboxie](https://user-images.githubusercontent.com/38260267/85921530-7230c900-b86c-11ea-9804-0e3c93377548.png)

**Comment by rugabunda** [comment]
I will try disable "force manditory aslr on images"

**Comment by rugabunda** [comment]
that did not fix it but so far it seems to have gone away after updating to windows 10 2004

**Comment by rugabunda** [comment]
that did not fix it but so far it seems to have gone away after updating to windows 10 2004

**Comment by Gravityzwell** [comment]
I think SB blocks specifically if you use the Hide button. You said the numbers keep changing, so that would make sense and is the same as I've seen for years.

You can manually add a rule to sandbox config that should catch them all. I don't think it supports wildcards, but partial should work. I remember struggling with that before. Another enhancement request for our underworked dev, regex for SbieCtrl_HideMessage :)

**Comment by rugabunda** [comment]
> 
> 
> I think SB blocks specifically if you use the Hide button. You said the numbers keep changing, so that would make sense and is the same as I've seen for years.
> 
> You can manually add a rule to sandbox config that should catch them all. I don't think it supports wildcards, but partial should work. I remember struggling with that before. Another enhancement request for our underworked dev, regex for SbieCtrl_HideMessage :)

Thanks for the tip, the problem has not been persistent but yes simplifying this action would be very helpful! Thanks for the tip. What line would one add to accomplish this, can you offer an example?
