### ISSUE TITLE
Manifest issue

### ISSUE THREAD

**Issue by feanorgem** [sandboxie-plus/Sandboxie#762]
I run VS2008 within a sandbox with sandboxie 5.33.3.0 and have no problems. After updating to either 5.49.0 or Sandboxie Plus 0.7.2 I can compile c/c++ with VS but running (even without recompiling since the update) will result in a popup:

This application has failed to start because the application configuration is incorrect. Review the manifest file for possible errors....

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/114185750-5c494c00-9946-11eb-8a5c-5f2b1a627f5f.png)

does this solve your issue?

**Comment by feanorgem** [comment]
Yes, that worked, thanks. FYI upgrading from old 5.33.3.0 to Plus 0.7.2 has problems but going to Classic 5.49.0 does not and going from Classic 5.49.0 to 0.7.2 is then problem-free as well. 

Changing this setting is per sandbox, perhaps it should be in the global settings or checked by default? What's the downside of doing this or what is the upside to having it unchecked?

**Comment by DavidXanatos** [comment]
It being checked breaks some apps for example the paint.net installer but also others that relay on having a proper manifest.

**Comment by isaak654** [comment]
> FYI upgrading from old 5.33.3.0 to Plus 0.7.2 has problems but going to Classic 5.49.0 does not and going from Classic 5.49.0 to 0.7.2 is then problem-free as well.

This is why I proposed this: https://github.com/sandboxie-plus/Sandboxie/issues/738

**Comment by feanorgem** [comment]
My point is more that the installer for 0.7.2 lacks some features of 5.49.0 and therefore could be updated to also have a clean install.
