### ISSUE TITLE
[Feature Req] RegHive Registry Viewer/Editor

### ISSUE THREAD

**Issue by OkeanGames** [sandboxie-plus/Sandboxie#765]
It would be a nice feature to have an registry editor built into the Sandboxie-Plus GUI to view and manual edit the "X:\Sandbox\\%USERNAME%\DefaultBox\RegHive" file without the need to import the file in system registry to view the contents.

Another one feature I missed in the original Sandboxie was to log registry changes (reads/writes) an application do.

Cheers!

**Comment by isaak654** [comment]
I agree. 
In the meantime, you could try SandboxToys2: #60
