### ISSUE TITLE
Access Is Denied (5) when running application

### ISSUE THREAD

**Issue by nearbaskara** [sandboxie-plus/Sandboxie#766]
Hello guys, I have a problem where I couldn't open exe file on sandboxie. Steam and other games. 
![image](https://user-images.githubusercontent.com/29061590/114259019-83af2000-99fd-11eb-8297-1f0e28b9291c.png)
![image](https://user-images.githubusercontent.com/29061590/114259049-b48f5500-99fd-11eb-9d13-fc217b6fb0d6.png)

this is the error. 

Update:
I tried using Sandboxie plus and got the error too.
![image](https://user-images.githubusercontent.com/29061590/114260073-36cf4780-9a05-11eb-9825-dd56d119d362.png)

Any solution for this? 

thank you in advance!

I use the latest version of sandboxie-plus 
![image](https://user-images.githubusercontent.com/29061590/114259041-a3dedf00-99fd-11eb-9fd9-6e7d4c926133.png)

Updated: 

I finally know the culprit. It seems my old Sandboxie broke sandboxie plus. All I need to do is reinstall the driver and the service from the Maintenance advance tab. Now the program works like a charm! 
![image](https://user-images.githubusercontent.com/29061590/114270530-76b32080-9a3f-11eb-83cd-6cd044df3d86.png)

**Comment by isaak654** [comment]
Please mention if you have any security software running in the background, even if the real-time protection is disabled.

**Comment by nearbaskara** [comment]
> Please mention if you have any security software running in the background, even if the real-time protection is disabled.

it's working now, All I need to do is reinstall service and driver of the program. Maybe it was broken because of my old sandboxie file.

**Comment by isaak654** [comment]
Yeah, upgrades from old versions can be messy.
