### ISSUE TITLE
Some files could not be recovered dialog box hard to close

### ISSUE THREAD

**Issue by Jimmy03** [sandboxie-plus/Sandboxie#767]
Just a small UI issue (Sandboxie Plus v0.7.2)

When Sandboxie shows the dialog box of "some files could not be recovered", it's not accessible by alt-tabbing to it, at first I thought Sandboxie had frozen. I managed to close it by clicking down on the taskbar and then hitting the X when the box was shown.  
  
The box shows an OK button that you are supposed to click, but I was never able to bring that box up via simple alt-tab.

**Comment by isaak654** [comment]
Can you reproduce it on 0.7.3?
https://github.com/sandboxie-plus/Sandboxie/releases

**Comment by Jimmy03** [comment]
> 
> 
> Can you reproduce it on 0.7.3?
> https://github.com/sandboxie-plus/Sandboxie/releases

Not sure how to reproduce, I was saving some images, and I got the error with one image.

**Comment by DavidXanatos** [comment]
if it can not be reproduced i cant fix it so i'll close this issue then
