### ISSUE TITLE
`BoxDisplayOrder` doesn't work in SandMan

### ISSUE THREAD

**Issue by Zymlex** [sandboxie-plus/Sandboxie#771]
`BoxDisplayOrder` from `[UserSettings_Portable]` doesn't work in SandMan.

For example:
`
BoxDisplayOrder=DefaultBox,Браузеры(Firefox,IE,Chrome),Мессенджеры(Telegram,Skype,Discord,Slack)
`

**Comment by Coverlin** [comment]
It's not meant to work with the new UI ...for now.

#262
