### ISSUE TITLE
[Feature] Add Show Code button in the Plus templates view

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#772]
In the Plus edition, there is no feature to show quickly the code for each template.

I suggest a Show Code button (like in Classic template view) to display the code of the selected template in the UI.

![show_code_button](https://user-images.githubusercontent.com/12372772/114312618-82f8b580-9af3-11eb-93d4-01fe90d9a3a1.png)

It would help me a lot to analyze quickly a template without scrolling templates.ini or jumping to sbiectrl in the installation folder.

![show_code_screen](https://user-images.githubusercontent.com/12372772/114312319-948d8d80-9af2-11eb-8cde-77f6c5ad3c54.png)

**Comment by DavidXanatos** [comment]
ah but there is something much better, double click on any template and you get a graphical editor, that also shows the code if you need

**Comment by isaak654** [comment]
> 
> 
> ah but there is something much better, double click on any template and you get a graphical editor, that also shows the code if you need

Nope, not working:
![plus_templates_list](https://user-images.githubusercontent.com/12372772/114317034-76ca2380-9b06-11eb-80a5-841a7d2b3a80.png)

**Comment by DavidXanatos** [comment]
> 
> 
> > ah but there is something much better, double click on any template and you get a graphical editor, that also shows the code if you need
> 
> Nope, not working:
> https://user-images.githubusercontent.com/12372772/114317034-76ca2380-9b06-11eb-80a5-841a7d2b3a80.png
> 
> Edit:
> I think I know what you're talking about, but you need to refine it by going directly to the ini section.

Ok next version will do that
