### ISSUE TITLE
[Plus] Software Compatibility tab doesn't show template names correctly

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#774]
**Describe the bug**
[Plus 0.7.3/0.7.4] Software Compatibility tab doesn't always show template names correctly.

**To Reproduce**
1. Open templates.ini in admin mode
2. Add this to the end of [Template_Firefox_Phishing_DirectAccess]
```
Tmpl.Scan=s
Tmpl.ScanProduct=Mozilla Firefox *
Tmpl.ScanService=MozillaMaintenance
```
3. See screenshot below

![software_compatibility_tab](https://user-images.githubusercontent.com/12372772/114313139-91e06780-9af5-11eb-85ac-ce16a501dc6d.png)

**Expected behavior**
Template name should be represented correctly without hashes or numeric values.

**Comment by DavidXanatos** [comment]
fixed in next build
