### ISSUE TITLE
START.EXE - Request to change Internet Settings system object

### ISSUE THREAD

**Issue by vebmaster** [sandboxie-plus/Sandboxie#776]
Hello.
Windows 10 pro 20H2
Outpost Pro 9.3.4934 firewall
I had Sandboxie-Classic-x64-v5.48.0.exe installed through the installer
One process "Telegram.exe" was running through Sandboxie
I was working in a browser (not Telegram), I was not working with Sandboxie at the moment and noticed a popup from Outpost with a request:

24.03.2021 13:53:37 START.EXE Request to change Internet Settings system object HKEY_USERS\-1-5-21-2974561527-887511215-1751437472-1001\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap

After a minute and a half, I blocked the request:

24.03.2021 13:55:24 START.EXE Block modification of system objects Internet Settings HKEY_USERS\S-1-5-21-2974561527-887511215-1751437472-1001\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap

Can you please tell me when these registry changes occur?
Thank you.

**Comment by isaak654** [comment]
https://docs.microsoft.com/en-US/troubleshoot/browsers/ie-security-zones-registry-entries
https://getadmx.com/HKCU/Software/Policies/Microsoft/Windows/CurrentVersion/Internet%20Settings/ZoneMap
