### ISSUE TITLE
Regression between 5.49.0 classic and 5.49.5 classic with jDownloader

### ISSUE THREAD

**Issue by Clouds123** [sandboxie-plus/Sandboxie#777]
When using SB 5.49.5 classic, the Linkgrabber tab in jDownloader does not redraw properly. If you add some URL's to jDownloader, they are not visible in the Linkgrabber tab unless you move the jdownloader window off screen and bring it back into view. With 5.49.0, the Linkgrabber tab works fine, and the files are immediately visible.

You can get jdownloader from jdownloader.org

This is on Windows 10 20H2 with all updates as of now.

**Comment by Clouds123** [comment]
Bit more info.

With a freshly downloaded version of jdownloader2, it works fine when sandboxed with the 5.49.5 and the latest 5.49.7.

The issue I was seeing was with a really old jdownloaderportable version (although it had been updated to latest version with in-built updater). If you're interested, I could send you a copy of the version that has problems with 5.49.5 and 5.49.7, in case it is some how highlighting a possible bug, even though there are no issues with a freshly downloaded version of jdownloader ?

Another noticeable issue with the problematic version, is that even switching tabs from either Downloads/Settings tabs to LinkGrabber tab results in a slight delay, and busy mouse cursor briefly.

**Comment by DavidXanatos** [comment]
can you first test in a virtual machine with 5.49.0 installed if the issue there is really not present?
To me this behavior sounds more like something broke in that particular installation only coincidentally with the update.
If in a VM the issue reproducibly goes away with 5.49.0 and re appears with 5.49.7 than please send me the files for a closer inspection.

**Comment by DavidXanatos** [comment]
whats the status on that?
is is still present or can i close it?

**Comment by Clouds123** [comment]
Thanks fr replying. Give me a couple of weeks to verify, and I'll respond. Don't close it yet though.

**Comment by DavidXanatos** [comment]
couple of months passed -> closed
