### ISSUE TITLE
0.7.4 update broke Debut Video Capture

### ISSUE THREAD

**Issue by X6B** [sandboxie-plus/Sandboxie#779]
For the first time i can´t run this software sandboxed. 0.7.2 and all earlier versions worked fine. I can´t even run the installer now. 

`WerFault.exe (3752): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1`

You can download the installer (2,9 MB only) from here: https://www.nchsoftware.com/capture/index.html  

Windows 10 20H2 64 bits.

**Comment by isaak654** [comment]
I can't run the installer sandboxed with 0.7.3, so it's 0.7.3 that broke it.

**Comment by X6B** [comment]
Still the same problem using 0.7.5 version. The installer runs now, but the program itself not. 

`WerFault.exe (5888): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1`

**Comment by DavidXanatos** [comment]
damn it i found the bug the new global hook mechanism that uses APC is at fault, due to a limitation in cross process communication: https://groups.google.com/g/microsoft.public.win32.programmer.kernel/c/UPkkhlAPhRs/m/1TIXq90yaYUJ?pli=1
now that will be fun fixing that :(

**Comment by isaak654** [comment]
I think this bug might also be related to the following Sticky Password issue: #780.

**Comment by DavidXanatos** [comment]
please try this new SbieSvc.exe https://xanasoft.com/Downloads/SbieSvc_5.49.9a.zip replacing the SbieSvc.exe of the latest build.
