### ISSUE TITLE
Sticky Password desktop app can't run sandboxed with 5.49.5/5.49.7/5.49.8

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#780]
**Describe the bug**
Can't run Sticky Password desktop app in 5.49.5, 5.49.7 and 5.49.8. Last working version was 5.49.0.

**To Reproduce**
1. Download Sticky password free (just the desktop app) from [here](https://www.stickypassword.com)
2. Install it outside of the sandbox, in the real system
3. Try to run it in a new fresh sandbox with 5.49.5/5.49.7/5.49.8... the tray icon of Sticky Password will appear for a few seconds, then the program will crash.

Workaround: return to 5.49.0, because it's the last working version.

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 20H2
 - Windows Defender

**Comment by isaak654** [comment]
This is still an issue in the current 5.49.8 version.

**Comment by DavidXanatos** [comment]
please try this new SbieSvc.exe https://xanasoft.com/Downloads/SbieSvc_5.49.9a.zip replacing the SbieSvc.exe of the latest build
and report back if the issue is solved

**Comment by isaak654** [comment]
> 
> 
> please try this new SbieSvc.exe https://xanasoft.com/Downloads/SbieSvc_5.49.9a.zip replacing the SbieSvc.exe of the latest build
> and report back if the issue is solved

It works fine, just a little drawback: _stpass.exe_ remains open for around 3 minutes in the sandbox after exiting the application from the UI.

**Comment by DavidXanatos** [comment]
according to a report in the wilders forum the build 0.7.5/5.49.8 fixed the issue
