### ISSUE TITLE
Snapshot Manager

### ISSUE THREAD

**Issue by rogansama** [sandboxie-plus/Sandboxie#782]
The Snapshot manager does not scale very well on a 4K display. I can't access any of the options or use it at all really.

To reproduce, it's just to go into the Snapshot manager of any Sandbox on a 4K display and see the scaling on it.

![Screenshot_2](https://user-images.githubusercontent.com/41278972/114476796-8d34b580-9bc0-11eb-94eb-714af85ec12a.png)

This issue is present on Sandboxie v0.7.4.

**Comment by DavidXanatos** [comment]
are all other windows working fine?

**Comment by rogansama** [comment]
Yeah, all windows are working fine except for the snapshot manager.

**Comment by DavidXanatos** [comment]
imho that shoud be fixed already with one of the recent DPI fixes so I'll close this if the issue as i can no longer reproduce it

**Comment by matuusu** [comment]
This issue is still present in Sandboxie-Plus v1.7.2

![image](https://user-images.githubusercontent.com/26598183/220750139-d444560f-6883-4608-9da6-6c2a5804a7bb.png)

**Comment by NewUserHa** [comment]
![image](https://user-images.githubusercontent.com/32261870/231911674-e0e4aaf3-91ba-4710-8ef2-6c782633a4f6.png)
4K with 100% dpi scaling of sandboxie-plus manager
![image](https://user-images.githubusercontent.com/32261870/231911785-9c899674-cd18-48ae-85e8-16ac81f503aa.png)
4K with 150% dpi scaling of sandboxie-plus manager
