### ISSUE TITLE
Can we start a browser with appending an argument at the end every time.

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#784]
Is there a way to start Brave in Sandboxie classic with the following argument " --disable-gpu".
This is so Brave isn't all white on one laptop I'm dealing with.

As always, thanks to everyone for your help.

**Comment by NewKidOnTheBlock** [comment]
This is how it works.
Create a link to your Sandboxie's Start.exe and then edit it like this:
`C:\Sandboxie\Start.exe /box:Browser C:\Brave\Brave.exe --disable-gpu`

This example assumes that your Sandboxie is located in `C:\Sandboxie`
and your Brave located in `C:\Brave`
and your Sandbox's name is `Browser`

**Comment by jedimasterspaz** [comment]
Do you mean a shortcut; because it won't let me create the shortcut in C:\Program Files\BraveSoftware\Brave-Browser\Application.
Please advise.
If not a shortcut,  What do you mean by link?

**Comment by jedimasterspaz** [comment]
"C:\Program Files\Sandboxie\Start.exe" /box:Defaultbox "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-gpu

The above opens Brave in the default box, crashing the extensions and doesn't load the pages.
FYI

**Comment by NewKidOnTheBlock** [comment]
Call it shortcut then
![mybad](https://user-images.githubusercontent.com/12411527/114923197-cffac580-9e2c-11eb-9787-9eab4d02288b.png)

**Comment by jedimasterspaz** [comment]
How do you get to the "Windows Shell Integration" windows?

**Comment by bjm234** [comment]
<img width="385" alt="png_10480" src="https://user-images.githubusercontent.com/25015553/118335264-43036480-b4dd-11eb-82f8-363a4e3f4565.png">

**Comment by DavidXanatos** [comment]
i take it the issue is resolved?
