### ISSUE TITLE
[0.7.3b / 0.7.4] Application crash on launch with OpenWinClass=*

### ISSUE THREAD

**Issue by JohnathanGalt** [sandboxie-plus/Sandboxie#786]
**Describe the bug**
CheatEngine 0.7.x crashes in a new sandbox with OpenWinClass=* set.

**To Reproduce**
1. Create new box with **_OpenWinClass=*_** setting included.
2. download CE no-setup version (https://www.cheatengine.org/downloads.php) Ctrl-F "by the setup click"
3. run CE binary ( cheatengine-x86_64-SSE4-AVX2.exe ) inside of newly created sandbox.
3. CE Instantly crashes with no error on Desktop, on a clean VM it does the same but also outputs an error in the Messages tab, 
```WerFault.exe (4704): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1```

**Expected behavior**
On 0.7.2 and all previous versions it works perfectly.

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? **Win10 Pro 1909** / **Win10 Pro 2004**
 - What is your current Sandboxie edition and version? **SBIE-Plus 0.7.4**
 - Please mention in which version this bug got introduced: **SBIE-Plus 0.7.3 beta** and continued into **SBIE-Plus 0.7.4**
 - Please mention any security software running in the background: **none**.

**Sandboxie configuration**
<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```
[GlobalSettings]

[Test]
Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
Template=AutoRecoverIgnore
openWinClass=*
```

</details>

**Comment by DavidXanatos** [comment]
Soooo... there is a workaround for your issue: add
```SkipHook=cheatengine-*.exe,createwin```
to your sbie ini, I'll be looking into a better fix
but it may stay at that if i cant find one

**Comment by DavidXanatos** [comment]
ok I think I know how to properly fix that, the above workaround wont longer be needed in the next build

**Comment by JohnathanGalt** [comment]
I tested the new SBIE+ v0.8.0 and it still crashes/closes instantly without the workaround in a fresh sandbox with default config,

**Comment by JohnathanGalt** [comment]
the 0.8.x changelogs mentions it being fixed but its doing the exact same thing still, bug shouldn't be closed. for time being I will continue to use that workaround you posted which does allow it to work.

**Comment by DavidXanatos** [comment]
indeed in broke the fix later on, will be fixed properly in the next build, promiss
her is a fixed sbiedll.sll for you: https://xanasoft.com/Downloads/SbieDll_5.50.1a.zip
fix will be included in the next build
