### ISSUE TITLE
wps can't run

### ISSUE THREAD

**Issue by God-Asimov** [sandboxie-plus/Sandboxie#787]
I can install wps in sandboxie, but it will crash after any operation.The problem is more serious in wps pro.

**Comment by DavidXanatos** [comment]
what os wps?
did it ever run in any sandboxie version?

**Comment by God-Asimov** [comment]
Wps is an office software from China, similar to MSoffice.
Its website in China is
standard version:https://www.wps.cn/
pro version:https://ep.wps.cn/
I am not sure if you can visit.

It has not been able to run in all versions.
The software can be installed successfully, but the shortcuts are all wrong.  It crashed after a limited number of operations, but sandbixie did not issue any warnings.

**Comment by DavidXanatos** [comment]
well its all chinese so i cont understand it and cant use this program to test it but clicking around with 0 understanbding i could install it and it opened in tne latest build so the issue may be fixed
