### ISSUE TITLE
Sandboxie duplicates specific sandbox when settings are changed and some settings enable other settings

### ISSUE THREAD

**Issue by darkthepro1990** [sandboxie-plus/Sandboxie#789]
**Describe the bug**
When I change the settings in advanced options(Miscellaneous and Isolation), sandboxie duplicates specific sandbox and Miscellaneous and Isolation settings enable other settings in advanced options

**To Reproduce**
Go to Advanced Options -> Miscellaneous -> Compatibility
Check/uncheck Emulate sandboxed window station for all processes
Confirm settings

**Expected behavior**
Enable settings with interface instead of editing edit.ini manually 

**Screenshots**
![1](https://user-images.githubusercontent.com/17624280/114870648-19352000-9e01-11eb-8858-c9a6bc970bdc.PNG)
![2](https://user-images.githubusercontent.com/17624280/114870658-1b977a00-9e01-11eb-8fdc-f50169798d87.PNG)
https://user-images.githubusercontent.com/17624280/114872748-47b3fa80-9e03-11eb-9295-9646effbbe48.mp4

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2).
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.4).
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. (after 0.7.3)
 - Please mention any security software running in the background, even if the real-time protection is disabled. (bitdefender)

**Sandboxie configuration**

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#0400ff,on,6
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
DropAdminRights=y
ClosePrintSpooler=y
OpenSmartCard=n
BoxNameTitle=n
BlockNetParam=y
FakeAdminRights=y
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
CopyLimitKb=-1
PromptForFileMigration=n
CopyLimitSilent=y
NeverDelete=n
AutoDelete=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=y
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
HideOtherBoxes=y
MonitorAdminOnly=y
UseSbieWndStation=y

[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=y
ForceDisableAdminOnly=y
ForgetPassword=n
StartRunAlertDenied=y
NotifyStartRunAccessDenied=y
Template=RpcPortBindings
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=InternetDownloadManager
Template=7zipShellEx
TemplateReject=BitDefenderInternetSecurity

[UserSettings_175D0429]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
BoxDisplayOrder=Isolated1,Isolated,Isolated,Isolated,Isolated,Isolated

[DefaultBox]

Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore

**Comment by supracoralline** [comment]
Just want to bump this and ask if there are any work around or temporary solution for this (other than having to manually reinstall, delete every associated folder and sandbox, delete registry keys, etc.)

**Comment by DavidXanatos** [comment]
shoudl be fixed in the recent builds
