### ISSUE TITLE
Request: Allow resize of resource monitor window

### ISSUE THREAD

**Issue by DocMAX** [sandboxie-plus/Sandboxie#79]
Request: Allow resize of resource monitor window.
I allways didn't understand why this has been programmed as fixed size window.

**Comment by DavidXanatos** [comment]
This is a part of the legacy UI on which I will only do the absolute minimum.
You can check out the SandMan.exe UI it has a tab for the resource monitor that can be resized.

**Comment by DavidXanatos** [comment]
The sandman UI is really superior in any regard, as of the next build it will be even able to search strings in the resource monitor tab. So I'll close this here.
