### ISSUE TITLE
Disk operations requiring Admin rights ... ?

### ISSUE THREAD

**Issue by macruspareto** [sandboxie-plus/Sandboxie#790]
I'm a happy user of Sandboxie-Plus 0.7.2 and would like to ask if there's any way to perform admin-only HDD operations inside the box?

I need to change the volume label of my HDD to debug a program in the box. Are these actions supported/virtualized? Thanks!

`Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>label
Volume in drive C: is WINDOWS
Volume Serial Number is F1F1-F2F2
Volume label (32 characters, ENTER for none)?

Access Denied as you do not have sufficient privileges.
You have to invoke this utility running in elevated mode.

C:\Windows\system32>
`

**Comment by DavidXanatos** [comment]
no raw disk access is not visualized so this wont work unfortunately.
