### ISSUE TITLE
Internet Download Manager seems have problems in default sandbox 

### ISSUE THREAD

**Issue by shineboyxxb** [sandboxie-plus/Sandboxie#791]
**Describe the bug**
When I run Chrome in the sandbox and download files through IDM, the IDM application that chrome pulled up does not run in the sandbox, and the downloaded files are not isolated.

**To Reproduce**
1. install Sandboxie plus
2. install IDM
3. run chrome in default sandbox
4. download file from chrome with IDM

**Expected behavior**
IDM run in the default sandbox

**Comment by isaak654** [comment]
I would suggest to delete all preset text where you don't provide any information.

**Comment by shineboyxxb** [comment]
> I would suggest to delete all preset text where you don't provide any information.

thanks

**Comment by DavidXanatos** [comment]
The issue is that the IDM is using a socket to communicate with the desktop component,
you can add
```BlockPort=1001```
to your sandboxie ini in order to prevent this behavioure,
with that port blocked IDM wil not be able to communicate with the unsandboxed component and start a local sandboxed instance

**Comment by sixiansheng** [comment]
我也遇到这个问题，添加了BlockPort=1001之后，依然还是调用shandboxie外的下载器下载

**Comment by isaak654** [comment]
> 
> 
> 我也遇到这个问题，添加了BlockPort=1001之后，依然还是调用shandboxie外的下载器下载

This workaround is no longer needed, because that line was integrated directly in IDM template since v0.8.0 / 5.50.0.
Latest release is v0.8.2 / 5.50.2, if you still have this problem please report in english and I'll reopen the issue.

**Comment by sixiansheng** [comment]
> > 我也遇到这个问题，添加了BlockPort=1001之后，依然还是调用shandboxie外的下载器下载
> 
> This workaround is no longer needed, because that line was integrated directly in IDM template since v0.8.0 / 5.50.0.
> Latest release is v0.8.2 / 5.50.2, if you still have this problem please report in english and I'll reopen the issue.

Thank you very much, v0.8.2/5.50.2 solved this problem really great, this makes my computer very clean
