### ISSUE TITLE
Clipboard and Keypress protection?

### ISSUE THREAD

**Issue by macruspareto** [sandboxie-plus/Sandboxie#794]
Hello guys!

I'm wondering if its possible to have the host clipboard isolated from sandboxed processes?

Imagine a well-hidden malicious process sitting quietly in the sandbox but seeing everything you'd typed or copypasted.... How would you mitigate that?

**Comment by DavidXanatos** [comment]
The next build will contain the option 
```OpenClipboard=n```
that will allow to block a particular sandbox from accessing the clipboard
