### ISSUE TITLE
Sandboxie continues to pull in files after I've closed the app I was running

### ISSUE THREAD

**Issue by oldcrankyman** [sandboxie-plus/Sandboxie#797]
I use Sandboxie to run 2 instances of a Steam game, Naval Action.   Yesterday and today, after I logged out of the game, I noticed that my machine was lagging, so looked at task manager.  I saw that sandboxie was still active, and when I went to delete the contents, It showed over 9 gigs of files, with the number going up very rapidly.

I'm running a version of sandboxie that I downloaded years ago and am running Win 7 home 64 bit.   I use Total AV for security software.

Is somebody using sandboxie to look at my files?

**Comment by DavidXanatos** [comment]
> I'm running a version of sandboxie that I downloaded years ago

please try a recent build
