### ISSUE TITLE
5.49.7 breaks Unity-games again

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#799]
Issue #319 is back!
Games based on the Unity-Engine are broken again and take a long time to launch in the latest Sandboxie.

**Freezes**

- Candleman
- Into The Woods
- Iron Harvest
- Oddworld Soulstorm
- The Universim
- 

All these games freeze for 5 minutes on launch, stop responding and start only after 5 minutes of waiting time.
If necessary I can test more.

Windows 10 20H2
Sandboxie 5.49.7

I've also tested Breathedge (an Unreal-engine game) and The Binding of Isaac Rebirth (which got its own engine) - those still work.

**Comment by NewKidOnTheBlock** [comment]
Can anyone confirm?

I've tried adding the following lines:
OpenSamEndpoint=y
OpenDevCMApi=y
AllowRawDiskRead=y
RpcMgmtSetComTimeout=y
...but that didn't help.

**Comment by davi-ro** [comment]
In the latest two releases David wrote that RpcMgmtSetComTimeout was deprecated.
`reworked RPC resolver to be ini configurable
-- the following options are now deprecated:
--- "UseRpcMgmtSetComTimeout=some.dll,n", so use "RpcPortBinding=some.dll,*,TimeOut=y"`

Try using the new RpcPortBinding instead of UseRpcMgmtSetComTimeout. Maybe that will help

**Comment by NewKidOnTheBlock** [comment]
Just the game Iron Harvest has 223 .dlls (sic!) - how would I adjust for that?
![iron harvest](https://user-images.githubusercontent.com/12411527/115185532-4d019580-a0e0-11eb-90f2-ed07f1d007e8.png)

**Comment by dxq3** [comment]
I had problems with my games (I use SB-PLUS 0.7.4) and found some working tricks. For the game "Forgotton Anne" I block access to BluetoothApis.dll in system32 and for the game "Stranded Deep" same file in syswow64. Hiding insead of blocking works too.

**Comment by DavidXanatos** [comment]
try adding the new bluetooth compatybility template

**Comment by NewKidOnTheBlock** [comment]
I got not clue how templates work.
There is a Templates.ini

I found this section in it concerning bluetooth, but I don't know what I'm supposed to do with it:
`#
# Optional RPC Port Config
#

[Template_OpenBluetooth]
Tmpl.Title=Open Bluetooth RPC port
Tmpl.Class=Misc
#bluetooth
RpcPortBinding=BluetoothApis.dll,'ncalrpc:',Resolve=Bluetooth,TimeOut=y
RpcPortBindingIfId=Bluetooth,{2ACB9D68-B434-4B3E-B966-E06B4B3A84CB}
RpcPortBindingSvc=Bluetooth,bthserv`

**Comment by NewKidOnTheBlock** [comment]
Update: The games don't crash, but it's the old 5-minute-freeze @isaak654 pointed out in issue #319

For testing, I put the line 
`OpenBluetooth=y` into my Sandbox's config, but that doesn't make a difference.
The 5-minute-freeze occurs with and without it.

**Comment by Coverlin** [comment]
> I got not clue how templates work.
> There is a Templates.ini
> 
> I found this section in it concerning bluetooth, but I don't know what I'm supposed to do with it:
> 
> ```
> #
> # Optional RPC Port Config
> #
> 
> [Template_OpenBluetooth]
> Tmpl.Title=Open Bluetooth RPC port
> Tmpl.Class=Misc
> #bluetooth
> RpcPortBinding=BluetoothApis.dll,'ncalrpc:',Resolve=Bluetooth,TimeOut=y
> RpcPortBindingIfId=Bluetooth,{2ACB9D68-B434-4B3E-B966-E06B4B3A84CB}
> RpcPortBindingSvc=Bluetooth,bthserv
> ```

`Template=OpenBluetooth` add to box or global
Or use the tmpl.class/title info to find it and add it via the UI's

**Comment by NewKidOnTheBlock** [comment]
@Coverlin
Thanks, I think I understand how the system works now.
I can derive the Templates' names from the .ini and then put them into the config.

`Template=OpenBluetooth`
solves the freeze and Unity-games start practically instantly

**Comment by isaak654** [comment]
I don't like how this works, I would prefer an informative prompt that allows you to open these RPC ports when a process requires them.

**Comment by NewKidOnTheBlock** [comment]
@isaak654 Agreed.
Unity Engine programs (aka games) are legion.
![Global-game-engine-market](https://user-images.githubusercontent.com/12411527/115748949-ec4fb280-a396-11eb-82d6-395834983b59.png)
([Source](https://thenextweb.com/news/engine-dominating-gaming-industry-right-now))
The "closest competitor" would be Unreal Engine. Now these numbers come directly from Unity, so I went ahead and counted how many games in my Steam library are powered by Unity.

Result: 127 out of 592 games are Unity games.
That's a whopping 21.4% and it stands to reason that there are more Unity games published every day.

Closing thought:
It makes for a bad sandboxing experience if a new SB user has to actively dig through this issue section to (hopefully) find the magic template hack that helps him run hundreds of games which all freeze on him out of the box.

**Comment by DavidXanatos** [comment]
So we should make open BT enabled by default?

**Comment by isaak654** [comment]
> 
> 
> So we should make open BT enabled by default?

Yes, unless there is another way to detect in realtime if a process needs bluetooth.

**Comment by NewKidOnTheBlock** [comment]
Yes, because it means hundreds, if not thousands of programs will work out-of-the-box.
If there is a smarter way (like isaak654 mentioned), that's even better.

**Comment by DavidXanatos** [comment]
> 
> 
> > So we should make open BT enabled by default?
> 
> Yes, unless there is another way to detect in realtime if a process needs bluetooth. I don't know if it's achievable.

sure we could detectt that but than always allwoing it would be equivalent to always including this template, so no point in doin that

The next build of sandboxie+ will for all existing non hardened sandboxes automatically add this template and when creating a new non hardened box automatically add it
