### ISSUE TITLE
GTA5 (Epic verison) not running

### ISSUE THREAD

**Issue by DocMAX** [sandboxie-plus/Sandboxie#80]
I try to run GTA5 (Epic version) in Sandboxie.
I get an error 7002.1 from the Rockstar Launcher.
Anyone else trying this?

**Comment by DocMAX** [comment]
Looks like the Rockstar service doesn't run well on sandboxie. Anyway. I will close this here.

**Comment by isaak654** [comment]
See https://github.com/sandboxie-plus/Sandboxie/issues/2236#issuecomment-1255901875 for a possible workaround.
