### ISSUE TITLE
Warn before a programme starts WITHIN a sandbox

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#800]
* I never sandbox my email client, but I normally sandbox my browsers.
  --- To email from a webpage address, I copy the address, then open the email client.
* But occasionally I forget, and I click on an email address in a webpage.
  --- The mail client opens in the sandbox, and I send my email without noticing.
  --- The sent message is then lost, unless I remember before deleting the sandbox.

REQUEST:  Could we have a new button on Sandboxie Control: 
       'Warn before these programmes start within a sandbox.'  
Clicking the button should allow selection of programmes that this warning applies to.

My problem concerns only my email client, but others will surely have similar problems with other software.

**Comment by Dyras** [comment]
Start Restrictions -> Prevent selected programs from starting in this sandbox

Maybe that helps?

**Comment by NotepadPlusUser** [comment]
Thanks, @Dyras.  It sounds exactly what I want.  But I can't find it.  The only thing that I can find,in Sandboxie Control (I missed it before) is:
_Click on sandbox --> Sandbox Settings --> Restrictions --> Start/Run Access --> The following programs will be the only programs in this sandbox that can start and run._

Not exactly what I suggested, which was a list of programmes that should NOT start in the sandbox.  But I wonder if your setting is new in Sandboxie Plus, whereas I am still only using Sandboxie Classic V5.49.7.  If it's only in Plus, then I will change over right now.

**Comment by Dyras** [comment]
I think it's a Sandboxie-Plus feature, yes.

**Comment by NotepadPlusUser** [comment]
I have now taken the plunge and installed Sandboxie-plus.  I found the setting, and it works perfectly for blocking my email client from opening in the sandbox.

Thank you very much, @Dyras.  You've saved me (and my wife) from ourselves.

Notes on the process for anyone following --- I may have been overcautious:
* Save a copy of C:\Windows\Sandboxie.ini for safety.  
* Close all running programs.
* Run the Sandboxie-classic installer file to uninstall Sandboxie-classic, choosing to keep Sandbox.ini.
* Install Sandboxie-Plus --- everything configured itself exactly correctly.
* Open Sandboxie Control, now called Sandman --> double-click on DefaultBox. 
* _Start Restrictions --> Prevent selected programs from starting in this sandbox_.
* _Add program_ --> Type in thebat64.exe (my email client --- wasn't on drop-down list).
* Repeat the last three steps for each of the other sandboxes.
