### ISSUE TITLE
IME not working with Elevation restrictions all on

### ISSUE THREAD

**Issue by sakuyaa** [sandboxie-plus/Sandboxie#801]
**Describe the bug**
Hi, recently I found when the setting `Make applications think they are running elevated` was on, the Chinese IME (Rime) is not working.

**To Reproduce**
1. Create new box with `Drop rights from Administrators and Power Users grops` setting included.
2. Add full access to file `\Device\NamedPipe\your-username\WeaselNamedPipe` discribe in https://github.com/sandboxie-plus/Sandboxie/issues/39#issuecomment-723469155 and https://github.com/sandboxie-plus/Sandboxie/issues/120#issuecomment-726010336 .
3. IME works fine.
4. With the setting `Make applications think they are running elevated` on, IME not working.

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? Windows 10 LTSC.
 - What is your current Sandboxie edition and version? Sandboxie Plus 0.7.4.

**Comment by isaak654** [comment]
This incompatibility with `FakeAdminRights=y` is also related to various templates like `[Template_IExplore_History_DirectAccess]`, so I would also suggest to implement some sort of detection that will warn you when a running sandboxed application is not compatible with that setting, starting from IE.

**Comment by sakuyaa** [comment]
In the latest release 0.9.3, IME works fine with the setting `Make applications think they are running elevated` on (steps 2 still needed).
