### ISSUE TITLE
How to change LANGUAGE to Chinese or etc. ?

### ISSUE THREAD

**Issue by Tomsu2016** [sandboxie-plus/Sandboxie#802]
**Is your feature request related to a problem? Please describe.**
Sandboxie is a good software, and i like it. But I can't change the display language of sandboxie plus to Chinese.

**Describe the solution you'd like**
Adding change display language function.

**Comment by DavidXanatos** [comment]
the Plus UI already has this function, are you asking for that function in the classic UI?

**Comment by woshiniming007** [comment]
> the Plus UI already has this function, are you asking for that function in the classic UI?

Hello, I also have a question. The classic installer has an option to select language but plus installer doesn't have. This can affect localized right menu in explorer.

**Comment by Nick768** [comment]
You can change the lanuage... It's not very intuitive, but i've found this thread:
[How to change interface language on the fly](https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic76417641.html?f=14&t=6362&p=41694).
There was a List of possible languages and their decimal value linked, but the link is dead. But here it is with the help of archive.org:
[Sandboxie Corporate Installation](https://web.archive.org/web/20170721060250/http://www.sandboxie.com/index.php?CorporateInstallation).

Now in my own words:
1. Open regedit
2. navigate to: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\SbieSvc
3. check if there is a DWORD value called "Language" (without the quotes)
4. if necessary: create a DWORD called "Language"
5. tick "decimal"
6. type in "2052" for Chinese (Simplified)

Then everything should work, except the "Run Sandboxed" text in right click context menu. I guess this entry manages the display text:
HKEY_CURRENT_USER\Software\Classes\*\shell\sandbox
The (Default) value seems to be responsible for this text. It seems to work if you change this text to something fitting to your language, BUT I don't know what this "&Sandboxed" means. Why is there a "&"?
