### ISSUE TITLE
Windows default color picker + DPI change issue

### ISSUE THREAD

**Issue by CarlColijn** [sandboxie-plus/Sandboxie#803]
**Describe the bug**
When a sandboxed application opens the default Windows color picker dialog (Windows common controls) when the DPI is set to something not 100%, mouse clicks in the color hue/saturation square and on the value slider trigger a mouse cursor reposition outside of the dialog's bounds, making the dialog unworkable.  I got this bug to show for Paint.exe as well as FireFox (when clicking on a color picker form element), so I assume it is just the common controls dialog itself that's at fault.

**To Reproduce**
1. Set the display's DPI to e.g. 150%
2. Force-start Paint.exe in a sandbox
3. Click the color picker toolbar button
4. Click anywhere in the mentioned parts of the dialog

**Screenshots**
See [FireFox in action on YouTube](https://www.youtube.com/watch?v=YnKTGWdxl80), though Paint.exe exhibits identical behavior (I found out about that after the above video was uploaded; I was going to use it for reporting a FireFox bug).

**System details and installed software (please provide the following information):**
- Windows 10 Home, Version 10.0.19041 Build 19041
- Sandboxie Plus 5.49.7 64 bit
- I don't know which Sandboxie version started this; I virtually never encounter sandboxed color pickers :)
- Other security software: Windows Defender, real time protection: on

**Additional context**
It seems the color picker dialog is itself actively repositioning the cursor, so there's nothing stopping that.  Somehow Sandboxie Plus manages to make the common control code not be able to retrieve the right DPI settings when repositioning, and/or doesn't allow the host app to show the color picker dialog in the right DPI state (think SetThreadDpiAwarenessContext and such)?

**Sandboxie configuration**
[Gist of the relevant parts of my Sandboxie.ini](https://gist.github.com/CarlColijn/f72213bdc9b309c78b04581937094d5b)

**Comment by DavidXanatos** [comment]
this should be fixed in build 1.0.10
