### ISSUE TITLE
can't delete or rename the "DefaultBox" in sandboxie plus 0.7.4

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#807]
if we try to rename the "DefaultBox" in sandboxie plus 0.7.4 is just creates a new sandbox with the new name, and the "DefaultBox" remains there, we can't delete it either, just to point out that i CAN delete and rename it in sandboxie classic, is it a feature or a bug in sandboxie plus?
![z6R1ibQ](https://user-images.githubusercontent.com/54504707/115790458-202dd680-a39d-11eb-9fdb-920c302f025c.png)

**Comment by Coverlin** [comment]
`Enabled=y,Guest`

**Comment by DavidXanatos** [comment]
its intended that there always is a default box, sbie plus recreates it on the fly, classic woudl iirc recreate it on restart
