### ISSUE TITLE
disabled box showing in dropdown menu

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#808]
bug in latest sandboxie plus 0.7.4

I disabled the defaultbox and when try to open a new program the disabled box appear in the dropdown menu

could you make it not to show a disabled box in dropdown menu when we try to open a program?
![5fr3wUg](https://user-images.githubusercontent.com/54504707/115796174-bf57cb80-a3a7-11eb-94d9-234c628a0719.png)

**Comment by DavidXanatos** [comment]
fixed in next build
