### ISSUE TITLE
Hi guys can I ask one thing? about sbie2224

### ISSUE THREAD

**Issue by BMC222** [sandboxie-plus/Sandboxie#809]
The game I play has a security program.
If I run a game on a sandboxie, the security program and the sandboxie crashed with sbie2224
I think the security program is detecting the sandboxie
The game ends because the security program fails due to a crash
Is it possible to bypass this part?
I've been searching for this problem for a year and I haven't found an answer....
Sorry if this is a different question from what this community means.

**Comment by DavidXanatos** [comment]
possible yes, 
easy idk, 

what security program etc...
