### ISSUE TITLE
Steam to detect running game?

### ISSUE THREAD

**Issue by DocMAX** [sandboxie-plus/Sandboxie#81]
Running games launched by steam is working fine (forced folders). But only problem is steam does not detect the game is running once in the sandbox. Any workarounds for this? I guessed "OpenWinClass=*" would do the trick but does not.

**Comment by AndhikaWB** [comment]
Why would you run a game inside a sandbox? Didn't it decrease overall performance too?

**Comment by DocMAX** [comment]
I don't see performance loss.
I use this to isolate my savegames (written all over the place Documents, Appdata, Localappdata, Save Games,...) and keep them in one place. I can switch from Win10 to Win7 back and forth with this and have my same game states.

**Comment by johndoe84329** [comment]
Could you specify what Windows version are you using? I am on Win10 2004, and Steam can't even launch game in forced folder.

**Comment by DavidXanatos** [comment]
It may be enough to OpenWinClass=# and would be much more secure ;)
