### ISSUE TITLE
Can rules match precise paths first?

### ISSUE THREAD

**Issue by StrollStars** [sandboxie-plus/Sandboxie#813]
Rules:
WriteFilePath=C:\Program Files\
OpenFilePath=C:\Program Files\Tools

Effect:
Now I can't see the Tools folder. I hope the following rule will work.

**Comment by Nick768** [comment]
I don't exactly understand your question, but in Sandboxie you can generally edit your .ini file and rearrange the order of rules. In your example if "WriteFilePath=C:\Program Files" is your first rule and "OpenFilePath=C:\Program Files\Tools" is somewhere after your first rule, then everything in C:\Program Files is hidden and write only. But if you open your .ini and write it like this: 
OpenFilePath=C:\Program Files\Tools
WriteFilePath=C:\Program Files 
C:\Program Files\Tools should now be directly accessed and everything else in C:\Program Files should be hidden

**Comment by StrollStars** [comment]
@Nick768 Thank you for your help, my Sandboxie.ini file reads as follows:
> ForceProcess=notepad.exe
OpenFilePath=D:\Program Files\Tools
WriteFilePath=D:\Program Files

But I open D:\Program Files\Tools by notepad, it says windows can't find D:\Program Files\Tools.

**Comment by Nick768** [comment]
Sorry for my late response... i've tested this settings... you are absolutely wright! I didn't noticed that my suggestion won't work for resource access. Perhaps the more restrictive settings have a higher priority? Perhaps somebody could explain how the the lines in the .ini are parsed? I thought sandboxie reads it line by line and executes it line by line.

**Comment by StrollStars** [comment]
@Nick768 Thank you all the same. Many programs match rules sequentially such as firewall, but I haven't get sandbox's priorities yet, and I haven't found the documents. I hope the developer will see this issue.

**Comment by DavidXanatos** [comment]
> Perhaps the more restrictive settings have a higher priority?

yes thats the issue

**Comment by DavidXanatos** [comment]
see https://github.com/sandboxie-plus/Sandboxie/issues/890
