### ISSUE TITLE
Registry operations logging?

### ISSUE THREAD

**Issue by macruspareto** [sandboxie-plus/Sandboxie#814]
Hello everyone!

Is there a SBPlus option to log all or specific registry operations inside the box?
Keys created / deleted / modified etc?

Or should I try third-party apps like RegShot? What's the best way? Thanks!

**Comment by isaak654** [comment]
You can find a few suggestions [here](https://github.com/sandboxie-plus/Sandboxie/issues/60).

**Comment by DavidXanatos** [comment]
Use the tracing feature 
or go for procmon.eye from sysinternals
