### ISSUE TITLE
SBIE2101

### ISSUE THREAD

**Issue by hollesser** [sandboxie-plus/Sandboxie#816]
Hello,
i tried Sandboxie-Classic-x64-v5.49.7 and Sandboxie-Plus-x64-v0.7.4 on Windows 10 Pro 64 bit Build 19041.867
and after install and launch web browser in DefaultBox i get:
SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
Starting Windows Explorer in Sandbox causes an Windows error message 0xc00000e5.
I have no chance of the ini.
Creating a new sandbox causes the same error. Reinstall does not help.

**Comment by isaak654** [comment]
1) What's your web browser?
2) Can you reproduce the same issues on `Sandboxie-Classic-x64-v5.49.0`?

**Comment by DavidXanatos** [comment]
Please provide infos about your setup / browserand try the previosue version
