### ISSUE TITLE
How do I update/reinstall?

### ISSUE THREAD

**Issue by tolga694** [sandboxie-plus/Sandboxie#818]
Check for updates doesn't work in 0.7.3 portable and I started getting a SBIE2224. How do I go about updating or making a clean install with my settings and sandboxes preserved?
Thank you very much for this fork it's great.

system: Windows 7 SP1 64-bit
version: Sandboxie Plus portable 0.7.3
no security software exists

**Comment by NewKidOnTheBlock** [comment]
You simply install the new version over it. Sandboxie has become pretty good at that. All the recent updates went through flawlessly for me.
If you want to be super-safe, you could create a backup of C:\Windows\Sandboxie.ini beforehand.
