### ISSUE TITLE
Auto Delete contents still shows files already downloaded - Sandboxie-Classic-x64-v5.49.7

### ISSUE THREAD

**Issue by jacksterx** [sandboxie-plus/Sandboxie#819]
Sandboxie-Classic-x64-v5.49.7 - Auto Delete contents still shows files already downloaded.
![Download Folder](https://user-images.githubusercontent.com/83376095/116479575-dd14ad00-a84d-11eb-84f8-b7dc1ac0b0f8.jpg)
![Delete Contents - DefaultBox](https://user-images.githubusercontent.com/83376095/116479576-ddad4380-a84d-11eb-9489-cf5bb99a1461.jpg)

**Comment by Coverlin** [comment]
> Sandboxie-Classic-x64-v5.49.7 - Auto Delete contents still shows files already downloaded.
> ![Download Folder](https://user-images.githubusercontent.com/83376095/116479575-dd14ad00-a84d-11eb-84f8-b7dc1ac0b0f8.jpg)
> ![Delete Contents - DefaultBox](https://user-images.githubusercontent.com/83376095/116479576-ddad4380-a84d-11eb-9489-cf5bb99a1461.jpg)

![read](https://user-images.githubusercontent.com/34079190/116486221-c134f980-a895-11eb-8ea3-d0ddcbb0dc79.jpg)

**Comment by jacksterx** [comment]
Coverlin,

Exactly what are you showing in your diagram?  Should I uncheck Automatically delete contents of sandbox?  I've had this setup for years now and it has worked (Deleted all files) when ending the Sandbox.  It's only recently that it is selectively asking what to recover even after the download has completed successfully!

**Comment by Coverlin** [comment]
> Coverlin,
> 
> Exactly what are you showing in your diagram? Should I uncheck Automatically delete contents of sandbox? I've had this setup for years now and it has worked (Deleted all files) when ending the Sandbox. It's only recently that it is selectively asking what to recover even after the download has completed successfully!

Remove the Downloads folder or everything from Quick recovery if you don't care about saving files outside the box

`lf any sandboxed files are eligible for recovery. Quick Recovery will be invoked instead
of automatic delete.`

**Comment by jacksterx** [comment]
That's not the problem I'm having. I do want to download files using Quick Recovery and get prompted to save them to my Download folder which I do successfully.  It's when I exit Sandboxie with Delete invocation (Auto delete the remaining contents of sandbox) that the successfully downloaded file/s are still listed after exit.
![Downloads](https://user-images.githubusercontent.com/83376095/116832684-1453c880-ab84-11eb-95f9-d1876324f778.jpg)
![Quick Recovery](https://user-images.githubusercontent.com/83376095/116832689-1c136d00-ab84-11eb-9020-857a53b48afd.jpg)
![Exiting Sandbox](https://user-images.githubusercontent.com/83376095/116832697-27ff2f00-ab84-11eb-8dbc-610228963905.jpg)

**Comment by DavidXanatos** [comment]
the last build had some imoprovements in the region of file recovery i'll close this issue if it stil persists please let em knwo than i'l reopen it
