### ISSUE TITLE
"A sandbox must be emptied before it can be deleted."?

### ISSUE THREAD

**Issue by WhiteWolf-One** [sandboxie-plus/Sandboxie#820]
Having right-clicked a sandbox and chosen 'remove sandbox', I get: A sandbox must be emptied before it can be deleted.

How do I go about emptying a sandbox?

**Comment by isaak654** [comment]
Right click on the sandbox -> Delete Content

**Comment by Dyras** [comment]
Might be worth considering changing "Delete Content" into "Remove Content" to make it more consistent
