### ISSUE TITLE
 SBIE2203 error after Vivaldi update

### ISSUE THREAD

**Issue by Deadite333** [sandboxie-plus/Sandboxie#821]
With todays Vivaldi update Sandboxie can no longer start the browser:

SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]

De- and reinstalled, tried a previous Sandboxie version, to no avail.

**Comment by isaak654** [comment]
A similar issue is under investigation: #795 
Did you try to turn off hardware acceleration outside of the sandbox, as workaround?

**Comment by oximeter** [comment]
This happens after the Vivaldi  update to Chrome 90. Hardware acceleration is disabled already. Chrome 89 branch works.
Edge is not affected by the Chrome 90 issue, just Vivaldi
See here 
https://www.wilderssecurity.com/threads/sandboxie-plus-0-7.436454/page-10#post-3003603

**Comment by isaak654** [comment]
There are similar reports for Edge, Chrome, Brave updated to v90... the only difference is that disabling hw acceleration doesn't always work (as workaround).

Could you share your graphics card information & driver version installed on your system(s)? This might help the dev.

**Comment by NotepadPlusUser** [comment]
For what it's worth, here are the 12 lines of the error message that Sandboxie-plus 0.7.4 generated this morning when I tried to open Vivaldi 3.8.2259.37 (with Chrome/90.0.4430.95) in the DefaultBox.  There seemed to be problems with Edge 90.0.818.51.  I'm working on a 64-bit desktop with Windows 10 20H2 (19042.928).
 - - - - - - - -
WerFault.exe (15348): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (15348): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
WerFault.exe (4156): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (4156): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
WerFault.exe (12812): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (12812): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
WerFault.exe (22316): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (22316): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
WerFault.exe (15348): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (4156): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (12812): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
WerFault.exe (22316): SBIE2101 Object name not found: Unnamed object, error OpenProcess (C0000022) access=001FFFFF initialized=1
 - - - - - - - -

**Comment by bighippo999** [comment]
I'm getting the same kind of errors but only 7 lines worth.
I did manage to start Vivaldi though:
Right click sandbox> Run Sandboxed > Run Any Program > type (without quotes) "vivaldi.exe --no-sandbox"
Hopefully it works for you too until it's fixed in an update.

**Comment by NotepadPlusUser** [comment]
Thanks @bighippo999.  I have a button to turn _disable_forcing_ on and off quickly, so no worries running Vivaldi unsandboxed.  But it's a great nuisance, as it was a few months ago when a previous change in Chrome similarly caused Vivaldi not to run in Sandboxie.  

Hopefully the next version of Sandboxie-plus will again make the necessary adjustment.

APOLOGIES: I made a typo in my report above.  I meant to type:
_'There seemed to be NO problems with Edge 90.0.818.51.'_ 

I also failed to report that turning hardware acceleration on and off seems to make no difference to these results in either Edge or Vivaldi.

**Comment by isaak654** [comment]
Someone renamed vivaldi.exe to firefox.exe with success as workaround [here](https://www.wilderssecurity.com/threads/released-sandboxie-plus-sbie-fork-versions-with-signed-driver.434924/page-39#post-3004894).

**Comment by Deadite333** [comment]
Thanks, especially for the suggested workarounds.

It's pretty weird, but the firefox-method works well, nice find.

**Comment by FredB750** [comment]
I experienced trouble with all 64 bit chrome v90+ browsers. The 32bit versions seem to run OK.??
Would like to hear if anyone else has found the same to be true?

**Comment by DavidXanatos** [comment]
the issue will be fixed in the next build,
till then you can use this patched SbieDll.dll: https://xanasoft.com/Downloads/SbieDll_5.49.8a.zip
