### ISSUE TITLE
Is there a way to create a shortcut for launching application that was installed in a sandbox?

### ISSUE THREAD

**Issue by nyorf** [sandboxie-plus/Sandboxie#827]
Hi, I don't know where should I be asking this, but I installed Steam into a sandbox, is there a way to create a desktop shortcut so it automatically launches Steam in a certain sandbox with UAC administrator privileges?

**Comment by isaak654** [comment]
Sandbox context menu -> Create shortcut (only in Plus UI) or open Sbiectrl.exe in your Sbie folder -> Configure Menu -> Windows Shell Integration -> Add Shortcut Icons

**Comment by nyorf** [comment]
Thank you, it worked.

**Comment by ZeroMaki** [comment]
is there no way to do this in sandboxie plus  the new ui?

> Sandbox context menu -> Create shortcut (only in Plus UI) or open Sbiectrl.exe in your Sbie folder -> Configure Menu -> Windows Shell Integration -> Add Shortcut Icons

**Comment by nv4** [comment]
> Sandbox context menu -> Create shortcut (only in Plus UI) or open Sbiectrl.exe in your Sbie folder -> Configure Menu -> Windows Shell Integration -> Add Shortcut Icons

What a useless response... This literally does not exist in Sandboxie-Plus (as of v1.0.5 anyway)

**Comment by DavidXanatos** [comment]
Which shortcuts are you referring to?
"Add desktop shurtcut for starting Webbrowser under sandboxie" is now part of the plus installer when instaling this option can be picked
the quick launch option is afaik obsolete, tehre is no quick launch in win 7 or later

If you are refferint go the button "add shurtcut icons" to add more custom shortcuts this option is here:

![grafik](https://user-images.githubusercontent.com/3890945/148675314-f2ee796e-4467-4a1a-bc02-37800b5a8fea.png)

**Comment by ccchan234** [comment]
> Which shortcuts are you referring to? "Add desktop shurtcut for starting Webbrowser under sandboxie" is now part of the plus installer when instaling this option can be picked the quick launch option is afaik obsolete, tehre is no quick launch in win 7 or later
> 
> If you are refferint go the button "add shurtcut icons" to add more custom shortcuts this option is here:
> 
> ![grafik](https://user-images.githubusercontent.com/3890945/148675314-f2ee796e-4467-4a1a-bc02-37800b5a8fea.png)

hi, i think your method would work on applications INSTALLED into the sandbox.

for me, i install chrome outside the sandboxie.

then i have 2 sandbox A and B. i'll run chrome.exe under both sandbox.

i tried your method, i think it wouldnot work.

may i ask any solution for my need? i live in an environment where my chrome browsers have different configs.

thanks
