### ISSUE TITLE
Comodo HIPS doesn't work

### ISSUE THREAD

**Issue by r21N8AeVeov8** [sandboxie-plus/Sandboxie#829]
Sandbox-Plus v0.74 x64
Comodo v12.2.2.8012
![1](https://user-images.githubusercontent.com/80880561/117435574-95cea080-af60-11eb-84fd-e36387aa31f3.jpg)

Comodo dll not injection

**Comment by isaak654** [comment]
Please check if this can help you: https://github.com/sandboxie-plus/Sandboxie/issues/1427#issuecomment-1001273168

If not, please share more details about your problem:
* What is your Windows edition and version? 
* Could you share a direct download link of the incompatible product?
* Could you retest the behavior with Plus v1.0.15 x64?
* Could you provide a detailed description of what you expected to happen?
* Please consider to take one or more logs for Resource Access issues. For instructions, see https://git.io/Jwj2y
