### ISSUE TITLE
5.42, "page_fault_in_nonpaged_area" death screen.

### ISSUE THREAD

**Issue by JulyMorning** [sandboxie-plus/Sandboxie#83]
was working okay on previous version, triggered by palemoon 28.10 (firefox based) browser. profile is stored outside of the sandbox with direct access to that folder, if matters.

upd.
tried to download the previous version of sandboxie plus with chromium (ran in the same sandbox) – got the same bluescreen while downloading.

sandbox config just in case, not well optimized and cute but working for me:

```
[Browsers]


ConfigLevel=7
AutoRecover=y
Template=Firefox_Force
Template=Chrome_Force
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=WindowsFontCache
Template=qWave
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
BorderColor=#00FFFF,off
Enabled=y
BoxNameTitle=-
ForceProcess=palemoon.exe
ForceProcess=updater.exe
ForceProcess=notification_helper.exe
ForceProcess=plugin-hang-ui.exe
ForceProcess=plugin-container.exe
OpenPipePath=S:\moon\
OpenPipePath=%AppData%\Browsers\palemoon\ //WHERE BROWSER INSTALLED
NotifyStartRunAccessDenied=y
OpenFilePath=updater.exe,%AppData%\Browsers\palemoon\
OpenFilePath=S:\moon\ //WHERE PROFILE LOCATED
OpenFilePath=%{374DE290-123F-4565-9164-39C4925E467B}%\ // I GUESS IT'S THE DOWNLOAD FOLDER
OpenFilePath=%{754AC886-DF64-4CBA-86B5-F7FBF4FBCEF5}%\ // OR DESKTOP
OpenFilePath=<ChromePrograms>,%{374DE290-123F-4565-9164-39C4925E467B}%\
OpenFilePath=<ChromePrograms>,%Desktop%\
OpenFilePath=<FirefoxPrograms>,%{374DE290-123F-4565-9164-39C4925E467B}%\
OpenFilePath=<FirefoxPrograms>,%Desktop%\
ProcessGroup=<StartRunAccess>,<FirefoxPrograms>,<ChromePrograms>,dllhost.exe,firefox installer.exe,firefox.exe,RuntimeBroker.exe,ImeBroker.exe,Keygen.exe,eMule0.50a-Installer.exe,xf-adsk2018_x64v3.exe,adesk_patcher64.exe,Setup.exe,setup.tmp,flashplayer31pp_xa_install.exe,palemoon.exe,helper.exe,CompPkgSrv.exe
ProcessGroup=<InternetAccess>,<FirefoxPrograms>,<ChromePrograms>,firefox installer.exe,palemoon.exe
ProcessGroup=<FirefoxPrograms>,firefox installer.exe,plugin-container.exe,plugin-hang-ui.exe,updater.exe
ProcessGroup=<ChromePrograms>,chrome.exe,chrlauncher.exe,notification_helper.exe
NotifyInternetAccessDenied=y
BlockNetworkFiles=y
LeaderProcess=updater.exe
LeaderProcess=chrome.exe
LeaderProcess=firefox.exe
AutoRecoverIgnore=%Desktop%
AutoRecoverIgnore=%{374DE290-123F-4565-9164-39C4925E467B}%
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
ClosedIpcPath=!<StartRunAccess>,*
```

**Comment by DavidXanatos** [comment]
oh... not good... do you have a kernel crash dump?

**Comment by JulyMorning** [comment]
where can I find it?

**Comment by DavidXanatos** [comment]
C:\Windows\minidump

**Comment by JulyMorning** [comment]
I guess, I should install 5.42 again and wait until windows will create a dump (because I force-restarted it). Okay, I can do it.

**Comment by JulyMorning** [comment]
[070420-47406-01.zip](https://github.com/sandboxie-plus/Sandboxie/files/4872981/070420-47406-01.zip)

**Comment by JulyMorning** [comment]
once again, just in case, roaming folder where browser located is the mounted partition. you know, it's possible to mount a partition as a folder. I found it useful long time ago to store roaming separated in case of reinstalling the system. anyway, I guess it's not related.

**Comment by DavidXanatos** [comment]
[SbieDrv.zip](https://github.com/sandboxie-plus/Sandboxie/files/4872986/SbieDrv.zip)

try this driver in sbieplus use option stopp all in the ui, then delete SbieDrv.sys.rc4 and SbieDrv.sys from the app directory and extract the zip into it than use the connect option to load the new driver. 
tell me if that fixes the issue, and if not and you get a new ump send it to me please

**Comment by JulyMorning** [comment]
great, the problem is cured now) thanks for what you do.

**Comment by DavidXanatos** [comment]
I write the new config value names always in the changelog but i chould start a proepr documentation i guess...

**Comment by DavidXanatos** [comment]
[SbieDrv.zip](https://github.com/sandboxie-plus/Sandboxie/files/4873056/SbieDrv.zip)

could you please test if this also works fine?

**Comment by JulyMorning** [comment]
will check it tomorrow.

**Comment by JulyMorning** [comment]
forgot about it. still relevant?

**Comment by DavidXanatos** [comment]
would be good to know yes
