### ISSUE TITLE
How to prevent sandbox applications from detecting any host processes?

### ISSUE THREAD

**Issue by nyorf** [sandboxie-plus/Sandboxie#830]
Hi, is there a way to prevent applications running in a sandbox from viewing my host machine's processes? I know that i can exclude hose processes by name, but is there a way to hide all host processes from a sandbox?

**Comment by Dyras** [comment]
Does it work if you put a "*" as an excluded process?

**Comment by nyorf** [comment]
It doesn't, still detects everything

**Comment by macruspareto** [comment]
I can confirm, the * wildcard is not working.
I tried * alone, *process.exe, *.exe, *.*
Nope.

Ended up adding all known host processes one by one.
Can this get fixed?

**Comment by DavidXanatos** [comment]
this is not a bug, its intended to be a simple list only, why would you want to hide all host prcesses instead of only some selected once?
