### ISSUE TITLE
Sandboxie Classic 5.49.7 = 'CRITICAL_PROCESS_DIED' BSOD

### ISSUE THREAD

**Issue by bytos** [sandboxie-plus/Sandboxie#831]
Windows 10 LTSC 2019 (fresh install) crashes with BSOD when running latest Firefox ESR (78.10.1) on default sandbox. Same for portable Chrome 87.0.4280.88.

Sending the executables to the default sandbox causes the crash (BSOD).

I uninstalled the latest version of Sandboxie (5.49.7) and installed the previous version (5.48.5) and is not crashing anymore.

**Comment by DavidXanatos** [comment]
can you provide additional informations like the crash dump

**Comment by DavidXanatos** [comment]
is this also a 32 bit system?

**Comment by bytos** [comment]
64-bit OS

I moved to version 5.48.5 and haven't had any issues.

Could try again and check for the crash dump.

**Comment by DavidXanatos** [comment]
if it works now that i think the issue can be closed

**Comment by bytos** [comment]
The old version 5.48.5 is working, something happened with the code of version 5.49.x that causes the crashes.

**Comment by DavidXanatos** [comment]
ah.... so the  latest one does not work for you?

**Comment by DavidXanatos** [comment]
could you pelase test which version exactly broke it if the latest is still not fixed, so
5.48.5 ... ok
5.49.0 ... ???
5.49.5 ... ???
5.49.7 ... fail

**Comment by bytos** [comment]
Will check. Can I just install versions in any order, then go back to 5.48.5?

**Comment by DavidXanatos** [comment]
mostly yes you may get some template errors but thats fine

**Comment by bytos** [comment]
Installed Sandboxie Classic 5.50.8 and is not causing a BSOD like 5.49.7 did.
