### ISSUE TITLE
Battle.net installed in a sandbox somehow detects my host install even though i "isolated" it

### ISSUE THREAD

**Issue by nyorf** [sandboxie-plus/Sandboxie#833]
Hi everyone, i'm still trying to setup some some gaming stuff in a sandbox for a multiseat project, and even though i got Steam working flawlessly with sandboxie's own separate library, battle.net is somehow smarter than me and it detects my host installation. So, for example, when i'm trying to install a game in a sandboxie's version on battle.net, my host installation somehow picks it up and showing the same progress bar, thinking that the game is being installed to the host too. And after download is complete, host still thinks that it also got the game, but it only starts up in a sandbox (well, obviously because host pc doesn't have the game installed in its location)

How can i prevent that? I've hidden every folder that battle.net launcher creates, every process that battle.net has and even every registry entry that battle.net has. What else should i do? 

Thanks in advance.

**Comment by DavidXanatos** [comment]
what compatybility templates do you have active?
did you open any WinClasses?

**Comment by DavidXanatos** [comment]
no feadbeck -> issue closed
