### ISSUE TITLE
Sanboxies crashed on Win8.1 x86 when i try to run a program in box

### ISSUE THREAD

**Issue by MCSE-2000** [sandboxie-plus/Sandboxie#834]
Sanboxies crashed on Win8.1 x86 when i try to run a program in box.
QSbieAPI.dll makes an error-code 0xc0000409
I use sandboxies-plus 0.74 on Windows 8.1 Enterprise - Testversion X86-based PC Version 6.3.9600.

This is the message in application event:
Protokollname: Application
Quelle:        Application Error
Datum:         12.05.2021 09:40:03
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      WIN8VHD
Beschreibung:
Name der fehlerhaften Anwendung: SandMan.exe, Version: 0.7.4.0, Zeitstempel: 0x6072fcba
Name des fehlerhaften Moduls: QSbieAPI.dll, Version: 0.7.4.0, Zeitstempel: 0x6072fca0
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0001cf52
ID des fehlerhaften Prozesses: 0xd6c
Startzeit der fehlerhaften Anwendung: 0x01d74701fa66a583
Pfad der fehlerhaften Anwendung: C:\Program Files\Sandboxie-Plus\SandMan.exe
Pfad des fehlerhaften Moduls: C:\Program Files\Sandboxie-Plus\QSbieAPI.dll
Berichtskennung: 431cce3a-b2f5-11eb-9762-0022431d12a8
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-12T07:40:03.000000000Z" />
    <EventRecordID>3859</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WIN8VHD</Computer>
    <Security />
  </System>
  <EventData>
    <Data>SandMan.exe</Data>
    <Data>0.7.4.0</Data>
    <Data>6072fcba</Data>
    <Data>QSbieAPI.dll</Data>
    <Data>0.7.4.0</Data>
    <Data>6072fca0</Data>
    <Data>c0000409</Data>
    <Data>0001cf52</Data>
    <Data>d6c</Data>
    <Data>01d74701fa66a583</Data>
    <Data>C:\Program Files\Sandboxie-Plus\SandMan.exe</Data>
    <Data>C:\Program Files\Sandboxie-Plus\QSbieAPI.dll</Data>
    <Data>431cce3a-b2f5-11eb-9762-0022431d12a8</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by DavidXanatos** [comment]
seams there is somethign wrong with the 32 bit version as you also reported a bsod: https://github.com/sandboxie-plus/Sandboxie/issues/838

a'll close this issue and lets discuss all the 32 bit issues in the BSOD thread

I almost dont test the 32 bit versions as imho only ver  fre people are using those,
I'll set up a 8.1 32 bit VM and test the latest build in detail
