### ISSUE TITLE
Processes which run automatically on startup do not controlled by Sandboxie-Plus

### ISSUE THREAD

**Issue by MikeMirzayanov** [sandboxie-plus/Sandboxie#835]
I added `ForceProcess=test1.exe` into `[DefaultBox]`. If I run this process from the command line everything works great. But if this process is started automatically via Windows scheduled tasks (on reboot) or via any other way to start it on boot (like started from a service), it is not controlled by Sandboxie-Plus.

**Comment by eneerge** [comment]
As a workaround, you could try using Start.exe to launch the file instead of relying on the ForceProcess configuration.
https://sandboxie-website-archive.github.io/www.sandboxie.com/StartCommandLine.html

**Comment by DavidXanatos** [comment]
mmh... sandboxie will not force processes if they are started with a system token, 
so you will need to ind an otehr way of starting it atboot like the mentioned start.exe
