### ISSUE TITLE
often using sandboxes the mouse does not respond correctly

### ISSUE THREAD

**Issue by gederico76** [sandboxie-plus/Sandboxie#837]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2).
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2).
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**Additional context**

**Sandboxie configuration**
If applicable, consider to attach your sandboxie.ini configuration by copying the content at https://gist.github.com and sharing the resulting link here. If you decide to paste the configuration directly here, make sure to use the backticks around strings, like in this working example:

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]

.....

[UserSettings_175D0429]

.....

[DefaultBox]

.....

```

</details>

**Comment by lahma0** [comment]
Uhh.. Copying/pasting the issue report template without changing anything probably isn't going to be too helpful for anyone..
