### ISSUE TITLE
BSOD with sandboxies-plus 0.74 when i click on Options -> Software Compatibility

### ISSUE THREAD

**Issue by MCSE-2000** [sandboxie-plus/Sandboxie#838]
Sandboxies-plus 0.74 makes a BSOD when i click Options -> Global Settings -> Software Compatibility

I use sandboxies-plus 0.74 on Windows 8.1 Enterprise - Testversion X86-based PC Version 6.3.9600.

Bluescreenviewer show me this:
==================================================
Dump-Datei        : 051621-9000-01.dmp
Absturzzeit       : 16.05.2021 10:10:57
Fehlerprüfstring  : DRIVER_CORRUPTED_MMPOOL
Fehlerprüfcode    : 0x000000d0
Parameter 1       : 0x786f6273
Parameter 2       : 0x00000006
Parameter 3       : 0x00000000
Parameter 4       : 0x00000000
Verursachender Treiber: SbieDrv.sys
Verursachende Adresse: SbieDrv.sys+bf03
Dateibeschreibung : 
Produktname       : 
Hersteller        : 
Dateiversion      : 
Prozessor         : 32-Bit
Absturzadresse    : ntoskrnl.exe+e2d58
Stapeladresse 1   : SbieDrv.sys+be8f
Stapeladresse 2   : SbieDrv.sys+2292
Stapeladresse 3   : SbieDrv.sys+2952
Computername      : 
Pfad              : C:\Windows\Minidump\051621-9000-01.dmp
CPUs              : 2
Hauptversion      : 15
Nebenversion      : 9600
Dump-Dateigröße   : 149.720
Dump-Dateizeit    : 16.05.2021 10:11:54
==================================================

Message from BSOD:
--------------------------------------------------------------------------------------------------------------
A problem has been detected and Windows has been shut down to prevent damage
to your computer.

The problem seems to be caused by the following file: SbieDrv.sys

DRIVER_CORRUPTED_MMPOOL

If this is the first time you've seen this stop error screen,
restart your computer. If this screen appears again, follow
these steps:

Check to make sure any new hardware or software is properly installed.
If this is a new installation, ask your hardware or software manufacturer
for any Windows updates you might need.

If problems continue, disable or remove any newly installed hardware
or software. Disable BIOS memory options such as caching or shadowing.
If you need to use safe mode to remove or disable components, restart
your computer, press F8 to select Advanced Startup Options, and then
select Safe Mode.

Technical Information:

*** STOP: 0x000000d0 (0x786f6273, 0x00000006, 0x00000000, 0x00000000)

*** SbieDrv.sys - Address 0x8b9c2f03 base at 0x8b9b7000 DateStamp 0x605f5fc3
--------------------------------------------------------------------------------------------------------------

**Comment by DavidXanatos** [comment]
could you please provide the kernel dump?

Also can you test older versions which one introduced this problem

**Comment by MCSE-2000** [comment]
Version 0.03 + 0.35 works only in portable mode, the installer says "KmdUtil ControlServiceStart: The system cannot find the specified path. (3)". Failed to install SbieDrc.sys driver. and Sandbox depends.
V0.40 - 0.41 ... 0.45 and 0.50 I can install and i can start programs in the sandbox but when I press in "options -> Global Settings -> Button OK" the sandbox hangs, in V0.44 I got a bluescreen.
