### ISSUE TITLE
KmdUtil failed

### ISSUE THREAD

**Issue by Dark-Magician** [sandboxie-plus/Sandboxie#84]
Sandboxie-Plus v5.42, 64-bit

During the installation process:

"ControlService Start: The system cannot find the file specified. (2)"

and then

"*** KmdUtil failed. Installation or un-installation may not complete successfully. ***

C:\Users\. . .\AppData\Local\Temp\nsg9E6.tmp\KmdUtil.exe start SbieSvc"

-

Also:

Sandboxie-Plus v0.3, 64-bit

In SandMan.exe GUI:

"Failed to communicate with Sandboxie Service: Error Code: - 1073741772

-

OS: Win 8.1, 64-bit

-

Note: I tried versions 5.41.2 and 0.2.2, and the same things occurred.

**Comment by CrendKing** [comment]
I noticed that the SbieDrv driver was installed with path like `"C:\SbiePlus\SbieDrv.sys"` (notice the quotes). However, the Sandboxie installer installs with path as `\??\C:\SbiePlus\SbieDrv.sys`. Once I change the path, I can start SandMan.exe without problem.

**Comment by DavidXanatos** [comment]
Yes that's correct and normally KmdUtil.exe should have added the correct prefix automatically.
I'll test it if i can reproduce the issue.

**Comment by Dark-Magician** [comment]
After a few more tries, I was able to install Sandboxie Plus. I did not make any changes to my system; I just reinstalled the program until the installation succeeded. It is working now, but I suspect the problem may occur again during future installations. Although Sandboxie Plus is working now, Sandboxie Control displays "KmdUtil failed - issue #84" next to the vivaldi.exe process under "Window Title."

-

The SandMan GUI stopped displaying the aforementioned error code after it unpacked the driver and I restarted the program a few times.

**Comment by deflock** [comment]
Can confirm. Something strange with `kmdutil`. I've uninstalled Sandboxie 5.33 completely. Then trying to run portable SandMan latest. It runs: 
`kmdutil.exe  install SbieDrv \"D:\programs\Sandboxie\App\SbieDrv.sys\" type=kernel start=demand altitude=86900`
Then I get:
`ControlService Start: The filename, directory name, or volume label syntax is incorrect. (123)`

**Comment by CrendKing** [comment]
Also, notice that `"Sandboxie Service"` service name. There shouldn't be a pair of quotes in a service name. I think the bug is due to the escaped quote `\"`.

**Comment by deflock** [comment]
I can't make it work in portable sandman. Now just have installed it as usual and using SbieCtrl

**Comment by typpos** [comment]
Same problem: Unable to get Sandman working.

* Windows 10.0.18363
* Start "Windows Sandbox" (sic!)
* Inside "Windows Sandbox" run "Sandman.exe"  from SbiePlus64-v0.3.zip
* App shows "..was started in portable mode and it needs to create nececery services.."
* Click OK
* Error message "KmdUtil" "ControlService Start: The filename, directory name, or volume label syntax is incorrect. (123)"
* Sandman runs and shows icon in taskbar
* Unable to open or close Sandman other than kill in Task Manager
* Windows Services shows new service named with quotes:  "Sandboxie Service" with path to SbieSvc.exe

Side notes:
* I can use default windows command "SC" to create/delete services. Unclear why "kmdutil.exe" is needed
* Cosmetic spelling error in sandman dialog - see dot point 4 above
* When starting Sandman, I can press "Cancel" on the dialog (dot point 4 above) and get to the Sandbox main screen. Should this be possible at all? When I try to create a sandbox, Sandman hangs.
* Release version is 0.3, but Sandman.exe version (Windows Explorer > Properties > Details) says version is 1.0.0.1.

**Comment by 0m3rta13** [comment]
> Same problem: Unable to get Sandman working.
> 
> * Windows 10.0.18363
> * Start "Windows Sandbox" (sic!)
> * Inside "Windows Sandbox" run "Sandman.exe"  from SbiePlus64-v0.3.zip
> * App shows "..was started in portable mode and it needs to create nececery services.."
> * Click OK
> * Error message "KmdUtil" "ControlService Start: The filename, directory name, or volume label syntax is incorrect. (123)"
> * Sandman runs and shows icon in taskbar
> * Unable to open or close Sandman other than kill in Task Manager
> * Windows Services shows new service named with quotes:  "Sandboxie Service" with path to SbieSvc.exe
> 
> Side notes:
> 
> * I can use default windows command "SC" to create/delete services. Unclear why "kmdutil.exe" is needed
> * Cosmetic spelling error in sandman dialog - see dot point 4 above
> * When starting Sandman, I can press "Cancel" on the dialog (dot point 4 above) and get to the Sandbox main screen. Should this be possible at all? When I try to create a sandbox, Sandman hangs.
> * Release version is 0.3, but Sandman.exe version (Windows Explorer > Properties > Details) says version is [1.0.0.1](http://1.0.0.1).

You ever get this working?
Am having similar (and one or two extra) issues

**Comment by typpos** [comment]
@0m3rta13 
No. Currently using 5.33.1 for "production use" and waiting for SB+ to sort itself out.

**Comment by 0m3rta13** [comment]
> @0m3rta13 
> 
> No. Currently using 5.33.1 for "production use" and waiting for SB+ to sort itself out.

Damn. 
Can't get that working on insider either. Gives more errors than SB+

Thanks for the response though!

**Comment by DavidXanatos** [comment]
The latest build runs fine with 20h2 so I'll clsoe that here
