### ISSUE TITLE
FakeAdminRights not working in some case

### ISSUE THREAD

**Issue by akizuha** [sandboxie-plus/Sandboxie#842]
**Describe the bug**
FakeAdminRights not working in some case. Even when these programs do not need admin rights out of the sandbox.

**To Reproduce**

_this is just an example, many other programs behaviour the same_
1. get grapholite(https://grapholite.com/) installed (https://grapholite.com/Download/Grapholite.msi)
2. this app will not open without admin rights in the sandbox
------work around-------
3. using Resource Hacker (http://www.angusj.com/resourcehacker/) to open the exe
4. select `manifest 1:0` and remove `<requestedPrivileges>` block, and save.
5. now this app opens in sandbox without admin rights or FakeAdminRights.

Hope sandboxie-plus can deal with this manifest thing automatically. Also some programs do self check, so modify the exe is not that easy.

**Comment by DavidXanatos** [comment]
I can not reproduce this, the app opens just fien and does not seam to requrie any admin rights.
please chekc if the issie is fixed in the last build or provide a updated guide how to reproduce teh issue
