### ISSUE TITLE
Your old forum is gone, the new one will not let me register. Access Protected Memory 

### ISSUE THREAD

**Issue by sockelganger** [sandboxie-plus/Sandboxie#846]
Sorry to write this here, but https://forum.xanasoft.com/viewforum.php?f=4 simply doesn't work. When I request an account to be created I never get the email with the key to confirm who I am.
I've a question for the forum, if I were to mount an application in SandBoxie, would I be able to access would I be able to use this application to access and view what would normally be the protected memory of the process?

**Comment by DavidXanatos** [comment]
not sure why it fails anyhow i disabled the email requirement...

if you run an application in sandboxie or outside you can use tools like taskexplorer to view the memory of the process
