### ISSUE TITLE
Google Safe Browsing marked Sandboxie releases as harmful

### ISSUE THREAD

**Issue by Erquint** [sandboxie-plus/Sandboxie#847]
When navigating to https://github.com/sandboxie-plus/Sandboxie/releases
![](https://i.imgur.com/W5OeJ1D.png)
Google's report here:
https://transparencyreport.google.com/safe-browsing/search?url=https://github.com/sandboxie-plus/Sandboxie/releases&hl=en-US

If it's a false positive, please sort it out with Google.

**Comment by isaak654** [comment]
If you want, you can still submit the URL that you would like to whitelist in this Google form:
https://support.google.com/websearch/contact/safe_browsing

I've just did it, but more reports might help.

**Comment by DavidXanatos** [comment]
seams fixed: https://www.virustotal.com/gui/url/0198d25daa5841c0d608e9034fe20a51a08d53337165c5735f8ca053baeecadc/detection

**Comment by isaak654** [comment]
I can still reproduce the warning, despite Virustotal whitelisted the URL.

**Comment by isaak654** [comment]
Please use this issue if you discover something new or if you have further questions.

**Comment by isaak654** [comment]
Second post updated with another workaround.

As always, please use this issue if you discover something new or if you have further questions.

**Comment by isaak654** [comment]
This is now fixed on both VirusTotal and Google!

Apparently this pull request made the difference: https://github.com/sandboxie-plus/Sandboxie/pull/1037

**Comment by Erquint** [comment]
Glad it's been resolved and my gratitude to @isaak654 for a recap.
