### ISSUE TITLE
Add auto recovery

### ISSUE THREAD

**Issue by NebelNidas** [sandboxie-plus/Sandboxie#848]
If you want to recover files as soon as they are created, you currently only have the option to check `Enable Immediate Recovery prompt to be able to recover files as soon as they are created`:
![image](https://user-images.githubusercontent.com/48808497/119110609-a3852b00-ba22-11eb-80e1-0718d190bfe6.png)

 I would like an option to bypass this message completely and just recover things automatically without user interaction.

**Comment by Coverlin** [comment]
> If you want to recover files as soon as they are created, you currently only have the option to check `Enable Immediate Recovery prompt to be able to recover files as soon as they are created`:
> ![image](https://user-images.githubusercontent.com/48808497/119110609-a3852b00-ba22-11eb-80e1-0718d190bfe6.png)
> 
> I would like an option to bypass this message completely and just recover things automatically without user interaction.

If you want to "recover" the files immediately without review , setup resource access for the almost the same effect
If you want to "silently" recover the files at the end of the sandbox session you have a feature request

**Comment by DavidXanatos** [comment]
> If you want to "recover" the files immediately without review , setup resource access for the almost the same effect
> If you want to "silently" recover the files at the end of the sandbox session you have a feature request
> 

yes so which of the two is it?

I would think that for your use casee setting up direct access is best.

**Comment by NebelNidas** [comment]
Oops, sorry for the late response, I must have missed the notification for @Coverlin's response. Resource Access is exactly what I need, thank you for the help!
