### ISSUE TITLE
SandMan feature parity

### ISSUE THREAD

**Issue by CrendKing** [sandboxie-plus/Sandboxie#85]
What is the plan for SandMan? Is it supposed to be improved to eventually replace the old Sandboxie GUI and Start.exe? If so, I think SandMan currently still lack some features to make the parity.

- Start minimized.
- Run sandboxed programs from command line with SandMan instead of Start.
- Terminate programs in a sandbox from command line.
- Delete sandbox content from command line.
- Change system tray icon to indicate there are sandboxed programs running. This is important because some programs take long time to create their main window. Or due to compatibility issue programs might terminate without any error dialog. User needs to know what's happening.
- Provide GUI configuration for a sandbox (such as border color).

**Comment by CrendKing** [comment]
Also, the SandMan.exe process has a thread that's constantly consuming CPU (miniscule but nonetheless). I don't have any monitoring enabled. A bug?

![Screenshot](https://user-images.githubusercontent.com/975235/86525625-6df14680-be3e-11ea-95de-f43fbcd61e40.jpg)

**Comment by DavidXanatos** [comment]
> 
> 
> What is the plan for SandMan? Is it supposed to be improved to eventually replace the old Sandboxie GUI and Start.exe? If so, I think SandMan currently still lack some features to make the parity.
> 

It is supposed to replace SbieCtrl.exe but at least on the short run not the start.exe

>     * Start minimized.

will be added and auto start as well...

>     * Terminate programs in a sandbox from command line.

I'll add that to my todo

>     * Delete sandbox content from command line.

That is done using start.exe so as long as we keep start.exe sandman does not have to do that

> 
>     * Change system tray icon to indicate there are sandboxed programs running. This is important because some programs take long time to create their main window. Or due to compatibility issue programs might terminate without any error dialog. User needs to know what's happening.
> 

That is already so just the change is very minimal the sand in the sandbox goes from gray to yellow, I should may be make it more prominent of a change.

>     * Provide GUI configuration for a sandbox (such as border color).

Yes I know its on my todo


> Also, the SandMan.exe process has a thread that's constantly consuming CPU (miniscule but nonetheless). I don't have any monitoring enabled. A bug?
> 

I'll look into optimizing the CPU usage further but Qt and large lists/trees is a bit hard on the CPU, it was a loot of work to get it to a usable stat in Task Explorere.

**Comment by CrendKing** [comment]
> That is already so just the change is very minimal

Now you mentioned it, it is already there! That's a evasive one. At least make the purple color change or something like the old systray does please.

> I'll look into optimizing the CPU usage further but Qt and large lists/trees is a bit hard on the CPU, it was a loot of work to get it to a usable stat in Task Explorere.

The CPU usage is there even the main window of SandMan is closed. The only thing is the systray. So shouldn't be a Qt thing right? I could compile SandMan myself and debug a bit once I got time.

BTW, I was using Process Hacker, not Task Explorer. I think your Task Explorer is a prominent tool, but not yet fully comparable to the Hacker in terms of usability and feature parity. Keep working on it!

**Comment by DavidXanatos** [comment]
> 
> BTW, I was using Process Hacker, not Task Explorer. I think your Task Explorer is a prominent tool, but not yet fully comparable to the Hacker in terms of usability and feature parity. Keep working on it!

What features are you missing?

**Comment by CrendKing** [comment]
Just list a few that came first into mind (order != importance or priority):

- Find window (and thread) picker
- Option to change font and grid appearance
- Collapse certain process tree by name
- Once find the processes that contains a module, go to the process or close the handle
- Hide drivers in Services tab
- Direct button or MDI to access Services and other useful System Info tabs
