### ISSUE TITLE
cannot navigate to nas from firefoxportable within sandbox

### ISSUE THREAD

**Issue by darchon7** [sandboxie-plus/Sandboxie#851]
**Describe the bug**
within firefox inside a sandbox, when i navigate to my nas (eg when attempting to attach a file), i get prompted for a password and constantly get Access Denied and an error message SBIE2205:  Service not implemented: NetUseAdd

**To Reproduce**
1. Start firefoxportable inside a sandbox
2. File Open, navigate to nas
3. Password is prompted. enter password. Access is denied.
4. Sandboxie notification error window appears with message SBIE2205:  Service not implemented: NetUseAdd

**Expected behavior**
Able to access nas and see files. Running in an unsandboxed browser has no issues.

**Screenshots**

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? Windows 10 Pro 20H2 64bit
 - What is your current Sandboxie edition and version? Sandboxie Plus 0.7.2
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Sandboxie Plus 0.7.2
 - Please mention any security software running in the background, even if the real-time protection is disabled.
 - Bitdefender Antivirus

**Additional context**

**Sandboxie configuration**
If applicable, consider to attach your sandboxie.ini configuration by copying the content at https://gist.github.com and sharing the resulting link here. If you decide to paste the configuration directly here, make sure to use the backticks around strings, like in this working example:

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 

[GlobalSettings]

Template=WindowsRasMan
Template=BitDefenderInternetSecurity
Template=7zipShellEx
Template=Listary
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=RoboForm
FileRootPath=d:\Sandbox\%USER%\%SANDBOX%
KnownConflicts=BitDefender

[DefaultBox]

ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
RecoverFolder=d:\Program Files
RecoverFolder=F:\Downloads
BorderColor=#00FFFF,ttl,6
Enabled=y
OpenFilePath=<firefoxprograms>,D:\Program Files\
OpenFilePath=firefoxportable.exe,D:\Program Files\
OpenFilePath=firefox.exe,D:\Program Files\
OpenFilePath=<firefoxprograms>,F:\Downloads\
OpenFilePath=<firefoxprograms>,D:\Program Files\
OpenFilePath=robotaskbaricon.exe,%Personal%\My RoboForm Data\
OpenFilePath=robotaskbaricon.exe,C:\Program Files (x86)\Siber Systems\AI RoboForm\
OpenFilePath=qbittorrent.exe,%AppData%\qBittorrent\
OpenFilePath=qbittorrent.exe,%Local AppData%\qBittorrent\
OpenFilePath=qbittorrent.exe,H:\
OpenFilePath=operaportable.exe,D:\Program Files\
OpenFilePath=opera.exe,D:\Program Files\
OpenFilePath=chrome.exe,D:\Program Files\
OpenFilePath=googlechromeportable.exe,D:\Program Files\
OpenPipePath=qbittorrent.exe,%{374DE290-123F-4565-9164-39C4925E467B}%\
ClosedFilePath=*BitDefender*atcuf*.dll
WriteFilePath=C:\Program Files\Bitdefender\*
OpenWinClass=#

[UserSettings_11C20289]

SbieCtrl_UserName=dwayne
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1614796928
SbieCtrl_WindowCoords=200,150,909,596
SbieCtrl_ActiveView=40021
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_AutoStartAgent=SandMan.exe

</details>

**Comment by eneerge** [comment]
I have ran into the access is denied when trying to access network locations. By default, Sandboxie restricts access to network files. To disable this restriction, you can uncheck "Block network files and folders, unless specifically opened" from the General Options->Box Options tab in the Sandbox Options. Maybe this is your issue.

**Comment by DavidXanatos** [comment]
does eneerge's sugestion help?

**Comment by darchon7** [comment]
yup that fixed it! tx eneerge!!
