### ISSUE TITLE
Brave v1.24 failing with Aw , Snap! STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Shadowized** [sandboxie-plus/Sandboxie#852]
**Describe the bug**
Updated my Brave Install and upon launching it inside of a sandbox it now shows Aw, Snap! with error code STATUS_ACCESS_VIOLATION

**To Reproduce**
1. Install Latest Brave browser 64-bit
2. Run Sandboxed with default config (didn't change anything in Sandboxie, just installed and ran both)
3. it does the above mentioned error on all tabs and refuses to work unless I launch it with --no-sandbox flag
4. interestingly enough, the 32-bit version works fine, as did the 32 and 64bit version of Chrome 91 that I tried which is odd.

**Expected behavior**
I expect it to work fine just as it did with the previous versions of the browser, the last release version I tried without this issue was **[v1.22.72](https://github.com/brave/brave-browser/releases/tag/v1.22.72)**

**Screenshots**
![image](https://user-images.githubusercontent.com/5408749/119685963-dad54c80-be13-11eb-90ba-9b66d95821f0.png)

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? **Win10 1909** + **Win10 2004**
 - What is your current Sandboxie edition and version? **Sandboxie Plus 0.7.4**
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. **N/A**
 - Please mention any security software running in the background, even if the real-time protection is disabled. **N/A**

**Additional context**
I tried it on my Desktop and in a couple of VM's, its failing in 2 out of 3, and I can't replicate why in one VM it works fine but another it crashes harder than even on my desktop with werFault, object not found, etc

**Comment by Shadowized** [comment]
It appears that Vivaldi also has the same problem as Brave, I suppose it must be something to do with the Chromium v90 upgrades that came with later versions, because Brave 1.22.76 Release is built on Chromium v89 and works fine.

**Comment by NewKidOnTheBlock** [comment]
Can confirm for Brave Portable 1.24.84-73

**Comment by SINE** [comment]
Same issue.

Windows x64 20H2 19042.631
Sandboxie-Plus 0.7.4
Brave Beta v1.26.52

**Comment by isaak654** [comment]
Release v0.7.5 / 5.49.8 is out, please confirm whether the issue is fixed or not.

**Comment by Shadowized** [comment]
Seems to be working fine now 👍

**Comment by SINE** [comment]
Fixed!
