### ISSUE TITLE
system sound volume is changeable

### ISSUE THREAD

**Issue by norelmas** [sandboxie-plus/Sandboxie#853]
C:\Windows\System32\SndVol.exe can change the volume in win10 21H1.

**Comment by norelmas** [comment]
https://www.pcmag.com/news/malware-steals-data-by-adjusting-screen-brightness , is it possible to adjust screen brightness in sandbox?

**Comment by DavidXanatos** [comment]
Well yes, is that bad?
If you want to prevent this add CloseIpcPath=\RPC Control\AudioClientRpc
to your sandboxie ini but than you will have no sound at all in the sandbox
But given your thread model that would be better anyways.
I mean on an airgapped machien some one could also exfiltrate data through some noice generated through teh speakers
