### ISSUE TITLE
Change MAC address inside the box

### ISSUE THREAD

**Issue by macruspareto** [sandboxie-plus/Sandboxie#855]
I'm trying to change the mac address (inside the box) to make one shady application working.

Locally administered MAC addresses are stored in HKLM\System\ControlSet\blahblah\NetworkAddress however if I run regedit inside the box, the UAC asks me for direct access to the registry. Otherwise it would say:

"SBIE2217 Request to run as Administrator was denied due to dropped rights"

My box is set to "Emulate Admin Rights" and I thought that all HKLM operations are fully virtualized.

Any chance to do that?

**Comment by DavidXanatos** [comment]
"Emulate Admin Rights" is still experimental and does not cover all possble cases,
disable ebulat and grant the regedit proper admin rights in sie the sadbox, despide having admin rights it can only alter sanboxed locations so its safe enough

**Comment by DavidXanatos** [comment]
i think i can close this now
