### ISSUE TITLE
Add whitelist principle instead of only blacklist

### ISSUE THREAD

**Issue by Pr0mises** [sandboxie-plus/Sandboxie#859]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I add new programs to the main host and have to block read access to that folder. E.x I'm using Discord and Discord scans all files and directories a Host has (yes, every drive)

**Describe the solution you'd like**
Give us the option to make a whitelist instead of a blacklist of files/directories and processes

**Describe alternatives you've considered**
Don't think there is an alternative

**Additional context**
The solution would help to isolate programs even better, also would fix this issue: #830

**Comment by isaak654** [comment]
Full list of related issues (for record-keeping purposes):
#194 
#398
#673
#689
#699
#830

**Comment by DavidXanatos** [comment]
I know and that's on my todo since a longtime but its not so easy to implement properly.

**Comment by isaak654** [comment]
Update: please post on the new issue #890, thanks.
