### ISSUE TITLE
LogAPI?

### ISSUE THREAD

**Issue by gjf** [sandboxie-plus/Sandboxie#86]
Latest SandboxiePlus release includes logapi folder and it includes newer versions of dlls (both x64 and x32).
Although "verbose" versions are not included and sources of newer version are also cannot be found.
Is it possible to share them also?

**Comment by DavidXanatos** [comment]
The dll's are the verbose edition, the sources can be found at: https://github.com/sandboxie-plus/LogApiDll

**Comment by gjf** [comment]
OK just surprised that sources mostly were made a month ago :)

**Comment by DavidXanatos** [comment]
There are only very minor changes I added a few more functions to hook. actually much more are missing but adding them manually is a lot of work.
Ideally I would need something to parse standard MSFT include headers and auto generate all the individual hook and log routines.
Its doable I did some parsing and script translation work in the past but its not super high priority and also a lot of work.
