### ISSUE TITLE
Question. Microsoft Teams save credentials

### ISSUE THREAD

**Issue by stasonchickk** [sandboxie-plus/Sandboxie#862]
Trying to use microsoft teams with different accounts. I have created several sandboxes for this. I can login with different accounts in each sandbox but  sandbox not remember credentials for the next sessions. I think it could be solved by templates, who can help with this thing?

**Comment by isaak654** [comment]
See [OpenCredentials](https://sandboxie-plus.github.io/sandboxie-docs/Content/OpenCredentials.html) documentation.
