### ISSUE TITLE
[Request] Upload Inno Setup files into this repository

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#863]
As you can see [here](https://github.com/sandboxie-plus/Sandboxie/search?l=nsis) and [here](https://github.com/sandboxie-plus/Sandboxie/tree/master/Sandboxie/install), all NSIS installer scripts + a readme file for Sandboxie Classic are stored in the `Sandboxie/install` folder of this repository. 
So why not include all Inno Setup files with a readme file on a separate Plus directory like `SandboxiePlus/install`?

**Comment by DavidXanatos** [comment]
file is here: https://github.com/sandboxie-plus/Sandboxie/blob/master/Installer/Sandboxie-Plus.iss
no time to write a readme though
