### ISSUE TITLE
The Quick Recovery settings should mention Immediate Recovery

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#864]
**Describe the bug**
The Quick Recovery settings state:
> Before the contents of the sandbox are deleted, or when you manually invoke the Quick Recovery function, the following folders will be checked for sandboxed content.

**To Reproduce**
1. Enter a sandbox' settings
2. Click **Recovery**
2. Click **Quick Recovery**

**Expected behavior**
The Quick Recovery settings should also add:
> **_When Automatic Recovery is used_**, before the contents of the sandbox are deleted, or when you manually invoke the Quick Recovery function or, the following folders will be checked for sandboxed content.

**Additional context**
Since **Automatic Recovery** is enabled by default, it might be the most used situation for **Quick Recovery**, so it would be helpful to clarify it.

**Comment by Coverlin** [comment]
invalid based on the latest release (5.49.7)

The classic UI settings are clear enough as they are

Quick rec : `Before the contents of the sandbox are deleted or when you manually invoke the Quick
Recovery function the following folders will be checked for sandboxed content. If any
mes are found you will get a chance to easily recover them out of the sandbox`

Immediate rec(AutoRecover) : `Immediate Recovery enhances Quick Recovery by automatically invoking the recovery
function as soon as files are created`

The setting `AutoRecover=y` is not default in this version neighter for defaultbox or new boxes and will most likely stay like that in future versions (fresh config created by sandboxie)

**Comment by lwcorp** [comment]
I don't see the big different from my quote. Unless they're in the same screen, my point is that Immediate Recovery should be mentioned in Quick Recovery, not just vice versa.

Why is it off by default? It might confuse most users.

**Comment by DavidXanatos** [comment]
in the plus ui all recovery options are on teh same screen
