### ISSUE TITLE
Quick Recovery doesn't offer to overwrite files

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#865]
**Describe the bug**
If you download a file which name already exists in one of the Quick Recovery folders, choose (inside the sandbox) to overwrite it, and agree to recover it anyway, Sandboxie will automatically rename it (e.g. "same-file.exe (1)").

**To Reproduce**
1. Download a file which name already exists in one of the Quick Recovery folders
2. When prompted (inside the sandbox) to choose where to save it, choose the previous file in order to overwrite it
3. When warned if you're sure, click "yes"
3. Launch Quick Recovery (or let Immediate Recovery #864 do its work)

**Expected behavior**
Sandboxie should prompt you "There's already such a file in the destination folder, would you like to overwrite it?".
If you choose no, it should act like today (i.e. rename the new file).
If you choose yes, it should overwrite.

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 20H2
 - Sandboxie 5.49.7
 
**Additional context**
I recall in the past Sandboxie didn't even support recovering files that already exist in the destination folder. It used to ignore them in Quick Recovery.
The current behavior is million times better than what it used to be.
Still, it's best not to rename without asking.

**Comment by DavidXanatos** [comment]
Well this behavior applies to the classical UI,
the plus UI already asks if the user wants to overwrite the file.

Since the classical UI is only provided as a  legacy option I will not change its behavior regarding file recovery.
