### ISSUE TITLE
Sandboxed Edge 91+ is stuck in a loop when you clean Media Foundation data

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#867]
**Describe the bug**
Sandboxed Edge 91.0.864.41 is stuck in a loop after trying to clean Media Foundation data. In order to stop the loading circle, you are forced to close the 'Clear browsing data' window. It doesn't happen when you run Edge unsandboxed.

**Screenshot**
![Media Foundation data Cleaning in Edge Browser](https://www.wilderssecurity.com/data/attachments/103/103512-8d9de8cceb1f0707781ba11c3828d5fa.jpg)

**System details and installed software (please provide the following information):**
 - Windows 10 Pro 20H2
 - Sandboxie Classic 5.49.7 64bit
 - Windows Defender

**Additional context**
I'm already using the SbieDLL fix [here](https://www.wilderssecurity.com/threads/sbie-chromium-90-compatybility-analysis.438203/#post-3010669), but it didn't work.

**Comment by DavidXanatos** [comment]
On a quick glance I don't see what causes that,
but when you close the settings window this closes to and nothing seams blocked.

**Comment by isaak654** [comment]
This is still an issue on 5.51.3 x64.

**Comment by DavidXanatos** [comment]
is this issue stil present with the latest sbie+? i could not rteproduce it with a quick test

**Comment by isaak654** [comment]
It's no longer stuck.
