### ISSUE TITLE
LogAPI random name changing at start

### ISSUE THREAD

**Issue by gjf** [sandboxie-plus/Sandboxie#87]
Don't really know to whom it should be addressed - to BSA or Sandboxie coder.

Anyway: as a feature request - is it possible to perform a random name changing of injected logapi.dll at every start of process inside Sandboxie?

I can expect some malware will check the name of injected dll and crash when logapiXX.dll will be found.

Sure it can be done manually... so just a wish, not the first priority.

**Comment by DavidXanatos** [comment]
I would see that to be something in the scope of BSA,
in Sandboxie the API logging is used to help me track down compatibility issues, hence no mitigation for adversarial behavior is required.
