### ISSUE TITLE
Typos to fix in setup interface

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#870]
Two typos to fix in 0.7.5 setup interface:

![typos_0.7.5_setup](https://user-images.githubusercontent.com/12372772/120893610-7afd5380-c614-11eb-8734-fb4af0cc1f0a.png)

And you could also replace classic with Classic here:

![](https://user-images.githubusercontent.com/12372772/120894105-0f68b580-c617-11eb-99e9-a5646f518c79.png)

This is inherent to #863 issue, because it would help to improve the maintenance of the installer code in the repository itself.

**Comment by DavidXanatos** [comment]
fixed for next build
