### ISSUE TITLE
Vivaldi can't install

### ISSUE THREAD

**Issue by Nypheena** [sandboxie-plus/Sandboxie#871]
**Describe the bug**
Running the vivaldi setup get notification that it crashed

**To Reproduce**
1. Go to vivaldi.com
2. Click on download windows setup
3. Run it

**Expected behavior**
No crash and that it installs

**Screenshots**

https://i.imgur.com/MNUSY5B.png

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2). 10 pro 2004
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2). 0.7.5
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. 0.7.5
 - Please mention any security software running in the background, even if the real-time protection is disabled. F-Secure

**Additional context**

**Sandboxie configuration**
https://gist.githubusercontent.com/ZeroMaki/390a051fe768383506430b3eb10a2419/raw/94f9ce1e981249772b48a1fb5f7f1b38779bf203/gistfile1.txt

**Comment by NewKidOnTheBlock** [comment]
I've had the same crash with SB 5.49.8
_However_.
The installer unpacked ~510MB and when I went to that folder, I could succesfully run Vivaldi from there by starting Vivaldi.exe through Sandboxie. Look:
![vivaldi](https://user-images.githubusercontent.com/12411527/120914313-b5f79980-c69d-11eb-9cf5-824e60d457fd.png)

**Comment by DavidXanatos** [comment]
did the installer run in any older version successfully?

**Comment by ZeroMaki** [comment]
> did the installer run in any older version successfully?

unfortunately I do not know, I only tried now with this version

**Comment by dmaeby** [comment]
I'm having the same issue.  I was initially getting the same error as the user above.  I updated Sandboxie to 5.50.9 (64-bit) and attempted to install Vivaldi.4.1.2369.15.x64.exe and now I get the error "The installer failed to uncompress archive. Please download Vivaldi again."  There is no problem with the exe as I can extract / test the archive with 7Zip and there is only a .7z archive in there.  If I manually extract the archive and attempt to run the vivaldi.exe in Sandboxie it just quits with no error message.  I can install and run Vivaldi (same installer exe) using the Windows Sandbox without any issues.  I've never used Vivaldi before and just wanted to try it out.

**Comment by DavidXanatos** [comment]
can you pelase try the latest build?

**Comment by isaak654** [comment]
> 
> 
> can you pelase try the latest build?

### Steps to reproduce the behavior for Plus 0.9.2
(requirement: not having Vivaldi installed outside of the sandbox)

1. Go to [vivaldi.com](https://vivaldi.com)
2. Click on download windows setup
3. Create a new box with default template
3. Run the vivaldi installer on the new box
4. Click on the "Accept and install" button
5. After 3 minutes of loading, it appears the error: SBIE2224 Sandboxed program has crashed: setup.exe

**Comment by dmaeby** [comment]
I get the same error message I received previously:

[https://i.imgur.com/Dw1qwss.png](url)

**Comment by DavidXanatos** [comment]
thats strange for me the setup also dies not work yet but it just crashes after some time of extracting files do you use the 0.9.2 version as isaak654 advised?

**Comment by NewKidOnTheBlock** [comment]
Just gave it another test:
SB 5.51.2
Vivaldi.4.1.2369.16.x64

Still SBIE2224 when trying to install.

**Comment by dmaeby** [comment]
I'm using Sandboxie Classic 5.50.9 (64-bit) and tried to install it into a newly created Sandbox with no presets.  I'm running Windows Version 21H1 (OS Build 19043.1151).

**Comment by DavidXanatos** [comment]
vivaldi instals fine in 1.0.17 on my system

**Comment by skycommand** [comment]
@DavidXanatos I am experiencing this problem on Sandboxie Plus v1.16.8 right now, trying to install Vivaldi 7.7.3851.58 x64. Please advise.

![Image](https://github.com/user-attachments/assets/784b9cb2-2026-4ac9-9daf-1f98b8efb51c)

**Comment by offhub** [comment]
@skycommand Try this:

1. Open Sandboxie Plus
2. Right-click on your sandbox
3. Select **Sandbox Options**
4. Go to **Edit ini Section** (to edit the configuration directly)
5. Add the line to to list
```ini
ClosedClsid=setup.exe,{9BA05972-F6A8-11CF-A442-00A0C90A8F39}
```
6. Click **OK** and try again installing Vivaldi in the sandbox

**Comment by skycommand** [comment]
If I've understood correctly, your instructions disable a COM object called `ShellWindows` (which permits a "Run As" verb, although this fact may not be relevant). It's certainly effective.

How did you conclude that this particular COM object was to blame?

**Comment by DavidXanatos** [comment]
@offhub i think we should add ```ClosedClsid={9BA05972-F6A8-11CF-A442-00A0C90A8F39}``` to the default template

**Comment by offhub** [comment]
@skycommand The installer was crashing shortly after executing the following command during installation. Blocking the object referenced in the command line allowed the installation to complete without crashing.

```
|Name|       |Status|            |Path / Command Line|                                                                                                      

rundll32.exe   Running (RunDll32)    C:\Windows\System32\rundll32.exe shell32.dll,SHCreateLocalServerRunDll {9BA05972-F6A8-11CF-A442-00A0C90A8F39} -Embedding   
```
