### ISSUE TITLE
Roll back a portable SandMan exit behaviour and make a confirmation dialog Y/N/C

### ISSUE THREAD

**Issue by VitRom** [sandboxie-plus/Sandboxie#874]
As I remeber, after a portable mode been introduced, for a several versions in row a portable SandMan exit confirmation was a way more handy. After a decline of proposal to stop-remove service and driver SandMan just did exits. No additional menu clicks to "disconnect".

So to both return this behaviour and still same safe as it is now I propose just to make confirmation dialog three-state. **Yes** to remove-and-exit, **No** to _keep-and-exit_ and **Cancel** to cancel, indeed.

**Comment by DavidXanatos** [comment]
yea the change was annoying myself to for a while, I'll roll that behavior back in the next build
