### ISSUE TITLE
Visual studio doesn't launch

### ISSUE THREAD

**Issue by john-throwaway** [sandboxie-plus/Sandboxie#877]
OS: Windows 10 21H1 (and Windows sandbox 2004)
Program: Visual studio 2019
Version: Sandboxie+ v0.7.5

Visual studio does not launch in sandboxie.
Tried both running already-installed-VS from host and installing new one inside sandbox
Also tested in windows sandbox for a clean env (other programs worked)
Tested with admin priv, tested with every sandboxie isolation stuff turned off. It errors no matter what I do

Error: "Package management initialization failed: Access Denied"
Repro: Just try to open visual studio inside sandboxie

**Comment by DavidXanatos** [comment]
That's not surprising IMHO,
was ist ever workignin any Sbie build?

**Comment by john-throwaway** [comment]
Haven't tried to sandbox it before, don't know

**Comment by DavidXanatos** [comment]
I think its a next to impossible fix, I mean you will also want the debugger to work etc, that from within a sandbox is probably not possible without disabling a lot of security

**Comment by john-throwaway** [comment]
Alright then, I'm going to be closing this

**Comment by Gravityzwell** [comment]
FYI older versions can work, 2010 maybe. It may be similar to Wine's compatibility, which is newer versions don't work.
