### ISSUE TITLE
Firefox add-ons automatically disabled after reboot

### ISSUE THREAD

**Issue by Bliepo2** [sandboxie-plus/Sandboxie#878]
**Description**
When running the latest stable version of FireFox in sandboxie plus, after reboot all add-ons in firefox will have been disabled. Manually enabling add-ons again works, but they will be disabled again. In addition, after the issue occurs even once, the option to pin firefox to the task bar dissapears.

The issue is somewhat intermittent and does not occur after every reboot/restart, but I have been able to successfully reproduce it on three different systems.

**Repoduction steps**
1. Install firefox
1. Create a hardened sandbox, and add the Firefox Programs Group to Forced Programs. Non-standard options: Sandbox Indicator in title = Don't alter window title, Sandbox window border = Border disabled, Protect this sandbox from deletion or emptying = true, Copy file size limit = 9999999)
1. Install the following add-ons: CanvasBlocker, Dark Reader, uBlock Origin, Violentmonkey
1. Use firefox normally
1. Reboot windows / restart firefox
1. Issue should arise automatically after a few times of repeating the previous step (in my case, it always happened in less than 10 reboots).

**Comment by bastik-1001** [comment]
I used different versions of Firefox and different versions of Sandboxie and never encountered that issue. Does this still happen with the latest version?
