### ISSUE TITLE
[Plus 0.7.5] Sandbox Isolation options UI bug

### ISSUE THREAD

**Issue by Coverlin** [sandboxie-plus/Sandboxie#879]
Advanced Options -> Isolation
the following options will not be saved correctly:
```
OpenDevCMApi
OpenSamEndpoint
OpenLsaEndpoint
```

Checking their respective checkboxes and clicking apply will unckeck and set them with the default `n` value

**Comment by DavidXanatos** [comment]
thanks will be fixed in the next build
