### ISSUE TITLE
is there way to use emoji inside sandboxed program windows 10?

### ISSUE THREAD

**Issue by GrennKren** [sandboxie-plus/Sandboxie#88]
I can't click any single icon from emoji window in **Chrome Browser** Windows 10, that was from `Win + period` keys to show that but I also have tried with **context** chrome from right click then choose "**Emoji**" on top. Again, nothing work.

just to make sure, the chrome browser was sandboxed and doesn't work but it's work without inside sandbox.

**Comment by skygunner** [comment]
\BaseNamedObjects\\[CoreUI]-PID*

Right-click on Sandboxie icon, then :
Sandbox > Defaultbox > Sandbox Settings > Resource Access > IPC Access > Direct Access
Click Add

same issue as issue 120
