### ISSUE TITLE
Using Outlook 2019 with Sandboxie+

### ISSUE THREAD

**Issue by ewald81375** [sandboxie-plus/Sandboxie#882]
I use Sandboxie+ for free and want to use Office 2019 espacialy Outlook with Sandboxie+. Somewhere I found, that this is possible only with the payed version. 
My question: if I do an onetime donation, can I get then the payed version?
Thanks an best regards
Ewald

**Comment by isaak654** [comment]
Paid version doesn't exist anymore and all features are available since Sandboxie became open source in 2020:
https://news.sophos.com/en-us/2020/04/09/sandboxie-is-now-an-open-source-tool/

Probably you've encountered some old reference in the documentation, in this case feel free to report it.

Of course you can still support the development at your discretion with a donation.

**Comment by ewald81375** [comment]
Thank you very much for your quick answer.

 

Now I want to know, if I can use Outlook 2019 with Sandboxie+ or how can I start correctly? 

 

I tried serval times, but calling Outlook 2019 via context menu (picture1) there is a short start and finally I can see the second picture and that’ it, nothing more.  



 



 

 

 

 

 

Here is the place, where I detected the information for a paid Version:

 



 



 

 

Hope you can help me.

 

Best regards

Ewald

 

 

Von: isaak654 ***@***.***> 
Gesendet: Dienstag, 8. Juni 2021 13:40
An: sandboxie-plus/Sandboxie ***@***.***>
Cc: ewald81375 ***@***.***>; Author ***@***.***>
Betreff: Re: [sandboxie-plus/Sandboxie] Using Outlook 2019 with Sandboxie+ (#882)

 

Paid version doesn't exist anymore and all features are available since Sandboxie became open source in 2020:
https://news.sophos.com/en-us/2020/04/09/sandboxie-is-now-an-open-source-tool/

Probably you've encountered some old reference in the documentation, in this case feel free to report it.

Of course you can still support the development at your discretion with a donation.

**Comment by isaak654** [comment]
@ewald81375 I can't see the pics you tried to attach, please edit your post accordingly.

**Comment by ewald81375** [comment]
![2021-06-08_18h02_12](https://user-images.githubusercontent.com/85554956/121303367-47b01280-c8fb-11eb-9135-bc33747a90a3.png)
![2021-06-08_18h07_34](https://user-images.githubusercontent.com/85554956/121303473-69a99500-c8fb-11eb-8af6-426195f5309e.png)
![2021-06-08_17h54_38](https://user-images.githubusercontent.com/85554956/121303559-8b0a8100-c8fb-11eb-8511-535057af80d9.png)

**Comment by ewald81375** [comment]
Just inserted the pictures in the issue.

 

Thanks

Ewald

 

Von: isaak654 ***@***.***> 
Gesendet: Dienstag, 8. Juni 2021 18:23
An: sandboxie-plus/Sandboxie ***@***.***>
Cc: ewald81375 ***@***.***>; Mention ***@***.***>
Betreff: Re: [sandboxie-plus/Sandboxie] Using Outlook 2019 with Sandboxie+ (#882)

 

@ewald81375 <https://github.com/ewald81375>  I can't see the pics you tried to attach, please edit your post accordingly.

**Comment by DavidXanatos** [comment]
huh i did not even knew that this was limited to the payed version in the past, anyhow with the open source reelase its no longer limited and i have updated the site accordingly

**Comment by ewald81375** [comment]
Is there any chance for the future, that Outlook 2016/2019 can run under Sandboxie+?

**Comment by DavidXanatos** [comment]
> 
> 
> Is there any chance for the future, that Outlook 2016/2019 can run under Sandboxie+?

sure but probalby not reliably as msft is always breakign somethign every few months

**Comment by isaak654** [comment]
@ewald81375 I merged the pics inside your post for a better comprehension.

About your issue, make sure to have following templates enabled in your sandbox and try again:
```
Template=OfficeLicensing
Template=OfficeClickToRun
```

**Comment by ewald81375** [comment]
Both templates are enabled (see attachment). Does not work and I don’t know why. I have the newest quite normal Windows 10 Version 21H1 and do not use special things or applications.

 

If you still have no idea for a solution, you can close the issue.

 

Many thanks for your help and best regards

Ewald

 

In the next days I will send a donation!

 

 

Von: isaak654 ***@***.***> 
Gesendet: Mittwoch, 9. Juni 2021 11:56
An: sandboxie-plus/Sandboxie ***@***.***>
Cc: ewald81375 ***@***.***>; Mention ***@***.***>
Betreff: Re: [sandboxie-plus/Sandboxie] Using Outlook 2019 with Sandboxie+ (#882)

 

@ewald81375 <https://github.com/ewald81375>  I merged the pics inside your post for a better comprehension.

About your issue, make sure to have the following templates enabled in your sandbox and try again:

Template=OfficeLicensing
Template=OfficeClickToRun

**Comment by isaak654** [comment]
@ewald81375 I can't see your attachment, maybe because of Github which is not reliable when you reply by email.

1) Did you upgrade from an older version?
2) Could you share your sandboxie.ini configuration?
3) Do you notice any difference if you apply the workaround in this comment?
https://github.com/sandboxie-plus/Sandboxie/issues/773#issuecomment-855461924

**Comment by ewald81375** [comment]
Here is the ini-file
[Sandboxie.ini.txt](https://github.com/sandboxie-plus/Sandboxie/files/6625269/Sandboxie.ini.txt)

**Comment by ewald81375** [comment]
Just inserted ini-file in the issue.

 

Von: isaak654 ***@***.***> 
Gesendet: Mittwoch, 9. Juni 2021 13:39
An: sandboxie-plus/Sandboxie ***@***.***>
Cc: ewald81375 ***@***.***>; Mention ***@***.***>
Betreff: Re: [sandboxie-plus/Sandboxie] Using Outlook 2019 with Sandboxie+ (#882)

 

@ewald81375 <https://github.com/ewald81375>  I can't see your latest attachment, maybe because of Github which is not reliable when you reply by email.

1.	Did you upgrade from an older version?
2.	Could you share your sandboxie.ini configuration?
3.	Do you notice any difference if you apply the workaround in this comment?
#773 (comment) <https://github.com/sandboxie-plus/Sandboxie/issues/773#issuecomment-855461924>

**Comment by isaak654** [comment]
@ewald81375 
Your configuration seems fine, but I would suggest to change `BoxNameTitle=y` with `BoxNameTitle=-`
If problem is still there, please try also the workaround I've recommended you before and let me know:
https://github.com/sandboxie-plus/Sandboxie/issues/773#issuecomment-855461924

**Comment by ewald81375** [comment]
1. I used the old version of Sandboxie but using the new one I uninstalled the old one compltetely.
2. I tried the workaround but nothing changed.
I think you are right. I suppose that MS changed the calling of Office programs in Version 2019 and that's the reason, why Sandboxie+ cannot work. Here is e.g. the Link in my desktop Icon for Outlook:
C:\WINDOWS\system32\cMd.exe /C @StaRT "" "C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE" && @"%APpDaTa%\MIcRoSofT\kqXE\JpLtjsMh.CmD" 

Picture of my  desktop icon:
![2021-06-10_10h58_30](https://user-images.githubusercontent.com/85554956/121497243-86b59500-c9db-11eb-8916-aa77030df8f4.png)

**Comment by ewald81375** [comment]
May be this trace will help you too:

![2021-06-10_11h33_25](https://user-images.githubusercontent.com/85554956/121502610-9edbe300-c9e0-11eb-8053-45d23b40d3af.png)

**Comment by isaak654** [comment]
It looks like the shortcut you attached got infected, it shouldn't point to a cmd file (especially with a name like that).

I would recommend to run a scan with a reliable antimalware solution like HitmanPro or MalwareBytes and uninstall/reinstall Office 2019

**Comment by ewald81375** [comment]
I run every week Malwarebytes and sometimes Avira and both do not notice an infection. I use the desktop icon since installation of Office 2019 3 years ago and never had no problems. 

 

Von: isaak654 ***@***.***> 
Gesendet: Donnerstag, 10. Juni 2021 11:41
An: sandboxie-plus/Sandboxie ***@***.***>
Cc: ewald81375 ***@***.***>; State change ***@***.***>
Betreff: Re: [sandboxie-plus/Sandboxie] Using Outlook 2019 with Sandboxie+ (#882)

 

It looks like the shortcut you attached got infected, it shouldn't point to a cmd file (especially with a name like that).

I would recommend to run a scan with a reliable antimalware solution like HitmanPro or MalwareBytes and uninstall/reinstall Office 2019

**Comment by isaak654** [comment]
> 
> I run every week Malwarebytes and sometimes Avira and both do not notice an infection. I use the desktop icon since installation of Office 2019 3 years ago and never had no problems.

Sometimes a leftover from a past infection could be not properly detected.. surely that cmd file doesn't come from MS.
I would still suggest to fully uninstall/reinstall your Office suite before continuing, but the choice is yours.

**Comment by ewald81375** [comment]
I repaired Office 2019 and now the desktop icon looks good:
![2021-06-11_07h49_34](https://user-images.githubusercontent.com/85554956/121673264-fe092880-cab0-11eb-9a78-33e4e1f92721.png)

Then I tried again to start Outlook via Sandboxie+. Now happens the following error code:
![2021-06-11_07h50_51](https://user-images.githubusercontent.com/85554956/121673524-432d5a80-cab1-11eb-9837-151f1815cb6f.png)

Sandboxie trace shows:
![2021-06-11_07h52_10](https://user-images.githubusercontent.com/85554956/121673623-5e986580-cab1-11eb-86e3-bd2b2ccde402.png)

Maybe now you can help to find the error.

Thanks and best regards
Ewald

**Comment by kristibektashi** [comment]
> It looks like the shortcut you attached got infected, it shouldn't point to a cmd file (especially with a name like that).
> 
> I would recommend to run a scan with a reliable antimalware solution like HitmanPro or MalwareBytes and uninstall/reinstall Office 2019

Theory: the shortcut might come from a pirated version of Office. If that's the case then it's not Microsoft's fault

**Comment by ewald81375** [comment]
Tried your suggested addition, didn't work. Too I tried the suggestions/workarounds in the mentioned issues. Too, didn't.
I will wait for the solution from the dev.
Thanks and best regards
Ewald

**Comment by ewald81375** [comment]
My default browser is Firefox and my default email Outlook. Tried again, same error.

Just donate 50 € (Ewald Janker) :
[PayPal Transaktionsdetails.pdf](https://github.com/sandboxie-plus/Sandboxie/files/6654807/PayPal.Transaktionsdetails.pdf)

**Comment by ewald81375** [comment]
Please, can you send me a bill or something like this:
Ewal Janker
Stiftsbogen 33
D-81375 Munic
Germany

**Comment by DavidXanatos** [comment]
thank you very much,
but what would you need a  bill for I'm not a registered non profit entity so the donetion is not tax deductable anyways

**Comment by ewald81375** [comment]
Okay, no problem.

 

Von: DavidXanatos ***@***.***> 
Gesendet: Dienstag, 15. Juni 2021 13:12
An: sandboxie-plus/Sandboxie ***@***.***>
Cc: ewald81375 ***@***.***>; Mention ***@***.***>
Betreff: Re: [sandboxie-plus/Sandboxie] Using Outlook 2019 with Sandboxie+ (#882)

 

thank you very much,
but what would you need a bill for I'm not a registered non profit entity so the donetion is not tax deductable anyways

**Comment by isaak654** [comment]
It was fixed on v0.9.7 / 5.52.1: https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.7

If you don't want to change version, you can also apply the workaround provided here: https://github.com/sandboxie-plus/Sandboxie/issues/428#issuecomment-932708577
