### ISSUE TITLE
Problem opening QuickBooks data file in sandboxed instance

### ISSUE THREAD

**Issue by ylluminate** [sandboxie-plus/Sandboxie#884]
**Describe the bug**
When I open QuickBooks in Sandboxie Plus it has errors / problems opening the QuickBooks database file (QBW). The app itself seems to start fine.  I did enable networking support as the database is on a server, but unfortunately it still will not open and asks me to use the doctor app to diagnose issues, which also seems to really do nothing.

**System details and installed software (please provide the following information):**
 - Windows 10 LTSC 1809
 - Sandboxie Plus 0.7.5
 - No security software running 

**Sandboxie configuration**
ini: https://gist.github.com/ylluminate/f10dbcca40aa93592c2bb8878981dc68

**Trace Log**
https://gist.github.com/ylluminate/4a98956fa5bf7a04119e865bc65dbddb

Any thoughts about how to troubleshoot this?

**Comment by DavidXanatos** [comment]
was it working in any sbie version?

**Comment by ylluminate** [comment]
Have not tested with any sbie version...

Trial download: https://quickbooks.intuit.com/learn-support/en-us/new-subscriptions/download-a-trial-of-quickbooks-desktop/00/185974

We're using Enterprise edition and I'm not really sure if that will be required in this situation since we use it on a network share with a number of users. Ultimately you and I might need to get together privately on a remote session to debug...

**Comment by DavidXanatos** [comment]
Is the problem only present when accessing a DB on a server or also with local DB's?
also please test older versions of sbie just in case

**Comment by ylluminate** [comment]
A bit low on the personal bandwidth side of things for this issue currently. I managed to work around the issue that Sandboxie would have helped me solve, but I will need this again and I'll circle back to this when I have more time to do further testing and reopen with answers for your questions.
