### ISSUE TITLE
Updating translations on Sandboxie Plus - how to?

### ISSUE THREAD

**Issue by RockyTDR** [sandboxie-plus/Sandboxie#885]
@DavidXanatos I wanted to put this on the forum but I lost my password and I'm not able to reset it... so here goes:

I have been translating the "old" Sandboxie files to Dutch, which is rather easy because the source file is text based. However, I have no idea how to get the English source file for Sanboxie Plus... As I understand, it uses .qm and .qt files, but I'm not familiar with the format. Can you guys point me in the right direction?

Additional: would it be possible to set up an online translation tool (e.g. Transifex), that makes it possible to have automated translation updates? This would make it easier for translators (like me, who aren't programmers) and also for the developers, because translations would be updated automatically in the background.

Lastly, it would be convenient for future translators if there are some instructions for translating on the homepage or on GitHub.

**Comment by Dyras** [comment]
I think this is the source file
https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/Sbie-English-1033.txt

**Comment by yuhao2348732** [comment]
1、download Qt Installer，http://download.qt.io/archive/qt/，
2、change  system variable
3、download Source code
4、open（load）SandboxiePlus.pro
5、tools  lupdate

**Comment by isaak654** [comment]
> 
> 
> I think this is the source file
> https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/Sbie-English-1033.txt

That is for Sandboxie Classic only.

**Comment by DavidXanatos** [comment]
to translate the plus UI you need https://doc.qt.io/archives/qt-4.8/linguist-translators.html
and a ts file for the language, you can find these files on guthub here: https://github.com/sandboxie-plus/Sandboxie/tree/master/SandboxiePlus/SandMan
if the file for your language is missing you can eider install QT and add it or ask me and I'llc reate one and uplaod to github.
once an up to date file is there you only need to the mentioned linguist tool

**Comment by DavidXanatos** [comment]
Which dutch do you want to so "Durch Belgium" or "Durch Netherlands"?

**Comment by RockyTDR** [comment]
Thanks for the answers! 
Just "Dutch" is fine, if possible, There is virtually no difference in grammar or spelling (just pronunciation) between Belgian or Netherlands Dutch.

**Comment by DavidXanatos** [comment]
well i have to choose one or the other, so which one should i choose

![grafik](https://user-images.githubusercontent.com/3890945/121523605-af975380-c9f6-11eb-8794-141a450ee9ff.png)

**Comment by DavidXanatos** [comment]
her it is: https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_nl.ts

**Comment by RockyTDR** [comment]
Thank you! I imported it in Transifex to translate. Is it possible to create an "english.ts" in GitHub that auto-updates ? That way I can set "automatic source file updates" in Transifex and I'll receive notifications when new strings are available to translate.

**Comment by RockyTDR** [comment]
@DavidXanatos Any news regarding my previous question: "_Is it possible to create an "english.ts" in GitHub that auto-updates?_"

**Comment by DavidXanatos** [comment]
i can create a english ts and update it with every release auto update i dont think so

**Comment by RockyTDR** [comment]
Ok, please do! Having an "english.ts" would be amazing!

If you could update it a few days before a new release, I could deliver a 100 % translated file in time. Otherwise, the translations will be "perpetually unfinished" (however, this is mostly not really a problem because a few untranslated strings won't make the program unusable).

**Comment by DavidXanatos** [comment]
her it is: https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_en.ts

**Comment by RockyTDR** [comment]
Thanks! This will enable me to receive notifications whenever the english.ts gets updated.

**Comment by sebadamus** [comment]
Hi, if I post wrongly here, please tell.
I found there is a source text that has no entry to be trasnlated, so it appears in english always and cant find searching it in the [sandman_es.ts](https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_es.ts) file.

![imagen](https://user-images.githubusercontent.com/1787753/156936469-91e00a5f-fc9c-4565-9822-b8f045a88f5e.png)

So, do I have to re-sync main english file with spanish one? mmm think yes, will read that post about syncing.
