### ISSUE TITLE
Add base image support

### ISSUE THREAD

**Issue by tsao-chi** [sandboxie-plus/Sandboxie#887]
**Is your feature request related to a problem? Please describe.**
#859

**Describe the solution you'd like**
Add optional base image option

base image provides base C drive for sandboxes

It can be a img file or a directory of a fully installed Windows instance.

**Describe alternatives you've considered**

**Additional context**

**Comment by isaak654** [comment]
Please post on the issue you linked, thanks.

**Comment by isaak654** [comment]
Update: please post on issue #890, thanks.
