### ISSUE TITLE
bootim.exe hides the mouse pointer

### ISSUE THREAD

**Issue by norelmas** [sandboxie-plus/Sandboxie#889]
C:\Windows\system32\bootim.exe shows an option "Turn off your PC" in win10 21H1, click on it and the mouse pointer disappears. Ctrl+Alt+Del let the pointer appear again.

**Comment by DavidXanatos** [comment]
I can't confirm that, moving the mouse was enough to get the cursor back also it would be a bit to much preventing applications from changing the cursor when they have focus as this is a often used feature to indicate interaction opportunities.
You can also press teh win key to get out of that screen , to close it though you need a task manager i think as it ignores the taskbar close command and alt f4 but that's acceptable behavioure

**Comment by ikyynites** [comment]
can confirm it does make my mouse cursor disappear and it does come back with "ctrl+alt+del"
