### ISSUE TITLE
Windows Explorer Crashes (Sandboxed)

### ISSUE THREAD

**Issue by AbedKarmi** [sandboxie-plus/Sandboxie#89]
When I open Windows Explorer (Sandboxed), it crashes immediatly, with error "SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1".
I spent hours until I found that DropBox Desktop is causing this!. When I uninstall it everything works fine!. I believe something must be fixed in sandboxie, as dropbox integrates with windows explorer.

**Comment by githubcek** [comment]
I can confirm. I have uninstalled Dropbox and now Sandboxed Windows Explorer is working.
Win10 (v2004)

**Comment by githubcek** [comment]
I have found workaround: 

In configuration file added path to Dropbox (in GlobalSettings):
[GlobalSettings]
ClosedFilePath=C:\Program Files (x86)\Dropbox\

No more crashes :)

**Comment by 0xBADDCAFE** [comment]
If Dropbox installed itself in user directory, the path is like below:

```
[GlobalSettings]
ClosedFilePath=C:\Users\USERNAME\AppData\Roaming\Dropbox
```

**Comment by flewisflewis** [comment]
This doesn't work for me.  

I found a qt.conf file here:
C:\Program Files (x86)\Dropbox\Client\qt.conf

I added the following to the above file:
[GlobalSettings]
ClosedFilePath=C:\Program Files (x86)\Dropbox\

But I still got the error.

So instead of adding the above, I added:
[GlobalSettings]
ClosedFilePath=C:\Users\[USERNAME]\AppData\Roaming\Dropbox\

But I still got the error.

**Comment by githubcek** [comment]
> This doesn't work for me.
...
> But I still got the error. Do I have the wrong .conf file?

Yes don't put this lines in qt.conf but in sandboxie settings: Configure -> Edit Configuration. 
I'm talking about this "Edit Configuration": https://www.filecroco.com/wp-content/uploads/2017/11/sandboxie-2.jpg
This is the easiest way. You can of course find sandboxieini file.

**Comment by flewisflewis** [comment]
Thank you!  It works perfectly!
