### ISSUE TITLE
Thunderbird doesn't open when I check Thunderbird in email apps.

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#891]
When I checked the box for Thunderbird in Sandboxie and close it.  I then click on Thunderbird in the task bar, it doesn't go into the Sandboxie.

Sandboxie version 5.49.8
Thunderbird 78.11

Windows 10 Home
21H1
OS build 19043.1052

Here's the Sandboxie.ini file:

[GlobalSettings]

OpenFilePath=c:\windows\system32\spool\printers\*
OpenFilePath=firefox.exe,%UserProfile%\AppDataLocalLow\Mozilla\temp-*
AllowSpoolerPrintToFile=y
Template=RpcPortBindings
Template=WindowsRasMan
Template=SynapticsTouchPad
Template=WindowsLive
Template=OfficeLicensing
ForceDisableSeconds=300

[DefaultBox]

ConfigLevel=9
BlockNetworkFiles=y
Template=AdobeDistiller
Template=AdobeAcrobatReader
Template=AdobeAcrobat
Template=Thunderbird
Template=Chrome_Profile_DirectAccess
Template=Chrome_Sync_DirectAccess
Template=Chrome_Preferences_DirectAccess
Template=Chrome_Passwords_DirectAccess
Template=Chrome_Cookies_DirectAccess
Template=Chrome_History_DirectAccess
Template=Chrome_Bookmarks_DirectAccess
Template=Chrome_Force
Template=Firefox_Profile_DirectAccess
Template=Firefox_Session_DirectAccess
Template=Firefox_Passwords_DirectAccess
Template=Firefox_Cookies_DirectAccess
Template=Firefox_Bookmarks_DirectAccess
Template=Firefox_Force
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
Enabled=y
AutoDelete=y
NeverDelete=n

[UserSettings_085A01AD]

SbieCtrl_UserName=info
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_NextUpdateCheck=1624047375
SbieCtrl_AutoRunSoftCompat=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_WindowCoords=-1,5,1237,632
SbieCtrl_ActiveView=40021

**Comment by isaak654** [comment]
In order to force Thunderbird process in Sandboxie, you need to add manually `ForceProcess=thunderbird.exe` in your sandbox.

**Comment by jedimasterspaz** [comment]
Where do I add this command?

Thanks

**Comment by jedimasterspaz** [comment]
Why does it work on my computer, but not on my customer's computers?

Again, Thanks

**Comment by isaak654** [comment]
You can find further details about this setting in the documentation:
https://davidxanatos.github.io/sandboxie-docs/Content/ForceProcess.html
