### ISSUE TITLE
Network connection options (Bridged / NAT)

### ISSUE THREAD

**Issue by c-sanchez** [sandboxie-plus/Sandboxie#893]
**Option to use Bridged or NAT connection.**

Virtual Machine software like VMware Workstation or VirtualBox have a option to setup the network connection in VM as Bridged or NAT.
This is useful if we want use the same IP in host and vm (or sandboxed) software.
We can have by example a IP Addres from an VPN runing in the host system and the physical ip address in the vm, or the opposite, or have the same IP on both.

So that, I wonder if possible to have a Bridged connection with Sandboxie.

![](https://i.ibb.co/YdG5Lv1/vmware-workstation-network-options.png)

**Comment by DavidXanatos** [comment]
Gelerally its not possible as sandboxie is not a VM and doe snot have an own network stack

If you configure your PC's Network card to have more than one IP or you have more than one network card, 
it would be in principle possible to force newly created sockets to be bound to a specified IP address though.
This would require quite a bit of a rework.

**Comment by DavidXanatos** [comment]
further discussion on sandboxie's networking aspects please in issue #894
