### ISSUE TITLE
can't move the camera vertically in some games

### ISSUE THREAD

**Issue by mio-19** [sandboxie-plus/Sandboxie#895]
**Describe the bug**
The character keeps spinning

**To Reproduce**
BeamNG:
1. Spawn a vehicle
2. shift + c
3. Move mouse

Some version of modded Minecraft Java Edition:
1. Move mouse
2. See error

**Expected behavior**
The camera is moved vertically

**Screenshots**

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2). Windows 10 Pro 20H2 and 21H1
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2). Sandboxie Plus v0.7.5
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. unknown
 - Please mention any security software running in the background, even if the real-time protection is disabled. Microsoft Defender

**Additional context**

**Sandboxie configuration**

**Comment by DavidXanatos** [comment]
can the game be downloaded for free for testing?

**Comment by GraxMonzo** [comment]
I have this problem on my laptops. Everything works fine on desktop.

**Comment by DavidXanatos** [comment]
have you tryed the program without a sandbox on your laptop?
may be its not sbie related?

**Comment by tsao-chi** [comment]
> can the game be downloaded for free for testing?

Unfortunately no

**Comment by tsao-chi** [comment]
video:
https://github.com/tsao-chi/files/blob/_/VID_20210615_072205.mp4
https://github.com/tsao-chi/files/blob/_/VID_20210615_072615.mp4

**Comment by DavidXanatos** [comment]
in the past builds some input device issues have been fixed, is this issue stil present?

**Comment by DavidXanatos** [comment]
as there is no more feedback I'll close this one
