### ISSUE TITLE
[Plus UI 0.8.0/0.8.1] Typo in the new Trace log checkbox

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#897]
https://github.com/sandboxie-plus/Sandboxie/blob/1a6c09490cfc6d00ee4df50c58b0aa7fc60073d3/SandboxiePlus/SandMan/Views/TraceView.cpp#L74

I would suggest `Show only for the selected box`, but any other suggestion is welcome.

**Comment by DavidXanatos** [comment]
how about "Filter for selected box only"

**Comment by isaak654** [comment]
> 
> 
> how about "Filter selected box only"

It looks fine to me.

**Comment by DavidXanatos** [comment]
ok will be in includedin the next build
