### ISSUE TITLE
Sandboxie-Classic-x86-v5.50.0 DcomLaunch Error

### ISSUE THREAD

**Issue by TeslaMagic** [sandboxie-plus/Sandboxie#898]
Windows 7 (32-bit) - tested on three systems.

The installation is normal but when you try launch Firefox, or some other software into Sandboxie, the following (attached) DcomLaunch error occurs and the application that is launched never starts.

A clean uninstall-reboot-install produces the same results.

The fix was to revert back to v5.49.8.

![DcomLaunch Error](https://user-images.githubusercontent.com/16181192/121822581-174ed800-cc5d-11eb-8abc-9007e74e06a0.png)

**Comment by DavidXanatos** [comment]
fixed release is out: bugfix release is out: https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.8.1
