### ISSUE TITLE
Sandboxie-Classic-x64-v5.50.0 Clipboard Error

### ISSUE THREAD

**Issue by reraikes** [sandboxie-plus/Sandboxie#899]
Copy to clipboard (^C) in Microsoft Edge (Windows 8.1) results in:

SBIE2205 Service not implemented:  CloseClipboard C0000058

Reverting to Sandboxie 5.49.8 (64-bit) eliminates the problem.

**Comment by DavidXanatos** [comment]
fixed release is out: bugfix release is out: https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.8.1
