### ISSUE TITLE
ESET antivirus prevents sandboxie installation

### ISSUE THREAD

**Issue by AbedKarmi** [sandboxie-plus/Sandboxie#90]
Old versions 5.33.3 and 5.33.6 work fine, but 5.42 is recognized as a virus, specifically kmduil !

**Comment by deflock** [comment]
Guys do you read anything before installing/using something? 😀
https://github.com/sandboxie-plus/Sandboxie/issues/52
https://github.com/sandboxie-plus/Sandboxie/releases/tag/v0.3

@DavidXanatos looks like your important note is not enough :)) Maybe it makes sense to create a dedicated issue "NOT A VIRUS!!!!!" with explanation what is going on and what to do and pin it to the top of issues 😂

**Comment by AndhikaWB** [comment]
I believe there is also ability to pin certain issue on GitHub (so it stay on top).

**Comment by rugabunda** [comment]
yes eset updated their obfuscated detection modules/algorithms

**Comment by DavidXanatos** [comment]
I have created a pinned issue for the topic
