### ISSUE TITLE
Internal pdf reader from Brave does not work

### ISSUE THREAD

**Issue by otto1984** [sandboxie-plus/Sandboxie#903]
Thanks for the Chrome 90+ fixes, however I still have an issue with Brave opening PDF documents inside the sandbox.
I also tried it with Edge, there it works without problems.

Error Message in Brave: "Couldn't load plungin."

I can reproduce the issue with the versions 5.49.8 to 5.50.1.

**Comment by isaak654** [comment]
Thank you for the confirmation. An issue is already open in #817.
