### ISSUE TITLE
[Plus 0.8.1] Regression with some installers

### ISSUE THREAD

**Issue by Shadowized** [sandboxie-plus/Sandboxie#906]
**Describe the bug**
It would seem that after upgrading to **SBIE+ v0.8.1**, bug #595 is happening again.

**To Reproduce**
1. Run setup.exe inside a sandbox
2. a dialog with "Runtime error 229" appears, a few more of the same dialog spawn with no interaction after some time.
3. Clicking OK closes the installer.
4. See screenshot.

**Expected behavior**
The installer should run fine like in the prior versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/5408749/122018457-e079de80-cd90-11eb-84b0-c3ad251c777b.png)

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? **Win10 1909** + **Win10 2004**
 - What is your current Sandboxie edition and version? **Sandboxie Plus v0.8.1**
 - Please mention in which version this bug got introduced, **v0.8.1** From my testing **v0.8.0** works fine works fine.
 - Please mention any security software running in the background, even if the real-time protection is disabled. N/A

**Additional context**
Tried testing and toggling the new flags but to no avail, using both my own and clean Sandboxie.ini

**Comment by DavidXanatos** [comment]
what installers are causing this issue?

Also please try the option```ApplyElevateCreateProcessFix=y```

**Comment by Shadowized** [comment]
> what installers are causing this issue?

CODEX ones, here's the [setup exe/ini](https://files.lulzbin.com/2021/06/exampleInstall.zip) from cd which should be sufficient enough to trigger the error.
 

> Also please try the option`ApplyElevateCreateProcessFix=y`

I did, along with the other documented additions and it still errors.

**Comment by DavidXanatos** [comment]
on my system the installer opens just fine, should I click on something? (i would guess than it would error out mussing the other files)

**Comment by Shadowized** [comment]
interesting, perhaps its related to my systems not having UAC enabled? I didn't see much in the changelog from v0.8.0 to v0.8.1 that could cause this.

**Comment by DavidXanatos** [comment]
ok and 0.7.5 was working fine?

**Comment by Shadowized** [comment]
> ok and 0.7.5 was working fine?
yes, 0.7.4, 0.7.5, and 0.8.0 work fine.

**Comment by Shadowized** [comment]
So I installed a fresh Win10 201H VM, All I did was create a new user, install SBIE+ **v0.8.1** x64, ran the setup.exe in defaultBox and received the same Runtime error. Uninstalled **v0.8.1** and installed **v0.8.0**, it works fine. I tested a bit further and downloaded a fresh [Win10 20H2 development environment VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/), which are neat ready-to-go VM's and did the same thing, the results did not change,

so at the very least, I can confirm to the best of my knowledge that the issue is in fact not on my end as I can replicate it on multiple fresh VM's and bare metal.

**Comment by DavidXanatos** [comment]
ok that is strange...
and you tried with this stripped down installer you posted here?
or with the full one?

**Comment by Shadowized** [comment]
the stripped down one, as its easier to chuck it on a network share and copy the files to desktop in a few seconds.

**Comment by DavidXanatos** [comment]
ok will take a second look also with a clean vm may be some artefact in my dev vm prevents the issue from manifesting

**Comment by DavidXanatos** [comment]
darn it... i have found the bug, its the fix for the driver verifier fix, working on fixing it probably we wil soon have a 0.8.2 LOL
