### ISSUE TITLE
progress of copying files

### ISSUE THREAD

**Issue by norelmas** [sandboxie-plus/Sandboxie#907]
In win10 21H1, use a sandboxed explorer to copy large files(e.g, 300MB in size) it doesn't show the progress.

**Comment by DavidXanatos** [comment]
does the copy finishes ok is only the progres display affected?

**Comment by norelmas** [comment]
> does the copy finishes ok is only the progres display affected?

The copy finishes normally.

**Comment by DavidXanatos** [comment]
i can not reproduce that does anyone else has this problem?

**Comment by DavidXanatos** [comment]
since we dont have a confirmation and i cant reproduce it i'll clode this one
