### ISSUE TITLE
Run explorer as administrator

### ISSUE THREAD

**Issue by norelmas** [sandboxie-plus/Sandboxie#908]
The root folder, e.g., E: F: are root folders, may be owned by SYSTEM and other accounts don't have permissions. Unprivileged explorer can't access them.

**Comment by DavidXanatos** [comment]
i can not reproduce this error

**Comment by norelmas** [comment]
> 
> 
> i can not reproduce this error

Remove some principals from a partition. ![remove](https://user-images.githubusercontent.com/84897073/122047580-29cc2d00-cd95-11eb-8acd-0f9bb6eb36b2.png)

**Comment by DavidXanatos** [comment]
this is not the default windows preset, if you mess with the ACLs than it surely will cause issues.
I'm surprised this does not break the the non sand boxed explorer.

**Comment by norelmas** [comment]
Win10 doesn't tell us some apps' locations. File explorer and UWP apps don't show their locations. ![filelocation](https://user-images.githubusercontent.com/84897073/122048892-af9ca800-cd96-11eb-88c2-2a3958484e43.png)

**Comment by DavidXanatos** [comment]
> 
> 
> Win10 doesn't tell us some apps' locations. File explorer and UWP apps don't show their locations. ![filelocation](https://user-images.githubusercontent.com/84897073/122048892-af9ca800-cd96-11eb-88c2-2a3958484e43.png)

well that's a windows 10 bug
