### ISSUE TITLE
[Sbie Plus] Windows Finder height is too short (no dpi scaling)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#912]
**Describe the bug**
Windows Finder height appears too short for some translations like russian or italian. In the following examples, the final word is missing in the Windows Finder on both translations:

![windows_finder_shortheight_1](https://user-images.githubusercontent.com/12372772/122133523-242a2200-ce3d-11eb-9a1f-f4a172dc793d.png)

![windows_finder_shortheight_2](https://user-images.githubusercontent.com/12372772/122132004-5e45f480-ce3a-11eb-94b3-d64dc67f8221.png)

**Expected behavior**
Windows Finder height should be increased furtherly, by adding 1 or 2 lines.

**System details and installed software (please provide the following information):**
Windows 10 Pro 20H2
Sandboxie Plus 0.8.2
Screen resolution: 1600x1200, no change to any dpi setting.

**Comment by isaak654** [comment]
I still have this issue on 1.0.7 Plus - 2560x1440 - custom dpi scaling = 140

**Comment by DavidXanatos** [comment]
wil be fixed in the next build
