### ISSUE TITLE
What does "do you want to put the sandbox folder into its parent directory?" mean?

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#916]
**Describe the bug**
What does this message mean?

**To Reproduce**
1. Extract Sandboxie Plus Portable
1. Enter SandMan.exe
1. See message

**Expected behavior**
Display a more clarified message. It should clarify:
1. What happens when you choose Yes?
1. What happens when you choose No?

**Screenshots**
![image](https://user-images.githubusercontent.com/1773306/122277263-619ab800-ceee-11eb-94ed-ef63af2dedcc.png)

**System details and installed software (please provide the following information):**
 - Windows 10 21H1
 - Sandboxie Plus 0.8.2 Portable

**Comment by Coverlin** [comment]
Example
Will create the sandboxie container at `C:\Program Files\Sandbox`
If you use default install path `C:\Program Files\Sandboxie` or `C:\Program Files\Sandboxie-Plus`
The parrent directory is `C:\Program Files`

**Comment by lwcorp** [comment]
And if I choose No then it'll be at `C:\Program Files\Sandboxie\Sandbox` / `C:\Program Files\Sandboxie-Plus\Sandbox` ?

**Comment by DavidXanatos** [comment]
I hope you did not extract a portable instalation to C:\Program Files thats not good practice,
you should eider install it properly or choose a custom location.

If you choose no on this screan the box fodler will be created at C:\Sandbox

**Comment by lwcorp** [comment]
No, I used something like `%USERPROFILE%\Downloads\Sandboxie-Plus`.
Does it mean:
1. Choosing Yes will select `%USERPROFILE%\Downloads\Sandboxie-Plus\Sandbox`?
1. Choosing No will select `C:\Sandbox`?

**Comment by DavidXanatos** [comment]
Choosing Yes will select %USERPROFILE%\Downloads\Sandbox?

The idea was that on a pen drive with *:\Sandboxie-Plus
it will result in *:\Sandbox being used

**Comment by lwcorp** [comment]
Any chance to change the default to be a subfolder like `Sandboxie-Plus\Sandbox`?
It'll be especially useful for portable use.

**Comment by DavidXanatos** [comment]
> 
> 
> Any chance to change the default to be a subfolder like `Sandboxie-Plus\Sandbox`?
> It'll be especially useful for portable use.

Unfortunately this is not possible, sandboxies home / instalation directory has some special protection so putting the box root there or as a sub dir would not work
