### ISSUE TITLE
Auto updater which will auto update or at least alert on new versions

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#917]
**Is your feature request related to a problem? Please describe.**
Most people don't manually constantly to the website (in this case repository) to check for updates and then download them.
One of the most helpful features of the original Sandboxie was that it automatically altered about new versions and gave a link to them.

**Describe the solution you'd like**

1. Alert there's a new update with a link to download it.
2. Better yet (which the original Sandboxie didn't do), offer to automatically download and install it.

**Comment by Coverlin** [comment]
Plus and Classic UI manual and auto check4up

![SandboxieWheelChairEditionTBA](https://user-images.githubusercontent.com/34079190/122310140-56f51880-cf18-11eb-890c-ce54af51dc03.png)

**Comment by lwcorp** [comment]
In the upper image (Sandboxie Plus) can you enable it by default? Will get more people to update this way.

In the lower image (Sandboxie Classic) isn't it a manual check (one has to click `Help=>Check For Updates=>Choose Now/Next Week`)?

**Comment by DavidXanatos** [comment]
Sandboxie Plus will ask after one week the user if he wants to use auto updates and if the user says yes the checkbox will get enabled

**Comment by lwcorp** [comment]
Thanks!

For portable use will it ask for updates?

For Classic, can you see my question above?

**Comment by DavidXanatos** [comment]
The classic version iirc should also show that window after 7 days, i think dont remember and am to lazy to chekc right now lol

anyhow for one of the upcomming builds I'll upgrade the updater offering the options to install the latest build

**Comment by Dyras** [comment]
Personally, I wish there was an option for automatic silent updates. Disabled by default, of course.
