### ISSUE TITLE
What is Force into this sandbox

### ISSUE THREAD

**Issue by sixiansheng** [sandboxie-plus/Sandboxie#918]
I'm sorry, I used a translator and may not be accurate, I want to know what this arrow means, this software is not already in the sandbox, so what does this Force into this sandbox mean?
![image](https://user-images.githubusercontent.com/35787924/122340723-38713a80-cf75-11eb-9611-6fc9d84fcda8.png)

**Comment by DavidXanatos** [comment]
it means that if you check this box and in future try to start this program unsandboxed it will automatically be put into this sandbox no mather how it was started.

**Comment by sixiansheng** [comment]
> it means that if you check this box and in future try to start this program unsandboxed it will automatically be put into this sandbox no mather how it was started.

Thank you. I know what it means. Thank you😊
