### ISSUE TITLE
google detecting sandbox releases tab as a virus

### ISSUE THREAD

**Issue by huzunluartemis** [sandboxie-plus/Sandboxie#919]
![resim](https://user-images.githubusercontent.com/84624971/122381594-c4816300-cf71-11eb-80d1-f764f8797c47.png)

https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2Fsandboxie-plus%2FSandboxie%2Freleases

**Comment by isaak654** [comment]
It's a known issue, please help us to report it as false positive to Google and Virustotal (read here):
https://github.com/sandboxie-plus/Sandboxie/issues/847#issuecomment-845918141
