### ISSUE TITLE
Adding a description to the UI for "do you want to put the sandbox folder into its parent directory?"

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#924]
**Is your feature request related to a problem? Please describe.**
Now that #916 clarified this UI question, please add the explanation to the UI itself to clarify it.

**Describe the solution you'd like**
Having this UI message instead:
> Sandbox-Plus was started in portable mode in {folder}
> Do you want to create the sandbox folder into its parent directory as {parent folder}\Sandbox?
> Choosing No means it'll use C:\Sandbox as usual.

**Additional context**
The current UI message:
![image](https://user-images.githubusercontent.com/1773306/122277263-619ab800-ceee-11eb-94ed-ef63af2dedcc.png)

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/122607463-e3b7e780-d07a-11eb-8239-1458bfd24cf8.png)
like this?
will be in next build

**Comment by lwcorp** [comment]
I think it's not clear enough. It refers to a parent folder yet displays the original folder.
Also, I think it should be mentioned what happens if you click No.

Maybe:

> ...its parent directory?
> 
> Yes will choose C:\Projects\SandboxiePlus\Sandbox
> No will choose C:\Sandbox

**Comment by DavidXanatos** [comment]
ok
![grafik](https://user-images.githubusercontent.com/3890945/122638063-38e31000-d0f2-11eb-89ca-25949ce4cda7.png)

**Comment by isaak654** [comment]
I would also replace the first "SandBox" in the second line to "Sandbox".

**Comment by DavidXanatos** [comment]
ok

**Comment by lwcorp** [comment]
Much better, thanks! But if the executable resides at `C:\Projects\SandboxiePlus\SandboxiePlus\x64`, shouldn't Yes mean `C:\Projects\Sandboxie\SandboxiePlus\Sandbox`?
