### ISSUE TITLE
Can't reset configuration password

### ISSUE THREAD

**Issue by p1r473** [sandboxie-plus/Sandboxie#925]
**Describe the bug**
Hello,
I can't find a way to remove the configuration password even after a full uninstallation
I set a 100 character password that isnt working. Either the max password length is 64, or I saved it incorrectly in my password manager. Either way I am locked out
I have tried to uninstall it even with RevoUninstaller which also deletes leftover registry keys
I don't really want to reformat so I can resume using Sandboxie

**To Reproduce**
1. Set 100 character configuration password, or just forget your password
2. Can't log in because the app might have a  hardcoded 64 character limit or because you forgot password
3. Uninstall
4. Reinstall
5. Password remains, still locked out

**Expected behavior**
Configuration password should be removed on uninstallation

**Screenshots**
![image](https://user-images.githubusercontent.com/9235633/122629997-c4c35080-d08e-11eb-96f5-f43e21e40f0c.png)

If you can't help me, I will have to reformat, and that is not really ideal
**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? Windows 10 X64
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2). Sandboxie Plus  0.8.2

**Additional context**
The reason I may believe my password length is the issue is because I found in the code a hardcoded limit of 64 characters and I used a 100 character password
```
         wmemcpy(req->new_password, NewPassword66, 64);
         req->new_password[65] = L'\0';
```

I've even tried to log in with the first 64 characters of my 100 character password but still locked out

**Comment by p1r473** [comment]
I've tried deleting the .ini files where EditPassword= was saved but that doesn't remove it either

**Comment by DavidXanatos** [comment]
There actually is a simple way around that use the Stop All command from the Sandman UI to stop the service and the driver,
and that disables the protection of sandboxie.ini than you can edit it with notepad and restart sandboxie

This password feature is really something rather to keep the lid on non administrative users.

You could probably also use a tool like LockHunter to unlock the sandboxie.ini edit it and reboot the pc.

The architecture is not meant to provide adequate defenses against users with administrative privileges.

**Comment by DavidXanatos** [comment]
ps will add the check to the next build
