### ISSUE TITLE
Sandboxie directs help for SBIE errors to non-existing web pages

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#93]
* Windows 10.0.18363
* Sandboxie from SandboxieInstall64-v5.42

1. Cause any SBIE error in sandboxie
2. On the "Message from Sandboxie" dialog, select "Help"
3. On the "Open Web Browser" dialog Select to open the URL
   Example: https://www.sandboxie.com/index.php?SBIE2331
4. Bug: The website shows an XML formatted response, "Access Denied"

Proposal:
* Use SBIE pages from Issue #31: Sandboxie Website Archive, to create a permanent static set of pages and change the target URL in Sandboxie for help pages.

**Comment by DavidXanatos** [comment]
I will redirect the urls to xanasoft.com/sandboxie in the next build

**Comment by typpos** [comment]
It might reduce your future workload if you host these directly on github, either as part of the main project or a separate project or "github pages". That way people can issue pull requests and they're closer to the code base.

**Comment by DavidXanatos** [comment]
As the redirection is in place and the messages are ported to my homepage I'll close this issue
