### ISSUE TITLE
Vivaldi Browser Issue - PDF's not Loading/Displaying

### ISSUE THREAD

**Issue by Numbat2913** [sandboxie-plus/Sandboxie#930]
Hi David,

Thanks for all your work on keeping the Sandboxie project going it is much appreciated.

I have been a Sandboxie user since 2012 and it has saved me, my clients, friends and family
from malware countless number of times over the years and myself from having to do call-outs
to rid computers of infections.  I have tried other virtualization software and keep on coming
back to Sandboxie for it's simplicity and usability especially for less savvy users (most of the
time I have installed it for others the default settings are sufficient).

But I have an issue with Vivaldi Browser not displaying PDF's (BTW MS Edge seems fine).
It tries to load the PDF but it states it "Couldn't load plugin".
It works fine when Vivaldi is not sandboxed, the issue is only when it is sandboxed.
I think the issue started around Sandboxie Plus/Classic release 0.80/5.50.0, but not 100% sure
on that. Also I have had other's report the same issue to me so I am not the only one.

Just so you know I  also created a clean sandbox profile, opened Vivaldi in it with no extentions running that and that did not fix the issue either.

Hope you can help and all the best for the future.

Setup at this end as follows:
Windows 10Pro 21H1 OS Build: 19043.1055
Vivaldi 4.0.2312.33 (Stable channel) (64-bit)
Sandboxie Classic 5.50.2 (64bit)
Bitdefender Total Security: Build 25.0.21.78

Test PDF Site: http://www.orimi.com/pdf-test.pdf

**Comment by isaak654** [comment]
@DavidXanatos 
I wanted to mention that Brave has a similar issue in #817, so it could be the same issue.

**Comment by Numbat2913** [comment]
@isaak654 
Thanks, I checked out the Brave issue at #817 and it seems very similar, hope it is fixed soon :-)

**Comment by isaak654** [comment]
I can reproduce it on most Sandboxie versions (including Plus 0.2), that means it's the current Vivaldi version that broke the compatibility with Sandboxie.
