### ISSUE TITLE
SB 5.50.2 breaks some more installers

### ISSUE THREAD

**Issue by Smurf451** [sandboxie-plus/Sandboxie#933]
### Setup
Windows 10 20H2 64bit
Sandboxie Classic 5.50.2

### Issue
All anomaly installers cannot run in 5.50.2
There are no error messages from Sandboxie, the installer just stops.
The issue is related to #595 and #906

The installer itself seems to be made with Python.
I've captured the log from the Resource Access Monitor, if that helps:

(Drive)     \Device\HarddiskVolume10; PID: 10720
(Drive)     \Device\HarddiskVolume10; PID: 12380
(Drive)     \Device\HarddiskVolume10; PID: 12848
(Drive)     \Device\HarddiskVolume10; PID: 2124
(Drive)     \Device\HarddiskVolume10; PID: 5868
(Drive)     \Device\HarddiskVolume10; PID: 7880
(Drive)     \Device\HarddiskVolume4; PID: 10720
(Drive)     \Device\HarddiskVolume4; PID: 12380
(Drive)     \Device\HarddiskVolume4; PID: 12848
(Drive)     \Device\HarddiskVolume4; PID: 2124
(Drive)     \Device\HarddiskVolume4; PID: 5868
(Drive)     \Device\HarddiskVolume4; PID: 7880
(Drive)     \Device\HarddiskVolume6; PID: 10720
(Drive)     \Device\HarddiskVolume6; PID: 12380
(Drive)     \Device\HarddiskVolume6; PID: 12848
(Drive)     \Device\HarddiskVolume6; PID: 2124
(Drive)     \Device\HarddiskVolume6; PID: 5868
(Drive)     \Device\HarddiskVolume6; PID: 7880
(Drive)     \Device\HarddiskVolume8; PID: 10720
(Drive)     \Device\HarddiskVolume8; PID: 12380
(Drive)     \Device\HarddiskVolume8; PID: 12848
(Drive)     \Device\HarddiskVolume8; PID: 2124
(Drive)     \Device\HarddiskVolume8; PID: 5868
(Drive)     \Device\HarddiskVolume8; PID: 7880
Clsid       -------------------------------
Clsid       {C2F03A33-21F5-47FA-B4BB-156362A2F239} Immersive Shell; PID: 5868
Clsid       {C2F03A33-21F5-47FA-B4BB-156362A2F239} Immersive Shell; PID: 7880
Clsid       Windows.Foundation.PropertyValue; PID: 5868
Clsid       Windows.Foundation.PropertyValue; PID: 7880
Clsid       Windows.Internal.StateRepository.FileTypeAssociation; PID: 5868
Clsid       Windows.Internal.StateRepository.FileTypeAssociation; PID: 7880
File        -------------------------------
File     X  \Device\HarddiskVolume4\WINDOWS\system32\apphelp.dll; PID: 12848
File     X  \Device\HarddiskVolume4\WINDOWS\System32\apphelp.dll; PID: 12848
File     X  \Device\HarddiskVolume4\WINDOWS\System32\apphelp.dll; PID: 5868
File     X  \Device\HarddiskVolume4\WINDOWS\SYSTEM32\apphelp.dll; PID: 5868
File     X  \Device\HarddiskVolume4\WINDOWS\system32\apphelp.dll; PID: 5868
File     X  \Device\HarddiskVolume4\WINDOWS\System32\apphelp.dll; PID: 5868
File     X  \Device\HarddiskVolume4\WINDOWS\system32\apphelp.dll; PID: 7880
File     X  \Device\HarddiskVolume4\WINDOWS\SYSTEM32\apphelp.dll; PID: 7880
File     X  \Device\HarddiskVolume4\WINDOWS\System32\apphelp.dll; PID: 7880
Image       -------------------------------
Ipc         -------------------------------
Ipc         \BaseNamedObjects\__ComCatalogCache__; PID: 10720
Ipc         \BaseNamedObjects\__ComCatalogCache__; PID: 2124
Ipc         \BaseNamedObjects\__ComCatalogCache__; PID: 5868
Ipc         \BaseNamedObjects\__ComCatalogCache__; PID: 7880
Ipc         \BaseNamedObjects\{A3BD3259-3E4F-428a-84C8-F0463A9D3EB5}; PID: 2124
Ipc         \BaseNamedObjects\{A64C7F33-DA35-459b-96CA-63B51FB0CDB9}; PID: 2124
Ipc         \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000008.db; PID: 5868
Ipc         \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000008.db; PID: 7880
Ipc         \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000008.db; PID: 5868
Ipc         \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000008.db; PID: 7880
Ipc         \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro; PID: 5868
Ipc         \BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro; PID: 7880
Ipc         \BaseNamedObjects\RotHintTable; PID: 2124
Ipc         \BaseNamedObjects\SC_AutoStartComplete; PID: 10720
Ipc         \BaseNamedObjects\SC_AutoStartComplete; PID: 7880
Ipc         \BaseNamedObjects\windows_shell_global_counters; PID: 5868
Ipc         \BaseNamedObjects\windows_shell_global_counters; PID: 7880
Ipc         \RPC Control\actkernel; PID: 10720
Ipc         \RPC Control\actkernel; PID: 2124
Ipc         \RPC Control\epmapper; PID: 10720
Ipc         \RPC Control\epmapper; PID: 12380
Ipc         \RPC Control\epmapper; PID: 12848
Ipc         \RPC Control\epmapper; PID: 2124
Ipc         \RPC Control\epmapper; PID: 5868
Ipc         \RPC Control\epmapper; PID: 7880
Ipc         \RPC Control\OLE6250D5AC9C8AF39EBB5F320B967E; PID: 5868
Ipc         \RPC Control\OLEB473B186A824B38386A13E2329A1; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\__ComCatalogCache__; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\__ComCatalogCache__; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\__ComCatalogCache__; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\__ComCatalogCache__; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\{A3BD3259-3E4F-428a-84C8-F0463A9D3EB5}; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\{A64C7F33-DA35-459b-96CA-63B51FB0CDB9}; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000008.db; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000008.db; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000008.db; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*{DDF571F2-BE98-426D-8288-1A9A39C3FDA2}.2.ver0x0000000000000008.db; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\C:*ProgramData*Microsoft*Windows*Caches*cversions.2.ro; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*{3DA71D5A-20CC-432F-A115-DFE92379E91F}.3.ver0x0000000000000894.db; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*{3DA71D5A-20CC-432F-A115-DFE92379E91F}.3.ver0x0000000000000894.db; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x00000000000002d1.db; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x00000000000002d1.db; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*cversions.1.ro; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*cversions.1.ro; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*cversions.3.ro; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\C:*Users*******AppData*Local*Microsoft*Windows*Caches*cversions.3.ro; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\ComPlusCOMRegTable; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\RotHintTable; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_10720; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_12380; PID: 12380
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_12848; PID: 12848
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_2124; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_5868; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_7880; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_RPCSS_SXS_READY; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_RPCSS_SXS_READY; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch; PID: 12380
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch; PID: 12848
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_Mutex1; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcEptMapper; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs; PID: 12380
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs; PID: 12848
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SboxSession; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SboxSession; PID: 12380
Ipc         \Sessions\1\BaseNamedObjects\SboxSession; PID: 12848
Ipc         \Sessions\1\BaseNamedObjects\SboxSession; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SboxSession; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SboxSession; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SC_AutoStartComplete; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SC_AutoStartComplete; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\ScmCreatedEvent; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SM0:10720:120:WilError_03; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SM0:10720:120:WilError_03_p0; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SM0:10720:120:WilError_03_p0h; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SM0:10720:304:WilStaging_02; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SM0:10720:304:WilStaging_02_p0; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SM0:10720:304:WilStaging_02_p0h; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\SM0:2124:120:WilError_03; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SM0:2124:120:WilError_03_p0; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SM0:2124:120:WilError_03_p0h; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SM0:2124:304:WilStaging_02; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SM0:2124:304:WilStaging_02_p0; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SM0:2124:304:WilStaging_02_p0h; PID: 2124
Ipc         \Sessions\1\BaseNamedObjects\SM0:5868:120:WilError_03; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SM0:5868:120:WilError_03_p0; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SM0:5868:120:WilError_03_p0h; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SM0:5868:304:WilStaging_02; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SM0:5868:304:WilStaging_02_p0; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SM0:5868:304:WilStaging_02_p0h; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SM0:7880:120:WilError_03; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SM0:7880:120:WilError_03_p0; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SM0:7880:120:WilError_03_p0h; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SM0:7880:304:WilStaging_02; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SM0:7880:304:WilStaging_02_p0; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SM0:7880:304:WilStaging_02_p0h; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\SyncRootManager; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\SyncRootManager; PID: 7880
Ipc         \Sessions\1\BaseNamedObjects\windows_shell_global_counters; PID: 10720
Ipc         \Sessions\1\BaseNamedObjects\windows_shell_global_counters; PID: 5868
Ipc         \Sessions\1\BaseNamedObjects\windows_shell_global_counters; PID: 7880
Ipc      O  \KernelObjects\MaximumCommitCondition; PID: 10720
Ipc      O  \KernelObjects\MaximumCommitCondition; PID: 2124
Ipc      O  \KernelObjects\MaximumCommitCondition; PID: 5868
Ipc      O  \KernelObjects\MaximumCommitCondition; PID: 7880
Ipc      O  \KnownDlls\advapi32.dll; PID: 10720
Ipc      O  \KnownDlls\advapi32.dll; PID: 12848
Ipc      O  \KnownDlls\advapi32.dll; PID: 2124
Ipc      O  \KnownDlls\advapi32.dll; PID: 5868
Ipc      O  \KnownDlls\advapi32.dll; PID: 7880
Ipc      O  \KnownDlls\bcrypt.dll; PID: 10720
Ipc      O  \KnownDlls\bcrypt.dll; PID: 2124
Ipc      O  \KnownDlls\bcrypt.dll; PID: 5868
Ipc      O  \KnownDlls\bcrypt.dll; PID: 7880
Ipc      O  \KnownDlls\bcryptPrimitives.dll; PID: 10720
Ipc      O  \KnownDlls\bcryptPrimitives.dll; PID: 2124
Ipc      O  \KnownDlls\bcryptPrimitives.dll; PID: 5868
Ipc      O  \KnownDlls\bcryptPrimitives.dll; PID: 7880
Ipc      O  \KnownDlls\cfgmgr32.dll; PID: 5868
Ipc      O  \KnownDlls\cfgmgr32.dll; PID: 7880
Ipc      O  \KnownDlls\clbcatq.dll; PID: 10720
Ipc      O  \KnownDlls\clbcatq.dll; PID: 2124
Ipc      O  \KnownDlls\clbcatq.dll; PID: 5868
Ipc      O  \KnownDlls\clbcatq.dll; PID: 7880
Ipc      O  \KnownDlls\combase.dll; PID: 10720
Ipc      O  \KnownDlls\combase.dll; PID: 12848
Ipc      O  \KnownDlls\combase.dll; PID: 2124
Ipc      O  \KnownDlls\combase.dll; PID: 5868
Ipc      O  \KnownDlls\combase.dll; PID: 7880
Ipc      O  \KnownDlls\COMDLG32.dll; PID: 5868
Ipc      O  \KnownDlls\COMDLG32.dll; PID: 7880
Ipc      O  \KnownDlls\CRYPT32.dll; PID: 12848
Ipc      O  \KnownDlls\gdi32.dll; PID: 10720
Ipc      O  \KnownDlls\gdi32.dll; PID: 12848
Ipc      O  \KnownDlls\gdi32.dll; PID: 2124
Ipc      O  \KnownDlls\gdi32.dll; PID: 5868
Ipc      O  \KnownDlls\gdi32.dll; PID: 7880
Ipc      O  \KnownDlls\gdi32full.dll; PID: 10720
Ipc      O  \KnownDlls\gdi32full.dll; PID: 12848
Ipc      O  \KnownDlls\gdi32full.dll; PID: 2124
Ipc      O  \KnownDlls\gdi32full.dll; PID: 5868
Ipc      O  \KnownDlls\gdi32full.dll; PID: 7880
Ipc      O  \KnownDlls\IMM32.dll; PID: 10720
Ipc      O  \KnownDlls\IMM32.dll; PID: 12848
Ipc      O  \KnownDlls\IMM32.dll; PID: 2124
Ipc      O  \KnownDlls\IMM32.dll; PID: 5868
Ipc      O  \KnownDlls\IMM32.dll; PID: 7880
Ipc      O  \KnownDlls\kernel32.dll; PID: 10720
Ipc      O  \KnownDlls\kernel32.dll; PID: 12380
Ipc      O  \KnownDlls\kernel32.dll; PID: 12848
Ipc      O  \KnownDlls\kernel32.dll; PID: 2124
Ipc      O  \KnownDlls\kernel32.dll; PID: 5868
Ipc      O  \KnownDlls\kernel32.dll; PID: 7880
Ipc      O  \KnownDlls\kernelbase.dll; PID: 10720
Ipc      O  \KnownDlls\kernelbase.dll; PID: 12848
Ipc      O  \KnownDlls\kernelbase.dll; PID: 2124
Ipc      O  \KnownDlls\kernelbase.dll; PID: 5868
Ipc      O  \KnownDlls\kernelbase.dll; PID: 7880
Ipc      O  \KnownDlls\MSCTF.dll; PID: 10720
Ipc      O  \KnownDlls\msvcp_win.dll; PID: 10720
Ipc      O  \KnownDlls\msvcp_win.dll; PID: 12848
Ipc      O  \KnownDlls\msvcp_win.dll; PID: 2124
Ipc      O  \KnownDlls\msvcp_win.dll; PID: 5868
Ipc      O  \KnownDlls\msvcp_win.dll; PID: 7880
Ipc      O  \KnownDlls\MSVCRT.dll; PID: 10720
Ipc      O  \KnownDlls\MSVCRT.dll; PID: 12848
Ipc      O  \KnownDlls\MSVCRT.dll; PID: 2124
Ipc      O  \KnownDlls\MSVCRT.dll; PID: 5868
Ipc      O  \KnownDlls\MSVCRT.dll; PID: 7880
Ipc      O  \KnownDlls\ole32.dll; PID: 10720
Ipc      O  \KnownDlls\ole32.dll; PID: 12848
Ipc      O  \KnownDlls\ole32.dll; PID: 5868
Ipc      O  \KnownDlls\ole32.dll; PID: 7880
Ipc      O  \KnownDlls\OLEAUT32.dll; PID: 10720
Ipc      O  \KnownDlls\OLEAUT32.dll; PID: 2124
Ipc      O  \KnownDlls\OLEAUT32.dll; PID: 5868
Ipc      O  \KnownDlls\OLEAUT32.dll; PID: 7880
Ipc      O  \KnownDlls\PSAPI.DLL; PID: 10720
Ipc      O  \KnownDlls\PSAPI.DLL; PID: 12848
Ipc      O  \KnownDlls\PSAPI.DLL; PID: 2124
Ipc      O  \KnownDlls\PSAPI.DLL; PID: 5868
Ipc      O  \KnownDlls\PSAPI.DLL; PID: 7880
Ipc      O  \KnownDlls\rpcrt4.dll; PID: 10720
Ipc      O  \KnownDlls\rpcrt4.dll; PID: 12848
Ipc      O  \KnownDlls\rpcrt4.dll; PID: 2124
Ipc      O  \KnownDlls\rpcrt4.dll; PID: 5868
Ipc      O  \KnownDlls\rpcrt4.dll; PID: 7880
Ipc      O  \KnownDlls\sechost.dll; PID: 10720
Ipc      O  \KnownDlls\sechost.dll; PID: 12848
Ipc      O  \KnownDlls\sechost.dll; PID: 2124
Ipc      O  \KnownDlls\sechost.dll; PID: 5868
Ipc      O  \KnownDlls\sechost.dll; PID: 7880
Ipc      O  \KnownDlls\SHCORE.dll; PID: 10720
Ipc      O  \KnownDlls\SHCORE.dll; PID: 5868
Ipc      O  \KnownDlls\SHCORE.dll; PID: 7880
Ipc      O  \KnownDlls\SHELL32.dll; PID: 10720
Ipc      O  \KnownDlls\SHELL32.dll; PID: 5868
Ipc      O  \KnownDlls\SHELL32.dll; PID: 7880
Ipc      O  \KnownDlls\SHLWAPI.dll; PID: 10720
Ipc      O  \KnownDlls\SHLWAPI.dll; PID: 5868
Ipc      O  \KnownDlls\SHLWAPI.dll; PID: 7880
Ipc      O  \KnownDlls\ucrtbase.dll; PID: 10720
Ipc      O  \KnownDlls\ucrtbase.dll; PID: 12848
Ipc      O  \KnownDlls\ucrtbase.dll; PID: 2124
Ipc      O  \KnownDlls\ucrtbase.dll; PID: 5868
Ipc      O  \KnownDlls\ucrtbase.dll; PID: 7880
Ipc      O  \KnownDlls\user32.dll; PID: 10720
Ipc      O  \KnownDlls\user32.dll; PID: 12380
Ipc      O  \KnownDlls\user32.dll; PID: 12848
Ipc      O  \KnownDlls\user32.dll; PID: 2124
Ipc      O  \KnownDlls\user32.dll; PID: 5868
Ipc      O  \KnownDlls\user32.dll; PID: 7880
Ipc      O  \KnownDlls\win32u.dll; PID: 10720
Ipc      O  \KnownDlls\win32u.dll; PID: 12848
Ipc      O  \KnownDlls\win32u.dll; PID: 2124
Ipc      O  \KnownDlls\win32u.dll; PID: 5868
Ipc      O  \KnownDlls\win32u.dll; PID: 7880
Ipc      O  \KnownDlls\wow64.dll; PID: 12380
Ipc      O  \KnownDlls\wow64cpu.dll; PID: 12380
Ipc      O  \KnownDlls\wow64win.dll; PID: 12380
Ipc      O  \KnownDlls\WS2_32.dll; PID: 10720
Ipc      O  \KnownDlls32\kernel32.dll; PID: 12380
Ipc      O  \KnownDlls32\kernelbase.dll; PID: 12380
Ipc      O  \KnownDlls32\MSVCRT.dll; PID: 12380
Ipc      O  \KnownDlls32\PSAPI.DLL; PID: 12380
Ipc      O  \KnownDlls32\rpcrt4.dll; PID: 12380
Ipc      O  \RPC Control\lsapolicylookup; PID: 10720
Ipc      O  \RPC Control\lsapolicylookup; PID: 2124
Ipc      O  \RPC Control\lsapolicylookup; PID: 5868
Ipc      O  \RPC Control\lsapolicylookup; PID: 7880
Ipc      O  \RPC Control\lsasspirpc; PID: 10720
Ipc      O  \RPC Control\lsasspirpc; PID: 2124
Ipc      O  \RPC Control\lsasspirpc; PID: 5868
Ipc      O  \RPC Control\lsasspirpc; PID: 7880
Ipc      O  \RPC Control\SbieSvcPort; PID: 10720
Ipc      O  \RPC Control\SbieSvcPort; PID: 12380
Ipc      O  \RPC Control\SbieSvcPort; PID: 12848
Ipc      O  \RPC Control\SbieSvcPort; PID: 2124
Ipc      O  \RPC Control\SbieSvcPort; PID: 5868
Ipc      O  \RPC Control\SbieSvcPort; PID: 7880
Ipc      O  \Security\LSA_AUTHENTICATION_INITIALIZED; PID: 10720
Ipc      O  \Security\LSA_AUTHENTICATION_INITIALIZED; PID: 2124
Ipc      O  \Security\LSA_AUTHENTICATION_INITIALIZED; PID: 5868
Ipc      O  \Security\LSA_AUTHENTICATION_INITIALIZED; PID: 7880
Ipc      O  \Sessions\1\Windows\ApiPort; PID: 10720
Ipc      O  \Sessions\1\Windows\ApiPort; PID: 12380
Ipc      O  \Sessions\1\Windows\ApiPort; PID: 12848
Ipc      O  \Sessions\1\Windows\ApiPort; PID: 2124
Ipc      O  \Sessions\1\Windows\ApiPort; PID: 5868
Ipc      O  \Sessions\1\Windows\ApiPort; PID: 7880
Ipc      O  \Sessions\1\Windows\SharedSection; PID: 10720
Ipc      O  \Sessions\1\Windows\SharedSection; PID: 12380
Ipc      O  \Sessions\1\Windows\SharedSection; PID: 12848
Ipc      O  \Sessions\1\Windows\SharedSection; PID: 2124
Ipc      O  \Sessions\1\Windows\SharedSection; PID: 5868
Ipc      O  \Sessions\1\Windows\SharedSection; PID: 7880
Ipc      O  \Sessions\1\Windows\Theme2469003638; PID: 10720
Ipc      O  \Sessions\1\Windows\Theme2469003638; PID: 5868
Ipc      O  \Sessions\1\Windows\Theme2469003638; PID: 7880
Ipc      O  \Sessions\1\Windows\ThemeSection; PID: 10720
Ipc      O  \Sessions\1\Windows\ThemeSection; PID: 5868
Ipc      O  \Sessions\1\Windows\ThemeSection; PID: 7880
Ipc      O  \ThemeApiPort; PID: 10720
Ipc      O  \ThemeApiPort; PID: 5868
Ipc      O  \ThemeApiPort; PID: 7880
Ipc      O  \Windows\Theme3571799876; PID: 10720
Ipc      O  \Windows\Theme3571799876; PID: 5868
Ipc      O  \Windows\Theme3571799876; PID: 7880
Key         -------------------------------
Other       CreateProcess: [noName] (.installer\pythonw.exe -m install); err=2; PID: 12380
Other       CreateProcess: C:\Sandboxie\SandboxieDcomLaunch.exe ("C:\Sandboxie\SandboxieDcomLaunch.exe"); err=0; PID: 10720
Other       CreateProcess: C:\Sandboxie\SbieSvc.exe ("C:\Sandboxie\SbieSvc.exe" Sandboxie_UacProxy:00001EC8_00007FF4_8F600108_0000015E_); err=0; PID: 5868
Other       CreateProcess: C:\Downloads\F N U H v20210619-ANOMALY\setup.exe ("C:\Downloads\F N U H v20210619-ANOMALY\setup.exe" ); err=0; PID: 12848
Other       CreateProcess: C:\Downloads\F N U H v20210619-ANOMALY\setup.exe ("C:\Downloads\F N U H v20210619-ANOMALY\setup.exe" ); err=740; PID: 7880
Other       StartService: pcasvc; PID: 7880
Pipe        -------------------------------
Pipe        \Device\CNG; PID: 10720
Pipe        \Device\CNG; PID: 2124
Pipe        \Device\CNG; PID: 5868
Pipe        \Device\CNG; PID: 7880
Pipe        \Device\DeviceApi; PID: 5868
Pipe        \Device\DeviceApi; PID: 7880
Pipe        \Device\HarddiskVolume1; PID: 5868
Pipe        \Device\HarddiskVolume1; PID: 7880
Pipe        \Device\HarddiskVolume10; PID: 5868
Pipe        \Device\HarddiskVolume10; PID: 7880
Pipe        \Device\HarddiskVolume2; PID: 5868
Pipe        \Device\HarddiskVolume2; PID: 7880
Pipe        \Device\HarddiskVolume4; PID: 5868
Pipe        \Device\HarddiskVolume4; PID: 7880
Pipe        \Device\HarddiskVolume6; PID: 5868
Pipe        \Device\HarddiskVolume6; PID: 7880
Pipe        \Device\HarddiskVolume8; PID: 5868
Pipe        \Device\HarddiskVolume8; PID: 7880
Pipe        \Device\KsecDD; PID: 10720
Pipe        \Device\KsecDD; PID: 2124
Pipe        \Device\KsecDD; PID: 5868
Pipe        \Device\KsecDD; PID: 7880
Pipe        \Device\MountPointManager; PID: 5868
Pipe        \Device\MountPointManager; PID: 7880
Pipe        \Device\Ndis; PID: 10720
Pipe        \Device\NDMP1; PID: 10720
Pipe        \Device\NDMP2; PID: 10720
Pipe        \Device\NDMP3; PID: 10720
Pipe        \Device\NDMP4; PID: 10720
Pipe        \Device\NDMP5; PID: 10720
Pipe        \Device\NDMP6; PID: 10720
Pipe        \Device\NDMP7; PID: 10720
Pipe        \Device\NDMP8; PID: 10720
Pipe        \Device\NDMP9; PID: 10720
WinCls      -------------------------------
WinCls      $:explorer.exe; PID: 5868
WinCls      Progman; PID: 5868
WinCls      Sandboxie_DDE_ProxyClass1; PID: 10720
WinCls   O  Shell_TrayWnd; PID: 10720
WinCls   X  Progman; PID: 5868

**Comment by DavidXanatos** [comment]
can you post a download link to an affected instaler

**Comment by Smurf451** [comment]
Here is the [dowload link](https://mega.nz/file/HwxjDIDZ#rUtgSsJ4dcMk23ZxpFk3fRT6nvDwIJK3M0cbVTEh4MY).
Please let me know when you got it.

**Comment by DavidXanatos** [comment]
I have downloaded the file will try it out shorty, can you tell me what was the last sbie version that it worked with

**Comment by DavidXanatos** [comment]
seam to also crash on the last sophos build

**Comment by DavidXanatos** [comment]
emmm. .... i tryed runnign it without a sandbox on 21H1 and it also crashed,
so it may not be a sbie issue at all.

**Comment by DavidXanatos** [comment]
since there is no more feadback and on my tests it crahed even without sbie I'll close this one
