### ISSUE TITLE
Vivaldi still doesn't launch with Sandboxie Classic 5.50.2

### ISSUE THREAD

**Issue by Astrohere** [sandboxie-plus/Sandboxie#943]
Vivaldi 3.7.2218.45 (Stable channel) (64-bit) works fine as a Standalone, but anything over doesn't want to launch at all.

All other programs run fine, in and out of the sandbox. And newer versions of Vivaldi does run when outside of the sandbox.

Using:
Sandboxie Classic 5.50.2
Windows 8.1 64 bit
Comodo Internet Security Premium 12.2.2.7098
ExpressVPN 10.3.0(23)
Vivaldi Browser 3.7.2218.45

**Comment by Astrohere** [comment]
Update:

After installing the latest Sandboxie Classic 5.50.5 64 bit with the latest Vivaldi browser 4.1.2345.3 (Official Build) (64-bit), Vivaldi once again open up Sandboxed in Windows 8.1 64 bit.

**Comment by DavidXanatos** [comment]
great to i can close this issue
