### ISSUE TITLE
Using GeForce Experience's shadowplay to capture sandboxed game 

### ISSUE THREAD

**Issue by johndoe84329** [sandboxie-plus/Sandboxie#944]
It's not an issue, but a question. Is it possible to capture video and photo with GeForce Experience from sandboxed game?
GeForce Experience is running outside sandbox. Game is sandboxed.

**Comment by DavidXanatos** [comment]
I haven't tried it but i would bet on it working.
The isoaltion is mostly one way so an unsandboxed process should have full access to a sandboxed game
