### ISSUE TITLE
Sanboxies crashed on Win8.1 x86 when i try to run a program in box.

### ISSUE THREAD

**Issue by MCSE-2000** [sandboxie-plus/Sandboxie#945]
Sanboxies crashed on Win8.1 x86 when i try to run a program in box.

I use sandboxies-plus 0.82 on Windows 8.1 Enterprise - X86-based PC Version 6.3.9600.

When i right click in the GUI on the "DefaultBox" and then click on "RUN".
Then popup the Window "[#] Run Sanboxed - DefaultBox [#]" and the Window "SandBox Manager - SandboxManager funktioniert nicht mehr".

![2021-06-27 17_10_17-SandBox Manager](https://user-images.githubusercontent.com/84094043/123550349-63297300-d76d-11eb-98a8-3ebf23eb6381.png)

This is the message in application event:
Protokollname: Application
Quelle:        Application Error
Datum:         27.06.2021 17:00:35
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      WIN8VHD
Beschreibung:
Name der fehlerhaften Anwendung: SandMan.exe, Version: 0.8.2.0, Zeitstempel: 0x60c8dc81
Name des fehlerhaften Moduls: QSbieAPI.dll, Version: 0.8.2.0, Zeitstempel: 0x60c8dc61
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0001df5e
ID des fehlerhaften Prozesses: 0x634
Startzeit der fehlerhaften Anwendung: 0x01d76b651e3a4b5d
Pfad der fehlerhaften Anwendung: C:\Program Files\Sandboxie-Plus\SandMan.exe
Pfad des fehlerhaften Moduls: C:\Program Files\Sandboxie-Plus\QSbieAPI.dll
Berichtskennung: 6c989511-d758-11eb-97ab-0022431d12a8
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by isaak654** [comment]
Continuation of this issue: #995
