### ISSUE TITLE
Update icon suggestion

### ISSUE THREAD

**Issue by jojoharry16** [sandboxie-plus/Sandboxie#947]
I don't know how to leave a pull request, but I made an upres'd start-icon.ico file

https://user-images.githubusercontent.com/39400627/123954069-7ae43f80-d997-11eb-9544-f2ba89902a9a.png
_Image was too big to be attached, so I replaced it with its link - isaak654_

If anyone wants to make a pull request or suggest changes, I'm fine with anything

**Comment by DavidXanatos** [comment]
is that for classic or plus?
for classic I'm not sure if we should change it,
for plus it must look more plus like.

**Comment by jojoharry16** [comment]
> is that for classic or plus?

Honestly, I just made it for myself since the pixelated large icon was annoying me, and I thought if anyone else felt the same way there's now an HD version available
