### ISSUE TITLE
Unable to mount ISO inside sandbox

### ISSUE THREAD

**Issue by droped** [sandboxie-plus/Sandboxie#952]
**Describe the bug**
I'm attempting to mount an ISO using windows 10's own ISO mounting ability and I can't do it from inside the sandbox.

**To Reproduce**
1. Run explorer.exe inside a sandbox
2. Mount an ISO inside the sandbox
3. Error when mounting

**Expected behavior**
I would expect the ISO to be mounted inside the sandbox.

**System details and installed software (please provide the following information):**
 - Windows 10 Home 21H1
 - Sandboxie-Plus Version 0.8.2 (I've only ever used this version so I don't know if it ever worked in the past)
 - Windows defender

**Additional context**
I could potentially mount the ISO outside of the sandbox (didn't try, don't have a safe installable ISO on my pc) and run it from inside the sandbox but it sounds like a security risk. Also, Sandboxie is in portable mode.

**Sandboxie configuration**

<details>
 
<summary>My current sandboxie.ini settings</summary>
 
````

[GlobalSettings]

FileRootPath=D:\Programas\Windows\Sandboxie\Sandbox\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=RpcPortBindings
TemplateReject=WindowsLive
TemplateReject=OfficeLicensing
TemplateReject=OfficeClickToRun

[UserSettings_0C81031C]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[Temporary]

Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
DropAdminRights=y
ClosePrintSpooler=y
BoxNameTitle=n
FakeAdminRights=y
CopyLimitKb=81920
HideOtherBoxes=y
AutoDelete=y

</details>

**Comment by DavidXanatos** [comment]
hmm.... 
this will not work...
the iso and more general volume mounting system of windows is part of the kernel and cant be reasnoably virtualized

**Comment by droped** [comment]
You don't happen to know any program that emulates iso mounting without installing a driver, right?

Every single iso mounting program that I tested required a driver and those don't work inside Sandboxie.

**Comment by DavidXanatos** [comment]
Well for mounting you need a driver, I mean if I really wanted I could simulate the behavior of mounting something in the sandbox but that's a lot of work for very little benefit.

You could use a program like 7zip to brows the content of an iso and to extract individual files.
Also there is not really any risk in mounting an iso unsandboxed, as long as you run the files from it sandboxed.
You could set the mounting letter as a forced folder that would enforce all the files form there being run sandboxed

**Comment by droped** [comment]
Ok, thank you. Thankfully the iso I was testing did not require mounting, only extraction, so I found a way eventually.
