### ISSUE TITLE
Error deleting sandbox folder  plus-v0.8.2

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#954]
using latest sandboxie-plus v0.8.2

when click "delete content" with programs open this happen: 
all programs close, then message pops up "Error deleting sandbox folder" and no file is deleted
if we click "delete content" again message doesn't pop up and files are properly deleted

this issue doesn't occur on sandboxie classic

you have to fix this issue as it's a basic feature of sandboxie

**Comment by diieg707** [comment]
sandboxie plus is great but this annoying bugs ruin the experience

**Comment by DavidXanatos** [comment]
i cant reproduce it but i added a retry that should fix the issue in such edge cases
