### ISSUE TITLE
[BUG] UI of Sandboxie Classic appears in Sandboxie Plus after staring with Start.exe

### ISSUE THREAD

**Issue by dingwen07** [sandboxie-plus/Sandboxie#957]
**Describe the bug**
If Sandboxie Plus is not running, launch any program using `Start.exe` (like shortcuts) will cause Sandboxie Classic being used instead of Sandboxie Plus UI.

**To Reproduce**
1. Create a shortcut of any program
2. Exit Sandboxie Plus from tray
3. Invoke the shortcut

**Expected behavior**
Sandboxie Classic UI should not shown

**Comment by DavidXanatos** [comment]
Well its not a bug, its a miss configuration

![grafik](https://user-images.githubusercontent.com/3890945/124379968-86e34080-dcba-11eb-85b7-56edc31c5c2c.png)

uncheck apply, check and apply again this option to resolve the issue

**Comment by dingwen07** [comment]
> Well its not a bug, its a miss configuration
> 
> ![grafik](https://user-images.githubusercontent.com/3890945/124379968-86e34080-dcba-11eb-85b7-56edc31c5c2c.png)
> 
> uncheck apply, check and apply again this option to resolve the issue

It is not expected that the old Sandboxie Classic UI will be launched with this settings enabled.

**Comment by DavidXanatos** [comment]
true but iirc this situation can appear only when switching from classic to plus, i can make the check box dispaly a intermeiate state for this case?

**Comment by DavidXanatos** [comment]
hmm.... there is somethign strange, sandman should always set SbieCtrl_AutoStartAgent=SandMan.exe if the setting wasnt already set
can you check your sandboxie ini whats under this option?

**Comment by dingwen07** [comment]
> hmm.... there is somethign strange, sandman should always set SbieCtrl_AutoStartAgent=SandMan.exe if the setting wasnt already set
> can you check your sandboxie ini whats under this option?

I have `SbieCtrl_AutoStartAgent=SandMan.exe` in the config

**Comment by DavidXanatos** [comment]
then i don't see why it would start the old ui

**Comment by isaak654** [comment]
@dingwen07 Did you upgrade from an old version? We need exact steps to reproduce it always.

**Comment by DavidXanatos** [comment]
there are multiple user sections for different users, are you sure the the SbieCtrl_AutoStartAgent entry was in your section, or that there is only one section?

**Comment by dingwen07** [comment]
> @dingwen07 Did you upgrade from an old version? We need exact steps to reproduce it always.

No, it's a fresh install.

**Comment by dingwen07** [comment]
I tested again after rebooting the system, and this issue no longer occurs.
