### ISSUE TITLE
[Feature request] Option to skip sandbox selection

### ISSUE THREAD

**Issue by daveout** [sandboxie-plus/Sandboxie#959]
Please add an option in the settings menu to skip the 'sandbox selection' window when an app is started from the context menu. Currently, we have to press 'ctrl' every time we want to skip that. Which is very inconvenient (and I believe that most ppl only use one sandbox anyway, the default one). Thank you.

**Comment by LennyFox** [comment]
It is better to use concrete seperated sandboxes. When reading Wilders Security and MalwareTips forums for Sandboxie that seems to be the best practice. Do you have your default Sandbox on default settings? What is the advantage of putting all programs in the same sandbox.

**Comment by daveout** [comment]
In my case, I don't deal with any type of sensitive info on the sandboxed apps, so I do mind if they access each other's data. I use the sandbox solely to protect the host from those apps. (for example, when I want to test an app that I casually downloaded from the internet).
