### ISSUE TITLE
Networking: Sandbox-local network access

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#96]
Various applications are implemented as a client-server model where 2 processes communicate with each other via sockets. Typical examples are computer games or business applications with license servers.

Feature proposal:
* Ability to allow applications inside a sandbox to communicate with each other through sockets even when network access by sandboxie is blocked.

Current workaround:
* Enable sandboxie network access
* Use Windows firewall outside sandboxie and block all applications inside the sandbox from accessing the network
* Risk: Error prone; Possibility to miss blocking an executable; inability to block dynamically created executable; does not prevent sandboxed applications from accessing outside-sandboxie-applications via open sockets.

**Comment by DavidXanatos** [comment]
further discussion on sandboxie's networking aspects please in issue #894
