### ISSUE TITLE
Bring back the access sandbox from tray menu feature

### ISSUE THREAD

**Issue by mercury233** [sandboxie-plus/Sandboxie#960]
In Classic, I can access the sandbox directly from the menu of the tray icon of Sandboxie Control
![image](https://user-images.githubusercontent.com/13391795/124525845-5b379600-de33-11eb-99f0-fc6238405e9f.png)

But in Plus, the tray don't have those menu.

**Comment by isaak654** [comment]
It was just added in Plus 0.8.7

**Comment by mercury233** [comment]
thank you!

**Comment by mercury233** [comment]
When I left click on the sandbox listed, nothing happens. Right click don't give useful functions too.

**Comment by isaak654** [comment]
Left click is needed only for selecting the sandbox first, right click comes afterwards:

<img alt="right_click_on_sandbox_tray" src="https://user-images.githubusercontent.com/12372772/125179886-8afbea80-e1f3-11eb-9e0c-e921328ef597.png" height="380">

**Comment by mercury233** [comment]
![GIF 2021-7-11 9-07-44](https://user-images.githubusercontent.com/13391795/125179992-910bbe80-e227-11eb-9874-c9ebd5170b46.gif)

I think I found a bug: If the sandman GUI wasn't inited(for example, autorun on windows start), the right menu of sandbox won't show fully

**Comment by isaak654** [comment]
I'm going to create a new issue for it.
