### ISSUE TITLE
Icon of Sandboxie PLUS is fuzzy, reason for people to stay with classic

### ISSUE THREAD

**Issue by LennyFox** [sandboxie-plus/Sandboxie#963]
**Is your feature request related to a problem? Please describe.**
As illustrated by these posts on MalwareTips, people find the Sandboxie plus icon fuzzy https://malwaretips.com/threads/benefits-of-using-a-sandbox-ie-sandboxie.108759/#post-947828 and less pronounced https://malwaretips.com/threads/benefits-of-using-a-sandbox-ie-sandboxie.108759/#post-947824

**Describe the solution you'd like**
A simpler icon for new sandboxie-plus

**Describe alternatives you've considered**
Use visual langauge of old sandboxie (color scheme) and combine it with the symbols of Sandbox (a sand spade) and Sandboxie plus (a plus), as explained in this post https://malwaretips.com/threads/benefits-of-using-a-sandbox-ie-sandboxie.108759/#post-949917

**Additional context**
It is a shame people stay on the old UI because of something silly as an icon. I hope a DTP-er will use the visual language elements explained below and design an appealing looking icon (I obviously have no DTP-skills). 

![image](https://user-images.githubusercontent.com/63356355/124577791-e32a9980-de4d-11eb-8948-44defef0f46d.png)

Icon on the left with the red plus means that a sandbox is running/active without the red plus in the shield shaped spade means that no sandbox is running/active.

**Explanation of visual language:**
Our eyes first recognize shapes, then color, then known images and symbols, then text. Therefore the old sandboxie icon (which looked more like a kite than a sandbox to me) has to go. Keeping the known old sandboxie color scheme has the advantage that old icon's color scheme was related to on-off status. Existing sandboxie users are familiar with this color scheme/function and are probably happy to see these trusted colors (subliminal effect).

Because the spade shade, looks very much like a shield and shields are used for security software and a spade is associated with a sandbox, this is a good "background" shape to use for a sandbox security program. The red plus is a direct connection to sandboxie plus new user interface.

**Comment by daveout** [comment]
It's very easy to change an app's icon using 'Resource Hacker'. 
The old icon looks like it was drawn by an 8yo on Windows 3.1's Paint.
I love the new icon and UI, and I hope it stays.

**Comment by DavidXanatos** [comment]
Well I'm not super happy with the current icon eider all the icons were changed some time ago for better looking once
I don't really want to use the old icon.

I'm thinking of using the old pizza icon for the plus tray still and only keep the other icon for the main exe...

Ofcause if someone with the graphical skills is willing to donate a great new icon to the project that would be great :)


PS: resource hacker will not help you with a Qt application it stors the resources differntly, so the oynly thing you can change tehr eis the exe icon but not the tray or internal icons

**Comment by LennyFox** [comment]
LOL de old icon was a pizza slice in stead of a (wind) kite!  

@DavidXanatos 
As explained in the visual language, I agree you don't want to use the the old icon.. What are you thoughts on

a) using the same color scheme (yellow red) as old Sandboxie

b) instead of a pizza-slice use a spade as background shape (looks like a shield associates to a sandbox)

c) using a plus sign in red whan a sandbox is active (obviously relating to your Sandboxie-Plus UI)?

**Comment by daveout** [comment]
I've made some mock-ups with icons from icons8 and icon-icons.com (just some possibilities).

![ui changes mockup](https://user-images.githubusercontent.com/54579499/125024291-d927b700-e056-11eb-9f32-204a4cf873b4.png)

**Comment by DavidXanatos** [comment]
the current one remade looks great, do you have it also as 16x16 one for the tray?

**Comment by daveout** [comment]
Well, I tried. Not sure if it looks very good tho. (i'm not a graphic designer or anything). Icons that small normally need to be drawn from scratch, not only downscaled, (however you can simply downscale the original icon if you find it looks better).

[icons for sandboxie.zip](https://github.com/sandboxie-plus/Sandboxie/files/6793087/icons.for.sandboxie.zip)

**Comment by DavidXanatos** [comment]
looks nice, for the tray we need also an empty icon i.e. without the sand

**Comment by DavidXanatos** [comment]
PS: fro tray would be best to have also a 32x32 icon scaled down that often looks better then a dedicated 16x16 icon

**Comment by DavidXanatos** [comment]
PPS: also a box with a green border looks better imho

**Comment by DavidXanatos** [comment]
![sb3d](https://user-images.githubusercontent.com/3890945/125123786-6c182e00-e0f7-11eb-958e-d0df1523a742.png)
![sb2d](https://user-images.githubusercontent.com/3890945/125123789-6cb0c480-e0f7-11eb-8e2b-999fd4523bc9.png)
![sb2](https://user-images.githubusercontent.com/3890945/125123791-6d495b00-e0f7-11eb-949a-396b27385dde.png)
![sb3](https://user-images.githubusercontent.com/3890945/125123792-6d495b00-e0f7-11eb-89f2-0acbac2a1593.png)
here is what I came up based on the icons provided

**Comment by daveout** [comment]
Glad you liked it. I kinda prefer the orange box tho. The "original.svg" file has all the image elements ungrouped and is relatively easy to edit (change form and color) using the appropriate software (like 'lunacy'). Here are so more icons, let me know if they need more tuning or if you need anything else.

[icons for sandboxie.zip](https://github.com/sandboxie-plus/Sandboxie/files/6793682/icons.for.sandboxie.zip)

**Comment by isaak654** [comment]
> 
> 
> ![sb3d](https://user-images.githubusercontent.com/3890945/125123786-6c182e00-e0f7-11eb-958e-d0df1523a742.png)
> ![sb2d](https://user-images.githubusercontent.com/3890945/125123789-6cb0c480-e0f7-11eb-8e2b-999fd4523bc9.png)
> ![sb2](https://user-images.githubusercontent.com/3890945/125123791-6d495b00-e0f7-11eb-949a-396b27385dde.png)
> ![sb3](https://user-images.githubusercontent.com/3890945/125123792-6d495b00-e0f7-11eb-89f2-0acbac2a1593.png)
> here is what I came up based on the icons provided

Just my opinion, I don't think I will enjoy the green border.

**Comment by isaak654** [comment]
Just my opinion, I don't think I will enjoy the green border on the icons.

**Comment by DavidXanatos** [comment]
@daveout What do you use to edit the svg files?
@isaak654  whats wrong with green?

**Comment by DavidXanatos** [comment]
PS: we would also need some box icons for the list, the one for the tray looks a bit to busy in the list
we should have

Hardened
Default
Lenient (i.e. less secure than default)
Insecure (like. totally please don't use insecure, for the case some debug options are active that disable parts of the isolation)

**Comment by DavidXanatos** [comment]
PPS: the dots in the sandbox should be red not orange ;)

**Comment by daveout** [comment]
i used lunacy (https://icons8.com/lunacy) but there are probably better ones. 

any ideas for how list boxes should be ?

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/125131639-53ae1080-e103-11eb-81da-f90c397602db.png)

that looks simple enough but may be to simple

**Comment by isaak654** [comment]
> @isaak654 whats wrong with green?

It looks like a meadow on a hill or green salad in a sandwich.

**Comment by DavidXanatos** [comment]
> 
> 
> > @isaak654 whats wrong with green?
> 
> @DavidXanatos
> It looks like a meadow on a hill or green salad in a sandwich.

i think the problem with the original yellow border is that yellow is well it looks very bright or white...
so on a bright background it will just look liek nothing so adding some contrast coller helps a lot.
Red is to agressive, blue to close to black, may be cyan or something? but than it looks strange

**Comment by isaak654** [comment]
> @isaak654 whats wrong with green?

@DavidXanatos 
It looks like a meadow on a hill or green salad in a sandwich.

**Comment by daveout** [comment]
> PS: we would also need some box icons for the list, the one for the tray looks a bit to busy in the list
> we should have
> 
> Hardened
> Default
> Lenient (i.e. less secure than default)
> Insecure (like. totally please don't use insecure, for the case some debug options are active that disable parts of the isolation)

Sometimes there are some red or green dots blinking on those list icons, (if I'm not mistaken) what do they mean? activity? programs running? attention needed ? Are there other signals that need representing ?

**Comment by DavidXanatos** [comment]
there are eider dots something is in the box or no dots box is not active there is no more indication there

**Comment by DavidXanatos** [comment]
btw: how to export to an *.ico file with multiple resolutions? lunacy makes only 50x50pix for me rignt now

**Comment by daveout** [comment]
This is probably not the most practical way but it is what I do: I export in PNG then I use [this site](https://redketchup.io/icon-converter) to adjust the ICO.

**Comment by daveout** [comment]
how about ?
![Screenshot 2021-07-09 175200](https://user-images.githubusercontent.com/54579499/125134840-6bbf6900-e0de-11eb-9d64-8862cff1f10c.png)

**Comment by DavidXanatos** [comment]
![IconEmpty](https://user-images.githubusercontent.com/3890945/125155679-d960a900-e161-11eb-9076-a7af21e5f57e.png)
![IconFull](https://user-images.githubusercontent.com/3890945/125155678-d8c81280-e161-11eb-8cef-6c8ae3be3582.png)
![SandMan32](https://user-images.githubusercontent.com/3890945/125155682-e087b700-e161-11eb-8e69-60e6f16aeeb7.png)
![SandMan48](https://user-images.githubusercontent.com/3890945/125155683-e1204d80-e161-11eb-899e-c3a2a8f329af.png)
![SandMan64](https://user-images.githubusercontent.com/3890945/125155684-e1204d80-e161-11eb-8a77-abdeb49a6f1f.png)
![SandMan96](https://user-images.githubusercontent.com/3890945/125155685-e1b8e400-e161-11eb-87f6-d1135fbd595e.png)
![SandMan](https://user-images.githubusercontent.com/3890945/125155671-c9e16000-e161-11eb-8bec-e716a7edeb60.png)


I think I'll with these

**Comment by daveout** [comment]
Looks great and should please everyone (those who miss the old visual identity and those who don't like the pizza icon).

**Comment by daveout** [comment]
[List icons.zip](https://github.com/sandboxie-plus/Sandboxie/files/6794936/List.icons.zip)

Icons for the list (in case you decide to use them).

**Comment by DavidXanatos** [comment]
About the icons I have to think what to do with the color scheme.
You see I want to have a usage mode for application packaging and no strict isolation.
So a box in which you run something you don't want to install or want to have multiple instances of, but with minimal isolation and maximal compatibility.
At the same time such a box should not look dangerous, I mean we could take blue...
but still idk... 
a green box suggests its safe, but at the same its the box most likely to contain something harmful...
While a box configured for minimal security is much more likely to contain harmless things.
This should somehow be reflected by the color scheme..

**Comment by NewKidOnTheBlock** [comment]
I'd like to remind everybody that the tray icon, while being strange*, also serves an actual function:
The red tomate dots indicate whether sandboxie is currently running.
When all sandboxes are inactive, it's just the yellow cheese.

* What's the relation between a sandbox and a slice of pizza?

**Comment by DavidXanatos** [comment]
the old icon is supposed to be an actual box of sand, but for many people it looks more like a pizza or a kite, as simple as that

The new icon tray features also red dots when in use.

**Comment by isaak654** [comment]
The new tray icon in 0.8.7 looks very small compared to the Windows Defender icon... I think that removing the purple shovel would help.

**Comment by isaak654** [comment]
P.S. If someone else has further improvements to suggest about the current icons, I might consider to reopen this issue.

**Comment by StoneMoe** [comment]
the current icon in the task bar has too much details, and shape is too complicated, which makes it not easy to recognize in such a small area.
and its active state only got a few red pixels different with the idle state.

Practicality of the old icon is more than the new one IMO.

**Comment by isaak654** [comment]
> 
> Practicality of the old icon is more than the new one IMO.

You mean the old Sandboxie Plus tray icon or the pizza tray icon on Classic edition?

**Comment by StoneMoe** [comment]
> You mean the old Sandboxie Plus tray icon or the pizza tray icon on Classic edition?

Both

**Comment by StoneMoe** [comment]
> You mean the old Sandboxie Plus tray icon or the pizza tray icon on Classic edition?

![image](https://user-images.githubusercontent.com/5786577/130092688-99929ae3-0417-4f70-848e-17b3bacaae08.png)
This one. it looks old and ugly, but it did its work really well.

**Comment by isaak654** [comment]
I've just published a method to change the icons on Sandboxie Plus: https://github.com/sandboxie-plus/Sandboxie/discussions/1130
That would help you if you want to test any new icons before proposing them to David.

**Comment by daveout** [comment]
Customizable icons sounds like a great idea.

**Comment by NewKidOnTheBlock** [comment]
No, just no.
There shouldn't be 5,000 Firefox Logos to choose from, there shouldn't be 5,000 Sandboxie Icons.

There should be one and it should be easily readable, recognizable and useful.

**Comment by daveout** [comment]
There should be a good default icon set, of course. But good according to whom? No icon set will ever please everyone. Customizability is the logical solution here.

And I don't see how allowing other users to customize THEIR copy of the software affects your life.

**Comment by DavidXanatos** [comment]
Look we need ed some sort of visual differentiation from the old version, 
For me the new icon looks good enough the old one was more distinct between active and inactive,
but for my plans with the app virtualization i expect people to have some boxes at least always running like one with skype and an other with whatsap atc, so the distinguishability of the full and empty icon is not that relevant.
Also in the past it was possible to run the plus UI and SbieCtrl side by side, somethign I think now is really obsolete, so i could really go for booth of them having the same tray icons.
I think for the next build I will just add an option to switch the Plus UI's tray icon between the new and the classical one and that should make everyone happy?

**Comment by isaak654** [comment]
> I think for the next build I will just add an option to switch the Plus UI's tray icon between the new and the classical one and that should make everyone happy?

That would be a start, but I would also propose to contact a professional designer to replace the default Plus icons in the long term. In this case, you could try to obtain an estimate of the sum you need and add a "One-time sponsorship tier" through [GitHub Sponsors](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/managing-your-sponsorship-tiers) for this job in order to convince more users to donate.

**Comment by isaak654** [comment]
> I think for the next build I will just add an option to switch the Plus UI's tray icon between the new and the classical one and that should make everyone happy?

That would be a start, but I would also propose to contact a professional designer to replace the default Plus icons in the long term. In this case, you could try to obtain an estimate of the sum you need and adding a "One-time sponsorship tier" for this job through [GitHub Sponsors](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/managing-your-sponsorship-tiers) in order to convince the users who want new icons to donate if they really want.

Of course you would also need to attach a number of possible mockups of the final icon set, because people wouldn't be happy to see unpleasant icons afterwards.

**Comment by daveout** [comment]
I like the idea of being able to use my own custom icons. So I prefer Isaak's workaround. (but both solutions could be implemented simultaneously.)

(Firefox's interface can be configured in [a similar way](https://www.howtogeek.com/334716/how-to-customize-firefoxs-user-interface-with-userchrome.css/): The user creates a folder and a file titled 'userChrome.css' and then adds code to that file in order to change the browser's interface. I use it to remove clutter, specially in the context menus.)

**Comment by DavidXanatos** [comment]
the build with the option to use old icons is out, can we please close this issue now?

**Comment by StoneMoe** [comment]
appreciate for new option! it's ok to me to close :D

> the build with the option to use old icons is out, can we please close this issue now?
