### ISSUE TITLE
add a switch configuration to  caller verification ??

### ISSUE THREAD

**Issue by 344389541** [sandboxie-plus/Sandboxie#964]
The v0.8.5 / 5.50.5 version of the driver adds caller verification, we will modify sbiesvc.exe and sbiedll.dll, but we do not have a signature, can we add a switch configuration to this function

![image](https://user-images.githubusercontent.com/26427035/124574779-631c2800-de7d-11eb-86a1-f2f4b1969925.png)

**Comment by DavidXanatos** [comment]
Yes you can or just comment out the check if you don't need it entirely in your build.

**Comment by 344389541** [comment]
hi, how to generate this .sig file?

**Comment by DavidXanatos** [comment]
https://github.com/processhacker/processhacker/tree/master/tools/CustomSignTool
