### ISSUE TITLE
SandMan.exe - No Disk error at Windows startup

### ISSUE THREAD

**Issue by Domochevsky** [sandboxie-plus/Sandboxie#966]
When SandMan.exe starts together with Windows, a modal error dialogue pops up (likely from Windows itself) to tell me that
_"There is no disk in the drive. Please insert a disk into drive \Device\Harddisk2\DR2"_

The "disk" in question appears to be my USB SD card reader. If I insert an SD card before system start it will not produce this error.

I don't know how to let others reproduce this. This started to occur out of nowhere a couple days ago. I suspect that this is not Sandboxie-specific. It's likely just the first program that stumbles over this by doing... something. But I am hoping that you can at least provide me with a hint of why this is occuring and what to do about it. The usual internet searches and subsequent random guesses have left me empty-handed.

![SandmanDR2](https://user-images.githubusercontent.com/6913626/124594081-a9628e80-de5f-11eb-9b5a-e51b09acdb93.png)

It does not matter which of these four buttons I press. They all make the dialogue disappear without issue. I'd classify this as "mild annoyance".

This is on Windows 7 HP 64 Bit.
Sandboxie Version: 0.8.2

**Comment by isaak654** [comment]
@Domochevsky 
1) Is 0.8.2 the first Plus release to present this bug?
2) Did you reproduce it on 0.8.8 too?

**Comment by Domochevsky** [comment]
1. I think so, yes. Could also be a type of coincidence. I am hesitant to install previous versions again.
2. I disabled the error message via registry by this point. I suspect it is still there; I just don't see it (since it doesn't seem to do anything either way.)

So... I guess this issue timed out from underneath us.

**Comment by isaak654** [comment]
I think it's a sort of incompatibility regarding Plus, the SD card reader and possibly a Windows 7 system.

Another user just had an issue like yours: 
https://www.wilderssecurity.com/threads/sandboxie-plus-0-8-8.438930/#post-3020679
https://www.wilderssecurity.com/threads/sandboxie-plus-0-8-8.438930/page-2#post-3020863
