### ISSUE TITLE
All upgrades from 0.8.2 need a reboot (KmdUtil error 1061)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#968]
**Expected behavior**
Upgrade from Plus 0.8.2 to Plus 0.8.6 sometimes needs a reboot, so I would suggest:
1) to provide a message like "The installation requires a reboot. Click Yes to restart now or No if you plan to restart later." in another release, in order to not induce people to think there is a problem
OR
2) to prevent the error 1061 and the chance of a further reboot

**To Reproduce**
1. Install Sandboxie Plus 0.8.6 over 0.8.2
2. I do a right-click -> Run sandboxed to any PDF file associated with Vivaldi, and I receive this:

![sandb2](https://user-images.githubusercontent.com/12372772/124730667-da030080-df11-11eb-84ba-6ce734973f3d.png)

3. I had to fix it with a manual reboot ~~+ a manual restore of the Vivaldi association to open PDF files with it. The last measure could have been avoided if I rebooted the system in time.~~

Windows 10 Pro 20H2
Sandboxie Plus 0.8.6
Windows Defender + GhostPress in background

**Comment by isaak654** [comment]
This reboot thing is still an issue when you upgrade from 0.8.6 to 0.8.7, so I decided to do a clean uninstall and a reinstall of 0.8.7 without any reboot involved. Fortunately it seems that I can't reproduce it in the last case... to be completely sure I'll need to wait the next release update.

**Comment by isaak654** [comment]
Upgrade from 0.8.7 to 0.8.7b still reproduces the error warning in first post, so it continues to be a consistent bug.

**Comment by isaak654** [comment]
Upgrade from 0.8.7 to 0.8.7b still reproduces the error warning in first post, so it continues to be a consistent bug.

If you can't prevent the error 1061 and the chance of a further reboot, at least provide a message like "The installation requires a reboot. Click Yes to restart now or No if you plan to restart later."

**Comment by d4k0** [comment]
Same problem here. This happened the first time when I updated from 0.8.2 to 0.8.6 I think. This problem is still present in version 0.8.7b. I have to reboot in order to not have the message displayed every time I start Sandboxie Plus.

Uninstalling the old version and installing the new version seems to be a workaround, but during uninstallation there is also an error message (something about Sandboxie not being able to control its service if I remember correctly).

**Comment by isaak654** [comment]
This new required reboot bothers me a lot, since I forget to reboot before the error and often when I have heavy programs running in the system.

**Comment by isaak654** [comment]
Upgrade from 0.8.7b to 0.8.8 went smooth and fixed the KmdUtil error 1061.

**Comment by d4k0** [comment]
> Upgrade from 0.8.7b to 0.8.8 went smooth and fixed the KmdUtil error 1061.

I can confirm this.

**Comment by d4k0** [comment]
@DavidXanatos 
This problem was reintroduced in version 0.8.9.

**Comment by isaak654** [comment]
> 
> 
> @DavidXanatos
> This problem was reintroduced in version 0.8.9.

I can't reproduce this time, unless you have the following Windows 7 issue: #1040

**Comment by d4k0** [comment]
@isaak654 
I'm on Windows 10 21H1 x64, so #1040 shouldn't be the problem.

After the upgrade from v0.8.8  to v0.8.9, I get this error message every time when I start Sandboxie Plus (the program also asks for admin rights):

![KmdUtil_2021-07-27_18-34-57](https://user-images.githubusercontent.com/10982825/127202865-214a3a95-1ad0-4856-b30b-912083354d31.png)

I haven't rebooted yet, but this will probably "fix" it again.

**Comment by isaak654** [comment]
@d4k0 
Plus v0.8.9 fixed another annoying issue that prevented the removal of shell integration keys during Sandboxie Plus uninstall, so it would be curious to know what happens if you uninstall 0.8.9 -> install 0.8.8 -> upgrade to 0.8.9 again.

Maybe that's the reason why I can't reproduce it anymore...

**Comment by d4k0** [comment]
@isaak654 
I tried your way (uninstall 0.8.9 -> install 0.8.8 -> upgrade to 0.8.9) as I was also curious about this, and it seems to have worked. During the uninstallation the error message I posted popped up again, but the Sandboxie service was removed nevertheless.

**Comment by isaak654** [comment]
Upgrade from 0.8.9 to 0.9.2 produces the KmdUtil error 1061, the only workaround to avoid a reboot is to uninstall 0.8.9 and install 0.9.2.

@bjm234

**Comment by isaak654** [comment]
Upgrade from 0.9.2 to 0.9.3 produces the KmdUtil error 1061, the only workaround to avoid a reboot is to uninstall 0.9.2 and install 0.9.3.

**Comment by bjm234** [comment]
> Upgrade from 0.9.2 to 0.9.3 produces the KmdUtil error 1061, the only workaround to avoid a reboot is to uninstall 0.9.2 and install 0.9.3.
Will 0.9.3 uninstall (retaining Sandboxie.ini) and 0.9.3 install ...sort 1061 for next upgrade.  Or, is over install new build + machine restart = best practice going forward?

**Comment by isaak654** [comment]
> Will 0.9.3 uninstall (retaining Sandboxie.ini) and 0.9.3 install ...sort 1061 for next upgrade. Or, is over install new build + machine restart = best practice going forward?

Uninstall of current Plus versions keep the ini files in their place because currently there is no option to remove them... this could change in a later version. Please check [here](https://git.io/JRREO) if you want to monitor the progress.

**Comment by bjm234** [comment]
> > Will 0.9.3 uninstall (retaining Sandboxie.ini) and 0.9.3 install ...sort 1061 for next upgrade. Or, is over install new build + machine restart = best practice going forward?
> 
> Uninstall of current Plus versions keep the ini files in their place because currently there is no option to remove them... this could change in a later version. Please check [here](https://git.io/JRREO) if you want to monitor the progress.

Hmm....does uninstall install any scenario sort 1061?

**Comment by isaak654** [comment]
> 
> Hmm....does uninstall install any scenario sort 1061?

Not forever, it's just a way to prevent the reboot... but it helps to fix possible shell integration issues that could be problematic if you upgrade a lot. For example, older Plus versions < 0.8.9 left a few keys in the registry even after the uninstall.

**Comment by isaak654** [comment]
> 
> Hmm....does uninstall install any scenario sort 1061?

Not forever, it's just a way to prevent the reboot... but it helps to fix possible shell integration issues that could be problematic if you upgraded a lot in the past. 

For example, older Plus versions < 0.8.9 left a few keys in the registry even after the uninstall.
This is no longer the case, fortunately.

**Comment by bjm234** [comment]
> Not forever, it's just a way to prevent the reboot... but it helps to fix possible shell integration issues that could be problematic if you upgraded a lot in the past.
> 
> For example, older Plus versions < 0.8.9 left a few keys in the registry even after the uninstall.

Okay. Thanks

**Comment by isaak654** [comment]
KmdUtil error 1061 just reproduced after the upgrade from 0.9.3 to 0.9.4.

**Comment by isaak654** [comment]
The upgrade issue will be fixed on the next build, see: https://github.com/sandboxie-plus/Sandboxie/discussions/1147#discussioncomment-1253253

**Comment by DavidXanatos** [comment]
instalers updat
