### ISSUE TITLE
Installer bug of Classic version is back

### ISSUE THREAD

**Issue by APMichael** [sandboxie-plus/Sandboxie#969]
Unfortunately, the bug (#495) is back in the current version (5.50.5/5.50.6):

With a clean reinstallation (with previous uninstallation and reboot) certain registry values are no longer set (autostart, context menu).

Therefore, you must now always start "Sandboxie Control" manually from the start menu and then just click OK under "Configure" > "Windows Shell Integration". Afterwards everything is entered correctly in the registry again.

Also, after uninstalling, the file "SboxHostDll.dll" still remains.

**Comment by isaak654** [comment]
I would also suggest a correlation with #968

**Comment by DavidXanatos** [comment]
I dont think its back i think it was never properly fixed in the first place, sorry for that

**Comment by APMichael** [comment]
Confirmed! It is fixed with the new version 5.50.7. Thank you very much. 😃

JFYI: After uninstalling, the file "SboxHostDll.dll" still remains.
