### ISSUE TITLE
A few installer bugs of Plus to fix (0.8.6)

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#970]
1) Repair/reinstall option in Plus doesn't work. It always shows the same static error, even after restarting Windows and trying again:

<img alt="repair_reinstall_option" src=https://user-images.githubusercontent.com/12372772/124742973-8a2a3680-df1d-11eb-90da-32a778864b2b.png height=275> <img alt="bug_reinstall_option" src=https://user-images.githubusercontent.com/12372772/124742979-8b5b6380-df1d-11eb-8e91-e382e4a1416a.png width=380>

2) After uninstalling Plus via unins000.exe, there will remain some leftovers. All folders except "LogAPI" are empty, so it's not the cleanest approach:
![Plus_leftovers](https://user-images.githubusercontent.com/12372772/124743373-f6a53580-df1d-11eb-80ae-5b58dd34747c.png)
![Plus_leftovers_2](https://user-images.githubusercontent.com/12372772/124745556-3ec55780-df20-11eb-8d7c-70041e9c8fd6.png)

**Comment by DavidXanatos** [comment]
that looks liek teh remanents of the old installer before we were using ino setup,
i would recommend, uninstall , delete the entire folder and whats left.
re install with the inno setup and try again

**Comment by isaak654** [comment]
> 
> 
> that looks liek teh remanents of the old installer before we were using ino setup,
> i would recommend, uninstall , delete the entire folder and whats left.
> re install with the inno setup and try again

That's gone indeed, thank you for the extra confirmation.
