### ISSUE TITLE
Upgrade from 5.33, OpenFilePath=* not work any more?

### ISSUE THREAD

**Issue by asbai** [sandboxie-plus/Sandboxie#971]
I just upgraded from 5.33 to 5.50.2, then I found that the new version no longer correctly recognizes the `OpenFilePath=*` and `OpenPipePath=*` instructions.

I tried to modify them to `OpenFilePath=*.*` and `OpenPipePath=*.*` The problem was alleviated.

But when I tried to use WinRAR to perform decompression in a sandbox configured with `OpenFilePath=*.*` and `OpenPipePath=*.*`, these configurations still did not take effect (the decompressed files were thrown into the sandbox) .

How can I keep the same behavior as `OpenFilePath=*` and `OpenPipePath=*` in version 5.33?

Thanks :-)

**Comment by asbai** [comment]
I found  `OpenFilePath=*:\*` do the trick.

**Comment by isaak654** [comment]
It looks for me on v0.9.6 / 5.51.6, see also https://github.com/sandboxie-plus/Sandboxie/discussions/1175#discussioncomment-1303845.

**Comment by isaak654** [comment]
It looks fixed for me on v0.9.6 / 5.51.6, see also https://github.com/sandboxie-plus/Sandboxie/discussions/1175#discussioncomment-1303845.

**Comment by asbai** [comment]
This bug reproduced on 5.55.6, Now neither `*` nor `*:\*` will work anymore. :-(

**Comment by isaak654** [comment]
If it didn't occur with Classic 5.55.5, then there is a chance this will be fixed on next v5.55.7:

> fixed issue with file renaming in open paths introduced in 1.0.6

**Comment by asbai** [comment]
We can also reproduce it on 5.55.5, version 5.53.3 is fine.

**Comment by isaak654** [comment]
> We can also reproduce it on 5.55.5, version 5.53.3 is fine.

In this case, please report which is the exact release that introduced the regression (including each pre-release in the middle).

**Comment by asbai** [comment]
> In this case, please report which is the exact release that introduced the regression (including each pre-release in the middle).

The first version to reproduce this problem is 5.55.0

**Comment by DavidXanatos** [comment]
What you need is 
OpenFilePath=*
OpenPipePath=*

*.* does work for files but not directories
and *:\* seams also wrong as internally nt paths are used which don't have : and while C:\ can be converted to an nt path if the volume is present *:\ can not

I tested with 
OpenFilePath=*
OpenPipePath=*
and it worked as expected i.e. all paths were open except those explicitly not

**Comment by DavidXanatos** [comment]
PS: you may also run into issues when you have folders in the sandbox in the location of open paths, so try clearing the sandbox if the issue persists

**Comment by asbai** [comment]
We tried:
1. Deleting the `drive` directory in the sandbox directory;
2. Starting notepad in the sandbox and modifying C:\test.txt.
3. Starting from version 5.55.0, the `drive` directory will appear in the sandbox directory at this time, and the modified content will exist under `C\test.txt`.

We tried `*` as well as `*:\*` and both behaved like this.

**Comment by asbai** [comment]
> and *:* seams also wrong as internally nt paths are used which don't have : and while C:\ can be converted to an nt path if the volume is present *:\ can not

Let's tidy up the timeline:
1. `OpenFilePath=*` worked fine in older versions (eg: 5.33) until 5.50.2.
2. In version 5.50.2, `OpenFilePath=*:\*` must be used, `OpenFilePath=*` will not work.
3. As of version 5.55.0, neither `OpenFilePath=*:\*` nor `OpenFilePath=*` work.

So `OpenFilePath=*:\*` should be no NT Kernel path matching problem.

Also, maybe in some version between 5.50.2 and 5.55.0, `OpenFilePath=*` used to work correctly, but we haven't tested it.

Thanks :-)

**Comment by DavidXanatos** [comment]
I see... with the last verbose issue report I coudl replicate the issue,

It only apples to the following locations:
\Device\HarddiskVolume4\Program Files (x86)\*
\Device\HarddiskVolume4\Program Files\*
\Device\HarddiskVolume4\Windows\*
other paths should work properly

a fix for that will be included in the built 1.0.8

**Comment by DavidXanatos** [comment]
PS:
if you specify more specific paths like C\Program Files\test-folder this wil overrule the mentioned location as well and allow open access

**Comment by asbai** [comment]
OK, Thanks :-)
