### ISSUE TITLE
[Plus 0.8.6/0.8.7/0.8.8/0.8.9/0.9.0/0.9.1] Can't open a folder/CD drive using the "Explore Sandboxed" entry

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#972]
**Describe the bug**
I'm not able to open any folder using the "Explore sandboxed" entry in the context menu.
![immagine](https://user-images.githubusercontent.com/12372772/124758238-aa162600-df2e-11eb-9f62-b82df1f57d9c.png)

In return I receive these errors:
![errors_notifications_list](https://user-images.githubusercontent.com/12372772/124758707-23157d80-df2f-11eb-8116-c97f5c4f6e32.png)

I can reproduce this behavior even with new sandboxes.

**Workaround**
I can still open Windows Explorer correctly if I run it from the Sandman UI:
![immagine](https://user-images.githubusercontent.com/12372772/124757730-2ceab100-df2e-11eb-8b59-1aa92e7619e9.png)

**Expected behavior**
Explorer.exe should run correctly also using the "Explore sandboxed" entry.

Windows 10 Pro 20H2
Sandboxie Plus 0.8.6
Windows Defender

**Comment by DavidXanatos** [comment]
strange for me it works fine

**Comment by DavidXanatos** [comment]
have you tried rebooting?

**Comment by isaak654** [comment]
> 
> 
> have you tried rebooting?

I rebooted something like three times.

It's a VM with .vdi extension (25 GB), if you want I can send you the link privately or we can arrange a remote session.
Just let know what you prefer.

**Comment by DavidXanatos** [comment]
found and fixed

**Comment by isaak654** [comment]
It's better but still buggy in one case... if you create a folder named AKLT(pw=snapfiles)xxx in the desktop and you try to run it  using the "Explore sandboxed" entry, it will open the Documents folder instead.

**Comment by isaak654** [comment]
I'm going to reopen this, because I found another way to reproduce this bug.

Only in Plus 0.8.8, the "Explorer Sandboxed" command points straightly to My Documents folder when I right-click on my DVD drive. On Classic 5.50.8 I can still run the DVD drive as sandboxed without issues.

In order to reproduce it, you need to put a CD/DVD on your DVD reader.

The test was done on the same W10 VM, so it should be easy to reproduce.

**Comment by isaak654** [comment]
> 
> 
> I'm going to reopen this, because I found another way to reproduce this bug.
> 
> Only in Plus 0.8.8, the "Explorer Sandboxed" command points straightly to My Documents folder when I right-click on my DVD drive. On Classic 5.50.8 I can still run the DVD drive as sandboxed without issues.
> 
> In order to reproduce it, you need to put a CD/DVD on your DVD reader.
> 
> The test was done on the same W10 VM that David already has, so it should be easy to reproduce.

Still unfixed in 0.8.9

**Comment by isaak654** [comment]
See the post above :point_up_2:
