### ISSUE TITLE
Don't use a standard Windows key combo (Ctrl+Break) as a global hotkey

### ISSUE THREAD

**Issue by benrg** [sandboxie-plus/Sandboxie#974]
Ctrl+Break is a bad choice for a global hotkey, especially one that does something as drastic as killing all boxed processes, because it already has a meaning in stock Windows (https://docs.microsoft.com/en-us/windows/console/ctrl-c-and-ctrl-break-signals).

Ctrl+Alt+Break would be a better default, but it is used by some software, notably Remote Desktop.

How about Ctrl+Alt+Backspace?

**Comment by DavidXanatos** [comment]
I'll change it to Ctrl+Alt+Break
