### ISSUE TITLE
hiding sbiedll.dll in PEB

### ISSUE THREAD

**Issue by Noksiowski** [sandboxie-plus/Sandboxie#98]
Very simple topic, anyone could pull? 
Process iam trying to run in sandbox detects if sbiedll.dll module is loaded, hiding it in Process Environment Block would solve the issue.

**Comment by DavidXanatos** [comment]
I don't think this would help much, once you take a look on the sbie sources it will became apparent that three are much more ways to detect that one runs in a sandbox.
To make it really stealth i would need to change much more than just add hiding from peb.

**Comment by Noksiowski** [comment]
Hiding in peb will be enough for this one particular aplication iam trying to run.
no need to make it really stealthly.

**Comment by diversenok** [comment]
Isn't it easier to patch the application instead?

**Comment by Noksiowski** [comment]
Its not open-source.
Already took attempt of reverse-engineering it but removing dll from peb since sbie is opensource now would be much simpler approach Let's fix the problem instead of avoiding it.

**Comment by DavidXanatos** [comment]
I'll add that to my todo seams easy enough although it will be only optional

**Comment by Noksiowski** [comment]
Thank you very much kind soul :)

**Comment by Noksiowski** [comment]
How far is this on your TODO? 👍

**Comment by Hiche3** [comment]
Win Li Sense (all one word and change the first "S" to a "c") allows developers to detect SB.

**Comment by DavidXanatos** [comment]
> 
> 
> How far is this on your TODO? 👍


Not as far as i would like it, last few weeks were to much homeoffice work...

**Comment by Noksiowski** [comment]
I still belive :D

**Comment by DavidXanatos** [comment]
as there is the sbiehide project we can close this
