### ISSUE TITLE
add an option in the right-click menu to duplicate a sandbox

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#982]
add an option to duplicate a sandbox

sometimes we need to use the same sandbox with little changes so this feature would be useful to a lot of ppl.

**Comment by Coverlin** [comment]
Create new box already has the option to copy settings from another box
It's a feature for both plus and classic

**Comment by diieg707** [comment]
> 
> 
> Create new box already has the option to copy settings from another box
> It's a feature for both plus and classic

now i saw it, thanks, but i think an option "duplicate sandbox" in right click menu would be great as well

**Comment by DavidXanatos** [comment]
do you want the duplication to also copy the box content?

**Comment by diieg707** [comment]
> 
> 
> do you want the duplication to also copy the box content?

what's a good idea, but for me i think it's unecessary, 

just add add an option in the right-click menu to duplicate a sandbox, if click, then a window pops up to rename it, and place a pre typed names like sandbox_duplicate1 or something.

**Comment by diieg707** [comment]
> do you want the duplication to also copy the box content?

i got an Idea from your comment..

If we click duplicate box a little windows pops up to rename box with a pre typed name like boxname_duplicate1,2,3 , and below that you put a unchecked box named copy files, then 2 buttons, cancel and ok

**Comment by DavidXanatos** [comment]
that was added in 1.0.0 or so
