### ISSUE TITLE
[Bug] | Getting an error message on upgrade

### ISSUE THREAD

**Issue by John4266** [sandboxie-plus/Sandboxie#983]
**Describe the bug**
Getting an error message every time i upgrade the program.
It only happens once tho on every upgrade.

**To Reproduce**
1. Have an older version of the program.
2. Upgrade it.
3. Run the upgraded version.
3. Observe the results.

**Expected behavior**
Shouldn't happen i guess.

**Screenshots**
![DbQa5VJ](https://user-images.githubusercontent.com/70203256/125174280-cdf69780-e1cc-11eb-98d8-26ad46f7b7ca.png)

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? Windows 10 Pro | 64 Bit
 - What is your current Sandboxie edition and version? Sandboxie Plus 0.8.2 | (Even tho it started in bit earlier versions)
 - Please mention in which version this bug got introduced: uhh i kinda forgot. i think around 0.7.5, not sure tho.
 - Please mention any security software running in the background: ESET Smart Security Premium 14.2.19.0

**Sandboxie configuration**

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```


[GlobalSettings]

FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n

[UserSettings_0BB001B0]

SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

[DefaultBox]

Enabled=y
ConfigLevel=9
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore

```

</details>

**Comment by isaak654** [comment]
There is already an open issue #968, you can continue there.

**Comment by John4266** [comment]
ooh ok thanks, i didn't notice 😅
