### ISSUE TITLE
OPEN FILE, SAVE AS, on every program is broken, click and nothing happen

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#984]
OPEN FILE, SAVE AS, commands on every program is broken, click and window doesn't appear

sandboxie plus 0.8.7

**Comment by isaak654** [comment]
1) Is it a clean Plus installation or an installation upgraded from previous versions (if yes, which ones)?
2) Windows edition and version? (i.e. Windows 10 Pro 20H2).
3) Any security software running in the background?
4) Possibly attach any screenshot or write your problem in steps like this:

**Steps to reproduce the behavior:**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by diieg707** [comment]
it is a clean plus installation 0.8.7
w10 version 1803 (os build 17134.285)
no security software running

no screenshot, just try with VLC, mpc classic and other programs: CLICK OPEN FILE, OPEN FOLDER, SAVE AS commands doesn't work

**Comment by isaak654** [comment]
I've just tried with VLC and notepad both sandboxed... open file and save dialogs run fine here.
Windows 10 20h2 - 0.8.7

**Comment by diieg707** [comment]
> otepad both s

my notepad doesn't even open bro

![Capture](https://user-images.githubusercontent.com/54504707/125180945-5fb6d280-e1d6-11eb-87f6-aa4bd85260c4.JPG)

**Comment by diieg707** [comment]
just to mention that previous versions are working fine..

installed classic 5.49.7 and it's working fine
then upgraded to latest 0.8.7 and these problems occur.

**Comment by diieg707** [comment]
THE LOG WHEN I CLICK OPEN FILE AND DIALOG DOESN'T OPEN, **(log of mpc classic clicked twice, vlc clicked once)**

|Process|                                  |Type|     |Status|    |Value|                                                         

mpc-hc64.exe (7128, 4772) - 00:53:26.174   WinClass   open (3)    Shell_TrayWnd                                                   
mpc-hc64.exe (7128, 4772) - 00:53:27.601   Ipc                    \Sessions\1\BaseNamedObjects\AsyncKeyStateTrackerSharedMemory   
mpc-hc64.exe (7128, 4772) - 00:53:27.601   WinClass               Auto-Suggest Dropdown                                           
mpc-hc64.exe (7128, 4772) - 00:53:27.633   WinClass   open (3)    Shell_TrayWnd                                                   
mpc-hc64.exe (7128, 4772) - 00:53:27.644   Ipc        open (3)    \BaseNamedObjects\TabletHardwarePresent                         
mpc-hc64.exe (7128, 4772) - 00:53:27.747   WinClass               SHELLDLL_DefView                                                
mpc-hc64.exe (7128, 3324) - 00:53:27.747   Pipe                   \Device\HarddiskVolume3                                         
mpc-hc64.exe (7128, 3324) - 00:53:27.747   Pipe                   \Device\MountPointManager                                       
mpc-hc64.exe (7128, 4772) - 00:53:27.810   WinClass               SHELLDLL_DefView                                                
mpc-hc64.exe (7128, 4772) - 00:53:27.842   Ipc        open        \BaseNamedObjects\TabletHardwarePresent    



|Process|                                  |Type|     |Status|    |Value|                                                         

mpc-hc64.exe (5344, 4400) - 01:01:00.912   Ipc        open        \BaseNamedObjects\TabletHardwarePresent                         
mpc-hc64.exe (5344, 4400) - 01:01:00.870   WinClass               SHELLDLL_DefView                                                
mpc-hc64.exe (5344, 4248) - 01:01:00.807   Pipe                   \Device\MountPointManager                                       
mpc-hc64.exe (5344, 4248) - 01:01:00.807   Pipe                   \Device\HarddiskVolume3                                         
mpc-hc64.exe (5344, 4400) - 01:01:00.796   WinClass               SHELLDLL_DefView                                                
mpc-hc64.exe (5344, 4400) - 01:01:00.733   Ipc        open (3)    \BaseNamedObjects\TabletHardwarePresent                         
mpc-hc64.exe (5344, 4400) - 01:01:00.701   WinClass   open (3)    Shell_TrayWnd                                                   
mpc-hc64.exe (5344, 4400) - 01:01:00.701   WinClass               Auto-Suggest Dropdown                                           
mpc-hc64.exe (5344, 4400) - 01:01:00.701   Ipc                    \Sessions\1\BaseNamedObjects\AsyncKeyStateTrackerSharedMemory   
mpc-hc64.exe (5344, 4400) - 01:00:59.273   WinClass   open (3)    Shell_TrayWnd                                                                        




|Process|                             |Type|     |Status|    |Value|                                                         

vlc.exe (6424, 7108) - 00:55:35.881   Ipc                    \Sessions\1\BaseNamedObjects\HWNDInterface:100452               
vlc.exe (6424, 7108) - 00:55:35.881   WinClass   closed      ApplicationManager_DesktopShellWindow                           
vlc.exe (6424, 7108) - 00:55:35.881   WinClass               $:explorer.exe                                                  
vlc.exe (6424, 7108) - 00:55:35.881   WinClass               ApplicationManager_DesktopShellWindow                           
vlc.exe (6424, 7108) - 00:55:35.881   Ipc                    \Sessions\1\BaseNamedObjects\HWNDInterface:100452               
vlc.exe (6424, 7108) - 00:55:35.881   WinClass   closed      ApplicationManager_DesktopShellWindow                           
vlc.exe (6424, 7108) - 00:55:35.881   WinClass               $:explorer.exe                                                  
vlc.exe (6424, 7108) - 00:55:35.881   WinClass               ApplicationManager_DesktopShellWindow                           
vlc.exe (6424, 7108) - 00:55:35.881   Ipc                    \Sessions\1\BaseNamedObjects\HWNDInterface:100452               
vlc.exe (6424, 7108) - 00:55:35.818   Ipc        open        \BaseNamedObjects\TabletHardwarePresent                         
vlc.exe (6424, 7108) - 00:55:35.775   WinClass               SHELLDLL_DefView                                                
vlc.exe (6424, 3320) - 00:55:35.743   Pipe                   \Device\MountPointManager                                       
vlc.exe (6424, 3320) - 00:55:35.743   Pipe                   \Device\HarddiskVolume3                                         
vlc.exe (6424, 7108) - 00:55:35.743   WinClass               SHELLDLL_DefView                                                
vlc.exe (6424, 7108) - 00:55:35.639   Ipc        open (3)    \BaseNamedObjects\TabletHardwarePresent                         
vlc.exe (6424, 7108) - 00:55:35.628   WinClass   open (3)    Shell_TrayWnd                                                   
vlc.exe (6424, 7108) - 00:55:35.628   WinClass               Auto-Suggest Dropdown                                           
vlc.exe (6424, 7108) - 00:55:35.628   Ipc                    \Sessions\1\BaseNamedObjects\AsyncKeyStateTrackerSharedMemory   
vlc.exe (6424, 7108) - 00:55:35.474   ComClass               {53BD6B4E-3780-4693-AFC3-7161C2F3EE9C} MruLongList              
vlc.exe (6424, 7108) - 00:55:35.321   WinClass   open (3)    Shell_TrayWnd                                                   
vlc.exe (6424, 7108) - 00:55:35.321   WinClass   closed      ApplicationManager_DesktopShellWindow                           
vlc.exe (6424, 7108) - 00:55:35.321   WinClass               $:explorer.exe                                                  
vlc.exe (6424, 7108) - 00:55:35.321   WinClass               ApplicationManager_DesktopShellWindow                           
vlc.exe (6424, 7108) - 00:55:35.321   Ipc        (3)         \Sessions\1\BaseNamedObjects\HWNDInterface:100452               
vlc.exe (6424, 7108) - 00:55:35.321   WinClass   open (3)    Shell_TrayWnd                                                   
vlc.exe (6424, 7108) - 00:55:35.321   WinClass               Qt5QWindowIcon

**Comment by DavidXanatos** [comment]
could you pelase test some inbetween verions
between 5.49.7 and 5.50.7 are quite a few versions

**Comment by diieg707** [comment]
> 7 and 5.5

0.8.2 is the last variation that works, problem persists in 0.8.7b, 
(but 0.8.2 have issues deleting sandbox, that you fixed in latest buildings)

note that in mpc classic the buttons turn black

i was going to test Release v0.8.5 / 5.50.5 but it seems you forgot to post the files, just assets are available

![Capture](https://user-images.githubusercontent.com/54504707/125191414-b7762d80-e218-11eb-854c-e975a427c88d.JPG)

**Comment by isaak654** [comment]
I need to know if you also encountered #968 when switching from a Plus version to another.

**Comment by diieg707** [comment]
> rom a Plus versio

i encounted this error when switching from classic to 0.8.7 version, but a simple reboot resolves the issue, not a big deal

**Comment by DavidXanatos** [comment]
v0.8.5 / 5.50.5 is same as v0.8.6 / 5.50.6 except one bugfix

could you please  v0.8.2 with first the SbieDll.dll from 0.8.6 than the SbieSvc.exe and than the SbieDrv.sys
the files should be interchangeable and it would help me a lot to know in which component the breaking change is located, as I can not reproduce the issue locally.

Please note the because of the code signing when trying the SbieSvc.exe from 0.8.6 you will need to take the updated sandman.exe with the sandman.exe.sig
and if testing the new driver you need the newer SbieSvc.exe with the accompanying SbieSvc.exe.sig

**Comment by diieg707** [comment]
> 
> 
> v0.8.5 / 5.50.5 is same as v0.8.6 / 5.50.6 except one bugfix
> 
> could you please v0.8.2 with first the SbieDll.dll from 0.8.6 than the SbieSvc.exe and than the SbieDrv.sys
> the files should be interchangeable and it would help me a lot to know in which component the breaking change is located, as I can not reproduce the issue locally.
> 
> Please note the because of the code signing when trying the SbieSvc.exe from 0.8.6 you will need to take the updated sandman.exe with the sandman.exe.sig
> and if testing the new driver you need the newer SbieSvc.exe with the accompanying SbieSvc.exe.sig

hello man, i didn't understand well what you wrote..

but the problem is related to services, if i open 0.8.2 and start it's services and close it
then start 0.8.6 problem doesn't occur, as you can see no black mpc buttons

![solv](https://user-images.githubusercontent.com/54504707/125210931-19ff1600-e279-11eb-9cc2-25df06f584a6.JPG)

**Comment by diieg707** [comment]
how to place services from 0.8.2 to 0.8.6?

**Comment by isaak654** [comment]
Sandboxie service is the SbieSvc.exe file located in the main Sandboxie installation folder.

**Comment by diieg707** [comment]
> oxi

i tried to put SbieSvc.exe on 0.8.6 but it didn't work

**Comment by isaak654** [comment]
> 
> 
> > oxi
> 
> i tried to put SbieSvc.exe on 0.8.6 but it didn't work

Did you rename the _SbieSvc.exe.sig_ file to something else?

**Comment by diieg707** [comment]
> > i tried to put SbieSvc.exe on 0.8.6 but it didn't work
> 
> Did you rename the _SbieSvc.exe.sig_ file to something else?

There's no SbieSvc.exe.sig in 082
and i also deleted SbieSvc.exe.sig on 086 before open it

**Comment by DavidXanatos** [comment]
go the other way instal the old build and then put the new svc in it

**Comment by diieg707** [comment]
> go the other way instal the old build and then put the new svc in it
I tried that quite some time, the times I manage it to work mpc opened with black buttons, and open file dialog broken
other times showed errors on notification

**Comment by DavidXanatos** [comment]
Ok lets make it simple
1. go to the maintenace menu of your sandman and click stop all
2. exit sandman
3. rename your instalation folder to somethign else
4. download one of the prepared test instals
5. extract it in place of your original instalation folder
6. start samdman let it start the drv and svc
7. test if it works
8. repeat for the other test install

test installs
http://xanasoft.com/Downloads/Sandboxie-Plus 0.8.2 with 0.8.6 SbieDll.zip
http://xanasoft.com/Downloads/Sandboxie-Plus 0.8.2 with 0.8.6 SbieSvc.zip

**Comment by diieg707** [comment]
> Ok lets make it simple
> 
> 1. go to the maintenace menu of your sandman and click stop all
> 2. exit sandman
> 3. rename your instalation folder to somethign else
> 4. download one of the prepared test instals
> 5. extract it in place of your original instalation folder
> 6. start samdman let it start the drv and svc
> 7. test if it works
> 8. repeat for the other test install
> 
> test installs
> http://xanasoft.com/Downloads/Sandboxie-Plus 0.8.2 with 0.8.6 SbieDll.zip
> http://xanasoft.com/Downloads/Sandboxie-Plus 0.8.2 with 0.8.6 SbieSvc.zip

Ok

**Comment by diieg707** [comment]
> 4\. nload one

i think you didn't post properly your test installs

**Comment by DavidXanatos** [comment]
just copy the entire test up to zip and paste it

**Comment by isaak654** [comment]
> 
> 
> > 4. nload one
> 
> i think you didn't post properly your test installs

You can still copy and paste both URLs, it's just GitHub that doesn't handle the spaces in the URLs.

**Comment by isaak654** [comment]
> 
> i think you didn't post properly your test installs

You can still copy and paste both URLs, it's just GitHub that doesn't handle the spaces.

**Comment by diieg707** [comment]
tests done, here's what i did..

- installed 0.8.2
- went to maintenance and stopped all
- exit sandman.exe
- created a copy of C:\Program Files\Sandboxie-Plus, as Sandboxie-Plus_bkp
- extracted and replaced ALL FILES in place of original instalation folder (C:\Program Files\Sandboxie-Plus)

i made sure sandboxie asked to create services on both cases
and also to crean up services when closing programs

i hope i did it right

 **0.8.6 SbieDll**
![sbiedll](https://user-images.githubusercontent.com/54504707/125326155-9421b000-e2f6-11eb-8bb3-a7f240482056.JPG)

**0.8.6 SbieSvc**
![svc](https://user-images.githubusercontent.com/54504707/125326351-ccc18980-e2f6-11eb-92b3-2b4b0d4a0d93.JPG)

**Comment by diieg707** [comment]
nothing opens on **0.8.6 SbieDll**, and show errors on notification

**Comment by DavidXanatos** [comment]
ah damn there seam to be an incompatibility with the sbiedll
i have compiled fresh working inbetween builds, 3 in total all in one zip
http://xanasoft.com/Downloads/testbuilds-0.8.2-0.8.6.0.zip
test them one after the other and tell me with which the issues appear

**Comment by diieg707** [comment]
> ah damn there seam to be an incompatibility with the sbiedll
> i have compiled fresh working inbetween builds, 3 in total all in one zip
> http://xanasoft.com/Downloads/testbuilds-0.8.2-0.8.6.0.zip
> test them one after the other and tell me with which the issues appear

**Sandboxie-Plus 0.8.2_with_0.8.6_sbiedll**
open file dialog broken, (error deleting sandbox (with programs open))

**Sandboxie-Plus 0.8.2_with_0.8.6_sbiedll_and_sbiesvc**
open file dialog broken, (error deleting box (with programs open)) doesn't occur

**Sandboxie-Plus 0.8.2_with_0.8.6_sbiesvc**
open file dialog WORKS, (error deleting box (with programs open))

**Comment by DavidXanatos** [comment]
ok good so thet tells be the breakign change for you is in sbiedll.dll,
please stay tuned I'll cook up some more test builds with a more fine grained changes, so we can pin point what exactly caused the issue...

**Comment by diieg707** [comment]
> ok good so thet tells be the breakign change for you is in sbiedll.dll,
> please stay tuned I'll cook up some more test builds with a more fine grained changes, so we can pin point what exactly caused the issue...

ok

**Comment by DavidXanatos** [comment]
here thay are: http://xanasoft.com/Downloads/testbuilds-0.8.2-0.8.6.0-misc.zip

**Comment by diieg707** [comment]
> here thay are: http://xanasoft.com/Downloads/testbuilds-0.8.2-0.8.6.0-misc.zip

do you expect to find some bug?
i tested the first 3 folders and open file dialog works in all of them

**Comment by DavidXanatos** [comment]
one of them should break it
if non of them braks it we have a problem

**Comment by diieg707** [comment]
this one didn't work
Sandboxie-Plus_0.8.2_obj

> one of them should break it
> if non of them braks it we have a problem

Sandboxie-Plus_0.8.2_obj
the last one didn't work

**Comment by DavidXanatos** [comment]
> 
> 
> the last one didn't work, this is the buggy one
> Sandboxie-Plus_0.8.2_obj
> 

hmm... damn it... that was the fix for #951
please test this one also http://xanasoft.com/Downloads/Sandboxie-Plus_0.8.2_obj_a.zip
does this one work of break?

**Comment by diieg707** [comment]
Sandboxie-Plus_0.8.2_obj_a.zip
this one break

**Comment by DavidXanatos** [comment]
ok and this one: http://xanasoft.com/Downloads/Sandboxie-Plus_0.8.2_obj_b.zip

**Comment by diieg707** [comment]
> Sandboxie-Plus_0.8.2_obj_b.zip

Sandboxie-Plus_0.8.2_obj_b.zip
break too

**Comment by DavidXanatos** [comment]
that is not good it means that the fix for the mentioned issue breaks sbie for you and it seams only for you as others do not complain, not sure why that is.
I'll add a switch and make the old behaviorue that worked for you default as the change seams to break in your usecase more
than the fix fixes in the other case

**Comment by diieg707** [comment]
> that is not good it means that the fix for the mentioned issue breaks sbie for you and it seams only for you as others do not complain, not sure why that is.
> I'll add a switch and make the old behaviorue that worked for you default as the change seams to break in your usecase more
> than the fix fixes in the other case

thank you man

**Comment by DavidXanatos** [comment]
please also test the builds with your other issue #985

**Comment by DavidXanatos** [comment]
PS: also are you using any other security software, or virtualization or sandboxing software?
IMHO something is messing with the object name resolution on your system, not sure what though

**Comment by diieg707** [comment]
> sure

i use Flattastic OS, 
no security software
on my system tray i only have steam, IDM, Pdanet

**Comment by diieg707** [comment]
> PS: also are you using any other security software, or virtualization or sandboxing software?
> IMHO something is messing with the object name resolution on your system, not sure what though

BTW you said on #951 that you could use  NtQueryObject instead but have to check if this can cause any other issues

**Comment by DavidXanatos** [comment]
yea apparently it does, after soem more testing it seals windows 10 build 1803 it doe snot work properly, but on 7 ot does so really streame
