### ISSUE TITLE
chrome.exe - System Error, chrome_elf.dll was not found, chrome doesn't open

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#985]
The code execution cannot proceed because chrome_elf.dll was not found.

sandboxie plus 0.8.7

**Comment by DavidXanatos** [comment]
is this issue also appearing after 0.8.2

**Comment by diieg707** [comment]
> 
> 
> is this issue also appearing after 0.8.2

chrome is working on 0.8.2
this issue is appearing after 0.8.2

**Comment by DavidXanatos** [comment]
ok then please do the same testing as for the other issue with parts of the newer release

**Comment by diieg707** [comment]
**LOTS OF BUGS AFTER 0.8.2**

**run sandboxed explorer doesn't work**
![explorer](https://user-images.githubusercontent.com/54504707/125206330-15c4ff80-e25d-11eb-9117-8d11ff621508.JPG)

**chrome error**
![chrome](https://user-images.githubusercontent.com/54504707/125206339-237a8500-e25d-11eb-80f9-75fb75e34de0.JPG)

**notepad error**
![notepad22](https://user-images.githubusercontent.com/54504707/125206363-4ad15200-e25d-11eb-8e66-05d6a8dfb2fc.JPG)

**OPEN FILE/FOLDER, SAVE AS dialog doesn't show up, mpc buttons turn black for some reason**
![mpc223](https://user-images.githubusercontent.com/54504707/125206397-77856980-e25d-11eb-84da-3980210846b6.JPG)

**Comment by diieg707** [comment]
word 2019
![WORDsss](https://user-images.githubusercontent.com/54504707/125206569-5ec98380-e25e-11eb-9b2c-d59660d27ed5.JPG)

**Comment by DavidXanatos** [comment]
could you pelase test this issue with the test builds from #984 and tell me if it has teh same cause

**Comment by diieg707** [comment]
> e if it h

yes issue have the same cause as #984, 

chrome works with those testbuilds

**Comment by DavidXanatos** [comment]
Are you using any other security software, or virtualization or sandboxing software?
IMHO something is messing with the object name resolution on your system, not sure what though

**Comment by diieg707** [comment]
> Are you using any other security software, or virtualization or sandboxing software?
> IMHO something is messing with the object name resolution on your system, not sure what though

i use Flattastic OS,
no security software
on my system tray i only have steam, IDM, Pdanet and intel hd graphics
