### ISSUE TITLE
[Plus 0.8.7] Sandboxed programs won't run when AutoDelete is enabled

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#986]
**Describe the bug**
Sandboxed programs won't run when AutoDelete is enabled for the box.

**To Reproduce**
1. Go to 'Sandbox Options'
2. Click on 'File Options'
3. Enable 'Auto delete...' option for the box.
4. Click OK
5. Right click to the box
6. Run anything from the menu
7. It runs for a moment, then terminates? without an error.

**Expected behavior**
It should keep running.

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version?
 **Windows 10 21H1**
 - What is your current Sandboxie edition and version?
 **Sandboxie Plus 0.8.7**
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 **Sandboxie Plus 0.8.7**
 - Please mention any security software running in the background, even if the real-time protection is disabled.
 **Microsoft Defender**

**Comment by isaak654** [comment]
You're right, I can reproduce it reliably - same version.
