### ISSUE TITLE
[Plus 0.8.7] Box options in Tray menu are not displayed fully

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#989]
<img src="https://user-images.githubusercontent.com/13391795/125179992-910bbe80-e227-11eb-9874-c9ebd5170b46.gif" height="450">

> I think I found a bug: If the sandman GUI wasn't inited(for example, autorun on windows start), the right menu of sandbox won't show fully

_Originally posted by @mercury233 in https://github.com/sandboxie-plus/Sandboxie/issues/960#issuecomment-877724553_

**Comment by indig0F10w** [comment]
Confirmed on Windows 10 Pro x64.

![Capture](https://user-images.githubusercontent.com/17021548/126031503-3ba382cf-987f-44fc-8a07-a4500781694c.PNG)

**Comment by isaak654** [comment]
> 
> 
> Confirmed on Windows 10 Pro x64.
> 

There is no right-click menu on your _DefaultBox_ in the attached screenshot, are you sure it's the same issue?

**Comment by indig0F10w** [comment]
I thought you're talking about the useless blank space after right-click on tray icon. Now I know it is supposed to be reserved for sandboxes.

You are using old version, update to 0.8.8 and try again.

**Comment by isaak654** [comment]
> 
> I thought you're talking about the useless blank space after right-click on tray icon.

@indig0F10w 
That's nasty too, I agree... feel free to open a new issue for it.
