### ISSUE TITLE
SBIE2224 when trying to install a program from portableapps.com

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#99]
Reproduction steps:
1) Download Google Chrome Portable: https://portableapps.com/apps/internet/google_chrome_portable
2) Run the installer in Sandboxie
3) Select a target folder

-> Crash SBIE2224
![portable app crash](https://user-images.githubusercontent.com/12411527/87858738-6480d780-c930-11ea-93a5-5a7a80c277f9.png)

**Comment by NewKidOnTheBlock** [comment]
I've tried it with a couple more programs from portableapps.com

Interestingly, the Foxit Portable Installer works just fine in Sandboxie:
https://portableapps.com/apps/office/foxit_reader_portable

I then tried Skype Portable:
https://portableapps.com/apps/internet/sportable
Here, the same kind of crash occured.

Chrome Portable and Skype Portable have both in common that their installer is a very small downloader that downloads an additional packet.

**Comment by DavidXanatos** [comment]
Its really strange, as even the offline chrome installers seam to crash in sandboxie, not sure why that is, I will take a look with a debugger on the weekend to see whats happening there.

**Comment by NewKidOnTheBlock** [comment]
Today I tried again with:
Windows 10 20H2 64bit
Sandboxie 5.44.1
[Chrome Portable 87](https://portableapps.com/apps/internet/google_chrome_portable)

It works right up to the point where the installer tries to download the necessary files:
![SB5441vsChromePortable87](https://user-images.githubusercontent.com/12411527/99507165-52b54c80-2983-11eb-8f14-cc4dc3e33199.png)

**Comment by NewKidOnTheBlock** [comment]
BIG UPDATE!
I tried again with Chrome Portable and Skype Portable.
This time with Sandboxie 5.45.2

The downloader is now able to grab the files and complete the installation.
Downloader type installers seem to work now!
Great job.
