### ISSUE TITLE
Sandboxie Classic greater than v5.49.8 breaks Internet Download Manager integration in Firefox

### ISSUE THREAD

**Issue by arie93** [sandboxie-plus/Sandboxie#991]
**Describe the bug**
When I run Firefox in the sandbox and download files through IDM, the IDM application does not run at all. I also already added Internet Download Manager in "Software Compability", and still doesn't work.

**To Reproduce**
1. Install Sandboxie Classic
2. Run Internet Download Manager
3. Add Internet Download Manager in "Software Compability"
4. Run Firefox in default sandbox
5. Download the file link from firefox

**Expected behavior**
Internet Download Manager doesn't launch at all to download the file. So, the file just downloaded with firefox.

**System details and installed software (please provide the following information):**
OS: win 10 x64 v1809
Firefox: v89.0.1 x64
Internet Download Manager: v6.38 Build 21
Sandboxie Classic: > v5.49.8
No antivirus or any other security software

**Comment by isaak654** [comment]
Behavior tested and confirmed.

**Comment by DavidXanatos** [comment]
what is the last version it worked in?

**Comment by isaak654** [comment]
> 
> 
> what is the last version it worked in?

v5.49.8, without any doubt.

**Comment by DavidXanatos** [comment]
ok so its broken since we added

[Template_InternetDownloadManager]
BlockPort=1001

because an other user complained that it opens an unsandboxed download agent.
we should split this template then or something

**Comment by isaak654** [comment]
Imho there should be a way to customize BlockPort per process, while making sure to test it for Chrome too: #791

**Comment by isaak654** [comment]
I would suggest a way to customize BlockPort per process, while making sure to test it for Chrome too: #791
Unless you think it's needed another implementation.

**Comment by DavidXanatos** [comment]
"customize BlockPort per process" with the new WFP based filter we could have this indeed

**Comment by isaak654** [comment]
As a temporary workaround for this issue, I would recommend to remove in each release this line from the `Templates.ini` file in your sandboxie folder:
https://github.com/sandboxie-plus/Sandboxie/blob/a4e6b4913b908c002bd19b0886dc38f63fdcc22a/Sandboxie/install/Templates.ini#L2912

This because I don't think it's wise to create a temporary template elsewhere that could be forgotten, and for only one line.

**Comment by arie93** [comment]
BlockPort=1001

Removing that line just fixed this IDM integration in Firefox on the latest Sanboxie classic version.

**Comment by Dean-Corso** [comment]
Info: IDM integration is still NOT working in Firefox or Chrome/Brave and it also dosen't matter to keep or remove the "BlockPort=1001" line from the template.ini file.IDM is already long time not working in Sandboxie Classic and thats the reason why I have still to use the old version "SandboxieInstall64-v5.45.2".This works but makes trouble with other things.So my goal is it to install and use the latest SBC-64 version but only if IDM will work with it (not yet for me).So could you please check this problem and really fix it?I'am using this config...

Windows 10 x64 Version 20H2 (Build 19042.1110)
Sandboxie-Classic-x64-v5.50.9
`# prevetn access to host port`
`BlockPort=1001` <--keep or remove line = makes no diffrent
Firefox x64 Version 89.0.2
Brave x64 Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)

...just test it again.Thank you.

**Comment by isaak654** [comment]
I would also suggest to apply the recommendations about removing the remaining traces of BlockPort(s): https://github.com/sandboxie-plus/Sandboxie/discussions/1085#discussioncomment-1164860

**Comment by DavidXanatos** [comment]
The current version of IDM seams to work fien with the latest sandboxie tested booth with chroem and firefox, so I'll clsoe this issue
