### ISSUE TITLE
add a "make sandbox files visible" feature

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#994]
it would be a great feature if you add a "make sandbox files visible" option..

add an "eye toggle option" in sandboxie panel, and if we turn it on all files in a specific sandbox will be visible around a retangle, (NOT BEING POSSIBLE to make 2 boxes visible at the same time)

![594px-ChristineC_icons4](https://user-images.githubusercontent.com/54504707/125191835-db3a7300-e21a-11eb-9d94-6191b78acb4b.jpg)

**Comment by DavidXanatos** [comment]
this is imho not doable with a reasonabel ammount of afford, 
what you have sellected are not sandboxed links to a sandboxed file
how should sandboxie know the location of all links in the system pointing to it

**Comment by diieg707** [comment]
> at you have sellected

you got a point, could it be done at least in specific locations like personal folders, desktop, c:..

**Comment by diieg707** [comment]
kind of like this pic
regarding of how sandboxie would know the location, i'm not a programmer but just use the make mechanics as when we open sandboxied explorer
![Image 3](https://user-images.githubusercontent.com/54504707/125193192-9239ed00-e221-11eb-8a00-cb56de30d407.png)

**Comment by DavidXanatos** [comment]
no that is still not really doable, I'll close this issue as i really see no good way to implement it.
I mean the only possible option would be to mess with the icons but than the icon cache would be in the way
