### ISSUE TITLE
Sanboxies 0.8.7.2 crashed on Win8.1 x86 on 2 PC's when i try to run a program in box

### ISSUE THREAD

**Issue by MCSE-2000** [sandboxie-plus/Sandboxie#995]
Sanboxies crashed on Win8.1 x86 when i try to run a program in box.

I try today the new sandboxies-plus 0.8.7.2 on Windows 8.1 Enterprise - X86-based PC Version 6.3.9600.
I also try it on a second PC with Win8.1 Pro x86 and their is also the Exception code: 0xc0000409 in QSbieAPI.dll.

When i right click in the GUI on the "DefaultBox" and then click on "Run" -> "Run Program".
Then popup the Window "[#] Run Sanboxed - DefaultBox [#]" and the Window "SandBox Manager - SandboxManager has stopped working".

Here is the entry in Application Event:
Log Name:      Application
Source:        Application Error
Date:          7/11/2021 2:41:04 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WIN8VHD
Description:
Faulting application name: SandMan.exe, version: 0.8.7.2, time stamp: 0x60ea97fa
Faulting module name: QSbieAPI.dll, version: 0.8.7.2, time stamp: 0x60ea97df
Exception code: 0xc0000409
Fault offset: 0x0001e3de
Faulting process id: 0xdd4
Faulting application start time: 0x01d77651dca4f36d
Faulting application path: C:\Program Files\Sandboxie-Plus\SandMan.exe
Faulting module path: C:\Program Files\Sandboxie-Plus\QSbieAPI.dll
Report Id: 40b658e9-e245-11eb-97b9-0022431d12a8
Faulting package full name: 
Faulting package-relative application ID: 

Snapshot:
![grafik](https://user-images.githubusercontent.com/84094043/125196083-b533c380-e258-11eb-88da-c546692353ec.png)

**Comment by DavidXanatos** [comment]
seams same as https://github.com/sandboxie-plus/Sandboxie/issues/945
Will have to set up a 8.1 32 bit Vm to debug that

**Comment by DavidXanatos** [comment]
hmm there is soemthign broken with the build process, the binarys i build locally work fine, the binaries from the github actions used for the releases dont WTF

**Comment by DavidXanatos** [comment]
> Why are they not identical?
slightly different visual studio and library versions I presume.

**Comment by MCSE-2000** [comment]
You have write "hmm there is soemthign broken with the build process, the binarys i build locally work fine, the binaries from the github actions used for the releases dont WTF"
If your local version works for you but the version on GitHub doesn't, then something is wrong. 
Can you fix the STATUS_STACK_BUFFER_OVERRUN in the Release for x86 on GitHub?

All the best

**Comment by MCSE-2000** [comment]
Also version 0.8.9 does not work on x86 Win8.1. There is still in QSbieAPI.dll the error STATUS_STACK_BUFFER_OVERRUN!

Protokollname: Application
Quelle:        Application Error
Datum:         28.07.2021 11:40:51
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      WIN8VHD
Beschreibung:
Name der fehlerhaften Anwendung: SandMan.exe, Version: 0.8.9.0, Zeitstempel: 0x60f9d922
Name des fehlerhaften Moduls: QSbieAPI.dll, Version: 0.8.9.0, Zeitstempel: 0x60f9d900
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0001e21e
ID des fehlerhaften Prozesses: 0xb6c
Startzeit der fehlerhaften Anwendung: 0x01d7839490122a3d
Pfad der fehlerhaften Anwendung: C:\Program Files\Sandboxie-Plus\SandMan.exe
Pfad des fehlerhaften Moduls: C:\Program Files\Sandboxie-Plus\QSbieAPI.dll
Berichtskennung: e4e98a7b-ef87-11eb-97c6-c3ec780c96b3
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

![2021-07-28 11_41_11-Sandboxie-Plus v0 8 9](https://user-images.githubusercontent.com/84094043/127304196-709183a4-36eb-4f79-bdbc-b9db51dbee4a.png)
