### ISSUE TITLE
Linger process don't get killed if runned from the start menu of sandboxie

### ISSUE THREAD

**Issue by mercury233** [sandboxie-plus/Sandboxie#997]
**Describe the bug**
Linger process don't get killed if runned from the start menu of sandboxie.

**To Reproduce**
1. Set Bing IME as default IME, add the linger process (BingIMEPlatform.exe).
2. Run any program from the start menu of sandboxie.
3. BingIMEPlatform.exe is automatically started.
4. Close the program.

**Expected behavior**
Only the linger processes left, them should be killed automatically.

**Screenshots**
![GIF 2021-7-12 16-49-29](https://user-images.githubusercontent.com/13391795/125259370-d1effa00-e331-11eb-93d5-e4e33b90b8fa.gif)

**System details and installed software (please provide the following information):**
 - Win7, no antivirus
 - sandboxie plus 0.8.7
 - this problem exists since the versions of Invincea

**Additional context**
If the program is started directly from explorer, the linger processes will be killed as expected.

**Comment by isaak654** [comment]
1) Could you share a download link to this Bing IME?
2) Could you reproduce the same issue by opening Chrome and its secondary telemetry process named _software_reporter_tool.exe_ ?

**Comment by mercury233** [comment]
It is produced by microsoft but it had been stopped support. You can get it from archive.org
http://web.archive.org/web/20160403071144/http://download.get.live.cn/components/pinyin/BingPinyinSetup_1.6.98.04.exe

I'll try other software later.

**Comment by mercury233** [comment]
SESecurityCenter.exe of [sogou browser](https://ie.sogou.com/) has the same effect, and it will be kept sometimes even when sogou browser is launched from explorer.

**Comment by mercury233** [comment]
![GIF 2021-7-13 23-41-27](https://user-images.githubusercontent.com/13391795/125482688-af04b5c5-e019-4e34-8e89-1b2fac469d3f.gif)

Even SandboxieBITS.exe can have this problem...

**Comment by DavidXanatos** [comment]
that sounds fixable will take a look on it soon

**Comment by DavidXanatos** [comment]
I can't reproduce this, the bing thing does not seam to start on my win 10 vm and the  sogou browser dows nto open sesecuritycenter.exe or do i need to click on somethign for it to open?

**Comment by isaak654** [comment]
The lingering issue occurs if you install Bing IME, set it as default on Win7 and run a program exclusively from the Sandboxie's start menu.

According to my tests, it looks like Bing IME (only when it's set as default IME in the system outside of sandbox) is automatically preloaded from Sandboxie when you run the Sbie start menu, even before selecting any program of your choice like notepad.

**Comment by DavidXanatos** [comment]
I can't reproduce this but after browsing through teh lingerer code i have an idea what may be the issue, you see, evertyhign started before PRCSS is excempted from being considdered a lingering process
And it seams that this bight be whats happening here.
So as a workaround we wil have a new ini setting Linger LingerLeniency=n that disabled this behavioure.
